api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29208
- CI - OK
cas de test détecté: 
cas visible -> si authentification avec utilisateur fraud
cas invisible -> si authentification avec utilisateur non fraud
- La couleur est elle celle demandé?
=> (PC-29208)[BO] feat: Pro Support - status pro account suspended

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29187
=> PC-29187 - Add app sync / increased timeout to 600

pro/src/core/Bookings/types.ts, pro/src/pages/Bookings/adapters/getFilteredBookingsRecapAdapter.ts, pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.tsx, pro/src/screens/IndividualOffer/BookingsSummary/__specs__/BookingsSummary.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29207
=> (PC-29188)[PRO] feat: add number of total bookings to booking summary

api/src/pcapi/scripts/emergency-pod-console/main.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29226
=> (PC-29226)[API] feat: emergency pcapi console pod script

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/OffererBanners.tsx, pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29057
=> (PC-29057)[PRO] refactor: use SWR for homepage offerer

api/src/pcapi/core/external/compliance.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/offers_test.py, api/tests/routes/backoffice/users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28969
=> (PC-28969)[BO] feat: show prices to fraud admin in offer list

pro/src/components/NewNavReview/NewNavReview.tsx, pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.module.scss, pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.tsx, pro/src/components/NewNavReview/NewNavReviewDialog/__specs__/NewNavReviewDialog.spec.tsx, pro/src/components/NewNavReview/NewNavReviewDialog/validationSchema.ts, pro/src/components/NewNavReview/__specs__/NewNavReview.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28495
Ajout de la pop-in pour permettre aux utilisateurs issus de la beta test de donner leur avis sur la nouvelle interface du portail pro. 
_A noter que la partie envoie des données sera faite dans un autre ticket_ 
| Normal | Responsive | 
| ------- | ------------ |
| ![Capture d’écran 2024-04-16 à 14 14 13](https://github.com/pass-culture/pass-culture-main/assets/71768799/e0431ad3-3aa2-4267-8a7a-ad83d84f559a) | ![Capture d’écran 2024-04-16 à 14 14 26](https://github.com/pass-culture/pass-culture-main/assets/71768799/25166702-4aec-43f4-bd61-865e6ae2857b) |
=> (PC-28495)[PRO] feat: add dialog for new nav review

helmfile.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29320
=> PC-29320 - Upgrade chart version (testing/ops) to 0.26.1

pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx
=> (BSR)[PRO] fix: flaky test in offers

pro/src/components/Banner/BannerReimbursementsInfo.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28500
=> (PC-28500)[PRO] fix: add space in reimbursment banner

pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29203
=> (PC-29203)[PRO] fix: gtl_id not showing in summary

api/.env.development, api/.env.integration, api/.env.production, api/.env.staging, api/.env.testing, api/src/pcapi/connectors/virustotal.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/__init__.py, api/src/pcapi/routes/backoffice/redirect.py, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/home/redirect.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/settings.py, api/tests/connectors/virustotal_test.py, api/tests/connectors/virustotal_test_data.py, api/tests/core/history/test_api.py, api/tests/core/offerers/test_api.py, api/tests/routes/backoffice/redirect_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28745
Les trois messages possibles si la redirection ne se fait pas automatiquement :
=> (PC-28745)[API] feat: Safe redirect in the backoffice using VirusTotal

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29220
CAS POSITIF
CAS NEGATIF 
- CI - ROUGE MAIS LES TEST FAIL DANS MASTER AUSSI 
- faute d'orthographe -
cas de test détecté: 
cas positif -> si deposit et expiration date sup a maintenant
cas négatif -> si pas de deposit ou expiration date inf maintenant
- nombre de commit ->OK 
- mettre le ticket en code-review -> 
=> (PC-29220)[BO] feat: individual bookings show deposit state

pro/src/pages/Home/__specs__/Homepage.spec.tsx
=> (BSR)[PRO] fix: flaky test

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/backoffice/venues/forms.py, api/src/pcapi/static/backoffice/js/addons/pc-postal-address-autocomplete.js, api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29332
=> (PC-29332)[BO] fix: Fix address autocomplete

pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/AdageOfferInstitutionPanel.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29342
Lorsqu'on réserve une offre réservable on veut que le numéro dans le header diminue de 1
=> (PC-29342)[PRO] fix: dynamic number in header for my institution

api/src/pcapi/core/mails/transactional/pro/invoice_available_to_pro.py, api/tests/core/mails/transactional/pro/invoice_available_to_pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29328
=> (PC-29328)[API] fix: send mails to bank accounts in batch timespan

api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28969
=> (PC-28969)[BO] fix: show empty price when no stock on offer

pro/src/components/IndividualOfferForm/ExternalLink/ExternalLink.tsx, pro/src/components/IndividualOfferForm/ExternalLink/validationSchema.ts, pro/src/components/IndividualOfferForm/UsefulInformations/validationSchema.ts, pro/src/core/shared/constants.ts, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/validationSchema.ts, pro/src/pages/VenueEdition/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29111
il reste encore un champ qui peut être soumis à cette erreur, 
mais on ne peut pas utiliser la validation de yup
=> (PC-29111)[PRO] fix: too much recursion in url validation

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/OfferListSwitch.ts, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28872
Ajout d'un log pour le changement du mode de vue.
=> (PC-28872)[EAC] feat: logs: track offer list switch

pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.admin.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/OffererStats/__specs__/OffererStats.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx, pro/src/pages/Offers/__specs__/Offers.admin.spec.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/__specs__/Reimbursements.spec.tsx, pro/src/pages/VenueCreation/Accessibility/Accessibility.tsx, pro/src/pages/VenueCreation/Accessibility/__specs__/Accessibility.spec.tsx, pro/src/pages/VenueCreation/__specs__/VenueCreation.spec.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx, pro/src/pages/VenueSettings/__specs__/VenueSettingsFormScreen.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx, pro/src/screens/OfferType/__specs__/OfferType.spec.tsx, pro/src/screens/OffererStats/__specs__/OffererStatsScreen.spec.tsx, pro/src/utils/individualApiFactories.ts, pro/src/utils/renderWithProviders.tsx, pro/src/utils/storeFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29222
=> (PC-29222)[PRO] feat: Retirer la bannière acceslibre de la création de lieu sous FF

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240419T084536_9660ff700ed1_remove_ff_wip_ff_side_nav.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/backoffice/templates/pro_user/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/routes/backoffice/venues_test.py, pro/src/app/__specs__/AppLayout.spec.tsx, pro/src/components/Footer/__specs__/Footer.spec.tsx, pro/src/components/SignupJourneyFormLayout/SignupJourneyFormLayout.tsx, pro/src/components/SignupJourneyFormLayout/SignupJourneyFormLayoutContent.module.scss, pro/src/hooks/__specs__/useIsNewInterfaceActive.spec.tsx, pro/src/hooks/useIsNewInterfaceActive.tsx, pro/src/pages/CsvTable/CsvTable.tsx, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx, pro/src/screens/SignupJourneyForm/Validation/Validation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26865
=> (PC-26865)[PRO][BO] chore: Remove `WIP_ENABLE_PRO_SIDE_NAV`

api/src/pcapi/routes/backoffice/venues/forms.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29231
=> (PC-29231)[BO] fix: IntegrityError when clearing address on non-virtual venue without SIRET

pro/src/components/SideNavLinks/SideNavLinks.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29264
- Marge plus grande pour le dernier lien en bas de la barre latérale de navigation.
=> (PC-29264)[PRO] style: More margin for the last link on the lateral pan.

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/forms/string_field.html, api/src/pcapi/routes/backoffice/utils.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29260
decimal 100,25
multi recherche : 
- CI - verte 
- décimal remplacé dans test pour assurer la cohérence du form
IMPOSSIBLE DE TESTER EN PROD VIA L'EXEMPLE ( pas d'accès )
=> (PC-29260)[BO] fix: fix decimal price form in offer and collective offer in BO

api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/templates/venue/get/collective_dms_applications.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28975
=> (PC-28975)[BO] feat: add ds adage applications on venue page

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28319
=> Qds pc 28319 sandbox industrial small addition

pro/src/app/App/hook/__specs__/useLoadFeatureFlags.spec.tsx, pro/src/components/Footer/__specs__/Footer.spec.tsx, pro/src/components/NewNavReview/NewNavReviewDialog/__specs__/NewNavReviewDialog.spec.tsx, pro/src/components/Notification/__specs__/Notification.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.admin.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx, pro/src/pages/Home/ProfileAndSupport/__specs__/ProfileAndSupport.spec.tsx, pro/src/pages/Offers/__specs__/Offers.admin.spec.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx, pro/src/utils/renderWithProviders.tsx
On retire un `any` d'un type un peut structurant
=> (BSR)[PRO] refactor: improve render with providers types

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240416T130925_d1c087ca4219_add_on_delete_cascade_on_offerer_offerer_address.py, api/src/pcapi/alembic/versions/20240416T135342_984376b85d8e_validate_on_delete_cascade_on_offerer_offerer_address.py, api/src/pcapi/core/geography/factories.py, api/src/pcapi/core/geography/models.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_addresses.py, api/tests/routes/pro/get_offerer_addresses_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetOffererAddressResponseModel.ts, pro/src/apiClient/v1/models/GetOffererAddressesResponseModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26154
=> (PC-26154)[API] feat: add get offerer addresses route

api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28492
=> Qds pc 28492 api docs music genres

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28319
=> (PC-28319)[API] fix: fix one permanent venueTypeCode in sandbox industrial

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
This reverts commit cc5f469c2b963e84524a9701b488f78c0c2b16bd.
Ticket Jira : https://passculture.atlassian.net/browse/PC-28319
=> Revert "(PC-28319)[API] fix: fix one permanent venueTypeCode in sandbox industrial

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/pro_users/forms.py, api/src/pcapi/routes/backoffice/templates/pro_user/get.html, api/src/pcapi/routes/external/sendinblue.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/routes/external/sendinblue_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-27835
=> (PC-27835)[BO] feat: toggle marketing email subscription from user details

api/src/pcapi/repository/clean_database.py
Add OffererAddress & Address in tables to clean
=> (BSR)[API] fix: add OffererAddress & Address in tables to clean

api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29322
=> (PC-29322)[PRO] fix: getOffers should not return deleted stocks

api/src/pcapi/core/search/__init__.py
=> (BSR)[API] feat: Use cursor batching for reindexing after last 30 days booking update

pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29304
=> (PC-29304)[PRO] style: Callout de l'offre collective, date et prix

pro/src/app/AppLayout.module.scss, pro/src/app/AppLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29345
Changer la taille du logo dans la barre de navigation en mode mobile
=> (PC-29345)[PRO] fix: change logo size in lateral panel

.github/workflows/dev_on_dispatch_release_deploy.yml
=> (BSR)[api] fix: markdown notification slack on deploy

pro/src/sentry.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29063
=> (PC-29063)[PRO] fix: ignore Norton error

api/src/pcapi/core/educational/factories.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/collective_dms_applications.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28976
=> (PC-28976)[BO] feat: add ds adage applications to offerer page

pro/src/config/swrQueryKeys.ts, pro/src/pages/AdageIframe/app/App.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29055
Utiliser useSwr pour l'appel au budget dans le header adage
=> (PC-29055)[PRO] fix: useswr for budget call to fix sentry error

api/src/pcapi/routes/native/v1/offers.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29090
=> (PC-29090)[API] feat: add route for offers stocks

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28954
J'ai fait le test de mon côté sur un job, ça fonctionne quand le backoffLimit est à 0.
Je fais donc ce fix qui est loin d'être idéal mais qui fonctionnera tant qu'on ne rechange pas le backoffLimit.
Dans tous les cas cette partie sautera lorsqu'on aura fait la migration vers ArgoCD.
=> (PC-28954) ci: fix return code in case of migration failure

.github/workflows/dev_on_dispatch_release_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29477
=> (PC-29477) ci: post success only on workflow success

api/alembic_version_conflict_detection.txt
=> (BSR)[API] fix: Remove new blank line in alembic_version_conflict_detection

.github/workflows/dev_on_workflow_deploy.yml
This reverts commit 7e1a85e0cd0496aaaaa08c8493fc76f16c18b90b.
=> (PC-28945) ci: fix return code in case of migration failure [revert]

pro/src/apiClient/adage/core/request.ts, pro/src/apiClient/v1/core/request.ts, pro/src/apiClient/v2/core/request.ts
Ticket Jira (ou description si BSR) : corrige la CI pour l'erreur lié à yarn `generate:api:client:local`
=> (BSR) fix ci 

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29426
=> (PC-29426)[API] feat: add MeG row to down payment files

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/patch_offerer_address_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/PatchOffererAddressRequest.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26155
=> (PC-26155)[API] feat: Add route to update OffererAddress label

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29467
=> (PC-29467)[API] feat: add allocineId as facet on algolia

api/src/pcapi/core/bookings/repository.py, api/tests/core/bookings/test_repository.py
Les réservations annulées ne sont pas réservées
=> (PC-29502)[API] fix: download validated bookings not cancelled bookings

api/src/pcapi/routes/serialization/offers_serialize.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29494
=> (PC-29494)[API] fix: funk music type is not saved in database

api/src/pcapi/routes/backoffice/offerers/validation_repository.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29463
According to pg_stat_user_tables, index ix_offerer_trgm_unaccent_city was never used.
Actually, a sequential scan was still made on offerers to validate.
Before:
```
EXPLAIN ANALYZE SELECT
offerer.address AS offerer_address, offerer.street AS offerer_street, offerer.id AS offerer_id, offerer."isActive" AS "offerer_isActive", offerer."validationStatus" AS "offerer_validationStatus", offerer."postalCode" AS "offerer_postalCode", offerer.city AS offerer_city, offerer."dateCreated" AS "offerer_dateCreated", offerer.name AS offerer_name, offerer.siren AS offerer_siren, offerer."dateValidated" AS "offerer_dateValidated", offerer."allowedOnAdage" AS "offerer_allowedOnAdage", "user".id AS creator_id, "user".email AS creator_email …
```
=> (PC-29463)[BO] perf: avoid sequential scan on offerer, use existing indexes when listing offerers to validate

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240426T094654_cae1de5d0a6a_drop_ix_user_email_history_olduseremail.py, api/src/pcapi/alembic/versions/20240426T095356_f0ddc19f43e2_drop_ix_user_email_history_newuseremail.py, api/src/pcapi/alembic/versions/20240426T095527_eccba6a07b17_drop_ix_user_email_history_newdomainemail.py, api/src/pcapi/alembic/versions/20240426T100015_43ed9b16fbd7_create_ix_user_email_history_oldemail.py, api/src/pcapi/alembic/versions/20240426T102651_092b7c983605_drop_ix_user_email_history_olddomainemail.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/core/users/email/test_update.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29499
=> (PC-29499)[API] chore: review indexes in user_email_history table 

api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/tests/routes/backoffice/autocomplete_test.py, api/tests/routes/backoffice/collective_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29480
=> (PC-29480)[API] feat: add institution filter on collective bookings page

.github/workflows/dev_on_workflow_deploy.yml
=> (BSR)[API] ci: fix job apply Algolia settings

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240426T115516_46e9f8e3ee4f_drop_ix_user_irisfranceid.py, api/src/pcapi/alembic/versions/20240426T120033_6a223b2b5823_drop_ix_action_history_financeincidentid.py, api/src/pcapi/alembic/versions/20240426T120416_889589793df1_recreate_ix_action_history_financeincidentid.py, api/src/pcapi/alembic/versions/20240426T121133_b2eb82127e19_drop_ix_action_history_bankaccountid.py, api/src/pcapi/alembic/versions/20240426T121424_8b64c0296103_recreate_ix_action_history_bankaccountid.py, api/src/pcapi/alembic/versions/20240426T121940_c33860967b7e_drop_ix_action_history_ruleid.py, api/src/pcapi/alembic/versions/20240426T122034_51e29a607253_recreate_ix_action_history_ruleid.py, api/src/pcapi/alembic/versions/20240426T123217_cf70cfe76aa4_drop_ix_action_history_venueid.py, api/src/pcapi/alembic/versions/20240426T123326_c51c13995e1f_recreate_ix_action_history_venueid.py, api/src/pcapi/core/history/models.py, api/src/pcapi/core/users/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29505
=> (PC-29505)[API] chore: review indexes

pro/src/components/Header/Header.module.scss, pro/src/components/Header/Header.tsx, pro/src/components/SideNavLinks/SideNavLinks.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29374
Ne pas afficher l'icone burger quand le lien vers la home est désactivé et qu'on n'affiche donc pas la barre de navigation. 
BSR : Ajouter les aria-expanded manquants dans la side-nav
=> Pc 29374 dont display burger if home link disable

api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/core/educational/api/playlists.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/routes/adage_iframe/playlist_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29283
Aller chercher des lieux plus loin si la première requête n'a renvoyé que quelques éléments.
=> (PC-29283)[EAC] feat: iframe: playlists: load more items if necessary

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/commands.py
BSR pour corriger une typo, un message d'erreur, et le découpage par batch et [cette erreur sentry](https://sentry.passculture.team/organizations/sentry/issues/1605832/?referrer=slack)
=> (BSR) refactor: acceslibre command

api/src/pcapi/core/permissions/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/conftest.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29401
- CI - verte 
- refresh de la page github -> OK
- contacter Victor pour ajouter a google -> KO
=> (PC-29401)[BO] feat: add user gestionnaire_des_droits with managed_permission

pro/src/components/Callout/AddBankAccountCallout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28987
Ne pas afficher la bannière d'ajout de compte bancaire si un compte bancaire existe déjà avec des demandes de corrections
=> (PC-28987)[PRO] fix: fix addbankaccount callout display condition

pro/src/config/swrQueryKeys.ts, pro/src/pages/AdageIframe/app/App.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/ClassroomPlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/__specs__/ClassroomPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/VenuePlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/__specs__/VenuePlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/OfferInfos.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/__specs__/OffersForMyInstitution.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29242
=> (PC-29242)[PRO] feat: use SWR for some requests on adage

pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27778
Patch disabled primary button colors.
=> (PC-27778)[PRO] fix: patch disabled button colors

api/src/pcapi/core/users/api.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/forms/fields.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/pro_users/forms.py, api/src/pcapi/routes/backoffice/templates/components/forms/date_field.html, api/src/pcapi/utils/date.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/utils/date_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29189
L'objectif est de pouvoir activer ou désactiver la nouvelle navigation PRO pour un utilisateur depuis le Back Office
=> Pc 29189 bo expose eligibility newnavdate

api/src/pcapi/core/users/models.py, api/src/pcapi/routes/serialization/users.py, api/tests/core/users/test_models.py, api/tests/routes/pro/get_user_profile_test.py, api/tests/routes/pro/signin_test.py, pro/src/apiClient/v1/models/SharedCurrentUserResponseModel.ts, pro/src/apiClient/v1/models/SharedLoginUserResponseModel.ts
Ticket Jira : https://passculture.atlassian.net/browse/PC-29366
=> (PC-29366)[API] feat: add hasPartnerPage to user profile

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/offer_metadata.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/favorites.py, api/src/pcapi/routes/native/v1/offers.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28767
=> Pc 28767 return multiple product images

api/src/pcapi/domain/book_types.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29437
=> (PC-29437)[API] fix: typo on romances

api/src/pcapi/algolia_settings_venues.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29408
=> (PC-29408)[API] feat: add Algolia accessibility filters for venues

api/src/pcapi/core/bookings/repository.py, api/tests/core/bookings/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29563
=> (PC-29563)[API] fix: duplicated bookings on offerer with multiple venues

api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/providers/forms.py, api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/components/revenue_details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/offerer/get/stats.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/templates/venue/get/stats.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/finance_test.py, api/tests/routes/backoffice/fraud_test.py, api/tests/routes/backoffice/individual_bookings_test.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/routes/backoffice/venues_test.py
5 commits (à relire séparément) pour des corrections mineures dans le backoffice, pour lesquelles l'écriture de tickets Jira aurait pris plus de temps que la correction.
=> (BSR)[BO] Minor fixes in the backoffice

api/.env.testing, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py, api/src/pcapi/settings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29568
=> (PC-29568)[ADAGE] feat: add institutions for Adage testing purposes

.github/workflows/dev_on_workflow_deploy.yml
=> PC-29434 - Fix for PCAPI secrets outputs

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29315
[x] J'ai lancé avec succès la sandbox en local
Screen de mon retour API en local pour ce lieu:
=> (PC-29315)[API] chore: add a venue with-gmaps like image info to the sandbox

api/src/pcapi/routes/backoffice/templates/bank_account/get.html, api/src/pcapi/routes/backoffice/templates/components/generic_modal.html, api/src/pcapi/routes/backoffice/templates/components/history/comment.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/backoffice/templates/pro_user/comment.html, api/src/pcapi/routes/backoffice/templates/pro_user/get.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29564
=> (PC-29564)[BO] fix: make all modals scrollable

api/src/pcapi/routes/pro/users.py, api/tests/routes/pro/signin_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29403
aucune verification front possible ( le timeout met 3 mois d'après Raphael
- CI - verte 
cas de test lorsqu'un précédent utilisateur connecté est présent et que l'on doit se connecter sur un autre utilisateur.
- refresh de la page github ->  OK
=> (PC-29403)[API] feat: clean the session before login in pro

.github/workflows/dev_on_workflow_deploy.yml
=> (BSR)[API] fix: ci using wrong kubectl cmd

pro/cypress/e2e/adageDiscovery.cy.ts, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/__specs__/ClassroomPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOfferPlaylist/__specs__/NewOfferPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29547
=> (PC-29547)[PRO] feat: Link to adage url of offer with target parent.

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29574
=> (PC-29574)[BO] fix: Woops 'method does not exist' when refreshing page after form validation error

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_build_and_push_docker_images.yml
=> Pc 29434 parallel docker build

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29537
=> (PC-29537)[BO] feat: show bank account name and link in managed venues list

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240426T155648_ba7542f1fa64_add_venue_offerer_address_relation.py, api/src/pcapi/alembic/versions/20240429T124218_fdb469eddd52_add_venue_offerer_address_fk_constraint.py, api/src/pcapi/core/offerers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28649
=> (PC-28649)[API] feat: add offererAddressId to venue

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py, api/src/pcapi/settings.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29568
=> (PC-29568)[ADAGE] fix: remove duplicated institutions from sandbox

pro/src/components/SummaryLayout/SummaryLayout.module.scss, pro/src/components/SummaryLayout/SummarySubSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29573
Ajout des séparateurs entre chaque sous-section
Changer de place le bouton Modifier pour qu'il soit à côté du titre
=> (PC-29573)[PRO] feat: redesign offer recap

api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/utils/crypto.py, api/tests/utils/crypto_test.py, api/tests/validation/routes/users_authentifications_test.py
This reverts commit 5743201820059c306058103139f403919e111658.
=> (PC-29065)[API] feat: Revert commit to include FF

.github/workflows/dev_on_workflow_deploy.yml
=> (BSR)[API] ci: export POD_NAME on fix algolia settings

.github/workflows/dev_on_schedule_prepare_cache_weekly.yml
=> (BSR)[API] ci: fix missing perm prepare cache weekly

pro/src/pages/VenueSettings/VenueProvidersManager/CinemaProviderForm/CinemaProviderForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29613
Le bouton lancer la synchronisation de la page paramètre de l'activité ne déclenche aucune action. 
Cause : Le formulaire est imbriqué dans un autre.
=> (PC-29613)[PRO] fix: change button to submit cinema provider form

pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.module.scss, pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29126
=> (PC-29126)[PRO] style: Ajout ul, li au récap, handicap list

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29607
=> (PC-29607)[API] fix: typo in count venues with accessibility provider

api/src/pcapi/routes/backoffice/templates/bank_account/get.html, api/tests/routes/backoffice/bank_account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29542
- CI - verte 
ajout du status du bank_account dans les test
- auteur du ticket -> OK
- nombre de commit -> OK 
- nom du commit -> OK 
- mettre le ticket en code-review -> OK 
- refresh de la page github -> OK
=> (PC-29542)[BO] feat: add status bank in bank account page

.github/workflows/dev_on_dispatch_release_deploy.yml, .github/workflows/dev_on_push_workflow_main.yml
=> (BSR)[API] ci: fix teleport auth

.github/workflows/dev_on_workflow_tests_api.yml
=> (BSR)[API] ci: more verbose pytest output

pro/src/apiClient/v1/models/SharedCurrentUserResponseModel.ts
Fix api client after https://github.com/pass-culture/pass-culture-main/pull/12169 merge (and the workflow seems to be broken)
=> (BSR)[API] fix: generate api client

api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/utils.py, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29539
=> (PC-29539)[BO] feat: sort bookings by event date (or booking date when not an event)

.github/workflows/dev_on_dispatch_release_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29378
=> (PC-29378)[API] ci: upgrade teleport cli version to v15.2.5

api/src/pcapi/core/fraud/api.py, api/src/pcapi/scripts/beneficiary/import_test_users.py, api/src/pcapi/utils/email.py, api/tests/core/fraud/test_api.py, api/tests/scripts/beneficiary/import_test_users_test.py, api/tests/utils/email_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29555
- CI - verte 
ajout dans un test existant d'une vérification de log montrant l'anonymization des mails.
- auteur du ticket -> OK
- nombre de commit -> OK 
- nom du commit ->OK
- mettre le ticket en code-review -> OK 
- refresh de la page github -> OK
=> (PC-29555)[API] feat: anonymize email when import user in EHP

api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/forms.py, api/src/pcapi/routes/backoffice/home.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/components/forms.html, api/src/pcapi/routes/backoffice/templates/components/forms/field_list_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/form_field.html, api/src/pcapi/routes/backoffice/templates/home/home.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/utils.py, api/src/pcapi/static/backoffice/js/addons/pc-field-list.js, api/src/pcapi/static/backoffice/js/addons/pc-form-field.js, api/src/pcapi/utils/string.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29603
=> (PC-29603)[BO] Improve advanced search and keep only advanced search for offers

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/models/feature.py, api/src/pcapi/utils/crypto.py, api/tests/routes/public/collective/endpoints/get_collective_offers_test.py, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/get_product_test.py, api/tests/utils/crypto_test.py, api/tests/validation/routes/users_authentifications_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29065
=> PC-29065 new hash function on FF 

api/tests/routes/native/v1/offers_test.py
=> (BSR) fix: make test deterministic

pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/DownloadBookingsModal.module.scss, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/DownloadBookingsModal.tsx, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/__specs__/DownloadBookingModal.spec.tsx, pro/src/screens/IndividualOffer/BookingsSummary/__specs__/BookingsSummary.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29210
=> (PC-29210)[API] fix: table header margin

pro/src/pages/LostPassword/LostPassword.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21640
Wording:
=> (PC-21640)[PRO] style: Wording sur bouton, confirmation password

pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/FormDates.tsx, pro/src/ui-kit/form/RadioButton/RadioButton.tsx, pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.module.scss, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.stories.tsx, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.tsx, pro/src/ui-kit/form/shared/BaseRadio/types.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28770
**Objectif**
Re-aligner les styles des composants `BaseRadio` et `BaseCheckbox` pour correspondre à la maquette figma.
En particulier, il ne devrait pas y avoir de variants dans ces composants, mais 1 seule version avec la couleur secondary.
[Le lien de la maquette](https://www.figma.com/file/AEXCkb4KbUyPmB4BRFa88s/PRO---Library?type=design&node-id=7764-101211&mode=design&t=VwALNJ1aMSsYQB0u-4)
**Checkbox**
**Radio**
=> Pc 28770 re align checkbox radio styles

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240514T072411_4c4e5383c6d3_validate_venue_offereraddressid_fk_constraint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28649
=> (PC-28649)[API] chore: Validate venue.offererAddressId FK constraint

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/scripts/acceslibre/match_acceslibre.py, api/src/pcapi/workers/match_acceslibre_job.py, api/tests/routes/backoffice/venues_test.py, api/tests/scripts/acceslibre/match_acceslibre_test.py
Lorsqu'on passe un lieu non permanent en lieu permanent dans le BO, on envoie un job asynchrone qui tente une synchro avec acceslibre
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29282
=> (PC-29282)[BO] feat: sync acceslibre with new permanent venue

api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetCollectiveOfferProviderResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts, pro/src/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx, pro/src/components/CollectiveOfferSummary/__specs__/CollectiveOfferSummary.spec.tsx, pro/src/utils/collectiveApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29600
=> (PC-29600) [PRO] Update front message for collective offer created by API

api/src/pcapi/routes/native/v1/recommendation.py, api/src/pcapi/routes/native/v1/serialization/recommendation.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/recommendation_test.py
Typer la route comme les autres pour mieux aider l'app à générer du code typé de son côté
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29474
=> (PC-29474)[API] feat: return typed responses from recommendation endpoints

.github/actions/render-push-manifests/action.yml, .github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29605
=> PC-29605 - Render manifests to composite actions

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_addresses.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29695
=> (PC-29695)[BO] feat: show offer address

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240515T125314_34a1a2acff4f_add_gcu_compatibility_type_to_product_table.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/models/feature.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/pro/post_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29678
=> Pc 29678 dont apply price limitation rules to ean offers

pro/src/components/OfferAppPreview/OfferAppPreview.tsx, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.module.scss, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27988
=> (PC-27988)[PRO] fix: Offer preview accessibility title

pro/src/components/Header/Header.module.scss, pro/src/components/Header/Header.tsx, pro/src/components/Header/HeaderDropdown/HeaderDropdown.module.scss, pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx, pro/src/components/Header/HeaderHelpDropdown/HeaderHelpDropdown.module.scss, pro/src/components/Header/HeaderHelpDropdown/HeaderHelpDropdown.tsx, pro/src/components/Header/HeaderHelpDropdown/HelpDropdownMenu.tsx, pro/src/pages/Home/Homepage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29350
Menu d'aide dans la nouvelle barre de navigation.
=> (PC-29350)[PRO] feat: Help Header Dropdown.

pro/src/components/NoData/NoData.module.scss, pro/src/components/NoData/NoData.tsx, pro/src/pages/Bookings/ChoosePreFiltersMessage/ChoosePreFiltersMessage.module.scss, pro/src/pages/Bookings/ChoosePreFiltersMessage/ChoosePreFiltersMessage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26717
=> (PC-26717)[PRO] fix: Improve bookings icons

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26319
=> (PC-26319)[API] feat: add filter by offerer address to get pro offers route

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240515T144454_b647a8e48fb5_add_address_department_code.py, api/src/pcapi/alembic/versions/20240515T150310_59c9e4903310_validate_address_department_code_check_constraint.py, api/src/pcapi/alembic/versions/20240515T153656_fbe025155bfa_add_address_timezone_column.py, api/src/pcapi/alembic/versions/20240515T155332_b423e5c9abca_validate_address_timezone_check_constraint.py, api/src/pcapi/core/geography/factories.py, api/src/pcapi/core/geography/models.py, api/tests/core/geography/test_models.py
And suitable index and check length constraint
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29765
=> (PC-29765)[API] feat: Add Address.departmentCode & Address.timezone columns

pro/cypress/e2e/updateVenue.cy.ts, pro/src/app/App/analytics/__specs__/firebase.spec.tsx, pro/src/app/App/analytics/firebase.ts, pro/src/components/Header/HeaderHelpDropdown/HelpDropdownMenu.tsx
La récupération de la remote config firebase rentre en intéraction avec Cypress. Je supprime cette partie vu qu'on ne l'utilise pas et que si on veut un système d'A/B tests réutilisable il faudra de toutes façons un chantier dédié
=> (BSR)[PRO] fix: e2e tests

api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29788
=> (PC-29788)[BO] feat: add more detailed wording to adage info in bo

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240516T083235_048bdcee32e9_create_table_gdpr_data_extract.py, api/src/pcapi/core/users/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29671
Creation de table gdpr_data_extract avec exemple : 
- CI - verte 
- nom du ticket conforme ->OK
- auteur du ticket -> OK
- refresh de la page github ->  OK
=> (PC-29671)[BO] feat: add table gdpr_data_extract

api/src/pcapi/connectors/acceslibre.py, api/tests/connectors/acceslibre/acceslibre_test.py, api/tests/connectors/acceslibre/fixtures.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29790
=> (PC-29790)[BO] fix: fetch correct field to check if id exists

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29832
=> (PC-29832)[API] feat: Create FF WIP_ENABLE_OFFER_MARKDOWN_DESCRIPTION

pro/src/app/AppRouter/ErrorBoundary.tsx, pro/src/app/AppRouter/__specs__/ErrorBoundary.spec.tsx, pro/src/index.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29243
=> (PC-29243)[PRO] fix: Unable to preload CSS for /assets/InfoBox-Dp24M655.css

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240517T153154_5809622e22d6_set_collective_offer_request_datecreated_non_nullable.py, api/src/pcapi/core/educational/models.py, api/tests/routes/pro/get_collective_offer_test.py
Ticket Jira (ou description si BSR) : la colonne est bien remplie
=> (BSR)[API] chore: make never empty column non nullable

pro/src/pages/AdageIframe/app/components/AdageDiscovery/Carousel/Carousel.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/__specs__/ClassroomPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOfferPlaylist/__specs__/NewOfferPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/__specs__/VenuePlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersFavorites/OffersFavorites.tsx, pro/src/pages/AdageIframe/app/components/OffersFavorites/__specs__/OffersFavorites.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx, pro/src/pages/AdageIframe/app/components/Skeleton/AdageSkeleton.module.scss, pro/src/pages/AdageIframe/app/components/Skeleton/AdageSkeleton.tsx, pro/src/styles/variables/_themes.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29364
Ajotu des skeletons pour les offres de la page recherche / découverte / pour mon établissement / mes favoris
=> (PC-29364)[PRO] feat: add adage skeleton

pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/VenuePlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/__specs__/VenuePlaylist.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29614
=> (PC-29614)[PRO] feat: display venue playlist title based on maximum venue distance

pro/.eslintrc.cjs, pro/src/app/__specs__/App.spec.tsx, pro/src/components/SkipLinks/SkipLinks.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Carousel/Carousel.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Carousel/__specs__/Carousel.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOfferPlaylist/NewOfferPlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOffererPlaylist/NewOffererPlaylist.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOffererPlaylist/NewOffererPlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/VenuePlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/__specs__/AdageDiscovery.spec.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx, pro/src/pages/AdageIframe/app/components/DiffuseHelp/DiffuseHelp.tsx, pro/src/pages/AdageIframe/app/components/OffersFavorites/__specs__/OffersFavorites.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/ModalFilterLayout/ModalFilterLayout.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/Skeleton/AdageSkeleton.tsx, pro/src/pages/AdageIframe/app/components/SurveySatisfaction/SurveySatisfaction.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/Offers/Offers/OffersTableHead/StatusFiltersButton.tsx, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/IndividualBookingsTable.tsx, pro/src/screens/Bookings/BookingsRecapTable/Filters/FilterByBookingStatus.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx, pro/src/ui-kit/Button/Button.tsx, pro/src/ui-kit/SvgIcon/SvgIcon.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29414
Supprimer le bloc qui permettait de remplir un formulaire en bas de la page découverte
Ajout de deux nouvelles playlist
=> (PC-29414)[PRO] refactor: delete discovery playlist suggestion form

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240517T130323_cef3565151cc_create_table_offerer_confidence_rule.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offers/api.py, api/tests/core/offerers/test_api.py, api/tests/core/offerers/test_models.py, api/tests/core/offers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29757
=> (PC-29757)[API] feat: Create model for fraud whitelist or full manual review on offerer or venue

pro/cypress/e2e/updateVenue.cy.ts, pro/src/app/__specs__/AppLayout.spec.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/utils.ts, pro/src/components/SideNavLinks/SideNavLinks.tsx, pro/src/components/SideNavLinks/__specs__/SideNavLinks.spec.tsx, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx, pro/src/pages/Home/Offerers/PartnerPageIndividualSection.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPageCollectiveSection.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPageIndividualSection.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataEdition.tsx, pro/src/pages/VenueEdition/VenueEdition.module.scss, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/VenueEditionHeader.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionHeader.spec.tsx, pro/src/ui-kit/Tag/Tag.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29367
- petits ajustement de la patenr page avec la nouvelle navigation
=> (PC-29367)[PRO] feat: new access to partner page

pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/DownloadBookingsModal.tsx, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/__specs__/DownloadBookingModal.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29835
=> (PC-29835)[PRO] fix: Download bookings day issue

pro/src/components/SideNavLinks/SideNavLinks.tsx, pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29367
=> (PC-29367)[PRO] fix: navigation to adage page

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29872
=> (PC-29872)[API] feat: update mail sent to pro when rejecting bookings

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240521T094246_fbb9ccd03884_delete_acces_libre_ff.py, api/src/pcapi/models/feature.py, pro/src/pages/VenueCreation/Accessibility/Accessibility.tsx, pro/src/pages/VenueCreation/Accessibility/__specs__/Accessibility.spec.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28863
=> (PC-28863)[PRO] feat: Remove acces libre ff

api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_individual_offerers.py, api/src/pcapi/static/backoffice/scss/pc/_base.scss
Ticket Jira (suite à une conversation Slack) : https://passculture.atlassian.net/browse/PC-29887
=> (PC-29887)[BO] feat: show full web presence URL in a tooltip when truncated

api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29580
=> (PC-29580)[PRO] fix: add venue image to collective offers for preview

pro/src/apiClient/adage/services/DefaultService.ts, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/ListOffersQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/core/Offers/constants.ts, pro/src/core/Offers/types.ts
BSR : update TS to be on par with the API
=> (BSR)[API] chore: update TS to be on par with the API

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240523T073045_73792a10a8f6_add_collective_stock_start_end_datetime.py, api/src/pcapi/core/educational/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29924
=> (PC-29924)[PRO] feat: add collective stock start/end dates

api/src/pcapi/core/finance/repository.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/pro/reimbursements.py, api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/tests/core/offerers/test_repository.py, api/tests/routes/pro/get_reimbursements_csv_by_invoices_test.py, api/tests/routes/pro/get_reimbursements_csv_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/ReimbursementCsvByInvoicesModel.ts, pro/src/apiClient/v1/models/ReimbursementCsvQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementDetails.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29399
=> PC-29399 download reimbursemnts by bank account

pro/README.md, pro/cypress/e2e/features/adage.feature, pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx, pro/src/components/OfferEducationalActions/__specs__/OfferEducationalActions.spec.tsx, pro/src/components/SideNavLinks/SideNavLinks.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/AdagePreviewLayout.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferShareLink/OfferShareLink.tsx, pro/src/pages/CollectiveOfferFromRequest/CollectiveOfferFromRequest.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPageCollectiveSection.spec.tsx, pro/src/pages/VenueCreation/VenueCreationForm.tsx, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx, pro/src/pages/VenueEdition/subroutesVenueEdition.tsx, pro/src/pages/VenueSettings/VenueSettingsScreen.tsx, pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29367
- changer un lien
- changer un titre 
- enlever le selecteur de page partenaire sur page adage
- renommer Adage en ADAGE
=> (PC-29367)[PRO] patrner page x new nav

api/src/pcapi/routes/pro/finance.py, api/tests/routes/pro/get_combined_invoices_pdf_test.py
Vérifier que le user a le droit de télécharger les justificatifs de la structure
=> (BSR)[API] fix: verify user can access invoices

api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/src/pcapi/routes/backoffice/templates/admin/users_generator.html, api/src/pcapi/routes/backoffice/templates/bank_account/get.html, api/src/pcapi/routes/backoffice/templates/components/generic_modal.html, api/src/pcapi/routes/backoffice/templates/components/public_accounts/registration_steps.html, api/src/pcapi/routes/backoffice/templates/multiple_offers/search_result.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/backoffice/templates/offerer/offerer_tag.html, api/src/pcapi/routes/backoffice/templates/pro_user/get.html, api/src/pcapi/routes/backoffice/templates/tags/list_tags.html, api/src/pcapi/routes/backoffice/templates/venue/get.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29891
=> (PC-29891)[BO] feat: use build_modal_form more often in BO

api/.env.development, api/.env.integration, api/.env.staging, api/.env.testing, api/src/pcapi/connectors/serialization/titelive_serializers.py, api/src/pcapi/core/providers/titelive_api.py, api/src/pcapi/core/providers/titelive_book_search.py, api/tests/connectors/titelive/fixtures.py, api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29956
=> PC-29956 reinforce titelive sync robustness

helmfile.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29917
=> (PC-29917)[API] chore: bump chart version

pro/src/pages/VenueEdition/VenueEdition.module.scss, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29367
=> (PC-29367)[PRO] fix: partner selector should only be in partner page

pro/src/components/IndividualOfferForm/Categories/Categories.tsx, pro/src/components/IndividualOfferForm/Categories/MusicTypes/MusicTypes.tsx, pro/src/components/IndividualOfferForm/Categories/__specs__/Categories.spec.tsx, pro/src/components/IndividualOfferForm/ImageUploaderOffer/__specs__/ImageUploaderOffer.tracker.spec.tsx, pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.tsx, pro/src/context/IndividualOfferContext/IndividualOfferContext.tsx, pro/src/pages/IndividualOfferWizard/Stocks/__specs__/Stocks.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.edition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/serializer.ts, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx, pro/src/screens/IndividualOffer/hooks/useIndividualOfferImageUpload.ts, pro/src/utils/individualApiFactories.ts
But final => supprimer le IndividualOfferContext
=> (BSR)[PRO] refactor: remove data from the indiv context

pro/src/pages/AdageIframe/app/components/OffersFavorites/__specs__/OffersFavorites.spec.tsx
=> (BSR)[PRO] fix: test unit fix skeleton

api/src/pcapi/core/mails/backends/sendinblue.py, api/src/pcapi/notifications/sms/backends/sendinblue.py, api/src/pcapi/utils/email.py, api/tests/core/mails/tests.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29776, créé à partir du ticket https://passculture.atlassian.net/browse/PC-26116
=> (PC-29776)[API] refactor: add WHITELISTED_EMAIL_RECIPIENTS_ENABLED

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/exceptions.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29045
=> (PC-29045)[API] feat: block venue deletion with bank account

pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28462
=> (PC-28462)[PRO] fix: link to adage page

pro/cypress/e2e/features/venue.feature, pro/cypress/e2e/step-definitions/venue.cy.ts, pro/src/app/AppRouter/routesMap.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/VenueEditionHeader.tsx, pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29889
=> (PC-29889)[PRO] feat: Change name general settings

.github/workflows/dev_on_push_workflow_main.yml
2 commits à relire séparément.
=> (BSR)[API] ci: Fix detection of database schema changes

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/collective_bookings.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general_commercial_gesture.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general_overpayment.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get_commercial_gesture.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get_overpayment.html, api/tests/core/finance/test_api.py, api/tests/routes/backoffice/finance_test.py, api/tests/routes/backoffice/helpers/html_parser.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29303
=> (PC-29303)[BO] feat: improve display of finance incidents page

api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/utils.py, api/src/pcapi/routes/adage_iframe/security.py, api/src/pcapi/settings.py, api/tests/core/token/test_token.py, api/tests/core/users/test_utils.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29753
=> (PC-29753)[API] feat: add asymetric token

api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/offers.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29669
=> PC-29669 change /offers/stocks route response to include more details and match get_offer model

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
This allows ADAGE to work/validate against our data
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30062
=> (PC-30062)[ADAGE] feat: add more offers to sandbox institutions

api/src/pcapi/core/history/models.py, api/src/pcapi/core/history/repository.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/forms/fields.py, api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html, api/src/pcapi/routes/backoffice/templates/components/forms/select_field.html, api/src/pcapi/routes/backoffice/templates/components/generic_modal.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/backoffice/venues/forms.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29759
=> (PC-29759)[BO] feat: fraud team can whitelist offerer or venue or force offers under review

api/src/pcapi/core/offerers/factories.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_individual_offerers.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30086
=> (PC-30086)[BO] feat: show whether AE documents have been received in offerers to validate

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29929 
Tentative de fix de l'erreur sentry suivante : https://sentry.passculture.team/organizations/sentry/issues/1589034/?project=2&referrer=jira_integration
L'erreur semble dire qu'on n'arrive pas à destructurer le useOutletContext dans certains cas. Pour palier à ce problème on rajoute des valeurs par défaut dans ces cas.
=> (PC-29929)[PRO] fix: add default values for rimbursmentcontext props

api/README.md
BSR parce que la grammaire c'est important
=> (BSR) refactor: correct grammar

pro/src/pages/Home/Homepage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29677
Fix l'effet de clignotement de la bannière "en cours de validation" (et autres bannière liés à la structure) à la connexion et au changement de structures sur la home
=> (PC-29677)[PRO] fix: fix offerer banner flashing effect on homepage

pro/src/pages/Offers/Offers/OffersStatusFiltersModal/OffersStatusFiltersModal.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30080
Avant
Après
=> (PC-30080)[PRO] fix: options wrapping in dropdown

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/commands.py, api/tests/core/offerers/test_api.py
Ajouter un nombre de jours sur lequel vérifier les nouvelles entrées acceslibre (au cas où le script à échoué )
=> (BSR) feat: add number of days to fetch to acceslibre new entries

pro/src/pages/VenueEdition/VenueEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29939
=> (PC-29939)[PRO] fix: use physical venues instead of permanent venues for ADAGE

api/src/pcapi/core/offers/api.py, api/src/pcapi/utils/cinema_providers.py, api/tests/routes/native/v1/offers_test.py
Quand on appelle EMS (ou un autre provider), on risque un retour non OK
Dans ce cas, on préfère ne pas jeter d'exception pour ne pas retourner de 500 au front (par exemple sur la page /offer)
Fixes Sentry issue: https://sentry.passculture.team/organizations/sentry/issues/917599/?environment=production&project=5&query=&statsPeriod=14d&stream_index=1
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29712
=> PC-29712 avoid EMS KOs on get offer

api/src/pcapi/core/external/batch.py, api/tests/routes/native/v1/favorites_test.py
Batch rejects payload with None as a value
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27583
=> (PC-27583)[API] fix: do not send None to Batch

api/src/pcapi/routes/pro/venue_providers.py, api/src/pcapi/routes/serialization/venue_provider_serialize.py
Altering a database model during serialization to use Pydantic from_orm is dangerous because the alterations can be persisted in database during a autoflush or autocommit.
Those alterations can break database constraints or corrupt further attempts to serialize the model using from_orm.
As for the price, we must keep reading it from the price rule. Replacing it by the provider price must be done in a future deployment(#12359).
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30109
L'accès à la page paramètre est OK :
=> (PC-30109)[API] fix: do not alter venue provider during serialization

pro/src/components/SideNavLinks/SideNavLinks.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29816
Fix la condition d'affichage de bouton "Créer une offre" dans la side nav. En effet suite au changement pour ne pas afficher ce bouton pour un acteur en cours de rattachement, un side effect entrainait la disparition de ce bouton sur certaines pages
=> (PC-29816)[PRO] fix: fix condition to display create offer button

pro/cypress/e2e/step-definitions/createAccount.cy.ts, pro/cypress/e2e/step-definitions/venue.cy.ts
Quelques petites améliorations, todo marqués dans le code:
- vérification du message de compte en cours de création + que l'API renvoie bien un code 200
- vérification qu'il n'y a pas de message rouge de sous-label de siret en erreur (mais le retour est forcé avec l'intercept)
=> (BSR)[PRO] E2E: A few improvements for todos 

api/src/pcapi/core/educational/models.py, pro/src/apiClient/adage/AppClientAdage.ts, pro/src/apiClient/adage/core/OpenAPI.ts, pro/src/apiClient/v1/AppClient.ts, pro/src/apiClient/v1/core/OpenAPI.ts, pro/src/apiClient/v1/models/CollectiveOfferDisplayedStatus.ts, pro/src/apiClient/v1/models/GetCollectiveOfferVenueResponseModel.ts, pro/src/apiClient/v1/models/OffererAddressResponseModel.ts, pro/src/apiClient/v2/AppClientV2.ts, pro/src/apiClient/v2/core/OpenAPI.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29748
=> (PC-29748)[PRO] feat: add new API status to collective offers

api/src/pcapi/core/offerers/api.py, api/tests/routes/pro/test_offerers_addresses.py
=> (PC-30131)[API] fix: Logging false positive addresses inconsistencies

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/scripts/booking/handle_expired_bookings.py, api/src/pcapi/scripts/booking/notify_soon_to_be_expired_bookings.py, api/tests/scripts/booking/notify_soon_to_be_expired_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29782
=> PC-29782 No expired bookings emails in ehp

pro/src/config/swrQueryKeys.ts, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesNoResult.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29795
=> (PC-29795)[PRO] reafactor: use swr for invoices

pro/src/app/App/analytics/sentry.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29898
=> (PC-29989)[PRO] fix: ignore network errors in Sentry

.github/workflows/dev_on_push_workflow_main.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30125
=> (PC-30125)[API] feat: add ops deployment on master

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_deploy.yml
=> (BSR)[API] ci: ops deployment without pro and image-resizing

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240603T124838_1161bdcd0100_remove_ff_wip_opening_hours.py, api/src/pcapi/models/feature.py, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx, pro/src/pages/VenueEdition/serializers.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28268
=> (PC-28268)[PRO] style: Suppression feasure WIP_OPENING_HOURS

pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30106
=> (PC-30106)[PRO] fix: reload offer after stock thing creation

.github/workflows/dev_on_workflow_deploy.yml
=> Fix nothing to commit error in update image tag while retrying job

api/src/pcapi/routes/native/v1/account.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30161
=> (PC-30161)[API] feat: check password strength on young account creation

pro/src/core/FirebaseEvents/constants.ts, pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx, pro/src/pages/Home/Offerers/PartnerPageIndividualSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29948
=> (PC-29948)[PRO] feat: Add two trackers for indiv and collective

api/src/pcapi/settings.py
=> (BSR)[API] feat: add IS_OPS settings

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240530T150820_7757198dbb83_add_offerer_address_id_column_on_collective_offer_table.py, api/src/pcapi/alembic/versions/20240531T114121_4b284e08940e_add_fk_contraint_on_collective_offer_offerer_addess_id.py, api/src/pcapi/core/educational/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30016
=> (PC-30016)[API] feat: Ajout de CollectiveOffer.offererAddressId

pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30106
=> (PC-30106)[PRO] fix: missing mutate in stock events

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/routes/public/individual_offers/v1/events.py
Description : Minor refactor and PEP8
=> Qds pep8 and misc

api/src/pcapi/core/offerers/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30170
=> (PC-30170)[API] fix: add batch_size to acceslibre_matching command

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR)[API] feat: add toggle to temporary disable pcapi-ops deploy

api/src/pcapi/core/bookings/repository.py, api/src/pcapi/routes/pro/bookings.py, api/src/pcapi/routes/pro/collective_bookings.py
Description : 4 commits issus d'une grande PR sur l'export des réservations ( https://github.com/pass-culture/pass-culture-main/pull/12394 ), pour la dépiler petit à petit.
=> Qds bsr bookings refactor

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240604T144721_869f869ef1bc_delete_download_bookings_ff.py, api/src/pcapi/models/feature.py, pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.tsx, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/__specs__/DownloadBookingModal.spec.tsx, pro/src/screens/IndividualOffer/BookingsSummary/__specs__/BookingsSummary.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29214
=> (PC-29214)[PRO] refactor: remove WIP_ENABLE_DOWNLOAD_BOOKINGS FF

pro/src/pages/VenueEdition/VenueEdition.tsx
This reverts commit 958245f87991887fe1badb851ac781ee5c7d7a51.
=> (PC-29939)[PRO] revert: use physical venues instead of permanent venues for ADAGE

.github/workflows/dev_on_workflow_deploy.yml
=> Fix IMAGE name not retrieved on first environment deploy

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/models/pc_object.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_app_users.py, api/src/pcapi/scripts/batch_update_offer_withdrawal_details_for_offerer.py, api/tests/routes/native/v1/offers_test.py, api/tests/scripts/rebuild_staging/test_anonymize.py
=> (PC-30165)[API] chore: Reduce SQLAlchemy warnings

api/README.md
=> (BSR)[API] docs: fix typo readme

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240531T073532_2e66d0e6d190_add_offerAddress_link_to_collective_offer_template.py, api/src/pcapi/core/educational/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30017
=> (PC-30017)[API] feat: adding offerAddress link to CollectiveOfferTemplate

api/README.md
=> (BSR)[API] docs: fix typo

api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_addresses_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30194
=> (PC-30194)[API] fix: make street optional in GetOffererAddressResponseModel serializer

api/src/pcapi/routes/backoffice/templates/offer/details.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30166
3 petites améliorations pour le support pro = 3 commits
=> (PC-30166)[BO] 3 améliorations dans la page d'une offre individuelle

api/src/pcapi/core/offers/api.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30169
=> (PC-30169)[BO] fix: soft deleted stocks should not prevent from moving event offer

api/README.md
=> (BSR)[API] docs: update typo in readme

api/src/pcapi/settings.py, api/src/pcapi/utils/db.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30164
PR liée : https://github.com/pass-culture/pass-culture-deployment/pull/368
=> (PC-30164)[API] feat: export pg stat data as CSV to Google Drive

api/src/pcapi/routes/backoffice/templates/pro_user/get.html, api/tests/routes/backoffice/pro_users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30195
Erreur Sentry : https://sentry.passculture.team/organizations/sentry/issues/1612323/?project=5
=> (PC-30195)[BO] fix: exception when opening pro user details with null names

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/repository/__init__.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/admin/blueprint.py, api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py, api/src/pcapi/routes/backoffice/auth.py, api/src/pcapi/routes/backoffice/autocomplete.py, api/tests/repository/test_on_commit.py, api/tests/routes/backoffice/admin_test.py
Application du @atomic sur un premier sous ensemble du BO et ajout des helpers necessaires pour la suite.
cette branche est lié au ticket https://passculture.atlassian.net/browse/PC-29668
Le nom de la branche reste inchangé pour garder l'historique de la PR mais les commit ont étés renomés en conséquence
=> Bsr rpa bo atomic part1

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30168
=> (PC-30168)[PRO] feat: do not disabled Invoices filters when no result

.github/workflows/templates/post-upgrade-job.yaml, .github/workflows/templates/pre-upgrade-job.yaml
=> (BSR)[API] ci: set request/limit cpu/ram on pre/post ugprade jobs

pro/scripts/customRequest.ts, pro/src/apiClient/adage/core/request.ts, pro/src/apiClient/v1/core/request.ts, pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts, pro/src/apiClient/v1/models/PatchCollectiveOfferBodyModel.ts, pro/src/apiClient/v1/models/PatchCollectiveOfferTemplateBodyModel.ts, pro/src/apiClient/v2/core/request.ts, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29796
=> (PC-29796)[PRO] feat: download several document in InvoicesTable 

pro/cypress/e2e/features/financialManagement.feature, pro/cypress/e2e/step-definitions/commonSteps.cy.ts, pro/cypress/e2e/step-definitions/financialManagement.cy.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29793
=> (PC-29793)[PRO] test: add e2e for invoices

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/core/users/repository.py, api/src/pcapi/routes/pro/bookings.py, api/src/pcapi/routes/pro/reimbursements.py, api/src/pcapi/utils/rest.py, api/src/pcapi/validation/routes/users_authorizations.py, api/tests/core/users/test_models.py
=> (BSR)[API] refactor: Move `User.has_access()` to a function

pro/src/core/FirebaseEvents/constants.ts, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceActions.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29794
=> (PC-29794)[PRO] feat: add logs to invoices table

api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/get_products_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30214
=> (PC-30214)[API] Correction du bug API dû à des noms d'offres trop grands

api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html, api/src/pcapi/routes/backoffice/templates/components/search/result.html, api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/list.html, api/src/pcapi/routes/backoffice/templates/home/home.html, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/src/pcapi/routes/backoffice/templates/multiple_offers/search_result.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/src/pcapi/routes/backoffice/templates/tags/list_tags.html, api/src/pcapi/routes/backoffice/templates/venue/list.html
Ticket Jira (ou description si BSR) : Utiliser pluralize dans un peu plus d'endroits
=> (BSR)[BO] refactor: use pluralize filters in bo templates

api/src/pcapi/core/mails/transactional/bookings/new_booking_to_pro.py, api/src/pcapi/core/mails/transactional/pro/first_venue_approved_offer_to_pro.py, api/src/pcapi/core/offerers/models.py, api/tests/core/mails/transactional/bookings/new_booking_to_pro_test.py, api/tests/core/mails/transactional/pro/first_venue_approved_offer_to_pro_test.py, api/tests/core/offerers/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29046
=> (PC-29046)[API] feat: Use suitable BankAccount data when sending transactionals mails

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/models.py, api/tests/core/finance/test_api.py
=> (PC-14903)[API] Ajout de PricingLog et CashflowLog lors de la génération des flux monétaires et des justificatifs de remboursement

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.module.scss, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30249
=> (PC-30249)[PRO] fix: Fix a11y focus styles of ADAGE menu links.

.github/workflows/dev_on_workflow_deploy.yml
Use render-push-manifests@render-push-manifests/v2.0.0 to push rendered manifests to target branch pcapi/$ENV
=> Deployment use render-push-manifests@render-push-manifests/v2.0.0

pro/src/pages/Reimbursements/BankInformations/BankInformations.module.scss, pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/BankInformations/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.module.scss, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30241
=> (PC-30241)[PRO] fix: a11y remove useless header

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30247
=> (PC-30247)[PRO] fix: add missing label for checkboxes in InvoicesTable

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/exceptions.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30239
=> (PC-30239)[BO] fix: delete VenueBankAccountLink at venue deletion

pro/src/pages/AdageIframe/app/components/AdageDiscovery/VenueCard/VenueCard.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30258
=> (PC-30258)[PRO] fix: Make ADAGE venue card names break when too long.

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29983
=> (PC-29983)[API] feat: delete offer reports when deleting their venue

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240530T085853_6733d62e9059_add_offerer_address_unique_index_with_nulls_values_not_distinct.py, api/src/pcapi/alembic/versions/20240530T093918_c551c042d2e6_remove_useless_index_on_offerer_address_table.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/test_offerers_addresses.py
=> (BSR)[API] feat: Fix failing unique constaint

pro/src/components/Header/HeaderHelpDropdown/HelpDropdownMenu.tsx, pro/src/core/FirebaseEvents/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30014
=> (PC-30014)[PRO] feat: Adds a third link in "Help Center" menu

pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.module.scss, pro/src/pages/AdageIframe/app/components/ToggleButtonGroup/ToggleButtonGroupButton/ToggleButtonGroupButton.tsx, pro/src/pages/AdageIframe/app/components/ToggleButtonGroup/__specs__/ToggleButtonGroupButton.spec.tsx, pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30243
- Zoom du texte à 200%
- Taille par défaut des images dans le HTML
- Focus des checkbox dans modal de filtre, bouton rechercher
- Le picto dans l'input de recherche n'a pas besoin d'être lu par le voiceover
- Label accessible pour élément vue liste/vue grille et lu une seule fois au voiceover
=> (PC-30243)[PRO] fix: accessiblity search page adage

api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30280
=> (PC-30280)[BO] fix: documents received badge condition in offerers to validate

api/src/pcapi/core/external/batch.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/notifications/push/__init__.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27796
=> (PC-27796)[API] feat: add batch event for account recredit

api/src/pcapi/routes/backoffice/titelive/blueprint.py
Correction suite à deux PR mergées en parallèle
=> (PC-20235)[BO] fix: conflict after commit 46034e08

api/src/pcapi/utils/db.py
Il manquait un nom de colonne dans le CSV exporté, ce qui décalait la moitié des titres.
=> (BSR)[API] fix: missing column name in CSV (indexes stats)

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240611T095743_5316ce0cc1dd_drop_wip_enable_boost_two_stages_booking_ff.py, api/src/pcapi/connectors/serialization/boost_serializers.py, api/src/pcapi/core/external_bookings/boost/client.py, api/src/pcapi/models/feature.py, api/tests/core/external_bookings/boost/test_client.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29786
=> (PC-29786)[API] refactor: remove WIP_ENABLE_BOOST_TWO_STAGES_BOOKING FF

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/styles/mixins/_a11y.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss
…Financial" page
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30242
=> (PC-30242)[PRO] feat: (a11y) Enhance table view's responsiveness in "Financial" page

pro/src/pages/IndividualOfferWizard/IndividualOfferWizard.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30162
=> (PC-30162)[PRO] fix: Use the good layout for offer /confirmation

pro/src/pages/Sitemap/Sitemap.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29997
⚠️ Lien manquant: La nouvelle maquette montre un lien « Collaborateurs » pour lequel je n'ai trouvé aucune URL ou correspondance dans l'existant. En attendant, j'ai mis un `<Link to={'#'}>`
=> (PC-29997)[PRO] feat: Reorganize SiteMap

pro/cypress/e2e/features/searchCollectiveOffer.feature, pro/cypress/e2e/step-definitions/searchCollectiveOffer.cy.ts
Scénario pour tester la combinaison de filtres dans la recherche d'offres collectives
=> (BSR)[PRO] test: add search with several filters scenario

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesNoResult.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30197
Ajustements sur le tableau des factures
=> (PC-30197) feat: various little improvements in InvoicesTable

api/src/pcapi/routes/backoffice/auth.py
Ignore les roles si on est dans l'env ops
=> (BSR)[BO] feat: add ops env to ignore roles verification in backoffice

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external/batch.py, api/src/pcapi/notifications/push/__init__.py, api/tests/core/bookings/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27585
=> (PC-27585)[API] feat: add batch event for offer booking

pro/src/components/CancelCollectiveBookingModal/CancelCollectiveBookingModal.module.scss, pro/src/components/CancelCollectiveBookingModal/CancelCollectiveBookingModal.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/Offers/OfferItem/CollectiveOfferItem.tsx, pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss, pro/src/pages/Offers/Offers/OfferItem/OfferItem.tsx, pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx, pro/src/pages/Offers/Offers/Offers.tsx, pro/src/pages/Offers/Offers/OffersTableBody/OffersTableBody.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveActionButtons.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29730
Annuler une réservation depuis la liste des offres
=> (PC-29730)[PRO] feat: cancel booking from list offer

api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30326
=> (PC-30326)[BO] feat: show deposit credited time

api/src/pcapi/core/external/attributes/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30332
=> (PC-30332)[API] fix: fix typo for beamer attributes update

api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_new_caledonia_offerers.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30309
=> (PC-30309)[API] test: add offerers in New Caledonia to sandbox

pro/src/pages/Accessibility/Commitment.tsx, pro/src/pages/Accessibility/Declaration.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30342
=> (PC-30342)[PRO] style: Wording des pages de l'accessibilité

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/commands.py
BSR pour 
- ajouter des messages pour l'execution des commandes acceslibre 
- migrer la commande `synchronize_accessibility_with_acceslibre` dans `offerers/api`
=> (BSR) refactor: add success message on acceslibre commands

pro/src/components/Header/HeaderDropdown/HeaderDropdown.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29676
=> (PC-29676)[PRO] style: Fixed offerer selection height.

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240606T081129_3e52841cdafa_create_discord_user_table.py, api/src/pcapi/alembic/versions/20240613T083156_20579712cf72_.py, api/src/pcapi/app.py, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/auth/discord.py, api/src/pcapi/routes/auth/templates/discord_signin.html, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/routes/auth/discord_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29764
=> Pc 29764 discord auth post route

pro/src/app/App/analytics/sentry.ts
=> (BSR)[PRO] fix: ignore more network errors

pro/src/apiClient/adage/models/NationalProgramModel.ts, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetOffererAddressResponseModel.ts, pro/src/apiClient/v1/models/NationalProgramModel.ts, pro/src/apiClient/v1/models/PatchCollectiveOfferArchiveBodyModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
=> (BSR)[PRO] chore: Generate/udpate front client

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/core/offers/test_api.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/get_event_dates_test.py, api/tests/routes/public/individual_offers/v1/patch_date_test.py, api/tests/routes/public/individual_offers/v1/post_dates_test.py
Ticket Jira  : https://passculture.atlassian.net/browse/PC-30349
=> (PC-30349)[API] feat: add `idAtProvider` in event stocks API endpoints

pro/cypress/README.md, pro/cypress/e2e/features/README.md
J'ai ajouté des guidelines et bonnes pratiques pour Cypress et Cucumber (j'ai mis de côté Testing Library pour l'instant).
Ce sera notre base commune pour la validation de PR.
=> (BSR)[PRO] test: guidelines and best practices for cypress and cucumber

pro/package.json, pro/src/pages/VenueSettings/VenueProvidersManager/DuoCheckbox/DuoCheckbox.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingDetails.module.scss, pro/src/ui-kit/Button/Button.module.scss, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30068
**Objectif**
Bump de stylelint
La règle qui bloque interdit de modifier "border-color" si dans le même style on modifie "border" par la suite.
=> (PC-30068)[PRO] bump: Stylelint 16.3.1 -> 16.6.1.

pro/src/components/CollectiveStatusLabel/CollectiveStatusLabel.module.scss, pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss, pro/src/pages/Offers/Offers/Offers.scss
Ticket Jira : https://passculture.atlassian.net/browse/PC-30298
- Suppression des largeurs de colonnes fixes pour les écrans d'offres collectives et individuelles.
- Amélioration de l'affichage des vues mobiles et tablette (restructuration de la `grid` CSS)
https://github.com/pass-culture/pass-culture-main/assets/171674396/515c3d2d-6ba1-4d54-a5cf-023667851a40
=> (PC-30298)[PRO] feat: Enhance Offers tables display in desktop/mobile

pro/src/pages/VenueEdition/VenueEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30294
=> (PC-30294)[PRO] style: Wording de la page Adage

.github/workflows/dev_on_workflow_tests_pro.yml, pro/.stylelintrc.json
Activation de la règle stylelint pour éviter du style non scopé
=> (BSR)[PRO] chore: enable selector-max-type rule

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29592
=> (PC-29592)[API] feat: remove None fields from offers in Algolia

.github/workflows/dev_on_pull_request_workflow.yml
Cancel running workflow from the same PR when a new one is triggered
=> Cancel running workflow from the same PR when a new one is triggered

api/src/pcapi/routes/native/v1/account.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-20031
=> (PC-20031)[API] feat: Adopt dms application on email change and on sso account creation

pro/src/components/FormLayout/FormLayoutSection.tsx, pro/src/screens/SignupJourneyForm/Activity/ActivityForm.tsx, pro/src/screens/SignupJourneyForm/Authentication/OffererAuthenticationForm.tsx, pro/src/screens/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/OffererForm.tsx, pro/src/screens/SignupJourneyForm/Welcome/Welcome.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29617
=> (PC-29617)[PRO] feat: [A11Y] Parcours d'inscription - titres KO

pro/src/components/StocksEventList/StocksEventList.module.scss, pro/src/components/StocksEventList/StocksEventList.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30107
=> (PC-30107)[PRO] feat: make StockEventList responsive

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240613T114840_d43d711e5f8a_add_date_archived_to_collective_offers.py, api/src/pcapi/alembic/versions/20240618T081524_f830372aa947_add_datearchived_to_collective_offer_template.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/pro/collective_offers.py, api/tests/routes/pro/patch_collective_offers_template_archive_test.py, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30397
=> (PC-30397)[PRO] feat: Add dateArchived to collective_offer_template

api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/scripts/beneficiary/import_test_users_test.py
Create api key for bounty hunters. This key will have right on the venue created for the hunter. 
The key will be `staging_{hunter_username}_{hunter_email}` 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30363
=> (PC-30363)[API] feat: create key for bounty hunters

pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30298
Comme vu en review, des marges de 8px ont été ajoutées sur les cellules pour la vue en Desktop, afin d'homogénéiser le contenu :
=> (PC-30298)[PRO] fix: Adds padding between cells

.github/workflows/dev_on_workflow_deploy_app_engine_image_resizing.yml
=> (BSR) ci: image resizing clean only when needed

api/src/pcapi/connectors/apps_flyer.py, api/src/pcapi/core/subscription/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/workers/apps_flyer_job.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29934
=> (PC-29934)[API] feat: add more apps flyer event for credit grant

pro/cypress/e2e/step-definitions/venue.cy.ts, pro/src/pages/VenueCreation/VenueFormActionBar/VenueFormActionBar.tsx, pro/src/pages/VenueCreation/VenueFormActionBar/__specs__/VenueFormActionBar.spec.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/DayCheckbox.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30625
=> (PC-30265)[PRO] feat: various little improvments on ParnterPage

api/src/pcapi/core/offerers/api.py
Description : Fix unindex_venue_ids in delete_offerer()
=> (BSR)[API] fix: fix unindex_venue_ids in delete_offerer()

api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py, api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py, api/tests/local_providers/cinema_providers/cgr/cgr_stocks_test.py, api/tests/providers/allocine_movie_list_test.py
Description : Ajout de fichiers `__init__.py` + gestion des warnings Pylint suite à l'ajout des `__init__.py`
=> (BSR)[API] chore: add __init__.py files

.gitignore, api/.gitignore
=> (BSR)[API] fix: gitignore all pem files

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/search/result_card.html, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/pro_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30322
=> (PC-30322)[BO] fix: wrong results count when user has several [un]suspend actions in history

api/src/pcapi/core/external/zendesk_sell_backends/zendesk_sell.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30365
Testé en local avec une connexion lecture seule à Zendesk Sell (équivalent à staging)
=> (PC-30365)[API] feat: tune conditions to match an offerer with Zendesk Sell

.github/workflows/dev_on_workflow_tests_api.yml, api/pyproject.toml, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/finance/siret_api.py, api/src/pcapi/core/mails/transactional/bookings/booking_withdrawal_updated.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/pro/stocks.py, api/tests/core/users/test_models.py, infra/pc_scripts/test_backend.sh
=> (BSR)[API] chore: Activate SQLA warnings in tests and local environment

pro/src/components/SideNavLinks/SideNavLinks.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/VenueEdition/VenueEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30395
=> (PC-30395)[PRO] fix: link not showing up as active in nav menu

pro/src/pages/Reimbursements/Reimbursements.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29960
=> (PC-29960)[PRO] feat: load reimbursment data with appLayout

api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/repository.py, api/tests/core/users/test_api.py
Description : Suppression de 5 fonctions inutilisées
* `get_all_collective_offers_by_institutionUAI()`
https://github.com/pass-culture/pass-culture-main/commit/588740211969426db2fd9636dd32547638d851ea
* `_set_offerer_departement_code()`
https://github.com/pass-culture/pass-culture-main/commit/65fd865996a3e93b8ac28fb20cdd2eb0ccbd5c0d
* `get_collective_offer_template_by_ids()`
https://github.com/pass-culture/pass-culture-main/commit/c10fe9aaba81852c32d0d3b627c58de9e95cbcf2
https://github.com/pass-culture/pass-culture-main/commit/c03be08f0d21ee2a6fcf3177accf5772810ebf56
* `offerer_address_exists()`
https://github.com/pass-culture/pass-culture-main/commit/42b635ff37e70f82c1a9a8776cc656eb75f53b78
* `find_pro_user_by_email_query()`
https://github.com/pass-culture/pass-culture-main/commit/b134ee0 …
=> Qds bsr deadcode v1

pro/src/app/App/App.tsx, pro/src/app/AppRouter/routesMap.tsx, pro/src/app/__specs__/App.spec.tsx, pro/src/context/IndividualOfferContext/__specs__/IndividualOfferContext.spec.tsx, pro/src/pages/Errors/NotFound/NotFound.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30180
=> (PC-30180)[PRO] feat: redirect to 404 when api not found

pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30347
- Correction de style dans le nouveau header.
=> (PC-30347)[PRO] style: Fixed buttons styles in the header dropdown.

.github/workflows/dev_on_push_workflow_main.yml
=> (PC-30463) ci: fix cancel-in-progress condition

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/routes/backoffice/bank_account/blueprint.py, api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30427
=> (PC-30427)[BO] feat: migrate back_account and booking to @atomic

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30463
=> (PC-30463) ci: make pcapi deploy only non-concurrent step

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30304
=> PC-30304 Add more cinema data in sandbox

api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/sandbox_industrial.py
=> (BSR)[API] fix: prepare mediations files before creation of offers in sandbox

api/bin/alembic_rebase_migrations.py
Automatically rebase Alembic migrations.
See module docstring for further details.
=> (BSR)[API] feat: Add alembic_rebase_migrations program

api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30391
=> (PC-30391)[BO] feat: filter bookings on deposit expiration

api/src/pcapi/connectors/api_adresse.py, api/tests/connectors/api_adresse/api_adresse_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29961
=> (PC-29961)[API] feat: caching api adresse

pro/src/pages/CollectiveOffers/CollectiveOffers.tsx, pro/src/pages/OffererStats/OffererStats.tsx, pro/src/pages/Offers/OffersRoute.tsx, pro/src/screens/Bookings/Bookings.tsx, pro/src/screens/Bookings/PreFilters/FilterByVenue.tsx, pro/src/screens/OffererStats/OffererStatsScreen.tsx, pro/src/screens/OffererStats/__specs__/OffererStatsScreen.spec.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29797
=> (Pc-29797)[PRO] feat: Offerer selector should change the page filters.

api/src/pcapi/core/geography/models.py, api/src/pcapi/core/offerers/api.py, api/tests/routes/pro/test_offerers_addresses.py
=> (BSR)[API] fix: False positives of log because of rounding

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30487
=> [FIX] make optional doc-api-entrypoint

api/src/pcapi/core/finance/api.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_commercial_gestures.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_incidents.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29681
=> (PC-29681)[BO] feat: sandbox - generate commercial gestures & finance incidents invoices

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240621T130534_a07d08bb52cf_add_future_offer_table.py, api/src/pcapi/alembic/versions/20240621T130747_2144f7e4df3c_add_future_offer_fk_constraint.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/pro/patch_publish_offer_test.py, api/tests/routes/pro/post_offer_test.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/post_event_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29500
=> Qds pc 29500 event offer in the future

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
=> (BSR)[PRO] ci: Move videos even if the tests fail.

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, pro/cypress/e2e/features/searchIndividualOffer.feature
Revert du Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30304
=> BSR fix: revert sandbox breaking change

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30516
=> [FIX] ignore ops environment for api documentation build and deploy

api/documentation/docusaurus.config.ts
Ticket Jira : https://passculture.atlassian.net/browse/PC-30510
=> (PC-30510)[API] feat: Update documentation footer

README.md
Description : Mise à jour de liens et correction d'une typo dans le README
=> (BSR)[API] chore: update README

api/documentation/docs/tutorials/create-an-event-linked-to-an-external-ticketing-systems.md, api/documentation/docs/understanding-our-api/resources/individual-offers.md, api/src/pcapi/routes/public/booking_token/v2/endpoints.py, api/src/pcapi/routes/public/books_stocks/endpoints.py, api/src/pcapi/routes/public/collective/endpoints/bookings.py, api/src/pcapi/routes/public/collective/endpoints/categories.py, api/src/pcapi/routes/public/collective/endpoints/domains.py, api/src/pcapi/routes/public/collective/endpoints/educational_institutions.py, api/src/pcapi/routes/public/collective/endpoints/national_programs.py, api/src/pcapi/routes/public/collective/endpoints/offers.py, api/src/pcapi/routes/public/collective/endpoints/students_levels.py, api/src/pcapi/routes/public/collective/endpoints/venues.py, api/src/pcapi/routes/public/documentation_constants/tags.py, api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/spectree_schemas.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/delete_date_test.py, api/tests/routes/public/individual_offers/v1/patch_date_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30289
=> (PC-30289)[API] Rename event dates event stocks

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Previous version did not handle well a second call to linking a user to an offerer.
Code allows it but fails on DB constraint.
This was because any UserOfferer in new or validated state was recreated which the DB does not allow.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30485
=> (PC-30485)[PRO] fix: avoid duplicated user offerer link.

pro/src/app/App/analytics/sentry.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30033
=> (PC-30033)[PRO] fix: error on Sentry initialization

api/src/pcapi/core/history/api.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30503
=> (PC-30503)[BO] fix: unexpected latitude/longitude modified in venue history

api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/venues/forms.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30479
=> (PC-30479)[BO] fix: exception when venue is edited with invalid latitude or longitude

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240516T150115_8698fb928069_create_offer_gtl_id_substring_index.py, api/src/pcapi/alembic/versions/20240520T084228_49b4f3ce3751_drop_offer_music_subtype_index.py, api/src/pcapi/core/categories/subcategories_v2.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28066
=> Remove music subtype from backoffice and add titelive music types

api/src/pcapi/app.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29752
=> (PC-29752)[API] fix: fix auth discord cannot access css

api/src/pcapi/core/geography/factories.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues_with_timezone.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_new_caledonia_offerers.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/venues_mock.py, api/tests/core/bookings/test_repository.py, api/tests/core/external/external_pro_test.py, api/tests/core/external/venue_automations_test.py, api/tests/core/geography/test_models.py, api/tests/core/mails/transactional/bookings/new_booking_to_pro_test.py, api/tests/core/offerers/test_repository.py, api/tests/local_providers/chunk_manager_test.py, api/tests/routes/adage/v1/get_all_venues_test.py, api/tests/routes/adage/v1/get_venues_from_name_test.py, api/tests/routes/backoffice/venues_test.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/pro/get_stocks_stats_test.py, api/tests/routes/pro/get_stocks_test.py, api/tests/routes/pro/post_offer_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30491
=> (PC-30491)[API] test: Rendre les données cohérentes dans la sandbox pour le chantier OA

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29407
Upgrade de @testing-library/react
=> (PC-29407)[PBSR] upgrade: maj testing library

api/bin/alembic_add_not_null_constraint.py
=> (BSR)[API] Corrections sur `alembic_add_not_null_constraint`

pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30298
- Après peer-review, il a été décidé une uniformisation du style des labels (stocks ou ISBN) sous les titres des offres.
=> (PC-30298)[PRO] fix: Uniformize title-column labels (stocks & isbn) 

api/documentation/docs/understanding-our-api/resources/collective-offers.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30285
Ajout d'une page de documentation de l'API publique concernant les offres collectives.
=> (PC-30285)[API] doc: add collective offers API doc

api/src/pcapi/core/offers/repository.py, api/tests/routes/pro/get_all_collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29904 fix https://passculture.atlassian.net/browse/PC-30524
Bug concernant les filtres réservés :
=> (PC-30524)[PRO] fix filter for status BOOKED/PREBOOKED

api/documentation/docs/tutorials/create-a-collective-offer.md, api/documentation/docs/understanding-our-api/resources/collective-offers.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30451 
Ajout d'un tutoriel pour créer une offre collective.
Ajout de précisions concernant le fonctionnement des offres collectives.
=> PC 30451 api doc collective offers second part

api/documentation/docs/understanding-our-api/resources/collective-offers.md, api/documentation/src/pages/change-logs.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30497
Mise à jour du _changelog_.
=> (PC-30497)[API] feat: public api doc: update changelog

pro/src/screens/OfferEducationalStock/utils/__specs__/getMaxEndDateInSchoolYear.spec.ts, pro/src/screens/OfferEducationalStock/utils/getMaxEndDateInSchoolYear.ts, pro/src/screens/OfferEducationalStock/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30490
=> (PC-30490)[PRO] feat: restrict start and end dates to the school year on collective offer form

api/documentation/docs/tutorials/create-a-book-or-cd-product.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30567
Supprimer une page vide (on va éviter d'ajouter une page en prod avec uniquement `TO DO !` comme contenu).
=> (PC-30567)[API] feat: doc: rm empty page

api/src/pcapi/connectors/boost.py, api/src/pcapi/routes/backoffice/pivots/contexts/boost.py, api/tests/connectors/api_boost_test.py, api/tests/routes/backoffice/pivots_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30200
=> (PC-30200)[API] feat: logout from Boost API before delete pivot

pro/src/screens/IndividualOffer/StocksEventCreation/AddRecurrencesButton.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29166
=> (PC-29166)[PRO] style: Add responsif css for date buttons, offer

pro/src/app/App/App.tsx, pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
=> (BSR)[PRO] fix: Handle offerer reset on login/logout.

api/documentation/docs/tutorials/create-a-collective-offer.md, api/documentation/src/pages/change-logs.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30566
Quelques corrections et reformulations pour la doc de l'api publique.
=> (PC-30566)[API] fix: doc: improve/correct stuff

api/src/pcapi/core/logging.py
These log levels are historical:
- rq: introduced in 7c1d1f241673e, where that change seems unrelated.
- werkzeug: introduced in 7ebef9e21271e to avoid log from Werkzeug for
each request, but it also masks WARNING logs.
I don't see a good reason not to log anything equal or above WARNING
for those two components.
=> (BSR)[API] feat: Lower log level for Werkzeug and RQ

pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts, pro/src/apiClient/v1/models/GetIndividualOfferWithAddressResponseModel.ts, pro/src/apiClient/v1/models/PatchOfferPublishBodyModel.ts
=> (BSR)[API] chore: Update front api client

pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts, pro/src/apiClient/v1/models/GetIndividualOfferWithAddressResponseModel.ts, pro/src/apiClient/v1/models/PatchOfferPublishBodyModel.ts, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.module.scss, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx, pro/src/screens/IndividualOffer/IndivualOfferLayout/__specs__/IndivualOfferLayout.spec.tsx, pro/src/screens/IndividualOffer/Status/Status.tsx, pro/src/screens/IndividualOffer/Status/StatusToggleButton.tsx, pro/src/screens/IndividualOffer/Status/__specs__/StatusToggleButton.spec.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/form/onSubmit.ts, pro/src/screens/IndividualOffer/StocksEventEdition/serializers.ts, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx, pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.tsx, pro/src/utils/date.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30152
=> (PC-30152)[PRO] feat: publication d'offre dans le futur

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_commercial_gestures.py
Arrêter d'essayer de générer un pricing pour les FinanceEvents annulés lors de la génération de gestes commerciaux dans la sandbox.
Fix ce sentry : https://sentry.passculture.team/organizations/sentry/issues/1605910/
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30548
=> (PC-30548)[BO] fix: avoid unintentional pricings deletion in industrial commercial gesture sandbox generator

pro/package.json, pro/src/core/shared/utils/parseAndValidateFrenchPhoneNumber.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30069
=> (PC-30069)[PRO] build: Update deps `libphonenumber-js`

pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30367
https://github.com/pass-culture/pass-culture-main/assets/171674396/656c71d2-5913-4a21-b66a-c8348dda5660
https://github.com/pass-culture/pass-culture-main/assets/171674396/75dad481-7517-446c-83b7-d2466cf9178a
=> (PC-30367)[PRO] feat: Removes structure menu for single-structure users

api/src/pcapi/core/external/zendesk.py, api/tests/routes/external/zendesk_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30549
=> (PC-30549)[API] fix: Zendesk Support note for NON_ATTACHED_PRO user

pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30088
- Supprimer les onglets Détails de l’offre / Date et prix / Etablissement scolaire de la page récapitulatif
- Supprimer le bouton “Modifier l’offre” qui est trop redondant avec le “modifier” qui est placé à côté des titres de sections.
=> (PC-30088)[PRO] feat: clean summary page eac link

api/src/pcapi/core/external/zendesk_sell_backends/zendesk_sell.py, api/tests/core/external/zendesk_sell_test.py
- Do not retrieve a venue contact as the parent offerer
- Do never try to send self id as parent id
- Consider "Typage" as reliable (agreed with DirDev)
Ticket Jira : https://passculture.atlassian.net/browse/PC-30520
Requêtes testées et validées en environnement de développement avec la clé d'API de staging.
=> (PC-30520)[API] fix: offerer/venue matching in Zendesk Sell

pro/src/components/FormLayout/FormLayout.module.scss, pro/src/components/FormLayout/FormLayoutSection.tsx, pro/src/components/FormLayout/__specs__/FormLayoutSection.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/EventPublicationForm/EventPublicationForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30480
=> (PC-30480)[PRO] feat: add new tag to futur offer

pro/src/pages/CollectiveOfferStockCreation/CollectiveOfferStockCreation.tsx, pro/src/screens/OfferEducationalStock/__specs__/OfferEducationalStock.spec.tsx, pro/src/screens/OfferEducationalStock/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29829
on pouvait mettre 0 participant et le stock ne se créait pas mais on passait bien à l'étape suivante donc arrivé à l'aperçu le stock était undefined
pour fix : on remonte le code qui redirige dans le try puis on rajoute une validation au formulaire pour avoir 1 participant minimum
=> (PC-29829)[PRO] fix: sentry error page nb participant

api/src/pcapi/scripts/install.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30583
=> (PC-30583)[API] fix: install offers commands

api/src/pcapi/core/object_storage/__init__.py, api/src/pcapi/core/object_storage/backends/base.py, api/src/pcapi/core/object_storage/backends/gcp.py, api/src/pcapi/core/object_storage/backends/local.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/commands.py, api/tests/core/users/test_api.py, api/tests/tasks/gdpr_tasks_test.py, api/tests/test_utils.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29702
=> Pc 29702 cleaning cron gdpr extract

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30564
=> (PC-30564)[API] feat: Add WIP_ENABLE_OFFER_ADDRESS FF

api/src/pcapi/alembic/versions/20240625T151325_4b41a69dfe71_remove_ff_wip_enable_new_nav_ab_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30329
=> (PC-30329)[API] fix: fix FF name

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_complex_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30550
=> (PC-30550)[API] feat: add music thing & event with gtl id

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_complex_offers.py
=> (BSR) refactor: remove useless repository save

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/admin_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30590
=> (PC-30590)[BO] fix: crash in admin user page

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30591
=> (PC-30591)[API] feat: add venue ids to bank accounts csv

api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30391
=> (PC-30391)[BO] feat: add default value to deposit filter

api/src/pcapi/core/history/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice/pro/blueprint.py, api/src/pcapi/routes/pro/venues.py, api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/core/offerers/test_api.py, api/tests/routes/backoffice/pro_test.py, api/tests/routes/pro/post_save_new_onboarding_data_test.py, api/tests/routes/pro/post_venue_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30569
=> (PC-30569)[API] feat: trace venue creation in the history

pro/src/pages/Sitemap/Sitemap.tsx, pro/src/pages/Sitemap/__specs__/Sitemap.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30400
=> (PC-30400)[PRO] feat: Add a script to generate SiteMap

pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx, pro/src/components/IndividualOfferForm/ImageUploaderOffer/ImageUploaderOffer.tsx, pro/src/components/IndividualOfferForm/ImageUploaderOffer/__specs__/ImageUploaderOffer.tracker.spec.tsx, pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx, pro/src/components/OfferEducationalActions/__specs__/OfferEducationalActions.spec.tsx, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/pages/CollectiveOfferFromRequest/CollectiveOfferFromRequest.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/BookingLinkCell.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/DeleteDraftCell.tsx, pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/DownloadBookingsModal.tsx, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/__specs__/DownloadBookingModal.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26887
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30132
Rajouter les offerId et offerType dans les trackers
=> (Pc-26887/30132)[PRO] feat: offerId and offerType in trackers.

api/src/pcapi/models/feature.py, pro/src/app/App/layout/Layout.module.scss, pro/src/app/App/layout/Layout.tsx, pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.module.scss, pro/src/components/Newsletter/Newsletter.module.scss, pro/src/components/StocksEventList/StocksEventList.module.scss, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/hooks/useWithoutFrame.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.module.scss, pro/src/pages/VenueCreation/VenueFormActionBar/VenueFormActionBar.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/VenueProviderItem.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/VenueProviderItem.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.module.scss, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/UserProfile/UserProfile.module.scss, pro/src/screens/UserProfile/UserProfile.tsx, pro/src/ui-kit/BoxRounded/BoxRounded.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30011
PR pour retirer la frame autour du contenu dans le portail PRO. 
| Avant | Après |
| ----- | ------- |
| <img width="1424" alt="Capture d’écran 2024-06-27 à 14 50 40" src="https://github.com/pass-culture/pass-culture-main/assets/71768799/77fbc140-8b71-4c76-ab9f-74370558752f"> | <img width="1435" alt="Capture d’écran 2024-06-27 à 14 50 26" src="https://github.com/pass-culture/pass-culture-main/assets/71768799/f1433c7a-2a57-45ab-9b6a-d668ac1a0fec"> |
=> Pc 30011 pro version sans frame du npp

pro/src/core/FirebaseEvents/constants.ts, pro/src/screens/IndividualOffer/Status/StatusToggleButton.tsx, pro/src/screens/IndividualOffer/Status/__specs__/StatusToggleButton.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30556
=> (PC-30556)[PRO] feat: add tracker to future offer publication

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30600
=> (PC-30600)[PRO] feat: Add WIP_SPLIT_OFFER FF

pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.tsx, pro/src/components/IndividualOfferNavigation/__specs__/IndividualOfferNavigation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30598
**Figma**:  https://www.figma.com/design/3MBpH3cfIK7RoOU13RLjAO/PRO---IA-s%C3%A9lection-de-cat%C3%A9gorie?node-id=2210-100411&t=9pHbBHCI9NGOiM6j-4
=> (PC-30598)[PRO] feat: Remove confirmation from stepper

pro/src/components/IndividualOfferForm/UsefulInformations/UsefulInformations.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/Venue.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30599
=> (PC-30599)[PRO] feat: Remove structure field

pro/src/app/App/analytics/orejime.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29859
Correction d'une erreur sentry
=> (PC-29859)[PRO] feat: Orejime init can throw an exception.

pro/src/hooks/__specs__/useWelcomeToTheNewBetaBanner.spec.tsx, pro/src/hooks/useWelcomeToTheNewBetaBanner.ts, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/WelcomeToTheNewBetaBanner/WelcomeToTheNewBetaBanner.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30535
=> (PC-30535)[PRO] feat: Display modal for users who discover the NPP

api/src/pcapi/routes/backoffice/external/zendesk_sell/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30621
=> (PC-30621)[BO] feat: use atomic in files starting with E

pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30481
=> (PC-30481)[PRO] fix: remove separator from partner page

pro/package.json, pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx, pro/src/utils/adageFactories.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30393
=> (PC-30393)[PRO] build: update react-instantsearch dependency

.github/workflows/dev_on_pull_request_workflow.yml, .github/workflows/dev_on_push_workflow_main.yml
Les fichiers dans script_test seront supprimés avant merge si la PR est acceptée
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30492
=> (PC-30492)[API] feat: do not run tests on script push and pr

api/documentation/docusaurus.config.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30635
=> [FIX] Add integration environment to docusaurus config

api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/scripts/beneficiary/import_test_users_test.py
This has been fixed by hand for this week, it will need to be HF on staging before Wednesday
=> (BSR)[API] fix: yes we hack provider creation

.github/workflows/dev_on_push_workflow_main.yml
=> PC-30398 - Fix build image parameter tag

pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30654
On remet les liens vers les pages du formulaires qui sont modifiables car elles sont nécessaire pour la validation d'une offre pour la fraude
=> (PC-30654)[PRO] fix: recap link edition

.github/workflows/dev_on_push_workflow_main.yml
Deploy jobs after push to registry jobs
=> PC-20398 - workflow master reorder deploy jobs

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/gdpr_user_extract_data/list_gdpr_user_extract.html, api/tests/routes/backoffice/gdpr_user_extract_data_test.py
4 commits pour 4 corrections minuscules dans l'interface d'extraction de données personnelles.
=> (BSR)[BO] gdpr extract minor UI improvements

api/src/pcapi/core/bookings/api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30484
=> (PC-30484)[API] fix: handle not cancelled case

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/core/users/email/update.py
Description : 4 petites refacto (1 refacto par commit):
* 6ffe87e4f39271e39b1411d8d3430f604926ae84 : utilisation de `d.get(k, default)` au lieu de `d[k] if k in d else default`
* f67be9b4e59cd77b98d3b102c7ff251cec19bf35 : utilisation de variables pour éviter certaines répétitions + simplification d'une condition
* 60f534c1f98640eacaae9c9cc6b707868e9eb5af : update de la docstring et utilisation d'une boucle for (permettant de return dès que possible)
* 9eeb5547c814fbc7f83178978c2e967f756901e7 : inverser la condition pour avoir un early return et économiser une indentation
=> Qds bsr misc refactor

pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29863
Gestion d'un fetch error.
=> (PC-29863)[PRO] feat: displaying a message error when image loading fails.

pro/cypress/e2e/features/searchIndividualOffer.feature, pro/cypress/e2e/step-definitions/commonSteps.cy.ts, pro/cypress/e2e/step-definitions/searchIndividualOffer.cy.ts
Fix un petit soucis de choix de structure (nouveau menu en haut à droite) avec la nouvelle navigation. Il faut attendre que tout soit bien fini avant de saisir l'EAN pour une recherche
=> (BSR)[PRO] test: fix individual offer. Wait for structure selection

api/src/pcapi/core/bookings/repository.py, api/tests/core/bookings/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30489
=> (PC-30489)[API] feat: Change bookings for offer csv/excel header when OA FF is enabled

api/src/pcapi/routes/public/blueprints.py
=> (PC-30661)[API] feat: fix CORS for deprecated V2

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceActions.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30266
=> (PC-30266)[PRO] style: Modification de cvg téléchargement

pro/src/pages/Offers/Offers/OfferItem/Cells/OfferNameCell/OfferNameCell.tsx, pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss, pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30595
=> (PC-30595)[PRO] fix: sold-out tooltip is not displayed at right place

pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30616
=> (PC-30616)[PRO] fix: draft indicator in individual offer

api/src/pcapi/connectors/recommendation.py
This has been validated by the data, when are starting to have problems this make it worse.
=> (BSR)[API] fix: Remove retry for recommendation API.

api/src/pcapi/routes/backoffice/gdpr_user_extract/blueprint.py, api/src/pcapi/routes/backoffice/templates/gdpr_user_extract_data/list_gdpr_user_extract.html, api/tests/routes/backoffice/gdpr_user_extract_data_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29707
voir la corbeille sur la droite, une fois cliqué, la ligne s'efface. 
- CI - verte 
L'utilisateur avec les droits BO ou au support lvl2 -> est dans la page extraction des données.
l'extraction ciblé est en "pret".
Le bouton est visible et clickable, le bouton supprimera avec succès le contenu de l'extract ainsi que la ligne d'extract lui correspondant.
L'utilisateur avec les droits BO ou au support lvl2 -> est dans la page extraction des données.
l'extraction ciblé est en "En attente".
Le bouton est grisé, la route d'extraction refusera la suppression de l'extract si l'utilisateur tente de le faire via l'URL, l'erreur en question …
=> Pc 29707 button to delete an extract

pro/src/components/ArchiveConfirmationModal/ArchiveConfirmationModal.tsx, pro/src/components/ArchiveConfirmationModal/utils/__specs__/canArchiveCollectiveOffer.spec.ts, pro/src/components/ArchiveConfirmationModal/utils/canArchiveCollectiveOffer.ts, pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.tsx, pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx, pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx, pro/src/icons/full-archive.svg, pro/src/pages/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/__specs__/CollectiveActionsCells.spec.tsx, pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss, pro/src/pages/Offers/Offers/OffersActionsBar/CollectiveOffersActionsBar.tsx, pro/src/pages/Offers/Offers/OffersActionsBar/__specs__/CollectiveOffersActionsBar.spec.tsx, pro/src/ui-kit/Icons/iconsList.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29686
Pouvoir archiver une/des offres depuis la liste des offres, l'actionBar et le récap d'une offre
=> (PC-29686)[PRO] feat: archivage offer

api/src/pcapi/core/providers/api.py, api/src/pcapi/core/providers/exceptions.py, api/src/pcapi/core/providers/factories.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/core/providers/validation.py, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/documentation_constants/tags.py, api/src/pcapi/routes/public/individual_offers/v1/__init__.py, api/src/pcapi/routes/public/individual_offers/v1/providers.py, api/src/pcapi/routes/public/serialization/providers.py, api/src/pcapi/routes/public/serialization/venues.py, api/tests/core/providers/test_api.py, api/tests/core/providers/test_repository.py, api/tests/core/providers/test_validation.py, api/tests/routes/public/collective/endpoints/get_collective_offers_venues_test.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/get_offerer_venue_test.py, api/tests/routes/public/individual_offers/v1/get_provider.py, api/tests/routes/public/individual_offers/v1/patch_provider.py
Ticket Jira  : https://passculture.atlassian.net/browse/PC-30310
=> (PC-30310)[API] feat: add `PATCH` endpoints to update external Urls

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240617T083927_e0d7e16bcbaa_.py, api/src/pcapi/alembic/versions/20240619T070632_11a733e8b667_.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/reactions/factories.py, api/src/pcapi/core/reactions/models.py, api/src/pcapi/core/users/models.py, api/src/pcapi/models/__init__.py, api/src/pcapi/routes/native/v1/serialization/bookings.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/bookings_test.py, api/tests/routes/native/v1/offers_test.py
Ajouter les réactions dans la route GET /bookings d'un user
Ticket Jira : https://passculture.atlassian.net/browse/PC-29490
=> PC-29490 add reaction first route

api/src/pcapi/routes/public/documentation_constants/fields.py, api/tests/routes/public/expected_openapi.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30609
=> (PC-30609)[API] feat: improve documentation field for publication date

pro/src/components/AdageButtonFilter/AdageButtonFilter.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingModal.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.module.scss, pro/src/pages/Offers/Offers/Offers.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/CinemaProviderParameters.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/VenueProviderItem.module.scss, pro/src/screens/CsvTable/CsvTable.module.scss, pro/src/screens/CsvTable/CsvTable.tsx, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/DownloadBookingsModal.module.scss, pro/src/styles/components/layout/CsvTable/_CsvTable.scss, pro/src/styles/components/layout/CsvTable/index.scss, pro/src/styles/components/layout/index.scss, pro/src/styles/global/_layout.scss, pro/src/ui-kit/Icons/Icons.module.scss, pro/src/ui-kit/InfoBox/InfoBox.module.scss, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss, pro/src/ui-kit/form/SelectAutoComplete/OptionsList/OptionsList.module.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30668
**Objectif**
- Suppression des `font-size` qui n'ont plus d'utilité
- Au passage, transformation du style global CsvTable à un style scopé dans le composant
=> Pc 30668 clean font size

pro/src/screens/CollectiveOfferConfirmation/CollectiveOfferConfirmation.tsx, pro/src/screens/IndividualOffer/IndivualOfferLayout/OfferStatusBanner/OfferStatusBanner.tsx, pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.module.scss, pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30560
**Figma**: https://www.figma.com/design/386uELLHfO6YHYNrLBZEj1/PRO---Publication-dans-le-futur?node-id=2045-69323&t=IM0PinogxNHwYFRr-11
**Before**
**After**
=> (PC-30560)[PRO] feat: Change wordings confirmation offer standby

pro/src/core/OfferEducational/utils/postCollectiveOfferImage.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29866
Erreur de chargement d'image
=> (PC-29866)[PRO] feat: handle image loading failing.

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30371
=> (PC-30371)[PRO] fix: `useOutletContext()` is undefined sometimes.

api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/routes/backoffice/templates/components/offerer_validation/extra_row.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30646
=> (PC-30646)[BO] feat: fetch all offerer dms applications in offerer list

api/src/pcapi/connectors/api_allocine.py, api/tests/connectors/api_allocine_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30314
Ne pas arrêter toute une synchronisation (d'un lieu) si un le json renvoyé contient un élément invalide. Si c'est le cas, filtrer la ou les séances qui posent problème et continuer la synchronisation.
=> (PC-30314)[API] fix: allocine show times list: discard invalid edges

api/src/pcapi/routes/public/individual_offers/v1/products.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
Handle unique constraint violation: venueId-idAtProvider pair already exists.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30390
Bug : si l'on essaie de créer une offre avec un `idAtProvider` qui existe déjà pour le lieu ciblé, l'erreur renvoyée par la base de données n'est pas traitée. L'utilisateur reçoit une erreur 500 et ne comprends pas ce qui s'est passé.
Fix : identifier au mieux cette erreur et renvoyer un message clair.
Au passage : mieux gérer les erreurs qui pourraient lors de la création d'une offre (ici, un produit).
=> (PC-30390)[API] fix: public api: create product: existing idAtProvider

api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/tests/core/offers/test_api.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/patch_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29855 
Permettre l'édition du titre (`name`) et de la description d'une offre via l'api publique.
+ quelques modifications pour diminuer le nombre de requêtes nécessaires à cette opération (dans un second commit).
=> PC 29855 public api update offers title and desc

api/src/pcapi/models/feature.py, api/src/pcapi/scripts/install_data.py, api/tests/models/feature_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30628
=> (PC-30628)[API] feat: add command to clean unused FF

api/src/pcapi/core/providers/api.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/core/providers/validation.py, api/src/pcapi/routes/public/documentation_constants/http_responses.py, api/src/pcapi/routes/public/individual_offers/v1/providers.py, api/src/pcapi/routes/public/serialization/providers.py, api/tests/core/providers/test_api.py, api/tests/core/providers/test_repository.py, api/tests/core/providers/test_validation.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/patch_venue_provider_external_urls.py
Ticket Jira: https://passculture.atlassian.net/browse/PC-30311
=> (PC-30311)[API] Add PATCH endpoint to update venue provider external urls

pro/src/pages/Home/Venues/Venue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30597
=> (PC-30597)[PRO] feat: Delete a button.

pro/src/screens/Bookings/Bookings.tsx, pro/src/screens/Bookings/PreFilters/FilterByVenue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30720
- Revert la supression du filtre "tous les lieux"
=> (PC-30720)[PRO] feat: We can still filter by all the venues.

api/tests/routes/native/v1/offers_test.py, api/tests/routes/native/v1/recommendation_test.py, api/tests/routes/native/v1/universal_links_test.py
=> (BSR)[API] chore: add assert num queries to some native routes

.github/workflows/dev_on_workflow_deploy.yml, api/documentation/docusaurus.config.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30739
=> [UPD] Remove integration environment support from CI and docusaurus

pro/src/pages/IndividualOfferWizard/About/About.tsx, pro/src/pages/IndividualOfferWizard/Details/Details.tsx
=> (BSR)[PRO] fix: linter for dead code

pro/src/app/App/App.tsx
Correction pour corriger la mauvaise structure selectionnée quand on vient du BO avec le connect as.
=> (BSR)[PRO] feat: Quickfix to handle connect-as offerers.

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/routes/pro/venue_providers.py, api/tests/core/external_bookings/test_api.py
Ticket: https://passculture.atlassian.net/browse/PC-30312
=> (PC-30312)[API] Implement logic to use VenueProviderExternalUrls in ticket booking/cancellation requests

api/src/pcapi/utils/urls.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30740
=> Modifier les liens du BO pour basculer automatiquement de structure

pro/src/core/shared/constants.ts, pro/src/custom_types/window.d.ts, pro/src/hooks/useInitReCaptcha.ts, pro/src/pages/LostPassword/LostPassword.tsx, pro/src/pages/SignIn/SignIn.tsx, pro/src/pages/Signup/SignupContainer/SignupContainer.tsx, pro/src/screens/SignupJourneyForm/Validation/Validation.tsx, pro/src/utils/recaptcha.ts
=> (BSR)[PRO] fix: Fixing a sentry error where `gcaptchaScript` is undefined.

api/src/pcapi/routes/public/individual_offers/v1/providers.py
Error due to `get_venue_provider_by_venue_and_provider_ids` returning `None` in some cases
=> (BSR)[API] fix: fix mypy error

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/routes/serialization/__init__.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/public/individual_offers/v1/post_dates_test.py
A relire commit par commit
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30518
=> (PC-30518)[API] feat: log subscription modification origin

.github/workflows/dev_on_workflow_push_docker_image.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28352
=> (PC-28352) ci: Add cosign to be able to sign image

pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
Correction d'un problème de rechargement remonté par les tests E2E.
=> (BSR)[PRO] fix: Fix a reloading issue seen with E2E tests.

api/src/pcapi/connectors/recommendation.py
=> (BSR)[API] fix: increase reco timeout to 10s

api/src/pcapi/core/reactions/api.py, api/src/pcapi/routes/native/v1/__init__.py, api/src/pcapi/routes/native/v1/reaction.py, api/src/pcapi/routes/native/v1/serialization/reaction.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/reaction_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29452
=> (PC-29452)[API] feat: add post reaction route

api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/pro/collective_offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/core/educational/test_models.py, api/tests/routes/pro/patch_collective_offer_test.py, pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts, pro/src/utils/collectiveApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29691
=> (PC-29691)[PRO] feat: add a isEditableByPcPro to indicate the pro/front if the offer is editable

pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferHeader/__specs__/AdageOfferHeader.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/__specs__/AdageOfferListCard.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/OfferFavoriteButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/__specs__/OfferFavoriteButton.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferShareLink/OfferShareLink.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferShareLink/__specs__/OfferShareLink.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30119
=> (PC-30119)[ADAGE] fix: fix adage tooltips and update wordings

pro/src/screens/Bookings/Bookings.tsx
Correction d'un problème de chargement des filtres
=> (BSR)[PRO] fix: Fix filters init on page refresh.

.github/workflows/dev_on_workflow_push_docker_image.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28352
=> (PC-28352) ci:Get the right sha when we inspect the container

api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/tests/routes/backoffice/pro_users_test.py
Fix de la suppression d'un compte pro sur le BO s'il a déjà été enregistré en tant que bénéficiaire
sentry: https://sentry.passculture.team/organizations/sentry/issues/1616637/?project=5
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30723
=> (PC-30723)[BO] fix: Delete pro user's related objects if he was beneficiary before

api/documentation/docs/understanding-our-api/authentication-authorization.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30500
Mise à jour de la documentation de l'API publique.
=> (PC-30500)[API] doc: public api: update authentication/authorization

.github/workflows/dev_on_workflow_update_jira_issues.yml, .jira.d/templates/edit
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30456
=> (PC-30456) CI - remove Jira issue's Impropre-related code

api/src/pcapi/routes/native/v1/serialization/offerers.py, api/tests/routes/native/v1/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29427
=> (PC-29427)[API] fix: allow non-valid phone numbers in get venues

pro/src/app/App/layout/Layout.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30715
=> (PC-30715)[PRO] fix: Remove content padding in register funnel

pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/__specs__/CollectiveTimeLine.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29812
=> (PC-29812)[PRO] fix: handle collective booking cancellation by backoffice

api/documentation/docs/tutorials/create-a-collective-offer.md, api/documentation/docs/tutorials/migrate-to-the-new-api.md, api/documentation/src/pages/change-logs.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30748
=> (PC-30748)[API] Add Documentation page to explain how to migrate to the new API

pro/src/config/swrQueryKeys.ts, pro/src/pages/AdageIframe/app/components/OffersFavorites/OffersFavorites.tsx, pro/src/pages/AdageIframe/app/components/OffersFavorites/__specs__/OffersFavorites.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/OfferFavoriteButton.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29241
=> (PC-29241)[ADAGE] fix: use swr to get favorites

pro/package.json, pro/src/components/DialogBox/DialogBox.tsx, pro/src/vitest.setup.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30640
=> (PC-30640)[PRO] bump: bump `@radix-ui/react-dropdown-menu.` version

api/src/pcapi/routes/pro/users.py, api/tests/routes/pro/get_reimbursements_csv_test.py, api/tests/routes/pro/patch_venue_test.py, api/tests/routes/pro/post_offerer_test.py, api/tests/routes/pro/post_venue_test.py, api/tests/routes/pro/signin_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30815
=> (PC-30815)[API] fix: add forgotten update of lastConnexionDate to pc pro

api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/get_all_collective_offers_test.py, pro/src/apiClient/v1/models/CollectiveOffersStockResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30571
=> (PC-30571)[PRO] feat: Add startDatetime and endDatetime in API

api/src/pcapi/connectors/subcategory_suggestion.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30675
=> (PC-30675)[API] feat: add connector to subcategory suggestion API

api/documentation/docs/understanding-our-api/authentication-authorization.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30501
Légère mise à jour de la description d'un lieu, dans la documentation de l'API publique.
=> (PC-30501)[API] feat: public api doc: update venue desc

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.module.scss, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderBudget/AdageHeaderBudget.module.scss, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30253
=> (PC-30253)[PRO] style: ADAGE header accessibility

pro/cypress/e2e/step-definitions/venue.cy.ts, pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/Offerers/PartnerPageIndividualSection.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30728
=> (PC-30728)[PRO] style: Wordings of home page

pro/src/components/UserIdentityForm/UserIdentityForm.tsx, pro/src/components/UserPasswordForm/UserPasswordForm.tsx, pro/src/utils/formatPrice.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29878
- Pas réussi à reproduire le problème, mais j'ai quand même rajouté un catch pour corriger. L'erreur se produisant souvent, on va vite savoir si ça marche ou pas.
=> (PC-29878)[PRO] fix: Fix a NumberFormat issue with safari version.

pro/.eslintrc.cjs, pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30871
**Objectif**
Forcer le PascalCase sur les types customs.
=> (PC-30871)[PRO] feat: Force PascalCase for types aliases.

pro/src/components/IndividualOfferForm/utils/setInitialFormValues.ts, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/constants.ts, pro/src/screens/IndividualOffer/DetailsScreen/types.ts, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/screens/IndividualOffer/DetailsScreen/validationSchema.ts, pro/src/screens/IndividualOffer/InformationsScreen/utils/filterCategories/filterCategories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30706
=> (PC-30706)[PRO] feat: details form, part 2

pro/src/components/IndividualOfferForm/UsefulInformations/Venue/Venue.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/__specs__/Venue.spec.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/__specs__/VenueAccessibilityUpdates.spec.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/utils.ts, pro/src/components/UserIdentityForm/UserIdentityForm.tsx, pro/src/components/UserPasswordForm/UserPasswordForm.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30821
=> (PC-30821)[PRO] feat: Change wording and behavior for OfferAddress creation

pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30692
=> (PC-30692)[PRO] feat: Summary with splited offer creation

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240716T093806_e3e9ba056dab_remove_ff_wip_future_offer.py, api/src/pcapi/models/feature.py, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx, pro/src/screens/IndividualOffer/IndivualOfferLayout/__specs__/IndivualOfferLayout.spec.tsx, pro/src/screens/IndividualOffer/Status/StatusToggleButton.tsx, pro/src/screens/IndividualOffer/Status/__specs__/StatusToggleButton.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30150
(bonjour Jean-Marie)
=> (PC-30150)[PRO] style: Delete of FF WIP_FUTURE_OFFER

api/tests/routes/pro/get_offers_test.py
corriger le assert_num_querie dans should_filter_offers_by_given_venue_id
=> (BSR)[API] fix: fix assert_num_queries

.github/workflows/dev_on_workflow_build_and_tag.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30811
=> (PC-30811) ci: Sign image when we push a tag

pro/src/screens/IndividualOffer/StocksThing/StockThing.module.scss, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30854
=> (PC-30854)[PRO] feat: Reduce 'stock & prices' fields in offer

.github/pull_request_template.md
=> (BSR)[PRO] docs: Add PR template checkbox for tests plan

pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/components/UserIdentityForm/UserIdentityForm.tsx, pro/src/components/UserPasswordForm/UserPasswordForm.tsx, pro/src/pages/IndividualOfferWizard/DetailsSummary/DetailsSummary.tsx, pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.module.scss, pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx, pro/src/screens/IndividualOffer/DetailsSummary/__specs__/DetailsSummary.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/DisplayOfferInAppLink/DisplayOfferInAppLink.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30606
=> (PC-30606)[PRO] feat: detailsSummary

pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx, pro/src/pages/Offers/Offers/OffersActionsBar/DeleteConfirmDialog.tsx, pro/src/pages/Offers/Offers/OffersActionsBar/IndividualOffersActionsBar.tsx, pro/src/pages/Offers/Offers/OffersActionsBar/__specs__/IndividualOffersActionsBar.spec.tsx, pro/src/pages/Offers/Offers/utils.ts, pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30681
=> (PC-30681)[PRO] fix: offers draft deletion

api/src/pcapi/core/finance/api.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/finance/generate_invoices_blueprint.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30622
=> migration des fichiers du BO qui commencent par F vers atomic()

pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/pages/IndividualOfferWizard/UsefulInformation/UsefulInformation.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.module.scss, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/utils.spec.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/constants.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/types.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/utils.ts, pro/src/ui-kit/form/Checkbox/Checkbox.tsx, pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30604
Figma: https://www.figma.com/design/3MBpH3cfIK7RoOU13RLjAO/PRO---IA-s%C3%A9lection-de-cat%C3%A9gorie?node-id=2172-96696&t=NGpRFvIlRkEmgyws-4
=> (PC-30604)[PRO] feat: offer usefulInformation page

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240717T150013_59d02d648922_add_venue_provider_permission.py, api/src/pcapi/alembic/versions/20240717T150226_08b944954eba_add_venue_provider_permission.py, api/src/pcapi/core/providers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30921
=> (PC-30921)[API] feat: add `venue_provider_permission` table

api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30647
=> (PC-30647)[BO] feat: add buttons validate reject wait in the structure page

.github/workflows/dev_on_dispatch_release_deploy.yml
Corriger une typo dans le worfklow de déploiement.
=> (BSR) fix: typo in ask-for-review-on-slack CI job

api/src/pcapi/core/mails/transactional/pro/offer_validation_to_pro.py, api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30713
=> (PC-30713)[API] feat: add publication_date to OFFER_APPROVAL_TO_PRO email

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/post_offer_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/PostOfferBodyModel.ts, pro/src/apiClient/v1/models/PostOfferOffererAddressBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30831
=> (PC-30831)[PRO] feat: create offer with offererAddress

pro/package.json, pro/src/components/Address/Address.tsx, pro/src/components/Address/__specs__/Address.spec.tsx, pro/src/components/Address/constants.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : Ajout du hook useDebounce() pour limiter les appels vers l'API Address à chaque onChange
=> (BSR)[PRO] feat: Adds debounce for Address API calls on type

pro/src/config/swrQueryKeys.ts, pro/src/core/Offers/types.ts, pro/src/pages/CollectiveOfferCreation/CollectiveOfferCreation.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataEditionReadOnly.tsx, pro/src/screens/CollectiveOfferSelectionDuplication/__specs__/CollectiveOfferSelectionDuplicationScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/serializers.spec.ts, pro/src/screens/IndividualOffer/InformationsScreen/serializePatchOffer.ts, pro/src/screens/IndividualOffer/InformationsScreen/serializePostOffer.ts, pro/src/screens/OfferEducational/useOfferEducationalFormData.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30961
**Objectif**
Supprimer des TODOs et FIX MEs
- Suppression du type custom `OfferExtraDat`
- Utilisation de SWR dans `useOfferEducationalFormData`
- Suppression d'un TODO qui est pas clair et semble pas super important
- 2 fix me corrigés dans un fichier de test
=> Pc 30961 fix todos 2

pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29089
=> (PC-29089)[PRO] fix: a11y for mailto in SignupConfirmation

pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25787
=> (PC-25787)[PRO] fix: a11y on checkboxes

pro/src/ui-kit/Thumb/Thumb.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29139
Ajouter un alt vide pour les images
=> (PC-29139)[PRO] feat: add empty alt for img

pro/src/components/ImageEditor/ImageEditor.tsx, pro/src/components/ImagePreview/ImagePreview.tsx, pro/src/components/ImageUploader/AppPreviewOffer/AppPreviewOffer.tsx, pro/src/components/ImageUploader/AppPreviewVenue/AppPreviewVenue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29094
=> (PC-29094)[PRO] fix: a11y in ImageUploader

pro/src/apiClient/__specs__/helpers.spec.ts, pro/src/screens/IndividualOffer/InformationsScreen/utils/files.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/utils/files.ts, pro/src/screens/IndividualOffer/hooks/useIndividualOfferImageUpload.ts
Ticket Jira (ou description si BSR) : Promisify la fonction `imageFileToDataUrl` et y ajoute un test
=> Bsr promisify and test `imageFileToDataUrl`

pro/src/screens/SignupJourneyForm/Activity/ActivityForm.module.scss, pro/src/screens/SignupJourneyForm/Authentication/OffererAuthenticationForm.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30857
- Correction de marges
=> (PC-30857)[PRO] style: Margin fix.

api/src/pcapi/core/providers/api.py, api/tests/core/providers/connect_provider_to_venue_test.py, api/tests/routes/pro/post_venue_provider_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23764
=> (PC-23764)[API] Add all permissions by default when creating a new VenueProvider

api/src/pcapi/models/feature.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/services/authorization.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/get_events_test.py, api/tests/routes/public/individual_offers/v1/utils.py, api/tests/routes/public/services/test_authorization.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30975
=> (PC-30975)[API] Add authorization service and first implementation on GET events endpoint

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30991
=> (PC-30991) ci: Fix deploy for adage

pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29165
([](http://localhost:3001/offre/individuelle/2266/creation/stocks))
=> (PC-29165)[PRO] style: A11Y, Add h2 at titles, creation-stocks

.github/workflows/dev_on_dispatch_release_deploy.yml
Modification du message de notification Slack lors d'une demande de déploiement
NB: le Markdown utilisé par l'API Slack est un peu différent de la norme, en particulier pour les liens.
On peut vérifier la syntaxe dans https://api.slack.com/tools/block-kit-builder
=> (BSR) ci: tweak notification of deployment review

pro/src/components/ImageUploader/ButtonAppPreview/ModalAppPreview.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageUploadBrowser.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageUploadConfirm.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/__specs__/ModalImageCrop.spec.tsx, pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.tsx, pro/src/pages/Home/WelcomeToTheNewBetaBanner/WelcomeToTheNewBetaBanner.tsx, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx, pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/PricingPointDialog.tsx, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/AllocineProviderFormDialog.tsx, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/CinemaProviderFormDialog.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/AddRecurrencesButton.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/__specs__/RecurrenceForm.spec.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29096
=> (PC-29096)[PRO] fix: a11y for Dialog with labelledby

pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25095
=> (PC-29095)[PRO] fix: a11y for errors in FieldsetLayout

pro/cypress/e2e/step-definitions/createEventIndividualOffer.cy.ts
=> (BSR)[PRO] fix: Fix e2e test issues with offer creation.

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/serialize.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/patch_draft_offer_details_test.py, api/tests/routes/pro/patch_draft_offer_test.py, api/tests/routes/pro/post_draft_offer_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/PatchDraftOfferBodyModel.ts, pro/src/apiClient/v1/models/PatchDraftOfferDetailsBodyModel.ts, pro/src/apiClient/v1/models/PostDraftOfferBodyModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira : https://passculture.atlassian.net/browse/PC-30613
=> (PC-30613)[API] feat: split offer creation

api/src/pcapi/core/subscription/profile_options.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/src/pcapi/routes/native/v1/serialization/subscription.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30737
=> (PC-30737)[API] feat: add postal code and activity edition for native 

api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py, pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30879
=> (PC-30879)[PRO] feat: Add a `dates` attribute in API return for GET /collective/offers/<id>

pro/src/pages/VenueCreation/VenueCreationForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26015
Changer le wording de ADAGE sur la page lieu pour qu'il soit complet
=> (PC-26015)[PRO] feat: wording ADAGE in venue page

api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/post_offer_test.py, pro/src/apiClient/v1/models/PostOfferOffererAddressBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30831
=> (PC-30831)[API] fix: make oa label optional

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py, api/tests/core/external_bookings/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30959
=> (PC-30959)[API] feat: implement logic to use `notificationExternalUrl` defined at `VenueProvider` level

pro/src/components/IndividualOfferForm/UsefulInformations/Venue/Venue.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/__specs__/Venue.spec.tsx, pro/src/pages/IndividualOfferWizard/Offer/Offer.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30821
=> Pc 30821 modifs informations pratiques

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://sentry.passculture.team/organizations/sentry/issues/1617338/?project=5&referrer=slack
=> (BSR)[PRO] fix: Fix deletion of playlist on deletion of venue

pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/utils.spec.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/validationSchema.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/constants.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/types.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/utils.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30889
=> (PC-30889)[PRO] feat: Useful information page v2

pro/src/components/AdageButtonFilter/AdageButtonFilter.module.scss, pro/src/components/ImageUploader/ButtonAppPreview/ButtonAppPreview.tsx, pro/src/components/ImageUploader/ButtonAppPreview/ModalAppPreview.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageUploadConfirm.module.scss, pro/src/components/OfferAppPreview/VenueDetails/VenueDetails.module.scss, pro/src/components/OfferAppPreview/VenueDetails/VenueDetails.tsx, pro/src/components/StocksEventList/StocksEventList.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30802
=> (PC-30802)[PRO] feat: Remove some line-height

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_addresses_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetOffererAddressWithIsEditableResponseModel.ts, pro/src/apiClient/v1/models/GetOffererAddressesResponseModel.ts
Envoyer l'information du lien entre oa et venue dans le retour de l'api
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30942
=> (PC-30942)[API] feat: Sending isEditable attribut of oa

pro/src/app/AppRouter/routesMap.tsx, pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/core/Offers/utils/getIndividualOfferUrl.ts, pro/src/hooks/__specs__/useOfferEditionURL.spec.tsx, pro/src/hooks/useOfferEditionURL.ts, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOfferRow/IndividualOfferRow.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveActionButtons.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx, pro/src/screens/OfferType/OfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30983
=> (PC-30983)[PRO] feat: implement navigation for new offer journey

pro/src/screens/IndividualOffer/StocksThing/ActivationCodeFormDialog/AddActivationCodeForm.tsx, pro/src/ui-kit/form/shared/BaseFileInput/BaseFileInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29113
=> (PC-29113)[PRO] fix: a11y for upload file field

pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30834
=> (PC-30834)[PRO] feat: add tracker to Details form

pro/cypress/e2e/features/adage.feature, pro/cypress/e2e/step-definitions/adage.cy.ts, pro/src/pages/AdageIframe/app/components/Pagination/Pagination.tsx, pro/src/store/adageFilter/reducer.ts, pro/src/store/adageFilter/selectors.ts, pro/src/ui-kit/Pagination/Pagination.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30851
Sauvegarder la page pour pouvoir revenir à la bonne page au retour sur la page de recherche sur ADAGE
=> (PC-30851)[PRO] feat: adage save page value

api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30935
=> (PC-30935)[API] feat: add isPermanent, venueTypeCode and bannerUrl to algolia offer object

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31092
=> (PC-31092)[BO] feat: don't send notif to Adage when rejecting offer

pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.tsx, pro/src/components/IndividualOfferNavigation/constants.ts, pro/src/core/Offers/utils/getIndividualOfferUrl.ts, pro/src/pages/IndividualOfferWizard/UsefulInformationsSummary/UsefulInformationsSummary.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx, pro/src/screens/IndividualOffer/UsefulInformationsSummaryScreen/UsefulInformationsSummary.tsx, pro/src/screens/IndividualOffer/UsefulInformationsSummaryScreen/__specs__/UsefulInformationsSummary.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30605
=> (PC-30605)[PRO] feat: UsefulInformationsSummary

pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29114
=> (PC-29114)[PRO] fix: a11y for error in fieldsetLayout

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30980
=> (PC-30980)[PRO] bump: Bump vitest to 2.0.4.

pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31047
=> (PC-31047)[PRO] fix: offer summary display

pro/src/pages/Offers/OffersTable/Cells/OfferNameCell/OfferNameCell.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31026
Ré-afficher la date de l'évènement sous le titre de l'offre collective quand le FF ENABLE_COLLECTIVE_OFFERS_EXPIRATION est désactivée
=> (PC-31026)[PRO] fix: readd eventdate informations when ff not active

api/documentation/docs/understanding-our-api/resources/individual-offers.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30495
Compléter les informations concernant les réservations individuelles dans la documentation de l'API publique.
Ajout d'une section concernant les différents statuts. Et d'une autre concernant les règles d'annulation.
=> (PC-30495)[API] feat: public api doc: update indiv. bookings section

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30894
=> (PC-30894)[PRO] feat: add ff WIP_SUGGESTED_SUBCATEGORIES

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30687
=> (PC-30687)[PRO] feat: Create the FF ENABLE_COLLECTIVE_NEW_STATUSES.

.github/workflows/dev_on_workflow_deploy.yml
=> (BSR)[API] ci: fix kubectl logs returning before container is created

api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/offers.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py
Co-authored-by: @anoukhello 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30912
=> (PC-30912)[ADAGE] fix: Remove archived/inactive offer from listed templates

api/src/pcapi/connectors/api_adresse.py, api/src/pcapi/connectors/serialization/boost_serializers.py
- Supprimer des FIXME/TODO
- Déployer le back sur testing suite à un correctif de CI
=> (BSR)[API] chore: remove obsolete FIXMES

pro/src/components/IndividualOfferForm/ImageUploaderOffer/ImageUploaderOffer.module.scss, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30987
=> (PC-30987)[PRO] fix: various adjustments on offer creation

pro/cypress/e2e/step-definitions/createCommonIndividualOffer.cy.ts, pro/cypress/e2e/step-definitions/createEventIndividualOffer.cy.ts, pro/cypress/support/intercepts.ts
=> (BSR)[PRO] test: Wait fixes.

pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Correction d'une inversion d'une condition qui affiche le mauvais wording
=> (PC-31136)[PRO] fix: Fix inverted wording

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31099
=> (PC-31099)[BO] fix: better error management on mass booking validation

api/src/pcapi/routes/pro/users.py, api/src/pcapi/utils/login_manager.py, api/tests/utils/login_manager_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29653
=> (PC-29653)[API] feat: add session timeout to pro backend

pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.tsx, pro/src/utils/getOfferConditionalFields.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30987
=> (PC-30987)[PRO] fix: withdrawal fields on UsefulInformationsForm

api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31147
=> (PC-31147)[API] feat: add more user personal data in get profile route

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/tests/routes/pro/get_reimbursements_csv_by_invoices_test.py, api/tests/routes/pro/get_reimbursements_csv_test.py
replace "lieu" par "partenaire culture"
supprimer la colonne  "Adresse du lieu"
Ajouter la colonne "Adresse de l'offre"
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30380
=> (PC-30380)[API] feat: add offer address info in reimbursement csv

api/tests/routes/pro/get_all_bookings_test.py, api/tests/routes/pro/get_all_collective_bookings_test.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_autocomplete_educational_redactors_for_uai_test.py, api/tests/routes/pro/get_bank_accounts_test.py, api/tests/routes/pro/get_bookings_csv_test.py, api/tests/routes/pro/get_bookings_excel_test.py, api/tests/routes/pro/get_categories_test.py, api/tests/routes/pro/get_collective_booking_csv_test.py, api/tests/routes/pro/get_collective_booking_excel_test.py, api/tests/routes/pro/get_collective_booking_test.py, api/tests/routes/pro/get_collective_offer_template_test.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/get_combined_invoices_pdf_test.py, api/tests/routes/pro/get_connect_as_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30623
=> (PC-30623)[API] test: add assert_num_queries in pro

pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/core/Offers/utils/getIndividualOfferUrl.ts, pro/src/hooks/__specs__/useOfferEditionURL.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.tsx, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30983
=> (PC-30983)[PRO] fix: offer form navigation

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
fix un test flacky en lui donnant la possiblité de s'executer deux fois moins vite.
=> (BSR)[API] fix: fix flakyness in finance tests

pro/src/app/App/analytics/firebase.ts, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30898
=> (PC-30898)[PRO] feat: Add AB test Firebase

pro/src/screens/Bookings/PreFilters/PreFilters.module.scss, pro/src/screens/Bookings/PreFilters/PreFilters.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.module.scss, pro/src/screens/Offers/SearchFilters/SearchFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30910
=> (PC-30910)[PRO] feat: Reset filters button with inputs.

pro/src/components/FormLayout/FormLayout.module.scss, pro/src/components/FormLayout/FormLayoutSection.tsx, pro/src/components/FormLayout/__specs__/FormLayoutSection.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/EventPublicationForm/EventPublicationForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30596
=> (PC-30596)[PRO] feat: remove new tag from future offer

api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/schemas.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_schemas.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/OfferExtraData.ts, pro/src/apiClient/v1/models/PatchDraftOfferBodyModel.ts, pro/src/apiClient/v1/models/PostDraftOfferBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31088
=> (PC-31088)[API] refactor: post patch draft offer

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31154
Création d'un FF pour les brouillons des offres collectives : ENABLE_COLLECTIVE_DRAFT_OFFERS
=> (PC-31154)[PRO] feat: create ff collective offer draft

api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_repository.py, api/tests/routes/pro/get_all_collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29685
=> (PC-29685)[PRO] fix: Some status where not exclusive

api/src/pcapi/core/mails/backends/sendinblue.py
fix suite a une erreur dans la lecture de la doc.
=> (BSR)[API] fix: fix sendinblue raw contact data return type

api/src/pcapi/routes/pro/collective_offers.py
=> (BSR)[PRO] fix: Typo on API error

api/src/pcapi/core/users/models.py, api/src/pcapi/routes/native/v1/__init__.py, api/src/pcapi/routes/native/v1/feedbacks.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/src/pcapi/routes/native/v1/serialization/feedbacks.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/feedbacks_test.py
=> (PC-30989)[API] feat: add user feedback route

pro/src/pages/VenueSettings/VenueSettingsForm.tsx, pro/src/pages/VenueSettings/__specs__/VenueSettingsFormScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31009
=> (PC-31009)[PRO] feat: Add leaving guard for venue settings

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240802T092958_4bd28b6d5d6c_.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/models/feature.py, api/tests/routes/native/v1/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26459
=> (PC-26459)[API] chore: remove WIP_GOOGLE_MAPS_VENUE_IMAGES feature flag

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/commands.py, api/tests/core/users/test_api.py
deux petites correction sur l'extraction RGPD
=> Bsr rpa multiple fix gdpr extract

api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_repository.py, pro/src/apiClient/v1/models/CollectiveOfferDisplayedStatus.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31000
=> (PC-31000)[PRO] feat: Add the reimbursed status

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/offers.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29918
=> PC-29918 add reactions to offer

api/tests/routes/native/v1/offers_test.py
This unbreaks the ci
Ticket to fix for real: https://passculture.atlassian.net/browse/PC-31181
Green-ifier la CI sur master
=> (BSR)[API] test: unflake some tests

api/tests/core/bookings/test_api.py, api/tests/routes/adage/v1/get_all_venues_test.py, api/tests/routes/adage/v1/get_venue_by_id_test.py, api/tests/routes/adage/v1/get_venues_from_name_test.py, api/tests/routes/adage/v1/get_venues_from_siret_test.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/signin_test.py
=> (BSR)[PRO] style: use offerers_factories instead of offerer_factories

api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/offers.py, api/tests/core/offers/test_repository.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31181
=> PC-31181 improve offer route queries

pro/src/pages/Reimbursements/BankInformations/__specs__/LinkVenuesDialog.spec.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/Filters/__specs__/FilterByOmniSearch.spec.tsx, pro/src/screens/Bookings/PreFilters/FilterByBookingStatusPeriod/FilterByStatus.tsx, pro/src/screens/Bookings/PreFilters/PreFilters.tsx, pro/src/screens/Bookings/PreFilters/__specs__/PreFilters.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31206
=> (PC-31206)[PRO] test: complete tests

pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/serializers.ts, pro/src/utils/translate.ts, pro/tsconfig.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30960
=> (PC-30960)[PRO] feat: Remove noUncheckedIndexedAccess TODOs

pro/src/components/Header/__specs__/HeaderDropdown.spec.tsx, pro/src/components/IndividualOfferForm/Categories/__specs__/Categories.spec.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/TicketWithdrawal/__specs__/TicketWithdrawal.spec.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx, pro/src/components/Newsletter/__specs__/Newsletter.spec.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx, pro/src/pages/Offers/OffersTable/Cells/OfferNameCell/OfferNameCell.tsx, pro/src/pages/Offers/OffersTable/Cells/OfferNameCell/__specs__/OfferNameCell.spec.tsx, pro/src/pages/Signup/__specs__/Signup.spec.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx, pro/src/screens/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx, pro/src/screens/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx, pro/src/ui-kit/Button/__specs__/ButtonLink.spec.tsx
Reprendre les tests unitaires n'ont réalisé de ce fichier en commençant par le haut : 
https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98/edit?gid=358599908#gid=358599908
=> (BSR)[PRO] test: unit test 

pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
=> (BSR)[PRO] test: try to solve flaky Reimbursment test

pro/cypress/e2e/features/createEventIndividualOffer.feature, pro/cypress/e2e/features/createThingIndividualOffer.feature, pro/cypress/e2e/step-definitions/createEventIndividualOffer.cy.ts, pro/cypress/e2e/step-definitions/createThingIndividualOffer.cy.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31033
=> (PC-31033)[PRO] test: e2e for split offer

pro/src/pages/IndividualOfferWizard/UsefulInformation/UsefulInformation.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/utils.spec.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31187
=> (PC-31187) fix& refactor : corrections on new offer

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240716T150036_5f46232cb72f_add_cancellationauthor_for_booking.py, api/src/pcapi/alembic/versions/20240716T150204_35d67a2cddcd_add_cancellationauthor_for_collective_booking.py, api/src/pcapi/alembic/versions/20240716T150303_ebbed0db4e99_add_cancellationauthor_foreign_key_for_booking.py, api/src/pcapi/alembic/versions/20240716T150445_9118d1848c98_add_cancellationauthor_foreign_key_for_collective_booking.py, api/src/pcapi/alembic/versions/20240806T082505_227228152465_revert_adding_cancellationauthorid_column_on_booking_and_collective_booking.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/accounts/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/collective_bookings.html, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30509
=> (BSR)[BO] revert: revert commit PC-30509 because of wrong process migration

api/src/pcapi/alembic/versions/20240806T082505_227228152465_revert_adding_cancellationauthorid_column_on_booking_and_collective_booking.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30509
=> (PC-30509)[BO] fix: add quote for sql cancellationAuthorId

api/documentation/docs/understanding-our-api/resources/individual-offers.md, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/tests/routes/public/expected_openapi.json
Ticket Jira : https://passculture.atlassian.net/browse/PC-30502
=> (PC-30502)[API] feat: improve batch upsert endpoint documentation

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/get_venues_test.py, pro/src/apiClient/v1/models/VenueListItemResponseModel.ts
Ticket Jira : https://passculture.atlassian.net/browse/PC-31138
=> (PC-31138)[PRO] feat: include OffererAddress in venues response API

api/src/pcapi/scripts/rebuild_staging/anonymize.sql, api/tests/scripts/rebuild_staging/test_anonymize.py
Show timing for anonymization steps
=> (BSR)[API] feat: show anonymize script timings

pro/cypress/e2e/features/navigation.feature, pro/cypress/e2e/step-definitions/navigation.cy.ts, pro/src/app/App/hook/useFocus.ts, pro/src/pages/IndividualOfferWizard/Details/Details.tsx, pro/src/pages/IndividualOfferWizard/UsefulInformation/UsefulInformation.tsx
=> (BSR)[PRO] refactor: handle new layout in useFocus

pro/src/repository/venuesService.ts, pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx, pro/src/screens/IndividualOffer/DetailsSummary/__specs__/DetailsSummary.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/serializer.ts, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30826
=> (PC-30826)[PRO] feat: Offerer address displaying in split view.

api/src/pcapi/core/offers/api.py, api/tests/routes/pro/post_draft_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31199
=> (PC-31199)[PRO] fix: create_draf_offer a11y compliance

api/src/pcapi/routes/public/documentation_constants/fields.py, api/tests/routes/public/expected_openapi.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30941
Corriger l'exemple de date de publication car il est impossible de créer une offre qui a lieu dans plus de deux ans.
=> (PC-30941)[API] fix: public api doc: publication date: 2034->2024

pro/src/components/IndividualOfferForm/OfferLocation/validationSchema.ts
Correction pour la validation du schéma qui ne fonctionne pas, et qui bloque la navigation
=> (BSR)[PRO] fix: Fix conditional validation schema.

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/local_providers/allocine/allocine_stocks.py, api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py, api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py, api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py, api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/tests/core/offers/test_validation.py, api/tests/local_providers/allocine_stocks_test.py, api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py, api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py, api/tests/local_providers/cinema_providers/cgr/cgr_stocks_test.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31247
=> (PC-31247)[API] Fix cinema synchronisation bug caused by massive images

api/src/pcapi/core/history/models.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/src/pcapi/routes/backoffice/templates/pivots/get.html, api/tests/routes/backoffice/accounts_test.py
Micro corrections mineures dans le backoffice
=> (BSR)[BO] fix: minor fixes in the backoffice

api/src/pcapi/sandboxes/scripts/creators/data/create_data_admin_users.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_admin_users.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_gdpr_users.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_individual_offerers.py, api/src/pcapi/sandboxes/scripts/getters/pro_01_create_pro_user.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30722
- Les utilisateurs pros créés via la sandbox on le NPP
=> (PC-30722)[API] chore: Sandbox pro users now use the new interface.

pro/src/pages/Errors/NotFound/NotFound.module.scss, pro/src/pages/Errors/Unavailable/Unavailable.module.scss, pro/src/screens/IndividualOffer/StocksEventCreation/HelpSection/HelpSection.module.scss, pro/src/styles/mixins/_fonts.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31261
**Objectif**
Supprimer la typo hero! Elle n'existe pas dans la lib figma pro et c'est validé par Marion, Agathe et Martin
=> (PC-31261)[PRO] style: Replace hero with title1.

pro/src/components/IndividualOfferForm/UsefulInformations/UsefulInformations.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31184
=> (PC-31184)[PRO] feat: Change some wordings

pro/package.json, pro/src/app/App/analytics/orejimeConfig.ts, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/screens/CollectiveOfferVisibility/CollectiveOfferVisibility.tsx, pro/src/screens/Offers/Offers.tsx, pro/src/ui-kit/Banners/LinkNodes/LinkNodes.tsx, pro/src/ui-kit/form/SelectAutoComplete/SelectAutocomplete.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30979
- MAJ de prettier + fix des problèmes
=> (PC-30979)[PRO] bump: update prettier + fix new issues.

api/src/pcapi/core/offers/repository.py, api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31143
=> (PC-31143)[PRO] feat: Add draft collective offers to query

pro/src/components/IndividualOfferForm/OfferLocation/OfferLocation.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/Venue.tsx, pro/src/components/IndividualOfferForm/utils/resetAddressFields.ts, pro/src/repository/__specs__/venuesService.spec.ts, pro/src/repository/venuesService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31135
=> (PC-31135)[PRO] feat: Displays venue OA in offer creation

pro/src/components/ArchiveConfirmationModal/utils/__specs__/canArchiveCollectiveOffer.spec.ts, pro/src/components/ArchiveConfirmationModal/utils/canArchiveCollectiveOffer.ts, pro/src/hooks/__specs__/useOfferEditionURL.spec.tsx, pro/src/hooks/useOfferEditionURL.ts, pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31145
Ajouter les actions possibles pour les offres en statut brouillon
=> (PC-31145)[PRO] feat: action possible for draft offer in collective list

pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx
=> (PC-31204)[PRO] fix: re-order final step offer creation buttons

pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31258
=> (PC-31258)[PRO] fix: Change venue label

api/src/pcapi/core/finance/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31227
Split de la query qui partait en timeout. Testé en staging contre le batch 2065 les résultats (ordonnés) étaient identiques.
=> (PC-31227)[API] fix: split generate invoice query to avoid timeout

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ne plus générer de factures à 0€ (sans remboursements ni contributions offreur)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31011
=> (PC-31011)[BO] fix: Finance don't generate invoices if having only pricings with 0€ revenue and 0€ reimbursements

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31246
=> (PC-31246)[API] ci: make migrations work when cluster is under load

pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.module.scss, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/Subcategories/Subcategories.tsx, pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.module.scss, pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/constants.ts, pro/src/screens/IndividualOffer/DetailsScreen/types.ts, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
…tion
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30897
activer le ff WIP_SUGGESTED_SUBCATEGORIES & WIP_SPLIT_OFFER
=> (PC-30897)[PRO] feat: add subcategory suggestion radios to offer creation

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31267
=>  (PC-31267)[BO] fix: fix individual booking validation error messages

.github/workflows/dev_on_workflow_deploy.yml
=> (BSR)[API] ci: fix post-migration running pre-migrations

pro/src/pages/CollectiveOffers/CollectiveOffers.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/Offers/OffersRoute.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31298
=> (PC-31298)[PRO] fix: back button on pages Offers & Reimbursement

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/templates/offer/confirm_stock_price_change.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30508
=> Pc 30508 rpa change stock price percent

api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31318
=> (PC-31318)[API] fix: handle legacy activity serialization

pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31258
=> (PC-31258)[PRO] feat: Change venue position for Summary page

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30642
=> (PC-30642)[BO] feat: use atomic in multiple offers routes

api/src/pcapi/routes/backoffice/offer_price_limitation_rules/blueprint.py, api/src/pcapi/routes/backoffice/offer_validation_rules/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31339
=> Pc 31339 rpa atomic part7

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/validation/models/offer.py, pro/src/screens/IndividualOffer/PriceCategoriesScreen/__specs__/PriceCategories.submit.spec.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/form/submitToApi.ts, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/submitToApi.ts
…is not valid
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31253
=> (PC-31253)[API|PRO] feat: display virtual without url error message

pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/screens/IndividualOffer/UsefulInformationsSummaryScreen/UsefulInformationsSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31337
=> (PC-31337)[PRO] fix: swap informations on summary

.githooks/pre-commit
Ajout d'un pre-commit check pour vérifier que les modifications apportées à la documentation ne cassent pas sa génération.
=> (BSR)[API] feat: add pre-commit check for API documentation

api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/native/v1/banner_test.py, api/tests/routes/native/v1/favorites_test.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/native/v1/offers_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31324
=> PC-31324 add assert num queries in native routes

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240806T182701_f189cd721831_add_cancellationauthor_for_booking.py, api/src/pcapi/alembic/versions/20240806T183121_a838739fcc02_add_cancellationauthor_for_collective_booking.py, api/src/pcapi/alembic/versions/20240807T141040_b0b1f2a95d61_add_cancellationauthor_to_collective_booking_foreignkey.py, api/src/pcapi/alembic/versions/20240808T081801_84359b3cc978_add_cancellationauthor_to_collective_booking_foreignkey.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/accounts/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/collective_bookings.html, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
…
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30509
Ce ticket a été refait et le code a été copier coller à partir de ce ticket https://github.com/pass-culture/pass-culture-main/pull/13088
Seul le processus de migration a été modifié - un second ticket doit etre fait pour finaliser la migration une fois ce ticket approuvé.
=> (PC-30509)[BO] feat: Cancellation reason for booking and collective booking display user informations if done by BOuser or pro -2

api/tests/routes/saml/educonnect_test.py
Fix the test by computing the user's birth date instead of using an absolute date
=> (BSR)[ADAGE] fix: educonnect test should not depend on abs date

api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offerers/forms.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31326
=> (PC-31326)[BO] fix: rejection reason labels

api/poetry.lock, api/pyproject.toml
downgrade types-redis qui semble causer des soucis avec rq
=> (BSR)[API] fix: downgrade types-redis to a known good version

api/src/pcapi/workers/worker.py
=> (BSR)[API] chore: run rq worker on debug

api/src/pcapi/workers/worker.py
This reverts commit 9309d2480be414510e6b58cf5d63ec46896ef7de.
=> Revert "(BSR)[API] chore: run rq worker on debug"

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240819T121553_d3e56f793b31_drop_offerer_rejection_reason.py, api/src/pcapi/core/mails/transactional/pro/new_offerer_validation.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/tests/core/mails/transactional/pro/new_offerer_validation_test.py, api/tests/core/offerers/test_api.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31367
=> (PC-31367)[API] chore: drop useless column offerer.rejectionReason

api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offerers/tasks.py, api/src/pcapi/routes/backoffice/filters.py, api/tests/core/offerers/test_tasks.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31362
=> (PC-31362)[API] fix: offerer rejection reason for closed SIREN

pro/src/screens/Offers/Offers.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29140
=> (PC-29140)[PRO] fix: Adds role=status on actions bar

api/src/pcapi/connectors/serialization/acceslibre_serializers.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/serialization/base.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/post_draft_offer_test.py
*Note*: [nommage] j'ai modifié un `from_orm` qui n'avait pas trop de sens
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31269
=> (PC-31269)[API] fix: offer accessibility when venue is sync with acceslibre

api/src/pcapi/workers/worker.py
Se départir d'une boucle `while` désormais inutile grâce à https://github.com/rq/rq/pull/1387 
RQ fera de nouvelles tentatives de connexion à redis après 1, 2, 4, 8 16, 32, 60, 60... secondes
=> (BSR)[API] refactor: rely on rq mechanism for connection failures

api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_repository.py, pro/src/apiClient/v1/models/CollectiveOfferDisplayedStatus.ts, pro/src/screens/Offers/SearchFilters/CollectiveSearchFilters.tsx, pro/src/utils/translate.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31144
=> (PC-31144)[API/PRO] feat: add draft status to collective search filter

pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.tsx, pro/src/components/IndividualOfferNavigation/__specs__/IndividualOfferNavigation.spec.tsx, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31209
=> (PC-31209)[PRO] fix: Stepper stocks useful information

api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_product_by_ean_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetProductInformations.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ajouter un endpoint afin de récupérer les information produit à partir du code EAN
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31216
=> (PC-31216)[API]feat: add endpoint get product by EAN

api/src/pcapi/core/offers/api.py, api/tests/routes/pro/patch_collective_offers_archive_test.py, api/tests/routes/pro/patch_collective_offers_template_archive_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31268
=> (PC-31268)[API] feat: allow draft collective offers to be archived

api/src/pcapi/utils/sentry.py
=> (BSR)[API] fix: typo in sentry filter function

api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/pro/blueprint.py, api/src/pcapi/routes/backoffice/pro/forms.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/pro/users.py, api/src/pcapi/settings.py, api/src/pcapi/utils/urls.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_test.py, api/tests/routes/backoffice/pro_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30799
=> (PC-30799)[BO] feat: prepare connect as generalisation

pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/utils/filterCategories/__specs__/filterCategories.spec.ts, pro/src/screens/IndividualOffer/InformationsScreen/utils/filterCategories/filterCategories.ts, pro/src/screens/OfferType/OfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31417
=> (PC-31417)[PRO] feat: Update hub for subcategories

pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31425
=> (PC-31425)[PRO] feat: Handle suggested categories unfilled error

api/src/pcapi/routes/native/v1/reaction.py, api/tests/routes/native/v1/reaction_test.py
Remonter le bon type pour les images sur la route /native/v1/reaction/available
=> (BSR)[API] fix: fix available reaction offer image response

pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31456
=> (PC-31456)[PRO] fix: show edition links when navigating to collective edition page

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31281
=> (PC-31281)[PRO] feat: add WIP_EAN_CREATION feature flag

api/src/pcapi/core/external/subcategory_suggestion_backends/subcategory_suggestion.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31435
=> (PC-31435)[API] feat: add is_virtual to post for category suggestion

pro/src/components/AddressManual/AddressManual.spec.tsx, pro/src/components/IndividualOfferForm/OfferLocation/OfferLocation.tsx, pro/src/components/IndividualOfferForm/OfferLocation/validationSchema.ts, pro/src/components/IndividualOfferForm/types.ts, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/validationSchema.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/types.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/utils.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/validationSchema.ts
=> (PC-31131)[PRO] feat: OA selection in new split offer.

pro/src/hooks/useOfferWizardMode.ts, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31427
=> (PC-31427)[PRO] fix: Handle modification update toaster

.github/pull_request_template.md
Ticket Jira (ou description si BSR) : Add checkbox for route page in pull request template
=> (BSR)[PRO] docs: Add checkbox for route page in pull request template

pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31502
**Objectif**
Correction d'un import manquant de `GetIndividualOfferResponseModel ` qui casse la ci
=> (PC-31502)[PRO] fix: Fix import of GetIndividualOfferResponseModel.

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/templates/accounts/search.html, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31410
=> (PC-31410)[BO] feat: search accounts by multiple emails

api/src/pcapi/repository/__init__.py
ajout d'une documentation minimal sur @atomic
=> (BSR)[API] docs: add minimal documentation for @atomic

api/src/pcapi/routes/public/booking_token/v2/serialization.py, pro/src/pages/Desk/BookingDetails.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30687
=> (PC-30867)[PRO|API] display ean in desk

api/documentation/docs/tutorials/create-a-collective-offer.md, api/src/pcapi/routes/public/documentation_constants/fields.py, api/tests/routes/public/expected_openapi.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31336
Divers petites correction dans les examples. Le but est que le JSON d'exemple généré automatiquement soit utilisable en intégration.
=> (PC-31336)[DOC] fix: public api: fix examples

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240821T125341_869f0d3be788_create_table_gdpr_user_anonymization.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/constants.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/repository/clean_database.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31164
=> Pc 31164 rpa anonymize under 21

api/tests/routes/pro/get_offerers_bank_accounts_test.py, api/tests/routes/pro/get_offerers_names_test.py, api/tests/routes/pro/get_offers_music_genres_test.py, api/tests/routes/pro/get_offers_test.py, api/tests/routes/pro/get_providers_by_venue_test.py, api/tests/routes/pro/get_reimbursements_csv_by_invoices_test.py, api/tests/routes/pro/get_reimbursements_csv_test.py, api/tests/routes/pro/get_stats_dashboard_url_test.py, api/tests/routes/pro/get_stocks_stats_test.py, api/tests/routes/pro/get_stocks_test.py, api/tests/routes/pro/get_suggested_subcategories_test.py, api/tests/routes/pro/get_user_email_token_test.py, api/tests/routes/pro/get_user_has_collective_bookings_test.py, api/tests/routes/pro/get_user_profile_test.py, api/tests/routes/pro/get_user_token_test.py, api/tests/routes/pro/get_venue_labels_test.py, api/tests/routes/pro/get_venue_providers_test.py, api/tests/routes/pro/get_venue_test.py, api/tests/routes/pro/get_venue_types_test.py, api/tests/routes/pro/get_venues_educational_status_test.py, api/tests/routes/pro/get_venues_of_offerer_from_siret.py, api/tests/routes/pro/get_venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31325
=> (PC-31325)[API] chore: add assert_num_queries on pro tests routes

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31483
=> (PC-31483)[API] fix: set gtl labels only for books in Algolia

api/src/pcapi/algolia_settings_offers.json
=> (PC-31532)[ALGOLIA] Add new replica in Algolia config file

api/src/pcapi/sandboxes/scripts/creators/data/create_data_offerers_with_pro_users.py, api/src/pcapi/sandboxes/scripts/creators/data/create_data_venues.py
=> (BSR)[API] fix: sandbox data duplicate objects

pro/cypress/e2e/features/createThingIndividualOffer.feature, pro/cypress/e2e/step-definitions/createThingIndividualOffer.cy.ts, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31527
=> (PC-31527)[PRO] feat: Hide venue field and virtual venues

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/geography/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/native/v1/serialization/bookings.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30807
=> (PC-30807)[API] feat: add offer address in booking response

api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/pro/blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/pro/users.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_test.py, api/tests/routes/pro/get_connect_as_test.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31524
=> (PC-31524)[API] chore: remove WIP_CONNECT_AS feature flag

api/.env.development, api/.env.testauto, api/src/pcapi/core/mails/models.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/settings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31540
=> (PC-31540)[API] feat: use homologation address for reminder email

api/src/pcapi/core/external/subcategory_suggestion_backends/subcategory_suggestion.py, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/InformationsScreen/utils/filterCategories/__specs__/filterCategories.spec.ts, pro/src/screens/IndividualOffer/InformationsScreen/utils/filterCategories/filterCategories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31529
=> (PC-31529)[API] revert: do not filter subcategories by isVirtual

pro/src/screens/SignupJourneyForm/Welcome/Welcome.module.scss, pro/src/screens/SignupJourneyForm/Welcome/Welcome.tsx, pro/src/styles/mixins/_fonts-legacy.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31440
**Objectif**
Remplacer la typo du sous-titre de la première étape du parcours d'inscription pour homogénéiser avec le reste. On a aujoutd'hui une font-size de title3 avec une font-weight de body, validé avec Marion qu'on passe sur une font-size de body aussi.
avant/après
=> (PC-31440)[PRO] feat: Remove regular legacy typo.

api/src/pcapi/routes/backoffice/templates/offer/details.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31523
=> (PC-31523)[BO] fix: display of offer details on small screens

pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31556
=> (PC-31556)[PRO] Add banner for physical offer when no venue has been created

api/tests/core/external/subcategory_suggestion_test.py
=> (BSR)[API] chore: clean suggestion

api/src/pcapi/core/offerers/schemas.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/schemas.py, api/src/pcapi/routes/serialization/offers_serialize.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/AddressBodyModel.ts, pro/src/apiClient/v1/models/PatchOfferBodyModel.ts, pro/src/apiClient/v1/models/PostOfferBodyModel.ts
Juste histoire que ça soit mieux rangé
=> (BSR)[API] chore: change AddressModel to AddressBodyModel

pro/src/screens/OfferEducationalStock/__specs__/validationSchema.spec.ts
=> (BSR)[PRO] test: Correct issue with a date

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31244
=> (PC-31244)[API] feat: recredit underage users of all their missing recredits

api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/core/educational/test_models.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_collective_offer_template_test.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py, pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts, pro/src/utils/collectiveApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30578
=> (PC-30578)[PRO] feat: Add a displayedStatus attribute on collective_offer

pro/src/components/MultiDownloadButtonsModal/MultiDownloadButtonsModal.tsx, pro/src/pages/Bookings/BookingsRecap.scss, pro/src/screens/Bookings/BookingsRecapTable/Filters/FilterByOmniSearch.module.scss, pro/src/screens/Bookings/PreFilters/PreFilters.module.scss, pro/src/screens/Bookings/PreFilters/PreFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31587
https://github.com/user-attachments/assets/6aa7feb4-9354-43a5-acdd-60041a472523
> [!NOTE]
> Le filtre suivant devant être retravaillé par EAC, le responsive n'a pas été corrigé dessus.
> ![image](https://github.com/user-attachments/assets/94e131cf-1538-4681-a39a-d0878cbed02a)
=> (PC-31587)[PRO] fix: Makes reservations filters responsive

pro/src/screens/IndividualOffersScreen/__specs__/IndividualOffersScreen.spec.tsx
=> (BSR)[PRO] test: Add unit tests for filtering individual offers

pro/src/screens/IndividualOffersScreen/IndividualOffersSearchFilters/IndividualOffersSearchFilters.module.scss, pro/src/screens/IndividualOffersScreen/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31208
=> (PC-31208)[PRO] fix: adapt creation mode filter

api/src/pcapi/core/offers/validation.py, api/tests/routes/pro/post_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31634
=> (PC-31634)[API] fix: Broken free product stock creation

pro/src/ui-kit/Button/ButtonLink.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31636
Fix le téléchargement de l'aide sur l'iframe adage
=> (PC-31636)[PRO] fix: bug download adage help link

pc
[pgcli](https://www.pgcli.com) offer a good DX to interact with db. This is a good alternative to psql
=> (BSR)[API] doc: Commenting pgcli command to launch pgcli with the `pc` script

pro/src/pages/Home/Venues/__specs__/VenueList.spec.tsx, pro/src/screens/CollectiveOfferVisibility/CollectiveOfferVisibility.tsx, pro/src/screens/CollectiveOfferVisibility/__specs__/CollectiveOfferVisibility.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx, pro/src/screens/OfferEducational/__specs__/validationSchema.spec.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31585
=> (PC-31585)[PRO] test: add tests

pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31576
=> (PC-31576)[PRO] fix: Compare offerers by ID instead of name

pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31613
=> (PC-31613)[PRO] fix: typo in Summary
