- api/src/pcapi/sandboxes/scripts/creators/e2e/create_e2e_event_offers.py
- api/src/pcapi/sandboxes/scripts/creators/e2e/create_e2e_thing_offers.py
- pro/cypress/e2e/features/searchIndividualOffer.feature
Pour éviter certains échecs avec la sandbox qui ne génère pas exactement les mêmes données, on simplifie ici la création des offres pour (peut-être) éviter les échecs sur searchIndividualOffer comme [ici](https://cloud.cypress.io/projects/rit5sb/runs/637)
> (BSR)[PRO] test: may fix random list of offers modulo-ed

- api/src/pcapi/core/mails/transactional/pro/offer_validation_to_pro.py
- api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31126
Suppression de l'information "heure de publication" dans les informations envoyées à Brevo lors de la validation d'une offre
> (PC-31126)[API]feat: remove time from publication date info send to Brevo

- api/src/pcapi/core/history/models.py
- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/src/pcapi/routes/backoffice/templates/accounts/get/general.html
- api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31161
Un bouton est accessible au utilisateur possédant les droit MANAGE USER ACCOUNT
au click sur le bouton un formulaire apparait, le formulaire n'est présent que pour une raison de sécurité ( éviter les missclick ) 
Lorsque l'on confirme un message flash est envoyé et le mot de passe de l'utilisateur en question est modifié par un mot de passe aléatoire et hashé ( afin de le forcer a reinitialiser son mot de passe )
un exemple de changement de mot de passe aleatoire
un action history est envoyé : 
- CI - verte 
CAS 0 : test du bouton avec les bon droits
CAS 1 : 
LORSQUE
je suis sur la page d'un utilisateur et j'ai les droits …
> (PC-31161)[BO] feat: FRAUD button to unvalidate user password

- pro/.storybook/preview-body.html
- pro/.storybook/preview.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31590
**Objectif**
Corriger le style des dialogs dans le storybook.
Le pb est que le `preview-body.html` ne laisse pas vraiment modifier les attributs du body, mais ajoute une div dans le body de la preview. Les Portals des dialogs étant envoyés directement sous le body, ils sont siblings de la div root ajoutée. On dirait qu'on est obligés de modifier les attributs du body en JS.
Le avant/après :
> (PC-31590)[PRO] feat: Fix storybook dialog theme.

- pro/src/pages/Home/Offerers/OffererDetails.tsx
- pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
- pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx
- pro/src/ui-kit/Button/ButtonLink.tsx
- pro/src/ui-kit/Button/__specs__/ButtonLink.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31589
> (PC-31589)[PRO] feat: button link should not be disabled

- api/src/pcapi/routes/public/collective/__init__.py
- api/src/pcapi/routes/public/collective/endpoints/simulate_adage_steps/bookings.py
- api/src/pcapi/routes/public/collective/endpoints/simulate_adage_steps/errors.py
- api/src/pcapi/routes/public/collective/endpoints/simulate_adage_steps/utils.py
- api/src/pcapi/routes/public/documentation_constants/http_responses.py
- api/src/pcapi/routes/public/documentation_constants/tags.py
- api/tests/routes/public/collective/endpoints/simulate_adage_steps/test_bookings.py
- api/tests/routes/public/expected_openapi.json
- api/tests/routes/public/helpers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31307
Ajout d'une nouvelle route (d'autres arrivent) qui permet de confirmer une réservation collective.
Le but est de permettre de simuler les différents parcours possibles d'une réservation collective lorsqu'il n'y a pas de plateforme Adage disponible dans un environnement donné (par exemple en intégration).
Cette fonctionnalité est donc logiquement bloquée en production. Et maintenue dans les autres environnements à des fins de validation et de test.
> (PC-31307)[API] feat: simulate adage actions: confirm booking

- pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx
- pro/src/pages/Offers/OffersTable/Cells/__specs__/CollectiveActionsCells.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31508
Bug: on ne peut plus dupliquer les offres réservables et le bouton de duplication apparaît 2 fois pour les offres vitrines (dupliquer + créer une offre réservable)
Fix: on peut dupliquer n'importe quelle offre tant qu'elle n'est pas au statut brouillon.
> (PC-31508)[PRO] fix collective offers duplication bug

- pro/src/core/FirebaseEvents/constants.ts
- pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31510
Ajout d'un tracker sur le bouton modifier depuis la liste des offres collectives
> (PC-31510)[PRO] feat: add tracker on collective offer edit button

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/exceptions.py
- api/tests/core/offers/test_api.py
règles métier : 
lorsque le FF WIP_SUGGESTED_SUBCATEGORIES est activé
- si on choisi une sous-catégorie numérique, on doit utiliser la venue virtuelle associée à l'offerer 
- si aucune venue numérique n'est associée au lieu -> pas traité car 3 cas en prod
- si on n'a pas de venue physique et qu'on choisi une sous-catégorie numérique -> géré côté front, pas de back à faire
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31528
> (PC-31528)[API] feat: use virtual venue on online offer creation

- pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31511
**Objectif**
Le bouton "Télécharger l'aide" ne télécharge pas le fichier pptx dans le header de la page de recherche ADAGE. Cette PR corrige ça en s'assurant que quand on est dans l'iframe, le bouton se télécharge dans la page parente (ADAGE) et pas dans l'iframe.
A tester dans une iframe ADAGE (et pas en standalone sinon l'url ne peut pas être construite).
> (PC-31511)[PRO] fix: Open the help link file in the topmost frame.

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20240902T142336_63fa42fd8352_drop_unique_constraint_on_stock_idatproviders.py
- api/src/pcapi/core/offers/models.py
`stock.idAtProviders` is now editable through the public API so `idAtProviders` cannot be unique anymore (two providers can have two stocks with the same id). The unique constraint is now on the pair (`idAtProviders`, `offerId`)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31275
> (PC-31275)[API] feat: drop unique constraint on `stock.idAtProviders`

- pro/src/screens/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.module.scss
- pro/src/screens/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31614
**Objectif**
Corriger la ci. La suppression du composant `Titles` était basé sur le master d'avant l'ajout de la page des offres vitrines qui contient un `<Titles>` et j'ai pas relancé la ci de la PR avant de merge 😢
> (PC-31614)[PRO] feat: Remove Titles use to fix ci.

- pro/src/pages/VenueSettings/VenueProvidersManager/AddVenueProviderButton.tsx
- pro/src/pages/VenueSettings/VenueProvidersManager/OffersSynchronization.tsx
- pro/src/pages/VenueSettings/VenueProvidersManager/__specs__/AddVenueProviderButton.spec.tsx
To prevent concurrent synchronisations from different providers
Ticket Jira : https://passculture.atlassian.net/browse/PC-31600
> (PC-31600)[PRO] feat: filter out integrated providers from venue settings options when the venue is already linked to a integrated provider

- pro/cypress/e2e/features/searchIndividualOffer.feature
Ma précédente tentative de tacler le problème de sandbox ayant ou pas une "Offer 1922" n'a pas été concluant puisqu'on a encore eu un échec récemment. Voir sur [Cypress Cloud](https://cloud.cypress.io/projects/rit5sb/runs/675/test-results/c89649d8-7a6e-4ce9-886f-bc978466e252?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22features%2FsearchIndividualOffer.feature%22%2C%22value%22%3A%22%5B%5C%2222ae16bd-6ad2-4feb-b40b-06bf2728559c%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)
Cette fois je propose de chercher avec une autre structure, donc une autre liste d'offres en croisant les doigts que ça passe …
> (BSR)[PRO] test: search other data in offer list of an offerer

- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/CollectiveOffersActionsBar.tsx
- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/__specs__/CollectiveOffersActionsBar.spec.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/IndividualOffersActionsBar.tsx
- pro/src/screens/CollectiveOffersScreen/CollectiveOffersScreen.tsx
- pro/src/screens/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31546
**Objectif**
- N'utiliser que des toaster de notif success dans la liste des offres à la place des "information".
- Aligner tous les fonctionnements de bulk edit collectifs pour que quand on applique une action, les offres sont désélectionnées 
- Aligner tous les fonctionnements de bulk edit collectifs pour que quand on applique une action, les statuts des offres modifiées changent en temps réel
- Corriger un message d'erreur "offres archivée" -> "offres archivées"
Et au passage Agathe a demandé de passer les statuts de notif à succès aussi pour les offres indiv (voir 2e commit)
> Pc 31546 collective bulk edit uncheck

- pro/src/pages/IndividualOfferWizard/Stocks/__specs__/Stocks.spec.tsx
- pro/src/screens/IndividualOffer/StocksThing/StockThingFormActions/StockThingFormActions.module.scss
- pro/src/screens/IndividualOffer/StocksThing/StockThingFormActions/StockThingFormActions.tsx
- pro/src/screens/IndividualOffer/StocksThing/StockThingFormActions/__specs__/StockThingFormActions.spec.tsx
- pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx
- pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx
- pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx
- pro/src/screens/OfferEducational/OfferEducationalForm/FormAccessibility/FormAccessibility.tsx
- pro/src/screens/OfferEducational/OfferEducationalForm/FormContactTemplate/FormContactTemplate.tsx
- pro/src/screens/OfferEducational/OfferEducationalForm/FormContactTemplate/FormContactTemplateCustomForm/FormContactTemplateCustomForm.tsx
- pro/src/ui-kit/form/Checkbox/Checkbox.tsx
- pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.tsx
- pro/src/ui-kit/form/CheckboxGroup/CheckboxGroupItem.tsx
- pro/src/ui-kit/form/RadioButton/RadioButton.tsx
- pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
- pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.tsx
- pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31591
- Modification du composant `FieldSetLayout` de façon à faire sauter la déclaration `aria-live="assertive"` qui n’est pas très efficace pour relayer l’erreur au niveau des inputs entourés par le <fieldset>.
- Avec le aria-live en assertive, l’erreur est annoncée 1 seule fois quand elle apparaît dans le DOM.
- Il n’y a pas d’association avec les champs marqués en erreur.
- Si l’erreur est levée une fois et que l’user se balade dans le formulaire avant de retourner sur les checkbox, alors l’erreur n’est pas rappelée.
- Cette modification permet de corriger ces points en exploitant le `aria-describedby`.
- Doublon d’ids sur les <fieldset>. Voir FieldSetLayout, id / aria-labelledby inutile en présence de …
> (PC-31591)[PRO] fix: <fieldset> a11y improvements + indiv. offer creation "Stock" action buttons html

- api/src/pcapi/core/offers/validation.py
- api/tests/routes/public/individual_offers/v1/post_product_test.py
As of today, all offers do not have their OffererAddress. In order for the users to modify older offers, we need to let them update physical offers that do not have OffererAddress associated.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31638
> (PC-31638)[PRO] fix: soften rules to edit legacy offers

- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31604
A présent lorsque l'on a deja anonymisé un utilisateur de plus de 21 ans, le bouton anonymisé aura disparu pour des raisons évidente de clarté: 
- CI - verte 
c'est du front aucun test ( voir image) 
- auteur du ticket -> Ok
- nombre de commit -> Ok 
- refresh de la page github ->  OK
> (PC-31604)[BO] fix: when user is already anonymized button to anonymize should not appear

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20240903T113527_8523f3e2d7d6_add_idatprovider_in_price_category.py
- api/src/pcapi/alembic/versions/20240903T114208_404b3075d1a4_add_unique_index_on_price_category_idatprovider.py
- api/src/pcapi/core/offers/models.py
Add unique index on `PriceCategory` values couple (`idAtProvider`, `offerId`). This index will be transformed into a unique constraint in a later migration
Ticket Jira : https://passculture.atlassian.net/browse/PC-31395
> (PC-31395)[API] feat: add `idAtProvider` in `PriceCategory`

- pro/src/pages/VenueSettings/VenueSettings.tsx
- pro/src/pages/VenueSettings/VenueSettingsForm.tsx
- pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
- pro/src/pages/VenueSettings/__specs__/VenueSettingsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30946
> (PC-30946)[PRO] feat: Adds warning popup when updating a venue address that have offers

- pro/src/components/Dialog/Dialog/Dialog.tsx
Afin de corriger l'erreur console survenant avec l'apparition d'une modale `<ConfirmDialog>`
PR ouverte aux discussions (cf. code) car cela implique d'utiliser un `<h2>` au lieu d'un `<h1>`
> (BSR)[PRO] fix: Remove missing <DialogTitle> alert on modal display

- pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
Il arrive parfois qu'un test `signupJourney` échoue (6% d'échecs). Ici par exemple: https://cloud.cypress.io/projects/rit5sb/runs/646/test-results/7b41924c-5204-473b-a998-f6933c8b9fd7/replay
Après discussion/analyse avec les devs Back, on a un comportement inexpliqué qui fait qu'on peut avoir la même requête interceptée 2 fois par Cypress, alors qu'elle semble bien être envoyée qu'une seule fois!
Cette PR est là pour proposer une petite modification sans être assuré que ça résolve le problème. Au pire ça ne change rien, au mieux ça corrige! Donc tentons:
- ajout de `times: 1` pour n'intercepter qu'une seule requête
- `wait` juste après le `click()`et plus dans un autre bloc cucumber. Qui sait l'état de fraicheur du 🥒  ?
> (BSR)[PRO] test: only intercept one create offer

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/schemas.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/core/search/__init__.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/src/pcapi/sandboxes/scripts/creators/data/create_data_event_occurrences.py
- api/src/pcapi/sandboxes/scripts/creators/data/create_data_event_stocks.py
- api/src/pcapi/sandboxes/scripts/creators/e2e/create_e2e_event_occurrences.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_occurrences.py
- api/src/pcapi/validation/routes/offers.py
- api/tests/core/offers/test_schemas.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/post_draft_offer_test.py
- pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
- pro/src/apiClient/v1/models/GetIndividualOfferWithAddressResponseModel.ts
- pro/src/apiClient/v1/models/PostDraftOfferBodyModel.ts
Ticket Jira : https://passculture.atlassian.net/browse/PC-31217
Ajout de validation lors de la création et mise à jour d'offre draft. Le code EAN devient obligatoire lorsque la venue est un disquaire et que le produit est un CD ou vinyle.
Il n'est pas possible de mettre à jour le produit d'une offre (et donc le code EAN dans les extra data non plus)
> (PC-31217)[API]feat: add new validation for post and patch offer regarding EAN code

- pro/cypress/e2e/step-definitions/commonSteps.cy.ts
Après connexion, on attend que la page d'accueil soit bien complètement chargée. On a eu un cas de test flaky qui changeait de structure quand la page n'était pas encore chargée, et le changement de structure n'était pas pris en compte.
On reproduit en ralentissant le réseau (`network throttling`)
Voir [ici sur Cypress Cloud](https://cloud.cypress.io/projects/rit5sb/runs/704/test-results/ddabb1bc-9da5-4998-98f4-cf8795a38879/replay)
> (BSR)[PRO] test: be sure to have homepage loaded

- api/src/pcapi/connectors/dms/api.py
https://passculture.atlassian.net/browse/PC-31668
Pas besoin de 3 tentatives d'appel à DMS pour afficher la page dans le BO.
Croisons les doigts pour que ça suffise à afficher la page, lorsque DMS ne répond pas.
Testé en console sur staging, mais il faut attendre le déploiement sur staging pour tester dans le BO.
Ça reste un « quick fix » !
> (PC-31668)[BO] fix: timeout in bank accounts details when DMS timeouts

- pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.tsx
- pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingsTable.tsx
- pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTableRow.tsx
- pro/src/screens/Bookings/BookingsRecapTable/__specs__/BookingsRecapTable.spec.tsx
Ticket Jira (ou description si BSR) : Ajout de tests sur les tris des colonnes pour les resa collectives
> (BSR)[PRO] test: Add tests for sorting collective bookings columns

- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/post_draft_offer_test.py
- pro/cypress/e2e/step-definitions/createEventIndividualOffer.cy.ts
This was done in the front before the FF WIP_SUGGESTED_SUBCATEGORIES, fixed it by doing it in the back with the FF WIP_SUGGESTED_SUBCATEGORIES activated.
Ticket Jira : https://passculture.atlassian.net/browse/PC-31618
> (PC-31618)[API]fix: isDuo of offer event that can be duo are set to True by default

- pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.module.scss
- pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.spec.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30915
- Désormais si la feature "Suggestions de sous-catégories" est activée, alors on affiche toujours le composant et son titre "Catégories suggérées pour votre offre :" en état EMPTY, avec un message complémentaire "Veuillez renseigner un titre ou une description".
- Si au premier appel, l'API est en erreur alors on affiche seulement le radio button "Autre" préselectionné. Sur les futurs appels, les suggestions pourraient apparaître en complément si l'API répond à nouveau.
- Si l'API retombe en erreur, alors les suggestions correspondent au dernier appel OK.
> (PC-30915)[PRO] fix: support subcat suggestion API error

- pro/cypress/e2e/step-definitions/financialManagement.cy.ts
Ajout d'attentes et étapes de vérifications pour que le nouveau test `financialManagement` ajouté dans cette [PR](https://github.com/pass-culture/pass-culture-main/pull/13982)  n'échoue plus
> (BSR)[PRO] test: fix new financialManagement test that fails

- api/.env.integration
- api/.env.ops
- api/.env.staging
- api/.env.testing
- api/src/pcapi/connectors/recommendation.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31643
Theses configs will now be defined in the deployment repo for ehp : https://github.com/pass-culture/pass-culture-deployment/pull/455/commits/5d848910e109a689a20cec8c99a347df10165387
> (PC-31643)[API] chore: change recommendation endpoints urls for ehp

- pro/cypress/cypress.config.ts
- pro/cypress/support/e2e.ts
- pro/package.json
- pro/yarn.lock
Ajout du plugin fail-fast. Avec celui-ci, dès que 3 scénarios auront échoué alors tous les tests suivants seront skipper. Cela évite d'avoir des runs de tests e2e tous pétés qui tournent pendant 30 minutes (et des jobs bloquant les autres) [comme ici par exemple](https://github.com/pass-culture/pass-culture-main/actions/runs/10703065721/job/29673789279)
> (BSR)[PRO] test: add fail-fast plugin

- api/src/pcapi/routes/auth/discord.py
- api/src/pcapi/routes/auth/templates/discord_retry.html
- api/tests/routes/auth/discord_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31571
Screen video de succès (réseau lent, mais tout ok):
https://github.com/user-attachments/assets/af29b767-1aa6-4d71-8952-6eca856b43ef
Screen vidéo de comment on gère une erreur (ajout d'un raise à la main dans le code)
https://github.com/user-attachments/assets/02259ad5-4f09-448a-8ce9-12156ca87b9e
> (PC-31571)[API] fix: improve discord login by moving the main logic in a success page

- api/src/pcapi/routes/backoffice/forms/fields.py
- api/src/pcapi/routes/backoffice/templates/components/forms/date_field.html
- api/tests/routes/backoffice/collective_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31616
à présent pour collective booking ET individual booking, mettre en date 01-01-0001 devrait mettre un message flash au lieu d'une 500.
> (PC-31616)[BO] fix: fix 500 when searching by event_from_date 01-01-0001 in booking and collective booking

- api/src/pcapi/connectors/api_adresse.py
- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/patch_offer_test.py
This works around a weird issue if selecting the venue's offerer address as the front will send us the venue common name as label but the OA expects a NULL/None value.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31595
> (PC-31595)[PRO] fix: ignore label if matching the venue's

- api/src/pcapi/scripts/rebuild_staging/anonymize.sql
> (BSR)[BO] fix: Set default placeholder to avoid dummys decryption errors

- scripts/pc-completion.sh
Pour bénéficier de la completion pour le script `pc` dans zsh.
> (BSR)[PRO] script: Zsh completion script for `pc` script

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/core/offers/test_api.py
Correction d'un bug lors de la mise à jour d'une offre non musical avec gtl_id (pour les offres livres par exemple). Des actions spécifiques aux offres musicales sont faites lors de la mise à jour d'offre sur condition de présence du gtl_id dans les extra_data. Ajout d'une condition pour ne pas faire cette action lorsque l'offre n'est pas concernée. 
Ticket Jira: https://passculture.atlassian.net/browse/PC-31691
Fix bug sentry https://sentry.passculture.team/organizations/sentry/issues/1618207/?project=5&referrer=jira_integration
> (PC-31691)[API]fix: modification spécifique aux offres musicales sous conditions

- api/src/pcapi/core/offers/schemas.py
- api/tests/routes/pro/patch_draft_offer_test.py
Sans le FF `WIP_EAN_CREATION`, il doit être possible d'éditer l'EAN d'une offre
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31733
> (PC-31733)[API] fix: patch draft offer must not fail with ean without FF

- pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31735
> (PC-31735)[PRO] feat: display api errors in DetailsForm

- pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx
- pro/src/ui-kit/form/TextArea/TextArea.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31734
- Les inputs “Lieu” + “Titre” + “Description” doivent avoir un aria-controls uniquement si le composant est présent dans le dom. Autrement on a l’erreur suivante : https://dequeuniversity.com/rules/axe/4.10/aria-valid-attr-value?application=AxeChrome
- “aria-controls” n’était de toute façon pas bien passé dans le textarea “Description”.
> (PC-31734)[PRO] fix: only add aria-controls=suggested-subcat when component exists in dom

- pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
Quelques petites modifications pour éviter l'échec sur signupJourney (`POST /offerers/new` qui répond bien mais Cypress n'intercepte pas la bonne réponse, peut-être en doublon)
Voir [échec suivant](https://cloud.cypress.io/projects/rit5sb/runs/747/overview/2a840616-8a4d-40e0-abf4-f99cdac3d5aa/replay) dont on essaye de se débarrasser
> (BSR)[PRO] test: workaround to not make flaky signupJourney fail

- api/documentation/src/pages/change-logs.md
- api/src/pcapi/routes/public/documentation_constants/fields.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/expected_openapi.json
- api/tests/routes/public/individual_offers/v1/get_eans_availability_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31345
- **Change logs**
- **REST API**
- New endpoint 
- Existing endpoint (in red)
> (PC-31345)[API] feat: add new endpoint in public API to check EANs availability for bulk upsert

- api/src/pcapi/core/educational/api/offer.py
- api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31555
Bug : la variable institution était mal identée.
Fix : inverser la condition (`if value is None -> break`) pour gagner en clarté.
> (PC-31555)[API] fix: public api: wrong identation error

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/bookings/utils.py
- api/src/pcapi/core/educational/repository.py
- api/tests/core/bookings/test_repository.py
- api/tests/routes/backoffice/collective_bookings_test.py
- api/tests/routes/backoffice/individual_bookings_test.py
- api/tests/routes/backoffice/offers_test.py
- api/tests/routes/pro/get_all_bookings_test.py
- api/tests/routes/pro/get_collective_booking_csv_test.py
- api/tests/routes/pro/get_collective_booking_excel_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30552
> (PC-30552)[API] feat: Use OA department code as source for compute TZ

- pro/src/components/CollectiveOfferSummary/components/CollectiveOfferDateSection.tsx
- pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/adageOfferDates.ts
- pro/src/pages/Offers/OffersTable/Cells/OfferEventDateCell/OfferEventDateCell.tsx
- pro/src/pages/Offers/OffersTable/Cells/OfferEventDateCell/__specs__/OfferEventDateCell.spec.tsx
- pro/src/utils/__specs__/date.spec.ts
- pro/src/utils/date.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31601
**Objectif**
Corriger l'affichage de la date dans la colonne "date de l'évènement" de la table des offres collectives.
Il y a 2 problèmes :
- Jusqu'à maintenant on affiche l'heure de l'événement et la/les dates en faisant `new Date(startDate)` qui crée un formattage de date en UTC alors que les dates des offres réservables doivent être affichées dans la timezone de la venue.
- On a la possibilité de créer une offre vitrine avec des dates de début et de fin mais sans heure précise. Auquel cas, l'api enregistre la date à minuit. Et on n'a pas d'autre indication sur l'existence d'une heure de début pour l'offre. Donc on doit vérifier si c'est pas minuit UTC pour afficher ou non l'heure.
> Pc 31601 template offer date midnight

- pro/src/styles/global/_layout.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31773
**Objectif**
Corriger l'affichage du bold sur Firefox et Safari. Ces navigateurs n'interprètent pas les `font-face` de la même manière que Chrome, et ne comprennent pas que Montserrat-Bold ayant une `font-weight` définie à 600 dans la `font-face` est une police bold (on voit dans l'onglet Style/Police de Safari que la police interprétée est Montserrat Thin (?)). 
Donc quand on applique le `font-weight: 600` de nouveau dans la mixin, le navigateur essaie de créer du bold lui-même en épaississant les glyphes de la police.
Pour éviter ça, j'ai ajouté la propriété CSS qui interdit au navigateur de prendre ce genre de liberté.
> (PC-31773)[PRO] style: Fix font-weight of bold on safari and firefox.

- pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx
Utilisation plus conforme de l'attente du loading d'un champs dans le render d'un formulaire + mock d'un API call provoquant potentiellement le problème de flaky test
c.f. https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-waitfor-to-wait-for-elements-that-can-be-queried-with-find
> (BSR)[PRO] fix: Properly wait for test form render (flaky test)

- api/src/pcapi/core/educational/api/booking.py
- api/src/pcapi/routes/public/collective/endpoints/simulate_adage_steps/bookings.py
- api/tests/routes/public/collective/endpoints/simulate_adage_steps/test_bookings.py
- api/tests/routes/public/expected_openapi.json
- api/tests/routes/public/helpers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31390
Ajout d'une route qui permet d'annuler une réservation collective, à destination de l'environnement d'intégration qui n'a pas d'équivalent Adage - ce qui empêche d'aller au-delà de la création d'une offre.
1. Ajout de quelques __fixtures__.
2. fonctions déplacées dans des modules plus appropriés (`conftest`, nouveau, pour les __fixtures__, `helpers` pour les deux __context managers__).
> (PC-31390)[API] feat: public api: adage mock: cancel booking

- pro/src/config/swrQueryKeys.ts
- pro/src/core/Offers/constants.ts
- pro/src/core/Offers/utils/serializer.ts
- pro/src/pages/Offers/OffersRoute.tsx
- pro/src/pages/Offers/__specs__/Offers.admin.spec.tsx
- pro/src/pages/Offers/__specs__/Offers.spec.tsx
- pro/src/repository/__specs__/venuesService.spec.ts
- pro/src/repository/venuesService.ts
- pro/src/screens/IndividualOffersScreen/IndividualOffersScreen.tsx
- pro/src/screens/IndividualOffersScreen/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx
- pro/src/screens/IndividualOffersScreen/__specs__/IndividualOffersScreen.spec.tsx
- pro/src/screens/IndividualOffersScreen/__specs__/IndividualOffersScreen.tracker.spec.tsx
- pro/src/utils/offererAddressFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30829
- Ajout du filtre par adresse dans les offres
> (PC-30829)[PRO] feat: OffererAddress select in offers filters.

- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/patch_collective_offers_archive_test.py
https://passculture.atlassian.net/browse/PC-31564
Permettre d'archiver une offre refusée par la fraude
> (PC-31564)[PRO] feat: allow rejected offers to be archived

- pro/src/core/FirebaseEvents/constants.ts
- pro/src/pages/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx
- pro/src/screens/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31505
Le bouton s'affiche seulement sous FF (WIP_ENABLE_COLLECTIVE_DRAFT_OFFERS)
Ajout d'un tracker pour le bouton Sauvegarder le brouillon et quitter lors de la création d'une offre collective
> (PC-31505)[PRO] feat: tracker save and quit eac button

- pro/src/screens/Bookings/BookingsRecapTable/__specs__/BookingsRecapTable.spec.tsx
> (BSR)[PRO] test: Reenabled bookingTable tests without being flaky

- api/src/pcapi/core/reactions/api.py
- api/tests/routes/native/v1/reaction_test.py
Fix [sentry error](https://sentry.passculture.team/organizations/sentry/issues/1618510/?project=5&referrer=slack) when trying to add a reaction to an unknown offer
> (BSR)[API] fix: do not fail on reaction creation if offer doesn't exists

- pro/src/components/SideNavLinks/SideNavLinks.module.scss
- pro/src/components/SideNavLinks/SideNavLinks.tsx
- pro/src/components/SideNavLinks/__specs__/SideNavLinks.spec.tsx
- pro/src/pages/CollectiveOffers/CollectiveOffers.tsx
- pro/src/pages/Offers/OffersRoute.tsx
- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTable.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersTable.tsx
- pro/src/screens/CollectiveOffersScreen/CollectiveOffersScreen.tsx
- pro/src/screens/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31764
**Objectif**
2 correctifs a11y :
- Annoncer le nombre d'offres trouvées quand on fait une recherche sur les offres indiv et collectives. Pour ça il faut que le conteneur en `role="alert"` du message à annoncer soit déjà dans le DOM avant le changement (et n'apparaisse pas au moment du changement). Il a fallu enlever le loader au niveau de la page qui semble inutile (et qui fait un rechargement de page à chaque fois qu'on fait une recherche qui est pas en cache).
- Enlever les divs entre le `ul` et les `li` des `NavLinks`
> Pc 31764 offers list role status

- pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.spec.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31285
Hotfix !
> (PC-31285)[PRO] fix: make redirection callback appear when WIP_EAN_SEARCH only

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20240912T082546_4a4fb0253a9b_update_rural_level.py
- api/src/pcapi/core/educational/models.py
- api/tests/core/educational/test_api.py
- api/tests/routes/adage_iframe/get_authenticate_test.py
- api/tests/routes/adage_iframe/playlist_test.py
- pro/src/apiClient/adage/models/InstitutionRuralLevel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31473
Le but de cette PR est de fixer la commande CRON -> `synchronise-rurality-level` 
Pour plus de contexte voir:
* https://passcultureteam.slack.com/archives/C01DXAW6YFJ/p1722253684823239
* https://passcultureteam.slack.com/archives/CQAMXPQSZ/p1722257245484799
> (PC-31473)[ADAGE] fix: use new values for rural level

- .github/workflows/dev_on_workflow_configure_live_channel_pro_generic.yml
Because of [this issue](https://github.com/firebase/firebase-tools/issues/7648) pro deployment failed. 
We try this workaround to unlock the situation
> (BSR)[PRO] fix: firebase PRO deployment

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20240911T145845_afa7af785d3a_drop_unused_index_collective_offer_lastValidationDate.py
- api/src/pcapi/alembic/versions/20240911T150554_29b3530a7eac_drop_unused_index_collective_offer_template_lastValidationDate.py
- api/src/pcapi/alembic/versions/20240911T151216_60adfaea930c_drop_unused_index_offer_lastValidationDate.py
- api/src/pcapi/alembic/versions/20240911T152012_265af0d4682c_drop_unused_index_offer_music_type.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/models/offer_mixin.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31795
> (PC-31795)[API] chore: drop unused indexes

- api/src/pcapi/routes/public/collective/serialization/offers.py
- api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31444
Bug : deux champs de début et de fin d'une offre collective sont déclarés comme optionnels alors que les validateurs considèrent qu'ils sont obligatoires (et donc présents).
Fix : modifier les validateurs pour qu'ils ne cherchent pas à vérifier quoi que ce soit s'il n'y a rien à vérifier.
> (PC-31444)[API] fix: public collective api: optional start and end datetimes

- api/src/pcapi/core/finance/models.py
- api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
- api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general_commercial_gesture.html
- api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general_overpayment.html
- api/tests/routes/backoffice/finance_test.py
- api/tests/routes/backoffice/helpers/html_parser.py
Ajout des infos batch et justificatif de remboursement dans la page incident finance
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30880
> (PC-30880)[BO] feat: Include cashflow batch's info in finance incident/commercial gesture page

- infra/pc_scripts/start_backend.sh
- pc
- scripts/pc-completion.sh
Ajout d'une commande à pc pour lancer `docker-compose up` (sans build les images)
Ajout de la doc manquante pour les commandes -proxy
> (BSR)[PRO] script: add a pc command for docker-compose up

- api/src/pcapi/core/educational/adage_backends/adage.py
- api/tests/core/educational/adage_backends/test_adage.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30592
Ajout de détail dans le message de l'exception quand l'API Adage renvoie une erreur
> (PC-30592)[ADAGE] fix: add details in adage exception message

- api/src/pcapi/core/educational/api/favorites.py
- api/src/pcapi/routes/adage_iframe/favorites.py
- api/tests/routes/adage_iframe/post_favorite_offer_test.py
- api/tests/routes/adage_iframe/post_favorite_template_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31814
Fixes this [sentry issue](https://sentry.passculture.team/organizations/sentry/issues/427587/?project=5&query=is%3Aunresolved+Error+in+repository.save&referrer=issue-stream&statsPeriod=14d&stream_index=0) . Inspired by what is done [for beneficiary favorites](https://github.com/pass-culture/pass-culture-main/blob/b127b20547139ad8d679b0278f49df24b60a2ae2/api/src/pcapi/routes/native/v1/favorites.py#L202)
> (PC-31814)[API] fix: post multiple favorite on same offer

- api/tests/routes/public/helpers.py
- api/tests/routes/public/individual_offers/v1/post_image_test.py
With `abc.abstractmethod`, if an abstract method or an abstract property was not defined in the child class, all the tests were skipped. Now instead it raises a `NotImplementError`
With `abc.abstractmethod`, if an abstract method or an abstract property was not defined in the child class, all the tests were skipped. Now instead it raises a `NotImplementError`.
**Before:**
**Now:**
> (BSR)[API] feat: remove `abc` from `PublicAPIEndpointBaseHelper` definition

- api/src/pcapi/routes/public/collective/endpoints/bookings.py
- api/src/pcapi/routes/public/collective/endpoints/categories.py
- api/src/pcapi/routes/public/collective/endpoints/domains.py
- api/src/pcapi/routes/public/collective/endpoints/educational_institutions.py
- api/src/pcapi/routes/public/collective/endpoints/national_programs.py
- api/src/pcapi/routes/public/collective/endpoints/offers.py
- api/src/pcapi/routes/public/collective/endpoints/simulate_adage_steps/bookings.py
- api/src/pcapi/routes/public/collective/endpoints/students_levels.py
- api/src/pcapi/routes/public/collective/endpoints/venues.py
- api/src/pcapi/routes/public/individual_offers/v1/bookings.py
- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/tests/routes/public/collective/endpoints/get_collective_offers_categories_test.py
- api/tests/routes/public/collective/endpoints/get_list_subcategories_test.py
- api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
- api/tests/routes/public/helpers.py
No change for old stock and booking endpoints (`/v2/stock` & `/v2/booking`). All the current endpoints requires the api key to authenticate a `provider` (and not an `offerer` like the old endpoint did)
Ticket Jira (ou description si BSR) :https://passculture.atlassian.net/browse/PC-31785
> (PC-31785)[API] feat: change `@api_key_required` for `@provider_api_key_required` in public API current endpoints

- pro/src/screens/CollectiveOfferConfirmation/CollectiveOfferConfirmation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31693
**Objectif**
Corriger l'affichage de la taille de texte du titre du callout au moment de la validation de publication d'une offre collective :
> (PC-31693)[PRO] style: Fix Callout title size.

- pro/src/components/Address/Address.tsx
- pro/src/components/IndividualOfferForm/OfferLocation/OfferLocation.module.scss
- pro/src/components/IndividualOfferForm/OfferLocation/OfferLocation.tsx
- pro/src/components/IndividualOfferForm/types.ts
- pro/src/components/OfferAppPreview/OfferAppPreview.tsx
- pro/src/components/OfferAppPreview/VenueDetails/VenueDetails.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
- pro/src/screens/IndividualOffer/InformationsScreen/__specs__/serializers.spec.ts
- pro/src/screens/IndividualOffer/InformationsScreen/serializePatchOffer.ts
- pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx
- pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.tsx
- pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
- pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx
- pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/utils.spec.ts
- pro/src/screens/IndividualOffer/UsefulInformationScreen/types.ts
- pro/src/screens/IndividualOffer/UsefulInformationScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31391
Features flags à activer :
- WIP_SPLIT_OFFER
- WIP_ENABLE_OFFER_ADDRESS
> [!NOTE]
> Pour tester en local la sauvegarde de l'adresse, il faut désactiver le connecteur de l'API adresse en modifiant la variable d'environnement suivante dans `api/.env.development`
> ```env
> # ADRESSE_BACKEND=pcapi.connectors.api_adresse.TestingBackend
> ADRESSE_BACKEND=pcapi.connectors.api_adresse.ApiAdresseBackend
> ```
> … et relancer le conteneur `pc-api`
> (PC-31391)[PRO] feat: Sauvegarde de l'adresse lors de la création/édition de l'offre

- pro/cypress/e2e/features/searchIndividualOffer.feature
Déjà 2 échecs des tests e2e à cause de la sandbox qui ne génère pas toujours les mêmes données!
Voir [ici](https://cloud.cypress.io/projects/rit5sb/runs/822/test-results/cf07fd9d-f75d-4dbd-b326-e67c685374f5/replay)
On est moins strict sur les comparaisons d'affichage pour que ça passe avec `Michel et son accordéon` et `Michel - Offre numérique`
> (BSR)[PRO] test: workaround for flaky sandbox with changing data

- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/get_product_by_ean_test.py
Suite de la PR sur la validation d'une offre. 
Une vérification d'existence d'une offre avec le même EAN est faite.
Nous faisons la vérification seulement si la structure ne possède qu'un lieux (physique) car il est impossible de connaitre le lieux choisie à cette étape du formulaire. Dans la précédente PR, le filtre sur les lieux physique a été oublié, il s'agit d'un correctif.  
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31752
> (PC-31752)[API] Filtre des lieux virtuels pour effectuer la vérification d'existence d'une offre avec un EAN.

- pro/src/pages/Offers/__specs__/Offers.admin.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31830
**Objectif**
Corriger le test sur `Offers.admin.spec.tsx` "should reset status filter when offerer filter is removed" qui échoue en local chez moi au moment de `expect(api.getOffererAddresses).toHaveBeenCalled()`
> (PC-31830)[PRO] fix: Fix Offers.admin unit test.

- api/src/pcapi/routes/backoffice/venues/blueprint.py
- api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31776
> (PC-31776)[BO] fix: do not fail to set permanent venues in batch action when one has an inconsistent SIRET

- api/documentation/docs/understanding-our-api/resources/individual-offers.md
Rajout d'un petit lien dans la documentation.
> (PC-31345)[API] feat: add link to `CheckEansAvailability` endpoint documentation in `individual-offers.md`

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/models.py
- api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31816
Ajout de la catégorie de valorisation "geste commercial" dans l'export csv invoices.
Avant :
Après :
> (PC-31816)[BO] feat: add new 'commercial gesture' pricing category in exported invoices csv

- api/src/pcapi/core/search/__init__.py
- api/tests/core/search/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31789
> (PC-31789)[API] feat: limit booking count reindexation in staging

- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31896
Liée à un problème avec les suggestions algolia qui parfois n'ont pas de formats à la génération, pour ne plus avoir de crash sur adage on corrige côté front, un autre ticket back a été créé pour investiguer si il y a encore des offres sans formats qui sont indexés sur algolia. 
Lorsqu'une suggestion n'a pas de formats, on n'affiche plus son format
Pour reproduire en testing : 
il faut faire une recherche avec 'no' pour qu'on n'affiche plus le format
pour vérifier qu'il y a toujours le format si une suggestion en a une : recherche avec 'offer'
> (PC-31896)[PRO] fix: algolia adage offer format bug

- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py
- api/tests/routes/public/collective/endpoints/adage_mock/base.py
- api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py
- api/tests/routes/public/expected_openapi.json
Travail initié par @jeremieb-pass.  (PR d'origine: https://github.com/pass-culture/pass-culture-main/pull/14148)
Tickets Jira : 
- https://passculture.atlassian.net/browse/PC-31411
- https://passculture.atlassian.net/browse/PC-31452
Ajout de deux routes mockant les comportement d'une réservation sur adage :
- une route pour mocker le remboursement
- une route pour reset le statut d'une réservation
> (PC-31411)[API] feat: Add 2 endpoint to mock adage bookings lifecycle

- pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx
- pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
- Les offres numériques ne devraient pas voir "Localisation de l'offre"
> (BSR)[PRO] fix: Do not display offer location for virtual offers.

- api/src/pcapi/routes/backoffice/offers/blueprint.py
- api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31820
> (PC-31820)[BO] fix: manage price category when editing stock in BO

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/routes/serialization/address_serialize.py
- api/tests/core/bookings/test_repository.py
- api/tests/routes/pro/get_venue_test.py
Our tests was populate with wrong data. Offers used to had OffererAddress, while this isn’t the case in reality. Moreover, the joins on the query fetching the rows wasn’t under FF.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31907
> (PC-31907)[API] fix: Export bookings csv/xlsx

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
- api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
- api/tests/core/providers/test_api.py
- api/tests/local_providers/allocine_stocks_test.py
- api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
- api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py
- api/tests/routes/pro/post_draft_offer_test.py
- api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31894
Do not save description in offer when a product is linked to this offer
> (PC-31894)[API] feat: remove description double writing

- pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
Le stub de l'appel à `https://api-adresse.data.gouv.fr/search` avait été enlevé car on observait des doublons de requêtes. Voir cette précédente PR: https://github.com/pass-culture/pass-culture-main/pull/13004
Mais aujourd'hui on a aussi eu un échec qui pourrait s'expliquer par le fait qu'on attend un appel à l'api externe qui ne répond pas et donc toute la suite est compromise. Voir l'échec sur Cypress Cloud: https://cloud.cypress.io/projects/rit5sb/runs/862/test-results/4b25df67-260d-4154-8660-fbc8f07433c9/replay
Cette PR remet ce stub qui semble indispensable (on ne doit pas faire d'appel externe depuis les tests e2e)
> (BSR)[PRO]: add again stubbing of api-adresse

- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/tests/core/educational/test_models.py
- api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/CollectiveOfferAllowedAction.ts
- pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts
- pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30781
Ajout des actions autorisées en fonction du displayedStatus dans les api collective offers
> (PC-30781)[API] feat: add allowed actions to collective offers api

- pro/src/components/IndividualOfferForm/OfferLocation/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31932
Pas d'oa pour les liens numériques
> (PC-31932)[PRO] fix: OA fields are not required for virtual offers.

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/external/attributes/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/tests/core/users/test_api.py
Prise en compte des incidents finance partiels dans le calcul du crédit des bénéficiaires
Exemple: 
Un jeune ayant :
- 1 réservation (40€) validée et remboursée à l'AC. Son status est "reimbursed"
- 1 réservation validée (33€) et remboursée à l'AC puis totalement annulée (0€). Son status est "cancelled" donc pas incluse dans le crédit du jeune
- 1 réservation validée (67€) et remboursée à l'AC puis partiellement annulée. On veut récupérer 40€ de l'AC, donc son nouveau prix est de 27€. **Son status reste "reimbursed" pas "cancelled"** 
Le crédit du jeune doit être à `300€ - 40€ - 27€ = 233€`
Dans le fonctionnement actuel, on ne prend en considération que les réservations complètement annulées il manquait le calcul des réservations dont on ne prend pas directement le montant depuis …
> (PC-31957)[API] feat: include booking with partial finance incident in the beneficiary's credits

- pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31863
- Lorsque l'on crée une offre individuelle, si on passe de "Détails" à "Informations" en cliquant sur "Enregistrer & continuer", alors l'offre devient une draft offer (une requête POST est effectuée).
- En revenant sur "Détails", on se base sur les valeurs de l'objet draft offer ainsi créé. 
- Si ce draft offer n'est pas basé sur un produit, alors on considère que la recherche EAN ne doit plus être disponible.
> (PC-31863)[PRO] fix: stop displaying EAN search when draft offer is created but not product based

- .github/workflows/dev_on_pull_request_workflow.yml
- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_tests_pro_e2e.yml
- .github/workflows/dev_on_workflow_tests_pro_e2e_migration.yml
Groupe les 2 résultats des tests avec sandbox et migration (les cas qui vont être migrés avec la Data Factory) pour fixer #14221
Ceci est important pour Cypress Cloud qui regroupera tous les résultats dans un seul run (et pas 2)
Voir https://cloud.cypress.io/projects/rit5sb/runs/902/specs
Au fur et à mesure de la migration faite par @Aliochka le premier groupe s'agrandira pendant que le second se videra
> (BSR)[PRO] test: Group in 1 run tests with sandbox and tests with Data Factory

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/patch_offer_test.py
- api/tests/routes/public/individual_offers/v1/patch_event_test.py
- pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
- pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Lors d'un `PATCH offer` et/ou `PATCH draft offer`, les `extra_data` de l'offre sont écrasées par les données renvoyées par le front. Cela entraîne la disparition de données synchronisées (avec allociné lors de l'édition du champ `isDuo` qui appelle la route `PATCH offer`) ou lorsqu'on appelle la route `PATCH Draft Offer` avec un `EAN`: 
__explications__:  le front ne renvoie pas ce champ lors de l'appel à cette route, puisqu'il ne peut pas être modifié (choix tech front). On récupère des `extraData` sans l'`EAN`. Lors de l'appel à `_format_extra_data(...)`, on écrase les `extra_data` avec les données du formulaire renvoyés par le front (donc pas les `EAN`) -> les `EAN` disparaissent des `extraData` 
On corrige en repartant des extraData existant lors du PATCH, et on fait un vrai PATCH des …
> (PC-31878)[API]fix: Mise à jour des extraData d'offres sur les conditional_fields seulement

- .github/workflows/dev_on_workflow_tests_pro_e2e.yml
- .github/workflows/dev_on_workflow_tests_pro_e2e_migration.yml
[Corrige](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example) pour n'avoir l'option "group:" uniquement sur les builds master (suite de cette [PR](https://github.com/pass-culture/pass-culture-main/pull/14257)  faisant hélas échouer les builds de branche)
Le dernier Check a tout skippé car il ne contient aucun changement dans le code PRO mais un précédent avec fausse modification est bien passé.
> (BSR)[PRO] test: no group on non-master branches for Cypress Cloud E2E tests

- pro/src/components/ArchiveConfirmationModal/ArchiveConfirmationModal.tsx
- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/CollectiveOffersActionsBar.tsx
- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/__specs__/CollectiveOffersActionsBar.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31883
Ajouter un paramètre qui renvoie les ids des offres qui ont été sélectionnées à l'EVENT d'archivage côté collectif
> (PC-31883)[PRO] feat: add params selected_offers for archivage events

- README.md
- api/README.md
- docker-compose-backend.yml
- infra/pc_scripts/logs.sh
- infra/pc_scripts/start_backend.sh
- infra/pc_scripts/test_backend.sh
- pc
Utiliser `docker compose` au lieu de `docker-compose`
> (BSR)[API] chore: User `docker compose` instead of `docker-compose`.

- api/src/pcapi/routes/adage_iframe/logs.py
- api/src/pcapi/routes/adage_iframe/serialization/logs.py
- api/tests/routes/adage_iframe/post_logs_test.py
- pro/src/apiClient/adage/models/OfferListSwitch.ts
- pro/src/apiClient/adage/models/PlaylistBody.ts
- pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSuggestions/__specs__/OffersSuggestions.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31759
Ajout d'un paramètre pour savoir si la liste par défaut et en mode mobile ou non
Sur le log du switch du mode de vue pour la liste dans la recherche sur ADAGE
> (PC-31759)[API] feat: add params to log offer list view in adage

- api/src/pcapi/routes/serialization/finance_serialize.py
- pro/src/apiClient/v1/models/ManagedVenues.ts
- pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
- pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/PricingPointDialog.tsx
- pro/src/pages/Reimbursements/BankInformations/__specs__/LinkVenuesDialog.spec.tsx
- pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx
- pro/src/utils/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31536
- Afficher le name au lieu du commonName dans le select des venues.
> (PC-31536)[PRO] feat: Display the venue name instead of the common one.

- pro/src/config/swrQueryKeys.ts
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx
- pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31829
Utilisation de swr pour la requête qui permet de récupérer les academies pour résoudre une erreur sentry 
https://sentry.passculture.team/organizations/sentry/issues/1618482/?project=2&referrer=jira_integration
> (PC-31829)[PRO] fix: useSwr for academies in adage filter academies

- pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31864
Ne plus afficher le lien qui permet de voir l'aperçu d'une offre si l'offre est réservable avec un statut archivée, garder le lien pour une offre vitrine au statut archivée
> (PC-31864)[PRO] fix: adage preview when offer is archived

- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTable.module.scss
- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTable.tsx
- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTableHead/CollectiveOffersTableHead.tsx
- pro/src/screens/CollectiveOffersScreen/CollectiveOffersScreen.module.scss
- pro/src/screens/CollectiveOffersScreen/CollectiveOffersScreen.tsx
- pro/src/screens/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.module.scss
- pro/src/screens/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
- pro/src/utils/__specs__/sortCollectiveOffers.spec.tsx
- pro/src/utils/sortCollectiveOffers.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31918
**Objectif**
Corriger le bug suivant : sur la page des offres collectives, si on va a la page 2 et qu'on filtre de manière à avoir entre 1 et 10 résultats (ex: filtrer sur le statut en attente), la table affiche le thead mais pas de contenu dans le tbody.
Pour corriger, il faut synchroniser la page active dans le hook `usePagination` avec celle qu'on passe à la fonction de redirection `applyUrlFiltersAndRedirect`. Pour ça il faut utiliser la fonction du hook de pagination `setPage` et donc faire remonter la logique le pagination dans le screen (et la logique de tri aussi puisque la pagination en dépend).
Pour la duplication c'est des pages différentes avec des systèmes de filtres qui vont diverger donc …
> Pc 31918 fix offers filter pagination

- .github/dependabot.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31950
**Objectif**
Empecher dependabot de faire les updates auto du repo design-system. 
Tant que le design system risque d'avoir des breaking changes régulièrement et est encore versionné via des tags il vaut mieux pas laisser dependabot faire les updates auto.
> (PC-31950)[PRO] ci: Ignore design-system lib in debendabot auto updates.

- pro/src/components/ArchiveConfirmationModal/ArchiveConfirmationModal.tsx
- pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx
- pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32009
Suite d'une PR qui envoyait seulement les ids des offres sélectionnées et archivé depuis l'actionbar, on le fait aussi pour envoyer l'id d'une offre archivée depuis la page de récap ou des boutons d'actions
> (PC-32009)[PRO] feat: tracker achivage params

- api/src/pcapi/routes/internal/e2e.py
BSR
Avoir plus de détails dans Cypress sur les erreurs des createurs de données
> (BSR)[API] test: display more info on api error with e2e

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/mails/transactional/finance_incidents/finance_incident_notification.py
- api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
- api/tests/core/finance/test_api.py
Fix du calcul du montant des gestes commerciaux lors de la création sur plusieurs réservations
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32010
> (PC-32010)[API] fix: correctly set the commercial gesture's amount on multiple bookings

- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/tests/core/educational/test_models.py
- api/tests/routes/pro/get_collective_offer_template_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts
- pro/src/apiClient/v1/models/CollectiveOfferTemplateAllowedAction.ts
- pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts
- pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts
- pro/src/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx
- pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/__specs__/AdagePreviewLayout.spec.tsx
- pro/src/screens/OfferEducational/useCollectiveOfferFromParams.tsx
- pro/src/utils/collectiveApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31838
Ajout des actions autorisées sur une offre vitrine en fonction du statut.
Envoi au front quand on récupère une offre ou la liste des offres vitrines.
> (PC-31838)[API] feat: add allowed actions for collective offer templates

- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/schemas.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/validation/routes/offers.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/patch_offer_test.py
- pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
- pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx
- pro/src/screens/IndividualOffer/InformationsScreen/serializePatchOffer.ts
- pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31965
> (PC-31965)[API]fix: Le patch n'est pas fait sur la 1ère étape du formulaire de mise à jour d'offre si produit

- api/src/pcapi/core/categories/subcategories_v2.py
- api/src/pcapi/core/search/backends/algolia.py
- api/tests/routes/native/openapi_test.py
- api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29215
> (PC-29215)[API] feat: split films, series, cinema search group

- api/tests/routes/pro/post_draft_offer_test.py
Ajout d'un test permettant de s'assurer une non régression avec les modifications faites sur les extraData.
> (BSR)[API]fix: Ajout d'un test de création d'offre CD ou vinyle sans EAN pour un disquaire si FF WIP_EAN_CREATION désactivée

- pro/src/screens/OfferType/CollectiveOfferType/CollectiveOfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32021
Le lien de la bannière de référencement ne récupérait pas le bon offererId et donc la redirection renvoyait une page blanche
> (PC-32021)[PRO] fix: bug redirection referencement banner

- api/src/pcapi/core/educational/api/institution.py
- api/tests/core/educational/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31996
Fix concerne https://sentry.passculture.team/organizations/sentry/issues/1618939/?referrer=slack
> (PC-31996)[ADAGE] fix: Add the null value for rural level

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/banner_test.py
The `ENABLE_PHONE_VALIDATION` feature flag is now only used to toggle between the phone validation screens in the native app.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32046
> (PC-32046)[API] feat: always ask for 18yo beneficiary phone number

- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/src/pcapi/routes/backoffice/templates/accounts/get/general.html
- api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32039
Et un second commit cosmétique pour aligner les boutons (demande du support jeunes).
> (PC-32039)[BO] feat: send reset password email from user details page

- pro/vite.config.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32064
**Objectif**
Utiliser la nouvelle JS api au moment du build vite pour corriger les warnings de depreciation (https://sass-lang.com/documentation/breaking-changes/legacy-js-api/)
> (PC-32064)[PRO] fix: Warnings of scss deprecated api.

- pro/src/pages/VenueCreation/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx
- pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32060
Le lien ne s'ouvre pas dans une nouvelle fenêtre (comportement souhaité car a11y compliant), il faut donc retirer tous les icônes indiquant le contraire pour rester cohérent.
> (PC-32060)[PRO] fix: Removes icon={fullLinkIcon} in timeline links

- pro/yarn.lock
Tenter de corriger ces 3 erreurs sentry qui sont liées à search-insights (dépendance d'algolia) :
- https://passculture.atlassian.net/browse/PC-31621 - https://sentry.passculture.team/organizations/sentry/issues/1618124/?project=2&referrer=jira_integration
- https://passculture.atlassian.net/browse/PC-31886 - https://sentry.passculture.team/organizations/sentry/issues/1618422/?referrer=jira_integration
- https://passculture.atlassian.net/browse/PC-31517 - https://sentry.passculture.team/organizations/sentry/issues/1618070/?referrer=jira_integration
D'après le changelog https://github.com/algolia/search-insights.js/releases la màj en v2.17.2 touche au local storage qui semble être la cause des 3 erreurs
> (PC-31621)[PRO] build: bump search-insights dependency to fix sentry errors

- pro/src/index.html
- pro/src/ui-kit/Spinner/Spinner.module.scss
- pro/src/ui-kit/Spinner/Spinner.stories.tsx
- pro/src/ui-kit/Spinner/Spinner.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32079
Comportement implémenté en vidéo :
https://github.com/user-attachments/assets/1c09afc8-0c34-4633-9981-a5db17f6d2f0
L'animation des trois petits points `.` `..` `...` était gérée avec un `useEffect` React. Il est maintenant géré par une animation CSS, avec l'avantage de pouvoir la désactiver avec la règle `@prefers-reduced-motion: reduce`
J'en ai profité pour également ajouter `<Spinner>` dans le storybook.
> [!NOTE]
> Le second commit change le thème par défaut à "blue" (validé avec le Design)
> Pc 32079 spinner a11y amelioration

- api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py
- api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py
Utiliser logger.exception à la place de logger.error afin de ne pas perdre d'informations. En l'état, on sait quelle erreur est survenue mais on ne peut pas savoir d'où elle provient exactement.
> (BSR)[API] feat: public api: adage mock: use logger.exception

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/schemas.py
- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/patch_offer_test.py
- api/tests/routes/pro/post_offer_test.py
- pro/src/apiClient/v1/models/AddressBodyModel.ts
- pro/src/screens/IndividualOffer/InformationsScreen/__specs__/serializers.spec.ts
- pro/src/screens/IndividualOffer/InformationsScreen/serializePatchOffer.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31953
> (PC-31953)[API] feat: Handle manual edition on pro side

- .vscode/launch.json
- api/src/pcapi/backoffice_app.py
Ajout de configs de launch VSCode pour lancer en debug les serveurs api et backoffice (sans Docker) + attach à un serveur existant
> (BSR) feat: add vscode launch configs to debug api and BO servers

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/models/feature.py
- api/tests/routes/backoffice/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31756
Lorsque le feature flag est activé :
ALORS 
au niveau des structures, la recherche approximative fonctionne ( comme avant ) 
de meme que la recherche filtres accent, lettre capital, charactere speciaux
au niveau des lieux la recherche approximative fonctionne (comme avant)
Lorsque le feature flag est désactiver 
ALORS
la recherche est moins approximative et l'on ne verra pas si il y a une faute sur quelque chose de tapé sauf accent, casse etc
de meme dans les lieux 
- CI - verte 
LORSQUE 
j'effectue une recherche de structure via le nom et que le feature flag est activé
ALORS
la recherche peut etre approximative, les résultats …
> (PC-31756)[BO] feat: add ff that allow extended search on offerer and venue

- pro/package.json
- pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx
- pro/src/components/IndividualOfferNavigation/__specs__/IndividualOfferNavigation.spec.tsx
- pro/src/ui-kit/Tabs/Tabs.module.scss
- pro/src/ui-kit/Tabs/Tabs.stories.tsx
- pro/src/ui-kit/Tabs/Tabs.tsx
- pro/src/ui-kit/Tabs/__specs__/Tabs.spec.tsx
- pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32062
Change Tabs component to use Radix Tabs library
> (PC-32062)[PRO] feat: Change Tabs component to use Radix Tabs

- pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplicationScreen.tsx
- pro/src/screens/CollectiveOfferSelectionDuplication/__specs__/CollectiveOfferSelectionDuplicationScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32158
**Objectif**
Correction de la requête faite pour la liste des offres collectives à partir desquelles on peut créer une offre réservable.
Aujourd'hui on affiche toutes les offres (vitrines et réservables) dans cette liste, mais on ne peut que créer d'offre réservable à partir d'une offre réservable. Donc cans la page de ducplication, on ne veut **que** les offres vitrines.
> (PC-32158)[PRO] fix: Dont fetch bookable offers in duplication list.

- pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.spec.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.tsx
- pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32068
- Voir description du ticket Jira, mais ceci permet notamment de marquer le champ en erreur lorsque l'ean a déjà été utilisé avec une venue (contrainte de création d'offre basée sur un produit).
> (PC-32068)[PRO] fix: forward /draft/offer POST api error regarding EAN as DetailsEanSearch input error

- pro/src/pages/Offers/OffersTable/Cells/OfferNameCell/OfferNameCell.tsx
- pro/src/pages/Offers/OffersTable/Cells/OfferNameCell/__specs__/OfferNameCell.spec.tsx
- pro/src/screens/IndividualOffer/utils/getDepartmentCode.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32136
Le composant `<OfferNameCell>` est utilisé sur la part individuelle et collective.
- Sur la part collective, il faut que  :
- la cellule affiche la date et heure en fonction du `departementCode` de la **venue**
- Sur la part individuelle, il faut que …
- … si `WIP_USE_OFFERER_ADDRESS_AS_DATA_SOURCE` est **désactivé**, la cellule affiche la date et heure en fonction du `departementCode` de la **venue** (même comportement que pour collective)
- … si le FF est **activé**, la cellule affiche la date et heure en fonction du `departmentCode` de l'OA
> (PC-32136)[PRO] feat: Show individual offers datetime with OA’s departmentCode

- api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Correction de données incohérentes dans la sandbox, conduisant à cette erreur ne pouvant a priori pas se produire en production :
https://sentry.passculture.team/organizations/sentry/issues/1619173/?project=5&referrer=slack
> (BSR)[API] fix: unconsistent stocks in sandbox

- pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx
- pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx
- pro/src/pages/CollectiveOfferCreation/CollectiveOfferCreation.tsx
- pro/src/pages/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreation.tsx
- pro/src/pages/CollectiveOfferStockCreation/CollectiveOfferStockCreation.tsx
- pro/src/pages/CollectiveOfferVisibility/CollectiveOfferCreationVisibility.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32005
**Objectif**
Dans le formulaire de création d'offres collectives (résevables ou vitrines), pouvoir accéder via le Stepper aux étapes suivantes si on a déjà tout rempli pour y avoir accès. 
Par exemple, on crée une offre réservable et on valide l'étape de détail. Si on revient à l'étape de détail par la suite, on aura toujours au moins accès à l'étape de Date et prix.
> (PC-32005)[PRO] fix: Rework collective offers form steps links.

- api/documentation/docs/understanding-our-api/managing-bookings/connection-with-ticketing-system.md
- api/tests/core/external_bookings/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31823
Simple PR suite à une fausse alerte au bug (remainingQuantity peut être nul).
1. correction de la documentation (le modèle Pydantic dit que remainingQuantity peut être nul donc la documentation doit être mise à jour);
2. ajout de tests pour éviter une régression involontaires au niveau de ce champ.
Bonus : (tout) petit fix au niveau du style d'une colonne sur une page de la documentation.
> PC 31823/fix public api null remaining quantity

- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py
- api/src/pcapi/routes/backoffice/templates/accounts/get/details/roles.html
- api/src/pcapi/routes/backoffice/templates/accounts/get/general.html
- api/src/pcapi/routes/backoffice/templates/layouts/connected.html
- api/tests/routes/backoffice/admin_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32169
Exemple d'affichage pour un profil ayant les deux rôles fraude :
> (PC-32169)[BO] feat: any BO user can view his/her roles and permissions

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/finance/api.py
- api/tests/core/bookings/test_api.py
- api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32204
> (PC-32204)[BO] fix: Use endDatetime to switch reservation from CONFIRMED -> USED

- pro/src/screens/SignupJourneyForm/Activity/ActivityForm.module.scss
- pro/src/screens/SignupJourneyForm/Activity/ActivityForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31407
Avant:
Après
> (PC-31407)[PRO] fix: Fix alignment of trash button on activity page

- api/documentation/static/openapi.json
- api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py
- api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31986
Ajout d'une nouvelle route pour réserver une offre collective, dans la série des mock Adage existants.
Pour rappel, il s'agit de routes dont le but est de simuler des actions sur des offres collectives. Le but est de permettre de débloquer les tests en intégration car Adage n'existe pas dans cet environnement et on ne peut donc que créer des offres (personne ne peut les réservers, les annuler, etc.).
> (PC-31986)[API] feat: public api: adage mock: book offer

- pro/cypress/e2e/migrations/signupJourneyCreateOfferer.cy.ts
> (BSR)[PRO] fix: Add reload to correct e2e tests

- api/src/pcapi/core/providers/titelive_book_search.py
- api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32024
Fixes : https://sentry.passculture.team/organizations/sentry/issues/1618832/?project=5
> (PC-32024)[API] fix: ignore errors when titelive sends a list of integers at the end of a synchronization

- api/src/pcapi/core/offers/repository.py
- api/tests/routes/pro/patch_publish_offer_test.py
This fixes the flacky tests.
Somehow SQLAlchemy sometimes loaded all the venue at once, sometime it only loaded the fields one at a time, creating a huge number of new DB queries.
> (BSR)[API] fix: joinedload venue in get_offer_and_extradata

- pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.module.scss
- pro/src/components/CollectiveStatusLabel/CollectiveStatusLabel.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32061
Page récap d'une offre collective en responsive pour le mobile
Avant : 
Après :
> (PC-32061)[PRO] fix: recap collective offer responsive for mobile

- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/patch_offer_test.py
`isVenueAddress` addressed the issue to figure out whether or not an address is linked to a venue or not.
Therefore, we don't need the "hack" to check whether the label is equal to the venue's name or not.
Reminder, the venue's OA label is empty in the database BUT is filled with venue's common name which we get back when the front sends its data.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32289
> (PC-32289)[API] fix: ensure any OA label is valid

- pro/package.json
- pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31921
- Mise à jour de vite-tsconfig-paths
> (PC-31921)[PRO] bump: vite-tsconfig-paths

- pro/src/components/IndividualOfferForm/OfferLocation/OfferLocation.tsx
- pro/src/components/IndividualOfferForm/utils/resetAddressFields.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32282
> (PC-32282)[PRO] fix: Don't reset location label in generic function

- api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32279
> (PC-32279)[PRO] chore: add WIP_OFFERER_STATS_V2 feature flag

- pro/cypress/e2e/migrations/adage.cy.ts
- pro/cypress/e2e/migrations/createAccount.cy.ts
- pro/cypress/e2e/migrations/createIndividualOffer.cy.ts
- pro/cypress/e2e/migrations/editDigitalIndividualOffer.cy.ts
- pro/cypress/e2e/migrations/navigation.cy.ts
- pro/cypress/e2e/migrations/searchCollectiveOffer.cy.ts
- pro/cypress/e2e/migrations/searchIndividualOffer.cy.ts
- pro/cypress/e2e/migrations/signupJourneyCreateOfferer.cy.ts
- pro/cypress/e2e/migrations/venue.cy.ts
- pro/cypress/support/commands.ts
- pro/cypress/support/index.d.ts
Avant, avec Cucumber, on retrouvait les différentes étapes (Given, When, Then) du Gherkin dans la vue des différentes étapes sur Cypress Cloud et dans l'ui Cypress qu'on lance en local.
Après avoir supprimé Cucumber, ces étapes n'apparaissent plus que dans le code (en commentaire) mais pas dans Cypress Cloud ni l'UI. C'est devenu difficile de suivre le déroulé.
Dans cette PR, en rajoutant une commande `stepLog` on peut faire apparaitre ces steps pour plus de lisibilité.
Dans l'UI, avec un peu de couleur:
Dans Cypress Cloud, on ne retrouve hélas pas les couleurs mais on a comme avant avec Cucumber (GIVEN, WHEN, THEN en majuscule)
> (BSR)[PRO] test: e2e format logs with logs steps

- pro/cypress/e2e/migrations/createIndividualOffer.cy.ts
Depuis la migration de Cucumber vers Cypress basique, le cas `Should create an individual offer (thing)` était devenu flaky. Ces changements semblent corriger
> (BSR)[PRO] test: fix flaky after cucumber migration

- api/documentation/static/openapi.json
- api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py
- api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py
- api/tests/routes/public/helpers.py
Fix: renvoyer l'identifiant de la réservations collective créée via la route du mock Adage dans l'API publique.
> (BSR)[API] fix: public api: adage mock: return booked offer id

- api/tests/core/offers/test_repository.py
Réparer l'intégration continue, rouge à cause des tests basés sur la date.
Au plus rapide, en attendant mieux.
> (BSR)[API] fix: tests which fail from 2024-10-16

- pro/src/app/App/hook/__specs__/useFocus.spec.tsx
- pro/src/app/App/hook/useFocus.ts
- pro/src/app/App/layout/LateralPanel/LateralPanel.tsx
- pro/src/app/App/layout/Layout.module.scss
- pro/src/app/App/layout/Layout.tsx
- pro/src/app/App/layout/OldLayout.module.scss
- pro/src/app/App/layout/OldLayout.tsx
- pro/src/app/AppLayout.tsx
- pro/src/app/__specs__/AppLayout.spec.tsx
- pro/src/components/Header/Header.tsx
- pro/src/components/Header/OldHeader.tsx
- pro/src/components/SkipLinks/SkipLinks.tsx
- pro/src/components/SkipLinks/__specs__/SkipLinks.spec.tsx
- pro/src/pages/Accessibility/AccessibilityLayout.tsx
- pro/src/pages/Accessibility/AccessibilityMenu.module.scss
- pro/src/pages/Accessibility/AccessibilityMenu.tsx
- pro/src/pages/Accessibility/Commitment.module.scss
- pro/src/pages/Accessibility/Commitment.tsx
- pro/src/pages/Accessibility/Declaration.module.scss
- pro/src/pages/Accessibility/Declaration.tsx
- pro/src/pages/Accessibility/MultiyearScheme.module.scss
- pro/src/pages/Accessibility/MultiyearScheme.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32137
Objectifs
Cette tâche permet d’adresser la question des redirections (non annoncées) au sein des applications de type SPA.
“In general, we found that resetting focus to the top of the app would be very overwhelming, especially in large applications.” : c’est notre traitement actuel, il faut trouver une meilleure solution.
Permet au passage d’enrayer l’erreur suivante : https://dequeuniversity.com/rules/axe/4.10/link-name?application=AxeChrome , puisqu’un faux lien était déclaré pour réaliser un autofocus en haut des pages.
👎🏼 Solution 1 : 
On fait un auto-focus sur les `<h1>` sur des redirections de page (ne concerne donc pas les dialog). Ceci en partant du principe que toute page devrait avoir un …
> (PC-32137)[PRO] fix: auto-focus on "skip/back to nav" link + aria-live announcing new page on redirect

- .gitignore
- .vscode/launch.json
Ajout d'une config de launch VSCode pour debug un script local python
La conf a un input pour le chemin vers le fichier, avec comme valeur par défaut `api/src/pcapi/scripts/local_debug_script.py` qui est ajouté au .gitignore. Pour que cette valeur par défaut de l'input fonctionne, créer d'abord le fichier en question
> (BSR) feat: add a vscode launch config to run a local python file

- pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32198
> (PC-32198)[PRO] fix: Hide scrollbar on full screen for stocks

- pro/src/components/IndividualOfferForm/OfferLocation/OfferLocation.tsx
- pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32445
Résoud le problème suivant sur l'édition d'une offre ayant l'adresse d'une venue sélectionnée :
- Lors d'un refresh de la page, la valeur "À une autre adresse" devenait cochée, alors que l'offre était bien positionnée sur l'adresse de la venue.
Le problème était lié au fait qu'une fois que `selectedVenue` était mis à jour via la requête SWR, les `initialValues` ne se mettaient pas à jour dynamiquement dans Formik parce qu'il n'actualise pas les valeurs initiales une fois qu'elles sont définies (d'où le `enableReinitialize: true`)
Il a également fallu utiliser un `useEffect` dans ce cas précis car `<Offerlocation/>` devait lire `formik.initialValues.offerlocation`, qui venait à changer dynamiquement en …
> (PC-32445)[PRO] fix: Re-render Formik form with good values when SWR call returned venues

- api/tests/core/finance/test_validation.py
Ajout de la fixture `db_session` pour l'ensemble du fichier.
> (BSR)[API] fix: add BDD pytest mark on finance tests

- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/pro/venues.py
- api/src/pcapi/settings.py
- api/tests/routes/pro/patch_venue_test.py
Security added: ENFORCE_SIRET_CHECK settings must be true. This is to avoid SIRET check deactivation in prod
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32131
> (PC-32131)[API] feat: disable SIRET checks with DISABLE_SIRET_CHECK FF

- api/src/pcapi/core/external_bookings/decorators.py
- api/src/pcapi/core/external_bookings/exceptions.py
- api/tests/core/external_bookings/test_decorator.py
`catch_cinema_provider_request_timeout` est un décorateur qui a pour objectif de logger les erreurs de timeout lorsque nous faisons des appels aux APIs des cinémas et de raise une erreur unique : `ExternalBookingTimeoutException`. Le but est d'avoir des logs qui ressemblent à ça : 
```JSON
{
"insertId": "efkmhkhfm",
"jsonPayload": {
"user_id": 1979728,
"module": "pcapi.core.external_bookings.decorators",
"extra": {
"cinema_id": 789,
"method": "book_ticket",
"client": "BoostClientAPI",
"method_params": {
"show_id": "12345",
"booking": "<Booking #1>",
"beneficiary": "<User #3>"
},
"request": {"url": "https://unproviderado.re/mais/dont/lurl/est/un/peu/flaky", "method": "POST"},
},
"technical_message_id": "",
"api_key_offerer_id": null,
"message": "Cinema Provider API Request Timeout"
}
}
```
> (BSR)[API] feat: add `catch_cinema_provider_request_timeout` decorator

- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
- api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
- api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py
- api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py
- api/src/pcapi/routes/public/individual_offers/v1/utils.py
- api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
- api/tests/routes/backoffice/offers_test.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/validation/models/generic_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29597
> (PC-29597)[API] chore : read duration minutes from produts

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241022T114248_88c4d806c740_alter_fields_updated_nullable.py
- api/src/pcapi/alembic/versions/20241022T114614_56372cadc547_remove_unused_product_mediation_fields.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/providers/titelive_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32602
Delete unused columns on Product Mediation
```
staging> select count(*) from product_mediation where "idAtProviders" is not null;
+-------+
| count |
|-------|
| 0     |
+-------+
SELECT 1
Time: 0.023s
staging> select count(*) from product_mediation where "fieldsUpdated" <> '{}';
+-------+
| count |
|-------|
| 0     |
+-------+
SELECT 1
Time: 0.065s
```
> (PC-32602)[API] chore: delete unused columns from productMediation

- api/src/pcapi/routes/backoffice/forms/fields.py
- api/tests/routes/backoffice/collective_bookings_test.py
- api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32544
Sentry : https://sentry.passculture.team/organizations/sentry/issues/1620632/?project=5
> (PC-32544)[BO] fix: non-numeric ids were not rejected in autocomplete filters

- api/documentation/static/openapi.json
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/public/documentation_constants/descriptions.py
- api/src/pcapi/routes/public/documentation_constants/fields.py
- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/src/pcapi/routes/public/individual_offers/v1/utils.py
- api/tests/routes/public/individual_offers/v1/patch_product_test.py
- api/tests/routes/public/individual_offers/v1/post_event_test.py
- api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
- api/tests/routes/public/individual_offers/v1/post_product_test.py
> (PC-31915)[API] feat: add `AddressLocation` option in `OfferCreation` serializer

- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32511
L'ensemble des cas se trouve sur le document : https://docs.google.com/spreadsheets/d/1yQvw2AA_PxlDtHRmFbB6ORmuSfCoN5-HXVd5sIn465g/edit?pli=1&gid=0#gid=0
> (PC-32511)[PRO] Ajout de donnée sur la sandbox pour gérer tous les cas de displayedStatus

- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/patch_collective_offers_template_archive_test.py
- pro/src/commons/core/OfferEducational/types.ts
- pro/src/components/ArchiveConfirmationModal/utils/__specs__/isCollectiveOfferArchivable.spec.ts
- pro/src/components/ArchiveConfirmationModal/utils/isCollectiveOfferArchivable.ts
- pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.tsx
- pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx
- pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx
- pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx
- pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/CollectiveOffersActionsBar.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30662
SOUS FF : ENABLE_COLLECTIVE_NEW_STATUSES
Gérer via une info back dans la requête de l'offre si elle est archivable ou non -> on garde l'ancien code car l'action est conditionné au statut des offres qui sont sous FF pour le moment
> (PC-30662)[PRO] feat: use can archive in eac front

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241015T144117_5b903a069f48_add_status_to_special_event_response.py
- api/src/pcapi/core/operations/factories.py
- api/src/pcapi/core/operations/models.py
- api/src/pcapi/repository/clean_database.py
- api/src/pcapi/routes/backoffice/filters.py
- api/src/pcapi/routes/backoffice/operations/blueprint.py
- api/src/pcapi/routes/backoffice/templates/components/links.html
- api/src/pcapi/routes/backoffice/templates/operations/details.html
- api/src/pcapi/routes/backoffice/templates/operations/list_events.html
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_special_events.py
- api/tests/routes/backoffice/operations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31827
> (PC-31827)[BO] feat: add special event page

- api/src/pcapi/core/offers/models.py
We run through this code even if the value is None. We should not log anything in case we have a null value
> (BSR)[API] fix: only log if a non null value is set

- pro/cypress/e2e/adage.cy.ts
- pro/cypress/e2e/collectiveBooking.cy.ts
- pro/cypress/e2e/cookieBanner.cy.ts
- pro/cypress/e2e/createIndividualOffer.cy.ts
- pro/cypress/e2e/desk.cy.ts
- pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
- pro/cypress/e2e/financialManagement.cy.ts
- pro/cypress/e2e/navigation.cy.ts
- pro/cypress/e2e/searchCollectiveOffer.cy.ts
- pro/cypress/e2e/searchIndividualOffer.cy.ts
- pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
- pro/cypress/e2e/venue.cy.ts
- pro/cypress/support/e2e.ts
- pro/cypress/support/helpers.ts
- pro/cypress/tsconfig.json
- pro/src/pages/Reimbursements/Reimbursements.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32595
- déduplication
- passage des intercept en haut de test
- fonctions en bas de page
> (PC-32595)[PRO] refactor: test e2e

- api/src/pcapi/core/finance/commands.py
- api/src/pcapi/scripts/pro/upload_reimbursement_csv_to_offerer_drive.py
- api/src/pcapi/workers/export_csv_and_send_notfication_emails_job.py
- api/tests/scripts/pro/upload_reimbursement_csv_to_offerer_drive_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31666
Utilisation du batch_id pour filtrer les invoices afin d'éviter d'utiliser des plages de dates pour filtrer. L'utilisation des batch_id permet de ne pas avoir de discontinuité entre les factures.
Le script est lancé lors de la génération des factures et ne sera pas lancé par un cron.
> (PC-31666)[API] feat: reimbursement csv

- api/src/pcapi/core/providers/titelive_book_search.py
- api/tests/providers/titelive_search_test.py
Sometimes, TiteLive returns a dictionary with indexes as keys instead of a list.
```python
{"response": {"1": book1, "2": book2}}  # what can be returned
{"response": [book1, book2]}  # what we expected
```
Amends: b1b6ec75e10af55af47c6cf0cf3e4ba444aba872
> (PC-32024)[API] fix: titelive book serialization when dict is received

- api/documentation/src/pages/change-logs.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31313
Mise à jour du __changelog__ de la documentation de l'API publique : ajout d'un paragraphe concernant l'arrivée de nouvlles routes permettant de mettre à jour le statut d'une réservation collective.
Pour rappel, ces actions ne seront pas accessibles en production et leur but et de permettre de réaliser des actions en intégration qui ne sont pas possibles car Adage ne dispose pas d'un environnement d'intégration.
> (PC-31313)[API] public api doc: update changelog

- pro/src/components/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
- pro/src/components/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx
- pro/src/components/IndividualOffer/UsefulInformationScreen/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32248
Fix de bugs en revue KO :
- La checkbox devait être pré-cochée automatiquement
- Lorsque les modalités de retrait d'une offre ayant des réservations étaient déjà enregistrées comme vides, et que l'on revenait sur le formulaire en modifiant ces modalités, et qu'on les remettait à vide ensuite, la popup apparaissait quand même (en raison de la default value à "undefined" !== '' (empty string) car il manquait la clé dans "DEFAULT_USEFULL_INFORMATION_INTITIAL_VALUES"
> (PC-32248)[PRO] fix: Makes box checked by default + fix withdrawalDetails default value to an empty string

- pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.tsx
- pro/src/pages/Signup/__specs__/Signup.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30711
- Rediriger les utilisateurs connectés qui arrivent sur la page de confirmation d'inscription.
> (PC-30711)[PRO] fix: Redirect logged users on signup confirmation page.

- pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
- pro/cypress/support/commands.ts
Ligne 186 du spreadsheet https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98
Vérifie que le fiche d'une offre individuelle est bien présentée en onglet
> (BSR)[PRO] test: check individual offer with tab view

- api/src/pcapi/core/offerers/api.py
- api/tests/routes/pro/get_offerer_members_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32961
> (PC-32961)[PRO] fix: do not show deleted members in 'Collaborateurs' page

- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/tests/routes/public/individual_offers/v1/patch_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31813
Avant : lors de l'édition d'une offre individuelle, on peut se retrouver à mettre à jour une offre avec `isActive` à `None` alors que la colonne ne peut pas l'être (=> erreur).
Après : on s'assure qu'on ne peut pas envoyer `None` comme valeur lors de la mise à jour. Si le champ `isActive` dans le JSON d'entrée vaut `null` ou s'il vaut nul parce qu'il n'a pas été renseigné, la colonne ne sera pas mise à jour.
> (PC-31813)[API] fix: public api: isActive cannot be null

- pro/src/pages/Reimbursements/Income/Income.module.scss
- pro/src/pages/Reimbursements/Income/Income.spec.tsx
- pro/src/pages/Reimbursements/Income/Income.tsx
- pro/src/pages/Reimbursements/Income/IncomeError/IncomeError.module.scss
- pro/src/pages/Reimbursements/Income/IncomeError/IncomeError.tsx
- pro/src/pages/Reimbursements/Income/IncomeNoData/IncomeNoData.module.scss
- pro/src/pages/Reimbursements/Income/IncomeNoData/IncomeNoData.tsx
- pro/src/pages/Reimbursements/Income/IncomeVenueSelector/IncomeVenueSelector.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32547
Couvre les cas d'affichage suivants : 
- Venues en chargement, pas de venue, 1 seule venue et erreur sur la récupération des venues.
- Revenus / income en chargement, pas d'income, requête pour récupérer l'income en erreur.
- Petit fix #a11y sur le contraste de couleur des écrans d'erreur
- Petite optimisation pour ne pas réécrire le state et set activeYear inutilement.
- Petit fix css pour supporter les très larges écrans (tags venues)
> (PC-32547)[PRO] feat: better support stats v2 edge cases

- api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32727
> (PC-32727)[API] fix: remove `ordered` from Algolia config

- pro/cypress/e2e/desk.cy.ts
L'exécution des tests `desk` est très long or on a pas de besoin de tout recréer avant chaque test avec un `beforeEach`, un `before` est suffisant et le temps d'exécution est ainsi divisé par 3 (46" au lieu de 2'12)
> (BSR)[PRO] test: useless beforeEach takes too much time

- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/educational/repository.py
- api/tests/core/educational/test_models.py
- pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32648
Les offres vitrines expirées (dates d'événement passées) sont marquées comme publiées dans pc pro alors qu'elles disparaissent d'ADAGE, il faut donc les marquer comme "masquées"
> (PC-32648)[API] fix: fix expired template offers displayed status

- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/search/__init__.py
Also adds a fallback on venue's timezone for offer list filters.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32726
> (PC-32726)[API] fix: remove N+1 queries on algolia serialization

- api/src/pcapi/core/finance/commands.py
DSv4 is outdated and we should'nt try to import related applications. All applications are now going through DSv5 and all existing data has been move from BankInformation to BankAccount.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32593
> (PC-32593)[API] chore: Don't import DSv4 applications anymore

- api/src/pcapi/core/educational/api/playlists.py
- api/src/pcapi/core/offerers/api.py
- api/tests/core/educational/api/test_playlists.py
- api/tests/core/offerers/test_api.py
```
(psycopg2.errors.ForeignKeyViolation) update or delete on table "collective_offer_template" violates foreign key constraint "collective_playlist_collectiveOfferTemplateId_fkey" on table "collective_playlist" DETAIL:  Key (id)=(84516) is still referenced from table "collective_playlist".
```
Ticket Jira : https://passculture.atlassian.net/browse/PC-32653
> (PC-32653)[API] fix: IntegrityError when a venue with template in playlist is deleted

- api/src/pcapi/sandboxes/scripts/getters/pro.py
- pro/cypress/e2e/financialManagement.cy.ts
- pro/cypress/support/helpers.ts
J'ai modifié le cas existant et rajouté 1 nouveau cas pour tester les lignes 273 et 274 du fichier https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98:
- Informations bancaire/Modification/Désassociation de 1 ou plusieurs lieux d'un compte
- Informations bancaire/Modification/Désassociation de tous les lieux d'un compte
> (BSR)[PRO] test: add unattach 2 or all venues in financial

- api/src/pcapi/core/educational/adage_backends/__init__.py
- api/src/pcapi/core/educational/adage_backends/adage.py
- api/src/pcapi/core/educational/adage_backends/base.py
- api/src/pcapi/core/educational/adage_backends/logger.py
- api/src/pcapi/core/educational/adage_backends/testing.py
- api/src/pcapi/core/educational/api/adage.py
- api/src/pcapi/core/educational/commands.py
- api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32661
According to the doc https://bv.ac-versailles.fr/adage/swagger#/default/a211309023e5b4e27eb12056f1899a77 the parameter must be provided in the format 'format YYYY-MM-DD hh:mm:ss'
> (PC-32661)[ADAGE] fix: Fix the format of the parameter 'dateModificationMin'

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/post_stocks_test.py
- api/tests/routes/public/individual_offers/v1/patch_date_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31975
Add a log inside `handle_stocks_edition` in order to track some specific stock updates with its bookings.
> (PC-31975)[API] feat: log stock update changes

- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/mails/transactional/users/personal_data_updated.py
- api/src/pcapi/core/users/email/update.py
- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py
- api/src/pcapi/routes/backoffice/users/blueprint.py
- api/src/pcapi/routes/backoffice/users/forms.py
- api/tests/core/mails/transactional/users/personal_data_updated_test.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32742
> (PC-32742)[BO] feat: send transactional email when personal data is updated

- api/.env.development
- api/.env.testauto
- api/src/pcapi/connectors/clickhouse/__init__.py
- api/src/pcapi/connectors/clickhouse/backend.py
- api/src/pcapi/connectors/clickhouse/queries/__init__.py
- api/src/pcapi/connectors/clickhouse/queries/base.py
- api/src/pcapi/connectors/clickhouse/queries/yearly_revenue.py
- api/src/pcapi/connectors/clickhouse/testing_backend.py
- api/src/pcapi/settings.py
- api/tests/connectors/clickhouse/clickhouse_test.py
- api/tests/connectors/clickhouse/fixtures.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31450
Ajout d'un connecteur clickhouse.
Backend clickhouse de test utilisé dans l'environnement testing. Données mockées
> (PC-31450)[API] feat: add backends to clickhouse

- pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
Vérifie que le changement de date d'une offre change aussi la date de la réservation.
Ligne 197 de https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98 qui était au 2/3 vérifier en tests unitaires
> (BSR)[PRO] test: add test change date in bookings

- pro/src/components/Bookings/BookingsRecapTable/Filters/FilterByBookingStatus.tsx
- pro/src/components/Bookings/BookingsRecapTable/Filters/Filters.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/__specs__/RecurrenceForm.spec.tsx
- pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.module.scss
- pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
- pro/src/components/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
- pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx
- pro/src/components/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx
- pro/src/pages/Offers/OffersTable/Cells/Cells.module.scss
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersTable.module.scss
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersTable.tsx
- pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss
- pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx
- pro/src/pages/VenueSettings/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.tsx
- pro/src/pages/VenueSettings/VenueProvidersManager/AllocineProviderForm/__specs__/AllocineProviderForm.spec.tsx
- pro/src/ui-kit/form/Checkbox/Checkbox.tsx
- pro/src/ui-kit/form/QuantityInput/QuantityInput.mdx
- pro/src/ui-kit/form/QuantityInput/QuantityInput.module.scss
- pro/src/ui-kit/form/QuantityInput/QuantityInput.spec.tsx
- pro/src/ui-kit/form/QuantityInput/QuantityInput.stories.tsx
- pro/src/ui-kit/form/QuantityInput/QuantityInput.tsx
- pro/src/ui-kit/form/SelectAutoComplete/OptionsList/OptionsList.module.scss
- pro/src/ui-kit/form/SelectAutoComplete/OptionsList/OptionsList.tsx
- pro/src/ui-kit/form/TextInput/TextInput.tsx
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
- pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31264
- Ajout du composant QuantityInput avec documentation et usage à tous les endroits où on a besoin de définir des quantités, quantités indéfinies étant comprises comme "illimitées".
- CheckboxInput : déplacement du label pour une déclaration explicite car plus robuste #a11y (et non implicite par imbrication) + adaptation des fichiers .scss  afin de ne plus styliser par sélecteur de balise `label`, mais par classe.
- Réadaptation des tests en conséquence en privilégiant l'usage de `getByRole`.
> (PC-31264)[PRO] feat: add QuantityInput component and use it when relevant

- pro/src/pages/Collaborators/Collaborators.module.scss
- pro/src/pages/Collaborators/Collaborators.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32795
**Objectif**
Correction des marges du sous-titre de la page collaborateurs.
> (PC-32795)[PRO] fix: Margins of collaborator page subtitle.

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/backoffice/test_users/blueprint.py
- api/src/pcapi/routes/backoffice/titelive/blueprint.py
https://passculture.atlassian.net/browse/PC-31782
Voir l'epic https://passculture.atlassian.net/browse/PC-29667
Ajout du décorateur atomic sur les routes
- test_users
- titelive
> PC-31782-migrer-les-routes-du-bo-vers-atomic-part-11

- api/src/pcapi/core/external/attributes/api.py
- api/src/pcapi/core/offerers/models.py
- api/tests/core/external/external_pro_test.py
- api/tests/core/offerers/test_models.py
- api/tests/routes/external/zendesk_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32870
> (PC-32870)[API] fix: use bankAccount info for pro contacts

- api/documentation/static/openapi.json
- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v1/patch_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32626
Avant : seuls les noms des produits pouvaient être mis à jour via l'API publique.
Après : les noms des événements et des produits peuvent être mis à jour via l'API.
> PC 32626/feat update offer name

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/email/update.py
- api/src/pcapi/routes/backoffice/pivots/blueprint.py
- api/src/pcapi/routes/backoffice/pivots/contexts/boost.py
- api/src/pcapi/routes/backoffice/preferences/blueprint.py
- api/src/pcapi/routes/backoffice/pro/blueprint.py
- api/src/pcapi/routes/backoffice/pro_users/blueprint.py
- api/src/pcapi/routes/backoffice/providers/blueprint.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/backoffice/venues_test.py
- api/tests/routes/pro/patch_venue_test.py
- api/tests/routes/pro/test_offerers_addresses.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31774
> Pc 31774 use atomic in bo

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241104T112917_4999605acac1_fix_archived_collective_offer_templates.py
- api/src/pcapi/alembic/versions/20241104T113207_6519c3689ae8_fix_archived_collective_offers.py
- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/routes/pro/collective_offers.py
- api/tests/core/educational/test_models.py
- api/tests/core/offers/test_repository.py
- api/tests/routes/adage_iframe/get_collective_offer_template_test.py
- api/tests/routes/adage_iframe/get_collective_offers_for_my_institution.py
- api/tests/routes/pro/patch_collective_offers_archive_test.py
- api/tests/routes/pro/patch_collective_offers_template_archive_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32803
> (PC-32803)[API] fix: explicitely set archived collective offers as inactive

- api/src/pcapi/core/educational/adage_backends/adage.py
- api/tests/core/educational/adage_backends/test_adage.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32625
> (PC-32625)[ADAGE] fix: handle empty json response in adage client

- api/poetry.lock
- api/pyproject.toml
Somehow commit cbc4fc81db2840390a3e2f72dae132a577dfe66f (rq bump) did remove a constraint on IPython which bumped into a version that crashes on startup making it impossible to start a shell with our setup.
See https://github.com/ipython/ipython/issues/14255 for the issue. This commit ensure this version is not used without pinning IPython.
> (BSR)[API] fix: remove buggy IPython version

- api/src/pcapi/workers/decorators.py
started_at is a timezone aware field while enqueued_at is not. Remove timezone information
Fixes this issue : https://sentry.passculture.team/organizations/sentry/issues/1622802/?project=5&referrer=slack
> (BSR)[API] chore: fix rq bump.

- api/src/pcapi/routes/backoffice/bookings/forms.py
- api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
- api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_venue_provider_and_external_bookings.py
- api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32238
> (PC-32238)[BO] feat: permit to filter solo/duo bookings in bo

- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/routes/pro/venues.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/src/pcapi/sandboxes/scripts/creators/data/create_data_venues.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py
- api/src/pcapi/sandboxes/scripts/getters/pro.py
- api/tests/core/finance/test_api.py
- api/tests/routes/backoffice/conftest.py
- api/tests/routes/backoffice/venues_test.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/routes/pro/get_offerer_test.py
- api/tests/routes/pro/get_reimbursements_csv_test.py
- api/tests/routes/pro/get_venue_test.py
- pro/src/apiClient/v1/models/GetOffererResponseModel.ts
- pro/src/apiClient/v1/models/GetOffererVenueResponseModel.ts
- pro/src/apiClient/v1/models/GetVenueManagingOffererResponseModel.ts
- pro/src/apiClient/v1/models/GetVenueResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32555
> Pc 32555 delete uses of VenueReimbursementPointLink and BankInformation

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32954
Paginer la màj des bookings pour éviter le timeout lors de la génération des invoices
> (PC-32954)[API] fix: paginate bookings status update in generate_invoice to avoid statement timeout

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/src/pcapi/routes/backoffice/accounts/serialization.py
- api/tests/routes/backoffice/accounts_test.py
`NEW_EMAIL_SELECTION` added in 2024 had never been taken into account in the backoffice
Ticket Jira : https://passculture.atlassian.net/browse/PC-32561
> (PC-32561)[BO] fix: conditions for email updated icon

- .github/workflows/dev_on_workflow_tests_api.yml
- api/tests/routes/backoffice/venues_test.py
Séparer en deux blocs les tests BO pour accélérer l'intégration continue.
> (BSR)[BO] test: split BO tests on CI

- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32974
The join on Offer broke things since it missed the filters on it because there was already an alias used on offer.
It looks like the second join got all the stocks all the time, making the filters on date useless.
The test did not detect it because it was only making sure the offers were OK within the time range but was not checking if the offers were correctly ignored when outside the time range.
> (PC-32974)[API] fix: broken date filters on offer's page

- pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
- pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx
- pro/src/components/IndividualOffer/StocksThing/__specs__/validationSchema.spec.tsx
- pro/src/components/IndividualOffer/StocksThing/utils/__specs__/buildInitialValues.spec.ts
- pro/src/components/IndividualOffer/StocksThing/utils/buildInitialValues.ts
- pro/src/components/IndividualOffer/StocksThing/validationSchema.ts
- pro/src/ui-kit/form/QuantityInput/QuantityInput.spec.tsx
- pro/src/ui-kit/form/QuantityInput/QuantityInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32982
Par défaut, le min du composant est à 0.
Dans le cas du RecurrenceForm, il est à 1.
Dans le cas de StockThing et en édition, il ne peut pas être inférieur au nombre de réservations.
Il correspond dans tous les cas à ce qui est contrôlé dans les schémas de validation Formik.
> (PC-32982)[PRO] fix: align QuantityInput mins with formik validation rules + avoid null/undefined init values

- api/src/pcapi/connectors/acceslibre.py
- api/src/pcapi/connectors/api_recaptcha.py
- api/src/pcapi/connectors/recommendation.py
- api/src/pcapi/core/external/compliance_backends/compliance.py
- api/src/pcapi/core/monkeypatches.py
- api/tests/connectors/api_recaptcha_test.py
Do not log calls to some external services. Impacted services : 
- Reco API (logs are exists on passculture-data-prod project)
- Compliance API (logs exists on passculture-data-prod project)
- Brevo (for this calls, only the URL and the timing is displayed. I don't really see how this can be useful)
- Reptcha (likewise)
- AccesLibre (likewise)
> (BSR)[API] chore : do not log some external calls

- api/src/pcapi/routes/internal/e2e.py
- pro/cypress/e2e/collaborator.cy.ts
- pro/cypress/e2e/createAccount.cy.ts
Nouveau test pour ajouter un collaborateur (ligne 67 du [fichier](https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98))
J'ai aussi ajouté une route pour vider l'outbox de mails (en cas de retry) ce qui permet de récupérer un seul email dans la suite du test et bien vérifier que c'est celui-ci qu'on attendait
> (BSR)[PRO] test: add collaborator test and clean_email_list

- api/src/pcapi/core/finance/siret_api.py
- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/src/pcapi/routes/backoffice/autocomplete.py
- api/src/pcapi/routes/backoffice/health_check.py
- api/src/pcapi/routes/backoffice/home.py
- api/src/pcapi/routes/backoffice/move_siret.py
- api/src/pcapi/routes/backoffice/redirect.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31791
Ajout du décorateur atomic sur les routes
siret_api
autocomplete
health_check
home
move_siret
redirect
> (BSR)[API] chore: add atomic decorators in backoffice root routes

- pro/cypress/e2e/collaborator.cy.ts
Corrige quelques échecs uniquement observés sur master après merge: on attend l'affichage du compte courant dans la liste des collaborateurs avant d'en rajouter un nouveau
> (BSR)[PRO] test: wait for all collaborator page before adding a new one

- api/src/pcapi/core/educational/api/institution.py
- api/src/pcapi/core/educational/commands.py
- api/tests/core/educational/api/test_import_deposit_institution_deposit_data.py
Ticket Jira (ou description si BSR) : ajout d'un paramètre pour pouvoir lancer `import_deposit_csv` en dry-run
> (BSR)[API] feat: add a dry run option to import_deposit_csv command

- pro/src/components/Bookings/BookingsRecapTable/BookingsTable/CollectiveActionButtons.tsx
- pro/src/components/Bookings/BookingsRecapTable/BookingsTable/__specs__/CollectiveActionButtons.spec.tsx
- pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx
- pro/src/pages/Offers/OffersTable/Cells/__specs__/CollectiveActionsCells.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30786
> (PC-30786)[PRO] feat: use CAN_CANCEL action to show collective booking cancel button when FF is on

- pro/firebase.json
Ajout de frame-ancestors dans les CSP
PR pour fix les attaques de type clickjacking -> on autorise seulement les urls listés à afficher notre iframe sur leurs site, les autres non listées auront un message d'erreur fourni par le navigateur (si vous avez une idée d'autres lien qui utiliserait le portail pro dans une iframe, ajoutez le en commentaire pour qu'on puisse l'ajouter)
> (BSR)[PRO] fix: csp clickjacking

- pro/src/components/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
- pro/src/components/IndividualOffer/UsefulInformationScreen/__specs__/utils.spec.ts
- pro/src/components/IndividualOffer/UsefulInformationScreen/types.ts
- pro/src/components/IndividualOffer/UsefulInformationScreen/utils.ts
- pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/components/OfferLocation/OfferLocation.module.scss
- pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/components/OfferLocation/OfferLocation.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/components/OfferLocation/validationSchema.ts
- pro/src/pages/IndividualOffer/commons/__specs__/serializers.spec.ts
- pro/src/pages/IndividualOffer/commons/serializePatchOffer.ts
- pro/src/pages/IndividualOffer/commons/types.ts
- pro/src/pages/Offers/OffersTable/Cells/AddressCell.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOfferRow/IndividualOfferRow.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32969
- The venue address is the default value
- Do not display the venue address for offers without one.
> (PC-32969)[PRO] feat: Handle default value for offer location

- pro/cypress/e2e/createAccount.cy.ts
- pro/cypress/e2e/desk.cy.ts
- pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
- pro/cypress/e2e/searchCollectiveOffer.cy.ts
Le retry ne pouvait pas fonctionner avec un `before(()`donc on met `beforeEach(()`. Voir https://cloud.cypress.io/projects/rit5sb/runs/1450/overview/1c0ba722-dbcf-4237-b6a9-5cc7d89e065c/replay?att=1&roarHideRunsWithDiffGroupsAndTags=1&ts=1732011458668.2002
> (BSR)[PRO] test: use beforeEach bc before not used when retry

- pro/cypress/e2e/collaborator.cy.ts
Timeout et spinner pour l'affichage de la liste des collaborateurs qui traine parfois et rend le test flaky
> (BSR)[PRO] test: increase timeout in collaborateur list

- infra/pc_scripts/start_backend.sh
- pc
Refonte du code de `start-backend`, `start-proxy-backend`, `restart-backend` et `restart-proxy-backend` pour les rendre plus modulaires/maintenables, éviter la répétition de code et ajouter deux options:
`--fast` permet d'ignorer la phase re rebuild des images dockers
`--force-recreate` permet de forcer ce rebuild.
Ces deux flags sont disponibles pour les 4 commandes.
> Bsr rework pc backend

- pro/cypress/e2e/collaborator.cy.ts
Le timeout de 60" précédemment ajouté était inutile et n'a pas résolu le flakyness (difficile à reproduire en local). Le problème semble dû au fait d'afficher la page `/collaborateurs` directement au login, on passe donc par l'affichage de la page `accueil` avant d'ouvrir `/collaborateurs` et ça semble mieux!
> (BSR)[PRO] test: loading /collaborateurs page too soon caused flakyness

- pro/cypress/e2e/adage.cy.ts
La mise en favori se faisait trop tôt, il est préférable d'attendre le chargement de la page (quelques cas [flaky](https://cloud.cypress.io/projects/rit5sb/analytics/flaky-tests?att=1&branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&replayTestId=e1b3136a-3374-40fa-871f-3623478e83a7&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-11-13%22%2C%22endDate%22%3A%222024-11-20%22%7D&ts=1732106982088&viewBy=TEST_CASE) sur master aboutissant à …
> (BSR)[PRO] test: fix flaky adage when favorite too quick

- api/tests/core/bookings/test_models.py
The test was partially removed by 8a7f7e89b6d21153eb77c4fac77e2908f9a85b1d The commit removed the code tested, so it is safe to remove (plus it asserts nothing)
Merci @bpeyrou-pass d'avoir détecté ça 🙌 
🔥 dead code
> (BSR)[API] test: remove obsolete test

- pro/src/components/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32886
les données de la sandbox sont bien incohérentes → il s’agit d’une offre publiée sans price_categories / tarif ce qui bloque le passage à l'étape suivante
or on ne peut pas supprimer les price categories en édition donc ce cas ne peut actuellement pas se produire
Cependant comme c’est une feature qu’on pourrait développer un jour nous avons proposé un correctif
> (PC-32886)[PRO] fix: in offer we cannot change to price step in edition

- pro/src/components/AddressManual/AddressManual.tsx
- pro/src/components/IndividualOffer/UsefulInformationScreen/UsefulInformationForm/UsefulInformationForm.tsx
- pro/src/components/IndividualOffer/UsefulInformationScreen/__specs__/utils.spec.ts
- pro/src/components/IndividualOffer/UsefulInformationScreen/constants.ts
- pro/src/components/IndividualOffer/UsefulInformationScreen/utils.ts
- pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/components/OfferLocation/OfferLocation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33111
Ce ticket corrige la situation où l'on pouvait modifier la localisation d'une offre en attente de validation.
Les champs d'adresse sont désormais désactivés si l'offre est en _pending_.
> (PC-33111)[PRO] fix: Makes location fields disabled for pending offers

- pro/src/pages/OffererStats/OffererStats/OffererStatsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33122
> (PC-33122)[PRO] fix: auto-redirect old stats url to new one

- pro/package.json
- pro/src/vitest.setup.ts
- pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33091
- Mise à jour de react-router-dom.
Pas mal de nouveaux logs (discuté [ici](https://github.com/remix-run/react-router/issues/12250) et [là](https://github.com/remix-run/react-router/pull/11750))
> (PC-33091)[PRO] bump: react-router-dom.

- api/src/pcapi/connectors/boost.py
- api/src/pcapi/connectors/cgr/cgr.py
- api/src/pcapi/connectors/cine_digital_service.py
- api/src/pcapi/connectors/ems.py
- api/src/pcapi/core/external_bookings/api.py
- api/src/pcapi/core/external_bookings/boost/client.py
- api/src/pcapi/core/external_bookings/cds/client.py
- api/src/pcapi/core/external_bookings/cgr/client.py
- api/src/pcapi/core/external_bookings/ems/client.py
- api/src/pcapi/core/external_bookings/models.py
- api/tests/connectors/api_cine_digital_service_test.py
- api/tests/connectors/cgr/api_cgr_test.py
- api/tests/core/external_bookings/boost/test_client.py
- api/tests/core/external_bookings/cds/test_client.py
- api/tests/core/external_bookings/cgr/test_client.py
- api/tests/core/external_bookings/ems/test_client.py
- api/tests/core/external_bookings/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33041
Ce qui est fait dans cette PR  : 
- Ajout d'une constante `EXTERNAL_BOOKINGS_TIMEOUT_IN_SECONDS` au niveau de `external_bookings/api.py`
- Modification de la classe abstraite `ExternalBookingsClientAPI` et de toutes classes enfants (`EMSClientAPI`, `CGRClientAPI`, `CineDigitalServiceAPI`, `BoostClientAPI`) : 
- Ajout de l'attribut `request_timeout`, défini à l'initialisation de la classe
- Transmission de l'attribut `request_timeout` aux requêtes effectuées à partir des connecteurs (pour surcharger le timeout par défaut défini [`REQUEST_TIMEOUT_IN_SECOND`](https://github.com/pass-culture/pass-culture-main/blob/tcoudray-pass/PC-33041-increase-timeout/api/src/pcapi/utils/requests.py#L40))
- Modification …
> (PC-33041)[API] Increase request timeout for external bookings

- pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx
- pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx
- pro/src/pages/Offers/OffersTable/Cells/__specs__/CollectiveActionsCells.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32750
> (PC-32750)[PRO] feat: do not show create bookable offer button when offer is pending

- api/src/pcapi/connectors/clickhouse/backend.py
- api/src/pcapi/connectors/clickhouse/queries/__init__.py
- api/src/pcapi/connectors/clickhouse/queries/total_revenue.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
- api/src/pcapi/routes/backoffice/templates/components/revenue_details.html
- api/src/pcapi/routes/backoffice/venues/blueprint.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33135
> (PC-33135)[BO] feat: use Clickhouse for statistics in BO

- api/src/pcapi/routes/backoffice/filters.py
- api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31872
> (PC-31872)[BO] feat: Use only the two first gtl_id digits to format music type on offer's BO

- pro/src/commons/utils/factories/statisticsFactories.ts
- pro/src/pages/Reimbursements/Income/Income.spec.tsx
- pro/src/pages/Reimbursements/Income/Income.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33026
- Followup de la tâche côté frontend, pour faire suite aux changements de typage d'api. 
- Sans cette PR, le type check est cassé !
> (PC-33026)[PRO] fix: use last typings for Income page

- pro/eslint.config.mjs
- pro/src/pages/Offers/OffersTable/Cells/__specs__/CollectiveActionsCells.spec.tsx
- pro/src/ui-kit/form/QuantityInput/QuantityInput.spec.tsx
Poursuite du cleanup suite à la migration eslint, fix des alertes suivantes : 
```
'@typescript-eslint/no-unnecessary-condition': 'error',
'require-await': 'error',
```
> (BSR)[PRO] cleanup after eslint update

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/external_bookings/boost/client.py
- api/src/pcapi/core/external_bookings/cds/client.py
- api/src/pcapi/core/external_bookings/ems/client.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/native/v1/bookings.py
- api/tests/core/bookings/test_api.py
- api/tests/routes/native/v1/bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32546
> (PC-32546)[API] feat: catch timeout on cinema providers

- pro/src/pages/IndividualOffer/commons/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33110
Empêche la modification du champs "Localisation de l’offre" sur une offre synchronisée.
> (PC-33110)[PRO] fix: Makes offer location field disabled for synchronized offers

- pro/src/pages/Offers/OffersRoute.tsx
- pro/src/pages/Offers/OffersTable/Cells/DeleteDraftCell.tsx
- pro/src/pages/Offers/OffersTable/Cells/IndividualActionsCell.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOfferRow/IndividualOfferRow.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOfferRow/__specs__/IndividualOfferRow.spec.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/IndividualOffersActionsBar.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/__specs__/IndividualOffersActionsBar.spec.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersTable.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersTableBody/IndividualOffersTableBody.tsx
- pro/src/pages/Offers/components/IndividualOffersScreen/IndividualOffersScreen.tsx
- pro/src/pages/Offers/utils/computeIndividualApiFilters.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32898
Les offres n'étaient plus raffraichies après une action parce que les apiFilters n'étaient plus identiques
j'ai donc créé une fonction pour centraliser leur gestion
> (PC-32898)[PRO] fix: refresh after actions in individual offers

- api/src/pcapi/routes/pro/collective_offers.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/tests/routes/pro/patch_collective_offer_test.py
- api/tests/routes/pro/post_collective_offers_template_test.py
- api/tests/routes/pro/post_collective_offers_test.py
- pro/src/apiClient/v1/models/PostCollectiveOfferBodyModel.ts
- pro/src/apiClient/v1/models/PostCollectiveOfferTemplateBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33154
On revert les changements de ces 2 commits :
https://github.com/pass-culture/pass-culture-main/commit/5f2b148d517d8c129c0b92b8aeba5485d52253f9
https://github.com/pass-culture/pass-culture-main/commit/6b87d4b351154cbf1afa5b7e9ce7eb53f28ab841
> (PC-33154)[API] feat: remove update of collective offer template when editing collective offer

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : Sur les offres collectives de la sandbox ajoutées pour tester les statuts, il manque le champ "priceDetail" du stock et "formats" des offres vitrine.
Ces champs étant obligatoires sur le front, en l'état ça bloque la modification des offres.
> (BSR)[API] fix: add some missing fields in collective offers in sandbox

- pro/src/pages/Offers/OffersTable/Cells/DeleteDraftCell.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/IndividualOffersActionsBar.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/__specs__/IndividualOffersActionsBar.spec.tsx
- pro/src/pages/Offers/components/IndividualOffersScreen/IndividualOffersScreen.tsx
- pro/src/pages/Offers/components/IndividualOffersScreen/__specs__/IndividualOffersScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33133
La vérification sur les offres brouillons étaient inutile, le back s'en charge et l'appel au back était de toute manière identique
en le retirant les trois actions/boutons se comportent de la même manière
> (PC-33133)[PRO] feat: harmonize publish action in offers

- pro/src/components/CollectiveOffersTable/CollectiveOffersTable.module.scss
- pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/CollectiveOffersScreen.tsx
- pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersTable.module.scss
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33015
Avoir un comportement normal pour la checkbox 'Tout sélectionner' dans la liste des offres :
si 1 offre coché ou + -> état indeterminate 
si tout sélectionné -> état checked
si on décoche à la main les offres checked -> la checkbox ne doit plus afficher l'état indeterminate
> (PC-33015)[PRO] fix: indeterminate checkbox

- pro/src/components/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33269
Il semblerait que l'erreur se produise suite à une not-null assertion sur `offerData.address!`
Une valeur "undefined" peut alors potentiellement arriver en argument de "computeAddressDisplayName" et provoquer l'erreur.
> (PC-33269)[PRO] fix: Adds condition to check if an address isn't undefined

- pro/src/commons/utils/__specs__/findLastIndex.spec.ts
- pro/src/commons/utils/findLastIndex.ts
- pro/src/components/Stepper/Stepper.tsx
This reverts commit 2a6844d089cf40fe4e544d0e1de0a9fcd073dfd4.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32983
Il semblerait que la suppression de cette fonction provoque de nombreuses erreurs sur de vieux navigateurs n'ayant pas implémentés nativement la fonction "findLastIndex".
Cette PR fait-donc un revert du commit pour récupérer la fonction de polyfill pour "findLastIndex".
> Revert "(PC-32716)[PRO] refactor: Replace obsolete util function by a standard one"

- api/src/pcapi/sandboxes/scripts/getters/pro.py
- pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
Dernier cas de signup manquant: nouvelle venue avec structure existante.
J'ai aussi réorganisé le titres Mocha dans le but de bien rendre visible ce qui est testé dans chacun des 4 cas.
> (BSR)[PRO] test: add new signup test case with known offerer and unknown venue

- pro/src/components/ArchiveConfirmationModal/ArchiveConfirmationModal.tsx
- pro/src/components/CollectiveOffersTable/CollectiveOffersActionsBar/__specs__/CollectiveOffersActionsBar.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33246
Problème avec une valeur qui était envoyer à la data qui contenait un tableau avec plusieurs objets, on ne voyait pas les objets mais [object Object], pour résoudre le souci, on fait comme l'app jeune, c'est à dire qu'on JSON.stringify la valeur pour que la data puisse manipuler les données
> (PC-33246)[PRO] feat: tracking archive data

- api/src/pcapi/core/external/compliance_backends/compliance.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33366
Retenter pour ne pas omettre les infos dans l'offre en cas d'erreur aléatoire de l'API Compliance.
> (PC-33366)[API] fix: make job retryable when receiving random 403 from Compliance API

- api/src/pcapi/routes/backoffice/auth.py
- api/tests/routes/backoffice/auth_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33367
> (PC-33367)[BO] fix: do not make login crash when CSRF token expired

- .github/pull_request_template.md
Afin de permettre de savoir rapidement si la revue fonctionnelle d'un ticket à été faite ou non, ajout de ce champ dans la template des PR
> (BSR)[API] chore: add pair testing validation in PR template

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33389
> (PC-33220)[API] fix: missing offer_id in data log

- api/src/pcapi/sandboxes/scripts/getters/pro.py
- pro/cypress/e2e/searchCollectiveOffer.cy.ts
- pro/cypress/e2e/searchIndividualOffer.cy.ts
- pro/cypress/support/helpers.ts
(PC-33167)[PRO] test: add more tests for collective search
Ajoute un cas de filtre de recherche d'offre collective:
- par nom
- par lieu
- par format
- par type
- par date
- par status
et la réinitialisation des filtres dans une recherche combinée
> (PC-33167)[PRO] test: add more tests for collective search

- pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32895
**Objectif**
Supprimer le style qui retire la bordure de l'input de recherche des composants de filtre d'ADAGE.
> (PC-32895)[PRO] fix: Dont hide the multiselect border

- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32396
Fix : on doit être en mesure de mettre à jour le prix d'un stock via l'API publique et de le rendre gratuit (`price = 0`).
Source du problème : la condition n'était pas assez précise puisque `0` était évalué à faux, tout comme `None` ce qui n'est pas ce que l'on souhaite.
> (PC-32396)[API] fix: public api: create/update free offer

- api/src/pcapi/core/educational/utils.py
- api/tests/core/educational/test_utils.py
Exception liée au ticket Jira qui n'est actuellement déployé que sur testing : https://passculture.atlassian.net/browse/PC-32979
> (PC-32979)[API] fix: 'ValueError: second must be in 0..59' in get_non_empty_date_time_range

- api/src/pcapi/connectors/typeform.py
- api/src/pcapi/core/chronicles/api.py
- api/src/pcapi/core/chronicles/commands.py
- api/src/pcapi/core/chronicles/constants.py
- api/src/pcapi/core/chronicles/models.py
- api/src/pcapi/routes/backoffice/templates/components/collapsable_text.html
- api/src/pcapi/routes/backoffice/templates/components/display_selector.html
- api/src/pcapi/scheduled_tasks/decorators.py
- api/src/pcapi/scripts/install.py
- api/src/pcapi/scripts/rebuild_staging/anonymize.sql
- api/src/pcapi/static/backoffice/js/addons/pc-display-selector.js
- api/tests/core/chronicles/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32405
> Pc 32405 rpa import book club chronicles

- api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py
- api/tests/routes/pro/get_reimbursements_csv_by_invoices_test.py
- pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32112
Limiter le nombre de csv de détails de remboursements à 24: un utilisateur ne peut pas sélectionner plus de 24 remboursements à la fois.
Cette limite existe pour le téléchargement des justificatifs (sur la même page) mais pas pour les csv. Un utilisateur pouvait donc sélectionner plus de cent (par exemple) remboursements et demander les csv de détails, ce qui peut générer des requêtes beaucoup trop lourdes au niveau de la base de données (et donc un timeout ensuite).
> (PC-32112)[PRO] invoicetable: csv: 24 rows selected max

- api/src/pcapi/core/external/zendesk_sell_backends/zendesk_sell.py
Inutile de m'alerter sur Sentry quand une requête à Zendesk Sell finit en timeout.
> (BSR)[API] fix: sentry alert is useless in case Zendesk Sell server is not reachable

- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/post_price_categories_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33006
Fix : lorsqu'un client essayait d'éditer le prix d'une offre rejetée ou en brouillon, une erreur était générée mais pas gérée.
Correction : gérer cette erreur et informer le client que cette opération n'est pas possible.
> (PC-33006)[API] fix: handle error: price cat edit: reject/pend offer

- pro/package.json
- pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33296
**Objectif**
Upgrade de la lib design-system :
- Changement de noms de design tokens en interne qui n'ont pas d'effet sur les variables utilisées dans l'app pro
- Passage de title4 de 16px à 17px de font-size
> (PC-33296)[PRO] bump: Upgrade design-system.

- api/alembic_version_conflict_detection.txt
- api/pyproject.toml
- api/src/pcapi/alembic/versions/20241206T150902_58f3ca2882c6_bank_account_cegid_sync.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/backend/__init__.py
- api/src/pcapi/core/finance/backend/base.py
- api/src/pcapi/core/finance/backend/cegid.py
- api/src/pcapi/core/finance/commands.py
- api/src/pcapi/core/finance/conf.py
- api/src/pcapi/core/finance/external.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/testing.py
- api/src/pcapi/models/feature.py
- api/tests/conftest.py
- api/tests/core/finance/conftest.py
- api/tests/core/finance/test_backends.py
- api/tests/core/finance/test_external.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31818
Synchronisation des BankAccounts avec l'outil finance externe
> (PC-31818)[API] feat: add bank account sync with external finance backend

- api/src/pcapi/core/offers/validation.py
Crash caused by an image with too many pixels
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33466
> (PC-33466)[API] fix:prevent CGR synchronisation crash

- api/src/pcapi/repository/clean_database.py
BSR: rajout du truncate de la table achievement dans le reset de la sandbox
> (BSR)[API] chore: clean achievements on sandbox reset

- api/src/pcapi/core/external_bookings/api.py
- api/src/pcapi/settings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33041
Objectif : ne plus utiliser une constante dans le code pour le temps de _timeout_, mais une variables d'environnement. Ce qui devrait rendre les modifications beaucoup plus simples (et rapides).
La PR côté déploiement est [là](https://github.com/pass-culture/pass-culture-deployment/pull/569).
> (PC-33041)[API] feat: ext. bookings api: move timeout const to settings

- .github/workflows/dev_on_schedule_delete_pullrequest_deployments.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33480
Delete pullrequests deployments on schedule :
- Runs every hour
- Get deployments older than 4 hours by looking for namespaces pcapi-pr-* created older than 4 hours and retrieves PR ids
- Delete matching folders ids in rendered-manifests/pcapi/pullrequests
- Finally delete matching namespaces
> PC-33480 - Delete pullrequests deployments on schedule

- pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32800
**Objectif**
Ne pas avoir 2 outlines sur le bouton de type Box au focus.
Avant/Après
> (PC-32800)[PRO] fix: Box button double outline on focus.

- pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx
- pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33476
**Objectif**
Suppression d'un message de TODO qui propose de supprimer un cas de tri de la table des justificatifs de remboursement. Comme le FF n'existe déjà plus mais que le tri existe encore, je propsoe de laisser le tri même si le message de TODO propose de l'enlever.
> (PC-33476)[PRO] feat: Remove todo message and inexistant FF.

- api/src/pcapi/core/educational/api/institution.py
- api/src/pcapi/core/educational/commands.py
- api/tests/core/educational/api/test_import_deposit_institution_deposit_data.py
Ticket Jira (ou description si BSR) : Ajout de la mise à jour du educational_program lors de l'import des budgets
Une fois ce changement dispo en prod, mettre à jour le script : https://github.com/pass-culture/pass-culture-main/pull/15315
> (BSR)[API] feat: add educational program update to budget import

- pro/cypress/support/commands.ts
- pro/cypress/support/helpers.ts
- pro/cypress/support/index.d.ts
Ajoute de la JSDoc pour les helper et nouvelles `Cypress.Commands` créées
> (BSR)[PRO] test: add some JSDoc for commands and helper functions

- api/tests/conftest.py
BSR: pytest should not exit with failure when it collects only the tests even if the tests are mixed with BO / non-BO routes
> (BSR)[API] fix: don't crash on collect only with BO non-BO tests

- pro/cypress/e2e/adageConfirmation.cy.ts
Test adage confirmation flaky, j'ai ici précisé les intercept plus précisément pour qu'ils ne soient pas détectés plusieurs fois.
> (BSR)[PRO] test: more specific waits for adage confirmation

- pro/cypress/e2e/adage.cy.ts
- pro/cypress/support/commands.ts
- pro/cypress/support/index.d.ts
Il arrive que les tests adage soient flaky, j'ajoute ici une attente sur le `GET /adage-iframe/authenticate`
> (BSR)[PRO] test: wait authenticate after visit adage iframe

- pro/cypress/e2e/collaborator.cy.ts
- pro/cypress/e2e/createAccount.cy.ts
Dans la route `get_unique_email` de `e2e.py` on lit la file d'attente d'email pendant 60 secondes max, il faut donc que le timeout dans l'appel depuis les tests e2e soit le même
> (BSR)[PRO] test: timeout 60 secs for request to get email

- api/src/pcapi/sandboxes/scripts/getters/pro.py
- pro/cypress/e2e/adage.cy.ts
- pro/cypress/e2e/createCollectiveOffer.cy.ts
- pro/cypress/e2e/createIndividualOffer.cy.ts
- pro/cypress/e2e/desk.cy.ts
- pro/cypress/e2e/searchCollectiveOffer.cy.ts
- pro/cypress/e2e/searchIndividualOffer.cy.ts
- pro/cypress/support/helpers.ts
On utilise maintenant le contenu des datas générées (nom d'offre, de venue...) plutôt que copier les labels côté back et front e2e
C'était une suggestion de @abouabdallaoui-pass [ici](https://github.com/pass-culture/pass-culture-main/pull/15238#discussion_r1867247669)
> (BSR)[PRO] test: share data from backend route retrieved in e2e code

- api/documentation/src/pages/change-logs.md
- api/documentation/static/openapi.json
- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/src/pcapi/routes/public/individual_offers/v1/utils.py
- api/tests/routes/public/individual_offers/v1/get_events_test.py
- api/tests/routes/public/individual_offers/v1/get_products_test.py
Drop required constraint on `venueId`.
Ticket Jira  : https://passculture.atlassian.net/browse/PC-33575
> (PC-33575)[API] feat: add `addressId` param in GET Events and GET Products API endpoints

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241213T125457_1343aeafc182_create_function_email_domain.py
- api/src/pcapi/alembic/versions/20241213T130718_9803f6ec13df_create_index_user_email_domain.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/backoffice/fraud/blueprint.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33581
```
pcapi-staging> explain analyze select email from "user" where email like '%@passculture.app';
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                                                  |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Gather  (cost=1000.56..591798.83 rows=744 width=28) (actual time=0.543..27953.140 rows=679 loops=1) …
```
> (PC-33581)[BO] fix: timeout when filtering by email domain

- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33613
**Objectif**
Désactiver le téléchargement automatique de la lib `search-insight` au moment de l'initialisation de l'autocomplete algolia. La lib search-insight est déjà dans nos dépendances.
> (PC-33613)[PRO] fix: Dont dl the search-insights lib automatically.

- api/src/pcapi/core/educational/api/booking.py
- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/core/educational/exceptions.py
- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/educational/validation.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/collective_bookings.py
- api/src/pcapi/routes/pro/collective_offers.py
- api/tests/core/educational/test_models.py
- api/tests/routes/pro/patch_cancel_collective_offer_booking_test.py
- api/tests/routes/pro/patch_collective_offers_archive_test.py
- api/tests/routes/pro/patch_collective_offers_educational_institution_test.py
- api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33285
Partie 1 des actions sur les offres réservables :
- edit institution
- duplicate
- cancel booking
- archive
> (PC-33285)[API] feat: check allowed actions when editing collective offer

- pro/cypress/support/helpers.ts
On faisait précédemment (changé dans cette [PR](https://github.com/pass-culture/pass-culture-main/pull/15501/files#diff-d96f7a1a0c58a137f1a785b46eeed8b3f60819a9df05182efab9fb93c140d86d)) un `expect(truc).to.be.true` alors qu'on compare les valeurs de tableau affiché avec ce qu'on attend.
Voilà les logs dans Cypress
J'ai remis pour qu'on voit bien ce qu'ils se passe, notamment en cas d'erreur.
> (BSR)[PRO] test: expect shows real comparison

- pro/firebase.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33626
**Objectif**
Ajouter l'url de prod d'ADAGE dans le frame-ancestor de la prod dans la config firebase.
> (PC-33626)[PRO] fix: Add adage prod url in prod firebase config.

- pro/cypress/e2e/adageConfirmation.cy.ts
- pro/cypress/e2e/createCollectiveOffer.cy.ts
- pro/cypress/e2e/searchCollectiveOffer.cy.ts
- pro/src/Root.tsx
- pro/src/app/App/hook/__specs__/usePageTitle.spec.tsx
- pro/src/app/App/hook/usePageTitle.ts
- pro/src/app/App/layout/Layout.module.scss
- pro/src/app/App/layout/Layout.tsx
- pro/src/app/App/layout/__specs__/Layout.spec.tsx
- pro/src/components/BackToNavLink/BackToNavLink.module.scss
- pro/src/components/BackToNavLink/BackToNavLink.tsx
- pro/src/components/PageTitleAnnouncer/PageTitleAnnouncer.module.scss
- pro/src/components/PageTitleAnnouncer/PageTitleAnnouncer.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33000
> (PC-33000)[PRO] feat: add 'focus:visible' on back to nav link, only display when connected + aria-live to announce page titles

- api/src/pcapi/core/users/api.py
abaisse le log level a error dans l'anonymisation des users
> (BSR)[API] feat: tone down log level to error in user anonymisation

- api/src/pcapi/scripts/rebuild_staging/anonymize.sql
Des informations incomplètes étaient affichées dans le backoffice (exemple : modification d'un rôle du BO sans préciser le rôle) à cause de l'anonymisation du dump/restore qui efface trop d'infos. Proposition : ne le faire que pour les actions qui peuvent contenir des informations personnelles ou sensibles.
> (BSR)[API] test: dump/restore on staging: clear action_history.jsonData only when it contains sensitive information

- pro/cypress/e2e/createCollectiveOffer.cy.ts
- pro/cypress/e2e/createIndividualOffer.cy.ts
Corrige les derniers échecs depuis ce matin
> (BSR)[PRO] test: fix errors when creation offers

- api/documentation/static/openapi.json
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32196
Suppression d'un enum inutile (et trompeur) pour les événements musicaux.
> (PC-32196)[API] public doc: mark MusicTypeEnum as deprecated

- api/src/pcapi/connectors/titelive.py
- api/src/pcapi/core/providers/titelive_api.py
- api/tests/connectors/titelive/titelive_test.py
- api/tests/providers/titelive_search_test.py
TiteLive search query pagination is broken when more than 20 000 results can be returned. To alleviate this issue, we only query a day at a time.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33675
> (PC-33675)[API] fix: only sync titelive products a day at a time

- pro/cypress/e2e/adageConfirmation.cy.ts
- pro/cypress/e2e/collaborator.cy.ts
Lignes 232, 233 et 234 du cahier de test 
pour tester la bonne réception des mails de pré-réservation, réservation et annulation de réservation
> (BSR)[PRO] test: check emails for pre-booked, booked and canceled collective offers

- pro/cypress/README.md
- pro/cypress/e2e/README.md
D'où viennent les données ? Data factory ? Comment lancer Cypress ?
+ il était encore fait référence à Gherkin et aux features/scenario dans la guideline du `cypress/e2e/README`
> (BSR)[PRO] test: how to use cypress e2e in README

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/bookings/utils.py
- api/tests/core/bookings/test_repository.py
- api/tests/core/bookings/test_utils.py
- api/tests/routes/pro/get_all_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33084
Actuellement le téléchargement des réservations pour les grosses structures (type FNAC ou Cultura) ne fonctionne plus car la requête SQL prend trop de temps.
Le but de cette PR est d'améliorer les performances de la requête SQL en changeant notre stratégie concernant le filtrage par date. 
Plutôt que de faire :
```sql
WHERE
-- Transformation 2: Cast de la datetime en date
CAST(
-- Transformation 1: Calcul de la date dans la timezone du booking
timezone(
coalesce(address.timezone, address_2.timezone, venue.timezone),
timezone('UTC', booking."dateCreated")
) 
AS DATE) BETWEEN SYMMETRIC '2024-11-28' AND '2024-12-03'
```
Faire plutôt (pour tirer au maximum profit des index sur les dates): 
```sql
WHERE
(coalesce(address.timezone, …
```
> (PC-33084)[API] feat: improve bookings fetching strategy

- api/src/pcapi/core/offerers/exceptions.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offerers/schemas.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/native/v1/offerers.py
- api/src/pcapi/routes/native/v1/serialization/offerers.py
- api/src/pcapi/routes/pro/offerers.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/tests/core/offerers/test_repository.py
- api/tests/core/search/test_serialize_algolia.py
- api/tests/routes/native/openapi_test.py
- api/tests/routes/native/v1/offerers_test.py
- api/tests/routes/pro/get_offerer_headline_offer_test.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/post_draft_offer_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/OffererHeadLineOfferResponseModel.ts
- pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33385
- création des deux routes
- dépacement de `BannerMetaModel` et `VenueTypeCode` pour résoudre un import circulaire
> (PC-33385)[API]  feat: routes get offerer headline offer

- pro/package.json
- pro/scripts/customRequest.ts
- pro/src/apiClient/adage/core/request.ts
- pro/src/apiClient/v1/core/request.ts
- pro/src/apiClient/v2/core/request.ts
- pro/vite.config.ts
- pro/yarn.lock
Remplacement de coverage V5 par Istanbul pour le coverage de l'application
> (BSR)[PRO] feat: replace coverage V8 by istanbul

- pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
- pro/src/components/IndividualOffer/SummaryScreen/EventPublicationForm/EventPublicationForm.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.module.scss
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormDates/FormDates.module.scss
- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormDates/FormDates.tsx
- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx
- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/OfferEducationalForm.module.scss
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/SuggestedSubcategories/SuggestedSubcategories.tsx
- pro/src/pages/IndividualOffer/IndividualOfferInformations/components/OfferLocation/OfferLocation.tsx
- pro/src/pages/IndividualOffer/IndividualOfferSummary/IndividualOfferBookings/components/DownloadBookingsModal/DownloadBookingsModal.tsx
- pro/src/ui-kit/form/IconRadioGroup/IconRadioGroup.stories.tsx
- pro/src/ui-kit/form/RadioButton/RadioButton.stories.tsx
- pro/src/ui-kit/form/RadioButton/RadioButton.tsx
- pro/src/ui-kit/form/RadioGroup/RadioGroup.module.scss
- pro/src/ui-kit/form/RadioGroup/RadioGroup.stories.tsx
- pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx
- pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.module.scss
- pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.spec.tsx
- pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.stories.tsx
- pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.tsx
- pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33526
**Objectif**
- Donner la possibilité au `RadioGroup` d'avoir une section qui s'affiche sous les options quand elles sont sélectionnées.
- Revue des styles disabled du `BaseRadio` pour coller à [ce design](https://www.figma.com/design/z4Hs7lbjyI0gi8O9wxSgJb/Am%C3%A9lio-offre-vitrine?node-id=6503-9072&t=O0MJER3bjqoT86NT-4).
- La props `legend` ou `describedBy` rendues obligatoires.
> Pc 33526 rework radio group box

- pro/src/pages/SignIn/SignIn.tsx
- pro/src/pages/SignIn/__specs__/SignIn.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33741
**Objectif**
Lors du login, ajouter la mise à jour dans le store de l'offerer de l'utilisateur. Sans ça, si le store est initialisé alors que l'utilisateur n'est pas connecté, l'offerer n'est jamais ajouté au store et la page d'accueil est vide.
Voir la description du ticket pour la reproduction du bug.
@abouabdallaoui-pass  Je pense que c'est depuis [le commit d'ajout du store de l'offerer](https://github.com/pass-culture/pass-culture-main/commit/fcd8d3d95b7f020f5ca0f60821f7c2de03f3746e). J'ai fait de mon mieux pour corriger rapidement, mais ce serait top si tu pouvais jeter un oeil. Aussi est-ce que pour éviter les multiples appels sur `offerers/names` on pourrait mettres les offerers dispo dans le …
> (PC-33741)[PRO] fix: Load the offerer when logging in.

- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/tests/routes/public/individual_offers/v1/delete_event_stock_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33722
Bug : impossible d'annuler le stock d'un événement via l'API publique si celui-ci a au moins une réservation.
Fix : ne pas utiliser `current_user` dans l'API publique puisqu'il renvoie un objet représentant un utilisateur anonyme (logique, puisqu'elle n'utilise pas flask login) ce qui créé quelques étincelles au moment de mettre à jour la réservation ("`cancellationUserId` doit être un entier").
> (PC-33722)[API] fix: rm current_user as a parameter inside public route

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241220T091708_4c53718279e7_drop_headline_offer_unicity_constraints.py
- api/src/pcapi/alembic/versions/20241220T095131_4c3be4ff5274_add_timespan_on_headline_offer.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/commands.py
- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_offers.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_headline_offers.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_offers.py
- api/tests/core/offerers/test_repository.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_models.py
- api/tests/core/offers/test_repository.py
- api/tests/routes/native/v1/offerers_test.py
- api/tests/routes/pro/get_offerer_headline_offer_test.py
- api/tests/routes/pro/get_offerer_stats_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33423
commit 1 : retirer les contraintes d'unicité sur les offres & venues (pour préparer la suite)
commit 2: ajouter un timespan et des contraintes d'unicité sur l'overlap du timespan par offre et venue
commit 3: mettre à jour la fin du timespan si une offre n'est plus active (sera ajoutée à la crontab)
commit 4: mise à jour de la sandbox pour avoir des offres à la une valide
commit 5: mise à jour des routes GET offerer / headline_offer (PRO + NATIF)
> (PC-33423)[API] feat: add status isActive to headline_offer

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241220T090811_f512de569bde_drop_ix_partial_unique_address_per_street_and_insee_code_address_table.py
- api/src/pcapi/core/geography/models.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/schemas.py
- api/tests/core/geography/test_models.py
- api/tests/routes/pro/patch_offer_test.py
- api/tests/routes/pro/test_offerers_addresses.py
with isManualEdition at True and False
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33410
> (PC-33410)[API] fix: Prevent crash on PATCH /offer when address exist

- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_confirmation_by_pro.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/routes/pro/get_product_by_ean_test.py
- api/tests/routes/pro/get_stocks_stats_test.py
- api/tests/routes/pro/get_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32883
> (PC-32883)[API] chore: add atomic to offer routes

- pro/src/components/IndividualOffer/StocksEventCreation/DayCheckbox.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/DayCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33803
**Objectif**
Corriger l'affichage des `DayCheckbox` dans le form d'édition des jours d'ouverture d'un lieu.
Avant/après :
> (PC-33803)[PRO] fix: Width of day checkboxes.

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250110T100616_b44dae2d1489_drop_provider_api_columns.py
- api/src/pcapi/core/providers/factories.py
- api/src/pcapi/core/providers/models.py
- api/src/pcapi/routes/backoffice/venues/blueprint.py
- api/src/pcapi/scripts/rebuild_staging/anonymize.sql
- api/tests/core/providers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33658
> (PC-33658)[API] Delete old provider API columns

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/schemas.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/backoffice/pro/blueprint.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/src/pcapi/scripts/beneficiary/import_test_users.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/pro/post_offerer_test.py
- api/tests/routes/pro/post_save_new_onboarding_data_test.py
- api/tests/routes/pro/post_venue_test.py
- pro/src/apiClient/v1/models/AddressBodyModel.ts
- pro/src/apiClient/v1/models/PostVenueBodyModel.ts
- pro/src/apiClient/v1/models/SaveNewOnboardingDataQueryModel.ts
- pro/src/components/Address/constants.ts
- pro/src/components/Address/types.ts
- pro/src/components/Address/validationSchema.ts
- pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.tsx
- pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx
- pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx
- pro/src/components/SignupJourneyForm/Validation/Validation.tsx
- pro/src/components/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx
- pro/src/pages/VenueCreation/serializers.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32880
Ajout de la saisie d’adresse manuelle lors de l'inscription d'une nouvelle structure à l'entité juridique
> (PC-32880)[PRO] feat: Ajout saisie d’adresse manuelle sur le parcours d’inscription de l’offerer+venue

- pro/src/app/App/layout/Layout.module.scss
- pro/src/app/App/layout/Layout.tsx
- pro/src/components/Footer/Footer.module.scss
- pro/src/pages/Onboarding/OnboardingOfferIndividual/OnboardingOfferIndividual.tsx
- pro/src/pages/Onboarding/OnboardingOfferIndividualAutomatic/OnboardingOfferIndividualAutomatic.tsx
- pro/src/pages/Onboarding/OnboardingOffersTypeChoice/OnboardingOffersTypeChoice.tsx
- pro/src/pages/Onboarding/components/OnboardingLayout/OnboardingLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33707
- Mettre le footer sur toutes les pages de l'onboarding.
> (PC-33707)[PRO] feat: Footer on all onboarding pages.

- pro/src/components/IndividualOffer/PriceCategoriesScreen/PriceCategoriesForm.tsx
- pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx
- pro/src/pages/IndividualOffer/IndividualOfferInformations/components/UsefulInformationForm/UsefulInformationForm.module.scss
- pro/src/pages/IndividualOffer/IndividualOfferInformations/components/UsefulInformationForm/UsefulInformationForm.tsx
- pro/src/ui-kit/form/Checkbox/Checkbox.tsx
- pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.module.scss
- pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.stories.tsx
- pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.tsx
- pro/src/ui-kit/form/CheckboxGroup/CheckboxGroupItem.tsx
- pro/src/ui-kit/form/RadioGroup/RadioGroup.stories.tsx
- pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.spec.tsx
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.stories.tsx
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
- pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33527
**Objectif**
Comme pour les radio group, avoir le variant des checkbox avec bordure, et potentiellement inline, et pouvoir afficher du contenu sous la checkbox quand elle est cochée. 
C'est dans le cadre de l'amélioration des offres vitrines côté collectif. Les différents écrans qu'on doit pouvoir développer à terme [sont ici](https://www.figma.com/design/z4Hs7lbjyI0gi8O9wxSgJb/Am%C3%A9lio-offre-vitrine?node-id=6834-9056&t=5DM9ruHNU0rnrbvo-4), cependant, cette PR ne concerne que le travail sur les checkbox elles-mêmes et pas l'implémentation.
> Pc 33527 checkbox group with border

- api/Dockerfile
> (BSR)[API] fix: Missing `--no-root` poetry install for proxy backend

- api/src/pcapi/routes/backoffice/filters.py
- api/src/pcapi/routes/backoffice/operations/blueprint.py
- api/src/pcapi/routes/backoffice/operations/forms.py
- api/src/pcapi/routes/backoffice/templates/operations/details.html
- api/tests/routes/backoffice/operations_test.py
Ajout d'un filtre par état de la candidature dans la page d'une opération spéciale :
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33696
> (PC-33696)[BO] feat: add filter responses by status in special operation details page

- api/src/pcapi/routes/backoffice/custom_reimbursement_rule/blueprint.py
- api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list.html
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_with_custom_reimbursement_rule.py
- api/tests/routes/backoffice/custom_reimbursement_rules_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32783
> (PC-32783)[BO] feat: extend search reimbursment rules by offerer

- pro/src/components/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33779
> (PC-33779)[PRO] fix: Adds caret « - » in offer recap for empty OA labels

- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/routes/adage_iframe/serialization/offers.py
- api/tests/routes/adage_iframe/get_favorites_test.py
- api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
Ceci permettra de pouvoir modifier une offre sur la sandbox lors des tests un peu plus simplement
> (BSR)[API] test: Add a default value for priceDetail

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241218T160009_ab6fe51d82bb_add_offer_ean.py
- api/src/pcapi/alembic/versions/20241218T163213_17a79fcf1646_add_offer_constraint.py
- api/src/pcapi/alembic/versions/20241218T164758_2ef0dd81b7c6_validate_offer_constraint.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33672
Add a column and constraint for ean
> (PC-33672)[API] feat: add new offer ean column

- api/.env.development
- api/.env.production
- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20241216T162934_8a3126f15848_drop_externalId.py
- api/src/pcapi/alembic/versions/20241216T163240_7f870f74ea1e_responseid_not_nullable.py
- api/src/pcapi/alembic/versions/20241216T163456_723ca088adc4_questionid_not_null.py
- api/src/pcapi/alembic/versions/20241216T163644_30a53e3cc7b2_eventId_not_null.py
- api/src/pcapi/alembic/versions/20241216T163929_138018be9e5a_eventid_non_nullable.py
- api/src/pcapi/connectors/typeform.py
- api/src/pcapi/core/chronicles/api.py
- api/src/pcapi/core/chronicles/commands.py
- api/src/pcapi/core/chronicles/constants.py
- api/src/pcapi/core/operations/api.py
- api/src/pcapi/core/operations/commands.py
- api/src/pcapi/core/operations/factories.py
- api/src/pcapi/core/operations/models.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/scripts/install.py
- api/src/pcapi/settings.py
- api/tests/connectors/typeform/fixtures.py
- api/tests/connectors/typeform/typeform_test.py
- api/tests/core/chronicles/test_api.py
- api/tests/core/operations/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32007
> Pc 32007 retrieve special event

- api/src/pcapi/routes/pro/users.py
- api/tests/routes/pro/post_user_review_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33989
> (PC-33989)[API] fix: prevent call to harvestr when `userComment` is emply

- api/documentation/src/pages/change-logs.md
Le warning ajouté récemment dans le changelogs de l'api publique est mis en premier, pour être aligné avec le reste du fichier
> (BSR) docs: move warning at the top of changelogs

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/tests/connectors/beneficiaries/ubble_test.py
In staging and production, going through an Ubble v2 flow has a nasty side-effect. The certificates used for mutual TLS are also sent during the Ubble v1 flow, making Ubble crash and return 500 errors.
This commit attempts to isolate the requests session to prevent this side-effect.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34037
> (PC-34037)[API] fix: isolate the two Ubble requests sessions

- pro/scripts/generator/_templates/component/<% name %>.module.scss.mustache
- pro/scripts/generator/_templates/component/<% name %>.spec.tsx.mustache
Met à jour le template de génération de composant (`yarn generate:component MyComponentName`) en prenant en compte : 
- la suppression du fichier `fonts-design-system.scss`
- un test unitaire finalement souvent inutile
> (BSR)[PRO] fix: Removes useless style and test in templates

- pro/src/commons/core/FirebaseEvents/constants.ts
- pro/src/components/Header/components/HeaderHelpDropdown/HelpDropdownMenu.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33828
**Objectif**
Ajouter un lien des nouveautés du pass dans le header. + Ajout d'un tracker sur le click et update d'un autre tracker du header (doc notion trackers màj)
> (PC-33828)[PRO] feat: Add a new evolutions link in header menu.

- api/src/pcapi/core/mails/transactional/pro/offerer_attachment_invitation.py
- api/tests/core/mails/transactional/pro/offerer_attachment_invitation_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33757
Ajout de deux paramètres manquants aux données de templates à envoyer à Brevo.
Des liens en durs (vers testing, les joies des hackatons) sont utilisés jusqu'ici. Une fois cette PR fusionnée, on pourra mettre à jour les templates sur Brevo.
> (PC-33757)[API] fix: add missing params to some pro email data

- api/src/pcapi/core/chronicles/api.py
- api/src/pcapi/core/chronicles/models.py
- api/src/pcapi/routes/native/v1/offers.py
- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/tests/routes/native/openapi_test.py
- api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33895
Route des chroniques d'une offre
> PC-33895 chronicles route

- .github/workflows/dev_on_pull_request_workflow.yml
- .github/workflows/dev_on_workflow_deploy_pullrequests.yml
Deactivate pcapi backend env preview deployment using flags to keep all code in place in case of future reactivation
> Deactivate pcapi env preview deployment

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/connectors/serialization/ubble_serializers.py
- api/tests/connectors/beneficiaries/ubble_test.py
- api/tests/core/subscription/ubble/end_to_end/fixtures.py
There is a window when Ubble notifies us of a check in progress, but the photo of the ID document is not ready yet.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34066
> (PC-34066)[API] fix: allow missing id photo in ubble response

- pro/cypress/e2e/adageConfirmation.cy.ts
- pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.spec.tsx
- pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.tsx
- pro/src/components/CollectiveOffersTable/CollectiveOfferRow/__specs__/CollectiveOfferRow.spec.tsx
- pro/src/styles/components/Cells.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34011
**Objectif**
Corriger les endroits où l'augmentation de la taille de la police a décalé le reste du contenu :
**Le bouton des actions de la table collective**
-> Utilisation le composant partagé du dropdown menu qui a lui une largeur auto
avant/après : 
**Le badge "Offre vitrine"**
avant/après :
> (PC-34011)[PRO] feat: UI fixes to fix new typos mis-alignments.

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/subscription/ubble/exceptions.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/routes/native/v1/account_test.py
Our Ubble v1 flow marked declined checks as suspicious instead of ko.
This used to work because we always create a new identity verification
at every Ubble v1 attempt.
However, we reuse existing Ubble v2 identity verifications if they are
marked as suspicious. If the id verification is declined, Ubble v2
returns a 409 error. Therefore, we should not reuse declined Ubble v2
checks by marking them as KO instead of suspicious.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34065
> (PC-34065)[API] fix: mark declined ubble checks as ko 

- api/tests/core/offers/test_repository.py
In order to avoid flakiness, we order the result of the query
> (BSR)[API] fix: potentially flaky test

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250120T090637_f42c23a1a832_index_offer_ean.py
- api/src/pcapi/core/offers/models.py
Add migration for offer.ean. The index should already be created by this script : https://github.com/pass-culture/pass-culture-main/pull/15923
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33672
> (PC-33672)[API] feat: add index on offer.ean

- api/src/pcapi/routes/backoffice/forms/empty.py
- api/src/pcapi/routes/backoffice/operations/blueprint.py
- api/src/pcapi/routes/backoffice/templates/operations/details.html
- api/tests/routes/backoffice/operations_test.py
Ajout des actions batch sur les candidatures dans la page d'une opération spéciale :
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33242
> (PC-33242)[BO] feat: add batch actions on responses in operation details page

- .github/workflows/dev_on_pull_request_workflow.yml
- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_tests_pro.yml
Fix allure report not found when test pro are not played
> (BSR)[PRO] desactive allure result

- pro/src/commons/custom_types/window.d.ts
- pro/src/pages/SignupJourneyRoutes/SignupJourneyRoutes.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34189
**Objectif**
Quand on ouvre la signup journey depuis la page d'accueil, il faut que Beamer ait chargé avant de pouvoir le cacher.
La reproduction du bug est dispo dans le ticket.
> (PC-34189)[PRO] fix: Dont show/hide beamer if it has not loaded yet.

- pc
Une petite typo causant un facheu : `/usr/local/bin/pc: line 353: f: command not found`
> (BSR) fix: Typo on pc script lors de `pc psql`

- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/tests/routes/native/openapi_test.py
- api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33946
> (PC-33946)[API] feat: add publicationDate in offer route

- .vscode/launch.json
Ticket Jira (ou description si BSR) : ajout d'une config dans launch.json pour debug vitest
> (BSR) feat: add vitest config in vscode launch.json

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250127T104717_1b5deb8e094c_add_ean_column_in_product_table.py
- api/src/pcapi/alembic/versions/20250127T105755_5eb5a5f7189c_add_not_valid_constraint_on_product_ean_column.py
- api/src/pcapi/core/offers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34233
Une fois cette PR mergée et déployée dans les différents environnements, il faudra lancer dans chaque environnement : 
- Le script pour valider la contrainte sur `product.ean` (#16042)
- Le script pour créer l'index unique sur `product.ean` (#16043)
> (PC-34233)[API] feat: add `ean` column in `product` table

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/validation/models/offer.py
- api/tests/core/offers/test_api.py
- api/tests/routes/public/individual_offers/v1/post_product_test.py
- api/tests/validation/models/entity_validator_test.py
To enable the creation of digital offers linked to physical venue
Première étape vers la suppression des venues virtuelles.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34217
> (PC-34217)[API] feat: drop constraint `venue.isVirtual=True` for digital offers

- .github/workflows/dev_on_pull_request_workflow.yml
- .github/workflows/dev_on_workflow_deploy.yml
BSR : cette PR à pour but de toujours déployer un env de test, même si les tests failed pour le front
> (BSR)[PRO] fix: always deploy on testing env

- pro/src/components/UserIdentityForm/UserIdentityForm.tsx
- pro/src/ui-kit/formV2/TextInput/TextInput.module.scss
- pro/src/ui-kit/formV2/TextInput/TextInput.spec.tsx
- pro/src/ui-kit/formV2/TextInput/TextInput.tsx
BSR comme discuté en journée de pratique front, je retire le field layout des nouveaux formulaire
> (BSR)[PRO] remove firld layout for text input v2

- .vscode/settings.json
- README.md
Ticket Jira (ou description si BSR) : ajout d'une section dans le README pour tester via VSCode
> (BSR) docs: add a section in README to run tests in VSCode

- api/src/pcapi/core/educational/api/adage.py
- api/src/pcapi/routes/backoffice/filters.py
- api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py
https://passculture.atlassian.net/browse/PC-34275
> (PC-34275)[API] feat: log action in venue history when setting/clearing adageId

- api/src/pcapi/core/offerers/models.py
- api/tests/core/offerers/test_models.py
isOpenToPublic will replace isPermanent to know whether or not a venue should be indexed in Algolia.
Ticket Jira: https://passculture.atlassian.net/browse/PC-33116
> (PC-33116)[API] feat: use isOpenToPublic to index venues

- api/src/pcapi/core/offers/validation.py
- api/tests/core/offers/test_validation.py
Now publication date can be every quarter of hour
PR liée côté deployement : https://github.com/pass-culture/pass-culture-deployment/pull/651
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34317
> (PC-34317)[API] feat: update constraint on publication date

- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
- api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34341
> (PC-34341)[BO] fix: avoid crash at collective offer validation when ADAGE notification timeouts

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/routes/pro/headline_offer.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_repository.py
- api/tests/routes/pro/post_upsert_headline_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34016
Context : Lors de l'ajout d'une offre en tant qu'offre à la une, il faut désactiver l'offre à la une déjà en place si elle existe. Pour cela, il faut ajouter une borne max au timespan. Un cron tourne toutes les 10min pour vérifier que les offres à la une sont toujours éligible (offre active, avec une image). Il existe donc un laps de temps de 10min pendant lequel on essaye de mettre une nouvelle offre à la une alors que la précédente n'est plus éligible mais dont l'objet `HeadlineOffer` ne possède toujours pas de borne max dans son timespan. Il faut donc récupérer ces offres à la une et non simplement les offres à la une avec une borne max dans leur timespan.
> (PC-34016) upsert on inactive offer

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/validation.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_validation.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/patch_offer_test.py
- api/tests/routes/pro/post_draft_offer_test.py
- api/tests/routes/pro/post_offer_test.py
- api/tests/routes/public/individual_offers/v1/patch_product_test.py
- api/tests/routes/public/individual_offers/v1/post_product_test.py
Check added in `create_offer`, `update_offer`, `create_draft_offer`, `update_draft_offer`
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34314
> (PC-34314)[API] feat: add check_offer_name_does_not_contain_ean in offer.api methods

- .github/workflows/dev_on_workflow_deploy.yml
- .github/workflows/dev_on_workflow_deploy_pullrequests.yml
Utiliser la dernière version de common-workflows pour traiter un souci de CI
> (BSR) ci: use latest render-push-manifests action to pin dependency

- api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
- api/src/pcapi/routes/backoffice/offers/blueprint.py
- api/src/pcapi/routes/backoffice/utils.py
inner join on educational_institution was not applied when only Marseille en Grand was set, which caused too many SQL rows, then less results than Marseille en Grand + Ministry, which applied inner join properly.
The issue was about "inner_join" + "custom_filter" in advanced search filter.
Ticket Jira : https://passculture.atlassian.net/browse/PC-34366
Testé en local avec 100 résultats max dans la recherche.
Pour vérifier en test auto il faudrait créer trop d'objets.
> (PC-34366)[BO] fix: filter on Marseille en Grand in collective offers

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/patch_publish_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34083
**Avant**
Sur le portail pro, il était possible d'éditer en de publier une offre en brouillon même si l'EAN était déjà utilisé par une offre publiée.
Pour l'offre en brouillon, il faut la créer, en publier une avec le même EAN et revenir dessus : il n'y a plus de vérification sur l'EAN.
**Après**
La vérification au niveau de l'EAN se fait au moment de la publication et de l'édition d'un brouillon d'offre, et plus seulement à sa création.
> (PC-34083)[API] fix: pro: draft offer: always check if EAN is used

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/enum.py
- api/tests/connectors/virustotal_test.py
- api/tests/core/bookings/test_repository.py
- api/tests/core/external/user_automations_test.py
- api/tests/core/finance/test_api.py
- api/tests/core/users/test_api.py
- api/tests/core/users/test_models.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/finance_test.py
- api/tests/routes/backoffice/individual_bookings_test.py
- api/tests/routes/native/openapi_test.py
- api/tests/routes/native/v1/favorites_test.py
- api/tests/sandboxes/scripts/create_industrial_app_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34162
Créer le nouveau type de deposit
Vide pour l'instant
> (PC-34162)[API] feat: credit v3 - create new deposit when v3 active

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250129T103506_8ee08df65b28_add_closed_validation_status_to_offerer.py
- api/src/pcapi/core/history/models.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/models/validation_status_mixin.py
- api/src/pcapi/routes/backoffice/filters.py
- api/src/pcapi/routes/backoffice/offerers/forms.py
- api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
- api/src/pcapi/routes/backoffice/offerers/validation_repository.py
- api/src/pcapi/routes/backoffice/templates/components/badges.html
- api/src/pcapi/routes/backoffice/templates/components/history/actions.html
- api/src/pcapi/routes/backoffice/templates/offerer/get.html
- api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_closed_offerers.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/backoffice/venues_test.py
This commit is a first step which defines the new status, creates an offerer in the sandbox and display it properly in the backoffice.
Next steps:
- Check and adapt the behevior for their offers in the application
- Check and adapt the behavior in PC Pro
- Implement transitions from VALIDATED to CLOSED
Ticket Jira : https://passculture.atlassian.net/browse/PC-34250
> (PC-34250)[BO] feat: new CLOSED status in offerer lifecycle

- api/src/pcapi/routes/auth/discord.py
- api/src/pcapi/routes/auth/forms/fields.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34390
> (PC-34390)[API] fix: log recaptcha errors and remove token length limit

- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/patch_offer_test.py
- api/tests/routes/pro/post_draft_offer_test.py
- api/tests/routes/pro/post_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34381
> (PC-34381)[API] feat: Update offer ean field when offer extraData contains ean info

- api/src/pcapi/routes/external/users_subscription.py
- api/tests/core/subscription/ubble/end_to_end/test_subscription_via_ubble.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34344
> (PC-34344)[API] feat: add a dummy webhook for ubble

- api/src/pcapi/routes/public/individual_offers/v1/addresses.py
- api/tests/routes/public/individual_offers/v1/get_search_addresses_test.py
- api/tests/routes/public/individual_offers/v1/post_address_test.py
To prevent incoherent addresses in case of big cities
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34357
> (PC-34357)[API] fix: use postal code sent by provider if address not found on BAN API

- api/tests/routes/pro/get_venues_test.py
Dans certain cas de sequence nous avons un ordre alphabetique qui n'est pas respecter :
"Le Petit Rintintin 99" > "Le Petit Rintintin 98" > "Le Petit Rintintin 100"
Exemple de run en erreur https://github.com/pass-culture/pass-culture-main/actions/runs/13159480726
> (BSR)[PRO] fix: Flaky test depending on order

- pro/src/commons/store/StoreProvider/StoreProvider.tsx
- pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.spec.tsx
- pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.tsx
- pro/src/components/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx
- pro/src/components/IndividualOffer/SummaryScreen/SummaryScreen.tsx
- pro/src/components/RedirectToBankAccountDialog/RedirectToBankAccountDialog.tsx
- pro/src/components/SignupJourneyForm/Validation/Validation.tsx
- pro/src/components/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx
- pro/src/pages/IndividualOfferWizard/IndividualOfferWizard.tsx
- pro/src/pages/OfferType/OfferType.tsx
- pro/src/pages/OfferType/OfferType/OfferType.tsx
- pro/src/pages/Onboarding/OnboardingOfferIndividual/OnboardingOfferIndividual.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34321
- **[Commit 1](https://github.com/pass-culture/pass-culture-main/pull/16103/commits/b03351b0dbe10626b717f019864608f83ad6a79b)** : Fix d'un problème (régression) ➡️  au clic sur "manuellement" sur la page `/onboarding/individuel` on est redirigé vers `/onboarding` au lieu de poursuivre vers la créa d'offre.
> [!NOTE]
> Le bug venait du fait que le récent hook `useHasAccessToDidacticOnboarding()` s'initialise avec la valeur "undefined" et se met à jour avec "useEffect" à la suite d'un retour de firebase.
>
> Or les composant de page qui lisaient le retour de `useHasAccessToDidacticOnboarding()` obtenaient un "undefined" et testaient la condition : `if ( … && !isDidacticOnboardingEnabled)` qui équivaut …
> (PC-34321)[PRO] fix: Fix unintended redirection to /onboarding when creation first offer

- api/src/pcapi/core/finance/backend/base.py
- api/src/pcapi/core/finance/backend/cegid.py
- api/src/pcapi/core/finance/commands.py
- api/src/pcapi/core/finance/external.py
- api/tests/core/finance/test_backends.py
Utilisation de la valeur absolue des montants des invoices lors du push vers cegid
> (BSR)[API] fix: correctly set the debit note's amount when pushing to cegid

- .github/workflows/dev_on_pull_request_workflow.yml
Correction du pro qui se déploie systématiquement même si il n'est pas changé dès qu'il y a un changement sur l'API
> (BSR)[PRO] ci: stop deploying pro when only api change

- pro/src/components/IndividualOffer/StocksEventCreation/AddRecurrencesButton.tsx
- pro/src/ui-kit/DialogBuilder/DialogBuilder.module.scss
- pro/src/ui-kit/DialogBuilder/DialogBuilder.spec.tsx
- pro/src/ui-kit/DialogBuilder/DialogBuilder.stories.tsx
- pro/src/ui-kit/DialogBuilder/DialogBuilder.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34260
**Objectif**
Créer une variation du dialog qui s'ouvre en mode "drawer"
- Ajout des props title et footer pour a terme centraliser les styles des titres de dialog & du separator + padding du footer
- Fix du click sur la scrollbar qui ferme le dialog dans le cas du drawer
**A noter**
Le formulaire de récurrence a temporairement été mis en "drawer" dans le dernier commit pour permettre à Marion de tester sur l'url de la PR.
https://github.com/user-attachments/assets/3dc6cfd5-c0ad-4514-a695-16e23c16883c
> Pc 34260 drawer

- .github/workflows/dev_on_pull_request_workflow.yml
- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_tests_pro.yml
- pro/vite.config.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34428
> PC-34428 BSR pro shard strategy

- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34125
Tentative de fix d'un bug difficile à reproduire lors de la fusion de deux produits qui a lieu lors de la synchronisation d'offres de cinéma.
Il semblerait qu'avec les transactions, les flush, etc. on puisse se retrouver dans un état étrange où l'offre est censée être rattachée au nouveau produit... mais pas vraiment.
Je n'ai pas réussi à reproduire le bug en local mais vu la différence entre les tests et la production à ce niveau-là, je ne suis pas certain que ce soit possible.
Et vu le contexte de l'erreur, j'espère que ce simple flush() suffira. A voir... au moins, ça ne devrait rien casser.
> (PC-34125)[API] fix: kinda: flush after product merge

- README.md
> (BSR) docs: Replace logo in README

- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/offers/test_models.py
- api/tests/core/search/test_api.py
- api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34454
> (PC-34454)[API] feat: add publicationDate to Algolia serializer

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250205T140815_a534059325fe_create_chronicle_external_id_column.py
- api/src/pcapi/alembic/versions/20250205T141711_8e97f8429b91_set_chronicle_external_id_not_null.py
- api/src/pcapi/alembic/versions/20250205T142335_117b23c66633_drop_column_chronicle_formId.py
- api/src/pcapi/core/chronicles/api.py
- api/src/pcapi/core/chronicles/factories.py
- api/src/pcapi/core/chronicles/models.py
- api/tests/core/chronicles/test_api.py
- api/tests/core/users/test_api.py
Renommer chronicle.formId en chronicle.externalId par cohérence avec le reste de la bdd. On  profite du fait que la table soit encore petite pour pouvoir le faire facilement.
> (BSR)[API] chore: rename chronicle.formId to chronicle.externalId

- .github/workflows/dev_on_pull_request_workflow.yml
- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_tests_pro_e2e.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34427
> (PC-34427) ci: parallelized e2e

- api/src/pcapi/core/educational/commands.py
Ticket Jira (ou description si BSR) : suppression de la commande `notify_pro_users_one_day` qui n'est pas utilisée (on a à la place `eac_notify_pro_one_day_before` et `eac_notify_pro_one_day_after`)
On peut vérifier sur le repo deployment : https://github.com/search?q=repo%3Apass-culture%2Fpass-culture-deployment%20eac_notify_pro_one_day&type=code
> (BSR)[API] feat: remove unused notify_pro_users_one_day command

- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/core/offers/test_api.py
- api/tests/routes/public/individual_offers/v1/patch_date_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34142
Fix rapide concernant la mise à jour des stocks.
Avant
Impossible de détecter que la nouvelle date et l'actuelle sont en fait les mêmes : celle qui vient de la base de données n'a pas d'information de fuseau horaire, le paramètre d'entrée de la fonction l'a. 
Après
On retire l'information du fuseau horaire le temps de comparer les deux dates avant de déterminer s'il y a eu un changement à ce niveau-là.
> (PC-34142)[API] fix: edit stock: compare dates without tz

- .github/workflows/dev_on_workflow_tests_api.yml
https://passculture.atlassian.net/browse/PC-34512
- output en couleurs
- 1 ligne par fichier plutôt qu’une ligne par fonction de test
- Le job Pytest report ne doit pas échouer en plus du job de test
- Ne pas publier de job summary pour les jobs pytest réussis
exemple:
https://github.com/pass-culture/pass-culture-main/actions/runs/13245381814/job/36970834632?pr=16259
> (PC-34512) ci: Pytest output tweaks

- api/src/pcapi/core/search/__init__.py
- api/src/pcapi/core/search/backends/algolia.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33538
This is a far from perfect fix but hopefully should help. It does limit the time during which read locks are kept by the index_offers_in_algolia_by_offer cron.
Although it does not write anything in the DB by the time of this commit, it does read offers though and does not close its transaction untill all the offers are sent to Algolia.
This has kept read lock for very long times (60+ minutes). By rollbacking, this commit should release the locks on a regular basis. Commit may not work as we use savepoints for subtransactions and commiting the savepoint will only move the read locks into the transaction whereas the rollback should remove them. However, it probably will not be enough as each subtransaction may last around 60 …
> (PC-33538)[API] fix: limit index_offers_in_algolia_by_offer

- .github/workflows/dev_on_workflow_tests_pro.yml
- pro/vite.config.ts
Fix coverage : https://passculture.atlassian.net/browse/PC-34428
> (BSR)[PRO] fix: fix coverage reports

- pro/src/pages/IndividualOffers/IndividualOffers.tsx
- pro/src/pages/IndividualOffers/IndividualOffersContainer/components/HeadlineOfferBanner/HeadlineOfferBanner.spec.tsx
- pro/src/pages/IndividualOffers/IndividualOffersContainer/components/HeadlineOfferBanner/HeadlineOfferBanner.tsx
- pro/src/pages/IndividualOffers/__specs__/IndividualOffers.spec.tsx
- pro/src/pages/IndividualOffers/context/IndividualOffersContext.spec.tsx
- pro/src/pages/IndividualOffers/context/IndividualOffersContext.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34397
- Ajout du localStorage pour mémoriser la fermeture.
- Fermer la bannière lorsqu'une offre est mise en avant.
> (PC-34397)[PRO] feat: use localStorage to never display headline offer banner again once closed

- api/src/pcapi/core/users/factories.py
The new eligibility should have its own fraud check eligibility, instead of defaulting to EligibilityType.AGE18
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34523
> (PC-34523)[API] fix: beneficiary factory fraud check eligibility

- api/poetry.lock
- api/pyproject.toml
This lib is used to upload files to S3 servers that currently do not support 1.36.
Re-upgrade will be done later, on their notice.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34507
> (PC-34507)[API] fix: downgrade boto3 back to 1.35

- api/src/pcapi/core/finance/siret_api.py
- api/src/pcapi/routes/backoffice/venues/blueprint.py
- api/tests/routes/backoffice/move_siret_test.py
Test was skipped because of session restarted in the code, to ensure that flask command did not commit anything tried before. Command has already been removed.
Skipped test was already implemented in superclass and _assert_move_siret_ok_response.
Ticket Jira : https://passculture.atlassian.net/browse/PC-34447
> (PC-34447)[API] test: enable ApplyMoveSiretTest.test_move_siret_ok

- api/src/pcapi/core/mails/transactional/bookings/booking_withdrawal_updated.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/patch_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33865
> (PC-33865)[API] chore: add atomic to offer routes part 2

- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v1/post_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28095
Ajout d'un log qui nous permettra d'identifier si l'utilisation d'un enum de genre musical est encore (très) utilisé ou non et si oui, par qui.
L'idée étant de supprimer cet enum obsolète plus tard.
> (PC-28095)[API] feat: public API: add warning log for deprecated enum

- pro/src/commons/core/Offers/utils/__specs__/hasSearchFilters.spec.ts
- pro/src/commons/core/Offers/utils/hasSearchFilters.ts
- pro/src/components/CollectiveOffersTable/CollectiveOffersTable.tsx
- pro/src/components/OffersTable/OffersTable.tsx
- pro/src/components/OffersTable/OffersTableSearch/utils.ts
- pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx
- pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/CollectiveOffersScreen.tsx
- pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.tsx
- pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx
- pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/IndividualOffersTable.tsx
- pro/src/pages/IndividualOffers/__specs__/IndividualOffers.spec.tsx
- pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
- pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34013
> (PC-34013)[PRO] feat: decorrelate nameOrIsbn from offer filters

- api/src/pcapi/core/search/__init__.py
- api/src/pcapi/core/search/backends/algolia.py
- api/src/pcapi/core/search/backends/base.py
- api/src/pcapi/core/search/backends/redis_queues.py
- api/src/pcapi/core/search/backends/serialization.py
- api/tests/core/search/test_api.py
- api/tests/core/search/test_backend_algolia.py
- api/tests/core/search/test_serialize_algolia.py
The AlgoliaBackend used to index offers to Algolia had too many concepts embedded within:
- the communication with Algolia
- the Redis queues and hashmaps management
- the object's serialization
This commit split those 3 area into different parts.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34592
> (PC-34592)[API] refactor: split Algolia indexing concepts appart

- pro/src/components/UserPasswordForm/UserPasswordForm.tsx
- pro/src/components/UserPasswordForm/__specs__/UserPasswordForm.spec.tsx
- pro/src/components/UserPasswordForm/validationSchema.ts
- pro/src/ui-kit/formV2/ValidationMessageList/ValidationMessageList.module.scss
- Migration du formulaire de modification du mot de passe vers `react-hook-form`
- Ajout de tests manquants sur l'affichage des erreurs.
> (BSR)[PRO] feat: Migrates <UserPasswordForm/> to react-hook-form

- api/poetry.lock
- api/pyproject.toml
- api/src/pcapi/celery_tasks/celery.py
- api/src/pcapi/celery_tasks/celery_worker.py
- api/src/pcapi/celery_tasks/sendinblue.py
- api/src/pcapi/core/external/sendinblue.py
- api/src/pcapi/core/mails/backends/sendinblue.py
- api/src/pcapi/core/mails/transactional/send_transactional_email.py
- api/src/pcapi/flask_app.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/settings.py
- api/src/pcapi/tasks/sendinblue_tasks.py
- api/start-celery-worker.sh
- api/tests/conftest.py
- api/tests/core/mails/mails_celery_test.py
- api/tests/core/mails/transactional/test_send_transactional_email.py
- docker-compose-backend.yml
Utilisation de celery pour lancer les tâches asynchrones liées au mail (sous feature flag).
Voici la configuration utilisée (qui pourrait être changée)
`acks_late` et `task_reject_on_worker_lost` mis par défaut pour éviter de perdre la tâche si le worker est tué (⚠️  cela peut faire que la tâche se joue 2 fois).
`retry` sur un type d'erreur en particulier, sur les autres erreurs la tâche est acquitée.
> (PC-34345)[API] setup celery tasks for mails

- .github/workflows/dev_on_workflow_tests_api.yml
Actuellement les tests pylint mettent 2mins 34s. En diminuant le nombre de jobs en parallèle on évite d'overcharged les runners github ne disposant que de 4 CPU
> Bsr improve pylint workflow

- .github/workflows/dev_on_workflow_deploy_app_engine_image_resizing.yml
Une mise à jour de la gcloud cli a eu lieu le 19 Fevrier. Cette version comporte des Breaking change, notamment
```
*   **(Google Cloud CLI)** Removed explicit use of `true/false` values in `--user-output-enabled` flag.
*   **(Container)** Fixed missing KeyError when parsing the `~/.kube/config` file. File is now
*   **(Container)** recreated from scratch when such a corrupted entry
*   **(Container)** is found in it. This is a breaking change as recreating the config may cause
*   **(Container)** entries for already authenticated contexts to be lost.
```
> (BSR)[API] ci: Remove user-output-enabled since gcloud cli 511.0.0 remove it

- api/src/pcapi/core/users/factories.py
- api/tests/core/users/test_generator.py
```python
development❯ from pcapi.core.users.factories import ProfileCompletedUserFactory
...: from datetime import datetime
...: 
...: user = ProfileCompletedUserFactory(age=16, beneficiaryFraudChecks__dateCreated=datetime(2024, 12, 1))
...: user.eligibility
<EligibilityType.UNDERAGE: 'underage'>
```
> (BSR)[API] feat: use dateCreated kwarg in completed profile user factory

- pro/src/app/App/App.tsx
- pro/src/components/IndividualOffer/SummaryScreen/SummaryScreen.tsx
- pro/src/components/SignupJourneyForm/Validation/Validation.tsx
- pro/src/components/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx
- Fix des redirections entre `/accueil` et `/onboarding` à la fin du parcours d'inscription (en fonction de si l'offerer est déjà activé ou non).
Mise à jour des différents états du store selon les cas.
- Fix du problème de redirection vers la page des remboursements bancaires à la fin de la création de la 1ère offre dans l'onBoarding.
> (BSR)[PRO] hotfix: Didactic onboarding redirections

- api/src/pcapi/connectors/api_adresse.py
- api/tests/connectors/api_adresse/api_adresse_test.py
... when searching for an address
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34697
> (PC-34697)[API] fix: Ensure we don’t cache wrongly empty BAN response

- api/src/pcapi/connectors/dms/api.py
- api/src/pcapi/connectors/dms/exceptions.py
- api/tests/routes/backoffice/update_request_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34753
> (PC-34753)[BO] fix: don't alert Sentry when DS connection fails on user action

- pro/src/commons/context/HeadlineOfferContext/HeadlineOfferContext.spec.tsx
- pro/src/commons/context/HeadlineOfferContext/HeadlineOfferContext.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34728
> (PC-34728)[PRO] fix: refresh indiv. list offer after headline offer deletion

- .github/dependabot.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34687
**Objectif**
Laisser dependabot bump automatiquement les dépendances du front de la doc.
> (PC-34687)[PRO] docs: Dependabot auto bump of frontend app.

- api/tests/routes/pro/patch_offerer_bank_accounts_test.py
ActionHistory.actionDate server default is set to the database now().
Multiple objects written almost at the same time may have different
insertions order in the db, making the column flaky for sorting.
> (BSR)[API] test: do not rely on ordered creation date in flaky test

- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/users/models.py
- api/tests/core/offerers/test_models.py
- api/tests/core/search/test_api.py
- api/tests/core/search/test_commands_indexation.py
- api/tests/core/search/test_integration.py
- api/tests/core/users/test_models.py
- api/tests/routes/pro/get_offerer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34727
Les contraintes sur la présence d'une offre individuelle et l'offerer actif n'existaient pas, c'est désormais le cas.
> (PC-34727)[PRO] fix: A user has a partner page only if managing a permanent, non virtual venue with at least one individual offer

- api/src/pcapi/core/finance/api.py
- api/tests/core/subscription/test_api.py
At every new deposits or recredits, the frontend needs recreditAmountToShow to be set.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34811
> (PC-34811)[API] feat: always update recredit amount to show

- api/src/pcapi/core/finance/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34862
Turns out not flushing makes `update_external_user` throw the biggest tantrum (`CardinalityViolation` and whatnot)
> (PC-34862)[API] fix: flush after expiring deposit

- pro/src/components/OffersTable/OffersTableHead/OffersTableHead.module.scss
- pro/src/components/OffersTable/OffersTableHead/OffersTableHead.tsx
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34819
Les checkbox sur la liste des offres collectives et indiv avait disparu -> on les réaffiche
Ne plus avoir de label qui n'est pas aligné avec la checkbox
> (PC-34819)[PRO] fix: display checkbox in list offer

- api/src/pcapi/routes/public/individual_offers/v1/bookings.py
Ticket Jira (ou description si BSR) : La méthode `check_is_usable` est déjà appelée dans `mark_as_used`.
> (BSR)[API] refactor: remove unecessary check in `validate_booking_by_token`

- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx
- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx
- pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx
- pro/src/ui-kit/MultiSelect/MultiSelect.module.scss
- pro/src/ui-kit/MultiSelect/MultiSelect.stories.tsx
- pro/src/ui-kit/MultiSelect/MultiSelect.tsx
Cette PR enlève le fielLayout du multiselect pour éviter les effets de bord, la recommandation est de ne plus utilisé ce composant dans les composants. Il pose des problèmes pour le positionnement des inputs, les éléments de design ne doivent pas gérer leur positionnement au risque de devoir écraser les styles depuis le niveau du dessus.
> (BSR)[PRO] fix: remove field layout from multiselect

- api/src/pcapi/core/users/eligibility_api.py
- api/tests/core/users/test_eligibility.py
Fix https://pass-culture.sentry.io/issues/31386138/
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34891
> (PC-34891)[API] fix: crash known birthday calculation on empty action history

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/models/feature.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/post_draft_offer_test.py
**Description:** Suppression d'un FF temporaire `WIP_URL_IN_OFFER_DRAFT`
> (BSR)[API] feat: remove `WIP_URL_IN_OFFER_DRAFT` ff

- api/src/pcapi/core/offers/models.py
Somehow the hybrid properties' expression are not evaluated on usage but rather at the start time when a server is started. Print statements within those functions will only appear when the server is started.
Surprisingly they are reevaluated between the tests. Anyway, one should not rely on anything dynamic in the hybrid properties' expression part and should only include defered calls.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34046
> (PC-34046)[API] fix: use PostgresQL's now instead of Python's

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
- api/tests/core/subscription/test_api.py
Deposit upsertion should expire the underage credit, not the creation.
Ref: c62ee19f
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34895
> (PC-34895)[API] fix: expire underage credit before checking for active credit

- pro/src/pages/LostPassword/LostPassword.tsx
- pro/src/pages/LostPassword/__specs__/LostPassword.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34105
- Corrections de wording.
> (PC-34105)[PRO] fix: Lostpassword 2025 wording.

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/exceptions.py
- api/src/pcapi/core/users/factories.py
- api/tests/core/finance/test_api.py
When recrediting a big page of users, `get_wallet_balance` likes to
crash complaining that there is two active deposits. This messes up the
whole page transaction, so we work around it by setting the expiration
date to earlier.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34940
Ce test à lancer dans le flask shell échoue sans le commit `fix: expire deposit even sooner` :  
```
import datetime
from dateutil.relativedelta import relativedelta
import time_machine
from pcapi import settings
from pcapi.core.finance import api
from pcapi.core.users import factories as users_factories
one_year_before_decree = settings.CREDIT_V3_DECREE_DATETIME - relativedelta(years=1)
next_week = datetime.datetime.utcnow() + relativedelta(weeks=1)
with …
```
> (PC-34940)[API] fix: expire deposit even sooner

- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/tests/routes/backoffice/accounts_test.py
Fix de la frise du parcours d'inscription: éviter l'erreur 500 si la date de naissance du jeune  est erronée
> (BSR)[BO] fix: avoid crash when displaying subscription tunnel for users with wrong birthdate

- api/src/pcapi/celery_tasks/sendinblue.py
- api/src/pcapi/celery_tasks/tasks.py
- api/tests/core/mails/mails_celery_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34345
Lorsque Celery passe une task avec le serializer JSON il utilise la __repr__() de l'objet et donc les champ de type Decimal par exemple sont conservés. Cela pose problème à la lib sendinblue qui s'attend à recevoir un objet JSON serializable, mais le champ Decimal ne l'est pas.
On a pas le problème sur les cloud_tasks car on a cette ligne qui est jouée : `payload = json.loads(payload.json())` et elle a pour effet de transformer les champs qui ne sont pas JSON serializable en champs qui le sont.
Cette PR reproduit ce comportement pour les cloud_task à l'aide d'un décorateur. J'ai également rajouté un petit test avec le cas concret que j'ai rencontré pour s'assurer qu'on ne retombe pas dessus.
> (PC-34345) setup decorator for celery tasks

- api/documentation/package-lock.json
- api/documentation/package.json
- api/documentation/src/components/HomepageFeatures/index.tsx
- api/documentation/src/components/HomepageFeatures/styles.module.css
- api/documentation/src/pages/index.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34938
**Objectif**
Améliorer l'accessibilité de la page d'accueil de la doc api.
- Ajout de texte alternatif sur les images
- Structure des features en liste html
- Correction de la hiérarchie des titres
Et au passage suppression de la dépendance pour concaténer les classes qui est pas très utile
> (PC-34938)[API] docs: Improve doc landing page accessibility.

- api/src/pcapi/connectors/dms/graphql/beneficiaries/get_applications_with_details.graphql
Ticket Jira : https://passculture.atlassian.net/browse/PC-35015
`updatedAt` était bien dans `get_single_application_details.graphql` mais manquant dans `get_applications_with_details.graphql`.
> (PC-35015)[API] fix: missing DS annotation date and time

- api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34531
> (PC-34531)[API] fix: use object_id for artists product mediations

- api/src/pcapi/core/users/models.py
The join between UserOfferer and Offer was missing, leading to unhealthy cartesian product between the two tables, possible perfomance issues and non fonctional check on offerer being active.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35019
> (PC-35019)[API] fix: avoid cartesian product on partner page check

- pro/src/ui-kit/formV2/Checkbox/Checkbox.module.scss
- pro/src/ui-kit/formV2/Checkbox/Checkbox.spec.tsx
- pro/src/ui-kit/formV2/Checkbox/Checkbox.stories.tsx
- pro/src/ui-kit/formV2/Checkbox/Checkbox.tsx
- pro/src/ui-kit/formV2/EmailSpellCheckInput/EmailSpellCheckInput.module.scss
- pro/src/ui-kit/formV2/EmailSpellCheckInput/EmailSpellCheckInput.spec.tsx
- pro/src/ui-kit/formV2/EmailSpellCheckInput/EmailSpellCheckInput.stories.tsx
- pro/src/ui-kit/formV2/EmailSpellCheckInput/EmailSpellCheckInput.tsx
- pro/src/ui-kit/formV2/EmailSpellCheckInput/suggestEmail.ts
- pro/src/ui-kit/formV2/PhoneNumberInput/CodeCountrySelect/CountryCodeSelect.module.scss
- pro/src/ui-kit/formV2/PhoneNumberInput/CodeCountrySelect/CountryCodeSelect.tsx
- pro/src/ui-kit/formV2/PhoneNumberInput/PhoneNumberInput.module.scss
- pro/src/ui-kit/formV2/PhoneNumberInput/PhoneNumberInput.spec.tsx
- pro/src/ui-kit/formV2/PhoneNumberInput/PhoneNumberInput.stories.tsx
- pro/src/ui-kit/formV2/PhoneNumberInput/PhoneNumberInput.tsx
- pro/src/ui-kit/formV2/PhoneNumberInput/constants.ts
- 1er commit : Met à jour les composants `<Checkbox>` et `<EmailSpellCheckInput>` vers /formV2/ pour react-hook-form 
- 2ème commit : Réécriture complète du coeur du composant `<PhoneNumberInput>` vers /formV2/ pour react-hook-form
- Le composant utilise toujours deux states internes pour gérer la partie préfixe du numéro (ex: +33) et le reste du numéro, mais effectue une remontée de la valeur combinée vers le parent en exposant une ref customisée
> (BSR)[PRO] feat: Migrates <Checkbox>, <EmailSpellCheckInput> and <PhoneNumberInput> for react-hook-form

- pro/src/ui-kit/SelectedValuesTags/SelectedValuesTags.module.scss
BSR regression design sur le multiselect suite à l'intégration de celui-ci dans la page chiffre d'affaire 
AVANT 
APRÈS
> (BSR)[PRO] fix: excess padding on selected tags

- api/bin/generate_script_file.py
Modif sur `generate_script_file` pour le rendre plus simple à appeler
`bin/generate_script_file.py <my_script_namespace>`
au lieu de
`python bin/generate_script_file.py --namespace <my_script_namespace>`
> (BSR) feat: update command to generate a script file

- api/src/pcapi/core/finance/api.py
- api/tests/core/users/test_api.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
This commits handles non-regular data that to exist in production Further investigation may render this commit useless, however there is no garantee
Corriger le non-cumul de crédit au déblocage des 150€ pour certains users
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34983
> (PC-34983)[API] fix: reactivate underage deposits before 17-18 activation

- pro/src/pages/LostPassword/LostPassword.module.scss
- pro/src/pages/LostPassword/LostPassword.tsx
- Corrections d'alignements pour le nouveau design de la page mot de passe perdu.
> (BSR)[PRO] style: Changes to password page style.

- pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx
- pro/src/pages/VenueEdition/OpeningHoursReadOnly/__specs__/OpeningHoursReadOnly.spec.tsx
- pro/src/pages/VenueEdition/VenueEdition.module.scss
- pro/src/pages/VenueEdition/VenueEdition.tsx
- pro/src/pages/VenueEdition/VenueEditionForm.tsx
- pro/src/pages/VenueEdition/VenueEditionFormScreen.module.scss
- pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx
- pro/src/pages/VenueEdition/VenueEditionHeader.tsx
- pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx
- pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
- pro/src/pages/VenueEdition/__specs__/VenueEditionHeader.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34746
> (PC-34746)[PRO] feat: refacto partner page display (moving / deleting / renaming sections) in context of isOpenToPublic feature

- api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35036
**Objectif**
Ajout du FF `WIP_ENABLE_EVENT_WITH_OPENING_HOUR`.
> (PC-35036)[API] fix: Add WIP_ENABLE_EVENT_WITH_OPENING_HOUR  FF.

- api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35083
```
The creation of array `numericAttributesForFiltering` implies
that all facets not mentioned in this array won't be able to
be used as numeric filters. Whereas if the array is not specified,
all facets can be used as numeric filters. This is what we want
for now.
cf: https://www.algolia.com/doc/api-reference/api-parameters/numericAttributesForFiltering/#how-to-use
```
> (PC-35083)[API] fix: delete numeric filters in Algolia conf

- pro/src/pages/Reimbursements/Income/IncomeResultsBox/IncomeResultsBox.module.scss
- pro/src/pages/Reimbursements/Income/IncomeResultsBox/IncomeResultsBox.tsx
- pro/src/ui-kit/Button/Button.module.scss
- pro/src/ui-kit/Tooltip/Tooltip.module.scss
- pro/src/ui-kit/Tooltip/Tooltip.spec.tsx
- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35051
**Objectif**
Faire disparaitre l'espace qui apparait en dessous des liens ternary, et des checkbox. Et corriger l'affichage du tooltip income (voir screen).
**Avant/après**
**Tooltip avant/après**
> (PC-35051)[PRO] fix: Useless margin added by display inline.

- pro/src/ui-kit/form/Select/Select.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34665
Avant : 
Après :
> (PC-34665)[PRO] feat: fix space between option and icon in select

- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34710
and fix missing condition on get_venues_with_same_pricing_point which returns any venue on the same offerer
> (PC-34710)[API] feat: move offer with past stocks

- api/src/pcapi/core/educational/constants.py
- api/src/pcapi/core/educational/testing.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
- api/tests/routes/pro/patch_collective_offer_template_test.py
- api/tests/routes/pro/patch_collective_offer_test.py
- api/tests/routes/pro/post_collective_offers_template_test.py
- api/tests/routes/pro/post_collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34921
> (PC-34921)[API] Ajouter des validations sur les routes patch et post pour les champs oa

- api/src/pcapi/routes/backoffice/venues/blueprint.py
- api/tests/routes/backoffice/venues_test.py
```
PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_unique_offerer_address_per_label"
```
Ticket Jira : https://passculture.atlassian.net/browse/PC-35177
> (PC-35177)[BO] fix: exception when refreshing after exception during flush()

- api/poetry.lock
- api/pyproject.toml
Ceci devrait fix https://github.com/pass-culture/pass-culture-main/security/dependabot/342
> (BSR)[BO] fix: Update jinja2 to fix vulnerability

- api/src/pcapi/connectors/apps_flyer.py
- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/routes/native/v1/authentication.py
- api/src/pcapi/workers/apps_flyer_job.py
- api/tests/core/bookings/test_api.py
- api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/(PC-34889
Cette PR ajoute le tracking des événements AppsFlyer pour suivre les conversions clés dans l'application :
- Validation d'email lors de l'inscription
- Réservation d'une offre
- af_complete_registration_XX : Déclenché lors de la validation d'email
- Différencié par âge : 15, 16, 17, 18, 19+
- Inclut l'ID utilisateur et firebase_pseudo_id
- af_complete_book_offer : Déclenché lors d'une réservation
- Inclut les détails de la réservation (offre, prix, catégorie)
- Ajout de log_offer_event dans le connecteur AppsFlyer
- Intégration dans le flow de réservation via bookings/api.py
- Intégration dans le processus de validation d'email
- Utilisation de jobs asynchrones pour éviter l'impact sur les …
> (PC-34889)[API] feat: Add new AppsFlyer events

- pro/src/commons/utils/__specs__/getFormattedAddress.spec.ts
- pro/src/commons/utils/getFormattedAddress.ts
- pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx
- pro/src/components/ExternalAccessibility/ExternalAccessibility.tsx
- pro/src/components/ExternalAccessibility/ExternalAccessibilityCollapse/ExternalAccessibilityCollapse.tsx
- pro/src/components/SummaryLayout/SummaryLayout.module.scss
- pro/src/components/SummaryLayout/SummarySubSubSection.tsx
- pro/src/pages/VenueEdition/AccessibilityReadOnly/AccessibilityReadOnly.tsx
- pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.module.scss
- pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx
- pro/src/pages/VenueEdition/OpeningHoursReadOnly/__specs__/OpeningHoursReadOnly.spec.tsx
- pro/src/pages/VenueEdition/VenueEditionForm.tsx
- pro/src/pages/VenueEdition/VenueEditionFormScreen.module.scss
- pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx
- pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34990
> (PC-34990)[PRO] feat: under isOpenToPublic FF, reorganize readonly venue settings headings (and fix edition ones)

- pro/cypress/e2e/financialManagement.cy.ts
- pro/src/app/App/hook/__specs__/useLogExtraProData.spec.tsx
- pro/src/commons/hooks/swr/useOffererNamesQuery.spec.tsx
- pro/src/commons/hooks/swr/useOffererNamesQuery.ts
- pro/src/commons/utils/__specs__/hardRefresh.spec.ts
- pro/src/commons/utils/hardRefresh.ts
- pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.spec.tsx
- pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.tsx
- pro/src/pages/Homepage/Homepage.tsx
- pro/src/pages/Homepage/__specs__/Homepage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35114
> [!NOTE]
> Nouveau hook `useOffererNamesQuery` dont le but est de récupérer les "offererNames"
>
> Ce hook combine les données du Redux store avec une requête SWR pour obtenir la liste des "offererNames".
> Si les données sont déjà présentes dans le store, elles sont renvoyées immédiatement sans faire de requête (plus éco)
> (PC-35114)[PRO] feat: Force hard refresh when changing offerer

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35180
> (PC-35180)[API] fix: give correct role when a 18yo is processed in the recredit function

- api/src/pcapi/core/offerers/models.py
- api/tests/core/offerers/test_models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-35261
The has_partner_page hybrid expression did not properly linked the venue's offers to the current venue.
Long story short, the SQL generated was similar to simplified:
SELECT venue.* FROM venue
WHERE venue.id = 978
AND (EXISTS(
SELECT 1
FROM offer
JOIN venue ON offer."venueId" = venue.id
WHERE venue."isPermanent" IS true
AND venue."isVirtual" IS false
AND venue.id = venue.id
)) = true
Note the useless venue.id = venue.id.
Using an aliased Venue table changes the SQL subquery to use an isolated venue table which can then be linked with the outer venue table through a `venue_1.id = venue.id`.
> (PC-35261)[API] fix: isolate has_partner_page SQL prop

- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35118
**Bug**
La route `GET /offers/<int:venue_id>/ean/<string:ean>` du portail pro renvoie une erreur lorsqu'on cherche à savoir si une offre active avec un EAN existe déjà ou non : la fonction chargée de la recherche part du principe que pour un lieu donné, chaque EAN (au niveau des offres) est unique, ce qui n'est pas le cas dans la pratique.
**Fix**
Si plusieurs offres actives sont trouvées, alors on enregistre un log avec l'EAN et l'identifiant du lieu et la plus récente est renvoyée. Ceci est tout à fait acceptable puisque l'intérêt principal de cette route est de savoir si un lieu a déjà une offre avec cet EAN, on ne cherche pas à identifier une offre spécifiquement.
> (PC-35118)[API] fix: if EAN is shared, return the most recent offer

- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35262
Fix : permettre aux offres dans le futur (?) d'être activées au-delà des heures piles par défaut puisque les dates de publication peuvent maintenant être tous les quarts d'heure.
> (PC-35262)[API] fix: activate future offers: update filter

- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
- api/tests/routes/pro/patch_venue_test.py
On a actuellement un get_or_create sur la factory OffererAddressFactory, on ne va donc pas recréer un objet si on appelle la factory avec les mêmes valeurs pour `("offerer", "address", "label")`.
Cela a du sens pour coller à la contrainte d'unicité, mais seulement dans le cas ou le label n'est pas None. En effet, plusieurs Venue d'un même Offerer peuvent être liés à la même Address, dans ce cas on aura plusieurs lignes avec les même valeurs `offererId, addressId, None` -> il ne faut donc pas aller chercher la même ligne dans ce cas
On supprime ici le get_or_create, il faudra potentiellement contourner la contrainte manuellement dans certains cas (en mettant un label explicite par exemple)
> (BSR)[API] feat: remove get_or_create logic in OffererAddressFactory

- pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferCreation/CollectiveOfferCreation.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferLayout/__specs__/CollectiveOfferLayout.spec.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferPreview/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreation.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferPreview/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferStock/CollectiveOfferStockCreation/CollectiveOfferStockCreation.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferStock/CollectiveOfferStockEdition/CollectiveOfferStockEdition.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.spec.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.spec.tsx
- pro/src/pages/CollectiveOfferVisibility/CollectiveOfferCreationVisibility.tsx
- pro/src/pages/CollectiveOfferVisibility/CollectiveOfferEditionVisibility.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35169
Ré-afficher le stepper pour les étapes de création d'une offre collective
Ré-afficher le menu qui s'affiche dans le récapitulatif d'une offre
> (PC-35169)[PRO] fix: display stepper for collective offer in edition

- pro/src/components/BackToNavLink/BackToNavLink.tsx
- pro/src/components/IndividualOffer/StocksThing/StockThingFormActions/StockThingFormActions.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35289
**Objectif**
Corriger le test e2e sur `createCollectiveOffer` qui fail en testing ([comme ici](https://github.com/pass-culture/pass-culture-main/actions/runs/13974991129/job/39126548885)).
Pour corriger j'ai remplacé les "min-width" qui ont été modifiés par des "max-width". A priori "min-width" est mieux, et il faudrait faire `!useMediaQuery('(min-width: 64rem)')`, mais je crois que caster la variable isMobileScreen en booléen casse aussi le test e2e. Donc je propose de rester sur du max-width pour débloquer la ci rapidement.
> (PC-35289)[PRO] fix: Use max-width for hook media queries.

- api/src/pcapi/core/external_bookings/api.py
- api/tests/routes/native/v1/bookings_test.py
Add a try/catch around client.book_ticket and raise a custom generic
error that will be handled by the controller.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35156
Ne pas laisser s'échapper une erreur lors de la réservation d'un ticket via une API externe.
En cas d'erreur : ajouter un log et en renvoyer une générique de chez nous qui devra être gérée par une fonction appelante (par exemple un contrôleur des routes de l'application native).
> (PC-35156)[API] fix: external ticket booking: handle unexpected error

- api/src/pcapi/routes/external/users_subscription.py
- api/src/pcapi/utils/lock.py
- api/tests/utils/lock_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-35301
> (PC-35301)[API] fix: DS webhook concurrent calls

- api/src/pcapi/core/mails/transactional/send_transactional_email.py
- api/tests/core/mails/transactional/test_send_transactional_email.py
Lors d'une erreur 400 sur Brevo, les emails sont anonymisés dans Sentry et le message de log, il est difficile de retrouver d'où vient l'erreur. Ajoutons les emails en clair dans les logs GCP pour visualiser l'erreur.
> (BSR)[API] feat: extra data in GCP logs to help debug invalid email

- api/src/pcapi/validation/routes/users_authentifications.py
To ease debugging of public API errors
Ticket Jira (ou description si BSR) : Ajout des tags sentry `provider-id` et `provider-name` au niveau du décorateur `@provider_api_key_required`.
> (BSR)[API] feat: add sentry tags in `@provider_api_key_required`

- .github/workflows/dev_on_pull_request_closed.yml
Rajout d'une commande pour vérifier si l'environnement de preview associé à la PR existe avant de tenter de le delete
Exemple ou il existe et ou il delete : https://github.com/pass-culture/pass-culture-main/actions/runs/14058276433/job/39362643873
Exemple ou il n'existe pas et donc il skip le delete : https://github.com/pass-culture/pass-culture-main/actions/runs/14057465924/job/39360043240
> (BSR)[PRO] ci: do not issue delete preview env command if not exists

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
- api/tests/routes/public/individual_offers/v1/patch_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35321
Fix du bug : https://pass-culture.sentry.io/issues/34393092/?alert_rule_id=155878&alert_type=issue&environment=production&notification_uuid=a7be98bb-01f4-4e90-86df-b50f84951950&project=4508776981069904&referrer=slack
> (PC-35321)[API] fix: prevent ean duplication when `extraData["ean"]` is an empty string

- api/start-celery-worker.sh
Corriger le lancement de celery en environnement de développemen et permettre de voir les logs des tâches celery.
> (BSR)[API] fix: celery worker in dev environment

- api/src/pcapi/routes/backoffice/templates/offer/details.html
- api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32138
Ajouter une ligne sur la page de détails d'une offre (dans le BO) qui indique à quel produit elle est rattachée.
S'il l'offre n'est liée à aucun produit, ne rien afficher.
> (PC-32138)[BO] feat: offer details: add product information

- api/src/pcapi/routes/backoffice/templates/venue/get.html
Ticket Jira (ou description si BSR) : On ne peut plus filtrer les offres par venueId sur PC Pro, ce bouton ne sert donc plus
> (BSR)[BO] chore: remove inefficient connect as button

- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
- api/src/pcapi/routes/backoffice/collective_offers/forms.py
- api/src/pcapi/routes/backoffice/templates/collective_offer/details.html
- api/tests/core/educational/api/test_move_collective_offer.py
- api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34671
Principalement un ajout de tests
Fonctionnalité de mouvement d'une offre collective vers une nouvelle venue disponible dans le BO (sur la page de détail d'une offre collective) si au moins une venue de destination est disponible.
Il s'agit de tester le changement de venue d'une offre collective sans restrictions pour, à terme, implémenter un script de modification de venue par lot : toutes les offres collective de cette venue A vers venue B.
L'ajout de cette option dans le BO sera supprimé.
> (PC-34671)[API] feat: Move collective offer from one venue to another

- api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Correction des offres de type livre pour qu'elles n'aient qu'un seul stock (avec 5 fois plus de quantité).
Avec plusieurs stocks sur une offre de livre, l'édition du stock sur PC Pro ne marche pas.
> (BSR)[API] fix: book offers should only have one stock

- api/src/pcapi/core/educational/factories.py
- api/tests/core/search/test_serialize_algolia.py
- api/tests/routes/adage/v1/conftest.py
- api/tests/routes/adage/v1/get_all_bookings_per_year_test.py
- api/tests/routes/pro/get_collective_offer_template_test.py
Ticket Jira (ou description si BSR) : les formats sont obligatoires quand on créé une offre collective. On ajoute une valeur dans la factory pour être cohérent (la colonne devra être rendue non-nullable ultérieurement)
> (BSR)[API] feat: add formats in collective offer factory

- api/src/pcapi/core/offerers/api.py
utiliser "message" dans un log est interdit : 
```shell
for key in extra:
if (key in ["message", "asctime"]) or (key in rv.__dict__):
raise KeyError("Attempt to overwrite %r in LogRecord" % key)
rv.__dict__[key] = extra[key]
return rv
```
> (BSR)[API] fix: do not use 'message' in logger info

- pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
- pro/src/ui-kit/formV2/DayCheckbox/DayCheckbox.module.scss
- pro/src/ui-kit/formV2/DayCheckbox/DayCheckbox.spec.tsx
- pro/src/ui-kit/formV2/DayCheckbox/DayCheckbox.stories.tsx
- pro/src/ui-kit/formV2/DayCheckbox/DayCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35383
**Objectif**
Dans le cadre du nouveau drawer de récurrence qui est un form utilisant react-hook-form, on a besoin du DayCheckbox en mode FormV2. Au passage je l'ai modifié pour ajouter un Tooltip aux inputs.
> (PC-35383)[PRO] feat: Add DayCHeckbox to FormV2 and rework it.

- api/src/pcapi/routes/public/individual_offers/v1/utils.py
- api/tests/routes/public/individual_offers/v1/get_event_test.py
- api/tests/routes/public/individual_offers/v1/get_events_test.py
- api/tests/routes/public/individual_offers/v1/get_product_by_ean_test.py
- api/tests/routes/public/individual_offers/v1/get_product_test.py
- api/tests/routes/public/individual_offers/v1/get_products_test.py
- api/tests/routes/public/individual_offers/v1/patch_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35408
Remplacer des [joinedload ](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#sqlalchemy.orm.joinedload) par des [selectinload](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#sqlalchemy.orm.selectinload), utilisés indirectement par des routes de l'API publique.
Problème : certaines routes se retrouvent à charger toutes les données liées à chaque offre d'un coup, comme ses stocks, ses catégories de prix, etc. Ce qui entraînait quelques soucis en terme de consommation mémoire.
Au passage : ne charger que le strict nécessaire pour un lieu, dans ce contexte.
> (PC-35408)[API] fix: avoid joinedload, prefer selectinload

- .github/workflows/dev_on_push_workflow_main.yml
Ticket Jira (ou description si BSR) : `algolia-config-changed` est un string, il faut ajouter `== 'true'` pour passer un boolean à l'input `apply_algolia_config `
> (BSR) fix: fix wrong type in deploy-to-testing inputs

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_future_offers.py
Ticket Jira (ou description si BSR) : corrections de la creation de Future Offers dans la Sandbox, les date de disponibilité des stocks ne sont pas valables, suppression de l'utilisation de random.
> (BSR)[Sandbox] feat: add more relevant future offers in sandbox

- api/src/pcapi/core/users/ds.py
- api/tests/core/users/ds_fixtures.py
- api/tests/core/users/test_ds.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35439
> (PC-35439)[API] feat: include old instructors in ds sync

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : le cas avec `"venueId": 424242` dans les cas de test de la sandbox ne peut plus arriver en prod suite à un rattrapage + ajout d'un check, on le supprime donc des données de test
Bonus : le dispositif national `Olympiade culturelle de PARIS 2024` n'était pas cohérent avec la vraie valeur. Avoir un cas avec `isActive=False` permet de mieux tester par ailleurs
> Remove invalid address case

- .github/workflows/dev_on_workflow_tests_pro_e2e.yml
- pro/cypress/e2e/navigation.cy.ts
- pro/src/app/App/layout/Layout.tsx
- pro/src/pages/Homepage/components/Offerers/components/PartnerPages/PartnerPages.spec.tsx
- pro/src/pages/Homepage/components/Offerers/components/PartnerPages/PartnerPages.tsx
- pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPage.tsx
- pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/__specs__/PartnerPage.spec.tsx
- pro/src/pages/Homepage/components/Offerers/components/VenueList/venueUtils.ts
- pro/src/pages/Homepage/components/VenueOfferSteps/VenueOfferSteps.tsx
- pro/src/pages/VenueEdition/VenueEditionHeader.tsx
- pro/src/pages/VenueEdition/__specs__/VenueEditionHeader.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35369
- Ne plus utiliser les données dans `venue` pour afficher l'addresse.
> (PC-35369)[PRO] fix: Do not use venue address details.

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : on a actuellement un champ `Address.street` avec la valeur `35 Bd de Sébastopol, 75001 Paris` ce qui n'est pas cohérent, on indique ici une valeur explicite
> (BSR)[API] fix: update address of some collective offers in sandbox

- api/src/pcapi/routes/pro/collective_offers.py
- api/tests/routes/pro/patch_collective_offer_test.py
Catch erreur lors du transfert d'une offre sur une venue non éligible.
Résoudre [cette erreur sentry](https://pass-culture.sentry.io/issues/35599614/?alert_rule_id=139263&alert_type=issue&environment=testing&notification_uuid=19f8bdf2-f585-4add-8e3f-fc834c56cec4&project=4508776981069904&referrer=slack)
> (BSR)[API] fix: Catch error when move offer

- api/src/pcapi/core/educational/models.py
Ticket Jira (ou description si BSR) : la property n'a plus de sens, et en plus elle ne sert pas
> (BSR)[API] chore: remove useless isEvent property on collective offers

- api/src/pcapi/core/users/eligibility_api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_eligibility.py
- api/tests/core/users/young_status_test.py
Some users fill their birth date wrong, so their first fraud checks are considered age18. We should ignore these fraud checks eligibility type when the birth date is corrected by the identity provider.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35309
> (PC-35309)[API] fix: ignore age18 fraud checks if the user was not yet 18

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
It should only apply on the venue.
Ticket Jira : https://passculture.atlassian.net/browse/PC-35485
> (PC-35485)[API] fix: move_offer should not affect the offer's location

- pro/cypress/support/commands.ts
- pro/cypress/support/index.d.ts
Ajout d'un retry pour les requêtes sandbox
> (BSR)[PRO] ci: Retrying sandbox calls.

- api/src/pcapi/workers/decorators.py
Fixes this sentry issue : https://pass-culture.sentry.io/issues/35760210/?referrer=slack&notification_uuid=e0a80cd8-d642-4dc9-9afa-8ef1cab57968&environment=staging&alert_rule_id=146084&alert_type=issue
> (BSR)[API] fix: compare unaware datetime

- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/core/educational/exceptions.py
- api/src/pcapi/core/educational/validation.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/collective_offers.py
- api/src/pcapi/routes/public/collective/endpoints/offers.py
- api/src/pcapi/routes/public/collective/serialization/offers.py
- api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
Ticket Jira (ou description si BSR) : déplacement de validation et exceptions sur national_program dans core/educational
> (BSR)[API] refactor: move national program validation in educational

- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34943
On créer une offre vitrine, elle s'affiche dans la page de recherche sur ADAGE ensuite on l'archive depuis le portail pro, elle est censé disparaitre de la page recherche et le nombre total doit diminué de 1 (après une recherche) sans avoir à recharger la page
> (PC-34943)[PRO] fix: total numbre offer in adage

- pro/src/components/HeadlineOfferBanner/components/HeadlineOfferInformationDialog.module.scss
- pro/src/components/HeadlineOfferBanner/components/HeadlineOfferInformationDialog.tsx
- pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35515
**Objectif**
Corriger l'affichage de la couleur du bouton ternary pour la bannière de l'offre à la une que j'ai cassé en appliquant les couleurs DS.
**Avant/après :**
> (PC-35515)[PRO] fix: Set specific color for locked button ternary.

- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_schedule_deploy_main_and_pro.yml
Deploy testing every hour between 7:30 to 19:30. We deploy everything, main, pro, api docs and algolia settings, like staging, production or integration deployment. 
Some things needs to be migrated to this new workflow too (maybe?) like storybook or maintenance site. 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34934
> (BSR)[API] ci: deploy testing every hour

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py
Réparation de la sandbox data suite au ticket Jira : https://passculture.atlassian.net/browse/PC-35226
Sentry : https://pass-culture.sentry.io/issues/36376435/
> (PC-35226)[API] test: fix sandbox (data)

- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarActionsBar/StocksCalendarActionsBar.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarActionsBar/StocksCalendarActionsBar.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarActionsBar/StocksCalendarActionsBar.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/__specs__/StocksEventCreation.spec.tsx
- pro/src/components/IndividualOffer/StocksEventEdition/getPriceCategoryOptions.ts
- pro/src/pages/IndividualOffer/components/ActionBar/ActionBar.tsx
- pro/src/ui-kit/ListIconButton/ListIconButton.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35415
**Objectif**
- Retravail de la structure de `StocksEventCreation` pour afficher la table des stocks quand le FF est activé
- Création du nouveau composant de la table
- Passage des "sticky actions" au même niveau quand le FF est actif pour ne pas afficher les barres l'une par dessus l'autre
WIP_ENABLE_EVENT_WITH_OPENING_HOUR
**A noter**
Les options de tri et de filtre sur la table seront ajoutées par la suite, mais la pagination doit déjà être fonctionnelle.
> (PC-35415)[PRO] feat: Rework the stocks table for event creation.

- pro/src/apiClient/adresse/apiAdresse.spec.ts
- pro/src/apiClient/adresse/apiAdresse.ts
- pro/src/apiClient/adresse/types.ts
- pro/src/apiClient/api.ts
- pro/src/commons/core/Venue/getSiretData.tsx
- pro/src/components/Address/Address.spec.tsx
- pro/src/components/Address/Address.tsx
- pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.tsx
- pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx
- pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx
- pro/src/components/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx
- pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
- pro/src/pages/VenueSettings/SiretOrCommentFields/SiretOrCommentFields.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35371
S'assure que les résultats renvoyés par l'API Adresse disposent bel et bien de numéros de rue par défaut (dits des "**numéros à la plaque**" :
> (PC-35371)[PRO] feat: Restrict <AddressSelect> results to streets with a number by default

- api/src/pcapi/core/history/models.py
- api/src/pcapi/core/offerers/api.py
- api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35284
Ajout d'un type d'ActionHistory dans le cadre du chantier de régularisation. Ajout d'une méthode pour fixer le format attendu des entrées d'historique pour ces mouvements d'offres :
- Une entrée par venue, d'origine et de destination
- Une entrée par type d'offre, individuelles et collectives
Si le découpage des migrations d'offres est différent, il faudra peut-être ajouter plus d'information dans les extraData. Il se peut que le découpage se fasse par PriceCategoryLabel et/ou par offre collective vitrine si le nombre d'offre est trop important. Ce n'est pour l'instant pas la stratégie adoptée.
> (PC-35284)[API] feat: Create new ActionHistory type for venue regularisation

- api/src/pcapi/core/operations/api.py
Sentry : https://pass-culture.sentry.io/pass-culture/api/events/c69e0cf27c534954878469962531ed8d/
> (BSR)[API] fix: Do not log an error at sync time when a form has been deleted on Typeform side

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : les id fixes dans l'appel à NationalProgramFactory donnent une erreur si l'on essaie de créer un nouveau national program (erreur d'unicité sur la clé primaire)
> (BSR)[API] fix: do not set id when creating national program in sandbox

- pro/src/commons/core/FirebaseEvents/constants.ts
- pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
- pro/src/components/StocksEventList/StocksEventList.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35533
**Objectif**
Ajouter un tracker sur le tri des tables de création/edition/read only des stocks pour étudier l'utilité de la feature. On regarde l'usage que sur l'ancienne interface (je suis par conséquent tenté de ne pas couvrir les tests des fonctions de tri existantes qui vont disparaitre sous peu).
> (PC-35533)[PRO] feat: Add tracker on stocks tables sort buttons.

- api/pyproject.toml
- api/src/pcapi/models/beneficiary_import.py
Ticket Jira (ou description si BSR) : Je supprime le dernier as_scalar() du code pour remettre le warning SQL
> (BSR)[API] chore: readd warning on as_scalar use

- pro/src/pages/SignIn/SignIn.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35576
Suite à un bug introduit avec l'onboarding didactique, cette PR le corrige en permettant à nouveau à un user en attente de rattachement à un offerer de pouvoir se connecter.
> (PC-35576)[PRO] fix: Allow non-rattached users to log in

- api/src/pcapi/core/educational/api/adage.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/routes/adage_iframe/serialization/venues.py
- api/src/pcapi/routes/adage_iframe/venues.py
- pro/src/apiClient/adage/models/VenueResponse.ts
Ticket Jira (ou description si BSR) : on remplace l'usage du champ `venue.departementCode` par le champ `address.departementCode` dans les routes adage iframe des venues
> (BSR)[ADAGE] fix: use OA for venue address in adage iframe route

- .github/workflows/dev_on_schedule_deploy_main_and_pro.yml
```
The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. 
High load times include the start of every hour. 
If the load is sufficiently high enough, some queued jobs may be dropped. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
```
[source](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule)
We had workflow that were delayed by 10-15 minutes
> (BSR)[API] ci: Change testing deployment time

- api/src/pcapi/routes/backoffice/templates/home/home.html
Afficher automatiquement le menu au chargement de la page d'accueil
> (BSR)[BO] fix: auto-display main menu on home page

- api/src/pcapi/core/external/attributes/api.py
- api/src/pcapi/core/users/models.py
- api/tests/routes/native/v1/bookings_test.py
get_wallet_balance likes to crash after expiring a deposit and creating a new one. Since we update the beneficiary's external attribute just after granting the new deposit, we work around this tendency to crash by not calling get_wallet_balance.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35445
> (PC-35445) refactor: do not call get_wallet_balance during user update

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35623
Un probable auto flush de SQLAlchemy arrivant trop tôt permet un FinanceEvent pending (sans pricingPoint) de devenir ready sans pricingPoint.
> (PC-35623)[API] fix: Pending FinanceEvent raised error when move from one venue to another

- api/src/pcapi/flask_app.py
- api/src/pcapi/routes/backoffice/home.py
- api/tests/routes/backoffice/redirect_test.py
Experimentation sur le comportement effectif de gunicorn dans notre deployment en cas de timeout 
Cette PR n'arrivera pas en staging et sera revert avant la MES. La qualité de code et la maintenabilité sont donc sans objets
> (BSR)[BO] test: timeout experimentation

- api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
- api/src/pcapi/routes/backoffice/templates/collective_offer/details.html
Suppression de la double initialisation du formulaire de déplacement d'offre collective.
> (BSR)[BO] fix: Init move collective offer form only once

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250414T090046_32bc8b20a0e1_validate_event_opening_hours_constraints_on_stock.py
Ces deux contraintes `'stock_eventOpeningHoursId_fkey'` et `'check_stock_with_opening_hours_does_not_have_beginningDatetime'` ont déjà été validées en production via [ce script](https://github.com/pass-culture/pass-culture-main/pull/16884). Les migrations sont là pour valider ces contraintes sur les environnements de dev et de testing.
Ticket Jira : https://passculture.atlassian.net/browse/PC-35338
> (PC-35338)[API] feat: add migrations to validate constraints on stock

- api/src/pcapi/routes/backoffice/templates/collective_offer/details.html
- api/src/pcapi/routes/backoffice/templates/collective_offer/details_v2.html
~~Suppression d'un test pas très pertinent :~~
~~Le test vérifiait la présence du bouton "Changer le partenaire culturel". La condition d'affichage du bouton était sur la présence d'une venue éligible. Ce bouton est désormais présent sous condition FF MOVE_OFFER_TEST = True. Ça devient beaucoup moins pertinent de le tester.~~
> (BSR)[BO] fix: Mise à jour collective offer template V1 et V2 pour afficher l'option "déplacer l'offre" correctement

- api/tests/routes/pro/get_offer_test.py
Correction du test `test_returns_an_event_stock_with_opening_hours`
> (BSR)[API] fix: correctly test get offer api endpoint (test_returns_an_event_stock_with_opening_hours)

- api/src/pcapi/routes/backoffice/templates/collective_offer/details_v2.html
- api/tests/routes/backoffice/collective_offer_details_test.py
- api/tests/routes/backoffice/helpers/html_parser.py
Fix de l'affichage de la modal "déplacer l'offre" dans la page détails de l'offre collective v2
> (BSR)[BO] fix: 'move offer' modal in collective offer details v2 page

- api/src/pcapi/notifications/push/backends/batch.py
- api/src/pcapi/notifications/push/backends/testing.py
- api/src/pcapi/notifications/push/trigger_events.py
- api/tests/core/reminders/external/test_reminders_notifications.py
Corriger la payload que l'on envoie à Batch pour les track events en bulk. L'id du user doit être une string et non un integer, il faut que je lise mieux les docs (je le copierai 100 fois) https://doc.batch.com/developer/api/mep/trigger-events-api/track-events#bulk-tracking
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35616
> (PC-35616)[API] fix: batch payload for bulk events

- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarFilters/StocksCalendarFilters.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarFilters/StocksCalendarFilters.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarFilters/StocksCalendarFilters.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/form/types.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35481
**Objectif**
Ajouter le nouveau tri et les nouveaux filtres à la table des stocks en création d'événement.
WIP_ENABLE_EVENT_WITH_OPENING_HOUR
**Screens**
> Pc 35481 sort filter stocks table

- api/src/pcapi/connectors/serialization/ubble_serializers.py
`declared_data` must be sent to Ubble but we do not do anything with this field. This field can be missing when the identity check is cancelled, so we do not deserialize it to avoid crashing.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35707
> (PC-35707) fix: do not deserialize unused ubble field

- api/src/pcapi/routes/backoffice/offers/blueprint.py
- api/src/pcapi/routes/backoffice/templates/collective_offer_template/details.html
- api/tests/routes/backoffice/collective_offer_templates_test.py
Refonte de la page "Offres collectives vitrine"
Avant : 
Après : 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35619
> (PC-35619)[BO] feat: refresh collective offer template details page's design

- api/src/pcapi/routes/pro/stocks.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/src/pcapi/routes/serialization/stock_serialize.py
- api/tests/routes/pro/post_stocks_test.py
- api/tests/routes/public/individual_offers/v1/patch_date_test.py
- api/tests/routes/public/individual_offers/v1/patch_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35639
Limiter la modification des dates de stocks : ne pas permettre de renseigner une (nouvelle) date dans le passé.
Ce fix concerne le portail PRO et l'API publique.
> (PC-35639)[API] fix: cannot set stock date in the past

- api/src/pcapi/core/object_storage/__init__.py
- api/src/pcapi/core/object_storage/backends/base.py
- api/src/pcapi/core/object_storage/backends/gcp.py
- api/src/pcapi/core/object_storage/backends/local.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_mediations.py
- api/src/pcapi/sandboxes/scripts/save_sandbox.py
- api/src/pcapi/sandboxes/scripts/utils/storage_utils.py
- api/src/pcapi/scripts/sandbox.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35126
[Commit 1](https://github.com/pass-culture/pass-culture-main/pull/16833/commits/bffb59bd3bb8dfa5738a933fd7802f8692388793) : Option de nettoyage des mediations de la sandboxe
[Commit 2](https://github.com/pass-culture/pass-culture-main/pull/16833/commits/03bb57ea1d43c3a3e494ba3d6b7bbefcad99bce2) : Récupération des images déjà présentent sur le bucket plutôt que d'en créer de nouvelles à chaque fois
> (PC-35126)[API] feat: New option to clean mediation before building sandbox

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/pro/offerers.py
- api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35634
New FF WIP_RESTRICT_VENUE_ATTACHEMENT_TO_COLLECTIVITY
> (PC-35634)[API] feat: Venue attachment only for collectivity

- pro/src/components/IndividualOffer/StocksCalendarSummaryScreen/StocksCalendarSummaryScreen.spec.tsx
- pro/src/components/IndividualOffer/StocksCalendarSummaryScreen/StocksCalendarSummaryScreen.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendar.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarActionsBar/StocksCalendarActionsBar.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarActionsBar/StocksCalendarActionsBar.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarLayout/StocksCalendarLayout.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarLayout/StocksCalendarLayout.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/__specs__/StocksEventCreation.spec.tsx
- pro/src/pages/IndividualOfferWizard/Stocks/Stocks.tsx
- pro/src/pages/IndividualOfferWizard/Stocks/__specs__/Stocks.spec.tsx
- pro/src/pages/IndividualOfferWizard/StocksSummary/StocksSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35558
**Objectif**
Mise en place de l'onglet "Calendrier" de la page de réumé d'une offre de type événement (read-only).
Pour ça et pour que toutes les pages de liste des stocks se basent sur la même table (création, read-only, edition à venir):
- Création d'un layout pour réutiliser la logique d'affichage du nouveau drawer de récurrence
- Passage des effets des actions dans StocksCalendarActionsBar
- Appel de `StocksCalendar` 2 fois : 1 fois pour le summary (readonly), et une fois depuis `Stocks` pour création/edition
> Pc 35558 creation stocks readonly

- api/src/pcapi/sandboxes/scripts/utils/storage_utils.py
Suppression de l'option de réutilisation des mediations du bucket lors de la création de la sandbox.
> (BSR)[API] fix: Fix sandbox, remove reuse mediation

- api/src/pcapi/connectors/entreprise/backends/insee.py
- api/tests/connectors/sirene_test.py
- api/tests/connectors/sirene_test_data.py
Otherwise, it fails after 10000th result with error 400: {
"header": {
"statut": 400,
"message": "valeur maximale pour le paramètre debut: 10000. Récupérez les fichiers exhaustifs sur https:\\www.data.gouv.fr ou utilisez la fonctionnalité curseur."
}
}
Documentation: https://www.sirene.fr/static-resources/documentation/multi_pagination_curseur_311.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-35702
> (PC-35702)[API] fix: use cursor instead of offset for pagination in Sirene API

- api/src/pcapi/routes/public/collective/endpoints/offers.py
- api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
Ticket Jira (ou description si BSR) : la route a été mise à jour mais oubli du décorateur
> (BSR)[API] fix: add missing atomic in collective public api PATCH

- .github/workflows/dev_on_workflow_tests_api.yml
- .github/workflows/dev_on_workflow_tests_pro_e2e.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35810
[Run](https://github.com/pass-culture/pass-culture-main/actions/runs/14622949622) avec 8 jobs de tests pytest et 5 jobs E2E en échec, mais seulement 2 notifications Slack
> (PC-35810) : Send a single slack failure notification per test matrix

- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/routes/pro/get_categories_test.py
- pro/src/apiClient/v1/models/SubcategoryResponseModel.ts
- pro/src/commons/utils/factories/individualApiFactories.ts
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarForm.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormMultipleDays/StocksCalendarFormMultipleDays.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormMultipleDays/StocksCalendarFormMultipleDays.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormOneDay/StocksCalendarFormOneDay.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormTimeAndPrice/StocksCalendarFormTimeAndPrice.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormTimeAndPrice/StocksCalendarFormTimeAndPrice.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35058
**Objectif**
N'afficher le choix d'horaire "Horaire précis"/"Plage horaire" dans le form de récurrence uniquement quand l'offre a une sous-catégorie éligible.
WIP_ENABLE_EVENT_WITH_OPENING_HOUR
> (PC-35058)[PRO] feat: Hide the opening hours form for ineligible offers.

- api/src/pcapi/core/external/sendinblue.py
- api/src/pcapi/core/mails/backends/sendinblue.py
- api/src/pcapi/models/feature.py
- api/tests/core/mails/mails_celery_test.py
- api/tests/core/mails/transactional/test_send_transactional_email.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35492
Renommage du feature flag pour bien indiquer le fait qu'il sera spécifique à l'envoi de mail et pouvoir contrôler le passage de différentes tâches à Celery.
> (PC-35492)[API] chore: rename celery ff to be mail specific

- .github/workflows/dev_on_push_workflow_main.yml
Only pcapi-tests is useful since we don't deploy. Build it when api or pro has changed to run E2E tests
> (BSR)[API] ci: fix merge ci

- api/tests/sandboxes/scripts/test_save_sandbox.py
(BSR)[API] fix: flaky test in sandbox index all offers
> (BSR)[API] fix: flaky test in sandbox index all offers

- api/src/pcapi/connectors/titelive.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/providers/titelive_book_search.py
- api/src/pcapi/core/providers/titelive_music_search.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35343
> (PC-35343)[API] chore: stop writing ean in product extraData

- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/tests/routes/pro/post_collective_offers_test.py
Ticket Jira (ou description si BSR) : côté front le champ `contactEmail` est required, on ne recevra donc pas ""
> (BSR)[API] fix: remove unnecessary EmailStrOrEmpty custom field

- api/src/pcapi/utils/login_manager.py
- api/tests/routes/backoffice/static_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-35876
> (PC-35876)[BO] perf: avoid DB requests when serving static files

- pro/src/commons/core/Venue/getSiretData.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35697
- Afficher l'adresse récupérée de l'api adresse, et non pas celle de l'api siret/siren.
> (PC-35697)[PRO] feat: Use the adress api data instead of the siret one.

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/conftest.py
- api/tests/routes/pro/delete_offer_opening_hours_test.py
- pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35413
Ajout d'une nouvelle route à l'API du portail PRO : suppression d'un ensemble d'horaires d'ouvertures pour une offre.
Les réservations liées sont annulées tandis que tous les autres objets impliqués ici ne sont en réalité pas supprimés, ils sont marqués comme `soft deleted`.
> (PC-35413)[API] feat: opening hours (pro): add delete route

- .github/workflows/dev_on_dispatch_deploy_pullrequests.yml
- .github/workflows/dev_on_pull_request_workflow.yml
- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_schedule_deploy_main_and_pro.yml
The only time we build pcapi and pcapi-console are during testing deployment. Clean other workflows.
This will be a small improvment for testing deployment since image changes nearly every hour. It might save ~3/4 minutes for PR deployment if image stays the same
> (BSR) CI : fix check-image-exists and build image if not

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/commands.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35736
Ajout d'une commande qui permet de faire du nettoyage dans la table des offres, càd supprimer les offres créées il y a plus d'un an ET qui n'ont pas de stock utilisable (supprimé ou dont la date limite de réservation est dépassée) ET qui n'ont aucune réservation.
> (PC-35736)[API] feat: offer command: delete old unbookable offers

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/exceptions.py
- api/src/pcapi/routes/pro/offerers.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/pro/post_offerer_invite_member_again_test.py
- api/tests/routes/pro/post_offerer_invite_member_test.py
- pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35700
L'objectif est de proposer une solution simple pour les pro pour renvoyer des invitations perdues.
Seules les invitations "en attente" sans user, ni user offerer associés peuvent être renvoyées.
Une erreur générique est renvoyée au front car le bouton CTA ne sera proposé que si le renvoi est possible.
> (PC-35700)[API] feat: New route to send invite again

- api/src/pcapi/core/token/__init__.py
- api/tests/core/token/test_token.py
- api/tests/routes/pro/validate_user_test.py
> bdalbianco/PC-35450: proper error when token is already used

- .github/workflows/dev_on_dispatch_release_build.yml
- .github/workflows/dev_on_dispatch_release_build_hotfix.yml
- .github/workflows/dev_on_dispatch_release_deploy.yml
- il manquait des secrets pour appeler `dev_on_workflow_post_slack_message`
- le YAML était mal indenté
- on avait besoin de quotes autour de `{{ steps.slack-text.outputs.text }}`
> (BSR) ci: fix again

- api/tests/core/bookings/test_api.py
Ticket Jira (ou description si BSR) : On a supprimé pytest-flask-sqlalchemy, ça devrait marcher maintenant non ?
> (BSR)[API] chore: remove xfail on test

- .github/workflows/dev_on_dispatch_release_build.yml
- .github/workflows/dev_on_dispatch_release_build_hotfix.yml
- .github/workflows/dev_on_dispatch_release_deploy.yml
- .github/workflows/dev_on_schedule_deploy_main_and_pro.yml
- Corriger la condition d'exécution d'un step.
`if failure()` en début de job est vrai si un job précédent du workflow a échoué tandis que `if failure()` en début de step s'exécute si un step précédent au sein du job a échoué.
- Au passage, on améliore la mise en forme de certains messages.
> (BSR) ci: some changes and a fix

- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarForm.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormMultipleDays/StocksCalendarFormMultipleDays.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormOneDay/StocksCalendarFormOneDay.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormTimeAndPrice/StocksCalendarFormSpecificTimeSlots/StocksCalendarFormSpecificTimeSlots.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormTimeAndPrice/StocksCalendarFormTimeAndPrice.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormTimeAndPrice/StocksCalendarPriceCategories/StocksCalendarPriceCategories.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormTimeAndPrice/StocksCalendarPriceCategories/StocksCalendarPriceCategories.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarForm/StocksCalendarFormTimeAndPrice/StocksCalendarPriceCategories/StocksCalendarPriceCategories.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTableEditStock/StocksCalendarTableEditStock.module.scss
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTableEditStock/StocksCalendarTableEditStock.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTableEditStock/specs/validationSchema.spec.tsx
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTableEditStock/utils.ts
- pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTableEditStock/validationSchema.ts
- pro/src/components/IndividualOffer/StocksEventCreation/form/__specs__/validationSchema.spec.ts
- pro/src/components/IndividualOffer/StocksEventCreation/form/types.ts
- pro/src/components/IndividualOffer/StocksEventCreation/form/validationSchema.ts
- pro/src/ui-kit/formV2/QuantityInput/QuantityInput.module.scss
- pro/src/ui-kit/formV2/QuantityInput/QuantityInput.spec.tsx
- pro/src/ui-kit/formV2/QuantityInput/QuantityInput.stories.tsx
- pro/src/ui-kit/formV2/QuantityInput/QuantityInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35965
**Objectif**
Utiliser le `QuantityInput` du formV2 dans les nouveaux formulaires `react-hook-form` d'ajout et édition de stocks indiv.
Pou pouvoir controller le composant depuis le formulaire, il a fallu ajouter la prop `value`. Et au passage : 
- Ajout d'une story pour l'utilisation du composant dans un formulaire
- Update des props pour ressembler aux autres composants de formV2 (label, onBlur, asterisk, error, minimum, maximum & suppression des props qui doivent être évitées)
Le 2e commit implémente le composant dans les formulaires de stock en question.
> Pc 35965 suantity input within form

- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
This will be used to move offers from a venue to another and prevent any booking during that period.
Ticket Jira : https://passculture.atlassian.net/browse/PC-35393
> (PC-35393)[API] feat: add stock locking function

- pro/package.json
- pro/yarn.lock
Update storybook router version after react router upgrade
> (BSR)[PRO] fix: update router storybook version

- api/documentation/src/pages/change-logs.md
- api/documentation/static/openapi.json
- api/src/pcapi/routes/public/documentation_constants/fields.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v1/post_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35958
> (PC-35958)[API] feat: update max length for offer description

- pro/src/ui-kit/MultiSelect/MultiSelect.stories.tsx
- pro/src/ui-kit/MultiSelect/MultiSelect.tsx
- pro/src/ui-kit/MultiSelect/MultiSelectTrigger.tsx
- pro/src/ui-kit/MultiSelect/__specs__/MultiSelectTrigger.spec.tsx
Corriger la structure du composant Multiselect d'après ces retours : https://github.com/pass-culture/pass-culture-main/pull/17405#discussion_r2081146540
> (BSR)[PRO] fix: multiselect legend tag should be fieldset's first child

- api/src/pcapi/core/offers/repository.py
Fix de la commande de suppression des vieilles offres non réservables et non réservées :
1. la boucle qui fait itère progressivement sur les lignes des offres utilisait `max_id + batch_size` comme limite supérieure au lieu de `min_id + batch_size`... cette correction devrait nous éviter des requêtes qui vont viser des dizaines, voire des centaines, de millions d'offres...
2. si max_id était null (toujours dans la même fonction du `repository`), on allait chercher l'id maximum... en prenant celui de la toute première offre, donc le plus petit.
> (BSR)[API] fix: old offers cleanup command: bounds

- .github/workflows/dev_on_schedule_delete_pullrequest_deployments.yml
Tiny proxy is up from 6am to 8pm Europe/Paris time
> (BSR)[API] fix: run worflow only when tinyproxy is up

- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/core/offers/api.py
- api/tests/core/educational/api/test_move_collective_offer.py
- api/tests/core/offers/test_api.py
OA was designed so that if a venue change location, the offers would stay on the OA and the OA would use the venue's common name. Let's reuse this when moving offer as the end goal is to remove the venue anyway.
Ticket Jira: https://passculture.atlassian.net/browse/PC-35871
> (PC-35871)[API] fix: move_offer should use a non venue OA

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_mediations.py
Ne pas empiler des png dans GCP à l'infini
Testé en local
> (BSR)[API] build: sandbox - clear all images from gcp when cleaning sandbox

- api/src/pcapi/core/providers/repository.py
- api/src/pcapi/routes/pro/venue_providers.py
- api/tests/routes/pro/post_venue_provider_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35782
[Portail PRO] Lors de l'activation d'un synchronisation, la condition qui permet de décider si on lance une tâche de synchronisation n'est pas à jour : il faudrait vérifier que la synchronisation concerne un cinéma puisque c'est uniquement ce type de synchronisation que la tâche lancée accepte. 
-> le portail pro lance beaucoup (pas tant que ça non plus) de tâches qui déclenchent très vite une erreur, pour rien. Cette PR vise à réduire le bruit généré sur Sentry.
> (PC-35782)[API] fix: new venue provider: sync movies only

- pro/src/components/ImageDragAndDrop/ImageDragAndDrop.spec.tsx
- pro/src/components/ImageDragAndDrop/ImageDragAndDrop.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36130
> (PC-36130)[PRO] fix: prevent using .gifs on ImageDragAndDrop component

- api/src/pcapi/core/offers/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35736
Ajout d'un `@atomic()` manquant : sans, rien n'est sauvegardé (le _context manager_ `atomic()` ne fonctionne pas comme prévu s'il n'y a un décorateur `@atomic` utilisé plus haut)
> (BSR)[API] fix: delete old unusable offers: add missing @atomic()

- api/src/pcapi/scripts/move_offer/move_batch_offer.py
FI are linked to Booking through BookingFinanceIncident and must move to keep data consistency
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35949
> (PC-35949)[API] feat: Move FinanceIncident to the new venue during regularisation

- api/src/pcapi/scripts/move_offer/move_batch_offer.py
move_offer has a transaction block. Since the script is outside an atomic bloc, the transaction block will commit as soon as it is exited.
Adding the atomic block globally will change how the transaction block works and will not commit the changes.
Ticket Jira : https://passculture.atlassian.net/browse/PC-36088
> (PC-36088)[API] fix: don't commit individual offers one by one

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_api.py
Amélioration concernant le script de suppression des vieilles offres non réservables et non réservées : ne pas s'arrêter en cas d'erreur de suppression.
> (BSR)[API] fix: delete old offers commands: ignore&continue on error

- api/src/pcapi/routes/backoffice/filters.py
- api/tests/routes/backoffice/bank_account_test.py
Une _venue_ était encore nommée « lieu » dans les actions.
> (BSR)[BO] fix: lieu -> partenaire culturel

- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/models/api_errors.py
- api/src/pcapi/routes/error_handlers/generic_error_handlers.py
- api/src/pcapi/routes/pro/collective_offers.py
- api/src/pcapi/routes/pro/collective_stocks.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/pro/stocks.py
- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/tests/core/educational/test_api.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_schemas.py
- api/tests/core/offers/test_validation.py
- api/tests/routes/pro/patch_publish_offer_test.py
- api/tests/routes/pro/post_price_categories_test.py
- api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
Ticket Jira (ou description si BSR) : Cette PR vise à réduire le nombre d'exceptions définies au niveau de `core.offers.exceptions` pour simplifier le code.
> (BSR)[API] Refacto offer exceptions

- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/openapi_test.py
- api/tests/routes/native/v1/account_test.py
Cette PR ajoute le champ **address** de l’utilisateur à l’endpoint **me** (`GET /native/v1/me`). Auparavant, la réponse ne comprenait pas l’adresse postale de l’utilisateur ; cette évolution permet aux clients de recevoir le champ `address` en complément des données de localisation existantes.
* **JIRA** : [[PC-35537](https://passculture.atlassian.net/browse/PC-35537)](https://passculture.atlassian.net/browse/PC-35537)
1. **Sérialisation**
* **Fichier** : `api/src/pcapi/routes/native/v1/serialization/account.py`
* **Mise à jour** :
* Ajout de l’attribut `address: str | None` au modèle `UserProfileResponse` pour sérialiser le champ `address` dans la réponse de l’API.
2. **Tests**
* **Fichier** : `api/tests/routes/native/v1/account_test.py`
* **Mise à jour** :
* Renforcement du test …
> (PC-35537)[API] feat: Add address to me endpoint

- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v1/get_events_test.py
Fix de [ce bug](https://pass-culture.sentry.io/issues/42366503/?alert_rule_id=155878&alert_type=issue&environment=production&notification_uuid=c76b5f7c-2346-4991-b36c-5044f3b6c9a3&project=4508776981069904&referrer=slack)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36191
> (PC-36191)[API] fix: do not crash on empty string in extra data

- api/src/pcapi/flask_app.py
retiait de deux tentative de corrections.
la premiere (dans `remove_db_session`) mennait a un crash si elle était appelé (mais en pratique ne peut pas être appelée)
la seconde a fait la preuve de son innutilitée.
> (BSR)[API] fix: remove flawed fix for the session issue

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/commands.py
- api/src/pcapi/core/offers/repository.py
1. Ajouter un méchanisme qui ré-exécute une requête de filtre en erreur (par exemple suite à un _time out_)
2. Ne pas réindexer les offres dont on supprime l'image : il est inutile de les ajouter dans la file d'attente des offres à réindexer puisqu'elles ne pourront pas l'être.
> (BSR)[API] feat: delete old offers command: add retries

- pro/src/commons/hooks/usePrevious.ts
- pro/src/components/ImageDragAndDrop/ImageDragAndDrop.tsx
- pro/src/components/ImageDragAndDropUploader/ImageDragAndDropUploader.tsx
- pro/src/components/ImageUploader/components/ButtonImageEdit/ButtonImageEdit.tsx
- pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.module.scss
- pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.spec.tsx
- pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.tsx
- pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferImageDialogs.tsx
- pro/src/ui-kit/DialogBuilder/DialogBuilder.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35694
- Gérer les reprises de focus après annulation / enregistrement / suppression d'image.
- Utiliser le DialogBuilder afin d'exploiter sa propriété `title`.
> (PC-35694)[PRO] fix: focus on image drag and drop uploader

- api/documentation/static/openapi.json
- api/src/pcapi/routes/public/collective/serialization/offers.py
- api/src/pcapi/routes/public/documentation_constants/descriptions.py
- api/src/pcapi/routes/public/documentation_constants/fields.py
Ticket Jira (ou description si BSR) : on place la mention DEPRECATED au niveau du champ offerVenue directement au lieu de addressType
> (BSR)[API] feat: move deprecated mention of public api offerVenue field

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250521T143840_541fcbeb419e_add_datetime_columns_in_offer.py
- api/src/pcapi/core/offers/models.py
Migration creates `finalizationDatetime`, `publicationDatetime` & `bookingAllowedDatetime`
Ticket Jira (étape 1) : https://passculture.atlassian.net/browse/PC-35964
> (PC-35964)[API] feat: add offer migration to add new columns

- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
- api/src/pcapi/routes/backoffice/offers/blueprint.py
- api/src/pcapi/routes/backoffice/templates/collective_offer/details.html
- api/src/pcapi/scripts/move_offer/move_batch_offer.py
- api/tests/core/educational/api/test_move_collective_offer.py
- api/tests/core/offers/test_api.py
- api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36168
> (PC-36168)[API] chore: Split move_collective_offer_venue into 2 distinct methods

- pro/src/components/SignupJourneyForm/Offerers/Offerers.tsx
- pro/src/components/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx
Joining and creating new venues should be available to everybody *if*:
- WIP_RESTRICT_VENUE_CREATION_TO_COLLECTIVITY
- WIP_RESTRICT_VENUE_ATTACHMENT_TO_COLLECTIVITY
are off. If they are on, it should only be possible for ape code 84.11Z - ie collectivities.
Ticket Jira : https://passculture.atlassian.net/browse/PC-36233
> (PC-36233)[PRO] fix: user should join/create new venues

- api/src/pcapi/core/educational/api/offer.py
- api/src/pcapi/scripts/move_offer/move_batch_offer.py
- api/tests/scripts/move_offer/move_batch_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36257
> (PC-36257)[API] fix: Removed flush to avoid updating collectiveOffers iterable when looping over it in move_batch_offer command

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/patch_offers_active_status_test.py
- api/tests/routes/pro/patch_publish_offer_test.py
Those 2 routes now updates `offer.publicationDatetime` & `offer.bookingAllowedDatetime`
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36229
> (PC-36229)[API] feat: update `patch_offers_active_status` & `patch_publish_offer`

- api/src/pcapi/core/chronicles/models.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offers/models.py
ne plus utiliser le binding de sqlalchemy et sqlalchemy_orm sur l'objet db pour la déclaration des models.
Ce binding n'apporte rien en dehors de nous lier a flask_sqlalchemy
> (BSR)[API] refactor: use sa and sa_orm instead of db to declare models

- api/src/pcapi/core/mails/transactional/users/accepted_as_beneficiary.py
- api/tests/core/subscription/test_api.py
Free offers beneficiaries should not receive the email congratuling them for the 150€ credit unlock.
While waiting for the new email to send instead, we disable the currently sent email for those beneficiaries.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36279
> (PC-36279)[API] fix: do not send emails for free beneficiaries

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/schemas.py
- api/tests/routes/pro/patch_draft_offer_test.py
- pro/src/apiClient/v1/models/PatchDraftOfferBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35960
Permettre l'ajout des dates de publication et de d'ouverture des réservations pour une offre, sur le portail PRO.
Ces deux dates sont obligatoires, ne peuvent être dans le passé et la date d'ouverture des réservation ne peut être avant celle de publication.
> (PC-35960)[API] feat: future publication: update patch draft offer

- pro/src/components/Newsletter/Newsletter.tsx
- pro/src/components/Newsletter/__specs__/Newsletter.spec.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36412)
Remplacement du lien du bloc "newsletter" en bas de la page d'accueil.
Pas de changements graphiques.
> (PC-36412)[PRO] feat: Replace newsletter link on home page.

- api/src/pcapi/connectors/ems.py
- api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
- api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
- api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36483)
> (PC-36483)[API] feat: use `EXTERNAL_BOOKINGS_TIMEOUT_IN_SECONDS` in `synchronize_venue_provider`

- api/poetry.lock
- api/pyproject.toml
Mise à jour de paquets Python.
Retour en arrière sur cryptography + pyopenssl, car on a des "Segmentation fault" sur le script de resynchro des attributs depuis la MEP de lundi, alors que ça tournait sans problème pendant des journées consécutives avant la MES. Debug impossible en prod.
> Bsr upgrade python packages

- pro/cypress/e2e/navigation.cy.ts
Correction du test E2E de navigation. Le test vérifiait l'existence d'un titre qui est toujours présent, alors que le reste de la donnée ne l'est pas.
> (BSR)[PRO] ci: Fix e2e navigation test.

- api/src/pcapi/core/logging.py
Le "subset" n'attrape pas ou plus tous les logs bruyants de fontTools, donc on adapte, pour éviter le spam à la génération des invoices
> (BSR)[API] feat: silence noisy fontTools logs

- api/src/pcapi/scripts/sandbox.py
On a des warnings au lancement de la sandbox :
```
docker exec pc-api bash -c "cd /usr/src/app/ && flask sandbox -n industrial"
/home/pcapi/.local/lib/python3.11/site-packages/click/core.py:1193: UserWarning: The parameter -c is used more than once. Remove its duplicate as parameters should be unique.
```
Je les corrige
> (BSR)[API] feat: rename param to avoid click warning

- api/src/pcapi/core/offers/schemas.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/patch_offer_test.py
- pro/src/apiClient/v1/models/PatchDraftOfferBodyModel.ts
- pro/src/apiClient/v1/models/PatchOfferBodyModel.ts
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36545)
This PR brings 2 changes :
- Move `bookingAllowedDatetime` & `publicationDatetime` from `patch_draft_offer` to `patch_offer`
- `bookingAllowedDatetime` & `publicationDatetime` are now independant
> (PC-36545)[API] feat: move `bookingAllowedDatetime` & `publicationDatetime` from `patch_draft_offer` to `patch_offer`

- pro/src/pages/OfferType/OfferType/CollectiveOfferType/CollectiveOfferType.tsx
- pro/src/pages/OfferType/OfferType/__specs__/OfferType.spec.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36388)
Une bannière avait été supprimé, on l'a remet. C'était pour afficher une bannière rouge lorsque la structure ne peut pas créer d'offres collective (pas autoriser sur adage et aucun dossier DS)
> (PC-36388)[PRO] feat: add banner dms for collective offer

- api/src/pcapi/connectors/big_query/queries/pro_email_churned_40_days_ago.py
- api/src/pcapi/connectors/big_query/queries/pro_no_bookings_since_40_days_ago.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-36568
Sentry : https://pass-culture.sentry.io/issues/36402599/?environment=production
La correction reprend la même condition que dans https://github.com/pass-culture/pass-culture-main/blob/master/api/src/pcapi/connectors/big_query/queries/marketing.py.
> (PC-36568)[API] fix: exception when retrieving empty booking emails from BigQuery

- api/src/pcapi/static/backoffice/scss/pc/_utilities.scss
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36592)
apres:
> (PC-36592)[BO] fix: tomselect display when empty and unfold

- api/src/pcapi/routes/auth/discord.py
Je ne perçois pas utile de remonter les Recaptcha Failed dans Sentry ! On peut donc descendre le niveau de log à `warning`.
https://pass-culture.sentry.io/issues/33141295/?environment=production
> (BSR)[API] chore: recaptcha failed has no reason to be an error on the platform

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py
- api/src/pcapi/routes/backoffice/operations/blueprint.py
- api/src/pcapi/routes/backoffice/templates/components/search/result_card.html
- api/src/pcapi/routes/backoffice/templates/operations/details.html
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_special_events.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/finance_test.py
- api/tests/routes/backoffice/helpers/html_parser.py
- api/tests/routes/backoffice/operations_test.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36484)
Display account tags in:
- Accounts search page
- Special operation responses page
> (PC-36484)[BO] feat: display account tag in special operation and accounts pages

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250620T113901_a35242268279_user_account_update_request_userId_on_delete_set_null.py
- api/src/pcapi/alembic/versions/20250620T113902_4b97dba7262f_validate_user_account_update_request_user_id.py
- api/src/pcapi/core/users/models.py
- api/tests/routes/backoffice/pro_users_test.py
```
IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "user" violates foreign key constraint "user_account_update_request_userId_fkey" on table "user_account_update_request"
DETAIL:  Key (id)=(6600195) is still referenced from table "user_account_update_request".
[SQL: DELETE FROM "user" WHERE "user".id = %(id_1)s] [parameters: {'id_1': 6600195}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (9 additional frame(s) were not displayed)
...
File "pcapi/routes/backoffice/utils.py", line 157, in wrapped
return function(*args, **kwargs)
File "pcapi/routes/backoffice/pro_users/blueprint.py", line 243, in delete
db.session.query(users_models.User).filter(users_models.User.id == user_id).delete(synchronize_session=False)
```
Ticket Jira : …
> (PC-36646)[BO] fix: ForeignKeyViolation when a 'pro' user is deleted and has beneficiary update request

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/tests/routes/public/individual_offers/v1/get_event_stocks_test.py
- api/tests/routes/public/individual_offers/v1/get_event_test.py
- api/tests/routes/public/individual_offers/v1/get_events_test.py
Apply `@atomic` to the following endpoints :
- POST `/public/offers/v1/events` -> ✅ 
- GET `/public/offers/v1/events/<int:event_id>` -> ✅ 
- GET `/public/offers/v1/events` -> ✅ 
- PATCH `/public/offers/v1/events/<int:event_id>` -> ✅ 
- POST `/public/offers/v1/events/<int:event_id>/price_categories` -> ✅ 
- GET `/public/offers/v1/events/<int:event_id>/price_categories` -> ✅ 
- PATCH `/public/offers/v1/events/<int:event_id>/price_categories/<int:price_category_id>` -> ✅ 
- POST `/public/offers/v1/events/<int:event_id>/dates` -> ✅ 
- GET `/public/offers/v1/events/<int:event_id>/dates` -> ✅ 
- DELETE `/public/offers/v1/events/<int:event_id>/dates/<int:stock_id>` -> ✅ 
- PATCH `/public/offers/v1/events/<int:event_id>/dates/<int:stock_id>` -> ✅ 
- GET `/public/offers/v1/events/categories` -> ✅
> (BSR)[API] feat: apply `@atomic` to public API events endpoints

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/exceptions.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/eligibility_api.py
- api/src/pcapi/core/users/exceptions.py
- api/src/pcapi/routes/backoffice/accounts/blueprint.py
- api/src/pcapi/routes/backoffice/filters.py
- api/tests/core/users/test_api.py
- api/tests/repository/test_transaction.py
- api/tests/routes/backoffice/accounts_test.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36185)
Avant cette PR, il est possible d'effectuer une revue manuelle `UNDERAGE` (mineur pré-décret) à un bénéficiaire de 18 ans, ce qui entraîne un comportement un peu louche : le bénéficiaire est crédité du crédit 18 post-décret (150€). Pour éviter toute confusion, cette PR désactive la revue manuelle `UNDERAGE` sur tous les comptes qui ont plus de 18 ans.
> (PC-36185)[BO] fix: disable underage manual review on eighteen years old

- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36666)
Lorsqu'on cliquait sur réinitialiser dans le filtre pour choisir un rayon sur ADAGE, on remettait la valeur de 50 au lieu de la valeur par défaut
> (PC-36666)[PRO] fix: reset filter geoloc radius

- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/__specs__/validationSchema.spec.ts
- pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/validationSchema.ts
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36754)
On doit pouvoir entrer une durée sur le form d'offre collective, mais la regex qui vérifie le format HH:mm n'autorise pas à avoir une durée > 23:59, alors que ça doit être possible.
Je remets la regex d'avant migration rhf (a la différence qu'il faut autoriser à avoir une valeur vide aussi dans la regex).
> (PC-36754)[PRO] fix: Allow collective duration above 23:59.

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/routes/public/booking_token/v2/endpoints.py
- api/src/pcapi/routes/public/individual_offers/v1/bookings.py
- api/tests/routes/public/individual_offers/v1/get_booking_test.py
- api/tests/routes/public/individual_offers/v1/get_bookings_test.py
Endpoints:
- GET `/public/bookings/v1/bookings` -> testé manuellement ✅ 
- GET `/public/bookings/v1/token/<string:token>`  -> testé manuellement ✅ 
- PATCH `/public/bookings/v1/use/token/<token>`  -> testé manuellement ✅ 
- PATCH `/public/bookings/v1/keep/token/<token>`  -> testé manuellement ✅ 
- PATCH `/public/bookings/v1/cancel/token/<token>` -> (à tester sur testing)
> (BSR)[API] feat: apply `@atomic` to public API bookings endpoints 

- api/documentation/src/pages/change-logs.md
- api/documentation/static/openapi.json
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/public/documentation_constants/descriptions.py
- api/src/pcapi/routes/public/documentation_constants/fields.py
- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/src/pcapi/routes/public/individual_offers/v1/serializers/products.py
- api/src/pcapi/routes/public/individual_offers/v1/utils.py
- api/src/pcapi/serialization/utils.py
- api/tests/core/offers/test_validation.py
- api/tests/routes/public/individual_offers/v1/get_event_test.py
- api/tests/routes/public/individual_offers/v1/get_product_by_ean_test.py
- api/tests/routes/public/individual_offers/v1/get_product_test.py
- api/tests/routes/public/individual_offers/v1/patch_product_test.py
- api/tests/routes/public/individual_offers/v1/post_event_test.py
- api/tests/routes/public/individual_offers/v1/post_product_test.py
[Ticket JIRA](https://passculture.atlassian.net/browse/PC-36182)
Dans cette PR :
- ajout de `bookingAllowedDatetime` & `publicationDatetime` dans le endpoint `post_product_offer`
- ajout de `bookingAllowedDatetime` & `publicationDatetime` dans le endpoint `edit_product`
> (PC-36182)[API] feat: implement `bookingAllowedDatetime` & `publicationDatetime` logic in public API products endpoints

- api/src/pcapi/connectors/typeform.py
```
...
File "/usr/src/app/src/pcapi/core/chronicles/api.py", line 45, in import_cine_club_chronicles
for form in typeform.get_responses_generator(get_last_chronicle_date, form_id):
File "/usr/src/app/src/pcapi/connectors/typeform.py", line 97, in get_responses_generator
forms = get_responses(
^^^^^^^^^^^^^^
File "/usr/src/app/src/pcapi/connectors/typeform.py", line 76, in get_responses
return _get_backend().get_responses(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/app/src/pcapi/connectors/typeform.py", line 278, in get_responses
data = self._get(path, params=params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/app/src/pcapi/connectors/typeform.py", line 187, in _get
logger.error(
File "/usr/local/lib/python3.11/logging/__init__.py", line 1518, in …
```
> (BSR)[API] fix: avoid crash in error log

- pro/src/pages/ResetPassword/ResetPassword.spec.tsx
- pro/src/pages/ResetPassword/ResetPassword.tsx
- pro/src/pages/ResetPassword/__specs__/ResetPassword.spec.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36734)
> [!IMPORTANT]
> Nécessite le FF `WIP_2025_SIGN_UP` d'activé
- Modification de la condition pour gérer le cas du token manquant
- Ajout d'un test unitaire pour gérer le cas du token manquant
- Modification du message d'erreur dans la notification afin qu'il soit plus générique
- (refacto) Déplacement du fichier unique de tests à côté du composant (et suppression de `__specs__`)
Before | After
:---: | :---:
❌ Accès à `/mot-de-passe-perdu` sans `?token` ->  loading infini ![image](https://github.com/user-attachments/assets/e0e52a43-5331-46e5-9149-20800920e2e1) | ✅ Redirection vers `/demande-mot-de-passe` avec notification d'erreur ![image](https://github.com/user-attachments/assets/42716884-c8a6-4167-b34d-eeed889691aa)
> (PC-36734) [PRO] fix: Redirects to forgotten password page is token is missing in reset page

- pro/src/pages/IndividualOffer/IndividualOfferDetails/commons/utils.ts
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.spec.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsSubForm/DetailsSubForm.spec.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsSubForm/DetailsSubForm.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/ImageUploaderOffer.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/EanSearchCallout/EanSearchCallout.spec.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/EanSearchCallout/EanSearchCallout.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx
- pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx
> (PC-36128)[PRO] fix: dispay ean disabled text input on creation mode, once details is submitted and re-displayed

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20240621T130747_2144f7e4df3c_add_future_offer_fk_constraint.py
- api/src/pcapi/alembic/versions/20250227T165242_b587bd63c5b6_add_future_offers_reminders_constraints.py
- api/src/pcapi/alembic/versions/20250227T165606_ea04f7c88f15_validate_future_offers_reminders_constraints.py
- api/src/pcapi/alembic/versions/20250605T150203_9b599c492622_remove_future_offer_reminder_table.py
- api/src/pcapi/alembic/versions/20250627T130249_7cbc7b9e7230_rm_future_offer.py
- api/src/pcapi/core/offers/models.py
- api/tests/core/offers/test_api.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36183)
Suppression du modèle FutureOffer et de la table future_offer.
Toute la suppression de code liée à l'utilisation de FutureOffer a déjà été réalisée dans une précédente PR : https://github.com/pass-culture/pass-culture-main/pull/17980.
> Pc 36183/bye bye future offer another try

- api/src/pcapi/flask_app.py
Small fix to https://github.com/pass-culture/pass-culture-main/pull/18032; `request.path` includes a leading slash that was not accounted for.
> Fix metric url prefix

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
Ajout d'une valeur pour `collectiveEmail` sur les Venues EAC de la sandbox, pour pré-remplir les champs à la création d'une offre
> (BSR)[API] feat: add collectiveEmail for EAC venues in sandbox

- api/src/pcapi/core/geography/factories.py
- api/src/pcapi/core/offerers/factories.py
- api/tests/routes/backoffice/venues_test.py
Afin de pouvoir supprimer les données d'adresse de la Venue, nettoyage de tests qui utilisent l'adresse par défaut de la Venue au lieu de celle de l'OffererAddress
> (BSR)[API] chore: Rely on location info & factory and not obsolete Venue address in tests

- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_tests_pro_e2e.yml
- pro/cypress/cypress.config.ts
- pro/cypress/e2e/oaCollectiveOffer.cy.ts
- pro/src/pages/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplication.tsx
Remise d'ordre et amélioration des tests e2e, qui devraient améliorer un peu la vitesse d'exécution.
_Commits un peu désordonnés en raison de divers essais sur certaines parties (ex: retrait de recording vidéo, mais finalement non …)_
- Mise en cache des layers Docker et Poetry (pour éviter de re-build à chaque job)
- Remise de `fail-fast` à `true`
- ~~Parallèlisation automatique des tests e2e~~ -> Remise en manuel (en attendant mieux) avec prise en compte du nouveau `oaCollectiveOffer.cy.ts`
- Désactivation des logs verbose
- Correction d'un test e2e en échec (`oaCollectiveOffer.cy.ts`) sur la part collective (`CollectiveOfferSelectionDuplication.tsx`)
> (BSR)[PRO] chore: Attempt to enhance e2e tests and CI

- pro/src/pages/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplication.tsx
- pro/src/pages/OfferType/OfferType/OfferType.spec.tsx
- pro/src/pages/OfferType/OfferType/OfferType.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36369)
- Hide offer subtype selection when creating a new individual offer with `WIP_ENABLE_NEW_OFFER_CREATION_FLOW ` feature flag.
1. Enable the `WIP_ENABLE_NEW_OFFER_CREATION_FLOW` feature flag
2. Try creating a new individual offer
3. You won't see "Votre offre est ..." with the subtype selection anymore
Before | After
:---: | :---:
> (PC-36369)[PRO] feat: remove offer subtype selection from new offer creation flow

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/schemas.py
- api/tests/routes/pro/patch_draft_offer_test.py
- api/tests/routes/pro/post_draft_offer_test.py
- pro/src/apiClient/v1/models/PatchDraftOfferBodyModel.ts
- pro/src/apiClient/v1/models/PostDraftOfferBodyModel.ts
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36838)
- Validate accessibility modes body props on POST et PATCH `/offers/draft[/<offer_id>]` when `WIP_ENABLE_NEW_OFFER_CREATION_FLOW` FF is enabled.
N/A.
> (PC-36838)[PRO] feat: prepare post & patch routes for new offer creation flow

- api/tests/core/subscription/test_api.py
Unless specified, identity provider content factories set the birth date
to a date computed from the current date. This can mess up age
calculations that rely on time traveling.
The FraudCheckFactory already sets up the ContentFactory with fields
computed from the user as default, which removes the dependency on
current date.
> (BSR)[API] fix: beneficiary activation test that relied on current time

- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/search/__init__.py
- api/src/pcapi/core/search/serialization.py
- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
- api/tests/core/search/test_serialize_algolia.py
- api/tests/files/native_openapi.json
- api/tests/routes/native/v1/offers_test.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36742)
> Pc 36742 add chronicles count to offer route

- pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
> (PC-36979)[PRO] fix: restore sorting on stocks table

- api/src/pcapi/core/object_storage/__init__.py
- api/src/pcapi/core/object_storage/backends/base.py
- api/src/pcapi/core/object_storage/backends/gcp.py
- api/src/pcapi/core/object_storage/backends/local.py
- api/src/pcapi/routes/backoffice/gdpr_user_extract/blueprint.py
- api/src/pcapi/tasks/cultural_survey_tasks.py
- api/tests/core/object_storage/object_storage_test.py
- api/tests/routes/native/v1/cultural_survey_test.py
- api/tests/tasks/cultural_survey_task_test.py
using dependency injection allows the local object storage backend to be used, making the beneficiary activation flow possible in local development environment without having gcp credentials.
> (BSR)[API] fix: use backend injection for cultural survey

- api/src/pcapi/core/search/serialization.py
- api/tests/core/search/test_serialize_algolia.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36799)
Partly reverts the modifications of PC-36900.
Reintroduces _tag `is_future` when serializing offers in algolia.
> (PC-36799)[API] feat: add bookingAllowedDateTime to agolia offer serialization

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250710T172534_82773754a29f_opening_hours_use_venue_or_offer.py
- api/src/pcapi/alembic/versions/20250721T175641_c333f15058f1_opening_hours_add_offerid_index.py
- api/src/pcapi/alembic/versions/20250722T152014_a927abb5583b_opening_hours_validate_offer_id_fkey.py
- api/src/pcapi/alembic/versions/20250722T152332_0bfe4eb50b49_opening_hours_validate_offer_xor_venue_constraint.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/opening_hours/api.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/offers/schemas.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/core/offers/opening_hours/test_api.py
- api/tests/core/offers/test_schemas.py
- api/tests/routes/pro/get_offer_opening_hours_test.py
- api/tests/routes/pro/patch_offer_opening_hours_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/OfferOpeningHoursSchema.ts
- pro/src/apiClient/v1/models/WeekdayOpeningHoursTimespans.ts
- pro/src/apiClient/v1/services/DefaultService.ts
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36382)
Ajout de routes concernant les horaires d'ouvertures d'une offre sur le portail pro, qui permettent les actions suivantes : 
- créer des horaires d'ouvertures ;
- modifier des horaires d'ouverture ;
- supprimer des horaires d'ouverture ;
- consulter les horaires d'ouverture existant.
Les trois premières sont réalisées par une seule et même route : la suppression revient à indiquer explicitement l'absence d'horaires d'ouverture pour chaque jour de la semaine. Etant donnée qu'on ne sauvegarde en base de données que les horaires d'ouvertures explicites, cette même route peut être utilisée pour réaliser les trois premières actions.
Dans tous les cas, l'objet de réponse contiendra les horaires d'ouverture de l'offre sur toute une …
> (PC-36382)[API] feat: pro:offers: CRUD opening hours routes

- pro/README.md
Correction de la version de Node.js conseillée dans le README de /pro/
(La version 21 précédemment conseillée n'est pas compatible avec Yarn 1.22.22 ➡️ il faut avoir au maximum la version 20 de Node.js)
> (BSR)[PRO] docs: Updates /pro/ README with correct Node.js version

- api/src/pcapi/core/offers/repository.py
En faisant un `count()` sur l'`id` du modèle, postgres doit récupérer cette valeur et fait donc un Index Scan au lieu d'un Index Only Scan
Sur la query qui est faite pour l'indexation des offres (dans `get_base_query_for_offer_indexation`), pour 1 seule offre en staging, on passe de :
````
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
| QUERY PLAN                                                                                                                                                                                                                                   > …
```
> (BSR)[API] perf: delete count() arg to allow index only scan

- api/src/pcapi/sandboxes/scripts/save_sandbox.py
- api/src/pcapi/sandboxes/scripts/utils/helpers.py
- api/src/pcapi/scripts/sandbox.py
- api/tests/sandboxes/scripts/test_utils.py
Ajout d'une option pour skip des étapes de la sandbox
Usage : `flask sandbox -n industrial --step-to-skip build_many_extra_invoices`
> (BSR)[API] feat: add option to sandbox command to skip steps

- api/src/pcapi/connectors/entreprise/api.py
- api/src/pcapi/connectors/entreprise/backends/api_entreprise.py
- api/src/pcapi/connectors/entreprise/backends/base.py
- api/src/pcapi/connectors/entreprise/backends/testing.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/pro/offerers.py
- api/src/pcapi/routes/pro/sirene.py
- api/tests/routes/pro/post_offerer_test.py
- api/tests/routes/pro/post_save_new_onboarding_data_test.py
- api/tests/routes/pro/sirene_test.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36975)
When searching for SIRET and creating new Venue & Offerer, we should rely on Open Data API Entreprise routes, which send only public data that can be safely show in our pro frontend
- Add `get_siren_open_data` and `get_siret_open_data `in connector to call `.../diffusibles/` routes
- Replace usages in structure identification, structure creation, and manual structure creation in backoffice
> (PC-36975)[API] feat: Use Open Data API Entreprise routes in structure creation

- api/src/pcapi/core/offers/models.py
- api/src/pcapi/routes/institutional/playlist.py
- api/tests/routes/institutional/playlist_test.py
Cette PR modifie la logique de filtrage pour les playlists institutionnelles. Auparavant, une offre devait être à la fois `released` (publiée) et `bookable` (réservable) pour apparaître. Désormais, le seul critère est que l'offre soit `released`.
https://passculture.atlassian.net/browse/PC-36332
- **API (`api/src/pcapi/routes/institutional/playlist.py`)**:
- La requête a été mise à jour pour ne plus filtrer sur `is_released_and_bookable`, mais uniquement sur l'état `_released` de l'offre.
- Cela signifie que des offres publiées mais sans stock disponible (ou avec des stocks expirés) seront maintenant incluses dans les résultats.
- **Tests (`api/tests/routes/institutional/playlist_test.py`)**:
- Le test `test_unbookable_offers_are_ignored` a été mis à jour pour refléter ce nouveau …
> (PC-36332)[API] feat: Change playlist url to return unbookable offers

- api/src/pcapi/routes/public/individual_offers/v1/events.py
- api/tests/routes/public/individual_offers/v1/events/post_event_test.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36875)
Changement de l'erreur de 500 à 400 lors de la création d'un évènement sur une venue `softDeleted = True`
> (PC-36875)[API] feat: Update error message when trying to create an event offer on soft deleted venues through public API

- api/src/pcapi/routes/public/individual_offers/v1/products.py
- api/tests/routes/public/individual_offers/v1/products/post_product_by_ean_test.py
The regression happened here : https://github.com/pass-culture/pass-culture-main/commit/9057b5294119a4d28a47d3f635a9f0502cbae8e6#diff-71490f5793d9fba5a23611e7221cab71f869f3154846b1a3b612e5af739329acL11-L312 (search "delay")
> (BSR)[API] fix: make /ean public route asynchronous again

- pro/cypress/e2e/desk.cy.ts
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37280)
- Intercept useless 401 responses on connection page first load, hoping to fix this flakyness error:
- Ran CI 5 times without failure on the last commit:
> (PC-37280)[PRO] test: attempt to fix connection page e2e test flakyness

- .github/workflows/dev_on_workflow_deploy.yml
Utilisation du binaire en Go pc-render-manifests plutôt que de l'action github en bash.
Testé avec succès sur l'environnement ops : https://github.com/pass-culture/pass-culture-main/actions/runs/16726767365/job/47344359643
> (IC-284)[API] ci: use pc-render-manifest binary for basic deployment

- .github/workflows/dev_on_dispatch_delete_pullrequest_deployment.yaml
- .github/workflows/dev_on_dispatch_deploy_pullrequests.yml
Utilisation du binaire pc-render-manifests sur la partie pr-deployments.
Lancé avec succès ici : https://github.com/pass-culture/pass-culture-main/actions/runs/16746785718
> (IC-284)[API] ci: use pc-render-manifests for pr deployments

- pro/src/components/IndividualOfferLayout/OfferPublicationEdition/OfferPublicationEditionForm/OfferPublicationEditionForm.tsx
- pro/src/components/IndividualOfferLayout/OfferPublicationEdition/OfferPublicationEditionForm/__specs__/OfferPublicationEditionForm.spec.tsx
- pro/src/pages/IndividualOfferSummary/IndividualOfferSummary/components/EventPublicationForm/EventPublicationForm.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37361)
Modification du nom du radio groupe de la publication dans le futur (sinon le "?" passe a la ligne).
Pour tester activer le FF `WIP_REFACTO_FUTURE_OFFER`, et créer un offre indiv. Le radio group se trouve a la dernière étape.
Before | After
:---: | :---:
> (PC-37361)[PRO] feat: Update publication radiogroup wording.

- api/src/pcapi/connectors/entreprise/api.py
- api/src/pcapi/connectors/entreprise/sirene.py
- api/src/pcapi/core/offerers/tasks.py
- api/src/pcapi/routes/backoffice/pro/forms.py
- api/src/pcapi/routes/backoffice/venues/blueprint.py
- api/src/pcapi/routes/pro/venues.py
- api/tests/connectors/sirene_test.py
- api/tests/routes/backoffice/pro_test.py
- api/tests/routes/backoffice/venues_test.py
- api/tests/routes/pro/patch_venue_test.py
- Ne plus utiliser l'API Insee et migrer vers l'API Entreprise lorsque c'est possible
- Privilégier les routes Open Data aux routes exposant des données protégées
- Supprimer les appels redondants du connecteur API Insee
> (PC-37327)[API] chore: Use open data API Entreprise whenever possible and delete redondant API Insee calls

- api/src/pcapi/scripts/move_offer/move_batch_offer.py
- api/tests/scripts/move_offer/move_batch_offer_test.py
BSR
Fix de la création des actionHistory lors de la régularisation (commande move_batch_offer)
Avant la correction :
Création d'une actionHistory pour indiquer le passage en permanent de la venue de destination dans tous les cas : que la venue soit permanente ou non avant le lancement de la commande
Après correction :
Création de l'actionHistory seulement lorsque nécessaire
Un ticket est prévu pour supprimer les actionHistory inutiles créées lors du lancement de la commande par le passé : https://passculture.atlassian.net/browse/PC-37378
> (BSR)[API] fix: Do not create action history for destination venue if already permanent during regularization

- api/src/pcapi/core/offers/repository.py
Adding the join on Venue for all the cases removes a SQLAlchemy warning for the should_consider_venue_locale_datetime_when_filtering_by_date test.
Also include more explicit joins between the tables. SELECT statement has a cartesian product between FROM element(s) "offerer_address", "address", "offer_1", "stock" and FROM element "venue".  Apply join condition(s) between each element to resolve.
> (BSR)[API] perf: avoid cartesian product on offer lis test

- api/src/pcapi/core/opening_hours/deprecated.py
- api/tests/core/offerers/test_api.py
Bug : lors de l'ajout d'horaires d'ouverture à un lieu sur le portail pro (le lieu n'en a pas et on en créé), le nouvel objet `OpeningHours` créé l'était sans lieu... ce que n'apprécie pas la base de données (logique).
Fix : ajouter le lieu.
> (BSR)[API] fix: (deprecated) opening hours upsert: missing venue

- .github/workflows/dev_on_workflow_dependabot_auto_merge.yml
This permission should allow Dependabot to approve then merge its PRs
> (BSR) ci: fix Dependabot auto-merge workflow

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/commands.py
- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
[Ticket JIRA](https://passculture.atlassian.net/browse/PC-37450)
Améliorer la tâche de suppression des anciennes offres non réservables et non réservées : au lieu de scanner toute la table des offres progressivement, n'avancer que par 10% au maximum et enregistrer le dernier id d'offre supprimé pour savoir d'où commencer la prochaine fois. Cela permettra de lancer plus de petites tâches, plus régulièrement : par exemple, une tous les jours pendant 10 jours au lieu d'une toutes les une ou deux semaines.
> (PC-37450) [journée backend] suppression des anciennes offres non réservées et non réservations : quelques améliorations

- api/src/pcapi/core/users/generator.py
- api/src/pcapi/routes/backoffice/dev/blueprint.py
- api/src/pcapi/routes/backoffice/dev/forms.py
- api/tests/routes/backoffice/dev_test.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-33233)
Add `postal_code` field to the form of user generator page
> (PC-33233)[BO] feat: add 'postal code' field in user generator page

- api/src/pcapi/core/users/gdpr_api.py
- api/tests/core/users/test_gdpr_api.py
This helps to know whether an action was initiated from pass Culture team or not in actions history, even if the employee has left.
Ticket Jira : https://passculture.atlassian.net/browse/PC-37274
> (PC-37274)[API] feat: keep info about ex BO user at anonymization time

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37460)
Le compte eac_pending_bank_informations@example.com doit avoir hasPendingBankAccount à true au lieu de false
> (PC-37460)[PRO] feat: update sandbox eac pending bank account

- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37381)
La tâche de suppression des anciennes offres non réservées et non réservables ne prenait pas en compte le statut de l'offre pour déterminer si elle était réservable ou non. Cette PR vient corriger cela : une offre rejetée n'est pas réservable même si elle a au moins un stock qui l'est.
⚠️ cette modification ne concerne que la partie "non réservable" de la définition. Une offre rejetée avec des réservations ne peut pas, et ne doit pas, être supprimée.
> (PC-37381)[API] fix: delete old offers: handle rejected

- pro/src/components/ImageDragAndDropUploader/ImageDragAndDropUploader.spec.tsx
- pro/src/components/ImageUploader/ImageUploader.spec.tsx
- pro/src/components/ImageUploader/components/ButtonImageEdit/ButtonImageEdit.tsx
- pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.spec.tsx
- pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.tsx
- pro/src/components/ModalImageUpsertOrEdit/components/ImageEditor/ImageEditor.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37556)
- Micro-optimisation pour éviter de GET l'image originale d'une venue ou d'une offre si la modale n'est pas ouverte (et puisqu'elle est toujours rendue). C'est ce qui faisait afficher des toaster d'erreur énigmatiques pour l'user quand il y avait un problème sur celle-ci (voir broken url / buckets non correspondants) alors que l'image croppée (généralement affichée) ne semblait pas avoir eu de problème à être chargée.
- Quelques biome/eslint fixes.
> (PC-37556)[PRO] fix: avoid loading original image url within modal if not opened

- pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37632)
- Déclare une url manquante pour afficher la page media / "Image & Vidéo", étape du process de création d'offre indiv. dans un contexte d'onboarding.
> (PC-37632)[PRO] fix: add missing url to display media page in the context of onboarding indiv. offer creation

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250829T160610_2b1434238dd9_drop_datelaststatusupdated_in_bankaccount.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
- api/src/pcapi/routes/backoffice/templates/offerer/get/details/bank_accounts.html
- api/src/pcapi/routes/serialization/finance_serialize.py
- api/tests/core/finance/test_ds.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/pro/get_venue_test.py
- pro/src/apiClient/v1/models/BankAccountResponseModel.ts
- pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37648)
PR deux en un :
- utiliser la table BankAccountStatusHistory dans le BO, et pas la colonne dateLastStatusUpdate, qui n'est quasiment pas remplie
- supprimer cette colonne, qui ne sert ni dans le front ni dans le BO
> Pc 37648 use ba status history in bo

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37688)
prevents offer update to create empty metadata
> (PC-37688)[API] fix: do not create offer metadata if it has no video url

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37695)
Delete OfferMetaData from DB if front sends empty videoUrl field
> (PC-37695)[API] feat: remove offer_meta_data when emptied in update offer

- api/src/pcapi/connectors/titelive.py
- api/tests/connectors/titelive/titelive_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-37693
Sentry : https://pass-culture.sentry.io/issues/60958168/
> (PC-37693)[API] fix: KeyError: 'token', when Titelive returns error 500

- api/src/pcapi/connectors/entreprise/backends/api_entreprise.py
- api/tests/connectors/api_entreprise_test.py
- api/tests/connectors/api_entreprise_test_data.py
- api/tests/routes/pro/post_offerer_test.py
- api/tests/routes/pro/post_save_new_onboarding_data_test.py
When the SIREN/SIRET was invalid, an InvalidFormatException was raised so that the error message is properly displayed in PC Pro. Now API Entreprise is called, but a generic error is reported in our alerts. We should handle this invalid SIREN/SIRET the same way ; best before calling API.
https://pass-culture.sentry.io/issues/51070177/
Ticket Jira : https://passculture.atlassian.net/browse/PC-37692
> (PC-37692)[API] fix: raise InvalidFormatException in case of invalid SIREN or SIRET

- biome.jsonc
- pro/biome.jsonc
- pro/package.json
Lorsqu'on run :
```
❯ yarn version --new-version "1.0.0-beta3"                                                                                                                          ✘ 130 
yarn version v1.22.22
info Current version: 0.0.0
info New version: 1.0.0-beta3
✨  Done in 0.01s.
❯ git diff                                                                                                                                                            ✘ 1 
diff --git a/pro/package.json b/pro/package.json
index c909c5893f..35a09d6d34 100644
--- a/pro/package.json
+++ b/pro/package.json
@@ -1,6 +1,6 @@
{
"name": "@pass-culture/pass-culture-pro",
-  "version": "0.0.0",
+  "version": "1.0.0-beta3",
"private": true,
"homepage": "/",
"type": "module",
@@ -133,8 +133,14 @@
"node": ">=20 <21"
}, …
```
> (BSR)[PRO] ci: fix Biome VS yarn version bump linting conflict

- pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.spec.tsx
- pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37613)
Ne plus afficher les cta préreservation et reservation si le ff de split des pages est activé
> (PC-37613)[PRO] feat: delete prebooked cta when ff is active

- api/src/pcapi/core/educational/repository.py
Les tests suivants sont en erreur sur master : 
```
FAILED tests/routes/pro/get_collective_offer_test.py::Returns200Test::test_location_address_venue - Failed: 7 queries executed, 6 expected
FAILED tests/routes/pro/patch_collective_offer_test.py::Returns200Test::test_location_address_venue - assert 500 == 200
```
Sans doute du au chargement dans la session de test des objets OA, et notamment l'expression isLinkedToVenue
populate_existing avait déjà fixé des cas similaires, on tente la même chose ici
> (BSR)[API] fix: fix failing tests on collective location

- api/src/pcapi/connectors/api_adresse.py
If no city is found in BAN database when looking with an Insee code, try again without any Insee code restriction - Here we'd rather have a very approximate address than no address at all
> (BSR)[API] feat: Get city centroid address without Insee code restriction

- api/src/pcapi/celery_tasks/sendinblue.py
- api/tests/core/mails/mails_celery_test.py
Exception suite au merge de https://github.com/pass-culture/pass-culture-main/pull/18695 hier.
```
pc-celery-worker    | Error:
pc-celery-worker    | Unable to load celery application.
pc-celery-worker    | While trying to load the module pcapi.celery_tasks.celery_worker the following error occurred:
pc-celery-worker    | Traceback (most recent call last):
pc-celery-worker    |   File "/home/pcapi/.local/lib/python3.11/site-packages/celery/app/utils.py", line 383, in find_app
pc-celery-worker    |     sym = symbol_by_name(app, imp=imp)
pc-celery-worker    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pc-celery-worker    |   File "/home/pcapi/.local/lib/python3.11/site-packages/kombu/utils/imports.py", line 64, in symbol_by_name
pc-celery-worker    |     return getattr(module, cls_name) if …
```
> (PC-35943)[API] fix: circular import in celery tasks

- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_beneficiary.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary.py
- api/src/pcapi/core/mails/transactional/bookings/booking_confirmation_to_beneficiary.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_test.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary_test.py
- api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py
Renommer le paramètre Brevo `FORMATTED_OFFER_PRICE` en `FORMATTED_PRICE`
> (PC-37625)[API] feat: rename formatted price parameter for brevo templates

- pro/src/pages/IndividualOffer/IndividualOfferPracticalInfos/components/IndividualOfferPracticalInfosForm/IndividualOfferPracticalInfosForm.spec.tsx
- pro/src/pages/IndividualOffer/IndividualOfferPracticalInfos/components/IndividualOfferPracticalInfosForm/IndividualOfferPracticalInfosForm.tsx
- pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/IndividualOfferTimetableScreen.module.scss
- pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/IndividualOfferTimetableScreen.tsx
- pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/StocksCalendar/StocksCalendar.module.scss
- pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/StocksCalendar/StocksCalendar.spec.tsx
- pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/StocksCalendar/StocksCalendar.tsx
- pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/StocksCalendar/StocksCalendarCancelBanner/StocksCalendarCancelBanner.tsx
- pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryStocks/components/IndividualOfferSummaryStocksCalendarScreen/IndividualOfferSummaryStocksCalendarScreen.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37905)
- Modification de la banner d'expiration à la nouvelle étape "informations pratiques" pour les livres papier (sous FF `WIP_ENABLE_NEW_OFFER_CREATION_FLOW`)
- Déplacement de la banner d'annulation pour qu'elle soit tout le temps juste avant le tableau des stocks
> (PC-37905)[PRO] feat: Edit banner logics in new individual offer flow.

- api/src/pcapi/routes/serialization/finance_serialize.py
- api/tests/routes/pro/get_collective_offer_template_test.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/routes/pro/get_offerers_bank_accounts_test.py
- api/tests/routes/pro/get_venue_test.py
- pro/src/apiClient/v1/models/BankAccountResponseModel.ts
- pro/src/commons/utils/factories/individualApiFactories.ts
- pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx
- pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
- pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx
L'information du BIC n'est plus utile côté finance, elle ne sert donc plus dans PC Pro
> (BSR)[PRO] feat: remove BIC from front pro

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20250916T092911_7ad93a37b8f0_drop_bic_column_of_bank_account.py
- api/src/pcapi/connectors/dms/serializer.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/ds.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/finance/utils.py
- api/src/pcapi/scripts/beneficiary/import_test_users.py
- api/src/pcapi/scripts/rebuild_staging/anonymize.sql
- api/tests/connector_creators/demarches_simplifiees_creators.py
- api/tests/core/finance/test_api.py
- api/tests/core/finance/test_ds.py
- api/tests/core/finance/test_utils.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37966)
Les BICs ne sont plus nécessaires dans le backend.
Après le merge, il faudra supprimer le champ dans la procédure DS.
> (PC-37966)[API] feat: remove BIC from DS imports

- api/src/pcapi/connectors/cine_digital_service.py
- api/src/pcapi/core/external_bookings/api.py
- api/src/pcapi/core/external_bookings/cds/client.py
- api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
- api/tests/connectors/api_cine_digital_service_test.py
- api/tests/core/external_bookings/cds/test_client.py
- api/tests/core/external_bookings/test_api.py
[Ticket JIRA](https://passculture.atlassian.net/browse/PC-37956)
Le but de cette PR est de commencer la réécriture du client API `CineDigitalServiceAPI` afin de supprimer le connecteur `cine_digital_service`. Ce connecteur ajoute un niveau d'abstraction, et donc de la complexité, inutile.
2 éléments importants dans cette PR : 
1. L'URL CDS n'est plus donnée en paramètre à `CineDigitalServiceAPI`. Le service utilise directement la valeur définie dans `settings.CDS_API_URL`.
2. Le service n'utilise plus la méthode `get_resource` de `cine_digital_service`
> (PC-37956)[API] refactor: Suppression du connector `cine_digital_service` - Etape 1/2

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/commands.py
- api/tests/core/offers/test_commands.py
Proposition d'optimisation.
Étape un pour réactiver le cron `reindex_recently_published_offers`
> (BSR)[API] perf: treat offers by batch in cron command

- .vscode/extensions.json
- .vscode/settings.json
- README.md
- biome.jsonc
- pro/.vscode/settings.json
- pro/biome.jsonc
- pro/package.json
- Finalise une config VSCode qui fonctionne out-of-the-box qu'on ouvre le projet par la racine ou par le dossier `pro/`.
- Corrige le check Biome en erreur au precommit lorsqu'aucun fichier ne peut être linté car exclus.
- Plus d'erreur Biome dans les IDE lors de l'enregistrement de fichiers JSONC-like.
- Petite note dans la documentation pour le setup non-VSCode.
- Plus besoin d'installer Biome en global / à part pour les devs sous VSCode.
> (BSR) style: finalize Biome integration

- pro/src/pages/IndividualOffer/IndividualOfferMedia/components/IndividualOfferMediaScreen.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-38010)
- Revalidation du cache en attendant de trouver un fix backend - puisque le retour du PATCH videoUrl utilisé pour mettre à jour le cache n'avait pas de clé address, l'étape "Localisation" était considérée comme non franchie, ainsi que toutes les étapes suivantes. On revalide le cache pour réaliser un GET offer qui lui comprend toujours l'objet entier. À terme on réalise un fix backend pour que l'objet offre retourné sur des POST / PATCH soit toujours complet.
> (PC-38010)[PRO] fix: revalidate cache in indiv. offer media page to fix stepper (dirty quick fix)

- api/src/pcapi/core/external_bookings/cds/client.py
- api/tests/core/external_bookings/cds/test_client.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-38099)
> (PC-38099)[API] feat: update `CineDigitalServiceAPI._create_ticket_sale_dict` to raise `ExternalBookingNotEnoughSeatsError` when no seats available

- api/tests/core/subscription/ubble/test_api.py
Test failed from 2025-09-29 because of hardcoded created_on in UBBLE_IDENTIFICATION_V2_RESPONSE
> (BSR)[API] fix: test_ubble_workflow_with_eligibility_change_with_first_attempt_at_18

- api/src/pcapi/connectors/entreprise/api.py
- api/src/pcapi/connectors/entreprise/backends/api_entreprise.py
- api/src/pcapi/routes/pro/structure_data.py
- api/tests/connectors/api_entreprise_test.py
- api/tests/routes/pro/get_structure_data_test.py
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37947)
API Entreprise used to return a specific error code when caller's SIRET and searched SIRET where identical. This error is not sent anymore, and the specific checks are now useless.
> (PC-37947)[API] chore: Remove error case for pass Culture SIRET

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/schemas/__init__.py
- api/src/pcapi/core/offers/schemas/deprecated.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/serialization/offers_serialize/__init__.py
- api/src/pcapi/routes/serialization/offers_serialize/deprecated.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_commands.py
- api/tests/core/offers/test_schemas.py
- api/tests/routes/pro/post_offer_test.py
- pro/src/apiClient/adage/services/DefaultService.ts
- pro/src/apiClient/v1/services/DefaultService.ts
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37815)
Ajout d'une nouvelle route de création d'offre, appelée à remplacer celle de création d'offre brouillon. L'idée étant de revoir le parcours de création d'offre du portail pro en créant directement une offre sans chercher d'étape intermédiaire et de notion de brouillon qui complique les choses et qui n'a pas réellement de sens.
Le coeur du commit est relativement court, les plus importants ajouts se situent au niveau des tests. Afin d'y voir un peu plus clair j'ai regroupé les créations par ensemble de sous-catégories pour commencer à identifier les règles implicites en place et avoir une idée de certaines incohérences (je n'ai rien mis ou presque à ce niveau-là dans les tests pour éviter d'en avoir beaucoup trop). Pour avoir …
> (PC-37815)[API] feat: pro: new offer creation route

- pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.spec.tsx
- pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx
[Ticket Jira](https://passculture.atlassian.net/browse/PC-38017)
Lorsque l'on ouvre le récapitulatif d'une offre vitrine, et que l'on clique sur "Retour à la liste des offres" on veut rediriger vers la liste des offres vitrines et non réservable
> (PC-38017)[PRO] feat: redirect to offer list template
