api/src/pcapi/core/finance/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31663
=> (PC-31663)[API] revert: partial revert of PC-31414

api/src/pcapi/core/offers/api.py, api/tests/core/offers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31592
=> (PC-31592)[API] feat: get withdrawalDetails from venue in offer creation

api/src/pcapi/core/offers/api.py, api/tests/routes/pro/post_draft_offer_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31216
Activation de la FF (oubli)
=> (PC-31217)[API]feat: ean validation feature flip activation

pro/src/screens/OfferEducationalStock/__specs__/validationSchema.spec.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31671
**Objectif**
Corriger une erreur d'import dans la ci après un merge qui avait quelques commits de retard.
=> (PC-31671)[PRO] fix: Fix ci cannot find function sub after merge.

api/src/pcapi/core/offerers/models.py
We only need one to know it has offers.
Otherwise, memory consumption skyrockets and the pod explodes.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31664
=> (PC-31664)[PRO] fix: hasOffers should not load all the offers

pro/src/ui-kit/form/TimePicker/BaseTimePicker.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31617
=> (PC-31617)[PRO] fix: timepicker init value display

pro/src/hooks/useSuggestedSubcategoriesAbTest.ts, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/screens/OfferType/OfferType.tsx, pro/src/screens/OfferType/__specs__/OfferType.navigation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31530
=> (PC-31530)[PRO] feat: ab test for suggested subactegories

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py, api/src/pcapi/connectors/entreprise/models.py, api/src/pcapi/core/offerers/tasks.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/tests/connectors/api_entreprise_test.py, api/tests/connectors/api_entreprise_test_data.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31673
=> (PC-31673)[API] fix: exception when company creation date is unknown by API Entreprise

api/src/pcapi/routes/backoffice/filters.py, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31676
=> (BSR)[BO] fix: modify connect as sentence

pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31681
=> (PC-31681)[PRO] fix: Modal wording change

pro/src/screens/OffererStats/OffererStatsScreen.tsx, pro/src/screens/OffererStats/__specs__/OffererStatsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30379
> [!WARNING]
> Sous FF `WIP_ENABLE_OFFER_ADDRESS`
=> (PC-30379)[PRO] feat: Change wording on stats page

api/src/pcapi/core/subscription/phone_validation/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31252
=> (PC-31252)[API] feat: add phone number to patch profile body

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240906T161800_d0a81150dd8d_add_unique_constraint_on_price_category_offerid_idatprovider.py, api/src/pcapi/core/offers/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31630
=> (PC-31628)[API] feat: transform unique index `unique_ix_offer_id_id_at_provider` into unique constraint `unique_offer_id_id_at_provider`

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31645
Puisque les pricings "gratuits" on déjà été identifiés à la génération des cashflows, et qu'ils ont été marqués en PROCESSED sans les lier à un cashflow, il devient très facile des les identifier ensuite, donc pas besoin de tout refiltrer dans la query.
=> (PC-31645)[API] feat: mark free pricings as invoiced more easily

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py, api/src/pcapi/connectors/entreprise/backends/testing.py, api/src/pcapi/connectors/entreprise/models.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/entreprise_info_rcs.html, api/tests/connectors/api_entreprise_test.py, api/tests/connectors/api_entreprise_test_data.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31741
=> (PC-31741)[BO] fix: exception when an observation in RCS data has no date

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31537
note d'ux: quand on a les droits fraude ET les droits de support ça rend l'interface très lourde mais en pratique personne n'a cette combinaison de droits (elle n'a pas de sens)
=> (PC-31537)[BO] feat: permit to manage individual offer from the BO

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/tests/core/bookings/test_models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31757
=> (PC-31757)[BO] fix: OneSideCancellationForbidden exception with new backoffice reasons

pro/src/app/App/analytics/firebase.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31530
=> (PC-31530)[PRO] fix: ab test begin being undefined

pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31512
Sur ADAGE depuis la page de projet, il y a un lien qui redirige vers les offres du pass avec un paramètre tab=institution, on souhaite rediriger vers la page "Pour mon établissement" dans ce cas. On en profite pour gérer les cas pour les favoris, la découverte aussi au cas où adage en aurait besoin à l'avenir
=> (PC-31512)[PRO] feat: redirect from adage my project to my establishment

pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.module.scss, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31286
=> (PC-31286)[PRO] feat: add button to clear indiv. creation pre-filled form

pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31762
=> (PC-31762)[PRO] feat: ean search - remove duplicate ean input, change banner after post

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/exceptions.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/native/v1/account.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31623
=> (PC-31623)[API] feat: add native anonymization route

pro/src/ui-kit/form/TimePicker/BaseTimePicker.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31810
=> (PC-31810)[PRO] fix: support undefined duration value in BaseTimePicker

pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
=> (BSR)[PRO] fix: Fix logout url.

pro/src/app/App/App.tsx, pro/src/hooks/useRedirectLoggedUser.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31811
- Corriger les erreurs liées au fait que localstorage pourrait ne pas être `available`
=> (PC-31811)[PRO] fix: Check for storage availability before `removeItem`.

.github/workflows/dev_on_workflow_configure_live_channel_pro_generic.yml
This reverts commit 8ccfca055ef15c1c74b5a8f6fedaae33baae131f.
=> Revert "(BSR)[PRO] fix: firebase PRO deployment"

api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30690
=> (PC-30690)[PRO] fix: Add the filter for REIMBURSED displayedStatus

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31807
=> (PC-31807) ci: Github deployments take pro PRs into account

api/src/pcapi/core/offers/api.py, api/tests/routes/pro/patch_draft_offer_test.py
L'ajout de la ligne _format_extra_data permet de ne mettre à jour que les informations utiles et non tout le payload renvoyé par le front dans tous les cas
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31796
=> (PC-31796)[API] fix: patch should not update extra data with empty values

api/src/pcapi/core/external_bookings/serialize.py, api/src/pcapi/core/offerers/models.py, api/tests/core/external_bookings/test_api.py
Utiliser les offererAddress dans les routes natives
Cette PR: external bookings info
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30808
=> PC-30808 oa external bookings

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31441
=> (PC-31441)[API] feat: allow batch action even if some case fails

.github/workflows/dev_on_workflow_deploy.yml
This reverts commit 9bc0cf63cf97aa06ea7fdf0af7f265e38696ed19.
=> Revert "(PC-31807) ci: Github deployments take pro PRs into account"

api/src/pcapi/routes/public/collective/endpoints/simulate_adage_steps/bookings.py
Une précédente PR a été merged un peu vite, et contenait le résultat d'une rebase un peu rapide.
=> (BSR)[API] fix: rebase: api_key_required should not have been kept

api/documentation/src/pages/change-logs.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31625
=> (PC-31625)[API] feat: update september 2024 change-logs

api/tests/core/educational/test_repository.py
The feature flag ENABLE_COLLECTIVE_NEW_STATUSES is here to enable the use of new status like REIMBURSED.
=> (BSR)[PRO] refactor: replace condition in test by feature flag use

api/src/pcapi/core/reactions/api.py, api/src/pcapi/routes/native/v1/reaction.py, api/src/pcapi/routes/native/v1/serialization/reaction.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/reaction_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31800
=> (PC-31800)[API] feat: accept bulk update on post reaction route

api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_price_categories.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31819
=> (PC-31819)[BO] fix: show price from price_category in offer details

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/validation.py, api/src/pcapi/routes/pro/venues.py, api/tests/routes/pro/post_venue_test.py
Check if venue with siret exists before trying to create it and display an error on PRO app. 
[Sentry issue](https://sentry.passculture.team/organizations/sentry/issues/1616777/?project=5&referrer=jira_integration)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31831
Before : 
After (typo on screenshot has been fixed) :
=> (PC-31831)[API] fix: do not fail if venue already exists

api/src/pcapi/routes/backoffice/offers/forms.py, api/tests/routes/backoffice/offers_test.py
Micro correction pourcent -> pourcentage
=> (BSR)[BO] fix: wording

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/constants.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31750
=> Pc 31750 rpa forbid fraud anonymisation

api/src/pcapi/templates/invoices/debit_note.html, api/tests/files/invoice/rendered_debit_note.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31817
AVANT
APRES :
=> (PC-31817)[BO] refactor: modifie wording template debit note

api/src/pcapi/connectors/titelive.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31873
J'ai testé ce code en production, sur un pod console
=> (PC-31873)[API] fix: remove extra space from auth bearer token

api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_models.py, api/tests/core/educational/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31808
=> (PC-31808)[PRO] fix: output the good displayedStatus when the bookingLimitDatetime is passed

pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.admin.spec.tsx, pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx, pro/src/screens/CollectiveOffersScreen/CollectiveOffersScreen.tsx, pro/src/screens/CollectiveOffersScreen/CollectiveOffersSearchFilters/CollectiveOffersSearchFilters.tsx, pro/src/screens/CollectiveOffersScreen/__specs__/CollectiveOffersScreen.spec.tsx, pro/src/screens/IndividualOffersScreen/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx, pro/src/screens/IndividualOffersScreen/__specs__/IndividualOffersScreen.spec.tsx, pro/src/screens/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx, pro/src/screens/TemplateCollectiveOffersScreen/TemplateOffersSearchFilters/TemplateOffersSearchFilters.tsx, pro/src/screens/TemplateCollectiveOffersScreen/__specs__/TemplateCollectiveOffersScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31715
Ce n'est plus de la nouveauté donc on supprime le tag nouveau ainsi que la bannière d'explication pour les offres archivées
=> (PC-31715)[PRO] feat: delete new tag and callout archivage

api/src/pcapi/routes/adage/v1/serialization/prebooking.py, api/tests/routes/adage/v1/conftest.py, api/tests/routes/adage/v1/get_prebookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31679
=> (PC-31679)[ADAGE] feat: Add the cancellationReason in adage API

pro/src/core/Bookings/constants.ts, pro/src/core/Bookings/types.ts, pro/src/core/Bookings/utils.ts, pro/src/core/Offers/constants.ts, pro/src/pages/Bookings/adapters/getFilteredIndividualBookingsAdapter.ts, pro/src/screens/Bookings/Bookings.tsx, pro/src/screens/Bookings/PreFilters/PreFilters.tsx, pro/src/screens/Bookings/PreFilters/__specs__/PreFilters.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30829
- filtrer les réservations par OA
=> (PC-30829)[PRO] feat: OffererAddress select in bookings filters.

api/src/pcapi/core/offers/repository.py, api/tests/routes/pro/get_offers_test.py
Utiliser le fuseau horaire de l'adresse de l'offre dans les filtres de get_offer_by_filter cad dans l'endpoint /offers [GET]
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30553
=> (PC-30553)[API] feat: use offer address timezone in get_offer_by_filter

pro/src/store/features/selectors.ts
https://sentry.passculture.team/organizations/sentry/issues/1431342/?environment=production&project=2&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=2
=> (BSR)[PRO] fix: error Sentry features could be undefined

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31824
Use of argocd app sync without --async option
=> PC-31824 - Use argocd-sync/v0.3.0

pro/yarn.lock
Mise à jour de browser-list pour retirer le warning.
=> (BSR)[PRO] bump: update browser-list.

pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31839
=> (PC-31839)[PRO] fix: readOnlyFields on offer creation/edition

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31744
=> (PC-31744)[API] feat: add indexation date for offers in Algolia

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/tests/routes/backoffice/offers_test.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/pro/get_offers_test.py, api/tests/routes/public/individual_offers/v1/get_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29599
=> (PC-29599)[API] feat: use product description instead of offer's one

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31674
=> (PC-31674)[API] feat: add command to fetch missing synchronization at acceslibre

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31958
=> (PC-31958)[API] feat: make some templates into pro templates

api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py, api/tests/routes/backoffice/multiple_offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31934
=> (PC-31934)[BO] fix: reject product by EAN as incompatible did not save in database

pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.module.scss, pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/Subcategories/Subcategories.module.scss, pro/src/screens/IndividualOffer/DetailsScreen/Subcategories/Subcategories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31931
=> (PC-31931)[PRO] fix: Fix callout margins

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py, api/tests/routes/backoffice/multiple_offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31934
2 commits, qu'on peut idéalement relire séparément.
=> (PC-31934)[BO] fix: reject product by EAN - real fix for atomic + fix for performance

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/offerers/offerer_tag_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31472
=> (PC-31472)[BO] chore: migrate offerer part of BO to atomic

pro/cypress/e2e/features/adage.feature
=> (BSR)[PRO] tests: skip ADAGE e2e failings tests

api/src/pcapi/core/mails/CONTRIBUTING.md, api/src/pcapi/core/mails/backends/sendinblue.py, api/src/pcapi/core/mails/models.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation.py, api/src/pcapi/notifications/sms/backends/sendinblue.py, api/tests/core/mails/tests.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31987
=> (PC-31987)[API] feat: remove sender from Brevo backend

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31999
=> (PC-31999)[BO] fix: wrong display of active deposit column

pro/src/screens/IndividualOffer/InformationsScreen/utils/files.spec.tsx, pro/src/screens/IndividualOffer/hooks/useIndividualOfferImageUpload.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31327
Gestion des erreurs d'upload d'image
=> (PC-31327)[PRO] fix: Handle image upload failing.

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31824
=> PC-31824 - Use argocd-sync v0.3.0

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31974
Ajout du label "Gestes commerciaux" pour les InvoiceLines et mettre à jour les justificatifs de remboursements.
Avant :
Après :
=> (PC-31974)[API] feat: generate 'commercial gesture' invoice lines and update invoice pdf accordingly

api/src/pcapi/routes/backoffice/custom_reimbursement_rule/forms.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/addresses.html
Corrections anecdotiques dans le BO.
=> (BSR)[BO] minor fixes

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32023
=> (PC-32023)[API] feat: modify ranking attributes for offers in Algolia

.github/workflows/dev_on_pull_request_workflow.yml, .github/workflows/dev_on_push_workflow_main.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31788
=> PC-31788 - Cancel step e2e

api/src/pcapi/routes/native/v1/favorites.py, api/src/pcapi/routes/native/v1/serialization/favorites.py, api/tests/routes/native/v1/favorites_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31430
=> (PC-31430)[API] feat: user offer address in favorites response

api/src/pcapi/core/offerers/api.py
Si on a un timeout chez acceslibre lorsqu'on essaye de récupérer une venue, on veut continuer le script
=> (BSR)[API] feat: improve log and error handling for acceslibre matching script

pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31752
=> (PC-31752)[PRO] fix: wrong condition on EAN FF

api/src/pcapi/routes/backoffice/providers/blueprint.py, api/src/pcapi/routes/backoffice/providers/forms.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31946
=> (PC-31946)[BO] fix: HMAC key was not filled properly in provider edition

.github/workflows/dev_on_workflow_build_and_tag.yml, .github/workflows/dev_on_workflow_push_docker_image.yml
=> [action] Add prefix to tag for cleanup policies

pro/src/store/features/selectors.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32080
=> (PC-32080)[PRO] fix: Issue with feature flags

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/tests/core/offers/test_api.py, api/tests/routes/public/individual_offers/v1/patch_date_test.py, api/tests/routes/public/individual_offers/v1/post_event_stocks_test.py
Fix this error : https://sentry.passculture.team/organizations/sentry/issues/1618045/events/13a0f8504e0f42b785527e6ea076d224/?project=5
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31984
=>  (PC-31984)[API] Add validation step on modification of `stock.idAtProvider` to prevent 500 caused by DB constraint violation

pro/src/index.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32083
=> (PC-32083)[PRO] fix: re-enable zooming/scaling in <meta> #a11y

api/.env.production, api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240924T131901_b409480c6113_create_special_events_models.py, api/src/pcapi/alembic/versions/20240924T131902_e76deb66bf86_create_special_operations_indexes.py, api/src/pcapi/alembic/versions/20240924T131903_909195d99f43_validate_constraint_on_special_event_response_user_id.py, api/src/pcapi/alembic/versions/20240926T162803_53b965cf3401_validate_constraint_on_special_event_offerer_id.py, api/src/pcapi/alembic/versions/20240926T162904_e1eb1a0b2870_validate_constraint_on_special_event_venue_id.py, api/src/pcapi/connectors/typeform.py, api/src/pcapi/core/operations/api.py, api/src/pcapi/core/operations/factories.py, api/src/pcapi/core/operations/models.py, api/src/pcapi/core/permissions/models.py, api/src/pcapi/models/__init__.py, api/src/pcapi/repository/clean_database.py, api/src/pcapi/routes/backoffice/__init__.py, api/src/pcapi/routes/backoffice/operations/blueprint.py, api/src/pcapi/routes/backoffice/operations/forms.py, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/routes/backoffice/templates/operations/list_events.html, api/src/pcapi/sandboxes/scripts/creators/e2e/create_role_permissions.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_special_events.py, api/src/pcapi/settings.py, api/tests/connectors/typeform/fixtures.py, api/tests/connectors/typeform/typeform_test.py, api/tests/core/operations/test_api.py, api/tests/core/operations/test_models.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/operations_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31558
=> (PC-31558)[API] feat: connection with Typeform API from the Backoffice

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/search/__init__.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31755
=> (PC-31755)[BO] fix: unindex offers and venues when offerer is suspended

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31824
Use argocd-sync/v0.5.0
=> PC-31824 - Use argocd-sync/v0.5.0

pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.module.scss, pro/src/screens/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/EanSearchCallout/EanSearchCallout.module.scss, pro/src/screens/IndividualOffer/DetailsScreen/EanSearchCallout/EanSearchCallout.tsx, pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx, pro/src/screens/IndividualOffer/DetailsSummary/__specs__/DetailsSummary.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/__specs__/serializer.spec.ts, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/serializer.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31287
=> (PC-31287)[PRO] feat: display callout + remove edit button on details summary for product based offers

pro/src/screens/IndividualOffer/hooks/useIndividualOfferImageUpload.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32100
=> (PC-32100) fix: Error message rewording

api/documentation/static/openapi.json, api/src/pcapi/core/geography/repository.py, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/documentation_constants/http_responses.py, api/src/pcapi/routes/public/documentation_constants/tags.py, api/src/pcapi/routes/public/individual_offers/v1/__init__.py, api/src/pcapi/routes/public/individual_offers/v1/addresses.py, api/src/pcapi/routes/public/individual_offers/v1/serializers/addresses.py, api/tests/core/geography/test_repository.py, api/tests/routes/public/individual_offers/v1/get_address_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31912
=> (PC-31912)[API] feat: add check address endpoint in public API

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offers/api.py
=> (BSR)[API] fix: pylint too-many-arguments complaint

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32097
=> (PC-32097)[API] feat: use endDatetime to price collectiveBookings

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31922
=> (PC-31922)[PRO] bump: Update JSDOM

api/src/pcapi/routes/backoffice/venues/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32133
=> (PC-32133)[BO] fix: venue deletion in BO

api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer/details.html, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32098
=> (PC-32098)[BO] feat: show collective offer start AND end date

api/src/pcapi/routes/native/v1/account.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31908
=> (PC-31908)[API] feat: add new suspicious login route using jwt

api/src/pcapi/core/educational/adage_backends/serialize.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/adage/v1/serialization/prebooking.py, api/src/pcapi/routes/pro/offers.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_repository.py, api/tests/routes/pro/get_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30554
=> (PC-30554)[API] feat: Use offer address timezone to filter stocks

api/src/pcapi/routes/pro/users.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31861
- ❌ J'ai écrit les tests nécessaires: aucune idée de comment tester cette erreur ...
=> (PC-31861)[API] fix: error during update of user pro flags

pro/src/screens/IndividualOffer/DetailsSummary/DetailsSummary.tsx, pro/src/screens/IndividualOffer/DetailsSummary/__specs__/DetailsSummary.spec.tsx, pro/src/screens/IndividualOffer/UsefulInformationsSummaryScreen/UsefulInformationsSummary.tsx, pro/src/screens/IndividualOffer/UsefulInformationsSummaryScreen/__specs__/UsefulInformationsSummary.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32139
=> (PC-32139)[PRO] feat: Moves offers location details in "Useful Informations" section

.github/workflows/dev_on_workflow_build_and_tag.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32173
=> (PC-32173)[GA] fix: docker image missing tag

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_api.py, api/tests/core/educational/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32130
=> (PC-32130)[PRO] fix: Use endDate for triggering the end of a collectiveOffer

api/src/pcapi/routes/pro/venues.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/patch_venue_test.py, pro/src/apiClient/v1/models/EditVenueBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32180
=> (PC-32180)[API] feat: add isManualEdition to PATCH /venues/<id> API

pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.module.scss, pro/src/screens/IndividualOffersScreen/IndividualOffersSearchFilters/IndividualOffersSearchFilters.module.scss, pro/src/screens/IndividualOffersScreen/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31207
=> (PC-31207)[PRO] fix: margins on indivdual offer filters, accessibility sections on venue/offer display

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32193
=> (PC-32193)[API] ci: pull rebase before pushing when deploying

api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_product_by_ean_test.py, pro/src/apiClient/v1/models/GetProductInformations.ts, pro/src/screens/IndividualOffer/DetailsScreen/types.ts, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32179
=> (PC-32179)[API] fix: Fix search by ean when product has no description

api/src/pcapi/models/feature.py, api/src/pcapi/routes/auth/discord.py, api/src/pcapi/routes/auth/exceptions.py, api/src/pcapi/routes/auth/templates/discord_signin_disabled.html, api/tests/routes/auth/discord_test.py
On a peu (trop peu) de users qui ont rejoint le discord. La whitelist semble poser problème.
On la retire, et on ajoute un bouton OFF si jamais l'adoption s'emballe
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32174
Screen du nouveau template
=> PC-32174 remove whitelist

api/src/pcapi/core/users/api.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31968
=> (PC-31968)[BO] feat: do not cancel event bookings on fraud suspicion

api/src/pcapi/routes/backoffice/collective_offers/forms.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32191
=> (PC-32191)[BO] fix: search for free offers

api/tests/scripts/external_users/batch_update_users_attributes_test.py
Ticket Jira (ou description si BSR) : fix d'un test
=> (BSR)[API] fix: fix brevo script test

api/src/pcapi/core/offers/repository.py, api/src/pcapi/scheduled_tasks/commands.py, api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32168
=> (PC-31268)[API] fix: remove collective draft offers deletion cron

pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx
=> (BSR)[PRO] fix: Remove debug label

api/src/pcapi/core/categories/subcategories_v2.py, api/tests/routes/native/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32117
=> PC-32117 change film native categories

.github/workflows/dev_on_workflow_deploy_pro_pr_version_generic.yml, .github/workflows/dev_on_workflow_deploy_storybook.yml, .github/workflows/dev_on_workflow_tests_pro.yml, .github/workflows/dev_on_workflow_tests_pro_e2e.yml, .github/workflows/dev_on_workflow_tests_pro_e2e_migration.yml, .github/workflows/dev_on_workflow_update_api_client_template.yml
=> [BSR] bump node workflow version

api/src/pcapi/core/users/models.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/authentication_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32013
=> (PC-32013)[API] feat: add new waiting for anonymization account status

.gitignore, api/src/pcapi/connectors/beneficiaries/ubble.py, api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30761
=> (PC-30761)[API] refactor: prepare ubble connector for v2

pro/src/components/IndividualOfferForm/OfferLocation/validationSchema.ts, pro/src/screens/IndividualOffer/DetailsScreen/validationSchema.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32200
Corrige les 2 soucis suivants :
=> (PC-32200)[PRO] fix: trimmer les espaces pour les champs d'adresse

.github/workflows/dev_on_workflow_tests_api.yml, .github/workflows/dev_on_workflow_tests_pro_e2e.yml, .github/workflows/dev_on_workflow_tests_pro_e2e_migration.yml
=> [API] BSR: update docker login on ci workflows

api/src/pcapi/connectors/recommendation.py
These warnings appeared ~40_000 times during a 15 minutes time span -> https://cloudlogging.app.goo.gl/n4pVTqgaLNaFgFdZ7
=> (BSR)[API] chore: filter InsecureRequestWarning for reco calls

api/src/pcapi/core/history/models.py, api/src/pcapi/core/providers/api.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/pro/venue_providers.py, api/tests/core/providers/test_api.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32066
=> (PC-32066)[BO] feat: manage provider sync from venue page

api/documentation/src/pages/change-logs.md, api/documentation/static/openapi.json, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_event_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32201
- **Change logs**
- **REST API doc**
=> (PC-32201)[API] feat: add `idsAtProvider` query param in public API `GET` event stocks endpoint

pro/src/pages/Collaborators/Collaborators.module.scss, pro/src/pages/Collaborators/Collaborators.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31588
Avant: 
Après
=> (PC-31588)[PRO] fix: Issue with add collaborator alignment

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31928
=> (PC-31928)[PRO] chore: Update testing library Cypress

pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31904
=> (PC-31904)[PRO] fix: prevent 'Ajouter une ou plusieurs dates' modal width to increase on start time additions

api/documentation/static/openapi.json, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/serialization/venues.py, api/tests/routes/public/collective/endpoints/get_collective_offers_venues_test.py, api/tests/routes/public/individual_offers/v1/get_offerer_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31420
Dans réponse de la route /offerer_venues de l'API publique, indiquer si la structure a le droit de créer une offre Adage.
=> (PC-31420)[API] feat: public api: add allowedOnAdage field

api/src/pcapi/routes/backoffice/venues/blueprint.py
Correction de l'activation/désactivation qui ne marchait pas en revue PM.
https://passculture.atlassian.net/browse/PC-32066
=> (PC-32066)[BO] fix: manage provider sync from venue page

pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/AdagePreviewLayout.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/__specs__/AdagePreviewLayout.spec.tsx, pro/src/pages/CollectiveOfferPreviewEdition/__specs__/CollectiveOfferPreviewEdition.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32004
Ajouter la bonne adresse de l'évènement dans l'aperçu sur adage
=> (PC-32004)[PRO] fix: fix address in adage preview

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/external/booking_notifications.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/models/feature.py, api/src/pcapi/scheduled_tasks/commands.py, api/tests/core/bookings/external/test_booking_notifications.py, api/tests/core/bookings/test_api.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/delete_stock_test.py, api/tests/routes/public/booking_token/v2/patch_cancel_booking_by_token_test.py, api/tests/scheduled_tasks/commands_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31051
=> Pc 31051 hide batch push notifs behind ff

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/subscription/dms/commands.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/tests/routes/backoffice/offers_test.py, api/tests/routes/pro/patch_offer_test.py, api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31781
=> (PC-31781)[API] refactor: use atomic in bo offer routes

pro/src/core/Offers/constants.ts, pro/src/core/Offers/hooks/useDefaultCollectiveSearchFilters.ts, pro/src/core/Offers/utils/computeCollectiveOffersUrl.ts, pro/src/core/Offers/utils/serializer.ts, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffers.spec.tsx, pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffersQueryParams.spec.tsx, pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplicationScreen.tsx, pro/src/screens/CollectiveOfferSelectionDuplication/__specs__/CollectiveOfferSelectionDuplicationScreen.spec.tsx, pro/src/screens/OfferType/OfferType.tsx, pro/src/screens/OfferType/__specs__/OfferType.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32202
=> (PC-32202)[PRO] feat: remove default status filters

api/src/pcapi/backoffice_app.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32288
=> (PC-32288)[BO] perf: cache backoffice static files in the browser

pro/src/hooks/useInitReCaptcha.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31521
- Handle android 13/14 issue with recaptcha.
=> (PC-31521)[PRO] fix: Reset can trigger issue on old android devices.

pro/src/components/SideNavLinks/SideNavLinks.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31398
- Fix de scrollbar
=> (PC-31398)[PRO] style: Hide scrollbars on side nav links.

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31924
- MAJ de date-fns
=> (PC-31924)[PRO] bump: date-fns

.github/workflows/dev_on_workflow_build_docker_image.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32308
=> (PC-32308) fix: pin runner version to install poetry

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31924
MAJ de @types/node
=> (PC-31924)[PRO] bump: @types/node

.github/workflows/dev_on_workflow_deploy.yml
Fix for wrong configMapRef after chart migration to v1.0.x
=> Use action pcapi-migration/v0.2.1

pro/package.json, pro/src/screens/OfferEducational/OfferEducationalForm/__specs__/OfferEducationalForm.spec.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31929
Upgrade de vitest et @vitest/coverage-v8
=> (PC-31929)[PRO] feat: upgrade vitest

api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/routes/adage_iframe/offers.py, api/tests/routes/adage_iframe/get_collective_offers_for_my_institution.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32369
=> (PC-32369)[API] fix: do not show archived offers in adage iframe route

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32325
=> (PC-32325)[API] feat: modify searchable attributes for offers in Algolia 

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/pro/users.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32249
=> (PC-32249)[API] fix: add logs to user_pro_flags for investigation

api/src/pcapi/core/subscription/api.py, api/tests/core/subscription/test_api.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/banner_test.py
Amend: 0990b8c4
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32188
=> (PC-32188)[API] fix: toggle phone validation using feature flag

pro/src/screens/IndividualOffer/DetailsScreen/__specs__/utils.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/serializers.spec.ts, pro/src/screens/IndividualOffer/InformationsScreen/serializePatchOffer.ts, pro/src/utils/__specs__/isPlainObject.spec.ts, pro/src/utils/__specs__/trimStringsInObject.spec.ts, pro/src/utils/isPlainObject.ts, pro/src/utils/trimStringsInObject.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32290
=> (PC-32290)[PRO] feat: Trim whitespaces in offer creation/edition

api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/pro_users/forms.py, api/src/pcapi/routes/backoffice/templates/components/badges.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/backoffice/templates/pro_user/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/static/backoffice/scss/pc/_variables.scss, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32225
=> (PC-32225)[BO] feat: delete old/new nav status

api/src/pcapi/core/educational/models.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/models/feature.py, api/tests/core/finance/test_api.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32048
=> (PC-32048)[API] feat: remove USE_END_DATE_FOR_COLLECTIVE_PRICING FF

api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32388
=> (PC-32388)[BO] fix: batch validation crash when something went wrong

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32296
=> PC-32296 add release date to algolia

api/src/pcapi/core/categories/subcategories_v2.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32346
=> PC-32346 rename streaming category

pro/src/pages/Home/Homepage.tsx
Correction du problème de l'envoie des user proflags
=> (BSR)[PRO] fix: Correct proflag issue

api/documentation/src/pages/change-logs.md, api/documentation/static/openapi.json, api/src/pcapi/connectors/api_adresse.py, api/src/pcapi/core/geography/repository.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/public/documentation_constants/http_responses.py, api/src/pcapi/routes/public/individual_offers/v1/__init__.py, api/src/pcapi/routes/public/individual_offers/v1/addresses.py, api/src/pcapi/routes/public/individual_offers/v1/serializers/addresses.py, api/tests/connectors/api_adresse/api_adresse_test.py, api/tests/connectors/api_adresse/fixtures.py, api/tests/core/geography/test_repository.py, api/tests/routes/public/individual_offers/v1/get_address_test.py, api/tests/routes/public/individual_offers/v1/get_search_addresses_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32195
- **`GET` Address**:
- **`SEARCH` Addresses**:
- **Change logs**:
=> (PC-32195)[API] feat: add `GET` address and `SEARCH` addresses endpoint in public API

api/documentation/src/pages/change-logs.md, api/documentation/static/openapi.json, api/src/pcapi/routes/public/individual_offers/v1/addresses.py, api/src/pcapi/routes/public/individual_offers/v1/serializers/addresses.py, api/tests/routes/public/individual_offers/v1/post_address_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31914
**POST address**:
**Change logs**
=> (PC-31914) [API] Add `POST` address endpoint in public API

api/src/pcapi/routes/public/individual_offers/v1/addresses.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31914
=> (PC-31914)[API] feat: add missing transaction in `create_address` controller

api/src/pcapi/connectors/api_adresse.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32195
=> (PC-32195)[API] feat: add `city` param in query_params used to search API

api/src/pcapi/core/logging.py, api/src/pcapi/flask_app.py, api/src/pcapi/validation/routes/users_authentifications.py
Cette PR ajoute des informations lors du log post-traitement de la requête : l'id de la clé d'api et du partenaire technique, afin de faciliter les recherches.
=> (BSR)[API] feat: log provider id

api/src/pcapi/core/permissions/api.py, api/src/pcapi/routes/backoffice/admin/blueprint.py, api/src/pcapi/routes/backoffice/admin/forms.py, api/src/pcapi/routes/backoffice/templates/admin/roles_management.html, api/tests/routes/backoffice/admin_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32431
Commentaire obligatoire en production et staging, optionnel ailleurs.
=> (PC-32431)[BO] feat: add a comment when updating permissions for a role

pro/src/components/CollectiveStatusLabel/CollectiveStatusLabel.tsx, pro/src/components/CollectiveStatusLabel/__specs__/CollectiveStatusLabel.spec.tsx, pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx, pro/src/components/StatusLabel/StatusLabel.tsx, pro/src/components/StatusLabel/__specs__/StatusLabel.spec.tsx, pro/src/core/OfferEducational/constants.ts, pro/src/pages/Home/StatisticsDashboard/OfferStats.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/CollectiveDeactivationConfirmDialog.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/CollectiveOffersActionsBar.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/IndividualDeactivationConfirmDialog.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/IndividualOffersActionsBar.tsx, pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffers.spec.tsx, pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffersQueryParams.spec.tsx, pro/src/screens/CollectiveOffersScreen/CollectiveOffersSearchFilters/CollectiveOffersSearchFilters.tsx, pro/src/screens/IndividualOffer/Status/StatusToggleButton.tsx, pro/src/screens/IndividualOffersScreen/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/FormDates.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/__specs__/FormDates.spec.tsx, pro/src/screens/TemplateCollectiveOffersScreen/TemplateOffersSearchFilters/TemplateOffersSearchFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31882
=> (PC-31882)[PRO] feat: rename statuses

api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_models.py, api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32246
=> (PC-32246)[API] fix: collective offer template filtering on status

pro/src/pages/VenueSettings/VenueSettingsForm.tsx, pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32484
Fix un oubli de feature flag sur de précédents tickets déjà en Staging
=> (PC-32484)[PRO] fix: Adds forgotten feature flag to PC-30946 and PC-31468 !

api/src/pcapi/core/categories/subcategories_v2.py, api/tests/routes/native/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32459
=> (PC-32459)[API] feat: add search group 'Musique'

api/src/pcapi/routes/backoffice/pro/blueprint.py, api/tests/routes/backoffice/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32501
=> (PC-32501)[BO] fix: connect as when role are not properly synchronized

api/src/pcapi/routes/backoffice/users/blueprint.py, api/tests/routes/backoffice/users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32495
=> (PC-32495)[BO] fix: unsuspend backoffice user

pro/src/pages/Reimbursements/Income/Income.module.scss, pro/src/pages/Reimbursements/Income/Income.tsx, pro/src/pages/Reimbursements/Income/IncomeResultsBox/IncomeResultsBox.module.scss, pro/src/pages/Reimbursements/Income/IncomeResultsBox/IncomeResultsBox.tsx, pro/src/pages/Reimbursements/Income/IncomeVenueSelector/IncomeVenueSelector.module.scss, pro/src/pages/Reimbursements/Income/IncomeVenueSelector/IncomeVenueSelector.tsx, pro/src/ui-kit/form/SelectAutoComplete/SelectAutocomplete.tsx, pro/src/ui-kit/form/SelectAutoComplete/SelectedValuesTags/SelectedValuesTags.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32277
=> (PC-32277)[PRO] fix: better-written styles on Income and its subcomponents

pro/src/pages/Accessibility/Commitment.module.scss, pro/src/pages/Accessibility/Commitment.tsx, pro/src/pages/Accessibility/Declaration.module.scss, pro/src/pages/Accessibility/Declaration.tsx, pro/src/pages/Accessibility/MultiyearScheme.module.scss, pro/src/pages/Accessibility/MultiyearScheme.tsx, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31207
=> (PC-31207)[PRO] fix: add missing margins/paddings on accessibility pages + venue edit

api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32545
=> (PC-32545)[API] feat: ask for cultural survey before credit activation

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32590
=> (PC-32590)[API] feat: remove diffusionVersion from Algolia distinct

pro/cypress/e2e/financialManagement.cy.ts
De nouveaux échecs ont fait planter financialManagement depuis qu'on a rajouté desk qui n'a pourtant rien à voir.
Cette PR permet d'attendre que tout soit bien affiché avant de passer à l'étape suivante. Avant, on cliquait sur des choses alors qu'une modale était encore affichée, ou qu'on avait un spinner d'affichage incomplet.
=> (BSR)[PRO] test: try to fix financialManagement by waiting

api/src/pcapi/core/offers/validation.py, api/tests/routes/pro/post_draft_offer_test.py, pro/src/components/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.spec.tsx, pro/src/components/IndividualOffer/DetailsScreen/DetailsEanSearch/DetailsEanSearch.tsx, pro/src/components/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/components/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.spec.tsx, pro/src/components/IndividualOffer/DetailsScreen/DetailsSubForm/DetailsSubForm.tsx, pro/src/components/IndividualOffer/DetailsScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32594
=> (PC-32594) ean search non mandatory for vinyls

pro/src/components/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx, pro/src/components/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx, pro/src/ui-kit/form/Checkbox/Checkbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32378
=> (PC-32248)[PRO] feat: Show unified dialog at offer address/withdrawal edition

api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/core/search/backends/base.py, api/src/pcapi/core/search/backends/testing.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/forms/fields.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/templates/components/display_selector.html, api/src/pcapi/routes/backoffice/templates/components/forms.html, api/src/pcapi/routes/backoffice/templates/components/forms/form_field.html, api/src/pcapi/routes/backoffice/templates/layouts/base.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/utils.py, api/src/pcapi/static/backoffice/js/addons/pc-display-selector.js, api/src/pcapi/static/backoffice/scss/pc/addons/_display_switch.scss, api/src/pcapi/static/backoffice/scss/pc/pc.scss, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32235
NOTE: l'ux est provisoire et sera completement revue dans un prochain ticket
=> Pc 32235 rpa algolia bo

api/src/pcapi/core/offers/repository.py, api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/native/v1/serialization/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/search/test_serialize_algolia.py, api/tests/routes/native/openapi_test.py, api/tests/routes/pro/post_draft_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32562
=> (PC-32562)[API] chore: use product extraData in algolia serializer

api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/tests/core/finance/test_api.py, api/tests/core/finance/test_commands.py
Suppression du feature flag `WIP_ENABLE_FINANCE_INCIDENT`
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32612
=> (PC-32612)[BO] feat: remove WIP_ENABLE_FINANCE_INCIDENT feature flag

api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/native/v1/account_test.py
Amend: 8f80de3fea
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32545
=> (PC-32545)[API] fix: ask cultural survey only for eligible users

api/src/pcapi/routes/backoffice/templates/admin/roles.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-32639
=> (PC-32639)[BO] fix: links to Google Groups

api/src/pcapi/routes/backoffice/templates/offer/details.html
Vu en prod : « Adresse : None »
=> (BSR)[BO] fix: do not show 'None' string

pro/vite.config.ts
=> (BSR)[PRO] chore: ignore *.stories.tsx in vitest

pro/src/commons/store/features/selectors.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32454
=> (PC-32454)[PRO] fix: Issue with isActiveFeature and firefox

api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32562
=> (PC-32562)[API] fix: use product or offer extra data

api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32666
=> (PC-32666)[API] fix: factorize counts

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32413
=> (PC-32413)[API] feat: create feature flag for onboarding epic

api/documentation/static/openapi.json, api/src/pcapi/routes/public/collective/serialization/offers.py, api/src/pcapi/routes/public/documentation_constants/descriptions.py, api/src/pcapi/routes/public/documentation_constants/fields.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31492
API publique : petits correctifs et améliorations de la documentation.
L'objectif est que l'exemple généré pour la création d'une offre collective puisse être copié/collé (à quelque détails près comme l'identifiant du lieu).
=> (PC-31492)[API] feat: improve public api doc

pro/src/app/App/App.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32652
=> (PC-32652)[PRO] fix: Fix current user undefined

pro/src/components/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx
=> (BSR)[PRO] fix: Correct issue with date in unit tests

api/src/pcapi/core/mails/backends/sendinblue.py, api/src/pcapi/core/mails/models.py, api/src/pcapi/core/mails/transactional/send_transactional_email.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/tasks/serialization/sendinblue_tasks.py, api/tests/core/mails/tests.py, api/tests/core/mails/transactional/test_send_transactional_email.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32660
=> (PC-32660)[API] feat: Prevent transactional emails from unsubscription

api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/offers/repository.py, api/tests/core/bookings/test_repository.py, api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32726
=> (PC-32726) api corrections pour utiliser oa comme source de donnees

api/src/pcapi/core/external/compliance.py, api/src/pcapi/core/offers/factories.py, api/tests/core/external/compliance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32724
=> (PC-32724)[API] fix: upsert offer_compliance

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241018T095515_92cafc4e6b68_drop_venue_check_constraint_venue_is_virtual_xor_has_address.py, api/src/pcapi/core/offerers/models.py, api/tests/core/offerers/test_models.py, api/tests/routes/pro/patch_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32256
=> (PC-32256)[API] fix: Failing update location on venue without siret

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241028T084501_58750d92ea20_fix_saint_martin_departement_code_on_user.py, api/src/pcapi/alembic/versions/20241028T084502_c2282b67bd45_fix_saint_martin_departement_code_on_venue.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/forms/constants.py, api/src/pcapi/utils/postal_code.py, api/tests/core/offerers/test_models.py, api/tests/utils/postal_code_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32692
https://fr.wikipedia.org/wiki/Saint-Martin_(Antilles_fran%C3%A7aises)
=> (PC-32692)[API] fix: Saint-Martin department code is 978

pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
Mock la réponse à https://api-adresse.data.gouv.fr avec limit à 5
=> (BSR)[PRO] test: mock external call to api-adresse.data.gouv.fr

api/tests/routes/external/user_subscription_test.py
=> (BSR)[API] chore: Fix flaky tests due to date

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241014T101659_c1eaf46afc44_add_unique_index_over_address_with_nulls_not_distinct.py, api/src/pcapi/alembic/versions/20241014T140359_464e20772637_drop_unused_unique_index_on_address.py, api/src/pcapi/core/geography/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/static/backoffice/js/addons/pc-postal-address-autocomplete.js, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32087
=> (PC-32087)[BO] feat: Empty banId field when performing manual edition

api/src/pcapi/scripts/pro/upload_reimbursement_csv_to_offerer_drive.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31666
Avoir une remonté dans sentry sans bloquer le script pour les autres User
=> (PC-31666)[API] feat: Mise à jour du niveau de log sur User unknown

pro/src/pages/Reimbursements/Income/Income.spec.tsx, pro/src/pages/Reimbursements/Income/Income.tsx, pro/src/repository/venuesService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32627
=> (PC-32627)[PRO] feat: only load & display relevant venues in stats v2

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/finance/utils.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_new_caledonia_offerers.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32250
Le premier commit vient de https://github.com/pass-culture/pass-culture-main/pull/14782, il faut relire le deuxième commit seulement.
=> Pc 32250 add payment files with nc pricings

pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32773
=> (PC-32773)[PRO] fix: Fixes need to re-click the form validation button if address changed on a venue that has no offers

pro/src/components/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32485
Adapter la date jusqu'à laquelle il est possible de modifier le prix et le nombre de participants lorsqu'une réservation est confirmée en mettant la date de fin + 48h
=> (PC-32485)[PRO] fix: eac date in reservation

pro/cypress/e2e/financialManagement.cy.ts, pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/BankAccountHasPendingCorrectionCallout.tsx, pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx, pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx, pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx, pro/src/pages/Home/Offerers/OffererBanners.tsx, pro/src/pages/Home/Offerers/__specs__/OffererBanners.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/commons/__specs__/utils.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/commons/utils.ts, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/commons/validationSchema.ts, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/components/OfferLocation/OfferLocation.tsx, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx, pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/PricingPointDialog.tsx, pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/validationSchema.ts, pro/src/pages/Reimbursements/BankInformations/__specs__/LinkVenuesDialog.spec.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32735
=> (PC-32735)[PRO] feat: Replace "Lieu" by "Structure"

api/src/pcapi/core/external/compliance.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/core/external/compliance_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32749
=> (PC-32749)[API] chore : read compliance from offer compliance table

pc
=> (BSR)[API] chore: disable pc command that rely on console in production

pro/src/pages/Offers/OffersRoute.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx, pro/src/pages/Reimbursements/__specs__/Reimbursements.spec.tsx
- Correction d'une erreur sentry
=> (BSR)[PRO] fix: handle query error for data displaying.

api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32786
=> (PC-32786)[BO] fix: do not show 'Réservations' and 'Offres associées' without connect-as link

pro/src/commons/utils/__specs__/timezone.spec.ts, pro/src/commons/utils/timezone.ts, pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/ui-kit/form/TimePicker/BaseTimePicker.tsx, pro/src/ui-kit/form/TimePicker/__specs__/BaseTimePicker.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32496
=> (PC-32496)[PRO] fix: rgx control time format in basetime picker and stock/event filtered list

.github/workflows/dev_on_dispatch_release_build.yml, .github/workflows/dev_on_dispatch_release_build_hotfix.yml, .github/workflows/dev_on_dispatch_release_deploy.yml, .github/workflows/dev_on_pull_request_workflow.yml, .github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_build_and_tag.yml, .github/workflows/dev_on_workflow_check_folder_changes.yml, .github/workflows/dev_on_workflow_configure_live_channel_pro_generic.yml, .github/workflows/dev_on_workflow_dependabot_auto_merge.yml, .github/workflows/dev_on_workflow_deploy.yml, .github/workflows/dev_on_workflow_deploy_app_engine_image_resizing.yml, .github/workflows/dev_on_workflow_deploy_maintenance_site.yml, .github/workflows/dev_on_workflow_deploy_pro_pr_version_generic.yml, .github/workflows/dev_on_workflow_deploy_storybook.yml, .github/workflows/dev_on_workflow_mypy_cop.yml, .github/workflows/dev_on_workflow_ping_data_team.yml, .github/workflows/dev_on_workflow_push_docker_image.yml, .github/workflows/dev_on_workflow_tests_api.yml, .github/workflows/dev_on_workflow_tests_api_documentation.yml, .github/workflows/dev_on_workflow_tests_pro.yml, .github/workflows/dev_on_workflow_tests_pro_e2e.yml, .github/workflows/dev_on_workflow_update_api_client_template.yml, .github/workflows/dev_on_workflow_update_jira_issues.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32361
=> (PC-32361) ci:Change image used by ci for ubuntu-22

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
Exceptions which should not really happen in real life, which occurred with sandbox.
Ticket Jira : https://passculture.atlassian.net/browse/PC-32839
=> (PC-32839)[BO] fix: empty error message when booking validation/cancellation failed

pro/cypress/e2e/venue.cy.ts
Il restait un cas Venue qui a été [flaky](https://cloud.cypress.io/projects/rit5sb/runs/1319/test-results/07b2beac-0f58-4688-a668-34449974a7b7/replay) une fois (sur 50 exécutions) et donc il faut mocker
=> (BSR)[PRO] test: remaining api-address.data.gouv.fr not mocked

api/src/pcapi/core/offers/api.py, api/tests/core/offers/test_api.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32756
=> (PC-32756)[API] fix: prevent deactivation of cinemas manual offers

api/src/pcapi/routes/backoffice/fraud/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31786
Ajout du décorateur atomic sur les routes /fraud
=> (BSR)[API] chore: add atomic decorators in fraud routes

api/src/pcapi/utils/requests.py
Log de niveau info seulement sur demande lors des requests sur les services externes. L'objectif est de diminuer la quantité de log. Par défaut les log INFO sont fait.
=> (BSR)[API] refactor: Log info level on requests only if needed

api/src/pcapi/core/offers/repository.py, api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31432
=> PC-31432 oa when stock notifications

api/src/pcapi/core/users/factories.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32561
=> (PC-32561)[BO] feat: tune conditions to show email changed icon

pro/cypress/e2e/adage.cy.ts, pro/cypress/e2e/collectiveBooking.cy.ts, pro/cypress/e2e/cookieBanner.cy.ts, pro/cypress/e2e/createAccount.cy.ts, pro/cypress/e2e/createIndividualOffer.cy.ts, pro/cypress/e2e/desk.cy.ts, pro/cypress/e2e/editDigitalIndividualOffer.cy.ts, pro/cypress/e2e/financialManagement.cy.ts, pro/cypress/e2e/searchCollectiveOffer.cy.ts, pro/cypress/e2e/searchIndividualOffer.cy.ts, pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts, pro/cypress/e2e/venue.cy.ts
Modification des titres des tests pour avoir plus de cohérence avec globalement "I/It should be able to..."
=> (BSR)[PRO] test: consistency in test title "It should"

pro/src/app/App/analytics/firebase.ts, pro/src/commons/core/FirebaseEvents/constants.ts, pro/src/commons/core/OfferEducational/utils/duplicateBookableOffer.ts, pro/src/components/ArchiveConfirmationModal/ArchiveConfirmationModal.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx, pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/OffersTable/Cells/__specs__/CollectiveActionsCells.spec.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/__specs__/CollectiveOffersActionsBar.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32665
=> (PC-32665)[PRO] feat: fix eac trackers

pro/src/commons/utils/factories/individualApiFactories.ts, pro/src/pages/Home/Offerers/OffererBanners.tsx, pro/src/pages/Home/Offerers/__specs__/OffererBanners.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/__specs__/PricingPoint.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32735
- Corrections
=> (PC-32735)[PRO] feat: Replace "Lieu" by "Structure" everywhere

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241024T093500_049490d79544_create_table_chronicle.py, api/src/pcapi/alembic/versions/20241024T093721_cbf6f244c14c_create_table_product_chronicle.py, api/src/pcapi/alembic/versions/20241024T131738_7cd334485a55_create_table_offer_chronicle.py, api/src/pcapi/alembic/versions/20241104T102427_aac1de8cfaf8_validate_constraints_chronicles.py, api/src/pcapi/connectors/typeform.py, api/src/pcapi/core/chronicles/factories.py, api/src/pcapi/core/chronicles/models.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/repository/clean_database.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_chronicles.py, api/src/pcapi/utils/db.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32390
=> Pc 32390 rpa create chronicle db

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32940
=> (PC-32940)[API] feat: add offer address in offer route

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/patch_draft_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31695
=> (PC-31695)[API] feat: Don't create offer address in funnel first step

api/tests/routes/pro/patch_draft_offer_test.py
=> (BSR)[API] chore: Fix deleted FF

pro/src/components/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32929
- Ne pas afficher la modale d'envoi de mail si le label de l'adresse change.
=> (PC-32929)[PRO] feat: Do not trigger dialog if label changed.

api/src/pcapi/core/external/subcategory_suggestion.py, api/src/pcapi/core/external/subcategory_suggestion_backends/base.py, api/src/pcapi/core/external/subcategory_suggestion_backends/fixtures.py, api/src/pcapi/core/external/subcategory_suggestion_backends/subcategory_suggestion.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/schemas.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/external/subcategory_suggestion_test.py, api/tests/routes/pro/get_suggested_subcategories_test.py, pro/src/apiClient/v1/models/PostDraftOfferBodyModel.ts, pro/src/apiClient/v1/models/SuggestedSubcategoriesResponseModel.ts, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/commons/__specs__/utils.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/commons/constants.ts, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/commons/types.ts, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/commons/utils.ts, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/components/DetailsForm/SuggestedSubcategories/SuggestedSubcategories.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetailsAndInformations/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30679
Deux review back & front sont lancés pour cette PR.
**Ne pas merger avant que les deux parties ne soient approved.**
=> (PC-30679)[API] feat: add call_id log to subcategory suggestion

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32561
Jamais deux sans trois.
=> (PC-32561)[BO] fix: conditions for email updated icon

pro/src/components/IndividualOffer/UsefulInformationScreen/UsefulInformationScreen.tsx, pro/src/components/IndividualOffer/UsefulInformationScreen/__specs__/UsefulInformationScreen.spec.tsx, pro/src/pages/VenueSettings/VenueSettingsScreen.tsx, pro/src/pages/VenueSettings/__specs__/VenueSettingsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32966
- Wording changes
=> (PC-32966)[PRO] feat: Wording changes.

pro/src/pages/VenueSettings/setInitialFormValues.ts
Also handle disgraceful whitespace if so.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32804
↓
=> (PC-32804)[PRO] fix: Don't show street field if null

api/src/pcapi/sandboxes/scripts/creators/industrial/create_new_caledonia_offerers.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32707
=> (PC-32707)[API] feat: add new caledonian venues in sandbox

pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOfferRow/__specs__/IndividualOfferRow.spec.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/DeleteConfirmDialog.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/IndividualOffersActionsBar.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/__specs__/IndividualOffersActionsBar.spec.tsx, pro/src/pages/Offers/components/IndividualOffersScreen/IndividualOffersScreen.tsx, pro/src/pages/Offers/components/IndividualOffersScreen/__specs__/IndividualOffersScreen.spec.tsx, pro/src/pages/Offers/utils/computeDeletionSuccessMessage.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32570
=> (PC-32570)[PRO] feat: Show number offers that are changing status

api/src/pcapi/sandboxes/scripts/creators/industrial/create_new_caledonia_offerers.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32707
=> (PC-32707)[API] fix: new caledonian sandbox

api/src/pcapi/core/offers/models.py, api/src/pcapi/core/providers/allocine.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32703
=> (PC-32703)[API] feat: add allocine certificate in movie extradata

api/src/pcapi/connectors/beneficiaries/ubble.py, api/src/pcapi/connectors/serialization/ubble_serializers.py, api/src/pcapi/core/fraud/models.py, api/src/pcapi/core/fraud/ubble/api.py, api/src/pcapi/core/subscription/ubble/api.py, api/src/pcapi/routes/external/users_subscription.py, api/src/pcapi/validation/routes/ubble.py, api/tests/connectors/beneficiaries/ubble_fixtures.py, api/tests/core/subscription/ubble/test_api.py, api/tests/routes/external/user_subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32147
=> (PC-32147)[API] feat: support ubble v2 workflow update

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_backend_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32978
Cette fonction est mocké en local et en test donc non testé.
=> (PC-32978)[API] fix: algolia ids that are not ids

api/src/pcapi/core/finance/utils.py, api/src/pcapi/core/geography/factories.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_new_caledonia_objects.py, api/tests/routes/public/individual_offers/v1/get_search_addresses_test.py, api/tests/routes/public/individual_offers/v1/post_address_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32086
=> Pc 32086 new caledonia sandbox

.github/workflows/dev_on_workflow_deploy.yml
Augmentation de la valeur du timeout pour le démarrage des jobs de migration
=> (BSR)[API] ci: increase migration timeout

api/src/pcapi/routes/backoffice/templates/components/collapsable_text.html, api/src/pcapi/static/backoffice/js/addons/pc-display-selector.js
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32913
=> (PC-32913)[BO] feat: create widget collapse text

api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/core/educational/models.py, api/tests/routes/adage_iframe/get_collective_offer_test.py, api/tests/routes/adage_iframe/get_collective_offers_for_my_institution_test.py, api/tests/routes/adage_iframe/get_favorites_test.py, api/tests/routes/pro/get_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32486
=> (PC-32486)[ADAGE] feat: Hide cancelled booking from adage-iframe

pro/src/ui-kit/form/QuantityInput/QuantityInput.spec.tsx, pro/src/ui-kit/form/QuantityInput/QuantityInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32999
=> (PC-32999)[PRO] fix: fully disable QuantityInput (input+checkbox) when needed

api/src/pcapi/connectors/clickhouse/queries/yearly_revenue.py
Correction d'une typo dans la requête à clickhouse, pas de test à écrire car le retour de cette query est substitué
=> (BSR)[API] fix: clickhouse queries

api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py, api/tests/core/educational/test_models.py, api/tests/core/offers/test_repository.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32739
=> (PC-32739)[API] feat: add collective offer template ended status and offers in sandbox

api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33021
=> (PC-33021)[BO] fix: Do not show links 'Offres BO' and 'Réservations BO' when user does not have the associated permission

api/documentation/package-lock.json, api/documentation/package.json
=> (BSR)[API] feat: bump docusaurus version

pro/.vscode/extensions.json, pro/.vscode/settings.json, pro/package.json, pro/yarn.lock
Enlever les dernières dépendances utilisées par cucumber.
=> (BSR)[PRO] chore: Remove remaining cucumber dependency.

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/scripts/pro/upload_reimbursement_csv_to_offerer_drive.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33096
=> (PC-33096)[API] feat: use brevo subaccount for finance templates

api/Dockerfile
=> (BSR) feat: Test download DIGI cert file

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/core/external/batch.py, api/src/pcapi/core/users/api.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32426
=> (PC-32426)[API] feat: send last_status_update_date to batch

api/src/pcapi/core/permissions/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/conftest.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33094
=> (PC-33094)[BO] feat: add new role: connect_as_pro

api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/tests/routes/pro/get_reimbursements_csv_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33049
=> (PC-33049)[API] fix: column shift in reimboursments CSV

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241115T141456_c05644202f3d_add_uuid_column_to_product_mediation.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/providers/titelive_api.py, api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33050
=> (PC-33050)[API] chore: add new uuid column to procut_mediation table

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/routes/pro/collective_bookings.py, api/tests/routes/pro/get_collective_booking_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33059
=> (PC-33059)[PRO] chore: Atomic on collective_bookings endpoints

api/src/pcapi/core/educational/api/adage.py, api/src/pcapi/core/offerers/repository.py
BSR : removing isPermanent condition which is unused
=> (BSR)[API] refactor: remove unused condition

pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/VenueEditionHeader.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32879
3 bugs en 1
- l'url de la page ne changeait pas en changeant de page patenaire
- l'image n'apparaissait pas après upload
- on restait sur une ancienne image en changeant de page partenaire
=> (PC-32879)[PRO] fix: img and url in partner page

api/src/pcapi/core/categories/subcategories_v2.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32526
=> (PC-32526)[API] feat: change streaming and films labels

api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33089
Voir discussion https://passculture.atlassian.net/browse/PC-31644?focusedCommentId=60628 pour plus de context fonctionnel.
=> (PC-33089)[PRO] fix: Handle INACTIVE filter for collective offer with new statuses

pro/src/repository/venuesService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33138
=> (PC-33138)[PRO] fix: Attempt to fix `undefined` error

api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings_for_statistics.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32270
L'ajout de ces réservations = +4 secondes sur la création de la sandbox en local
=> (PC-32270)[API] feat: Added bookings in sandbox industrial for statistics

api/src/pcapi/connectors/serialization/allocine_serializers.py, api/tests/domain/fixtures.py, api/tests/providers/allocine_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32770
=> (PC-32770)[API] feat: replace apostrophe in allocine data

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33126
=> (PC-33126)[BO] fix: crash when IntegrityError on duplicate id piece number

api/src/pcapi/alembic/versions/20241120T081129_3b79fd434823_add_backoffice_profile_ds_application_id.py
=> (BSR)[API] fix: Wrong down revision hash 

pro/eslint.config.mjs
=> (BSR)[PRO] fix: esling prettier config

api/src/pcapi/routes/backoffice/templates/components/forms/field_list_field.html, api/src/pcapi/static/backoffice/js/addons/pc-field-list.js
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33141
=> (PC-33141)[BO] fix: make the advanced search blink less obvious

pro/cypress/e2e/adage.cy.ts, pro/cypress/e2e/editDigitalIndividualOffer.cy.ts, pro/cypress/e2e/navigation.cy.ts, pro/cypress/e2e/venue.cy.ts, pro/eslint.config.mjs, pro/package.json, pro/yarn.lock
Ajoute eslint-plugin-cypress et corrige quelques trucs qui ne sont pas recommandés et donc détectés par le plugin
=> (BSR)[PRO] test: Cypress ESLint Plugin and recommended changes

api/src/pcapi/core/categories/subcategories_v2.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33156
=> (PC-33156)[API] fix: change wording for music categories

api/README.md
=> (BSR)[API] chore: make readme consistent

api/documentation/docs/tutorials/create-a-collective-offer.md, api/documentation/docs/tutorials/create-an-event-linked-to-an-external-ticketing-systems.md, api/documentation/docs/tutorials/migrate-to-the-new-api.md, api/documentation/docs/understanding-our-api/managing-bookings/connection-with-ticketing-system.md, api/documentation/docs/understanding-our-api/managing-bookings/countermarks-management.md, api/documentation/docs/understanding-our-api/resources/collective-offers.md, api/documentation/docs/understanding-our-api/resources/cursor-pagination.md, api/documentation/docs/understanding-our-api/resources/individual-offers.md, api/documentation/src/pages/change-logs.md, api/documentation/static/openapi.json, api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py, api/src/pcapi/routes/public/collective/endpoints/bookings.py, api/src/pcapi/routes/public/collective/endpoints/domains.py, api/src/pcapi/routes/public/collective/endpoints/educational_institutions.py, api/src/pcapi/routes/public/collective/endpoints/national_programs.py, api/src/pcapi/routes/public/collective/endpoints/offers.py, api/src/pcapi/routes/public/collective/endpoints/students_levels.py, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/documentation_constants/http_responses.py, api/src/pcapi/routes/public/documentation_constants/tags.py, api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/providers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32876
=> [Documentation] [API] Update EAC documentation

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241114T091053_8e2d25f7d65b_add_history_chronicle_link.py, api/src/pcapi/alembic/versions/20241114T091653_b86bf7cb97f2_validate_fkey_action_history_chronicle.py, api/src/pcapi/alembic/versions/20241114T092315_9bca134a0476_create_index_ix_action_history_chronicleId.py, api/src/pcapi/alembic/versions/20241119T140117_025aaed1c957_update_check_action_resource_constraint.py, api/src/pcapi/core/chronicles/models.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/history/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/permissions/models.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/__init__.py, api/src/pcapi/routes/backoffice/chronicles/blueprint.py, api/src/pcapi/routes/backoffice/chronicles/forms.py, api/src/pcapi/routes/backoffice/templates/chronicles/list.html, api/src/pcapi/routes/backoffice/templates/components/collapsable_text.html, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/src/pcapi/static/backoffice/scss/pc/_utilities.scss, api/tests/routes/backoffice/chronicles_test.py, api/tests/routes/backoffice/conftest.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32391
=> Pc 32391 chronicle list

api/src/pcapi/connectors/clickhouse/queries/yearly_revenue.py, pro/src/apiClient/v1/models/StatisticsModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33026
=> (PC-33026)[API] feat: Better typing for YearlyAggregatedRevenueModel

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33186
- Ajout d'un établissement aux offres
- Ajout d'un format aux offres
- Deux offres en état "annulée automatiquement" avait le champ "confirmationDate" rempli, ce qui ne doit pas être le cas
=> (PC-33186)[API] feat: add missing data in collective offers in sandbox

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241122T151319_15b6b1abc8f1_add_not_null_constraint_on_product_mediation_uuid_step_4_of_4.py, api/src/pcapi/alembic/versions/20241122T151319_30d1be7a9be4_add_not_null_constraint_on_product_mediation_uuid_step_2_of_4.py, api/src/pcapi/alembic/versions/20241122T151319_657e790a7537_add_not_null_constraint_on_product_mediation_uuid_step_3_of_4.py, api/src/pcapi/alembic/versions/20241122T151319_eea52af556f7_add_not_null_constraint_on_product_mediation_uuid_step_1_of_4.py, api/src/pcapi/alembic/versions/20241125T085807_bbe4eaf21da3_create_unique_index_product_mediation.py, api/src/pcapi/alembic/versions/20241125T085901_03fe9009ff8e_create_unique_constraint_uuid.py, api/src/pcapi/core/offers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33182
=> (PC-33182)[API] feat: add not null and unique constraint on product_mediation uuid column

api/documentation/static/openapi.json, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/stocks.py, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/post_event_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33046
=> (PC-33046)[API] feat: add constraint to enforce stocks limit per offer in public API event endpoint

pro/src/components/Address/Address.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33024
=> (PC-33024)[PRO] fix: remove not a11y placeholder

api/src/pcapi/core/offers/api.py
Le if concerné ne fonctionne pas, mais le seul effet était qu'on envoyait un log avec des données vides.
Je répare donc le if :)
=> (BSR)[API] feat: avoid log spam in tl provider

api/src/pcapi/core/offerers/api.py, api/tests/routes/pro/patch_offer_test.py, api/tests/routes/pro/patch_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33173
=> (PC-33173)[API] test: add a failing test case for edition on address

api/documentation/static/openapi.json, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/tests/routes/public/helpers.py, api/tests/routes/public/individual_offers/v1/patch_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33229
Permettre la mise à jour de l'emplacement d'un produit via l'API publique.
=> (PC-33229)[API] public api: fix: can update product location

pro/src/components/AddressManual/AddressManual.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/OfferLocation/validationSchema.ts, pro/src/pages/VenueSettings/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33107
=> (PC-33107)[PRO] fix: Adds postalCode rules and notification error message

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_api_legacy.py, api/tests/core/finance/test_commands_legacy.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33266
=> (PC-33266)[API] feat: add dehumanized bankAccountId to csv files

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_ean.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33243
=> (PC-33243)[API] feat: Add an image on product with EAN in sandbox

pro/eslint.config.mjs
=> Bsr cypress

pro/README.md, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33019
Lien pour tester l'iframe : https://pc-pro-testing--pr15241-pc-33019-fix-adage-p-sqrgid2u.web.app/adage-iframe/recherche?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaXZpbGl0ZSI6Ik0uIiwibm9tIjoiVEVTVCIsInByZW5vbSI6IkNPTVBURSIsIm1haWwiOiJjb21wdGUudGVzdEBlZHVjYXRpb24uZ291di5mciIsInVhaSI6IjA5MTA2MjBFIiwiZXhwIjoxNzMyNzQ0NjExLCJsYXQiOiI0OC42MTMwOTgiLCJsb24iOiIyLjQ1OTI3OCIsImRlZ3JlIjoyLCJtZWciOmZhbHNlfQ.q5p0oxtFclgi447iiPt21ZlKnUxWZkGtzzkPUIS9W6Pm54KL-_ebBGfbBubi_pZLF3KFTCFQXA9P2pa1bizWI5VtZk_-Zr3JWo28y0CLVDJViS1rvHAj6DvRIt5xWXH66bwjW2fPWzjP1v_B-N_B7pz3Is0ebf6sehBMzssMnHoHg3UfoQlbaqfVbx1wEqS3EvdOvqEerUi1PfH0Zcg3jJMGu_SHGme5gq7Av7f0L1cdH762LoIQ7a06qpBtnNZx3DRGWIMWUzqbsOBUGZRvNLjrqJEhEi9iTQHHUFeb4BwA2xQ70yArk …
=> (PC-33019)[ADAGE] fix adage pagination

api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_user_account_update_requests.py, api/tests/routes/backoffice/update_request_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32566
=> (PC-32566)[BO] feat: add filters to account update requests page

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33316
=> (PC-33316)[API] feat: add ff WIP_HEADLINE_OFFER

pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/components/IndividualOffer/StocksThing/__specs__/validationSchema.spec.tsx, pro/src/components/IndividualOffer/StocksThing/validationSchema.ts, pro/src/pages/VenueSettings/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.tsx, pro/src/pages/VenueSettings/VenueProvidersManager/AllocineProviderForm/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33064
=> (PC-33064)[PRO] fix: establish clear min rule for QuantityInputs

api/gunicorn.conf.py, api/src/pcapi/flask_app.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33339
=> (PC-33339)[API] feat: unshare connection pool between worker processes

api/gunicorn.conf.py
Add missing app context
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33339
=> (PC-33339)[API] fix: add app context when forking processes

api/src/pcapi/core/search/commands/indexation.py
=> (BSR)[API] chore: delete unused code

api/src/pcapi/connectors/clickhouse/queries/yearly_revenue.py, api/src/pcapi/routes/serialization/statistics_serialize.py, api/tests/routes/pro/get_statistics_test.py, pro/src/apiClient/v1/models/AggregatedRevenue.ts, pro/src/commons/utils/factories/statisticsFactories.ts, pro/src/pages/Reimbursements/Income/Income.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33258
Front :
- un commit avec un coup de prettier
- un commit avec la modif de la factory + ajout du test
=> (PC-33258)[API] feat: do not serialize previous years expected revenue

api/documentation/docs/understanding-our-api/authentication-authorization.md, api/documentation/docs/understanding-our-api/resources/individual-offers.md, api/documentation/package-lock.json, api/documentation/package.json, api/documentation/src/pages/change-logs.md, api/documentation/static/openapi.json, api/src/pcapi/routes/public/documentation_constants/tags.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32971
=> (PC-32971)[API] Ajout de la documentation sur les adresses dans docusaurus

api/src/pcapi/repository/clean_database.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33086
Ajout de remboursement sur un lieu créé pour l'occasion (sinon l'opération devient un peu plus compliquée).
Ce n'est pas idéal et certainement pas élégant mais j'ai peur qu'en l'état on soit un peu coincé.
=> (PC-33086)[API] sandbox: add function to build lots of invoices

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_ean.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ajout d'une image réelle pour une offre avec produit afin d'avoir un cas de test concret pour du front.
=> (BSR)[API] feat: Add real image to product in sandbox for specific offer

pro/cypress/e2e/editDigitalIndividualOffer.cy.ts, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33313
=> (PC-33313)[PRO] feat: remove success notification in IndividualOffer

pro/cypress/e2e/createIndividualOffer.cy.ts, pro/src/components/IndividualOffer/PriceCategoriesScreen/PriceCategoriesForm.module.scss, pro/src/components/IndividualOffer/PriceCategoriesScreen/PriceCategoriesForm.tsx, pro/src/styles/variables/_forms.scss, pro/src/ui-kit/Button/Button.module.scss, pro/src/ui-kit/Button/Button.tsx, pro/src/ui-kit/form/PriceInput/PriceInput.spec.tsx, pro/src/ui-kit/form/PriceInput/PriceInput.tsx, pro/src/ui-kit/form/TextInput/TextInput.module.scss, pro/src/ui-kit/form/TextInput/TextInput.tsx, pro/src/ui-kit/form/TextInput/__specs__/TextInput.spec.tsx, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33236
=> (PC-33236)[PRO] fix: alignement issues in indiv. offer creation price screen + improve price input a11y

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241125T153652_1e2330f8af48_add_columns_to_user_account_updatel.py, api/src/pcapi/connectors/dms/api.py, api/src/pcapi/connectors/dms/graphql/beneficiaries/get_account_update_applications.graphql, api/src/pcapi/connectors/dms/models.py, api/src/pcapi/connectors/dms/utils.py, api/src/pcapi/core/educational/api/dms.py, api/src/pcapi/core/finance/commands.py, api/src/pcapi/core/finance/ds.py, api/src/pcapi/core/users/commands.py, api/src/pcapi/core/users/ds.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/bank_accounts.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_user_account_update_requests.py, api/tests/core/finance/test_ds.py, api/tests/core/users/ds_fixtures.py, api/tests/core/users/test_commands.py, api/tests/core/users/test_ds.py, api/tests/routes/backoffice/update_request_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32575
=> (PC-32575)[API] feat: synchronize DS applications into user_account_update_request table

pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.tsx
Oubli d'un console.log dans le code et d'une constante non utilisée
=> (BSR)[PRO] refactor: Removes forgotten log + unused constant

api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/pro/stocks.py, api/src/pcapi/routes/public/books_stocks/serialization.py, api/src/pcapi/routes/serialization/stock_serialize.py, api/tests/routes/pro/post_stocks_test.py, pro/src/components/IndividualOffer/StocksEventCreation/form/onSubmit.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32967
=> (PC-32967)[PRO] feat: Improve stocks error message

pro/src/components/ArchiveConfirmationModal/ArchiveConfirmationModal.tsx, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.tsx, pro/src/components/CollectiveOffersTable/CollectiveOffersActionsBar/__specs__/CollectiveOffersActionsBar.spec.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferPreview/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferPreview/CollectiveOfferPreviewCreation/components/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33301
=> (PC-30686)[PRO] feat: EAC tacking improvement

api/pyproject.toml, api/src/pcapi/core/mails/transactional/send_transactional_email.py, api/tests/core/mails/transactional/test_send_transactional_email.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33365
=> (PC-33365)[API] feat: better tracking for invalid parameters sent to SIB transactional email API

api/src/pcapi/core/external/subcategory_suggestion_backends/subcategory_suggestion.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33004
=> (PC-33004)[API] chore: add backend logs to auth error on compliance API call

api/src/pcapi/connectors/api_allocine.py, api/tests/connectors/api_allocine_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33340
=> (PC-33340)[API] fix: handle empty node in Allocine data

pro/src/pages/Reimbursements/Income/Income.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33312
=> (PC-33312)[PRO] fix: improve Income responsiveness

pro/src/components/AddressManual/AddressManual.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33147
Corrige les erreurs côté front-end de séparation de la latitude/longitude
=> (PC-33147)[PRO] fix: Properly splits latitude and longitude

api/src/pcapi/core/users/api.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/authentication_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33395
=> (PC-33395)[API] chore: remove WIP_ENABLE_TRUSTED_DEVICE ff

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/accounts/forms.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/helpers/html_parser.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33378
=> (PC-33378)[BO] fix: timeout when searching for very short names

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241202T100520_1007ef88d004_add_booking_cancellationuserid_index.py, api/src/pcapi/core/bookings/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33368
=> (PC-33368)[API] fix: timeout when a user is deleted

api/src/pcapi/core/search/__init__.py, api/tests/core/search/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33351
=> (PC-33351)[API] feat: limit number of batches to process by indexation cron

.githooks/pre-commit
=> (BSR)[PRO] ci: Added tsc to pre-commit checks.

.github/workflows/dev_on_workflow_deploy.yml
=> Fix CI Main after values.yaml name change

api/src/pcapi/routes/serialization/base.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/pro/get_venue_test.py, pro/src/apiClient/v1/models/GetVenueResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32334
=> (PC-32334)[PRO] feat: add isOpenToPublic to getVenue

api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/tests/routes/backoffice/update_request_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32577
=> (PC-32577)[API] feat: filter update request with flags

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241202T142933_0fcad96c98ba_add_user_account_update_request_dstechnicalid.py, api/src/pcapi/connectors/dms/api.py, api/src/pcapi/connectors/dms/exceptions.py, api/src/pcapi/connectors/dms/graphql/beneficiaries/get_account_update_applications.graphql, api/src/pcapi/connectors/dms/graphql/make_on_going.graphql, api/src/pcapi/core/users/ds.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/tests/core/users/ds_fixtures.py, api/tests/core/users/test_ds.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/update_request_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-32818
=> (PC-32818)[BO] feat: instruct DS update account request

api/src/pcapi/templates/extracts/beneficiary_extract.html, api/tests/files/gdpr/rendered_beneficiary_extract.html, api/tests/files/gdpr/rendered_minimal_beneficiary_extract.html
Corrections mineures suite à la revue fonctionnelle du ticket Jira : https://passculture.atlassian.net/browse/PC-33224
=> (PC-33224)[API] fix: minor fixes in GDPR extract

api/src/pcapi/sandboxes/scripts/getters/pro.py, pro/cypress/cypress.config.ts, pro/cypress/e2e/createCollectiveOffer.cy.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33163
Créer un scénario qui vérifie : 
Parcours à couvrir en E2E :
créer une offre réservable en brouillon
quitter le brouillon
aller sur la liste des offre, filtrer sur le statut brouillon et voir l’offre apparaître
reprendre la création du brouillon jusqu'à la publication
retourner sur la liste des offres, filtrer sur le statut publié et voir l’offre apparaître
=> (PC-33163)[PRO] feat: test e2e cypress bookable offer draft

pro/src/components/Address/Address.spec.tsx
Fix un test flaky sur le composant de choix d'une adresse via l'API
=> (BSR)[PRO] test: Fix a flaky test in <AddressSelect> component

api/src/pcapi/connectors/api_adresse.py, api/tests/connectors/api_adresse/api_adresse_test.py, api/tests/connectors/api_adresse/fixtures.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33310
=> (PC-33310)[API] fix: Allow manual edition with cities names < 3 chars

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241125T153453_90128ccd108a_add_achievements_table.py, api/src/pcapi/alembic/versions/20241125T163240_53e2600b8585_add_achievements_constraints.py, api/src/pcapi/alembic/versions/20241127T164150_43fee1eab19d_validate_achievements_constraints.py, api/src/pcapi/core/achievements/factories.py, api/src/pcapi/core/achievements/models.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/users/models.py, api/src/pcapi/models/__init__.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32857
=> (PC-32857)[API] feat: add table achievement

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Mise à jour de la quantité du stock suite à l'annulation d'une réservation liée à un 
incident finance
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33338
=> (PC-33338)[API] fix: correctly update stock's quantity after booking cancellation related to finance incident

api/src/pcapi/connectors/clickhouse/queries/yearly_revenue.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33419
=> (PC-33419)[API] feat: change creation_year to year

api/src/pcapi/core/users/api.py, api/src/pcapi/models/feature.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/authentication_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33398
=> (PC-33398)[API] chore: remove WIP_ENABLE_SUSPICIOUS_EMAIL_SEND ff

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240116T115746_c95cbcd8d765_add_partial_index_for_musicsubtype_in_offer_extradata.py, api/src/pcapi/alembic/versions/20240116T120118_cb8859f6ac97_add_partial_index_for_showtype_in_offer_extradata.py, api/src/pcapi/alembic/versions/20240116T120236_fadf7f6f4c60_add_partial_index_for_showsubtype_in_offer_extradata.py, api/src/pcapi/alembic/versions/20241209T150858_ffc1d7402c8a_delete_offer_indexes.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33475
=> (PC-33475)[API] chore: delete unused search fields from BO individual offers search form

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241204T150145_bcf2693c0c2c_create_headline_offer_table.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_offers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33347
=> (PC-33347)[API] feat: add headline offer table

api/src/pcapi/routes/backoffice/chronicles/blueprint.py, api/src/pcapi/routes/backoffice/chronicles/forms.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/chronicles/details.html, api/src/pcapi/routes/backoffice/templates/chronicles/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/details.html, api/src/pcapi/routes/backoffice/templates/components/collapsable_text.html, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/src/pcapi/static/backoffice/scss/pc/_utilities.scss, api/src/pcapi/static/backoffice/scss/pc/addons/_display_switch.scss, api/tests/routes/backoffice/chronicles_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32392
=> (PC-32392)[BO] feat: create chronicle details page

pro/eslint.config.mjs, pro/src/app/App/App.tsx, pro/src/app/App/hook/useLogExtraProData.ts, pro/src/app/App/hook/usePageTitle.ts, pro/src/commons/config/swrQueryKeys.ts, pro/src/commons/hooks/useGetBitmap.ts, pro/src/commons/hooks/useIsElementVisible.ts, pro/src/commons/hooks/useNotification.ts, pro/src/commons/utils/sortCollectiveOffers.ts, pro/src/commons/utils/timezone.ts, pro/src/components/Address/Address.tsx, pro/src/components/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingsTable.tsx, pro/src/components/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine.tsx, pro/src/components/Bookings/BookingsRecapTable/BookingsTable/IndividualBookingsTable.tsx, pro/src/components/FormLayout/FormLayoutDescription.tsx, pro/src/components/IndividualOffer/DetailsSummary/DetailsSummary.tsx, pro/src/components/IndividualOffer/utils/getSuccessMessage.ts, pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/AdageOfferInfoSection.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/RequestFormDialog.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/utils/getOfferTags.ts, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/EanSearchCallout/EanSearchCallout.tsx, pro/src/pages/IndividualOffer/commons/filterCategories.ts, pro/src/pages/OffererStats/OffererStats/OffererStatsScreen.tsx, pro/src/pages/VenueCreation/SiretOrCommentFields/SiretOrCommentFields.tsx, pro/src/ui-kit/Callout/Callout.tsx, pro/src/ui-kit/Callout/types.ts, pro/src/ui-kit/Timeline/Timeline.tsx, pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.tsx
=> (BSR)[PRO] chore: fix eslint warning

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR)[API] fix: build docker image on master regardless of checksum

api/src/pcapi/routes/backoffice/offers/forms.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33497
=> (PC-33497)[BO] fix: remove forgotten element in individual offer search

api/src/pcapi/core/offerers/factories.py, api/tests/routes/pro/patch_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33492
=> (PC-33492)[API] feat: Added isOpenToPublic in VenueFactory

pro/cypress/e2e/editDigitalIndividualOffer.cy.ts, pro/src/components/OffersTable/Cells/CheckboxCell.tsx, pro/src/components/OffersTable/Cells/OfferNameCell/OfferNameCell.tsx, pro/src/components/OffersTable/Cells/OfferVenueCell.tsx, pro/src/components/OffersTable/Cells/ThumbCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.spec.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/IndividualOffersTable.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.module.scss, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.spec.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/AddressCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/DeleteDraftCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/EditOfferCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/EditStocksCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/IndividualActionsCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/OfferRemainingStockCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/OfferStatusCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferTableHead/IndividualOffersTableHead.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOffersTableBody/IndividualOffersTableBody.tsx, pro/src/styles/components/Cells.module.scss, pro/src/ui-kit/Button/Button.module.scss, pro/src/ui-kit/DropdownMenuWrapper/DropdownItem.tsx, pro/src/ui-kit/DropdownMenuWrapper/DropdownMenuWrapper.module.scss, pro/src/ui-kit/DropdownMenuWrapper/DropdownMenuWrapper.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33323
=> (PC-33323)[PRO] feat: mv indiv. offer list actions in menu

pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersSearchFilters/IndividualOffersSearchFilters.module.scss, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33445
=> (PC-33445)[PRO] feat: align status input with other filters in indiv. offer list

api/documentation/docs/understanding-our-api/authentication-authorization.md, api/documentation/src/pages/change-logs.md, api/documentation/static/openapi.json, api/src/pcapi/routes/public/documentation_constants/http_responses.py, api/src/pcapi/routes/public/individual_offers/v1/__init__.py, api/src/pcapi/routes/public/individual_offers/v1/addresses.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/venues.py, api/tests/routes/public/individual_offers/v1/get_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33490
=> (PC-33490)[API] feat: add GET venue in public API

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR)[API] fix: missing && operand on build job

api/tests/conftest.py
Backoffice's routes tests are a bit specific as
it requires a different app to be installed in
order for the routes to properly work.
This commit adds a pytest collection hook
to autodetect if tests are supposed to be run
within the backoffice application or not and
properly setup the appropriate application.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33468
=> (PC-33468)[API] test: autodetect backoffice tests

api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/admin_test.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/update_request_test.py, api/tests/routes/backoffice/venues_test.py
=> (BSR)[BO] feat: use → instead of =>

api/src/pcapi/core/bookings/repository.py
=> (BSR)[API] chore: fix _get_filtered_booking_report typing

api/src/pcapi/routes/backoffice/offers/blueprint.py
=> (BSR)[BO] chore: add missing atomic decorator

api/src/pcapi/core/offers/api.py, api/tests/routes/pro/patch_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32856
=> (PC-32856)[API] fix: Move pricing events when changing venue on collective_offer

.github/workflows/dev_on_workflow_deploy_pro_pr_version_generic.yml, pro/.firebaserc, pro/firebase.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33417
=> (PC-33417)[PRO] fix: firebase pro

api/src/pcapi/core/external/subcategory_suggestion_backends/subcategory_suggestion.py
BSR pour améliorer le log en cas d'erreur 403
=> (BSR)[API] fix: add more log for non json response

api/src/pcapi/connectors/api_adresse.py, api/src/pcapi/utils/postal_code.py, api/tests/connectors/api_adresse/api_adresse_test.py, api/tests/connectors/api_adresse/fixtures.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33537
=> (PC-33537)[API] fix: missing postcode in API Adresse response in Saint-Martin and Saint-Barthélémy

api/documentation/static/openapi.json, api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/src/pcapi/routes/public/individual_offers/v1/bookings_serialization.py, api/tests/routes/public/individual_offers/v1/get_booking_test.py, api/tests/routes/public/individual_offers/v1/get_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33170
=> (PC-33170)[API] fix: Handle new address modeling in booking validation

.github/workflows/dev_on_pull_request_closed.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33566
On PR closed : delete matching pro preview deployment
=> PC-33566 - Clean pro firebase deployments

pro/scripts/generator/_templates/component/<% name %>.module.scss.mustache, pro/scripts/generator/_templates/component/<% name %>.tsx.mustache, pro/scripts/generator/_templates/component/config.js, pro/scripts/generator/functions.js, pro/scripts/generator/index.js
Ajoute la ligne d'export pour un composant lazy-loaded pour react-router-dom (si besoin)
⏬
=> (BSR)[PRO] feat: Asks if new generated component will be lazy-loaded

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33572
=> (PC-33572) ci:Increase argocd timeout for sync

api/src/pcapi/core/mails/backends/sendinblue.py, api/tests/core/mails/mails_test.py
+ better handling of different cases of status 400 (similar to transactional email function)
Ticket Jira : https://passculture.atlassian.net/browse/PC-33543
=> (PC-33543)[API] fix: Sendinblue API Exception when updating a contact email (duplicate)

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/core/external/attributes/models.py, api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py, api/src/pcapi/models/feature.py, api/tests/core/external/external_pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33115
=> (PC-33115)[API] feat: Google image sync and has banner url based on isOpenToPublic

api/src/pcapi/connectors/clickhouse/backend.py, api/src/pcapi/connectors/clickhouse/query_mock.py, api/src/pcapi/connectors/clickhouse/testing_backend.py, api/tests/connectors/clickhouse/clickhouse_test.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py, api/tests/routes/pro/get_statistics_test.py
=> (BSR)[API] feat: Clickhouse refactor: return mocked data from clickhouse TestingBackend 

api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_complex_offers.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33477
=> (PC-33477)[BO] feat: additional information in offer details

api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/collective_offer/details.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/details.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/tests/routes/backoffice/collective_offer_templates_test.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33461
=> (PC-33461)[BO] feat: add manual review tag on details pages

api/src/pcapi/core/mails/transactional/bookings/booking_cancellation.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_beneficiary.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_to_pro.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/users/blueprint.py, api/tests/routes/backoffice/users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31790
=> (PC-31790)[BO] chore: migrate users blueprint to atomic

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_app_users.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Adaptation de la sandbox pour la nouvelle façon de gérer la DB en testing. Cette PR ne sera mergé que quand testing sera pret a migrer vers la nouvelle DB.
=> (BSR)[API] feat: adapt sandbox for new testing infra

pro/src/app/App/layout/Layout.module.scss, pro/src/components/Bookings/BookingsRecapTable/Filters/FilterByOmniSearch.module.scss, pro/src/components/Bookings/PreFilters/PreFilters.module.scss, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.module.scss, pro/src/components/Footer/Footer.module.scss, pro/src/components/Header/Header.module.scss, pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.module.scss, pro/src/components/Header/components/HeaderHelpDropdown/HeaderHelpDropdown.module.scss, pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss, pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.module.scss, pro/src/components/UserReview/UserReviewDialog/UserReviewDialog.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOffer.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferHeader/AdageOfferHeader.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/AdagePreviewLayout.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.module.scss, pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.module.scss, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.module.scss, pro/src/pages/Reimbursements/Income/Income.module.scss, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/AllocineProviderFormDialog.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/VenueProviderCard.module.scss, pro/src/styles/components/Cells.module.scss, pro/src/styles/mixins/_size.scss, pro/src/ui-kit/DialogBuilder/DialogBuilder.module.scss
À la demande du design nous modifions les breakpoints de l'application, il a été décidé de passer au mobile first : 
Nouveau breakpoints, le mobile disparaît. 
``` 
tablet >= 600
laptop >= 1024
desktop >= 1440 
```
[NOTION
](https://www.notion.so/passcultureapp/Sujet-des-breakpoints-mort-de-la-frame-3e36a954a63b47a189af821d3506b553?pvs=4)
=> (BSR)[PRO] feat: mobile first

api/src/pcapi/core/finance/repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33630
Ce matin (17/12/24) nous avons connu un downtime dû à la sur-utilisation de la route `/v2/reimbursements/csv`. Cette route exécutait une requête SQL qui prenait beaucoup de temps à s'exécuter (et qui [timeoutait](https://sentry.passculture.team/organizations/sentry/issues/1613914/?environment=production&project=5&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=21)).
Cette PR transforme légèrement la requête en faisant une sous-requête sur les données financières avant de join les données `CollectiveBooking`.
La requête initiale (environ 25s à s'exécuter sur Metabase):
```sql
SELECT 
educational_redactor."firstName" AS redactor_firstname, 
educational_redactor."lastName" AS …
```
=> (PC-33630)[API] fix: improve collective booking invoice detail query

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20241210T134713_2b4a02b0a8d5_product_mediation_url_nullable.py, api/src/pcapi/alembic/versions/20241210T135002_93656ed7ed24_product_mediation_delete_url.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/providers/titelive_api.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/routes/native/v1/offers_test.py, api/tests/routes/pro/get_offerer_stats_test.py, api/tests/routes/pro/get_product_by_ean_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33182
=> (PC-33182)[API] chore: delete unused product_mediation.url column

api/src/pcapi/core/chronicles/api.py, api/src/pcapi/core/chronicles/constants.py, api/tests/core/chronicles/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33632
=> (PC-33632)[BO] fix: chronicle import routine

api/src/pcapi/models/CONTRIBUTING.md
=> (BSR)[API] docs: update the FF removal process

api/src/pcapi/core/artist/models.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Corriger la sandbox, sans ce fix on ne réussi pas à créer des artistes sans préciser l'id
=> (BSR)[API] fix: use correct default for artist ID

api/src/pcapi/core/achievements/api.py, api/src/pcapi/core/achievements/exceptions.py, api/src/pcapi/routes/native/v1/__init__.py, api/src/pcapi/routes/native/v1/achievements.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/src/pcapi/routes/native/v1/serialization/achievements.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/achievements_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32860
=> (PC-32860)[API] feat: add route to mark achievements as seen

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_stats_test.py, pro/src/apiClient/v1/models/TopOffersResponseData.ts, pro/src/pages/Homepage/components/StatisticsDashboard/__specs__/MostViewedOffers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33387
=> (PC-33387)[API] feat: add isHeadlineOffer to get offerer stats

api/src/pcapi/connectors/dms/utils.py, api/src/pcapi/core/finance/commands.py, api/src/pcapi/repository/clean_database.py, api/src/pcapi/use_cases/save_venue_bank_informations.py, api/tests/core/finance/test_commands.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33627
=> (PC-336247)[API] feat: enable to resync DS bank accounts forgotten after DS was unavailable

api/tests/core/educational/test_integration.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33165
=> (PC-33165)[TEST] test: Integration for test collective offer

api/src/pcapi/models/feature.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/routes/native/v1/authentication_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33661
=> (PC-33661)[API] chore : delete WIP_ENABLE_GOOGLE_SSO ff and 2 unused others

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : ajout d'offres collectives dans la sandbox pour les statuts Brouillon, En instruction, Non conforme, Archivé
=> (BSR) feat: add collective offers with missing status in sandbox

.vscode/launch.json
Ajout du champ version dans le launch.json, pour éviter une erreur de certains plugins
=> (BSR) fix: add version in vscode launch.json

api/src/pcapi/core/artist/factories.py, api/src/pcapi/core/artist/models.py, api/src/pcapi/routes/native/v1/__init__.py, api/src/pcapi/routes/native/v1/artists.py, api/src/pcapi/routes/native/v1/serialization/artists.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/artists_tests.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33314
=> (PC-33314)[API] feat: add simple artist route

pro/src/pages/Onboarding/OnboardingOfferIndividual/OnboardingOfferIndividual.module.scss, pro/src/pages/Onboarding/OnboardingOffersTypeChoice/OnboardingOffersTypeChoice.module.scss, pro/src/pages/Onboarding/OnboardingOffersTypeChoice/OnboardingOffersTypeChoice.tsx, pro/src/pages/Onboarding/components/OnboardingLayout/OnboardingLayout.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33648
=> (PC-33648)[PRO] feat: Update onboarding spaces and screens positions

api/src/pcapi/models/feature.py, api/src/pcapi/sandboxes/scripts/getters/pro.py, pro/cypress/e2e/adageConfirmation.cy.ts, pro/cypress/e2e/createCollectiveOffer.cy.ts, pro/cypress/e2e/searchCollectiveOffer.cy.ts, pro/cypress/support/helpers.ts, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.tsx, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/__specs__/CollectiveOfferRow.spec.tsx, pro/src/components/CollectiveOffersTable/CollectiveOffersTableHead/CollectiveOffersTableHead.tsx, pro/src/components/OffersTable/Cells/OfferNameCell/OfferNameCell.tsx, pro/src/components/OffersTable/Cells/OfferNameCell/__specs__/OfferNameCell.spec.tsx, pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/__specs__/CollectiveOffersScreen.spec.tsx, pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffersScreen/__specs__/TemplateCollectiveOffersScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33431
Suppression du FF `ENABLE_COLLECTIVE_OFFERS_EXPIRATION`
=> (PC-33431)[PRO] refactor: delete ENABLE_COLLECTIVE_OFFERS_EXPIRATION ff

api/src/pcapi/core/chronicles/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33703
=> (PC-33703)[API] fix: add missing limit on chronicle import

api/src/pcapi/core/mails/transactional/bookings/booking_expiration_to_pro.py, api/tests/core/mails/transactional/bookings/booking_expiration_to_pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33705
=> (PC-33705)[API] fix: correct typo on OFFER_ADDRESS param

api/tests/core/mails/transactional/users/ubble_ko_reminder_test.py
=> (BSR) fix: flaky ubble reminder test

pro/src/app/AppRouter/AppRouter.tsx
=> (BSR)[PRO] feat: 404 page should be public.

api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/home.py, api/src/pcapi/routes/backoffice/templates/home/home.html, api/tests/routes/backoffice/home_test.py, api/tests/routes/backoffice/update_request_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33704
=> Pc 33704 user account update requests instructor filter

.github/workflows/dev_on_schedule_delete_pullrequest_deployments.yml
Set autodelete preview env >12h
=> Set autodelete preview env >12h

api/documentation/src/pages/change-logs.md
=> (BSR)[API] fix: Link on change logs

api/src/pcapi/routes/backoffice/dev/blueprint.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33706
=> (PC-33706)[BO] fix: TemplateNotFound exception

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33670
Ajout d'un FF qui permettra d'activer l'envoi de commentaires sur Harvestr (en utilisant leur API).
Le but de cette PR est uniquement de mettre en place le FF, l'implémentation viendra ensuite.
=> (PC-33670)[API] add WIP_API_HARVESTR FF

api/src/pcapi/models/feature.py, pro/src/app/AppRouter/routesMap.tsx, pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33594
=> (PC-33594)[PRO] chore: Rename FF.

api/src/pcapi/alembic/versions/sql/schema_init.sql
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23400
=> (PC-23400)[PRO] chore: Remove old FF from init file.

api/src/pcapi/core/geography/repository.py, api/tests/core/geography/test_repository.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33713
Je préfère proposer un correctif qui impacte uniquement l'anonymisation pour ne pas prendre de risque.
A priori on n'a pas rencontré de problème ailleurs jusqu'ici.
=> (PC-33713)[API] fix: anonymize user without address

api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/collective_offer/details.html, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/details.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/collective_offer_templates_test.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33669
=> (PC-33669)[BO] feat: add top acteur tag to offer page

api/src/pcapi/connectors/beneficiaries/ubble.py, api/src/pcapi/connectors/titelive.py, api/src/pcapi/core/logging.py, api/src/pcapi/core/subscription/dms/api.py, api/src/pcapi/routes/saml/educonnect.py
BSR : not sure what this was intended for.
=> (BSR)[API] chore: remove empty log_for_supervision function

api/src/pcapi/core/educational/api/national_program.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/external/compliance.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/adage_data.py, api/src/pcapi/routes/pro/collective_offers.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_autocomplete_educational_redactors_for_uai_test.py, api/tests/routes/pro/get_collective_offer_template_test.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/patch_collective_offers_archive_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33061
=> (PC-33061)[API] feat: add atomic in collective_offers routes

api/src/pcapi/scripts/rebuild_staging/anonymize.sql
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33715
=> (PC-33715)[API] feat: anonymize DMS data in staging

pro/src/pages/VenueCreation/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx, pro/src/pages/VenueCreation/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33443
(Également corrigé une faute d'orthographe : *réference* --> **réf<ins>é</ins>rence**)
=> (PC-33443)[PRO] fix: 'Lieu' -> 'Structure' in Collective DMS timeline

api/src/pcapi/core/bookings/repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33333
=> (PC-33333)[API] fix: Replace 'lieu' if OfferAddress is active

pro/src/app/AppRouter/routesMap.tsx, pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/components/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/components/IndividualOffer/SummaryScreen/PriceCategoriesSection/PriceCategoriesSection.tsx, pro/src/components/IndividualOffer/SummaryScreen/StockSection/StockSection.tsx, pro/src/components/OnboardingOffersChoice/OnboardingOffersChoice.tsx, pro/src/pages/OfferType/OfferType/ActionsBar/ActionsBar.tsx, pro/src/pages/Onboarding/OnboardingOfferIndividual/OnboardingOfferIndividual.tsx, pro/src/pages/Onboarding/OnboardingOfferIndividualAutomatic/OnboardingOfferIndividualAutomatic.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33619
Changement des urls du parcours d'onboarding
=> (PC-33619)[PRO] feat: Change onboarding urls.

pro/src/ui-kit/form/SelectAutoComplete/OptionsList/OptionsList.module.scss, pro/src/ui-kit/form/SelectAutoComplete/OptionsList/OptionsList.tsx, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33749
=> (PC-33749)[PRO] extend click zone on checkbox

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR)[PRO] fix: Fix issue with allure e2e

api/src/pcapi/routes/backoffice/filters.py, api/tests/core/offerers/test_api.py, api/tests/core/offerers/test_tasks.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/native/v1/bookings_test.py
Certains tests n'ont pas bien géré le passage à la nouvelle année.
=> (BSR) fix: some tests did not handle the new year well

.github/workflows/dev_on_workflow_build_docker_image.yml, api/Dockerfile
Poetry a été mis à jour en 2.0.0 hier. En attendant de régler les problèmes liés à cette version voici un petit fix pour pin la version.
=> (BSR)[API] build: pin poetry version

api/src/pcapi/alembic/versions/20241220T095131_4c3be4ff5274_add_timespan_on_headline_offer.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33423
=> (PC-33423)[API] fix: not null constraint on healine offer migration

api/src/pcapi/routes/backoffice/filters.py, api/tests/routes/backoffice/collective_offer_templates_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33760
=> (PC-33760)[BO] feat: use new offer status wording in BO

api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/collective_offer/details.html, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/details.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/collective_offer_templates_test.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
This reverts commit d03fef7d91ce662e806655a73d020f3872bb844e.
Ticket Jira (ou description si BSR) : La feature a des perfs exécrables
=> Revert "(PC-33669)[BO] feat: add top acteur tag to offers"

api/alembic_version_conflict_detection.txt, api/pyproject.toml, api/src/pcapi/alembic/versions/20241218T154642_b9b007fd9c03_.py, api/src/pcapi/connectors/big_query/queries/__init__.py, api/src/pcapi/connectors/big_query/queries/artist.py, api/src/pcapi/core/TODO.md, api/src/pcapi/core/artist/commands.py, api/src/pcapi/core/artist/models.py, api/src/pcapi/core/artist/utils.py, api/tests/core/artist/fixtures.py, api/tests/core/artist/test_commands.py, api/tests/core/artist/test_utils.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33276
=> PC-33276 add artist import

.github/workflows/dev_on_pull_request_workflow.yml
Only run Allure check on pro folder changes
=> (BSR)[API] fix: allure only run on pro folder changes

api/src/pcapi/connectors/dms/api.py, api/src/pcapi/core/users/ds.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33774
Sentry : https://sentry.passculture.team/organizations/sentry/issues/1625106/?project=5
=> (PC-33774)[API] fix: try to avoid DS timeout in daily/hourly cloud tasks

pro/src/components/ConfirmDialog/ConfirmDialog.stories.tsx, pro/src/components/RedirectDialog/RedirectDialog.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30885
=> (PC-30885)[PRO] fix: fix dialogs displaying in storybook.

api/src/pcapi/scripts/install.py
Il manque l'export de la commande pour que ça marche 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33276
=> (PC-33276)[API] feat: add command to import artists

api/src/pcapi/routes/backoffice/home.py, api/src/pcapi/routes/backoffice/templates/home/home.html, api/tests/routes/backoffice/home_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33827
=> (PC-33827)[BO] feat: Hide DS links on homepage when profile is not instructor

api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/chronicles/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/collapsable_text.html, api/tests/routes/backoffice/chronicles_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33692
=> Pc 33692 rpa cosmetic collapsable

api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary.py, api/src/pcapi/core/mails/transactional/bookings/booking_confirmation_to_beneficiary.py, api/src/pcapi/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary.py, api/src/pcapi/core/mails/transactional/bookings/booking_postponed_by_pro_to_beneficiary.py, api/tests/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary_test.py, api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py, api/tests/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary_test.py, api/tests/core/mails/transactional/bookings/booking_postponed_by_pro_to_beneficiary_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32524
=> (PC-32524)[API] feat: add booking contact to some booking emails

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesNoResult.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Résoudre le TODO dans les tests de la page de remboursement -> appel à l'api 3 fois
=> (BSR)[PRO] refactor: invoices/reimbrusement refacto

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/pro/__init__.py, api/src/pcapi/routes/pro/headline_offer.py, api/src/pcapi/routes/serialization/headline_offer_serialize.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/pro/delete_headline_offer_test.py, api/tests/routes/pro/post_headline_offer_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/HeadlineOfferCreationBodyModel.ts, pro/src/apiClient/v1/models/HeadlineOfferDeleteBodyModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33346
=> (PC-33346)[API] feat: add create and delete headline offer routes

api/src/pcapi/core/providers/api.py, api/src/pcapi/routes/pro/providers.py, api/src/pcapi/routes/pro/venue_providers.py, api/tests/routes/pro/get_providers_by_venue_test.py, api/tests/routes/pro/get_venue_providers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32888
=> (PC-32888)[API] : atomic on venue_providers 

pro/src/apiClient/helpers.ts, pro/src/commons/config/swrQueryKeys.ts, pro/src/commons/hooks/usePagination.ts, pro/src/commons/utils/config.ts, pro/src/components/ArchiveConfirmationModal/utils/canArchiveCollectiveOffer.ts, pro/src/components/Bookings/Bookings.tsx, pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx, pro/src/components/IndividualOffer/StocksSummaryScreen/StocksSummaryScreen.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/__specs__/OfferEducationalEventAddressStep.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/Homepage/Homepage.tsx, pro/src/pages/Homepage/__specs__/Homepage.spec.tsx, pro/src/pages/Homepage/components/StatisticsDashboard/components/OfferStats.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/commons/validationSchema.ts, pro/src/pages/IndividualOffer/commons/serializers.ts, pro/src/pages/Signup/SignUpValidation/SignUpValidation.tsx, pro/src/pages/Sitemap/__specs__/Sitemap.spec.tsx, pro/src/registerServiceWorker.ts
=> (BSR)[PRO] chore: resolve todos

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesNoResult.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Règler les erreurs eslint pour fix la CI
=> (BSR)[PRO] fix: quality check error

api/src/pcapi/core/mails/transactional/finance_incidents/finance_incident_notification.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33776
=> (PC-33776)[API] feat: update overpayment emails

api/src/pcapi/core/educational/api/stock.py, api/src/pcapi/routes/pro/collective_stocks.py, api/tests/routes/pro/patch_collective_stock_test.py, api/tests/routes/pro/post_collective_stock_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33077
=> (PC-33077)[PRO] chore: Atomic on collective_stock endpoints

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250108T101801_fa316a36cbcc_add_not_null_constraint_on_address_is_manual_edition_1_of_4.py, api/src/pcapi/alembic/versions/20250108T101802_02d9fd145348_add_not_null_constraint_on_address_is_manual_edition_2_of_4.py, api/src/pcapi/alembic/versions/20250108T101803_98af38b1891d_add_not_null_constraint_on_address_is_manual_edition_3_of_4.py, api/src/pcapi/alembic/versions/20250108T101804_d9b82f286880_add_not_null_constraint_on_address_is_manual_edition_4_of_4.py, api/src/pcapi/alembic/versions/20250108T103801_6c644b6bd07d_add_not_null_constraint_on_user_account_update_request_ds_technical_id_1_of_4.py, api/src/pcapi/alembic/versions/20250108T103802_378a6eed6341_add_not_null_constraint_on_user_account_update_request_ds_technical_id_2_of_4.py, api/src/pcapi/alembic/versions/20250108T103803_cc9a939003aa_add_not_null_constraint_on_user_account_update_request_ds_technical_id_3_of_4.py, api/src/pcapi/alembic/versions/20250108T103804_83e0ea9a1587_add_not_null_constraint_on_user_account_update_request_ds_technical_id_4_of_4.py, api/src/pcapi/core/geography/models.py, api/src/pcapi/core/users/models.py, api/tests/core/users/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33845
=> Pc 33845 not nullable columns

api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : Fix CI master
=> (BSR)[API] fix: fix titelive fixture test

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250107T162403_1c267d0a5fb9_drop_index_user_email_domain.py, api/src/pcapi/alembic/versions/20250107T162604_64c8345d8d49_create_index_user_email_domain_and_id.py, api/src/pcapi/core/users/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33833
=> (PC-33833)[BO] fix: timeout when filtering by email domain

pro/src/ui-kit/SelectedValuesTags/SelectedValuesTags.module.scss
Fix des fonts du nouveau selected tag
=> (BSR)[PRO] fix: selected tag fonts

api/src/pcapi/alembic/CONTRIBUTING.md
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30418
=> (PC-30418)[API] docs: write zero downtime migration recipes

api/src/pcapi/routes/pro/collective_offers.py, api/tests/routes/pro/patch_collective_offer_test.py
…
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33708
=> (PC-33708)[PRO] fix: Raise an error when trying to move the offer on an incorrect venue

api/pyproject.toml, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/templates/admin/feature_flipping.html, api/src/pcapi/routes/backoffice/templates/components/forms/checkbox_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/field_list_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/select_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/select_multiple_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/select_with_placeholder_value_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/switch_boolean_field.html, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/src/pcapi/routes/backoffice/templates/preferences/edit.html, api/src/pcapi/routes/backoffice/templates/pro/move_siret.html, api/src/pcapi/utils/image_conversion.py
3 petits commits indépendants :
- (BSR)[API] fix: mypy 1.14.1 error: Enum members must be left unannotated
- (BSR)[API] chore: remove deprecated comment about sqlalchemy version
- (BSR)[BO] chore: djlint updated end of December, 2024
=> Bsr misc backend 36

api/src/pcapi/core/mails/transactional/bookings/booking_cancellation.py, api/src/pcapi/utils/date.py, api/tests/emails/offer_cancellation_test.py, api/tests/utils/date_test.py
Ticket Jira (ou description si BSR) : c'est surtout pour supprimer une fonction qui sert peu
=> (BSR)[API] refactor: use better date in templateless mail

api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/scripts/beneficiary/import_test_users_test.py
- most of them were no longer validated
- clearer naming
- use valid addresses, including an additional second address
- enable to create collective offers
Ticket Jira : https://passculture.atlassian.net/browse/PC-33853
=> (PC-33853)[API] test: fix and improve pro staging test accounts

.github/workflows/dev_on_pull_request_workflow.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33825
Tests :
=> (PC-33825)[API] ci: deploy preview env only if api is changed

pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.spec.tsx, pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.tsx, pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageUploadBrowser/ImageUploadBrowserForm/ImageUploadBrowserForm.spec.tsx, pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageUploadBrowser/ImageUploadBrowserForm/ImageUploadBrowserForm.tsx, pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageUploadConfirm/ModalImageUploadConfirm.spec.tsx, pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageUploadConfirm/ModalImageUploadConfirm.tsx, pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPage.tsx, pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/__specs__/PartnerPage.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/ImageUploaderOffer.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/__specs__/ImageUploaderOffer.tracker.spec.tsx, pro/src/pages/VenueEdition/VenueEditionHeader.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionHeader.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33755
=> (PC-33755)[PRO] feat: track image journey

api/tests/connectors/harvestr_test.py
=> (BSR)[API] fix: fix CI by removing unexisting import

.github/workflows/dev_on_workflow_deploy_pullrequests.yml, .github/workflows/templates/pullrequest-db-init-01.yaml, .github/workflows/templates/pullrequest-db-init-02.yaml, .github/workflows/templates/pullrequest-db-init-03.yaml, .github/workflows/templates/pullrequest-db-init-05.yaml, .github/workflows/templates/pullrequest-db-init.yaml, api/src/pcapi/app.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33758
=> (PC-33758) fix pr env deployments

api/src/pcapi/scripts/pro/upload_reimbursement_csv_to_offerer_drive.py
Tentative pour fix un oomkill lorsqu'on lance cette commande. 
Ticket JIRA : https://passculture.atlassian.net/browse/PC-33864
Revue fonctionnelle OK
=> (PC-33864)[API] fix: oomkill error while writing csv

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
Fixes exception caused by PC-33086:
UniqueViolation: duplicate key value violates unique constraint "cashflow_batch_label_key" DETAIL:  Key (label)=(VIR25) already exists.
Ticket Jira : https://passculture.atlassian.net/browse/PC-33814
Sentry : https://sentry.passculture.team/organizations/sentry/issues/1625871/
=> (PC-33814)[API] test: fix cashflow batch generation when using sandbox in dev/testing

pro/src/pages/VenueEdition/VenueEdition.tsx
Correction d'une erreur de out of memory.
=> (BSR)[PRO] fix: Fix out of memory bug.

api/Dockerfile
=> (BSR)[CI] chore: Pin squawk version

pro/src/components/IndividualOffer/SummaryScreen/EventPublicationForm/EventPublicationForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33678
=> (PC-33516)[PRO] feat: add more precise options for publication hours

pro/src/app/AppRouter/findCurrentRoute.ts, pro/src/app/AppRouter/routesMap.tsx, pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33654
- Changement des titres des pages de l'onboarding
=> (PC-33654)[PRO] chore: change onboarding page titles.

.github/workflows/dev_on_workflow_deploy.yml
=> (BSR) chore: update action version for migration

api/src/pcapi/connectors/dms/api.py, api/src/pcapi/core/users/commands.py, api/src/pcapi/core/users/ds.py, api/tests/core/users/ds_fixtures.py, api/tests/core/users/test_commands.py, api/tests/core/users/test_ds.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33412
PR déploiement testing : https://github.com/pass-culture/pass-culture-deployment/pull/626
PR déploiement prod : https://github.com/pass-culture/pass-culture-deployment/pull/627
=> (PC-33412)[API] feat: delete archived/deleted user account update requests from DS

api/src/pcapi/core/bookings/repository.py, api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/tests/core/bookings/test_repository.py, api/tests/routes/backoffice/bank_account_test.py, api/tests/routes/pro/get_reimbursements_csv_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33751
=> (PC-33751)[API] fix: « Partenaire Culturel » -> « Structure » in bookings CSVs & XLS

pro/src/pages/Collaborators/Collaborators.module.scss, pro/src/pages/Collaborators/Collaborators.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferConfirmation/CollectiveOfferConfirmation/CollectiveOfferConfirmation.module.scss, pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPage.module.scss, pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPage.tsx, pro/src/pages/VenueEdition/VenueEditionHeader.module.scss, pro/src/pages/VenueEdition/VenueEditionHeader.tsx, pro/src/styles/mixins/_fonts.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33851
**Objectif**
- Corriger les espacements entre les titres/liens de l'en-tête de la page structure (venue)
- Corriger la largeur de la colonne email de la page Collaborateurs
**avant**
**après**
=> (PC-33851)[PRO] style: Adjust partner header margines & collaborators width.

api/src/pcapi/core/educational/api/dms.py, api/src/pcapi/core/educational/commands.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/get_offerer_test.py, api/tests/routes/pro/get_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33446
=> (PC-33446)[API] feat: Consider EAC DS applications for onboarded status

pro/src/pages/Onboarding/OnboardingOffersTypeChoice/OnboardingOffersTypeChoice.spec.tsx, pro/src/pages/Onboarding/OnboardingOffersTypeChoice/OnboardingOffersTypeChoice.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33923
=> (PC-33923)[PRO] feat: Remove "plus tard" button.

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33673
Suppression d'un FF plus utilisé.
=> PC 33673/rm not used anymore ff

api/src/pcapi/core/subscription/messages.py, api/src/pcapi/core/subscription/ubble/messages.py, api/tests/core/subscription/educonnect/test_api.py, api/tests/core/subscription/ubble/test_api.py, api/tests/routes/external/user_subscription_test.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33712
=> (PC-33712)[API] feat: update identity check deeplink to universal link

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/fraud/api.py, api/src/pcapi/core/fraud/common/models.py, api/src/pcapi/core/fraud/ubble/api.py, api/src/pcapi/core/subscription/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/utils.py, api/tests/core/subscription/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31022
=> (PC-31022)[API] fix: compute age using timezoned datetimes

api/src/pcapi/core/chronicles/models.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33636
=> PC-33636 add chronicles to offer route

api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/src/pcapi/routes/backoffice/templates/components/links.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-34017
=> (PC-34017)[BO] feat: Open 'Pièces jointes' tab when clicking on DS application link

pro/src/commons/core/OfferEducational/constants.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCardContent/AdageOfferListCardContent.module.scss, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/__specs__/OfferEducationalCreationOfferTypeStep.spec.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/validationSchema.ts, pro/src/pages/CollectiveOffer/CollectiveOfferStock/components/OfferEducationalStock/OfferEducationalStock.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferStock/components/OfferEducationalStock/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33821
=> (PC-33821)[PRO] feat: increase collective offer description max length

api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/repository.py, api/tests/core/offerers/test_repository.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_models.py, api/tests/core/offers/test_repository.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/pro/get_offerer_headline_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33424
=> (PC-33424)[API] feat: set headline offer to inactive when it has no image

api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/pro/headline_offer.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/pro/post_headline_offer_test.py
…tion
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33766
=> (PC-33766)[API] feat: add validation on image for headline offer creation

pro/src/pages/VenueEdition/serializers.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34022
**Objectif**
Corriger la ci après [cette PR mergée](https://github.com/pass-culture/pass-culture-main/pull/15390) qui déplace une constante qui a été utilisée ailleurs dans [un commit récent](https://github.com/pass-culture/pass-culture-main/blob/master/pro/src/pages/VenueEdition/serializers.ts).
=> (PC-34022)[PRO] fix: Fix import in serializer of venue edition.

api/src/pcapi/core/finance/utils.py, api/src/pcapi/routes/native/v1/serialization/settings.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/settings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33427
=> (PC-33427)[API] feat: add rates to settings

api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33636
Se baser sur les liens product <-> chronicle (ce qui est lié dans le BO) au lieu de offer
=> PC-33636 add chronicles to offer route using product link

api/src/pcapi/routes/backoffice/chronicles/blueprint.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_chronicles.py, api/tests/routes/backoffice/chronicles_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33813
=> Pc 33813 rpa multiple add product to chronicle

.github/workflows/dev_on_dispatch_delete_pullrequest_deployment.yaml, .github/workflows/dev_on_dispatch_deploy_ops.yml, .github/workflows/dev_on_dispatch_release_deploy.yml, .github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32932
=> (PC-32932)[API] chore: use tinyproxy instead of teleport for deployment workflows

api/.env.rebuild_staging
see https://passcultureteam.slack.com/archives/CU0SQ8Y58/p1737036220390119
=> (BSR)[API] fix: backoffice permissions rebuild_staging config

api/src/pcapi/alembic/versions/20241218T164758_2ef0dd81b7c6_validate_offer_constraint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33672
=> (PC-33672)[API] fix: skip migration that will timeout in prod

pro/src/commons/hooks/useSuggestedSubcategoriesAbTest.ts, pro/src/components/Markdown/Markdown.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx, pro/src/pages/OfferType/OfferType/OfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33860
conditionné la création d'offre par ean au fait d'avoir choisi un bien physique
=> (PC-33860)[PRO] feat: create offer by ean for record store

.github/workflows/dev_on_workflow_deploy.yml
=> (BSR)[API] ci: fix deployments that occur on non EHP environments

api/src/pcapi/connectors/beneficiaries/ubble.py, api/tests/connectors/beneficiaries/ubble_test.py
Second try.
Fixup: ed56abef98
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34037
=> (PC-34037)[API] fix: isolate the two Ubble requests sessions

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/testing.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/collective_offers.py, api/tests/routes/pro/patch_collective_offer_template_test.py, api/tests/routes/pro/patch_collective_offers_template_active_status_test.py, api/tests/routes/pro/patch_collective_offers_template_archive_test.py, api/tests/routes/pro/post_collective_offers_test.py
…creation
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33286
=> (PC-33286)[PRO] valider les modifications envoyées par le front sur l'édition/autres actions des offres vitrines

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33871
=> (PC-33871)[PRO] feat: Add a new feature flag

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250107T160202_bfd459b4a913_special_event_event_date_not_null.py, api/src/pcapi/core/operations/api.py, api/src/pcapi/core/operations/factories.py, api/src/pcapi/core/operations/models.py, api/src/pcapi/routes/backoffice/operations/blueprint.py, api/src/pcapi/routes/backoffice/operations/forms.py, api/src/pcapi/routes/backoffice/templates/components/forms/date_field.html, api/src/pcapi/routes/backoffice/templates/operations/details.html, api/src/pcapi/routes/backoffice/templates/operations/list_events.html, api/tests/core/operations/test_api.py, api/tests/routes/backoffice/operations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31825
=> Pc 31825 rpa eventdate special event

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33903
=> (PC-33903)[API] feat: set top offer to headline offer in sandbox

pro/src/pages/CollectiveOffer/CollectiveOfferStock/components/OfferEducationalStock/FormStock/FormStock.tsx, pro/src/ui-kit/form/DatePicker/DatePicker.tsx, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.module.scss, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33504
=> (PC-33504)[PRO] feat: add help tooltip on field layout

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/headline_offer.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33769
Pas de test, il s'agit uniquement de logs
=> (PC-33769)[API] feat: add log for headline offer deactivation reasons

api/tests/routes/pro/patch_collective_offer_template_test.py
Ticket Jira (ou description si BSR) : déplacement de tests dans `api/tests/routes/pro/patch_collective_offer_template_test.py` pour avoir le bon match entre les classes Returns<status_code> et les tests + update des imports
=> (BSR) test: refactor patch collective offer template test

api/src/pcapi/core/categories/subcategories_v2.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33802
=> (PC-33802)[API] feat: reorder n-1 music search

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_api_legacy.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34075
=> (PC-34075)[API] feat: readd old bank_accounts csv

api/src/pcapi/connectors/dms/exceptions.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/scripts/rebuild_staging/anonymize.sql, api/tests/connectors/dms/exceptions_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34042
=> (PC-34042)[API] fix: avoid mutation on production DS application from staging

api/src/pcapi/core/chronicles/api.py, api/src/pcapi/routes/native/v1/offers.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33895
=> PC-33895 fix chronicles route

.gitignore, api/src/pcapi/connectors/beneficiaries/ubble.py, api/src/pcapi/core/subscription/ubble/exceptions.py, api/src/pcapi/routes/native/v1/subscription.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34065
=> (PC-34065)[API] feat: handle ubble 409 error

api/src/pcapi/core/providers/titelive_api.py, api/tests/providers/titelive_search_test.py
This allows the sync to be self healing
=> (BSR)[API] feat: sync TiteLive up to yesterday by default

api/src/pcapi/core/categories/subcategories_v2.py, api/tests/routes/native/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33922
=> (PC-33922)[API] feat:change some homepage_label_name

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/serialization/offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33486
=> (PC-33486)[API] fix: Use venue.offererAddress instead of legacy fields

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33871
=> (PC-33871)[PRO] fix: Rename FF to WIP_ENABLE_OFFER_ADDRESS_COLLECTIVE

api/src/pcapi/core/offers/repository.py
=> (BSR)[API] fix: Missing loaded columns trigger n+1 query

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33938
=> (PC-33938)[BO] feat: add beginningDatetime to offer list

api/src/pcapi/routes/pro/collective_offers.py, api/tests/routes/pro/patch_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33919
Erreur sentry : https://sentry.passculture.team/organizations/sentry/issues/1626735/?project=5&referrer=jira_integration
=> (PC-33919)[PRO] fix: Handling error OfferEventInThePast

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250122T174736_5450a88dc12b_assign_manual_review_permission.py, api/src/pcapi/core/permissions/models.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/conftest.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34175
=> (PC-34175)[BO] feat: dedicated permission for manual review

api/src/pcapi/connectors/typeform.py, api/src/pcapi/core/operations/api.py, api/src/pcapi/core/operations/models.py, api/tests/core/operations/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32008
=> (PC-32008)[API] feat: link special event response to user when possible

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/RequestFormDialog.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferShareLink/OfferShareLink.tsx, pro/src/ui-kit/ListIconButton/ListIconButton.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34096
=> (PC-34096)[ADAGE] feat: add target blank to mailto links in ADAGE

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-33980
=> (PC-33980)[API] feat: use OA for acceslibre

api/src/pcapi/core/fraud/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/core/users/utils.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/tests/core/fraud/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31022
=> (PC-31022)[API] fix: compute eligibility using user timezone

pro/src/components/FormLayout/FormLayout.module.scss, pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.module.scss, pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.tsx, pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/CollectiveOffersSearchFilters/CollectiveOffersSearchFilters.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx, pro/src/ui-kit/Button/Button.module.scss, pro/src/ui-kit/form/Select/Select.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34080
=> (PC-34080)[PRO] filter design adjustement

pro/src/commons/core/FirebaseEvents/constants.ts, pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss, pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx, pro/src/components/IndividualOffer/StocksEventCreation/__specs__/RecurrenceForm.spec.tsx, pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/components/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferStock/components/OfferEducationalStock/FormStock/FormStock.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/VenueSettings/VenueProvidersManager/AllocineProviderForm/__specs__/AllocineProviderForm.spec.tsx, pro/src/ui-kit/form/DatePicker/DatePicker.tsx, pro/src/ui-kit/form/PriceInput/PriceInput.tsx, pro/src/ui-kit/form/QuantityInput/QuantityInput.tsx, pro/src/ui-kit/form/TextInput/TextInput.tsx, pro/src/ui-kit/form/TextInput/__specs__/TextInput.spec.tsx, pro/src/ui-kit/form/shared/BaseInput/BaseInput.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33971
**Objectif**
Ajouter des trackers sur les mises à jour des inputs de date limite de réservation dans les formulaires d'offre indiv.
Au passage, suppression des hack sur les interactions clavier/souris avec les input `type="number"` pour l'a11y (ne pas bloquer l'update de l'input au scroll, et ne pas empêcher la navigation dans le champ).
Bcp de changements sont juste de l'indentation
=> Pc 33971 quantity inputs

api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/pro/get_offerer_headline_offer_test.py, pro/src/apiClient/v1/models/OffererHeadLineOfferResponseModel.ts, pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.spec.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/HeadlineOffer/HeadlineOffer.module.scss, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/HeadlineOffer/HeadlineOffer.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.spec.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferCell/HeadlineOfferCell.tsx, pro/src/pages/IndividualOffers/context/IndividualOffersContext.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33325
- un commit api pour rajouter venueId à la route headline offer
- un commit front pour le block headline offer
- [ x] J'ai écrit les tests nécessaires
=>  (PC-33325)[PRO] feat: add block for headline offer in offers 

.github/workflows/dev_on_workflow_deploy.yml
=> Fix algolia job

api/src/pcapi/routes/public/collective/endpoints/offers.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34172
=> (PC-34172)[API] fix: update collective public api patch error message

api/src/pcapi/core/finance/backend/base.py, api/src/pcapi/core/finance/backend/cegid.py, api/src/pcapi/core/finance/commands.py, api/src/pcapi/core/finance/conf.py, api/src/pcapi/core/finance/exceptions.py, api/src/pcapi/core/finance/external.py, api/src/pcapi/models/feature.py, api/src/pcapi/utils/date.py, api/src/pcapi/utils/requests.py, api/tests/core/finance/test_backends.py, api/tests/core/finance/test_external.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32163
Implémentation de l'envoi des invoice vers Cegid XRP Flex
=> (PC-32163)[API] feat: add push invoice to cegid xrp flex

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_venue_offer_by_ean_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetActiveEANOfferResponseModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34174
=> (PC-34174)[API] feat: add `get_active_venue_offer_by_ean` endpoint

api/src/pcapi/scripts/rebuild_staging/anonymize.sql
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34167
=> (PC-34167)[PRO] feat: Add an anomized attribute for bookingsEmail on collective_offers

api/tests/core/achievements/test_api.py, api/tests/core/bookings/test_models.py, api/tests/core/finance/test_commands.py, api/tests/core/mails/transactional/bookings/booking_expiration_to_pro_test.py, api/tests/core/offerers/test_models.py, api/tests/core/providers/test_api.py, api/tests/core/search/test_serialize_algolia.py, api/tests/local_providers/provider_manager_test.py, api/tests/routes/backoffice/finance_test.py, api/tests/routes/backoffice/venues_test.py, api/tests/routes/external/user_subscription_test.py, api/tests/routes/native/v1/artists_tests.py, api/tests/routes/native/v1/reaction_test.py, api/tests/routes/pro/get_bank_accounts_test.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/pro/get_venue_offer_by_ean_test.py, api/tests/routes/pro/patch_offer_test.py, api/tests/routes/pro/post_venue_provider_test.py, api/tests/routes/pro/signin_test.py, api/tests/routes/pro/signup_pro_V2_test.py, api/tests/routes/pro/upsert_venue_banner_test.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py, api/tests/scripts/beneficiary/archive_dms_applications_test.py, api/tests/test_cors_config.py, api/tests/utils/date_test.py
Corriger les erreurs pylints des tests pour finalement réactiver pylint
Merger [cette PR](https://github.com/pass-culture/pass-culture-main/pull/15789) commit par commit (sinon chaque merge sur master apporte trop de conflits)
=> (BSR)[API] refactor: remove unused imports in tests

.github/workflows/dev_on_workflow_deploy.yml
Bumping timeout to 20 min due to failures @15min
=> Argocd sync timeout 20min

.github/workflows/dev_on_schedule_delete_pullrequest_deployments.yml
=> Schedule delete env preview every hour between 09:00AM 08:00PM only

pro/src/pages/Accessibility/MultiyearScheme.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34143
**Objectif**
Mettre à jour les plans d'action d'accessibilité 2024 et 2025
=> (PC-34143)[PRO] feat: Update the accessibility multiyear schema.

api/bin/generate_script_file.py
Ticket Jira (ou description si BSR) : ajout d'une commande dans bin/ pour générer dossier + fichier pour un job console
=> (BSR) feat: add a command to generate a console job script file

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_test.py, pro/src/apiClient/v1/models/GetOffererResponseModel.ts, pro/src/commons/utils/factories/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33921
=> (PC-33921)[API] feat: add hasHeadlineOffer to GET offerer/

api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/collective_bookings.html
Ticket Jira (ou description si BSR) : Des petites modifs
=> (BSR)[BO] feat: remove useless lines in incident pages in BO

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34110
=> (PC-34110)[API] feat: Add WIP_2025_SIGN_UP FF

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34223
=> (PC-34223)[BO] feat: permit to search all offers with the same product

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/api/favorites.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/mails/transactional/educational/eac_new_prebooking_to_pro.py, api/src/pcapi/core/mails/transactional/educational/eac_new_request_made_by_redactor_to_pro.py, api/src/pcapi/routes/adage_iframe/academies.py, api/src/pcapi/routes/adage_iframe/authentication.py, api/src/pcapi/routes/adage_iframe/bookings.py, api/src/pcapi/routes/adage_iframe/educational_institution.py, api/src/pcapi/routes/adage_iframe/favorites.py, api/src/pcapi/routes/adage_iframe/features.py, api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/offers.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/src/pcapi/routes/adage_iframe/redactor.py, api/src/pcapi/routes/adage_iframe/venues.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py, api/tests/routes/adage_iframe/get_collective_offers_for_my_institution_test.py, api/tests/routes/adage_iframe/playlist_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33724
=> (PC-33724)[ADAGE] feat: add atomic in adage_iframe routes

.github/workflows/dev_on_workflow_deploy_pullrequests.yml
Temporarily deactivate the backend preview environment.
=> (BSR)[API] fix: temporary deactivate preview env

api/src/pcapi/core/bookings/repository.py, api/src/pcapi/routes/pro/bookings.py, api/tests/core/bookings/test_repository.py, api/tests/routes/backoffice/individual_bookings_test.py, api/tests/routes/backoffice/offers_test.py, pro/src/components/Bookings/PreFilters/utils/downloadIndividualBookingsCSVFile.ts, pro/src/components/Bookings/PreFilters/utils/downloadIndividualBookingsXLSFile.ts, pro/src/pages/Bookings/__specs__/BookingsRecap.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33941
=> (PC-33941)[API] feat: Handle location while fetching csv bookings

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
Ticket Jira (ou description si BSR) : Ces tags sont déjà présents dans Brevo
=> (BSR)[API] chore: remove useless tags in Brevo templates

api/tests/conftest.py, api/tests/core/achievements/test_api.py, api/tests/core/bookings/test_api.py, api/tests/core/bookings/test_utils.py, api/tests/core/external/pro_user_automations_test.py, api/tests/core/external_bookings/test_decorator.py, api/tests/core/mails/transactional/bookings/booking_expiration_to_pro_test.py, api/tests/core/offerers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/native/v1/bookings_test.py, api/tests/routes/pro/get_offerer_addresses_test.py, api/tests/routes/pro/get_statistics_test.py, api/tests/routes/pro/patch_draft_offer_test.py, api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py, api/tests/routes/public/individual_offers/v1/get_search_addresses_test.py, api/tests/routes/public/individual_offers/v1/post_address_test.py
Corriger les erreurs pylints des tests pour finalement réactiver pylint
Merger https://github.com/pass-culture/pass-culture-main/pull/15789 commit par commit (sinon chaque merge sur master apporte trop de conflits)
=> BSR misc in tests

pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.module.scss, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33951
=> (PC-33951)[PRO] align and reduce padding on selection

api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/patch_venue_test.py, pro/src/apiClient/v1/models/EditVenueBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34200
=> (PC-34200)[API] feat: Enable update on venue field isOpenToPublic

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34308
=> (PC-34308)[BO] fix: avoid to use the session after a rollback

api/tests/core/achievements/test_api.py, api/tests/core/bookings/test_repository.py, api/tests/core/offers/test_api.py, api/tests/local_providers/allocine_stocks_test.py, api/tests/routes/backoffice/dev_test.py, api/tests/routes/backoffice/pro_test.py, api/tests/routes/backoffice/update_request_test.py, api/tests/routes/pro/get_reimbursements_csv_test.py
Corriger les erreurs pylints des tests pour finalement réactiver pylint
Merger https://github.com/pass-culture/pass-culture-main/pull/15789 commit par commit (sinon chaque merge sur master apporte trop de conflits)
=> (BSR)[API] refactor: rename tests with duplicated names

api/src/pcapi/routes/backoffice/accounts/forms.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/custom_reimbursement_rule/blueprint.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/forms/fields.py, api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/routes/backoffice/pivots/contexts/allocine.py, api/src/pcapi/routes/backoffice/pivots/contexts/base.py, api/src/pcapi/routes/backoffice/pro/blueprint.py, api/src/pcapi/routes/backoffice/pro/forms.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/utils/string.py, api/tests/routes/backoffice/autocomplete_test.py, api/tests/utils/string_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34277
=> (PC-34277)[BO] fix: ValueError: invalid literal for int() with base 10: '²'

pro/src/components/ImageUploader/components/ButtonImageEdit/ButtonImageEdit.module.scss, pro/src/components/ImageUploader/components/ButtonImageEdit/ButtonImageEdit.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/OfferEducationalForm.module.scss, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/__specs__/OfferEducationalCreationOfferTypeStep.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33533
Petites mises à jour design sur l'input de durée + l'upload d'image
=> (PC-33533)[PRO] feat: design updates on template creation form + image uploader

pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.module.scss, pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.spec.tsx, pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersSearchFilters/IndividualOffersSearchFilters.tsx, pro/src/ui-kit/ButtonFilter/ButtonFilter.module.scss, pro/src/ui-kit/ButtonFilter/ButtonFilter.spec.tsx, pro/src/ui-kit/ButtonFilter/ButtonFilter.stories.tsx, pro/src/ui-kit/ButtonFilter/ButtonFilter.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34216
=> (PC-34216)[PRO] fix: filter button

api/src/pcapi/routes/adage_iframe/playlists.py
=> (BSR)[ADAGE] refactor: Remove unused fonction `get_random_results`

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/display_selector.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/static/backoffice/js/addons/pc-display-selector.js
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34224
=> (PC-34224)[BO] fix: search engine to display on deep link for offer page

.cz.toml, .githooks/pre-commit, .gitignore, proxy/README.md, proxy/pyproject.toml, proxy/src/pcproxy/connectors/recommendation.py, proxy/src/pcproxy/main.py, proxy/src/pcproxy/routes/recommendation.py, proxy/src/pcproxy/serializers/error.py, proxy/src/pcproxy/serializers/recommendation.py, proxy/src/pcproxy/settings.py, proxy/src/pcproxy/utils/jwt.py, proxy/src/pcproxy/utils/routes.py, proxy/tests/routes/test_recommendation.py, proxy/tests/utils/test_jwt.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34038
=> Pc 34038 recommandation proxy

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250129T092736_7d06482102c6_special_event_status_index.py, api/src/pcapi/core/operations/api.py, api/src/pcapi/core/operations/commands.py, api/src/pcapi/core/operations/models.py, api/tests/core/operations/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34313
=> (PC-34313)[API] feat: reject old event response with status NEW

api/src/pcapi/core/offerers/api.py, api/src/pcapi/scripts/acceslibre/match_acceslibre.py, api/tests/core/offerers/test_api.py, api/tests/routes/backoffice/venues_test.py, api/tests/routes/pro/patch_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32797
=> (PC-32797)[PRO] feat: resync acceslibre when venue address change

pro/src/apiClient/v1/services/DefaultService.ts
It seems that it comes from https://github.com/pass-culture/pass-culture-main/pull/15677
=> (BSR)[API] fix: open api schema

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_api_legacy.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34342
=> (PC-34342)[API] feat: adapt finance docs to unique deposit type

api/src/pcapi/connectors/api_recaptcha.py, api/src/pcapi/routes/auth/blueprint.py, api/src/pcapi/routes/auth/discord.py, api/src/pcapi/routes/auth/forms/fields.py, api/src/pcapi/routes/auth/forms/forms.py, api/src/pcapi/routes/auth/templates/discord_signin.html, api/src/pcapi/routes/auth/templates/layouts/base.html, api/src/pcapi/routes/auth/utils.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/pro/signup.py, api/src/pcapi/routes/pro/users.py, api/src/pcapi/routes/shared/passwords.py, api/src/pcapi/settings.py, api/tests/routes/auth/discord_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33642
=> (PC-33642)[API] feat: add recaptcha validation to discord signin

pro/cypress/e2e/collaborator.cy.ts, pro/cypress/e2e/cookieBanner.cy.ts, pro/cypress/e2e/navigation.cy.ts, pro/src/components/Bookings/Bookings.tsx, pro/src/components/CollectiveBudgetInformation/CollectiveBudgetCallout.tsx, pro/src/components/CollectiveBudgetInformation/CollectiveBudgetDialog.tsx, pro/src/components/CollectiveBudgetInformation/CollectiveBudgetInformation.module.scss, pro/src/components/CollectiveBudgetInformation/constants.ts, pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.module.scss, pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.tsx, pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/CollectiveOffersScreen.tsx, pro/src/pages/Homepage/Homepage.tsx, pro/src/pages/OfferType/OfferType/OfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34356
https://www.figma.com/design/QDbFK0dMWhNyXjSrADhceQ/EAC---budget-MEN?node-id=5401-3044&t=Clf20c4E8tQjf03E-0
**EDIT MAQUETTES** : vu avec Agathe, on passe les bannières sous les titres des pages
=> (PC-34356)[PRO] feat: inform collective users about eac budget situation

.github/workflows/dev_on_workflow_deploy.yml, .github/workflows/dev_on_workflow_deploy_pullrequests.yml
Bump push-render-manifests to 2.4.4
=> (BSR) ci: Bump push-render-manifests to 2.4.4

api/src/pcapi/connectors/dms/api.py, api/src/pcapi/connectors/dms/graphql/send_user_message.graphql, api/src/pcapi/core/mails/transactional/__init__.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/core/mails/transactional/users/update_request_ask_for_correction.py, api/src/pcapi/core/users/ds.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/tests/routes/backoffice/update_request_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34222
=> (PC-34222)[API] feat: ask for update request correction

.vscode/settings.json, README.md
Ticket Jira (ou description si BSR) : update du readme pour lances les tests front avec VSCode
=> (BSR) docs: add description of VSCode vitest testing in README

api/tests/core/finance/test_api.py, api/tests/core/finance/test_api_legacy.py
Ticket Jira (ou description si BSR) : pour réparer la CI
=> (BSR)[API] fix: update broken finance tests

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/schemas.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/models/feature.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/post_draft_offer_test.py, api/tests/routes/pro/post_offer_test.py, api/tests/routes/public/individual_offers/v1/patch_product_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py, pro/src/apiClient/v1/models/PatchDraftOfferBodyModel.ts, pro/src/apiClient/v1/models/PostDraftOfferBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34361
=> (PC-34361)[API] feat: add `url` in `PostDraftOfferBodyModel` and `PatchDraftOfferBodyModel`

.github/workflows/dev_on_pull_request_workflow.yml
Comment backend deployment for preview environments
=> (BSR)[API] chore: disable pull request env for backend

pro/src/commons/config/swrQueryKeys.ts, pro/src/commons/context/IndividualOfferContext/IndividualOfferContext.tsx, pro/src/commons/context/IndividualOfferContext/__specs__/IndividualOfferContext.spec.tsx, pro/src/components/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.module.scss, pro/src/components/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx, pro/src/components/IndividualOffer/IndivualOfferLayout/__specs__/IndivualOfferLayout.spec.tsx, pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/components/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/IndividualOfferDetails.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/IndividualOfferInformations.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/OfferLocation/OfferLocation.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/UsefulInformationForm/UsefulInformationForm.tsx, pro/src/pages/IndividualOffer/components/ActionBar/ActionBar.tsx, pro/src/pages/IndividualOfferWizard/Stocks/Stocks.tsx, pro/src/pages/IndividualOfferWizard/Summary/Summary.tsx, pro/src/ui-kit/Callout/Callout.tsx, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32025
**Objectif**
Empêcher de créer une offre indiv avec un EAN qui est déjà utilisé par une autre offre publiée. En particulier, si on crée 2 offres en brouillon avec le même EAN (ce qui est possible), si on publie une de ces offres, il faut que sur celle qui reste en brouillon :
- Il y a une bannière au dessus de stepper qui indique qu'on ne peut plus la publier
- Les champs du formulaire & les boutons de submit des forms sont désactivés
- La mention "Brouillon sauvegardé" est cachée
WIP_EAN_CREATION
EAN valides en testing :
```
"8393233096608" | COMPATIBLE
"9509362020448" | COMPATIBLE
"0552212342923" | COMPATIBLE
"5461624527307" | COMPATIBLE
"2758920009976" | COMPATIBLE
"8014229282606" | …
```
=> Pc 32025 prevent creating two offerw with same ean

api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32987
=> (PC-32987)[API] feat: add headline offer info to Algolia

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34368
=> (PC-34368)[API] feat: Add venue isOpenToPublic attribut to get_offer native route

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
Regression caused by commit: 279894a0
Ticket Jira : https://passculture.atlassian.net/browse/PC-34396
=> (PC-34396)[BO] fix: timeout when listing collective offers without permission PRO_FRAUD_ACTIONS

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/staging_indexation.py, api/src/pcapi/routes/institutional/playlist.py, api/tests/core/offers/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34204
=> (PC-34204)[API] feat: update offer indexation criteria

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_test.py, pro/src/apiClient/v1/models/GetOffererResponseModel.ts, pro/src/commons/utils/factories/individualApiFactories.ts, pro/src/pages/Onboarding/OnboardingOfferIndividual/OnboardingOfferIndividual.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34394
=> (PC-34394) Suppression d'une variable inutile pour l'Onboarding Didactique

api/src/pcapi/core/artist/factories.py, api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33464
=> Pc 33464 add artists to algolia venues

api/src/pcapi/connectors/api_adresse.py, api/tests/connectors/api_adresse/api_adresse_test.py, pro/src/commons/utils/__specs__/removeQuotes.spec.ts, pro/src/commons/utils/removeQuotes.ts, pro/src/components/SignupJourneyForm/Authentication/OffererAuthentication.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.tsx, pro/src/pages/IndividualOffer/commons/serializers.ts, pro/src/pages/VenueSettings/serializers.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34085
=> (PC-34085)[PRO] feat: Removes various quotes from street & city payloads

pro/src/commons/utils/factories/adageFactories.ts, pro/src/pages/AdageIframe/app/components/DisabledPrebookCallout/DisabledPrebookCallout.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOffer.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOffer.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/AdageOfferInstitutionPanel.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/__specs__/OffersForMyInstitution.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/__spec__/PrebookingButton.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34417
=> (PC-34417)[ADAGE] feat: disable prebook adage

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34410
Je n'ai pas réussi à reproduire le bug en local, ni en test automatique. Mais j'ai pu reproduire la requête et son résultat avant/après correction dans une console Python sur staging, validant l'origine du bug et la solution.
J'ajoute cependant des années passées à la sandbox, nécessaires pour ce genre d'investigations.
=> (PC-34410)[BO] fix: wrong educational year displayed in collective offers list

pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferCell/HeadlineOfferCell.module.scss, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferCell/HeadlineOfferCell.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34099
=> (PC-34099)[PRO] fix: design on headline offer actions

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32987
=> (PC-32987)[API] feat: add headline infos to Algolia filters

api/src/pcapi/core/mails/transactional/bookings/new_booking_to_pro.py, api/src/pcapi/tasks/decorator.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34421
=> (PC-34421)[API] fix: SAWarning when sending template 21

pro/src/commons/core/FirebaseEvents/constants.ts, pro/src/components/OnboardingOffersChoice/OnboardingOffersChoice.spec.tsx, pro/src/components/OnboardingOffersChoice/OnboardingOffersChoice.tsx, pro/src/components/OnboardingOffersChoice/components/OnboardingCollectiveModal/OnboardingCollectiveModal.spec.tsx, pro/src/components/OnboardingOffersChoice/components/OnboardingCollectiveModal/OnboardingCollectiveModal.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33934
- Tracking sur l'onboarding.
=> (PC-33934)[PRO] feat: Didactic onboarding tracking events.

api/src/pcapi/core/users/ds.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34222
=> Pc 34222 adapt correction message for ds

pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.module.scss, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.tsx, pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx, pro/src/ui-kit/formV2/TextInput/TextInput.module.scss, pro/src/ui-kit/formV2/TextInput/TextInput.spec.tsx, pro/src/ui-kit/formV2/TextInput/TextInput.tsx
Migration du composant `<DetailsEanSearch />` vers react hook form
=> BSR migrate details Ean search to react hook form

pro/src/components/OnboardingOffersChoice/components/OnboardingCollectiveModal/OnboardingCollectiveModal.tsx, pro/src/ui-kit/form/SelectAutoComplete/SelectAutocomplete.tsx
Correction d'une erreur sentry où la valeur du champ de recherche pourrait être undefined.
=> (BSR)[PRO] fix: searchField value can be undefined.

pro/cypress/e2e/createCollectiveOffer.cy.ts, pro/src/components/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.tsx, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/__specs__/CollectiveOfferRow.spec.tsx, pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.tsx, pro/src/components/Header/components/HeaderHelpDropdown/HeaderHelpDropdown.tsx, pro/src/components/ImageUploader/components/ButtonAppPreview/__specs__/ButtonAppPreview.spec.tsx, pro/src/components/ImageUploader/components/ButtonImageDelete/__specs__/ButtonImageDelete.spec.tsx, pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageUploadConfirm/ModalImageUploadConfirm.tsx, pro/src/components/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/components/OffersTable/Cells/ThumbCell.tsx, pro/src/components/OnboardingOffersChoice/OnboardingOffersChoice.spec.tsx, pro/src/components/OnboardingOffersChoice/OnboardingOffersChoice.tsx, pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.tsx, pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx, pro/src/components/StocksEventList/SortArrow.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.tsx, pro/src/pages/AdageIframe/app/components/SurveySatisfaction/SurveySatisfaction.tsx, pro/src/pages/AdageIframe/app/components/SurveySatisfaction/__specs__/SurveySatisfaction.spec.tsx, pro/src/pages/Homepage/components/StatisticsDashboard/StatisticsDashboard.tsx, pro/src/pages/Homepage/components/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/OfferLocation/OfferLocation.tsx, pro/src/pages/Reimbursements/BankInformations/__specs__/BankInformations.spec.tsx, pro/src/pages/VenueSettings/VenueSettingsForm.tsx, pro/src/ui-kit/Button/Button.tsx, pro/src/ui-kit/Button/ButtonLink.tsx, pro/src/ui-kit/DialogBuilder/DialogBuilderCloseButton.tsx, pro/src/ui-kit/Thumb/Thumb.tsx, pro/src/ui-kit/form/PasswordInput/PasswordInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34294
**Objectif**
Supprimer les attributs `title` puisqu'ils portent des informations qui sont non accessibles aux interfaces touch et aux lecteurs d'écran. [Voir la doc MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns).
=> Pc 34294 delete titles

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/post_offerer_test.py, api/tests/scripts/beneficiary/import_test_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34047
=> (PC-34047)[API] feat: disable virtual venue creation at offerer creation

pro/src/components/IndividualOffer/StocksEventCreation/AddRecurrencesButton.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34459
=> (PC-34459)[PRO] fix: Do not use drawer dialog on recurrence form.

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34041
=> (PC-34041)[API] feat: Add sandbox cases for collectives offers - EAC

api/src/pcapi/core/fraud/factories.py, api/src/pcapi/core/fraud/ubble/api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/generator.py, api/src/pcapi/routes/backoffice/dev/blueprint.py, api/src/pcapi/routes/backoffice/dev/forms.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/core/fraud/dms/test_api.py, api/tests/core/subscription/test_api.py, api/tests/core/subscription/ubble/test_api.py, api/tests/core/users/test_generator.py, api/tests/routes/backoffice/accounts_test.py, api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34407
=> PC-34407 add bo features for credit

pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.tsx, pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
=> (BSR)[PRO] fix: avoid intempestive re-renders on indiv. & template offers list (+ fix test flakiness)

api/src/pcapi/connectors/api_adresse.py, api/src/pcapi/routes/public/individual_offers/v1/addresses.py, api/tests/routes/public/individual_offers/v1/post_address_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34386
=> (PC-34386)[API] feat: improve public API error message when BAN API is down

pro/src/commons/core/FirebaseEvents/constants.ts, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/HeadlineOfferBanner/HeadlineOfferBanner.spec.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/HeadlineOfferBanner/HeadlineOfferBanner.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferCell/HeadlineOfferCell.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferImageDialogs.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/IndividualActionsCells.tsx, pro/src/pages/IndividualOffers/context/IndividualOffersContext.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33321
- [] J'ai écrit les tests nécessaires
=> (PC-33321)[PRO] feat: add trackers to headline offer feature

api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/tests/routes/backoffice/multiple_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34239
=> Pc 34239 use offer ean instead of json data ean

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
=> (BSR)[PRO] fix: ci e2e

api/src/pcapi/core/banner/api.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/conf.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/subscription/api.py, api/tests/core/finance/test_api.py, api/tests/core/subscription/test_api.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/banner_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34163
=> PC-34163 add new recredit after deposit creation

.github/workflows/dev_on_pull_request_closed.yml, .github/workflows/dev_on_schedule_delete_pullrequest_deployments.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33480
Reprise de https://github.com/pass-culture/pass-culture-main/pull/15859/files mais sans les merge commit dans l'historique
=> (PC-33480)[API] ci: reenable delete PR deployment on pr closed

api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/search/__init__.py, api/src/pcapi/routes/native/v1/offerers.py, api/tests/core/educational/test_models.py, api/tests/core/offerers/test_models.py, api/tests/core/offers/test_models.py, api/tests/core/search/test_api.py, api/tests/routes/native/v1/bookings_test.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34251
=> (PC-34251)[API] Les offres de structures fermées ne doivent être ni trouvées ni réservées

api/src/pcapi/core/external/attributes/api.py, api/tests/core/external/external_pro_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34252
=> Pc 34252 closed offerer in brevo

pro/src/components/OnboardingOffersChoice/components/OnboardingCollectiveModal/OnboardingCollectiveModal.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34522
=> (PC-34522)[PRO] fix: Dispatch offerer onboarding status after file has been filed

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250207T100745_2c9f88a4345a_add_function_postal_code_to_department_code.py, api/src/pcapi/alembic/versions/20250207T102316_00722e04ea13_create_index_educational_institution_department_code.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/forms.py, api/src/pcapi/utils/postal_code.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34475
=> (PC-34475)[BO] feat: filter collective offers by institution department

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
```
if: ${{ inputs.tag }} != 'latest' is wrong
if: ${{ inputs.tag != 'latest' }} is correct
```
=> (BSR) ci: fix bad syntax for if expression

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33239
=> (PC-33239)[BO] feat: show isOpenToPublic on BO pages

pro/cypress/support/helpers.ts, pro/src/pages/Homepage/Homepage.tsx, pro/src/pages/SignIn/SignIn.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34123
**Objectif**
Modifier les titres de la page de connexion et de la page d'accueil.
=> (PC-34123)[PRO] feat: Change signin and home main heading wording.

api/src/pcapi/core/offers/api.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/post_upsert_headline_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32564
=> (PC-32564)[API] feat: reindex offers when made/removed from headline

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/core/mails/transactional/users/accepted_as_beneficiary.py, api/tests/core/mails/transactional/users/accepted_as_beneficiary_test.py, api/tests/core/subscription/test_api.py, api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34661
Note: je remplace les tests parce que les anciens tests (FF désactivé) seront obsolète
=> (PC-34661)[API] feat: use new activation email after v3 is active

api/documentation/src/pages/change-logs.md, api/documentation/static/openapi.json, api/src/pcapi/routes/public/documentation_constants/descriptions.py, api/src/pcapi/routes/public/documentation_constants/fields.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34478
=> (PC-34478)[API] feat: update `publicationDate` documentation

pro/yarn.lock
BSR update de la version de browser sync pour les tests e2e
=> (BSR)[PRO] feat: update browser sync

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34041
Intégrations des retours : voir commentaires du tickets jira
=> (PC-34041)[API] fix: Improve sandbox for OA collectives offers

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250210T093352_6d08cf9b25c2_assign_read_tech_partners_parmission.py, api/src/pcapi/core/permissions/models.py, api/src/pcapi/routes/backoffice/pivots/blueprint.py, api/src/pcapi/routes/backoffice/providers/blueprint.py, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/routes/backoffice/templates/pivots/get/allocine.html, api/src/pcapi/routes/backoffice/templates/pivots/get/boost.html, api/src/pcapi/routes/backoffice/templates/pivots/get/cgr.html, api/src/pcapi/routes/backoffice/templates/pivots/get/cineoffice.html, api/src/pcapi/routes/backoffice/templates/pivots/get/common.html, api/src/pcapi/routes/backoffice/templates/pivots/get/ems.html, api/src/pcapi/routes/backoffice/templates/providers/list.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/pivots_test.py, api/tests/routes/backoffice/providers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34362
=> (PC-34362)[BO] feat: new permission: READ_TECH_PARTNERS

pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferImageDialogs.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34519
=> (PC-34519)[PRO] fix: close image dialog for headline offer

api/src/pcapi/connectors/titelive.py, api/src/pcapi/core/providers/titelive_book_search.py, api/src/pcapi/core/providers/titelive_music_search.py, api/tests/connectors/titelive/titelive_test.py, api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34234
=> (PC-34234)[API] feat: add double writing for product.ean

api/src/pcapi/core/offers/factories.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_future_offers.py, api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_models.py, api/tests/core/offers/test_repository.py, api/tests/core/offers/test_validation.py, api/tests/core/search/test_api.py, api/tests/core/search/test_serialize_algolia.py, api/tests/routes/native/v1/offers_test.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/public/individual_offers/v1/get_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34455
=> (PC-34455)[API] feat: add future offer creation for sandbox

pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx, pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx, pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.tsx, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormDates/FormDates.tsx, pro/src/pages/Desk/Desk.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx, pro/src/pages/VenueEdition/OpeningHoursForm/HourLine.tsx, pro/src/ui-kit/MultiSelect/MultiSelect.module.scss, pro/src/ui-kit/form/DatePicker/DatePicker.tsx, pro/src/ui-kit/form/EmailSpellCheckInput/EmailSpellCheckInput.tsx, pro/src/ui-kit/form/QuantityInput/QuantityInput.tsx, pro/src/ui-kit/form/Select/Select.module.scss, pro/src/ui-kit/form/Select/Select.tsx, pro/src/ui-kit/form/Select/SelectInput.stories.tsx, pro/src/ui-kit/form/Select/SelectInput.tsx, pro/src/ui-kit/form/SelectAutoComplete/SelectAutocomplete.stories.tsx, pro/src/ui-kit/form/SelectAutoComplete/SelectAutocomplete.tsx, pro/src/ui-kit/form/TextInput/TextInput.tsx, pro/src/ui-kit/form/TimePicker/TimePicker.tsx, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33498
=> (PC-33498)[PRO] feat: update select design

pro/src/commons/core/FirebaseEvents/constants.ts, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/__specs__/FormOfferType.spec.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/OfferEducationalForm.module.scss, pro/src/ui-kit/form/TextArea/TextArea.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33740
=> (PC-33740)[PRO] feat: add description examples faq on template form

pro/src/components/ArchiveConfirmationModal/utils/canArchiveCollectiveOffer.ts, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.tsx, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.tsx, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/ThumbCell.tsx, pro/src/components/CollectiveOffersTable/CollectiveOfferRow/__specs__/CollectiveOfferRow.spec.tsx, pro/src/components/CollectiveOffersTable/CollectiveOffersActionsBar/CollectiveOffersActionsBar.tsx, pro/src/components/CollectiveOffersTable/CollectiveOffersActionsBar/__specs__/CollectiveOffersActionsBar.spec.tsx, pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferConfirmation/CollectiveOfferConfirmation.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferConfirmation/CollectiveOfferConfirmation/CollectiveOfferConfirmation.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferConfirmation/CollectiveOfferConfirmation/__specs__/CollectiveOfferConfirmation.spec.tsx, pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveEditionOfferNavigation/CollectiveEditionOfferNavigation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33641
=> (PC-33641)[PRO] fix: clean deprecated collective offer status

api/src/pcapi/core/offerers/api.py, api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/scripts/beneficiary/import_test_users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34612
=> (PC-34612)[API] fix: many staging test offerers did not have adageId and bank accounts

pro/src/components/UserPhoneForm/UserPhoneForm.tsx, pro/src/components/UserPhoneForm/__specs__/UserPhoneForm.spec.tsx, pro/src/components/UserPhoneForm/validationSchema.ts
Migrate user phone number form to react hook form
=> (BSR)[PRO] feat: migrate phone form to react-hook-form

api/tests/routes/external/sendinblue_test.py
Correction d'un test en échec s'il n'est pas lancé seul.
=> (BSR)[API] test: fix test_get_user_recommendations

pro/src/pages/User/UserProfile/UserEmail/UserEmailForm/UserEmailForm.tsx
Migration du formulaire de mise à jour de l'email du profil utilisateur vers react hook form
=> (BSR)[PRO] feat: profil email update react hook form migration

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_commercial_gestures.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_venue_provider_and_external_bookings.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_status.py
=> (BSR)[API] fix: sandbox after credit amount changes

.github/workflows/dev_on_schedule_delete_pullrequest_deployments.yml
Correction de ce genre de workflows qui ne fonctionne plus depuis quelques semaines : https://github.com/pass-culture/pass-culture-main/actions/runs/13377813315
=> (BSR)[API] ci: fix ghost workflow runs

pro/src/pages/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplication.tsx, pro/src/pages/CollectiveOfferSelectionDuplication/__specs__/CollectiveOfferSelectionDuplicationScreen.spec.tsx, pro/src/pages/IndividualOffer/IndividualOfferInformations/commons/__specs__/utils.spec.ts, pro/src/pages/IndividualOffer/IndividualOfferInformations/commons/utils.ts, pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.spec.tsx, pro/src/pages/OfferType/OfferType/OfferType.tsx, pro/src/pages/OfferType/OfferType/__specs__/OfferType.navigation.spec.tsx
Ajouter des valeurs par défaut pour les input radio qui n'ont pas de valeur par défaut
2 côté indiv : 
avant : 
après : 
avant : 
après : 
1 côté collectif : 
avant : 
après :
=> (BSR)[PRO] feat: add default value for input radio

api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/templates/layouts/base.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/static/backoffice/js/addons/pc-table-manager.js, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34406
=> (PC-34406)[BO] feat: first prototype for table personalisation in BO

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/commands.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/subscription/api.py, api/tests/core/finance/test_api.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/account_test.py, api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34164
=> PC-34164 recredit users

pro/src/commons/context/HeadlineOfferContext/HeadlineOfferContext.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34532
=> (PC-34532)[PRO] fix: avoid racing conditions on returning headline offer

pro/src/commons/hooks/useGTMHeadlineOfferAbTest.ts, pro/src/components/HeadlineOfferBanner/HeadlineOfferBanner.module.scss, pro/src/components/HeadlineOfferBanner/HeadlineOfferBanner.spec.tsx, pro/src/components/HeadlineOfferBanner/HeadlineOfferBanner.tsx, pro/src/components/HeadlineOfferBanner/components/HeadlineOfferInformationDialog.module.scss, pro/src/components/HeadlineOfferBanner/components/HeadlineOfferInformationDialog.tsx, pro/src/pages/IndividualOffers/__specs__/IndividualOffers.spec.tsx, pro/src/ui-kit/Callout/Callout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33837
=> (PC-33837)[PRO] feat: ab test headline offer banners

api/src/pcapi/routes/backoffice/static_utils.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34715
=> (PC-34715)[API] fix: add missing js import for table customization

api/tests/core/finance/test_commands_legacy.py, api/tests/core/offers/test_models.py
Correction de deux tests en échec aléatoire.
=> Fix flaky tests 2025 02 19

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/sandboxes/scripts/create_industrial_app_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34663
=> (PC-34663)[API] chore: add users for v3 to sandbox

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/exceptions.py, api/tests/core/finance/test_api.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34430
=> (PC-34430)[API] feat: recredit users only if no missing activation steps

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/sandboxes/scripts/create_industrial_app_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34663
=> (PC-34663)[API] chore: add users with cumulated credits in sandbox

api/src/pcapi/connectors/dms/api.py, api/src/pcapi/core/finance/ds.py, api/src/pcapi/core/users/ds.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/src/pcapi/scripts/subscription/dms/handle_inactive_dms_applications.py, api/tests/connectors/api_demarches_simplifiees_test.py, api/tests/core/finance/test_ds.py, api/tests/core/users/ds_fixtures.py, api/tests/core/users/test_ds.py, api/tests/core/users/test_models.py, api/tests/routes/backoffice/update_request_test.py, api/tests/scripts/beneficiary/handle_inactive_dms_applications_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34718
Les deux premiers commits font partie de https://github.com/pass-culture/pass-culture-main/pull/16403, PR depuis laquelle démarre celle-ci pour éviter les conflits. **Seuls les deux derniers commits sont donc à relire ici.** Le dernier commit est une factorisation du comportement dans le code existant.
=> (PC-34718)[BO] feat: Accept update request from DS either in draft or on-going state

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/accounts/forms.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34526
=> (PC-34526)[API] feat: adapt public account search to new deposit

api/src/pcapi/core/bookings/exceptions.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/bookings/validation.py, api/src/pcapi/routes/error_handlers/bookings_error_handlers.py, api/src/pcapi/routes/public/booking_token/v2/endpoints.py, api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_closed_offerers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/tests/routes/backoffice/individual_bookings_test.py, api/tests/routes/pro/get_all_bookings_test.py, api/tests/routes/pro/get_collective_booking_csv_test.py, api/tests/routes/pro/get_collective_booking_excel_test.py, api/tests/routes/pro/get_invoices_v2_test.py, api/tests/routes/pro/get_offerer_test.py, api/tests/routes/public/booking_token/v2/get_booking_by_token_v2_test.py, api/tests/routes/public/booking_token/v2/patch_booking_use_by_token_test.py, api/tests/routes/public/individual_offers/v1/get_booking_test.py, api/tests/routes/public/individual_offers/v1/patch_validate_booking_by_token_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-34253
=> Pc 34253 closed offerer in pc pro

api/src/pcapi/core/testing.py, api/src/pcapi/repository/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34754
=> (PC-34754)[API] fix: explore connexion corruption in BO

api/src/pcapi/sandboxes/scripts/creators/industrial/create_closed_offerers.py
=> (BSR)[API] fix: give old deposit to sandbox beneficiary

api/src/pcapi/connectors/typeform.py, api/src/pcapi/core/operations/api.py, api/src/pcapi/workers/operations_jobs.py, api/tests/core/operations/test_api.py, api/tests/routes/backoffice/operations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34558
=> Pc 34558 rpa auto import special event

pro/src/components/IndividualOffer/StocksEventCreation/AddRecurrencesButton.tsx, pro/src/components/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx, pro/src/components/IndividualOffer/StocksSummaryScreen/RecurrenceSummary.tsx, pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/components/IndividualOffer/StocksThing/submitToApi.ts, pro/src/components/IndividualOffer/StocksThing/utils/__specs__/buildInitialValues.spec.ts, pro/src/components/IndividualOffer/StocksThing/utils/buildInitialValues.ts, pro/src/components/IndividualOffer/SummaryScreen/StockSection/StockSection.tsx, pro/src/components/IndividualOffer/utils/getDepartmentCode.ts, pro/src/components/OffersTable/Cells/OfferNameCell/OfferNameCell.tsx, pro/src/components/OffersTable/Cells/OfferNameCell/__specs__/OfferNameCell.spec.tsx, pro/vite.config.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34353
=> (PC-34353)[PRO] feat: Removes WIP_USE_OFFERER_ADDRESS_AS_DATA_SOURCE feature flag

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/sandboxes/scripts/create_industrial_app_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34770
=> PC-34770 fix sandbox users

api/src/pcapi/routes/adage_iframe/favorites.py, api/tests/routes/adage_iframe/delete_favorite_template_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34594
=> Pc 34594 adapt favorites tables to sqlalchemy bump

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/fraud/common/models.py, api/src/pcapi/core/subscription/api.py, api/src/pcapi/core/users/eligibility_api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/core/finance/test_api.py, api/tests/core/subscription/test_api.py, api/tests/core/subscription/ubble/test_api.py, api/tests/core/users/test_eligibility.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34762
=> (PC-34762)[API] feat: activate pre decree deposit when eligible

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20250212T152215_9d1b6d3edf16_drop_constraint_on_beginningdatetime.py, api/src/pcapi/alembic/versions/20250212T152519_c34443975234_drop_column_beginningdatetime.py, api/src/pcapi/core/educational/adage_backends/serialize.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/api/stock.py, api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/educational/schemas.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_confirmation_by_pro.py, api/src/pcapi/routes/adage/v1/serialization/prebooking.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/tests/routes/adage/v1/conftest.py, api/tests/routes/adage/v1/get_all_bookings_per_year_test.py, api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32748
=> PC-32748  [EAC] supprimer la colonne beginningDatetime de CollectiveStock

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/external_bookings/validation.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/native/v1/bookings.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/tests/core/bookings/test_api.py, api/tests/core/external_bookings/test_api.py, pro/src/components/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
=> (BSR)[API] Refactor external booking methods - Part 1 (Ticketing systems)

api/src/pcapi/connectors/beneficiaries/ubble.py, api/src/pcapi/core/subscription/ubble/api.py, api/tests/core/subscription/ubble/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34775
=> (PC-34775)[API] feat: enable some emails to overwrite ubble response

pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.spec.tsx, pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.tsx, pro/src/components/OffersTable/OffersTableSearch/utils.ts, pro/src/pages/CollectiveOffers/CollectiveOffers.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/IndividualOffers/IndividualOffers.tsx, pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffers.tsx, pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffersQueryParams.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34014
=> (PC-34014)[PRO] fix: reset offers search (url & storage) on offerer change to avoid side effects

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/core/mails/transactional/educational/eac_booking_cancellation.py, api/src/pcapi/core/mails/transactional/educational/eac_new_booking_to_pro.py, api/src/pcapi/routes/adage/v1/educational_deposit.py, api/src/pcapi/routes/adage/v1/educational_institution.py, api/src/pcapi/routes/adage/v1/prebooking.py, api/src/pcapi/routes/adage/v1/venue.py, api/src/pcapi/routes/internal/testing.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34575
=> (PC-34575)[API] feat: add atomic on adage routes

.github/workflows/dev_on_workflow_deploy.yml
Rendre la paix de l'esprit à @mgeoffray-pass et moi quand un manifeste helm est généré
=> (BSR) ci: generate rendered manifest with app_version

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py, api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/operations/blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/src/pcapi/routes/backoffice/templates/accounts/modal/accept_update_request.html, api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html, api/src/pcapi/routes/backoffice/templates/components/search/result_card.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/operations/details.html, api/tests/routes/backoffice/filters_test.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34527
=> (PC-34527)[BO] feat: add new beneficiary rules when computing role tags

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/conf.py, api/tests/core/subscription/dms/test_api.py
Corriger un bug en prod asap
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34816
=> (PC-34816)[API] fix: avoid consequences if race conditions apply when importing ds applications

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/fraud/repository.py, api/src/pcapi/core/history/models.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/eligibility_api.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/subscription/test_api.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/banner_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34767
=> PC-34767 stepper fix

api/src/pcapi/core/banner/api.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/conf.py, api/src/pcapi/core/subscription/api.py, api/src/pcapi/core/users/eligibility_api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/generator.py, api/src/pcapi/routes/backoffice/dev/blueprint.py, api/src/pcapi/routes/backoffice/dev/forms.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/subscription/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34775
=> (PC-34811)[API] fix: credit amount to display before credit activation

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/educational/models.py, api/tests/core/educational/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34784
=> (PC-34784)[API] fix: Fixed python call in hybrid_property expressions

api/src/pcapi/core/finance/api.py, api/tests/core/subscription/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34826
=> (PC-34826)[API] feat: update recredit amount to display in 18 recredit

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/mails/transactional/users/accepted_as_beneficiary.py, api/tests/core/finance/test_api.py, api/tests/core/subscription/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34826
=> (PC-34826)[API] feat: update recredit amount to display in 18 recredit mail

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33282
=> (PC-33282)[API] feat: add artists to offer route

api/src/pcapi/connectors/beneficiaries/ubble.py, api/src/pcapi/core/fraud/api.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34383
=> (PC-34383)[BO] feat: adapt manual review to new eligibility

pro/src/pages/User/UserProfile/UserIdentity/UserIdentity.spec.tsx, pro/src/pages/User/UserProfile/UserPhone/UserPhone.spec.tsx
Fix les tests unitaires cassé sur master
=> (BSR)[PRO] fix: fix unit test ci

api/src/pcapi/core/mails/transactional/users/accepted_as_beneficiary.py, api/tests/core/mails/transactional/users/accepted_as_beneficiary_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34733
=> (PC-34733)[API] fix: send correct credited amount when activationg user

pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/CollectiveOffersScreen.tsx, pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.tsx, pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34852
=> (PC-34852)[PRO] fix: prevent filters disabled on no results / collective offers

pro/cypress/e2e/adage.cy.ts, pro/cypress/e2e/adageConfirmation.cy.ts, pro/cypress/e2e/collaborator.cy.ts, pro/cypress/e2e/collectiveBooking.cy.ts, pro/cypress/e2e/cookieBanner.cy.ts, pro/cypress/e2e/createAccount.cy.ts, pro/cypress/e2e/createCollectiveOffer.cy.ts, pro/cypress/e2e/createIndividualOffer.cy.ts, pro/cypress/e2e/desk.cy.ts, pro/cypress/e2e/navigation.cy.ts, pro/cypress/e2e/oaIndividualOffer.cy.ts, pro/cypress/e2e/searchCollectiveOffer.cy.ts, pro/cypress/e2e/searchIndividualOffer.cy.ts, pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts, pro/cypress/support/commands.ts, pro/cypress/support/index.d.ts
=> (BSR)[PRO] ci: fix E2E test timeouts.

pro/src/components/SignupJourneyForm/Validation/Validation.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormNotifications/FormNotifications.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
- Désactiver le bouton au submit de la création d'une structure
- Fixes de lint
=> Bsr loading

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/search/commands/indexation.py, api/src/pcapi/scripts/full_index_collective_offers.py, api/tests/core/educational/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34402
=> (PC-34402)[ADAGE] fix: Do not include archived collective offer on algolia

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33744
=> (PC-33744)[API] feat: update algolia config with numeric attributes for filtering

api/src/pcapi/core/fraud/api.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/accounts/forms.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34861
a pu la nouvelle éligibilité :
la revue manuelle marche :
=> (PC-34861)[BO] fix: hide new eligibility button when v3 credit ff is off

api/tests/core/search/test_api.py
Test was made flaky by unintentional removal of these lines in commit 0c57f85690
=> (BSR)[API] fix: unflake `test_index_offers_of_venues_in_queue`

pro/src/components/FormLayout/FormLayout.module.scss, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormDates/FormDates.module.scss, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormDates/FormDates.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx, pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/OfferEducationalForm.module.scss, pro/src/ui-kit/InfoBox/InfoBox.module.scss, pro/src/ui-kit/InfoBox/InfoBox.tsx, pro/src/ui-kit/MultiSelect/MultiSelect.module.scss, pro/src/ui-kit/form/Select/Select.module.scss, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33629
Utiliser le nouveau variant pour l'affichage des radio qui ont des children lorsque l'input est coché
=> (PC-33629)[PRO] feat: use new variant for radio group

api/src/pcapi/core/educational/factories.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34724
=> (PC-34724)[API] fix: use correct adageId in educational year factories
