pass-culture/pass-culture-main

api/src/pcapi/core/finance/api.py
api/src/pcapi/core/subscription/api.py
api/tests/core/subscription/dms/test_api.py
api/tests/core/subscription/test_api_race_condition.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34860

(PC-34860)[API] feat: make beneficiary activation thread-safe

---

api/src/pcapi/connectors/thumb_storage.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/providers/titelive_api.py
api/src/pcapi/local_providers/local_provider.py
api/src/pcapi/sandboxes/scripts/creators/industrial/utils.py
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
api/src/pcapi/sandboxes/scripts/utils/storage_utils.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34531

(PC-34531)[API] feat: add author artists in sandbox

---

api/src/pcapi/core/search/backends/serialization.py
api/tests/core/search/test_serialize_algolia.py

(PC-34340)[API] feat: add algolia tag for future_offer

---

api/src/pcapi/core/categories/models.py
api/src/pcapi/routes/native/v1/serialization/subcategories_v2.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34869

(PC-34869)[API] fix: reimplement categories position handling

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/offers/forms.py
api/tests/core/offers/test_models.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34046

(PC-34046)[BO] feat: add an is headline offer filter

---

api/src/pcapi/routes/backoffice/templates/components/presentation/details/tabs.html
api/src/pcapi/static/backoffice/scss/pc/_forms.scss
api/src/pcapi/static/backoffice/scss/pc/_variables.scss

- fix tab color background to white
- fix tomselect min height
- fix tomselect max height, hide label under valmues in tomselect
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34778

(PC-34778)[BO] fix: multiple css glitch in BO

---

pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
pro/src/commons/context/SignupJourneyContext/SignupJourneyContext.tsx
pro/src/components/OpenToPublicToggle/OpenToPublicToggle.module.scss
pro/src/components/OpenToPublicToggle/OpenToPublicToggle.spec.tsx
pro/src/components/OpenToPublicToggle/OpenToPublicToggle.tsx
pro/src/components/SignupJourneyForm/Authentication/OffererAuthentication.tsx
pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.tsx
pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx
pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx
pro/src/components/SignupJourneyForm/Authentication/validationSchema.tsx
pro/src/components/SignupJourneyForm/Offerer/constants.ts
pro/src/components/SignupJourneyForm/Validation/Validation.tsx
pro/src/components/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormNotifications/FormNotifications.tsx
pro/src/pages/VenueEdition/VenueEditionForm.tsx
pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx
pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.module.scss
pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33255

(PC-33255)[PRO] feat: add isOpenToPublic toggles in onboarding form when ff is enabled

---

api/src/pcapi/routes/backoffice/templates/tags/list_tags.html

(BSR)[BO] fix: missing text in button (create category)

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34932

(PC-34932)[BO] fix: correctly calculate subscription timeline when birthday and signup at age 17 post decree

---

api/src/pcapi/routes/backoffice/collective_offers/forms.py
api/src/pcapi/routes/backoffice/offers/forms.py
api/tests/routes/backoffice/collective_offers_test.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-34911

(PC-34911)[BO] fix: crash with unsupported operator in offers search

---

pro/package.json
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormAccessibility/FormAccessibility.module.scss
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormAccessibility/FormAccessibility.tsx
pro/src/ui-kit/MultiSelect/MultiSelect.module.scss
pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.module.scss
pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.tsx
pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34872

(PC-34872)[PRO] feat: update accessibility form design on collective offer creation

---

pro/package.json

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33824

(PC-33824)(PRO) feat: Adds @pass-culture organization to package.json

---

api/tests/conftest.py

Run BO and core tests in the same run.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34949

(PC-34949)[API] feat: run BO tests along with other non route tests

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/users/repository.py
api/src/pcapi/routes/backoffice/auth.py
api/src/pcapi/routes/native/v1/authentication.py
api/tests/core/offers/test_api.py

(BSR)[API] fix: some log parameters broke data imports

---

api/src/pcapi/scripts/beneficiary/import_test_users.py
api/tests/scripts/beneficiary/import_test_users_test.py

Ticket : https://passculture.atlassian.net/browse/PC-34946

(PC-34946)[API] fix: import_test_users should create deposit V3 with new amounts (staging)

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250227T164818_8868d0c16c76_add_future_offer_reminders.py
api/src/pcapi/alembic/versions/20250227T165242_b587bd63c5b6_add_future_offers_reminders_constraints.py
api/src/pcapi/alembic/versions/20250227T165606_ea04f7c88f15_validate_future_offers_reminders_constraints.py
api/src/pcapi/core/reminders/api.py
api/src/pcapi/core/reminders/factories.py
api/src/pcapi/core/reminders/models.py
api/src/pcapi/models/__init__.py
api/src/pcapi/routes/native/v1/__init__.py
api/src/pcapi/routes/native/v1/reminder.py
api/src/pcapi/routes/native/v1/serialization/reminder.py
api/tests/routes/native/openapi_test.py
api/tests/routes/native/v1/reminder_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34618

(PC-34618)[API] feat: add reminder model for futureOffer

---

api/src/pcapi/core/users/eligibility_api.py
api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/filters.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34932

(PC-34932)[BO] fix: correctly calculate subscription timeline when user have underage + pass 17 eligibility

---

api/src/pcapi/core/permissions/models.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
api/tests/routes/backoffice/conftest.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-34962

(PC-34962)[BO] feat: add new role: support_n3

---

api/src/pcapi/connectors/acceslibre.py
api/src/pcapi/settings.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34827

(PC-34827)[API] fix: add custom timeout rule to acceslibre requests

---

api/src/pcapi/connectors/dms/api.py
api/src/pcapi/routes/backoffice/bank_account/blueprint.py
api/src/pcapi/routes/backoffice/templates/bank_account/get.html
api/tests/routes/backoffice/bank_account_test.py
api/tests/routes/backoffice/update_request_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-34998

(PC-34998)[BO] fix: better handling of DS errors in bank account page

---

api/src/pcapi/core/subscription/dms/api.py
api/src/pcapi/core/users/ds.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35001

(PC-35001)[BO] fix: increase DS timeout when processing DS application

---

api/src/pcapi/core/geography/repository.py
api/tests/core/geography/test_repository.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35003

(PC-35003)[API] fix: avoid 'Could not anonymize user' when street causes an error with API Adresse

---

api/src/pcapi/core/finance/models.py
api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
api/src/pcapi/routes/backoffice/finance/forms.py
api/tests/routes/backoffice/finance_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-34088

(PC-34088)[BO] feat: add booking type filter to finance incident

---

pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34899
**Objectif**
S'assurer que les labels des inputs date de la récurrence ne passent pas à la ligne.
**Avant/après**

(PC-34899)[PRO] fix: Date input min width in recurrence form.

---

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
pro/cypress/support/commands.ts

(BSR)[PRO] ci: trying to debug E2E error messages.

---

api/src/pcapi/routes/backoffice/users/blueprint.py
api/tests/routes/backoffice/users_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35014

(PC-35014)[BO] fix: beneficiary pro account can not be reactivated with permission UNSUSPEND_USER

---

api/src/pcapi/routes/backoffice/finance/validation.py
api/tests/routes/backoffice/finance_test.py

Ticket Jira (ou description si BSR) : Spécifier un peu plus certains messages d'erreur

(BSR)[BO] feat: clearer incidents creation messages

---

pro/src/pages/Reimbursements/Income/Income.module.scss
pro/src/pages/Reimbursements/Income/Income.spec.tsx
pro/src/pages/Reimbursements/Income/Income.tsx
pro/src/pages/Reimbursements/Income/IncomeNoData/IncomeNoData.module.scss
pro/src/pages/Reimbursements/Income/IncomeResultsBox/IncomeResultsBox.tsx
pro/src/pages/Reimbursements/Income/useIncome.ts
pro/src/ui-kit/MultiSelect/MultiSelect.tsx

BSR Statistiques/chiffre d'affaire formulaire React-Hook-Form migration 
https://passculture.atlassian.net/browse/PC-34853

(BSR)[PRO] feat: migrate income form

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35030

(PC-35030)[API] fix: do not recredit when id check has failed

---

api/src/pcapi/core/bookings/factories.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/backend/base.py
api/src/pcapi/core/finance/enum.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/core/users/models.py
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
api/tests/core/bookings/test_validation.py
api/tests/core/external/external_users_test.py
api/tests/core/finance/test_backends.py
api/tests/core/finance/test_models.py
api/tests/core/subscription/test_api.py
api/tests/core/users/test_api.py
api/tests/routes/backoffice/finance_test.py
api/tests/scripts/fill_fraud_review_eligibility_type_test.py

Ticket Jira (ou description si BSR) : ça fait un fichier de moins

(BSR)[API] chore: move DepositType in models

---

pro/src/commons/core/shared/interventionOptions.ts
pro/src/commons/utils/interventionAreaMultiSelect.ts
pro/src/components/FormLayout/FormLayout.module.scss
pro/src/components/ImageUploader/ImageUploader.module.scss
pro/src/components/SignupJourneyForm/Activity/ActivityForm.module.scss
pro/src/components/SignupJourneyForm/Activity/ActivityForm.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/OfferEducationalForm.module.scss
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx
pro/src/ui-kit/MultiSelect/MultiSelect.module.scss
pro/src/ui-kit/MultiSelect/MultiSelect.tsx
pro/src/ui-kit/SelectedValuesTags/SelectedValuesTags.module.scss
pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.module.scss
pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.module.scss
pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34795

(PC-34795)[PRO] fix: fix spacing between form components

---

api/src/pcapi/routes/native/v1/serialization/offers.py
api/tests/routes/native/openapi_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35070

(PC-35070)[API] fix: make artist image nullable in offer route

---

api/src/pcapi/connectors/typeform.py
api/src/pcapi/core/operations/api.py
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/tests/connectors/typeform/fixtures.py
api/tests/connectors/typeform/typeform_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35057

(PC-35057)[API] fix: add support for multiple choices typeform questions

---

pro/cypress/e2e/adageConfirmation.cy.ts
pro/cypress/e2e/collaborator.cy.ts
pro/cypress/e2e/createAccount.cy.ts
pro/cypress/e2e/didacticOnboarding.cy.ts
pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
pro/cypress/e2e/financialManagement.cy.ts
pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts

(BSR)[PRO] ci: more sandboxes timeouts.

---

api/src/pcapi/algolia_settings_offers.json

Mettre à jour la config algolia en prenant bien en compte tous les champs numériques filtrables.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35069

(PC-35069)[API] feat: update algolia config with numeric filters

---

pro/src/components/IndividualOffer/DetailsSummary/DetailsSummary.tsx
pro/src/components/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
pro/src/components/MarkdownInfoBox/MarkdownInfoBox.tsx
pro/src/components/OfferAppPreview/OfferAppPreview.module.scss
pro/src/components/OfferAppPreview/OfferAppPreview.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33653

(PC-33653)[PRO] feat: add markdown support on indiv offer creation for descriptions

---

api/src/pcapi/core/finance/api.py
api/tests/core/subscription/test_api_race_condition.py
api/tests/routes/native/v1/account_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35076

(PC-35076)[API] fix: make recredit function thread-safe

---

api/tests/core/bookings/test_repository.py
api/tests/core/bookings/test_utils.py
api/tests/core/bookings/test_validation.py
api/tests/core/chronicles/test_api.py
api/tests/core/external_bookings/test_api.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_backends.py
api/tests/core/offerers/test_api.py
api/tests/core/offerers/test_models.py
api/tests/core/offerers/test_synchronize_venues_banners_with_google_places.py
api/tests/core/offerers/test_update_offerer_stats.py
api/tests/core/offers/test_api.py
api/tests/core/search/test_api.py
api/tests/core/subscription/test_api_race_condition.py
api/tests/core/users/test_eligibility.py
api/tests/core/users/test_models.py
api/tests/routes/backoffice/filters_test.py
api/tests/routes/backoffice/operations_test.py
api/tests/routes/backoffice/venues_test.py
api/tests/routes/native/v1/authentication_test.py
api/tests/routes/pro/patch_draft_offer_test.py
api/tests/scripts/beneficiary/import_test_users_test.py
api/tests/validation/routes/users_authentifications_test.py

Ticket Jira (ou description si BSR) : Des petits warnings de pylint dans tests

(BSR)[API] chore: fix some minor pylint errors

---

api/src/pcapi/core/finance/utils.py
api/src/pcapi/core/users/factories.py
api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/accounts/serialization.py
api/src/pcapi/routes/backoffice/filters.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34918

(PC-34918)[BO] feat: add deposit history to account page

---

api/src/pcapi/routes/pro/users.py
api/src/pcapi/settings.py
api/tests/routes/pro/signin_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26462

(PC-26462)[API] chore: remove unused RECAPTCHA WHITELIST

---

api/src/pcapi/routes/backoffice/venues/blueprint.py
api/tests/routes/backoffice/venues_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35101

(PC-35101)[BO] chore: show IntegrityError in an alert instead of crashing when updating venue

---

api/src/pcapi/connectors/dms/api.py
api/src/pcapi/core/users/ds.py
api/tests/connectors/api_demarches_simplifiees_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35103

(PC-35103)[API] fix: handle DS response already refused or ongoing

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250311T163538_69add328b9fa_assign_read_special_events_permission.py
api/src/pcapi/core/permissions/models.py
api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/templates/components/menu/menu.html
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/src/pcapi/routes/backoffice/templates/operations/list_events.html
api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
api/tests/routes/backoffice/conftest.py
api/tests/routes/backoffice/operations_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35102

(PC-35102)[BO] feat: read-only view for special events

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35095
fix: https://sentry.passculture.team/organizations/sentry/issues/1628644/?project=5

(PC-35095)[BO] fix: correctly calculate subscription timeline when user is under 17 post-decree

---

api/src/pcapi/core/reminders/api.py
api/src/pcapi/routes/native/v1/reminder.py
api/src/pcapi/routes/native/v1/serialization/reminder.py
api/tests/routes/native/openapi_test.py
api/tests/routes/native/v1/reminder_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35072

(PC-35072)[API] feat: add reminder infos in POST response

---

api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
api/src/pcapi/routes/backoffice/finance/forms.py
api/tests/routes/backoffice/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34089

(PC-34089)[BO] feat: add origin filter on finance incident page

---

pro/src/commons/hooks/useGTMHeadlineOfferAbTest.ts
pro/src/components/HeadlineOfferBanner/HeadlineOfferBanner.spec.tsx
pro/src/pages/IndividualOffers/__specs__/IndividualOffers.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34991

(PC-34991)[PRO] feat: initiate manual AB test

---

pro/src/styles/variables/_forms.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33604

(PC-33604)[PRO] feat: update input border radius

---

api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py
api/tests/routes/adage/v1/confirm_prebooking_test.py
api/tests/routes/adage/v1/refuse_prebookings_test.py
api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py
api/tests/routes/public/helpers.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35106

(PC-35106)[API] feat: add atomic in adage_mock routes

---

api/src/pcapi/connectors/typeform.py
api/tests/connectors/typeform/fixtures.py
api/tests/connectors/typeform/typeform_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35127

Pc 35127 rpa fix typeform again

---

api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/static/backoffice/js/addons/pc-table-manager.js
api/src/pcapi/static/backoffice/scss/pc/_variables.scss
api/src/pcapi/static/backoffice/scss/pc/addons/_table_manager.scss
api/src/pcapi/static/backoffice/scss/pc/pc.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34832
- les border radius seront fait en global au niveau du BO plus tard (quand on fera les pages)
- idem pour les couleurs
demandé:
fait:

(PC-34832)[BO] feat: implement most of the UI features for table manager

---

api/src/pcapi/celery_tasks/sendinblue.py
api/src/pcapi/flask_app.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35007
Petit renommage des tasks et queue celery actuelles sur les mails pour deux raisons : 
* Faciliter leur monitoring via le redis exporter
* Mettre en place l'architecture de queue decidée en journée backend
⚠️ Ne pas merger avant d'avoir adpaté la config du déploiement car les workers doivent écouter sur différentes queue une fois cette PR mergée

(PC-35007)[API] chore: define external_calls low and high priority queues

---

pro/src/pages/LostPassword/LostPassword.module.scss
pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.module.scss
pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.tsx
pro/src/pages/Signup/SignupContainer/SignupContainer.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34104

(PC-34104)[PRO] feat: subscription confirmation redesign.

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/workers/update_all_offers_active_status_job.py
api/src/pcapi/workers/update_all_venue_offers_accessibility_job.py

Déplacer des fonctions de offers.api qui concernent des offres collectives dans le bon module (educational.api.offer).

(BSR)[API] feat: move coll. functions from offers.api

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/commands.py
api/tests/core/offerers/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34831

(PC-34831)[API] feat: Clean unecessary accesibility provider for venues close to public

---

api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35148

(PC-35148)[API] fix: do not use timezone in adage_mock routes

---

api/src/pcapi/core/subscription/dms/api.py
api/src/pcapi/scripts/subscription/dms/handle_inactive_dms_applications.py
api/tests/core/subscription/dms/test_api.py
api/tests/scripts/beneficiary/handle_inactive_dms_applications_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35143

(PC-35143)[API] fix: DS application may be refused without existing user account

---

api/src/pcapi/static/backoffice/js/addons/pc-postal-address-autocomplete.js

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35150

(PC-35150)[BO] fix: address autocomplete in BO

---

pro/src/components/SignupJourneyForm/Validation/Validation.tsx
pro/src/pages/Signup/SignupContainer/validationSchema.ts

(BSR)[PRO] fix: wrong import order

---

api/src/pcapi/core/reminders/api.py
api/src/pcapi/routes/native/v1/reminder.py
api/tests/routes/native/openapi_test.py
api/tests/routes/native/v1/reminder_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34794

(PC-34974)[API] feat: add reminder DELETE route

---

pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferCreation/__specs__/CollectiveOfferCreation.spec.tsx

(BSR)[PRO] fix: flaky test fix.

---

api/src/pcapi/core/external/attributes/api.py
api/src/pcapi/core/external/commands/update_brevo_batch_attributes.py
api/src/pcapi/core/external/sendinblue.py
api/tests/core/external/test_commands.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35159
Sentry : https://pass-culture.sentry.io/issues/33373661/
Problème observé en validant un ticket précédent sur staging.
Correction vérifiée dans la console python sur staging.

(PC-35159)[API] fix: error when refreshing Brevo user attributes (not pro)

---

api/documentation/docs/understanding-our-api/resources/collective-offers.md

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34379
Actions / status :
Tableau :

(PC-34379)[API] docs: update public api Collective offers page

---

api/src/pcapi/flask_app.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35170

(PC-35170)[API] fix: fix teardown order for atomic

---

api/src/pcapi/core/bookings/commands.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35181

(PC-35181)[API] feat: add recompute dnBookedQuantity command

---

api/documentation/package-lock.json
api/documentation/package.json

(BSR)[API] bump: Upgrade docusaurus core & babel deps.

---

api/src/pcapi/core/search/commands/indexation.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35006

(PC-35006)[API] refactor: reindex staging offers in batch

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
api/tests/routes/pro/get_collective_offer_template_test.py
api/tests/routes/pro/get_collective_offer_test.py
api/tests/routes/pro/patch_collective_offer_template_test.py
api/tests/routes/pro/patch_collective_offer_test.py
api/tests/routes/pro/post_collective_offers_template_test.py
api/tests/routes/pro/post_collective_offers_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
pro/src/apiClient/v1/models/CollectiveLocationType.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35128

(PC-35128)[API] feat: remove VENUE option in CollectiveLocationType

---

.github/workflows/dev_on_dispatch_release_deploy.yml
.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/dev_on_workflow_deploy.yml
api/src/pcapi/core/search/commands/settings.py
api/tests/core/search/test_commands_settings.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35105

(PC-35105)[API] feat: apply Algolia config for testing only if files changed

---

pro/src/components/SignupJourneyForm/Activity/ActivityForm.tsx
pro/src/components/UserPasswordForm/UserPasswordForm.tsx
pro/src/components/UserPasswordForm/validationSchema.ts
pro/src/components/UserPhoneForm/UserForm.module.scss
pro/src/pages/SignIn/SigninForm.tsx
pro/src/pages/Signup/SignupContainer/SignupContainer.module.scss
pro/src/pages/Signup/SignupContainer/SignupForm.tsx
pro/src/pages/Signup/SignupContainer/__specs__/validationSchema.spec.ts
pro/src/pages/Signup/SignupContainer/validationSchema.ts
pro/src/ui-kit/formV2/PasswordInput/validation.ts
pro/src/ui-kit/formV2/ValidationMessageList/ValidationMessageList.module.scss
pro/src/ui-kit/formV2/ValidationMessageList/ValidationMessageList.spec.tsx
pro/src/ui-kit/formV2/ValidationMessageList/ValidationMessageList.stories.tsx
pro/src/ui-kit/formV2/ValidationMessageList/ValidationMessageList.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35188
(sur le parcours d'inscription et pour la modification de mot de passe dans le profile)

(PC-35188)[PRO] feat: ameliorations ux sur champ mdp et label numero de telephone

---

pro/src/ui-kit/form/DatePicker/BaseDatePicker.tsx
pro/src/ui-kit/form/Select/SelectInput.tsx
pro/src/ui-kit/form/TimePicker/BaseTimePicker.tsx
pro/src/ui-kit/formV2/DatePicker/DatePicker.module.scss
pro/src/ui-kit/formV2/DatePicker/DatePicker.spec.tsx
pro/src/ui-kit/formV2/DatePicker/DatePicker.stories.tsx
pro/src/ui-kit/formV2/DatePicker/DatePicker.tsx
pro/src/ui-kit/formV2/Select/Select.module.scss
pro/src/ui-kit/formV2/Select/Select.spec.tsx
pro/src/ui-kit/formV2/Select/Select.stories.tsx
pro/src/ui-kit/formV2/Select/Select.tsx
pro/src/ui-kit/formV2/TimePicker/TimePicker.module.scss
pro/src/ui-kit/formV2/TimePicker/TimePicker.spec.tsx
pro/src/ui-kit/formV2/TimePicker/TimePicker.stories.tsx
pro/src/ui-kit/formV2/TimePicker/TimePicker.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35211
**Objectif**
Créer les composants formV2 suivants : 
- TimePicker
- DatePicker
- Select

(PC-35211)[PRO] feat: Add form v2 components.

---

pro/src/pages/OfferType/OfferType/CollectiveOfferType/CollectiveOfferType.tsx
pro/src/pages/OfferType/OfferType/IndividualOfferType/IndividualOfferType.tsx
pro/src/pages/OfferType/OfferType/IndividualOfferType/__specs__/IndividualOfferType.spec.tsx
pro/src/pages/OfferType/OfferType/OfferType.tsx
pro/src/pages/OfferType/OfferType/types.ts

BSR migration vers react-hook-form de la première étape de création d'offre

Bsr pro create offer migration

---

pro/src/pages/Signup/SignupContainer/SignupForm.tsx
pro/src/ui-kit/formV2/Checkbox/Checkbox.module.scss
pro/src/ui-kit/formV2/Checkbox/Checkbox.spec.tsx
pro/src/ui-kit/formV2/Checkbox/Checkbox.stories.tsx
pro/src/ui-kit/formV2/Checkbox/Checkbox.tsx
pro/src/ui-kit/formV2/CheckboxGroup/CheckboxGroup.module.scss
pro/src/ui-kit/formV2/CheckboxGroup/CheckboxGroup.spec.tsx
pro/src/ui-kit/formV2/CheckboxGroup/CheckboxGroup.stories.tsx
pro/src/ui-kit/formV2/CheckboxGroup/CheckboxGroup.tsx
pro/src/ui-kit/formV2/IconRadio/IconRadio.module.scss
pro/src/ui-kit/formV2/IconRadio/IconRadio.spec.tsx
pro/src/ui-kit/formV2/IconRadio/IconRadio.stories.tsx
pro/src/ui-kit/formV2/IconRadio/IconRadio.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35229
**Objectif**
Créer les composants suivants dans la V2 :
- CheckboxGroup
- IconRadio

Pc 35229 add components v2

---

api/src/pcapi/core/search/backends/serialization.py
api/tests/core/search/test_serialize_algolia.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34828

(PC-34828)[API] feat: filter valid extra data artists in Algolia

---

pro/src/components/SignupJourneyForm/Authentication/validationSchema.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35168

(PC-35168)[PRO] fix: restore isOpenToPublicToggle error message in onboarding

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250314T143929_91ce430722b1_add_lat_long_to_eduational_institution.py
api/src/pcapi/core/educational/adage_backends/logger.py
api/src/pcapi/core/educational/adage_backends/serialize.py
api/src/pcapi/core/educational/adage_backends/testing.py
api/src/pcapi/core/educational/api/institution.py
api/src/pcapi/core/educational/commands.py
api/src/pcapi/core/educational/factories.py
api/src/pcapi/core/educational/models.py
api/tests/core/educational/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34377

(PC-34377)[ADAGE] feat: Add latitude/longitude to adage_institutions

---

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/components/revenue_details.html
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35208

(PC-35208)[BO] fix: exception when getting statistics for an offerer with no venue

---

api/src/pcapi/models/feature.py
api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/accounts/forms.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_api_legacy.py
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/finance_test.py
api/tests/routes/backoffice/individual_bookings_test.py

Ticket Jira (ou description si BSR) : Un léger ménage

(BSR)[API] chore: remove some CREDIT_V3 FF from BO

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35201

(PC-35201)[BO] fix: correctly calculate subscription timeline when user's 18th birthday is one after the decree's start

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34897
Eviter de charger trop de données à l'intérieur de la fonction `batch_update_offers`.
Et au passage, remanier légèrement les deux logs de deux cette fonction pour trois raisons : 
1. éviter d'envoyer trop de données à logger.info dans le doute pour éviter toute mauvaise surprise ;
2. éviter d'avoir des logs difficiles à exploiter sur certaines interfaces qui ne gèrent pas très bien les logs avec des listes de (dizaines de) milliers d'éléments ;
3. s'assurer que le log qui indique un changement le fasse une fois que ce changement est fait.
Le premier cas n'est peut-être pas indispensable mais dans le doute, cela évite toute mauvaise surprise quant à d'éventuelles limites liées à la sérialisation des …

(PC-34897) fix: batch update offers: avoid high memory usage

---

api/src/pcapi/core/reminders/api.py
api/src/pcapi/routes/native/v1/reminder.py
api/src/pcapi/routes/native/v1/serialization/reminder.py
api/tests/routes/native/openapi_test.py
api/tests/routes/native/v1/reminder_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35071

(PC-35071)[API] feat: add reminders GET route

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py
api/tests/core/users/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35266

(PC-35266)[API] fix: transfer cancellable bookings to new deposits

---

api/src/pcapi/algolia_settings_offers.json

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34530

(PC-34530)[API] feat: make `artists.id` a filter for Algolia

---

api/src/pcapi/core/bookings/repository.py
api/src/pcapi/routes/pro/bookings.py
api/tests/routes/pro/get_all_bookings_test.py
api/tests/routes/pro/get_bookings_csv_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35093

(PC-35093)[API] fix: Filter by offererId on `bookings/pro`

---

api/src/pcapi/core/fraud/factories.py
api/src/pcapi/core/operations/factories.py
api/src/pcapi/core/users/factories.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_new_caledonia_objects.py
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/admin_test.py
api/tests/routes/backoffice/chronicles_test.py
api/tests/routes/backoffice/filters_test.py
api/tests/routes/backoffice/fraud_test.py
api/tests/routes/backoffice/individual_bookings_test.py
api/tests/routes/backoffice/move_siret_test.py
api/tests/routes/backoffice/offers_test.py
api/tests/routes/backoffice/pro_test.py
api/tests/routes/backoffice/pro_users_test.py
api/tests/routes/backoffice/update_request_test.py
api/tests/routes/backoffice/users_test.py
api/tests/routes/backoffice/venues_test.py

Ticket Jira (ou description si BSR) : Ménage dans les factories du BO

(BSR)[BO] chore: use BeneficiaryFactory instead of older ones

---

pro/src/components/ImageUploader/ImageUploader.spec.tsx
pro/src/components/ImageUploader/ImageUploader.stories.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ImageEditor/ImageEditor.spec.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ImageEditor/ImageEditor.stories.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ImageEditor/ImageEditor.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.spec.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
pro/src/ui-kit/form/Slider/Slider.stories.tsx
pro/src/ui-kit/form/Slider/Slider.tsx
pro/src/ui-kit/form/Slider/__specs__/Slider.spec.tsx

BSR cette PR enlève formik du process d'upload d'image pour préparer le chantier à venir sur le parcours d'upload des images

PC-35294 pro remove formik from image uploader

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250319T154233_508b85341c00_add_event_opening_hours.py
api/src/pcapi/core/offers/models.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35041

(PC-35041)[API] feat: add `EventOpeningHours` and `EventWeekDayOpeningHours` models

---

pro/src/pages/LostPassword/LostPassword.module.scss
pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.module.scss
pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.spec.tsx
pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.tsx
pro/src/pages/Signup/SignupContainer/SignupContainer.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35315

(PC-35315)[PRO] feat: subscription confirmation redesign.

---

.github/workflows/dev_on_workflow_deploy.yml

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35290

(PC-35290) ci: fix apply Algolia config

---

pro/src/app/App/layout/Layout.module.scss
pro/src/app/App/layout/Layout.tsx
pro/src/components/IndividualOffer/IndividualOfferLayout/IndividualOfferLayout.module.scss
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.module.scss
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35319

(PC-35319)[PRO] fix: restore IndividualOfferLayout / CollectiveOfferLayout header elements css

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250324T091925_d25a79f51151_remove_provider_id_in_collective_offer_template.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/providers/models.py
api/src/pcapi/workers/update_all_offers_active_status_job.py
api/tests/routes/backoffice/providers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35317

(PC-35317)[API] feat: remove providerId in collective offer template

---

api/.vscode/settings.json
api/pyproject.toml
api/tests/conftest.py
api/tests/connectors/api_demarches_simplifiees_test.py
api/tests/connectors/harvestr_test.py
api/tests/connectors/typeform/typeform_test.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_api_legacy.py
api/tests/core/fraud/test_api.py
api/tests/core/offerers/test_api.py
api/tests/core/offerers/test_commands.py
api/tests/core/offers/test_models.py
api/tests/core/offers/test_repository.py
api/tests/core/search/test_backend_algolia.py
api/tests/core/search/test_serialize_algolia.py
api/tests/core/subscription/test_api.py
api/tests/core/subscription/ubble/end_to_end/test_subscription_via_ubble.py
api/tests/core/token/test_token.py
api/tests/core/users/test_models.py
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/collective_offers_test.py
api/tests/routes/backoffice/offerers_test.py
api/tests/routes/native/openapi_test.py
api/tests/routes/pro/get_all_bookings_test.py
api/tests/routes/pro/get_bookings_csv_test.py
api/tests/routes/pro/patch_collective_stock_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
api/tests/routes/public/individual_offers/v1/patch_date_test.py
api/tests/utils/lock_test.py

Ticket Jira (ou description si BSR) : Pour réactiver Pylint dans les tests

(BSR)[API] feat: reactivate pylint in tests

---

api/src/pcapi/core/educational/models.py
api/src/pcapi/routes/pro/national_programs.py
api/tests/core/educational/test_models.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35322

(PC-35322)[API] refactor: rewrite imports in educational models

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/workers/apps_flyer_job.py
api/tests/core/bookings/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35324

(PC-35324)[API] fix: Issue for log_user_booked_offer_event_job

---

api/src/pcapi/core/achievements/models.py
api/src/pcapi/core/bookings/models.py
api/src/pcapi/core/bookings/repository.py
api/src/pcapi/core/chronicles/api.py
api/src/pcapi/core/educational/api/venue.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/users/backoffice/api.py
api/src/pcapi/flask_app.py
api/src/pcapi/models/beneficiary_import_status.py
api/src/pcapi/models/pc_object.py
api/src/pcapi/models/providable_mixin.py
api/src/pcapi/models/soft_deletable_mixin.py
api/src/pcapi/repository/user_queries.py
api/src/pcapi/routes/backoffice/bookings/helpers.py
api/src/pcapi/routes/backoffice/titelive/blueprint.py
api/src/pcapi/routes/institutional/playlist.py
api/src/pcapi/routes/native/v1/favorites.py
api/src/pcapi/routes/pro/stocks.py
api/src/pcapi/routes/public/individual_offers/v1/bookings.py
api/src/pcapi/routes/public/individual_offers/v1/utils.py
api/src/pcapi/scripts/batch_update_offer_withdrawal_details_for_offerer.py
api/src/pcapi/use_cases/save_venue_bank_informations.py
api/src/pcapi/validation/models/generic.py
api/tests/models/pc_object_test.py

Ticket Jira (ou description si BSR) : un peu de ménage

(BSR)[API] chore: better imports and aliases

---

pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPage.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/__specs__/PartnerPage.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34742

(PC-34742)[PRO] feat: under FF, only display 'Grand public' section for venue in Home when hasPartnerPage

---

pro/src/pages/Signup/SignupContainer/SignupForm.tsx

Correction d'un bug Sentry : https://sentry.passculture.team/organizations/sentry/issues/1628880/?project=2&referrer=slack
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35339

(PC-35339)[PRO] fix: Replace modern .toSorted by old alternative .sort

---

api/tests/repository/test_on_commit.py

fix broken test on linter  on master

(BSR)[API] fix: test on master

---

.github/workflows/dev_on_workflow_deploy_pro_pr_version_generic.yml
pro/src/.env.staging
pro/src/.env.testing

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34652
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34655
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34658

(PC-34652)(PC-34655)(PC-34658)[PRO]: Migrer vers le sentry SaaS

---

api/src/pcapi/core/educational/commands.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34377

(PC-34377)[ADAGE] fix: Add a session commit for the command

---

api/src/pcapi/core/educational/models.py

Ticket Jira (ou description si BSR) : il n'y a plus de règles de fraude qui utilisent ces propriétés

(BSR)[API] chore: remove unused category properties

---

api/src/pcapi/core/reminders/api.py
api/tests/routes/native/v1/reminder_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35350

(PC-35350)[API] fix: fix post reminders for multi users

---

api/src/pcapi/algolia_settings_offers.json

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35372

(PC-35372)[API] feat: few Algolia improvements

---

pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferCreation/__specs__/CollectiveOfferCreation.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.spec.tsx
pro/src/pages/CollectiveOfferFromRequest/CollectiveOfferFromRequest.spec.tsx

Ticket Jira (ou description si BSR) : ils ne servent pas, je crois

(BSR)[PRO] chore: remove useless mocks in collective tests

---

.github/workflows/dev_on_pull_request_closed.yml

Petite erreur qui s'est glissée dans la dernière PR

(BSR)[PRO] ci: fix small syntax error in setup node step

---

api/src/pcapi/core/offers/repository.py
api/tests/core/offers/test_repository.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35017

(PC-35017)[API] feat: add retry to `merge_products`

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_future_offers.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35275

(PC-35275)[API] feat: add more relevant future offers in sandbox

---

pro/src/app/App/layout/Layout.module.scss
pro/src/pages/OfferType/OfferType.tsx
pro/src/pages/OfferType/OfferType/IndividualOfferType/IndividualOfferType.module.scss
pro/src/pages/OfferType/OfferType/IndividualOfferType/IndividualOfferType.tsx
pro/src/pages/OfferType/OfferType/IndividualOfferType/__specs__/IndividualOfferType.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35368
Avant ❌ :
Après ✅ :

(PC-35368)[PRO] fix: Fix visual regression on OB main heading

---

api/src/pcapi/models/feature.py
api/tests/core/educational/api/test_edit_collective_offer_stock.py
api/tests/core/educational/test_integration.py
api/tests/core/educational/test_models.py
api/tests/core/educational/test_repository.py
api/tests/core/offers/test_repository.py
api/tests/routes/adage_iframe/get_collective_offers_for_my_institution_test.py
api/tests/routes/pro/delete_image_collective_offers_test.py
api/tests/routes/pro/patch_cancel_collective_offer_booking_test.py
api/tests/routes/pro/patch_collective_offer_template_test.py
api/tests/routes/pro/patch_collective_offer_test.py
api/tests/routes/pro/patch_collective_offers_active_status_test.py
api/tests/routes/pro/patch_collective_offers_archive_test.py
api/tests/routes/pro/patch_collective_offers_educational_institution_test.py
api/tests/routes/pro/patch_collective_stock_test.py
api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
api/tests/routes/pro/post_image_collective_offers_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30688

(PC-30688)[API] feat: remove feature flag ENABLE_COLLECTIVE_NEW_STATUSES

---

api/src/pcapi/connectors/entreprise/backends/insee.py
api/src/pcapi/connectors/entreprise/sirene.py
api/src/pcapi/core/offerers/commands.py
api/src/pcapi/core/offerers/tasks.py
api/tests/connectors/sirene_test.py
api/tests/connectors/sirene_test_data.py
api/tests/core/offerers/test_commands.py
api/tests/core/offerers/test_tasks.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35022

(PC-35022)[API] feat: schedule re-check offerers closed in the future

---

app-engine/image-resizing/README.md
app-engine/image-resizing/requirements.txt

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35392

(PC-35392)[Image-resize] bump : gunicorn to 23.0.0

---

api/src/pcapi/routes/backoffice/templates/offerer/get.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35399

(PC-35399)[BO] feat: add link to collective offers

---

pro/src/app/AppRouter/routesMap.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPageIndividualSection.tsx
pro/src/pages/VenueEdition/VenueEdition.tsx
pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
pro/src/pages/VenueEdition/context.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34744

(PC-34744)[PRO] fix: get rid of last /partner-page > /page-partenaire

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250326T142747_38997fdd252c_add_event_opening_hours_id_in_stock_table.py
api/src/pcapi/alembic/versions/20250328T093529_dc00a380dc2e_add_foreign_key_constraint_on_stock.py
api/src/pcapi/core/offers/models.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35338
⚠️ La validation des contraintes se fera à l'aide de ce script #16884

(PC-35338)[API] feat: add `eventOpeningHoursId` in `stock` table

---

pro/src/pages/VenueSettings/__specs__/setInitialFormValues.spec.ts
pro/src/pages/VenueSettings/setInitialFormValues.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35369

(PC-35369)[PRO] fix: Do not use venue address details.

---

api/src/pcapi/core/token/__init__.py
api/src/pcapi/routes/pro/users.py
api/tests/conftest.py
api/tests/core/token/test_token.py
api/tests/routes/pro/validate_user_test.py
pro/src/pages/Signup/SignUpValidation/SignUpValidation.tsx
pro/src/pages/Signup/SignUpValidation/__specs__/SignupValidation.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34840

(PC-34840)[API]: feat: Passwordless login on signup

---

.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/dev_on_workflow_deploy.yml

Ticket Jira (ou description si BSR) : please :'(

(BSR) fix: apply-algolia-config job (please)

---

api/src/pcapi/routes/public/individual_offers/v1/products.py
api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35349
Fix : pour savoir s'il existe une offre avec un EAN, regarder dans l'ancienne et la nouvelle colonne.
Ce n'est pas idéal car on ne devrait pas avoir plusieurs EAN pour une même offre (`idAtProvider`, `jsonData->>ean` et `ean`), mais cela évitera aux synchronisations de planter : l'offre n'est pas trouvée parce que `jsonData->>ean` a été mis à jour mais pas `idAtProvider` (ni même `ean`), donc on essaie d'en créer une nouvelle... ce qui plante parce que `l'idAtProvider` de la nouvelle est déjà pris.
La vraie solution serait de tout bien nettoyer mais en attendant, on peut au moins éviter certaines erreurs.

(PC-35349)[API] fix: create/update offers by ean: check offer.ean

---

api/src/pcapi/core/offers/factories.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/search/backends/serialization.py
api/src/pcapi/repository/clean_database.py
api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_event_with_opening_hours_offers.py
api/tests/core/search/test_api.py

Ticket Jira  : https://passculture.atlassian.net/browse/PC-35056
PR dépendante de #16882

(PC-35056)[API] feat: Add event opening hours in sandbox

---

api/src/pcapi/workers/decorators.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35431
see https://python-rq.org/docs/results/#result-ttl

(PC-35431)[API] fix: Add a ttl for rq result keys

---

api/src/pcapi/core/educational/api/adage.py
api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35434

(PC-35434)[API] fix: unexpected history items created when ADAGE ID did not change

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-34491

(PC-34491)[API] feat: allow to move offers with reimboursed bookings

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_api_legacy.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35460

(PC-35460)[API] fix: better group by in invoices csv query

---

api/src/pcapi/connectors/apps_flyer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35435

(PC-35435)[API] fix: Object of type Decimal is not JSON serializable

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250402T095359_579ca0aff07d_create_index_collective_dms_application_siren.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/offerers/validation_repository.py
api/tests/core/educational/test_models.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35469
Solution testée sur staging : détails dans Jira

(PC-35469)[BO] fix: timeout when listing validated offerers

---

api/src/pcapi/routes/backoffice/offerers/forms.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35461

(PC-35461)[BO] feat: invite user from the backoffice

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35252

(PC-35252)[API] chore: normalize logs for offer and stock updates

---

api/src/pcapi/core/offers/api.py

(BSR)[API] refactor: remove print

---

pro/src/components/ImageUploader/ImageUploader.spec.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ButtonImageEdit.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.module.scss
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35404

(PC-35404)[PRO] feat: move image upload in drawer

---

api/src/pcapi/sandboxes/scripts/save_sandbox.py
api/tests/sandboxes/scripts/test_save_sandbox.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35464

(PC-35464)[API] fix: update sandbox offer indexing

---

pro/cypress/e2e/createIndividualOffer.cy.ts
pro/cypress/e2e/oaIndividualOffer.cy.ts

(BSR)[PRO] fix: Failing E2E test with picture drawer.

---

api/src/pcapi/core/offerers/api.py
api/tests/routes/backoffice/venues_test.py
api/tests/routes/pro/patch_venue_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35446

(PC-35446)[API] feat: When update venue, keep isOpenToPublic and isPermanent consistent

---

api/src/pcapi/core/artist/commands.py
api/tests/core/artist/test_commands.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35184

PC-35184 import artists by batch

---

api/src/pcapi/routes/backoffice/forms/fields.py
api/src/pcapi/routes/backoffice/offers/forms.py
api/src/pcapi/routes/backoffice/templates/components/collapsable_text.html
api/src/pcapi/routes/backoffice/templates/components/display_selector.html
api/src/pcapi/routes/backoffice/templates/components/forms.html
api/src/pcapi/routes/backoffice/templates/components/forms/field_list_field.html
api/src/pcapi/routes/backoffice/templates/components/forms/limit_field.html
api/src/pcapi/routes/backoffice/templates/components/links.html
api/src/pcapi/routes/backoffice/templates/layouts/list.html
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/static/backoffice/js/addons/pc-batch-action-form.js
api/src/pcapi/static/backoffice/js/addons/pc-display-selector.js
api/src/pcapi/static/backoffice/js/addons/pc-table-manager.js
api/src/pcapi/static/backoffice/scss/pc/_forms.scss
api/src/pcapi/static/backoffice/scss/pc/_utilities.scss
api/src/pcapi/static/backoffice/scss/pc/_variables.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34924
avant:
apres:

(PC-34924)[BO] feat: fully rework offer list page

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250327T131331_0fbfa18bdad2_remove_collective_subcategory_id_from_venue.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/serialization/offerers_serialize.py
api/src/pcapi/routes/serialization/venues_serialize.py
api/tests/routes/pro/get_educational_offerers_test.py
api/tests/routes/pro/get_venue_test.py
api/tests/routes/pro/get_venues_test.py
api/tests/routes/pro/patch_venue_collective_data_test.py
pro/src/apiClient/v1/models/EditVenueCollectiveDataBodyModel.ts
pro/src/apiClient/v1/models/GetEducationalOffererVenueResponseModel.ts
pro/src/apiClient/v1/models/GetVenueResponseModel.ts
pro/src/apiClient/v1/models/VenueListItemResponseModel.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35387

(PC-35387)[PRO] feat: drop collectiveSubCategoryId column from Venue

---

api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/static/backoffice/scss/pc/_utilities.scss
api/tests/routes/backoffice/offers_test.py
docker-compose-backend.yml
nginx/conf.d/flaskapp_nossl

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35236
Le premier commit répond au ticket, le second essaye de le rendre utilisable sur les env de dev.
note: les images dans le screenshot sont sous licence cc-by David Revoy

Pc 35236 rpa offres list bo images

---

api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
api/src/pcapi/routes/backoffice/finance/forms.py
api/tests/routes/backoffice/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35484

(PC-35484)[BO] feat: add kind filter on incident list

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35505
Aujourd'hui les produits sont mergés sans laisser aucune trace, ce qui ne permet pas de se faire une idée de la quantité de produits supprimés ni de la fréquence de ces suppressions, on veut y remédier.

(PC-35505)[API] feat: log merging products

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/backoffice/venues/forms.py
api/tests/core/offerers/test_api.py
api/tests/routes/backoffice/venues_test.py
api/tests/routes/pro/patch_venue_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35483

(PC-35483)[API] fix: Accelibre synch only called when venue is open to public

---

api/src/pcapi/core/categories/models.py
api/src/pcapi/core/categories/subcategories.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/offers/schemas.py
api/src/pcapi/core/offers/validation.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/serialization/base.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/src/pcapi/utils/date.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_schemas.py
api/tests/routes/pro/post_event_opening_hours_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/CreateEventOpeningHoursModel.ts
pro/src/apiClient/v1/models/GetEventOpeningHoursResponseModel.ts
pro/src/apiClient/v1/models/TimeSpan.ts
pro/src/apiClient/v1/services/DefaultService.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35042

(PC-35042)[API] feat: add `CreateEventOpeningHoursModel`

---

api/src/pcapi/core/offerers/api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35527

(PC-35527)[API] fix: delete venue accessibility provider commited when updated to close to public

---

pro/src/commons/config/swrQueryKeys.ts
pro/src/pages/VenueEdition/VenueEditionForm.tsx
pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
pro/src/pages/VenueSettings/VenueSettings.tsx
pro/src/pages/VenueSettings/VenueSettingsForm.tsx
pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
pro/src/pages/VenueSettings/__specs__/VenueSettingsScreen.spec.tsx
pro/src/pages/VenueSettings/__specs__/serializers.spec.ts
pro/src/pages/VenueSettings/__specs__/setInitialFormValues.spec.ts
pro/src/pages/VenueSettings/serializers.ts
pro/src/pages/VenueSettings/setInitialFormValues.ts
pro/src/pages/VenueSettings/types.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-32601

(PC-32601)[PRO] feat: remove venueLabel field from venue settings from

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250402T082108_feb74e81bf45_add_timespan_to_program_association.py
api/src/pcapi/core/educational/api/institution.py
api/src/pcapi/core/educational/constants.py
api/src/pcapi/core/educational/factories.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/backend/base.py
api/src/pcapi/routes/adage_iframe/authentication.py
api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
api/src/pcapi/routes/backoffice/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice/utils.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py
api/tests/core/educational/test_models.py
api/tests/core/educational/test_repository.py
api/tests/core/external/external_pro_test.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_api_legacy.py
api/tests/core/finance/test_backends.py
api/tests/routes/adage_iframe/get_authenticate_test.py
api/tests/routes/backoffice/collective_offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35226

(PC-35226)[ADAGE] feat: Add timespan for programs (like MEG)

---

api/tests/routes/pro/patch_collective_offer_template_test.py
api/tests/routes/pro/patch_collective_offer_test.py
api/tests/routes/pro/post_collective_offers_template_test.py
api/tests/routes/pro/post_collective_offers_test.py

Ticket Jira (ou description si BSR) : Les validateurs n'étaient pas testés

(BSR)[PRO] feat: add some tests about formats

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/accounts/forms.py
api/src/pcapi/routes/backoffice/forms/search.py
api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/operations/forms.py
api/src/pcapi/routes/backoffice/search_utils.py
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/operations_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-34796

(PC-34796)[BO] feat: filter special events by beneficiary status

---

api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/tests/routes/backoffice/offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35396

(PC-35396)[BO] feat: add bookingLimitDatetime to offer list

---

api/src/pcapi/core/external/batch.py
api/src/pcapi/core/offers/commands.py
api/src/pcapi/core/reminders/external/reminders_notifications.py
api/src/pcapi/core/reminders/repository.py
api/src/pcapi/notifications/push/__init__.py
api/src/pcapi/notifications/push/backends/batch.py
api/src/pcapi/notifications/push/backends/logger.py
api/src/pcapi/notifications/push/backends/testing.py
api/src/pcapi/notifications/push/trigger_events.py
api/src/pcapi/tasks/batch_tasks.py
api/tests/core/reminders/external/test_reminders_notifications.py
api/tests/core/reminders/test_repository.py
api/tests/core/subscription/ubble/test_api.py
api/tests/routes/native/v1/favorites_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34620

(PC-34620)[API] feat: add batch notification for future offer reminders

---

api/src/pcapi/scripts/move_batch_offer/main.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35283

(PC-35283)[API] script: Check venue compatibility for regularisation

---

api/src/pcapi/routes/native/v1/reminder.py
api/tests/routes/native/openapi_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35566

(PC-35566) fix: add response model in reminders routes

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/search/__init__.py
api/src/pcapi/core/search/backends/serialization.py
api/tests/core/search/test_serialize_algolia.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35363

(PC-35363)[API] feat: add chroniclesCount to Algolia

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/search/__init__.py
api/src/pcapi/core/search/backends/serialization.py
api/tests/core/search/test_serialize_algolia.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35363

(PC-35363)[API] feat: add headlineCount to Algolia

---

api/src/pcapi/routes/adage/v1/serialization/venue.py

Ticket Jira (ou description si BSR) : on remplace l'usage des champs de la venue par les champ sur l'objet address dans les routes adage. Comme on requête des venue avec isVirtual=False, on devrait avoir une adresse

(BSR)[ADAGE] fix: use OA only for venue address in adage v1 routes

---

api/src/pcapi/alembic/versions/20240419T143429_154f5e68cb31_create_product_mediation.py
api/src/pcapi/core/offers/factories.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/providers/titelive_api.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
api/tests/core/offers/test_models.py
api/tests/routes/external/sendinblue_test.py
api/tests/routes/native/v1/offers_test.py
api/tests/routes/pro/get_offerer_headline_offer_test.py
api/tests/routes/pro/get_product_by_ean_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33298

PC-33298 use product mediations in cine synchro (prequel)

---

api/src/pcapi/core/offers/models.py
api/tests/providers/titelive_search_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33298

(PC-33298)[API] fix: product images values must be URLs

---

api/src/pcapi/routes/backoffice/filters.py
api/tests/routes/backoffice/filters_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35552

(PC-35552)[BO] feat: show expired in deposit badge

---

api/src/pcapi/scripts/subscription/dms/handle_deleted_dms_applications.py
api/tests/core/subscription/test_api.py
api/tests/scripts/subscription/handle_deleted_dms_applications_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35311

(PC-35311) fix: do not cancel OK DMS fraud checks

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/commands.py
api/tests/core/offerers/test_api.py

(BSR)[API] chore: remove unused acceslibre commands

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/routes/native/v1/serialization/bookings.py
api/tests/routes/native/openapi_test.py
api/tests/routes/native/v1/bookings_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34674

(PC-34674) feat: add infos in Booking Venue serializer

---

api/src/pcapi/core/geography/api.py
api/src/pcapi/core/geography/models.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/fill.py
api/tests/core/geography/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34954

(PC-34954)[API] feat: fix collective playlist data in sandbox

---

pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.tsx
pro/src/pages/VenueSettings/VenueProvidersManager/AddVenueProviderButton.tsx
pro/src/pages/VenueSettings/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.tsx
pro/src/pages/VenueSettings/VenueProvidersManager/CinemaProviderForm/CinemaProviderForm.tsx
pro/src/pages/VenueSettings/VenueProvidersManager/StocksProviderForm/StocksProviderForm.tsx
pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderForm.tsx
pro/src/pages/VenueSettings/VenueProvidersManager/__specs__/AddVenueProviderButton.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35611
- Mettre le formulaire allociné dans une dialog pour résoudre un problème avec les boutons close.

(PC-35611)[PRO] fix: Use dialog on allociné creation too to fix an issue.

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/exceptions.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/routes/public/collective/endpoints/domains.py
api/src/pcapi/routes/public/collective/endpoints/educational_institutions.py
api/src/pcapi/routes/public/collective/endpoints/national_programs.py
api/src/pcapi/routes/public/collective/endpoints/offers.py
api/src/pcapi/routes/public/collective/endpoints/students_levels.py
api/src/pcapi/routes/public/collective/endpoints/venues.py
api/tests/routes/public/collective/endpoints/get_collective_formats_test.py
api/tests/routes/public/collective/endpoints/get_collective_offer_public_provider_test.py
api/tests/routes/public/collective/endpoints/get_collective_offers_educational_domains_test.py
api/tests/routes/public/collective/endpoints/get_collective_offers_students_levels_test.py
api/tests/routes/public/collective/endpoints/get_collective_offers_test.py
api/tests/routes/public/collective/endpoints/get_collective_offers_venues_test.py
api/tests/routes/public/collective/endpoints/get_educational_institutions_test.py
api/tests/routes/public/collective/endpoints/get_national_programs_test.py
api/tests/routes/public/collective/endpoints/post_collective_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35579

(PC-35579)[API] feat: add atomic on public api collective routes

---

pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ImageEditor/utils.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35625

(PC-35625)[PRO] fix: resizing on save without modification

---

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33799

(PC-33799)[API] feat: add offers with interactions in sandbox

---

pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.spec.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35627

(PC-35627)[PRO] fix: set credit on image

---

api/src/pcapi/core/external/attributes/api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35445

(PC-35445) refactor: add comment that was deleted

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/exceptions.py
api/src/pcapi/routes/backoffice/move_siret.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/pro/move_siret_confirmation.html
api/src/pcapi/routes/backoffice/venues/blueprint.py
api/tests/core/offerers/test_api.py
api/tests/routes/backoffice/move_siret_test.py
api/tests/routes/backoffice/offerers_test.py
api/tests/routes/backoffice/venues_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35502

(PC-35502)[BO] fix: ForeignKeyViolation on custom_reimbursement_rule when deleting venue or offerer

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/pro/headline_offer.py
api/tests/core/offers/test_api.py
api/tests/routes/pro/delete_headline_offer_test.py
api/tests/routes/pro/post_upsert_headline_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35524

(PC-35524)[API] fix: do not send delete headline offer log twice

---

pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.tsx
pro/src/ui-kit/formV2/RadioButton/RadioButton.spec.tsx
pro/src/ui-kit/formV2/RadioButton/RadioButton.stories.tsx
pro/src/ui-kit/formV2/RadioButton/RadioButton.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35637

(PC-35637)[PRO] feat: Migrate <RadioButton> input to /formV2/

---

api/src/pcapi/core/reactions/api.py
api/src/pcapi/core/reactions/exceptions.py
api/src/pcapi/routes/native/v1/reaction.py
api/tests/routes/native/v1/reaction_test.py

Ticket Jira: https://passculture.atlassian.net/browse/PC-35648

(PC-35648)[API] fix: ensure that user can react to an offer on backend side

---

api/tests/routes/pro/get_all_collective_offers_test.py

(BSR)[PRO] test: Remove `seed` from test GET /collective/offers

---

api/src/pcapi/flask_app.py
api/src/pcapi/routes/backoffice/home.py
api/tests/routes/backoffice/redirect_test.py

This reverts commit 6c68deb73face6b464973e48816d05e705ebe74f.
revert de https://github.com/pass-culture/pass-culture-main/pull/17183

Revert "(BSR)[BO] test: timeout experimentation"

---

api/src/pcapi/routes/backoffice/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice/templates/components/badges.html
api/src/pcapi/routes/backoffice/templates/components/forms.html
api/src/pcapi/routes/backoffice/templates/components/forms/string_field.html
api/src/pcapi/routes/backoffice/templates/components/messages.html
api/src/pcapi/routes/backoffice/templates/components/navbar.html
api/src/pcapi/routes/backoffice/templates/layouts/details.html
api/src/pcapi/routes/backoffice/templates/multiple_offers/search_result.html
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/src/pcapi/static/backoffice/js/addons/pc-table-manager.js
api/src/pcapi/static/backoffice/scss/pc/_buttons.scss
api/src/pcapi/static/backoffice/scss/pc/_utilities.scss
api/src/pcapi/static/backoffice/scss/pc/_variables.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35644

(PC-35644)[BO] fix: multiple UI problems

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250414T151402_c8e0b1764aa7_remove_product_jsondata_ean_index.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35657

(PC-35657)[API] fix: remove index Product jsonData->>'ean'

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/pro/get_offer_test.py
pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
pro/src/apiClient/v1/models/GetIndividualOfferWithAddressResponseModel.ts
pro/src/commons/utils/factories/individualApiFactories.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35043

(PC-35043)[API] feat: add event opening hours in GET offer

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250414T153518_377710c191ca_remove_offer_jsondata_ean_index.py
api/src/pcapi/core/offers/models.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35658

(PC-35658)[API] fix: remove index Offer jsonData->>'ean'

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/search/__init__.py
api/src/pcapi/core/search/backends/serialization.py
api/tests/core/search/test_serialize_algolia.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35676

(PC-35676) revert chronicles and headlines in algolia

---

pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35182

(PC-35182)[PRO] fix: fetch updated offer status (out of stock) when all dates (stock events) are deleted

---

api/src/pcapi/scripts/move_batch_offer/main.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35286

(PC-35286)[API] script: regularisation, move all offers, collective template, collective playlist and price category label

---

pro/src/commons/hooks/swr/useOfferer.ts
pro/src/commons/store/nav/reducer.ts
pro/src/commons/store/nav/selector.ts
pro/src/commons/utils/__specs__/savedPartnerPageVenueId.spec.ts
pro/src/commons/utils/savedPartnerPageVenueId.ts
pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.tsx
pro/src/components/SideNavLinks/SideNavLinks.tsx
pro/src/components/SideNavLinks/__specs__/SideNavLinks.spec.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/PartnerPages.spec.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/PartnerPages.tsx
pro/src/pages/VenueEdition/VenueEdition.tsx
pro/src/pages/VenueEdition/VenueFormActionBar/__specs__/VenueFormActionBar.spec.tsx
pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
pro/src/pages/VenueEdition/context.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35422

(PC-35422)[PRO] feat: memorize venue / partnerPage id selections from homepage & "page sur l'application"

---

pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.spec.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferImageDialogs.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35629

(PC-35629)[PRO] feat: remove last step on mise à la une

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/exceptions.py
api/src/pcapi/core/offers/factories.py
api/src/pcapi/core/offers/schemas.py
api/src/pcapi/core/offers/validation.py
api/src/pcapi/routes/pro/offers.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_validation.py
api/tests/routes/pro/patch_offer_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/UpdateEventOpeningHoursModel.ts
pro/src/apiClient/v1/services/DefaultService.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35411
Ajout d'une route sur le portail PRO permettant de mettre à jour les horaires d'ouvertures d'un événement.

(PC-35411)[API] feat: pro: opening hours: add update route

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/backoffice/offerers/forms.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/get.html
api/src/pcapi/routes/backoffice/templates/offerer/validation.html
api/src/pcapi/routes/backoffice/venues/blueprint.py
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35674

(PC-35674)[BO] feat: enable to set all offers manual review at offerer validation

---

api/src/pcapi/models/feature.py
api/src/pcapi/routes/shared/collective/serialization/offers.py
api/tests/routes/pro/post_collective_offers_test.py
pro/cypress/support/index.d.ts
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.tsx
pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx
pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducational.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveEditionOfferNavigation/CollectiveEditionOfferNavigation.tsx
pro/src/pages/CollectiveOfferFromRequest/CollectiveOfferFromRequest.tsx
pro/src/pages/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplication.tsx
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/__specs__/CollectiveDataForm.spec.tsx

Ticket Jira (ou description si BSR) : On veut garder le FF à long terme pour le front, au final

(BSR)[PRO] feat: rename WIP_ENABLE_MARSEILLE to ENABLE_MARSEILLE

---

api/src/pcapi/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary.py
api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
api/src/pcapi/models/feature.py
api/tests/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary_test.py

Ticket Jira (ou description si BSR) : ça semble être un test d'il y a 2 ans...

(BSR)[API] chore: remove useless WIP FF and mail template

---

pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.spec.tsx
pro/src/components/ImageUploader/components/ButtonImageEdit/ModalImageEdit/components/ModalImageCrop/ModalImageCrop.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35705

(PC-35705)[PRO] feat: hide preview offer

---

api/poetry.lock
api/pyproject.toml
api/src/pcapi/core/logging.py
api/src/pcapi/core/subscription/api.py
api/src/pcapi/core/subscription/machines.py
api/tests/routes/native/v1/account_test.py
api/tests/routes/native/v1/banner_test.py
api/tests/routes/native/v1/subscription_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35698

(PC-35698) refactor: use state machines for beneficiary subscription

---

api/src/pcapi/models/feature.py
api/tests/core/subscription/ubble/end_to_end/test_subscription_via_ubble.py
api/tests/core/subscription/ubble/test_api.py
api/tests/routes/native/v1/account_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35545

(PC-35545) feat: add free eligiblity feature flag

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/exceptions.py
api/src/pcapi/models/feature.py
api/src/pcapi/routes/pro/offerers.py
api/tests/core/offerers/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35633

(PC-35633)[API] feat: New venue without siret only allowed to collectivity

---

api/src/pcapi/core/offers/schemas.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/CreateEventOpeningHoursModel.ts
pro/src/apiClient/v1/models/OpeningHoursByWeekDayModel.ts
pro/src/apiClient/v1/models/UpdateEventOpeningHoursModel.ts

Ticket Jira (ou description si BSR) : PR pour fixer le typing généré par typescript à partir de la documentation openapi.json

(BSR)[PRO] fix: rename `OpeningHoursModel` to `OpeningHoursByWeekDayModel` to fix typing

---

api/src/pcapi/routes/backoffice/offerers/forms.py
api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py
api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html
api/src/pcapi/routes/backoffice/templates/components/forms.html
api/src/pcapi/routes/backoffice/templates/layouts/list.html
api/src/pcapi/routes/backoffice/templates/offerer/validation.html
api/src/pcapi/static/backoffice/js/addons/pc-table-multi-select.js
api/src/pcapi/static/backoffice/scss/pc/_variables.scss
api/tests/routes/backoffice/helpers/html_parser.py
api/tests/routes/backoffice/offerers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35687
avant:
apres:

(PC-35687)[BO] feat: migrate offerer validation to new UI

---

api/src/pcapi/routes/backoffice/offerers/forms.py
api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html
api/tests/routes/backoffice/offerers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35692
avant
apres

(PC-35692)[BO] feat: apply new UI on user offerer validation page

---

pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.module.scss
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.tsx
pro/src/ui-kit/form/shared/BaseInput/BaseInput.module.scss
pro/src/ui-kit/form/shared/FieldLayout/FieldLayoutCharacterCount/FieldLayoutCharacterCount.module.scss
pro/src/ui-kit/formV2/TextInput/TextInput.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35570

(PC-35570)[PRO] fix: restore DetailsEanSearch style after migration

---

api/src/pcapi/routes/backoffice/templates/gdpr_user_extract_data/list_gdpr_user_extract.html
api/src/pcapi/routes/backoffice/templates/layouts/list.html
api/tests/routes/backoffice/gdpr_user_extract_data_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35763
avant:
apres:

(PC-35763)[BO] feat: migrate dgpr extraction list to the new UI

---

api/src/pcapi/routes/backoffice/accounts/forms.py
api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py
api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html
api/src/pcapi/routes/backoffice/templates/layouts/base.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35765
avant:
apres:

(PC-35765)[BO] feat: migrate DS list to new UI

---

api/src/pcapi/algolia_settings_offers.json

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35710

(PC-35710)[API] feat: make artists list searchable

---

api/src/pcapi/core/external/batch_utils.py
api/tests/core/external/batch_utils_test.py
pro/cypress/e2e/createIndividualOffer.cy.ts
pro/src/components/FormLayout/FormLayoutRow.tsx
pro/src/components/FormLayout/FormLayoutRowWithInfo.tsx
pro/src/components/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.tsx
pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx

(BSR)[PRO] fix: Failing E2E tests.

---

.github/workflows/dev_on_dispatch_deploy_pullrequests.yml
.github/workflows/dev_on_pull_request_workflow.yml
.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/dev_on_schedule_deploy_main_and_pro.yml
.github/workflows/dev_on_workflow_tests_pro_e2e.yml
.github/workflows/dev_on_workflow_update_api_client_template.yml
pc

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35791

(PC-35791)[API] ci: deploy preview env on branch

---

pro/src/components/ImageUploader/ImageDragAndDropUploader.module.scss
pro/src/components/ImageUploader/ImageDragAndDropUploader.spec.tsx
pro/src/components/ImageUploader/ImageDragAndDropUploader.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35407

(PC-35407)[PRO] feat: rewrite available opts after image upload (indi…v. offer creation)

---

api/src/pcapi/core/users/exceptions.py
api/src/pcapi/routes/auth/discord.py
api/tests/routes/auth/discord_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35682

(PC-35682)[API] feat: allow discord access from 17 yo

---

.github/workflows/dev_on_pull_request_workflow.yml

(BSR)[API] ci : fix e2e tests

---

.github/workflows/dev_on_schedule_deploy_main_and_pro.yml

(BSR)[API] ci: fix testing deployment

---

.github/workflows/dev_on_schedule_deploy_main_and_pro.yml

Give all permissions to deploy step. This is needed for firebase deployment : 
```
The nested job 'deploy_on_firebase' is requesting 'actions: write, attestations: write, checks: write, contents: write, deployments: write, discussions: write, issues: write, packages: write,[...]
```

(BSR)[API] ci: last fix for permissions

---

api/src/pcapi/connectors/dms/utils.py
api/src/pcapi/routes/external/users_subscription.py
api/src/pcapi/scripts/subscription/dms/handle_inactive_dms_applications.py
api/src/pcapi/scripts/subscription/dms/import_dms_applications.py
api/tests/connectors/dms/utils_test.py

Concurrent access caused an exception:
"DmsGraphQLApiError: Le dossier est déjà classé sans suite"
Ticket Jira : https://passculture.atlassian.net/browse/PC-35776

(PC-35776)[API] fix: DS concurrent access to the same application

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/backoffice/bookings/forms.py
api/src/pcapi/sandboxes/scripts/getters/pro.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_repository.py

Ticket Jira (ou description si BSR) : C'est plus beau

(BSR)[API] chore: import EacFormat from its file

---

api/src/pcapi/routes/backoffice/bookings/forms.py
api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
api/src/pcapi/static/backoffice/js/addons/pc-table-manager.js
api/tests/routes/backoffice/collective_bookings_test.py
api/tests/routes/backoffice/individual_bookings_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35794
avant:
apres:

(PC-35794)[BO] feat: migrate individual booking list to new UI

---

api/src/pcapi/core/artist/commands.py
api/tests/core/artist/test_commands.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35617

(PC-35617)[API] feat: ignore artists import errors

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_incidents.py
api/tests/core/educational/api/test_edit_collective_offer_stock.py
api/tests/routes/native/v1/bookings_test.py
api/tests/routes/pro/get_offers_test.py
api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py

Ticket Jira (ou description si BSR) : un peu de ménage

(BSR)[API] chore: remove minor and useless fixmes

---

api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35805
Problemes connu:
- la personalisation du tableau est cassée
- la gestion du nombre de lignes retournée est cassée.
Ces deux problemes sont résolu par la PR: https://github.com/pass-culture/pass-culture-main/pull/17293 qui est a merger avant
avant:
apres:

(PC-35805)[BO] feat: migrate collective-booking list to the new ui

---

api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/offers/forms.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35344

(PC-35344)[BO] fix: temporary remove VISA search for offer on backoffice

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/repository.py
api/tests/core/offerers/test_api.py
api/tests/routes/pro/get_venues_of_offerer_from_siret_test.py
api/tests/routes/pro/post_offerer_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35641

(PC-35641)[PRO] fix: create rejected offerers again

---

api/src/pcapi/routes/pro/offers.py
api/tests/routes/pro/post_thumbnail_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35693

(PC-35693)[API] feat: Removed mediation size constraints

---

api/src/pcapi/routes/backoffice/custom_reimbursement_rule/forms.py
api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list.html
api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list/stats.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35815
avant:
apres:

(PC-35815)[BO] feat: migrate custom reimbursement rules to new UI

---

api/src/pcapi/core/external_bookings/serialize.py
api/tests/core/external_bookings/test_api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35827

(PC-35827)[API] fix: ValidationError: 1 validation error for ParsingModel[ExternalEventCancelBookingResponse]

---

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35517

(PC-35517)[PRO] fix: reset button alignement in reimbursment

---

api/src/pcapi/core/providers/titelive_api.py
api/src/pcapi/core/providers/titelive_book_search.py
api/src/pcapi/core/providers/titelive_music_search.py
api/tests/providers/titelive_search_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35855

(PC-35855) fix: silence truncated titelive thumbnail error

---

pro/cypress/e2e/collectiveBooking.cy.ts
pro/cypress/e2e/cookieBanner.cy.ts
pro/cypress/e2e/createIndividualOffer.cy.ts
pro/cypress/e2e/desk.cy.ts
pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
pro/cypress/e2e/financialManagement.cy.ts
pro/cypress/e2e/oaIndividualOffer.cy.ts
pro/cypress/e2e/searchCollectiveOffer.cy.ts
pro/cypress/e2e/searchIndividualOffer.cy.ts
pro/cypress/support/helpers.ts

- Changer les before par des beforeEach

(BSR)[PRO] fix: Removing `before` and using `beforeEach`.

---

pro/cypress/support/helpers.ts

- Rajouter un check du status de l'inscription.

(BSR)[PRO] fix: Check signup status.

---

api/src/pcapi/core/logging.py
api/src/pcapi/flask_app.py
api/src/pcapi/utils/login_manager.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35867

(PC-35867)[API] fix: try to fix the random broken session problem in the BO

---

api/tests/sandboxes/scripts/test_save_sandbox.py

(BSR)[API] fix: flaky test in save sandbox

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250425T154704_1dd69b99a36d_add_not_null_constraint_on_address_departmentCode_step_2_of_4.py
api/src/pcapi/alembic/versions/20250425T154704_57fed0c8eb34_add_not_null_constraint_on_address_departmentCode_step_1_of_4.py
api/src/pcapi/alembic/versions/20250425T154704_60fdd63d8828_add_not_null_constraint_on_address_departmentCode_step_4_of_4.py
api/src/pcapi/alembic/versions/20250425T154704_eed8954b8bca_add_not_null_constraint_on_address_departmentCode_step_3_of_4.py
api/src/pcapi/core/geography/models.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35655

(PC-35655)[API] feat: add not null constraint on Address.departmentCode

---

api/src/pcapi/core/offers/schemas.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/core/offers/test_schemas.py
api/tests/routes/pro/get_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35043

(PC-35043)[API] fix: send opening hours without seconds

---

api/poetry.lock
api/pyproject.toml

(BSR)[API] bump: upgrade pyhton packages (no major version)

---

api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py

(BSR)[API] test: remove useless and harmful time decoration in tests

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250424T082440_052c063a3fd5_add_soft_delete_future_offers.py
api/src/pcapi/alembic/versions/20250428T075154_2720029af088_add_soft_delete_future_offers.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/commands.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/reminders/external/reminders_notifications.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_repository.py
api/tests/core/reminders/external/test_reminders_notifications.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35734

(PC-35734)[API] feat: add soft delete for future offer when offer is activated

---

.github/workflows/dev_on_pull_request_workflow.yml

(BSR)[API] ci: do not run pcapi tests when only front changed

---

pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.module.scss
pro/src/components/Header/components/HeaderDropdown/HeaderDropdown.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35862

(PC-35862)[PRO] fix: HeaderDropdown design

---

pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/__specs__/FormOfferType.spec.tsx
pro/src/ui-kit/form/TextArea/TextArea.tsx
pro/src/ui-kit/form/TextArea/__specs__/TextArea.spec.tsx
pro/src/ui-kit/formV2/TextArea/TextArea.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35234
On supprime le code liée à l'a/b test qui concerne la génération d'un exemple pour la description d'une offre vitrine, on veut maintenant l'afficher pour tout le monde

(PC-35234)[PRO] refactor: delete template ab test

---

api/src/pcapi/models/feature.py

BSR problème de rebase, j'ai laissé le ff

(BSR)[PRO] feat: remove WIP_EAN_CREATION

---

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
pro/cypress/e2e/collectiveBooking.cy.ts
pro/cypress/e2e/cookieBanner.cy.ts
pro/cypress/e2e/createIndividualOffer.cy.ts
pro/cypress/e2e/desk.cy.ts
pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
pro/cypress/support/helpers.ts

- Réessayer la connexion si ça ne fonctionne pas.
- Enlever des créations de compte inutiles.
- Chunks manuels pour avoir des durées plus ou moins similaires.

(BSR)[PRO] ci: Retry signup if it fails.

---

api/src/pcapi/core/artist/models.py
api/src/pcapi/core/chronicles/models.py
api/src/pcapi/core/criteria/models.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/permissions/models.py

Ticket Jira (ou description si BSR) : Pour le bump

(PC-35901)[API] feat: use __table__ many-to-many relationships

---

pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPage.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/__specs__/PartnerPage.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35964

(PC-35864)[PRO] feat: add venue settings button to home

---

pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/IndividualOfferRow.spec.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/IndividualOfferRow/components/HeadlineOfferImageDialogs.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35588

(PC-35588)[PRO] feat: use new upload & crop image modal on /offers when an offer is about to become a headline offer

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250429T125155_38128af23ab7_add_softdelete_to_venue.py
api/src/pcapi/core/offerers/models.py

Ticket Jira: https://passculture.atlassian.net/browse/PC-35915

(PC-35915)[API] feat: add isSoftDeleted to Venue

---

.github/workflows/dev_on_workflow_ping_data_team.yml

(BSR) ci: fix typo in Slack action payload

---

pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
pro/src/commons/context/SignupJourneyContext/SignupJourneyContext.tsx
pro/src/components/SignupJourneyForm/Offerer/Offerer.tsx
pro/src/components/SignupJourneyForm/Offerers/Offerers.tsx
pro/src/components/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx
pro/src/pages/Signup/SignupContainer/constants.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35851

(PC-35851)[PRO] feat: only local authority can add venue

---

api/src/pcapi/routes/backoffice/templates/components/forms.html
api/src/pcapi/routes/backoffice/templates/venue/list.html
api/src/pcapi/routes/backoffice/venues/forms.py
api/src/pcapi/static/backoffice/scss/pc/_utilities.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35761

(PC-35761)[BO] feat: convert action on venue to the new ui

---

api/src/pcapi/routes/backoffice/templates/layouts/list.html
api/src/pcapi/routes/backoffice/templates/providers/list.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35811
avant:
apres:

passage de la page providers a la nouvelle UI

---

.github/workflows/dev_on_dispatch_deploy_pullrequests.yml
pc

(BSR)[API] ci : deploy only front preview

---

api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
api/src/pcapi/routes/backoffice/templates/components/generic_modal.html
api/src/pcapi/routes/backoffice/templates/components/history/comment.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card_offerer.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card_venue.html
api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list.html
api/src/pcapi/routes/backoffice/templates/fraud/domain_names.html
api/src/pcapi/routes/backoffice/templates/offer_price_limitation_rules/list_rules.html
api/src/pcapi/routes/backoffice/templates/offer_validation_rules/list_rules.html
api/src/pcapi/routes/backoffice/templates/offer_validation_rules/sub_rules_extra_row.html
api/src/pcapi/routes/backoffice/templates/pivots/get/common.html
api/src/pcapi/routes/backoffice/templates/providers/list.html
api/src/pcapi/routes/backoffice/templates/tags/list_tags.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35947

(PC-35947)[BO] fix: css on mouse hover on buttons

---

api/src/pcapi/routes/backoffice/templates/admin/subcategories.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35942
avant:
apres:

(PC-35942)[BO] feat:migrate subcategories page to the new UI

---

pro/src/pages/Homepage/components/StatisticsDashboard/components/LoadingSkeleton.module.scss
pro/src/pages/Homepage/components/StatisticsDashboard/components/LoadingSkeleton.tsx
pro/src/pages/Homepage/components/StatisticsDashboard/components/OfferStats.tsx
pro/src/ui-kit/Skeleton/Skeleton.module.scss
pro/src/ui-kit/Skeleton/Skeleton.spec.tsx
pro/src/ui-kit/Skeleton/Skeleton.stories.tsx
pro/src/ui-kit/Skeleton/Skeleton.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35147

(PC-35147)[PRO] feat: poc to add skeleton in the application

---

api/src/pcapi/routes/backoffice/templates/components/forms.html
api/src/pcapi/routes/backoffice/templates/offer_price_limitation_rules/list_rules.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35939
avant:
apres:

(PC-35939)[BO] feat: migrate price change rules to the new ui

---

README.md
api/README.md

(BSR)[API] docs: add deployment to readme + small fixes

---

api/documentation/docs/understanding-our-api/resources/collective-offers.md
api/documentation/src/pages/change-logs.md
api/documentation/static/openapi.json
api/src/pcapi/core/educational/factories.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/educational/testing.py
api/src/pcapi/routes/public/collective/endpoints/offers.py
api/src/pcapi/routes/public/collective/serialization/offers.py
api/src/pcapi/routes/public/documentation_constants/fields.py
api/src/pcapi/routes/public/documentation_constants/http_responses.py
api/tests/core/educational/test_repository.py
api/tests/routes/pro/patch_collective_offers_archive_test.py
api/tests/routes/pro/patch_collective_offers_template_archive_test.py
api/tests/routes/public/collective/endpoints/post_archive_collective_offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33996
Les docs correspondantes

(PC-33996)[API] Ajouter une route sur lapi publique pour archiver une offre collective

---

api/tests/routes/backoffice/individual_bookings_test.py

Ticket Jira (ou description si BSR) : Fix d'un test flaky

(BSR)[API] fix: repair fraudulent flaky test

---

pro/src/ui-kit/chartGlobals.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35957

(PC-35957)[PRO] build: Import specific chartjs modules for lighter bundle.

---

pro/src/styles/components/_CookieModals.scss

(BSR)[PRO] build: Fixed sass warning.

---

pro/src/components/ImageDragAndDrop/ImageDragAndDrop.module.scss
pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.module.scss
pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.spec.tsx
pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35512

(PC-35512)[PRO] feat: add warning callout on image upload modal for indiv.offers when small dimensions

---

.github/workflows/dev_on_dispatch_deploy_pullrequests.yml

(BSR)[API] ci: fix backend deployment

---

api/src/pcapi/core/offers/commands.py
api/src/pcapi/models/feature.py
api/tests/core/offers/test_commands.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35738

(PC-35738)[API] feat: secure offers auto cleanup behind a feature flag

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/routes/native/v1/serialization/bookings.py
api/tests/routes/native/openapi_test.py
api/tests/routes/native/v1/bookings_test.py

(PC-35743)chore: remove venue location occurences in getbookings

---

api/src/pcapi/serialization/decorator.py
api/tests/serialization/serialization_decorator_test.py

(BSR)[API] chore: do not serialize body if not in kwargs

---

api/src/pcapi/core/reminders/external/reminders_notifications.py
api/src/pcapi/core/reminders/repository.py
api/tests/core/reminders/external/test_reminders_notifications.py
api/tests/core/reminders/test_repository.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35865

(PC-35865)[API] feat: remove reminders after users notified

---

api/src/pcapi/routes/backoffice/templates/home/home.html
api/src/pcapi/routes/backoffice/templates/home/login.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35953
avant:
apres:

(PC-35953)[BO] feat: migrate home and connexion page to the new UI

---

api/src/pcapi/connectors/api_adresse.py
api/tests/connectors/api_adresse/api_adresse_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35975

(PC-35975)[API] fix: do not create incorrect addresses with empty street

---

.github/workflows/dev_on_schedule_deploy_main_and_pro.yml

We should have had an error on this : https://github.com/pass-culture/pass-culture-main/actions/runs/14840218925/job/41661762590

(BSR)[API] fix: testing deployment

---

api/documentation/docs/integrations/test-data.md
api/documentation/docs/understanding-our-api/resources/individual-offers.md
api/documentation/static/openapi.json
api/src/pcapi/routes/public/documentation_constants/descriptions.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35783

(PC-35783)[API] feat: update public documentation

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35773

(PC-35773)[API] feat: Do not move FinanceEvent from one venue to another during regularisation - individual offer

---

api/src/pcapi/core/educational/api/offer.py
api/tests/core/educational/api/test_move_collective_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35838

(PC-35838)[API] feat: Do not move FinanceEvent from one venue to another during regularisation - collective offers

---

.github/workflows/dev_on_pull_request_workflow.yml

(BSR) ci : save 30s to ci startup

---

api/src/pcapi/routes/backoffice/venues/forms.py
api/tests/routes/backoffice/venues_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35711
- Le champ street est optionnel.

(PC-35711)[PRO] feat: Street field is required.

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/offers/api.py
api/tests/core/educational/api/test_move_collective_offer.py
api/tests/core/offers/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35774

(PC-35774)[API] feat: Remove pricingPoint condition on pricing in regularisation move indiv and collective offers

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/providers/models.py
api/src/pcapi/core/providers/repository.py
api/tests/core/external_bookings/test_api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35933

(PC-35933)[API] feat: enable the use of provider not enabled for pro for booking external ticket

---

api/documentation/src/pages/change-logs.md
api/documentation/static/openapi.json
api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/factories.py
api/src/pcapi/routes/public/collective/serialization/offers.py
api/src/pcapi/routes/public/documentation_constants/fields.py
api/tests/routes/public/collective/endpoints/get_collective_offer_public_provider_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
api/tests/routes/public/collective/endpoints/post_collective_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35867

(PC-35867)[API] feat: Add a return locationType for offer in public API

---

api/tests/core/educational/api/test_move_collective_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35816
CollectiveOfferStatus is deprecated

(PC-35816)[API] chore: Replace CollectiveOfferStatus by CollectiveOfferDisplayedStatus in move collective offer tests

---

api/src/pcapi/core/educational/constants.py
pro/src/commons/core/OfferEducational/types.ts
pro/src/commons/core/OfferEducational/utils/__specs__/createOfferPayload.spec.ts
pro/src/commons/core/OfferEducational/utils/applyVenueDefaultsToFormValues.ts
pro/src/commons/core/OfferEducational/utils/computeInitialValuesFromOffer.ts
pro/src/commons/core/OfferEducational/utils/createOfferPayload.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferEdition/utils/__specs__/createPatchOfferPayload.spec.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferEdition/utils/createPatchOfferPayload.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/FormLocation.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/__specs__/FormLocation.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/OfferEducationalForm.module.scss
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/__specs__/validationSchema.spec.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/validationSchema.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35025
Ajouter le cas "en établissement scolaire" pour le sujet OA côté collectif -> Sous FF

(PC-35025)[PRO] feat: oa etablissement

---

api/src/pcapi/scripts/install.py
api/src/pcapi/scripts/move_offer/move_batch_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34492

(PC-34492)[API] feat: Update move batch offer script into command

---

.githooks/pre-commit
api/pyproject.toml
api/src/pcapi/app.py
api/src/pcapi/backoffice_app.py
api/src/pcapi/core/bookings/constants.py
api/src/pcapi/core/chronicles/api.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/routes/serialization/stock_serialize.py
api/src/pcapi/utils/requests.py
api/stubs/flask/__init__.pyi
api/stubs/flask/app.pyi
api/tests/conftest.py
api/tests/routes/pro/patch_collective_offers_archive_test.py
api/tests/routes/pro/patch_draft_offer_test.py
api/tests/routes/pro/patch_venue_test.py
api/tests/routes/public/collective/endpoints/get_collective_offer_test.py
api/tests/scripts/pro/upload_reimbursement_csv_to_offerer_drive_test.py

Ticket Jira (ou description si BSR) : ajout de la règle unused-import, qu'on ignore dans les fichiers __init__ + quelques cas particuliers

(BSR) style: add unused-import ruff rule

---

api/src/pcapi/routes/public/individual_offers/v1/events.py

(BSR)[API] fix: remove an unused import

---

api/src/pcapi/models/feature.py
api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/tests/routes/public/individual_offers/v1/post_event_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35929

(PC-35929)[API] fix: better handling of music types to remove obsolete ff

---

api/src/pcapi/routes/public/individual_offers/v1/serialization.py

(BSR)[API] fix: unused import

---

.github/workflows/dev_on_schedule_deploy_main_and_pro.yml

(BSR)[API] fix: deploy testing even if backend image hasn't changed

---

pro/src/commons/store/StoreProvider/StoreProvider.module.scss

(BSR)[PRO] feat: center StoreProvider spinner in the page

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36066

(PC-36066)[API] feat: add national program in sandbox

---

pro/src/commons/core/OfferEducational/constants.ts
pro/src/commons/core/OfferEducational/types.ts
pro/src/commons/core/OfferEducational/utils/__specs__/computeInitialValuesFromOffer.spec.ts
pro/src/commons/core/OfferEducational/utils/__specs__/createOfferPayload.spec.ts
pro/src/commons/core/OfferEducational/utils/computeInitialValuesFromOffer.ts
pro/src/commons/core/OfferEducational/utils/createOfferPayload.ts
pro/src/commons/utils/selectInterventionAreas.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferEdition/utils/__specs__/createPatchOfferPayload.spec.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferEdition/utils/createPatchOfferPayload.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/FormLocation.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/InterventionAreaMultiSelect.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/__specs__/FormLocation.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/__specs__/InterventionAreaMultiSelect.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/__specs__/validationSchema.spec.ts
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx
pro/src/ui-kit/MultiSelect/MultiSelect.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35026

(PC-35026)[PRO] feat: add new collective location type TO_BE_DEFINED

---

api/src/pcapi/routes/pro/offers.py
api/src/pcapi/workers/update_all_offers_active_status_job.py
api/tests/routes/pro/patch_all_offers_active_status_test.py
api/tests/routes/pro/patch_offers_active_status_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35621

(PC-35621)[API] feat: notify users w/ reminders manual future offer activation

---

api/src/pcapi/core/offerers/models.py

(BSR)[API] chore: remove None from _has_partner_page column typing

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/accounts/serialization.py
api/src/pcapi/routes/backoffice/templates/accounts/get/details.html
api/src/pcapi/routes/backoffice/templates/accounts/get/details/activity.html
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35877

(PC-35877)[BO] feat: add special event and chronicle to user page

---

api/poetry.lock
api/pyproject.toml

Mise à jour de dépendances
Changelog

(BSR)[API] bump: upgrade pyhton packages

---

pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/CollectiveOfferSummary.module.scss
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/components/CollectiveOfferLocationSection.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/components/OldCollectiveOfferLocationSection.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/components/__specs__/CollectiveOfferLocationSection.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/components/__specs__/OldCollectiveOfferLocationSection.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35033

(PC-35033)[PRO] feat: update collective offer location section on summary when OA FF is active

---

api/src/pcapi/core/history/models.py
api/src/pcapi/core/offerers/commands.py
api/src/pcapi/core/permissions/api.py
api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/models.py
api/src/pcapi/repository/clean_database.py
api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
api/src/pcapi/routes/backoffice/finance/validation.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/pivots/contexts/ems.py
api/src/pcapi/routes/backoffice/templates/components/history/actions.html
api/src/pcapi/templates/extracts/beneficiary_extract.html
api/tests/core/users/test_api.py
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/admin_test.py
api/tests/routes/backoffice/bank_account_test.py
api/tests/routes/backoffice/conftest.py
api/tests/routes/backoffice/finance_test.py
api/tests/routes/backoffice/health_check_test.py
api/tests/routes/backoffice/offerers_test.py
api/tests/routes/backoffice/offers_test.py
api/tests/routes/backoffice/pivots_test.py
api/tests/routes/backoffice/pro_users_test.py
api/tests/routes/backoffice/tags_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36064
10 commits à relire séparément.

Pc 36064 fixes before upgrading flask sqlalchemy etc

---

pro/src/commons/core/Offers/types.ts
pro/src/components/ImageDragAndDropUploader/ImageDragAndDropUploader.spec.tsx
pro/src/components/ImageDragAndDropUploader/ImageDragAndDropUploader.tsx
pro/src/components/IndividualOffer/utils/__specs__/getIndividualOfferImage.spec.ts
pro/src/components/IndividualOffer/utils/getIndividualOfferImage.ts
pro/src/pages/IndividualOffer/IndividualOfferDetails/commons/__specs__/useIndividualOfferImageUpload.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/commons/useIndividualOfferImageUpload.ts
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/ImageUploaderOffer.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/__specs__/ImageUploaderOffer.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/__specs__/buildInitialValues.spec.ts
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/buildInitialValues.ts
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35849

(PC-35849)[PRO] feat: avoid uploading / deleting img thumb on indiv. offer details screen before form submit

---

pro/src/components/ModalImageUpsertOrEdit/ModalImageUpsertOrEdit.module.scss
pro/src/components/ModalImageUpsertOrEdit/components/ImageEditor/ImageEditor.module.scss
pro/src/components/ModalImageUpsertOrEdit/components/ImageEditor/ImageEditor.spec.tsx
pro/src/components/ModalImageUpsertOrEdit/components/ImageEditor/ImageEditor.tsx
pro/src/ui-kit/form/Slider/Slider.module.scss
pro/src/ui-kit/form/Slider/Slider.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35920

(PC-35920)[PRO] feat: add description and custom css for disabled zoom in image upload

---

pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/HeadlineOffer/HeadlineOffer.module.scss
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersTable/components/HeadlineOffer/HeadlineOffer.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35874

(PC-35874)[PRO] fix: set min width for headline offer thumbnail in offers list

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36100

(PC-36100)[API] fix: invalid OA for collective offer in sandbox

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34492
Ajout de:
- lock sur les stock
- option pour préciser 1 venue d'origine, 1 venue de destination
- utilisation du commit par venue uniquement
- désindexation de la venue d'origine si commit

(PC-34492)[API] feat: Updated flask command to move offer

---

pro/src/commons/core/OfferEducational/constants.ts
pro/src/commons/core/OfferEducational/types.ts
pro/src/commons/core/OfferEducational/utils/__specs__/computeInitialValuesFromOffer.spec.ts
pro/src/commons/core/OfferEducational/utils/computeInitialValuesFromOffer.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/FormLocation.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/validationSchema.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36094

(PC-36094)[PRO] fix: do not validate former location data on collective offer form when OA FF is active

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/providers/api.py
api/src/pcapi/workers/update_all_offers_active_status_job.py

(BSR)[API] fix: remove subcategory in some collective functions

---

api/src/pcapi/core/mails/transactional/pro/offerer_closed.py
api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/tasks.py
api/src/pcapi/core/permissions/models.py
api/src/pcapi/routes/backoffice/offerers/forms.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/components/history/actions.html
api/src/pcapi/routes/backoffice/templates/offerer/get.html
api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
api/tests/core/mails/transactional/pro/offerer_closed_test.py
api/tests/core/offerers/test_api.py
api/tests/core/offerers/test_tasks.py
api/tests/routes/backoffice/conftest.py
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36031

(PC-36031)[BO] feat: close offerer from the backoffice

---

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/get.html
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36095

(PC-36095)[BO] feat: Generate API key with permission: MANAGE_TECH_PARTNERS

---

api/src/pcapi/core/offerers/models.py
api/src/pcapi/core/offerers/repository.py
api/tests/core/offerers/test_models.py
api/tests/routes/pro/get_offerer_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36102

(PC-36102)[PRO] feat: closed offerer does not have partner page

---

api/src/pcapi/flask_app.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36129

(PC-36129)[API] fix: try to fix worker hard crash due to session lifecycle corruption

---

api/src/pcapi/routes/pro/offerers.py
api/tests/routes/pro/post_offerer_test.py
pro/src/components/SignupJourneyForm/Offerers/Offerers.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35912
faire remonter correctement les messages de l'api sur le rattachement

(PC-35912)[PRO] feat: error message user offerer

---

api/src/pcapi/core/banner/api.py
api/src/pcapi/routes/native/v1/banner.py
api/tests/routes/native/v1/banner_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35539

(PC-35539)[API] feat: disable activation banner for free eligibility

---

api/src/pcapi/core/external/attributes/api.py
api/src/pcapi/core/offerers/repository.py
api/tests/core/external/external_pro_test.py
api/tests/routes/native/v1/bookings_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36124

(PC-36124)[API] fix: pro attribute HAS_COLLECTIVE_OFFERS

---

api/pyproject.toml
api/src/pcapi/connectors/api_adresse.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/repository.py
api/src/pcapi/core/geography/api.py
api/tests/core/finance/test_api_legacy.py
api/tests/routes/native/v1/reaction_test.py

(BSR)[API] style: activate ruff rule E731 (lambda-assignment)

---

api/src/pcapi/core/offers/schemas.py
api/tests/routes/pro/patch_draft_offer_test.py
api/tests/routes/pro/post_offer_test.py
pro/src/components/Markdown/Markdown.tsx
pro/src/components/Markdown/__specs__/Markdown.spec.tsx
pro/src/components/OfferAppPreview/OfferAppPreview.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35958

(PC-35958)[PRO] feat: update description max length in pro interface

---

api/src/pcapi/local_providers/allocine/allocine_stocks.py
api/tests/local_providers/allocine_stocks_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35613

(PC-35613) use product mediations in cine synchro allocine

---

api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33298

(PC-35889)[API] feat: create product mediations in boost sync

---

api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py
api/tests/local_providers/cinema_providers/cgr/cgr_stocks_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-33298

(PC-35890)[API] feat: create product mediations in cgr sync

---

api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35891

(PC-35891)[API] feat: create product mediations in CDS sync

---

.github/workflows/dev_on_schedule_deploy_main_and_pro.yml

(BSR)[API] fix: do not fetch all git history (30s to ~2s)

---

pro/src/app/App/App.tsx

- Enlever les paramètres de l'url pour éviter des redirections

(BSR)[PRO] fix: Remove params after settings offerer from url.

---

api/src/pcapi/core/finance/backend/cegid.py
api/src/pcapi/core/finance/utils.py
api/tests/core/finance/test_backends.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35713

(PC-35713)[API] feat: remove vendor location queries in cegid backend

---

.github/workflows/dev_on_workflow_tests_pro_e2e.yml

(BSR)[PRO] ci: Trying to move e2e suite to fixe the issues on master.

---

pro/src/components/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.module.scss
pro/src/pages/Collaborators/Collaborators.module.scss
pro/src/pages/Collaborators/Collaborators.tsx
pro/src/ui-kit/form/shared/FieldLayout/FieldLayoutCharacterCount/FieldLayoutCharacterCount.module.scss
pro/src/ui-kit/formV2/TextInput/TextInput.module.scss
pro/src/ui-kit/formV2/TextInput/TextInput.stories.tsx
pro/src/ui-kit/formV2/TextInput/TextInput.tsx

Ticket Jira (ou description si BSR) : Réaligner Input Extension en laissant les erreurs en dessous de l'input

(BSR)[PRO] feat: add grit text input

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250507T125212_f7a60b79eabd_fill_street_address_with_city_if_null.py
api/src/pcapi/alembic/versions/20250507T153958_1ad10f56b216_add_not_null_constraint_on_address_street_step_1_of_4.py
api/src/pcapi/alembic/versions/20250507T153958_2957c0896d6d_add_not_null_constraint_on_address_street_step_3_of_4.py
api/src/pcapi/alembic/versions/20250507T153958_9586c72d6f2c_add_not_null_constraint_on_address_street_step_2_of_4.py
api/src/pcapi/alembic/versions/20250507T153958_ad5725a20f5e_add_not_null_constraint_on_address_street_step_4_of_4.py
api/src/pcapi/connectors/api_adresse.py
api/src/pcapi/core/geography/models.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/factories.py
api/tests/core/geography/test_repository.py
api/tests/core/offerers/test_models.py
api/tests/core/offerers/test_repository.py
api/tests/core/offers/test_models.py
api/tests/routes/backoffice/autocomplete_test.py
api/tests/routes/pro/get_offerer_addresses_test.py
api/tests/routes/pro/patch_offer_test.py
api/tests/routes/pro/post_save_new_onboarding_data_test.py
api/tests/routes/public/individual_offers/v1/get_search_addresses_test.py
api/tests/routes/public/individual_offers/v1/post_address_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35653

(PC-35653)[API] feat: make street field mandatory in address

---

.github/workflows/dev_on_pull_request_workflow.yml
.github/workflows/dev_on_workflow_tests_api.yml
.github/workflows/dev_on_workflow_tests_pro.yml
.github/workflows/dev_on_workflow_tests_pro_e2e.yml

(BSR)[API] chore: bump ubuntu to 24.04 (latest version)

---

.github/workflows/dev_on_workflow_configure_live_channel_pro_generic.yml

(BSR)[PRO] ci: fix issue with firebase deploy.

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36161

(PC-36161)[API] fix: remove call to lock_stocks_for_venue

---

api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
api/src/pcapi/routes/backoffice/finance/forms.py
api/src/pcapi/routes/backoffice/templates/finance/incidents/list.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35839
avant:
apres:

Pc 35839 rpa incident list new UI

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/backoffice/templates/pro/search.html
api/tests/routes/backoffice/pro_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36164

(PC-36164)[BO] feat: add search bank account by id in BO

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py
api/tests/scripts/move_offer/move_batch_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36030

(PC-36030)[API] fix: When move offer, move priceCategoryLabel only when does not exist on destination venue.

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250502T084020_b82597ef665d_add_product_columns_for_counts.py
api/src/pcapi/core/chronicles/api.py
api/src/pcapi/core/chronicles/models.py
api/src/pcapi/core/history/api.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/reactions/models.py
api/src/pcapi/core/search/__init__.py
api/tests/core/chronicles/test_models.py
api/tests/core/offers/test_models.py
api/tests/core/reactions/test_models.py
api/tests/routes/native/v1/reaction_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35943

PC-35943 add product columns for counts

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py

Ajout de logs pour suivre la régul'

(BSR)[API] chore: add log on venue regularisation

---

api/src/pcapi/core/operations/models.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/operations/forms.py
api/src/pcapi/routes/backoffice/templates/admin/subcategories.html
api/src/pcapi/routes/backoffice/templates/components/presentation/list.html
api/src/pcapi/routes/backoffice/templates/layouts/details.html
api/src/pcapi/routes/backoffice/templates/layouts/list.html
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/tests/routes/backoffice/operations_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36062
avant:
apres:

(PC-36062)[BO] feat: rework special operation details page

---

.github/workflows/dev_on_workflow_deploy.yml

Pour faire suite à [ce commit](https://github.com/pass-culture/pass-culture-main/commit/9d9908091018ae5266496da9d33ba1254c1ffdcd)

(BSR)[API] ci: fix algolia workflow flag

---

api/documentation/src/pages/change-logs.md
api/documentation/static/openapi.json
api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/routes/public/collective/serialization/offers.py
api/src/pcapi/routes/public/documentation_constants/descriptions.py
api/src/pcapi/routes/public/documentation_constants/fields.py
api/src/pcapi/routes/public/individual_offers/v1/events.py
api/src/pcapi/routes/public/individual_offers/v1/products.py
api/src/pcapi/routes/public/individual_offers/v1/utils.py
api/src/pcapi/routes/public/utils.py
api/tests/routes/public/collective/endpoints/get_collective_offer_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
api/tests/routes/public/individual_offers/v1/post_event_test.py
api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
api/tests/routes/public/individual_offers/v1/post_product_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35798

(PC-35798)[API] fix: Add location to POST /collective/offers

---

api/src/pcapi/core/finance/backend/cegid.py

Ticket Jira (ou description si BSR) : pas utile

(BSR)[API] feat: remove time to sleep in cegid

---

api/src/pcapi/routes/public/individual_offers/v1/products.py
api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36117

(PC-36117)[API] fix: fix offer address update in `post_product_by_ean` endpoint

---

api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/templates/accounts/get/details/personal_information_registration.html
api/src/pcapi/static/backoffice/scss/pc/addons/_personal_information_registration_steps.scss

Avant : 
Après : 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35725

(PC-35725)[BO] feat: refresh user account tunnel's colors

---

api/src/pcapi/routes/native/v1/artists.py
api/src/pcapi/routes/native/v1/serialization/artists.py
api/tests/routes/native/openapi_test.py
api/tests/routes/native/v1/artists_tests.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35998

(PC-35998)[API] feat: add description and image to artist route

---

api/README.md
api/src/pcapi/core/providers/models.py
api/src/pcapi/routes/backoffice/providers/blueprint.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
api/src/pcapi/settings.py
api/tests/core/bookings/test_api.py

Ticket Jira (ou description si BSR) : Suppression des références à l'API Charlie pour améliorer la clarté du code.

(BSR)[API] feat: replace last mentions to charlie API with external ticketing API

---

api/src/pcapi/core/offerers/exceptions.py
api/src/pcapi/core/offerers/repository.py
api/src/pcapi/routes/native/v1/offerers.py
api/src/pcapi/routes/pro/offerers.py
api/tests/core/offerers/test_repository.py

Ticket Jira (ou description si BSR) : Supprime une exception non nécessaire

(BSR)[API] feat: remove `TooManyHeadlineOffersForOfferer` exception

---

api/src/pcapi/routes/serialization/bookings_recap_serialize.py
api/tests/routes/pro/get_all_bookings_test.py
pro/src/apiClient/v1/models/BookingRecapResponseStockModel.ts
pro/src/commons/utils/factories/individualApiFactories.ts

Ticket Jira (ou description si BSR) : Il ne sert plus

(BSR)[API] chore: remove unused stock identifier

---

api/src/pcapi/core/mails/transactional/__init__.py
api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
api/src/pcapi/core/mails/transactional/users/update_request_user_account_not_found.py
api/src/pcapi/core/users/ds.py
api/tests/core/users/test_ds.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-34373

(PC-34373)[API] feat: update request mail if user not found

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/offers/api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36159

(PC-36159)[API] feat: When moving offers in regul command, use update() for Booking 

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/script.py.mako
api/src/pcapi/alembic/versions/20250519T082552_c2065c857c35_add_end_import_date_column_to_special_event.py
api/src/pcapi/alembic/versions/20250519T105828_08346141b0cc_add_not_null_constraint_on_special_event_endImportDate_step_3_of_4.py
api/src/pcapi/alembic/versions/20250519T105828_4a9101c5aa05_add_not_null_constraint_on_special_event_endImportDate_step_1_of_4.py
api/src/pcapi/alembic/versions/20250519T105828_54e6167683c9_add_not_null_constraint_on_special_event_endImportDate_step_4_of_4.py
api/src/pcapi/alembic/versions/20250519T105828_cb4aae091f35_add_not_null_constraint_on_special_event_endImportDate_step_2_of_4.py
api/src/pcapi/core/operations/api.py
api/src/pcapi/core/operations/commands.py
api/src/pcapi/core/operations/factories.py
api/src/pcapi/core/operations/models.py
api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/operations/forms.py
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/tests/core/operations/test_api.py
api/tests/routes/backoffice/operations_test.py

permettre de choisir la date de fin d'import des opé spé
permettre de lier une opé spé avec une venue (partenaire culturel)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36166

PC-36166 - permettre la personalisation des opé spé

---

api/src/pcapi/core/fraud/api.py
api/src/pcapi/core/subscription/ubble/api.py
api/src/pcapi/core/users/api.py
api/src/pcapi/routes/backoffice/dev/blueprint.py
api/src/pcapi/routes/backoffice/dev/forms.py
api/tests/core/subscription/ubble/end_to_end/test_subscription_via_ubble.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35934

(PC-35934)[BO] fix: use most recent id number in manual review

---

api/src/pcapi/core/finance/commands.py

Ticket Jira (ou description si BSR) : Elle ne sert plus

(BSR)[API] chore: remove unused recredit command

---

api/src/pcapi/routes/backoffice/templates/components/presentation/list.html
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/tests/routes/backoffice/operations_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36224

(PC-36224)[BO] feat: tweak special event details ui

---

api/documentation/src/pages/change-logs.md
api/documentation/static/openapi.json
api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/routes/public/collective/endpoints/offers.py
api/src/pcapi/routes/public/collective/serialization/offers.py
api/src/pcapi/routes/public/documentation_constants/descriptions.py
api/tests/core/educational/test_api.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36173

(PC-36173)[API] fix: Add location to PATCH

---

api/tests/routes/backoffice/operations_test.py

(BSR)[BO] fix: tests

---

api/src/pcapi/core/offers/api.py

Ecrire chaque identifiant d'offre supprimée dans un log pour le suivi (notamment côté data).
Au passage, la variable `offer_ids` est renommée en `query` pour plus de clareté (au moment où elle est définie, elle ne contient pas d'identifiant puisqu'il s'agit d'un générateur). Et le log final contient maintenant le nombre d'offres supprimées.

(BSR)[API] feat: delete old offers command: log deleted rows

---

api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py

Ticket Jira (ou description si BSR) : On peut facilement tagguer une offre en testing, donc pas besoin de ça dans la sandbox

(BSR)[BO] chore: remove useless fraudulent booking in sandbox

---

api/src/pcapi/routes/backoffice/bookings/forms.py
api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
api/tests/routes/backoffice/individual_bookings_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36188

(PC-36188)[BO] feat: filter free indiv bookings

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py

Ticket Jira (ou description si BSR) : 32, c'est trop long, pour une vérif fonctionnelle une fois de temps en temps

(BSR)[API] feat: limit number of generated invoices in sandbox

---

pro/src/components/IndividualOffer/PriceCategoriesScreen/form/constants.ts

Ticket Jira : https://passculture.atlassian.net/browse/PC-36162

(PC-36162)[PRO] feat: update PRICE_CATEGORY_MAX_LENGTH

---

api/src/pcapi/routes/backoffice/templates/offer/list.html
api/tests/routes/backoffice/conftest.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36231

(PC-36231)[BO] feat: show fraud rules for homologation team

---

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
api/src/pcapi/core/mails/transactional/users/update_request_identity_theft.py
api/src/pcapi/core/users/ds.py
api/src/pcapi/core/users/models.py
api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py
api/src/pcapi/routes/backoffice/templates/accounts/update_requests_list.html
api/tests/routes/backoffice/update_request_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35004

(PC-35004)[BO] feat: refuse DS user request because of identity theft

---

api/src/pcapi/static/backoffice/js/addons/pc-postal-address-autocomplete.js
pro/src/apiClient/adresse/apiAdresse.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36208

(PC-36208)[PRO] feat: Homogenize address autocompletion to street and housenumber only

---

pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35080
Modifier le composant TimePicker par un TextInput car on ne pouvait pas mettre une durée supérieur à 23h59

(PC-35080)[PRO] feat: change input for duration of the event

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36217

(PC-36217)[API] feat: encapsulate move offer in try except and log into csv output

---

api/src/pcapi/core/finance/backend/cegid.py
api/tests/core/finance/test_backends.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36251

(PC-36251)[API] feat: update cegid url

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py
api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py
api/src/pcapi/routes/backoffice/chronicles/blueprint.py
api/src/pcapi/routes/backoffice/criteria/blueprint.py
api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py
api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/pro/blueprint.py
api/src/pcapi/routes/backoffice/search_utils.py
api/tests/routes/backoffice/search_utils_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35927

(PC-35927)[BO] refactor:reomplement paginate as a step to remove flask_sqlalchemy

---

api/src/pcapi/models/pc_object.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36260

(PC-36260)[API] feat: remove flask-sqlalchemy from PcObject

---

api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/operations/forms.py
api/src/pcapi/routes/backoffice/templates/offer/details.html
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/tests/routes/backoffice/operations_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36230

(PC-36230)[BO] feat: permit to edit event dates

---

api/src/pcapi/models/pc_object.py

Ticket Jira (ou description si BSR) : C'est long et pas très utile de remplacer `get` partout

(BSR)[API] feat: custom query.get in PcObject

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py
api/tests/scripts/move_offer/move_batch_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36270

(PC-36270)[API] fix: Use list instead of iterable when move idividual offers in regularisation command

---

api/src/pcapi/core/offerers/api.py
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36262

(PC-36262)[API] feat: set offers as PENDING their offerer is validated with manual review

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_ean.py
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36099

(PC-36099)[API] fix: remove Product idAtProviders from sandbox

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py

Tis log was using nullable parameters, not allowed in this one. Force using int
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36321

(PC-36321)[API] fix: Fix first log in move_batch_offer commande.

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36330

(PC-36330)[API] feat: Higher statement timeout for move_batch_offer

---

api/src/pcapi/models/feature.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36172

(PC-36172)[API] feat: add `WIP_REFACTO_FUTURE_OFFER` ff

---

api/src/pcapi/core/permissions/models.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36336

(PC-36336)[BO] feat: add new BO role for communication team

---

api/src/pcapi/repository/session_management.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36343
On capturait une erreur mais ce n'est pas cette `InternalError` qui se produit.
Par sécurité, je garde les deux.

(PC-36343)[API] fix: capture the InternalError which occurs in production

---

.github/pull_request_template.md

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36294)

(PC-36294)[PRO] chore: update github template

---

api/src/pcapi/routes/backoffice/finance/validation.py
api/tests/routes/backoffice/finance_test.py

Fix des tests flaky des routes finance du BO

(BSR) fix: finance bo flaky test

---

api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/validation.html
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36401
Complément à la PR #17876 : j'avais oublié la validation par lots.

(PC-36401)[BO] feat: Show information about pending bank account applications when several offerers are validated (batch)

---

.cz.toml
.git-commit-message-template
.github/workflows/dev_on_workflow_build_and_tag.yml

[Ticket Notion
](https://www.notion.so/passcultureapp/Github-Auth-Delete-les-PAT-obsol-tes-1faad4e0ff988041ad89e9eacaf13c63?source=copy_link)

(IC-219)[API] ci: delete push token

---

api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/operations/forms.py
api/src/pcapi/routes/backoffice/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html
api/src/pcapi/routes/backoffice/templates/components/forms/tom_select_field.html
api/src/pcapi/routes/backoffice/templates/components/presentation/list.html
api/src/pcapi/routes/backoffice/templates/finance/incidents/list.html
api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html
api/src/pcapi/routes/backoffice/templates/offerer/validation.html
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/src/pcapi/routes/backoffice/templates/venue/list.html
api/tests/routes/backoffice/operations_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36304
avant
apres

(PC-36304)[BO] feat: permit to modify venue for a special event

---

.github/workflows/dev_on_dispatch_deploy_pullrequests.yml

[Ticket Jira](https://www.notion.so/passcultureapp/Github-Auth-Delete-les-PAT-obsol-tes-1faad4e0ff988041ad89e9eacaf13c63?source=copy_link)

(IC-219)[API] ci: remove pat from pull request deployments

---

api/src/pcapi/scripts/move_offer/move_batch_offer.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36281

(PC-36281)[API] feat: Do not reindex destination venue in move batch offer when become permanent

---

api/documentation/docs/mandatory-steps/request-a-provider-account.md
api/documentation/src/components/HomepageFeatures/index.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36485)

(PC-36485)[API] fix: update typeform URL

---

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
api/src/pcapi/routes/backoffice/offers/blueprint.py
api/tests/routes/backoffice/collective_offers_test.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36487

(PC-36487)[BO] fix: timeout when listing offers

---

api/src/pcapi/core/search/__init__.py
api/src/pcapi/core/search/backends/serialization.py
api/tests/core/search/test_serialize_algolia.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-35952)

(PC-35952)[API] feat: adapt Algolia offer indexation to include product counts

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/commands.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_commands.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35945

PC-35945 add cron to check product counts consistency

---

pro/src/commons/hooks/__specs__/useAccessibilityOptions.spec.tsx
pro/src/components/OpenToPublicToggle/OpenToPublicToggle.spec.tsx
pro/src/components/OpenToPublicToggle/OpenToPublicToggle.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPage.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.tsx
pro/src/pages/VenueEdition/AccessibilityForm/AccessibilityForm.spec.tsx
pro/src/pages/VenueEdition/AccessibilityForm/AccessibilityForm.tsx
pro/src/pages/VenueEdition/OpeningHoursForm/HourLine.tsx
pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.tsx
pro/src/pages/VenueEdition/OpeningHoursForm/__specs__/OpeningHoursForm.spec.tsx
pro/src/pages/VenueEdition/VenueEditionForm.tsx
pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx
pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
pro/src/pages/VenueEdition/__specs__/VenueEditionHeader.spec.tsx
pro/src/pages/VenueSettings/VenueSettingsForm.tsx
pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
pro/src/ui-kit/formV2/TimePicker/TimePicker.module.scss
pro/src/ui-kit/formV2/TimePicker/TimePicker.tsx

BSR cette PR à pour but de migrer le formulaire d'édition de la page partenaire à l'identique

(BSR)[PRO] chore: remove formik

---

.github/workflows/dev_on_pull_request_workflow.yml
.github/workflows/dev_on_workflow_configure_live_channel_pro_generic.yml
.github/workflows/dev_on_workflow_dependabot_auto_merge.yml
.github/workflows/dev_on_workflow_deploy_pro_pr_version_generic.yml
.github/workflows/dev_on_workflow_tests_pro.yml

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36522)

(PC-36522)[API] fix: use github login for identification

---

pro/src/components/ImageDragAndDrop/ImageDragAndDrop.module.scss
pro/src/styles/components/Cells.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35983

(PC-35983)[PRO] chore: cleanup dead css code

---

pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/PricingPointDialog.tsx

BSR migration to react-hook-form

(BSR)[PRO] refactor: migrate to react hook form

---

api/src/pcapi/core/offers/offer_metadata.py
api/src/pcapi/core/providers/constants.py
api/src/pcapi/core/providers/titelive_book_search.py
api/src/pcapi/core/search/backends/serialization.py
api/tests/core/offers/test_offer_metadata.py
api/tests/core/search/test_serialize_algolia.py
api/tests/providers/titelive_search_test.py
api/tests/routes/native/v1/offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36096)

(PC-36096)[API] fix: change 'POCHE' to 'Poche'

---

pro/src/commons/store/adageFilter/reducer.ts
pro/src/components/OpenToPublicToggle/OpenToPublicToggle.spec.tsx
pro/src/design-system/RadioButton/RadioButton.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/__specs__/FiltersTags.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSuggestions/OffersSuggestions.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/utils.spec.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts
pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35249
Sous FF (**WIP_ENABLE_OFFER_ADDRESS_COLLECTIVE**) => Dans le cadre de OA, on doit adapter la partie adage c'est pourquoi on ajoute un locationType
Vérifier le bon fonctionnement de : 
La page de recherche (ordre d’affichage)
Les suggestions
Le filtre “Type d’intervention”

(PC-35249)[PRO] feat: location type adage oa

---

pro/src/components/Footer/Footer.module.scss

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36523)
Example:
Before | After
:---: | :---:

(PC-36523)[PRO] fix: handle wrapping footer link

---

pro/src/commons/utils/factories/adageFactories.ts
pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx
pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/__specs__/OfferCard.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCardTags/AdageOfferListCardTags.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/utils/__specs__/getOfferTags.spec.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/utils/getOfferTags.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-34952)
Sur la page de recherche et la découverte, on souhaite adapter l'affichage des tags pour qu'ils utilisent les nouvelles valeurs remontées par le back

(PC-34952)[PRO] feat: adapt tag for oa adage

---

api/src/pcapi/core/users/ds.py
api/src/pcapi/routes/backoffice/templates/accounts/modal/accept_update_request.html
api/tests/core/users/ds_fixtures.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36546

(PC-36546)[API] fix: new last name missing in production from DS update request

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/core/providers/titelive_book_search.py
api/src/pcapi/routes/backoffice/__init__.py
api/src/pcapi/routes/backoffice/docs/JSDOC.md
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py
api/src/pcapi/routes/backoffice/offers/serializer.py
api/src/pcapi/routes/backoffice/products/blueprint.py
api/src/pcapi/routes/backoffice/products/forms.py
api/src/pcapi/routes/backoffice/static_utils.py
api/src/pcapi/routes/backoffice/templates/collective_offer/details.html
api/src/pcapi/routes/backoffice/templates/collective_offer_template/details.html
api/src/pcapi/routes/backoffice/templates/components/description.html
api/src/pcapi/routes/backoffice/templates/layouts/base.html
api/src/pcapi/routes/backoffice/templates/layouts/details.html
api/src/pcapi/routes/backoffice/templates/offer/details.html
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/src/pcapi/routes/backoffice/templates/products/details.html
api/src/pcapi/routes/backoffice/templates/products/titelive_information.html
api/src/pcapi/routes/backoffice/templates/products/titelive_synchro_modal.html
api/src/pcapi/routes/backoffice/templates/titelive/search_result.html
api/src/pcapi/routes/backoffice/titelive/blueprint.py
api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_products.py
api/src/pcapi/static/backoffice/js/addons/pc-table-multi-select.js
api/src/pcapi/static/backoffice/js/addons/pc-table-paginator.js
api/tests/routes/backoffice/helpers/html_parser.py
api/tests/routes/backoffice/products_test.py
api/tests/routes/backoffice/titelive_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-36079

(PC-36079)[BO] feat: Product details page

---

pro/src/commons/context/SignupJourneyContext/SignupJourneyContext.tsx
pro/src/components/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
pro/src/components/SignupJourneyForm/Activity/Activity.tsx
pro/src/components/SignupJourneyForm/Activity/ActivityForm.tsx
pro/src/components/SignupJourneyForm/Activity/__specs__/ActivityForm.spec.tsx
pro/src/components/SignupJourneyForm/Activity/__specs__/ActivityScreen.spec.tsx
pro/src/components/SignupJourneyForm/Activity/constants.ts
pro/src/components/SignupJourneyForm/Activity/validationSchema.tsx

BSR migrate formik to react hook form

(BSR)[PRO] refacto: activity form react hook form migration

---

api/src/pcapi/core/educational/api/stock.py
api/src/pcapi/core/educational/validation.py
api/src/pcapi/core/offers/validation.py
api/src/pcapi/routes/pro/collective_stocks.py
api/tests/core/educational/test_api.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_validation.py
api/tests/routes/pro/delete_stock_test.py
api/tests/routes/pro/patch_bulk_update_event_stocks_test.py
api/tests/routes/pro/patch_offer_test.py
api/tests/routes/pro/post_collective_stock_test.py
api/tests/routes/pro/post_price_categories_test.py

Now, it raises an error only if the validation status is `REJECTED`

(PC-36455)[API] feat: update `check_validation_status`

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/pro/get_offer_test.py
api/tests/routes/pro/get_offers_test.py
pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
pro/src/apiClient/v1/models/GetIndividualOfferWithAddressResponseModel.ts
pro/src/apiClient/v1/models/ListOffersOfferResponseModel.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36549)

(PC-36549)[API] feat: add `bookingAllowedDatetime`, `publicationDatetime` et `bookingsCount` in offers endpoints

---

pro/src/components/OpenToPublicToggle/OpenToPublicToggle.tsx
pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.module.scss
pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36562)

(PC-36562)[PRO] fix: restore isOpenToPublic radio button feature in onboarding form

---

api/src/pcapi/routes/public/individual_offers/v1/addresses.py
api/tests/routes/public/individual_offers/v1/get_search_addresses_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36560
Sentry : https://pass-culture.sentry.io/issues/33286939/?environment=production
9200+ alertes en un mois et demi.

(PC-36560)[API] fix: crash when creating address with invalid format on public API

---

api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/pro/venues.py
api/src/pcapi/routes/serialization/finance_serialize.py
api/src/pcapi/routes/serialization/venues_serialize.py
api/tests/routes/pro/get_venue_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36566
Sentry : https://pass-culture.sentry.io/issues/43459591/?environment=production

(PC-36566)[PRO] perf: fix N+1 query in GET /venues/<id>

---

api/src/pcapi/connectors/dms/api.py
api/tests/routes/backoffice/update_request_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36583
Sentry : https://pass-culture.sentry.io/issues/46900841/

(PC-36583)[BO] fix: crash when asking for correction and DS is unavailable

---

api/src/pcapi/core/offers/factories.py
api/tests/routes/pro/get_offers_test.py

(PC-36588)[API] feat: set `publicationDatetime` according to `isActive` in `OfferFactory._create`

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36582
Sentry : https://pass-culture.sentry.io/issues/42367349/?project=4508776981069904
399k événements dans Sentry

(PC-36582)[BO] fix: IntegrityError when old unbookable unbooked offers are cleaned

---

api/src/pcapi/core/fraud/repository.py
api/tests/routes/native/v1/subscription_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36593
Sentry : https://pass-culture.sentry.io/issues/33134713/events/e9504bd6c91748298f60cebe5c8c344c/ (résolution partielle)

(PC-36593)[API] fix: oldest profile was retrieved in get_latest_completed_profile_check

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/reference/models.py
api/src/pcapi/routes/backoffice/products/blueprint.py
api/tests/core/offers/test_api.py

remplacer les dernier `model.query` par `db.session.query(model)`

(BSR)[API] fix: remove forgotten model.query and use db.session.query.(model) instead

---

api/src/pcapi/core/subscription/api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36596
Sentry : https://pass-culture.sentry.io/issues/46900583/?environment=production

(PC-36596)[API] fix: PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush

---

api/src/pcapi/core/fraud/models.py
api/tests/routes/native/v1/subscription_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36601
Sentry : https://pass-culture.sentry.io/issues/33134713/?environment=production
En complément de https://github.com/pass-culture/pass-culture-main/pull/18066

(PC-36601)[API] fix: Invalid profile data for user: 1 validation error for ProfileContent

---

api/src/pcapi/static/backoffice/js/addons/pc-batch-action-form.js

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36614)

(PC-36614)[BO] fix: multi-select counter displaying

---

api/src/pcapi/core/offers/factories.py
api/tests/core/offers/test_models.py

(BSR)[API] fix: update `OfferFactory._create`

---

pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffersScreen/TemplateOffersSearchFilters/TemplateOffersSearchFilters.tsx
pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffers.spec.tsx
pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffersQueryParams.spec.tsx

Commenter le code en rapport avec formik (liée au filtre des statuts), il faudra utiliser le nouveau composant SelectAutocomplete qui n'utilise plus formik.

(BSR)[PRO] comment status filter code

---

api/src/pcapi/core/offers/models.py
api/tests/core/offers/test_models.py
api/tests/routes/native/v1/offerers_test.py
api/tests/routes/pro/get_offerer_headline_offer_test.py
api/tests/routes/pro/get_offerer_test.py

Pour permettre de lancer les tests BO en local.

(PC-36589)[API] fix: remove FF in `offer.status` expression

---

api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/pro/patch_publish_offer_test.py

Fix de cette Issue JIRA : https://pass-culture.sentry.io/issues/47341462/?referrer=slack&notification_uuid=8aa96f13-289c-42f6-ae4a-d84401346964&environment=testing&alert_rule_id=139263&alert_type=issue

(BSR)[API] fix:  update `PatchOfferPublishBodyModel` to enforce datetime formatting

---

api/src/pcapi/routes/backoffice/non_payment_notices/forms.py
api/src/pcapi/routes/backoffice/non_payment_notices/non_payment_notices_blueprint.py
api/src/pcapi/routes/backoffice/templates/non_payment_notices/list.html
api/tests/routes/backoffice/non_payment_notices_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36314)

Pc 36314 add filters to non payment notice table

---

pro/cypress/e2e/createIndividualOffer.cy.ts
pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss
pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
pro/src/components/IndividualOffer/StocksEventCreation/__specs__/RecurrenceForm.spec.tsx
pro/src/components/IndividualOffer/StocksEventCreation/form/__specs__/onSubmit.spec.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/__specs__/validationSchema.spec.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/computeInitialValues.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/constants.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/onSubmit.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/types.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/validationSchema.ts

Migration rhf du fromulaire de récurrence. Pour y arriver : créer une offre indiv de type événement, dans la page Date et caacité, le formulaire se trouve dans le drawer qui s'ouvre quand on ajoute des dates.

(BSR)[PRO] feat: Migration rhf RecurrenceForm

---

api/src/pcapi/core/users/models.py
api/tests/core/subscription/test_api.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36647)

(PC-36647)[API] fix: upgrade from free beneficiary to 17 18 beneficiary

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/offers/forms.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36655

(PC-36655)[BO] feat: Enable to keep address when moving event offer

---

api/src/pcapi/core/finance/repository.py
api/tests/routes/pro/get_reimbursements_csv_by_invoices_test.py
api/tests/routes/pro/get_reimbursements_csv_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-35726

(PC-35726) refactor: remove_venue_location_fields_from_finance_csvs

---

api/src/pcapi/core/search/backends/algolia.py
api/src/pcapi/core/search/backends/testing.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36660)

(PC-36660)[API] feat: migrate Algolia's artist index to new style

---

pro/src/pages/CollectiveOffer/CollectiveOfferPreview/CollectiveOfferPreviewCreation/components/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreationScreen.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferPreview/CollectiveOfferPreviewEdition/CollectiveOfferPreviewEdition.module.scss
pro/src/pages/CollectiveOffer/CollectiveOfferPreview/CollectiveOfferPreviewEdition/CollectiveOfferPreviewEdition.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferPreview/components/PreviewHeader.module.scss
pro/src/pages/CollectiveOffer/CollectiveOfferPreview/components/PreviewHeader.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferPreview/components/PreviewHeader.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36466)

(PC-36466)[PRO] feat: show not visible preview label above adage preview for some statuses

---

api/src/pcapi/connectors/titelive.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/backoffice/menu.py
api/src/pcapi/routes/backoffice/products/blueprint.py
api/src/pcapi/routes/backoffice/products/forms.py
api/src/pcapi/routes/backoffice/templates/products/search.html
api/src/pcapi/routes/backoffice/templates/products/search_product_result.html
api/src/pcapi/routes/backoffice/titelive/blueprint.py
api/tests/routes/backoffice/search_product_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36082)

(PC-36082)[BO] feat: Product search page

---

.github/PULL_REQUEST_TEMPLATE/template_back.md

(BSR)[API] chore: turn item into a checkbox

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/pro/stocks.py

Décorateur atomic sur la route pro delete_stock
https://passculture.atlassian.net/browse/PC-36663

(PC-36663)[API] feat: add atomic in delete stock route

---

api/src/pcapi/routes/backoffice/products/blueprint.py
api/tests/routes/backoffice/products_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36719)
Erreur Sentry: https://pass-culture.sentry.io/issues/47844787/?project=4508776981069904

(PC-36719)[BO] fix: fix crash on product details page

---

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36664

(PC-36664)[BO] feat: show providers in managed venues

---

api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/non_payment_notices/non_payment_notices_blueprint.py
api/src/pcapi/routes/backoffice/templates/components/history/actions.html
api/tests/routes/backoffice/non_payment_notices_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36651

(PC-36651)[BO] feat: action stored when creating non-payment notice

---

pro/src/pages/IndividualOffer/IndividualOfferDetails/commons/utils.ts
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsEanSearch/DetailsEanSearch.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/ImageUploaderOffer/ImageUploaderOffer.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/EanSearchCallout/EanSearchCallout.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/EanSearchCallout/EanSearchCallout.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36127)

(PC-36127)[PRO] fix: make sure image drag & drop is disabled when offer (draft or not) is product based

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormNotifications/EmailInputRow/__specs__/EmailInputRow.spec.tsx

BSR remove formik from offers test and input row test

(BSR)[PRO] refacto: remove formik from offers tests

---

api/src/pcapi/core/offers/tasks.py
api/src/pcapi/routes/public/individual_offers/v1/products.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-35493)
Migration du job `create_or_update_ean_offers` dans le fichier offers/api en préparation de la création de la task celery

(PC-35943)[API] chore: extract ean task to offers api

---

api/src/pcapi/models/feature.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36713)
- Simple création du FF `WIP_2025_AUTOLOGIN`
- Mise à jour des wordings dans les descriptifs pour marquer la distinction entre `WIP_2025_AUTOLOGIN` et `WIP_2025_SIGN_UP`

(PC-36713)[PRO] feat: Création du FF WIP_2025_AUTOLOGIN

---

pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/__specs__/validationSchema.spec.ts
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/validationSchema.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36802)
Ma localisation est en adresse précise, édition manuelle
Je change la localisation pour “en établissement” ou “à déterminer”
J’enregistre → il ne se passe rien (rien dans la console ni appel back)
-> ce que l'on veut : Je peux faire les modifications de mon choix et valider le formulaire

(PC-36802)[PRO] fix: update loc oa

---

pro/src/components/BookableOfferSummary/BookableOfferSummary.module.scss
pro/src/components/BookableOfferSummary/BookableOfferSummary.spec.tsx
pro/src/components/BookableOfferSummary/BookableOfferSummary.tsx
pro/src/components/BookableOfferSummary/DetailItem/DetailItem.module.scss
pro/src/components/BookableOfferSummary/DetailItem/DetailItem.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.spec.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36460)
à tester sous ff : WIP_ENABLE_NEW_COLLECTIVE_OFFER_DETAIL_PAGE
ajouter le header pour la nouvelle page récap des offre réservables

(PC-36460)[PRO] feat: new header p2

---

api/src/pcapi/scripts/subscription/ubble/update_pending_ubble_applications.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36199)
La requête naïve a dépassé les 5 minutes de temps d'exécution, ce qui amène à un timeout en base de donnée. Pour remédier à ce problème, une pagination a été implémentée.

(PC-36199)[API] refactor: use pagination for ubble recovery cron

---

api/src/pcapi/core/offerers/api.py
api/tests/core/offerers/test_api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-35183
L'erreur :
```
ERROR:pcapi.routes.backoffice.venues.blueprint:IntegrityError when updating venue: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_unique_offerer_address_per_label"
DETAIL:  Key ("offererId", "addressId", label)=(3, 95, Librairie des GTls) already exists.
```

(PC-35183)[API] fix: IntegrityError when switching twice between two addresses

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-35772)

(PC-35772) prise en compte du soft deleted dans la finance

---

api/documentation/docs/tutorials/create-an-event-linked-to-an-external-ticketing-systems.md
api/documentation/docs/understanding-our-api/managing-bookings/connection-with-ticketing-system.md
api/documentation/docs/understanding-our-api/managing-bookings/countermarks-management.md
api/documentation/docs/understanding-our-api/resources/collective-offers.md
api/documentation/docs/understanding-our-api/resources/individual-offers.md
api/documentation/package-lock.json
api/documentation/package.json
api/documentation/src/pages/change-logs.md

- bump docusaurus to fix issues [found by dependabot here](https://github.com/pass-culture/pass-culture-main/security/dependabot?q=is%3Aopen+manifest%3Aapi%2Fdocumentation%2Fpackage-lock.json)
- Fix broken anchors found by docusaurus

bump docusaurus

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/core/bookings/test_api_race_condition.py
api/tests/core/offers/test_models.py
api/tests/routes/pro/get_offer_test.py
pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
pro/src/apiClient/v1/models/GetIndividualOfferWithAddressResponseModel.ts
pro/src/commons/utils/factories/individualApiFactories.ts
pro/src/components/IndividualOffer/IndividualOfferLayout/__specs__/IndivualOfferLayout.spec.tsx
pro/src/components/IndividualOffer/Status/Status.tsx
pro/src/components/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36544)
Le bouton `Mettre en pause / Publier` d'une offre ne devrait pas être visible si l'offre est synchronisée. Sinon, l'itulisateur prendra une 400 à la soumission du formulaire
https://github.com/user-attachments/assets/fc6a814a-df2b-43f1-bc8a-def98c223998

fix display of 'mettre en pause' button

---

pro/src/components/IndividualOffer/IndividualOfferLayout/IndividualOfferLayout.tsx
pro/src/components/IndividualOffer/IndividualOfferLayout/__specs__/IndivualOfferLayout.spec.tsx
pro/src/components/IndividualOffer/Status/Status.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36544)
Prendre en compte le comportement avec le FF `WIP_REFACTO_FUTURE_OFFER` activé

Pc 36544 fix publish display 2

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py

(BSR)[API] feat: add timing for sandbox invoices step

---

api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/commands.py
api/tests/core/users/test_api.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36886)

(PC-36886)[API] feat: manage internal users anonymization

---

api/src/pcapi/routes/backoffice/chronicles/blueprint.py
api/src/pcapi/routes/backoffice/chronicles/forms.py
api/src/pcapi/routes/backoffice/filters.py
api/tests/routes/backoffice/chronicles_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36756)

(PC-36756)[BO] feat: add chronicle filter for club type

---

api/src/pcapi/models/feature.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36370)
- Simply add Feature Flag in backend, no dev impact.
No UI change.

(PC-36370)[PRO] feat: add FF for new offer creation flow

---

api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/educational/exceptions.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/educational/validation.py
api/src/pcapi/routes/adage/v1/prebooking.py
api/src/pcapi/routes/public/collective/endpoints/adage_mock/bookings.py
api/tests/core/educational/test_models.py
api/tests/core/educational/test_validation.py
api/tests/core/finance/test_api.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36782)

Pc 36782 check deposit ratio

---

api/documentation/docs/mandatory-steps/create-test-accounts.md
api/src/pcapi/core/mails/transactional/pro/email_validation.py
api/src/pcapi/core/mails/transactional/pro/offerer_attachment_invitation.py
api/src/pcapi/core/users/api.py
api/src/pcapi/utils/mailing.py
api/tests/core/mails/transactional/pro/email_validation_test.py
api/tests/core/mails/transactional/pro/offerer_attachment_invitation_test.py
pro/cypress/e2e/createAccount.cy.ts
pro/src/app/AppRouter/findCurrentRoute.ts
pro/src/app/AppRouter/routesMap.tsx
pro/src/app/AppRouter/subroutesSignupMap.tsx
pro/src/pages/Accessibility/Declaration.tsx
pro/src/pages/ResetPassword/ResetPassword.spec.tsx
pro/src/pages/ResetPassword/ResetPassword.tsx
pro/src/pages/SignIn/SignIn.spec.tsx
pro/src/pages/SignIn/SigninForm.tsx
pro/src/pages/Signup/SignupContainer/SignupContainer.tsx
pro/src/pages/Signup/SignupContainer/__specs__/SignupContainer.spec.tsx
pro/src/pages/Signup/__specs__/Signup.spec.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36746)
- Changement des urls côté front et back des différentes pages d'inscripton et connexion.

(PC-36746)[PRO] chore: Change url pages.

---

pro/src/components/BookableOfferSummary/BookableOfferSummary.module.scss
pro/src/components/BookableOfferSummary/BookableOfferSummary.tsx
pro/src/components/BookableOfferSummary/BookingOfferSummary.module.scss
pro/src/components/BookableOfferSummary/DetailItem/DetailItem.module.scss
pro/src/components/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingDetails.module.scss
pro/src/components/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingDetails.tsx
pro/src/components/EducationalInstitutionDetails/EducationalInstititutionDetails.tsx
pro/src/components/EducationalInstitutionDetails/EducationalInstitutionDetails.module.scss
pro/src/components/EducationalInstitutionDetails/__specs__/EducationalInstitutionDetails.spec.tsx
pro/src/components/EductionalRedactorDetails/EducationalRedactorDetails.module.scss
pro/src/components/EductionalRedactorDetails/EducationalRedactorDetails.tsx
pro/src/components/EductionalRedactorDetailsForBooking/EducationalRedactorDetailsForBooking.module.scss
pro/src/components/EductionalRedactorDetailsForBooking/EducationalRedactorDetailsForBooking.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36465)
* Need to activate the FF -> `WIP_ENABLE_NEW_COLLECTIVE_OFFER_DETAIL_PAGE`

(PC-36465)[PRO] feat: Extract Institution Details into dedicated component

---

pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx

(BSR)[PRO] fix: formats clear error

---

api/Dockerfile

(BSR) fix: add SSL_CERT_FILE to poetry install in Dockerfile

---

api/.env.development

This config led to confusion. We don't use this service anymore

(BSR)[API] chore: delete unused setting

---

api/src/pcapi/routes/native/v1/serialization/account.py
api/tests/files/native_openapi.json
api/tests/routes/native/v1/account_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36816)

(PC-36816)[API] feat: add beneficiary address edition

---

pro/src/app/App/analytics/firebase.ts

Retour post-merge : https://github.com/pass-culture/pass-culture-main/pull/18307#pullrequestreview-2996201567
Re-throw oublié dans la dernière [PR suivante](https://github.com/pass-culture/pass-culture-main/pull/18307) qui a déjà été mergée.

(BSR)[PRO] fix: Re-throw non-controlled errors

---

pro/src/components/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
pro/src/components/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
pro/src/components/IndividualOffer/StocksEventEdition/__specs__/serializers.spec.ts
pro/src/components/IndividualOffer/StocksEventEdition/serializers.ts
pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx
pro/src/components/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36936)
StocksEventEdition
- écriture de test
- modif du onChange sur le quantityInput
- modif dans le serializer
StocksThings
- changement du onChange
- test

(PC-36936)[PRO] fix: StockEventEdition & StocksThings quantity 

---

pro/src/commons/hooks/__specs__/useRedirectLoggedUser.spec.tsx
pro/src/commons/hooks/useRedirectLoggedUser.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36731)
- Les utilisateurs avec le FF WIP_2025_SIGN_UP ne sont plus redirigés vers la page "Avant de commencer, munissez-vous du numéro de SIRET de votre structure."
- Activer le FF WIP_2025_SIGN_UP
- S'inscrire, valider son mail, se connecter
- Vérifier que je suis bien redirigé vers "/parcours-inscription/structure" au lieu de "/parcours-inscription"

(PC-36731)[PRO] feat: Users with WIP_2025_SIGN_UP redirection change.

---

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
api/src/pcapi/app.py
api/src/pcapi/settings.py

Désactivation du reloader de flask dans les tests E2E

(BSR)[API] fix: disable flask reloader in e2e tests

---

api/src/pcapi/routes/public/collective/endpoints/offers.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36973)

(PC-36973)[API] fix: do not update offer venue when id is the same

---

api/documentation/src/pages/change-logs.md
api/documentation/static/openapi.json
api/src/pcapi/routes/public/documentation_constants/descriptions.py

Indicates it is not yet implemented but it is coming soon
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36887)

(PC-36887)[API] feat: update documentation on `bookingAllowedDatetime`

---

pro/src/pages/IndividualOffer/IndividualOfferDetails/commons/__specs__/utils.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/commons/utils.ts
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/Subcategories/Subcategories.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/Subcategories/Subcategories.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx

BUG : le clear des erreurs ne se fait pas sur la première étape du formulaire
[PC-37017 ](https://passculture.atlassian.net/browse/PC-37017)

(PC-37017)[PRO] fix: clear error categories

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_api_legacy.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37041)

(PC-37041)[API] feat: add free grant to invoices csv

---

api/src/pcapi/routes/backoffice/templates/offer/details.html

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36668)

(PC-36668)[API] feat: add booking link to offer page

---

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/templates/accounts/get/details/bookings.html
api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/individual_bookings_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36925)

(PC-36925)[BO] feat: add withdrawal type to booking lists

---

pro/cypress/e2e/signupJourneyCreateOffererNewSignin.cy.ts
pro/src/app/App/App.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-PRO)
Correction de la redirection vers la bonne url en cas de FF.

(PC-37037)[PRO] fix: Fix redirect on wrong url.

---

pro/src/commons/context/HeadlineOfferContext/HeadlineOfferContext.tsx

(PC-34863)[PRO] feat: mutate GET_OFFERER_HEADLINE_OFFER_QUERY_KEY cache after an upsert

---

api/src/pcapi/models/feature.py
api/src/pcapi/routes/external/sendinblue.py
api/tests/routes/external/sendinblue_test.py

(BSR)[API] chore: remove unused brevo FF

---

api/src/pcapi/core/offers/factories.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/utils/date.py
api/tests/core/offers/test_models.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36744)

(PC-36744)[API] feat: update headlinesCount when headline offer status changes

---

pro/src/app/App/layout/Layout.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37036)
Le logo du header doit être un lien de navigation vers la page d'accueil.

(PC-37036)[PRO] feat: Add link to logo.

---

api/src/pcapi/core/finance/backend/cegid.py
api/tests/core/finance/test_backends.py

Reverts pass-culture/pass-culture-main#18395

Revert "(PC-37014)[API] feat: use R and not Open in invoice status"

---

api/src/pcapi/core/educational/adage_backends/__init__.py

De la même manière que le backend adresse, factoriser la récupération du backend Adage pour lui ajouter un typing (-> AdageClient) qui permet notamment un lien vers les différents méthodes du backend

(BSR)[ADAGE] refactor: add typing in adage client

---

api/src/pcapi/core/educational/repository.py
api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
api/src/pcapi/routes/backoffice/collective_offers/forms.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/templates/collective_offer/details.html
api/src/pcapi/routes/backoffice/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice/templates/collective_offer_template/details.html
api/src/pcapi/routes/backoffice/utils.py
api/tests/core/educational/test_repository.py
api/tests/routes/backoffice/collective_offer_templates_test.py
api/tests/routes/backoffice/collective_offers_test.py

https://passculture.atlassian.net/browse/PC-36806

(PC-36806)[BO] feat: replace collective offer status with displayedStatus

---

api/src/pcapi/core/artist/api.py
api/src/pcapi/core/search/serialization.py
api/src/pcapi/routes/native/v1/artists.py
api/tests/core/artist/test_api.py
api/tests/routes/native/v1/artists_tests.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-35999)

(PC-35999)[API] feat: prioritize artist image source

---

pro/cypress/e2e/didacticOnboarding.cy.ts
pro/cypress/support/commands.ts
pro/cypress/support/helpers.ts

(BSR)[PRO] fix: waiting for api calls so the test works.

---

api/src/pcapi/connectors/dms/models.py
api/src/pcapi/connectors/dms/serializer.py
api/src/pcapi/core/fraud/models.py
api/src/pcapi/core/subscription/dms/api.py
api/tests/core/subscription/dms/test_api.py
api/tests/scripts/beneficiary/fixture.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36916)

(PC-36916)[API] feat: remember DMS birth place

---

api/src/pcapi/routes/backoffice/templates/components/history/actions.html

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37183)
cette pr corrige les symptômes pas la cause. Je n'ai pas les moyens de corriger la cause du bug pour l'instant

(PC-37183)[BO] fix:display of offerer history in bo

---

pro/src/components/IndividualOffer/StocksEventCreation/__specs__/RecurrenceForm.spec.tsx
pro/src/components/IndividualOffer/StocksEventCreation/form/__specs__/onSubmit.spec.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/__specs__/validationSchema.spec.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/onSubmit.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/types.ts
pro/src/components/IndividualOffer/StocksEventCreation/form/validationSchema.ts

… recurring event
[Ticket Jira](https://passculture.atlassian.net/browse/PC-36992)
Premier fix d'une petite série de bugs du drawer de création des stocks pour event
- Affichage et gestion des validateurs pour les dates dans le cas 'monthly'

(PC-36992)[PRO] fix: correctly validate monthly options when creating offer

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/native/v1/serialization/offers.py
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
api/tests/files/native_openapi.json
api/tests/routes/native/v1/offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36949)

(PC-36949)[API] feat: add videoUrl to offer route

---

.github/workflows/dev_on_dispatch_deploy_pullrequests.yml
.github/workflows/dev_on_workflow_deploy.yml

(IC-235)[API] chore: bump render-push-manifest-action

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/native/v1/serialization/offers.py
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
api/tests/core/offers/test_api.py
api/tests/files/native_openapi.json
api/tests/routes/native/v1/offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36872)

(PC-36872)[API] feat: send youtube video id in offer route

---

api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py
api/src/pcapi/routes/backoffice/offerers/validation_repository.py
api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html
api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation_rows.html
api/tests/routes/backoffice/offerers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37135)

(PC-37315)[BO] feat: make the user-validation dynamic

---

api/src/pcapi/core/reminders/repository.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37255)

(PC-37255)[API] fix: delete reminder within transaction

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/offerers/repository.py
api/tests/core/educational/test_models.py
api/tests/routes/adage_iframe/get_collective_offer_template_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
pro/src/commons/utils/factories/collectiveApiFactories.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37085)

(PC-37085)[API] chore: remove usage of collective offers status field

---

pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/UnderReviewBanner.tsx

Jira : https://passculture.atlassian.net/browse/PC-36469

(PC-36469)[PRO] feat: add under review banner to collective timeline

---

api/src/pcapi/core/bookings/repository.py
api/src/pcapi/core/educational/api/export.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/serialization/collective_bookings_serialize.py
api/src/pcapi/utils/export.py
api/tests/routes/pro/get_collective_offers_csv_test.py
api/tests/routes/pro/get_collective_offers_excel_test.py
pro/src/apiClient/v1/services/DefaultService.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37119)

(PC-37119)[API] feat: export collective offers

---

pro/src/app/App/analytics/sentry.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37186)
- Filtrer le token d'autologin dans ce qui est envoyé à sentry.

(PC-37186)[PRO] chore: Scrub autologin token from urls sent to sentry.

---

pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/CancelledBanner.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/CancelledBanner.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36474)

(PC-36474)[PRO] feat: Add a banner for cancelled collective offer

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/commands.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/reminders/external/reminders_notifications.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_commands.py
api/tests/core/offers/test_repository.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37260)
Related PR pour le nouveau cron: https://github.com/pass-culture/pass-culture-deployment/pull/798

(PC-37260)[API] fix: change activate_future_offers command to handle future offer correctly

---

api/src/pcapi/routes/backoffice/templates/venue/list.html
api/src/pcapi/routes/backoffice/templates/venue/list_rows.html
api/src/pcapi/routes/backoffice/venues/blueprint.py
api/tests/routes/backoffice/venues_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37138)

Pc 37138 rpa dynamic venue list

---

api/src/pcapi/core/educational/adage_backends/serialize.py
api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/educational/serialization/collective_booking.py
api/tests/routes/public/collective/endpoints/adage_mock/test_bookings.py

Ne pas utiliser Venue.timezone directement mais passer par OA

(BSR)[API] fix: use venue OA to get timezone

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/scripts/move_offer/move_batch_offer.py
api/tests/scripts/move_offer/move_batch_offer_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37200)
Include traceback in exception message to figure what's going on.

(PC-37200)[API] chore: add more detailed exception message

---

pro/src/commons/utils/date.ts
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.module.scss
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/ExpiredBanner.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/ExpiredBanner.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/components/utils/formatDatetime.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36472)

(PC-36472)[PRO] feat: add expired banner for timeline

---

pro/src/commons/custom_types/form.ts
pro/src/commons/utils/factories/individualApiFactories.ts
pro/src/commons/utils/renderWithProviders.tsx
pro/src/components/Bookings/PreFilters/__specs__/PreFilters.spec.tsx
pro/src/components/IndividualOffer/PriceCategoriesScreen/form/getPriceCategoryOptions.ts
pro/src/components/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
pro/src/components/IndividualOffer/StocksEventCreation/form/computeInitialValues.ts
pro/src/components/IndividualOfferLayout/IndividualOfferLayout.spec.tsx
pro/src/components/IndividualOfferLayout/IndividualOfferNavigation/IndividualOfferNavigation.spec.tsx
pro/src/components/IndividualOfferLayout/IndividualOfferNavigation/IndividualOfferNavigation.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx
pro/src/pages/Homepage/components/Offerers/Offerers.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/Subcategories/Subcategories.module.scss
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/Subcategories/Subcategories.tsx
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.spec.tsx
pro/src/ui-kit/form/Select/Select.tsx
pro/src/ui-kit/form/shared/BaseSelectInput/SelectInput.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36971)
Before | After
:---: | :---:
https://github.com/user-attachments/assets/e979a8b7-6ef1-4b17-b655-92a3a505b430

(PC-36971)[PRO] feat: add callout & update offer creation stepper on subcat change

---

api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/templates/offer/details.html
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/routes/backoffice/templates/offer/list_rows.html
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
api/tests/routes/backoffice/offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37345)

(PC-37345)[BO] feat: add new Compliance API fields in BO Offers pages

---

pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.spec.tsx
pro/src/components/IndividualOffer/StocksEventCreation/StocksCalendar/StocksCalendarTable/StocksCalendarTable.tsx
pro/src/pages/IndividualOffer/IndividualOfferConfirmation/IndividualOfferConfirmation.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferConfirmation/components/IndividualOfferConfirmationScreen.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37336)

Pc 37336 fix wordings

---

pro/package.json
pro/src/components/Bookings/BookingsRecapTable/utils/bookingStatusConverter.ts
pro/src/design-system/Tag/Tag.module.scss
pro/src/design-system/Tag/Tag.stories.tsx
pro/src/design-system/Tag/Tag.tsx
pro/yarn.lock

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37285)
- Passage du tag des réservations indiv "réservée" du variant success au variant warning
- Bump de la lib design-system
- Ajout du variant de tag cinéclub
Before | After
:---: | :---:

Pc 37285 ds tags update

---

api/src/pcapi/settings.py
api/src/pcapi/utils/login_manager.py
api/tests/utils/login_manager_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37177)
Changement de nom pour les variables de temps de session pour clarifier leur contenu

BSR_change_session_time_variables_name

---

api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/educational/utils.py
api/src/pcapi/core/mails/transactional/educational/eac_booking_cancellation.py
api/src/pcapi/core/mails/transactional/educational/eac_new_booking_to_pro.py
api/src/pcapi/core/mails/transactional/educational/eac_new_prebooking_to_pro.py
api/src/pcapi/core/mails/transactional/educational/eac_new_request_made_by_redactor_to_pro.py
api/src/pcapi/core/mails/transactional/educational/eac_one_day_after_event.py
api/src/pcapi/core/mails/transactional/educational/eac_one_day_before_event.py
api/src/pcapi/core/mails/transactional/educational/eac_pending_booking_confirmation_limit_date_in_3_days.py
api/tests/core/educational/test_api.py
api/tests/core/educational/test_utils.py
api/tests/core/mails/transactional/bookings/booking_cancellation_by_institution_test.py
api/tests/core/mails/transactional/educational/eac_new_booking_to_pro_test.py
api/tests/core/mails/transactional/educational/eac_new_request_made_by_redactor_to_pro_test.py
api/tests/routes/adage/v1/confirm_prebooking_test.py
api/tests/routes/adage/v1/refuse_prebookings_test.py
api/tests/scripts/booking/handle_expired_bookings_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37124)

(PC-37124)[API] feat: add collective offer location to mails

---

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
api/src/pcapi/routes/backoffice/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice/templates/collective_offer/list_rows.html
api/tests/routes/backoffice/collective_offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37136)

Pc 37136 rpa collective offers dynamic

---

api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/src/pcapi/routes/backoffice/templates/operations/details/partial_response_container.html
api/src/pcapi/routes/backoffice/templates/operations/details/rows.html
api/src/pcapi/routes/backoffice/templates/operations/details/stats.html
api/src/pcapi/static/backoffice/js/addons/pc-table-manager.js
api/tests/routes/backoffice/operations_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37128)

(PC-37128)[BO] feat: make special event page dynamic

---

api/src/pcapi/models/feature.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37328)

(PC-37328)[API] chore: delete obsolete feature flag DISABLE_ENTERPRISE_API

---

api/src/pcapi/core/educational/repository.py

(BSR)[API] perf: always join venue when getting collective offers

---

.github/workflows/dev_on_pull_request_workflow.yml
.github/workflows/dev_on_workflow_dependabot_auto_merge.yml

Faire en sorte que les push fait par dependabot auto merge puisse trigger des CIs

(BSR)[PRO] ci: allow dependabot auto merge to trigger workflows

---

api/src/pcapi/templates/mails/payments_xml_email.html

Le fichier est hyper vieux, semble obsolète, et n'est appelé nulle part.

(BSR)[API] chore: remove useless email file

---

.github/workflows/dev_on_pull_request_workflow.yml

Correction d'une petite erreur sur le job dependabot auto update

(BSR)[PRO] ci: fix dependabot auto update job syntax

---

api/src/pcapi/core/finance/models.py
api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/accounts/serialization.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-37275

(PC-37275)[BO] fix: initial credit displayed in beneficiary history

---

api/src/pcapi/connectors/big_query/queries/__init__.py
api/src/pcapi/connectors/big_query/queries/artist.py
api/src/pcapi/core/artist/commands.py
api/src/pcapi/core/artist/utils.py
api/tests/core/artist/test_commands.py

[Ticket Notion](https://www.notion.so/passcultureapp/DS-3-tables-artiste-Etablir-une-strat-gie-et-faire-un-POC-pour-importer-les-trois-tables-delt-222ad4e0ff9880fda9ebd9800ffed5dc?v=21cad4e0ff9880bbb75b000ccde7bad7&source=copy_link)

(DS-1986)[API] feat: import delta artist tables

---

api/src/pcapi/models/feature.py
pro/src/commons/core/Offers/utils/serializer.ts
pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.spec.tsx
pro/src/components/OffersTable/OffersTableSearch/OffersTableSearch.tsx
pro/src/pages/CollectiveOffers/CollectiveOffers.tsx
pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx
pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx
pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/CollectiveOffersScreen.tsx
pro/src/pages/IndividualOffers/IndividualOffers.spec.tsx
pro/src/pages/IndividualOffers/IndividualOffers.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOfferColumns/components/HeadlineOfferImageDialogs.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOfferColumns/components/IndividualActionsCells.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOffersActionsBar/IndividualOffersActionsBar.tsx
pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffers.tsx
pro/src/pages/TemplateCollectiveOffers/TemplateCollectiveOffersScreen/TemplateCollectiveOffersScreen.tsx
pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffers.spec.tsx
pro/src/pages/TemplateCollectiveOffers/__specs__/TemplateCollectiveOffersQueryParams.spec.tsx

(PC-37321)[PRO] chore: remove WIP_COLLAPSED_MEMORIZED_FILTERS to enable feature permanently

---

pro/cypress/e2e/createAccount.cy.ts

BSR 
on attend que le titre soit dans la page pour faire les tests ally

(BSR)[PRO] test: try to de-flaky checkAlly in createAccount e2e

---

pro/src/pages/CollectiveOffer/CollectiveOfferSummary/BookableOfferSummary/BookableOfferSummary.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/EndBanner.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/EndBanner.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/ReimbursementWaitingBanner.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/ReimbursementWaitingBanner.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36477)

(PC-36477)[PRO] feat: Add a banner for ended collective offer

---

api/src/pcapi/core/finance/backend/cegid.py
api/tests/core/finance/test_backends.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37388)
Ajout d'un call pour passer les factures au statut Ouvert lors de leur push

(PC-37388)[API] feat: add set open call to cegid backend

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_api_legacy.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37397)
CSV des venues ayant changé de compte bancaire depuis la dernière quinzaine

(PC-37397)[API] feat: add changing bank accounts csv

---

api/src/pcapi/core/users/gdpr_api.py
api/src/pcapi/models/feature.py
api/tests/core/users/test_gdpr_api.py

(BSR)[API] chore: remove pro anonymization FF

---

pro/src/pages/CollectiveOffer/CollectiveOffer/CollectiveOfferEdition/__specs__/CollectiveOfferEdition.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveEditionOfferNavigation/CollectiveEditionOfferNavigation.module.scss
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveEditionOfferNavigation/CollectiveEditionOfferNavigation.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveEditionOfferNavigation/__specs__/CollectiveEditionOfferNavigation.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/__specs__/CollectiveOfferLayout.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferStock/CollectiveOfferStockEdition/__specs__/CollectiveOfferStockEdition.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/BookableOfferSummary/BookableOfferSummary.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/BookableOfferTimeline.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/EndBanner.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/ReimbursementWaitingBanner.spec.tsx
pro/src/pages/CollectiveOfferVisibility/__specs__/CollectiveOfferEditionVisibility.spec.tsx

https://passculture.atlassian.net/browse/PC-36759

(PC-36759)[PRO] feat: remove collective offer ctas on edition page

---

api/src/pcapi/core/finance/utils.py
api/tests/core/finance/test_utils.py
api/tests/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_to_pro_test.py
api/tests/core/mails/transactional/bookings/new_booking_to_pro_test.py
api/tests/core/mails/transactional/test_utils.py
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/bank_account_test.py
api/tests/routes/backoffice/finance_test.py
api/tests/routes/backoffice/offerers_test.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-37403

(PC-37403)[BO] feat: amounts rounded to the nearest 5 XPF

---

pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx
pro/src/components/SummaryLayout/SummaryLayout.module.scss
pro/src/components/SummaryLayout/SummarySection.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummary/components/IndividualOfferSummaryScreen.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummary/components/OfferSection/OfferSection.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummary/components/StockSection/StockSection.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryInformations/components/IndividualOfferSummaryInformationsScreen.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryPriceCategories/IndividualOfferSummaryPriceCategories.tsx
pro/src/pages/IndividualOfferSummary/components/MediaSection/MediaSection.tsx
pro/src/pages/IndividualOfferSummary/components/PriceCategoriesSection/PriceCategoriesSection.spec.tsx
pro/src/pages/IndividualOfferSummary/components/PriceCategoriesSection/PriceCategoriesSection.tsx

(PC-37409)[PRO] feat: improve indiv. offer creation summary page css

---

.github/dependabot.yml

[Ticket JIRA](https://passculture.atlassian.net/browse/PC-37536)

(PC-37536) ci: edit Dependabot config for npm dependencies

---

api/src/pcapi/routes/backoffice/filters.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-37550

(PC-37550)[BO] fix: active offer wording

---

api/src/pcapi/routes/pro/structure_data.py
api/tests/routes/pro/get_structure_data_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37554)

(PC-37554)[API] feat: edit error message when searching for SIRET in structure signup

---

api/src/pcapi/scripts/subscription/ubble/update_pending_ubble_applications.py

(BSR)[API] fix: lower ubble recovery cron page size

---

pro/src/ui-kit/Table/Table.module.scss
pro/src/ui-kit/Table/Table.stories.tsx
pro/src/ui-kit/Table/Table.tsx

Ajout d'un storybook sur le nouveau composant Table

(BSR)[PRO] fix: add storybook for new table component

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/pro/offerers.py
pro/cypress/e2e/signupJourneyCreateNotDiffusibleOfferer.cy.ts
pro/src/components/SignupJourneyForm/Authentication/OffererAuthentication.module.scss
pro/src/components/SignupJourneyForm/Authentication/OffererAuthentication.tsx
pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.module.scss
pro/src/components/SignupJourneyForm/Authentication/OffererAuthenticationForm.tsx
pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx
pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx
pro/src/components/SignupJourneyForm/Authentication/__specs__/validationSchema.spec.ts
pro/src/components/SignupJourneyForm/Authentication/validationSchema.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36983)
- Possibilité d'inscrire les structures avec un siret non diffusible.

(PC-36983)[PRO] feat: Not diffusible subscription.

---

.github/workflows/dev_on_pull_request_workflow.yml
.github/workflows/dev_on_workflow_tests_api_scripts.yml

Cette PR permet aux PR de scripts de seulement exécuter les tests `api/tests/scripts/**/test_main.py`. Exemple : https://github.com/pass-culture/pass-culture-main/pull/18664

(BSR)[API] ci: allow only scripts tests execution

---

pro/src/components/SignupJourneyForm/Authentication/OffererAuthentication.tsx

- Corriger un lien pour les siret non diffusibles

(BSR)[PRO] fix: Change the url for non diffusible sirets help page.

---

api/src/pcapi/models/feature.py
api/src/pcapi/routes/native/v1/offers.py
api/tests/routes/native/v1/offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-35666)

(PC-35666)[API] feat: add feature flag to toggle external cinema stocks update

---

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/get/details/bank_accounts.html
api/tests/routes/backoffice/offerers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37567)

(PC-37567)[BO] feat: add last BA update date in offerer page

---

api/src/pcapi/routes/backoffice/templates/chronicles/list_rows.html
api/src/pcapi/routes/backoffice/templates/components/dynamic/modal.html

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37624)

(PC-37624)[BO] fix: close chronicle modale on validation

---

api/src/pcapi/routes/backoffice/templates/components/links.html
api/src/pcapi/routes/backoffice/templates/offer/details.html
api/tests/routes/backoffice/offers_test.py

(BSR)[BO] feat: add product link to offer details page

---

api/src/pcapi/models/feature.py

Add content of deleted notion page to our code

(BSR)[API] docs: remove notion page and add its content to our code

---

pro/cypress/e2e/collaborator.cy.ts
pro/cypress/e2e/collectiveBooking.cy.ts
pro/cypress/e2e/createCollectiveOffer.cy.ts
pro/cypress/e2e/createIndividualOffer.cy.ts
pro/cypress/e2e/desk.cy.ts
pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
pro/cypress/e2e/financialManagement.cy.ts
pro/cypress/e2e/oaCollectiveOffer.cy.ts
pro/cypress/e2e/oaIndividualOffer.cy.ts
pro/cypress/e2e/searchCollectiveOffer.cy.ts
pro/cypress/e2e/searchIndividualOffer.cy.ts
pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
pro/cypress/support/constants.ts
pro/cypress/support/helpers.ts
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CheckboxCell.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveActionsCells/CollectiveActionsCells.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.spec.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferStatusCell/CollectiveOfferStatusCell.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/ExpirationCell/ExpirationCell.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/OfferEventDateCell/OfferEventDateCell.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/OfferInstitutionCell/OfferInstitutionCell.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/OfferNameCell/OfferNameCell.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/OfferVenueCell.tsx
pro/src/components/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37398)
on ajoute checkAlly au test e2e sauf adage
petite correction sur un bouton
correction sur le tableau des offres

(PC-37398)[PRO] test: add checkAlly to e2e but not adage

---

api/src/pcapi/core/finance/ds.py
api/tests/core/finance/test_ds.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37645)
Les modifications de BIC et d'IBAN par l'acteur culturel sur Démarche Simplifiée n'étaient pas correctement prises en compte lors de l'import des coordonnées bancaires

(PC-37645)[API] fix: Handle bank account edition by cultural partner without status modification

---

api/src/pcapi/core/artist/commands.py

(BSR) feat: Add --truncate-tables option to artist import command

---

api/tests/routes/backoffice/collective_offers_test.py

Fix broken test spanning a new educational year.

(BSR)[API] test: fix tests spanning new educational year

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250901T093344_0171499fda14_index_achievement_booking_id.py
api/src/pcapi/core/achievements/models.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37607)
Ajouter un index sur la clé étrangère `bookingId` de la table `Achievement`

(PC-37607)[API] feat: add index on 'bookingId' foreign key field of achievement table

---

pro/src/pages/CollectiveOffer/CollectiveOfferConfirmation/CollectiveOfferConfirmation/CollectiveOfferConfirmation.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferConfirmation/CollectiveOfferConfirmation/CollectiveOfferConfirmation.tsx

https://passculture.atlassian.net/browse/PC-37551

(PC-37551)[PRO] feat: redirect to template offers after template creation

---

pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.spec.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.tsx
pro/src/ui-kit/Table/Table.spec.tsx
pro/src/ui-kit/Table/Table.tsx

Fixer la sélection multiple sur le tableau d'offre, toutes les offres doivent être sélectionner sans tenir compte de la pagination.
[Ticket Jira](https://passculture.atlassian.net/browse/PC-37686)

(PC-37686)[PRO] fix: select all offers on all pages for bulk actions

---

api/src/pcapi/routes/backoffice/dev/blueprint.py
api/src/pcapi/routes/backoffice/templates/dev/users_generator.html
api/src/pcapi/settings.py
api/tests/routes/backoffice/dev_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36504)

(PC-36504)[BO] feat: add link to local web app

---

pro/src/pages/IndividualOffer/IndividualOfferPriceTable/components/IndividualOfferPriceTableScreen.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/components/PriceTableForm/PriceTableForm.spec.tsx
pro/src/pages/IndividualOffer/commons/__mocks__/constants.ts
pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryDetails/components/IndividualOfferSummaryDetailsScreen.spec.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryDetails/components/IndividualOfferSummaryDetailsScreen.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37621)
Before | After
:---: | :---:

(PC-37621)[PRO] feat: update offer summary detail for new creation flow

---

api/src/pcapi/core/users/generator.py
api/tests/routes/backoffice/dev_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36309)
Mettre une un statut par défaut pour l'utilisateur créé dans le générateur d'utilisateurs du BO

(PC-36309)[BO] feat: set value for 'activity' field in user generator page

---

.git-blame-ignore-revs

Le commit https://github.com/pass-culture/pass-culture-main/commit/36c6621f6b4e9130063c4c83f7afa437eed83bfa change beaucoup d'imports dans des fichiers educational, on l'ignore ici dans l'historique git

(BSR) chore: add educational import refactor commit in ignore-revs

---

.github/workflows/dev_on_call_release_build.yml
.github/workflows/dev_on_schedule_tag_and_deploy_staging.yml

Le Premier fichier modifié est une copie du 2eme avec workflow call à la place de workflow dispatch
Tous les jeudis, automatiquement trouver quelle sera la prochaine version et lancer le build et le tag de la nouvelle version. 
Next step -> Lancer la MES directement dans la foulée
Next next step -> Modifier le rythme des crons pour le lancer 2 x par semaine

(PC-37301)[API] ci: tag and deploy staging

---

pro/src/commons/utils/date.ts
pro/src/commons/utils/yup/__specs__/uniqueBy.spec.ts
pro/src/commons/utils/yup/index.ts
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/commons/__specs__/validationSchema.spec.ts
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/commons/schemas.ts
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/commons/utils/__specs__/makeFieldConstraints.spec.ts
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/commons/utils/makeFieldConstraints.ts
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/commons/utils/toBookingLimitDatetime.ts
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/components/PriceTableForm/PriceTableForm.module.scss
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/components/PriceTableForm/PriceTableForm.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37704)

(PC-37704)[PRO] fix: fix PM review issues for IndividualOfferPriceTable

---

pro/cypress/cypress.config.ts
pro/cypress/e2e/adageConfirmation.cy.ts
pro/cypress/e2e/didacticOnboarding.cy.ts
pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
pro/cypress/e2e/oaIndividualOffer.cy.ts
pro/cypress/e2e/searchCollectiveOffer.cy.ts
pro/cypress/e2e/searchIndividualOffer.cy.ts
pro/cypress/support/commands.ts
pro/cypress/support/index.d.ts

(BSR)[PRO] fix: biome warning

---

api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/pro/get_offer_test.py
api/tests/routes/pro/post_draft_offer_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
pro/src/apiClient/v1/models/GetIndividualOfferWithAddressResponseModel.ts
pro/src/apiClient/v1/models/VideoData.ts
pro/src/commons/utils/factories/individualApiFactories.ts
pro/src/pages/IndividualOffer/IndividualOfferMedia/components/IndividualOfferMediaScreen.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferMedia/components/IndividualOfferMediaScreen.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummary/components/IndividualOfferSummaryScreen.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryMedia/IndividualOfferSummaryMedia.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37382)

(PC-37382)[API] feat: Updated offer response to add video data

---

api/src/pcapi/core/offers/factories.py
api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37788)

(PC-37788)[API] test: Add video metadata to one offer in the sandbox

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20250819T155615_fe62e0063fc8_create_artist_alias_name_trigram_index.py
api/src/pcapi/core/artist/models.py
api/src/pcapi/routes/backoffice/artists/blueprint.py
api/src/pcapi/routes/backoffice/artists/forms.py
api/src/pcapi/routes/backoffice/menu.py
api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py
api/src/pcapi/routes/backoffice/products/blueprint.py
api/src/pcapi/routes/backoffice/templates/artists/list.html
api/src/pcapi/routes/backoffice/templates/artists/list_rows.html
api/src/pcapi/routes/backoffice/templates/components/links.html
api/src/pcapi/routes/backoffice/titelive/blueprint.py
api/tests/routes/backoffice/artists_test.py

[Ticket Notion](https://www.notion.so/passcultureapp/DS-Artiste-Cr-er-le-code-back-pour-diter-manuellement-les-artistes-224ad4e0ff9880afa870e7b3800484b5?v=21cad4e0ff9880bbb75b000ccde7bad7&source=copy_link)

(DS-2004)[BO] feat: advance search for artists

---

pro/biome.jsonc
pro/src/ui-kit/Button/Button.tsx
pro/src/ui-kit/Button/ButtonLink.tsx
pro/src/ui-kit/DropdownMenuWrapper/DropdownMenuWrapper.tsx
pro/src/ui-kit/Icons/SVGs/ShadowTipsHelpIcon.tsx
pro/src/ui-kit/Table/Table.tsx
pro/src/ui-kit/Timeline/Timeline.tsx
pro/src/ui-kit/form/AddressManual/AddressManual.tsx
pro/src/ui-kit/form/AddressSelect/AddressSelect.tsx
pro/src/ui-kit/form/DayCheckbox/DayCheckbox.tsx
pro/src/ui-kit/form/IconRadioGroup/IconRadioGroup.tsx
pro/src/ui-kit/form/MultiSelect/MultiSelectTrigger.tsx
pro/src/ui-kit/form/MultiSelect/__specs__/MultiSelectPanel.spec.tsx
pro/src/ui-kit/form/MultiSelect/__specs__/MultiSelectTrigger.spec.tsx
pro/src/ui-kit/form/PhoneNumberInput/CodeCountrySelect/CountryCodeSelect.tsx
pro/src/ui-kit/form/PriceInput/PriceInput.tsx
pro/src/ui-kit/form/TextArea/TextArea.tsx
pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx

(BSR)[PRO] fix: biome fix unsafe

---

api/src/pcapi/core/external/zendesk.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/dev/components.html
api/src/pcapi/routes/backoffice/templates/venue/get.html

BO uniquement : quelques mentions de « lieu » subsistaient.

(BSR)[BO] fix: wording 'lieu' is deprecated

---

pro/src/app/App/App.spec.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/OfferInstitutionCell/OfferInstitutionCell.spec.tsx
pro/src/components/EducationalInstitutionDetails/EducationalInstitutionDetails.tsx
pro/src/components/IndividualOffer/StocksThing/ActivationCodeFormDialog/AddActivationCodeForm.tsx
pro/src/components/OnboardingOffersChoice/components/OnboardingCollectiveModal/OnboardingCollectiveModal.tsx
pro/src/design-system/RadioButton/RadioButton.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/OfferFavoriteButton.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferSummary/OfferSummary.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/FormLocation/FormLocation.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferConfirmation/CollectiveOfferConfirmation/CollectiveOfferConfirmation.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferStock/components/OfferEducationalStock/OfferEducationalStock.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/components/BookableOfferTimeline/banners/BookedBanner.tsx
pro/src/pages/CollectiveOfferVisibility/components/CollectiveOfferVisibility/CollectiveOfferVisibility.tsx
pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx
pro/src/pages/Desk/ButtonInvalidateToken.tsx
pro/src/pages/Homepage/components/Offerers/components/OffererBanners/OffererBanners.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/PartnerPages.tsx
pro/src/pages/Homepage/components/Offerers/components/PartnerPages/components/PartnerPageIndividualSection.tsx
pro/src/pages/IndividualOffer/IndividualOfferMedia/components/VideoUploaderOfferTips/VideoUploaderOfferTips.tsx
pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/StocksCalendar/RecurrenceForm/RecurrenceForm.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/IndividualOffersContainer.tsx
pro/src/pages/IndividualOffers/IndividualOffersContainer/components/IndividualOfferColumns/components/IndividualActionsCells.tsx
pro/src/pages/OfferType/OfferType/OfferType.tsx
pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx
pro/src/pages/Reimbursements/Income/Income.tsx
pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceActions.tsx
pro/src/pages/SignupJourneyRoutes/SignupJourneyRoutes.tsx
pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx
pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/ToggleVenueProviderStatusButton.tsx
pro/src/pages/VenueSettings/VenueSettingsForm.tsx

This PR fix noUselessFragments biome rule

(BSR)[PRO] fix: noUselessFragments biome rule

---

api/src/pcapi/core/offerers/constants.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
api/src/pcapi/routes/backoffice/collective_offers/forms.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_tags.py
api/tests/core/offerers/test_models.py
api/tests/routes/backoffice/collective_offer_templates_test.py
api/tests/routes/backoffice/collective_offers_test.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-37804

(PC-37804)[BO] feat: filter collective offers by Top Acteur tag

---

pro/src/components/CollectiveBudgetInformation/CollectiveBudgetCallout.spec.tsx
pro/src/components/CollectiveBudgetInformation/CollectiveBudgetCallout.tsx
pro/src/components/CollectiveBudgetInformation/constants.ts
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/__specs__/CollectiveOfferLayout.spec.tsx
pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/__specs__/CollectiveOffersScreen.spec.tsx
pro/src/pages/OfferType/OfferType.spec.tsx

https://passculture.atlassian.net/browse/PC-37807

(PC-37807)[PRO] feat: update collective budget information banner

---

api/src/pcapi/algolia_settings_offers.json

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37354)

(PC-37354)[API] feat: add `chroniclesCount` as numeric filter in Algolia

---

pro/src/components/Bookings/IndividualBookings.tsx
pro/src/components/Bookings/IndividualBookingsTable/IndividualBookingsTable.tsx
pro/src/pages/Bookings/IndividualBookings.spec.tsx
pro/src/pages/Bookings/IndividualBookings.tsx
pro/src/pages/Bookings/adapters/getUserHasIndividualBookingsAdapter.ts
pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryBookings/components/IndividualOfferSummaryBookingsScreen.spec.tsx
pro/src/pages/IndividualOfferSummary/IndividualOfferSummaryBookings/components/IndividualOfferSummaryBookingsScreen.tsx

BSR l'idée ici est de d'utiliser les statuts du nouveau composant `<Table />`

Bsr display table loading

---

api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice/templates/collective_offer/list_rows.html
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/routes/backoffice/templates/offer/list_rows.html
api/tests/routes/backoffice/collective_offers_test.py
api/tests/routes/backoffice/offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37848)

(PC-37848)[BO] feat: show offer price and creator to every user

---

api/src/pcapi/core/educational/api/institution.py
api/src/pcapi/core/educational/models.py

Refacto des imports et ajout d'un typing dans `api/src/pcapi/core/educational/api/institution.py`
Le typing ajouté est `offer_query: "sa_orm.Query[models.CollectiveOffer]"` et permet d'identifier isBookable comme attribut de CollectiveOffer
\+ ajout d'un commentaire sur locationType

Educational import and typing

---

pro/src/commons/core/OfferEducational/utils/extractOfferIdAndOfferTypeFromRouteParams.ts
pro/src/commons/core/OfferEducational/utils/parseDuration.ts
pro/src/commons/core/Offers/hooks/useQuerySearchFilters.ts
pro/src/commons/store/features/reducer.ts
pro/src/commons/utils/date.ts
pro/src/commons/utils/formatPrice.ts
pro/src/commons/utils/timezone.ts
pro/src/commons/utils/types.ts
pro/src/repository/venuesService.ts

(BSR)[PRO] fix: biome write

---

api/src/pcapi/core/finance/backend/cegid.py
api/tests/core/finance/test_backends.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37981)

(PC-37918)[API] feat: fix cegid releasebill route

---

api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/commands.py
api/src/pcapi/core/finance/conf.py
api/tests/core/finance/test_api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-37560

(PC-37560)[API] feat: command which deletes duplicate bank accounts

---

pro/src/components/IndividualOfferLayout/IndividualOfferLayout.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37931)

(PC-37931)[PRO] fix: only display headline offer tag in indiv. offer pages when relevant

---

pro/src/components/SignupJourneyForm/Authentication/OffererAuthentication.tsx
pro/src/components/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx
pro/src/components/SignupJourneyForm/Offerer/Offerer.tsx
pro/src/components/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx
pro/src/components/SignupJourneyFormLayout/SignupJourneyFormLayout.spec.tsx
pro/src/components/SignupJourneyFormLayout/SignupJourneyFormLayout.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37705)
- Correction de redirections en cas de perte de contexte sur le parcours d'inscription.

(PC-37705)[PRO] fix: Refactor redirect on state lost and nav issues.

---

pro/src/components/SignupJourneyForm/Offerer/Offerer.tsx
pro/src/components/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx
pro/src/pages/VenueSettings/SiretOrCommentFields/SiretOrCommentFields.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37744)
- Enlever le formatage du siret et passer le champ siret en number

(PC-37744)[PRO] feat: remove siret formatting as it was causing issues.

---

api/src/pcapi/connectors/cgr/cgr.py
api/tests/core/external_bookings/cgr/test_client.py
api/tests/local_providers/cinema_providers/cgr/fixtures.py
api/tests/routes/backoffice/individual_bookings_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37922)

(PC-37922)[API] fix: prevent exception raising when booking is already cancelled on CGR side

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/backoffice/venues/blueprint.py
api/src/pcapi/routes/pro/venues.py
api/tests/core/offerers/test_api.py
api/tests/routes/backoffice/venues_test.py
api/tests/routes/pro/patch_venue_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37583)
replace null or empty public names by name for venues

(PC-37583)[API] feat:avoid empty public names for venues

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/models/feature.py
api/src/pcapi/routes/backoffice/filters.py
api/tests/core/offers/test_models.py
api/tests/routes/backoffice/offers_test.py
api/tests/routes/backoffice/products_test.py
api/tests/routes/native/v1/offers_test.py
api/tests/routes/pro/get_offer_test.py
api/tests/routes/pro/get_offerer_stats_test.py
api/tests/routes/pro/get_offers_test.py
api/tests/routes/pro/get_venue_offer_by_ean_test.py
api/tests/routes/pro/patch_offer_test.py
api/tests/routes/pro/patch_publish_offer_test.py
api/tests/routes/public/individual_offers/v1/events/get_event_test.py
api/tests/routes/public/individual_offers/v1/events/get_events_test.py
api/tests/routes/public/individual_offers/v1/events/patch_event_test.py
api/tests/routes/public/individual_offers/v1/products/get_product_by_ean_test.py
api/tests/routes/public/individual_offers/v1/products/get_product_test.py
api/tests/routes/public/individual_offers/v1/products/get_products_test.py
api/tests/routes/public/individual_offers/v1/products/patch_product_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37857)
Suppression du FF `WIP_REFACTO_FUTURE_OFFER`.

(PC-37857)[API] feat: rm WIP_REFACTO_FUTURE_OFFER ff

---

api/src/pcapi/core/offers/api.py

Suppression d'une fonction qui n'est plus utilisée depuis que cette PR #19198 a été mergée

(BSR)[API] feat: remove `get_shows_remaining_places_from_provider`

---

api/src/pcapi/core/highlights/factories.py
api/src/pcapi/routes/backoffice/autocomplete.py
api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/offers/forms.py
api/src/pcapi/routes/backoffice/utils.py
api/tests/routes/backoffice/autocomplete_test.py
api/tests/routes/backoffice/offers_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37293)
Ajout d'un filtre sur les demandes de participation aux temps fort dans la liste des offres

(PC-37293)[BO] feat: Add filter on highlight request in offers list

---

api/src/pcapi/routes/backoffice/operations/blueprint.py
api/src/pcapi/routes/backoffice/templates/operations/details.html
api/src/pcapi/routes/backoffice/templates/operations/details/rows.html
api/tests/routes/backoffice/operations_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37929)

(PC-37929)[BO] feat: add candidate email (from account) in operation details

---

api/rebuild_staging.sh
api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
api/src/pcapi/sandboxes/scripts/getters/native.py
api/src/pcapi/sandboxes/scripts/sandbox_accessibility_offers.py
api/src/pcapi/sandboxes/scripts/save_sandbox.py
api/src/pcapi/sandboxes/scripts/utils/helpers.py
api/src/pcapi/scripts/sandbox.py

Ajout d'un lieu et 4 offres pour tester l'accessibilité sur testing et staging

(PC-37625)[API] feat: add accessibility sandbox data for testing and staging

---

pro/src/components/Bookings/CollectiveBookingsTable/CollectiveTimeLine.tsx
pro/src/components/SoftDeletedOffererWarning/SoftDeletedOffererWarning.tsx
pro/src/pages/Homepage/components/Offerers/Offerers.tsx
pro/src/pages/Homepage/components/Offerers/components/OffererCreationLinks/OffererCreationLinks.module.scss
pro/src/pages/Homepage/components/Offerers/components/OffererCreationLinks/OffererCreationLinks.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37944)
Remplacement de mailto par des liens vers un formulaire du support.

(PC-37944)[PRO] feat: Replace mailto support with form link.

---

api/src/pcapi/core/mails/transactional/pro/non_payment_notice_notification.py
api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
api/src/pcapi/core/offerers/factories.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/backoffice/non_payment_notices/blueprint.py
api/src/pcapi/routes/backoffice/non_payment_notices/forms.py
api/src/pcapi/routes/backoffice/templates/non_payment_notices/list.html
api/tests/routes/backoffice/non_payment_notices_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-36315

(PC-36315)[BO] feat: actions on non-payment notices

---

.github/workflows/dev_on_workflow_deploy_app_engine_image_resizing.yml

(BSR) fix: fix image resizing deploy yml

---

pro/src/app/App/App.tsx

(BSR)[PRO] chore: stop calling the api two times

(BSR)[PRO] chore: stop calling the api two times

---

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py
api/src/pcapi/core/offerers/tasks.py
api/tests/connectors/api_entreprise_test.py
api/tests/core/offerers/test_commands.py
api/tests/core/offerers/test_tasks.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37368)

(PC-37368)[API] chore: Use Open Data API Entreprise route as data source

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py
pro/src/pages/IndividualOffer/IndividualOfferMedia/commons/isYoutubeValid.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37945)
Front-end and backend regex where not aligned, thus this PR. 
FYI: we accept embeded videos, mobile videos, but not shorts

(PC-37945)[API] feat: unify regex for youtube videos

---

pro/src/app/App/App.tsx

BSR pour fixer les tests end 2 end, en conditionnant le `dispatch` du current offerer seulement si l'utilisateur vient du BO.

(BSR)[PRO] fix: fix end 2 end

---

pro/src/pages/LostPassword/LostPassword.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-36745)
Bloquer la validation du formulaire de mot de passe oublié après la première fois.

(PC-36745)[PRO] feat: Disable button when submitting.

---

pro/src/commons/hooks/useIsAllowedOnAdage.ts
pro/src/components/Bookings/CollectiveBookings.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveOfferLayout.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/__specs__/CollectiveOfferLayout.spec.tsx
pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/CollectiveOffersScreen.tsx
pro/src/pages/CollectiveOffers/components/CollectiveOffersScreen/__specs__/CollectiveOffersScreen.spec.tsx
pro/src/pages/OfferType/OfferType.spec.tsx
pro/src/pages/OfferType/OfferType.tsx
pro/src/pages/OfferType/OfferType/CollectiveOfferType/CollectiveOfferType.tsx
pro/src/pages/OfferType/OfferType/OfferType.tsx
pro/src/pages/OfferType/OfferType/__specs__/OfferType.spec.tsx

BSR proposition de pattern pour gérer les `allowedOnAdage`

(BSR)[PRO] chore: isAllowedOnAdage partern proposition

---

api/src/pcapi/routes/serialization/finance_serialize.py
api/tests/routes/pro/patch_offerer_bank_accounts_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37851)

(BSR)[API] chore: use GetterDict instead of from_orm in serializers

---

pro/src/pages/Onboarding/OnboardingOfferIndividual/OnboardingOfferIndividual.spec.tsx
pro/src/pages/Onboarding/OnboardingOfferIndividual/OnboardingOfferIndividual.tsx

BSR récupérer l'offerer depuis le store pour améliorer les performances

(BSR)[PRO] chore: replace calling offerer by store

---

api/src/pcapi/connectors/ems.py
api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/external_bookings/ems/client.py
api/src/pcapi/core/external_bookings/exceptions.py
api/src/pcapi/routes/native/v1/bookings.py
api/tests/core/bookings/test_api.py
api/tests/core/external_bookings/ems/test_client.py
api/tests/core/external_bookings/test_api.py
api/tests/routes/native/v1/bookings_test.py

(BSR)[API] refactor: drop `ExternalBookingSoldOutError` in favor of `ExternalBookingNotEnoughSeatsError`

---

api/src/pcapi/connectors/api_adresse.py
api/src/pcapi/core/external/zendesk.py
api/src/pcapi/core/external_bookings/boost/client.py
api/src/pcapi/core/finance/deposit_api.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/core/fraud/models.py
api/src/pcapi/core/logging.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offers/tasks.py
api/src/pcapi/core/search/serialization.py
api/src/pcapi/core/users/api.py
api/src/pcapi/models/beneficiary_import.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/components/history/actions.html
api/src/pcapi/routes/backoffice/utils.py
api/src/pcapi/routes/backoffice/venues/blueprint.py
api/src/pcapi/routes/error_handlers/generic_error_handlers.py
api/src/pcapi/routes/native/v1/serialization/offers.py
api/tests/providers/titelive_search_test.py
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/serialization/collective_history_test.py

Un peu de ménage dans les FIXME et TODO

(BSR)[API] chore: remove, complete, or solve fixmes and todos

---

api/src/pcapi/core/finance/backend/base.py
api/src/pcapi/core/finance/backend/cegid.py
api/tests/core/finance/test_backends.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37967)

(PC-37967)[API] feat: fix many minor cegid things

---

api/src/pcapi/connectors/entreprise/backends/insee.py
api/src/pcapi/settings.py
api/tests/connectors/sirene_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-38080

(PC-30080)[API] fix: API Insee changed URL and authentication

---

.github/workflows/dev_on_schedule_tag_and_deploy_staging.yml

(BSR)[API] fix: checkout rc commit

---

pro/package.json
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/OfferEducational.tsx
pro/src/pages/CollectiveOffer/CollectiveOffer/components/OfferEducational/validationSchema.ts
pro/src/pages/IndividualOffer/IndividualOfferPracticalInfos/commons/validationSchema.ts
pro/src/pages/IndividualOffer/IndividualOfferPracticalInfos/components/IndividualOfferPracticalInfosScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferSummary/components/EventPublicationForm/validationSchema.ts
pro/src/pages/IndividualOffer/IndividualOfferSummary/components/IndividualOfferSummaryScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferTimetable/commons/validationSchema.ts
pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/IndividualOfferTimetableScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/StocksCalendar/StocksCalendarTable/StocksCalendarTableEditStock/StocksCalendarTableEditStock.tsx
pro/src/pages/IndividualOffer/IndividualOfferTimetable/components/StocksCalendar/StocksCalendarTable/StocksCalendarTableEditStock/validationSchema.ts
pro/yarn.lock

(BSR)[PRO] bump: yup.

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/external_bookings/cgr/client.py
api/src/pcapi/core/external_bookings/exceptions.py
api/src/pcapi/routes/native/v1/bookings.py
api/tests/core/external_bookings/cgr/test_client.py
api/tests/routes/native/v1/bookings_test.py

Delete stock when show does not exist on CGR API
[Ticket Jira](https://passculture.atlassian.net/browse/PC-38104)

(PC-38104)[API] feat: update `offers_api.book_offer` and `CGRClientAPI.book_ticket`

---

pro/src/components/IndividualOffer/StocksThing/ActivationCodeFormDialog/ActivationCodeFileChecker.ts
pro/src/components/IndividualOffer/StocksThing/__specs__/ActivationCodeFileChecker.spec.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38097)

(PC-38097)[PRO] fix: error on ActivationCode file was undefined

---

pro/src/app/App/analytics/orejime.ts
pro/src/components/Footer/Footer.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38076)
- Correction d'erreurs liées au chargement de orejime.

(PC-38076)[PRO] fix: check orejime loaded before using it.

---

api/src/pcapi/models/feature.py
pro/src/components/IndividualOffer/StocksThing/StocksThing.tsx
pro/src/components/IndividualOfferLayout/IndividualOfferNavigation/IndividualOfferNavigation.spec.tsx
pro/src/components/IndividualOfferLayout/IndividualOfferNavigation/IndividualOfferNavigation.tsx
pro/src/components/IndividualOfferLayout/IndividualOfferNavigation/utils/getSteps.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/DetailsForm/DetailsForm.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreenNext.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferDetails/components/IndividualOfferDetailsScreenNext.tsx
pro/src/pages/IndividualOffer/IndividualOfferInformations/components/IndividualOfferInformationsScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferLocation/commons/hooks/__tests__/useSaveOfferLocation.spec.ts
pro/src/pages/IndividualOffer/IndividualOfferLocation/commons/hooks/useSaveOfferLocation.ts
pro/src/pages/IndividualOffer/IndividualOfferLocation/components/IndividualOfferLocationScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferPriceCategories/components/IndividualOfferPriceCategoriesScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferPriceCategories/components/__specs__/PriceCategories.RouteLeavingGuard.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferPriceTable/components/IndividualOfferPriceTableScreen.tsx
pro/src/pages/IndividualOffer/IndividualOfferSummary/components/IndividualOfferSummaryScreen.spec.tsx
pro/src/pages/IndividualOffer/IndividualOfferSummary/components/IndividualOfferSummaryScreen.tsx
pro/src/pages/IndividualOffers/IndividualOffers.spec.tsx
pro/src/pages/IndividualOffers/IndividualOffers.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37182)
- Suppression du FF WIP_ADD_VIDEO

(PC-37182)[PRO/API] feat: remove WIP_ADD_VIDEO feature flag

---

api/src/pcapi/connectors/ems.py
api/tests/core/external_bookings/ems/test_client.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38059)

(PC-38059)[API] feat: update `EMSBookingConnector.raise_for_status` to raise `ExternalBookingNotEnoughSeatsError` when `error_code=106`

---

pro/cypress/e2e/createIndividualOffer.cy.ts
pro/cypress/e2e/didacticOnboarding.cy.ts
pro/cypress/e2e/editDigitalIndividualOffer.cy.ts
pro/cypress/e2e/oaIndividualOffer.cy.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37182)
- Rajout de tests e2e oubliés pour la page "Image et vidéo" autrement appelée "Media" / dans le contexte de parcours de créa./modification d'offre individuelle. 
Merci encore @abouabdallaoui-pass pour le heads up.

(PC-37182)[PRO] test: add missing e2e test regarding media page

---

pro/cypress/e2e/createIndividualOffer.cy.ts

On commente les tests de l'ajout de vidéo youtube en attendant le ticket   https://passculture.atlassian.net/browse/PC-38122

(BSR)[PRO] fix: ci by commenting youtube addition

---

api/src/pcapi/core/chronicles/models.py
api/src/pcapi/core/criteria/models.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/users/models.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38139)

(PC-38139)[API] feat: normalise criteria and chronicles

---

api/src/pcapi/routes/backoffice/offers/blueprint.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-38181

Pc 38181 bo batch validate offers

---

pro/cypress/e2e/didacticOnboarding.cy.ts
pro/cypress/e2e/oaIndividualOffer.cy.ts
pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts

(BSR)[PRO] fix: Fix issues with tests after useFocus changes.

---

api/src/pcapi/core/offers/tasks.py

Fix for https://pass-culture.sentry.io/issues/66450070/?project=4508776981069904&query=is%3Aunresolved&referrer=issue-stream

(BSR)[API] fix: flush to avoid call to partial with no ID

---

pro/cypress/e2e/createAccount.cy.ts
pro/src/commons/core/FirebaseEvents/constants.ts
pro/src/components/SignupJourneyForm/Offerer/Offerer.tsx
pro/src/components/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38008)
Afficher un lien redirigent vers l'annuaire des entreprises pour les utilisateurs qui ne connaissent pas leur siret.

(PC-38008)[PRO] feat: track users that do not know their siret.

---

api/src/pcapi/core/chronicles/models.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/core/highlights/models.py
api/src/pcapi/core/history/constants.py
api/src/pcapi/core/history/models.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/users/eligibility_api.py
api/src/pcapi/core/users/models.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38179)

(PC-38179)[API] refactor: normalise highlight and history

---

api/src/pcapi/core/offers/tasks.py

Fixes https://pass-culture.sentry.io/issues/66450070/\?alert_rule_id\=155878\&alert_type\=issue\&notification_uuid\=ed6ca17f-21bf-42e6-87a6-a1e715da011d\&project\=4508776981069904\&referrer\=slack

(BSR)[API] fix: add missing `db.session.add`

---

pro/cypress/e2e/createCollectiveOffer.cy.ts
pro/cypress/e2e/createIndividualOffer.cy.ts

(BSR)[PRO] ci: Mock api address call to prevent flakyness.

---

api/src/pcapi/core/educational/api/institution.py
api/src/pcapi/core/educational/commands.py
api/tests/core/educational/api/test_import_deposit_institution_deposit_data.py

On extrait la partie lecture du csv pour l'import des budgets dans une commande, ce qui permet de lancer cette commande en local et vérifier si le fichier est bien formaté

(BSR)[API] feat: add command to check institution deposit csv

---

pro/src/components/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx
pro/src/pages/Signup/SignupContainer/MaybeAppUserDialog/MaybeAppUserDialog.tsx

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38044)
Changement de wording pour les dialogs des certains codes ape.

(PC-38044)[PRO] chore: wording changes.

---

api/src/pcapi/core/criteria/models.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/core/users/models.py
api/src/pcapi/routes/backoffice/non_payment_notices/blueprint.py
api/src/pcapi/routes/backoffice/venues/blueprint.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38184)

(PC-38184)[API] refactor: normalize offerers models

---

api/documentation/docs/understanding-our-api/authentication-authorization.md

Update de l'url backend public dans la doc

(PC-38146)[API] docs: change backend url to correct one in documentation

---

api/src/pcapi/core/finance/external.py
api/tests/core/finance/test_external.py

La petite notif Slack pour l'import des factures

(BSR)[API] feat: add slack message to invoice generation

---

api/src/pcapi/core/external/zendesk.py
api/tests/routes/external/zendesk_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-38182

(PC-38182)[API] feat: send a department tag to Zendesk Support also for young users

---

api/src/pcapi/core/highlights/models.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/exceptions.py
api/src/pcapi/core/offers/schemas.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/src/pcapi/validation/routes/offers.py
api/tests/routes/pro/post_highlight_request_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/CreateOfferHighlightRequestBodyModel.ts
pro/src/apiClient/v1/models/OfferHighlightResquestsResponseModel.ts
pro/src/apiClient/v1/services/DefaultService.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37874)
Ajout d'une route permettant aux AC de demander à participer à des temps forts en y ajoutant leurs offres
- Une offre peut participer à plusieurs temps fort
- Les temps fort sont actifs sur une période et disponible à la demande de participation sur une autre période

(PC-37874)[API] feat: New route to create highlight request for an offer and one or more highlights

---

pro/src/components/Markdown/Markdown.module.scss

https://passculture.atlassian.net/browse/PC-38016
Formulaire :
Récap :
Aperçu ADAGE :

(PC-38016)[PRO] fix: handle line break in markdown offer description

---

api/src/pcapi/core/users/models.py
api/src/pcapi/models/beneficiary_import.py
api/src/pcapi/models/beneficiary_import_status.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38225)

(PC-38225)[API] refactor: normalize models

---

api/src/pcapi/routes/pro/bookings.py
api/src/pcapi/routes/pro/collective_bookings.py
api/src/pcapi/routes/pro/providers.py
api/src/pcapi/routes/pro/users.py
api/tests/routes/pro/get_user_profile_test.py
api/tests/test_flask_app.py

(BSR)[API] chore: use `@private_api` decorator for all PRO routes

---

api/src/pcapi/core/bookings/repository.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/educational/utils.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/repository.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/core/offerers/repository.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/models/has_address_mixin.py
api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py
api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
api/src/pcapi/routes/backoffice/offerers/validation_repository.py
api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/serialization/venues_serialize.py

Je teste des hybrid_properties plus propres

(BSR)[API] chore: better typing for some hybrid properties

---

api/.env.development
api/.env.testauto
api/src/pcapi/connectors/youtube.py
api/src/pcapi/settings.py
api/tests/connectors/youtube_test.py
api/tests/core/offers/test_api.py
pro/cypress/e2e/createIndividualOffer.cy.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38122)

(PC-38122)[API] feat: add backend for Youtube API client

---

api/src/pcapi/connectors/apps_flyer.py
api/src/pcapi/connectors/beneficiaries/educonnect/educonnect_connector.py
api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/fraud/utils.py
api/src/pcapi/core/mails/transactional/bookings/booking_withdrawal_updated.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/subscription/api.py
api/src/pcapi/core/users/models.py
api/src/pcapi/routes/auth/discord.py
api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py
api/src/pcapi/routes/native/v1/authentication.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38222)

(PC-38222)[API] refactor: normalize users models

---

pro/cypress/e2e/createIndividualOffer.cy.ts
pro/cypress/e2e/oaIndividualOffer.cy.ts

(BSR)[PRO] fix: test e2e video step

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/tests/routes/backoffice/accounts_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-38245
Sentry : https://pass-culture.sentry.io/issues/67075771/

(PC-38245)[BO] perf: avoid timeout on user account details page

---

api/bin/generate_script_file.py

(BSR)[API] doc: fix starting script

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20251003T084346_ce7379e58a5f_collective_offer_offer_venue_nullable.py
api/src/pcapi/alembic/versions/20251003T084506_4be9614ad8e3_collective_offer_remove_offer_venue.py
api/src/pcapi/alembic/versions/20251003T084640_be57eb4e814a_collective_offer_template_offer_venue_nullable.py
api/src/pcapi/alembic/versions/20251003T084746_5376ec9dfdf6_collective_offer_template_remove_offer_venue.py
api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/factories.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/educational/repository.py
api/tests/core/search/test_serialize_algolia.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38063)

(PC-38063)[API] feat: remove offerVenue column in collective offers

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/repository.py
api/src/pcapi/core/external/zendesk.py
api/src/pcapi/core/external_bookings/serialize.py
api/src/pcapi/core/finance/deposit_api.py
api/src/pcapi/core/fraud/api.py
api/src/pcapi/core/subscription/phone_validation/api.py
api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/eligibility_api.py
api/src/pcapi/core/users/factories.py
api/src/pcapi/core/users/gdpr_api.py
api/src/pcapi/core/users/models.py
api/src/pcapi/core/users/repository.py
api/src/pcapi/models/beneficiary_import.py
api/src/pcapi/models/validation_status_mixin.py
api/src/pcapi/notifications/sms/backends/sendinblue.py
api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/accounts/update_request_blueprint.py
api/src/pcapi/routes/backoffice/gdpr_user_extract/blueprint.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/offerers/validation_repository.py
api/src/pcapi/routes/backoffice/pro/blueprint.py
api/src/pcapi/routes/internal/e2e_ubble.py
api/src/pcapi/scripts/beneficiary/import_test_users.py

Toujours plus de ménage, cette fois dans User (et autres)
Ça soulève plein de pb de typing avec birth_date

(BSR)[API] feat: better typing for user hybrid properties

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/commands.py
api/tests/core/offers/test_api.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-38071)

(PC-38071)[API] feat: add command for `update_product_counts`

---

api/src/pcapi/core/highlights/factories.py
api/src/pcapi/core/highlights/models.py
api/src/pcapi/core/highlights/repository.py
api/src/pcapi/routes/pro/__init__.py
api/src/pcapi/routes/pro/highlights.py
api/src/pcapi/routes/serialization/highlight_serialize.py
api/tests/routes/pro/get_highlights_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/HighlightResponseModel.ts
pro/src/apiClient/v1/models/HighlightsResponseModel.ts
pro/src/apiClient/v1/services/DefaultService.ts

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37750)

(PC-37750)[API] feat: add GET highlights route

---

pro/yarn.lock

(BSR)[PRO] chore: update dependency

---

api/documentation/src/pages/change-logs.md
api/documentation/static/openapi.json
api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/public/documentation_constants/fields.py
api/src/pcapi/routes/public/individual_offers/v1/events.py
api/src/pcapi/routes/public/individual_offers/v1/serializers/events.py
api/src/pcapi/routes/public/individual_offers/v1/utils.py
api/tests/routes/pro/patch_draft_offer_test.py
api/tests/routes/public/individual_offers/v1/events/get_event_test.py
api/tests/routes/public/individual_offers/v1/events/patch_event_test.py
api/tests/routes/public/individual_offers/v1/events/post_event_test.py

[Ticket Jira](https://passculture.atlassian.net/browse/PC-37179)

(PC-37179)[API] feat: add video to post event offer

---

api/src/pcapi/models/feature.py
pro/cypress/e2e/createCollectiveOffer.cy.ts
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.spec.tsx
pro/src/components/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveEditionOfferNavigation/CollectiveEditionOfferNavigation.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferLayout/CollectiveEditionOfferNavigation/__specs__/CollectiveEditionOfferNavigation.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/BookableOfferSummary/BookableOfferSummary.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.spec.tsx
pro/src/pages/CollectiveOffer/CollectiveOfferSummary/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx

https://passculture.atlassian.net/browse/PC-36709

(PC-36709)[PRO]feat: delete wip enable new collective offer detail page
