- api/src/pcapi/core/offerers/validation.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/src/pcapi/use_cases/save_venue_bank_informations.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/pro/get_available_reimbursement_points_test.py
- api/tests/routes/pro/patch_venue_test.py
- api/tests/use_cases/save_venue_bank_informations_test.py
- pro/src/apiClient/v1/models/ReimbursementPointResponseModel.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16260
- Créer immédiatement un `VenueReimbursementPointLink` lorsqu'un dossier de CB est validé
- Vérifier que le lieu a bien a `pricingPoint` avant de le lier à un `reimbursementPoint`
- Edition de `SaveVenueBankInformations`
- Edition de `check_venue_can_be_linked_to_reimbursement_point()`
- Edition de `ReimbursementPointResponseModel` (supprimer des attributs superflus pour le front)
- Corriger la formulation d'erreurs remontées par la validation `check_venue_can_be_linked_to_reimbursement_point()`
> (PC-16260) edit venue DMS applications handling

- pro/testcafe/01_signup.js
```sh
✖ la balise script pour le tracking HubSpot est présente sur la page
(screenshots:
/home/circleci/pass-culture/pro/testcafe_screenshots/2022-07-21_10-16-47/test-4/Chrome_103.0.5060.134_Linux_0.0/errors/1.png)
1) AssertionError: expected false to be truthy
Browser: Chrome 103.0.5060.134 / Linux 0.0
Screenshot:
/home/circleci/pass-culture/pro/testcafe_screenshots/2022-07-21_10-16-47/test-4/Chrome_103.0.5060.134_Linux_0.0/errors/1.png
75 |test('la balise script pour le tracking HubSpot est présente
sur la page', async t => {
76 |  const trackingScript = Selector(
77 |    'script[src="//js.hs-scripts.com/5119289.js"]'
78 |  )
79 |
> 80 |  await t.expect(trackingScript.exists).ok()
81 |})
82 |
at <anonymous>
(/home/circleci/pass-culture/pro/testcafe/01_signup.js:80:41)
at …
```
> (BSR)[PRO] fix: testcafe/01_signup.js

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220721T124051_a7accb2d29db_new_eac_schema_payment.py
- api/src/pcapi/core/finance/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16318
- dans la tapble `payment` la colonne BookingId devien facultative, et la colonne collectiveBookingId apparait. Normalement cette table ne sert que d'archives mais l'ancien schema m'enpeche de faire le ménage dans les offres EAC.
> (PC-16318)[API] chore: adapt payment model to new eac schema

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
We had a "division by zero" error when a cashflow was linked to at
least one pricing of a free offer.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16366
> (PC-16366)[API] fix: Fix invoice generation with free offer

- api/tests/routes/pro/get_offerer_test.py
`session.expunge_all()` does not work as intended, `commit()` does.
Also, exhibit the extra SQL query that fetches venues when Pydantic
populates `GetOffererResponseModel.managedVenues`, even though we
overwrite that with our own joinedload'ed data. I tried to use an
alias to work around that but could not get it work (and still have
the field name `managedVenues` for API schema auto-generation).
> (BSR)[API] test: Better SQL queries check in `/offerers/<id>` route

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220725T135316_5311cec32519_fix_educational_institution_type_length.py
- api/src/pcapi/core/educational/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16203
- passage du champ educational_institution."institutionType" d'un VARCHAR(60) a un VARCHAR(80)
> (PC-16203)[API] fix: set the educational institution type field to 80 as there are data with length 68

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220726T101204_aed2f6174add_add_account_id_column_to_cds_cinema_details_table.py
- api/src/pcapi/connectors/cine_digital_service.py
- api/src/pcapi/core/booking_providers/api.py
- api/src/pcapi/core/booking_providers/cds/client.py
- api/src/pcapi/core/booking_providers/models.py
- api/src/pcapi/core/providers/factories.py
- api/src/pcapi/core/providers/models.py
- api/src/pcapi/core/providers/repository.py
- api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py
- api/tests/core/booking_providers/cds/test_client.py
- api/tests/core/booking_providers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16288
Ajout d'une colonne accountId dans la table cds_cinema_details, pour stock l'identifiant du compte des cinémas cds.
> (PC-16288)[API]: add cds account id column

- api/src/pcapi/connectors/dms/serializer.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15323
Erreur sentry : https://sentry.internal-passculture.app/organizations/sentry/issues/382141/events/aa17c015cdd54046afcd2590af6c722b/?project=5
Le type "Apprenti, Alternant, Volontaire en service civique rémunéré" vient d'être enlevé des choix du formulaire.
En revanche il faut bien ajouter collégien dans le code.
Labels dans le code : 
```
DMS_ACTIVITY_ENUM_MAPPING = {
"Collégien": users_models.ActivityEnum.MIDDLE_SCHOOL_STUDENT.value,
"Lycéen": users_models.ActivityEnum.HIGH_SCHOOL_STUDENT.value,
"Étudiant": users_models.ActivityEnum.STUDENT.value,
"Etudiant": users_models.ActivityEnum.STUDENT.value, # celui là est sûrement inutile mais je le laisse, dans le doute
"Employé": …
```
> (PC-15323)[API] fix: add dms activity choices

- .github/workflows/update-api-client.yml
Le cache n'est pas restauré entre les run du workflow de 2 PRs différentes, donc on perd du temps à éxécuter le post-cache à chaque workflow. En attendant de trouver une solution qui marche, je préfère retirer ce cache
> (BSR) ci: remove cache in update-api-client workflow

- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
The previous non-prod template (61) had errors that the prod template
did not have (a space was missing and there were too many decimals for
the reimbursement amount). The production template has thus been
copied over a new template (id 95) for the non-prod environments.
> (BSR)[API] feat: Update id for non-prod INVOICE_AVAILABLE_TO_PRO SendinBlue template

- pro/src/components/pages/SignIn/SignIn.tsx
- pro/src/components/pages/SignIn/__specs__/SignIn.spec.jsx
Lorsque le formulaire de login est en erreur, afficher l''erreur de l'api à l'utilisateur
> (BSR)[PRO] fix: Signin: display api errors

- backoffice/src/resources/PublicUsers/Components/FraudCheckCard.tsx
- backoffice/src/resources/PublicUsers/Components/FraudCheckStatusBadge.tsx
- backoffice/src/resources/PublicUsers/Components/ManualReviewModal.tsx
- backoffice/src/resources/PublicUsers/UserDetail.tsx
- backoffice/src/resources/PublicUsers/__specs__/BeneficiaryBadge.spec.jsx
- backoffice/src/resources/PublicUsers/__specs__/FraudCheckCard.spec.jsx
- backoffice/src/resources/PublicUsers/__specs__/FraudCheckStatusBadge.spec.jsx
- backoffice/src/resources/PublicUsers/__specs__/ManualReviewModal.spec.jsx
- backoffice/src/resources/PublicUsers/__specs__/StatusAvatar.spec.jsx
- backoffice/src/resources/PublicUsers/__specs__/StatusBadge.spec.jsx
- backoffice/src/resources/PublicUsers/types.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16103
Ajout du libellé du statut du fraud check.
- Remplacement du StatusAvatar par un nouveau composant IdCheckStatusBadge qui porte le picto et le label
- ajout d'un commit spécifique pour refactor  le nom `CheckHistory` par `IdCheck` qui colle mieux au métier.
- ajout d'un commit pour le "Nice to have" du ticket : affichage du json en <pre>
- ajout de tests sur certains composants qui n'en avaient pas encore
> Pc 16103 add fraud check textual status

- api/src/pcapi/routes/backoffice/accounts.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16095
ajout du status du user profiling dans l'historique d'inscription des utilisateurs
RAS
RAS
RAS technique_
> (PC-16095)[API] fix: add user profiling item to history

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220729T080301_4b549301f9f7_add_column_for_intervention_area.py
- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/core/educational/models.py
- Ajout d'une colonne `interventionArea` dans les tables `collective_offer` et `collective_offer_template` contenant une liste de département (par leur numero/code) décrivant la liste des départements ou les intervenant de cette offre peuvent se déplacer.
> PC-16429 create model for new intervention area in eac context

- .github/workflows/prepare-cache.yml
[La doc](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) de github-action stipule que pour des raisons de sécurité, le cache n'est pas partagé entre plusieurs PRs
On peut contourner le problème en cachant sur la branche main pour qu'il soit partagé avec les PRs
Ce workflow a pour but de tourner une fois par jour afin de set le cache pour les PRs de la journée. En cas d'invalidation du cache sur une PR à cause d'un changement de dépendances, alors le cache sera partiellement restauré
> (BSR) ci: create workflow to prepare cache on schedule

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16457
fix potential problem : stock.quantity < stock.dnBookedQuantity
could cause backend crash
- Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du …
> (PC-16457)[API] fix: CDS update_stock_to_match_provider_remaining_place

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
When there was a lot of bookings to price (which sometimes happens
during the day or just after we enable back the cronjob after having
stopped it for a few hours), `price_bookings()` took a lot of time on
the call to `db.session.commit()`. This is because SQLAlchemy had to
somehow update the session with a large number of objects. Calling
`price_booking()` (that includes the commit) could take up 1 or 2
seconds.
This commit is a quick, minimally changing hack that price bookings by
batches of 100, clearing the session after each batch.
> (BSR)[API] Optimisation dans `price_bookings()`

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
We used to base loops on the booking id. That was wrong. For example,
suppose that all bookings were sorted like this for pricing:
1, 4, 2, 3
With a batch size of 2, the first batch would be [1, 4]. The last id
being for, we would add a "id > 4" filter for the second batch. The
second batch would thus be empty.
Now we add a filter that uses the "composite key" with which bookings
are sorted: it's based on the "dateUsed", the date of the pricing
point link, the booking id, etc.
> (BSR)[API] fix: Fix looping in `price_bookings()`

- api/src/pcapi/scripts/handle_suspended_accounts_without_suspension_date.py
- api/tests/scripts/test_handle_suspended_accounts_without_suspension_date.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16456
Ajout d'un script permettant de corriger l'état de certains comptes : les passer de suspendus (à la demande de l'utilisateur) à supprimé.
D'anciennes versions de l'API inséraient des évènements de suspension avec un `eventDate` nul. Le problème est qu'aujourd'hui cette informations est toujours renseigné et que le code s'attend à ce qu'elle soit présente.
Ces suspensions de compte (à la demande de l'utilisateur) ont été réalisées il y a au minimum quelques mois et devraient donc être marqué comme supprimés s'il n'y a pas eu de réactivation entre temps.
Le script permet donc : 
1. d'identifier tous ces comptes ;
2. insérer un nouvel évènement de suspension pour chacun d'entre eux (suppression de compte).
Rappel : …
> (PC-16456)[API] feat:script: mark accounts as deleted

- api/src/pcapi/core/finance/api.py
This fixes an SQLAlchemy DetachedInstanceError in `_get_loop_query()`:
Instance <Booking at 0x7f38da3ef730> is not bound to a Session;
attribute refresh operation cannot proceed (Background on this
error at: https://sqlalche.me/e/14/bhk3)
> (BSR)[API] fix: Keep last booking in session for each loop of `price_bookings()`

- .circleci/config.yml
Envoyer une notification Slack de succès seulement après le succès du déploiement de chaque composant
Modification de la config CircleCI afin que le step `release-synthesis` requiert les précédents.
exemple de faux-positif:
> (BSR)[fix]ci: notify of deployment success when all deployments are OK

- api/src/pcapi/core/mails/transactional/bookings/booking_confirmation_to_beneficiary.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16405
Remonter la sous-catégorie au _template_ d'email de confirmation de réservation.
Et mise à jour de l'identifiant de _template_ (non prod).
Au passage : utilisation de l'id de la catégorie. Cela semble plus logique et plus sûr : on se sert uniquement de l'id dans le template, donc inutile de rajouter des informations inutiles (qui risquent de créer des erreurs de syntaxe ou des incompréhensions au moment de corriger le template via l'interface de SiB).
> [APi] PC 16405 add offer sub category

- .circleci/config.yml
If the cache of a frontend app is still valid at the CDN level,
this check could raise a false alarm.
> (BSR)[API] ci: edit deployment check failure message

- api/src/pcapi/templates/mails/offer_creation_notification_email.html
- api/src/pcapi/templates/mails/offer_creation_refusal_notification_email.html
- api/tests/emails/offer_creation_test.py
using VenueTypeCode column instead of VenueType table
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15529 …
> (PC-15529)[API] fix: venueTypeCode for offerer validation email

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx
If the new `ENABLE_NEW_BANK_INFORMATIONS_CREATION` feature flag is on,
we should not display the old business unit-related banner.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16578
> (PC-16578)[PRO] fix: Hide business unit banner on venue edition page if new FF is on

- api/src/pcapi/templates/admin/edit_many_offers_components/gcu_compatible_form.html
- api/tests/admin/custom_views/many_offers_operations_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16565
Ne pas griser le bouton « Rendre le produit et les offres incompatibles avec la GCU » si des offres sont actives (nouvelles ?) sur le produit déjà marqué incompatible.
détails dans les commentaires du ticket.
> (PC-16565)[API] fix: enable many offers deactivation even if product is already set as incompatible

- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/repository.py
- api/src/pcapi/routes/pro/finance.py
- api/src/pcapi/routes/serialization/finance_serialize.py
- api/tests/core/finance/test_repository.py
- api/tests/routes/pro/get_invoices_test.py
- api/tests/routes/pro/get_reimbursement_points_test.py
- pro/src/apiClient/v1/models/InvoiceListQueryModel.ts
- pro/src/apiClient/v1/models/InvoiceResponseModel.ts
- pro/src/apiClient/v1/services/DefaultService.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15702
Adapter les routes finance aux points de remboursement vs business unit
- ajout de la route `/finance/reimbursement-points`
- modification de la route `/finance/invoices`
N/A
N/A
> (PC-15702) edit finance routes for reimbursement points

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220803T153235_46ab023fbf0f_add_pricing_venue_id.py
- api/src/pcapi/alembic/versions/20220803T153725_934d0e50595f_add_fk_and_index_on_pricing_venue_id.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/models.py
- api/tests/core/finance/test_api.py
Commits à relire séparément, j'ai fait une mini-modification au
passage (qui n'affecte pas les performances).
---
The business unit-based SQL query in `_generate_cashflows()` was fast
because we filtered on `pricing.businessUnitId`, which has an index.
With reimbursement points, we did not use any index, so we JOINed a
lot of pricings with a lot of bookings. This took several seconds
for each reimbursement point to process.
This commit adds a `pricing.venueId` column with an index, on which
we can now quickly filter.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16633
> (PC-16633)[API] perf: Optimize `_generate_cashflows()` pricings query

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/native/v1/authentication.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/authentication_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15982
Permettre à un utilisateur dont le compte est suspendu (pour fraude ou à sa propre demande) ou supprimé de :
1. recevoir l'email _On se connaît, non ?_ lors de la création de compte si l'email existe déjà ;
2. modifier son mot de passe.
> [API] PC 15982 inactive users

- .github/workflows/prepare-cache-master.yml
- .github/workflows/prepare-cache-weekly.yml
- .github/workflows/update-api-client-template.yml
- .github/workflows/update-api-client.yml
Optimisation du workflow `Prepare cache master` pour qu'il ne soit trigger au merge sur master que si une dépendance (front ou back) a changé
> (BSR) ci: trigger prepare cache master only on dependency change

- pro/testcafe/helpers/navigations.js
We must check `location.pathname + location.search` in all cases.
Spotted by Romain.
> (BSR)[PRO] test: Better `navigateAfterVenueSubmit` testcafé helper

- pro/src/components/pages/Home/Offerers/MissingReimbursementPoints/MissingReimbursementPoints.tsx
- pro/src/components/pages/Home/Offerers/OffererDetails.jsx
- pro/src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx
- pro/src/components/pages/Home/Venues/VenueLegacy.jsx
- pro/src/components/pages/Home/Venues/__specs__/VenueLegacy.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16137
Affichage bannière jaune (ajouter votre coordonnées bancaires...) :
- Si au moins un lieu n'a pas de de point de remboursement 
CTA “Ajouter un RIB” (sur les lieux de la page d’accueil) 
-Affichage pour tous les lieux qui n’ont pas sélectionner ou ajouter de point de remboursement 
-Sauf les lieux numériques 
> (PC-16137)[PRO] feat: Home display yellow banner when missing reimbusement points

- pro/src/new_components/FormLayout/FormLayout.module.scss
- pro/src/new_components/FormLayout/FormLayout.stories.tsx
- pro/src/new_components/FormLayout/FormLayout.tsx
- pro/src/new_components/FormLayout/FormLayoutRow.tsx
- pro/src/new_components/FormLayout/FormLayoutRowWithInfo.tsx
..new_components/FormLayout
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14214
Ajout de la possibiliter d'avoir une colonnes à droite des champs dans le layout de nos formulaire.
Cette colonne doit etre utiliser pour placer les bulles d'aides:
> (PC-14214)[PRO] feat: add infobox column into..

- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16656
Ajout d'un champ `searchGroupNamev2` à une offre lors de la sérialisation : il s'agit du _search group name_ tiré du module `subcategories_v2`. Pour rappel : le champ `searchGroupName` provient lui du module `subcategories`.
On a besoin de ce nouveau champ parce l'app native utilise le search group name pour construire ses requêtes lors de la recherche notamment. Pour qu'elle soit en mesure d'utiliser la v2 des `sous-categories` (voir [PR précédente](https://github.com/pass-culture/pass-culture-main/pull/3052)), il faut lui donner la possibilité d'utiliser les v2 des search group name.
Avec le champ `searchGroupNamev2`, les dernières versions du front pourront reposer entièrement sur la v2 des sous-catégories, et …
> (PC-16656)[API] feat: add searchGroupId to offer serialization

- api/src/pcapi/models/feature.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/settings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16548 
Passer le _FF_ `ALLOW_ACCOUNT_UNSUSPENSION` à `True` par défaut.
**Au passage**
Refacto : dans certains tests, les appels à l'API sont sont explicitement dans la fonction de test, pas cachés dans une méthode-outil. C'est plus clair comme ça.
> [API] PC 16548 ff default to true

- .githooks/pre-commit
This happens if we only commit test files
Lien vers le ticket Jira : N/A
Eviter l'erreur suivante en cas de commit contenant uniquement des test:
```bash
Running mypy for type checking...
usage: mypy [-h] [-v] [-V] [more options; see below]
[-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Missing target module, package, files, or command.
```
- Ajout d'un IF
- None
- N/A
> (BSR) ci: do not run mypy if MYPY_FILES is empty

- api/src/pcapi/core/subscription/educonnect/api.py
- api/src/pcapi/core/subscription/messages.py
- api/tests/admin/custom_views/support_view_test.py
- api/tests/core/subscription/dms/test_api.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/saml/educonnect_test.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16175
Mettre à jour les formulations des messages d'activation de compte in-app 
- RAS
- RAS
- N/A
> PC-16175 subscription messages wordings update

- api/.flaskenv
- api/.gitignore
- api/.ipython/profile_default/ipython_config.py
- api/requirements.txt
1. Do not change the title of the terminal. "IPython: src/app" is not
particularly helpful (especially for those of us who customize
their terminal title with the environment they are on).
2. Do not reformat code with Black. It fails with an error on staging
and production.
3. Tweak color of the prompt as we used to do with the default Python
prompt.
> (BSR)[API] feat: Tweak IPython configuration

- api/src/pcapi/routes/pro/public_api/collective_offers.py
- api/src/pcapi/routes/serialization/public_api_collective_offers_serialize.py
- api/tests/routes/pro/openapi_test.py
- api/tests/routes/pro/public_api/get_collective_offers_categories_test.py
- api/tests/routes/pro/public_api/get_collective_offers_educational_domains_test.py
- api/tests/routes/pro/public_api/get_collective_offers_students_levels_test.py
- pro/src/apiClient/v2/index.ts
- pro/src/apiClient/v2/models/CollectiveOffersCategoryResponseModel.ts
- pro/src/apiClient/v2/models/CollectiveOffersDomainResponseModel.ts
- pro/src/apiClient/v2/models/CollectiveOffersListCategoriesResponseModel.ts
- pro/src/apiClient/v2/models/CollectiveOffersListDomainsResponseModel.ts
- pro/src/apiClient/v2/models/CollectiveOffersListStudentLevelsResponseModel.ts
- pro/src/apiClient/v2/models/CollectiveOffersStudentLevelResponseModel.ts
- pro/src/apiClient/v2/services/DefaultService.ts
Lien vers les tickets Jira : 
https://passculture.atlassian.net/browse/PC-16555
https://passculture.atlassian.net/browse/PC-16556
https://passculture.atlassian.net/browse/PC-16559
Implémenter les API des offres collectives : 
- liste des catégories (qui sont en dur dans le code)
- liste des domaines d'éducation (db)
- liste des publics cible (en dur dans le code)
Un commit par ticket.
La notion de cache, évoquée dans certains tickets, est le sujet du ticket PC-16561.
> Pc 16555 pc 16556 pc 16559 collective offers api

- api/src/pcapi/core/auth/api.py
- api/src/pcapi/core/permissions/utils.py
- api/tests/core/permissions/test_permissions_check.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16746
corriger une erreur Sentry dans le cas ou un appel est fait à l'API backoffice avec un token expiré
- RAS
- RAS
- RAS
> (PC-16746)[API] fix: fix backoffice API in case of expired token

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/templates/invoices/invoice.html
In reality, all invoices show a single cashflow. So this commit does
not fix any bug.
However, one of our test has an invoice with multiple cashflows. It
sometimes failed because the order of `invoice.cashflows` was not
reliable.
> (BSR)[API] test: Fix order of cashflows in PDF invoice

- api/src/pcapi/utils/requests.py
to reduce errors on ubble webhook ; the POST requests (called when starting ubble identification) are not impacted
Réduire le bruit sur sentry ["Could not update ubble workflow"](https://sentry.internal-passculture.app/organizations/sentry/issues/?environment=production&project=5&query=is%3Aunresolved+Could+not+update+Ubble+workflow&statsPeriod=14d), principalement dû à l'heure actuelle à des erreurs de connexion à l'api d'ubble. 
Il faut savoir qu'[ubble retente jusqu'à 2 fois](https://ubbleai.github.io/developer-documentation/#webhook) quand notre api [renvoie une erreur](https://github.com/pass-culture/pass-culture-main/blob/master/api/src/pcapi/routes/external/users_subscription.py#L54), donc a priori il n'y avait pas de souci fonctionnel.
> (BSR)[API] feat: add retry on ubble GET requests

- api/src/pcapi/use_cases/save_venue_bank_informations.py
- api/tests/core/logging/tests.py
- api/tests/use_cases/save_venue_bank_informations_test.py
There still are ongoing v3 applications. When they are validated, a
BankInformation object will be created (as it should), but we should
also create a new VenueReimbursementPointLink, just like we do when
processing a v4 application.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16776
---
+ 1 commit indépendant. **Donc commits à relire séparément.**
> (PC-16776)[API] feat: Link reimbursement point when processing a v3 applications

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/many_offers_operations_view.py
- api/src/pcapi/alembic/versions/20220802T130738_2967ed08d3e0_validation_type_cgu_incompatible_product.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/models/offer_mixin.py
- api/src/pcapi/templates/admin/edit_many_offers.html
- api/src/pcapi/templates/admin/edit_many_offers_components/gcu_compatible_form.html
- api/tests/admin/custom_views/many_offers_operations_view_test.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15048
- rejeter les offres liées lors du marquage d'un ISBN comme non conforme aux CGU (au lieu de les désactiver)
- modification de la fonction `deactivate_inappropriate_products` pour rejeter les offres au lieu de lesdésactiver (et renommage en `reject_inappropriate_products`)
- RAS
- Ajout de la valeur `CGU_INCOMPATIBLE_PRODUCT` à l'enum `validation_type`
> (PC-15048)[API] feat: reject offers related to a CGU-incompatible ISBN

- api/src/pcapi/models/offer_mixin.py
- api/src/pcapi/scripts/reject_cgu_incompatible_offers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15051
ajouter un script pour rejeter les offres liées à des produits qui ne respectent pas les CGU
- récupération des produits non compatibles avec le CGU
- pour chaque produit récupéré, rejet des offres liées
- une correction d'import dans `offer_mixin.py` qui fonctionnait "par accident"
- RAS
> (PC-15051)[API] feat: add a script to reject ineligible offers

- api/src/pcapi/core/users/external/__init__.py
- api/src/pcapi/core/users/external/models.py
- api/src/pcapi/core/users/external/user_automations.py
- api/src/pcapi/core/users/models.py
- api/tests/core/users/external/external_users_test.py
- api/tests/core/users/external/user_automations_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16708
Suite à une demande du marketing, on change la règle de l'attribut `is_former_beneficiary` envoyé à Batch et Sendinblue, pour que seuls les utilisateurs qui n'ont plus et n'auront plus de possibilité de recharge soient considérés comme ex-bénéficiaires.
Cela exclut donc tous les _underage beneficiaries_ qui ont encore la possibilité de demander un crédit 18 ans.
Plus de détails dans le ticket
Les ex-_underage_ qui n'ont pas demandé un crédit 18 ans à leur dix-neuvième anniversaire deviennent donc `is_former_beneficiary = True` à cet anniversaire, qui n'est pas sur une action. On enrichit donc l'automation de crédit expiré pour mettre à jour ces utilisateurs au bon moment.
Une fois déployé en production, un …
> (PC-16708)[API] feat: Batch/Sendinblue: New rule for is_former_beneficiary attribute

- api/src/pcapi/core/bookings/exceptions.py
- api/src/pcapi/scripts/booking/commands.py
- api/src/pcapi/scripts/booking/delete_cancelled_booking.py
- api/src/pcapi/scripts/install.py
- api/tests/scripts/booking/delete_cancelled_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15904
Ajout d'un script pour supprimer les réservations annulées sans remboursements liés. (Dans le but de supprimer par la suite la venue associé à ces remboursements)
> (PC-15904)[API] feat: add script to delete cancelled bookings

- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/native/v1/serialization/settings.py
- api/src/pcapi/routes/native/v1/settings.py
- api/tests/routes/native/v1/openapi_test.py
- api/tests/routes/native/v1/settings_test.py
Disabled by default.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16504
Créer un FF : `APP_ENABLE_COOKIES_V2`.
**Désactivé par défaut**.
> (PC-16504)[API] feat: add FF: APP_ENABLE_COOKIES_V2

- api/src/pcapi/routes/native/v1/offers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16901
Vérifier que l'offre est issue de la synchro CDS avant d'essayer de mettre à jour son stock.
> (PC-16901)[API] fix: fix update stock on non synchro cds offers

- helmfile.yaml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16900
Réactivation du flag `--wait` qui a sauté lors du passage à helmfile.
> [PC-16900] Activate wait flag again for helm upgrades

- api/rebuild_staging.sh
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16929
Plus besoin de truncate la table email dans le script rebuild_staging vu que la table n'existe plus.
> [PC-16929] Remove obsolete email table truncate

- api/src/pcapi/core/subscription/phone_validation/api.py
- api/tests/core/subscription/phone_validation/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16932
Avant : 
body.phoneNumber = "+33 6 82 10 10 10" => sms recipient = "33 6 82 10 10 10" => [Bad Request](https://sentry.internal-passculture.app/organizations/sentry/issues/392816/?environment=production&project=5&query=&statsPeriod=14d)
Maintenant : 
body.phoneNumber = "+33 6 82 10 10 10" => sms recipient = "33682101010" => Good Request
> (PC-16932)[API] fix: use formatted phone number to send sms

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16944
Utiliser l'image docker dont le tag est le tag git actuel s'il est disponible (pour les déploiements en staging/intégration/production)
> [PC-16944] Use tag to generate helm secrets value file

- .github/workflows/mypy-leaderboard.yml
~Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX~
Créer unleaderboard des résolveurs de mypy :partying_face: 
- Une github action récupère les infos au merge d'une PR dans master
- Puis envoie ça à une cloud task qui écris dans une google sheet
Exemple OK: https://github.com/pass-culture/pass-culture-main/runs/7914860417?check_suite_focus=true
- None
> Create github action for mypy leaderboard

- api/src/pcapi/core/offerers/api.py
- api/tests/core/offerers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16942
Permettre l'édition de lieu sans vérifier les CB de point de remboursement systématiquement
Correction de `update_venue()`
N/A
> (PC-16942) fix update venue

- api/src/pcapi/admin/custom_views/category_view.py
- api/src/pcapi/admin/custom_views/custom_reimbursement_rule_view.py
- api/src/pcapi/admin/custom_views/many_offers_operations_view.py
- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/core/categories/subcategories_v2.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/users/external/__init__.py
- api/tests/routes/adage_iframe/get_categories_test.py
- api/tests/routes/pro/get_categories_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16127
Ne plus utiliser l'id de la catégorie lors de la définition d'une sous-catégorie, mais directement la catégorie : cela évite d'avoir à vérifier que l'id correspond bien à une catégorie existante.
> Pc 16127 category id to category

- .circleci/config.yml
- api/.dockerignore
- api/Dockerfile
- api/pyproject.toml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16952
Utiliser l'image docker de pcapi pour exécuter les tests Circle CI plutôt que de remonter un contexte d'exécution à la main
> [PC-16952] Use pcapi docker image to run circle ci tests

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
- api/tests/core/finance/test_api.py
- api/tests/files/invoice/legacy_rendered_invoice.html
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16774
Ajouter en en-tête du justificatif du point de remboursement : 
- Le nom de la structure et son SIREN sous la forme “Nom de la structure - SIREN”
- Le nom du lieu porteur du point de remboursement avec son IBAN sous la forme “Nom du lieu porteur du point de remboursement - IBAN” (ici, c’est le nom d’usage du lieu qui apparaîtra s’il est disponible, sinon ce sera le nom du lieu)
> Pc 16774 pro add offerer name to invoice pdf header

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16952
L'ancienne commande dépendait de `xargs` dont les paramètres varient selon les images, cette commande plus récente n'en dépend pas.
> [PC-16952] Fix deploy rollout restart command

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16952
L'image alpine du sdk Google Cloud est 80% moins lourde que l'image full et permet de gagner 40 secondes par build. Par contre elle ne contient pas kubectl donc on continue d'utiliser l'image full pour le rollout restart.
> [PC-16952] Use cloud-sdk alpine image only for builds

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/fraud/ubble/constants.py
- api/src/pcapi/core/fraud/ubble/models.py
- api/src/pcapi/core/subscription/messages.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/tests/routes/external/user_subscription_test.py
'ove'=Optically Variable Elements score, score=0 means 'Document is probably a fake or a photocopy'
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16270
> (PC-16270)[API] feat: let user retry ubble after bad 'ove' score

- api/pyproject.toml
Ignorer un `Warning` (transformé en erreur) d'obsolescence introduit dans `urllib3==1.26.12`, en attendant que la lib tierce `requests-toolbelt` soit mise à jour.
Edition de `pyproject.toml`
- Une issue GH est ouverte dans le repo concerné: https://github.com/requests/toolbelt/issues/331
N/A
> (BSR)[API] tests: silence specific DeprecationWarning for urllib3

- pro/src/new_components/DialogBox/DialogBox.module.scss
- pro/src/new_components/ImportFromComputerInput/ImportFromComputerInput.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16622
Fix la modale permettant d'uploader une image 
- Suppression de la contrainte obsolète sur la taille du bouton 
- Ajout de la propriété `z-index = 1` pour la croix permettant de fermer la modal pour qu'elle reste tout le temps clicable
> (PC-16622)[PRO] fix: upload image modal css close button and upload link

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220819T120622_4df590d6ffb3_.py
- api/src/pcapi/connectors/dms/models.py
- api/src/pcapi/connectors/dms/serializer.py
- api/src/pcapi/core/fraud/common/models.py
- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/dms/repository.py
- api/src/pcapi/scripts/subscription/dms/handle_inactive_dms_applications.py
- api/tests/core/fraud/dms/test_api.py
- api/tests/core/subscription/dms/test_api.py
- api/tests/core/subscription/dms/test_repository.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16920
Rendre la gestion de dossiers DMS idemptotente pour pouvoir garder en parallèle le webhook et le cron
- Early return basés sur la datetime de dernière modification d'un dossier dans DMS
- None
- None
> PC-16920 make dms handling idempotent

- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17018
Supprimer les stocks des offres draft par le cron `clean_past_draft_offers`
> (PC-17018)[API] fix: delete stocks when delete draft offers

- .github/workflows/storybook.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17000
Corriger une typo dans la définition du workflow GH Storybook
> (PC-17000) fix: wrong path in storybook deploy definition

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/educonnect/api.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/native/v1/subscription_test.py
- api/tests/routes/saml/educonnect_test.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13624
Pour un flux plus cohérent : on n'enregistre les infos sur l'utilisateur que quand on va l'activer
> (PC-13624) refactor: save beneficiary information only when activating

- api/Dockerfile
Reverts pass-culture/pass-culture-main#3336
L'instruction `COPY [^tests]* .`  ne marche pas du tout comme on le pensait.
> Revert "[PC-17032] Copy sources in the right place directly"

- api/src/pcapi/templates/invoices/invoice.html
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16774
Modifier l'en tête des justificatifs de remboursements pour afficher le label "Point de remboursement" à la place de "IBAN"
- Commit(s) : …
> (PC-16774)[API] fix: modify invoice pdf header wording

- .github/workflows/update-api-client-template.yml
- adage-front/scripts/generate_api_client_local.sh
Comme sur PRO, pouvoir commit les changements API dans adage-front automatiquement
> (BSR) ci: update api client in adage-front

- pro/src/new_components/SummaryLayout/SummaryLayout.module.scss
testcafe n'arrivait pas à cliquer sur le lien car sa hauteur était de 0px (par contre je me demande pourquoi ça fonctionnait avant !)
> (BSR)[PRO] fix: e2e

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/offerer_tag_view.py
- api/src/pcapi/alembic/versions/20220823T083137_0502f0f2f72c_add_label_and_description_into_offerer_tag_table.py
- api/src/pcapi/core/offerers/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16760
Ajout de deux colonne (`label` et `description`) dans la table `offerer_tag` pour l'équipe data.
> (PC-16760)[API]: add label and description into offerer_tag table

- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/routes/pro/users.py
- api/src/pcapi/routes/serialization/users.py
- api/tests/routes/pro/patch_validate_email_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/ChangeProEmailBody.ts
- pro/src/apiClient/v1/services/DefaultService.ts
- pro/src/new_components/UserPhoneForm/validationSchema.ts
- pro/src/routes/EmailChangeValidation/EmailChangeValidation.tsx
- pro/src/routes/EmailChangeValidation/index.ts
- pro/src/routes/routes_map.tsx
- pro/src/screens/EmailChangeValidation/EmailChangeValidation.tsx
- pro/src/screens/EmailChangeValidation/README.md
- pro/src/screens/EmailChangeValidation/__specs__/EmailChangeValidation.spec.tsx
- pro/src/screens/EmailChangeValidation/index.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15858
Nous pouvons aujourd'hui modifier l'adresse email d'un pro à la validation d'un formulaire. On cherche à modifier ça et avoir le même porcess que pour les jeunes :
- envoi de 2 emails, un à l'ancienne et un avec un lien à la nouvelle adresse (PR précedente)
- validation de la nouvelle adresse au clic sur le lien dans le mail precedent. (ça se passe ici)
2 commits back : 
- Partage du model des routes de validation d'email entre jeune et pro (est-ce une bonne idée de partager ou je duplique?)
-  Ajout d'une route de validation de l'email
Commits front : 
- Ajout de la page de validation / refus du jeton
- Commit(s) : …
> (PC-15858)[API|PRO] feat: validate new pro email

- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/tests/local_providers/allocine_stocks_functions_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16235
Corriger la création d'un identifiant unique d'offer côté AlloCiné quand l'acteur culturel (le cinéma) n'a pas de Siret
> (PC-16235)[API] fix: fix allocine sync for venue without siret

- api/src/pcapi/scripts/reject_cgu_incompatible_offers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16708
Juste une petite condition pour que le script de rejet d'offres incompatibles ne soit pas interminable.
A été lancé en production avec cette modification ce matin.
Ne prend plus que 8 minutes quand il n'y a presque plus rien à rejeter.
> (PC-16708)[API] fix: optimize script which rejects incompatible offers

- .circleci/config.yml
- api/src/pcapi/connectors/dms/api.py
- api/src/pcapi/domain/demarches_simplifiees.py
Example of response:
{
'dossierModifierAnnotationText': {
'annotation': None,
'errors': [{'message': 'L’instructeur n’a pas les droits d’accès à ce dossier'}]
}
}
That denotes a problem in the configuration of the procedure. We'll be
happy to know that.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16765
> (PC-16765)[API] fix: Log error when updating DMS annotation fails

- api/.ipython/profile_default/ipython_config.py
By default, the IPython prompt shows a incrementing number:
In [1]: a = 1
In [2]: a
Out[2]: 1
That number does not seem very useful. Showing the environment instead
looks more interesting:
production❯ a = 1
production❯ a
1
--- 
Capture d'écran :
> (BSR)[API] feat: Show environment in IPython prompt instead of command number

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
It used to include all pricing lines and was thus quite large. Now it
only contains one line per reimbursement point and is thus much
smaller (< 1Mb). We don't need to compress the file anymore.
Also, we don't need `yield_per()` because only a few thousands rows
are returned.
> (BSR)[API] feat: Do not compress "payment_details.csv" finance file

- api/src/pcapi/core/finance/api.py
Not faster but easier to read.
> (BSR)[API] refactor: Use new `Pricing.venueId` in `_generate_cashflows()`

- api/src/pcapi/core/offerers/models.py
It's equivalent but more explicit.
> (BSR)[API] style: Use `contains()` instead of `overlaps()` on tsrange columns

- api/src/pcapi/core/users/external/sendinblue.py
- api/tests/core/users/external/user_automations_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17081
Réduire le temps que prend l'exécution des cron d'automatisation Sendinblue, en particulier "users-inactive-since-30-days-automation" suite à laquelle un timeout de la base de données crée une exception dans sqlalchemy au retour de fonction.
On n'attend plus que ce soit terminé (voir ticket)
Aussi quelques changements dans les logs pour « mettre aux normes ».
> (PC-17081)[API] fix: Reduce Sendinblue automations cron duration

- api/src/pcapi/routes/native/v1/bookings.py
- api/src/pcapi/routes/native/v1/serialization/bookings.py
- api/tests/routes/native/v1/bookings_test.py
booking.stock.offer.url was updated with booking.completedUrl. But booking.completedUrl is computed from offer.url. So we must not update the database object before all the objects have been serialized. Update the seralized object instead
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17062
> (PC-17062)[API] fix: update booking.offer.url only after serialization

- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/__init__.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/pro.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/pro_search_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16701
Première étape de la recherche d'acteurs culturels dans le nouveau backoffice : la recherche de comptes utilisateurs pro.
Similaire à la recherche des jeunes et grand public, on utilise les mêmes index.
Cadrage sur Notion :
https://www.notion.so/passcultureapp/Pr-sentation-recherches-avanc-es-avec-PostgreSQL-2d4a683e0e204dbbb43c7bcd904c076e
https://www.notion.so/passcultureapp/Strat-gie-tech-recherche-acteurs-culturels-e07b4437706c4d8985128265895e78fb
La recherche des jeunes et grand public a été modifiée car elle ne filtrait pas sur jeunes/pro, tout le monde pouvait apparaître dans les résultats.
- Commit(s) : …
> (PC-16701)[API] feat: New backoffice: search pro accounts

- api/src/pcapi/utils/requests.py
We have a non-zero (though not unacceptable) error rate on this API.
Since it's safe and easy to retry requests, let's do that.
> (BSR)[API] feat: Retry requests on Insee Sirene API upon error

- api/src/pcapi/core/subscription/dms/api.py
- api/tests/core/subscription/dms/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16753
Aussi nmettre à jour les éventuels messages d'erreurs du fraud check quand on reçoit une update
- None
> (PC-16753)[API] fix: reset error messages in fraud check when receiving an update

- api/requirements.txt
- api/src/pcapi/admin/validators.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/subscription/phone_validation/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/external/zendesk.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/models/user_session.py
- api/src/pcapi/repository/user_session_queries.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/serialization/base.py
- api/src/pcapi/routes/serialization/users.py
- api/src/pcapi/utils/phone_number.py
- api/tests/routes/native/v1/account_test.py
- api/tests/utils/phone_number_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17027
valider et formater les numéros de tel attribués à des DOM
- chaque numéro de téléphone est maintenant testée avec chacune des régions téléphoniques de France (Guadeloupe, Martinique, Guyane, Réunion, Saint Pierre et Miquelon,  Mayotte et métropole) avant d'être considéré comme invalide.
- Plus la peine de spécifier une région quand on enregistre un numéro de tel puisque toutes les régions autorisées seront testées
- Lé numéro de révision du paquet `phonenumberslite` n'est plus fixé pour permettre à d'éventuelles corrections et modification des plans de numérotations d'être prises en compte
RAS
- Commit(s) : …
> (PC-17027)[API] fix: fix DOM phone numbers formating

- api/src/pcapi/core/booking_providers/cds/client.py
- api/tests/core/booking_providers/cds/test_client.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17146
Problème résolu : lors du booking des tickets de cinéma, nous n'envoyons pas le montant des différentes réservations dans le dictionnaire payementCollection. N.B: Il faut envoyer autant d'éléments de payment dans payementCollection que de ticket à réserver.
- _A destination des Data Analysts, exposer le résultat final (tables et colonnes), sans détailler …
> (PC-17146)[API] fix: CDS transaction amount when booking ticket

- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_to_pro.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary.py
- api/src/pcapi/core/mails/transactional/bookings/booking_postponed_by_pro_to_beneficiary.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_test.py
- api/tests/core/mails/transactional/bookings/booking_postponed_by_pro_to_beneficiary_test.py
Also, raise an exception if a booking has no individual nor
educational booking. (We should probably have a database constraint
for this, but since these relationships will be removed, I don't see
much point in doing it now.)
`Booking.firstName` and `lastName` may still return None because
`EducationalRedactor` columns of the same name are nullable.
> (BSR)[API] chore: Fix typing of Booking.email and Booking.userName

- api/src/pcapi/scripts/subscription/dms/import_dms_applications.py
- api/tests/scripts/subscription/import_all_dms_applications_test.py
Currently running the script locally against prod-like data to have an idea of the time it would take
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16753
Premier run plus permissif pour éviter "0 dossiers trouvés" comme ça arrive en testing pour la procédure des étranger et en staging
- N/A
- None
- None
> (PC-16753)[API] feat: allow broader first run when importing dms applications

- api/src/pcapi/core/search/__init__.py
- api/tests/core/search/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17158
Éviter des N+1 lors de la réindexation des offres et des lieux.
Pour ce qui est des lieux, lors de la sérialisation on regarde si le lieu a au moins une offre indexable et ce calcul génère une requête. Je n'ai pas cherché à améliorer cet aspect parce que cela m'a l'air d'être plus compliqué qu'ajouter de simples `joinedload`.
Cette PR a pour but d'avoir une base de code à tester en situation réelle. Il faut d'abord vérifier que cette amélioration en est vraiment une : si la requête est trop lourde on évite les N+1 mais on pourrait y perdre (beaucoup).
> (PC-17158) indexing add joinedload

- api/src/pcapi/connectors/beneficiaries/educonnect/educonnect_connector.py
- api/src/pcapi/connectors/beneficiaries/educonnect/models.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/subscription/educonnect/api.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16031
Educonnect a un nouveau champ `civility` dans son vecteur identité. On l'enregistre donc aussi chez nous
- RAS
- None
- None
> PC-16031 get gender from educonnect

- api/src/pcapi/admin/custom_views/admin_user_view.py
- api/src/pcapi/admin/custom_views/partner_user_view.py
- api/src/pcapi/admin/custom_views/pro_user_view.py
- api/src/pcapi/core/mails/transactional/pro/email_validation.py
- api/src/pcapi/core/mails/transactional/pro/reset_password_to_pro.py
- api/src/pcapi/core/users/models.py
Non-nullable constraints are not taken in account (*), so mypy thought
that `Token.value` was optional. Let's make its type explicit.
(*) https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html#introspection-of-columns-based-on-typeengine
> (BSR)[API] chore: Specify type of Token.value

- api/src/pcapi/core/subscription/ubble/archive_past_identification_pictures.py
- api/src/pcapi/scripts/install.py
- api/src/pcapi/scripts/ubble_archive_past_identifications.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16993
Ajouter une commande qui permette de relancer l'upload des images Ubble à archiver pour rattraper celles qui n'ont pas été archivées en cas d'erreur côté ubble.
La commande sera lancée par un cron qui se déclenchera chaque nuit.
- ajout d'une commande `archive_past_identifications` qui pourra être lancée manuellement avec des paramètres spécifiques.
- ajout d'une commande `archive_past_identifications_automation` qui sera appelé par le cron.
> (pc-16993)[API] feat: add achive ubble pictures command

- .circleci/config.yml
- .githooks/pre-commit
- api/pyproject.toml
- api/src/pcapi/core/educational/api.py
~Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX~
J'ai découvert l'option `--warn-redundant-casts` qui m'a l'air d'être une bonne idée
J'ai run mypy sur pcapi avec l'option, qui a trouvé un warning, et qui permet de supprimer 3 lignes de code mort
- N/A
- Je retire `--show-error-codes` de la config de circle et du pre-commit hook, parce que c'est redondant avec pyproject.toml
- None
> (BSR)[API] ci: warn when redundant cast is used for mypy

- api/src/pcapi/scripts/subscription/dms/import_dms_applications.py
On production, we (almost) always have applications to process. If we
find none, there probably is a problem somewhere and we should be
notified. Outside production, we have few applications (and sometimes
none at all): this is a normal situation that does not warrant an
error entry in Sentry.
> (BSR)[API] feat: Lower log level when there is no DMS beneficiary application to process

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
We used to ignore (and not price) bookings that already had a
cancelled pricing. This was wrong. If a booking is used (and hence
priced), it may be marked as unused (and its pricing is cancelled),
and then used again, in which case we should price it.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16479
> (PC-16479)[API] fix: Price booking that has been unused and used again

- api/src/pcapi/core/users/external/zendesk_sell.py
- api/src/pcapi/tasks/zendesk_sell_tasks.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15943
Les cloud tasks pour Zendesk Sell ne reçoivent pas bien les offerer_id ou venue_id à partir du body (qui contient bien l'id) :
https://sentry.internal-passculture.app/organizations/sentry/issues/394959/?project=5&referrer=slack
Donc je tente de faire la manière la plus répandue dans le code, avec un objet pydantic.
Les cloud tasks ne peuvent pas être testées en environnement de développement
> (PC-15943)[API] fix: Zendesk Sell cloud tasks

- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/native/v1/settings.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16824
Ajout du FF ENABLE_NEW_IDENTIFICATION_FLOW permettant l'activation d'un nouveau parcours d'inscription sur l'application Jeunes.
Création du ticket visant à le supprimer lorsque le parcours sera adopté par tous. 
https://passculture.atlassian.net/browse/PC-17223
> (PC-16824) feat: add new identification flow flag

- api/src/pcapi/core/users/external/zendesk_sell.py
- api/src/pcapi/tasks/zendesk_sell_tasks.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15943
Ajouter des traces de debug pour essayer de comprendre pourquoi les tâches Zendesk Sell ne marchent pas.
Ce code est destiné à être déployé sur testing puis à être retiré une fois le problème compris et/ou résolu.
Erreur Sentry :
https://sentry.internal-passculture.app/organizations/sentry/issues/394959/events/c17b0750a47149f788fe52b30d2f5b85/?project=5
> (PC-15943)[API] debug Zendesk Sell

- api/src/pcapi/routes/backoffice/accounts.py
- api/tests/routes/backoffice/accounts_test.py
- backoffice/src/resources/PublicUsers/UserDetail.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16802
Afficher toutes les informations du parcours d’inscription, même si le compte est suspendu ou si rien n’est enregistré en base. Pour que le support puisse savoir quoi faire/répondre.
> (PC-16802)[BO-FRONT] fix: always show user details

- api/bin/pgcli-wrapper.sh
- pc
A wrapper around pgcli that:
- defaults to $DATABASE_URL if no argument is given;
- disables automatic LIMIT;
- disables startup and exit messages;
- sets a colored prompt that clearly distinguishes when you're on
your development machine or on production.
See code comments for the rationale.
---
> (BSR)[API] feat: Add wrapper around pgcli

- api/src/pcapi/core/bookings/api.py
The `PRICE_BOOKINGS` feature flag is now only used to disable the cron
job.
> (BSR)[API] feat: Remove condition on PRICE_BOOKINGS in mark_as_unused

- api/src/pcapi/core/booking_providers/models.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/payments/models.py
- api/src/pcapi/core/providers/models.py
- api/src/pcapi/core/users/models.py
The "PcObject" base class defines an "id" primary key column. We can
remove the redefinition of this column from classes that inherit from
"PcObject", when the redefined column is the same.
> (BSR)[API] chore: Remove redundant definition of "id" column from database models

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220909T094309_992529bd24e5_drop_recredit_constraint.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17129
2 problèmes : 
- il y a une check constraint qui nous empeche de mettre une autre valeur dans recreditType
- il y a une limite du nombre de caractères fixée à 11
> (PC-17129) Drop and bypass recredit.recreditType constraints

- pro/src/components/layout/inputs/PeriodSelector/PeriodSelector.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16208
Empêcher le flip du composant date-picker pour faire en sorte que le calendrier s'ouvre toujours en bas du champs de saisie. 
(voir l'exemple du comportement posant problème dans le ticket)
[Documentation du composant](https://popper.js.org/docs/v2/modifiers/flip/) `Popper` utiliser par `react-datetpicker`
> (PC-16208)[PRO] fix: force calendar to always open at input bottom

- pro/src/new_components/VenueForm/Informations/Informations.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16642
Rendre le champ `Nom du lieu` non editable dans le formulaire édition du lieu
> (PC-16642)[PRO] fix: venue name should be readonly in venue edition

- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/core/finance/exceptions.py
- api/src/pcapi/core/finance/validation.py
- api/src/pcapi/core/offers/api.py
- api/tests/admin/custom_views/venue_view_test.py
- api/tests/conftest.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17110
Pouvoir modifier le SIRET d'un lieu, en tenant compte de la nouvelle modélisation
- Edition de la vue FA
- traiter correctement les échecs d'updates de DB
- extraire la validation du format de SIRET
- ne pas logger des avertissements superflus
- ajouter un kwarg `follow_redirects` au client de test afin de pouvoir tester la réponse finale
> (PC-17110) edit venue siret in FA

- pro/src/ui-kit/form/TextInputAutocomplete/TextInputAutocomplete.module.scss
- pro/src/ui-kit/form/TextInputAutocomplete/TextInputAutocomplete.stories.tsx
- pro/src/ui-kit/form/TextInputAutocomplete/TextInputAutocomplete.tsx
- pro/src/ui-kit/form/TextInputAutocomplete/__specs__/TextInputAutocomplete.spec.tsx
- pro/src/ui-kit/form/TextInputAutocomplete/index.ts
- pro/src/ui-kit/form/shared/AutocompleteList/AutocompleteList.tsx
- pro/src/ui-kit/form/shared/AutocompleteList/type.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17206
Ajouter un composant TextInput permettant d'utiliser l'autocomplete avec source personnalisée.
Ce nouveau composant est basé sur l'implémentation de `SelectAutocomplete`, mais avec des fonctionnalités différentes
- Ajout d'un type `IAutocompleteItemProps` pour passer des data autres que le `label` et la `value` d'une option
- Ajout d'un `onSelectCustom` permettant d'ajouter une action à réaliser lorsque l'utilisateur choisi une donnée dans la liste déroulante
- Ajout du comportement qui fait que l'utilisateur ne peut pas entrer une valeur qui n'est pas issue de la liste des suggestions (voir `lastSelectedValue`)
- …
> (PC-17206)[PRO] feat: add input text autocomplete component

- api/src/pcapi/connectors/cine_digital_service.py
- api/src/pcapi/connectors/notion.py
- api/src/pcapi/infrastructure/repository/stock_provider/provider_api.py
- api/src/pcapi/local_providers/provider_manager.py
- api/tests/connectors/api_cine_digital_service_test.py
But : Grouper [les erreurs remontées sur sentry](https://sentry.internal-passculture.app/organizations/sentry/issues/?environment=production&project=5&query=is%3Aunresolved+Could+not+synchronize+venue+provider&statsPeriod=14d) dues au log *"Could not synchronize venue provider"*
Avant cette PR remontent les *issues* : 
- *Issues* liée à des problèmes de connexion
- `ReadTimeOut`
- `SSLError`
- `ConnectTimeout`
- ...
- Les `ProviderAPIException` -> majoritairement des 404. Si un autre code que 404 se produit, je pense qu'on n'est pas notifié
- Les `CineDigitalServiceAPIException`, qui peuvent être liées à des erreurs de connexion (c'est le cas quand on zoome sur les 2 qui sont présentes) ou alors a des codes de réponses >= 400.
- Toute autre exception
Après cette PR on aura : 
- 1 *issue* …
> (BSR)[API] sentry: merge provider synchronization exceptions

- pro/src/ui-kit/form/TextInputAutocomplete/TextInputAutocomplete.tsx
- pro/src/ui-kit/form/TextInputAutocomplete/__specs__/TextInputAutocomplete.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17206
Fix un test flacky lors du clic en dehors du menu des suggestions
- Ajout d'un bouton dans le test pour le click en dehors du menu déroulant (le click sur document.body semble avoir un comportement non souhaité)
- Refactodu code sur l'affichage ou non du menu lorsque la recherche change pour éviter d'avoir à utiliser un timeout
> (PC-17206)[PRO] fix: fix flacky test

- api/src/pcapi/core/subscription/dms/api.py
- api/tests/core/subscription/dms/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16263
Construire les annotations sur une ligne, car DMS ne les présente pas en multi lignes
- RAS
- J'en profite pour mettre à jour le fraud check au moment où on change l'annotation, comme ça on est à jour
- None
> PC-16263 build annotation on one line

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/tests/routes/pro/delete_thumbnail_test.py
- api/tests/routes/pro/post_thumbnail_test.py
- pro/src/apiClient/v1/services/DefaultService.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17271
Ajout de la suppression de thumbnail pour les offres. Reproduction de ce qui est fait pour les lieux
Pour avoir un peu d'historique, il était possible d'avoir plusieurs mediations, aujourd'hui uniquement la plus récente [est utilisée](https://github.com/pass-culture/pass-culture-main/blob/fef61af9f1d1a583d78cc64d16caf53eb0263f39/api/src/pcapi/core/offers/models.py#L589). 
[Un script](https://github.com/pass-culture/pass-culture-api/blob/master/api/src/pcapi/scripts/delete_unused_mediations_and_assets.py) était passé pour nettoyer les mediations supperflues, il en reste. 
On pourrait faire un nettoyage en modifiant la synchro titelive pour n'enregistrer que la thumb intéressante, supprimer les mediations non …
> (PC-17271)[API] feat:  new delete offer thumbnail route.

- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/routes/backoffice/__init__.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16002
Ajout d'un endpoint permettant d'afficher le contenu de l'onglet « Comptes rattachés » dans le détail d'une structure dans le nouveau backoffice. Il s'agit donc ici de récupérer les utilisateurs reliés à la structure (prénom, nom, email).
Les mêmes fichiers et permission que la PR https://github.com/pass-culture/pass-culture-main/pull/3517 (actuellement en revue) sont ajoutés dans cette PR, car il s'agit du même écran.
> (PC-16002)[API] feat: New backoffice: offerer details: get attached users

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/__specs__/VenueEdition.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/ReimbursementPoint/ReimbursementPoint.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17361
La valeur de de l'attribut`reimbursementPointId` dans le body de la requête d'édition de lieu doit être `null` quand aucun point de remboursement est sélectionné.
> (PC-17361)[PRO] fix: Fix validate venue edition error when venue doesn't have reimbursementPoint

- api/src/pcapi/core/offerers/validation.py
- api/tests/core/offerers/test_api.py
Only reimbursementPointId should be editable
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16425
Limiter, côté back, les attributs qui sont modifiables pour un lieu numérique; à ce jour, seulement le `reimbursementPointId`.
- Modification de la fonction de validation `check_venue_edition()`
- On a temporairement laissé businessUnitId dans la liste des attributs modifiables, même si on ne s'en sert plus. Le nettoyage sera fait dans un autre ticket.
> (PC-16425)[API] feat: prevent Virtual Venue edition of most attributes

- api/src/pcapi/models/feature.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17342
Ajout un feature flag pour la nouvelle fonctionnalité permettant d'afficher les statistiques d'une structure sur le portail pro
Nom du FF : `ENABLE_OFFERER_STATS`
> (PC-17342)[API] feat: add ff for offerer stats feature

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/ubble/archive_past_identification_pictures.py
- api/tests/core/subscription/ubble/test_archive_past_identification_pictures.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17411
Corriger https://sentry.passculture.team/organizations/sentry/issues/392943/events/latest/?environment=production&project=5&referrer=slack
- …
> (PC-17411)[API] fix: avoid calling ubble with deprecated fraud check ids

- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/ubble/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17192
Harmoniser les règles d'acceptation des dossiers Ubble sur celles de DMS
- cf. ticket
- None
- None
> PC-17192 allow ubble activation when process started before 19yo

- api/src/pcapi/core/users/external/sendinblue.py
- api/src/pcapi/core/users/external/user_automations.py
- api/src/pcapi/routes/external/__init__.py
- api/src/pcapi/routes/external/sendinblue.py
- api/src/pcapi/settings.py
- api/src/pcapi/tasks/cloud_task.py
- api/tests/core/users/external/sendinblue_test.py
- api/tests/core/users/external/user_automations_test.py
- api/tests/routes/external/sendinblue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17336
Raccourcir fortement la durée d'exécution des cron d'automatisation Sendinblue.
- ne plus vider les listes avant d'envoyer les contacts
- recevoir la notification de fin d'ingestion des contacts dans un webhook
Voir le ticket pour la description complète des idées évoquées.
> (PC-17336)[API] fix: Rework Sendinblue automation process to help cron return quickly

- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/tests/admin/custom_views/offer_view_test.py
- api/tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17433
Corriger une erreur serveur (500) reportée par Sentry :
Unexpected error on method=GET url=https://backend.passculture.pro/pc/back-office/venue_for_offerer/?id=286: NoResultFound('No row was found when one was required')
https://sentry.passculture.team/organizations/sentry/issues/395668/?project=5&referrer=slack
> (PC-17433)[API] fix: NoResultFound exception when requesting venue_for_offerer with wrong id

- pro/src/components/pages/Home/Homepage.tsx
- pro/src/components/pages/Home/OffererStats/OffererStats.tsx
- pro/src/components/pages/Home/OffererStats/index.ts
- pro/src/components/pages/Home/__specs__/Homepage.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17317
Ajout de la section Statistiques sur la homepage conditionné par l'activation du FF `ENABLE_OFFERER_STATS`
#
> (PC-17317)[PRO] feat: add offerer stats section on homepage

- pro/src/components/pages/Home/OffererStats/OffererStats.module.scss
- pro/src/components/pages/Home/OffererStats/OffererStats.tsx
- pro/src/routes/OffererStats/OffererStats.tsx
- pro/src/routes/OffererStats/index.ts
- pro/src/routes/routes_map.tsx
- pro/src/screens/OffererStats/OffererStatsScreen.tsx
- pro/src/screens/OffererStats/index.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17319
Dans la section statistiques de la homepage : 
- Ajouter un bouton permettant d'accèder à la page des satistiques d'une structure
> (PC-17319)[PRO] feat: add view offerer stats button on homepage

- pro/src/routes/OfferIndividualWizard/Summary/serializer.ts
- pro/src/screens/OfferIndividual/Summary/OfferSection/OfferSection.tsx
- pro/src/screens/OfferIndividual/Summary/__specs__/Summary.spec.tsx
- pro/src/screens/OfferIndividual/Summary/__specs__/Summary.tracker.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14229
_bug sur summary :
> l'url des offres numériques s'affichait dans la section lien externe
> le lien externe n'était pas affiché
> il n'y avait pas de section pour l'url des offres numériques
> (PC-14229)[PRO] fix: offer and external urls in summary

- api/src/pcapi/core/testing.py
Correction du typage des mots-clés du décorateur de contexte `override_features`, surtout pour éviter que mon IDE s'émeuve à chacune de ses utilisations.
> (BSR)[API] refactor: edit kwargs typing of override_features()

- api/src/pcapi/alembic/CONTRIBUTING.md
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/repository.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/core/subscription/test_api.py
- api/tests/core/subscription/ubble/end_to_end/requests_data.py
- api/tests/core/subscription/ubble/end_to_end/test_subscription_via_ubble.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15683
Pour démarrer une session Ubble, il faut envoyer le prénom et le nom de l'utilisateur (pour des raisons de sécurité).
Aujourd'hui on envoie à Ubble `user.firstName`, et `user.lastName` qui peuvent avoir été hydratés de deux manières : 
- soit par un résultat Ubble / DMS / Educonnect, au moment où on active le compte bénéficiaire de l'utilisateur.
- soit via l'étape de ProfileCompletion : si `user.firstName`, et `user.lastName` ne sont pas encore définis, on hydrate ces champs avec les données du formulaire. Cette condition est importante car si l'utilisateur a déjà fait un pass 15-17 et a maintenant 18 ans, on ne veut pas overrider le prénom et le nom validés par Ubble (ou DMS) avec les informations …
> (PC-15683) ubble names from profile

- pro/src/ui-kit/InfoBox/InfoBox.module.scss
Fix bug introduced in this [commit](https://github.com/pass-culture/pass-culture-main/pull/3376/commits/9fdf265f6b48fd7e28b976126e699e17f1469cc4#diff-f0feee59f9e7ffc26bda218f4d764f450ce9fbc5a1eca812dc6092e9cde42c4a) because of `height: auto`
> (BSR)[PRO] fix: button link margin top

- pro/src/components/pages/Home/Homepage.tsx
- pro/src/components/pages/Home/HomepageBreadcrumb.jsx
- pro/src/components/pages/Home/OffererStats/OffererStats.tsx
- pro/src/components/pages/Home/__specs__/Homepage.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17321
Ajouter l'étape statistiques dans le breadcrum de la homepage qui redirige vers l'ancre de la section associée plus bas dans la page.
> Pc 17321 pro add offerer stats anchor to homepage

- pro/src/screens/OfferEducationalStock/OfferEducationalStock.module.scss
- pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
- pro/src/ui-kit/form/RadioButton/RadioButton.module.scss
- pro/src/ui-kit/form/RadioButton/RadioButton.tsx
- pro/src/ui-kit/form/RadioGroup/RadioGroup.module.scss
- pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17558
Supprimer les séparateurs de la page stock (création d'offre collective)
- Supression du séparateur
- Ajustement des marges (notamment suppression d'une marge inutile sous les radio-buttons)
<p float="left">
</p>
> (PC-17558)[PRO] feat: remove separator on offer educational stock screen

- api/src/pcapi/core/offers/models.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/src/pcapi/routes/serialization/serializer.py
- api/src/pcapi/utils/date.py
- api/tests/core/offers/test_models.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/routes/serialization/serializer_test.py
- pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.create.spec.jsx
- pro/src/core/Offers/adapters/getOfferIndividualAdapter/__specs__/useGetIndividualOffer.spec.ts
- pro/src/routes/OfferIndividualWizard/__specs__/OfferIndividualWizard.spec.tsx
- pro/src/store/selectors/data/__specs__/mockState.json
It was used in the old web app. Now it's not used anywhere anymore.
> (BSR)[API] chore: Remove unused Offer.dateRange 

- pro/src/routes/OfferIndividualWizard/__specs__/OfferIndividualWizardAdmin.spec.tsx
Remove mention of `dateRange` (follow-up of c77cb3251d20c41a3bbfa8b4).
Apparently I cannot grep...
> (BSR)[API] chore: Remove unused `Offer.dateRange` (part 2)

- pro/src/new_components/TutorialDialog/TutorialDialog.tsx
fix against: ddda93d1
Slack 
> Thomas a relevé un bug pendant la recette sur le portail pro : à la 1ère connexion pour les structures non validées, la pop up tuto de la page d'accueil des acteurs culturels s'affiche à chaque changement de page.
> (PC-17585)[PRO] fix: tutorial display

- api/src/pcapi/core/users/external/sendinblue.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17336
Corriger l'appel  à Sendinblue dans les automatisations.
L'appel à url_for ne fonctionne pas sur staging (contexte des tâches GCP) à cause de SERVER_NAME.
Erreurs Sentry : 
https://sentry.passculture.team/organizations/sentry/issues/395852/?referrer=slack
https://sentry.passculture.team/organizations/sentry/issues/395678/?referrer=slack
https://sentry.passculture.team/organizations/sentry/issues/395853/?referrer=slack
https://sentry.passculture.team/organizations/sentry/issues/395854/?referrer=slack
https://sentry.passculture.team/organizations/sentry/issues/395857/?referrer=slack …
> (PC-17336)[API] fix: Sendinblue automation webhook URL

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220922T123207_6858182908fe_delete_enable_phone_in_stepper_flag.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/models/feature.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17496
Retrait du FF ENABLE_PHONE_VALIDATION_IN_STEPPER de la base de code.
- Suppression du FF via l'ajout d'une migration post de suppression du FF
> (PC-17496)[API] feat: remove ENABLE_PHONE_VALIDATION_IN_STEPPER 

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220926T082205_685f32d7cb22_user_validated_birth_date.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/payments/api.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/external/__init__.py
- api/src/pcapi/core/users/external/models.py
- api/src/pcapi/core/users/external/zendesk.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/core/users/utils.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/scripts/payment/user_recredit.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/tests/core/users/external/external_users_test.py
- api/tests/core/users/test_api.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16955
Le but est de garder la trace de la date de naissance déclarée par l'utilisateur lors de l'inscription, pour des raisons de debug, de suivi et de lisibilité.
Aujourd'hui cette date de naissance est écrasée par la date de naissance "validée" par Ubble, Educonnect ou DMS.
Stratégie : 
- [ce ticket] ajout de la propriété `validatedBirthDate` et d'une propriété `user.birth_date` qui retourne la date validée (en priorité) ou la date déclarée
- [PC-17174] rattrapage des données + ne pas écraser user.dateOfBirth + utiliser `validatedBirthDate` dans la recherche de doublons
- Ajout de la colonne `user.validatedBirthDate`
- …
> (PC-16955) Add user validated birth date

- api/src/pcapi/routes/error_handlers/generic_error_handlers.py
see this sentry issue https://sentry.passculture.team/organizations/sentry/issues/395899/?project=5&referrer=slack
> (BSR)[API] fix: catch werkzeug_exceptions.BadRequest when decoding requests with 429 status code

- .circleci/config.yml
Lien vers les conversations Slack
https://passcultureteam.slack.com/archives/C01CKL7LM6X/p1663578627261009
https://passcultureteam.slack.com/archives/C01CKL7LM6X/p1663773697314929
Restaurer la vérification de la couverture de tests sur le code modifié
> (BSR)[PRO] ci: reset coverage check on modified code

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/subscription/api.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
we don't want to downgrade a FraudCheck from OK to KO, which may be the case on concurrent Ubble webhook requests. (see this [issue on sentry](https://sentry.passculture.team/organizations/sentry/issues/394934/?environment=production&project=5&query=is%3Aunresolved+Deposit&statsPeriod=14d) and [this discussion](https://passcultureteam.slack.com/archives/C02RQP7APRA/p1663756354784269)). 
In that case, we used to override fraud_check with KO status and ALREADY_HAS_ACTIVE_DEPOSIT + ALREADY_BENEFICIARY reason codes. Now we will let a OK result, but the beneficiary role or another deposit wont be given again thanks to check performed in `create_deposit` and `_get_activable_eligibility` methods
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17086
- Branche : …
> (PC-17086)[API] feat: stop downgrading fraud_check if user has already an active deposit

- api/src/pcapi/utils/sentry.py
Eviter d'avoir du bruit sur sentry avec les erreurs qui arrivent dans le pod console, comme par exemple [celle-ci](https://passcultureteam.slack.com/archives/C01FVUFTXV1/p1664272022500549)
> (BSR)[API] feat: stop capturing error in sentry when occuring in flask shell

- api/src/pcapi/repository/clean_database.py
Comme discuté en synchro backend, le fait de réinitialiser les Feature Flags à chaque fois qu'on "relance la sandbox" est source d'incompréhensions / de perte de temps lors des tests sur l'environnement de testing.
> (BSR)[API] feat: stop deleting feature flags when resetting databse

- api/src/pcapi/scripts/rebuild_staging/anonymize.sql
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17671
Anonymisation des données cinéma:
- `token` table `venue_booking_provider`
- `cinemaApiToken` table `cds_cinema_details`
- `barcode` table `external_booking`
> (PC-17671)[API] feat: Anonymize cinema vad tokens and external booking barcodes

- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/users/external/zendesk_sell.py
- api/tests/core/users/external/zendesk_sell_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17662
- Corriger un problème d'utilisation mémoire : la mise à jour de certains lieux gérant beaucoup d'offres explose l'utilisation mémoire
- Pouvoir tester le script d'initialisation Zendesk Sell sur staging, en lecture seule (on n'a pas de sandbox Zendesk Sell donc restons prudents sur les données de prod)
- But : un hotfix sur staging
Cela permettra de tester le script Zendesk Sell affiné d'abord sur staging plutôt que sur la prod.
La dernière version du script fera l'objet d'une PR séparée quand le script aura pu tourner (sans _crash_ ni _kill_) jusqu'au bout sur staging.
- Commit(s) : `(PC-XXX)[PRO|API|…] description …
> Pc 17662 zendesk sell memory + staging

- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/users/external/zendesk_sell.py
- api/tests/core/offerers/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17662
Suite à la PR 3721 : https://github.com/pass-culture/pass-culture-main/pull/3721
Un nouveau test sur staging me montre que venue.nApprovedOffers() prend du temps et donc charge la base de données, alors qu'on ne veut que vérifier l'existence d'au moins une offre => nouvelle propriété faisant le minimum.
> (PC-17662)[API] fix: DB load when updating venue on Zendesk Sell

- api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
- api/src/pcapi/core/booking_providers/cds/client.py
vouchertype name is necessary for CDS to get correct report data during booking cancellation
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17690
- …
> (PC-17690)[API] fix: add vouchertype to TicketSaleCDS

- pro/testcafe/05_venue.js
Essai pour fix la flakyness de 2 tests e2e sur la page de lieux. 
-> cas siret on allonge le timeout pour attendre le retour de l'api
-> cas commentaire allonge le timeout pour attendre les propositions d'adresse
- PR : …
> (BSR)[PRO] fix: flakyness by adding a timeout on equality test

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220929T121607_4e55db3dc9c6_mandatory_description_on_collective_offer.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/tests/routes/pro/patch_collective_offer_test.py
- api/tests/routes/pro/post_collective_offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17669
Dans les tables collective_offer et collective_offer_template la colonne description passe en NOT NULL
> Pc 17669 rpa mandatory description eac

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/users/api.py
- api/tests/core/fraud/test_api.py
- api/tests/core/users/test_api.py
it has two benefits: we ensure the unicity is respected ; the duplicate search will be more perfomant (we will stop formatting idPieceNumber column on the fly)
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17691
> (PC-17691)[API] feat: save idPieceNumber with same format as duplicate search

- api/src/pcapi/core/mails/transactional/bookings/booking_confirmation_to_beneficiary.py
- api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17770
Faire remonter les tags des offres à Sendinblue pour personnaliser l'email transactionnel de confirmation de réservation.
Besoin discuté avec le marketing et avec Thierry.
C'est normalement dans le périmètre de l'équipe pro mais lié à Sendinblue.
Comme Thierry est parti et qu'on en avait parlé ensemble, je le fais pour débloquer le marketing.
> (PC-17770)[API] feat: offers tags available in Sendinblue to customize booking confirmation email

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/offerer_view.py
- api/src/pcapi/admin/custom_views/pro_user_view.py
- api/src/pcapi/alembic/versions/20220927T102855_246156d69d6f_create_action_history_table.py
- api/src/pcapi/core/history/api.py
- api/src/pcapi/core/history/factories.py
- api/src/pcapi/core/history/models.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/models/__init__.py
- api/src/pcapi/repository/clean_database.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/admin/custom_views/offerer_view_test.py
- api/tests/admin/custom_views/pro_user_view_test.py
- api/tests/core/history/test_api.py
- api/tests/core/history/test_factories.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/pro/get_educational_institutions_test.py
- api/tests/routes/pro/post_offerer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17455
Conserver un historique horodaté de toutes les actions effectuées dans le processus de validation des structures. Les utilisateurs du backoffice doivent pouvoir ajouter un commentaire, associé ou non à une action.
L'objectif est de pouvoir afficher dans le nouveau backoffice, une liste présentant l'historique de la structure..
Cette première version d'historique est censé devenir générique et conserver les actions sur toutes les ressources manipulées dans le backoffice : structures, lieux, utilisateurs pro et jeunes... pour afficher cet historique dans les détails de la ressource.
La route d'ajout d'un commentaire à une structure, demandée dans le nouveau backoffice, est aussi ajoutée dans ce ticket, afin …
> (PC-17455)[API] feat: Add action history for new backoffice, starting with offerer validation history

- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/routes/backoffice/permissions.py
- api/tests/routes/backoffice/permissions_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17809
corriger l'erreur qui survient quand on cherche à lister les permissions alors qu'il en existe encore en base qui ont été retirées de l'enum Python `Permissions` ou quand on cherche à lister les role alors qu'un de ces rôles est associé à une permission obsolète
RAS
RAS
RAS
> (PC-17809)[API] fix: manage obsolete perms

- pro/src/components/hooks/useNotification.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/__specs__/CollectiveDataEdition.spec.tsx
BSR
_ Rajouter un mock pour un test pour qu'il ne timeout plus
je n'ai pas réussi à simplement mocker juste ce que je voulais, les autres objets se construisaient à partir du `mainlandOptions` 
non mocké, donc le test échouait, relecteur si tu as une idée je suis preneur !
> (BSR)[PRO] test: decrease time of CollectiveDataEdition test

- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/mails/__init__.py
- api/src/pcapi/core/mails/backends/base.py
- api/src/pcapi/core/mails/backends/logger.py
- api/src/pcapi/core/mails/backends/sendinblue.py
- api/src/pcapi/core/mails/backends/testing.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_institution.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_confirmation_by_pro.py
- api/src/pcapi/core/mails/transactional/educational/eac_new_booking_to_pro.py
- api/src/pcapi/core/mails/transactional/send_transactional_email.py
- api/src/pcapi/tasks/serialization/sendinblue_tasks.py
- api/tests/core/mails/tests.py
- api/tests/routes/adage/v1/refuse_prebookings_test.py
- api/tests/scripts/booking/handle_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16951
Dans le cas ou l'acteur culturel renseigne plusieurs mail de notifications : 
- Le premier mail renseigné sert de destinataire principal 
- Les autres mails renseignés sont envoyés en copie cachées (cci)
- Ajout de la possibilité d'ajouter des mails en cci dans les mails sendinblue
- Modification des différents envoie de mails de notifs
> Pc 16951 eac use recipients as bcc when sending notifications email

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/pro_user_view.py
- api/src/pcapi/alembic/versions/20220930T103731_b0f79857ab7d_add_offerer_validation_status.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/models/validation_status_mixin.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/src/pcapi/routes/native/v1/favorites.py
- api/src/pcapi/routes/native/v1/offers.py
- api/src/pcapi/routes/pro/offerers.py
- api/src/pcapi/scripts/beneficiary/import_test_users.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/pro/get_offerer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17462
Permettre de modifier le statut d'avancement de la validation de structures.
Ce ticket vise à ajouter la possibilité de « mettre en attente » une validation, donc statut `OFFERER_PENDING`, avec un commentaire optionnel.
L'action devra apparaître dans l'historique de la structure.
- le champ `validationStatus` est ajouté pour gérer le statut ; cohabitation avec le `validationToken` le temps de la transition
- en l'état, on ne passe pas encore en REJECTED, donc ça n'influence pas les résultats pouvant être affichés dans le portail pro, la structure n'est pour l'instant que validée ou non (nouvelle ou en attente)
- on utilisera le même champ `validationStatus` pour la table `user_offerer` pour le rattachement …
> (PC-17462)[API] feat: Add validation status to offerer, set offerer validation as PENDING in new backoffice

- pro/src/app/AppRouter/AppRouter.tsx
Au premier chargement de l'application les routes ne sont pas encore initialisées et <NotFound /> est rendu. 
Nous n'avons pas besoin du useEffect, les features sont déjà chargées dans le storeProvider (un spinner est affiché quand on les load). 
> (BSR)[PRO] fix: do not use useEffect. We always have features loaded

- api/src/pcapi/core/offerers/models.py
Ajouter les index de recherche par trigramme dans les modèles `Offerer` et `Venue`.
Les index sont déjà créés par une migration.
Ce commit évite de créer des "drop" en auto-générant une nouvelle migration.
Migrations existantes :
- https://github.com/pass-culture/pass-culture-main/blob/v208.0.1/api/src/pcapi/alembic/versions/20220907T165520_3c4183de2005_add_trgm_index_on_offerer_name.py
- https://github.com/pass-culture/pass-culture-main/blob/v208.0.1/api/src/pcapi/alembic/versions/20220909T154021_abc92addfaeb_add_trgm_index_on_venue_name.py
- https://github.com/pass-culture/pass-culture-main/blob/v208.0.1/api/src/pcapi/alembic/versions/20220909T154047_53b7d749990e_add_trgm_index_on_venue_public_name.py
- PR : `(PC-XXX) Description rapide …
> (BSR)[API] fix: add missing trigram indexes in Offerer/Venue models

- pro/src/components/pages/Home/OffererStats/OffererStats.tsx
- pro/src/components/pages/Home/OffererStats/__specs__/OffererStats.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17836
Modifier le wording d'un des blocs de statistiques sur la page d'accueil
- Fix du wording
- BSR : ajout de tests sur les events envoyés au click sur les différents boutons du composant
> Pc 17836 pro offererer stats fix wording nb bookings

- doc/src/22_fournisseur.apib.md
1. The name of the API is "API Fournisseurs". "API Stocks" is something else.
2. We used to call this API once per day. We now call it every hour.
> (BSR)[API] docs: Update Provider API documentation

- .circleci/config.yml
BSR
_Améliorer la ci pour les branches de maintenances `maint/v<number>`
Actuellement on lançait le coverage de pro sur les branches de maintenances et il a la facheuse tendance à être toujours rouge
Pour rendre l'esprit plus tranquil aux développeurs / PO qui mergent des hotfix nous jouons les tests sans le coverage sur ces branches
doc ci : https://circleci.com/docs/configuration-reference/#logic-statements
le workflow en succès : https://app.circleci.com/pipelines/github/pass-culture/pass-culture-main/29538/workflows/f798b87e-3025-4cf3-ba68-987f344d9155/jobs/225059
(il n'y a pas l'étape sur la dernière ci car j'ai enlevé la modif sur pro qui nous a permis de tester)
> (BSR)[MAIN] ci: ignore pro coverage for maintenance branches

- api/.env.production
- api/.env.staging
- api/.env.testing
Missing: google big query table base names.
> [API] fix: add missing vars inside .env.* files

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20221010T092930_ac10b3d69c25_add_flag_for_collective_offers_from_api.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/educational/models.py
- api/tests/routes/pro/public_api/collective/post_collective_offer_public_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17780
- Ajout d'une colone `isPublicApi` dans la table `collective_offer` qui vaut `true` si l'offre a été créée par l'api collective publique et `false` sinon
> (PC-17780)[API] feat: flag collective offeres created by the public api

- api/src/pcapi/utils/requests.py
Il s'agit de réessayer par défaut les requêtes qui échouent lors de l'établissement de la connexion (ConnectTimeoutError). 
De plus, on peut réessayer les autres erreurs, notamment les [ReadTimeoutError](https://sentry.passculture.team/organizations/sentry/issues/?environment=production&project=5&query=is%3Aunresolved+ReadTimeoutError&statsPeriod=14d), lorsque la méthode http utilisée est "safe".
En fait `urllib3.util.retry` fait bien le travail :
- D'après la méthode 'init': by default the allowed_methods are ['HEAD', 'GET', 'PUT', 'DELETE', 'OPTIONS', 'TRACE']. So we can simplify then code that was adding an 'unsafe' retry startegy
- D'après la méthode `increment`:
- all [ConnectTimeoutError](https://sentry.passculture.team/organizations/sentry/issues/?environment=production&project=5&qu …
> (BSR)[API] feat: add retry on requests with urllib3 strategy

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/native/v1/offers.py
- api/tests/routes/native/v1/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16567
- Correction des paramètres d'appel de la fonction `get_shows_stock`.
- Ajout d'un test de récupération d'offre synchronisée via Ciné Office.
> (PC-16567)[API] fix: cds fix arguments get_shows_stock call

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/fraud/ubble/models.py
- api/tests/connectors/beneficiaries/ubble_test.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/core/users/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17884
Corriger le parsing de "gender" du Ubble, pour ne le faire qu'une fois. Sinon, au second parsing, on remplace par None 
- RAS
- RAS
- None
> (PC-17884)[API] fix: parse gender once when handling Ubble parsing

- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/scheduled_tasks/commands.py
- api/tests/core/offerers/test_repository.py
- api/tests/core/offers/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17866
Envoi de mail de relance de création d'offre pour les lieux physiques appartenant à des structures qui n’ont créé aucune offre ET dont la structure est validée 5j/10j avant
> (PC-17866)[API] feat: email reminder pro offer creation 5j and 10j after offerer validation

- pro/src/components/layout/form/fields/SirenField/__specs__/SirenField.spec.jsx
- pro/src/components/layout/form/fields/SirenField/__specs__/decorators.spec.js
- pro/src/components/layout/form/fields/SiretField/__specs__/SiretField.spec.tsx
- pro/src/components/pages/Offers/Offers/ActionsBar/adapters/__specs__/updateAllOffersActiveStatusAdapter.spec.ts
- pro/src/components/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/DuplicateOfferCell.tsx
- pro/src/core/OfferEducational/adapters/__specs__/cancelCollectiveBookingsAdapter.spec.ts
- pro/src/core/OfferEducational/adapters/__specs__/getStockCollectiveOfferTemplateAdapter.spec.ts
- pro/src/core/OfferEducational/adapters/__specs__/patchIsTemplateOfferActiveAdapter.spec.ts
- pro/src/core/Offerers/adapters/__specs__/getSirenDataAdapter.spec.js
- pro/src/core/Venue/adapters/getSiretDataAdapter.ts
- pro/src/new_components/VenueForm/Informations/SiretOrCommentFields/SiretOrCommentFields.tsx
- pro/src/new_components/VenueForm/Informations/__specs__/Informations.spec.tsx
- pro/src/routes/CollectiveOfferTemplateStockEdition/adapters/__specs__/patchCollectiveOfferTemplateAdapter.spec.ts
- pro/src/routes/CollectiveOfferTemplateStockEdition/adapters/__specs__/patchCollectiveOfferTemplateIntoCollectiveOffer.spec.ts
- pro/src/routes/Desk/__specs__/Desk.spec.tsx
- pro/src/routes/VenueEdition/VenueEdition.tsx
- pro/src/routes/VenueEdition/__specs__/VenueEdition.spec.tsx
- pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/TableRow/CollectiveTableRow.tsx
- pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/TableRow/TableRow.module.scss
- pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/TableRow/__specs__/CollectiveTableRow.spec.tsx
- pro/src/screens/CollectiveOfferVisibility/__specs__/CollectiveOfferVisibility.spec.tsx
- pro/src/screens/OfferEducational/__specs__/OfferEducationalEdition.spec.tsx
- pro/src/screens/OfferEducational/__tests-utils__/defaultProps.ts
- pro/src/screens/OfferEducationalStock/__specs__/OfferEducationalStockShowcaseOffer.spec.tsx
- pro/src/store/StoreProvider/__specs__/StoreProvider.spec.tsx
- pro/src/ui-kit/IconLinkBox/IconLinkBox.tsx
- pro/src/ui-kit/form/MultiSelectAutoComplete/__specs__/MultiSelectAutocomplete.spec.tsx
- pro/src/ui-kit/form/SelectAutocomplete/SelectAutocomplete.tsx
- pro/src/ui-kit/form/SelectAutocomplete/__specs__/SelectAutocomplete.spec.tsx
BSR
_Retirer les warnings des tests de PRO
sauf 16 warnings de 3 sortes :
1.
```
Warning: The <default /> component appears to be a function component that returns a class instance. 
Change default to a class that extends React.Component instead. I
f you can't use a class try assigning the prototype on the function as a workaround. `default.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.
```
une occurence, le plus mystérieux, lié à  `AvatarEditor` dans  `'react-avatar-editor'`
2. 
```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
&
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See …
```
> Bsr fix warnings 2

- api/src/pcapi/routes/adage_iframe/features.py
- api/src/pcapi/routes/adage_iframe/logs.py
- api/src/pcapi/routes/adage_iframe/offers.py
- api/src/pcapi/routes/pro/public_api/bookings.py
- api/src/pcapi/routes/pro/public_api/collective/categories.py
- api/src/pcapi/routes/pro/public_api/collective/domains.py
- api/src/pcapi/routes/pro/public_api/collective/educational_institutions.py
- api/src/pcapi/routes/pro/public_api/collective/offers.py
- api/src/pcapi/routes/pro/public_api/collective/students_levels.py
- api/src/pcapi/routes/pro/public_api/collective/venues.py
- api/src/pcapi/routes/pro/public_api/stocks.py
- api/tests/routes/pro/public_api/openapi_test.py
Bug : le champ `security` est absent du schéma openapi de certaines routes, comme [update_stocks](https://backend.integration.passculture.app/v2/swagger#/API%20Stocks/UpdateStocks).
Impact : tester ces routes via le swagger n'est pas fonctionnel. En effet la clé d'api qu'on ajoute à partir du bouton "Authorize" n'est pas transmise dans les headers des requêtes.
Fix : the add_security_scheme method should be called before spectree_serialize method so that the 'requires_authentication' attribute is defined when we try to use it in spectree_serialize
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17776
Le plus propre ne serait-il pas d'utiliser directement les security_schemes du ExtendedSpectree ? 
Cf [cette …
> (PC-17776)[API] fix: fix swagger security schemes

- pro/src/screens/OfferEducational/OfferEducationalForm/FormContact/FormContact.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17761
Le numéro utilisé dans le placeholder est un numéro qui ne peut pas être attribué à un utilisateur
> (PC-17761)[PRO] feat: add palceholder for phone number input on collective offer form

- api/src/pcapi/core/fraud/api.py
- api/tests/core/fraud/test_api.py
We now save id piece numbers without their spaces. (Barring a few exceptions we manually checked) We can avoid formating during the sql search
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17693
Améliorer le temps de recherche des doublons de pièces d'identité.
- Les `idPieceNumber` sont déjà enregistrés sans espaces (suite à d'autres tickets)
- Dans cette PR, on arrête de formatter les `idPieceNumber` au cours de la requête SQL pour améliorer la perf
- None 
- None
> (PC-17693)[API] feat: improve perf of function to find duplicate ids

- api/src/pcapi/scripts/venue/venue_label/create_venue_labels.py
- api/tests/scripts/venue/venue_label/create_venue_labels_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17957
Adage se synchronise avec nos ids de labels, pour tester la synchro ils ont besoin d'avoir les mêmes ids que sur staging
> (PC-17957)[API] feat: update sandbox to match venue_label ids with the ones from staging

- api/pyproject.toml
- api/requirements.txt
- api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/validation/routes/dms.py
- api/src/pcapi/validation/routes/zendesk.py
... such as useless-suppression. That's what we wanted to do with
"pylint_strict_informational" but that plugin does not work with
recent versions of pylint.
> (BSR)[API] style: Make pylint fail on info messages

- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/mails/backends/sendinblue.py
- api/tests/core/mails/tests.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17977
Afin que les gentils hackers participant au Bug Bounty puissent créer de nouveaux comptes (non bénéficiaires, ou pro non validés) pour suivre le parcours d’inscription (d’un jeune ou d’une structure) et tenter de casser nos protections, suite à des discussions ce matin, nous avons décidé de white-lister tous les emails d’alias YesWeHack (de la forme @yeswehack.ninja), sur staging uniquement, pour ces deux cas : 
- envoi d’emails (au lieu de rediriger à dev+staging@pc)
- identification Ubble, afin que la date de naissance soit ignorée (comme pour +ubble_test@)
On pourrait envisager une liste de domaines white-listés dans une variable d'environnement ou un secret, mais pour l'instant parons au plus urgent pour …
> [PC-17977][API] Whitelist YesWeHack email aliases for Boug Bounty on staging

- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/core/bookings/validation.py
- api/src/pcapi/routes/native/v1/bookings.py
- api/tests/core/bookings/test_api.py
- api/tests/routes/native/v1/bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17991
Un _hunter_ du Bug Bounty (YesWeHack) a rapporté un problème de logique : on peut annuler et ré-annuler à l'infini une réservation par l'API, ce qui déclenche à chaque fois un envoi d'email via Sendinblue. Risque de saturation de la file d'attente en exploitant cette faille.
Ce correctif sera déployé en hotfix sur staging afin de montrer notre réactivité aux nouveaux hachers.
> (PC-17991)[API] fix: Booking can be cancelled twice from the API, which sends email every time

- api/src/pcapi/routes/backoffice/offerers.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17939
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17943
Corriger une exception `KeyError: 'inactive'` dans le backoffice : 
https://sentry.passculture.team/organizations/sentry/issues/396754/?project=5
Au clic sur le profil de certains acteurs culturels, ça charge dans le vide pendant quelques secondes et on est redirigé vers la recherche.
> (PC-17939)(PC-17943)[API] fix: KeyError in backoffice route /offerer<offerer_id>/stats

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_draft_offers.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/delete_draft_offer_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/DeleteOfferRequestBody.ts
- pro/src/apiClient/v1/services/DefaultService.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15447
- 1er commit : 
Code très ressemblant au cron `delete_past_draft_offers` qui sera supprimé bientôt
Nouvelle route pour supprimer des brouillons par lot. Cette route se base sur une liste d'id pour chercher quelles offres à supprimer. 
Une 2eme route arrivera après permettant de supprimer des brouillons à partir des filtres utilisés sur la page offres.
- 2eme commit : 
Ajout de quelques offres brouillon dans la sanbox. Pour le moment 2 offres sont créés par lieux physique (1 avec stock). Ca fait 18 offres brouillons. Si on a besoin d'event/des catégories différentes je modifierai ensuite
- Commit(s) : …
> (PC-15447)[API] feat: new route to bulk delete draft offers

- api/tests/core/bookings/external/test_booking_notifications.py
- api/tests/core/bookings/test_repository.py
- api/tests/core/bookings/test_validation.py
There is no point in using `freeze_time()` in those tests, since we
use a relative time (e.g. `now() + timedelta(days=1)`).
In fact, it made those tests fail because we tried to create a booking
with a user whose deposit is more than 2 years old (i.e. expired).
> (BSR)[API] test: Remove gratuitous (but dangerous) calls to `freeze_time()`

- api/src/pcapi/connectors/boost.py
Gérer les réponses ne contenant pas un JSON lors d'une requête à l'API Boost (en cas d'erreur).
Extraire `message`  via un `try/except`
> (BSR)[API] fix: handle non-JSON responses from Boost API

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20221017T124613_6cdf0c518f89_.py
- api/src/pcapi/core/fraud/models.py
~Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX~
Eviter des timeouts quand on cherche un fraud check par son identifiant externe (Ubble par exemple)
Corriger [cette issue Sentry](https://sentry.passculture.team/organizations/sentry/issues/386345/activity/?environment=staging&project=5&query=&statsPeriod=14d) avant qu'elle débarque en prod 
- Ajout d'un index sur thirdPartyId
- RAS
- Ajout d'un index sur beneficiary_fraud_check.thirdPartyId (Ne change pas les data)
> (BSR)[API] fix: add index to beneficiary_fraud_check.thirdPartyId

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/EACInformation/EACInformation.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17864
Corriger le comportement du bouton du bloc EAC sur le formulaire de modification de lieux.
- La correction avait déjà été faite sur le formulaire V2 lors de la migration du composant vers formik.
> (PC-17864)[PRO] feat: Fixed issue with EAC button displaying.

- pc
Eviter que le script `pc` récupère un pod en erreur
Edition du merveilleux fichier `pc`
Sur une idée originale de @dbaty.
> (BSR) fix: get the running console pod in `pc` script

- api/src/pcapi/connectors/boost.py
- api/src/pcapi/connectors/serialization/boost_serializers.py
- api/src/pcapi/core/external_bookings/boost/client.py
- api/tests/core/external_bookings/boost/test_client.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15395
Récupérer les films d'un cinéma via l'API Boost
- ajout d'une classe `pcapi.core.external_bookings.boost.client.BoostClientAPI` et de sa méthode `get_venue_movies()`
- ajout des _serializers_ adéquats, en reprenant la nomenclature de leur schéma d'API récupéré via Swagger.
> (PC-15395)[API] feat: get movies with Boost API

- api/src/pcapi/core/finance/api.py
The deleted clause is not useful anymore: all collective bookings have
been moved to CollectiveBooking and their pricings are now available
through the `Pricing.collectiveBooking` relationship.
> (BSR)[API] fix: Simplify `get_non_cancelled_pricing_from_booking`

- pro/src/Root.tsx
- pro/src/app/AppLayout.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17970
Fix le comportement du toaster de notification qui apparait à chaque changement de page tant qu'on ne laisse pas le timer s'écouler.
- Déplacement de `Notification` au niveau du `Switch` dans `AppRouter` pour éviter le re-render du composant à chaque changement de route.
> (PC-17970)[PRO] fix: toaster notification timer reset on page change

- api/src/pcapi/routes/pro/venues.py
- pro/src/apiClient/__specs__/helpers.spec.ts
- pro/src/apiClient/helpers.ts
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/PostVenueBodyModel.ts
- pro/src/apiClient/v1/models/VenueResponseModel.ts
- pro/src/apiClient/v1/services/DefaultService.ts
- pro/src/core/Offers/adapters/createIndividualOffer/createIndividualOffer.ts
- pro/src/core/Offers/adapters/createIndividualOffer/serializers.ts
- pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/serializers.spec.ts
- pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts
- pro/src/core/Offers/adapters/updateIndividualOffer/updateIndividualOffer.ts
- pro/src/screens/VenueForm/VenueFormScreen.tsx
- pro/src/screens/VenueForm/__specs__/VenueFormScreen.spec.tsx
- pro/src/screens/VenueForm/__specs__/serializers.spec.tsx
- pro/src/screens/VenueForm/serializers.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17542
API -> Rendre la route post_create_venue pour la génération automatique des routes et model côté front.
PRO -> Faire en sorte que le formulaire de création/modification de lieu fasse appelle aux api.
- Introduction d'un `FIXME` qui sera corrigé avec [ce ticket](https://passculture.atlassian.net/browse/PC-17995)
> (PC-17542)[API] feat: Make `post_create_venue` route available.

- pro/src/new_components/VenueForm/Informations/Informations.tsx
- pro/src/new_components/VenueForm/Informations/SiretOrCommentFields/SiretOrCommentFields.tsx
- pro/src/screens/VenueForm/VenueFormScreen.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17995
- Le formulaire d'édition de lieu doit afficher le champ commentaire si le lieu a été créé sans SIRET.
La branche a été créée sur #3907 qui est encore en attente de merge. Seul le [dernier commit](https://github.com/pass-culture/pass-culture-main/pull/3940/commits/d7cebb5537c3b844477e1ac2c9b628b39ab70186) correspond à la correction.
> Pc 17995 siret comment fields issues

- api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
- api/src/pcapi/core/external_bookings/models.py
- api/tests/core/external_bookings/cds/test_client.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18079
Rendre l'attribut `visanumber` pour CDS optionnel
> (PC-18079)[API] fix: CDS make movie visa number optional

- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17965 (ticket front)
Il manquait l'id de l'association user_offerer dans la liste des utilisateurs rattachés à une structure, ou en attente de rattachement.
On en a besoin pour appeler les APIs de validation dessus.
> (PC-17965)[API] fix: backoffice: add user_offerer id in offerer users list

- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/utils.py
- api/src/pcapi/utils/db.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18002
corriger le filtrage sur la liste des structures à valider
- utilisation du [format spécifié dans Notion](https://www.notion.so/passcultureapp/Contrat-d-interface-entre-Back-et-Front-effea55e1a6d493790ab13d137788973) pour le paramètre de filtrage
- renvoi d'une 400 au lieu d'une 500 en cas de mauvaise valeur fournie
RAS
RASn technique_
> (PC-18002)[API] fix: fix sorting for the list of offerers to be validated

- api/src/pcapi/admin/custom_views/offerer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/core/bookings/exceptions.py
- api/src/pcapi/core/offerers/exceptions.py
- api/src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
- api/src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
- api/src/pcapi/scripts/suspend_fraudulent_pro_users.py
- api/tests/admin/custom_views/offerer_view_test.py
- api/tests/admin/custom_views/venue_view_test.py
- api/tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
- api/tests/scripts/offerer/delete_cascade_venue_by_id_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18053
Corriger une erreur 500 reçue par le support et remontée par Sentry, lors de la suppression d'une structure dont un lieu est utilisé comme point de valorisation : 
`ForeignKeyViolation: update or delete on table "venue" violates foreign key constraint "venue_pricing_point_link_pricingPointId_fkey" on table "venue_pricing_point_link"`
https://sentry.passculture.team/organizations/sentry/issues/395820/?project=5&referrer=jira_integration
Le but est donc de renvoyer un message d'erreur explicite.
> (PC-18063)[API] fix: IntegrityError when an offerer or a venue is deleted and the venue is used as a pricing point

- pro/src/new_components/OfferAppPreview/VenueDetails/VenueDetails.module.scss
- pro/src/new_components/SummaryLayout/SummaryLayout.module.scss
- pro/src/new_components/SummaryLayout/SummaryLayoutRow.tsx
- pro/src/routes/OfferIndividualWizard/Summary/Summary.tsx
- pro/src/screens/OfferIndividual/Summary/Summary.tsx
- pro/src/screens/OfferIndividual/Template/Template.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17930
Page récap:
- Couper le texte qui dépasse sur la vue appli.
- Couper le texte qui dépasse sur la vue Web.
- Ajouter un titre à la page lorsqu'on est sur le récapitulatif d'une offre.
- Modifications CSS et modification du template Summary.
> Hcapuano/pc 17930 pro page récap texte qui dépasse sur la vue appli

- api/src/pcapi/domain/admin_emails.py
- api/src/pcapi/models/feature.py
- api/tests/domain/admin_emails_test.py
This FF will be turned on when switching to offerer validation in the new backoffice instead of offerer management in Front
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18043
Ajout d'un FF pour baculer de la validation des structures et rattachements dans Front, à partir de l'email de validation contenant un token dans le lien, vers la validation dans le nouveau backoffice.
Il s'agit d'un FF temporaire, afin qu'un PM puisse facilement décider l'arrêt des emails, sans besoin de hotfix.
> (PC-18043)[API] feat: Add a feature flag to disable internal offerer validation email

- api/src/pcapi/routes/backoffice/serialization.py
suppression du typage fin des filtres pour le endpoint de liste des structures à valider
RAS
RAS
RAS
> (PC-18116)[API] fix: revert fine typing of filter for unvalidated offerers list

- pro/src/core/Offers/adapters/getOfferIndividualAdapter/__specs__/serializers.spec.ts
- pro/src/core/Offers/adapters/getOfferIndividualAdapter/serializers.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17922
Fixer l'affichage de l'image sur la page de récapitulatif pour les offres synchronisées 
> (PC-17922)[PRO] fix: serializer offer image from thumbUrl

- api/src/pcapi/connectors/serialization/boost_serializers.py
- api/tests/connectors/api_boost_test.py
- Corriger le modèle Pydantic `LoginBoost`, car `code` est optionnel.
> (BSR)[API] fix: LoginBoost.code is Optional

- pro/src/components/pages/Offers/Offer/Offer.scss
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferDetails.jsx
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferForm.jsx
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferFormActions/OfferFormActions.module.scss
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferFormActions/OfferFormActions.tsx
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferFormActions/index.ts
- pro/src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferCreationForPro.spec.jsx
- pro/src/components/pages/Offers/Offer/Stocks/EventStocks.jsx
- pro/src/components/pages/Offers/Offer/Stocks/FormActions/FormActions.tsx
- pro/src/components/pages/Offers/Offer/Stocks/Stocks.scss
- pro/src/components/pages/Offers/Offer/Stocks/ThingStocks.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.create.spec.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.draft.spec.jsx
- pro/src/new_components/RouteLeavingGuardOfferIndividual/RouteLeavingGuardOfferIndividual.tsx
- pro/src/screens/OfferIndividual/Summary/ActionsFormV2/ActionsFormV2.tsx
- pro/src/screens/OfferIndividual/Summary/ActionsFormV2/ActionsFormsV2.module.scss
- pro/src/screens/OfferIndividual/Summary/Summary.module.scss
- pro/src/screens/OfferIndividual/Summary/__specs__/Summary.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15721
Ajout de 3 boutons "Sauvegarder le brouillon".
Sur la page de détail des stocks et de récap. Sur le récap ce bouton n'a pas d'autres actions que de ramener à la page /offres
- PR : `(PC-XXX) …
> (PC-15721)[PRO] feat: add buttons to save draft on offer page

- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18116
passage à `string` du type du paramètre de filtrage pour la liste des structures à valider
RAS
RAS
RAS
> (PC-18116)[API] fix: set filter type to string

- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18114
Afficher le nom de l'utilisateur pro concerné: `accountName`, dans chaque action de l'historique d'une structure du nouveau backoffice.
Ainsi que `accountId` afin de pouvoir faire un lien vers le détail de l'utilisateur en question.
> (PC-18114)[API] feat: backoffice: add account name in offerer history endpoint

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17292
_Rajouter des logs pour que la data puisse tracker les offres
relecteur, j'ai un peu peur que du log ajouté dans `batch_update_offers` s'il y a beaucoup d'offre updaté ça peut poser problème ? 
> (PC-17292)[API] feat: add logs for draft offers

- pro/src/components/pages/Offers/Offers/OfferItem/OfferItem.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18010
_Mettre la même longueur à la colonne avec le bouton brouillon qu'avec le bouton stock (pour qu'elle ne change pas de taille)
> (PC-18010)[PRO] fix: Offers column size for buttons

- pro/src/app/App/App.tsx
- pro/src/app/__specs__/App.spec.jsx
- pro/src/utils/config.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17993
Rediriger l'utilisateur vers /login quand il se logout ou qu'il arrive sur une page privée non connecté …
> (PC-17993)[PRO] fix: redirect user to login page when not connected

- api/src/pcapi/core/offerers/factories.py
- api/tests/admin/custom_views/offer_view_test.py
- api/tests/core/bookings/test_repository.py
- api/tests/core/educational/test_models.py
- api/tests/core/educational/test_repository.py
- api/tests/core/finance/test_repository.py
- api/tests/core/offerers/test_api.py
- api/tests/core/offerers/test_models.py
- api/tests/core/offerers/test_repository.py
- api/tests/core/offerers/test_repository_get_venues.py
- api/tests/core/offers/test_models.py
- api/tests/core/users/test_models.py
- api/tests/core/users/test_repository.py
- api/tests/domain/admin_emails_test.py
- api/tests/emails/offerer_validation_test.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/pro/get_educational_offerers_test.py
- api/tests/routes/pro/get_invoices_test.py
- api/tests/routes/pro/get_offerers_names_test.py
- api/tests/routes/pro/get_offerers_test.py
- api/tests/routes/pro/get_offers_test.py
- api/tests/routes/pro/patch_cancel_collective_offer_booking_test.py
- api/tests/routes/pro/post_offerer_test.py
- api/tests/routes/pro/signup_pro_test.py
- api/tests/routes/pro/validate_offerer_attachment_test.py
- api/tests/routes/pro/validate_offerer_test.py
BSR, pas de ticket Jira
Utiliser les _factories_ qui remplissent à la fois `validationStatus` et `validationToken` sur les structures et rattachements.
Cela en attendant la future disparition de `validationToken`.
On se rapproche ainsi des données telles qu'elles sont en base de production.
> (BSR)[API] test: use Offerer and UserOfferer factories which set both validation status and token

- api/src/pcapi/core/providers/factories.py
- api/src/pcapi/local_providers/install.py
- api/src/pcapi/sandboxes/scripts/creators/allocine/__init__.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_cinema_venue_provider_and_external_bookings.py
Corriger la fonction `install_local_providers()`
- La variable `activate_and_enable_for_pro` allait à l'encontre de son usage spécifié en commentaire, et désactivait par défaut les Providers créés dans cette fonction, ce qui obligeait à modifier leurs attributs dans le script de sandbox.
- Pour simplifier, on utilise désormais une `ProviderFactory`, dont les valeurs par défaut pour `isActive` et `enabledForPro` sont True.
- La logique précédente de création en cas d'absence en DB est couverte par la propriété `sqlalchemy_get_or_create` 
- Doc factoryboy sur [sqlalchemy_get_or_create](https://factoryboy.readthedocs.io/en/stable/orms.html#factory.alchemy.SQLAlchemyOptions.sqlalchemy_get_or_create)
- Cette PR active par défaut les Providers Titelive, on va désactiver dans une autre PR les …
> (BSR)[API] fix: Provider creation in install_local_providers()

- api/requirements.txt
There is not much point in pinning a specific version of pytest, its
plugins and other dependencies that are only used for development. We
are more likely to benefit from any update than being bothered (by a
regression or a change that requires some modification on our
side). And if we are bothered, we can always pin the dependency to the
latest version that works until we have time to update our code to be
compatible with the latest version.
> (BSR)[API] chore: Unpin development dependencies

- backoffice/src/layout/CustomMenu.tsx
- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
- backoffice/src/resources/PublicUsers/types.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17743
Ne permettre d'accéder au sous-menu et à la page de validation des structures, qu'aux utilisateurs du backoffice ayant la permission `VALIDATE_OFFERER` (gérer la validation des structures et des rattachements)
> (PC-17743)[BO] feat: Block access to offerers validation page when permission is missing

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18140
Fournir au frontend du backoffice un endpoint pour récupérer le nombre de structures réparties par état (nouvelle, en attente, validée, rejetée).
> (PC-18140)[API] feat: backoffice: get offerers stats

- api/src/pcapi/core/offers/serialize.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- pro/src/apiClient/v1/models/ListOffersQueryModel.ts
- pro/src/apiClient/v1/services/DefaultService.ts
- pro/src/components/pages/Offers/Offers/Offers.scss
- pro/src/core/Offers/constants.ts
- pro/src/core/Offers/types.ts
- pro/src/routes/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx
- pro/src/routes/CollectiveOffers/adapters/getFilteredCollectiveOffersAdapter.ts
- pro/src/screens/Offers/SearchFilters/SearchFilters.tsx
- pro/src/screens/Offers/__specs__/Offers.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17480
Ajouter un filtre permettant de filtrer les offres affichées entre 'offre vitrine' ou 'offre réservable'
Page : Offres > Offres collectives 
FF : WIP_CREATE_COLLECTIVE_OFFER_FROM_TEMPLATE
> Pc 17480 add offer type filter for collective offers

- api/tests/connectors/dms/graphql_test.py
- api/tests/core/subscription/dms/test_api.py
Support for nose tests has been deprecated in pytest 7.2.0 (and will
be removed in a future version): usage of `setup()` and `teardown()`
now yields a warning. We only have to rename methods.
See https://docs.pytest.org/en/stable/deprecations.html#nose-deprecation.
> (BSR)[API] test: Remove nose-like setup functions

- pro/src/components/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/DuplicateOfferCell.tsx
- pro/src/components/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/__specs__/DuplicateOfferCell.spec.tsx
- pro/src/core/FirebaseEvents/constants.ts
- pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx
- pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17642
Ajouter des trackers lors de l'accès au parcours de duplication d'offres vitrine (depuis la liste d'offre ou la page de récap d'une offre vitrine)
- Fix le fait que le bouton (+) permettant d'accèder au parcours ne fonctionnait plus si l'utilisateur cochait la case pour ne plus afficher la modal 
- Ajout d'un tracker `hasClickedDuplicateTemplateOffer` sur les trois points d'accès avec une propriété from qui varie
> Pc 17642 add tracker for offer from template tunnel

- pro/src/hooks/__specs__/useGetBitmap.spec.ts
- pro/src/hooks/useGetBitmap.ts
- pro/src/new_components/ConstraintCheck/imageConstraints.ts
- pro/src/new_components/ImageEditor/ImageEditor.stories.tsx
- pro/src/new_components/ImageEditor/ImageEditor.tsx
- pro/src/new_components/ImageUploadBrowserForm/ImageUploadBrowserForm.tsx
- pro/src/new_components/ImageUploadBrowserForm/constants.ts
- pro/src/new_components/ImageUploadBrowserForm/validationSchema.ts
- pro/src/new_components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/ModalImageCrop.tsx
- pro/src/new_components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/utils/__specs__/getCropMaxDimension.spec.ts
- pro/src/new_components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/utils/getCropMaxDimension.ts
- pro/src/new_components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/utils/index.ts
- pro/src/new_components/ImageUploader/types.ts
- pro/src/utils/__specs__/image.spec.ts
- pro/src/utils/image.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17825
Configurer une hauteur ou une largeur maximal pour le resize, et utiliser cette contrainte sur les pages d’upload d’image d’offre(V3) et de lieu.
- Ajout d'une valeur maxScale (selon si on est dans offre ou lieu) pour ImageEditor
> (PC-17825)[PRO] image editor add max scale constraint

- pro/src/components/pages/Offers/Offer/OfferDetails/OfferDetails.jsx
- pro/src/components/pages/Offers/Offer/Stocks/EventStocks.jsx
- pro/src/components/pages/Offers/Offer/Stocks/StockItem/StockItem.jsx
- pro/src/components/pages/Offers/Offer/Stocks/ThingStocks.jsx
- pro/src/new_components/RouteLeavingGuardOfferIndividual/RouteLeavingGuardOfferIndividual.tsx
- pro/src/new_components/RouteLeavingGuardOfferIndividual/__specs__/RouteLeavingGuardOfferIndividual.spec.tsx
- Ne pas afficher certaines colonnes en completion de brouillon
- Ne afficher de popin pour les utilisateurs qui veulent quitter depuis la page de recap. L'offre est déjà enregistrée
- Reload les stocks quand on save en draft. Bug duplication de stocks sinon. Correction de l'affichage des stocks restants. On les affichait quand on avait un stock, on les affiche maintenant juste quand l'offre n'est plus draft (ie. en edition).
- _Exemples: suppressions de telles …
> (PC-15721)[PRO] fix: ultime fixes for draft release

- api/src/pcapi/models/feature.py
Corriger le préfixe à utiliser pour nommer un FF d'une fonctionnalité en cours de développement.
Plus de contexte sur [Notion](https://www.notion.so/passcultureapp/Feature-Flag-e7b0da7946f64020b8403e3581b4ed42)
> (BSR)[API] fix: FF naming convention

- api/src/pcapi/core/offerers/api.py
- api/tests/routes/backoffice/fixtures.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18231
Permette le filtrage par état de validation dans la liste des structures à valider du nouveau backoffice.
Par défaut on garde les nouvelles et celles en attente, mais le filtrage permet aussi de voir celles validées ou rejetées (pratique pour le métier).
> (PC-18231)[API] feat: backoffice: filter by status in the list of offerers to validate

- pro/src/components/pages/Offers/Offer/Stocks/EventStocks.jsx
- pro/src/components/pages/Offers/Offer/Stocks/ThingStocks.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.create.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15721
Quand un utilisateur essaye d'enregistrer un brouillon alors que la ligne de stock est vide (il n'a rien enregistré), ne pas afficher d'erreur mais un toaster de succès (même si on fait rien).  …
> (PC-15721)[PRO] feat: do not show error if stocks are empty

- .github/workflows/release--build-hotfix.yml
- .github/workflows/release--build.yml
En fait cette numérotation n’est pas standard, comme le montre l’échec de l’action de déploiement aujourd’hui.
`yarn version --new-version "211.0"` retourne une erreur, on attend plutôt une version à 3 nombres.
> Revert "(BSR) deployment: simplify release version number"

- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/fixtures.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18236
Corriger une erreur remontée par Sentry, en production, sur l'écran de validation de structures.
Cela empêche l'affichage de la liste dès lors qu'une des structures renvoyées n'a pas d'adresse (optionnelle), donc potentiellement assez bloquant. Apparue 13 fois sur Sentry, a priori par les utilisateurs côté homologation.
```
ValidationError: 1 validation error for OffererToBeValidated address
none is not an allowed value (type=type_error.none.not_allowed)
```
Actually adress is nullable un HasAddressMixin so it can be null in database
> (PC-18236)[API] fix: backoffice: validation error for OffererToBeValidated

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/exceptions.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/fixtures.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18139
Permettre une recherche par SIREN ou nom sur l'écran de validation de structure 
> (PC-18139)[API] feat: backoffice: search offerers to validate by SIREN or name

- .github/workflows/update-api-client-template.yml
Pour n'ajouter que les changements dans le dossier apiClient 
Les autres changements de type yarn.lock pas à jour ou autre changement ne devraient pas être commités par ce workflow
> (BSR) update-api-client workflow: dont add all changed files

- api/src/pcapi/routes/backoffice/offerers.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18204
Ajout de la _timezone_ aux dates de l'historique des validations de structures/rattachement.
> (PC-18204)[API] fix: backoffice: timezone-aware datetimes in offerer routes

- api/src/pcapi/core/educational/adage_backends/adage.py
- api/src/pcapi/core/educational/api.py
- api/tests/core/educational/adage_backends/test_adage.py
- api/tests/routes/adage_iframe/post_collective_booking_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18162
Règle cette issue Sentry : https://sentry.passculture.team/organizations/sentry/issues/398218/?project=5
Adage renvoyait une 500 si l'établissement n'avait pas d'email. Maintenant une 404 est renvoyée, il faut la gérer pour ne pas lever d'erreur dans Sentry
> (PC-18162)[API] fix: do not fail prebooking notification if institution has no email

- api/src/pcapi/core/offerers/api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18294
Éviter une exception à l'envoi de mail si on valide ou rejette une structure qui n'a aucun utilisateur attaché.
Ce cas ne devrait a priori pas se produire en production dans un cheminement "normal", mais se produit avec la sandbox sur testing, ou lors de tests. Ce cas se produit cependant forcément si on tente de valider une structure rejetée.
> (PC-18294)[API] fix: backoffice: avoid CannotFindOffererUserEmail exception when offerer has no user attached

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18279
Renvoyer la date de la demande dans l'endpoint de liste de structures à valider.
Si la structure a été inscrite, rejetée puis réinscrite, c'est la date de dernière demande qui compte.
> (PC-18279)[API] feat: backoffice: add request dates in the list of offerers to validate

- backoffice/src/resources/Pro/Components/ValidationStatusBadge.tsx
- backoffice/src/resources/Pro/Offerers/OffererDetail.tsx
- backoffice/src/resources/Pro/ProSearch.tsx
- backoffice/src/resources/Pro/types.tsx
- backoffice/src/resources/PublicUsers/Components/StatusBadge.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18019
Dans l'interface du nouveau backoffice, ajout d'une étiquette sur l'état de validation de la structure dans le profil et les résultats de recherche. Aussi l'état inactif (suspendu) est affiché, mais on ignore l'état actif, peu significatif.
- La couleur de l'étiquette "Suspendu" est désormais noire pour respecter le ticket, et ne pas confondre avec "Rejeté". Cela affecte aussi les étiquettes sur les utilisateurs (même badge) et il est cohérent d'utiliser la même couleur pour la même information.
> (PC-18019)[BACKOFFICE] Add status labels to pro search results

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/constants.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/scripts/suspend_fraudulent_beneficiary_users.py
- api/src/pcapi/scripts/suspend_fraudulent_pro_users.py
- api/tests/core/users/user_status_test.py
- api/tests/routes/external/zendesk_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17880
Ajout des [statuts principaux des utilisateurs](https://github.com/pass-culture/pass-culture-app-native/blob/chantier-cta/user_status.mmd)
- on a fait différentes classes pour pouvoir étendre avec certaines informations propre à certains statuts : ex: `Eligible` aura un champs `subscriptionStatus` qui pourra avoir l'une de ces valeur `has_subscription_pending`, `has_to_complete_subscription` ou `has_subscription_issues`
- on a uniformiser les imports de certaines constants, ça a cassé quelques imports, car apparemment il est possible d'importer un import d'un autre fichier
```python
toto = "toto"
from a import toto
from b import toto # chelou d'importer depuis `b` et pas depuis `a`
```
- Branche : …
> (PC-17880)[API] feat: add user status in `/native/v1/me`

- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/search/__init__.py
- api/src/pcapi/core/search/backends/algolia.py
- api/src/pcapi/core/search/backends/base.py
- api/src/pcapi/scripts/algolia_indexing/commands.py
- api/src/pcapi/scripts/algolia_indexing/indexing.py
- api/tests/core/search/test_backend_algolia.py
- api/tests/scripts/algolia_indexing/indexing_test.py
Les offres collectives et templates n'étaient plus désindexées puis réindexées après le dump/restore en staging suite à la séparation des modèles
Pour réparer ca : 
- création d'une commande qui reindexe les offres collectives et les offres collectives template
> (PC-18306)[API] fix: reindex collective offers and collective offers templates after dump restore

- api/requirements.txt
Version 1.0.0 has a fix [1] to handle 50x responses from Notion API.
As per the changelog [2], the only other significant change is the
upgrade to version 2022-02-22 of Notion API. Notion documentation [3]
seems to indicate that our code is not concerned by those changes.
[1] https://github.com/ramnes/notion-sdk-py/commit/36fc0e4d2bba3ce7f5c4ded48bcb85609b55d71e
[2] https://github.com/ramnes/notion-sdk-py/releases/tag/1.0.0
[3] https://developers.notion.com/changelog/releasing-notion-version-2022-02-22
---
Exemple d'erreur corrigée : https://sentry.passculture.team/organizations/sentry/issues/399029/activity
> (BSR)[API] chore: Bump version of notion-client

- api/src/pcapi/core/mails/__init__.py
- api/src/pcapi/core/mails/models.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/tests/core/mails/tests.py
Pouvoir débrayer l'envoi de mails transactionnels en EHP
Ajout de l'attribut `send_to_ehp` à `Template` dans `core/mails/models.py` 
2 templates ont été ainsi désactivés: 
- BIRTHDAY_AGE_18_TO_NEWLY_ELIGIBLE_USER
- RECREDIT_TO_UNDERAGE_BENEFICIARY
> (BSR)[API] feat: prevent some transactional emails to be sent in EHP

- api/tests/core/users/external/user_automations_test.py
Réparer les tests des _user automations_ qui, écrits il y a un an, ne passent plus à cause des dates figées.
Pour réparer vite, je décale toutes les dates de 12 ans (multiple de 4 pour tomber pareil sur les années bissextiles).
> (BSR)[API] fix: dates in user automation tests

- api/src/pcapi/routes/backoffice/serialization.py
- backoffice/src/resources/Pro/Offerers/OffererDetail.tsx
- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18319
Trois petites corrections dans le backoffice pour la validation et l'historique des structures : 
- Si aucun commentaire n’a été saisi lors du changement de statut, que ce soit sur la structure ou sur un compte pro de la structure, on affiche pas “Commentaire : undefined” dans la colonne commentaire.  Cette seconde sous ligne doit disparaître dans ce cas. On affiche uniquement le commentaire lorsqu’il y a eu une saisie. De même pour la colonne “Auteur”, s’il n’y a aucune valeur, on affiche rien plutôt que “undefined”
- Trier par défaut la liste des structures à valider de la date de création la plus récente à la plus ancienne
- En cas de SIREN vide, l’accès au profil de la structure doit fonctionner malgré tout …
> Pc 18319 backoffice offerer minor fixes

- api/src/pcapi/core/subscription/dms/messages.py
- api/tests/core/subscription/dms/test_api.py
- api/tests/core/subscription/dms/test_messages.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17242
Mise à jour de la formulation des messages dans l'app, quand un utilisateur active son crédit via DMS …
> (PC-17242)[API] feat: update wordings of DMS subscription messages

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/fixtures.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18224
Ajout d'un endpoint pour la liste des rattachements d'utilisateurs à des structures, à valider.
Voir détails dans le ticket.
Je voulais en même temps pouvoir filtrer par tag sur la structure, comme pour la validation des structures, mais : 
- ce n'est pas explicitement demandé,
- et surtout je me fais des nœuds au cerveau avec des erreurs dans la requête SQL,
donc parons au plus urgent pour le métier, on pourra ajouter cela après en cas de besoin.
> (PC-18224)[API] feat: backoffice: list user-offerers to validate

- api/src/pcapi/core/users/api.py
- api/tests/routes/pro/signup_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18224
En créant un compte pro avec une structure déjà existante (SIREN déjà validé), le nouveau rattachement n'apparaissait pas dans l'historique de la structure/du rattachement. Il manquait la création de l'action.
Sans cette action, on ne peut voir la date de la demande dans la liste des rattachements à valider.
> (PC-18224)[API] fix: missing action when creating a pro account with an existing offerer

- api/.vscode/settings.json
Le linting par MyPy n'était pas activé par défaut dans VSCode, cette PR corrige le problème
> (BSR)[API] chore: enable MyPy linting in VSCode

- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
- backoffice/src/resources/Pro/Offerers/UserOfferersToValidate.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18397
L'équipe homologation vérifie les données des acteurs culturels sur societe.com.
Comme ils ne reçoivent plus le mail avec les infos de l'API Sirene, on leur facilite la tâche avec un lien rapide vers la page de la societe, dans un nouvel onglet.
> (PC-18397)[BACKOFFICE] feat: external link to check SIREN before offerer validation

- pro/src/screens/VenueForm/VenueFormScreen.module.scss
- pro/src/screens/VenueForm/VenueFormScreen.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17273
- Faire en sorte que le lecteur d'écran épelle l'identifiant dms. 
- Le span ne permet pas d'ajouter un `aria-label`.
- J'ai tenté le code plus bas (qui me semble plus propre), mais VoiceOver considère le label comme étant "vide". Après avoir bien énoncé le label, il dit "Groupe vide" (comme quoi le label est vide). Vu avec Marion, ça reste dérangeant.
```
{!isCreatingVenue && isNewBankInformationCreation && venue && venue.dmsToken &&(
<>
<label
aria-label={`N° d'identifiant du lieu : ${venue.dmsToken.split('').join(' ')}`}
>
<span aria-hidden={true}>N° d'identifiant du lieu : ${venue.dmsToken}</span>
</label>
</>
)}
```
> (PC-17273)[PRO] feat: Screen reader need to spell-out the dms identifier.

- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18058
Ajouter le genre musical aux infos remontées à Algolia lors des l'indexation des offres
RAS
RAS
RAS
> (PC-18058)[API] feat: add musicType to Algolia offers index

- api/src/pcapi/routes/backoffice/offerers.py
- api/tests/routes/backoffice/offerers_test.py
- backoffice/src/layout/CustomMenu.tsx
- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18134
En tant que CT ou responsable homologation
J'aimerais effectuer une recherche par SIREN ou nom sur l'écran de validation de structure
Afin de filtrer les résultats et de valider plus rapidement les structures dont j’ai la charge
- Si on saisit un nom (par exemple “SIRENE”), alors toutes les structures qui inclue ce nom dans leur nom complet apparaissent dans les résultats
- Si on saisit un SIREN incomplet (moins de 8 caractères), on affiche un message d’erreur de type snackbar “Le SIREN doit faire 9 caractères)
- Au clic sur le bouton “Chercher”, la liste de résultats s’actualise en conséquence
Inclut une petite correction backend pour le SIREN invalide.
- PR : …
> (PC-18134)[BACKOFFICE] feat: search by name or siren in offerer validation screen

- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Ajouter le type de spectacle aux infos remontées à Algolia lors des l'indexation des offres
RAS
RAS
RAS
> (PC-18059)[API] feat: add showType to Algolia offers index

- .github/workflows/tests-pro.yml
Résoud ce problème : https://dev.to/bnb/jest-and-the-changedsince-flag-in-github-actions-ci-468i
L'option changedSince de Jest cause une erreur `fatal: bad revision 'master...HEAD'` car GitHub Actions ne fetch pas master par défaut => les tests ne se lancent pas.
Exemple de pipeline où les tests se lancent correctement avec cette nouvelle config : https://github.com/pass-culture/pass-culture-main/actions/runs/3392641957/jobs/5639077606 
(les tests de ce run sont rouges mais c'est parce que j'ai volontairement changé un fichier pour déclencher le workflow, l'important est que les tests se lancent jusqu'au bout)
> (BSR)[PRO] fix: update pipeline to fix GitHub Actions not checking out master

- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18061
Ajouter les genres de film aux infos remontées à Algolia lors des l'indexation des offres
RAS
RAS
RAS
> (PC-18061)[API] feat: add movieGenres to Algolia offers index

- pro/src/core/OfferEducational/adapters/postCollectiveOfferTemplateAdapter.ts
- pro/src/pages/CollectiveOfferTemplateCreation/CollectiveOfferTemplateCreation.tsx
- pro/src/pages/CollectiveOfferTemplateCreation/index.ts
- pro/src/routes/CollectiveOfferRoutes/CollectiveOfferCreationRoutes/CollectiveOfferCreationRoutes.tsx
- pro/src/routes/CollectiveOfferRoutes/CollectiveOfferRoutes.tsx
- pro/src/screens/OfferType/OfferType.tsx
- pro/src/screens/OfferType/__specs__/OfferType.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18221
Afficher la page de création d'une offre vitrine lorsque cette option est sélectionnée au début du parcours de création d'offre collective. 
Au clic sur étape suivante, créer une offre vitrine et rediriger vers la page des stocks.
> (PC-18221)[PRO] feat: add collective template offer creation page

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary.py
- api/tests/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18396
Le marketing a besoin du champ OFFER_TAGS dans le template 665 (id en prod).
La même chose que pour le template 725 où c'est déjà implémenté.
> (PC-18396)[API] feat: Add OFFER_TAGS in booking event reminder email

- api/src/pcapi/admin/custom_views/offerer_view.py
- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/core/monkeypatches.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offerers/validation.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/providers/models.py
- api/src/pcapi/models/api_errors.py
- api/src/pcapi/models/beneficiary_import.py
- api/src/pcapi/models/beneficiary_import_status.py
- api/src/pcapi/models/has_thumb_mixin.py
- api/src/pcapi/models/needs_validation_mixin.py
- api/src/pcapi/models/offer_mixin.py
- api/src/pcapi/models/pc_object.py
- api/src/pcapi/models/providable_mixin.py
- api/tests/routes/backoffice/accounts_test.py
Au menu : 
- ajouts et corrections d'annotations de type ;
- correction de requêtes SQL N+1 ;
- suppression de `BenecifiaryImport.setStatus()`, inutilisée.
Commits à relire séparément.
> (BSR)[API] Ajout et correction d'annotations de type dans `pcapi.core.offerers`, `pcapi.core.monkeypatches` et `pcapi.models` (+ bonus !)

- pro/src/screens/OfferIndividual/Informations/Informations.tsx
Lorsqu'on faisait back navigateur de stock vers informations on retournait sur la page de création.
Ici, via ce replace d'url, on retrouve bien l'édition de l'offre nouvellement créée
> (BSR)[PRO] offer v3 back to step 1

- api/src/pcapi/serialization/spec_tree.py
It worked and was not a typo: we want the literal "{model}" string. We
don't want `model` to be interpolated.
> (BSR)[API] style: Remove useless f-string

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17622
Fix une issue Sentry
Empêcher l'activation d'utilisateurs via un fraud check vide (c'est un edge case relevé par sentry, qui peut permettre d'activer son crédit malgré un KO des admins)
- PR : …
> (PC-17622)[API] fix: avoid activating user based on empty fraud checks

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/tests/routes/backoffice/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18316
Dans la liste des structures à valider, permettre le filtrage par date de la demande (dans un intervalle de dates).
> (PC-18316)[API] feat: backoffice: filter offerers to validate by request dates

- api/src/pcapi/core/users/external/batch.py
- api/tests/core/users/external/batch_test.py
- api/tests/scripts/external_users/batch_update_users_attributes_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18431
Ajout d'un attribut Batch : `deposit_activation_date`.
Identique à `DEPOSIT_ACTIVATION_DATE` déjà envoyé vers Sendinblue pour les jeunes.
> (PC-18431)[API] feat: Add Batch attribute 'deposit_activation_date'

- api/src/pcapi/routes/backoffice/offerers.py
- api/tests/routes/backoffice/offerers_test.py
- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18348
Ajout des tests du tri par requestDate (ajout des requestDate dans ce ticket mais déjà fait en parallèle dans https://github.com/pass-culture/pass-culture-main/pull/4208)
> (PC-18348)[API] feat: order offerer validation by requestDate

- api/pyproject.toml
mypy 0.990 a été publié lundi et rapporte 2 nouvelles erreurs que nous
devons désactiver temporairement, le temps de mettre à jour notre code.
2 commits à relire séparément, chaque message de commit donne des détails.
Pour le second commit, il faut trouver une façon de typer correctement
les méthodes décorées avec `hybrid_property`. J'ai vu une façon de
faire [ici](https://github.com/python/mypy/issues/4430#issuecomment-781272415), c'est en cours dans une autre pull request à venir.
> (BSR)[API] Contournements temporaires pour compatibilité avec mypy 0.990

- api/src/pcapi/core/subscription/dms/messages.py
- api/tests/core/subscription/dms/test_api.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17244
Update le message in app pour que l'utilisateur puisse contacter le support en 1 clic en cas de DMS KO …
> PC-17244 update dms instructor ko message

- backoffice/package.json
- backoffice/src/layout/theme.tsx
- backoffice/src/resources/Pro/Components/MinMaxDateRangePicker.tsx
- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
- backoffice/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18315
- En tant que responsable homologation 
- J'aimerais pouvoir filtrer sur la date de réception de la demande sur la liste de validation de structure
- Afin de gagner du temps sur la recherche d’une demande spécifique
- Ajout d’un filtre “Date” sur l'écran de validation des structures
- Ce filtre doit permettre de sélectionner les demandes de validation par semaine (du lundi au dimanche)
- Tout comme les filtres “Tags” et “Statut”, il est possible d’en sélectionner plusieurs, afin d’afficher par exemple les demandes sur 2 ou 3 semaines différentes
> (PC-18315) feat : Filtre de date pour la création des structures à valider

- pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18509
- Corriger le comportement qui faisait qu'un `submit` sur le formulaire à l'intérieur du formulaire de lieux déclenchait le `onSubmit` plus haut.
> (PC-18509)[PRO] fix: Prevent the inner form to trigger the `onSubmit` of the formik form.

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/alembic/versions/20221102T162613_ffd6d7217351_add_book_macro_section_table.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/search/backends/algolia.py
- api/src/pcapi/sandboxes/scripts/getters/pro_01_signup.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18060
Ajouter le macro rayon littéraire aux infos remontées à Algolia lors des l'indexation des offres
- Ajout d'un modèle `BookMacroSection` pour contenir le mapping entre les rayons et les maccro rayons, la table est remplie lors de la migration associée depuis un export des données de l'équipe data.
RAS
RAS
> (PC-18060)[API] feat: add bookMacroSection to Algolia offers index

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/young_status.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/core/users/young_status_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18365
Ajout des sous statuts des users éligibles
[Diagramme d'états](https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/user_status.mmd)
- On a ajouté `has_subscription_issues` qui pourrait etre améliorée / affinée plus tard
- est-ce qu'il faudrait faire un truc en particulier pour le cas commenté `should never happen` ?
> (PC-18365)[API] feat: young status add eligible sub status

- api/src/pcapi/core/users/models.py
- api/tests/admin/custom_views/beneficiary_user_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17242
Fix un bug qui enregistrait les ine vides comme des `""` au lieu de `NULL` 
Impact du bug: a partir de la 2nde soumission, on a une erreur de duplication
- Comme idPieceNumber, utiliser sa.String 
- None
- None
> (PC-17242)[API] fix: change ine column format to correctly handle empty form

- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/dms/messages.py
- api/tests/core/subscription/dms/test_api.py
- api/tests/core/subscription/dms/test_messages.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17242
Adapter les messages quand on a un DMS en instruction
> (PC-17242)[API] fix: add correct message when dms in_construction

- api/src/pcapi/routes/backoffice_v3/templates/components/offerer/badges.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18283
Fix : condition inversée. Il fallait afficher le badge « suspendue » si la structure était inactive...
> [BO] PC 18283 offerer profile

- api/src/pcapi/admin/base_configuration.py
- api/src/pcapi/admin/custom_views/custom_reimbursement_rule_view.py
- api/tests/admin/custom_views/admin_user_view_test.py
- api/tests/admin/custom_views/api_key_view_test.py
- api/tests/admin/custom_views/beneficiary_user_view_test.py
- api/tests/admin/custom_views/booking_view_test.py
- api/tests/admin/custom_views/boost_pivot_view_test.py
- api/tests/admin/custom_views/cine_office_pivot_view_test.py
- api/tests/admin/custom_views/criteria_view_test.py
- api/tests/admin/custom_views/custom_reimbursement_rule_view_test.py
- api/tests/admin/custom_views/feature_view_test.py
- api/tests/admin/custom_views/many_offers_operations_view_test.py
- api/tests/admin/custom_views/offer_view_test.py
- api/tests/admin/custom_views/offerer_tag_view_test.py
- api/tests/admin/custom_views/offerer_view_test.py
- api/tests/admin/custom_views/partner_user_view_test.py
- api/tests/admin/custom_views/pro_user_view_test.py
- api/tests/admin/custom_views/user_offerer_view_test.py
- api/tests/admin/custom_views/venue_provider_view_test.py
- api/tests/admin/custom_views/venue_view_test.py
Fix : certaines formulaires de `FlaskAdmin` n'avaient plus de _csrf_token_, ce qui bloquait certaines opérations. Faire hériter la nouvelle classe `FlaskWTFSecureForm` de `FlaskForm` et supprimer la sous-classe `Meta` permet de régler ce problème.
En revanche, avec l'arrivée de `FlaskForm` (qui provient de **flask-wtf** contrairement à `SecureForm` qui provient de **flask-admin**), on se retrouvait avec des erreurs de validation inexplicables. La seule différence que j'ai trouvé par rapport à master est que les formulaires n'ont plus de champ `_obj` (défini par `BaseForm` de **flask-admin**, dont `SecureForm` hérite), ce qui génère des erreurs qui n'apparaissaient pas avant.
Le champ `_obj` est créé [ici](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/form/__init__.py#L …
> (jeremieb)[ADMIN] fix: use FlaskForm

- api/src/pcapi/alembic/versions/20221109T184508_8b0574f4aa1b_add_primary_key_to_role_permission.py
- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/repository/clean_database.py
- api/tests/core/permissions/test_permissions_sync.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18505
Ajout d'une clé primaire (id) à `role_permission`.
Les colonnes `roleId` et `permissionId` peuvent être nulles donc je n'ai pas opté pour l'option clé primaire avec ces deux colonnes.
> [BO] PC 18505 add primary keys

- pro/src/components/VenueForm/Address/Address.tsx
- pro/src/components/VenueForm/Address/__specs__/Address.spec.tsx
- pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
- pro/src/ui-kit/form/SelectAutoComplete2/index.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18569
- Correction du composant utilisé + remise des tests.
- Ajout d'une props pour désactiver la remise à zéro au clic sur le `SelectAutoComplete`
- La touche entrer pour sélectionner un élément ne doit pas envoyer le formulaire.
> (PC-18569)[API] feat: Fix keyboard navigation and conditional field reset.

- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/core/mails/transactional/pro/permanent_venue_needs_picture.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17966
- Envoyer un mail d'incitation à ajouter un visuel pour lieu permanent, quand un lieu est sauvegardé sur FlaskAdmin comme étant permanent.
> (PC-17966)[API] feat: Send an email after a venue is set to permanent.

- api/src/pcapi/core/users/external/zendesk_sell.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18538
Lors de la mise à jour de Zendesk avec les données des acteurs culturels du portail pro, prévoir d’update tous les champs des AC à l'exception de “publicName”
> (PC-18538) fix: Non-mise à jour du nom d'un acteur culturel sur Zendesk Sell

- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
```shell
139 |     renderStockThingScreen({ props, storeOverride, contextValue })
140 |     expect(
> 141 |       screen.getByText(
|              ^
142 |         'Les utilisateurs ont 30 jours pour annuler leurs réservations d’offres numériques. Dans le cas d’offres avec codes d’activation, les utilisateurs ne peuvent pas annuler leurs réservations d’offres numériques. Toute réservation est définitive et sera immédiatement validée.'
143 |       )
144 |     ).toBeInTheDocument()
at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:38:19)
at node_modules/@testing-library/dom/dist/query-helpers.js:90:38
at node_modules/@testing-library/dom/dist/query-helpers.js:62:17
at getByText (node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
at Object.<anonymous> …
```
> (BSR)[PRO] StockThing : fix text against new wording

- pro/src/screens/OfferIndividual/StocksThing/adapters/__specs__/serializers.spec.ts
- pro/src/screens/OfferIndividual/StocksThing/adapters/serializers.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18618
Lors de l'enregistrement du stock:
- Si je rentre 0: quantity = 0
- Si je laisse vide: quantity = null
> (PC-18618)[PRO] fix: correct quantity serialize when quantity is 0

- pro/src/screens/OfferType/OfferType.tsx
- pro/src/screens/OfferType/OfferTypeButton/index.ts
- pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss
- pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.stories.tsx
- pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.tsx
- pro/src/ui-kit/RadioButtonWithImage/index.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18655
- Déplacer le composant `OfferTypeButton` dans ui-kit et le rendre réutilisable
- Utiliser ce nouveau composant (RadioButtonWithImage) dans OfferTypes
> (PC-18655)[PRO] chore: move OfferTypeButton to ui-kit

- pro/yarn.lock
BSR
_Fixer le warning des tests comme le suggère ma console ou github action :
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
j'ai simplement joué la commande en question !
> (BSR)[PRO] fix: warning: Browserslist: caniuse-lite is outdated

- .github/workflows/tests-api.yml
Collecter tous les tests api lors du lancement de pytest via GitHub Actions
Laisser Pytest découvrir tous les tests dans le dossier `tests`, définis via `testpaths` dans `pyproject.toml`
Un commit jetable est ajouté, contenant  un test en échec qui n'était pas collecté avec la précédente configuration.
> [BSR]ci: have Pytest collect all required files

- api/src/pcapi/core/offerers/models.py
Same thing as for Offerer. Without this, a user_offerer could behave like:
* user_offerer.validationStatus => 'REJECTED'
* user_offerer.isValidated => True
because of the inherited isValidated method which relies on the validationToken.
> (jeremieb)[API] fix: override isValidated/etc methods

- api/src/pcapi/core/history/repository.py
- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/serialization/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/comment.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details/history.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/history.html
- api/src/pcapi/routes/backoffice_v3/utils.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18305
Ajout de l'onglet historique de compte de la page de profil d'une structure
1. Ajout de deux `joinedload` manquant à `find_all_actions_by_offerer`.
2. Ajout de tests pour la partie statistiques de la page de profil d'une structure.
3. Import des _fixtures_ de la v2 dans le fichier `conftest` des tests des routes de la v3.
> [BO] PC 18305 offerer profile history

- pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18563
Ajouter une info box au niveau de la section `Participants` lors de la création d'une offre collective
> (PC-18563)[PRO] feat: add info box for eac offer participants

- .github/workflows/tests-backoffice.yml
- .github/workflows/tests-pro.yml
Aligner le fonctionnement avec le comportement actuel de CircleCI : 
- tests complets quand sur master
- tests que sur le diff quand sur une branche
> (BSR)[PRO] fix: only run unit tests on diff for pull requests in CI

- pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
- pro/src/screens/OfferEducational/__specs__/OfferEducationalCreationOffererStep.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18564
Trier par ordre alphabétique la sélection d'un lieu  lors de la création d'offres collectives 
BSR : ajout d'un test si le test d'éligibilité fail
> Pc 18564 eac sort venue alphabetically in offer creation

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/young_status_test.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18551
on a améliorer la détection des erreurs liés à identity check qui permet de détecter le sous statut `has_subscription_issues` du statut `Eligible`
On améliorera les problèmes liés au numéro de téléphone avec cette US https://passculture.atlassian.net/browse/PC-18598
> (PC-18551)[API] feat: better handles issues with identity check

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/users/models.py
- api/tests/core/users/external/user_automations_test.py
- api/tests/core/users/test_models.py
+1 commit de suppression d'une fonction qui n'est plus utilisée. Donc 2 commits à relire séparément. Ci-dessous, message du commit principal :
---
The generation of this CSV took between 10 and 15 minutes on
production. This is because we were calling the `get_wallet_balance()`
SQL function for each user (thus selecting the deposit and then
selecting related bookings for each user): that takes time.
And on staging the process was even OOMKilled, most probably because
it loaded all rows in memory (and our staging pods have less memory).
The calculation of the wallet balance is now done by a single query
that can join everything for all users. The SQL query is long but the
whole generation takes around 2 minutes on production. And we don't
keep all rows in memory anymore (making it work on …
> (PC-16737)[API] perf: Optimize generation of wallets CSV file

- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18703
Corriger la page de validation des structures, beaucoup trop lente : tri par `dateCreated` au lieu de `requestDate`
Détails dans le ticket
> (PC-18703)[BACKOFFICE] fix: performance for offerers validation list

- api/src/pcapi/core/offers/validation.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_validation.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18408
- L'API ne doit pas accepter le prix d'un stockEvent supérieur à 300€. 
- Suppression de la condition pour vérifier le prix maximum aussi pour les stocks de type évènement.
- Modification des tests associés.
> (PC-18408)[PRO] feat: Add stock event price limit and update tests

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/core/educational/api/booking.py
- api/src/pcapi/core/educational/models.py
- api/tests/core/bookings/test_api.py
2 commits à relire séparément. J'en ai profité pour améliorer
`Booking.cancel_booking()`.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18523
> (PC-18523)[API] fix: Reset `dateUsed` when cancelling a booking (+ bonus BSR)

- pro/src/components/StockEventForm/StockEventForm.tsx
- pro/src/components/StockEventForm/__specs__/StockEventForm.spec.tsx
- pro/src/components/StockEventForm/__specs__/validationSchema.spec.tsx
- pro/src/components/StockFormRow/StockFormRow.stories.tsx
- pro/src/components/StockThingForm/StockThingForm.tsx
- pro/src/icons/index.ts
- pro/src/screens/OfferIndividual/StocksEvent/StockFormList/StockFormList.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/ui-kit/form/TextInput/TextInput.tsx
- pro/src/ui-kit/form/shared/BaseInput/BaseInput.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17934
retour de la [PR](https://github.com/pass-culture/pass-culture-main/pull/4385) qui à été revert.
changements: 
- utilisation d'index de stock au lieu de fieldsPrefix
- possiblité d'avoir un composant icone retournant null, le calcule de l'affichage de l'icon € faisait que userEvent.type() s'arretait apres le 1er charactère.
> (PC-17934)[PRO] fix: draft stock submit

- api/src/pcapi/routes/backoffice_v3/templates/admin/roles.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/switch_boolean_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18436
Ne plus afficher l'étiquette “Actif” dans les résultats de recherche jeune
- Chore : Amélioration du style de la page admin 
> Pc 18436 remove active label from account search result

- api/src/pcapi/routes/backoffice_v3/pro_users.py
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get/general.html
- api/tests/routes/backoffice_v3/pro_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17228
Ajout de la page profil d'un user pro.
Le bouton pour modifier les informations est présent mais non-fonctionnel (sujet d'un autre ticket).
> (PC-17228)[API] feat: add pro_user profile to backoffice v3

- pro/src/components/OfferBreadcrumb/OfferBreadcrumb.tsx
- pro/src/components/OfferIndividualStepper/OfferIndividualStepper.tsx
- pro/src/components/OfferIndividualStepper/__specs__/OfferIndividualStepper.spec.tsx
- pro/src/components/OfferIndividualStepper/__specs__/OfferIndividualStepper.tracker.spec.tsx
- pro/src/components/RouteLeavingGuard/RouteLeavingGuard.tsx
- pro/src/components/RouteLeavingGuardOfferIndividual/RouteLeavingGuardOfferIndividual.tsx
- pro/src/core/FirebaseEvents/constants.ts
- pro/src/screens/OfferIndividual/ActionBar/ActionBar.tsx
- pro/src/screens/OfferIndividual/Informations/Informations.tsx
- pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.RouteLeavingGuard.spec.tsx
- pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.creation.spec.tsx
- pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.draft.spec.tsx
- pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.RouteLeavingGuard.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.tracker.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.RouteLeavingGuard.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.tracker.spec.tsx
- pro/src/screens/OfferIndividual/Summary/Summary.tsx
- pro/src/screens/OfferIndividual/Summary/__specs__/Summary.tracker.spec.tsx
- pro/src/screens/OfferIndividual/utils/logTo.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17618
_Ajouter / adapter les trackers à OfferFormV3
_ sur page détails
_ sur page stocks event
_ sur page stocks thing
_ sur page recap
_ dans le breadcrumb
_ dans le route leaving guard
_ tests
avec ces params :
```
Events.CLICKED_OFFER_FORM_NAVIGATION,
{
from: 'informations',
isEdition: false,
isDraft: true,
offerId: 'AA',
to: 'stocks',
used: 'Breadcrumb',
```
j'ai eu pas mal de rebase à faire, parfois un peu compliqués, j'espère que je n'ai rien cassé :/
> (PC-17618)[PRO] feat: trackers offer form v3

- pro/src/components/StockThingForm/StockThingForm.module.scss
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.edition.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18617
Ajout de la fonction de suppression pour le formulaire stock produit.
Les offres synchronisées ou en status refusée ou en attente ne sont pas modifiables.
NB : 3 cas où les stocks ne sont pas supprimables (ils sont que softdelete en vrai) (d'après la route de l'api [delete-stock](https://github.com/pass-culture/pass-culture-main/blob/93b0de5c609d88f568752734e0aec64526e302ff/api/src/pcapi/core/offers/api.py#L724)) :
Les offres sont REJECTED ou PENDING
Les offres sont synchronisées
Les évènements sont passés de 48h (isEventDeletable en back, isDeletable en front)
> (PC-18617)[PRO] feat: Offer V3 - Allow user to delete stock product

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/exceptions.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/components/offerer/user_offerer_status_badge.html
- api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/tests/core/offerers/test_api.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18390
Écran de validation des rattachements d'utilisateurs pro à des structures dans le backoffice v3.
Iso-fonctionnel avec le backoffice v2.
UX identique à celle de la validation des structures du backoffice v3.
Fonctionnalités et tests identiques à ceux des endpoints backend du backoffice v2.
La barre de filtrage, avec moins de possibilités que les structures, n'a pas été soignée pour ce choix réduit car des tickets arrivent derrière pour y ajouter des filtres comme sur la validation des structures. La forme prendra avec ces tickets.
> (PC-18390)[BO] feat: offerer attachments validation

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20221125T153444_c14229719483_add_userofferer_datecreated.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
- api/tests/core/offerers/test_api.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/backoffice_v3/offerers_test.py
- api/tests/routes/pro/signup_pro_test.py
- backoffice/src/TypesFromApi/models/OffererToBeValidated.ts
- backoffice/src/TypesFromApi/models/UserOffererToBeValidated.ts
- backoffice/src/resources/Pro/Offerers/OfferersToValidate.tsx
- backoffice/src/resources/Pro/Offerers/UserOfferersToValidate.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18820
Le temps de réponse est trop long lorsque l'on filtre les structures à valider sur la « Date de la demande ». Il s'agit donc ici d'améliorer les performances avec un filtre sur une colonne de la table `offerer`, plutôt que sur un calcul à partir de la table d'historique (juste dans le calcul, mais trop long).
On revient donc à `dateCreated` qui contient la date de la demande. La seule différence est sur les structures rejetées puis à nouveau inscrites. Dans ce cas, on décide finalement de modifier `dateCreated` pour la date de la nouvelle demande. Ça reste cohérent car :
- avant, l'homologation supprimait les structures dans FA, donc une nouvelle était créée, avec la nouvelle date ;
- c'est la dernière demande …
> (PC-18820)[BO] fix: use dateCreated instead of computed requestDate for performance reasons

- pro/src/pages/Signup/SignupForm/SignupForm.tsx
- pro/src/pages/Signup/SignupForm/__specs__/SignupForm.spec.jsx
- pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.stories.tsx
- pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.tsx
- pro/src/ui-kit/form/PhoneNumberInput/__specs__/PhoneNumberInput.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18791
- Utilisation du composant `PhoneNumberInput` dans le formulaire d'inscription
- Ajout de la possibilité de changer le label du `PhoneNumberInput`.
> (PC-18791)[PRO] feat: Using `PhoneNumberInput` in the signup form.

- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/forms/search.py
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/search_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_multiple_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/pagination.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18821
Afficher 100 résultats par page par défaut (au lieu de 10) dans les listes des structures et rattachements à valider.
Afficher la pagination en haut à droite plutôt qu'en bas.
Modifications faites dans le backoffice v3 uniquement.
> (PC-18821)[BO] feat: 100 results per page by default and pagination on top

- api/Dockerfile
- api/entrypoint.sh
Actuellement l'entrypoint n'est pas bon. 
Les pods ont pour PID 1 /bin/entrypoint soit bash :
```
k exec -it testing-pcapi-signin-api-579b8875fb-zrbtn cat /proc/1/cmdline
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/bin/bash./entrypoint.sh
```
Cela entraîne que le **sigterm** envoyé au pod n'est pas géré. Et du coup les pods ne s'arrêtent pas proprement et prennent un **sigkill** au bout de 30s :
```
❯ date; k delete po testing-pcapi-signin-api-579b8875fb-jzmb2 && date
Tue Nov 29 10:34:44 AM CET 2022
pod "testing-pcapi-signin-api-579b8875fb-jzmb2" deleted
Tue Nov 29 10:35:15 AM CET 2022
```
L'bjectif de ce commit est de faire en sorte que gunicorn soit le pid 1 du pod :
```
k exec -it …
```
> Fix entrypoint

- pro/src/components/OfferIndividualForm/utils/setInitialFormValues.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18837
- Remplir le champ durée au chargement de la page avec une valeur correcte (1:00 par exemple au lieu de 1:0)
- Modification dans la méthode de serialisation des minutes.
> (PC-18837)[PRO] Fix: DurationInput minutes serialization

- pro/src/screens/VenueForm/VenueFormScreen.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18909
- Corriger le problème de sauvegarde de lieu qui n'avaient ni siret ni commentaire.
- Quand le lieu n'avait ni commentaire ni siret, le lieu était considéré comme ayant un siret côté validateur, mais pas côté composant (affichage). La condition est maintenant identique côté composant et côté validateur.
> (PC-18909)[PRO] fix: Fixed saving a venue with neither a siret nor a comment.

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
- api/tests/core/offerers/test_api.py
- api/tests/routes/backoffice_v3/helpers/html_parser.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18136
Sur l'écran de validation de structures, Ajout de 4 blocs en haut de pages permettant d’afficher de gauche à droite : 
- Le nombre de structures à l'état “Nouveau”
- Le nombre de structures à l'état “En attente”
- Le nombre de structures à l'état “Validé”
- Le nombre de structures à l'état “Rejetée”
> (PC-18136)[BO] feat: Add offerers stats on top of validation screen

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/boost_pivot_view.py
- api/src/pcapi/admin/custom_views/cine_office_pivot_view.py
- api/src/pcapi/alembic/versions/20221129T111214_2ca4b0b05bc6_add_unique_provider_id_at_provider_constraint.py
- api/src/pcapi/core/providers/factories.py
- api/src/pcapi/core/providers/models.py
- api/src/pcapi/core/providers/repository.py
- api/tests/admin/custom_views/boost_pivot_view_test.py
- api/tests/admin/custom_views/cine_office_pivot_view_test.py
- api/tests/core/external_bookings/test_api.py
- api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
- api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py
Eviter les conflits d'`idAtProvider` lors de l'ajout/édition de pivot de cinéma
- Ajout de contrainte d'unicité
- Ajout d'un validateur dans le formulaire `CineOfficePivotForm` et `BoostPivotForm`
- Vu le faible nombre de lignes dans la table CinemaProviderPivot, j'ai écrit une migration naïve d'ajout de contrainte en une seule fois
- Modification des _Factories_ pour utiliser les bons _Providers_
> (BSR)[API]feat: add unique constraint in cinema pivots

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18844
Ajout d'un filtre "Tags" sur la liste des rattachements à valider, dans le nouveau backoffice v3.
Similaire au filtrage par tags dans la liste des structures à valider.
> (PC-18844)[BO] feat: filter offerer attachments to validate on offerer tags

- pro/src/screens/OfferIndividual/DialogStocksEventEditConfirm/DialogStocksEventEditConfirm.tsx
- pro/src/screens/OfferIndividual/DialogStocksEventEditConfirm/intex.ts
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StockEvent.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.tracker.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17935
Ajout d'une popin pour avertir l'utilisateur si des reservations ont été faites sur l'offre lors de la modification d'un évènement
- Commit(s) : …
> (PC-17935)[PRO] feat: New popin to warn user about event stock edition

- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details/history.html
- api/tests/routes/backoffice_v3/offerers_test.py
type is not user offerer
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18826
Ne pas avoir le nom et id de l'utilisateur concerné dans le commentaire d'une action si cette action n'est pas liée à un rattachement.
> (PC-18826)[API] fix: remove user name in action history when action

- api/src/pcapi/admin/custom_views/venue_view.py
- api/tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18591
Retirer la possibilité d'éditer le champs `adageId` dans l'édition d'un lieu sur le backOffice
> (PC-18591)[API] feat: remove adage id in backoffice venue edition

- pro/src/pages/Home/Venues/Venue.scss
- pro/src/pages/Home/Venues/Venue.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18961
- Changer l'icône du bouton "Ajouter un RIB"
> (PC-18961)[PRO] style: Fixed the `add-rib-link` icon.

- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/routes/backoffice/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
- api/tests/core/offerers/test_models.py
- api/tests/routes/backoffice/offerers_test.py
- api/tests/routes/backoffice_v3/offerers_test.py
`offerer.UserOfferer[0]` est utilisé pour récupérer la plus ancienne entrée, mais on ne pouvait pas s'en assurer.
Cela faisait échouer certains tests (aléatoirement ?).
Tri de `offerer.UserOfferer` et ajout d'une propriété `offerer.first_user` pour plus de clarté.
> (BSR)[BO] fix: first user for an offerer

- api/src/pcapi/routes/backoffice_v3/templates/components/badges.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card_venue.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17049
Fix : un lieu n'a pas de colonne isActive, et tout ce qui est isPending/New/etc n'en parlons pas.
Donc pour les badges/étiquettes, on ne peut pas reprendre la même logique que celle des structures.
> (PC-17049)[API] fix: templates: venue/offerer badges

- api/src/pcapi/core/mails/transactional/pro/reminder_venue_creation.py
If an offerer does not have any user, `find_new_offerer_user_email()`
raises an exception that we should catch.
> (BSR)[API] fix: Fix send_reminder_venue_creation_to_pro when offerer has no user

- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.tracker.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/adapters/__specs__/serializers.spec.ts
- pro/src/screens/OfferIndividual/StocksEvent/adapters/serializers.ts
comportements non voulu corrigé: 
* impossible de mettre à jours des nouveau stock sur une offre contenant des evenements dans le passé.
* affichage de la popin de warning "Des réservations sont en cours pour cette offre" meme lorsque le formulaire n'a pas été modifié.
> (19008)[PRO] stock v3: fix edition submit

- pro/src/components/ImageUploader/ImageUploader.module.scss
- pro/src/components/ImageUploader/ImageUploader.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19013
Retirer l'option de prévisualisation dans l'app pour les images des offres collectives
> (PC-19013)[PRO] feat: remove app preview for eac offer image

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20221201T175927_9f7d2f05b501_add_primary_key_to_role_backoffice_profile.py
- api/src/pcapi/core/permissions/models.py
Ajout d'une clé primaire (composée) sur `role_backoffice_profile` et suppression de la contrainte d'unicité.
> (BSR)[API] fix: add composite primary key to role_backoffice_profile

- pro/src/components/StockEventForm/StockEventForm.stories.tsx
- pro/src/components/StockEventForm/StockEventForm.tsx
- pro/src/components/StockEventForm/__specs__/StockEventForm.spec.tsx
- pro/src/components/StockEventForm/__specs__/validationSchema.spec.tsx
- pro/src/components/StockEventForm/constants.ts
- pro/src/components/StockEventForm/types.ts
- pro/src/components/StockEventForm/utils/buildInitialValues.ts
- pro/src/components/StockEventForm/utils/setFormReadOnlyFields.ts
- pro/src/components/StockEventForm/validationSchema.ts
- pro/src/core/Providers/utils/index.ts
- pro/src/core/Providers/utils/utils.ts
- pro/src/screens/OfferIndividual/StocksEvent/StockFormList/StockFormList.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StockEvent.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/adapters/__specs__/serializers.spec.ts
- pro/src/screens/OfferIndividual/StocksEvent/adapters/serializers.ts
..past event validation
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18998
* sur une offre avec 2 stock ayant des ‘bookingQuantity’ differentes
* je veux que la quantité minimum soit le `bookingQuantity’ de chaque stock.
* sur une offre ayant une stock dans le passé
* je ne veux pas avoir l’erreur “L'évènement doit être à venir” au submit.
> (PC-18998)[PRO] reafactor: stock v3: fix past event validation

- adage-front/package.json
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19028
Activation d'une option legacy pour avoir le comportement de Node 16 dessus : 
https://stackoverflow.com/questions/69962209/what-is-openssl-legacy-provider-in-node-js-v17
Avant :
Après : 
Spoiler alert mais le dossier adage-front sera probablement fusionné dans pro prochainement donc le build un peu custom de adage-front disparaitra en passant sur le build de pro qui est standard
> (PC-19028)[PRO] fix: adage deployment

- pro/src/screens/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18884
Ajouter des liens dans l'écran récap de création d'offre collective (vitrine ou non) pour revenir sur une des étapes précédentes (détails, stock, visibilité)
> (PC-18884)[PRO] feat: add edit link in offer collective summary creation

- api/src/pcapi/templates/mails/offer_creation_notification_email.html
- api/src/pcapi/templates/mails/offer_creation_refusal_notification_email.html
- api/src/pcapi/utils/mailing.py
- api/tests/emails/offer_creation_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19047
Corriger une exception remontée par Sentry : 
`IndexError('list index out of range')`
lorsqu'une offre et rejetée, si la structure parente du lieu n'a plus aucun utilisateur rattaché.
C'est un cas à la marge, mais qui peut arrivée si on rejette la structure, puis qu'on rejette ses offres.
> (PC-19047)[API] fix: list index out of range at offer rejection

- api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
- api/tests/core/external_bookings/cds/test_client.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18362
- Les indexes sur la matrice du plan de salles doivent commencer de 0 et non pas de 1.
- Prendre en considération les rangés manquants dans le calcul du numéro siège.
> (PC-18362)[API] fix: CDS seatmap row and col indexes should start from 0

- pro/src/screens/OfferIndividual/DialogStocksEventEditConfirm/DialogStocksEventEditConfirm.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17618
Fix du design de la popup avertissant les utilisateurs : 
Avant : 
Après :
> (PC-17618)[PRO] fix: edit booked offer popup design

- pro/public/index.html
- pro/src/index.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18745
Permettre l'utilisation de hotjar sans avoir besoin de `unsafe-inline` dans la Content Security Policy pour l'exécuter (car cela constitue une faille de sécurité)
- l'appel à hotjar se fait depuis le bundle
- `unsafe-inline` est conservé pour les styles uniquement (et non plus pour les scripts), ce sera un problème à régler dans un second temps
> (PC-18745)[PRO] refactor: add hotjar to bundle

- .circleci/config.yml
- .github/workflows/tests-api.yml
Corriger les configurations de CI
- réactiver le step tests-api dans GHA
- Corriger la syntaxe de `Check for alembic multiple heads` dans chaque CI
- Corriger l'image Docker de Postgres utilisée pour GHA
- On doit utiliser `bash` pour les commandes exécutées en CI, et il ne faut pas oublier de l'utiliser en local pendant le développement (et non `zsh` sur Mac)
> (BSR) Fix DB checks in CI

- api/src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
- api/src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
- api/tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
- api/tests/scripts/offerer/delete_cascade_venue_by_id_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19143
Corriger l'exception remontée par Sentry :
https://sentry.passculture.team/organizations/sentry/issues/401572/?project=5&referrer=slack
Les objets liés à Allocine sont supprimés à la suppression d'un lieu, sauf dans `AllocinePivot`, qui gardait donc une référence sur le lieu et en empêchait la suppression. Par cohérence, on le supprime donc aussi.
> (PC-19143)[API] fix: exception in FA when a venue with allocine pivot is deleted

- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
- api/src/pcapi/static/backoffice/css/base.css
Sur le profil d’un acteur culturel, rendre le nom d’une structure ou d’un lieu cliquable (le nom est souligné au passage de la souris) afin de rediriger l’utilisateur vers la fiche correspondante de l’AC sur le portail pro
> (PC-18967)[BO] feat: Link to PC Pro from offerer and venue details pages

- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
- api/src/pcapi/routes/backoffice_v3/venues.py
- api/tests/routes/backoffice_v3/helpers/html_parser.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18369
Ajout de la donnée ID Adage en dessous de “Éligible EAC”
Afficher ID Adage uniquement s’il existe
Si l’ID Adage est renseigné, Eligible EAC = OUI
> (PC-18369)[BO] feat: Show Adage id in venue details page

- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18848
Si un URL de site web est déclaré sur PC pro pour un lieu, alors l’URL doit s’afficher sur le profil du lieu concerné dans le back office
- afficher la donnée “Site web : xxxxxxx” uniquement s’il existe une valeur
- Cette donnée doit être présente dans le bloc d’informations générales sur le profil lieu
- l’URL doit être cliquable et redirige l’utilisateur vers le site correspondant (sur un nouvel onglet de préférence)
> (PC-18848)[BO] feat: Show website in venue details page

- pro/src/screens/OfferIndividual/ActionBar/ActionBar.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
- pro/src/screens/OfferIndividual/Summary/__specs__/Summary.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18865
- Toaster quand on sauvegarde un image en edition
- Toaster quand on sauvegarde un draft depuis la page de recap
- Toaster de success quand on sauvegarde un draft sur la page stock sans rien dans le form
> (PC-18865)[PRO] fix: save draft toaster

- .circleci/config.yml
Corriger le problème de déploiement de la MES : 
```
yarn install v1.22.19
[1/5] Validating package.json...
error pass-culture-adage-front@217.0.0: The engine "node" is incompatible with this module. Expected version ">=18 <19". Got "16.15.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code exit status 1
```
> (BSR)[PRO] fix: deployment with Node 18

- api/src/pcapi/routes/backoffice_v3/accounts.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/edit.html
- api/tests/routes/backoffice_v3/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19144
La modification des informations d'un compte jeune ou grand public dans le backoffice v3 ne fonctionnait pas.
Les `<form>` html ne peuvent être envoyés par les navigateurs qu'avec l'action `GET` ou `POST`, donc `PATCH` envoyait en fait en `GET`.
> (PC-19144)[BO] fix: update public account

- pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/TicketWithdrawal.tsx
- pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/__specs__/TicketWithdrawal.spec.tsx
- pro/src/components/OfferIndividualForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx
- pro/src/screens/OfferIndividual/Informations/Informations.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19174
Correction de l'enregistrement des informations dans le cas d'une offre avec information de retrait. 
Simplification du code, on ne devrait pas avoir besoin d'un useEffect, le onChange marche bien
> (PC-19174)[PRO] fix: reset withdrawalDelay value on withdrawal type change

- pro/src/components/Notification/Notification.tsx
- pro/src/components/StockEventForm/StockEventForm.tsx
- pro/src/components/StockEventForm/__specs__/StockEventForm.spec.tsx
- pro/src/components/StockEventForm/__specs__/validationSchema.spec.tsx
- pro/src/components/StockEventForm/validationSchema.ts
- pro/src/components/StockThingForm/StockThingForm.tsx
- pro/src/components/StockThingForm/__specs__/validationSchema.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
- pro/src/ui-kit/form/TextInput/TextInput.tsx
- pro/src/ui-kit/form/TextInput/index.ts
- pro/src/ui-kit/form/TimePicker/TimePicker.tsx
- pro/src/ui-kit/form/TimePicker/__specs__/TimePicker.spec.tsx
- pro/src/ui-kit/form/TimePicker/index.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18950
- Ne plus permettre à l'utilisateur de rentrer des lettres pour les champs prix, quantité et horaire.
- Ajout d'une option au composant TextInput: onlyNumbers qui ne modifie pas le champ lorsque l'utilisateur tape autre chose qu'un chiffre.
- Duplication de la règle dans le composant TimePicker
- Tests
- À la base, j'ai créé un composant NumberInput, mais il dupliquait simplement un TextInput avec l'ajout de la règle sur le onKeyPress. De plus, on veut garder un type text (pour le moment) même sur les champs où l'utilisateur ne peut rentrer que des chiffres.
Je l'ai donc supprimé et j'ai juste ajouté une option au composant TextInput.
- PR : `(PC-XXX) Description …
> (PC-18950)[PRO] feat: Write only numbers for price, quantity and timepicker inputs

- helmfile.yaml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19050
Mise à jour de la version du chart pcapi en v0.17.0 pour ajouter le déploiement backofficeV3
> [PC-19050] Upgrade pcapi chart to v0.17.0 for testing

- api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v0/endpoints_test.py
J'ai choisi de mettre ça dans une payload nestée :
```
itemCollection: {
details: str | None
}
```
car pour les événements je prévois d'avoir :
```
itemCollection: {
details: str | None
ticketCollectionWay: "sur place" | "à emporter" | "par email"
ticketSendingDelay : "30 minutes avant l'événement"
}
```
> (PC-18394)[API] feat: add item collection details to product creation payload

- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Ajout de la `native_category_id` lors de l'indexation d'une offre (Algolia).
> (BSR)[API] fix: algolia: add missing field to index

- api/src/pcapi/routes/backoffice_v3/__init__.py
- api/src/pcapi/routes/backoffice_v3/health_check.py
- api/tests/routes/backoffice_v3/health_check_test.py
Ajout des routes `/health/api` et `/health/database` au backoffice v3.
Elles ne sont pas liées au _blueprint_ afin d'avoir exactement les mêmes que sur l'application Flask principale.
> (BSR)[API] fix: add health check routes to backoffice (v3)

- api/src/pcapi/backoffice_app.py
`SESSION_COOKIE_SAMESITE` : **Strict** devient **Lax**.
Il semblerait qu'avec **Strict**, on ait des soucis avec l'authentification Google. **Lax** est l'option par défaut et celle utilisée par l'application principale.
> (BSR)[API] fix: backoffice: cookies: samesite: Lax not Strict

- pro/src/components/StockEventFormRow/StockEventFormRow.module.scss
- pro/src/components/StockThingForm/StockThingForm.module.scss
- pro/src/components/StockThingForm/StockThingForm.tsx
- pro/src/components/StockThingFormRow/StockThingFormRow.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19202
- Mettre les champs du formulaire stock physique à la bonne taille.
- Bien placer le bouton action pour les stocks à droite de la ligne
Avant:
Après:
- Correction de l'alignement pour le bouton action des stocks évènements
Avant:
Après:
> (PC-19202)[PRO] fix: css set correct fields width for stockThing and correct vertical align for stock action

- pro/src/components/OfferIndividualForm/UsefulInformations/Venue/hooks/useVenueUpdates.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19181
- Afficher la modalité de retrait du lieu s'il y en a une lors de la création d'une offre.
bouton “créer une offre” de la page accueil :heavy_check_mark: 
bouton “créer une offre” de la page lieu :heavy_check_mark: : 
bouton “créer une offre” de la page offres :heavy_check_mark: : 
bouton “créer une nouvelle offre” sur la page de confirmation de création d’une offre :heavy_check_mark:
> (PC-19181)[PRO] fix: add venue withdrawdetails when user create an offer

- api/src/pcapi/routes/backoffice_v3/pro.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19274
Changer de page ne fonctionnait pas dans les résultats de recherche d'acteur culturel.
- Cet endpoint n'a pas de test auto sur la fonctionnalité de recherche :-(
- Je n'ai pas pu tester (le backoffice v3 en local ne fonctionne plus) mais le _fix_ est trivial.
> (PC-19274)[BO] fix: pagination in pro search results

- pro/src/styles/components/layout/buttons/TertiaryButton/_TertiaryButton.scss
les css global avait des icons à 24px au lieu de 20px
> (BSR)[PRO] fix old ternary-link button icon size

- api/src/pcapi/routes/backoffice_v3/accounts.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/pro.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19281
Revenir à la page 1 lorsqu'on fait une nouvelle recherche dans le backoffice v3. Comme Google :)
Sinon,  on cherche un  nouveau terme, mais en affichant la 6ème page (par exemple) si on était à la 6ème de la précédente requête, ce qui n'a pas de sens.
Un test auto de cela vérifierait le rendu html du formulaire, en particulier l'attribut d'un tag, ce qui n'est a priori pas souhaitable suite à des discussions d'équipe.
> (PC-19281)[BO] fix: reset page param on new search

- api/src/pcapi/app.py
- api/src/pcapi/backoffice_app.py
Fix : ne pas appeler `install_local_providers()` dans _app.py_ et _backoffice.py_ lors des tests. Car à ce moment-là, les migrations n'ont pas nécessairement été exécutées.
Par exemple, si la base de données de test est réinitialisée. Lors du lancement du moindre test, la fonction plante parce que la table `provider` n'existe pas. Il faut donc s'assurer que les migrations ont bien été exécutées avant de l'appeler.
Cette fonction sera appelée dans les fonctions `build_main_app`/`build_backoffice_app` de _conftest.py_ : à ce moment-là, tout aura été correctement initialisé et la fonction s'exécutera sans problème.
> (BSR)[API] fix: tests: do not install local provider too soon

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20221215T153133_f35df0030ca5_add_offerer_index_postal_code.py
- api/src/pcapi/alembic/versions/20221215T153243_7b3320f4bd9a_add_offerer_index_city.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/models/has_address_mixin.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18772
Dans la recherche de structures à valider du backoffice v3, permettre de rechercher les structures par code postal, code de département et ville.
Ajout d'index sur le code postal et la ville, afin de viser une recherche performante.
> (PC-18772)[BO] feat: search offerers to validate by postal code, department, city

- api/src/pcapi/connectors/boost.py
- api/src/pcapi/core/external_bookings/boost/client.py
- api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
- api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15370
Récupération des affiches de films synchronisés avec Boost
Edition de` boost_stocks.py` et du client Boost.
> (PC-15370) retrieve movie posters from Boost API

- api/src/pcapi/admin/custom_views/boost_pivot_view.py
- api/src/pcapi/admin/custom_views/cine_office_pivot_view.py
- api/src/pcapi/core/providers/repository.py
- api/tests/admin/custom_views/boost_pivot_view_test.py
- api/tests/admin/custom_views/cine_office_pivot_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19142
Corriger la validation des formulaires des vues FA `cine_office_pivot_view` et `boost_pivot_view`
Le validateur du champ `cinema_id` refusait qu'une valeur idAtProvider existe déjà, ce qui bloquait l'édition.
La validation se fait désormais dans `validate_form()`, er ne concerne pas le `DeleteForm`
> (PC-19142) fix FA pivot views

- api/src/pcapi/core/categories/subcategories_v2.py
- api/src/pcapi/routes/native/v1/serialization/subcategories_v2.py
- api/tests/routes/native/v1/openapi_test.py
Correction : on a besoin du `genre_type` au même niveau que la `native_category` dans la réponse de l'API. Pas parmi toutes les informations d'une sous-catégorie.
> (BSR)[API] fix: native: send genre_type within native category

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/users/api.py
- api/tests/core/offerers/test_api.py
- api/tests/core/users/test_api.py
- api/tests/test_utils.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18828
implémenter l'auto tag des nouvelles structure aussi lorsqu'elles sont créées en même qu'un utilisateur pro
RAS
RAS
> (PC-18828)[API] fix: autotag offerer when created with user

- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/backoffice_v3/templates/components/badges.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/tests/core/users/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18840
Ajout d'une vignette explicitant le statut de validation d'un compte pro.
Si un utilisateur pro a au moins un rattachement validé, il est considéré comme validé.
Sinon, et s'il a au moins un rattachement en attente, il est considéré comme en attente.
Sinon, et s'il a au moins une nouvelle demande de rattachement, il est considéré comme nouveau.
Enfin, il y n'a aucun statut sinon.
Ajout d'une propriété au modèle des Users.
> (PC-18840)[API] feat: add pro user status tag

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19049
Ajout d'un filtre sur le statut de la structure à la liste des rattachements
Le filtrage par défaut (NEW et PENDING) pour les rattachements est clairement affiché.
> (PC-19049)[API] feat: add offerer status filter on user offerer list

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19290
Sur la page “Liste de structures à valider”, ajout de la possibilité de chercher par email et par prénom/nom d'un utilisateur pro.
Le ticket demandait plus précisément le filtrage par nom du responsable de la structure. Compte tenu du modèle de données qui ne l'identifie pas clairement, mais oblige à chercher pour chaque structure le `first_user`, limiter au responsable risque de trop impacter les performances de la recherche. En gros le même effet que lorsqu'on avait filtré sur un champ calculé `requestDate`.
Chercher sur n'importe quel utilisateur ne devrait pas être gênant pour le métier, notamment parce que les structures pas encore validées n'ont en général qu'un seul utilisateur, celui qui a demandé …
> (PC-19290)[BO] feat: filter offerers to validate by pro user name or email

- pro/src/core/Providers/constants.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19348
Permettre d'afficher les paramètres spécifiques de synchro de billetterie cinéma pour le Provider Boost
> (PC-19348)[PRO]feat: add boost to Providers constants

- api/src/pcapi/domain/music_types.py
- pro/src/core/Offers/categoriesSubTypes.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19224
- Corriger la faute d'orthographe à "accoustique"
- Changement appliqué au front (`categoriesSubTypes.ts`)  et back (`music_type.py`) .
> (PC-19224)[PRO] fix: blues acoustic subcategory wording

- api/src/pcapi/core/educational/api/stock.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/tests/routes/pro/post_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19044
Il est possible de créer un stock Thing sans date limite de reservation mais impossible de la supprimer une fois qu'elle a été ajoutée.  Il est impossible de supprimer la date limite de reservation pour les stocks Event
> (PC-19044)fix: allow user to delete stockThing limit datetime

- pro/src/components/StockEventForm/StockEventForm.module.scss
- pro/src/components/StockEventForm/StockEventForm.tsx
- pro/src/components/StockEventForm/__specs__/validationSchema.spec.tsx
- pro/src/components/StockEventForm/validationSchema.ts
- pro/src/components/StockEventFormRow/StockEventFormRow.module.scss
- pro/src/ui-kit/form/DatePicker/DatePicker.tsx
- pro/src/ui-kit/form/TextInput/TextInput.tsx
- pro/src/ui-kit/form/TimePicker/TimePicker.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18634
- Mettre les bons messages d'erreur des champs du formulaire de stock event
- Corriger la taille des champs
- Enlever l'espace créé par les messages d'erreur lorsqu'ils ne sont pas visibles.
> (PC-18634)[PRO] fix: stock event error messages and fit fields width with figma

- api/src/pcapi/routes/backoffice_v3/templates/offerer/edit_status_modal.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18822
Permettre de soumettre les formulaires de validation d'une structure en appuyant sur [Enter].
+ Ajout d'un bouton pour pouvoir ajouter un saut de ligne dans le commenaire
+ Ajout d'un raccourcis clavier Ctrl+Enter aussi pour ajouter un saut de ligne dans le commentaire
RAS
RAS
> (PC-18822)[API] feat: allow to submit modals by typing return

- pro/src/components/OfferIndividualForm/utils/__specs__/setFormReadOnlyFields.spec.ts
- pro/src/components/OfferIndividualForm/utils/setFormReadOnlyFields.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19403
In V2 in was possible to have an empty musicType or Show Type, not anymore in V3. 
We need to allow user to edit music types and show Types to solve historical data (and it better for the user to be allowed to change it)
> (PC-19403)[PRO] fix: allow user to change musicType and showType

- .githooks/pre-commit
Désactiver l'exécution parallèle de Pylint dans le `pre-commit` hook
Forcer l'option `--jobs=1` avec un commentaire
- La CI (CircleCI ou GHA) utilise encore ce parallélisme.
La probabilité que le souci apparaisse avec seulement 2 jobs est faible, mais existe -> à discuter dans une autre PR.
- Au passage, résolution d'un FIXME du mois d'août dans la config pylint
> (BSR)[API] fix: disable pylint parallel execution in git hook

- api/src/pcapi/connectors/serialization/boost_serializers.py
- api/src/pcapi/core/external_bookings/boost/client.py
- api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
- api/tests/core/external_bookings/boost/test_client.py
- api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
- Supprimer du code inutilisé: `get_venue_movies()` du client Boost
- Simplifier et tester l'ajout du visa d'exploitation dans les offres et produits
> (BSR) Boost code cleanup

- api/src/pcapi/models/feature.py
in addition to dev and tests environment, we want the FF to be activated by default on integration and testing environments
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19387
> (PC-19387)[API] feat: change Feature Flag default value

- api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v1/endpoints_test.py
books have a special behaviour: we (will) force the isbn field to be present, we retrieve the models.Product if it exists, raise an error if the models.Product is not gcu compatible...
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19318
> (PC-19318)[API] feat: prevent from posting books in POST /products route

- api/src/pcapi/backoffice_app.py
- api/start-backoffice-when-database-is-ready.sh
- docker-compose-backoffice.yml
- infra/pc_scripts/start_backend.sh
- pc
Ajouter une commande `pc start-backoffice` qui lance tout ce qu'il faut pour avoir un backoffice (v3) opérationnel, à la manière de `pc start-backend`.
Cette solution a toutefois un inconvénient : on ne peut lancer `pc start-backoffice` et `pc start-backend` en parallèle puisque les deux utilisent la même image. C'est une contrainte acceptable dans un premier temps.
Pour avoir les deux existant côte-à-côte, il faudrait sûrement regarder du côté de la configuration `nginx` et ça dépasse mes compétences.
> (BSR)[API] feat: pc start-backoffice command

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20221227T083920_3b199dcfba04_remove_app_enable_cookies_v2_feature_flag.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/native/v1/serialization/settings.py
- api/src/pcapi/routes/native/v1/settings.py
- api/tests/routes/native/v1/openapi_test.py
- api/tests/routes/native/v1/settings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18120
Suppression du FF APP_ENABLE_COOKIES_V2
> (PC-18120)[API] feat: FF: remove APP_ENABLE_COOKIES_V2

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/account.py
- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/forms/pro_user.py
- api/src/pcapi/routes/backoffice_v3/forms/utils.py
- api/src/pcapi/routes/backoffice_v3/forms/venue.py
- api/src/pcapi/routes/backoffice_v3/templates/components/form_body.html
- api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
- api/src/pcapi/routes/backoffice_v3/venues.py
- api/tests/routes/backoffice_v3/accounts_test.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18464
Backoffice : permettre la modification des détails d'un lieu.
Note : la nouvelle option `admin_update` est utilisée dans `update_venue` pour ne pas appeler `check_venue_edition` qui s'assure, entre autre, qu'on ne modifie pas le siret (action interdire pour les PRO mais qu'on veut permettre depuis le backoffice). Je ne sais pas s'il est plus pertinent de déplacer cette logique au coeur de `check_venue_edition` afin de mieux cibler les vérifications à ignorer.
> (PC-18464)[API] feat: bo: edit venue details

- api/src/pcapi/backoffice_app.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19241
passer l'expiration de cookie de session du BOv3 à 120 minutes
RAS
RAS
RAS
> (PC-19241)[API] feat: set login duration to 120 minutes on BO

- pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19075
Changer la couleur de la bordure et sa taille lorsqu'on focus via tabulation 
Avant : 
Après : 
> (PC-19075)[PRO] fix: change border color when focus visible

- pro/src/components/StockEventForm/__specs__/StockEventForm.spec.tsx
- pro/src/screens/OfferEducational/OfferEducationalForm/FormVenue/FormVenue.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19430
Régler un bug concernant la bannière de lieu lors de la création d'une offre, la bannière s'affichait alors que la structure n'était pas éligible mais avait déjà des lieux créer et validé. 
> (PC-19430)[PRO] fix: bug information lieu banner

- api/src/pcapi/routes/backoffice_v3/forms/fields.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19454
Sur les pages “Liste des structures à valider” et “Liste des rattachements à valider”, lorsqu’on met en attente ou rejette une demande avec le commentaire “AE”, on obtient une page de redirection puis un bandeau d’erreur après clic sur le lien, qui nous impose la saisie d’un commentaire différent 
> (PC-19454)[API] feat: Erreur lors de la saisie des commentaires de rejet ou mise ne attente

- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details/users.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19455
Comportement observé (+ screenshot ou vidéo)
La zone cliquable des actions “Valider”, “Rejeter” et “Mettre en attente” sur les pages “Liste des structures à valider” et “Liste des rattachements à valider” est trop restreinte, puisqu’il est nécessaire de cliquer précisément sur le libellé pour que l’action se réalise. Sinon il faut ré-ouvrir la pop-in et recliquer sur l’action.
Si on clique sur la ligne mais pas correctement sur le libellé, cela ne fonctionne pas.
Elargissement de la zone cliquable sur les boutons à toute la largeur. 
> (PC-19455)[API] feat: Zone cliquable des actions "Valider", "Mettre en attente" et "Rejeter"

- api/tests/core/external/external_users_test.py
- api/tests/routes/external/zendesk_test.py
- api/tests/scripts/external_users/batch_update_users_attributes_test.py
Corriger les tests Zendesk et Sendinblue qui échouent à cause du passage en 2023.
> (BSR)[API] test: Fix date-related errors in Zendesk and Sendinblue tests

- pro/src/core/OfferEducational/adapters/__specs__/cancelCollectiveBookingsAdapter.spec.ts
- pro/src/core/OfferEducational/adapters/cancelCollectiveBookingAdapter.ts
- pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19312
Changer le wording du toaster lorsqu'on annule une réservation / offre en status expiré, pour tous les autres status enlevé le '/ pré reservation' 
> (PC-19312)[PRO] fix: wording toaster when cancel resa expired status

- api/requirements.txt
The new SQLAlchemy 1.4.46 release introduces a new behaviour:
A new deprecation “uber warning” is now emitted at runtime the
first time any SQLAlchemy 2.0 deprecation warning would normally
be emitted, but the SQLALCHEMY_WARN_20 environment variable is not
set. The warning emits only once at most, before setting a boolean
to prevent it from emitting a second time.
See https://docs.sqlalchemy.org/en/20/changelog/changelog_14.html#change-1.4.46
for further details.
We're not ready for this warning, let's pin SQLAlchemy until then.
> (BSR)[API] chore: Pin SQLAlchemy until we have fixed deprecation warnings

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18964
En tant que responsable homologation ou chargé de développement
J'aimerais rechercher une demande de rattachement via le nom du compte pro
Afin de gagner du temps
- Ajout d’un champ de recherche sur la page “Rattachements à valider”, à positionner en haut de page tout à gauche (de la même façon que ce qu’on propose sur la page “Structures à valider”
- Il doit être possible de rechercher une demande de rattachement via : 
- Le nom du compte pro 
- l’email du compte pro
- Le nom de la structure 
- Le Siren de la structure 
> (PC-18964)[API] feat: Recherche sur la page "Rattachements à valider"

- pro/.prettierrc
- pro/.stylelintrc.json
- pro/.vscode/settings.json
- pro/package.json
- pro/yarn.lock
Fait apparaitre les erreurs Stylelint dans VSCode + fix des faux positifs avec Prettier
> (BSR)[PRO] fix: prettier+stylelint config

- api/src/pcapi/connectors/dms/serializer.py
Some old dms applications still have this old form value. Cf [cet événement sur sentry](https://sentry.passculture.team/organizations/sentry/issues/382141/events/4401e9f97e8b4598b9ea4df88e9eaca1/?environment=production&project=5&query=is%3Aunresolved&statsPeriod=14d)
Il y a toujours l'erreur avec la valeur "Apprenti, Alternant, Volontaire en service civique rémunéré" mais comme on ne peut pas savoir si c'est Apprenti, Alternant ou Volontaire, je laisse comme ça.
> (BSR)[API] feat: add dms form activity value

- api/src/pcapi/routes/backoffice_v3/forms/venue.py
- api/src/pcapi/routes/backoffice_v3/venues.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19147
Ajout d'un bouton pour passer un lieu (non-virtuel) en un lieu permanent (et vice-versa).
[PC-19147]: https://passculture.atlassian.net/browse/PC-19147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PC-19147)[API] feat: add isPermanent switch on venue edition page

- api/src/pcapi/routes/backoffice_v3/pro_users.py
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get/details.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get/details/user_offerer.html
- api/tests/routes/backoffice_v3/pro_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18478
Ajout de l'onglet rattachement aux structures dans la page d'un compte pro.
[PC-18478]: https://passculture.atlassian.net/browse/PC-18478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PC-18478)[API] feat: add user offerer tab on pro user page

- .circleci/config.yml
- .github/workflows/tests-api.yml
- .github/workflows/tests-backoffice-v3.yml
- .github/workflows/tests-backoffice.yml
- .github/workflows/tests-pro.yml
J'ai repris ce que j'avais configuré pour [l'action build-and-tag](https://github.com/pass-culture/pass-culture-main/blob/master/.github/workflows/reusable--build-and-tag.yml#L142)
> (BSR) feat: improve CI failure notification

- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get/details.html
Supprimer l'onglet comptes pro rattachés de la page de détails d'un lieu : il n'a aucune raison d'être là.
L'id de l'onglet a été renommé. `pills-history` me semblait plus logique que `pills-home`.
> (BSR)[API] fix: bov3: venue details: rm unused tabs

- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19556
Corriger le lien vers la page de la structure, depuis la page du lieu, dans le backoffice v3.
[PC-19556]: https://passculture.atlassian.net/browse/PC-19556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PC-19556)[BO] fix: offerer link in venue details page

- pro/src/components/Notification/Notification.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StockFormList/StockFormList.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StockEvent.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.edition.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19464
- Permettre à l'utilisateur de supprimer un stock synchronisé si possible en ne désactivant pas le bouton supprimer.
> (PC-19464)[PRO] fix: allow to delete synchronized offer in edition mode

- pro/src/components/FormLayout/FormLayoutSection.tsx
- pro/src/components/Notification/Notification.tsx
- pro/src/pages/OfferIndividualWizard/Stocks/__specs__/Stocks.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
- pro/src/ui-kit/Banners/Banner/Banner.tsx
- pro/src/ui-kit/Banners/Banner/index.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18985
Sur la page édition:
- Ajouter une bannière d'information pour les stocks événements et physique.
- Ajouter un lien FAQ pour les stocks de type événement et numériques.
- Changer les descriptions.
Numérique:
physique:
événement:
[PC-18985]: https://passculture.atlassian.net/browse/PC-18985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PC-18985)[PRO] feat: Add banner with link in edition mode

- api/src/pcapi/settings.py
It's defined in `.env.*` files.
> (PC-19544)[API] fix: OBJECT_STORAGE_URL is not a secret

- pro/src/components/HelpLink/HelpLink.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19200
Déplacer le bouton d'aide afin qu'il ne soit pas superposé avec la sticky bar
Avant:
Après:
> (PC-19200)[PRO] fix: replace help button

- api/src/pcapi/core/providers/api.py
- api/tests/core/providers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18594
marquer comme permanents les lieux qui déclarent une synchro
RAS
la requête de rattrapage à lancer sur la prod quand la PR sera mergée:
```sql
WITH permanent_venues AS (
SELECT
v.id,
v.name,
v."isPermanent",
p.name AS provider,
vt.label AS type
FROM provider AS p
JOIN venue_provider AS vp ON p.id = vp."providerId"
JOIN venue AS v ON v.id = vp."venueId"
JOIN venue_type AS vt ON v."venueTypeId" = vt.id
WHERE p."isActive" IS TRUE
AND p."enabledForPro" IS TRUE
AND v."isPermanent" IS FALSE
AND vt.label in ('Librairie', 'Cinéma - Salle de projections')
ORDER BY vt.label, p.name DESC
)
-- SELECT *
-- FROM permanent_venues
UPDATE venue
SET "isPermanent" = TRUE
WHERE id IN (SELECT id FROM permanent_venues)
;
```
RAS
- …
> (PC-18594)[API] feat: auto set permanent synced venues

- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/tests/routes/pro/get_offerer_test.py
- pro/src/apiClient/v1/models/GetOffererVenueResponseModel.ts
- pro/src/core/Venue/types.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18949
- Ajouter à une `Venue` l'information sur l'existence d'une `Offer` (pas en `DRAFT`) qui y serait liée.
- Ajout d'un champ hasCreatedOffer pour distinguer les lieux qui ont créé des offres.
[PC-18949]: https://passculture.atlassian.net/browse/PC-18949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PC-18949)[PRO] feat: Adding a flag for venues with offers.

- api/src/pcapi/core/finance/repository.py
- api/src/pcapi/routes/pro/finance.py
- api/src/pcapi/routes/serialization/finance_serialize.py
- api/tests/core/finance/test_repository.py
- api/tests/routes/pro/get_reimbursement_points_test.py
- pro/src/apiClient/v1/services/DefaultService.ts
This was the only place we had some dehumanization on finance endpoints. 
An other route GET business_units, that is not used anymore, should be deleted
It is not possible to filter by offerer_id from pro front
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19192
> (PC-19192) [API] chore: remove unused param

- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19345
Ajout d'un bouton pour cacher les filtres sur les pages de validation de structure et de validation des rattachements de structure.
> (PC-19345)[API] feat: add hiding filters button on validation pages

- adage-front/src/styles/_colors.scss
- pro/src/components/StockEventForm/StockEventForm.module.scss
- pro/src/components/StockEventForm/StockEventForm.tsx
- pro/src/components/StockEventFormRow/StockEventFormInfo/StockEventFormInfo.module.scss
- pro/src/components/StockThingForm/StockThingForm.tsx
- pro/src/screens/OfferEducationalStock/FormStock/FormStock.tsx
- pro/src/styles/mixins/_forms.scss
- pro/src/styles/variables/_forms.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19436
- Corriger l'affichage des champs du formulaire de stock (surtout en édition)
- Corriger la couleur du placeholder sur firefox
- Retirer le placeholder des champs prix, et ajouter l'icône € (même sans valeur)
> (PC-19436)[PRO] fix: stocks forms inputs width and price input placeholder

- .github/workflows/tests-main.yml
- .github/workflows/update-api-client.yml
Cancel previous workflows when a new one is triggered.
Pour que la facture soit moins salée.
Et pour que les océans restent salés.
> (BSR) workflow concurrency

- api/src/pcapi/routes/backoffice_v3/templates/components/history/actions.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/edit_status_modal.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19558
Corriger des petits bugs pour l'ajout d'une nouvelle ligne dans un commentaire
- newline button did not give focus back to textarea
- cursor was at the end when CR is entered, now at the same position
- shift+Enter submitted the form, now new line
- modal popup textarea did not show 3 rows
- comments were displayed as single lines in tables, now new line on CR
> (PC-19558)[BO] fix: new lines in comments

- api/src/pcapi/alembic/versions/sql/schema_init.sql
- api/src/pcapi/app.py
- api/src/pcapi/backoffice_app.py
- api/tests/conftest.py
Avantage : 
Supprimer les `install_local_providers` qu'il faut répéter à plein d'endroits (notamment dans les tests).
En effet les local_providers sont installés dans les migrations (init)
Le seul usage qui resterait serait pour "relancer la sandbox" en env testing.
Inconvénient : 
Quand on ajoute un "local provider" il faut l'ajouter à la fois dans `install_local_providers` (pour la sandbox de testing) et dans une migration de données.
> Stop installing local providers

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230110T082249_525089ccbb4d_remove_wip_enable_backoffice_v3_feature_flag.py
- api/src/pcapi/alembic/versions/20230110T082449_f94795ee981a_remove_venue_form_v2_feature_flag.py
Supprimer de la base de données deux FF qui n'existent plus :
- WIP_ENABLE_BACKOFFICE_V3 (supprimé hier)
- VENUE_FORM_V2
Afin d'éviter l'erreur au démarrage :
`ERROR:pcapi.models.feature:The following feature flags are present in database but not present in code: {'WIP_ENABLE_BACKOFFICE_V3', 'VENUE_FORM_V2'}`
> (BSR)[API] fix: delete removed feature flags from database

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/notifications/push/__init__.py
- api/src/pcapi/notifications/push/backends/batch.py
- api/src/pcapi/notifications/push/backends/logger.py
- api/src/pcapi/notifications/push/backends/testing.py
- api/tests/core/users/test_api.py
- api/tests/routes/native/v1/subscription_test.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19264
Envoyer un évènement à Batch quand un utilisateur voit son crédit activé, pour lui envoyer une notification par la suite
- Une fonction `track_event` pour batch
- Un evenement pour le cas concret
- None
- None
> PC-19264 send event to batch when a user activates their deposit

- .github/workflows/tests-main.yml
Sur master, budget illimité.
Pour éviter que le déploiement suite au merge d'une PR soit annulé par le merge d'une autre PR, ce qui met helm en pls et retarde la livraison des tickets
> (BSR) fix: remove workflow concurrency on master

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/forms/search.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/string_field.html
- api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details/users.html
- api/tests/routes/backoffice_v3/helpers/html_parser.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19110
Dans le backoffice v3, permettre d'ajouter un compte pro dans les rattachements d'une structure ; automatiquement validé.
Le compte ne peut être que parmi ceux ayant déjà eu un lien avec la structure (lien rejeté et/ou supprimé), à partir de l'historique que l'on construit désormais. Voir les conditions dans le ticket.
Le ticket suggérait un bouton grisé lorsque le formulaire de la popup n'est pas encore rempli, puis actif. Cela n'est pas cohérent avec le reste du backoffice v3, et demanderait à exécuter du JS natif à chaque touche appuyée.
La solution retenue est plutôt d'utiliser les attributs `required`, `minlength` et `maxlength` dans les champs du formulaire, associés à `checkValidity()` lors du clic sur le …
> (PC-19110)[BO] feat: add pro user to offerer

- api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19451
Depuis la version 7.2 de turbo, les erreurs 500 (et plus) sont traitées différemment : tout le contenu de la page est remplacé par celui reçu. Par exemple, si un `turbo-frame` de la page de détails d'une offre met trop de temps à répondre, nginx renvoie une 504 pour cet élément et turbo remplace toute la page par le code html d'erreur de nginx. Donc une erreur dans un `turbo-frame` et toute la page saute :cry:
Donc en cas d'erreur, ce fix permet d'afficher un message d'erreur basique.
Cette solution ne règle pas certains problèmes de fond mais elle permet de rendre certaines pages utilisables, en attendant.
> (PC-19451)[API] fix: bov3: JS: Handle 5xx errors within turbo-frames

- pro/src/components/StockEventForm/StockEventForm.tsx
- pro/src/components/StockEventForm/__specs__/StockEventForm.spec.tsx
- pro/src/components/StockEventForm/constants.ts
- pro/src/screens/OfferIndividual/StocksEvent/StockFormList/StockFormList.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19464
- Désactiver les champs du formulaire de stock pour les offres synchronisées en édtition.
> (PC-19464)[PRO] fix: remove synchronized stocks returns

- pro/src/ui-kit/form/PasswordInput/PasswordInput.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19322
ajout du type button pour ne plus avoir l'effet de bord d'affichage du mot de passe au click sur enter
> (PC-19322)[PRO] fix: style correction

- pro/src/screens/OfferIndividual/StocksEvent/adapters/__specs__/serializers.spec.ts
- pro/src/screens/OfferIndividual/StocksEvent/adapters/serializers.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19773
2 cas : 
- La date limite de reservation est le jour de l'évenement -> L'heure et la date de reservation sont mis à celle de l'évenement
- La date limite de reservation n'est pas le même jour que l'évt -> On set l'heure à 23:59:59s (fin de la journée de la date de limite de reservation)
> (PC-19773)[PRO] fix: when bookingLimitDatetime is same day as event begining

- api/src/pcapi/core/mails/backends/sendinblue.py
- api/src/pcapi/settings.py
- api/tests/core/mails/tests.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19791
Correction: déplacement des secrets de la variable `DEV_EMAIL_ALIAS_ADDRESS`  pour les envs
NA
Exemples: nettoyage de code
NA
> (PC-19791)[API] fix: rename secrets.DEV_EMAIL_ALIAS_ADDRESS to env.END_TO_END_TESTS_EMAIL

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/components/history/actions.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get.html
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18368
Permettre de gérer (ajouter ou retirer) les tags d'une structure depuis la page de détails d'une structure dans le backoffice v3.
> (PC-18368)[BO] feat: Edit offerer tags from details page

- pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/DuplicateOfferCell.tsx
- pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/__specs__/DuplicateOfferCell.spec.tsx
- pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx
- pro/src/ui-kit/Button/Button.stories.tsx
- pro/src/ui-kit/Tooltip/Tooltip.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19406
Ne plus avoir le bouton focus lorsqu'on ferme la modal concernant la duplication d'une offre vitrine, changer le wording du tooltip
> (PC-19406)[PRO] fix: button focus after modal

- .github/workflows/tests-main.yml
- .github/workflows/tests-pro.yml
- pro/sonar-project.properties
Mis en place sur le clone du repo https://github.com/pass-culture/pass-culture-main-config-sonarcloud, maintenant que nous avons une config qui marche bien on souhaite la mettre en place sur le vrai repo.
> (BSR)[PRO] chore: add SonarCloud to the project

- api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19781
Corriger l'affichage des filtres dans les écrans de validation des structures et rattachements.
Ils se retrouvaient cachés lorsqu'il n'y a pas de résultat (_body_ trop court).
> (PC-19781)[BO] fix: offerer validation filters hidden when no results returned

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
If a venue had 2 pricing points and one of them was in
FINANCE_OVERRIDE_PRICING_ORDERING_ON_PRICING_POINTS, we processed each
pricing twice, which failed the second time. Using `distinct()` solves
that.
> (PC-19809)[API] fix: Fix bug in _delete_dependent_pricings with FINANCE_OVERRIDE_PRICING_ORDERING_ON_PRICING_POINTS and multiple pricing points

- pro/src/components/StockEventForm/__specs__/StockEventForm.spec.tsx
- pro/src/screens/OfferIndividual/ActionBar/ActionBar.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StockEvent.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
- pro/src/ui-kit/SubmitButton/SubmitButton.tsx
- pro/src/utils/date.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19286
- Afficher un toast de succès lorsqu'il n'y a pas de stock et qu'on clique sur enregistrer les modifications.
- Afficher le modal de suppression de stock en edition et à chaque fois, même lorsqu'il n'y a pas de réservation.
> (PC-19286)[PRO] fix: toast when user delete stock thing or event

- .github/workflows/build-and-push-docker-images.yml
- .github/workflows/deploy.yml
- .github/workflows/tests-api.yml
- .github/workflows/tests-backoffice.yml
- .github/workflows/tests-main.yml
- .github/workflows/tests-pro.yml
- run api/pro/adage/backoffice test job only if the folder changes, which improves CI pull requests state visualization on Github
- stop deploying api (resp pro/backoffice/adage) if api (resp pro/backoffice/adage) folder did not change
- build api docker image just before deploying, which has 2 benefitss:
- the tests-api step lasts 30 seconds less
- the image build needed to deploy is less hidden (it was inside the tests-api job)
- drawback: the deployment on testing lasts 2 minutes more ; this will be less if we add cache to docker image
Avant : 
Maintenant :
> (BSR) Improve CI workflow

- backoffice/src/libs/environment/tests/parser.test.ts
- backoffice/src/providers/authProvider.ts
- backoffice/src/providers/dataProvider.ts
- pro/.eslintrc.js
- pro/scripts/customRequestv1.ts
- pro/scripts/customRequestv2.ts
- pro/src/apiClient/v1/core/request.ts
- pro/src/apiClient/v2/core/request.ts
- pro/src/components/RouteLeavingGuard/RouteLeavingGuard.tsx
- pro/src/core/OfferEducational/adapters/patchIsCollectiveOfferActiveAdapter.ts
- pro/src/core/OfferEducational/adapters/patchIsTemplateOfferActiveAdapter.ts
- pro/src/core/Offers/utils/computeOffersUrl.ts
- pro/src/pages/Bookings/__specs__/BookingsRecap.spec.tsx
- pro/src/pages/CollectiveOfferEdition/adapters/patchCollectiveOfferTemplateAdapter.ts
- pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx
- pro/src/pages/OffererStats/__specs__/OffererStats.spec.tsx
- pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderParamaters/AllocineProviderParameters.tsx
- pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderForm/CinemaProviderForm.tsx
- pro/src/pages/Offers/Offers/ActionsBar/adapters/__specs__/updateAllCollectiveOffersActiveStatusAdapter.spec.ts
- pro/src/pages/Offers/Offers/ActionsBar/adapters/__specs__/updateCollectiveOffersActiveStatusAdapter.spec.ts
- pro/src/pages/Offers/__specs__/Offers.spec.tsx
- pro/src/screens/Bookings/BookingsRecapTable/__specs__/BookingsRecapTable.spec.tsx
- pro/src/screens/Bookings/PreFilters/PreFilters.tsx
- pro/src/screens/CollectiveOfferVisibility/__specs__/CollectiveOfferVisibility.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/ActivationCodeFormDialog/ActivationCodeFormDialog.tsx
- pro/src/screens/OfferIndividual/Summary/StockSection/StockSection.tsx
`ts-expect-error` est meilleur que `ts-ignore` car si l'erreur TS originale disparait, `ts-expect-error` causera une erreur alors que `ts-ignore` restera indéfiniment (et prend le risque de masquer une 2nde erreur TS qui surviendrait au même endroit)
> (BSR)[PRO] style: replace ts-ignore by ts-expect-error

- api/src/pcapi/routes/native/v1/bookings.py
- api/src/pcapi/routes/native/v1/serialization/bookings.py
- api/tests/routes/native/v1/bookings_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18717
- ajout des dates de réservation à la réponse du endpoint de liste des réservations
- les réservations d'offres non expirables, qui ne sont pas des évènements, et qui ont plus de 30 jours sont considérées comme terminées
RAS
RAS
RAS
> Pc 18717 archive unexpirable digital offers

- .circleci/config.yml
- .githooks/pre-commit
- .github/workflows/check-folder-changes.yml
- .github/workflows/tests-main.yml
- pro/sonar-project.properties
Dans cette PR plusieurs améliorations : 
- lancement des pipelines sur l'event `pull_request` plutôt que `push`. [Pourquoi et les implications](https://passcultureteam.slack.com/archives/C01CTV65S3A/p1673617655110439)
- affichage du commentaire SonarCloud sur les PRs
- ignore du API client généré automatiquement dans le coverage/duplications
- suppression des checks coverage de Jest pour laisser la main à Sonar
> (BSR)[PRO] improve SonarCloud config

- pro/src/components/StockEventForm/stockEventFactory.ts
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StockEvent.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/hasChangesOnStockWithBookings.spec.tsx
- pro/src/ui-kit/Button/Button.tsx
- pro/src/ui-kit/Button/ButtonLink.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19823
_La modale attention stock déjà réservé lors d'une modif de stock ne s'affichait pas au bon moment
2 pb : 
- un mauvais rebase a dupliqué du code qu'il ne fallait pas
- on utilisait touched de formik mais en le mettant dans le submit tous les champs sont automatiquement passé à true (on regarde maintenant si nos champs sont différents)
> (PC-19823)[PRO] fix: warning when modifying booked event

- adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferDetails.tsx
- adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferVenue/OfferVenue.tsx
- pro/src/components/CollectiveOfferSummary/components/CollectiveOfferPracticalInformation/CollectiveOfferPracticalInformation.tsx
- pro/src/components/CollectiveOfferSummary/components/CollectiveOfferPracticalInformation/__specs__/CollectiveOfferPracticalInformation.spec.tsx
- pro/src/components/CollectiveOfferSummary/components/utils/__specs__/formatOfferEventAddress.spec.ts
- pro/src/components/CollectiveOfferSummary/components/utils/formatOfferEventAddress.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19897
Fix l'affichage du lieu dans les informations pratiques d'une offre collective. Actuellement le lieu affiché était le lieu qui percevra les remboursements alors que ces deux informations sont différentes.
> Pc 19897 eac fix venue displayed in collective practical informations

- api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v1/endpoints_test.py
Il y avait un bug en édition : si on mettait "unlimited" on avait une 500 car le champ n'était pas transformé en `None`.
> (PC-19746)[API] fix: fix 'unlimited' quantity deserialization

- .github/workflows/tests-api.yml
4 pytest instances are run in parallel through a matrix job. When one
of these instance fails, the default behaviour in GitHub Actions is to
cancel the other running ones [1]. As such, some tests are not run and
we just don't know whether they would have failed.
Now all pytest instances are run until their end, even if one them
already failed.
[1] https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
> Don't cancel a pytest matrix job when another fails

- api/src/pcapi/routes/serialization/collective_bookings_serialize.py
- api/tests/routes/pro/get_all_collective_bookings_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/CollectiveBookingCancellationReasons.ts
- pro/src/apiClient/v1/models/CollectiveBookingResponseModel.ts
- pro/src/apiClient/v1/models/CropParams.ts
- pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/CollectiveTimeLine/CollectiveTimeLine.tsx
- pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/CollectiveTimeLine/__specs__/CollectiveTimeLine.spec.tsx
- pro/src/ui-kit/Timeline/Timeline.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18943
Adapter la timeline pour le suivi des réservations lorsque le status de la réservation est annulé en créer la timeline via le `booking_status_history `
> pc-18943-reservation_status_cancelled

- pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx
- pro/src/components/OfferEducationalActions/__specs__/OfferEducationalActions.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19895
- Cacher le bouton 'Masquer la publication sur Adage/ Publier sur adage' quand le statut de l'offre est expiré 
- Ajouter des tests pour le fichier affichant ce bouton (OfferEducationalActions)
> Pc 19895 eac hide collective action button if offer expired

- pro/src/components/SummaryLayout/SummaryLayoutSection.tsx
- pro/src/screens/OfferIndividual/Summary/OfferSection/OfferSection.tsx
- pro/src/screens/OfferIndividual/Summary/StockSection/StockSection.tsx
- pro/src/ui-kit/Button/ButtonLink.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17066
- Ajouter des aria text aux boutons "modifier" de la page de récapitulatif.
- Ajout d'aria label.
> (PC-17066)[PRO] feat: add aria label to modifications buttons in summary

- api/src/pcapi/core/mails/transactional/pro/invoice_available_to_pro.py
`to_euros()` returns a Decimal. It's automatically turned into a float
by `pcapi.tasks.decorator.task()` that serializes in JSON the
SendTransactionalEmailRequest object and then deserializes it back
before sending it to Google Cloud Tasks.
But when running locally (or in end-to-end tests) with the SendinBlue
backend, we don't use tasks. Thus, a `Decimal` param is sent to the
SendinBlue client, which does not know how to serialize it to JSON.
By converting to a float here, we don't change what happens when going
through Google Cloud Tasks, and we fix the behaviour when we don't use
tasks.
> (BSR)[API] test: Fix e-mail template param type in send_invoice_available_to_pro_email

- api/src/pcapi/core/mails/backends/sendinblue.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20073
Modification de fonctionnalités: envoi de mail dans le cadre de test e2e
Les emails sont envoyés via sendinblue si :
- `RUN_ENV=tests`, `END_TO_END_TESTS_EMAIL_ADDRESS` et `EMAIL_BACKEND=pcapi.core.mails.backends.sendinblue.ToDevSendinblueBackend` 
au lieu de:
-  `IS_TESTING=true`,  `IS_STAGING=true`  et `END_TO_END_TESTS_EMAIL_ADDRESS` et `EMAIL_BACKEND=pcapi.core.mails.backends.sendinblue.ToDevSendinblueBackend`
> (PC-20073)[API] fix: sendinblue detect e2e RUN_ENV=tests

- api/requirements.txt
- api/src/pcapi/connectors/cgr/cgr.py
- api/src/pcapi/connectors/cgr/exceptions.py
- api/src/pcapi/connectors/serialization/cgr_serializers.py
- api/src/pcapi/settings.py
- api/tests/connectors/cgr/api_cgr_test.py
- api/tests/connectors/cgr/soap_definitions.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19935
- Ajout d'un connector pour l'API CGR
- Implémentation de l'appel `getSeancesPassCulture`.
- Ajout de la librairie `zeep` pour faire des appel SOAP
> (PC-19935)[API] feat: CGR Connector

- api/src/pcapi/core/bookings/factories.py
- api/src/pcapi/core/categories/categories.py
- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/forms/collective_booking.py
- api/src/pcapi/routes/backoffice_v3/forms/individual_booking.py
- api/src/pcapi/routes/backoffice_v3/forms/utils.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/components/filters_form.html
- api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html
- api/src/pcapi/utils/date.py
- api/tests/routes/backoffice_v3/collective_bookings_test.py
- api/tests/routes/backoffice_v3/individual_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19694
Ajout de champs de recherche/filtrage sur les écrans de réservations individuelles et collectives (backoffice v3).
> Pc 19694 backoffice bookings filters

- pro/src/pages/CollectiveOfferRoutes/CollectiveOfferCreationRoutes/CollectiveOfferCreationRoutes.tsx
- pro/src/pages/CollectiveOfferRoutes/CollectiveOfferEditionRoutes/CollectiveOfferEditionRoutes.tsx
Modifier le titre de la page des stocks des offres collectives -> désormais `Date et prix`
> (PC-19870)[PRO] chore: change collective stock page title

- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/src/pcapi/serialization/decorator.py
- api/tests/serialization/serialization_decorator_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19901
- 1 commits to forbid extra fields on PATCH and POST on individual offer api
We don't fail when provided json body is invalid. It is important for the CM API where lots of partners software send us PATCH and POST request without any body or an invalid body. We don't want that behaviour for the individual offer API.
Let's add some logging to see what is send
> (PC-19901)[API] fix: return 400 on invalid json

- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/history/models.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/core/providers/api.py
- api/src/pcapi/core/search/backends/algolia.py
- api/src/pcapi/infrastructure/repository/pro_offers/offers_recap_domain_converter.py
- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
- api/src/pcapi/local_providers/titelive_things/titelive_things.py
- api/src/pcapi/models/extra_data_mixin.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/src/pcapi/utils/db.py
- api/tests/core/providers/test_api.py
- api/tests/routes/native/v1/openapi_test.py
- api/tests/routes/pro/get_offers_test.py
- pro/src/apiClient/v1/models/WithdrawalTypeEnum.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20049
Malheureusement on ne peut pas : 
- utiliser une variable comme clé (cf [cette issue](https://github.com/python/mypy/issues/7178))
- typer les propriétés d'un TypedDict avec le type TypedDict (cf [cette issue](https://github.com/python/mypy/issues/5149))
- caster un TypedDict en dict (cf [cette issue](https://github.com/python/mypy/issues/4976))
- Le type de `extra_data.get("diffusionVersion", "")` est `str | None`
- pas de validation du typage quand on appelle extraData en tant que propriété de classe (ex: `offers_models.Product.extraData["isbnz"].astext`)
> (PC-20049)[API] refactor: improve offer ExtraData

- pro/src/pages/Home/Venues/Venue.scss
- pro/src/pages/Home/Venues/Venue.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20023
- Placer le nom du lieu à gauche, et aligner l'icône avec le texte.
- Alignement de l'icône avec le nom du lieu pour que ça fonctionne avec une ou plusieurs lignes de texte.
> (PC-20023)[PRO] fix: home venue name alignment

- api/src/pcapi/core/finance/commands.py
- api/tests/core/finance/test_commands.py
> FIXME: move this to a proper Flask command.
([source](https://github.com/pass-culture/pass-culture-main/blob/dbaty/move_siret/api/src/pcapi/scripts/move-siret.py))
C'est chose faite. Le code pour déplacer un siret a désormais sa propre commande Flask.
> (BSR)[API] feat: new finance command: move siret

- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/routes/backoffice_v3/blueprint.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details/managed_venues.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/offerer_tag.html
- api/src/pcapi/routes/backoffice_v3/utils.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19990
Possibilité de supprimer un tag de structures dans le backoffice v3.
Cette option nécessite une permission spécifique donnée aux admin, et n'est pas accessible pour tout utilisateur pouvant créer des tags ou gérer des structures (car ça retire le tag supprimé à toutes les structures ; donc plus destructif).
> (PC-19990)[BO] feat: Delete offerer tag

- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card_offerer.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card_venue.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get.html
- api/tests/routes/backoffice_v3/offerers_test.py
- api/tests/routes/backoffice_v3/pro_users_test.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20141
Uniformiser les ID entre les résultats de recherche et le profil des AC 
> (PC-20141)[BO] fix: consistent ids displayed in results/details

- api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
- api/tests/routes/public/individual_offers/v1/endpoints_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19569
Renvoyer 404 plutôt qu'une liste d'évènements/produits vide si un utilisateur requête ceux liés à un lieu qui n'est pas relié à l'utilisateur.
> (PC-19569)[API] feat: raise 404 when querying venue unrelated to user

- pro/src/components/FormLayout/FormLayout.module.scss
- pro/src/components/FormLayout/FormLayoutDescription.tsx
- pro/src/components/FormLayout/FormLayoutSection.tsx
- pro/src/components/FormLayout/__specs__/FormLayoutDescription.spec.tsx
- pro/src/components/FormLayout/index.tsx
- pro/src/components/OfferFormLayout/OfferFormLayout.module.scss
- pro/src/pages/OfferIndividualWizard/Stocks/__specs__/Stocks.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/StockFormList/StockFormList.module.scss
- pro/src/screens/OfferIndividual/StocksEvent/StocksEvent.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StockEvent.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.RouteLeavingGuard.spec.tsx
- pro/src/screens/OfferIndividual/StocksEvent/__specs__/StocksEvent.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.RouteLeavingGuard.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.draft.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.edition.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20020
- Ajuster l'espacement (bouton ajouter une date) entre la bannière et le formulaire de stock
- édition de stock: Lors du clique sur le bouton "enregistrer les modifications" avec un stock vide, rediriger vers le récapitulatif.
- Supprimer le titre Stock & prix en édition.
- 45px au dessus des bannières en édition de stock, 16px entre le bouton 'ajouter une date" et la ligne de stock (event), 32p entre le bouton "ajouter une date" et la bannière.
- Plus de titre "Stock & prix"
- Redirection vers le récapitulatif lorsque l'utilisateur enregistre les modifications avec un formulaire vide.
- Modifications dans les tests:
- Ajout de data-testid  pour compenser le findByRole('heading') dans les tests, pour les …
> (PC-20020)[PRO] fix: stocks ux UI

- api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/static/backoffice/js/pc-override-custom-textarea-enter.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20129
Resoudre le bug lié à ce Comportement Observé : 
Lorsqu’on sélectionne plusieurs demandes de rattachement pour mise en attente ou rejet en masse, il n’est pas possible de valider le commentaire et le changement de statut en appuyant sur Entrée (il faut cliquer sur le bouton), alors que c’est possible lors d’une sélection unique
Création des fonctions pour soumettre le formulaire lors de l'appui sur la touche entrée depuis le champs de commentaire et le retour à la ligne forcé depuis le clic du bouton. 
> (PC-20129)[API] fix: Liste des rattachements - Touche retour modale multi-sélection

- api/src/pcapi/core/external/batch.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/src/pcapi/notifications/push/__init__.py
- api/tests/core/fraud/dms/test_api.py
- api/tests/core/subscription/dms/test_api.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/routes/saml/educonnect_test.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18797
Envoyer un event batch au démarrage d'id check
Ct event est utilisé comme 'cancel event'  d'un event envoyé par le front
- Commit(s) : …
> PC-18797 add user events for id check

- pro/package.json
- pro/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19762
_montée de version de testcafe, ok en local
> (PC-19762)[PRO] bump: testcafe to 2.2.0

- pro/src/screens/OfferType/OfferType.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19983
Les boutons `Créer une nouvelle offre ou dupliquer une offre ?` s'affichent avant la banner demande de référencement
- Ajouter une condition pour l'affichage de ces boutons pour ne pas les afficher si l'appel api checkant l'eligibility n'est pas terminé
> (PC-19983)[PRO] fix: buttons display before eligibility banner

- api/src/pcapi/core/fraud/repository.py
- api/src/pcapi/core/subscription/api.py
- api/tests/core/fraud/test_repository.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/young_status_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20196
Ne pas bloquer les utilisateurs bénéficiaires quand ils réservent une offre
Early return si on est bénéficiaire, avant de checker les revues mannuelles
#beneficiaryTrumpsKOreviews …
> PC-20196 fix users blocked while beneficiary

- api/src/pcapi/core/users/models.py
- api/tests/core/users/test_models.py
Toujours avoir une valeur a full_name si jamais nom et prénom sont vides
> (BSR)[API] feat: make sure fullname always has a value

- api/src/pcapi/core/offers/api.py
- api/tests/local_providers/cinema_providers/boost/fixtures.py
- api/tests/routes/native/v1/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20157
Ajouter `None` comme valeur par défaut à `next()` pour ne pas avoir l'exception `StopIteration`
> (PC-20157)[API] fix: Boost add default None to next() in udpate stock quantity to match cinema remaining places add

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/workers/update_all_offers_active_status_job.py
- api/tests/core/offers/test_repository.py
- api/tests/routes/pro/patch_all_offers_active_status_test.py
to fix an edge case that happened: a PRO user clicked 'activate all my offers'. but without knowing that this would also include passed offers that used to be synchronized with a venue_provider. this venue_provider has been deactivated (or deleted) since and we don't want the imported offers to be activated
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19869
> (PC-19869)[API] feat: prevent from activating old venue_provider offers

- api/.env.production
- api/.env.staging
- api/.env.testing
- api/src/pcapi/core/external/zendesk.py
- api/src/pcapi/core/external/zendesk_sell.py
- api/tests/routes/external/zendesk_test.py
Fix des liens vers le backoffice dans zendesk, qui utilise les liens de la v2 et pas de la v3. 
> (BSR)[API] fix: use bov3 links in zendesk instead of bov2

- pro/package.json
- pro/src/custom_types/window.d.ts
- pro/src/utils/image.ts
- pro/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19736
- Mise à jour de Typescript
- Correction d'une erreur liée à `window`
- Mise à jour de `@typescript-eslint` case incompatible avec la nouvelle version de typescript.
> (PC-19736)[PRO] chore: Update Typescript version.

- api/src/pcapi/core/users/models.py
- api/tests/core/users/test_models.py
Gérer le cas où quand le nom et prénom d'un user sont nuls, une info apparaît quand même dans l'historique.
> (BSR)[API] feat: handle empty names in bov3 history

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/forms/search.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/credit.html
- api/src/pcapi/routes/backoffice_v3/templates/components/badges.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card_offerer.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card_venue.html
- api/tests/routes/backoffice/pro_search_test.py
- api/tests/routes/backoffice_v3/accounts_test.py
- api/tests/routes/backoffice_v3/admin_test.py
- api/tests/routes/backoffice_v3/helpers/html_parser.py
- api/tests/routes/backoffice_v3/offerers_test.py
- api/tests/routes/backoffice_v3/pro_test.py
- api/tests/routes/backoffice_v3/pro_users_test.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20144
Les API du backoffice v2 étaient mieux testées que les routes du backoffice v3.
Le but de cette PR est de reporter les scénarios de test v2 qui n'étaient pas testés en v3.
Les écrans suivants sont concernés : 
- public accounts
- pro search
- pro users
- offerers
- venues
- roles
Cette PR corrige aussi des bugs découverts en exécutant ces scénarios de test :
- "%" was allowed in search query, which could cause to load the whole db
- search venues were not ordered by similarity; reported same fix as offerers
- remaining credit displayed was rounded
- venue did not have "Suspended" badge when its offerer was suspended
- minor display fixes
- PR : `(PC-XXX) …
> (PC-20144)[BO] test: reintegrate auto tests created from backoffice v2 in v3

- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/src/pcapi/utils/urls.py
- api/tests/routes/backoffice_v3/helpers/button.py
- api/tests/routes/backoffice_v3/offerers_test.py
- api/tests/routes/backoffice_v3/pro_users_test.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20200
Ajout du lien pour valider l'email d'un compte pro dans sa page.
> (PC-20200)[API] feat: add link to email validation

- api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html
- api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html
- api/tests/routes/backoffice_v3/collective_bookings_test.py
- api/tests/routes/backoffice_v3/individual_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20130
Ajout de la date de réservation aux pages de réservations.
> (PC-20130)[API] feat: add booking creation date to bookings pages

- api/src/pcapi/core/offerers/api.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18464
Bug : si on ne modifie que des informations de contact via la page de détails d'un lieu, ceux-ci ne sont pas enregistrés dans l'historique.
L'historique de modification est sauvegardé à la fin de la fonction alors que celle-ci peut se terminer bien plus tôt s'il n'y a aucun changement à apporter au lieu. 
Fix : s'il n'y a aucun changement à apporter au lieu, sauvegarder l'historique de changement des informations de contact (s'il y en a).
> (PC-18464)[API] fix: bov3: save contact data on early return

- api/src/pcapi/routes/native/v1/bookings.py
- api/tests/routes/native/v1/bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20245
retour sur le mecanisme d'archivage des réservations numériquees de plus de 30 jours ajoutée dans le ticket https://passculture.atlassian.net/browse/PC-18717
RAS
RAS
RAS
> (PC-20245)[API] fix: remove ending of old digital offers

- adage-front/src/apiClient/models/CollectiveOfferResponseModel.ts
- adage-front/src/apiClient/models/CollectiveOfferTemplateResponseModel.ts
- adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/ContactButton.tsx
- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230131T093222_feba98cdb198_make_contact_phone_optional_collective_offer.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/routes/adage_iframe/serialization/offers.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts
- pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts
- pro/src/apiClient/v1/models/PostCollectiveOfferBodyModel.ts
- pro/src/apiClient/v1/models/PostCollectiveOfferTemplateBodyModel.ts
- pro/src/components/CollectiveOfferSummary/components/CollectiveOfferContactSection/CollectiveOfferContactSection.tsx
- pro/src/pages/CollectiveOfferEdition/utils/createPatchOfferPayload.ts
- pro/src/screens/OfferEducational/OfferEducationalForm/FormContact/FormContact.tsx
- pro/src/screens/OfferEducational/__specs__/OfferEducationalEdition.spec.tsx
- pro/src/screens/OfferEducational/validationSchema.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20063
Lors de la création/édition d'offre collectives : 
- Le champ téléphone n'est plus obligatoire
> Pc 20063 eac make phone field optional in collective offer creation

- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details.html
- api/src/pcapi/routes/backoffice_v3/templates/components/presentation/details/tabs.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get/details.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get/details.html
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20148
Charger le html pour les bloc de détails des comptes jeunes et grand public, des structures, des lieux et des acteurs culturels de la même manière. Plus de html copié et collé, plus de styles (classes bootstrap principalement) différents.
> (PC-20148)[API] feat: bov3: refactor details tabs

- api/src/pcapi/scripts/install_data.py
Fix : appeler `sync_db_permissions` dans `install_data` comme c'était le cas avant. Cette étape avait été supprimée par erreur.
> (BSR)[API] fix: sync permission inside install_data

- api/requirements.txt
See changelog: https://github.com/pyca/bcrypt/#changelog
Fixes include:
- NUL bytes are now allowed in inputs. This is nice for us because we
occasionally got some of those and bcrypt would raise an error that
was not caught.
> (BSR)[API] chore: Bump bcrypt

- .github/workflows/tests-main.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19591
Le build du de pcapi-console n'est actuellement pas effectué sur github-action, uniquement sur circle-ci (default = true)
> (PC-19591) Build pcapi-console on github

- pro/src/components/VenueForm/VenueForm.tsx
- La valeur du hook changeait, mais ce n'était pas la bonne qui était utilisée dans le useCallback.
> (BSR)[PRO] fix: Callback was using wrong hook value.

- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details/bookings.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20156
- Sur l’onglet “Suivi des réservations” sur le profil jeune, ajout d’un code couleur sur la colonne statut : 
- Surligner la ligne en vert si le statut = validée ou remboursée
- Surligner la ligne en rouge si statut = annulée
- Ne pas surligner la ligne si statut autre
- La flèche pointe vers la droite lorsque la sous ligne masquée, elle pointe vers le bas lorsqu’elle est ouverte 
- Mettre la flèche en rouge pour indiquer à l’utilisateur qu’elle est cliquable 
- Sur la sous ligne d’une réservation, ajout des informations suivantes : 
- Date de l’événement (s’il s’agit d’un événement daté, sinon on ne l’affiche pas)
- Le crédit utilisé par le jeune (Pass 15-17 ou Pass 18)
- Changement du bouton de développement de …
> (PC-20156)[API] feat: Suivi des réservations - Code couleur et ajout d'informations

- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
- api/src/pcapi/routes/public/individual_offers/v1/serialization.py
- api/tests/routes/public/individual_offers/v1/endpoints_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20160
Les dates qui n'ont pas de `PriceCategory` associés renvoient un `PartialPriceCategoryResponse` qui est similaire au `PriceCategoryResponse` avec l'`id` et le `label` à `None`
> (PC-20160)[API] feat: add price category to api return objects

- api/requirements.txt
Changelog: https://click-option-group.readthedocs.io/en/latest/changelog.html
Nothing notable.
> (BSR)[API] chore: Bump version of `click-option-group`

- api/pyproject.toml
- api/requirements.txt
Changelog: https://github.com/rq/rq/blob/master/CHANGES.md
Nothing notable, except `rq` stopped using deprecated `StrictVersion`
from distutils.
> (BSR)[API] chore: Bump version of `rq`

- api/requirements.txt
Changelog: https://requests.readthedocs.io/en/latest/community/updates/#release-history
Nothing notable.
> (BSR)[API] chore: Bump version of `requests`

- pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx
- pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/__specs__/FormParticipants.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19878
Changer le wording de l'info box concernant les participants d'une offre collective quand le FF `WIP_ADD_CLG_6_5_COLLECTIVE_OFFER` est actif
> (PC-19878)[PRO] feat: change info message if ff CLG 6 active

- api/src/pcapi/alembic/versions/20230130T150624_1eab834f493d_addpricecategory.py
- api/src/pcapi/alembic/versions/20230202T171059_930a602ac1af_add_stock_pricecategoryid_foreign_key.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19603
Both tables are locked during foreign key creation, to create it without downtime see [this article](https://travisofthenorth.com/blog/2017/2/2/postgres-adding-foreign-keys-with-zero-downtime). 
Note : **both** tables are locked during the creation of the fkey
Other foreign key created are : 
price_category -> venue (not many lines)
price_category -> price_category_label (no lines)
> (PC-19603)[API] fix: move foreignKey creation to post migration

- .circleci/config.yml
- api/src/pcapi/core/history/api.py
- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice_v3/__init__.py
- api/src/pcapi/routes/backoffice_v3/accounts.py
- api/src/pcapi/routes/backoffice_v3/blueprint.py
- api/src/pcapi/routes/backoffice_v3/forms/user.py
- api/src/pcapi/routes/backoffice_v3/pro_users.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_with_placeholder_value_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/generic_modal.html
- api/src/pcapi/routes/backoffice_v3/templates/components/history/actions.html
- api/src/pcapi/routes/backoffice_v3/templates/components/history/comment.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/src/pcapi/routes/backoffice_v3/users.py
- api/src/pcapi/routes/backoffice_v3/utils.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
- api/tests/core/users/test_api.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/blueprint_test.py
- api/tests/routes/backoffice/permissions_test.py
- api/tests/routes/backoffice_v3/accounts_test.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/pro_users_test.py
- api/tests/routes/backoffice_v3/users_test.py
- backoffice/src/resources/PublicUsers/types.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18475
Ajouter les boutons de suspension et réactivation de compte utilisateur dans le backoffice v3.
Fonctionnalité similaire à Flask-Admin et réservée à l'équipe Fraude & Conformité (comme la revue manuelle).
Plus de détails sur les spécifications dans le ticket.
À noter : j'ai renommé une permission, qui se retrouvera donc nouvelle, et sera à réaffecter dans les rôles sur les différents environnements.
> (PC-18475)[BO] feat: suspend and unsuspend user (beneficiary, gp, pro)

- api/src/pcapi/routes/backoffice_v3/templates/components/presentation/details/tabs.html
Tous les titres d'onglets doivent être en gras.
> (PC-20305)[API] fix: bov3: bold tab titles

- pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx
- pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/__specs__/FormParticipants.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19876
Ne pas afficher les options 6e et 5e dans la création d'offres collectives si le FF `WIP_ADD_CLG_6_5_COLLECTIVE_OFFER` n'est pas actif
> (PC-19876)[PRO] feat: hide clg 5 and 6 if ff is not active

- pro/src/screens/Bookings/Bookings.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20359
Fix le comportement du bouton `Voir toutes les réservations` qui ne réinitialisait pas les filtres correctement.
> (PC-20359)[PRO] fix: fix reset pre filters for collective bookings

- api/tests/core/mails/transactional/users/ubble_ko_reminder_test.py
Correction d'un test unitaire instable.
C'est un test ajouté récemment : https://github.com/pass-culture/pass-culture-main/commit/11f73f75c8cc1035751cbbe50da7c00f204d0cff
Sur master : 
https://app.circleci.com/pipelines/github/pass-culture/pass-culture-main/38697/workflows/ffe75614-49f2-4124-865f-7b3265ce369d/jobs/318319
> (BSR)[API] test: fix flaky unit test should_notify_users_after_sending_an_email

- api/Dockerfile
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19597
* Avoid install of "recommends" package which are not used
* Purge of apt directory
* Pimp pip install to increase velocity
* Changed trusted keys implementation to be iso bullseye recommendation
* Remove one unnecessary layer and use curl instead of wget
- Branche : `PC-19597-increase-docker-build-speed`
- PR : `(PC-19597) feat: Decrease image size and increase build speed`
- Commit(s) : `(PC-19597) feat: Decrease image size and increase build speed`
> (PC-19597) feat: Decrease image size and increase build speed

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230208T093931_62bea1f33bcf_rename_permission_review_public_account.py
- api/src/pcapi/alembic/versions/20230209T152624_b8b34e5a2e5b_remove_permission_review_suspend_user.py
- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice_v3/forms/user.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/src/pcapi/routes/backoffice_v3/users.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/blueprint_test.py
- api/tests/routes/backoffice/permissions_test.py
- api/tests/routes/backoffice_v3/accounts_test.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/pro_users_test.py
- api/tests/routes/backoffice_v3/users_test.py
- backoffice/src/resources/PublicUsers/types.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20398
Finalement, on veut deux permissions distinctes pour la revue manuelle et pour suspendre ou réactiver des utilisateurs.
Cette PR rétablit donc l'ancienne permission et crée la nouvelle distincte ; la fusion n'était pas encore en prod.
> (PC-20398)[BO] fix: distinct permissions for review and suspend, finally

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/native/v1/offers.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20374
Ne plus proposer à la réservation un stock dont la séance correspondante côté cinéma n'est plus renvoyée par l'API.
- Modification de `update_stock_quantity_to_match_cinema_venue_provider_remaining_places()`
- Au passage, on met à jour la quantité du stock à 1 si on sait qu'il ne reste qu'une place, afin d'éviter un échec de réservation duo 
- Si un stock est épuisé, on en profite pour ré-indexer l'offre
> (PC-20374)[API]feat: handle missing showtimes

- api/src/pcapi/core/mails/backends/sendinblue.py
- api/src/pcapi/routes/saml/educonnect.py
- api/src/pcapi/routes/serialization/educonnect.py
- api/src/pcapi/settings.py
- api/tests/core/mails/tests.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19289
Adaptation de la route login d'educonnect pour les tests e2e
> (PC-19289)[API] feat: add route for e2e tests requireing educonnect login

- api/src/pcapi/core/offerers/api.py
- api/tests/core/offerers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20464
Corriger l'exception remontée par Sentry :
AttributeError: 'Venue' object has no attribute 'email'
qui se produit lors de l'édition d'un lieu qui n'a pas encore d'info de contact.
> (PC-20464)[API] fix: AttributeError: 'Venue' object has no attribute 'email' when venue is edited from PC Pro

- api/src/pcapi/routes/backoffice_v3/__init__.py
- api/src/pcapi/routes/backoffice_v3/autocomplete.py
- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/forms/collective_booking.py
- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/forms/individual_booking.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
- api/src/pcapi/routes/backoffice_v3/templates/components/filters_form.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_multiple_field_autocomplete.html
- api/tests/routes/backoffice_v3/autocomplete_test.py
- api/tests/routes/backoffice_v3/collective_bookings_test.py
- api/tests/routes/backoffice_v3/individual_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19889
Filtrage des réservations individuelles et collectives par structure(s) et par lieu(x) dans le nouveau backoffice.
Il serait souhaitable de factoriser le code entre les deux pages de réservations. On garde l'idée pour plus tard :)
> (PC-19889)[BO] feat: Filter bookings on offerers and venues

- pro/src/screens/Bookings/BookingsRecapTable/components/Filters/FilterByOmniSearch/FilterByOmniSearch.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20388
- Retirer le warning: "Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>"
- Gestion par "value" dans le select plutôt que par selected sur les options.
> (PC-20388)[PRO] fix: warning setting selected on options

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230214T100715_e7443f71e558_drop_individual_booking.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20500
- Supression de la table individual_booking qui n'est plus accessible/utilisée depuis la version 226
> (PC-20500)[API] chore: remove unused table individual_booking

- api/src/pcapi/routes/backoffice_v3/autocomplete.py
- api/tests/routes/backoffice_v3/autocomplete_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19889
Dans l'autocomplétion des structures et lieux du backoffice v3, permettre de chercher indifféremment avec ou sans accents. « cinema » doit trouver des structures contenant « Cinéma ».
> (PC-19889)[BO] fix: autocomplete was accent-sensitive

- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20399
Ne pas afficher la modal quand on valide des offerer validation
Ajout d'une option pour valider sans confirmation
> (PC-20399)[BO] feat: bypass user offerer validation on validate

- api/src/pcapi/routes/backoffice_v3/offerers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20399
Lors d’une validation/rejet/mise en attente en masse, il n’y a aucun message de type snack bar en haut de page pour confirmer à l’utilisateur que l’action a bien été réalisée (alors que c’est le cas pour une action sur une demande invididuelle) 
- Ajout d'un message flash spécifique au type de traitement en batch effectué (validation, rejet, mise en attente)
> (PC-20399)[API] fix: Ajout du flash message lors de la réussite du traitement des rattachements

- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
- api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html
- api/src/pcapi/routes/backoffice_v3/templates/components/bookings/reimbursed.html
- api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html
- api/tests/routes/backoffice_v3/collective_bookings_test.py
- api/tests/routes/backoffice_v3/individual_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20025
Ajouter une ligne qui se déplie dans les tableaux des réservations individuelles et collectives. Celles-ci ne concernent que les réservations remboursées et contiennent des informations liées au remboursement (montant, rappel du lieu et de l'AC, informations concernant le virement...).
> (PC-20025)[API] feat: bov3: bookings: show pricing/cashflow information

- api/src/pcapi/routes/backoffice_v3/accounts.py
- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details.html
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details/personal_information_registration.html
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/src/pcapi/utils/urls.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20210
En tant que support jeune
J'aimerais accéder au profil doublon depuis le profil d’un jeune
Afin de gagner du temps
- L’onglet par défaut lorsqu’on arrive sur le profil jeune doit être “Informations personnelles” (et non plus “Historique du compte)
- Sur le profil jeune, lorsqu’un doublon est identifié par Ubble (ID doublon visible dans le bloc “ubble”) : 
- Remonter l’information du second ID dans le bloc d’informations générales en haut de page => User ID doublon : xxxxx
- L’afficher uniquement en cas de doublon
- Rendre cliquable cet ID doublon pour rediriger l’utilisateur vers le profil du doublon
- Commit(s) : …
> (PC-20210)[API] feat: Profil jeune - Lien vers le second profil en cas de doublon

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20496
- Limiter la mise à jour des stocks synchronisés à 0 ou 1 seulement pour les séances qui sont encore réservables.
- Ajouter un retry lorsqu'une erreur est levée suite à la vérification sur la colonne dé-normalisée `Stock.dnBookedQuantity`
> (PC-20496) cine update stocks

- api/src/pcapi/core/users/backoffice/api.py
- api/tests/core/users/backoffice/test_api.py
- api/tests/routes/backoffice_v3/helpers/unauthorized.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20523
Mettre à jour correctement les rôles depuis ceux reçus de Google lors de l'authentification.
En effet un utilisateur retiré d'un groupe ne perdait pas le rôle dans la base de données, et donc conservait les permissions à vie.
> (PC-20523)[BO] fix: properly update roles at authentication

- api/src/pcapi/routes/backoffice_v3/filters.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20467
Corriger les couleurs des badges d'état de réservation pour coller à la demande résumée dans le ticket.
Détail : j'ai mis des guillemets dans les tags html, ensuite c'est black qui force tantôt des apostrophes, tantôt des guillemets selon les apostrophes dans la chaîne.
> (PC-20467)[BO] fix: status badge color on user bookings

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/bookings/commands.py
- api/src/pcapi/core/bookings/constants.py
- api/src/pcapi/routes/native/v1/bookings.py
- api/src/pcapi/scripts/install.py
- api/tests/core/bookings/test_api.py
- api/tests/core/bookings/test_commands.py
- api/tests/core/finance/test_commands.py
- api/tests/test_utils.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20441
archiver les réservations avec code d'activation qui ont plus de 30 jours dans (càd. les renvoyer dans la liste des réservations terminées)
ajout d'une commande `archive_old_activation_code_bookings` pour passer l'attribut `Booking.displayAsEnded` à `True` pour les réservations avec code d'activation qui ont plus de 30 jours
[cette commande sera exécutée par un CRON](https://github.com/pass-culture/pass-culture-deployment/pull/199)
RAS
RAS
> Pc 20441 archive old digital bookings

- .circleci/config.yml
We won't need this secret once back-office v2 is deleted.
> (BSR)[API] docs: Add note about removing SENTRY_AUTH_TOKEN CircleCI secret

- pro/src/screens/OfferIndividual/PriceCategories/PriceCategories.tsx
- pro/src/screens/OfferIndividual/PriceCategories/PriceCategoriesForm.tsx
- pro/src/screens/OfferIndividual/PriceCategories/__specs__/PriceCategoriesForm.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20243
_Régler deux bugs (on avait besoin de refresh offer après avoir supprimer un price category)
1- le route leaving guard s'affichait après une suprression (qaund il reste deux éléments, le passage de 2 à 1 sera réglé ailleurs)
2- les tarifs supprimés apparaissaient encore
> (PC-20243)[PRO] fix: refresh bug on price category deletion

- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/forms/collective_booking.py
- api/src/pcapi/routes/backoffice_v3/forms/individual_booking.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
- api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html
- api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html
- api/tests/routes/backoffice_v3/collective_bookings_test.py
- api/tests/routes/backoffice_v3/individual_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20533
Améliorer les performances de la recherche des réservations individuelles ou collectives dans le backoffice.
- utilisation d'une `union` de deux sous-requêtes ayant chacune une seule clause `where`, plutôt qu'une seule requête avec un `or` de plusieurs conditions sur des tables différentes : gain sur staging : de 19 minutes à 0,15 seconde ;
- abandon de la pagination, remplacée par un nombre max de résultats, ce qui évite de trouver tous les résultats, les trier et les compter : gain sur staging : de 4-5 minutes à 0,1 seconde pour un filtre sur la catégorie "CINEMA" ;
- message affiché en cas de nombre de résultats au-delà du maximum pour inviter à affiner la recherche ;
- ajout d'un filtre par adresse email du …
> (PC-20533)[BO] fix: filter bookings performance

- adage-front/src/app/__spec__/App.spec.tsx
- adage-front/src/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
- adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/utils/getOfferVenueAndOffererName.ts
- adage-front/src/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
- adage-front/src/app/components/OffersInstantSearch/OffersSearch/filtersReducer.ts
- adage-front/src/app/components/OffersInstantSearch/utils.ts
- adage-front/src/app/constants.tsx
- adage-front/src/app/types/filters.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20277
Ajouter une checkbox dans l'iframe adage permettant aux utilisateurs de filtrer sur les offres d'acteurs culturels dans leur département.
> (PC-20277)[ADAGE] feat: add check to filter offer in my department

- pro/src/screens/OfferIndividual/PriceCategories/PriceCategoriesForm.tsx
- pro/src/screens/OfferIndividual/PriceCategories/__specs__/PriceCategoriesForm.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20581
_Lors de la suppression de l'avant dernière price category il faut refaire un appel au back pour la renommer en "tarif unique"
> (PC-20581)[PRO] fix: rename laste price categories on delete

- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
- api/tests/routes/pro/post_price_categories_test.py
- api/tests/routes/public/individual_offers/v1/endpoints_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20543
La sélection des stocks non expirés se fait directement dans la requête sqlalchemy.
`.first_or_404()` a été remplacé par un `.one_or_none()` parce que le `first` rajoute un `LIMIT 1` dans la requête SQL ce qui empêche les enfants (`stocks` et `priceCategories`) d'être peuplés par plus qu'un seul élément
> (PC-20543)[API] fix: expired event stock price edition when editing price category

- api/src/pcapi/analytics/amplitude/backends/amplitude_connector.py
- api/src/pcapi/core/logging.py
- api/tests/core/logging/tests.py
Amplitude SDK logs its events through the `extra` log argument [1].
Another workaround could be to just ignore INFO level for the logger
that is used by Amplitude SDK, but the SDK uses the INFO level for
errors, too [2]. It seems useful to keep those.
[1] https://github.com/amplitude/Amplitude-Python/blob/ec790705394ed180079e198099149574a402c614/src/amplitude/processor.py#L83
[2] e.g. https://github.com/amplitude/Amplitude-Python/blob/ec790705394ed180079e198099149574a402c614/src/amplitude/processor.py#L32
---
Exemple dans Sentry : https://sentry.passculture.team/organizations/sentry/issues/406635
> (BSR)[API] fix: Handle Amplitude events in logs

- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/routes/backoffice_v3/offers.py
- api/tests/routes/backoffice_v3/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20527
éviter le _timeout_ lors de la recherche d'offres dans le backoffice
Recherche « le seigneur des anneaux » sur staging (plus lent que la production) : 
- avant : 16 à 19 minutes
- après : 4"3
> (PC-20527)[BO] fix: timeout when searching for offers

- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/routes/pro/collective_offers.py
- api/tests/routes/pro/patch_all_collective_offers_active_status_test.py
- api/tests/routes/pro/patch_collective_offer_test.py
- api/tests/routes/pro/patch_collective_offers_active_status_test.py
- api/tests/routes/pro/patch_collective_offers_template_active_status_test.py
Prevent deregistered users from re-activating their deactivated offers
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20019
empecher les utilisateurs non enregistré de réactiver leur offre désactivé
> (PC-20019)[API] feat: Prevent deregistered users from re-activating their deactivated offers

- api/src/pcapi/local_providers/local_provider.py
- api/src/pcapi/repository/providable_queries.py
- api/tests/local_providers/allocine_stocks_test.py
- api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
- api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20466
Adapter `LocalProvider` pour ne mettre à jour les affiches qu'une seule fois par jour.
Comparaison en local et sandbox Boost:
- Avec mise à jour des affiches:
- Sans mise à jour des affiches:
> (PC-20466)[API] feat: Local provider handle thumb update only once per day

- api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
Sources: 
- https://github.com/twbs/bootstrap/blob/main/js/src/util/index.js#L180
- https://github.com/twbs/bootstrap/blob/main/js/src/dom/event-handler.js#L264
- https://getbootstrap.com/docs/5.0/getting-started/javascript/#events
Cette class sur le `body` interdit l'usage de jQuery par bootstrap si présente dans le DOM
Ceci évitera les erreurs lié à un ajout accidentel de jQuery par un dev
NA 
> (BSR)[API] fix: force disable jQuery by bootstrap

- api/src/pcapi/core/finance/commands.py
- api/src/pcapi/core/finance/siret_api.py
- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/routes/backoffice_v3/__init__.py
- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/forms/pro_support.py
- api/src/pcapi/routes/backoffice_v3/pro_support.py
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/string_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/history/actions.html
- api/src/pcapi/routes/backoffice_v3/templates/components/history/view.html
- api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details/history.html
- api/src/pcapi/routes/backoffice_v3/templates/pro/move_siret.html
- api/src/pcapi/routes/backoffice_v3/templates/pro/move_siret_confirmation.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get/details/history.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get/details/history.html
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/pro_support_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20537
Ajouter une page dans le backoffice afin de faire les déplacements de SIRET (lieu public vers lieu administratif), nombreux dans les demandes shérif. Le but est de pouvoir être fait directement côté support.
Un nouveau rôle a été ajouté car la permission ne doit être donnée qu'à un nombre très restreint de personnes.
> (PC-20537)[BO] feat: Move SIRET from backoffice (Legal SIRET)

- api/src/pcapi/scheduled_tasks/commands.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20201
Ajouter la procédure DMS 'jeune de nationalité étrangère' à la liste des procédures pour lesquelles on gère l'inactivité.
En effet cette procédure a maintenant les mêmes délais que les autres
- …
> (PC-20201)[API] feat: add procedure 47380 to handle inactive applications

- api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
- api/src/pcapi/static/backoffice/js/pc-event-handler.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20663
Ajout d'une version VanillaJS de `$.on` , `$.off`, `$.one` et `$.trigger` de jQuery:
- on: https://api.jquery.com/on/#on-events-selector-data
- off: https://api.jquery.com/off/#off-events-selector-handler
- one: https://api.jquery.com/one/#one-events-data-handler
- trigger: https://api.jquery.com/trigger/#trigger-event-extraParameters
Implémentation inspiré de la source bootstrap 5: https://github.com/twbs/bootstrap/blob/cf9454caa00872899215603e5e036d9a824b1b11/js/src/dom/event-handler.js
Cet outil permettra de :  
- Stocker tout les évents binder au même endroit
- Tuner des composants HTML avec JS sans écriture de code JS répétitive en cas d'usage additionel
NA
- …
> (PC-20663)[API] feat: add EventHandler vanilla js support on/off

- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
- api/tests/routes/backoffice_v3/individual_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20621
Les actions sur les réservations dans le backoffice finissent avec la page d'erreur 500 si l'opération échoue à cause d'une contrainte SQL. Solution : capturer l'exception pour afficher un message d'erreur comme sur FA permet.
> (PC-20621)[BO] fix: avoid http error 500 when bookings action fails because of SQL constraint

- api/src/pcapi/routes/serialization/base.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20686
Corriger une exception (erreur 500) qui se produit lors de la modification d'un lieu, si le numéro de téléphone n'est pas rempli.
https://sentry.passculture.team/organizations/sentry/issues/408130/?project=5
> (PC-20686)[BO] fix: exception when a venue is updated with empty phone number

- .circleci/config.yml
But : enlever les jobs de CircleCI qui sont déjà pris en charge par GHA.
> (BSR)[PRO] ci: remove steps for portail pro already migrated to GitHub Actions

- .github/workflows/update-jira-issues.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20679
Si le ticket est de type `OPS Task`, alors on ne fait rien. En effet ce type d ticket ne comporte plus les champs qui sont update par cette action, notamment le champ impropre. 
> PC-20679-ne-pas-faire-rentrer-dans-le-process-jira-update-les-tickets-ops-task

- api/src/pcapi/routes/backoffice_v3/templates/pro/move_siret.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20537
Corriger le formulaire de déplacement de SIRET.
Dû à un _merge_ entre le codage et le _merge_ de ce ticket.
> (PC-20537)[BO] fix: move siret form

- pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.tsx
- pro/src/components/CollectiveOfferLayout/__specs__/CollectiveOfferLayout.spec.tsx
- pro/src/core/OfferEducational/adapters/getCollectiveOfferAdapter.ts
- pro/src/core/OfferEducational/adapters/getCollectiveOfferTemplateAdapter.ts
- pro/src/hooks/__specs__/useCollectiveOfferRoute.spec.tsx
- pro/src/hooks/useCollectiveOfferRoute.ts
- pro/src/pages/CollectiveOfferCreation/CollectiveOfferCreation.tsx
- pro/src/pages/CollectiveOfferCreation/__specs__/CollectiveOfferCreation.spec.tsx
- pro/src/pages/CollectiveOfferRoutes/CollectiveOfferCreationRoutes/CollectiveOfferCreationRoutes.tsx
- pro/src/pages/CollectiveOfferRoutes/CollectiveOfferEditionRoutes/CollectiveOfferEditionRoutes.tsx
- pro/src/pages/CollectiveOfferRoutes/CollectiveOfferRoutes.tsx
- pro/src/pages/CollectiveOfferStockCreation/CollectiveOfferStockCreation.tsx
- pro/src/pages/CollectiveOfferStockCreation/__specs__/CollectiveOfferStockCreation.spec.tsx
- pro/src/pages/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx
- pro/src/pages/CollectiveOfferSummaryCreation/__specs__/CollectiveOfferSummaryCreation.spec.tsx
- pro/src/pages/CollectiveOfferVisibility/CollectiveOfferCreationVisibility.tsx
- pro/src/pages/CollectiveOfferVisibility/__specs__/CollectiveOfferCreationVisibility.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20391
Supprimer les paramètres passés aux routes pour les déplacer plus bas dans l'architecture
Ajout d'un hook qui récupère les paramètres d'une offre collective
> (PC-20391)[PRO] refactor: move collective offer params away from the router

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
- api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
- api/src/pcapi/repository/providable_queries.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_occurrences.py
- api/src/pcapi/scripts/stock/populate_event_stock_price_categories.py
- api/tests/local_providers/allocine_stocks_test.py
- api/tests/local_providers/chunk_manager_test.py
- api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
- api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20419
In the 2nd commit i replaced bulk_save_object by add_all.
bulk_save_object is slightly faster but does not check objects contraints and save relationships while writing them.
For titelive sync the biggest chunk (1000 objects to write - 0 to update) took an average time of 0.4s to be saved while with bulk_save_object it is around 0.3s
> (PC-20419)[API] feat: Add pricecategories for allocine stocks

- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/tests/routes/pro/get_all_collective_offers_test.py
- api/tests/routes/pro/get_collective_offer_test.py
- pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts
- pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts
- pro/src/utils/collectiveApiFactories.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20558
savoir si les offres ont été ajouter via l'api publique ou non 
la page de test dans test_api a été copié de master apres une erreur de ma part ( j'ai embarqué les info d'une autre branche et j'ai remis en modifiant.
> Pc 20558 remonter valeur ispublicapi dans routes offer

- pro/src/core/OfferEducational/utils/__specs__/extractInitialStockValues.spec.ts
- pro/src/core/OfferEducational/utils/extractInitialStockValues.ts
- pro/src/pages/CollectiveOfferStockCreation/CollectiveOfferStockCreation.tsx
- pro/src/pages/CollectiveOfferStockCreation/__specs__/CollectiveOfferStockCreation.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20585
Lorsqu'on créée une offre vitrine on a la possibilité de mettre une description pour le prix sauf qu'on ne l'a récupérait pas si on dupliquait l'offre vitrine en question. 
> (PC-20585)[PRO] feat: get price detail from offer template duplication

- api/pyproject.toml
- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/users/api.py
- api/tests/core/bookings/test_api.py
- api/tests/core/bookings/test_repository.py
- api/tests/core/users/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19409
Lors de la suspension de compte :
Ne plus annuler les réservations des événements qui ont été confirmées
- quelques petits refactoring, tout est découpé en commits atomics
- en faisant la feature, j'ai découvert que l'on calcul la date à laquelle on peut annuler une réservation, cette date correspond à :
- soit l'event à lieu dans un futur lointain : 48h après avoir fait la réservation elle est confirmée
- soit l'event à lieu dans un futur proche : 48h avant l'event
- sinon : la date de la réservation
> (PC-19409)[API] feat: do not cancel event booking on account suspension

- pro/src/app/AppRouter/routes_map.tsx
- pro/src/core/Offers/hooks/useQuerySearchFilters.ts
- pro/src/pages/CollectiveOffers/CollectiveOffers.tsx
- pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx
- pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx
- pro/src/screens/Offers/Offers.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20393
Rendre compatible la route de la liste des offres collectives avec le router react v6
> (PC-20393)[PRO] chore: move collective offers llist to react-router-v6

- adage-front/src/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20767
Remettre à zéro les filtres quand on accède à l'onglet 'Partagé avec mon établissement' sur adage
> (PC-20767)[PRO] feat: reset filters when changing tab in adage iframe

- api/src/pcapi/routes/serialization/base.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/patch_venue_test.py
- api/tests/routes/pro/post_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20783
Corriger une erreur remontée par le Bug Bounty (YesWeHack) : un hacker malintentionné pourrait créer un compte pro, créer des lieux sans SIRET sur lesquels envoyer des millions de caractères. De manière automatisée, cela aurait un impact négatif sur la taille de notre base de données.
> (PC-20783)[PRO] fix: check venue comment and withdrawal details max length

- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
BSR
Capturer n'importe quelle erreur plutôt que juste celles liées à la base de données (contraintes), lorsqu'une action sur les réservations échoue, pour l'afficher plutôt qu'une erreur 500.
> (BSR)[BO] fix: catch any Exception in bookings actions

- api/bin/alembic_add_not_null_constraint.py
Adding a NOT NULL constraint on a column of a large table (or a table
that is frequently modified) should be done in 4 steps. This new
command takes care of generating these 4 migrations and can be used
like this:
$ python bin/alembic_add_not_null_constraint.py --table pricing --column venueId
> (BSR)[API] feat: Add command to generate migrations for a NOT NULL constraint

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20485
Ajout de la colonne tags structure (homologation) au lieu de la colonne téléphone
> Pc 20485 bov3 add offerer tag to offerer validation list

- pro/src/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx
- pro/src/core/Offers/types.ts
- pro/src/pages/CollectiveOffers/adapters/serializers.ts
- pro/src/pages/CollectiveOffers/utils/collectiveOffersFactories.ts
- pro/src/pages/Offers/Offers/OfferItem/CollectiveOfferItem.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20649
Ne plus afficher le bouton crayon dans la liste des offres ni les bouton "Modifier" dans le récapitulatif pour une offre collective lorsque celle-ci provient de l'api public.
> (PC-20649)[PRO] feat: can't edit when offer from publicApi

- api/tests/alembic/alembic_version_conflict_detection_test.py
Eviter les KO Flaky de la CI sur le test de conflit de migrations
Par exemple dans [ce workflow](https://app.circleci.com/pipelines/github/pass-culture/pass-culture-main/40186/workflows/c276d96d-43ec-4f90-a97f-7919b1df5d22/jobs/332228/tests#failed-test-0) le fichier est correct, mais un changement d'ordre casse le test. Apperment l'ordre n'est pas consistent d'un run à l'autre 
Explicitement chercher pre et post au lieu de partir du principe qu'ils sont ordonnés
- _A destination des Data Analysts, exposer le …
> (BSR)[API] ci: fix flakiness in alembic conflict detection test

- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/tests/local_providers/allocine_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20819
Supprimer l'initialisation du `Product.thumbCount` à 0 pour la synchro Allociné
> (PC-20819)[API] feat: Allocine remove Product.thumbCount initialization

- api/src/pcapi/core/bookings/api.py
- api/tests/routes/external/zendesk_test.py
Since the user is born more than 19 years ago (today!), they're not
eligible anymore. That's not what we're testing, so we can just adapt
the tags.
> (BSR)[API] test: Fix ZendeskWebhookTest.test_webhook_update_user_by_phone

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/routes/native/v1/offers.py
- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/tests/core/bookings/test_api.py
- api/tests/routes/native/v1/offers_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20284
- ajout d'une nouvelle route native `GET /offer/<int:offer_id>/with-price-categories` pour ajouter à la réponse le `priceCategoryLabel` et la `remainingQuantity` de chaque stock
- enregistrement du `priceCategoryLabel` dans chaque nouvelle réservation
RAS
RAS
RAS
> Pc 20284 add price category label to offer stocks

- pro/public/index.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20708
-on essaye avec le bon sha
```
echo -n 'var beamer_config={product_id:"vjbiYuMS52566"}' | openssl sha256 -binary | openssl base64
lsVG3dRRjbLAsQIz53z4zymQ5Vw0cFQnOqNnY5sCuSM=
```
> (PC-20708)[PRO] fix: csp sha for beamer

- pro/src/hooks/useCollectiveOfferRoute.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20857
Lorsqu'on remplit le formulaire de création d'offre vitrine et que l'on arrive sur la page de récapitulatif et que l'on clique sur "Étape précédente" on revient sur le formulaire de création d'offre mais le stepper pour une offre réservable apparaît. Il ne faut afficher le stepper de l'offre vitrine.
Avant : 
Après : 
> (PC-20857)[PRO] fix: fix stepper bug when template offer

- pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20702
Remettre l'espace entre le select et la bannière qui affiche les informations selectionnées.
Avant :
Après :
> (PC-20702)[PRO] fix: space field field layout

- api/src/pcapi/core/categories/subcategories_v2.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20127
le retour des changements qui ont cassé la prod lundi 23/01/23.
cette fois, [le front est capable de gérer des différences entre les catégories back et les catégories front](https://github.com/pass-culture/pass-culture-app-native/pull/4283), donc ça ne devrait plus péter la prod.
⚠️ ⚠️ ⚠️ **ne pas merger cette PR avant que le ticket front ait été MEP et suivi d'une MAJ forcée de l'app**
mettre à jour la catégorisation des offres:
- Supprimer la catégorie plateforme en ligne côté back
- Associer la sous-catégorie pro CAPTATION MUSICALE au searchGroup ‘Arts et Loisir créatif’ et la nativ catégorie associée PRATIQUE et ATELIER ARTISTIQUE
RAS
RAS
RAS
- PR : `(PC-XXX) …
> (PC-20127)[API] feat: update subcategories mapping (again)

- pro/src/screens/SignupJourneyForm/Activity/Activity.tsx
- pro/src/screens/SignupJourneyForm/Activity/ActivityForm.module.scss
- pro/src/screens/SignupJourneyForm/Activity/ActivityForm.tsx
- pro/src/screens/SignupJourneyForm/Activity/__specs__/ActivityForm.spec.tsx
- pro/src/screens/SignupJourneyForm/Activity/validationSchema.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20298
- Inverser le titre “Activité” et “Tous les champs sont obligatoires sauf mention contraire.”
- Espacement entre “Activité” et le champ “Activité principale” : 24px 
- Comportement d’erreur manquant sur le champ “Site internet, réseau social” : Lorsqu’on le format de l’url n’est pas respecté → Indiquer sous le champ comme message d’erreur :  “Veuillez renseigner une URL valide. Ex : https://exemple.com/”
> (PC-20298)[PRO] fix: ui return on activity form

- pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/serializers.spec.ts
- pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/updateIndividualOffer.spec.ts
- pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20903
_Bug fix création d'offre, la serialization doit renvoyer null et pas undefined
> (PC-20903)[PRO] fix: patch offers bookingEmail should be null

- api/src/pcapi/core/users/api.py
- api/tests/routes/backoffice_v3/accounts_test.py
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20924
Empêcher une exception (erreur 500) lorsque l'historique contient une action sans date (cela se produit sur les actions anciennes recréées à partir de l'existant)
Erreur Sentry : 
https://sentry.passculture.team/organizations/sentry/issues/407715/
> (PC-20924)[BO] fix: TypeError in public account history

- api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_multiple_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_multiple_field_autocomplete.html
Retrait de la class css `border-rounded` pour repasser a un style `border-radius: 1rem`.
Le passage a la class `border-rounded` ne fonctionne pas bien si on séléctionne beaucoup d'élément dans le mutli select
Avant
Après
NA
NA
> (BSR)[API] fix: fix multiselect border radius

- .github/workflows/tests-api.yml
- .github/workflows/tests-backoffice-v3.yml
Ne plus montrer ses gros bras avec une couleur de succès quand on échoue
Suppression du if else car toutes ces notifications ne tournent qu'en cas d'échec.
NA
NA
> (BSR)[API] ci: fix slack failures colors

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230307T174719_a24e2d695e7c_delete_unique_cashflow_pricing_association_constraint.py
- api/src/pcapi/core/finance/models.py
The composite primary key already enforces unicity.
> (BSR)[API] fix: Remove useless unique constraint on cashflow_pricing

- api/src/pcapi/routes/backoffice_v3/templates/components/forms/postal_address_autocomplete.html
l'attribut `required` étant collé à l'attribut `data-has-reset`, le `data-has-reset` était toujours null et le `required` toujours `false`
NA
NA
NA
> (BSR)[API] fix: autocomplete reset button

- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/credit.html
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details/bookings.html
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details/personal_information_registration.html
- api/src/pcapi/routes/backoffice_v3/templates/admin/roles.html
- api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html
- api/src/pcapi/routes/backoffice_v3/templates/components/bookings/extra_row.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/date_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/search_field.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_field.html
- api/tests/routes/backoffice_v3/accounts_test.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20876
Actuellement, nous utilisons des id pour des composants réutilisable, ce qui empêche si l'on souhaite rester sémantiquement correct au yeux de la w3c, de réutiliser un composant.
Ceci peut également avoir un impact sur l'API du DOM, afin d'éviter l'accumulation de dette technique, ce nettoyage est nécessaire.
- Éviter le risque d'avoir deux identifiant unique dans la page
- Suppression de tout les ids (sauf pour checkbox/radio/accessibility, mais nous n'avons encore rien de tel)
- TODO: remove `id` from csrf input
NA
NA
> (PC-20876)[API] fix: remove id from all html templates

- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/forms/offer.py
- api/src/pcapi/routes/backoffice_v3/offers.py
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/string_field.html
- api/src/pcapi/routes/backoffice_v3/templates/offer/list.html
- api/tests/routes/backoffice_v3/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20081
En tant que support pro ou chargé de programmation
J'aimerais définir un tag pour une offre spécifique 
Afin de pouvoir ensuite constituer des playlist 
- Ajout d’un bouton action en première colonne du tableau sur la page “Rechercher les offres”
- Au clic, le bouton action affiche l’action “Modifier” (d’autres actions seront ajoutés par la suite) 
- Cette action ne doit être possible qu’avec la permission “Gérer les offres” (pour le moment spécifique au rôle “Programmation”)
- Au clic sur l’action “Modifier”, une modale s’ouvre pour permettre à l’utilisateur de modifier les champs : 
- Tag (il est possible d’en sélectionner plusieurs)
- Liste déroulante avec champ autocomplete
- En titre de la modale on met le …
> (PC-20081)[API] feat: Associate Tag to offer

- api/src/pcapi/routes/native/v1/serialization/bookings.py
- api/tests/routes/native/v1/bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20974
lorsque l'app native récupère la liste des réservations, elle attend que le prix des stock soient en centimes, hors le back renvoie des euros. cette PR corrige ça
RAS
RAS
RAS
- [ x J'ai écrit les tests nécessaires
> (PC-20974)[API] fix: convert stock price to cents in response

- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/templates/components/forms/string_field.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20964
Rendre optionnel le champ `rankingweight` du formulaire d'édition des offres. 
Création d'un champs `PCOptIntegerField`
Mise en place des vérifications adéquates pour afficher le champs en tant que champs nombre. 
> (PC-20964)[API] fix: Rendre le champs pondération optionnel

- .github/update-jira-issues.sh
- .github/workflows/update-jira-issues.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20984
Les deux valeurs de `needs.issue-number.outputs.commit-number ` et `${{ needs.issue-number.outputs.commit-hash }}` ne sont pas bine passées au sous job. 
> (PC-20984)[CI] Fix: values not passed to sub job

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
When we generate and store a file more than once on Google Drive
(which happened in the past when things went wrong), it's nice when
files have a different filename there.
> (PC-20990)[API] feat: Include timestamp in Google Drive-stored finance files

- pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx
- pro/src/components/OfferEducationalActions/__specs__/OfferEducationalActions.spec.tsx
- pro/src/core/FirebaseEvents/constants.ts
- pro/src/pages/Offers/Offers/OfferItem/Cells/BookingLinkCell/BookingLinkCell.tsx
- pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20592
Ajouter un tracker sur les boutons d'accès aux réservations collectives : 
- Depuis la liste des offres (filtrer sur une offre préservée ou réservée)
- Depuis la page récap d'une offre collective
> (PC-20592)[PRO] feat: add trackers on click collective booking link

- api/src/pcapi/routes/backoffice_v3/filters.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/edit.html
- api/src/pcapi/routes/backoffice_v3/templates/accounts/edit_review.html
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
- api/src/pcapi/routes/backoffice_v3/templates/admin/roles.html
- api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html
- api/src/pcapi/routes/backoffice_v3/templates/components/forms.html
- api/src/pcapi/routes/backoffice_v3/templates/components/generic_modal.html
- api/src/pcapi/routes/backoffice_v3/templates/components/history/comment.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/base.html
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result.html
- api/src/pcapi/routes/backoffice_v3/templates/components/turbo/modal_form.html
- api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html
- api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/get/details/users.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/offerer_tag.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
- api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
- api/src/pcapi/routes/backoffice_v3/templates/pro/move_siret.html
- api/src/pcapi/routes/backoffice_v3/templates/pro/move_siret_confirmation.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/comment.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20875
Actuellement, nos formulaires n'ont pas d'attribut `name` systématiquement, ce qui rend compliqué le traversing des forms en JavaScript. 
Cette PR à pour but de rajouter un name a tout les forms.
Nous avons d'obligatoire l'attribut `action`, la stratégie pour le name est:
- Si action -> slugification de l'action en name
- Si pas d'action -> random hash en name
- Ajout d'un filter jinja `action_to_name`, ex:
- Si action `/backofficev3/public-accounts/127/update` alors name `backofficev3_public_accounts_127_update`
- Si action `` alors name `78978921ef91d39b8d531375d78961c1` (random)
NA
NA
- Commit(s) : …
> (PC-20875)[API] fix: use name on all forms

- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/tests/routes/native/v1/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21011
corriger un bug intervenant quand on cherche à renvoyer le `remainingQuantity` d'une offre avec un stock illimité
RAS
RAS
RAS
> (PC-21011)[API] fix: fix validation error when stock remaingQuantity is "unlimited"

- .github/workflows/tests-main.yml
- .github/workflows/tests-pro.yml
... and simplify code for deployment failure. In both cases, we're in
a block that is only triggered on a failure.
Same as e70c38d94acb964671d732d11a7ada863df14578.
> (BSR)[*] ci: Fix color in Slack notification on build failure

- pro/package.json
- pro/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20955
_Montée de version de babel jest
> (PC-20955)[PRO] bump: babel-jest to 29.0.5

- api/src/pcapi/core/users/repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20880
Lors d'une connexion réussie, nous ne savons pas quel utilisateur s'est loggé.
Cette manque d'information est particulièrement dommageable pendant les attaques sur les routes signin : nous ne pouvons pas identifer quels comptes ont été signin avec succès (peut être par l'attaquant).
Ajout d'un log lors d'un signin avec succès.
Utilisation du même format que le signin raté.
Ajout d'un technical_message_id pour exporter ces deux informations.
Le log lors du signin avec succès n'est pas placé dans la même fonction (`check_user_and_credentials`) que celui du signin raté.
En effet cette fonction sert également à l'authentification forte lors des changement d'email ou de mot de passe, actions qui se font soit en …
> (PC-20880)[API] feat:Add a log for successful authentications

- pro/src/components/Breadcrumb/Breadcrumb.tsx
- pro/src/components/Breadcrumb/__specs__/Breadcrumb.spec.tsx
- pro/src/components/DomainNameBanner/DomainNameBanner.jsx
- pro/src/components/Header/Header.jsx
- pro/src/hooks/__specs__/useAnalytics.spec.tsx
- pro/src/hooks/useLogNavigation.ts
- pro/src/screens/CsvTable/CsvTable.tsx
- pro/src/screens/EmailChangeValidation/__specs__/EmailChangeValidation.spec.tsx
- pro/src/ui-kit/Hero/Hero.tsx
- pro/src/ui-kit/Logo/Logo.jsx
- pro/src/ui-kit/Logo/__specs__/Logo.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20781
- Migration de plusieurs composants génériques pour utiliser route v6
- pro/src/components/Header/Header.jsx
- pro/src/components/Breadcrumb/Breadcrumb.tsx
- pro/src/hooks/useLogNavigation.ts
- pro/src/components/DomainNameBanner/DomainNameBanner.jsx
- pro/src/ui-kit/Logo/Logo.jsx
- pro/src/ui-kit/Hero/Hero.tsx
- pro/src/screens/CsvTable/CsvTable.tsx
- Tests
> (PC-20781)[PRO] refactor: migrate generic component

- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/routes/backoffice_v3/forms/user.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
- api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html
- api/src/pcapi/routes/backoffice_v3/users.py
- api/src/pcapi/routes/backoffice_v3/utils.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
- api/tests/routes/backoffice_v3/accounts_test.py
- api/tests/routes/backoffice_v3/conftest.py
- api/tests/routes/backoffice_v3/pro_users_test.py
- api/tests/routes/backoffice_v3/users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20945
Séparation de la permission de suspension et réactivation de compte en deux permissions (une action chacune)
> (PC-20945)[API] feat: split user suspension and unsuspension permission

- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation.py
- api/tests/emails/offer_cancellation_test.py
This function is (usually) called by an asynchronous task. When the
task is performed, the status of the booking has been changed in the
database, so the booking does not appear in the e-mail. But it does in
the rare cases where the function is not called by an asynchronous
task.
> (BSR)[API] fix: Fix `send_booking_cancellation_by_beneficiary_email` and test

- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/tests/local_providers/allocine_stocks_functions_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21101
Corriger les erreurs de synchronisation Allociné lorsque l'attribut projection est vide
dans _`filter_only_digital_and_non_experience_showtimes()`, ignorer les séances pour lesquelles `projection` est vide
> (PC-21101)[API] fix: Allocine sync when projection attribute is empty

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/bookings/factories.py
- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/core/bookings/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18987
La période de 2 jours d'annulation possible prime sur l'impossibilité d'annuler deux jours avant le début de l'évènement en cas de modification de la date de l'évènement.
> (PC-18987)[API] fix: updated booking cancellation limit date

- api/src/pcapi/admin/custom_views/venue_view.py
- api/tests/admin/custom_views/venue_view_test.py
Avant : l'index des lieux permet d'éditer (est permanent et tags) plusieurs lieux en même temps, via une modale. Mais la route appelée ne lançait aucune indexation, donc si on passe un lieu de permanent à non permanent de cette manière, celui-ci reste indexé.
Après : lancer l'indexation des lieux et faire en sorte d'avoir le même comportement que lors de l'édition d'un lieu spécifique.
> (PC-20866)[API] fix: FA: venues: reindex on multi update

- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
Suite à l'ajout de `djlint`, une balise manquante `</div>` a été fermé en pied de page, alors qu'elle aurait du l'etre au milieu provoquant cet affichage:
La PR corrige pour remettre comme c'est actuellement en production:
NA
NA
NA
> (BSR)[API] fix: accounts button

- api/src/pcapi/algolia_settings_venues.json
- api/src/pcapi/core/search/backends/algolia.py
- api/src/pcapi/routes/native/v1/settings.py
- api/tests/core/search/test_serialize_algolia.py
The `is_eligible_for_strict_search` attribute has been renamed as
`has_at_least_one_bookable_offer` in app since pass-culture/pass-culture-app-native@f78fff6b3ff4c44e13a8a9773ea2631a13b82434,
which was first released in app version 194. The minimal version is
way past that, we can stop indexing data under the old name.
---
+ 1 commit bonus de suppression d'un FIXME oublié, cf. détail dans le message de commit. ;)
> (BSR)[API] feat: Remove is_eligible_for_strict_search for old apps

- api/pyproject.toml
- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/analytics/amplitude/backends/logger.py
- api/src/pcapi/connectors/beneficiaries/outscale.py
- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/educational/utils.py
- api/src/pcapi/core/external/zendesk_sell.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/providers/api.py
- api/src/pcapi/core/users/repository.py
- api/src/pcapi/routes/native/v1/cookies_consent.py
- api/stubs/logging/__init__.pyi
... + 1 commit de correction de `logging.info()` -> `logger.info()
---
We monkey patch `logging.Logger._log()` to allow us to provide an
additional argument (`technical_message_id`). mypy does not detect
that and reports an error when we call `info()`, `warning()`, etc.
with this argument.
Defining our own stub for the `logging` module solves the issue.
> (BSR)[API] chore: Provide stub for mypy to notice our monkeypatch of `logging`

- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
- api/tests/routes/backoffice_v3/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20870
Sur le profil d’un jeune, ajouter, sous la date de naissance d’aujourd’hui la “Date de naissance déclarée à l’inscription” si elle est différente de la “vraie” date de naissance, celle retournée par les vérifications d’identité
> (PC-20870)[BO] feat: show declared birth date when different

- api/src/pcapi/analytics/amplitude/backends/amplitude_connector.py
- api/src/pcapi/analytics/amplitude/events/booking_events.py
- api/src/pcapi/core/bookings/api.py
- api/tests/core/bookings/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19821
Répertorier ces events dans Amplitude
Cf. ticket
> PC-19821 track booking events in amplitude

- api/src/pcapi/algolia_settings_offers.json
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21185
mise à jour des settings de l'index des offres chez Algolia:
- déclaration d'un replica virtuel **_PRODUCTION Top offres_** pour l'index des offres (le replica existe dans les environnements de prod et de testing chez Algolia)
- suppression du customRanking sur `offer.last30DaysBookings`
RAS
RAS
RAS
> (PC-21185)[API] feat: update settings for offers index at Algolia

- api/src/pcapi/routes/backoffice_v3/forms/venue.py
- api/src/pcapi/routes/backoffice_v3/i18n.py
- api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card_venue.html
- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
- api/src/pcapi/routes/backoffice_v3/venues.py
- api/tests/routes/backoffice_v3/pro_test.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21175
Afficher un modifier `venue.bookingEmail` plutôt que `venue.contact.email` dans la page de détails d'un lieu dans le backoffice. C'est cette adresse de « notifications de réservations » qui est utilisée de préférence dans nos communications avec les AC.
> (PC-21175)[BO] feat: show bookingEmail instead of contact.email in venue details

- adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferVenue/OfferVenue.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferVenue/OfferVenue.tsx
- pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferVenue/__specs__/OfferVenue.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21088
- Afficher le nom public (si valorisé) au lieu du nom juridique dans l'iframe adage dans la section 'Adresse où se déroulera l’évènement' 
- Ajout de tests pour le coverage
> (PC-21088)[PRO] feat: should display public name for adage offer venue

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230321T133811_061957688845_add_ean_index_offer.py
- api/src/pcapi/alembic/versions/20230321T135100_474312bd6eaf_add_ean_index_product.py
- api/src/pcapi/core/offers/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21224
Add index to find offer/products by ean.
It will be usefull soon when we will block offer creation if another offer exists with this ean. Or getting/querying an offer by ean.
Duplicate of https://github.com/pass-culture/pass-culture-main/pull/5733 to have the right jira ticket name
> (PC-21224)[API] feat: Add index for ean value

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
L'ordre des id n'est pas garanti en sortie d'une requête sql qui ne contient pas d'`order by`
> (BSR)[API] fix: flaky log test

- api/src/pcapi/routes/backoffice_v3/forms/tags.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19127
Les tags pour les lieux et les offres peuvent contenir des espaces, contrairement à ceux des structures.
> (PC-19127)[API] feat: bov3: whitespaces are ok for some tags

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230323T093430_d1eb4e7db641_register_adage_id_create_date.py
- api/src/pcapi/core/educational/api/adage.py
- api/src/pcapi/core/offerers/models.py
- api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21220
- ajout d'une colonne `adageInsccriptionDate` dans la table venue qui contient la date a laquelle adageId a été set (et None si adageId est None)
> (PC-21220)[API] feat: register date of acceptation for venues in adage

- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.module.scss
- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx
- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx
- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/index.ts
- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveVenueInformations.tsx
- pro/src/components/VenueForm/CollectiveVenueInformations/__specs__/CollectiveVenueInformations.spec.tsx
- pro/src/components/VenueForm/CollectiveVenueInformations/index.ts
- pro/src/components/VenueForm/VenueForm.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21210
Ajouter un schéma visuel pour le référencement DMS sur la page lieu quand le FF WIP_ENABLE_COLLECTIVE_DMS_TRACKING est activé
ℹ️  _C'est simplement des briques placées sans logique pour l'instant, on implémentera tout ça dans un autre ticket quand le back sera implémenté_
> (PC-21210)[PRO] feat: add dms collective timeline in venue form

- api/src/pcapi/algolia_settings_offers.json
Revert pour débloquer le déploiement en staging.
Fix temporaire, on veut pouvoir laisser un replica sans casser les déploiements
> (BSR)[API] fix: revert algolia replica to unblock deployement

- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details/bookings.html
- api/tests/core/bookings/test_models.py
- api/tests/routes/backoffice_v3/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21064
Affiche l'email lié à la résas dans le détails d'une réservations
La jointure étant déjà présente, ceci ne fait qu'afficher l'email.
NA
NA
> (PC-21064)[API] fix: show email on bookings details

- api/src/pcapi/core/offers/models.py
- api/tests/core/offers/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21076
Ajout de la propriété showSubType à Offer, qui va chercher cette info dans extraData.
Le but est de pouvoir y accéder simplement pour l'utiliser dans les règles de fraude.
```
-   conditions:
-   attribute: showSubType
condition:
comparated: "some string value"
operator: ==
model: Offer
factor: 0
name: "Vérification des offres avec ce sous type"
```
> (PC-21076)[API] feat: add showsubtype property to offer

- pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/CollectiveTimeLine/CollectiveTimeLine.tsx
- pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/CollectiveTimeLine/__specs__/CollectiveTimeLine.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21019
Afficher la date de remboursement pour les réservations collectives remboursées
> (PC-21019)[PRO] feat: display reimbursment date in collective timeline

- api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21131
Renommer le champ “Présence CB” sur un lieu par “Relié à un point de remboursement”
> (PC-21131)[API] feat: rename reimbursement point label in bov3

- .github/workflows/build-and-push-docker-images.yml
On the backend we used to have "master" as the version, which was not
very distinctive... Now we have the SHA of the latest commit, which is
a bit more helpful.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20158
> (PC-20158)[*] build: Add version number when building image for testing

- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/routes/native/v1/openapi_test.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20006
Certaines données historiques ne suivent pas les contraintes des enums
Pour éviter des 500, dans ce cas on considère que le profil n'est pas rempli. 
Le but de ce ticket étant de proposer une route qui alimente de l'auto-complétion, on préfère ne rien retourner que des valeurs invalides
- try:except qui retourne None
- Nécessite une update de swagger pour le front
- C'est techniquement un breaking change, compte tenu de la nouvelle clef `profile` La route étant à peine en testing, elle n'est pas encore utilisée dans le front, on peut la modifier
- None
> (PC-20006)[API] fix: make profile route more robust to existing obsolete data

- .github/workflows/build-and-push-docker-images.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20158
yarn version --new-version only allow semantic version syntax MAJOR.MINOR.PATCH not a commit sha1
> (PC-20158)[PRO] fix: remove version from pro/adage deployment

- .github/workflows/mypy-cop.yml
- .github/workflows/update-api-client-template.yml
`set-output` is deprecated and is planned to stop working starting 1st
June: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
---
J'ai ajouté 2 commits déclenchant mypy-cop et update-api-client, pour vérifier que ces 2 actions fonctionnent;
> (BSR)[API] ci: Replace set-output by $GITHUB_OUTPUT

- api/src/pcapi/routes/backoffice_v3/serialization/accounts.py
Afficher correctement un changement d'email par l'admin dans l'historique d'un utilisateur, plutôt que "Action de changement d'email inconnue"
> (BSR)[BO] fix: missing label in user history for admin email change

- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/users/email/send.py
- api/src/pcapi/scripts/subscription/dms/__init__.py
- api/src/pcapi/scripts/subscription/dms/import_dms_applications.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20836
Arreter le spam de la messagerie DMS quand un email n'est pas encore attaché à un compte
On ne veut envoyer le msg qu'une fois
- Commit(s) : …
> PC-20836 fix dms messaging spam

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230324T183947_558feec91836_add_not_null_constraint_on_booking_userId_step_3_of_4.py
- api/src/pcapi/alembic/versions/20230324T183947_56bba24a7f57_add_not_null_constraint_on_booking_userId_step_4_of_4.py
- api/src/pcapi/alembic/versions/20230324T183947_8c17d89b7c9a_add_not_null_constraint_on_booking_userId_step_1_of_4.py
- api/src/pcapi/alembic/versions/20230324T183947_f1e0b83e0b42_add_not_null_constraint_on_booking_userId_step_2_of_4.py
- api/src/pcapi/analytics/amplitude/events/booking_events.py
- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/notifications/push/transactional_notifications.py
The column could store NULL values when `Booking` could be linked to
an `EducationalBooking`. Now that this model has been removed, all
instances of `Booking` are individual bookings and the column can be
made NOT NULLable.
> (BSR)[API] feat: Add NOT NULL constraint on `Booking.userId`

- api/src/pcapi/routes/backoffice_v3/forms/venue.py
- api/src/pcapi/routes/backoffice_v3/venues.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21338
Permettre la modification d'un lieu sans SIRET dans le backoffice.
On conserve toutefois l'interdiction d'ajouter un SIRET à un lieu sans SIRET ou de le supprimer d'un lieu avec SIRET.
Ces deux cas causeraient de toute façon une exception, puisqu'on n'a pas de champ pour modifier le commentaire (une contrainte vérifie SIRET ou commentaire).
> (PC-21338)[BO] fix: update venue without SIRET

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230327T183509_8dbbae44e380_delete_user_profiling_fraud_check_feature_flag.py
- api/src/pcapi/models/feature.py
This feature flag was never used. I suppose that it was "replaced" by
ENABLE_USER_PROFILING, which was removed in fe3111376c8350ff51750d1d.
> (BSR)[API] chore: Delete never used USER_PROFILING_FRAUD_CHECK feature flag

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/models/feature.py
- api/tests/core/bookings/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21241
Ajout de 3 FF:
- DISABLE_BOOST_EXTERNAL_BOOKINGS
- DISABLE_CDS_EXTERNAL_BOOKINGS
- DISABLE_CGR_EXTERNAL_BOOKINGS
afin de désactiver les réservations externes pour pouvoir tester en toute sécurité sur les environnements de pré-prod
> (PC-21241)[API] feat: add DISABLE_XXX_EXTERNAL_BOOKINGS FFs to disable external bookigns

- api/src/pcapi/core/finance/repository.py
- api/tests/core/finance/test_repository.py
We have generated complementary invoices that have extra information
(see PC-17186). Because bookings are linked to both original and
complementary invoices, these bookings would appear twice in the
reimbursement CSV file. That's confusing for users, we should rather
ignore complementary invoices when exporting these reimbursed
bookings.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21211
> (PC-21211)[API] feat: Do not duplicate bookings in reimbursement CSV file

- .gitignore
- api/src/pcapi/routes/backoffice_v3/docs/CSS.md
- api/src/pcapi/routes/backoffice_v3/scss.py
Lorsque boussole est lancé via python, cela créé une erreur récurrente:
```bash
File "/usr/local/lib/python3.10/shutil.py", line 713, in rmtree
ImportError: sys.meta_path is None, Python is likely shutting down
```
Bug reporté ici : https://github.com/sveetch/boussole/issues/46
- Suppression du process boussole lancé depuis python
- Ajout d'un code snippet pour lancer boussole dans la documentation css.
NA
NA
> (BSR)[API] fix: do not start boussole from py process

- .circleci/config.yml
Ne plus lancer les tests e2e, qui ne peuvent plus s'exécuter dans CircleCI (config trop basse de file watchers dans les exécuteurs)
- Commenter la définition des tests et le step, dans la config CircleCI
> (BSR) ci: comment out CircleCI e2e tests

- api/src/pcapi/routes/backoffice_v3/templates/home/home.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20837
Corriger la mise en forme CSS des compteurs pour s'assurer que les _cards_ aient toujours la même hauteur.
> (PC-20837)[BO] fix: always same height four counters cards

- api/src/pcapi/routes/backoffice_v3/forms/account.py
- api/src/pcapi/routes/backoffice_v3/forms/utils.py
- api/src/pcapi/routes/backoffice_v3/forms/venue.py
- api/tests/routes/backoffice_v3/venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21402
Correction (bis) de la modification d'un lieu sans SIRET
Le formulaire ne passe jamais `None` mais une chaîne vide, donc ça tentait de remplacer le SIRET à `None` par un SIRET chaîne vide ; lorsque ça existe déjà, ça refuse sur la contrainte d'unicité. Il faut laisser à `None` !
Le filtre `sanitize_pc_string` sera étendu à tous les champs, de manière globale, dans un prochain commit ; et pas dans celui-ci destiné à un hotfix !
> (PC-21402)[BO] fix: update venue without SIRET

- api/src/pcapi/scripts/external_users/max_user_id.py
It was useful when used in a loop for SendinBlue-related scripts. It's
not used anymore.
> (BSR)[API] chore: Delete unused `max_user_id` script

- api/src/pcapi/routes/backoffice_v3/autocomplete.py
- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/forms/collective_booking.py
- api/src/pcapi/routes/backoffice_v3/forms/individual_booking.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
- api/tests/routes/backoffice_v3/collective_bookings_test.py
- api/tests/routes/backoffice_v3/individual_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21099
En tant que support pro
J'aimerais filtrer les réservations sur les numéros de virement
Afin d’accompagner au mieux les pro lors de leurs questions sur les remboursements
- Sur les pages réservations individuelles et réservations collectives, ajouter un filtre “Numéro de virement” 
- booking.cashflow_batch.label
- Ce filtre regroupe tous les numéros de virement existants (se met à jour avec les nouveaux virements)
- Ce filtre permet de retrouver les réservations dont le numéro de virement est sélectionné dans le filtre
> (PC-21099)[API] feat: Ajouter un filtre numéro de virement sur les réservations

- api/src/pcapi/routes/backoffice_v3/forms/account.py
- api/src/pcapi/routes/backoffice_v3/forms/collective_booking.py
- api/src/pcapi/routes/backoffice_v3/forms/collective_offer.py
- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/forms/individual_booking.py
- api/src/pcapi/routes/backoffice_v3/forms/offer.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/forms/tags.py
- api/src/pcapi/routes/backoffice_v3/forms/utils.py
- api/src/pcapi/routes/backoffice_v3/forms/venue.py
BSR
Filtrer tous les champs de type chaîne de caractère des formulaires du backoffice afin d'éliminer les espaces en début et fin, et considérer les chaînes vides comme `None` (plus clair et pour être certains de ne jamais changer une colonne vide par une chaîne vide lors des éditions ; en bdd c'est `None` quand c'est vide).
Pas de régression dans les tests :)
> (BSR)[BO] refactor: strip() form strings globally and consider empty strings as None

- api/src/pcapi/core/fraud/repository.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/repository.py
- api/src/pcapi/routes/native/v1/banner.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/backoffice_v3/accounts_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/banner_test.py
BSR
Suite à un sujet travaillé en atelier lors de la journée backend :
Réduire le nombre de requêtes à la base de données lors de l'affichage d'un profil jeune dans le backoffice.
Utilisation de `joinedload` pour précharger tout ce qui est nécessaire, en une seule requête.
Il reste juste des vérifications de _feature flags_ en plus.
Les changements affectent aussi les routes de l'app jeunes.
J'ai pour exemple implémenté cette amélioration dans /banner.
Je laisse à la squad jeunes la suite pour anticiper les `joinedload` dans les autres routes. Mais déjà, le chargement de `user.beneficiaryFraudChecks doit se faire a priori une seule fois plutôt que faire n requêtes en fonction du type. @lixxday  …
> (BSR)[API] fix: fetch user with joinedloaded data to avoid N+1 queries

- api/src/pcapi/routes/backoffice_v3/collective_bookings.py
- api/src/pcapi/routes/backoffice_v3/collective_offers.py
- api/src/pcapi/routes/backoffice_v3/individual_bookings.py
- api/src/pcapi/routes/backoffice_v3/offerers.py
- api/src/pcapi/routes/backoffice_v3/offers.py
- api/src/pcapi/routes/backoffice_v3/utils.py
- api/tests/routes/backoffice_v3/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21467
Ignorer les paramètres de filtrage vides dans les paramètres d'URL, utilisés pour le filtrage et la pagination des listes.
La chaîne vide était conservée comme une valeur, qui ne permettait pas de garder la valeur par défaut (affectée uniquement si le paramètre est absent), d'où certaines erreurs 500 si on modifiait l'URL `&per_page=100` par `&per_page=` vide par exemple.
En fait on traite les _query params_ en les passant à un `FlaskForm` pour être considérés comme les données d'un `POST`.
> (PC-21467)[BO] fix: ignore empty strings in query parameters, which ignored default values

- api/src/pcapi/utils/cache.py
The previous version of the code did this:
1. Try to get a key.
2. If empty or `None`, declare that it's a miss only if the key
does not exist.
3. If it's a miss, recalculate the value and cache it.
If another thread sets the key between step 1 and 2, the code thinks
that it's not a miss because, at step 2, the key now exists.
We can fix that by changing the condition upon which we declare a
miss: Redis GET command either returns the value (which is always a
string, possibly empty) or `None` when the key does not exist (or when
it has expired). Thus, by properly checking the value ("is it `None`
or not?"), we don't need to explicitly use the `EXISTS` command. This
avoids the risk of a race condition.
> (BSR)[API] fix: Fix possible race condition in `get_from_cache()` Redis helper

- api/src/pcapi/core/users/api.py
- api/tests/core/users/test_api.py
Current version overrides the birth date when the support team changes a wrong date in an application
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21494
Débloquer les utilisateurs qui ont une date validée erronée (erreur DMS par exemple)
Si le support change la date de naisance, on veut qu'elle reste, pas qu'elle soit écrasée par celle du dossier
- _A destination des Data Analysts, exposer le résultat final (tables et …
> (PC-21494)[API] fix: do not update date of birth on activation if already validated

- api/src/pcapi/routes/backoffice_v3/collective_offers.py
- api/src/pcapi/routes/backoffice_v3/forms/collective_offer.py
- api/src/pcapi/routes/backoffice_v3/forms/fields.py
- api/src/pcapi/routes/backoffice_v3/forms/offer.py
- api/src/pcapi/routes/backoffice_v3/forms/offerer.py
- api/src/pcapi/routes/backoffice_v3/offers.py
- api/src/pcapi/routes/backoffice_v3/templates/home/home.html
- api/tests/routes/backoffice_v3/collective_offers_test.py
- api/tests/routes/backoffice_v3/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21495
Éviter que le tri ne se retrouve actif sur la recherche des offres quand il n'est pas attendu (il est demandé uniquement lors du clic sur les compteurs d'offres à valider). Sinon la recherche se retrouve beaucoup plus longue, potentiellement jusqu'au timeout.
Il y avait un `sort=y` inattendu.
Changement du champ `sort` pour s'aligner avec le tri des validations de structures, fait par @kopax hier.
> (PC-21495)[BO] fix: offers were unexpectedly sorted

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21127
Quand la date d'anniversaire est passé pendant la vérification de identité, on doit le recréditer de son anniversaire passé au moment de la validation.
- Refacto de la fonction create_deposit pour gérer les edge-case dans lesquels l'anniversaire est passé.
- Refacto aussi de la fonction de recredit quotidien.
- …
> PC-21127 Recredit user on validation when birthday occured during ID verification

- pro/src/app/AppLayout.tsx
- pro/src/pages/Offerers/List/Offerers.jsx
- pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.jsx
- pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderForm/CinemaProviderForm.tsx
- pro/src/pages/SignIn/__specs__/SignIn.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21501
- La mise à jour de react-tooltip semble avoir cassé certains tests unitaires. Il semblerait qu'au passage à la v5, il est plus pertinent d'utiliser le composant Tooltip seulement là ou on en a besoin. 
- BSR sur le fichier de test Signin : la variable storeOverride était écrasé dans plusieurs tests
> (PC-21501)[PRO] fix: move tooltip in composent using it

- api/src/pcapi/algolia_settings_offers.json
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21352
rétablir le replica _PRODUCTION Top offres_  dans la config de l’index des offres
(maintenant que le clef d'API est autorisée à faire des opérations sur l'index _PRODUCTION Top offres_, ça passe. testé en lanceant manuellement la commande sur le pod console de la prod)
RAS
RAS
RAS
> (PC-21352)[API] feat: set top offres replica on Algolia offers index

- api/.vscode/launch.json
Retirer un warning de VSCode quand on debug un test
[Screencast from 31-03-2023 12:22:29.webm](https://user-images.githubusercontent.com/14235661/229095411-9fb1cb36-ae7a-48af-837c-940278fcb09d.webm)
- PR : `(PC-XXX) …
> (BSR)[API] test: add version to launch.json to avoid vscode warning on debug

- pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
- pro/src/screens/OfferIndividual/StocksThing/adapters/serializers.ts
Bug intéressant :
Le test set une date au 25 du mois avec une heure UTC précise (22h59) et expect que le call backend est fait à la même date+heure toISOString 
Hors en interne le upsert stocks serialize les stocks en mettant l'heure à la fin du jour dans le département en question (23h59 avec l'heure de Paris dans le cas du test) et reconvertit en UTC
Là on est dans un cas où le test case a été construit pour correspondre au code, mais du coup ça ne marche que quand il n'y a qu'une heure de décalage entre UTC et la timezone de Paris.
Le changement d'heure a eu lieu au 26 mars, à partir duquel le temps UTC est décalé de 2h du temps de Paris
Jusqu'au 31 mars tout allait bien vu qu'on set la date au 25 du mois et que le changement d'heure est le 26
Au 1er avril, le 25 avril a 2h de décalage …
> (BSR)[PRO] fix: unit tests on master

- pro/src/core/Offers/constants.ts
- pro/src/pages/Offers/__specs__/Offers.spec.tsx
- pro/src/screens/Offers/__specs__/Offers.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21006
Masculiniser le dropdown du filtre des types d'offre.
Modifier le dropdown des filtres de la page Offre
Manuelle → Manuel
Importée → Synchronisé
- Branche : `PC-21006-dropdown-filtre`
- PR : `PC-21006-dropdown-filtre`
- Commit(s) : `PC-21006-dropdown-filtre`
> (PC-21006)[PRO] feat: dropdown  filtres page Offre

- pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/__specs__/TicketWithdrawal.spec.tsx
- pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/validationSchema.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18988
Changement wording message d'erreur création d'offre
“Veuillez sélectionner l’une de ces options”
- Branche : `PR-18988-wording-message`
- PR : `(PC-18988) Modification wording message`
- Commit(s) : `(PC-18988)[PRO] feat: wording message d'offre`
> (PC-18988)[PRO] feat: wording message d'offre

- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/routes/pro/offerers.py
- api/tests/routes/pro/get_available_reimbursement_points_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21304
Trier les points de remboursement par `common_name` quelque soit l'état du FF `WIP_ENABLE_NEW_ONBOARDING`
> (PC-21304)[API] feat: Always sort reimbursement points by common_name

- pro/src/pages/Home/Offerers/OffererDetails.jsx
You couldn't select another offerer from the homepage because it tried to set the option with a humanized Id
> (PC-BSR)[PRO] fix: homepage select

- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/routes/native/v1/openapi_test.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21395
Remonter des méthodes d'authentification disponibles dans la route appelée par le stepper /subscription/stepper. De la même manière que c'était déjà fait pour la route /subscription/next_step.
- Ajout du champ allowed_identity_check_methods à l'objet SubscriptionStepperResponse
- Le champ allowed_identity_check_methods dans l'objet NextSubscriptionStepResponse de la route /subscription/next_step est maintenant déprécié.
- _A destination …
> (PC-21395)[API] feat: Add authentication methods in /stepper route response

- api/src/pcapi/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/models/feature.py
- api/tests/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21228
Pour tester que le template qui contient les métadonnées fonctionne correctement en prod, on le conditionne d'un FF pour pouvoir le désactiver en cas de problème.
- Ajout d'un feature flag désactivé par défaut : ENABLE_MARKETING_MAIL_METADATA_DISPLAY
- Utilisation de ce FF dans les rappels de résa J-1, pour utiliser ou non ce nouveau template
> (PC-21228)[API] feat: Add FF and use it to choose booking reminder template

- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21187
Permettre à l'édition massive des offres de désactiver les offres créées par l'API Stock
Un `Provider` est considéré comme désactivé si le `VenueProvider` est inactif ou supprimé, or le `Provider` associé à l'API Stock n'a pas de `VenueProvider` donc il est considéré à tort comme inactif.
> (PC-21187)[API] fix: do not treat book stock api as an inactive provider

- api/src/pcapi/connectors/cgr/cgr.py
- api/tests/connectors/cgr/api_cgr_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21543
Eviter un appel récupérant le WSDL de CGR à chaque appel à une méthode de leur webservice.
- https://docs.python-zeep.org/en/master/transport.html#caching
- Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du …
> (PC-21543)[API] feat: cache CGR WSDL

- api/src/pcapi/connectors/beneficiaries/outscale.py
- api/tests/connectors/beneficiaries/outscale_test.py
- api/tests/core/subscription/ubble/test_api.py
`boto3.client()` is not thread-safe. We sometimes get the following
error:
KeyError: 'default_config_resolver'
File "pcapi/tasks/ubble_tasks.py", line 23, in store_id_pictures_task
ubble_subscription_api.archive_ubble_user_id_pictures(payload.identification_id)
[...]
File "pcapi/connectors/beneficiaries/outscale.py", line 13, in upload_file
client = boto3.client(
File "__init__.py", line 92, in client
return _get_default_session().client(*args, **kwargs)
[...]
File "botocore/session.py", line 1009, in get_component
del self._deferred[name]
To work around that, we now use a dedicated session. And we keep one
for each thread to lessen the overhead of the session initialization.
References:
- discussion of the issue and possible workarounds: https://github.com/boto/boto3/issues/1592
- …
> (BSR)[API] fix: Fix non-thread safe usage of boto3 client in outscale connector

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20230403T131445_66c2977b3cfe_add_pro_user_flags_table.py
- api/src/pcapi/alembic/versions/20230403T131907_841f91f7e665_add_pro_user_flags_userid_fkey_step_1_2.py
- api/src/pcapi/alembic/versions/20230403T132753_580466424daf_add_pro_user_flags_userid_fkey_step_2_2.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/pro/users.py
- api/src/pcapi/routes/serialization/users.py
- api/tests/core/users/test_api.py
- api/tests/routes/pro/post_user_pro_flags_test.py
- pro/src/apiClient/v1/index.ts
- pro/src/apiClient/v1/models/ProFlagsQueryModel.ts
- pro/src/apiClient/v1/services/DefaultService.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21157
Enregistrer en DB des infos de type navigation (quel parcours A/B par exemple) si l'info ne remonte pas via un service tiers comme Firebase
- Ajout d'une table `user_pro_flags`
- Ajout d'une route permettant l'écriture des données
N/A
- Ajout de la table `user_pro_flags` dont la colonne `firebase` de type JSONB permet de stocker des données de navigation comme par exemple quel parcours est présenté dans un A/B testing
> (PC-21157) save pc pro navigation flags

- api/src/pcapi/core/users/repository.py
- api/src/pcapi/routes/backoffice_v3/auth.py
- api/tests/routes/backoffice_v3/auth_test.py
- api/tests/routes/native/v1/authentication_test.py
- api/tests/routes/pro/signin_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21361
En tant que équipe data ou équipe fraude ou équipe infra
J'aimerais pourvoir identifier quels mails sont ciblés lors des tentatives de signin
Afin de mieux comprendre les attaques sur les routes /signin et prendre des actions pour réduire le nombre de comptes piratés.
doit prendre effet sur tous les endpoints possibles de connexion
> (PC-21361)[API] feat: log any successful or failed connexion with email

- api/src/pcapi/routes/backoffice_v3/admin.py
- api/src/pcapi/routes/backoffice_v3/templates/admin/feature_flipping.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20950
Ajout de l'environnement au message de confirmation d'activation/désactivation du FF.
> (PC-20950)[API] feat: add env name to warning feature flipping message

- pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.tsx
- pro/src/pages/SignIn/SigninForm/SigninForm.tsx
- pro/src/pages/SignIn/__specs__/SignIn.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21378
Sur la [page de connexion](https://pro.testing.passculture.team/connexion) remplacer le wording “égaré” par “oublié”.
- Branche : `PC-21378-wording-message-connexion`
- PR : `(PC-21378)[PRO] feat: wording message connexion`
- Commit(s) : `(PC-21378)[PRO] feat: wording message connexion`
> (PC-21378)[PRO] feat: wording message connexion

- api/src/pcapi/core/search/commands/indexation.py
- api/tests/core/search/test_commands_indexation.py
These commands have been replaced by "partially_index_offers" and
"partially_index_venues".
> (BSR)[API] chore: Remove backward-compatibility indexation commands

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/validation.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/pro/post_save_new_onboarding_data_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21320
Définir les 4 attributs d'accessibilité à None pendant l'onboarding, afin qu'ils soient remplis plus tard par l'AC.
- Ajout d'un argument `strict_accessibility_compliance` à `create_venue()`, dont la valeur par défaut est `True`, et qui permet d'ignorer la validation des attributs d'accessibilité.
> (PC-21320)[API] feat: set venue accessibility to None in onboarding

- api/src/pcapi/core/offerers/api.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/pro/post_save_new_onboarding_data_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21319
Définir le bookingEmail d'un lieu créé pendant l'onboarding comme étant l'email de l'utilisateur
> (PC-21319)[API] feat: set venue.bookingEmail to user.email in onboarding

- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx
- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx
- pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveVenueInformations.tsx
- pro/src/components/VenueForm/CollectiveVenueInformations/__specs__/CollectiveVenueInformations.spec.tsx
- pro/src/screens/VenueForm/__specs__/VenueFormScreen.spec.tsx
- pro/src/utils/collectiveApiFactories.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21066
Fix le typing du state des démarches dms collectives suite au changement côté back. 
On utilise désormais le type DMSApplicationForEAC
Impact : supression du state 'draft' qui n'est finalement pas pertinent pour le chantier
> (PC-21066)[PRO] fix: fix typing in collective dms timeline

- pro/src/components/SignupJourneyBreadcrumb/SignupJourneyBreadcrumb.module.scss
- pro/src/components/SignupJourneyBreadcrumb/SignupJourneyBreadcrumb.tsx
- pro/src/components/SignupJourneyFormLayout/SignupJourneyFormLayout.tsx
- pro/src/components/SignupJourneyFormLayout/SignupJourneyFormLayoutContent.module.scss
- pro/src/screens/SignupJourneyForm/ConfirmedAttachment/ConfirmedAttachment.module.scss
- pro/src/screens/SignupJourneyForm/Offerer/Offerer.module.scss
- pro/src/screens/SignupJourneyForm/Offerer/Offerer.tsx
- pro/src/screens/SignupJourneyForm/Validation/Validation.module.scss
- pro/src/screens/SignupJourneyForm/Validation/Validation.tsx
- pro/src/screens/SignupJourneyForm/Welcome/Welcome.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21337
- Corriger l'affichage du nouveau parcours d'inscription
Avant: 
Après:
Pour accéder au nouveau parcours d'inscription:
Après la création d'un nouveau compte, juste après la connexion, sinon il faut se rendre à /parcours-inscription
En local ce n'est pas vraiment possible, donc il faut aller sur l'url directement, ou alors il faut supprimer via le backoffice les structures d'un compte en local, le pro par exemple
à la connexion, le parcours s'affichera
Il faut le FF: WIP_ENABLE_NEW_ONBOARDING
> (PC-21490)[PRO] fix: signup journey breadcrumb position

- api/src/pcapi/routes/backoffice_v3/templates/offerer/user_offerer_validation.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21608
Par défaut, le rouge indiquait que le tri était actif sur la colonne date de création, cela faisait un mauvais UX, l'utilisateur ne comprenant pas pourquoi la couleur est actif que sur une page.
Cette PR supprime l'affichage de la séléction du tri, et affiche le text en rouge comme un lien ce qui est le comportement par défaut.
- Suppression de la class `text-body` ajouté automatiquement sur le `<th>` quand le query params `sort` n'est pas passé
NA
NA
> (PC-21608)[API] fix: show dateCreated label as a link

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/pro/signup.py
- api/tests/routes/pro/signup_pro_V2_test.py
- api/tests/routes/pro/signup_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21573
Enregistrer l'info de parcours présenté à l'utilisateur au moment où l'objet User est créé donc lors de l'envoi du formulaire de création de compte.
- Enregistrement de ce flag lors du traitement des routes signup v1 et v2
> (PC-21573)[API] save firebase flag when creating user
