- pc
pour avoir de la donnée testcafe pour pc 134 (genre des offerers avec ou sans iban, etc...)
c'est plus simple maintenant de passer par la sandbox industrial pour les tests ci.
> (pc-134) Manager js testcafe

- docker-compose.yml
- pc
Avec mon WSL sous Windows, je n'arrivais pas à lancer `pc start-backend` dû, j'imagine, à une mauvaise gestion du chemin `./api/postgres_data`. Par conséquent, et c'est une bonne pratique, il vaut mieux utiliser le nom du volume directement, comme ça, Docker met son volume dans un répertoire à lui et il n'y a plus de problème d'environnement.
Pour plus de détails : https://docs.docker.com/compose/compose-file/#volume-configuration-reference
> Mettre le nom du volume plutôt qu'un chemin

- README.md
- docker-compose-app-worker.yml
- docker-compose-app.yml
- docker-compose-metabase.yml
- infra/pc_scripts/test_backend.sh
- pc
A new "pcapi" Python package has been created so that we can get rid
of all PYTHONPATH overrides. See recent changes in `pass-culture-api`
for further details.
> (PC-4517) Adapt to new pcapi Python package

- install_lib_ci.sh
[La version de Chrome avait été freezée il y a un an car une version nous posait problème lors des testcafé](https://github.com/pass-culture/pass-culture-main/commit/c52562b2363b0237746dd987ad3e9bb18378b8b5).
Nous avons 10 versions de retard donc il est temps d'être à jour pour éviter d'avoir un delta entre nos machines locales et la CI.
> current version of chrome in ci

- hooks/pre-commit
Comme discuté en point standards, ne pas bloquer le commit à cause d'erreurs MyPy, en attendant de bien le configurer et de rendre la codebase compatible.
Aussi, afficher le code d'erreur (utile pour les directives d'ignorance que l'on pourrait ajouter).
> Edit mypy step in pre commit hook

- docker-compose-app.yml
The variables are defined in the api env files. The .env.development definitions were overriden by this setting
> (PC-5837) Remove environment variable override

- .circleci/config.yml
Les test cafe de pro n'utilisent plus la sandbox industrial mais une sandbox presque vide nommé testcafe
> [CI.testcafe] use "testcafe" sandbox instead of "industrial" for pro

- .gitignore
The `shared` submodule has been removed in https://github.com/pass-culture/pass-culture-main/pull/334
To prevent a local copy to be used when creating a tag for the project, we ignore it
> (PC-8760) .gitignore: ignore the former `shared` submodule

- infra/docker-images/db-ops/dump_restore.sh
On staging, we don't want to synchronize all venues:
- we don't need to have up-to-date offers and stocks;
- it fills Algolia staging index and exhausts our records quota.
> dump_restore: Disable all venue providers

- pc
Avant :
La commande "pc -e testing sandbox -n industrial" ne fonctionnait pas
Après : 
Elle fonctionne
> (Tech): Correction du script pc

- infra/docker-images/db-ops/anonymize.sql
Generated BIC (such as "XX001234") were not valid. They must be valid,
otherwise the validation of the "banque de France" XML file fails when
the "payment generation script" is run on staging.
> infra: Fix anonymization of BIC

- README.md
Améliorations du read me :  
- Instructions pour le déploiement / pose de tag : réorganisation des instructions pour mieux comprendre à quoi sert le tagging. 
- Environnement local : 
- dé-duplication d'instructions 
- possibilité d'utiliser pyenv plutôt que virtual env
- ajout de quelques informations pour l'IDE
- Autres améliorations (introduction, hooks, ...)
> Improve deploying and tagging instructions in readme

- api/src/pcapi/alembic/versions/20211115T073416_a0a822d365ac_add_not_null_venue_provider_venue_id_at_offer_provider_step_1.py
- api/src/pcapi/alembic/versions/20211115T080547_010aba57cb3e_add_not_null_venue_provider_venue_id_at_offer_provider_step_2.py
- api/src/pcapi/alembic/versions/20211115T080553_f2cb5833253a_add_not_null_venue_provider_venue_id_at_offer_provider_step_3.py
- api/src/pcapi/alembic/versions/20211115T080556_32c7ca9be253_add_not_null_venue_provider_venue_id_at_offer_provider_step_4.py
- api/src/pcapi/core/providers/models.py
- api/tests/admin/custom_views/venue_provider_view_test.py
- api/tests/local_providers/allocine_stocks_test.py
- api/tests/local_providers/provider_manager_test.py
- api/tests/models/allocine_venue_provider_price_rule_test.py
- api/tests/models/allocine_venue_provider_test.py
- api/tests/repository/venue_provider_queries_test.py
- api/tests/scripts/venue/modify_allocine_price_rule_for_venue_test.py
Old PR: pass-culture/pass-culture-api#3584
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11243
Rendre la colonne `venueIdAtOfferProvider` dans la table `venue_provider` non nullable
- Fix et migrations vers les factories des tests impactés 
​
> (PC-11243): fix null values venue id at offer provider

- api/src/pcapi/scheduled_tasks/clock.py
There might be a cleaner way to express "every ten minutes", but I
can't find this information in APScheduler documentation.
> (PC-11621) scheduled_tasks: Fix job definition for `price_bookings()`

- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/native/v1/settings.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11782
Conditionner l'utilisation de la vérification de l'identité de l'utilisateur via Ubble dans l'ensemble du produit : Aussi bien côté back / api que côté Front / app.
Ajout du feature toggle ENABLE_UBBLE
​
Vérifications de la présence du nouveau Feature Flag, à True et à False :
- dans le backoffice : http://localhost:5000/pc/back-office/feature/ => OK
- dans l'appel d'API réalisé par la webapp : http://localhost:5000/features => OK
​
> (PC-11782) Add feature flag for Ubble, disabled by default

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_educational_bookings.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11548
Notre PO souhaite pouvoir tester que les paiements pour les réservations éducationnelles et individuelles remontent bien, ensemble, dans le csv des paiements.
Dans le script sandbox qui crée des réservations éducationnelles, ajout d'une série de réservations individuelles avec le même offerer, afin de rendre testable facilement cette feature
​
La génération de ses réservations individuelles, au sein d'un script sur les réservations éducationnelles sera supprimée dans quelques heures, après la revue PO.
​
> (PC-11548) : modifiy sandbox : add UsedIndividualBookings along with EducationalBookings to make it easier for PO to test the feature in testing

- api/hooks/pre-commit
Mettre à jour les chemins de fichiers de configuration utilisés par les outils de lint/format du hook precommit:
- isort
- black
- mypy
- pylint
> [API] hooks: edit linters config path args

- .circleci/config.yml
Notifier uniquement pour la branche `master` les échecs des jobs de tests unitaires, d'intégration et de qualité.
D'autre part, améliorer le template de la notification.
Avant:
Après:
> circleci: notify test failures only for `master` branch

- api/src/pcapi/core/bookings/repository.py
- api/tests/core/bookings/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11779
Corriger le problème de format des exports CSV pour les réservations.
Excel most likely expects CSV to be separated by... semi colon.
> on European Windows versions this character [comma] is reserved
> as the Decimal Symbol and the “List Separator” is set by default
> to the semicolon
​
> [API][PC-11779] adapt bookings export for Excel

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20211115T135126_e2ec54a156f2_add_recredit_amount_to_show.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/routes/native/v1/account_test.py
- api/tests/scripts/payment/user_recredit_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11709
Remonter au front un point de donnée contenant le montant recrédité à un utilisateur lors de son passage de 15 à 16 ans, où 16 à 17 ans
- nouvelle colonne 
- update de la valeur au recredit
- route pour reset la valeur
​
> [PC-11709] [API] add recredit amount to show

- api/hooks/pre-commit
Git hooks are run from the root of the Git repository. As such,
running `alembic` fails because it cannot find its configuration
file. We could provide it (`alembic --config api/alembic.ini`). But
this file mentions `src/pcapi/alembic/` as the path of the "alembic"
folder, which cannot be found from the root of the Git repository. We
could specify `%(here)s/src/pcapi/alembic` and Alembic would find the
directory... but there would be an error while importing modules
because required environment variables are missing, since `.env.` file
are in the `api/` directory (and thus not read when running from the
Git repository).
> api: hooks: Fix Alembic pre-commit check

- api/hooks/pre-commit
Commits à relire séparément.
Démo du nouvel affichage (avec mypy et pylint désactivés) :
[![asciicast](https://asciinema.org/a/DI0w6Uplp4HmefsgK7VsKrxuL.svg)](https://asciinema.org/a/DI0w6Uplp4HmefsgK7VsKrxuL)
> [API] Hooks de pre-commit : affichage plus compact ; possibilité de désactiver certaines vérifications

- api/src/pcapi/core/bookings/factories.py
- api/src/pcapi/core/educational/factories.py
commits à relire séparément, cf. les messages de commit pour les détails.
> factories : Utiliser `utcnow()` au lieu de `now()`

- api/src/pcapi/flask_app.py
Why would we want to use the same color (red) on development (local)
and production? "Oh, the prompt is red, it must be my local
environment, right?"
(Bug introduced (by myself) in eca20610328298d6c9dd42e24f9b4d696a63f3b2.)
> [api] Fix color of Python shell prompt on development environment

- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11847
Fournir un hash unique au frontend à travers un endpoint, utilisé comme sessionId pour le profiling utilisateur
Endpoint native, hash par uuid4, de la forme '0900788f-0e04-4129-a652-1a5f045b06c8'
​
> Backend - Décli Web - Intégration de TMX - Ajout du endpoint qui génére le TMX Session ID

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20211117T110737_8794f331080c_update_beneficiaryfraudcheck.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11837
Démarrer le refactor des modèles de fraudes, afin de simplifier la modélisation en base, et mieux respecter les usages actuels et le workflow d'inscription revu récemment.
On ajoute au FraudCheck l'état, les codes d'erreurs, et un message pour un operationnel
Mise à jour des factories
​
> [PC-11837][API] Prepare BeneficiaryFraudCheck for subscription refactor

- api/.env.development
- api/.env.testauto
- api/src/pcapi/connectors/api_adage.py
- api/src/pcapi/core/educational/adage_backends/__init__.py
- api/src/pcapi/core/educational/adage_backends/adage.py
- api/src/pcapi/core/educational/adage_backends/base.py
- api/src/pcapi/core/educational/adage_backends/logger.py
- api/src/pcapi/core/educational/adage_backends/testing.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/educational/testing.py
- api/src/pcapi/settings.py
- api/tests/conftest.py
- api/tests/connectors/api_adage_test.py
- api/tests/core/educational/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11612
Notifier adage qu'un nouvelle préreservation a eu lieu pour une offre eac collective
- Dans la méthode `book_educational_offer`, ajouter la notification à adage après la sauvegarde du `prebooking`
- Creation de différents `adage_backends` en fonction des environnements:
- Un AdageHttpNotifier pour testing / staging / prod
- Un logger pour l'environnement de dev
- Un AdageSpyNotifier pour les tests "métier"
​
Les tests spécifiques au `AdageHttpNotifier` sont dans le fichier `tests/connectors/api_adage_test.py`
Un test cas passant avec le Spy a été réalisé dans `core/educational/test_api.py`
​
> [API][PC-11612] Notify adage of prebooking

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/fraud/models.py
- api/tests/connectors/beneficiaries/ubble_fixtures.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11703
Apres des tests de branchement, le retour de la 1ere requete n'étais pas le bon,
cette PR corrige la prise en compte du retour de l' API.
Modification de la fixture, du modele de retour de ubble avec des champs optionnels.
> (PC-11703) Fix ubble response parsing and fixture

- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11848
Corrections après les commentaires post-merge de la code review :
https://github.com/pass-culture/pass-culture-main/pull/503
La validation du session id n'était pas compatible avec le format créé dans :
https://passculture.atlassian.net/browse/PC-11847
​
​
> (PC-11848) api: Fix session id validation for user profiling

- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/scripts/payment/user_recredit_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11876
But de la pull request
Corriger le bug suivant: si un utilisateur créé son compte le jour de son anniversaire, il est recrédité à minuit, alors qu'il n'est pas éligible au recredit
Implémentation
`<=` devient `<` #changementmicroscopique
> (PC-11876) fix:[Recredit] fix double recredit on birthday bug

- pro/package.json
- pro/src/components/pages/Reimbursements/Reimbursement.scss
- pro/src/components/pages/Reimbursements/ReimbursementsDetails.tsx
- pro/src/components/pages/Reimbursements/ReimbursementsWithFilters.jsx
- pro/src/components/pages/Reimbursements/__specs__/ReimbursementWithFilters.spec.jsx
- pro/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11784
Implémenter un nouvel affichage en section sur la page des remboursements dépendamment du feature flag `SHOW_INVOICES_ON_PRO_PORTAL` pour permettre l'ajout d'une nouvelle section "Justificatifs de Remboursement" (vide pour le moment)
​
- Creation d'un nouveau composant en tsx pour l'affichage des détails de remboursement
​
> [PC-11784][PRO]: Display new invoice section when FF is active

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11703
Corriger l'URL de webhook envoyée à Ubble
> [PC-11703][API] Fix wrong webhook data sent to ubble

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11783
Le nom et le prénom, devenus obligatoires pour la parcours d'inscription via Ubble, ne doivent finalement être obligatoires que pour les utilisateurs de 15 à 18 ans, éligibles au crédit. Les autres utilisateurs peuvent s'inscrire sans prénom ni nom.
Mise à jour du validateur pydantic et enrichissement des tests unitaires
​
Je passe en même temps un commit pour enrichir les tests sur le session id
> Pc 11783 create account with first and last name

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11703
Retourner l' URL de l'identificationn Ubble
> [PC-11703][API] Returns the identification Url

- api/src/pcapi/core/fraud/repository.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/native/v1/__init__.py
- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11825
Ajouter une route pour que le front puisse commencer à l'utiliser pour le nouveau parcours d'inscription.
La fonction `get_next_subscription_step` est temporaire puisqu'elle s'appuiera par la suite sur `user.subscriptionState`.
> (PC-11825) Add new route to query next subscription step

- pro/src/ui-kit/Tag/Tag.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11894
fix css du tag eac passant sur plusieurs lignes
> (PC-11894)[PRO]: fix eac tag splitting in multiple lines in offers list

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/factories.py
- api/tests/core/users/external/external_users_test.py
- api/tests/core/users/test_api.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/shared/get_user_profile_test.py
- api/tests/scripts/batch_update_users_attributes_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11219
This field is used during signup process to prevent from re-entering the process if a CNI has already been uploaded.
This is a legacy field that will be soon removed with the introduction of user.subscriptionState.
For now, we need to reset it to let an ex-underage beneficiary user renter the subscription process
ld from).
J'ai eu la confirmation des data analystes : ils n'utilisent pas ce champ après l'activation du bénéficiaire (et les requêtes qui l'utilisent sur metabase sont parait-il obsolètes).
Et j'ai prévenu Coline du marketing qui l'utilise dans ses "automations" sur sendinblue...
​
> (PC-11219) Reset user.hasCompletedIdCheck after beneficiary activation

- api/src/pcapi/core/mails/transactional/send_transactional_email.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/mails/transactional/users/email_duplicate_pre_subscription_rejected.py
- api/src/pcapi/core/mails/transactional/users/fraud_suspicion_email.py
- api/tests/core/mails/transactional/test_send_fraud_suspicion_email.py
- api/tests/core/mails/transactional/test_send_transactional_email.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11937
Fixer https://sentry.internal-passculture.app/organizations/sentry/issues/235050/?referrer=jira_integration
- Sendinblue n'accepte pas `"params: {}` dans le body d'une requete pour envoyer un email
- On retire le champs à la place de le laisser vide
​
> (PC-11937) fix:[Sendinblue] remove params from body if it is empty

- api/src/pcapi/core/users/api.py
- api/src/pcapi/settings.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11669
Pour les tests de performance, les ops ne peuvent pas récupérer les token envoyés par email. 
On met donc en dur le nom du token créer.
Il y a une contrainte d'unicité sur Token.value. C'est pour cela qu'on spécifie le type de token créé et l'id de l'utilisateur dans le Token.value.
J'ai prévenu les ops qu'il ne faudra pas appeler ces routes plusieurs fois...
> (PC-11669) Create tokens with constant values if we are running performance tests

- api/src/pcapi/routes/pro/users.py
- api/tests/routes/pro/patch_user_test.py
It's clearer than looking for the presence of `UserOfferer` objects.
The downside is that only *validated* pro users will be able to change
their profile... but it's actually safer.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11929
> [PC-11929][api] Use new `User.has_xxx_role()` in `patch_profile` route

- api/src/pcapi/core/bookings/repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11892
Amélioration des temps de réponse de l'export CSV.
Dans le cas d'usage pointé par le ticket Jira on a:
Avant: Elapsed time: 121.7035 seconds
Après: Elapsed time: 0.1169 seconds
- Use PostgresQL's cursor - through SQLAlchemy's `yield_by` - instead of home made pagination.
​
​
> (PC-11892) improve bookings csv response time

- api/src/pcapi/scripts/beneficiary/remote_import.py
- api/tests/scripts/beneficiary/remote_import_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11865
Corriger un probleme de vérification d'utilisateur en doublon, lorsqu'il a deja effectué une vérification
de doublon de pièce d'identité, via jouve par exemple, et que l'information est deja en base: 
l'utilisateur se retrouve doublon de lui-meme
> (PC-11865) avoid checking id piece number with current applicant user

- api/src/pcapi/routes/native/v1/account.py
- api/tests/routes/native/v1/account_test.py
This route was created to prevent the user from re-entering the id-check process. But since then, a lot of patches have bee n added. Now the field is updated both in /beneficiary_information route and on jouve callback. So when the frontend calls the has_completed_id_check_ route we already had the information. And when we activate the beneficiary, we reset the field to false. So we dont want it to be re-updated afterwards
​
​
> (PC-11219) Do not update hasCompletedIdCheck on has_completed_id_check route

- webapp/scripts/build_redirects.js
- webapp/src/components/layout/Details/Details.jsx
- webapp/src/components/layout/Details/__specs__/Details.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11794
amélioration du wording de redirection v1 vers v2
- amélioration du wording de redirection v1 vers v2
​
​
> (PC-11794)(WebApp) amélioration du wording de redirection v1 vers v2

- api/src/pcapi/core/users/email/__init__.py
- api/src/pcapi/core/users/email/update.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11753
Permettre au client natif de connaître la date d'expiration du token utilisé pour le changement d'email (ajouté récemment via [cette PR](https://github.com/pass-culture/pass-culture-main/pull/468)). S'il n'y a aucun token actif au moment de la requête. La date d'expiration est `None`.
Le besoin côté client natif est le suivant : si l'utilisateur n'a pas cliqué sur le lien d'activation et qu'il commence à nouveau le parcours de modification d'email, on aimerait lui indiquer si un lien d'activation (avec un token actif) existe pour l'inciter à vérifier ses emails.
> [API] (PC-11753) feat:account: token expiration date

- pro/src/components/pages/Reimbursements/Reimbursement.scss
- pro/src/components/pages/Reimbursements/ReimbursementsWithFilters.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11784
Fix du titre Remboursements disparu après le merge de la première PR liée à ce ticket dû à dès règles CSS se chevauchant.
> (PC-11784)(PRO): Fix classname for new refund section to prevent css override

- api/src/pcapi/core/finance/repository.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/routes/pro/offerers.py
- api/src/pcapi/routes/serialization/finance_serialize.py
- api/tests/routes/pro/get_offerer_business_unit_list_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11476
Ajout d'un endpoint renvoyant des listes de business unit
​
> (PC-11476)(API) pro: create endpoint for business unit list

- api/src/pcapi/core/users/email/send.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/webapp/change_beneficiary_email_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11726
Ajouter la nouvelle adresse dans l'email d'activation de la nouvelle adresse.
Le but est de permettre au front de récupérer facilement cette information et de l'afficher, surtout en cas d'erreur (par exemple s'il y a besoin de contacter le support).
> [API] (PC-11726) feat:account: add new_email to link

- api/src/pcapi/connectors/beneficiaries/exceptions.py
- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/routes/native/v1/account.py
- api/tests/conftest.py
- api/tests/connectors/beneficiaries/ubble_test.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11842
Interne - Ubble (backend) - Message d'erreur en cas d'API down d'Ubble 
Renvoie une erreur HTTP avec un code d'erreur, afin d'être traité par le frontend
​
> (PC-11842) api: Error message when Ubble API is down

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20211125T162121_c86504df1384_create_index_on_offer_s_isbn.py
- api/src/pcapi/alembic/versions/20211125T180047_3cb2b2fb88d3_create_index_on_product_s_isbn.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/models/product.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11985
1. A missing index on `extraData -> isbn` forced the query to scan
the entire table which takes too much time.
2. searching for the name OR the ibsn made Postgres scan the
table instead of using the indexes. By using an union instead
of a OR condition, Postgres can spawn two worker to search against
the indexes and then create the result set.​
Un recherche via get_capped_offers_for_filters sur l'ISBN `9782075144292` avec un admin donne:
- ancienne méthode: coupée à 60 minutes
- nouvelle méthode: 0.7638 seconds (1.2391s avec la serialization)
> [PC-11985][API] Improve search performance on pro's offer page

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11783
Déplacement de la demande des prénom et nom du jeune bénéficiaire plus tard dans le parcours d'inscription.
- `first_name` et `last_name` ne sont plus demandés à la création du compte dans la route `/account`
- on les demande par contre dans la route `/beneficiary_information`
- ni le prénom ni le nom n’est obligatoire si le FF ENABLE_UBBLE n’est pas activé
- prénom et nom sont tous deux obligatoires si le FF ENABLE_UBBLE est activé ; plus besoin de vérifier l'âge car cet écran sera de base affiché uniquement aux users de 15 à 18 ans
​
> (PC-11783) api: First name and last name with Ubble moved later in account process

- api/src/pcapi/core/categories/subcategories.py
- api/tests/models/offer_type_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11991
Ajout d'une sous-catégorie :
https://www.notion.so/passcultureapp/Pratique-artistique-vente-distance-c0b652a5ee3d4983981f5832f1d024b5
Telle que décrite ici :
https://www.notion.so/passcultureapp/Process-de-cr-ation-de-sous-cat-gories-edbb6684ec084464b9766aee3744fe66
​
> (PC-11991) api: add subcategory 'Pratique artistique - vente a distance'

- api/src/pcapi/core/categories/subcategories.py
- api/tests/models/offer_type_test.py
[Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11992
Ajout d'une sous-catégorie :
https://www.notion.so/passcultureapp/Spectacle-vivant-vente-distance-2d98828e9d894672854f43f5e21933e0
Telle que décrite ici :
https://www.notion.so/passcultureapp/Process-de-cr-ation-de-sous-cat-gories-edbb6684ec084464b9766aee3744fe66
​
](https://passculture.atlassian.net/browse/PC-11992)
> (PC-11992) api: add subcategory 'Spectacle vivant - vente a distance'

- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/educational/utils.py
- api/tests/core/educational/test_api.py
- api/tests/core/educational/test_utils.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11809
Jusqu'à présent, les règles métiers régissant la date limite d'annulation pour les réservations eac étaient les mêmes que pour les réservations individuelles.
Désormais, ces règles divergent. Pour l'instant, la règle est : 15 jours avant l'évènement ou date de réservations
- Ajout d'une fonction `compute_cancellation_limit_date_for_educational_booking` dans un fichier `utils` dans `core.educational.api`
- Remplacement de l'appel existant par un appel à cette nouvelle fonction dans `api.create_educational_booking`
​
- NA
​
> [PC-11809][api] : extend cancellation limit date to 15 days prior event for eac bookings

- api/src/pcapi/connectors/api_demarches_simplifiees.py
- api/src/pcapi/core/subscription/messages.py
- api/src/pcapi/routes/external/users_subscription.py
- api/src/pcapi/scripts/beneficiary/remote_import.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11419
But de la pull request
Ajout de l'envoie de message d'erreur à l'utilisateur lors d'un dossier "en construction" pour indiquer un email non trouvé, une erreur de pièce d'identité ou de code postal.
Implémentation
Ajout d'une fonction dans le webhook
​
Informations supplémentaires
Exemples : nettoyage de code, utilisation de factories, Boy Scout Rule
Explications sur l'utilisation d'outils peu communs (Exemple psql window function, metaclasses, yield from)
​
> Pc 11419 send dms user message

- api/src/pcapi/core/educational/repository.py
- api/tests/routes/adage/v1/get_educational_institution_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12040
Réparer les problèmes de performance sur Adage (Query pas optim et N+1 corrigée au passage)
- Utilisation de contains_eager au lieu de joinedload pour éviter les problèmes de données récupérées sans filtre
​
AVANT: ([Version dalibo](https://explain.dalibo.com/plan/SpF))
```
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Gather  (cost=14032669.70..24052178.03 rows=14979378 width=2724) (actual time=480791.927..1016348.214 rows=3 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Parallel Hash Left Join  (cost=14031669.70..22553240.23 …
```
> (PC-12040) Fix adage query performance issue

- api/src/pcapi/core/categories/subcategories.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11730
Petit oubli de la part des POs pour ces 2 catégories de livres numériques
> (PC-11730) Allow underage to book ABO_LIVRE_NUMERIQUE and TELECHARGEMENT_LIVRE_AUDIO even if not free

- pro/config/webpack.config.js
Depuis peu les changements de configuration du projet on fait passer le build webpack en failure quand eslint lève une erreur.
Ici on conserve l'affichage des erreurs du linter sans bloquer le rendu du site.
> config.webpack dev: do not fail on linter error

- api/src/pcapi/admin/custom_views/suspend_fraudulent_users_by_ids.py
- api/src/pcapi/templates/admin/suspend_fraudulent_users_by_user_ids.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11106
Afficher un message d'information sur la page de suspension des utilisateurs par id sur FA pour prévenir les non super-admin qu'ils n'ont pas accès à cette fonctionnalité
> (PC-11106)[FA]: Add info message on user suspension by id view for non super admin

- pro/src/new_components/FormLayout/FormLayout.module.scss
- pro/src/new_components/FormLayout/FormLayout.tsx
- pro/src/new_components/FormLayout/FormLayoutActions.tsx
- pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12005
Fix design du bouton de droite qui prenait trop de place
Suppression de l'utilisation du design du formulaire
Ajout du css scopé pour cet écran
​
​
> (PC-12005)[PRO] fix design offer type screen

- api/src/pcapi/admin/custom_views/offer_view.py
- api/tests/admin/custom_views/offer_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12062
Corriger une erreur remontée par Sentry :
TypeError: 'Offer' object is not iterable
Tests unitaires créés pour ces actions approve/reject (cas nominal et cas d'erreur)
> (PC-12062) api: Fix TypeError: 'Offer' object is not iterable

- api/src/pcapi/core/users/external/educonnect/api.py
- api/src/pcapi/core/users/external/educonnect/exceptions.py
- api/src/pcapi/core/users/external/educonnect/models.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11763
Educonnect nous envoie une info sur le type d'utilisateur : élève ou représentant légal.
On veut tej les représentants légo.
> (PC-11763) Redirect parents to error page after educonnect

- api/src/pcapi/core/users/api.py
- api/src/pcapi/notifications/push/backends/batch.py
- api/src/pcapi/tasks/batch_tasks.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11955
Fix : les cloud tasks n'acceptent pas les méthodes DELETE (http), il faut donc transformer passer par une tâche interne, appelée par une cloud task.
> (PC-11955) fix:notifications: use internal task

- api/src/pcapi/core/categories/subcategories.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11730
Commentaire de Mariam dans le ticket : 
Revue PO: KO
Les sous-catégories suivantes doivent être reservable quand c’est payant:
- Cinéma - Vente à distance
- Musée - Vente à distance
La catégorie suivante est non reservable quand payant:
- Spectacle enregistrée
> (PC-11730) Fix bookability by underage for some subcategories

- api/src/pcapi/alembic/env.py
Otherwise `alembic revision --autogenerate` fails in
`run_migrations()` with an error:
Foreign key associated with column 'business_unit.bankAccountId'
could not find table 'bank_information' with which to generate a
foreign key to target column 'id'
> [bsr][api][alembic] Let Alembic know about our database models

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20211202T112702_503904c2cab7_add_number_of_tickets_to_stock_model_for_eac_collective_offers.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/stocks.py
- api/src/pcapi/routes/serialization/stock_serialize.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/post_educational_stock_test.py
- api/tests/routes/webapp/get_booking_by_id_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11973
Ajout d'une fonctionnalité côté eac collectif : création de stock en vue de la v0.1
- Ajout d'un nouveau champ dans le modèle `Stock` qui contiendra le nombre de places disponibles pour un évènement eac
- Nouvelle route de création de stock eac avec moins de contraintes métier
- Un seul stock possible par offre eac, d'où une quantité figée à 1, et la possibilité de séparer création et édition
​
​
> [PC-11973][api] educational offer stock creation

- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11711
En tant que l'équipe support. J’aimerais avoir accès au crédit restant de l’user dans FA Afin de traiter plus rapidement les tâches quotidiennes de calcul du crédit
Afficher dans l’onglet Jeunes du FA 
- le crédit global restant 
- le crédit restant par plafond (numérique, autre)​
> (pc-11711)(API)(FA) Fix wording in beneficiary view

- api/src/pcapi/core/fraud/api.py
- api/tests/core/fraud/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11910
En tant que pass Culture 
J'aimerais m’assurer que notre script d’import des dossiers DMS accepte bien les numéros de pièces étrangers. 
Afin de permettre aux utilisateurs avec les passeports et CNI étrangers de déposer un dossier.
- Mettre à jour les règles de validation de format pour accepter les formats suivants : 
- Tunisie (Y808952)
- Turquie (U 13884935)
- Ancienne ID italienne (AZ 1461290)
- ID Belge (595-0103264-74)
- ID Congolaise (1277367)
- ID Camerounaise (1238034)
- ID Algérienne (100030595009080004)
- ID Mauricienne (1774519)​
​
> Pc 11910 check id fraud foreign

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/validation.py
- api/src/pcapi/routes/pro/venues.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/patch_venue_test.py
- api/tests/routes/pro/post_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11480
Lorsque les route d'édition et de création de lieu contienne un `businessUnitId`, le lieu doit être édité en conséquence.
​
- Un développement future ajoutera un règle spécial pour l'édition de lieu etant "porteur" de business unit, voir : https://passculture.atlassian.net/browse/PC-11923
​
> (PC-11480) API: update venue BusinessUnitId

- api/src/pcapi/admin/custom_views/suspend_fraudulent_users_by_ids.py
- api/src/pcapi/domain/admin_emails.py
- api/src/pcapi/templates/admin/suspend_fraudulent_users_by_user_ids.html
- api/src/pcapi/templates/mails/suspend_fraudulent_beneficiary_by_ids_notification_email.html
- api/src/pcapi/utils/mailing.py
- api/src/pcapi/workers/suspend_fraudulent_beneficiary_users_by_ids_job.py
- api/tests/admin/custom_views/suspend_fraudulent_users_by_ids_test.py
- api/tests/domain/admin_emails_test.py
- api/tests/workers/suspend_fraudulent_beneficiary_users_by_ids_job_test.py
Résolution du problème de timeout lors de la suspension de plusieurs utilisateurs via ID sur FA.
- Lancer la suspension en asynchrone sur la `low_queue`
- Envoi d'un mail récapitulatif à la fin de l'opération.
​
> (PC-11486): [API][FA] async suspend fraudulent users by ids

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venue_types.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11645
Réparer la sandbox qui créait des lieux sans `venueTypeCode`. Tous les lieux avaient donc la valeur par défaut : **OTHER**.
​
`venueTypeCode` et `venueTypeId` (référence à une entrée de la table `venue_type`) cohabitent encore. Il reste un ou deux tickets en stock pour couper complètement `venueTypeId`.
> (PC-11645) fix:sandbox: set venueTypeCode

- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/users/external/educonnect/api.py
- api/src/pcapi/core/users/external/educonnect/models.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12077
Côté EduconnectContent, je laisse les champs en Optional vu qu'on a déjà des données en base sans le `school_uai`
> (PC-12077) Save school_uai in EduconnectContent

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/subscription/api.py
- api/tests/connectors/beneficiaries/ubble_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12155
Supprimer le champs qui est configuré en dur dans le Dashboard UBBLE, et non nécessaire ici
> [PC-12155][api] Suppression du champs face-required dans les requêtes d'Ubble

- api/src/pcapi/routes/native/v1/account.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12183
Ajout de log pour `user.id` et `sessionId` après un profiling
```py
logger.info(
"Success when profiling user: returned userdata %r",
profiling_infos.dict(),
extra={"sessionId": body.sessionId},
)
```
​
> (PC-12183)(Backend) Added logging in user profiling

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/admin_user_view.py
- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
- api/src/pcapi/admin/custom_views/pro_user_view.py
- api/src/pcapi/alembic/versions/20211206T090159_3b2ea23b8cf0_add_comment_to_users.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11982
En tant que contrôleur de la fraude
J'aimerais ajouter un commentaire dans le profil utilisateur 
Afin d’avoir de la visibilité sur les motifs de blocage ou autres informations pertinentes sur le profil du demandeur 
- Ajout d’un champs “Commentaire” sur le modèle User
- Rendre le champs éditable dans l’admin qu’aux super admins
- Activer la vue détails sur chaque onglet utilisateur
- Ajouter le champs détails dans chaque vue utilisateur, ainsi que dans la page Support > Beneficiaires​
> (pc-11982)(API)(FA) Add Comment to Detail View

- pro/src/components/pages/Home/Offerers/OffererDetails.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11877
Ajout d'un espace entre le nom de la rue et le code postal
> (PC-11877)[PRO] Add blank space between address and postalCode in OffererDetails

- pro/src/components/pages/Offers/Offers/SearchFilters/SearchFilters.jsx
- pro/src/components/pages/Offers/Offers/__specs__/Offers.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12114
Afficher seulement les catégories sélectionnables  dans le filtre 'Catégories' sur la page des offres
> (PC-12114): [PRO] Offers serachFilters: check if category isSelectable

- api/src/pcapi/routes/error_handlers/bookings_error_handlers.py
Cf cette erreur sur sentry : https://sentry.internal-passculture.app/organizations/sentry/issues/238571
> (PC-11730) Catch OfferCategoryNotBookableByUser exception for webapp booking route

- api/src/pcapi/admin/custom_views/suspend_fraudulent_users_by_ids.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11486
Pour les logiciels de tableur qui créent un fichier csv avec extension en majuscule
> (PC-11486)[API][FA] suspend fraudulent users by ids: convert file extention to lower case before check allowed file

- api/src/pcapi/admin/custom_views/booking_view.py
- api/src/pcapi/core/bookings/factories.py
- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/templates/admin/booking.html
- api/tests/admin/custom_views/booking_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11739
Permettre aux admins de dés-annuler une réservation portant sur une offre éducationnelle, via la BookingView de FA
- Adaptation de la query
- Adaptation du booking.html
- Ajout d'un test
​
​
> (PC-11739)[api]: allow educaitonal booking uncancelling through FA

- api/src/pcapi/core/mails/transactional/send_transactional_email.py
- api/src/pcapi/core/users/external/sendinblue.py
Sentry remonte bien les erreurs Sendinblue. Cependant, elles sont groupées dans la même issue sentry alors qu’elles peuvent être de nature différentes :
Exemple ici une [erreur 500](https://sentry.internal-passculture.app/organizations/sentry/issues/237466/events/5e986b11c6c04be59a976acdd57124a3/?environment=production&project=5&query=sendinblue&statsPeriod=14d)
Ici une [erreur 503](https://sentry.internal-passculture.app/organizations/sentry/issues/237466/events/994cddbc844c4a3cadaf2199e8708974/?environment=production&project=5&query=sendinblue&statsPeriod=14d)
On va donc utiliser un f-string pour différencier par status code `logger.error(f"Exception when calling SMTPApi->send_transac_email with status={e.status}")`
> (PC-10848) Add status in error log message to separate exceptions types in sentry

- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/tests/routes/pro/get_offerer_test.py
- pro/src/components/pages/Home/Venues/Venue.jsx
- pro/src/components/pages/Home/Venues/Venue.scss
- pro/src/components/pages/Home/Venues/VenueLegacy.jsx
- pro/src/components/pages/Home/Venues/VenueList.jsx
- pro/src/components/pages/Home/Venues/__specs__/Venue.spec.jsx
- pro/src/components/pages/Home/Venues/__specs__/VenueLegacy.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9868
Ajout d'un bouton "Ajouter un RIB" au niveau des lieux non rattachés à une business unit.
> (PC-9868)[API][PRO] Adding button add bank information for venues on homepage

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
During the initialization phase, some business units will be created
as "empty shells" that do not have any SIRET until validated by the
offerer. Venues may be changed to link to a new business unit (with a
SIRET). If we price bookings related to the "empty shell" business
unit, we'll have a problem when we try to generate cashflows. We'd
rather not price those bookings in the first place.
> [api][finance] Do not price bookings whose business unit don't have a SIRET

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/constants.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/core/users/utils.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/core/fraud/test_api.py
- api/tests/core/users/test_api.py
- api/tests/core/users/test_models.py
- api/tests/core/users/test_users_sql_entity.py
- api/tests/core/users/test_utils.py
- api/tests/routes/adage_iframe/utils_create_test_token.py
- api/tests/routes/native/v1/account_test.py
- api/tests/tasks/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11807
Le but est de lisser le nombre d'utilisateurs éligibles sur le mois de janvier 2022.
A scaling phase is planned where users will become eligible after UNDERAGE_GENERALISATION_OPENING_DATETIMES_BY_AGE.
However, as the legal opening day is on january 3rd 2022, if user's birthday happens between these dates, we let it enjoy a credit as soon as possible because otherwise it would not be given.
L'éligibilité se base maintenant sur `eligibility_start_datetime` / `eligibility_end_datetime`
On change aussi la règle pour la date de fin d'éligibilité. Avant, pour un 15-17, on considérait que c'était le jour de ses 18 ans. Maintenant, on considère qu'il est éligible en continu sur les phases 15-17 et 18. La date de fin …
> (PC-11807) Compute eligibility start datetime with generalisation rules

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
…
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12111
Bloquer toute demande d'identification Ubble pour un jeune qui a déjà demandé une première identification Ubble, sauf si celle-ci a été annulée (retour "aborted" de Ubble).
Un état CANCELED a été ajouté pour ne pas rester en PENDING dans notre modèle.
> (PC-12111) api: Block Ubble after identification has already been tried once

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/users/api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12197
Accepter des `registration_datetime` vides de DMS
> [PC-12197] handle dms registration with no registration date

- api/src/pcapi/core/users/constants.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11987
En tant que contrôleur de la fraudeJ'aimerais ajouter un motif de suspension mieux défini sur le profil utilisateur dans FAAfin d’avoir un suivi précis sur les raisons de blocage et des statistiques 
- Sur FA, lorsque le compte utilisateur (Jeune, Pro, GP) est suspendu, on affiche la liste déroulante des raisons de suspension qui suit (dans l’ordre de la liste, et en remplacement da la liste actuelle) : 
- Fraude faux document
- Fraude revente produit
- Fraude revente pass
- Fraude usurpation
- Fraude suspicion
- Fraude doublon
- Fraude hacking
- Fraude annulation réservation
- Fin de contrat
- Fin d'éligibilité
- Demande de l'utilisateur
- Fraude PRO usurpation
- Fraude PRO création
- Structure définitivement …
> (11987)(API)(FA) Fix Suspension Reason Choices Order

- api/src/pcapi/admin/custom_views/admin_user_view.py
- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
- api/src/pcapi/admin/custom_views/partner_user_view.py
- api/src/pcapi/admin/custom_views/pro_user_view.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11982
En tant que contrôleur de la fraude
J'aimerais ajouter un commentaire dans le profil utilisateur 
Afin d’avoir de la visibilité sur les motifs de blocage ou autres informations pertinentes sur le profil du demandeur 
- Ajout d’un champs “Commentaire” sur le modèle User
- Rendre le champs éditable dans l’admin qu’aux super admins
- Activer la vue détails sur chaque onglet utilisateur
- Ajouter le champs détails dans chaque vue utilisateur, ainsi que dans la page Support > Beneficiaires​
> (11982)(API)(FA) Add comment view for partners

- api/src/pcapi/core/fraud/api.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12111
Le cas BeneficiaryFraudCheck.status vide (null dans la base de données) n'était pas pris en compte lorsqu'on vérifie si un check a déjà été fait. Pour Ubble il ne devrait cependant pas être vide (en cours de correction dans une autre PR)
​
> (PC-12111) api: Fix id check already performed when BeneficiaryFraudCheck.status is null

- api/src/pcapi/core/subscription/school_types.py
- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11900
Typer correctement les response types du back pour que le front puisse générer les types TS sans erreurs et autres incongruitées
- Pour un Enum {clef: string_value}, les clefs sont typées comme ENUM, les values comme string
​
> [PC-11900] fix api contract types

- api/src/pcapi/admin/custom_views/mixins/suspension_mixin.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11987
En tant que contrôleur de la fraudeJ'aimerais ajouter un motif de suspension mieux défini sur le profil utilisateur dans FAAfin d’avoir un suivi précis sur les raisons de blocage et des statistiques 
- Sur FA, lorsque le compte utilisateur (Jeune, Pro, GP) est suspendu, on affiche la liste déroulante des raisons de suspension qui suit (dans l’ordre de la liste, et en remplacement da la liste actuelle) : 
- Fraude faux document
- Fraude revente produit
- Fraude revente pass
- Fraude usurpation
- Fraude suspicion
- Fraude doublon
- Fraude hacking
- Fraude annulation réservation
- Fin de contrat
- Fin d'éligibilité
- Demande de l'utilisateur
- Fraude PRO usurpation
- Fraude PRO création
- Structure définitivement …
> (pc-11987)(API)(FA) Fix Suspension Reason display if None

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/native/v1/subscription_test.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11947
Dans le nouveau parcours, la route `subscription/profile` est appelée *avant* la vérification de l'identité.
Du coup on peut brûler le hack qui consistait à passer le `hasCompletedIdCheck`.
Et doit le brûler car le ticket des nextSteps (PC-11947) était KO : on ne renvoyait pas nextStep = IdentityCheck dès lors que la route `subscription/profile` avait été appelée.
Autre conséquence : il faut activer le compte bénéficiaire juste après avoir fait educonnect. Plus tard, on attendra une autre étape qui consiste à la confirmation sur l'honneur que les données indiquées sont exactes.
Cela résout un autre bug : 
- educonnect réussi
- enregistrement INE hash, prénom, nom sur l'utilisateur
- l'utilisateur ne remplit pas …
> (PC-11947) Stop updating hasCompletedIdCheck in new profile completion route

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/repository.py
- api/tests/core/offers/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12061
Make the offer view great again.
Permettre à la vue des offres de répondre rapidement même en l'absence de filtres et/ou avec des filtres trop larges.
​
In order to order the offer list the database had to scan the
full list of possible offers, order them and only then limit the
count to a limited numbers.
Since the offers number is quite impressive for some offerer the
associated route would time out.
We now return an unordered list of offers and only order them
whenever the offer count is lower than the requested limit.
En staging:
- avec un utilisateur d'une grosse structure, sur la page des offres sans filtres:
- avant: Elapsed time: 386.0754 seconds
- après: …
> (PC-12061) improve PRO offer page response time

- pro/src/core/OfferEducational/adapters/getCategoriesAdapter.ts
- pro/src/core/OfferEducational/adapters/getOfferAdapter.ts
- pro/src/core/OfferEducational/adapters/getOfferersAdapter.ts
- pro/src/core/OfferEducational/types.ts
- pro/src/custom_types/adapters.d.ts
- pro/src/routes/OfferEducationalCreation/adapters/getIsOffererEligibleToEducationalOfferAdapter.ts
- pro/src/routes/OfferEducationalCreation/adapters/postOfferAdapter.ts
- pro/src/routes/OfferEducationalEdition/OfferEducationalEdition.tsx
- pro/src/routes/OfferEducationalEdition/adapters/patchOfferAdapter.ts
- pro/src/routes/OfferEducationalStockCreation/adapters/postEducationalStock.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12269
Améliorer le typage de l'adapter pour différencier le typage d'erreur et de succès pour ne pas avoir à caster les types après vérification de la valeur de `isOk`
- Création de 2 types générique de succès et de failure
- Modification du type de retour d'Adapter -> Promise<Failure | success>
- Mise à jour des utilisation d'adapter dans le code
​
​
> (PC-12269)[PRO] Improve adapter typing

- pro/src/components/pages/Offers/Offers/ActionsBar/__specs__/ActionsBar.spec.jsx
- pro/src/components/pages/Offers/Offers/Offers.jsx
- pro/src/components/pages/Offers/Offers/__specs__/Offers.spec.jsx
- pro/src/components/pages/Offers/Offers/_constants.js
- pro/src/components/pages/Offers/domain/getOffersCountToDisplay.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12216
Augmentation du seuil limite du nombre d'offres affichées à 500
Ajout d'un message plus clair si les filtres ne sont pas assez sélectifs.
> [PC-12216][PRO] increase max offer limit to 500 offers

- api/src/pcapi/core/bookings/repository.py
- api/tests/core/bookings/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12266
Ne pas montrer les contre-marques pour les biens culturels réservés.
> [PC-12266][API] Don't show tokens for non-event booked goods

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/fraud/api/ubble.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models/__init__.py
- api/src/pcapi/core/fraud/models/ubble.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/messages.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/models/beneficiary_import.py
- api/src/pcapi/routes/external/users_subscription.py
- api/src/pcapi/scripts/beneficiary/import_dms_users.py
- api/src/pcapi/use_cases/create_beneficiary_from_application.py
- api/src/pcapi/validation/routes/ubble.py
- api/tests/connectors/beneficiaries/ubble_fixtures.py
- api/tests/connectors/beneficiaries/ubble_test.py
- api/tests/core/fraud/test_factories.py
- api/tests/core/subscription/test_api.py
- api/tests/core/subscription/test_factories.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11705
Passer l'utilisateur en bénéficiaire quand celui-ci a reussi sa vérification d'identité via Ubble.
- généralisation des fonctions de vérification et validation de l'utilisateur utilisé pour DMS pour pouvoir les utiliser aussi avec Ubble
​
- migration du code spécifique Ubble dans des modules `ubble`, là ou c'était pertinent
- [ x PR : (PC-XXX) Description rapide de l' US
> [PC-11705] make user beneficiary on valid Ubble check

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/offers/utils.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/stocks.py
- api/src/pcapi/routes/serialization/stock_serialize.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/edit_educational_offer_test.py
- api/tests/routes/pro/edit_educational_stock_test.py
- api/tests/routes/pro/post_educational_stock_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11581
Implémenter l'édition des stocks pour les offres éducationnelles dans le cadre de la création d'offres v0.1
Nouvelle route `/stocks/educational/<stock_id>` dans `routes/pro/stocks`
​
N/A
​
> (PC-11581)[api] edit educational stock

- api/src/pcapi/admin/custom_views/support_view.py
- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models/__init__.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/src/pcapi/scripts/beneficiary/import_dms_users.py
- api/tests/admin/custom_views/support_view_test.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
- api/tests/routes/saml/educonnect_test.py
- api/tests/routes/webapp/phone_validation_test.py
- api/tests/routes/webapp/post_id_check_application_update_test.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
- api/tests/use_cases/create_beneficiary_from_application_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12240
Aujourd'hui, l'étape de confirmation sur l'honneur qui arrive à la fin du parcours n'est pas prise en compte côté back.
Le but est d'en faire une étape obligatoire.
Commits à lire séparément.
> (PC-12240) Add honor mandatory statement step

- api/requirements.txt
lxml 4.6.5 and 4.7.1 have been released with a security fix:
https://lxml.de/4.7/changes-4.7.1.html#id3
Our only direct use of lxml is to generate banking XML files
(which we actually don't send to the bank). Our indirect uses are less
clear. I don't think that we could be affected by the security bug.
Nevertheless, it looks easy enough to be up-to-date.
> [api][requirements] Bump version of lxml

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/messages.py
- api/src/pcapi/core/subscription/models.py
- api/tests/core/subscription/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11728
Ajouter les messages de com in app sur le parcours d'inscription Ubble
- Ajout d'un type d'icône CTA External pour les liens de type externes
​
​
> [PC-11728][api] add subscription message for Ubble

- pro/src/components/hooks/useNotification.js
- pro/src/routes/OfferEducationalStockCreation/OfferEducationalStockCreation.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12317
Eviter les appels répétitifs à /offers/offerid
- Le hook useNotification provoquait trop de rerender à cause de sa dépendance dans le useEffect. Pour éviter ca, j'ai wrappé la fonction utilisée dans le useNptification dans un useCallback pour mémoiser cette fonction et éviter qu'elle change de référence
- Dans le useEffect, on ne fait l'appel à getOfferAdapter que si on n'a pas déjà fait cet appel (utilisation du state `isReady`, setté à true après l'appel)
​
> (PC-12317) do not call /offers/offerid when offer is set

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
They are not included in the "old-style" CSV file, there is no reason
to include them in the "new-style" one.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11623
> [PC-11623][api][finance] Exclude free bookings from payments CSV file

- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11121
Lié au ticket 11121 car il y a un bug avec Educonnect : on renvoie toujours nextStep = "IDENTITY_CHECK" même si un dossier educonnect a été déposé.
​
> (PC-11121) Fix next step after educonnect success

- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12319
Renommer la route pour plus de cohérence avec ce qu'elle expose
​
​
> (PC-12319) refactor: Rename /school_types route to profile_options

- api/src/pcapi/core/users/models.py
- api/tests/core/users/test_models.py
SQLAlchemy events are quite ambigous, and callback does not have the same
signature.
This ensure we carefully loads data from guessed kwargs when creating an ORM object
(such as init event) from a dict.
On a load event (when data is fetched from the database), the callback signature slightly differs
but we do not need to look for data : the object is already filled from a row result.
Corriger l'initialisation de la machine a état de l'attribut SubscriptionState
dans le cas ou on récupère des données "User" qui ne sont pas dans la session.
le bug n'a pu être déduit facilement dans les tests: la session SQLA masquait le pb
Le test utilise une 2e session pour éviter qu'une requete get() ne requete le cache
> (BSR) Fix user statemachine initialization

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/support_view.py
- api/src/pcapi/alembic/versions/20211210T142011_608d334310cd_add_fraud_check_eligibility_type.py
- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/fraud/api/ubble.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models/__init__.py
- api/src/pcapi/core/fraud/repository.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/infrastructure/repository/beneficiary/beneficiary_sql_repository.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/src/pcapi/scripts/beneficiary/import_dms_users.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/tests/admin/custom_views/support_view_test.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
- api/tests/use_cases/create_beneficiary_from_application_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12249
Associer un eligibilityType au BeneficiaryFraudCheck afin de pouvoir retrouver si une identification Ubble (ou autre) était faite pour le crédit 15-17 ou pour le crédit de 300€.
Stratégie tech : voir ticket Jira
​
Bien testé par les tests unitaires, mais mieux vaut re-tester toutes les procédures d'inscription une fois sur testing !
​
> (PC-12249) api: Add eligibilityType to BeneficiaryFraudCheck

- api/src/pcapi/core/providers/api.py
Corriger le bug https://sentry.internal-passculture.app/organizations/sentry/issues/205917/
Le cas `stock.quantity = None` n'était pas géré.
> (BSR) Fix int / None comparison in stock_synchronization

- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12219
Ajout d'un champs 'hasIdentityCheckPending' dans le résultat de la route /subscription/next_step
pour aider l'application lorsque le retour d'Ubble n'est pas encore fait
> [pc-12219][api] Add ''hasIdentityCheckPending' in NextStep

- api/src/pcapi/core/fraud/models/ubble.py
- api/tests/core/fraud/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12342
Corriger le sentry : notre base de code est "timezone non-aware" ou "sans timezone"
On s'assure que l'ensemble des données utilisées pour vérifier l'eligibilité utilise bien un "datetime naîf"
et on corrige la sortie pour Ubble.
> [pc-12342][api] Ensure get_registration_datetime is datetime naive

- api/src/pcapi/routes/saml/educonnect.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12346
Pour que le front puisse logout l'utilisateur en cas d'erreur
​
​
> (PC-12346) Add logout url in educonnect error redirections

- api/src/pcapi/core/subscription/messages.py
- api/tests/core/subscription/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12353
Corriger le message inapp de redirection vers DMS : il manquait le titre du CTA
pour voir afficher le lien
> [pc-12353][api] Add missing cta title in dms redirection

- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/fraud/models/__init__.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12350
- Gérer le cas de User Profiling appelé sans Phone Validation (FF ENABLE_PHONE_VALIDATION désactivé)
- Ajouter un log pour mieux suivre les "next steps" renvoyées au front pour l'inscription
- Garder le status dans BeneficiaryFraudCheck pour un User Profiling, pour visualisation dans FA notamment
​
​
> Pc 12350 invalid data received from userprofiling

- api/src/pcapi/models/feature.py
- api/src/pcapi/scheduled_tasks/clock.py
We may not want the very first cashflow/files generation to be
automatically run by the cron job.
> [bsr][api][finance] Add feature flag for "generate_cashflows_and_payment_files" cron

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/tests/core/offers/test_api.py
- api/tests/core/offers/test_validation.py
When a reimbursement rule exists for an offer, we disallowed to change
the price of a stock. Now we also disallow to *create* a new stock
with a price that is different from exiting stocks.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12355
> [PC-12355][api][offers] Disallow stock creation with incoherent stock price if reimbursement rule exists

- api/src/pcapi/models/feature.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12022
Désactive le `needsToFillCulturalSurvey` lorsque l'utilisateur n'est pas bénéficiaire ou lorsque le feature flag est désactivé
- Renommage de la description du feature flag pour un texte plus concis fourni par Mathieu
> (PC-12022) add feature flag enable cultural survey

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/routes/external/users_subscription.py
- api/tests/connectors/beneficiaries/ubble_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12371
Besoin de logs pour comprendre les bugs rencontrés dans le parcours Ubble
Log au démarrage de l'identification, log à chaque notification de Ubble
​
> (PC-12371) api: Add logs to follow and debug Ubble identifications

- api/tests/routes/native/v1/subscription_test.py
The factory UserProfiling is very unstable leading to possible
flacky test: the fonction verifies the potential risk of a user,
depending on the userprofiling response.
This commit ensure the userprofilig response is not risky
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12226
Correction d'un test flacky lorsque la factory retourne un risque potentiel sur le profil utilisateur
> [pc-12226][api] Use Valid userprofiling data

- api/src/pcapi/admin/custom_views/support_view.py
- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/exceptions.py
- api/src/pcapi/core/users/exceptions.py
- api/src/pcapi/models/beneficiary_import.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/routes/saml/educonnect_test.py
Bug : un utilisateur de 16 ans se voit attribuer un crédit de 18 ans
Comment reproduire (reproduit dans les tests):
- `user.dateOfBirth` déclaré à l'inscription de façon à être éligible
- date de naissance éduconnect avec un âge éligible **mais** avant la généralisation (ouverture 1er janvier 2022)
Pourquoi ? 2 problèmes : 
- `user.is_eligible_for_beneficiary_upgrade(eligibility)`
si eligibility est null (qui se base sur la date de naissance du dossier), on va prendre user.eligibility qui peut ne pas être null !
Donc on réussit le check de fraud `_check_user_not_already_beneficiary`
(que je vais renommer check_user_eligibility ) et on enregistre un eligibilityTYpe null sur le FraudCheck
- ensuite on enregistre un …
> (PC-12369) Add check on eligibility type before creating educonnect beneficiary import

- webapp/scripts/build_redirects.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12389
Exposé `/version.txt` lorsque le la redirection v1 to v2 est ON
- Ajout d'un redirect rule netlify
​
​
> [PC-12389] (WebApp) expose version.txt when v1 to v2 redirect is on

- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/domain/beneficiary_pre_subscription/validator.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/routes/native/v1/subscription.py
The code was misleading and had lead to bugs. Now the caller of the function knows exactly what eligibility will be used
Cf bug PC-12369
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12369
> (PC-12369) Set eligibility property as required in is_eligible_for_bneficiary_upgrade

- pro/src/screens/OfferType/OfferTypeButton/OfferTypeButton.module.scss
rendre les boutons de choix du type d'offre accessibles au clavier
- supression du display: none sur les radio button (qui empêchent la sélection clavier)
- ajout d'une bordure au focus pour que le focus soit visible par l'utilisateur
​
https://user-images.githubusercontent.com/35567446/146741904-10498538-a5e3-443b-ba64-73de42a9e3d7.mov
> (PC-12396) make offer type screen accessible

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreation.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreationContainer.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/__specs__/VenueCreation.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/__specs__/VenueCreationContainer.spec.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/BankInformationFields/BusinessUnitFields.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/utils/formatVenuePayload.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11477
Ajouter la section business unit au formulaire de création de lieu lorsque le FF ENFORCE_BANK_INFORMATION_WITH_SIRET est activé
​
> (PC-11477)[PRO] venue creation: add business unit fields

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
We used to calculate the revenue per business unit, but that was a
misunderstanding: it must be calculated per SIRET (see a9de4222ebe1).
I forgot to update `_delete_dependent_pricings()` accordingly.
> [api][finance] Make _delete_dependent_pricings use SIRET, not the business unit

- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/tests/core/fraud/test_api.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12373
Reprendre un workflow d'identification si l'utiulisateur s'est arrêté et que celle-ci n'est pas marquee
comme annulée côté UBBLE
> Permettre de reprendre une identification UBBLE qui n'a pas pu être terminée

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/api.py
- api/tests/core/users/test_api.py
It must not depend on the date where it is computed, which was the case because the result was relying on a "current" age.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12414
Corriger le bug qui survient quand :
- la généralisation est activée (ENABLE_UNDERAGE_GENERALISATION)
- le dossier est déposé à 17 ans 
- le dossier est validé à 18 ans 
- l’anniversaire tombe pendant la phase de généralisation
`eligibility_start_datetime` calculé **avant** l'anniversaire de 18ans donnait le 3 janvier (ouverture)
`eligibility_start_datetime` calculé **après** l'anniversaire de 18ans donnait l'anniv de 18 ans
Cette donnée ne doit pas dépendre de la date à laquelle on le calcule
​
- Exemples : nettoyage de code, utilisation de …
> (PC-12414) Fix eligibility start datetime

- api/src/pcapi/core/finance/models.py
Corriger la définition de la colonne `status` du modèle `BusinessUnit`.
En effet, la génération automatique de migration par alembic détectait une incohérence et proposait :
```
def upgrade():
op.alter_column('business_unit', 'status',
existing_type=sa.TEXT(),
server_default=None,
existing_nullable=False)
```
- Remplacer `default` par `server_default`
- Fournir la valeur de l'enum, afin qu'alembic sache définir la bonne valeur de type `str`
> [api][alembic] Fix business_unit.status column definition

- api/src/pcapi/admin/custom_views/user_email_history_view.py
- api/src/pcapi/admin/install.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/email/update.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12099
Ajout d'une interface utilisateur dans l'admin pour afficher l'historique des changements d'adresse email
Dans l'onglet `Support`, dans la page de détail d'un bénéficiaire, lorsqu'il y a eu des changements d'adresse email et que l'user connecté est super admin
Dans l'onglet `Support`, dans la page de détail d'un bénéficiaire, lorsqu'il y a eu des changements d'adresse email et que l'user connecté est seulement admin
Dans l'onglet `Support`, dans la page de détail d'un bénéficiaire, lorsqu'il **n'y a pas** eu de changements d'adresse email
Dans l'onglet `Utilisateurs`, nouvelle page dédiée à l'historique de changements d'adresse email
> (PC-12099) email history UI

- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/tests/routes/pro/get_educational_offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12425
Côté front, on affiche le nom du lieu soit en utilisant la valeur publicName soit en utilisant la valeur name de l'entité Venue. En testing, tous les publicName étaient renseignés donc on n'a pas vu le bug, mais en staging, on fallback sur le name, or celui-ci n'était pas remonté dans la réponse de l'API
> (PC-12425)[PRO] add venue name in educational offerers response

- pro/src/routes/OfferEducationalConfirmation/OfferEducationalConfirmation.tsx
- pro/src/routes/OfferEducationalStockCreation/OfferEducationalStockCreation.tsx
- pro/src/screens/OfferEducationalConfirmation/OfferEducationalConfirmation.tsx
- pro/src/utils/routes_map.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12212
Informer l'utilisateur sur le statut de son offre après sa création. Parfois, celle-ci peut-être PENDING si elle doit passer certains contrôle de fraude.
- Ajout de l'offerId dans l'url de la page de confirmation
- Récupération du statut de l'offre et affichage du screen avec des données différentes suivant le statut
​
> (PC-12212)[PRO] update confirmation page with pending status

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/DeleteBusinessUnitConfirmationDialog/DeleteBusinessUnitConfirmationDialog.tsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/__specs__/VenueEdition.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/BankInformationFields/BusinessUnitFields.jsx
- pro/src/styles/components/pages/Offerer/BankInformation/_BankInformation.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12188
Remettre la valeur précédente à l'input informations bancaires sur le formulaire d'édition de lieu quand l'utilisateur annule ses modifications suite à la pop up. Mise à jour de wording et css.
> (PC-12188)[PRO]: Reset bank info input value on form submit cancellation, fix css & wording

- api/src/pcapi/routes/native/v1/serialization/offers.py
- api/tests/routes/native/v1/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11880
L'info est déjà présente sur le stock et permet au front de gérer l'affichage du bouton "Confirmer ma réservation"
On rajoute l'info sur l'offre pour que le front gère aussi l'affichage du premier CTA "Réserver cette offre" qui arrive plus en amont.
> (PC-11880) Add isForbiddenToUnderage in offer response

- api/tests/core/offers/test_repository.py
Prior to #617 the results were sorted whenever they were over the
limit. Since it had an impact on performances, the results are not
sorted any longer which means that from time to time the test would
fail.
Since the test is about making sure some offers are correctly
included, I don't see any reason not to increase the result limit
to include all the results.
> [PC-12061][API] fix flaky test

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
Bookings that have been used before 2022 will be priced manually.
> [bsr][api][finance] Restrict `price_bookings` cron job to year 2022

- api/src/pcapi/core/fraud/api/__init__.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models/__init__.py
- api/tests/connectors/beneficiaries/beneficiary_jouve_repository_test.py
- api/tests/core/fraud/test_api.py
- api/tests/use_cases/create_beneficiary_from_application_test.py
Résolution de 2 problèmes :
- Bug on flask admin : the operators cannot see the button 'Soumettre une revue manuelle' because old fraud_checks were created without eligibiltyType
- Enregistrer correctement le `registrationDate` des dossier jouve n’est pas enregistré, car on n’a pas le bon format de date
jouve envoie : ‘12/22/2021 5:00 PM’
nous on attend : ‘12/22/2021 17:00’
> (PC-12466) Fix ability for admin to submit a review on jouve cases

- api/src/pcapi/routes/serialization/finance_serialize.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12475
business unit may be created before the bic/iban are available.
This is required to be able to follow up a bic/iban procedure.
> [PC-12475] fix optional bic/iban on business unit serialization

- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/mails/transactional/users/subscription_document_error_email.py
- api/tests/core/mails/transactional/users/subscription_document_error_email_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12510
déclenche l'envoi d'un email transactionnel lorsque une erreur d'information d'inscription est remontée à la fonction send_subscription_document_error_email avec le code erreur : “information-error”
N/A
​
N/A
> (PC-12510)[API]sendinblue-transac-email-beneficiary-subscription-info-error

- api/src/pcapi/core/bookings/repository.py
- api/tests/core/bookings/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12483
Certaines réservations eac en statut "préréservé" remontée en statut "confirmé" dans le csv des réservations.
En effet, la détermination des statuts dans la construction du csv ne tenait pas compte du cas spécial pour les réservations eac : 
- Pour les réservations individuelles, l'une d'entre elles à le statut "confirmé" dès lors que la date limite d'annulation est dépassée
- Pour les réservations eac, ceci est vrai uniquement si la réservation a été validée par le chef d'établissement. Dans le cas contraire, son statut reste en "préréservé" même après la date limite d'annulation
Adaptation de la logique dans la fonction `_get_booking_status`
​
J'ai ajouté une bonne batterie de tests spécifiques aux statuts, …
> (PC-12483)[api]: correct wrong status in csv that lists bookings

- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/mails/transactional/users/anniversary_to_newly_eligible_user.py
- api/src/pcapi/core/users/repository.py
- api/src/pcapi/domain/user_emails.py
- api/src/pcapi/emails/beneficiary_activation.py
- api/src/pcapi/scheduled_tasks/clock.py
- api/src/pcapi/scripts/beneficiary/send_mail_after_idcheck_outage.py
- api/tests/core/mails/transactional/users/anniversary_to_newly_eligible_user_test.py
- api/tests/core/users/test_repository.py
- api/tests/domain/user_emails_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12507
Migration mailjet vers sendinblue : Envoi de mail pour devenir bénéficiaire lorsqu'un utilisateur non bénéficiaire atteint l'age de 18 ans
N/A​
N/A
​
> (PC-12507)[API]feat:sendinblue-transac-email-user-anniversary-age-18

- api/src/pcapi/core/finance/repository.py
- api/src/pcapi/routes/pro/finance.py
- api/tests/core/finance/test_repository.py
- api/tests/routes/pro/get_invoices_test.py
This endpoint does not accept an offerer id anymore. It returns all
invoices that are available to the current user... unless the user is
an admin, in which case they must provide a business unit id to filter
on. We really don't want to return all invoices of all business units
to an admin.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12327
> [PC-12327][api][finance] Adapt /finance/invoices endpoint

- api/src/pcapi/routes/native/v1/serialization/settings.py
- api/src/pcapi/routes/native/v1/settings.py
- api/tests/routes/native/v1/settings_test.py
Pas de ticket
https://github.com/pass-culture/pass-culture-app-native/pull/2405
enlever les champs qui ne sont pas ou plus utilisé par l'app native: `allowIdCheckRegistration`, `depositAmount` et `enableCulturalSurvey`.
C'est possible car on a fait une màj de la version `10166003` et elle n'utilise plus ces champs.
> [API] refactor(settings): remove unused settings fields

- pro/src/components/pages/Home/Offerers/InvalidBusinessUnits.jsx
- pro/src/components/pages/Home/Offerers/MissingBusinessUnits.jsx
- pro/src/components/pages/Home/Offerers/OffererDetails.jsx
- pro/src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx
- pro/src/components/pages/Home/Venues/__specs__/VenueLegacy.spec.jsx
- pro/src/components/pages/Offerers/Offerer/OffererDetails/BankInformation/BankInformation.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12413
Affichage des bandeaux jaunes "Points de remboursement" et "Coordonnées bancaires"
Points de remboursement:
- une business unit avec siret null.
Coordonnées bancaires:
- un lieu qui n'a pas de business unit et a au moins une offre active.
> (PC-12413)[API][PRO] pro homepage display cb alerte

- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/mails/transactional/users/recredit_to_underage_beneficiary.py
- api/src/pcapi/scheduled_tasks/clock.py
- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/core/mails/transactional/users/anniversary_to_newly_eligible_user_test.py
- api/tests/core/mails/transactional/users/recredit_to_underage_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12508
Envoi un email transactionnel par sendinblue 
lorsqu'un bénéficiaire mineur obtient un recredit durant son anniversaire
(exemple: obtention d'un jeune d'un nouveau crédit à 16 ans et 17 ans déclenche l'envoi de cet email)
N/A
​
N/A
> (PC-12508)[API] sendinblue transac email recredit anniversary underage beneficiary

- api/src/pcapi/admin/custom_views/support_view.py
- api/src/pcapi/admin/custom_views/user_email_history_view.py
- api/src/pcapi/core/testing.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/email/repository.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/templates/admin/list_user_email_history.html
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/tests/admin/custom_views/user_email_history_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12112
Permettre à un admin (FA) de valider manuellement une demande de modification d'un email à deux endroits : 
1. sur la page d'index des demandes de modifications ;
2. sur la vue détaillée d'un bénéficiaire, dans la section des modifications d'email.
A chaque fois, le bouton n'apparaît que sur les lignes qui correspondent à un événement `UPDATE_REQUEST`.
On pourrait filtrer encore mieux et ne l'afficher que sur les lignes qui n'ont pas d’événements `VALIDATION` ou `ADMIN_VALIDATION` associés (même utilisateur, mêmes ancienne et nouvelle adresse) mais je n'ai pas trouvé comment passer du SQL à SQLAlchemy / FlaskAdmin 😭 
Une fois l'adresse validée, l'utilisateur est redirigé par défaut sur l'index des demandes de …
> (PC-12112) feat:email_update: add validate button

- api/src/pcapi/routes/saml/educonnect.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12451
Standardiser les url de redirection d'educonnect
​
> [PC-12451][API] educonnect: remove idcheck subpath from error and validation url

- api/src/pcapi/notifications/push/backends/batch.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12026
Normaliser les logs d'erreur du _backend_ Batch afin de faciliter la recherche et l'extraction d'informations, en cas de besoin (api de Batchh h.s. par exemple).
> (PC-12026) logs:batch: normalize batch error logs

- api/src/pcapi/admin/base_configuration.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10114
Lors de l'accès à Flask Admin, si un utilisateur est connecté via le cookie "PRO" et visite la page `/no-user-found`, il recevait une 500.
Désormais, l'utilisateur est redirigé vers la page d'accueil de Flask Admin
- modification des conditions de redirection sur la route `/no-user-found`
​
> (PC-10114) fix no-user-found bug with pro login

- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/tests/routes/pro/get_offerers_test.py
Le endpoint GET /offerers doit renvoyer des id humanisées. 
​
​
> [PRO] (FIX) - humanize offerers id

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/scripts/booking/handle_expired_bookings.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12589
The scheduled tasks was pulling way too many objects from the DB
at once. This is reworked to proceed on a per user basis and
get the associated data for each user.
This is a bit less efficient than using a unique query and yield_per
but the later is much less readable as we'll need to regroup the
objects per user.
​
​
> [PC-12589][API] Fix OOM on scheduled tasks

- api/src/pcapi/core/mails/transactional/users/recredit_to_underage_beneficiary.py
- api/src/pcapi/scheduled_tasks/clock.py
- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/core/mails/transactional/users/recredit_to_underage_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11208
- Corriger le montant recrédité à l'utilisateur dans l'email transactionnel
- Programmer le cron de rechargement des utilisateurs à 7 heure (utc) tous les jours (au lieu de minuit)
> (PC-11208)[API] sendinblue: fix underage recredit transactional email

- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
> [bsr][api][admin] Do not show the user password in details page

- api/src/pcapi/scripts/business_unit/create_bu.py
- api/tests/scripts/business_unit/create_bu_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11636
Correction du nom des points de remboursement invalidé vers : "Point de remboursement #1" (puis \#2, \#3, etc)
> [PC-11636][PRO][API] Business unit script: name

- api/src/pcapi/core/users/repository.py
- api/tests/core/users/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11209
Envoyer le mail de notif des 18 ans à tous les utilisateurs eligibles
​
> (PC-11209)[API] clock: send 18 birthday email to ex underage beneficiary

- pro/src/components/pages/Offerers/Offerer/OffererDetails/BankInformation/BankInformation.jsx
- pro/src/components/pages/Offerers/Offerer/OffererDetails/OffererDetails.jsx
- pro/src/components/pages/Offerers/Offerer/OffererDetails/OffererDetailsContainer.js
- pro/src/components/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.jsx
- pro/src/components/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetailsContainer.spec.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12367
Afficher un bandeau jaune sur la page structure, lorsqu’une structure a au moins un de ses lieux qui contient un point de remboursement invalide.
- Migration de `OffererDetails.jsx` à un composant fonctionnel.
- Migration de redux-saga-data à des appel via pcapi client pour le composant `OffererDetails.jsx`
​
> (PC-12367)[PRO] offerer page: dispaly invalid business unit banner

- pro/src/components/pages/Home/Offerers/OffererDetails.jsx
- pro/src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12649
- Afficher la bannière cordonnées bancaires manquantes seulement si un ou plusieurs lieux physiques n'ont pas de CB
> (PC-12649)[PRO] homepage: display missing bank information banner only for physical venues

- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/routes/pro/patch_educational_offer_test.py
- api/tests/routes/pro/post_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12211
Lors de la création d'offre EAC, il y a des champs obligatoire du formulaire qui sont envoyés et stockés dans un objet `extraData` en base de donnée. Or cet `extraData` est typé comme `Any` donc on n'a pas de moyen de valider si tous les champs obligatoires sont bien présents ou non.
Cette PR a pour but de typer `extraData` pour s'assurer que l'objet soit complet et valide 
- Ajout de classes pour typer `extraData` au moment du `post` et du `patch`
- Ajout de tests
​
> (PC-12211) type extra data when creating and updating educational offer

- api/src/pcapi/scripts/force_19yo_dms_import.py
- api/src/pcapi/scripts/install.py
- api/tests/scripts/force_19_yo_dms_import_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12594
Forcer le passage beneficiaires d'utilisateur qui avaient 18 lors de leur creation de compte
mais dont le delais du traitement DMS a mis trop de temps.
​
​
> [pc-12594][api] add dms script to force 19 yo beneficiaries

- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/core/users/repository.py
- api/src/pcapi/domain/beneficiary_pre_subscription/exceptions.py
- api/src/pcapi/domain/beneficiary_pre_subscription/validator.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/scripts/beneficiary/send_mail_after_idcheck_outage.py
- api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py
- api/tests/core/mails/transactional/users/birthday_to_newly_eligible_user_test.py
- api/tests/core/users/external/external_users_test.py
- api/tests/core/users/test_api.py
- api/tests/domain/beneficiary/beneficiary_pre_subscription_validator_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/authentication_test.py
- api/tests/routes/shared/get_user_profile_test.py
- api/tests/routes/shared/signin_test.py
- api/tests/scripts/batch_update_users_attributes_test.py
- api/tests/scripts/beneficiary/send_mail_after_idcheck_outage_test.py
- api/tests/use_cases/create_beneficiary_from_application_test.py
- api/tests/utils/mailing_test.py
There should be no more postal code validation
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9822
Supprimer le code qui s'occupe de la vérification du code postal de l'utilisateur (éligibilité), puisque cela n'a plus de sens aujourd'hui.
> [API] (PC-9822) rm:account: rm postal code validation

- api/src/pcapi/scripts/business_unit/create_bu.py
- api/src/pcapi/scripts/business_unit/purge_virtual_venue_business_units.py
- api/tests/scripts/business_unit/purge_virtual_venue_business_units_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11636
Une fois le script de migration de business unit executer, nous avions quelques cas qui ne devaient pas exister:
* Un lieu virtuel sans offre ne doit pas avoir de BusinessUnit assignée.
> [PC-11636][API] BusinessUnit script : handle virtual venues

- api/src/pcapi/scripts/business_unit/create_bu.py
- api/src/pcapi/scripts/business_unit/rename_invalid_bu.py
- api/tests/scripts/business_unit/create_bu_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11636
Il y à un gros trou de BusinessUnit non créer en production : 
```sql
SELECT
count(DISTINCT(venue.id))
FROM venue
JOIN offerer ON (offerer.id = venue."managingOffererId")
JOIN bank_information ON (bank_information."offererId" = offerer.id)
WHERE venue."businessUnitId" IS NULL
AND venue.siret IS NULL
AND offerer."isActive"
AND bank_information.status = 'ACCEPTED'
;
-[ RECORD 1 ]
count | 4484
```
Parmis ces 4400 lieu, 680 ont des offres dont 540 ont des offre actives.
Une fois mergé il nous faut rééxécuter en production :
```
create_bu()  # creation de bu manquante
purge_virtual_venue_business_units()  # suppression des liens et business unit inutiles 
rename_invalid_business_unit() # normalisation des nom des …
```
> [PC-11636][API][PRO] missing business unit creation

- api/src/pcapi/core/subscription/transitions.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/models/pc_object.py
- api/tests/core/providers/test_api.py
- api/tests/models/pc_object_test.py
- api/tests/scripts/payment/add_custom_offer_reimbursement_rule_test.py
Lien vers le ticket Jira : [12644](https://passculture.atlassian.net/browse/PC-12644)
Depuis l'ajout de la machine a état sur le modèle utilisateur pour simplifier le parcours d'inscription,
la consommation de la ram a pu augmenter : une machine a état est instancié pour chaque `User`
Le design de la lib transitions permet de n'instancier qu'une seule fois la machine a état et d'ajouter le modele lors du chargement de la donnée depuis la base, et de le supprimer lorsqu'on n'utilise plus le modele User
Problème : la surcharge des méthodes __eq__ et __ne__ empêchent la bonne utilisation de ces deux fonctions d'ajout et de suppression : la machine a état vérifie qu'une instance du modèle n'a pas déjà été ajoutée:
`if mod not in self.models:`
de notre côté, un modele est considéré égal si il …
> [pc-12644][api] Instanciation unique de la machine à état d'inscription

- api/src/pcapi/core/bookings/repository.py
- api/tests/core/bookings/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12607
Ajout d'une colonne "Type d'offre" dans le csv des réservations, afin de pouvoir distinguer entre offres scolaires et grand public
​
​
> (PC-12607)[api] feat(bookings csv) : add offer type column to bookings csv - educational vs. individual

- pro/src/routes/OfferEducationalCreation/adapters/getIsOffererEligibleToEducationalOfferAdapter.ts
- pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12647
Retirer le toaster d'erreur en cas de non éligibilité de l'acteur culturel, car celui-ci porte à confusion --> l'utilisateur a l'impression que le problème vient de pass culture ou d'adage dans tous les cas
- Affichage du toaster uniquement si il y a une erreur du back autre qu'une 404 (qui indique que l'AC n'est pas éligible car non référencé auprès d'adage)
- Suppression du block jaune indiquant que l'utilisateur doit faire une référencement dans le cas de l'affichage du toaster
​
> (PC-12647) remove error toaster on backend error

- pro/src/core/OfferEducational/types.ts
- pro/src/routes/OfferEducationalConfirmation/OfferEducationalConfirmation.tsx
- pro/src/routes/OfferEducationalCreation/OfferEducationalCreation.tsx
- pro/src/screens/OfferEducationalConfirmation/OfferEducationalConfirmation.stories.tsx
- pro/src/screens/OfferEducationalConfirmation/OfferEducationalConfirmation.tsx
- pro/src/screens/OfferEducationalStock/OfferEducationalStock.stories.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12686
Pouvoir créer une nouvelle offre à la fin du parcours de création d'offre collective. 
Le formulaire a besoin de l'id de la structure comme donnée initiale. Celle-ci vient des query params dans l'url, or on ne les fait pas passer sur la page de confirmation, donc quand on clique sur "créer une nouvelle offre" les query params sont vides.
- Un peu de cleaning : suppression des query params qu'on n'utilise pas (sur la page stock et création)
- utilisation du managingOffer.id de l'offre créée pour renseigner la structure dans les query params lorsqu'on veut créer une nouvelle offre
> (PC-12686)[PRO] fix link to create another offer after submitting one

- adage-front/src/app/components/OffersSearch/Offers/Offer.tsx
- adage-front/src/utils/types.ts
- api/src/pcapi/routes/adage_iframe/serialization/offers.py
- api/tests/routes/adage_iframe/get_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12629
Ajouter le nom de la structure à côté du nom du lieu, sous le titre de l'offre sur adage
> (PC-12629)[API+ADAGE] add offerer name next to venue name in adage

- api/requirements.txt
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12688
empècher [pygments de casser pgcli](https://github.com/dbcli/pgcli/issues/1303)
limitation de la version de pygments à 2.11.1
​
nope
​
> [PC-12688][api] chore: limit version of pygments

- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/emails/offerer_expired_bookings.py
- api/src/pcapi/routes/pro/bookings.py
- api/src/pcapi/routes/serialization/bookings_serialize.py
- api/src/pcapi/utils/mailing.py
- api/tests/emails/offer_cancellation_test.py
- api/tests/emails/offerer_expired_bookings_test.py
- api/tests/routes/pro/get_booking_by_token_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12636
Utiliser prénom + nom dans l'affichage de l'utilisateur dans le guichet et les emails.
- modification du nom de la propriété `publicName` en `userName`
- édition de son résultat​
​
**Bénéficiaire:**
**Guichet existant:**
**Guichet avec correctif:**
> (PC-12636)[api][bookings] use firstName and lastName

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220110T114500_7b8966ff7913_add_invoice_models.py
- api/src/pcapi/alembic/versions/20220110T155918_d71dd05eae76_edit_invoice_url.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/conf.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/finance/utils.py
- api/src/pcapi/core/payments/models.py
- api/src/pcapi/domain/reimbursement.py
- api/src/pcapi/flask_app.py
- api/src/pcapi/templates/invoices/invoice.html
- api/tests/conftest.py
- api/tests/core/finance/test_api.py
- api/tests/core/finance/test_utils.py
- api/tests/domain/reimbursement_test.py
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11624
Créer des justificatifs de remboursement en DB, générer des PDF, les stocker.
- Ajout de fonctions d'API
- Ajout d'un template temporaire Jinja2 pour la génération de PDF avec weasyprint
- Stockage du PDF généré via le backend de stockage défini pour cet environnement
​
> (PC-11624) [api][finance] Generate and store Invoices

- .github/workflows/ping_data_team.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12735
Ceci est un POC qui sera challengé par l'équipe data s'il fonctionne.
Le but est de pinger slack pour chaque nouvelle pr sur l'api qui modifier la db : ajout, modification ou suppression d'une migration.
Avec github action
​
​
> (PC-12735) Add github workflow to ping slack on every db scheme change

- api/src/pcapi/admin/custom_views/support_view.py
- api/src/pcapi/admin/install.py
- api/src/pcapi/admin/templating.py
- api/src/pcapi/core/fraud/repository.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/models.py
- api/src/pcapi/static/css/support_beneficiary_details.css
- api/src/pcapi/templates/admin/support_beneficiary_details.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12583
- Ajout de fonction dans subsxcription_api pour récupérer des "SubscriptionItems"
- TODO : il faudra utiliser ces fonctions pour calculer le next SubscriptionStep
​
> (PC-12583) Add subscription steps visualisation in admin

- api/Dockerfile
Correction de l'erreur au lancement de la sandbox dans les jobs tests-pro-e2e
- Installation de `libharfbuzz0b` lors de la création de l'image Docker `pc-flask`
​
- Documentation d'installation de weasyprint sur Ubuntu >20.4: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#ubuntu-20-04
​
> (BSR) [api][Dockerfile] add missing library during image build

- api/src/pcapi/domain/show_types.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11970
Résoudre une erreur sentry sur les showType
le fichier showType avait été modifié sur pro mais pas sur l'api, j'ai donc repercuté les changements
​
​
> (PC-11970)[API] fix error on showType

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/educonnect/api.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/src/pcapi/scripts/beneficiary/import_dms_users.py
- api/tests/core/subscription/test_api.py
- api/tests/core/subscription/ubble/test_ubble_workflow.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12308
Enregistrer les données fournies par l'ID provider dès réception. 
Side effect (aussi une feature): l'utilisateur sera redirigé vers le bon parcours 
Exemple: s'il a déclaré avoir 17 ans in app, mais que le provider trouve 18 ans, on lui demandera les infos manquantes (i.e. num de téléphone) pour finaliser son inscription
> (PC-12308) update user data after id check

- api/src/pcapi/core/subscription/api.py
We were returning a fraud_models.FraudCheckStatus instead of a subscription_models.SubscriptionItemStatus
Error https://sentry.internal-passculture.app/organizations/sentry/issues/246592/?environment=testing&project=5&query=is%3Aunresolved
​
​
> (PC-12583) Fix UserProfiling status display in admin

- api/src/pcapi/notifications/push/__init__.py
- api/src/pcapi/notifications/push/backends/batch.py
- api/src/pcapi/notifications/push/backends/logger.py
- api/src/pcapi/notifications/push/backends/testing.py
- api/src/pcapi/notifications/push/models.py
- api/src/pcapi/tasks/batch_tasks.py
- api/tests/tasks/batch_tasks_test.py
Raising an error with status code = 400 in cloud task endpoint will trigger a retry by cloud task. The ConnectTimeout errors that we currently had were not retried because the exception was caught.
Erreur sentry liée https://sentry.internal-passculture.app/organizations/sentry/issues/10763/?environment=production&project=5&query=is%3Aunresolved
> (PC-12768) Add retry on batch ConnectTimeout requests

- api/src/pcapi/core/fraud/api/ubble.py
- api/tests/core/subscription/test_factories.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12566
Test avec l'app sur testing : Exception lorsque Ubble OK mais ma date de naissance n'est pas celle déclarée.
Ça reste en PENDING du fait de cette exception, à cause des dates offset-naive vs offset-aware.
https://sentry.internal-passculture.app/organizations/sentry/issues/247478/?project=5
​
> (PC-12566) api: Fix exception when processing Ubble response: aware-offfset datetime

- api/src/pcapi/core/mails/transactional/bookings/booking_confirmation_to_beneficiary.py
- api/src/pcapi/core/mails/transactional/bookings/booking_postponed_by_pro_to_beneficiary.py
- api/src/pcapi/utils/urls.py
- api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py
- api/tests/core/mails/transactional/bookings/booking_postponed_by_pro_to_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12608
Ajouter un lien web vers la réservation concernée dans l'email
/!\ le modèle des emails doit encore être modifié -> ajout de params.BOOKING_LINK dans un bouton de l'email
Voir détails sur Jira
Ajout fichier api/src/pcapi/core/bookings/utils.py
N/A
​
> (PC-12608)[API]sendinblue adding booking web link to transac email

- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12777
ajouter un template de mail manquant lorsque la réservation annulée par un acteur culturel 
a été faite par un enseignant
> (PC-12777)[API]sendinblue-fix-transac-email-cancelled-booking-to-teacher

- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
- api/tests/admin/custom_views/beneficiary_user_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12806
Permettre la mise à jour de la pièce d'identité en testing uniquement pour simplifier les tests ubble
et pouvoir retester avec la meme ID
Autoriser la modification uniquement en testing
> [pc-12806][api] Allows to update idPieceNumber in flask

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/common/models.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/fraud/ubble/models.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/external/users_subscription.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/validation/routes/ubble.py
- api/tests/connectors/beneficiaries/ubble_fixtures.py
- api/tests/connectors/beneficiaries/ubble_test.py
- api/tests/core/fraud/test_api.py
- api/tests/core/fraud/test_factories.py
- api/tests/core/subscription/test_factories.py
- api/tests/core/subscription/ubble/test_ubble_workflow.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
Comme discuté en synchro backend, on préfère une organisation : 
- fraud/api.py
- fraud/ubble/api.py
A ce qu'il y avait : 
- fraud/api/ubble.py
- fraud/api/__init__.py
Pour : 
- ne pas avoir de code écrit dans __init__.py
- ça fixe les `fraud_api.ubble.is_user_allowed_to_perform_ubble_check` où le ctrl+click ne fonctionne pas (sur vscode en tout cas)
> (PC-12584) Refacto core.fraud files

- api/src/pcapi/scripts/payment/mark_payments_as_sent.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12573
permettre de passer au status SENT seulement une partie des remboursements à partir d'un fichier texte de payment id
nouvelle fonction qui prend en entrée un fichier texte d'id de remboursements
​
nope
​
> [PC-12573][script] feature(payments): allow partial batch to be marked as sent

- api/src/pcapi/connectors/thumb_storage.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/object_storage/__init__.py
- api/src/pcapi/core/object_storage/backends/base.py
- api/src/pcapi/core/object_storage/backends/gcp.py
- api/src/pcapi/core/object_storage/backends/local.py
- api/src/pcapi/core/object_storage/backends/ovh.py
- api/src/pcapi/core/object_storage/testing.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/scripts/delete_unused_mediations_and_assets.py
- api/src/pcapi/settings.py
- api/tests/core/finance/test_api.py
- api/tests/files/invoice/rendered_invoice.html
- api/tests/routes/pro/post_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11624
Stocker les PDF avec un nom de fichier plus lisible par un être humain, et les placer chacun dans un dossier basé sur un token de 256 bits.
- Ajout d'une propriété `Invoice.storage_object_id`
- [object_storage] Renommage de variables confondant `bucket` et `folder`
- Ajout d'une méthode `recursive_listdir()` permettant de lister des fichiers de manière récursive dans les tests
​
> (PC-11264) tweak invoice pdf storage

- api/src/pcapi/admin/base_configuration.py
- api/src/pcapi/templates/admin/no_user_found.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12739
Sur l'environnement de testing et dev:
Lorsqu'un utilisateur se connecte à Flask Admin avec son compte Google `passculture.app` et que son compte n'existe pas en base de données, le compte est créé automatiquement avec les droits Admin.
​
> [PC-12739] add passculture.app users to testing env

- api/src/pcapi/core/offerers/models.py
- api/tests/core/search/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12853
Un lieu ne peut être indexé que s'il respecte ces trois conditions : 
1. il est permanent ;
2. sa structure est active ;
3. son type ne fait pas partie de la liste des types interdits (uniquement [lieux administratifs](https://github.com/pass-culture/pass-culture-main/pull/1030) pour l'instant).
Les deux premières sont celles déjà appliquées, cette PR ajoute la dernière.
​
Si la liste des types de lieux interdits grandit, on pourra déplacer tout ça dans une propriété / une constante / autre... mais pour l'instant, autant aller au plus simple.
> [API] (PC-12853) feat:search: administrative venues

- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Ajout de l'objet students dans les objets à indexer pour pouvoir filtrer par classe sur adage
> (PC-12743) add students in object to index in algolia

- api/src/pcapi/core/offers/repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12830
When rewriting the offer view's query the filter on date was moved
to a subquery to apply the DISTINCT ON offerId.
It seesm that the subquery was a bit too broad and missing filters
on venue/offerer takes way too long.
I guess that - at some point - this will be again an issue but
that should buy us time before.
​
​
> [PC-12830][API][PRO] fix filter per date on offers view

- api/src/pcapi/core/finance/api.py
The default value for `compression` is `ZIP_STORED`: "The numeric
constant for an uncompressed archive member". The 60Mb CSV file was
thus compressed into a 60Mb ZIP file. In fact, the ZIP file was
slightly larger. That was not quite what was intended.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12887
> [PC-12887][api][finance] Fix compression of `payments_details.csv` CSV file

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
…nerated csv
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11552
Retirer potentiel saut de ligne dans les champs texte de csv généré pour la finance
A voir dans un second temps contrôle des caractères dans les champs selon la norme ISO 20022 (XML SEPA)
qui normalement autorise tous les caractères UTF-8. Cependant, les banques françaises se limitent au jeu de caractères latins, composé de :
a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 / - ? : ( ) . , ? + Espace.
​
> (PC-11552)[API]payment script: clean text format for accounting 

- api/src/pcapi/admin/custom_views/support_view.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/repository.py
- api/src/pcapi/scripts/beneficiary/import_dms_users.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/saml/educonnect_test.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12582
Supprimer l'ensemble de l'utilisation des BeneficiaryFraudResults qui ne sont désormais plus utiles
​
​
> [pc-12582][api] Remove use of BeneficiaryFraudResult

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220119T134451_c0aecae92e70_upsert_invoice_reference_into_reference_scheme.py
- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11624
Utiliser des références uniques consécutives pour les Invoices.
- Migration d’ajout de données initiales dans la table reference_scheme (pour 5 ans)
- Utilisation d’un ReferenceScheme pour invoice.reference
​
​
> (PC-11624) use reference_scheme for invoice.reference

- api/src/pcapi/core/bookings/validation.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/finance/repository.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/repository/payment_queries.py
- api/src/pcapi/repository/reimbursement_queries.py
- api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py
- api/tests/core/bookings/test_api.py
- api/tests/core/finance/test_api.py
- api/tests/core/finance/test_integration.py
- api/tests/core/finance/test_repository.py
- api/tests/repository/payment_queries_test.py
- api/tests/repository/reimbursement_queries_test.py
- api/tests/routes/serialization/reimbursement_csv_test.py
Adaptation du CSV des remboursements pour prendre en compte les anciens (Payment + PaymentStatus) et les nouveaux modèles (Pricing + Cashflow). **Commits à relire séparément.**
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11628
> [PC-11628][api][finance] Utilisation de Pricing et Cashflow à la place de Payment

- api/src/pcapi/core/subscription/messages.py
- api/src/pcapi/routes/external/users_subscription.py
- api/src/pcapi/scripts/beneficiary/import_dms_users.py
- api/tests/routes/external/user_subscription_test.py
The eligibilityType was eroneously considered regarding datetime.now() instead of registration_datetime. Moreover, do not consider as 'ParsingException' when eligibilityType is None. It is a specific case we want to handle separately
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12899
​
​
> (PC-12899) Fix DMS eligibilityType definition

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/scripts/booking/handle_expired_bookings.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12916
Since we send an email  for expired bookings, an entry in the
mail table is added and commited for each user.
However the commit for the first user breaks the cursor used for
looping over users.
This work around the issue by getting the list of user's ids and
then fetch the user one by one. Might not be the most efficient
but saves memory.
> [PC-12916][API] fix email for expired bookings

- api/src/pcapi/core/mails/transactional/send_transactional_email.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12913
HF pour corriger l'adresse d'envoi du mail de reinitilisation mdp en production
support-pro@passculture.app (au lieu de support@passculture.app)
- fix temporaire pour cas particilier (1 seul mail concerné pour le moment)
​
N/A
​
> (PC-12913)[PRO]fix:sendinblue sender for email reset password

- .circleci/config.yml
- adage-front/src/app/components/OffersSearch/OfferFilters/OfferFilters.spec.tsx
- adage-front/src/app/types/facets.ts
Suite au passage monorepo, les tests de qualité adage-front ne se lançaient plus en ci
- Remontée de la conf circle-ci de adage-front/.circleci au niveau du fichier de config du main
​
​
> [MAIN] BSR: launch adage quality tests on ci

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/user_email_history_view.py
- api/src/pcapi/alembic/versions/20220119T145431_f477748a5c40_rm_deviceid.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/email/update.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/webapp/beneficiaries.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12869
Supprimer la colonne `deviceId` de la table `user_email_history` : l'information est récupérée de la requête http, l'information peut trop facilement être modifiée et n'est donc pas fiable, il n'y a donc aucune raison de la conserver.
> [API] (PC-12869) fix:account: rm device id

- api/src/pcapi/core/object_storage/backends/gcp.py
- api/tests/core/object_storage/object_storage_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11888
Catch not found file exception on GCP bucket when trying to delete thumbnail
> (PC-11888)[API] Catch not found file exception on GCP bucket when trying to delete thumbnail

- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_activation_offers.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_educational_bookings.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerers_with_pro_users.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py
- api/tests/core/search/test_serialize_algolia.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/routes/webapp/get_booking_by_id_test.py
- api/tests/scripts/update_venue_type_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12885
Faire en sorte que les lieux créés par la _sandbox industrial_ ont tous un type (`venueTypeId` et `venueTypeCode` - en attendant que la transition vers `venueTypeCode` soit terminée).
Le problème est que d'un côté la colonne `venueTypeId` peut être nulle, de l'autre on s'attend à ce qu'un lieu ait toujours un type. Résultat, avec la _sandbox_, deux tiers des lieux créés n'avaient pas de type, ce qui n'est pas idéal pour réaliser des tests en **testing**.
> [API] (PC-12885) fix:sandbox: all venues have a type

- api/src/pcapi/core/offerers/validation.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12872
Augmenter la taille max d'une image envoyée pour servir d'illustration à un lieu : 200Ko avant contre 10Mo après.
Note : un ticket chargé d'ajouter la compression va arriver rapidement, donc l'idée n'est pas d'enregistrer tel quel des images allant jusqu'à 10Mo.
> [API] (PC-12872) feat:venue: increase upload size limit

- adage-front/src/app/App.tsx
- adage-front/src/app/ui-kit/MultiSelectAutoComplete/MultiSelectAutocomplete.scss
Retour du ticket PC-12748
Le texte du placeholder du multiselect ne doit plus être en italique une fois qu'une valeur est sélectionnée
> (PC-12748) font-style normal in placeholder if value is selected

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12945
Lancer une opération d'invalidation de cache CDN sans attendre le résultat.
```
#!/bin/bash -eo pipefail
gcloud compute url-maps invalidate-cdn-cache testing-pro-url-map --path "/*"  --async
echo "An invalidateCache operation has been requested. You can follow its progress on https://console.cloud.google.com/compute/operations"
Invalidation pending for [https://www.googleapis.com/compute/v1/projects/**********************/global/urlMaps/testing-pro-url-map]
Monitor its progress at [https://www.googleapis.com/compute/v1/projects/**********************/global/operations/operation-1642695270949-5d605cc196299-c8c1bfba-b2fe6af9]
An invalidateCache operation has been requested. You can follow its progress on …
```
> (PC-12945)[CI] invalidate CDN cache asynchronously

- api/src/pcapi/repository/reimbursement_queries.py
- api/tests/repository/reimbursement_queries_test.py
- api/tests/routes/serialization/reimbursement_csv_test.py
New-style data must appear first because it's more recent.
I am not sure what we wanted to sort on by ordering on `Payment.id`. I
suppose that we wanted to order on `Booking.dateUsed`, since payments
are created by iterating over bookings ordered on this attribute.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12628
> [PC-12628][api][finance] Fix order of reservations in reimbursement list

- pro/src/components/pages/Home/Offerers/MissingBusinessUnits.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12935
Lorsque l'on clique sur le lien "Renseigner des coordonnées bancaires" le site DMS s'ouvre dans un nouvel onglet
​
> (PC-12935)(PRO) Open DMS link in new tab when offerer does not have a business unit

- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/BankInformationFields/ApplicationBanner.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/BankInformationFields/__specs__/ApplicationBanner.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/BankInformationFields/__specs__/BankInformation.spec.jsx
- pro/src/styles/components/pages/Venue/_Venue.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12648
- Modifier le wording et le style du bandeau dossier en cours (coordonnées bancaires)
- Modifier la taille et l'espacement du picto dans le bandeau BU invalide dans les détails d'un lieu.
Bandeau dossier en cours : 
Bandeau BU invalide : 
​
> (PC-12648) UI Fixes : ApplicationBanner and Venue invalid bu banner

- api/src/pcapi/alembic/run_migrations.py
- api/tests/alembic/run_migrations_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12970
Configurer des tables ou colonnes à ignorer par alembic pendant la génération auto de migrations
- édition de `pcapi.alembic.run_migrations.py`
> (PC-12970)[api]alembic: ignore certain columns

- api/src/pcapi/core/users/api.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12833
Après une identification Ubble, le numéro de la pièce d'identité n'était pas mise à jour sur l'utilisateur.
Donc la détection de doublon de pièce d'identité ne fonctionnait pas.
> (PC-12833) api: Fix duplicate id piece number detection after Ubble id check

- api/src/pcapi/core/offers/repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12830
Corriger le filtre de la page des offres pour un utilisateur non admin.
Filtre sur la sous-requête pour un utilisateur pro "classique"
> [PC-12830][API][PRO] fix filter per date on offers view for non admin

- api/requirements.txt
Corriger l'installation de GraphQL depuis la mise a jour vers la version 3.0.0
Il faut désormais utiliser le suffixe d'installation "requests" afin d'installer les dependances correctement
les tests utilisent des mocks, j'ai donc fait une requete a la main pour vérifier qu'on peut toujours se connecter à DMS.
> [api] Fix python gql installation with version 3.0.0

- api/src/pcapi/connectors/beneficiaries/educonnect/educonnect_connector.py
- api/src/pcapi/connectors/beneficiaries/educonnect/exceptions.py
- api/src/pcapi/connectors/beneficiaries/educonnect/models.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12986
Code plus robuste qui n'échoue pas si un champ manque dans le `educonnect_identity`.
Ainsi, on peut avoir plus d'information sur le vecteur identité reçu dans des cas d'erreur comme celui-ci : https://sentry.internal-passculture.app/organizations/sentry/issues/253669/?environment=production. 
La PR permet de grouper l'erreur ci-dessus et [cette erreur](https://sentry.internal-passculture.app/organizations/sentry/issues/253668/?environment=production).
Cette PR gère aussi le cas d'un élève dont le "Niveau" n'est pas défini (erreur mentionnée [ci-dessus](https://github.com/pass-culture/pass-culture-main/pull/1133)). Comme on n'utilise pas ce champ, on fait en sorte que ça marche pour cette pauvre Lola.
> (PC-12986)(API) Mark educonnect uai and level fields as optional

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/webapp/phone_validation_test.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
- api/tests/scripts/force_19_yo_dms_import_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12883
verifier la validation de l'userprofiling avant de passer un utilisateur beneficiaire
> [pc-12883][api] Enforce userprofiling check on DMS application before being beneficiary

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProvidersManager.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11271
Afficher la section 'providers' sur la page lieu s'il y a au moins un provider enabledForPro ou au moins un provider déjà activé pour le lieu
> (PC-11271)[PRO] Venue edition: display venue provider even when all providers are disabled for pro

- api/src/pcapi/admin/templating.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/tests/core/subscription/ubble/test_ubble_workflow.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12392
Ajouter un statut `STARTED` au FraudCheck pour le dissocier du statut `PENDING` qui correspond à un dossier en cours d'analyse.
> (PC-12392)[API] Add STARTED status to fraud check

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/model_creators/generic_creators.py
- api/src/pcapi/routes/pro/venue_types.py
- api/src/pcapi/routes/pro/venues.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/src/pcapi/routes/serialization/venue_types_serialize.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/get_offer_test.py
- api/tests/routes/pro/get_offerer_test.py
- api/tests/routes/pro/get_venue_test.py
- api/tests/routes/pro/get_venue_types_test.py
- api/tests/routes/pro/patch_venue_test.py
- api/tests/routes/pro/post_offerer_test.py
- api/tests/routes/pro/post_venue_test.py
- api/tests/routes/pro/signup_pro_test.py
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/__specs__/VenueCreationContainer.spec.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/__specs__/VenueEdition.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/__specs__/VenueEditionContainer.spec.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/IdentifierFields.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/__specs__/IdentifierFields.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/utils/getLabelFromList.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/utils/__specs__/formatPatch.spec.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/utils/formatVenuePayload.js
- pro/src/core/OfferEducational/adapters/getOfferersAdapter.ts
- pro/src/routes/BusinessUnitList/BusinessUnitList.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10791
Supprimer l'utilisation de `venueTypeId` côté pro.
**Contexte**
Cette colonne (avec la table `venue_type`) vise à être remplacée par `venueTypeCode`. Le but est d'avoir un code stable qui permet de faire un mapping (label / icône / etc.) - le mapping est réalisé côté app native pour l'instant.
L'app native utilise directement `venue.venueTypeCode` et pour l'instant on mettait à jour les deux colonnes (`venue.venueTypeId` et `venue.venueTypeCode`) en attendant de terminer la transition.
Il reste un test à corriger côté webapp mais c'est un peu plus compliqué que prévu, et vu qu'on veut supprimer la webapp... pas la peine de creuser, non ?
> [API] (PC-10791) use venueTypeCode only

- api/src/pcapi/core/reference/factories.py
- api/src/pcapi/repository/clean_database.py
- api/tests/core/finance/test_api.py
- api/tests/core/finance/test_integration.py
- api/tests/core/reference/test_models.py
There is a migration that creates multiple ReferenceScheme. We can use
that as data fixtures for tests, to avoid having to create a
ReferenceScheme each time a test generates invoices. For this to work,
we must not clean the table in `clean_database`, adapt the factory to
reuse existing instances, and be a bit more careful in tests that do
need to use `ReferenceSchemeFactory`.
> [bsr][api][tests] Keep ReferenceScheme in the test database

- pro/src/screens/OfferEducational/OfferEducationalForm/FormNotifications/FormNotifications.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12871
prefill l'email des notifications si l'AC a coché la case et qu'un email de contact est renseigné 
- état initial, l'AC rentre un `email`, coche la case des notifications => `contactEmail` est pré-rempli
- état initial, l'AC coche la case des notifications, rentre un `email` => `contactEmail` est pré-rempli
- état initial, l'AC rentre un `contactEmail`, coche la case des notifications => `contactEmail` ne change pas
- état initial, l'AC rentre un `contactEmail`, rentre un `email`, coche la case des notifications => `contactEmail` ne change pas
- email, contactEmail rempli, case cochée. L'AC supprime le `notificationEmail`, décoche puis recoche la case => `contactEmail` se pré-rempli
- email, contactEmail rempli, …
> (PC-12871) prefill notification email

- api/src/pcapi/core/bookings/models.py
The isCancelled column usage has been removed in a proper JIRA ticket but we were waiting for the MOB to help column removal.
Here is the PR associated to the cleaning of isCancelled
> (BSR) Remove isCancelled column from booking model

- api/src/pcapi/routes/serialization/finance_serialize.py
- api/tests/routes/pro/get_invoices_test.py
- pro/src/components/pages/Reimbursements/Reimbursement.scss
- pro/src/components/pages/Reimbursements/ReimbursementsDetails/DetailsFilters.tsx
- pro/src/components/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx
- pro/src/components/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx
- pro/src/components/pages/Reimbursements/ReimbursementsTable/ReimbursementsTable.module.scss
- pro/src/components/pages/Reimbursements/ReimbursementsTable/TableBody/ReimbursementsTableBody.module.scss
- pro/src/components/pages/Reimbursements/ReimbursementsTable/TableHead/ReimbursementsTableHead.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11786
Prend aussi en compte les retours pour les tickets 11787 & 11788
- L'API renvoie le montant en valeur absolue
- La colonne montant n'est plus triable
- Le bouton réinitialiser les filtres est disabled quand aucun filtre n'est sélectionné
- Petits retours UI tailles / espacements / ...
- Définir une valeur `selfDirection` à `'None'` pour la colonne `amount` (n'ayant pas réussi à rendre la valeur optionnelle avec TS) et changer la logique dépendamment de cette valeur côté Table
> (PC-11786): Remove sort on Amount, fix data sent by API, fix reset filters, improve UI

- api/src/pcapi/connectors/api_entreprises.py
- api/src/pcapi/models/feature.py
- api/tests/connectors/api_entreprises_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12947
- Make it possible to turn off the professionals account creation
- Ajout du feature flag `ENABLE_PRO_ACCOUNT_CREATION`
- `get_by_offerer`
- `make_validation_email_object`
- `maybe_send_offerer_validation_email`
- `_send_to_pc_admin_offerer_to_validate_email`
- `_send_to_pc_admin_offerer_to_validate_email`
- `create_offerer`
- `create_offerer` (route)
- `validate_user` (route)
- `get_offerer_legal_category` (catches `ApiEntrepriseException`)
- `Offerer.legal_category`
- `ValidationView.edit` (admin)
- `get_by_siret`
- `check_siret_is_still_active`
- `SaveVenueBankInformations.get_referent_venue` (procédure DMS bic/iban)
- PR : `(PC-XXX) Description rapide de l' …
> [PC-12947][API] indisponibilité de l'API entreprise

- api/src/pcapi/routes/pro/offers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13091
Ajout d'un log d'erreur de manière temporaire pour débugger la création d'offres avec des extraData vides
> (PC-13091) Temporary log error when returning an offer with empty extraData on educational offer creation or edition

- api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py
Some rules have a fixed amount instead of a reimbursement rate. It's
relatively rare and we never displayed the corresponding rate. Let's
keep it that way and do something simple.
> [bsr][api][finance] Fix reimbursement CSV for custom rule with amount

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/subscription/dms/api.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12975
Ajouter l'état "started" sur les dossiers dms pour améliorer l'infos et simplifier les regles de reprises ou re tentatives.
> [pc-12975][api] Add started state to DMS fraud check

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13109
Réutiliser un fraud_check ubble lorsque l'utilisateur reprend une session qu'il a précédemment quittée
> [pc-13109][api] restart workflow for STARTED fraud_check

- api/src/pcapi/core/mails/transactional/pro/offer_validation_to_pro.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12792
migration mailjet vers sendinblue
lorsqu'une offre est approuvé, l'acteur culturel reçoit un email de validation.
N/A
​
N/A
​
> (PC-12792)[API]sendinblue pro offer approval email

- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/serialization/utils.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13077
Vérifier que les nom et prénom renseignés dans la route /subscription/profile sont bien dans un alphabet latin.
- utilisation de la lib alphabet-detector
> (PC-13077)[API] subscription: check firstname and lastname validity

- api/src/pcapi/core/mails/transactional/pro/booking_expiration_to_pro.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/domain/user_emails.py
- api/src/pcapi/scripts/booking/handle_expired_bookings.py
- api/tests/core/mails/transactional/pro/booking_expiration_to_pro_test.py
- api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py
- api/tests/domain/user_emails_test.py
- api/tests/scripts/booking/handle_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12794
migration mailjet vers sendinblue - email de notification aux acteurs culturels quand des réservations expirent au bout de 30 jours (10 jours pour les livres) car les bénéficiaires n'ont pas utilisé leur contremarque
déplacement pcapi/emails vers pcapi/core/mails/transactional/pro
suppression des valeurs mailjet (pas nécessaire de les conserver) car le feature flag ne peut pas être retiré ENABLE_SENDINBLUE_TRANSACTIONAL_EMAILS
> (PC-12794)[PRO]sendinblue email booking expiration

- api/src/pcapi/alembic/versions/20220121T105010_1c78fd29dcf6_remove_offer_idatproviders_checks.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9019
Ajout d'une contrainte sur offer et idAtProvider.
- Migration pour ajouter la contrainte.
> (PC 9019) : add constraint to offer idAtProvider

- api/src/pcapi/core/offers/serialize.py
- api/tests/core/bookings/test_repository.py
- api/tests/routes/serialization/reimbursement_csv_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13065
Replacement de l'appellation` offre scolaire` par `offre collective` dans le CSV des réservations.
> (PC-13065)[api]bookings: edit eac booking label in csv

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
- api/tests/sandboxes/scripts/industrial/test_save_industrial_sandbox.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12927
Corriger le script de sandbox
- Création d'un `User` avec un portefeuille permettant de réserver un stock à presque 20000€, afin d'éviter la génération de 67 `Bookings` de 300€ pemettant à ce qu'une `Venue` ait un CA de plus de 20000€ et changer de règle de remboursement pour la valorisation.
- Utilisation de `UsedIndividualBookingFactory` au lieu de `IndividualBookingFactory`
> (PC-12927)[api]sandboxes: fix create_specific_invoice()

- pro/src/components/pages/Reimbursements/ReimbursementsTable/TableBody/ReimbursementsTableBody.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11791
Réduire la taille de l'icone téléchargement + ajout d'une marge à droite de l'icone pour compense. 
> [PC-11791] - Fix svg size + margin

- api/src/pcapi/domain/booking_recap/booking_recap.py
- api/tests/routes/pro/get_all_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13055
Ne plus voir de contremarque dans les réservations lorsqu'il s'agit d'une offre collective
> (PC-13055) set booking token to None if offer is educational

- pro/src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
- pro/src/components/pages/Offers/Offer/OfferLayout.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
- pro/src/core/OfferEducational/adapters/getStockOfferAdapter.ts
- pro/src/core/OfferEducational/types.ts
- pro/src/custom_types/offer.ts
- pro/src/routes/OfferEducationalEdition/OfferEducationalEdition.tsx
- pro/src/routes/OfferEducationalStockEdition/OfferEducationalStockEdition.tsx
- pro/src/screens/OfferEducationalStock/OfferEducationalStock.stories.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12723
- Un AC pouvait modifier l'url dans sa barre de navigation pour changer l'id de l'offre/stock qu'il était en train de modifier
- si l'url était l'url d'édition d'une offre individuelle et que l'id modifié était celui d'une offre collective alors l'AC avait accès à un formulaire différent de celui de la création d'offre, et donc avait la possibilité d'ajouter des champs à son offre
- idem dans l'autre sens
- Dans cette PR on interdit l'accès aux urls de l'individuel si l'offre est collective et vice versa
> (PC-12723)[PRO] Redirect to individual/collective depending on offer.isEducational

- api/alembic_version_conflict_detection.txt
Le fichier alembic_version_conflict_detection.txt n'avait pas été mis à jour lors de [ce commit](https://github.com/pass-culture/pass-culture-main/commit/4a37de7b51a6e5306073d974ec33affa16d43e57).
> (PC-FIX) fix:alembic: version conflict detection

- adage-front/src/app/components/OffersSearch/OffersSearchBarAndFilters/OffersSearchBarAndFilters.tsx
- adage-front/src/app/components/OffersSearch/SearchBox.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12977
Lorsque l'utilisateur entre une chaîne de caractères de recherche dans la barre de recherche adage, il doit pouvoir lancer la recherche en tapant sur la touche "Entrée"
Ajouter un appel à `refine(query)` dans la fonction `onSubmit` du formulaire
> (PC-12977)[ADAGE]: refine query when typing Enter key on search bar

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
- api/tests/routes/serialization/reimbursement_csv_test.py
We should wait for the event date before reimbursing an event
booking (like we used to do in the old Payment-based system).
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13156
> [PC-13156][api][finance] Do not generate cashflows for upcoming events

- api/src/pcapi/scripts/clean_duplicated_offers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9019
Dans le cadre de la migration des offer.idAtProviders vers les offer.idAtProvider, on a besoin de nettoyer certains offre en double qui bloquent la migration des données.
La mise à jour de ce script permet de le faire.
- mise à jour d'un script de nettoyage de doublons sur les offres.
> (PC 9019): update clean duplicated offers script

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreation.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreationContainer.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/__specs__/VenueCreationContainer.spec.js
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/IdentifierFields.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/__specs__/IdentifierFields.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13102
Création de lieu: ne pas faire des appels à l'api entreprise lorsque le FF DISABLE_ENTERPRISE_API est activé
> (PC-13102)[PRO] Venue Creation: do not call entreprise API when his FF is disabled

- pro/src/styles/components/pages/Venue/fields/LocationFields/_LocationViewer.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12812
Résolution d'un bug visuel sur la page d'édition de lieu : la carte passait au-dessus de la modale.
> (PC-12812) fix(venueEdition): remove magic z-indexes from the map

- .github/workflows/ping_data_team.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12735
Le channel slack #db-changes reçoit une notification pour chaque PR avec une migration.
Le but de la PR est que cette notif ne parte qu'au merge.
Et qu'elle parte aussi s'il y a une colonne qui est marqué comme supprimée sans avoir été enlevée de la db.
Modification de la CI
- filtre sur pull_request.merged : ça aurait pu être au push sur merge autrement mais on aurait pas eu le lien de la PR facilement
- déclenchement avec le fichier run_migrations.py également
> (PC-12735) Ping slack seulement au merge

- api/src/pcapi/admin/custom_views/booking_view.py
- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/scripts/stock/soft_delete_stock.py
There were a few places where we used `Booking.payments` which is not
the right way anymore to check whether a booking has been reimbursed.
> [bsr][api][finance] Use `has_reimbursement()` instead of `Booking.payments`

- api/src/pcapi/core/finance/repository.py
- api/src/pcapi/core/offers/validation.py
- api/tests/core/finance/test_repository.py
When creating a stock or editing the price of an existing stock, we
used to check if the offer had a custom reimbursement rule. If so, we
would reject the request.
Now we allow the creation or edition if the reimbursement rule is in
the past (i.e. if it's not active anymore). If the rule is active or
will be active, we still refuse to create or modify a stock.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13231
> [PC-13231][api][offers] Allow to change stock price if offer custom rule is not valid anymore

- api/src/pcapi/scripts/educational/update_educational_institutions_deposits.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13166
Dans le but de mettre à jour les budgets pour une année déjà démarrée, il faut pouvoir préciser l'année afin de ne pas modifier les budgets de l'année suivante
> (PC-13166)[API] update update_educational_institutions_deposits script to add year parameter

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/domain/booking_recap/booking_recap.py
- api/src/pcapi/domain/booking_recap/utils.py
- api/tests/core/bookings/test_repository.py
- api/tests/domain/booking_recap_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13232
- Il a récemment été décidé, et implémenté, le fait de ne pas remonter de contremarque pour les réservations correspondant à des offres collectives, dans la liste des réservations côté pro.
- Cependant, les contremarques remontaient dans le csv listant les réservations
- Le but de cette PR est double:
1. Ne pas remonter la contremarque d'une réservation collective dans le csv des réservations
2. Harmoniser la fonction _get_booking_token pour que cette dernière soit utilisée à la fois par la page des réservations et le csv 
- _Explications sur l'utilisation d'outils peu communs (ex.: …
> (PC-13232)[API PRO]: set eac bookings to none in booking csv

- api/src/pcapi/scripts/beneficiary/archive_dms_applications.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13236
Corriger un plantage des process DMS  à cause d'une trop grande consommation mémoire.
The fact that we have a lot of application to process and that
we query but don't commit when performing an archive means the
objects in SQLAlchemy session cache stack up to the point it
fills the memory and crashes the process.
Adding a rollback forces SQLAlchemy to clear its cache and
free memory.
> [PC-13236][API] clear SQLA. session between DMS archive action

- pro/src/components/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx
- pro/src/components/pages/Reimbursements/ReimbursementsInvoices/InvoicesNoResult.tsx
- pro/src/components/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13122
Remettre à l'état initial la page justificatifs de remboursement lors du clic sur Réinitialiser les filtres
> (PC-13122)(PRO): Reset invoices page state on filters reset

- api/src/pcapi/scheduled_tasks/clock.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-6876
Avant : on log un message alors que le contexte de l’application n’est pas encore disponible (à cause de l'ordre des décorateurs appliqués à `pc_notify_users_bookings_not_retrieved`)
Après : les décorateurs sont appliqués dans le bon ordre
Bug remonté et expliqué par @xordoquy , merci 🙏
> (PC-6876) fix:cron: update decorator order

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/templates/invoices/invoice.html
- api/tests/core/finance/test_api.py
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13244
Corriger une erreur de calcul des montants de remboursement des `InvoiceLines`
- Renommage et correction de la propriété `bookings_amount` de `InvoiceLine`
- Séparation de la création du contexte permettant de _render_ la version HTML de l'`Invoice` afin de le tester unitairement
> (PC-13244)[api]finance: fix InvoiceLine bookings_amount

- api/src/pcapi/alembic/run_migrations.py
- api/src/pcapi/routes/pro/stocks.py
- api/tests/core/providers/test_api.py
- api/tests/routes/pro/post_venue_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9019
Correction de l'erreur `KeyError` dans la synchronisation des offers dans le endpoint de l'API pro.
- correction de l'erreur
- adaptation des tests associés
- ajout d'un migration ignore pour la colonne idAtProviders de offer (elle ne sera plus prise en compte dans la génération automatique de migration d'alembic
> (PC 9019) fix KeyError in offers synchronisation

- api/src/pcapi/core/mails/transactional/bookings/booking_expiration_to_beneficiary.py
- api/tests/core/mails/transactional/bookings/booking_expiration_to_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13243
Fix du contenu généré pour l'email EXPIRED_BOOKING_TO_BENEFICIARY
N/A
N/A
> (PC-13243)[API]fix: sendinblue booking expiration to beneficiary email

- api/src/pcapi/core/educational/adage_backends/__init__.py
- api/src/pcapi/core/educational/adage_backends/adage.py
- api/src/pcapi/core/educational/adage_backends/base.py
- api/src/pcapi/core/educational/adage_backends/logger.py
- api/src/pcapi/core/educational/adage_backends/testing.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/offers/api.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary_test.py
- api/tests/routes/pro/cancel_educational_offer_booking_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13142
Notifier adage lorsqu'un acteur culturel annule une réservation collective.
- Ajout d'une méthode dans les adapter adage_backends pour les différents environnements
- Appel de cette méthode dans offers/api.py/cancel_educational_offer_booking
> Pc 13142/call adage route when booking cancelled by offerer

- api/src/pcapi/core/fraud/api.py
En ré-important l’utilisateur du ticket PC-13274, je me suis rendu compte d’un bug : quand le dossier dms est accepté, on ne met pas à jour le contenu du FraudCheck DMS. Celui-ci est créé lorsque le dossier DMS est passé en mode Draft ; mais il peut avoir changé entre temps.
> (PC-13274) Update dms fraudCheck content on reception

- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/serialization/utils.py
- api/tests/serialization/utils_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13077
Corriger la détection de caractères latin
Avant
```bash
In [6]: is_latin("a")                                                                                 
Out[6]: True
In [7]: is_latin("&")                                                                                 
Out[7]: True
```
Après
```bash
In [2]: is_latin("&")                                                                                 
Out[2]: False
In [3]: is_latin("a")                                                                                 
Out[3]: True
In [4]: is_latin("1")                                                                                 
Out[4]: False
```
Aussi s'assurer que les champs ne sont pas vides
- Branche : …
> (PC-13077)[API] fix: Update is_latin function

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/routes/pro/post_offer_test.py
- api/tests/routes/pro/post_shadow_stock_for_educational_showcase_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13160
Dans le cadre de la création d'offre vitrine, l'AC doit pouvoir créer une offre sans créer de date et de prix
Or, pour que celle-ci puisse remonter et être cohérente avec le reste des données, on doit créer un stock "fantôme" le temps que l'AC décide la date et le prix avec les rédacteurs de projet
> (PC-13160)[API] Create showase stock

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/routes/external/users_subscription.py
- api/src/pcapi/validation/routes/dms.py
- api/tests/routes/external/user_subscription_test.py
There were graphql exceptions because int was expected instead of str
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13312.
Bug créé par le ticket [PC-12335: App Native - DMS : Mettre à jour le fraudcheck (pending, cancelled) en fonction du retour DMS (webhook)TERMINE](https://passculture.atlassian.net/browse/PC-12335) à cause de [cette ligne](https://github.com/pass-culture/pass-culture-main/commit/93d18156da6baf185079b50ff4d8e66e3d76dba5#diff-d6ed29320fad01ec92a80616b0a0f100dc313811ad49d07d58cbe660fe00c159R26)
Erreur sentry : https://sentry.internal-passculture.app/organizations/sentry/issues/256627/events/latest : l’api graphql râle parce qu’on utilise un str plutôt qu’un int
- _Exemples: Ajouts de modèles, …
> (PC-13312) Fix dms webhook types

- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13203
Empêcher un champs contenant uniquement des espaces, si le champs est obligatoire et de type string 
- appliquer `string.strip()` avant de checker si elle est vide
- J'en profite pour régler un TODO
> PC-13203 fix: Check for empty strings when updating profile 

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/pro/venues.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/src/pcapi/utils/image_conversion.py
- api/tests/routes/pro/get_venue_test.py
- api/tests/routes/pro/post_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12874 
Ajout de la compression et du recadrage lors de l'enregistrement d'une image pour un lieu.
Au passage : 
* ajout d'une méthode `from_orm` à `GetVenueResponseModel` qui a besoin de modifier le champ `venueTypeCode` puisque ce dernier doit être une clé qui permet de reconstruire l'`enum` et non un `enum` directement (sinon pydantic ne parvient pas à sérialiser) ;
* la route d'api qui permet de sauvegarder l'image d'un lieu renvoie maintenant le lieu en question (avant la route ne renvoyait rien), ceci permet de récupérer l'URL de l'image sauvegardée.
> [API] PC 12874 compress venue banner

- api/src/pcapi/serialization/utils.py
- api/tests/serialization/utils_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13203
Accepter les apostrophes typographiques, qui peuvent provenir d'un clavier de téléphone mobile
> (PC-13203) accept typographic apostrophe in names and adresses

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13330
Changer dans le job de ci `export_chart_version` le fichier contenant la version du chart pcpai
> (Pc 13330) (CI) configure chart version per environment

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12932
Utilisation généralisée du statut `STARTED` ubble dans le processus de vérification.
Rattrapage des utilisateurs à la fois PENDING et INITIATED/UNINITIATED pour les passer en ubble status `STARTED`. Rattrapage effectué le 7 février en prod.
Suppression des vérifications sur le statut Initiated/uninitiated du fraud_check
- Le script passé en prod pour passer tous les PENDING INITIATED/UNINITIATED à STARTED est publié en commentaire du ticket JIRA. Il n'est pas commité pour ne pas alourdir la codebase.
> (PC-12932)[api] use STARTED ubble status for pending initiated uninitiated users

- pro/testcafe/06_offers.js
Le blocage de navigation est simulé via des history.push() et cela peut prendre du temps.
L'idéal serait de vraiment bloquer la navigation via un `history.block(() => window.confirm())` mais nous perdrions le design custom.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12612
> [PC-12612] RouteLeavingGuard: wait it in testcafe

- api/src/pcapi/domain/pro_offers/offers_recap.py
- api/src/pcapi/infrastructure/repository/pro_offers/offers_recap_domain_converter.py
- api/src/pcapi/routes/serialization/offers_recap_serialize.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/routes/pro/get_offers_test.py
- api/tests/routes/serialization/offers_recap_serialize_test.py
- pro/src/components/pages/Offers/Offers/OfferItem/OfferItem.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13162
Afficher les offres vitrines avec un label différent pour la date sur la liste des offres de PRO
> (PC-13162) [API+PRO] Display showcase offer on pro

- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_to_pro.py
- api/tests/core/bookings/test_api.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_to_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13392
fix : retire le surplus de données envoyées et non utilisés par le template 379 (sib prod)
N/A
N/A
> (PC-13392)[PRO]fix:sendinblue booking cancellation by user to pro

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
- api/tests/core/finance/test_api.py
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13280
Corriger une erreur lors de la génération des justificatifs de remboursement, causée par une assertion sur `InvoiceLine.rate`
Supprimer l'assertion, et utiliser le `rate` de la règle de remboursement, ou un `rate` calculé seulement dans le cas d'une règle de remboursement personnalisée qui définit un `amount`.
- Modification des données de test permettant de détecter ce bug.
- Utiliser des `int` dans les assertions de tests, au lieu de `float` multiplié par 100, certes plus lisibles mais pouvant causer des erreurs d'approximation, par exemple:
```
In [1]: 4.06 * 100
Out[1]: 405.99999999999994
```
- Modification de `create_specific_invoice()` dans la sandbox
- PR : …
> (PC-13280)[api]finance: fix assertion error in _make_invoice_line()

- .github/pull_request_template.md
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/ImportFromComputer/ImportFromComputer.module.scss
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/ImportFromComputer/ImportFromComputer.tsx
- pro/src/components/pages/Offers/Offer/Thumbnail/ThumbnailDialog.jsx
- pro/src/new_components/Advices/Advices.jsx
- pro/src/new_components/Advices/Advices.tsx
- pro/src/ui-kit/Divider/Divider.module.scss
- pro/src/ui-kit/Divider/Divider.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13364
Ajouter les conseils sur la modale d'upload d'une image pour les lieux
- Extraction du composant 'Advices' ;
- Import et utilisation dans la modale d'upload d'image
- [] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
> (PC-13364) Add advices to venue image upload

- api/src/pcapi/sandboxes/scripts/getters/pro_10_desk.py
- pro/testcafe/10_desk.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13431
- Test end-to-end qui n'est plus nécessaire : il n'y a pas de notion de validation de token dans le parcours d'une réservation collective
> (PC-13431)[PRO][API]: get rid of useless e2e test - there is no token validation in eac workflow

- api/src/pcapi/core/mails/backends/mailjet.py
- api/src/pcapi/utils/requests.py
- api/tests/core/mails/tests.py
We use version 1.3.3 of the `mailjet_rest` package. It sends requests
to `api.eu.mailjet.com`, whose SSL certificate expires on 2022-02-20.
We could move to version 1.3.4, which uses `api.mailjet.com`, but the
changelog is not up-to-date and I am not too confident about the
contents of the changes. So let's just tweak the URL when creating the
HTTP client. Since we're going away from Mailjet, it looks like it's
the simple solution.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13442
> [PC-13442][api][mail] Use new URL for Mailjet HTTP API

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/admin_user_view.py
- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
- api/src/pcapi/admin/custom_views/mixins/suspension_mixin.py
- api/src/pcapi/admin/custom_views/partner_user_view.py
- api/src/pcapi/admin/custom_views/pro_user_view.py
- api/src/pcapi/admin/install.py
- api/src/pcapi/admin/templating.py
- api/src/pcapi/alembic/versions/20220211T120000_4e4384ac4c8f_create_user_suspension_table.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/constants.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/tests/core/users/test_api.py
- api/tests/core/users/test_factories.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-8955
Permettre au support et à la fraude d'avoir des informations supplémentaires sur la suspension d'un compte utilisateur : la date, la personne qui a initié la suspension ou la réactivation, l'historique
Ajout d'une nouvelle table `user_suspension` dans la base de données (on ajoute des lignes, on n'en supprime ou modifie jamaisà)
Captures d'écran du backoffice dans le ticket Jira.
> (PC-8955) api: User suspension history

- api/src/pcapi/scripts/install.py
- api/src/pcapi/utils/human_ids.py
They accept one or more identifiers, and humanize or dehumanize them:
$ flask humanize 1234 2345
ATJA
BEUQ
$ flask dehumanize ATJA BEUQ
1234
2345
> [bsr][api][utils] Add `humanize` and `dehumanize` Flask command

- api/src/pcapi/core/users/models.py
- api/tests/validation/routes/users_authentifications_test.py
- api/tests/validation/routes/users_authorizations_test.py
Multiple fixes:
1. flask-login requires `is_authenticated`, `is_anonymous` and
`is_active` to be properties, not methods.
2. `is_active` is used by `flask_login.utils.login_user()`. Our code
should not pass inactive users to this function, but if it wrongly
did, we should rely on `User.is_active` to return the right thing.
> [bsr][api][users] Fix properties of User required by flask-login

- api/src/pcapi/notifications/push/transactional_notifications.py
- api/tests/routes/native/v1/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13149
Corriger le contenu de la notification : les _deeplink_ ne fonctionnent pas, le lien est ouvert dans l'app native, pas la web app.
> (PC-13149) [API] feat:notification: update content

- api/src/pcapi/admin/install.py
Tags (criterion) now works for offers and venues.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13370
Renommer le titre du menu des tags sur FA : les tags peuvent maintenant être utilisés pour des offres et des lieux.
> (PC-13370) [API] wording:admin: fix criterion menu name

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220215T141341_2a111d4feac2_create_user_suspension_foreign_keys.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13475
Dans le ticket [PC-8955](https://passculture.atlassian.net/browse/PC-8955), une table `user_suspension` a été créée en base de données, et référence l’utilisateur (`userId`) et la personne à l’origine de la suspension ou réactivation (`actorUserId`).
Dans la création de la table, les clés étrangères (_foreign keys_) vers la table user sont manquantes, alors qu’elles sont définies dans le modèle.
> (PC-13475) api: User suspension history: add foreign keys

- api/src/pcapi/core/offers/utils.py
- api/src/pcapi/models/feature.py
- api/tests/routes/native/v1/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13149
Ajout d'un FF qui permet d'activer et de désactiver le domaine utilisé pour les redirections, dans le cadre des liens vers des offres envoyés par mail à cause de restrictions ios.
> (PC-13149) [API] feat:offers: add FF for redirection links

- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_confirmation_by_pro.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_confirmation_by_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12793
fix pour retirer les détails utilisateurs quit peuvent dépasser la limite en données sendinblue de 100ko par email
(si plusieurs centaines d'utilisateurs pour un événement par exemple)
N/A
N/A
> (PC-12793)[PRO]fix: remove users details in email

- adage-front/eslint-plugin-pass-culture/lib/rules/use-date-fns-tz-format.js
- adage-front/eslint-plugin-pass-culture/tests/lib/rules/use-date-fns-tz.spec.js
- pro/eslint-plugin-pass-culture/lib/rules/use-date-fns-tz-format.js
- pro/eslint-plugin-pass-culture/tests/lib/rules/use-date-fns-tz.spec.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13500
Suite à l'implémentation du plugin eslint vérifiant l'utilisation de la fonction format de date-fns-tz (et non celle de date-fns), nous ajoutons ici une règle qui nécessite l'utilisation de la propriété `timeZone` dans les options de l'appel à cette fonction. Le but est toujours le même : éviter qu'un développeur n'oublie l'aspect timezone, fortement impactant sur les fronts du Pass Culture
- PR : `(PC-XXX) Description rapide …
> (PC-13500)[ADAGE] tech: add eslint rule requiring to use timezone as an option to format function

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
"Identifiant de la BU" est l'id de la venue ayant le meme siret que la BU.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12643
> [PC-12643][API][FINANCE] - Fix BU colomn value

- pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
Retour de validation : le séparateur en dessous de "date et prix" ne doit pas apparaître quand l'offre a une date et un prix
> (PC-13369)[PRO] fix: remove separator when offer has a date

- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/templates/mails/offer_creation_notification_email.html
- api/src/pcapi/templates/mails/offer_creation_refusal_notification_email.html
- api/src/pcapi/utils/mailing.py
- api/tests/emails/offer_creation_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13313
En tant que CT
J'aimerais voir indiqué “EAC” dans l’objet et le corps du mail des création d’offre
Afin de traiter ces offres plus rapidement 
Règles de gestion
Ajouter une variable dans l’objet du mail “[Création d’offre - XX EAC] Nom de l’offre”
Ajouter dans le corps du mail : 
Offre EAC = True 
> [PC-13313] Interne - Bizdev - Indiquer “EAC” dans les mails de notification de création d’offre

- pro/src/new_components/ImagePreview/stories/HomeScreenShell.module.scss
Correction de style du ImagePreview.stories pour corriger l'apparence dans storybook
Précédemment : 
Correction :
> Fix storybook style for image preview

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/ImageUploadButton/ImageUploadButton.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13282
Réduire la taille de l'icône + dans le bouton d'upload d'une image pour les lieux et offres.
Largeur et hauteur imposées : 32px.
Précédemment : 
Modification :
> (PC-13282) Reduce plus icon size in image upload button

- api/src/pcapi/core/users/external/sendinblue.py
- api/tests/core/users/external/external_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13511
Depuis quelques jours, des utilisateurs remontent un problème avec l'opt-in et opt-out des notifications SiB:
- certains ont opt-out et reçoivent les emails
- d'autres ont opt-in et ne reçoivent plus les emails
Une régression  avait été introduite lors de la précédente MEP.
L'attribut emailBlacklisted envoyé à SiB était incorrect.
- Ajout d'une assertion dans le test `test_update_external_user` pour éviter une future régression sur ce point
> (PC-13511)[api] fix: correct wrong emailBlacklisted sent to sendinBlue

- api/src/pcapi/local_providers/provider_api/provider_api_stocks.py
- api/tests/local_providers/provider_api_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13512
Order the stock synchronization by:
- starting with venue without no prior synchronization
- venues with the longest missed synchronization
This will makes sure that whenever the stock synchronization is
stopped for whatever reason (deploy, OOM killer...) it will
restart with those that have NOT been treated first.
> (PC-13512)[API] feat: order stocks sync by oldest sync date

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13515
Fix le chemin où sera build l'image db-ops
N/A
N/A
> (PC-13515) CI: Fix build-and-push-image-db-ops job

- api/src/pcapi/core/fraud/api.py
- api/tests/core/fraud/test_api.py
- api/tests/routes/saml/educonnect_test.py
Ticket : https://passculture.atlassian.net/browse/PC-12824
Anomalie détectée dans le cadre de [ce ticket](https://passculture.atlassian.net/browse/PC-13447)
[Cette utilisateur](https://backend.passculture.pro/pc/back-office/support_beneficiary/details/?id=2574681&url=%2Fpc%2Fback-office%2Fsupport_beneficiary%2F%3Fsearch%3D1766255) par exemple a un "educonnect KO", car il a dû appeler la route plusieurs fois.
- PR : `(PC-XXX) Description rapide de l' …
> (PC-12824)[API] fix: create a new fraud_check in case of educonnect multiple calls

- api/src/pcapi/routes/adage_iframe/offers.py
- api/tests/routes/adage_iframe/get_offer_test.py
Bug: après transformation d'une offre vitrine en offre normale, on affichait le stock "shadow" sur adage car on prend stocks[0] 
Tous les stocks remontaient car on ne filtrait pas sur les stocks actifs
> (PC-13163)[API] fix: return only active stocks for offers displayed in Adage

- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13536
Renommer le champ `bannerUrl` de l'index Algolia (les autres sont en _snake_case_).
> (PC-13536) [API] fix:venue: bannerUrl -> banner_url (Algolia)

- api/src/pcapi/connectors/thumb_storage.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/models/has_thumb_mixin.py
- api/src/pcapi/routes/pro/venues.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/post_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13479
1. Normaliser la fonction `save_venue_banner` qui n'appelait pas directement `create_thumb` et qui avait un nommage un peu différent pour ses fichiers : 
1. appeler `create_thumb` (avec un nouveau paramètre : `ratio`) ;
2. utiliser la valeur de `thumbUrl` (_property_) pour `bannerUrl` (colonne).
2. Mettre à jour le contenu de bannerMeta : suite à l'ajout de la compression et du redimensionnement, les nom et type du fichier envoyé ne sont plus pertinents donc on les supprime. Et ajout de image_credit qui contient le crédit photo (s'il y en a un).
Au passage : ajout du paramètre `ratio` à `create_thumb`.
- Commit(s) : …
> (PC-13479) [API] feat:venue: normalize save_venue_banner

- api/src/pcapi/alembic/versions/20210322_bd142e43ea07_add_feature_flag_offer_validation_.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/utils/custom_logic.py
- api/tests/core/offers/test_api.py
- api/tests/utils/custom_logic_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13563
Supprimer le FF OFFER_VALIDATION_MOCK_COMPUTATION, autrefois nécessaire au développement des fonctionnalités de validation d'offre.
- modification de la migration d'ajout
- suppression des occurrences dans le code
- Au passage, ajout d'une vérification que l'argument `comparated` de l'opérateur `contains` est bien une liste, et pas simplement une `str` afin d'éviter les faux positifs.
> (PC-13563) cleanup OFFER_VALIDATION_MOCK_COMPUTATION feature flag

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220221T104132_932e613984b3_add_ministry_enum_field_to_educational_deposit.py
- api/src/pcapi/core/educational/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13305
Préparer le backend pour recevoir les budgets des nouveaux ministères
- Créer une nouvelle colonne `ministry` dans la table `EducationalDeposit` (enum)
- Ecrire un script pour rattraper les données existantes
> (PC-13305)[API] feat: add ministry field in educational deposit table

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220214T111936_e9ddaad94156_set_jsonb_fields_as_used_ones.py
- api/src/pcapi/alembic/versions/20220214T145737_e9ddaad94157_create_new_index_product-jsondata-isbn.py
- api/src/pcapi/alembic/versions/20220214T145738_e9ddaad94158_create_new_index_offer-jsondata-isbn.py
- api/src/pcapi/alembic/versions/20220214T145739_e9ddaad94159_drop_obsolete_index_offer-extradata-isbn.py
- api/src/pcapi/alembic/versions/20220214T145740_e9ddaad94160_drop_obsolete_index_product-extradata-isbn.py
- api/src/pcapi/core/mails/models/models.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/models/extra_data_mixin.py
- api/src/pcapi/models/product.py
- api/src/pcapi/validation/models/generic.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13078
Utiliser les champs JSONB récemment créer plutôt que leurs équivalents JSON
- rename `email.content` to `email.contentOld` and `email.contentNew` to `email.content`
- rename `offer_validation_config.specs` to `offer_validation_config.specsOld` and `offer_validation_config.specsNew` to `offer_validation_config.specs`
- read from `jsonData` instead of `extraData` for `ExtraDataMixin`
- remove indexes `product_expr_idx` and `offer_expr_idx`
- create new index `product_isbn_idx` on `product.jsonData`
- create new index `offer_isbn_idx` on `offer.jsonData`
apparemment le renommage de champs, même sur des grosses tables, est très rapide (testé sur une table avec 43M+ enregistrement sur staging -> moins d'une seconde). …
> Pc 13078 use jsonb fields

- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/get_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13536
Bug : sans l'option `total=False`, le modèle `pydantic` s'attend à ce que les données correspondent exactement. Ce qui signifie que si `venue.bannerMeta` n'est pas nul et contient autre chose que `{"image_credit": "quelque_chose"}`, `pydantic` génère une erreur.
Fix : ajout de l'option [`total=False`](https://pydantic-docs.helpmanual.io/usage/types/#typeddict), qui permet de simplement dire quels champs sérialiser.
+ mise à jour d'un test pour contrôler ce comportement.
> (PC-13536) [API] fix:venue: add total=False to TypedDict

- api/src/pcapi/domain/admin_emails.py
- api/tests/domain/admin_emails_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9976
Aujourd’hui, les biz reçoivent tous les mails de création d’offres des acteurs : création de DVD, de CD, de vinyles… Ils souhaiteraient ne plus recevoir les mails liés aux CD, DVD, livres et vinyles.
Après discussion avec Caroline Nerot, il a été proposé de ne pas envoyer le mail “Création d’offre” (cf. [code ici](https://github.com/pass-culture/pass-culture-main/blob/2c0a4eb2c62211ef1e6508189015254fd995103a/api/src/pcapi/utils/mailing.py#L202-L222)) lorsque l’offre appartient aux 16 sous-catégories suivantes : 
* ABO_JEU_VIDEO
* ABO_LIVRE_NUMERIQUE
* ACHAT_INSTRUMENT
* AUTRE_SUPPORT_NUMERIQUE 
* BON_ACHAT_INSTRUMENT
* LIVRE_AUDIO_PHYSIQUE 
* LIVRE_NUMERIQUE
* LIVRE_PAPIER
* LOCATION_INSTRUMENT
* …
> PC-9976 check offer subcategory before notify

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/alembic/versions/20220221T195851_ddedcf7e2c67_add_ondelete_constraints_to_criterion_tables.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/models/offer_criterion.py
- api/tests/admin/custom_views/offer_view_test.py
- api/tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13531 
FA : Indexer immédiatement un lieu ou une offre lorsque la modification pour sur les tags.
Ceci permettra de faire remonter (quasi)immédiatement les tags sur l'index de recherche, dont se servent différents outils externes. Pour l'instant, on est obligé d'attendre que le prochain _job_ d'indexation se lance, ce qui rend le travail avec des outils externes pénibles et compliqués.
Au passage : ajout de contraintes `ondelete=CASCADE` aux tables `offer_criterion` et `venue_criterion`.
> [API] PC 13531 immediate indexing when tagging

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220222T083056_90c1a1eeeee0_add_index_on_booking_reimbursementdate.py
- api/src/pcapi/core/bookings/models.py
- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/routes/pro/bookings.py
- api/src/pcapi/routes/serialization/bookings_recap_serialize.py
- api/tests/core/bookings/test_repository.py
- api/tests/routes/pro/get_all_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13058
Ajout d'un filtre de Période de réservation / validation / remboursement sur la page de réservations.
- Ajout du paramètre `BookingStatusFilter` dans `ListBookingsQueryModel`.
- Filtrer les réservations sur (`dateCreated`, `dateUsed`, `reimbursementDate`) selon le paramètre `booking_status_filter` (`BOOKED`, `VALIDATED`, `REIMBURSED`).
> (PC-13058): get bookings pro filter by status date

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
- api/src/pcapi/alembic/versions/20220221T154105_70461af31b6e_drop_suspensionreason_from_user.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/utils/includes.py
- api/tests/core/users/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13452
Suppression de la colonne `suspensionReason` de la table user, remplacée dans `PC-8955` par une table `user_suspension`.
Migration PC-13451 exécutée le 21/02/2022 sur staging, OK.
Cette PR ne sera _mergée_ sur master qu'après PC-13451 sur la production.
> (PC-13452)[API] Remove column suspensionReason from user table

- pro/src/components/pages/Offerers/OffererCreation/OffererCreation.jsx
- pro/src/components/pages/Offerers/OffererCreation/OffererCreationContainer.js
- pro/src/components/pages/Offerers/OffererCreation/__specs__/OffererCreation.spec.jsx
- pro/src/components/pages/Offerers/OffererCreation/__specs__/OffererCreationContainer.spec.js
- pro/src/repository/pcapi/pcapi.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13189
Retirer redux-saga-data de OffererCreationContainer
> (PC-13189)[PRO] remove redux-saga-data from OffererCreationContainer

- pro/src/components/pages/Offers/Offer/Stocks/DeleteStockDialog/DeleteStockDialog.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13540
Modifier le wording de la pop-in de suppression de stocks : 
_Ce stock ne sera plus disponible à la réservation et entraînera l’annulation des réservations en cours !_ → **Ce stock ne sera plus disponible à la réservation et entraînera l’annulation des réservations en cours et validées !**
> (PC-13540)[PRO] feat: modify stock deletion pop in wording message

- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/get_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13610
Ajout du vrai id d'un lieu à la réponse renvoyée au client front, côté PRO.
Ceci permettra de construire l'URL vers l'app native (PRO utilise des ids "humanisés" alors que l'app native utilise les vrais ids).
> (PC-13610) [API] feat:venue: add nonHumanizedId to pro response

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13474
Petite faille détectée par notre chère PO : après DMS on peut activer un utilisateur même s'il n'a pas rempli l'étape du profil.
> (PC-13474)[API] feat: add check on profile completion

- api/src/pcapi/core/mails/backends/sendinblue.py
- api/src/pcapi/tasks/serialization/sendinblue_tasks.py
- api/tests/core/mails/transactional/pro/reset_password_to_pro_test.py
- api/tests/core/mails/transactional/test_send_transactional_email.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13589
Problème résolu: les emails sans template_id ne sont pas envoyés. Problème avec la dataclass SendinblueTransactionalEmailData où il manquait des champs optionnels
N/A
N/A
> (PC-13589)[PRO]fix: sendinblue email without template pydantic error

- api/requirements.txt
This new version does not have any upper limit on the version of
`httpx`, which lets us use httpx 0.18.0 (at least), which fixes a
warning (about an ignored exception) that is displayed when running
`flask shell` (or anything that imports "dns.query"):
$ python -c "import dns.query"
Exception ignored in: <function Client.__del__ at 0x7fce48ffc1f0>
File ".../site-packages/httpx/_client.py", line 1134, in __del__
self.close()
File ".../site-packages/httpx/_client.py", line 1106, in close
self._transport.close()
AttributeError: 'Client' object has no attribute '_transport'
See encode/httpx@b43af721cd7804214396b5511e4f for the fix in httpx.
> [bsr][api][requirements] Bump notion-client

- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/routes/external/users_subscription.py
- api/tests/core/fraud/dms/test_api.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13592
- Créer un fraud check en cas d'erreur de parsing ou d'éligibilité, pour tracer rapidement où en est le dossier, et pourquoi
> PC-13592 save fraud check on dms errors

- api/src/pcapi/domain/admin_emails.py
- api/tests/domain/admin_emails_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9976
Aujourd’hui, les biz reçoivent tous les mails de création d’offres des acteurs : création de DVD, de CD, de vinyles… Ils souhaiteraient ne plus recevoir les mails liés aux CD, DVD, livres et vinyles.
Après discussion avec Caroline Nerot, il a été proposé de ne pas envoyer le mail “Création d’offre” (cf. [code ici](https://github.com/pass-culture/pass-culture-main/blob/2c0a4eb2c62211ef1e6508189015254fd995103a/api/src/pcapi/utils/mailing.py#L202-L222)) lorsque l’offre appartient aux 16 sous-catégories suivantes : 
* ABO_JEU_VIDEO
* ABO_LIVRE_NUMERIQUE
* ACHAT_INSTRUMENT
* AUTRE_SUPPORT_NUMERIQUE 
* BON_ACHAT_INSTRUMENT
* LIVRE_AUDIO_PHYSIQUE 
* LIVRE_NUMERIQUE
* LIVRE_PAPIER
* LOCATION_INSTRUMENT
* …
> (PC-9976)[API] Add Offer Subcategory verification before send

- api/src/pcapi/admin/custom_views/booking_view.py
- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/templates/admin/booking.html
- api/tests/admin/custom_views/booking_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13269
Permettre au support d'annuler une contremarque dans l'état USED (mais pas encore remboursée).
Utilisation du paramètre `cancel_even_if_used` ajouté récemment par https://passculture.atlassian.net/browse/PC-13321
C'était peut-être un bug, puisque le bouton était affiché dans l'état USED, mais en cliquant sur le bouton rouge le message _flash_ indiquait une réussite de l'annulation, alors que rien n'avait changé dans la base de données.
J'ai donc corrigé la propagation des exceptions pour obtenir le message d'erreur dans Flask-Admin lorsqu'une erreur se produit.
J'ai également ajouté l'état de la réservation dans l'écran `booking_view`, ça ne coûte pas cher et c'est plus clair.
- Branche : …
> (PC-13269)[API] Cancel booking with status=USED from Flask Admin

- api/src/pcapi/admin/custom_views/user_offerer_view.py
- api/tests/admin/custom_views/user_offerer_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13568
Corriger le bug : une exception se produit lors de la suppression d'une relation UserOfferer dans Flask-Admin : 
`ERROR:pcapi.routes.error_handlers.generic_error_handlers:Unexpected error on method=POST url=http://localhost:5000/pc/back-office/userofferer/delete/: Parent instance <UserOfferer at 0x7fa614ef6730> is not bound to a Session; lazy load operation of attribute 'user' cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)`
> (PC-13568)[API] Fix deletion of UserOfferer association in FA

- api/src/pcapi/routes/external/users_subscription.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13592
Fix la mauvaise utilisation des ids de DMS
> (PC-13592)[API] fix: use DMS application id instead of the dossier id

- .circleci/config.yml
Les tests de `tests/core/users/external` sont actuellement très longs (environ 2 minutes).
En attendant de les optimiser, on les exécute dans un job parallèle aux 3 autres afin de raccourcir la durée des pipelines.
Edition du fichier `.circleci/config.yml`
> (PC-13646) Ajouter un job parallèle pour des tests lents d'api

- api/src/pcapi/admin/custom_views/criteria_view.py
- api/tests/admin/custom_views/criteria_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11806
Les noms des nouveaux tags ne doivent pas contenir de caractères d'espacement
Ajout d'un validateur sur une expression régulière
> (PC-11806)[API] No whitespace allowed in tag name when creating a new tag

- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13609
Supprimer la déduplication des offres qui ont le même visa d'exploitation.
Contexte: aujourd'hui beaucoup d'acteurs se plaignent de ne pas voir apparaître à la fois les films en VO et en VF dans leurs résultats de recherche.
> (PC-13609) algolia: remove visa from algolia distinct field

- pro/src/components/pages/Signup/SignupValidation/SignupValidation.jsx
- pro/src/components/pages/Signup/SignupValidation/__specs__/SignupValidation.spec.jsx
- pro/src/repository/pcapi/pcapi.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13192
retirer redux saga-data de SignupValidation
> (PC-13192)[PRO] remove redux-saga-data from SignupValidation

- pro/src/components/pages/Signup/SignupForm/SignupFormContainer.js
- pro/src/components/pages/Signup/SignupForm/__specs__/SignupFormContainer.spec.js
- pro/src/repository/pcapi/pcapi.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13191
Retirer redux saga data de SignupFormContainer
> (PC-13191)[PRO] remove redux-saga-data from SignupFormContainer

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueImageDelete/VenueImageDelete.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13106
Suite à un retour graphique, on agrandit, sur la modale de suppression de visuel de lieu, l'écart entre le contenu et les boutons.
| Retour graphique | Nouvelle implémentation |
| :---: | :---:|
| ![image](https://user-images.githubusercontent.com/26742386/155502945-752d2023-3285-4713-b381-a4db9f5e9f8f.png) | ![image](https://user-images.githubusercontent.com/26742386/155502564-38c3792d-65fe-44b6-8574-4276a850afe0.png) |
> (PC-13106) Fix venue image delete modal design

- pro/src/app/App.jsx
- pro/src/components/layout/Header/Header.jsx
- pro/src/store/features/actions.js
- pro/src/store/features/reducer.js
- pro/src/store/user/actions.js
- pro/src/store/user/reducer.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13194
App tentait de s'afficher lorsque l'on déloggait le user et ProfileAndSupport cassait car user n'etait pas défini.
> [PC-13194][PRO] useCurrentUser: fix signout

- pro/src/components/pages/Offers/Offer/Stocks/DeleteStockDialog/DeleteStockDialog.jsx
- pro/src/components/pages/Offers/Offer/Stocks/StockItem/StockItem.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13653
Lors de la suppression d'un stock non event, ne pas affichées le wording "validées"
> (PC-13653)[PRO] fix: fix wording for non event offers on stock deletion

- api/src/pcapi/admin/custom_views/offer_view.py
- api/tests/admin/custom_views/offer_view_test.py
Computing the score for each offer may make additional SQL queries if
we did not join the right table(s) beforehand. We were already bitten
by this in last December (see 981fc3f5c). The page is slow again
because of a new validation rule that selects all offers of the venue
of the offer we want the score of. Doing that for each of the 100
offers that are shown in the list view is not a good idea...
It appears that showing the score in the list view is not strictly
necessary. We can remove it. It's still shown in the validation page
for a single offer, and that's enough.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13667
> [PC-13667][api][admin] Do no show score on offer validation list view

- .jira.d/templates/edit
The custom field used to be a string type field on Jira.
It changed to an integer type. We need to edit the template so it reflects this changes.
> (BSR) Fix annotation github action

- api/src/pcapi/core/offers/offer_validation.py
If the score is zero, it won't increase anymore. No need to check
other validation rules.
> [bsr][api][offers] Optimize `compute_offer_validation_score()`

- api/src/pcapi/connectors/beneficiaries/educonnect/educonnect_connector.py
- api/src/pcapi/connectors/dms/api.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/fraud/utils.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/messages.py
- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/src/pcapi/serialization/utils.py
- api/tests/core/fraud/utils_test.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/scripts/beneficiary/fixture.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13307
Notre API refuse les utilisateurs dont les nom/prénom ne sont pas en caractères latins. DMS ne fait pas ce filtre. Cette PR fait deux choses : 
- Lors des dépôts de dossier DMS, on veut alerter l'utilisateur qu'il a mal renseigné ses informations et lui donner la chance de modifier sur DMS.
- Lors de l'import des dossiers validés par DMS, on invalide les dossiers mal renseignés et on remonte un subscription message pour l'utilisateur.
- Branche : …
> (PC-13307)[api] handle invalid name format dms

- api/src/pcapi/routes/apis.py
- api/src/pcapi/routes/native/v1/blueprint.py
- api/src/pcapi/routes/pro/blueprint.py
- api/src/pcapi/routes/pro/bookings.py
- api/src/pcapi/serialization/decorator.py
- api/src/pcapi/serialization/spec_tree.py
- api/tests/routes/native/v1/openapi_test.py
- api/tests/routes/pro/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13535
Le format des nom de fonction du client javascript ne sont pas tres jolie.Nous avons par example : `getuserstokentoken`. Ce nom vient du champs du schema openapi `operationId`. Pour `getuserstokentoken` nous avons `operationId: '/users/token/{token}'` La transformation est faite par [le generateur de code ici](https://github.com/wcandillon/swagger-js-codegen/blob/master/lib/codegen.js#L80). 
Si on regarde le code api:
```javascript
@private_api.route("/users/token/<token>", methods=["GET"])
@spectree_serialize(on_error_statuses=[404], on_success_status=204)
def check_activation_token_exists(token: str) -> None:
```
nous aimerions avoir une `operationId` qui serait: `getUsersCheckActivationTokenExist` ou …
> [PC-13535][PC-13579][API] Spectree: customise schema operationId

- api/src/pcapi/core/mails/backends/sendinblue.py
- api/src/pcapi/core/mails/models/sendinblue_models.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_to_pro.py
- api/src/pcapi/core/mails/transactional/bookings/new_booking_to_pro.py
- api/src/pcapi/core/mails/transactional/send_transactional_email.py
- api/src/pcapi/tasks/serialization/sendinblue_tasks.py
- api/tests/core/mails/transactional/bookings/booking_cancellation_by_beneficiary_to_pro_test.py
- api/tests/core/mails/transactional/bookings/new_booking_to_pro_test.py
- api/tests/core/mails/transactional/test_send_transactional_email.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13666
Ajout de la possibilité de définir le mail de réponse (le reply_to) lors de la définition d'un template de mail
2 mails concernés mis à jour pour empêcher une sur-sollicitation du support
> (PC-13666)[PRO]fix: sendinblue reply_to in template 376 379

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/criteria_view.py
- api/src/pcapi/admin/custom_views/offerer_tag_view.py
- api/src/pcapi/admin/custom_views/offerer_view.py
- api/src/pcapi/admin/install.py
- api/src/pcapi/alembic/versions/20220224T135029_ca95cbf376a1_create_offerer_tag_table.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/repository/clean_database.py
- api/tests/admin/custom_views/criteria_view_test.py
- api/tests/admin/custom_views/offerer_tag_view_test.py
- api/tests/admin/custom_views/offerer_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9892
Pouvoir définir des tags sur des structures, à des fins de filtrage dans le backoffice et de suivi dans metabase.
Règles de gestion dans le ticket https://passculture.atlassian.net/browse/PC-9892
J'ai en même temps ajouté la vérification de la longueur des tags des offres et lieux ; on avait une exception en saisissant plus de 140 caractères.
> (PC-9892)[API] Set tags on offerers

- api/tests/core/users/external/external_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13684
Réduire le temps d'exécution du test unitaire controversé `test_update_external_pro_user_attributes`
Réduire le nombre de combinaisons.
De 288 combinaisons par l'effet de 7 `parametrize`, j'en ai gardé 6 en un seul `parametrize`.
Cela devrait suffire à couvrir les attributs pro de manière satisfaisante.
Temps d'exécution passé de 57 secondes à 2,7 secondes pour le fichier `tests/core/users/external/external_pro_test.py`
> (PC-13684)[API] Optimize pro attributes unit test

- api/src/pcapi/routes/pro/venues.py
- api/tests/routes/pro/delete_venue_banner_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13608
FIX : ajout de l'appel à `check_user_has_access_to_offerer` avant la suppression de l'image d'un lieu.
Sans ça, n'importe quel utilisateur authentifié peut supprimer l'image de n'importe quel lieu.
> (PC-13608) [API] fix:venue: check right access before rm banner

- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/users/external/__init__.py
- api/src/pcapi/core/users/external/models.py
- api/tests/core/users/external/external_pro_test.py
- api/tests/core/users/external/external_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13688
Changement de spécification sur l’attribut pro `venue_count` envoyé à Sendinblue : ne pas prendre en compte uniquement les lieux rattachés, par leur structure, à l’email de l’utilisateur comme spécifié initialement, mais aussi les lieux qui ont l’adresse email en tant que `bookingEmail`
Ne compter qu’une seule fois  si le lieu a comme `bookingEmail` l’adresse email d’un utilisateur rattaché à la structure parente du lieu
> (PC-13688)[API] Pro attributes: include venues with bookingEmail in venue_count

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/routes/native/v1/serialization/subscription.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/openapi_test.py
- api/tests/routes/native/v1/subscription_test.py
- api/tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13477
- Rendre obligatoire les champs activityId et adresse de la route de mise à jour du profile. On enlève le champs `activity` (il ne devrait pas y avoir de breaking change car l'application native n'envoie plus ce champs depuis une version antérieure à la version dont on a forcé la màj (v1.166.0) fin décembre.
- L'étape profile est maintenant complétée si l'utilisateur a une ville ET une activité renseignées.
> (PC-13477)[API] subscription: make activity mandatory for profile completion

- api/src/pcapi/core/cultural_survey/cultural_survey.py
- api/src/pcapi/core/cultural_survey/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13333
- Ajout des classes `CulturalSurveyAnswer` et `CulturalSurveyQuestion` pour le questionnaire des pratiques initiales.
- Instanciation des différentes questions et réponses
> (PC-13333)[API] feat: add CulturalSurvey questions and answers

- api/src/pcapi/models/feature.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13332
Ajout du Feature flag qui permettra d'activer le questionnaire des pratiques initiales sur l'app native.
Ajout au fichier `feature.py` et désactivation par défaut.
> (PC-13332)[API] feat: add ENABLE_NATIVE_CULTURAL_SURVEY feature flag

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13716
Suppression d'un appel à un Grafana décommisionné empêchant le step `release-synthesis` d'être ✅
> (PC-13716)[API] ci: remove call to former Grafana during deploiement

- api/src/pcapi/core/subscription/dms/api.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12592
Enregistrer un dossier comme orphelin si on ne trouve pas l'utilisateur associé dans le webhook
Permet l'adoption à l'inscription après, sans avoir à attendre le cron
> (PC-12592)[API] fix: create orphan dms application in the webhook

- api/src/pcapi/core/mails/transactional/pro/event_offer_postponed_confirmation_to_pro.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/offers/api.py
- api/tests/core/mails/transactional/pro/event_offer_postponed_confirmation_to_pro_test.py
- api/tests/core/offers/test_api.py
/!\ Manque quelques tests unitaires -> Done
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13401
Envoi un email à l'acteur lorsque le stock d'une offre de type event est updaté
N/A
N/A
> (PC-13401)[PRO]feat: sib email to pro when stock update on an event offer

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
- api/tests/routes/native/v1/subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13721
- Tant qu'on a pas le nom + prénom de l'utilisateur, la prochaine étape d'activation doit être la complétion du profil
- Rendre ces deux champs obligatoirement non vides pour valider la complétion du profile dans le calcul des prochaines steps
- Fix un bug qui permettait de démarrer un dossier Ubble, sans nom + prénom. Ubble remonte alors les dossiers comme suspicieux car il n'a pas de noms pour comparer à celui de la pièce d'ID
> (PC-13721) add firstName and lastName to the fields necessary for profile completion

- api/src/pcapi/admin/custom_views/offerer_view.py
- api/tests/admin/custom_views/offerer_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13728
Corriger une exception remontée par Sentry lorsqu'on tente de supprimer une structure qui :
- n'a pas de réservations
- est liée à au moins un utilisateur pro (relation user_offerer)
Même correction que la même exception dans `user_offerer_view.py` vue dans PC-13568
> (PC-13728)[api] Fix exception when an offerer is deleted

- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/exceptions.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/pro/stocks.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/patch_shadow_stock_into_educational_stock_test.py
- api/tests/routes/pro/post_offer_test.py
- api/tests/routes/pro/post_shadow_stock_for_educational_showcase_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13545
- Dupliquer la création d'offre dans les nouveaux modèles CollectiveOffer et CollectiveOfferTemplate
3 étapes:
- à la création d'offre DRAFT, avant la création du stock, on duplique l'offre actuelle dans une CollectiveOffer
- à la réception du stock côté API:
- Si l'option offre vitrine a été sélectionnée : Création d'une CollectiveOfferTemplate et suppression de la CollectiveOffer précédente
- au switch offre vitrine -> offre collective effective => suppression du template et recréation d'une CollectiveOffer
- Branche : …
> Pc 13545/duplicate collective offer creation in new models

- api/src/pcapi/admin/custom_views/cultural_survey_view.py
- api/src/pcapi/admin/install.py
- api/src/pcapi/core/cultural_survey/cultural_survey.py
- api/src/pcapi/templates/admin/cultural_survey.html
- api/tests/admin/custom_views/cultural_survey_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13334
Ajout des questions et réponses correspondantes du Questionnaire de Pratiques initiales dans la route `pc/back-office/cultural_survey_answers/` sur FlaskAdmin
- Création d'un template html dédié
> (PC-13334)[API] feat: add cultural survey questions to back office

- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/mails/transactional/educational/eac_new_prebooking_to_pro.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/tests/core/educational/test_api.py
- api/tests/core/mails/transactional/educational/eac_new_prebooking_to_pro_test.py
En attente --> nom établissement scolaire -> ok
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13403
envoi un email lorsqu'une institution fait un prebooking
> (PC-13403)[PRO]feat: sib email when eac new prebooking to pro

- api/src/pcapi/templates/invoices/invoice.html
- api/tests/files/invoice/rendered_invoice.html
The HTML template uses the `font-display: swap` CSS directive that is
only useful for the HTML version of the invoice. As per the
documentation of Google Fonts [1]:
swap gives the font face a zero second block period and an
infinite swap period. This means the browser draws text
immediately with a fallback if the font face isn’t loaded, but
swaps the font face in as soon as it loads.
weasyprint (that transforms HTML into PDF) does not support it and
issues multiple warnings for each generated PDF file, such as:
Ignored `font-display: swap` at 5:3, descriptor not supported.
Since we do not display the HTML and only convert it to PDF, we can
get rid of the CSS directive.
[1] https://developers.google.com/web/updates/2016/02/font-display#swap:
Lien vers le ticket Jira : …
> [PC-13748][api][finance] Do not use `swap` CSS directive for invoice PDF

- api/requirements.txt
This reverts commit b2353d5d0bfe204fdd6d345b33d713914139ca92.
We added IPython mostly for the auto-completion, when we were using
Flask 1. Now we have migrated to Flask 2 that provides that feature.
We thus do not really need IPython.
---
Autre possibilité, conserver (mais personnaliser IPython) : #1144
> [bsr][api] Suppression de IPython pour "flask shell"

- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/core/finance/repository.py
- api/tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13522
Empêcher de pouvoir attribuer à un lieu un SIRET déjà affecté à une BusinessUnit dans le formulaire d'édition de lieu sur FA.
Modification de `VenueView`
Au passage, réorganisation des imports
> (PC-13522) add rule on siret in VenueView

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220303T150600_7ffe3aac83d2_unique_offer_criterion.py
- api/src/pcapi/alembic/versions/20220303T150700_25666068cabb_unique_venue_criterion.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/models/offer_criterion.py
- api/tests/core/offerers/test_models.py
- api/tests/core/offers/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13790
Ajouter des containtes `UNIQUE` sur les tables `offer_criterion` et `venue_criterion`, de la même manière que ce qui existe dans la table `offerer_tag_mapping`, afin d'éviter les doublons.
Ce ticket vient d'une exception remontée par Sentry à la suppression.
À la migration, suppression de tous les doublons. 12002 lignes sont concernées sur staging.
> (PC-13790)[api] Add unique constraints for offer_criterion and venue_criterion

- api/src/pcapi/admin/custom_views/offerer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/admin/install.py
- api/src/pcapi/templates/admin/offerer_venues_list.html
- api/tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13700
Dans la liste des structures dans le backoffice, ajouter une colonne proposant un lien vers les lieux associés, qui ouvre une page avec la liste des lieux de la structure.
Similaire à l'affichage de la liste des offres pour un lieu.
Captures d'écran dans le ticket Jira
> (PC-13700)[api] Show venues for offerers in Flask Admin

- api/src/pcapi/admin/custom_views/offerer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/core/users/external/__init__.py
- api/src/pcapi/core/users/external/models.py
- api/tests/admin/custom_views/offerer_view_test.py
- api/tests/admin/custom_views/venue_view_test.py
- api/tests/core/users/external/external_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13699
Désactivation de structures depuis Flask Admin
Reprise partielle de la PR https://github.com/pass-culture/pass-culture-main/pull/1591 après discussion avec Charlotte, Damien, Hadidja. On enlève la désactivation des lieux car l'équipe pro n'a pas la bande passante pour interpréter ce nouveau statut et gérer l'affichage ou non en conséquence dans le portail pro.
+ Test de la suppression et correction de la sélection des emails dont les attributs pro sont à mettre à jour
+ On ne prend pas les structures désactivées, ni les lieux associés aux structures désactivées, dans le calcul des attributs pro.
- Commit(s) : …
> (PC-13699)[api] Deactivate offferers from Flask Admin

- api/src/pcapi/core/offerers/exceptions.py
- api/src/pcapi/routes/pro/venues.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/post_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13800
Renvoyer une erreur 400, au lieu d'une 500, lorsque l'utilisateur (PRO) qui souhaite ajouter une image à un lieu n'envoie pas les bons paramètres (image manquante, etc.)
Le problème était lié au fait qu'on générait des erreurs via le modèle pydantic et qu'on ne les ignorait royalement.
> (PC-13800)[API] fix: return 400 code on user error

- api/src/pcapi/admin/custom_views/venue_view.py
Lien vers les tickets Jira : 
https://passculture.atlassian.net/browse/PC-13794
https://passculture.atlassian.net/browse/PC-13810
Visualiser le type et le label d'un lieu sur Flask Admin
> (PC-13794)(PC-13810)[api] Show venue type and venue label in Flask Admin

- api/src/pcapi/core/subscription/ubble/archive_past_identification_pictures.py
- api/tests/core/subscription/ubble/archive_past_identifications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12398
- correction de la requête pour archiver les images ubble.
- ajout d'une contrainte offset sur la requête sql
> Pc 12398 fix archive ubble pictures command

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
`Stock.fieldsUpdated` indicates which attributes have been customized,
so that they are not overwritten when the stock is synchronized from
Allociné.
If we first customize the quantity and then customize the price, we
must store both attributes, not only the latter.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13870
> [PC-13870][api][offers] Properly update `Stock.fieldsUpdated` on Allociné stock edition

- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/core/criteria/api.py
- api/src/pcapi/core/offers/factories.py
- api/tests/core/criteria/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13717 
Permettre d'ajouter/éditer des tags de lieux via la sélection multiple, sur `flask admin` (index des lieux)
1. Même fonctionnement que pour les offres.
2. Création d'un module `core.criteria.api` pour gérer ce qui touche aux tags (`criteria`), pour l'instant il n'y a que la mise à jour de plusieurs objets d'un coup.
Je me suis permis de reprendre la logique de zéro pour ce qui est de la création des tags ; l'implémentation précédente (dans le module `offer_view`) nécessitait une requête pour chaque tag de chaque offre afin de déterminer le nombre de `OfferCriterion` à créer, ce qui me semblait un peu risqué.
> [API] PC 13717 fa tags venues

- infra/pc_scripts/start_backend.sh
Lien vers le ticket Jira : pas de ticket
Réparer le script qui détecte la version de docker-compose (il renvoyait le message "This script requires docker-compose 1.24 or greater" alors que ma version de docker-compose  est 2.3.0)
- Modification de la regex
> (BSR)[API] chore: update detection of docker-compose version

- api/src/pcapi/core/users/factories.py
- api/src/pcapi/scripts/beneficiary/update_gender_and_married_name_from_ubble.py
- api/tests/scripts/beneficiary/update_gender_and_married_name_from_ubble_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13672
Depuis janvier, Ubble nous transmet deux champs `gender` et `married_name`
Depuis le ticket [#12929](https://passculture.atlassian.net/browse/PC-13672) on récupère ces données et on les enregistre dans `User`
Ce script a pour but de mettre à jour les utilisateurs qui ont été activés entre début janvier et le moment où ce ticket est passé en prod (Aujourd'hui en fait)
- Get tout les bénéficiaires sans gender ni married_name, qui sont passés par Ubble, depuis le 1er janvier
- yield_per 1000 
- Update si on a des données chez Ubble
- Avec un dry_run pour tester en prod avant d'update
- Ce script a pur but d'être run qu'une seule fois
- PR : `(PC-XXX) Description …
> (PC-13672)[API] feat: write script to update all gender and married_name attributes from ubble

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/monkeypatches.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/scheduled_tasks/clock.py
- api/src/pcapi/scripts/booking/handle_expired_bookings.py
- api/tests/core/bookings/test_api.py
- api/tests/core/offers/test_repository.py
- api/tests/scripts/booking/handle_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13423
Adapter les différents crons liés aux offres aux CollectiveOffers
update_booking_used
handle_expired_bookings
clean_past_draft_offers
> Pc 13423/duplicate cron operations for collective offers stocks bookings

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
The SIRET of some venues have been edited but we forgot to update the
same SIRET of their business unit. Thus, we have some business units
that have a SIRET that is not a SIRET of any venue. As such, the
current _inner_ join excludes them in `business_units.csv` and their
pricings from `payments_details.csv`.
The bogus SIRET edition should not happen and it will soon be blocked.
In the meantime, we must not exclude these business units and their
pricings from those files. We do that by using an _outer_ join.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13881
> [PC-13881][api][finance] Include unlinked business units in CSV files

- api/src/pcapi/core/search/backends/algolia.py
- api/src/pcapi/core/search/backends/base.py
- api/src/pcapi/local_providers/allocine/allocine_stocks.py
- api/tests/core/search/test_serialize_algolia.py
- api/tests/local_providers/allocine_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13609
Actuellement, s'il y a des séances de cinéma en VO et VF, on ne voit qu'une seule offre
Il nous a été demandé d'afficher 2 offres
- on stock l'information de la version de la séance diffusée qui nous est donné par Allociné
- on change ajoute la version de la séance diffusée sur le champ qui permet de distinguer 2 offres sur Algolia
> (PC-13609)[API] feat:search: theater distinct vo vf

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/alembic/versions/20220309T101015_f5a5da60e349_add_validation_type_to_offer.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/factories.py
- api/src/pcapi/models/offer_mixin.py
- api/tests/admin/custom_views/offer_view_test.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11415
Conserver et afficher le type de validation d'une offre :
- AUTO si elle a été validée automatiquement par le code (respectant les règles de conformité)
- MANUAL si le dernier état de validation vient d'une action sur le backoffice
Mise à jour de `lastValidationType` synchronisée avec le champ `lastValidationDate` déjà présent
L'idée de créer une table d'historique des actions manuelles de validation a été écartée au niveau PM car ne correspond pas à un besoin exprimé par le métier. Le besoin aujourd'hui est à des fins statistiques sur metabase.
> (PC-11415)[api] Save validation type (auto or manual) to offers

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/logging.py
- api/src/pcapi/core/offers/api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13711
En tant que DS,
J’aimerai avoir un nouveau champs dans les logs backend indiquant si la log doit aller dans la base analytics
Afin d’automatiser l’import de nouveaux types de logs en se basant uniquement sur ce champs lors du sink
Un nouveau champs booléen présent dans toutes les logs backend et set à False par défault
Le champs est set à True pour les logs de la fiche [notion suivante ](https://www.notion.so/passcultureapp/Liste-de-logs-pour-la-V0-ff1c55243e7f426b848da94926c2041f)
> (PC-13711)[API] feat: Add Technical Message ID in Logger

- api/mypy.ini
- api/requirements.txt
- api/src/pcapi/core/fraud/models.py
Améliorr les checks de mypy, pour rendre le typage moins painful 
- Ajouter une lib pour inférer les types des colonnes des modèles
- Ignorer les migrations et tests 
- Fix aussi un import de sqla
> (BSR) Improve mypy checks

- pro/src/styles/components/pages/LostPassword/_LostPassword.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13820
Ajuster la marge entre le champs texte et le tooltip pour être uniforme avec la page de création de compte
> (PC-13820)[PRO] fix: adjust tooltip margin

- api/src/pcapi/core/logging.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13711
En tant que DS,
J’aimerai avoir un nouveau champs dans les logs backend indiquant si la log doit aller dans la base analytics
Afin d’automatiser l’import de nouveaux types de logs en se basant uniquement sur ce champs lors du sink
Un nouveau champs booléen présent dans toutes les logs backend et set à False par défault
Le champs est set à True pour les logs de la fiche [notion suivante ](https://www.notion.so/passcultureapp/Liste-de-logs-pour-la-V0-ff1c55243e7f426b848da94926c2041f)
> (PC-13711)[API] feat: Update custom logger to have technical_message_id in test environments

- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/scripts/payment/user_recredit_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13927
- Ce matin, aucun des jeunes éligible à leur recrédit n'était recrédité
- Pourquoi ? Parce que le script a planté
- Pourquoi ? Parce que d'anciens fraud checks n'avaient pas de `reistration_datetime` et qu'on ne catchait pas d'erreurs
- Catch et utiliser la date de création du fraud check à la place
RAS
> (PC-13927)[API] fix: fix recredit underage users script

- pro/src/components/pages/Home/Offerers/Offerers.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13813
Ne pas afficher le message Structure désactivée quand la structure n'est pas encore validée
- ajout d'une condition pour définir la constante `isOffererSoftDeleted`
- pour reproduire, se connecter avec marie.destandau@passculture.app et aller sur https://pro.testing.passculture.team/accueil?structure=3Y
> (PC-13813)[PRO] fix: add condition to hide SoftDeleted message when the structure is not validated

- .github/workflows/debt-collector-pro.yml
- pro/.debt-collector/README.md
- pro/README.md
Nous somme spamés par debt-collector qui poste un commentaire à chaque push.
En suivant [cette documentation](https://github.com/marketplace/actions/create-or-update-comment), je tente ici de résoudre ce problème en mettant le commentaire existant à jours.
Voici une PR sur le laquelle ces changement on été testé: https://github.com/pass-culture/pass-culture-main/pull/1704
> (PC-13974)[PRO] debt-collector: create or update comment

- api/requirements.txt
It's not needed anymore since 84bd6afd45ef43365c6abe7af476b7acae5f1.
> [bsr][api][requirements] Remove dependency on lxml

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/educational/exceptions.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/educational/validation.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/stocks.py
- api/tests/core/educational/test_api.py
- api/tests/routes/adage/v1/confirm_prebooking_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13548
On continue le doublonage pour EAC collectif. Ce coup ci c'est l'edition des bookings.
> (PC-13548)[API] feat: double stock collective update

- .github/workflows/debt-collector-pro.yml
.. when we got changes in /pro
==============
Suite au modification du workflow mergé ce matin, debt-collector se lançait partiellement meme lorsqu'il n'y avait pas de modification sur `/pro/*`.
Let's fix it !
> (BSR)[PRO] fix: debt-collector should only run..

- api/src/pcapi/core/bookings/api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13423
Dans le cron `auto_mark_as_used`, on filtrait sur les reservations collectives CONFIRMED ou PENDING.
Il ne faut filtrer que sur les réservations CONFIRMED.
C'est plus un soucis de cohérence métier qu'un bug, car les réservations PENDING sont annulées lorsqu'on dépasse la date limite de confirmation (qui est au plus tard la date de l'évènement) …
> (PC-13423)[API] chore: change filter to exclude PENDING collective booking from mark_as_used cron

- pro/src/components/pages/Home/Offerers/Offerers.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13813
Empêcher l'affichage du bloc Structure désactivée quand l'ajout est en cours de validation
- mise à jour de la condition pour vérifier si l'offerer a bien été récupérée (`selectedOfferer` ne suffisait pas car quand on a une 403 on le set ligne 78, et `!selectedOfferer.isActive` était vraie aussi quand `isActive` était `undefined`)
> (PC-13813)[PRO] fix: check if the selectedOfferer.isValidated is set to false

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220311T144938_635158569c89_.py
- api/src/pcapi/connectors/dms/api.py
- api/src/pcapi/connectors/dms/models.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/fraud/ubble/models.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/serialization/users.py
- api/src/pcapi/scripts/beneficiary/update_gender_and_married_name_from_ubble.py
- api/tests/core/subscription/test_api.py
- api/tests/core/subscription/test_factories.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/pro/get_user_profile_test.py
- api/tests/routes/pro/signin_test.py
- api/tests/scripts/beneficiary/fixture.py
- api/tests/scripts/beneficiary/import_dms_users_test.py
- api/tests/scripts/beneficiary/update_gender_and_married_name_from_ubble_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13672
La colonne `civility` existe déjà (Anciennement remplie par Jouve) 
La colonne `gender` est donc redondante
- Retirer la colonne `gender`
- Sauver le gender de Ubble dans `civility`
- Ajoute un catch de HTTPError dansle script de rattrapage
> (PC-13672) Save gender in civility column

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/mails/backends/base.py
- api/src/pcapi/core/mails/backends/testing.py
- api/tests/core/bookings/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14000
relié l'envoi de mail d'annulation de réservation aux jeunes et pro
lorsque l'api contremarque est utilisé (lors de l'annulation d'une réservation par un AC)
> (PC-14000)[API] fix: sib email when booking cancelled by pro

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13939
Corrige le bon fonctionnement de la mise à jour en masse d'offres quand.... il n'y a pas d'offre mise à jour.
> (PC-13939)[API] fix: Fix batch offer update with no affected offer

- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/scripts/beneficiary/update_gender_and_married_name_from_ubble.py
- api/tests/admin/custom_views/support_view_test.py
- api/tests/core/subscription/test_api.py
- api/tests/core/subscription/ubble/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/pro/get_user_profile_test.py
- api/tests/routes/pro/signin_test.py
- api/tests/scripts/beneficiary/update_gender_and_married_name_from_ubble_test.py
Rollback sur le typage de la colonne `civility` de User
A l'affichage dans flask admin, la contrainte sur le type de valeur fait crasher FA sur les valeurs existantes 
> [API] fix: allow any text for civility to avoid crash on existing data

- pro/src/components/pages/Signup/SignupForm/SignupForm.jsx
- pro/src/components/pages/Signup/SignupForm/__specs__/SignupForm.spec.jsx
- pro/src/new_components/Banner/BannerRGS.tsx
- pro/src/new_components/Banner/__specs__/BannerRGS.spec.tsx
- pro/src/new_components/Banner/index.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13937
Ajout d'un bandeau informatif RGS sur la page de création de compte
- ui-kit component Banner
> (PC-13937)[PRO] feat: add RGS informative banner on SignUp page

- .circleci/config.yml
- api/README.md
- api/pytest.ini
CircleCI got a parallelism mechanism which check for tests timing before separating the different files.
This pull request aims to use this mechanism instead of the home-made one to go faster and have a more sustainable solution
> (BSR) Use circle ci parallelism instead of custom config

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/models/feature.py
- api/tests/core/fraud/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14067
Désactiver les controles sur les noms en test + staging à la demande, parce que les users de tests Educonnect ont tous des chiffres dans leurs noms
> [PC-14067] add feature flag for name format control in testing

- api/src/pcapi/core/fraud/models.py
- api/tests/core/fraud/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13673
Les formats de dates de naissance sur les fraud checks jouve ressemblent à ceci:
On veut pouvoir les lire à l'activation de l'utilisateur
> (PC-13673)[API] fix: allow yyyy-mm-dd format in jouve birthDate

- adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
- adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/utils/formatDescription.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14065
Si un AC écrit un mail dans la description de son offre, on veut pouvoir ouvrir directement le client mail au clic
> (PC-14065)[ADAGE] feat: handle mail in description

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/fraud/ubble/models.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/tests/core/subscription/ubble/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14103
Evolution du statut pour le stockage des images d'identité Ubble.
Avant : On considérait que les images étaient stockées si on avait archivé l'image Front et l'image Back.
Désormais: On considère la réussite de l'archive si les images fournies par ubble sont bien stockées sur le bucket sécurisé.
Pourquoi ? 
Pour certain type de pièce d'identité (passport), Ubble nous remonte uniquement l'image Front ce qui était considéré comme une erreur jusqu'alors.
- changement de critère de succès sur le stockage froid des images d'identification des jeunes.
> (PC-14103)[API] feat: change ubble image archive rules for passport

- api/src/pcapi/scripts/beneficiary/archive_dms_applications.py
- api/tests/scripts/beneficiary/archive_dms_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13668
Fixes https://sentry.internal-passculture.app/organizations/sentry/issues/363567/?project=5&referrer=slack
- Suite à l'oubli du script `archive_applications` lors de la refacto qui type les retours de DMS à l'aide de classes pydantic, on update l'accès aux données dans ce script
> (PC-13668)[API] fix: fix dms archive script

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/routes/pro/bookings.py
- api/src/pcapi/routes/serialization/bookings_recap_serialize.py
- api/tests/core/bookings/test_repository.py
- api/tests/routes/pro/get_all_bookings_test.py
- pro/src/components/pages/Bookings/PreFilters/FilterByBookingStatusPeriod/FilterByBookingStatusPeriod.tsx
- pro/src/components/pages/Bookings/PreFilters/PreFilters.jsx
- pro/src/components/pages/Bookings/__specs__/BookingsRecap.spec.jsx
- pro/src/repository/pcapi/pcapi.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13647
Page réservation : rendre le filtre de période optionnel si une date d’événement est renseignée.
> (PC-13647)[API][PRO] make bookings period filter optionnal when event date provided

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/educational/factories.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_institution.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/tests/routes/adage/v1/refuse_prebookings_test.py
- api/tests/scripts/booking/handle_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12934
- Utilisation du nouveau template d'email envoyé aux AC lorsqu'une réservation collective est annulée
- Il s'agit en fait du cas où une réservation est annulée par le chef d'établissement
- dans les fonctions api `refuse_educational_booking` et `refuse_collective_booking`, changement des data pour les envoyer au nouveau template
- changement du template dans la config SiB
> Pc 12934/get educational institution info for cancellation email to pro

- pro/package.json
- pro/src/components/layout/form/fields/TextField.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/LocationFields/AddressField.jsx
- pro/yarn.lock
Le passage à type-script des composants utilisant react-final-form nécessite de mettre à jours les types de la bibliothèque.
Voici une maj + fix vers la 6.8.1.
> (BSR)[PRO] chore: bump react-final-form to 6.8.1

- .gitignore
- pro/.gitignore
- pro/.vscode/extensions.json
- pro/.vscode/settings.json
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13950
👇  Ceci est une proposition !
Dans la config de VSCode sur Pro, ajouter l'autofix on save d'ESLint, et commiter cette config commune.
⚠️ config VSCode que pour PRO, en ouvrant VSCode au niveau du dossier `pro/`, pas à la racine de pass-culture-main.
> (PC-13950)[PRO] add eslint autofix on save

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/scripts/business_unit/rename_bu_not_matching_venue_public_name.py
- api/tests/core/finance/test_api.py
- api/tests/routes/pro/edit_business_unit_test.py
- api/tests/scripts/business_unit/rename_bu_not_matching_venue_public_name_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13938
Certains noms de business unit ne correspondent pas au nom du lieu auquel elles sont rattachées, l'objectif de cette PR est double : 
- Corriger via un script les noms incorrect quand la business unit possède un siret 
- Corriger la route permettant d'éditer le siret d'une business unit pour modifier le nom à ce moment là
> (PC-13938)[PRO] Fix bu name when not correponding to venue name

- api/requirements.txt
Version 0.812 requires `typed-ast<1.5`, for which there is no wheel
for one of our colleagues who uses a Mac M1, who hence has to compile
the library, which does not work, yada yada yada...
Let's use the latest version of mypy instead (which now requires
`typed-ast<2`, for which there _is_ a wheel).
(We should probably unpin mypy but it's not my call to make because I
don't use it.)
> [bsr][api][qa] Bump mypy version

- pro/src/components/pages/Signup/SignupConfirmation/SignupConfirmation.jsx
- pro/src/components/pages/Signup/SignupForm/SignupForm.jsx
- pro/src/components/pages/Signup/SignupForm/__specs__/SignupForm.spec.jsx
- pro/src/components/pages/Signup/SignupValidation/SignupValidation.jsx
- pro/src/components/pages/Signup/SignupValidation/__specs__/SignupValidation.spec.jsx
- pro/src/components/pages/Signup/__specs__/Signup.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14072
Migration des tests du SignUp Form
- transformation des fichiers `SignupValidation.spec.jsx`, `SignupForm.spec.jsx` et `Signup.spec.jsx`
- Le fichier `SignupFormContainer.spec.js` n'a pas été migré, je ne vois pas comment le passer en RTL tel quel, je le ferai lors de la refacto
- ajout d'une condition pour éviter l'appel à l'API de validation de token quand l'utilisateur est déjà loggé
- BSR: correction du texte alternatif dans `SignupConfirmation.jsx`
> (PC 14072)[PRO] test: migrate enzyme tests for SignUp Form to RTL

- pro/src/components/pages/Signup/SignupForm/SignupForm.jsx
- pro/src/styles/components/pages/Signin/_Signin.scss
- pro/src/styles/components/pages/SignupForm/_SignupForm.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13936 et https://passculture.atlassian.net/browse/PC-13937
Harmoniser l'espace blanc avant les boutons de validation de formulaire
- SignIn: modification de la valeur de la marge en bas
- Signup: ajout d'une div entourant les champs avant les boutons de validation, sur le même modèle que SignIn, et définition d'une marge en bas (boyscout: remplacement de la div vide d'espacement par une marge en haut sur cette nouvelle div)
> fix: harmonize spacing at the end of forms

- api/README.md
Lien vers le ticket Jira : pas de tiquet
Indiquer dans la doc la version de Python pour éviter des problèmes à l'installation
- README
> (BSR)[API] doc: indicate which version of Python to use

- api/src/pcapi/core/offers/repository.py
- api/tests/routes/pro/get_offers_test.py
- pro/src/api/v1/gen/api.ts
- pro/src/routes/Offers/CollectiveOffers/CollectiveOffers.tsx
- pro/src/routes/Offers/CollectiveOffers/index.ts
- pro/src/routes/Offers/IndividualOffers/IndividualOffers.tsx
- pro/src/routes/Offers/IndividualOffers/index.tsx
- pro/src/routes/Offers/Offers.tsx
- pro/src/routes/Offers/__specs__/Offers.spec.tsx
- pro/src/routes/Offers/adapters/getFilteredCollectiveOffersAdapter.ts
- pro/src/routes/Offers/adapters/index.ts
- pro/src/routes/Offers/adapters/serializers.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13519
- Création de 2 nouveaux composants dans le dossier `routes/Offers`
- `InvidividualOffers` et `CollectiveOffers`
- la logique est dupliquée pour l'instant (dans un prochain ticket les filtres vont changer)
- La route appelle l'un ou l'autre en fonction de la valeur du query param
> (PC-13519)[PRO] Visualize collective offers

- .circleci/config.yml
- api/pytest.ini
The glob was too laxist and caught non-test files, such as files in
`tests/files/` (amongst other directories). This caused an error
because there is a `pylint.py` file in this directory. Therefore,
`import pylint.testutils` (which appeared in a real test file) failed
with an ImportError because `import pylint` would import that
file (and not the `pylint` package).
I thought about using `pytest --collect-only` but it does not output
the path of all test files: sometimes the full path is displayed,
sometimes only the filename.
> [bsr][api][qa] Fix listing of test files in CircleCI configuration

- api/src/pcapi/connectors/dms/graphql/pro/get_banking_info_v2.graphql
- api/src/pcapi/domain/demarches_simplifiees.py
- api/src/pcapi/use_cases/save_venue_bank_informations.py
- api/tests/connector_creators/demarches_simplifiees_creators.py
- api/tests/domain/demarches_simplifiees_test.py
- api/tests/use_cases/save_venue_bank_informations_test.py
application_id et dossier_id sont 2 représentations de l'id d'un dossier, le premier un "Number" (entier), l'autre une string
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13207
cc [erreur sentry1](https://sentry.internal-passculture.app/organizations/sentry/issues/367384/?environment=testing&project=5&query=is%3Aunresolved&statsPeriod=14d) [erreur sentry2](https://sentry.internal-passculture.app/organizations/sentry/issues/367423/?environment=testing&project=5&query=is%3Aunresolved&statsPeriod=14d)
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, …
> (PC-13207)[API] fix: dossierModifierAnnotationText expects a "dossier_id" not an "application_id"

- api/src/pcapi/core/educational/models.py
- api/tests/core/educational/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14178
réparer l'attribut isSoldOut  des collectiveOffer colrs de son usage dans des query sqlalchemy
> (PC-14178)[API] fix: fix CollectiveOffer.isSoldOut in queries

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/scripts/algolia_indexing/commands.py
- api/src/pcapi/scripts/algolia_indexing/indexing.py
- api/src/pcapi/utils/chunks.py
- api/tests/core/offerers/test_api.py
- api/tests/scripts/algolia_indexing/indexing_test.py
- api/tests/utils/chunks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13524
Ajout d'une commande flask permettant de réindexer des lieux.
Au passage : ajout d'un nouveau module `pcapi.utils.chunks` qui ne contient qu'une fonction pour l'instant.
> (PC-13524)[API] feat:venues: add reindex venues command

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220316T115724_6ee927d299b1_make_ix_collective_stock_collectiveofferid_unique.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/educational/validation.py
- api/src/pcapi/routes/pro/stocks.py
- api/tests/routes/pro/post_educational_stock_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13888
Certaines requêtes concurrentes créaient deux stocks pour la même offre collective. Comme il ne peut y avoir qu'un stock par offre collective, nous avons ajouté une contrainte d'unicité sur l'index collectiveOfferId
À noter qu'il y a juste eu besoin de transformer l'index en index d'unicité. Il n'y a pas eu besoin d'ajouter une contrainte d'unicité ensuite. En effet, [comme indiqué ici](https://www.ibm.com/docs/en/db2/11.5?topic=indexes-unique-non-unique), la contrainte d'unicité correspond à index d'unicité + contrainte NOT NULL. La contrainte NOT NULL est déjà présente sur la colonne.
- _Explications sur l'utilisation d'outils peu communs …
> (PC-13888)[API] chore: add unique constraint on collectiveOfferId field in collective_stock table

- api/src/pcapi/templates/admin/edit_many_offers.html
- api/src/pcapi/templates/admin/edit_many_offers_components/gcu_compatible_form.html
- api/src/pcapi/templates/admin/edit_many_offers_components/playlist_tag_form.html
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/tests/admin/custom_views/many_offers_operations_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14177
Corriger un crash dans Flask-Admin en faisant une recherche par ISBN
Régression suite à https://github.com/pass-culture/pass-culture-main/commit/1d6591f37e3b2e4506e5b139c7828666084326f2
> (PC-14177)[api] Fix crash when searching by ISBN in FA

- api/src/pcapi/connectors/thumb_storage.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/src/pcapi/utils/image_conversion.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/native/v1/offerers_test.py
- api/tests/routes/pro/delete_venue_banner_test.py
- api/tests/routes/pro/post_venue_test.py
- api/tests/utils/image_conversion_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13890
Sauvegarder l'image originale lors de l'envoi d'une image d'illustration d'un lieu.
Le but est de permettre à l'utilisateur de recadrer l'image de nouveau, sans avoir à renvoyer l'image originale (qu'il n'a peut-être pas si c'est une personne de son équipe qui a fait le premier envoi).
> (PC-13890)[API] feat: save original venue banner

- api/tests/core/offerers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13524
Utiliser des sets, plutôt que de partir du principe que le premier élément de `eligible_venues` sera bien celui récupéré : si c'est un autre lieu, le test va planter pour rien.
> [API][FIX] (PC-13524)[API] fix:tests: compare sets

- api/hooks/pre-commit
Alembic's output is not stable. Which means that sometimes the "pre"
branch appears first, and sometime it's the "post" branch. It makes
diff (slightly) harder to read than necessary.
Now branches are sorted: "pre" is always on the first line, "post" is
always on the second line".
> [bsr][api][git hooks] Sort Alembic heads in `alembic_version_conflict_detection.txt`

- api/src/pcapi/core/mails/transactional/pro/first_venue_approved_offer_to_pro.py
- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/offers/api.py
- api/tests/core/mails/transactional/pro/first_venue_approved_offer_to_pro_test.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12782
Envoi un email à l'acteur culturel si c'est la première offre validée d'un lieu 
1/ check si une première offre approuvée dans le même lieu que l'offre en cours d'approbation existe
2/ si non, on check si l'offre en cours est approuvée puis on envoie le mail
N/A
> (PC-12782)[API] feat: sib email first venue approved offer to pro

- api/src/pcapi/connectors/dms/api.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14151
L'équipe support nous a remonté plusieurs utilisateurs dont le dossier DMS a été importé avec un statut OK mais ça n’a pas donné lieu à l’attribution du crédit car le champ ‘Éligibilité’ du Fraud Check est vide.
Exemple : https://backend.passculture.beta.gouv.fr/pc/back-office/support_beneficiary/details/?id=212885&url=%2Fpc%2Fback-office%2Fsupport_beneficiary%2F%3Fsearch%3D2802462
Régression apportée par ce commit du 14 mars : [f0bd9f49a1504ba3f780d096c9915ecb17c5eab4](https://github.com/pass-culture/pass-culture-main/commit/f0bd9f49a1504ba3f780d096c9915ecb17c5eab4)
Il manque `.value` sur `dms_models.FieldLabel.BIRTH_DATE_ET` (il y est bien partout ailleurs dans la fonction), donc aucune date de naissance n'est …
> (PC-14151)[api] Fix DMS application failure with no eligibility

- pro/package.json
- pro/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14187
Mettre à jour la lib @reach/dialog
La lib est utilisée dans notre composant `<DialogBox />`, qui apparait notamment:
- autour du tutorial
- quand on clique sur le bouton Modifier de la boite Profil sur la page d'accueil
- pour la suppression d'une clé d'api pour une offre
- quand on zoome sur une image
- quand on uploade une image
- quand on ajoute des codes d'activation pour un stock
- quand on essaie de quitter le dépot d'offre avant d'avoir finalisé le dépot
> (PC-14187)[PRO] chore: upgrade @reach/dialog

- api/src/pcapi/core/users/external/__init__.py
- api/src/pcapi/core/users/external/models.py
- api/tests/core/users/external/external_pro_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14271
Demande marketing : Forcer MARKETING_EMAIL_SUBSCRIPTION à Yes dans Sendinblue pour les attributs pro, lorsque ce champ était laissé à vide = pour les emails utilisés seulement comme bookingEmail d'un lieu, sans être l'email d'un compte utilisateur.
> (PC-14271)[api] Sendinblue pro attributes: force email subscription for booking emails only

- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/tests/routes/pro/get_all_collective_offers_test.py
Si on utilise les ids des models collectif, le front crash car on utilise encore les anciennes routes api qui s'attendent à recevoir un id d'un offre située dans l'ancien modèle
> (PC-13519)[API] fix: use old model ids while using old educational api url on frontend side

- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/subscription/dms/api.py
- api/tests/core/subscription/dms/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14274
La route /validate_email peut se faire spammer...
Impact décrits dans le ticket.
Retourner le fraud_check créé afin de bien pouvoir supprimer le orphan_dms.
> (PC-14274)[API] fix: delete orphan dms application when there is a parsing error

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14294
Répare la CI
ça a fonctionné sur cette pipeline https://app.circleci.com/pipelines/github/pass-culture/pass-culture-main/13053/workflows/ca9a268f-f90d-4ae1-9054-382ebe035b05/jobs/103472
> (PC-14294)[API] fix:ci: let the app start by owning files

- .git-commit-message-template
- pc
Set up with this command (which is now included in `pc install`):
git config --local commit.template .git-commit-message-template
Now when you run `git commit`, your editor/IDE will use this template
and you just have to fill in the blanks.
> (bsr) feat: Add a git commit template

- pro/src/components/layout/inputs/TextInputWithIcon/TextInputWithIcon.jsx
- pro/src/styles/components/layout/inputs/TextInputWithIcon/_TextInputWithIcon.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14136
Mettre une ombre autour du champ mot de passe sur le formulaire de création d'un compte
- ajout d'une propriété css sur le wrapper du champ
> (PC-14136)[PRO] fix: add shadow on password input wrapper

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/admin_user_view.py
- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
- api/src/pcapi/alembic/versions/20220404T071403_c00ea85d88c6_add_has_seen_pro_rgs_to_user.py
- api/src/pcapi/alembic/versions/20220404T071622_11f137937ae5_alter_has_seen_pro_rgs_to_not_null.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/pro/users.py
- api/src/pcapi/routes/serialization/users.py
- api/tests/admin/custom_views/admin_user_view_test.py
- api/tests/core/users/test_api.py
- api/tests/routes/pro/get_user_profile_test.py
- api/tests/routes/pro/patch_pro_user_has_seen_rgs_test.py
- api/tests/routes/pro/signin_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14110
Ajout d'une colonne hasSeenProRgs qui permet l'affichage ou non d'un panneau d'information sur la page d'accueil.
> PC-14110 Add new column hasSeenRgs to user table

- api/src/pcapi/alembic/versions/20220404T071622_11f137937ae5_alter_has_seen_pro_rgs_to_not_null.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13207
Fix : remplir la colonne hasSeenProRgs avant de la passer en NOT NULL
> (pc-13207)[API] fix: Update user before setting hasSeenProRgs to not Null

- pro/scripts/generate_api_client_local.sh
Le nom du blueprint utilisé sur pro.
Celui ci avait été mise à jours pour la génération depuis testing et pas pour la génération depuis l'api en locale.
> (BSR)[PRO] fix: yarn generate:api:client:local

- api/src/pcapi/tasks/cultural_survey_tasks.py
- api/tests/tasks/cultural_survey_tasks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13336
Corrige la définition de project id dans GCP backend
> (PC-13336)[API] fix: use project id from init in gcp backend

- pro/src/core/Offers/index.ts
- pro/src/routes/Offers/Offers.tsx
L'action de deploy du storybook est cassé depuis peu.
Le probleme vient de babel qui tente, sans y arriver, de compiler le client api généré.
```shell
ERROR in ./src/api/v1/gen/configuration.ts
Module build failed (from ./node_modules/@storybook/core-server/node_modules/babel-loader/lib/index.js):
SyntaxError: /home/rlecellier/work/passculture/pass-culture-main/pro/src/api/v1/gen/configuration.ts: Missing class properties transform.
25 |    * @memberof APIConfiguration
26 |    */
> 27 |   apiKey?: string | ((name: string) => string);
|   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Apres avoir tenter de fixer la configuration webpack sans success, il m'est venu en tete que storybook n'a pas besoin de ce morceau de code.
Il tente de le compiler car dans la storie OfferType nous …
> (BSR)[PRO] do not export adapters from core

- pro/src/components/pages/Offers/Offers/Offers.scss
- pro/src/screens/Offers/SearchFilters/SearchFilters.module.scss
Le bouton pour réinitialiser les filtres doit être à droite
Il y avait un défaut d'alignement sur l'onglet individuel donc j'ai agrandi un peu les champs pour que tout soit aligné sur la droite
> (PC-13530)[PRO] fix: design reset filters link

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220405T103926_d6d472d2dfad_add_booking_provider_and_venue_booking_provider_tables.py
- api/src/pcapi/core/booking_providers/models.py
- api/src/pcapi/models/__init__.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14013
Ajout du modèle BookingProvider pour stocker les informations des APIs billetteries.
Ajout du modèle VenueBookingProvider pour stocker les informations des lieux liés à des BookingProvider
> (PC-14013)[API] add BookingProvider model

- api/src/pcapi/core/educational/repository.py
It fixes a flaky test: `test_get_all_bookings_per_year`.
> (BSR)[API] fix: Order results in `get_bookings_for_educational_year()`

- api/src/pcapi/scripts/install.py
Script has been removed in 14513706840a27eba13950774037707480706af4.
(Confession: I cannot grep.)
> (BSR)[API] chore: Remove mention of deleted `full_extract_offers` script

- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/notifications/push/transactional_notifications.py
- api/src/pcapi/scheduled_tasks/clock.py
- api/src/pcapi/scheduled_tasks/commands.py
- api/src/pcapi/workers/push_notification_job.py
- api/tests/core/offers/test_repository.py
- api/tests/scheduled_tasks/clock_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14083
La notification qui rappelle à l'utilisateur qu'il a une réservation le lendemain change légèrement
de stratégie et le prévient maintenant le jour-même.
Pour l'instant, on ne s'occupe que des évènements qui ont lieu en métropole (et Corse). Une prochaine PR ajoutera l'envoi de notifications pour le reste du territoire : l'idée est de commencer simple et d'étendre la logique ensuite.
Les tâches cron sont réglées pour 8h UTC donc 9h/10h heure locale et filtrent les évènements qui ont lieu le matin (donc 11h UTC et 12h/13h heure locale) parce que le but de cette notification n'est pas de prévenir au dernier moment.
Le titre de la notification est modifiée (demain -> aujourd'hui).
L'heure de déclenchement du cron …
> (PC-14083)[API] feat:notification: send today instead of tomorrow

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220406T115030_a02d2297669c_add_business_unit_venue_link_table.py
- api/src/pcapi/alembic/versions/20220406T143007_b63eb1053857_populate_business_unit_venue_link_table.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/repository/clean_database.py
- api/src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
- api/tests/core/offerers/test_api.py
This new model is used to store the period of time during which a
venue is linked to a business unit. This information will soon be used
to control the order in which bookings are priced.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14336
> (PC-14336)[API] feat: Add BusinessUnitVenueLink model

- api/src/pcapi/core/mails/backends/sendinblue.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14349
Les emails sur testing ou staging sont respectivement envoyés vers dev+testing@pc ou dev+staging@pc.
Nous avons besoin que les hackers du Bug Bounty YesWeHack puissent recevoir les emails liés à leurs comptes.
Similaire au fonctionnement implémenté pour MailJet précédemment : `settings.WHITELISTED_EMAIL_RECIPIENTS`
La liste blanche est dans le secret `pcapi-staging_whitelisted_email_recipients` (qui contient déjà pas mal d'emails) 
Quick win compte tenu de l'urgence
> (PC-14349)[api] Whitelisted emails on staging

- api/src/pcapi/core/educational/api.py
- api/src/pcapi/utils/db.py
- api/tests/routes/adage/v1/get_venues_from_name_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14305
Permettre une recherche des venues plus souple sur le name et le publicName. La recherche ignore maintenant les diacritiques et les traits d'unions (seulement le "-").
> (PC-14305)[ADAGE] feat: make search venue by name more flexible

- api/src/pcapi/core/offers/api.py
- api/tests/routes/pro/post_shadow_stock_for_educational_showcase_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14326
répare un oublis du status da validation quand on créé un collectiveOfferTemplate a partir d'une offre
> (PC-14326)[API] fix: add the correct validation status to newly created collectiveOfferTemplate

- api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
- api/src/pcapi/core/mails/transactional/users/reset_password.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/native/v1/account.py
- api/tests/core/mails/transactional/users/reset_password_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/authentication_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13955
Corriger la vulnérabilité permettant à un individu de modifier le mot de passe d'un autre utilisateur entre la demande de création de compte et la validation de l'email
Contexte venant du ticket:
- Quand une nouvelle demande de création de compte est faite avec l’adresse email qui existe en base mais n’a pas encore été validée, au lieu de renvoyer le lien de confirmation, il faudrait envoyer le lien de réinitialisation de mot de passe via [ce template](https://my.sendinblue.com/camp/template/617/message-setup). 
- Quand une nouvelle demande de création de compte est faite avec l’adresse email qui existe en base et qui est validée, au lieu de renvoyer le mail ‘on s’est déjà vu', il faudrait envoyer le lien de …
> PC-13955 fix password theft vulnerability

- api/src/pcapi/alembic/versions/20220404T071622_11f137937ae5_alter_has_seen_pro_rgs_to_not_null.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14110
L'update d'une colonne sur la table user peut prendre du temps. Réaliser cette modification par lot plutôt que d'un coup.
> (PC-14110)[API] fix: Batch update user to alter table

- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/WithdrawalDetailsFields/WithdrawalDetailsFields.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13986
les chaines des caractères vides n'étaient pas prise ne compte par le formulaire pour les modalités de retrait 
lien de la documentation => https://final-form.org/docs/react-final-form/types/FieldProps#allownull
> (PC-13986)[PRO] fix: allows field to use empty string

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/pro/offers.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/routes/pro/patch_educational_offer_test.py
- api/tests/routes/pro/post_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14339
les offres EAC ne doivent pas avoir d'informations de retrait de billets
**avant** cette PR, ces informations étaient obligatoire lorsque le FF était actif
**avec** cette PR, ces informations ne sont plus obligatoire pour les offres collectives
> (PC-14339)[API] feat: EAC can't have withdrawal

- pro/src/components/hooks/useCurrentUser.ts
- pro/src/components/pages/Home/Homepage.tsx
- pro/src/components/pages/Home/__specs__/Homepage.spec.jsx
- pro/src/new_components/Banner/BannerRGS.tsx
- pro/src/new_components/Banner/__specs__/BannerRGS.spec.tsx
- pro/src/repository/pcapi/pcapi.js
- pro/src/ui-kit/Banner/Banner.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13935
Ajout d'un bandeau sur la Home jusqu'à ce que l'utilisateur ait cliqué sur Fermer.
- ajout de la possibilité de fermer le composant `BannerRGS`
- affichage du bandeau sur la home si la propriété `hasSeenProRgs` est `false`
- quand l'utilisateur ferme le bandeau, on masque le bandeau et passe `hasSeenProRgs` à `true`
> PC 13935 bandeau RGS home

- api/src/pcapi/domain/bank_information.py
- api/src/pcapi/use_cases/save_venue_bank_informations.py
- api/tests/use_cases/save_offerer_bank_informations_test.py
- api/tests/use_cases/save_venue_bank_informations_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13207
Remonter les erreurs à DMS au plus tôt dans la relecture par l'équipe support. 
Précision d'une erreur lorsqu'un dossier reçu est en DRAFT et qu'on a déjà des coordonnées bancaires pour ce lieu.
> (PC-13207) - Update DMS Text annotation in for dossier in DRAFT 

- api/src/pcapi/core/offerers/models.py
It's not used, but it causes a warning when the Flask-Admin
OffererTagView is loaded:
.../flask_admin/model/base.py:1416: UserWarning: Fields missing from ruleset: offerer_tags
> (BSR)[API] fix: Remove unused Offerer.offerer_tags backref

- api/src/pcapi/core/users/models.py
- api/tests/admin/custom_views/support_view_test.py
- api/tests/routes/native/v1/openapi_test.py
- pro/src/api/v1/gen/api.ts
Not needed anymore, since 094eff1e1d9c6f, fd13a6b35637, etc. No user
has this role in database.
> (BSR)[API] chore: Remove UserRole.JOUVE

- api/src/pcapi/admin/custom_views/support_view/api.py
- api/src/pcapi/admin/custom_views/support_view/utils.py
- api/src/pcapi/admin/custom_views/support_view/view.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/templates/admin/support_beneficiary_details.html
- api/tests/admin/custom_views/support_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13693
En tant que admin au pass Culture
J'aimerais pouvoir valider un dossier utilisateur depuis FA
Afin de créditer le compte de l’utilisateur sans passer par les devs
Stratégie tech
Dans src/pcapi/admin/custom_views/support_view/view.py
refacto: déplacer la logique dans des fonctions dans api.py 
Ajouter Eligibility dans la modale (dropdown)
Retirer le check if user.beneficiaryFraudReview:.
Dans BeneficiaryFraudReview user devient une relation one to many
user = sqlalchemy.orm.relationship(
"User", foreign_keys=[userId], backref=sqlalchemy.orm.backref("beneficiaryFraudReviews")
)
remplacer tous les user.beneficiaryFraudReviewpar des user.beneficiaryFraudReviews[?] (choisir lequel on veut récupérer)
Retirer de …
> (PC-13693)[API][FlaskAdmin] feat: Permettre une validation manuelle d'un user sur FA

- pro/src/api/helpers.ts
- pro/src/routes/Desk/adapters/getBooking.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14073
suite au changement fait dans la migration de Desk vers "functional component", nous recuperons uniquement la clef "global" au lieu de "la premier clef d'erreur".
l'ancien code : 
```javascript
getErrorMessageFromApi = errorResponse => {
const errorKey = this.firstErrorMessageFromApi(errorResponse.errors)
return errorResponse.errors[errorKey]
}
```
> (PC-14073)[PRO] fix: Desk displayed error message

- pro/jest.config.js
- pro/package.json
- pro/src/utils/csvConverter.ts
- pro/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14436
- problème rencontré : 
```   /home/romain/pass-culture-main/pro/node_modules/csv-parse/lib/sync.js:2
import { Parser } from './index.js';
^^^^^^
SyntaxError: Cannot use import statement outside a module
> 1 | import { parse } from 'csv-parse/lib/sync'
```
-> https://github.com/adaltas/node-csv/issues/309
> (PC-14436)[PRO] build: upgrade csv-parse to 5.0.4

- api/src/pcapi/connectors/beneficiaries/ubble.py
- api/src/pcapi/core/subscription/ubble/api.py
- api/tests/connectors/beneficiaries/ubble_test.py
- api/tests/core/subscription/ubble/end_to_end/test_subscription_via_ubble.py
Lien vers le ticket Jira  https://passculture.atlassian.net/browse/PC-14518
The phonenumber is only useful to prefill the user phonenumber when the user starts an identification on desktop (face verification cannot be performed on desktop so the user can scan a qr code on the computer with the user's smartphone or fill the user's number to receive an sms with the identification url) ; we remove it because sometimes the user phone number is not formatted with the international format, which results in a 400 error from ubble when we start the identification procedure ; we will try to understand later why some numbers have a wrong format ; sentry error : https://sentry.internal-passculture.app/organizations/sentry/issues/240585
- _Exemples: …
> (PC-14518)[API] fix: stop sending user phone number to ubble

- api/src/pcapi/scripts/payment/user_recredit.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13918
Rendre le script de recredit plus robuste en cas d'erreur: continuer le recredit si ça plante certains utilisateurs seulement
- Un bon vieux try/except des familles
> PC-13918 make recredit script more punchable

- api/src/pcapi/routes/internal/storage.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-NOPE
En local, on ne peut plus avoir les images : on se retrouve avec l'erreur suivante
```sh
INFO:pcapi.flask_app:HTTP request at /storage/thumbs/venues/H9_1649940478
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
File "[...]env3.9/lib/python3.9/site-packages/werkzeug/wsgi.py", line 538, in __next__
data = self.file.read(self.buffer_size)
ValueError: read of closed file
```
Ce qui n'arrive plus lorsque l'on passe le _path_ directement, ce qui est la seconde option possible [selon la doc de send_file](https://flask.palletsprojects.com/en/2.1.x/api/?highlight=send_file#flask.send_file).
> (PC-FIX)[API] fix: send_file path instead of fp

- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/notifications/push/transactional_notifications.py
- api/src/pcapi/workers/push_notification_job.py
- api/tests/core/bookings/test_api.py
- api/tests/scheduled_tasks/clock_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14083
Besoin : ajouter un lien vers la page de réservation dans la notification.
Le problème est que cela individualise la notification et on ne peut donc plus faire un appel groupé à l'API de Batch. Cet ajout implique donc de passer en mode "_un appel à l'API de Batch pour une réservation_" (contre _"un appel à l'API de Batch pour toutes les réservation liées au même stock"_ avant).
> (PC-14083)[API] feat: add booking link to notification

- api/pytest.ini
- api/tests/core/finance/test_api.py
- api/tests/routes/external/user_subscription_test.py
**Commits à relire séparément.**
Tous les warnings ont été traités (ou sont "temporairement" désactivés dans "pytest.ini"). Pour éviter la survenue de nouveaux "warnings" qu'on ignorerait (comme on l'a fait jusque là, dont certains étaient pourtant importants [*]), on force une levée d'erreur pour tout warning (non ignoré), lors du lancement des tests.
[*] Exemple : "hé, on dirait que tu surcharges un formulaire et que la validation du jeton CSRF est désactivée". On avait de tels warnings qu'on ignorait royalement (jusqu'à la correction du problème, cf. #2015).
> (BSR)[API] test: Turn warnings into exceptions when running pytest

- api/src/pcapi/connectors/thumb_storage.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offers/api.py
- api/src/pcapi/routes/serialization/thumbnails_serialize.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/src/pcapi/utils/image_conversion.py
- api/tests/core/offerers/test_api.py
- api/tests/routes/pro/post_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13890 
Sauvegarder et renvoyer les `crop_params` au client PRO.
➕  modifier les contraintes de `CropParam` : les valeurs doivent être supérieures **ou égales** à 0 et inférieures **ou égales** à 1, ces deux bornes sont des valeurs valides qui étaient refusées avant.
`CropParams` devient une `dataclass`, cela facilite la sérialisation et rend le code plus explicite.
> [API] PC 13890 fix save crop params

- api/src/pcapi/admin/custom_views/custom_reimbursement_rule_view.py
- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/admin/custom_views/offerer_view.py
- api/src/pcapi/admin/custom_views/user_offerer_view.py
- api/src/pcapi/admin/custom_views/venue_view.py
- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/utils/mailing.py
- api/tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14382
Ajouter des liens qui redirigent vers les pages lieux et structures du portail pro, sur les noms de structures et noms de lieux dans ces deux pages du backoffice :  
`/pc/back-office/offerer/`
`/pc/back-office/venue/`
En bonus : 
- Liens sur les noms d'offres : `/pc/back-office/offer/`
- Utilisation des générateurs de liens vers PC pro plutôt que forger l'URL à chaque fois
- Typage sur les _formatters_ dans les fichiers modifiés
> (PC-14382)[api] Links to PC PRO from Flask-Admin (offerers, venues, offers)

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/domain/booking_recap/booking_recap.py
- api/src/pcapi/routes/serialization/bookings_recap_serialize.py
- api/tests/domain_creators/generic_creators.py
- api/tests/routes/pro/get_all_bookings_test.py
- api/tests/routes/serialization/bookings_recap_serialize_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14412
Ajout de l'attribut `stock_id` dans la réponse du endpoint Pro/bookings.
- Ajout de l'attribut `stock_id` dans la réponse du endpoint Pro/bookings.
> (PC-14412)[API] feat: add stock id in pro bookings endpoint result

- pro/src/screens/OfferEducationalStock/OfferEducationalStock.stories.tsx
- pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14545
Ajouter un loader et disabled le bouton du formulaire de création de stock pour éviter les appels concurrents (qui parviennent parfois à créer plusieurs stocks alors que dans le cas du collectif on doit être limités à 1 stock)
> (PC-14545)[PRO] feat: add loader on stock form submit button

- pro/package.json
- pro/src/api/entreprise/apiEntreprise.ts
- pro/src/api/entreprise/constants.ts
- pro/src/components/layout/form/fields/SiretField/SiretField.tsx
- pro/src/components/layout/form/fields/TextField.jsx
- pro/src/core/Venue/adapters/getEntrepriseData.ts
- pro/testcafe/helpers/sirenes.js
- pro/yarn.lock
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14483
Deux fixes ici:
* Notre champ de formulaire final form `TextField` ne transférait pas la fonction `onBlur` de final form à la balise `<input>`. De ce fait final form ne peut pas savoir quand le champ passe en `touched` et n'affichait jamais les erreurs.
* Les valeurs de retour de l'api entreprise on changé:
* * `{message: "no results found"}` au lieu de 404
* * les entreprises fermé sont renvoyé avec un "etat_administratif: 'F'" pour "Fermé". Avant nous avions une 404.
Et une amélioration:
* Certain auto-entrepreneur n'ont pas de nom d'entreprise: utilisation de "prenom+nom" lorsque nous n'avons rien d'autre.
> (PC-14483)[PRO] new siren api responses

- api/src/pcapi/core/users/external/sendinblue.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14573
Éviter une exception JSONDecodeError remontée par Sentry lorsque l'API Sendinblue utilisée par les automations est en timeout.
Même chose que plus haut dans make_update_request.
> (PC-14573) Avoid JSONDecodeError reported by Sentry (Sendinblue timeout)

- api/pytest.ini
ignore les deprecation warning pour distutils dans les tests pour pouvoir les lancer avec setuptools 60+
> (BSR)[API] chore: ignore deprecation warning in tests for distutils

- api/src/pcapi/core/fraud/api.py
some fraud_checks are identity_fraud_check but do not have any resultContent, for example the ones created after migration of benficiary_imports
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14574
Erreur sentry : https://sentry.internal-passculture.app/organizations/sentry/issues/373422/?project=5&referrer=slack
> (PC-14574)[API] fix: add check on resultContent nullability

- api/src/pcapi/use_cases/save_venue_bank_informations.py
- api/tests/use_cases/save_venue_bank_informations_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13207
Lorsque nous recevons un dossier dans un état DRAFT (étape "brouillon" ou "en instruction" coté DMS) nous mettons à jour le champ d'annotation DMS avec "Valid dossier"
> (PC-13207)[API] feat : update dms annotation on success if dossier is in draft mode

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/common/models.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/fraud/ubble/api.py
- api/src/pcapi/core/fraud/ubble/constants.py
- api/src/pcapi/core/fraud/ubble/models.py
- api/src/pcapi/core/mails/transactional/users/duplicate_beneficiary.py
- api/src/pcapi/scripts/force_19yo_dms_import.py
- api/tests/core/fraud/test_api.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13871
Renforcer la détection d'utilisateur en doublon en faisant une correspondance sur le "married_name" ou "nom d'usage" en français.
ex : 
Je fais ubble avec mon passeport, prénom : 'Alphonse', nom : 'Brown' ( il n'y a pas de nom d'usage sur mon passeport). Puis je crée un autre compte et je fais ubble avec ma carte d'identité :  prénom : 'Alphonse', nom : 'Daudet',  nom d'usage : 'Brown'.
Il faut réussir à matcher ces deux utilisateurs derrière lesquels se cache en fait un unique jeune de 18 ans.
> (PC-13871)[API] feat: add duplicate search on married_name field

- pro/src/app/App.jsx
- pro/src/app/__specs__/App.spec.jsx
La multiple configuration de userId a l'air de poser des problèmes à firebase/GA pour les comptes d'event par utilisateur. 
> (BSR)[PRO] fix: Only initialize firebase userId once

- api/src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
- api/src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
- api/tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
- api/tests/scripts/offerer/delete_cascade_venue_by_id_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14572
Corriger un crash lors de la suppression d'une structure, sans réservation mais ayant des codes d'activation liés à des offres.
> (PC-14572) Fix exception in FA when an offerer is deleted (crashes if activation code exists)

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/educational/api.py
- api/src/pcapi/core/offers/api.py
- api/tests/core/educational/test_api.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/edit_educational_stock_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14444
Si un AC modifie la date de l'événement pour une année scolaire différente de celle de base, on modifie l'année scolaire du booking associé pour que le budget soit prélevé sur la bonne année scolaire
> (PC-14444)[API] feat: update booking educational year if needed

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/monkeypatches.py
- api/src/pcapi/core/users/external/sendinblue.py
See PC-13585 for an analysis of SendinBlue response times and why this
timeout value was chosen.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13585
> (PC-13585)[API] feat: Set a timeout for HTTP requests to SendinBlue

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
We delete pricings because we need a stable calculation of the revenue
of each year. As such, here we are only interested in pricings with a
value date within the year of the requested booking. Any pricing that
have a value date in another year should be ignored.
This was not an issue until now, where we are manually creating
pricings for bookings used in 2021 and before (see PC-11627). Some of
them are wrongly deleted.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14625
> (PC-14625)[API] fix: Ignore pricings of the previous year in `_delete_dependent_pricings()`

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220421T082905_8b8b73636328_add_collective_booking_ref_on_pricing_model.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/domain/reimbursement.py
- api/tests/core/finance/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13426
Créer les pricings des bookings collectifs lorsque le FF `ENABLE_NEW_COLLECTIVE_MODEL` est activé
⚠️⚠️⚠️ Lorsque ce FF est **activé** on ne veut plus pricer les bookings du modèle `Booking` qui sont de type éducationnel (donc reliés à des educational bookings - `EducationalBooking`) pour ne pas pricer 2 fois la même chose. En effet, les bookings éducationnels sont doublonnés dans la table des bookings collectif
> (PC-13426)[API] Handle collective pricing creation

- api/src/pcapi/admin/custom_views/beneficiary_user_view.py
- api/src/pcapi/admin/custom_views/support_view/api.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/fraud/repository.py
- api/src/pcapi/core/payments/api.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/factories.py
- api/src/pcapi/sandboxes/scripts/sandbox_payment.py
- api/src/pcapi/scripts/beneficiary/import_users.py
- api/src/pcapi/scripts/change_some_pro_users_to_beneficiary.py
- api/src/pcapi/scripts/grant_wallet_to_existing_users.py
- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/core/bookings/test_repository.py
- api/tests/core/payments/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_api.py
- api/tests/core/users/test_users_sql_entity.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14621
Réparer le bug : Des utilisateurs de 16 ans ont 60€ au lieu de 50€.
Il faut aligner la méthode qui attribue le deposit et celle qui recrédite l'utilisateur. Avant, la méthode qui attribuait le deposit se basait sur l'âge lors du premier fraud_check réussi, contrairement à la méthode qui recrédite l'utilisateur qui se base sur le premier fraud check de type identité, pas forcément réussi.
Changements sur la règle de détermination de la première date d'inscription : 
- au lieu de prendre seulement les fraud_checks de type identité, on peut ratisser large en prenant tous les fraud_checks (ex: validation du téléphone, même si ceux-ci ne s'appliquent pas aux UNDERAGE)
- avant on prenait le fraud_check qui a la …
> (PC-14621) Fix recredit bug

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/pro/stocks.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/post_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14528
Stocks - Valider la date limite de réservation sur la route `"/stocks/bulk"` (pro)
> (PC-14528)[API] fix: validate booking_limit_datetime on pro stocks route

- api/requirements.txt
this is a temporary fix until the tests pass with the unpinned version
> (BSR)[API] test: set email-validator function

- api/src/pcapi/domain/demarches_simplifiees.py
- api/tests/domain/demarches_simplifiees_test.py
Lorsqu'un dossier est créé sur DMS, nous requêtons leur API pour récupérer des infos sur l'entreprise. Si nous le faisons trop tot après la création, ce champ peut être vide. Nous l'utilisons uniquement pour récupérer le champ siren que nous pouvons récupérer en gardant les 9 premiers caractères du siret.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14653
- Commit(s) : …
> (PC-14653)[API] fix: Fix DMS when no entreprise is specified

- api/src/pcapi/templates/invoices/invoice.html
- api/tests/core/finance/test_api.py
Les deux dates sont arbitraires et viennent du moment où les scripts sont joués. Nous souhaitons juste harmoniser les dates entre les virements et la génération du justificatif
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14520
> (PC-14520)[API] fix: change cashflow date to invoice date

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14196
Mettre à jour le subscriptionMessage avec “La vérification d'identité est momentanément indisponible...”  uniquement si le nextStep = “Maintenance”
> PC-14196 update subscription messages

- api/src/pcapi/core/finance/api.py
This filter is not strictly required, but it:
- excludes rare bookings that have been used and then cancelled. We
also check that one last time in `price_booking()`, anyway;
- helps PostgreSQL excludes bookings more quickly. The query is around
33% faster. It's still relatively slow (around 15 seconds) but we
can live with that for now.
> (BSR)[API] perf: Filter on status in `price_bookings()`

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220426T125701_08899a47bb54_add_external_booking_table.py
- api/src/pcapi/core/bookings/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14531
Ajouter une table externalBooking pour stocker les nouvelles réservations externes avec ces tables pour le moment : 
- BookingID
- BarCode
- Seat 
> (PC-14531)[API] feat: add external booking table

- pro/src/screens/OfferEducational/OfferEducationalForm/FormVenue/FormVenue.tsx
- pro/src/screens/OfferEducational/__specs__/OfferEducationalCreationOffererStep.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14353
Afficher un bandeau quand la première structure n'est pas validée,
à la place des bandeaux sur le lieu et le référencement
> (PC-14353)[PRO] feat: add banner when first structure is not validated

- pro/src/api/entreprise/apiEntreprise.ts
- pro/src/api/entreprise/types.ts
- pro/src/components/layout/form/fields/SiretField/__specs__/SiretField.spec.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14770
Ce champ siret, ou plutot l'api de l'insee (https://entreprise.data.gouv.fr/api/sirene/v3) est pleine de surprises et pas documentée. Pour ce SIRET : 21140047800338 les champs geo_l4 (qui est la ligne "12 rue duhesme") est vide alors qu'on a la ville et le code postal. Nous pouvons récupérer l'adresse dans l'unite_legale comme c'est fait ici https://github.com/pass-culture/pass-culture-main/blob/5790cea84c2b85ea05231a62ede7a3d03a6326eb/pro/src/api/entreprise/apiEntreprise.ts#L68
J'en ai profité pour ajouter la longitute/latitude dans ces cas là aussi
- _Explications sur …
> (PC-14770) fix : Siret field on venue form

- api/src/pcapi/scripts/beneficiary/import_users.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14778
fix : le “publicName” de l’utilisateur [admin@example.com](mailto:admin@example.com) sur staging est celui du dernier utilisateur importé par le script import_users
> (PC-14778)[API] fix: admin publicName on staging after import_users

- api/src/pcapi/sandboxes/scripts/creators/beneficiaries/beneficiaries.py
This sandbox is run after the prod->staging database dump. It creates
an offerer and a venue, and our factories use 000000000 and
00000000000000 as the SIREN and SIRET. Unfortunately, we do have those
values in our production database. To avoid a unicity constraint
violation, the sandbox now uses different, non-existent SIREN and
SIRET.
> (BSR)[API] fix: Use specific SIREN and SIRET in "beneficiaries" sandbox

- api/src/pcapi/core/offers/api.py
Oubli d'indexation des offres templates lors de leur création avec le doublonnage
> (PC-14414)[API] feat: add collective offer template indexation

- api/src/pcapi/admin/custom_views/support_view/api.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/users/models.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_models.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14768
Le but est de permettre aux jeunes de 19 ans de pouvoir finaliser leur inscription (validation de téléphone, complétion du profil, etc) quand ils avaient initié le parcours à 18 ans.
En toute logique, il faut donc changer le calcul de `user.eligibility` pour se baser sur `decide_eligibility`, déjà implémentée pour gérer les imports.
Conséquences : 
- tout utilisateur qui a fait un FraudCheck à 18 ans aura `user.eligibility == Eligibility.AGE18` là où avant l'éligivilité s'arrêtait à 18 ans. Ça n'a pas beaucoup d'impact
- lorsqu'on appelle `user.eligibility`, par exemple sur la route /me, si l'utilisateur a 19ans, on va faire une requête sql sur la table BeneficiaryFraudCheck 
- Branche : …
> (PC-14768) Allow 19 users to finish subscription

- api/src/pcapi/core/finance/repository.py
- api/tests/core/finance/test_repository.py
- api/tests/routes/pro/get_invoices_test.py
A user could access invoices and business units of offerers he was not validated for as soon as the user tried to linked himself to the offerer
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14790
> (PC-14790)[API] fix: access invoice and business unit

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/post_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14776
Rendre les champs Genre Musical (`musicType`) et Type de Spectacle (`showType`) obligatoires pour la création d'offre, et non modifiable à l'édition de l'offre à l'exception du cas ou ils ne sont pas encore renseignés.
> (PC-14776)[API] feat: make offer showType and musicType required and not editable

- api/src/pcapi/core/offers/api.py
Oubli : il manquait un db.session.commit() après modification du statut de validation d'une offre template
> (PC-14144)[API] fix: commit template offer validation status

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14168
Quand un dossier DMS est pending, on ne demande pas de remplir le profile - il sera rempli par DMS a priori. 
On le redemandera en cas de KO
> PC-14168 dms completes the profile

- api/src/pcapi/core/offers/validation.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14836
Correction de l'erreur TypeError("'NoneType' object does not support item assignment") lorsque l'extraData envoyé du front est `null`
> (PC-14836)[API] fix: fix update offer NoneType error when extraData is none

- pro/src/new_components/Tabs/Tabs.tsx
- pro/src/new_components/Tabs/__specs__/Tabs.spec.tsx
- pro/src/screens/Bookings/Bookings.tsx
- pro/src/screens/Offers/Offers.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14831
Garder les query params quand on passe d'un onglet à l'autre
> (PC-14831)[PRO] feat: keep params in tabs

- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/dms/repository.py
- api/src/pcapi/routes/native/v1/authentication.py
- api/src/pcapi/scripts/beneficiary/archive_dms_applications.py
- api/tests/routes/native/v1/authentication_test.py
- api/tests/scripts/beneficiary/archive_dms_applications_test.py
- api/tests/scripts/beneficiary/fixture.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14491
Archiver les dossier dms pour ne pas les récupérer dans le cron `import_dms_users` . Dans le cron, la méthode `get_application_details` récupère tous les dossiers "Acceptés" qui ne sont pas archivés. On regarde si on les a déjà traités avec la méthode `get_arlready_processed_application_ids`. Du coup il suffit de réutiliser cette dernière méthode pour savoir s'il faut archiver ou non le dossier.
NB : un dossier archivé peut toujours être récupéré avec `get_single_application_details`, appelée par exemple lors de l'"adoption" d'un dossier dms qui vient de trouver un papa ou une maman. Par contre, il faut avoir en tête qu'un dossier archivé est supprimé au bout de 18 mois et qu'il ne sera plus récupérable.
- …
> (PC-14491) Fix dms files archive

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/ButtonEditImage/ButtonEditImage.tsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/ImageVenueUploaderSection/ImageVenueUploaderSection.tsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/ImageVenueUploaderSection/VenueImageUploaderModal.tsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueImageEdit/VenueImageEdit.tsx
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferDetails.jsx
- pro/src/new_components/ImageEditor/utils.ts
- pro/src/repository/pcapi/__specs__/pcapi.spec.ts
- pro/src/repository/pcapi/pcapi.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13641
Lorsque l'on valide une image sur un lieu, le back enregistre l'image telle qu'elle a été uploadée et une autre version éventuellement cropée et zoomée qui est utilisée sur la page du détail du lieu.
Lors de l'édition de l'image il faut afficher l’image originale + les paramètres de zoom + crop plutôt que l'image cropée sans réutiliser les paramètres utilisés pour la zoom/cropée
-Utilisation de l'objet bannerMeta du lieu qui contient le crédit de l'image, les paramètres de zoom/crop et l'image originale non cropée lors de l'édition de l'image
J'ai géré les cas particuliers suivants :
- Affichage de l'image cropée si pas d'image originale
- Si pas de crop_params complet (manque width_crop_percent) dans ce cas là …
> (PC-13641)[PRO] feat: keep original venue image

- api/src/pcapi/core/bookings/factories.py
- api/tests/core/bookings/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14025
Ajouter les externalBooking au cron update_booking_used
Ajout externalbooking à la fonction auto_mark_as_used_after_event
Création factory pour externalbooking
> Pc 14025 cds validation rule external booking status to used 48h after event

- api/src/pcapi/admin/custom_views/user_offerer_view.py
- api/src/pcapi/scripts/beneficiary/import_users.py
(pro)
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14777
Résoudre des problèmes d'identification avec les comptes pro importés sur staging : un token de validation présent indiquait un email non validé.
Je passe dans cette PR un micro changement pour voir dans le backoffice si un rattachement de structure à un utilisateur est validé (ça ne coûte rien et ça facilite l'investigation).
> (PC-14777)[API] feat: Fix import users on staging with email validated

- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/core/subscription/test_api.py
- api/tests/scripts/payment/user_recredit_test.py
the following happenned : a user creates an account with 14 yearls old but declares a 15 yo age. the user fails educonnect because the age is too young and we override user dateOfBirth with the right dateOfBirth. when the user comes back with 15 years old, in order to give the right amount for deposit, we look for the age at the first registration. If we consider it is 14 yo, we cannot find the right deposit
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14866
- Branche : …
> (PC-14866)[API] fix: filter out registration date where the user is not eligible

- api/src/pcapi/sandboxes/scripts/utils/storage_utils.py
Réparer la sandbox _industrial_ : la création d'image plante à cause de leur ratio hauteur/largeur.
Une fonctionnalité récente a introduit une vérification stricte de ce ratio afin d'empêcher une utilisateur PRO d'enregistrer une image qui ne ressemblerait à rien pour son offre ou son lieu. C'est cette vérification qui plante.
La solution est de contourner cette vérification avec l'option `keep_ratio` de `create_thumb()`, qui va alors appeler une autre fonction de traitement de l'image derrière. Cette dernière fait moins de traitement et de vérifications, notamment aucune vérification du ratio.
> (PC-FIX)[API] fix: sandbox: use keep_ratio for mediations

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
Newline characters may appear in the middle of offer names. "Computer
says no".
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14867
> (PC-14867)[API] fix: Remove newline characters for accounting software

- api/src/pcapi/flask_app.py
- api/tests/test_flask_app.py
To debug concurrent requests, the app will send a random request id in headers to check if the problem comes from the frontend or elsewhere
> (PC-14890)[API] feat: add requestId to request details logs

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/core/search/__init__.py
- api/src/pcapi/core/search/backends/algolia.py
- api/src/pcapi/models/feature.py
- api/tests/core/offerers/test_api.py
- api/tests/core/search/test_api.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13843 
Ajouter une information lors de la sérialisation d'un lieu : est-il éligible et a-t-il au moins une offre éligible à l'indexation ?
Ceci permettra de filtrer les lieux à certains endroits (par exemple n'afficher que des lieux qui ont au moins une offre sur la page d'accueil etc).
```sql
SELECT EXISTS (
SELECT 1
FROM
stock
JOIN
offer ON offer.id = stock."offerId"
WHERE
offer."venueId" = <venue_id>
AND offer."isActive"
AND offer.validation = 'APPROVED'
AND NOT (
stock."beginningDatetime" IS NOT NULL
AND stock."beginningDatetime" <= now()
OR stock."bookingLimitDatetime" IS NOT NULL
AND stock."bookingLimitDatetime" <= now()
) AND NOT (
stock."isSoftDeleted"
OR (
stock."beginningDatetime" IS NOT NULL
AND …
```
> [API] PC 13843 index venues with active offers

- .circleci/config.yml
- scripts/measure_workflow_execution_time.py
L'objectif de cette PR est de pouvoir lever une alerte lorsque ce temps de CI est trop élevé pour investiguer et corriger le problème.
Cela permet aussi de suivre son évolution au fil du temps et donc de mesurer l'impact des actions prises pour optimiser ce temps de CI.
Les mesures vont dans un outil hors du pass et ce job n'envoie que le temps d'exécution des workflows (données non sensibles donc) et permettent aux gens qui travaillent sur l'optimisation des CIs de regrouper les différents projets et apprentissages pour mieux aider ces projets.
> (BSR) Measure CI execution time

- api/src/pcapi/admin/custom_views/support_view/api.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/exceptions.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/scripts/payment/user_recredit.py
- api/tests/admin/custom_views/support_view_test.py
- api/tests/core/subscription/test_api.py
- api/tests/scripts/payment/user_recredit_test.py
Otherwise we could consider an attempt before 15-17 opening to be the first registration date
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14887
Avec ça on gère normalement tous les cas : 
Ça devrait gérer tous les cas :
- les utilisateurs qui ont tenté à 15 ans et réussi à 16 ans : ils auront bien un FraudCheck avec le eligibilityType rempli
- les utilisateurs qui ont tenté à 14 ans et réussi à 15 (ou +) : le eligibilityType ne sera pas rempli ; on peut garder le check sur l’âge
- les utilisateurs qui ont tenté de s’inscrire à 15 ans avant l’ouverture aux 15-17 : ils n’auront pas de eligibilityType rempli
- Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du …
> (PC-14887)[API] fix: add filter on eligibility to find first recent registration date

- api/src/pcapi/domain/demarches_simplifiees.py
- api/src/pcapi/use_cases/save_venue_bank_informations.py
- api/tests/use_cases/save_venue_bank_informations_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13208
Après avoir importé des coordonnées bancaires nous archivons le dossier. Nous archivons pour le moment uniquement les dossier en "Accepter".
Le comportement doit être validé pour les dossiers "Refusés" et "Sans continuation" qui pourraient aussi être archivés.  
> (PC-13208)[API] feat: archive CB DMS dossier

- api/src/pcapi/routes/native/v1/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14644
Il n'y avait pas de distinguo entre un numéro de téléphone invalide et un numéro de téléphone refusé car déjà existant en base. Cette PR résout ce problème.
Ajout d'un message d'erreur spécifique dans le cas où le numéro existe déjà.
> (PC-14644)[API] feat: raise more specific error message if phone already exists in base

- api/src/pcapi/connectors/googledrive.py
- api/tests/connectors/googledrive_test.py
Some of our files are shared on a so-called "shared drive" on Google
Drive, not in the "regular" drive. Access to a shared drive need
specific API arguments. Quoting https://developers.google.com/drive/api/guides/enable-shareddrives:
Shared drives follow different organization, sharing, and
ownership models from My Drive. If your app is going to create and
manage files on shared drives, you must implement shared drive
support in your app.
[...]
To begin, you need to include the supportsAllDrives=true query
parameter in your requests when your app performs the operations
listed below:
files.list
files.create
[...]
[...]
The files.list method contains the following shared drive-specific
fields and query modes:
[...]
includeItemsFromAllDrives — Whether shared drive items
should be included …
> (PC-10441)[API] fix: Fix list/create on shared (Google) drives

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/users/repository.py
- api/tests/core/users/test_models.py
[et encore un edge case...]
this is to fix a case when the fraud check is not created in the same time the dms application is created. thanks to webhook that notifies us on each dms application status change, it normally happens; but when the person creates a dms application before creating a passculture account, we cannot create a fraud_check, we create a orphan_dms_application object. the fraud_check is only created when the user validates its email
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14768
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, …
> (PC-14768)[API] fix: base 19 yo eligibility on dms registration_date instead of fraud_check dateCreated

- api/src/pcapi/utils/image_conversion.py
- api/tests/routes/pro/post_venue_test.py
- api/tests/utils/image_conversion_test.py
Supprimer la vérification du ratio des images.
C'était mal géré, il faudrait reprendre ça pour ne plus avoir cette erreur qui part dans la nature.
> (PC-FIX)[API] FIX: image conversion: remove ratio check

- api/src/pcapi/core/subscription/api.py
- api/tests/core/subscription/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14978
Corriger https://sentry.internal-passculture.app/organizations/sentry/issues/378077/?project=5&referrer=slack
> fix: avoid key error when checking if city is set in a fraud check

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/models.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14646
Cette PR fait suite à une volonté d'uniformiser la manière dont les FraudCheck sont stockés en base. Jusqu'ici le traitement des FraudCheck pour le processus de validation de numéro de téléphone était légèrement différent. Cette PR permet le stockage des informations dans l'objet FraudCheck générique.
On rend les attributs de `PhoneValidationFraudData` optionnels pour ne pas rendre invalides les entrées déjà en base. Désormais, on stocke les informations dans `BeneficiaryFraudCheck.reasonCodes` et `BeneficiaryFraudCheck.reason` à la place de `PhoneValidationFraudData['source']` et `PhoneValidationFraudData['message']`.
`PhoneValidationFraudData` ne stocke désormais que le numéro de téléphone.
- _Exemples: …
> (PC-14646) Standardize Phone Validation fraud checks

- api/src/pcapi/core/search/backends/dummy.py
Logs make it clearer that the dummy backend is used (whether
voluntarily or not).
> (BSR)[API] feat: Let dummy search backend log

- api/src/pcapi/core/users/factories.py
- api/src/pcapi/routes/native/security.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/authentication.py
- api/src/pcapi/routes/native/v1/bookings.py
- api/src/pcapi/routes/native/v1/cultural_survey.py
- api/src/pcapi/routes/native/v1/favorites.py
- api/src/pcapi/routes/native/v1/offers.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/src/pcapi/routes/native/v1/subscription.py
- api/src/pcapi/routes/saml/educonnect.py
- api/tests/core/fraud/test_api.py
- api/tests/core/users/test_api.py
- api/tests/core/users/test_factories.py
- api/tests/routes/external/zendesk_test.py
- api/tests/routes/native/security_test.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14813
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14814
(deux en un, Les deux tickets auraient probablement dû être fusionné, tant pis)
Permettre à un utilisateur suspendu de connaître sa date de suspension.
Cette route nécessite d'être authentifié, le problème est que le décorateur `authenticated_user_required` bloque les utilisateurs inactifs (`user.isActive == False`). Cette PR ajoute donc un second décorateur qui autorise les utilisateurs inactifs.
> Pc 14813 route suspension date

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/templates/mails/internal_validation_email.html
- api/src/pcapi/utils/mailing.py
- api/tests/emails/offerer_validation_test.py
More specifically, do not show technical (and possibly sensitive)
information through the use of `vars()`.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14202
> (PC-14202)[API] fix: Show less data in offerer internal validation e-mail

- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/core/users/repository.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14688
Endpoint d'API pour le nouveau backoffice :
En tant que support jeune, J'aimerais consulter le crédit du jeune
Règles de gestion
- Afficher le crédit initial et le crédit restant du jeune 
- Et le montant restant sur son plafond numérique
> (PC-14688)[API] feat: new back-office - add get beneficiary credit endpoint

- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/LocationFields/LocationFields.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/LocationFields/__specs__/LocationFields.spec.jsx
The address field is mandatory for the endpoint POST on "/venues"
Here is the api validator : https://github.com/pass-culture/pass-culture-main/blob/2f2e25507214a094f262dc83648c57e8ab89f005/api/src/pcapi/routes/serialization/venues_serialize.py#L34
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14542
> (PC-14542)[PRO] fix: Add frontend validation on addressField

- api/src/pcapi/scripts/beneficiary/import_test_users.py
- api/tests/scripts/beneficiary/import_test_users_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15066
Pour les comptes de test maestro, les adresses sont en `candidat*.maestro@passculture.app`.
L’email est _whitelisté_ mais personne ne le recevra, pour le lien de réinitialisation de mot de passe permettant d’en choisir un.
Pour cet usage, mettre un mot de passe **optionnel** dans le Google Sheets plutôt que celui secret (aussi pour admin) est ce qu’il y a de plus pratique. Nous l'ajoutons donc ici.
- Script déjà copié/exécuté manuellement sur staging en "update".
- Besoin de passer dans la v187 pour que le code soit actif pour le dump/restore de jeudi prochain.
- Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du …
> (PC-15066)[API] feat: Enable custom password at test account creation on staging

- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14813
Ajout de `format_into_utc_date` pour le modèle `UserSuspensionDateResponse` : le front s'attend à un `datetime` formaté correctement.
> (PC-14813)[API] fix: add utc formatter to pydantic model

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/scheduled_tasks/commands.py
- api/tests/core/fraud/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14398
**FIX**
`yield_per` + `session.commit` = 💣 
Ou plus exactement, les modifications peuvent passer mais psycopg2 va renvoyer une erreur.
On ne devrait pas récupérer un très grand nombre d'utilisateurs à chaque fois, donc ça devrait pas être (trop) un problème.
> (PC-14398)[API] fix: do not use yield_per

- api/src/pcapi/routes/native/v1/account.py
- api/tests/routes/native/v1/account_test.py
Use more adequate error message if phone already exists
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14644
Correction des wordings ajotués dans [cette PR](https://github.com/pass-culture/pass-culture-main/pull/2232)
> (PC-14644)[API] fix: use more adequate error message 

- pro/src/components/pages/Offers/Offer/OfferDetails/OfferDetails.jsx
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferThumbnail/OfferThumbnail.jsx
- pro/src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferCreationForPro.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15039
-Ajout d'un message d'erreur explicite lorsque l'image n'est pas conforme aux attentes de l'API
-Ne pas afficher dans l'encart l'image non enregistrée comme c'était le cas au bout de la 2ème tentative
-Remplacement du try/catch par une gestion de la promise par then/catch + ajout d'une props pour enregistrer le message d'erreur pour qu'il soit utilisable par le composant OfferThumbnail + tenir compte de la prop thumbnailError pour gérer l'affichage de la preview
- Adaptations effectuées pour que ça fonctionne en création et modification
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield …
> (PC-15039)[PRO] fix: add offer image error message 

- pro/src/screens/Offers/Offers.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14626
Afficher le bouton création d'offre tout le temps si l'utilisateur n'est pas administrateur.
> (PC-14626)[PRO] fix: display offer creation button if user is not admin

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/admin/custom_views/allocine_pivot_view.py
- api/src/pcapi/alembic/run_migrations.py
- api/src/pcapi/alembic/versions/20220512T091138_16ce9f750e7c_apply_not_null_constraint_on_allocinepivot_venueid.py
- api/src/pcapi/alembic/versions/20220512T160804_dd318872da8d_remove_not_null_siret_on_allocine_pivot.py
- api/src/pcapi/core/providers/factories.py
- api/src/pcapi/core/providers/models.py
- api/src/pcapi/core/providers/repository.py
- api/src/pcapi/repository/allocine_pivot_queries.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py
- api/src/pcapi/use_cases/connect_venue_to_allocine.py
- api/tests/models/allocine_pivot_queries_test.py
- api/tests/routes/pro/get_providers_by_venue_test.py
- api/tests/routes/pro/post_venue_provider_test.py
- api/tests/use_cases/connect_allocine_to_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14915
Dans la mesure où le siret n'existe pas forcément pour certains lieux,
nous devons remplacer le siret par le venue_id dans allocine_pivot.
- Premier commit : validation de la contrainte non-null sur `allocine_pivot.venue_id`
- Second commit : modification du code source pour utiliser le venue_id à la place du siret. A noter que le modèle n'a plus de propriété siret, mais la colonne en base de données est conservée temporairement (elle sera supprimée lors d'un prochain commit).
- ajout d'ignore pylint dans le fichier `run_migration`
- ajout d'un mecanisme d'ignore pour les contraintes sur les tables lors de la génération automatique de migration
- déplacement d'une requête isolée vers le repository du core
> Pc 14915 use venue id in allocine pivot

- api/src/pcapi/connectors/cine_digital_service.py
- api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
- api/src/pcapi/core/booking_providers/cds/client.py
- api/tests/core/booking_providers/cds/test_client.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15105
Appeler la route de récupération des média sur l’API CDS, récupérer les informations lié aux films 
[Lien de la documentation CDS](https://docs.cineoffice.fr/vad/#:~:text=1.3%20R%C3%A9cup%C3%A9ration%20medias%20(films%20planifi%C3%A9s))
> (PC-15015)[API] feat: get movies from cds api

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreation.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/LocationFields/LocationFields.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/LocationFields/__specs__/LocationFields.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14543
Le backend interdit d'avoir des lieux sans adresse à la création mais pas à l'édition. 
Il faut garder ce comportement. (Il y a beaucoup de lieux en base sans adresse, ils ne pourraient pas valider le formulaire)
> (PC-14543)[PRO] fix: Only require Address for venue creation form

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220513T093817_06190162f083_add_phone_number_index.py
- api/src/pcapi/core/users/models.py
Résoudre les [problèmes de perf](https://sentry.internal-passculture.app/organizations/sentry/performance/api:fc42986a6d134e73a39a5483de3a37a1/?environment=production&project=5&query=transaction.duration%3A%3C15m+transaction%3A%2Anative%2A+event.type%3Atransaction+http.method%3APOST&statsPeriod=14d&transaction=native_v1.send_phone_validation_code&unselectedSeries=p100%28%29) sur la route `send_phone_validation_code`. La requête faite dans `does_validated_phone_exist` est hyper longue, un index peut résoudre le pb.
La migration prend 30s en production.
> (BSR)[API] feat: add index on user.phoneNumber

- api/src/pcapi/connectors/dms/models.py
- api/src/pcapi/connectors/dms/serializer.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/scripts/beneficiary/handle_inactive_dms_applications.py
- api/tests/scripts/beneficiary/fixture.py
- api/tests/scripts/beneficiary/handle_inactive_dms_applications_test.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15131
Cf enquête dans le ticket. -> maintenant dans le formulaire on ne demande plus le département. Il faut se baser sur le code postal.
En bdd si on n'a pas le code postal alors on n'a pas le département non plus. Donc autant toujours se baser sur le code postal.
> (PC-15131)[API] fix: get departement from postal code in dms applications

- api/src/pcapi/infrastructure/repository/stock_provider/provider_api.py
- api/src/pcapi/routes/serialization/base.py
- api/tests/local_providers/provider_manager_test.py
- api/tests/scripts/stock/fully_sync_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14440
Rendre obligatoire le prix dans la synchro provider.
- ajout de la contrainte
- bsr : modif d'une string regex qui sortait en erreur sur mon IDE (et suppression de l'exception pylint)
> Pc 14440 add mandatory constraint to price in provider sync

- api/src/pcapi/admin/templating.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/serialization/account.py
- api/tests/routes/native/v1/account_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15056
Ajout d'une route native qui retourne le statut de suspension d'un compte utilisateur. Cette information permettra au client de savoir où rediriger l'utilisateur en fonction : parcours normal si non suspendu, parcours de réactivation si suspendu à sa demande, page de suspension si suspendu pour une autre raison, etc.
> (PC-15056)[API] feat: add suspension status route

- api/src/pcapi/routes/backoffice/accounts.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15177
visualiser les données de base d’un utilisateur (données calquées sur les données utilisateurs venant du endpoint de recherche)
> (PC-15177)[API] New back-office: get user basic information

- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15177
Pour coller aux pastilles de la maquette, il manque ces informations dans `PublicAccount` :
```
roles: list
isActive: bool
```
> (PC-15177)[API] New back-office: Add roles and isActive in basic user information

- api/src/pcapi/connectors/cine_digital_service.py
- api/src/pcapi/utils/requests.py
- api/tests/utils/requests_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15181
- Supprimer l'URL des logs d'exceptions dans le connector CDS pour ne pas afficher le token d'api.
- Caviarder le query param `api_token` des URLs dans le wrapper de request.
> (PC-15181)[API] refactor: remove cds url from exceptions logs and redact api token in request wrapper

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/native/v1/authentication.py
- api/tests/core/users/test_api.py
- api/tests/routes/native/v1/authentication_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14815
Ne pas modifier le mot de passe d'un compte lors de sa suspension s'il l'est à la demande l'utilisateur.
Le but est que l'utilisateur puisse toujours se connecter afin de l'authentifier pour le nouveau parcours de réactivation (à venir). Il pourra se connecter mais n'aura accès qu'à un nombre très restreint d'actions.
Les utilisateurs suspendus pour d'autres raisons, fraude notamment, ne sont pas concernés. Ils le seront peut-être plus tard.
MISE A JOUR : peu import la raison de la suspension, on ne modifie plus le mot de passe. Ce changement est encadré par un FF pour pas qu'un utilisateur qui suspend son compte avant que tout le nouveau parcours de réactivation soit disponible ne se retrouve coincé au milieu de …
> (PC-14815)[API] feat: upon user request: keep password

- api/src/pcapi/admin/custom_views/support_view/api.py
- api/src/pcapi/core/fraud/common/models.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/repository/beneficiary_import_queries.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14675
API pour fournir les infos de l'état du dossier de souscription du jeune, avec les retours sur l'état du dossier DMS, Ubble, Educonnect, Jouve, l’éligibilité du compte (bénéficiaire ou non), plus la date de dépôt du dossier, pour chaque étape.
Champs adaptés au design fourni dans le ticket front
> (PC-14675)[API] New back-office: get user subscription history

- api/src/pcapi/routes/native/v1/account.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-NOPE
Ajout de paramètres manquants dans l'utilisation du décorateur `spectree_serialize` : certaines routes ne précisaient pas le `response_model` alors qu'elles renvoyaient un objet JSON.
> [API](PC-FIX)[API] fix: add response_model parameter

- pc
nettoyage d'une commande `pc set-backend` qui n'était plus utilisée (ni fonctionnelle d'ailleurs)
> (BSR)[API] chore: remove unused pc set-backend command

- api/src/pcapi/core/fraud/phone_validation/sending_limit.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/exceptions.py
- api/src/pcapi/routes/native/v1/account.py
- api/tests/core/fraud/phone_validation/test_sending_limit.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14452
Cette PR vise à rendre plus explicite le message d'erreur présenté à l'utilisateur lorsqu'il entre un code erroné au moment de la validation du numéro de téléphone.
- Création d'une classe `PhoneValidationCodeAttempts` pour récupérer rapidement et le nombre d'essais de code et le nombre restant d'essais possible
- Ajout d'un attribut à l'erreur `NotValidCode` pour y intégrer le nombre d'essais restants
- On envoie désormais l'erreur `PhoneValidationAttemptsLimitReached` dès l'échec du dernier code, et non plus après l'envoi d'un code supplémentaire. Cela permet à l'utilisateur de naviguer vers la page d'erreur associée au nombre trop important de tentatives dès le dernier code erroné
- Branche : …
> (PC-14452)[API] Change CodeNotValid error message to be more explicit

- api/src/pcapi/core/users/external/sendinblue.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15525
Éviter une exception dans le traitement de l'exception ; erreur Sentry : 
https://sentry.internal-passculture.app/organizations/sentry/issues/380328/?project=5
> (PC-15525)[API] fix: Avoid JSONDecodeError when Sendinblue connection fails

- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/mails/transactional/users/duplicate_beneficiary.py
- api/tests/core/fraud/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15089
Etre meilleur à trouver les doublons de pieces d'identité
- Amélioration de la regexp d'acceptation de numéro de piece d'identité
- Checker les doublons en ignorant les espaces
> PC-15089 check cni duplicates ignoring spaces

- api/src/pcapi/core/booking_providers/api.py
- api/src/pcapi/core/bookings/api.py
- api/tests/core/bookings/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14022
Enregistrement de ExternalBooking quand un bénéficiaire fait une réservation
Appel de la fonction book_ticket si le FF ENABLE_CDS_IMPLEMENTATION est actif 
et que la catégorie de l'offre est de type SEANCE_CINE
N/A
> (PC-14022)[API] feat: CDS barcode saved when book_offer is called

- api/src/pcapi/core/bookings/repository.py
- api/tests/core/bookings/test_repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14131
les emails ne s'envoyaient pas via le cron en testing
on suspecte que c'était parce qu'il y avait plusieurs réservations pour une meme offre
avant, on ne sélectionnait que les stocks et s'il y avait plusieurs individuals bookings on ne mailait que le premier
maintenant, on sélectionne les individuals bookings
> (PC-14131)[API] fix: select several bookings given one stock with several bookings

- api/src/pcapi/core/users/api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15236
éviter l'exception remontée par Sentry avec un code postal vide (chaîne vide) : 
https://sentry.internal-passculture.app/organizations/sentry/issues/380646/?project=5
> (PC-15236)[API] fix: exception when creating pro user with empty postal code

- api/src/pcapi/infrastructure/repository/stock_provider/provider_api.py
- api/tests/local_providers/provider_manager_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15237
- Ne pas bloquer la synchro des stocks sans prix avant la date d'échéance du 1er juin 2022
> (PC-15237)[API] fix: do not block sync for stock without price before 1st of june

- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/native/v1/authentication.py
- api/src/pcapi/routes/native/v1/serialization/authentication.py
- api/tests/routes/native/v1/authentication_test.py
- api/tests/routes/native/v1/openapi_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15227
Renvoyer une erreur 400 avec un code spécifique lorsqu'un utilisateur dont le compte est dans l'état supprimé essaie de se connecter.
Au passage, on remplace le `User.isActive` de la réponse à `/signin` par `User.account_state` : puisqu'on va chercher l'historique du compte s'il est inactif, autant s'en servir directement. Cela permettra ensuite de supprimer la route, récemment ajoutée, `/account/suspension_status` et évitera un aller-retour client front - api.
> (PC-15227)[API] feat: signin: use account_state instead of isActive

- api/src/pcapi/core/permissions/models.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14680
Fonctionnalité du nouveau backoffice, côté backend :
API de renvoi d'un lien de validation d'email
> (PC-14680)[API] feat: new back-office - resend confirmation email

- api/src/pcapi/routes/serialization/collective_stock_serialize.py
Je ne sais pas pourquoi ce logger existe mais il n'est pas correcte:
- en français 
- pas de raison de le faire en error
- innutile
cette pr le retire.
> (BSR)[API] fix: remove useless logger in validator

- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/fraud/models.py
there is an issue in dms cron when the fraud_check is not saved: we try to access fraud_check.dateCreated which is not defined
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15300
[Erreur sentry](https://sentry.internal-passculture.app/organizations/sentry/issues/381657/?project=5&referrer=jira_integration) :
> (PC-15300)[API] fix: save dms fraud_check in db

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/offerers/api.py
- api/tests/core/finance/test_api.py
The previous change made us order on the business unit-link date first.
This was wrong for the following (rather obvious) case:
1. Venue V1 is linked to business unit BU on 01/01.
2. Venue V2 is then linked to the same BU on 05/01.
3. Booking B2 (on venue V2) is used on 10/01 and is priced.
4. Booking B1 (on venue V2) is used on 15/01.
The previous implementation would declare that bookings of V1 should
be booked before bookings of V2 (because it was linked to its BU
first). That made no sense. The first "component" of the order should
rather be `max(venue_link_date, used_date)` (in fact, something a
little more complex but that's the idea).
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15366
> (PC-15366)[API] fix: Correctly order booking for pricing (again)

- .github/pull_request_template.md
~~Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX~~
Avec le canal #db-changes, les Data Analysts savent quand une modification de la db arrive en prod.
Mais celle-ci doit être cherchée dans les fichiers de la PR (fichiers alembic) et elle est parfois difficile à lire (si elle est découpée en plusieurs opérations pour faire du zdd, s'il y a des élements inintéressants pour eux comme les index).
L'ajout d'une section dans le template de PR leur permettrait d'avoir une description humaine du changement de bdd.
Modification du template de pr.
~~- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira~~
- Commit(s) : `(PC-XXX)[PRO|API|…] description rapide …
> (BSR)[github] Add a "db modifications" section on github's pr template

- api/src/pcapi/utils/pylint.py
Defining the `__implements__` is deprecated... and is in fact not
necessary anymore.
> (BSR)[API] chore: Adapt our pylint checkers to pylint 2.14

- .circleci/config.yml
We used to required pylint (without pinning any version) and that
installed pylint 2.13.9 when it was the latest version. The dependency
cache hence had this version. A new 2.14 version has been released and
is now picked up. But the cache key was still the same, so CircleCI
jobs installed the old 2.13.9 version instead.
We hence need to invalidate this cache. But that's not possible, we
must use a new cache key. Hence the version infix ("v1"). And the use
of a clearer prefix while we're at it.
> (BSR)[API] ci: Fix Python dependency cache

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13949
On utilisait `helmfile apply` au lieu de `helmfile sync` pour déployer, or la commande `apply` fait un diff pour savoir s'il y a des changements et ne fait rien s'il n'y en a pas. Cela pose problème lorsqu'un déploiement a échoué et que l'on souhaite le relancer.
> [PC-13949] Use helmfile sync instead of apply

- pro/src/ui-kit/form/SirenInput/SirenInput.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15298
Pour reproduire le bug : 
Remplir le champ siren avec 123456789. Blur le champ
Blur n'importe quel autre champ, la dernière entrée du champ siren devrait se vider. 
La regex retire tous caractères n'étant pas un chiffre ou un espace.
- Branche …
> (PC-15298)[PRO] fix: siren bug in some weird cases

- api/src/pcapi/core/offers/api.py
- api/tests/core/offers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15573
Éviter l'exception UniqueViolation lorsque le marketing ajoute un tag à plusieurs offres simultanément, par ISBN, dans FA.
Cela se produit si au moins une des offres concernées a déjà le nouveau tag.
> (PC-15573) fix: UniqueViolation exception when adding criteria to many offers

- .circleci/config.yml
Fix de la commande helm pour pull et extraire le chart de `passculture-db-operations` vu que la syntaxe a changé en 3.7+
> [PC-13949] Fix helm chart pull command for db-ops

- api/src/pcapi/core/providers/exceptions.py
- api/src/pcapi/core/providers/repository.py
- api/src/pcapi/local_providers/CONTRIBUTING.md
- api/src/pcapi/routes/pro/venue_providers.py
- api/src/pcapi/use_cases/connect_venue_to_allocine.py
- api/tests/models/allocine_theater_queries_test.py
- api/tests/routes/pro/post_venue_provider_test.py
- api/tests/use_cases/connect_allocine_to_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15576
Faire apparaitre le provider AlloCine pour le lieux sans siret lors du choix de synchronisation.
- Refactor avec une nouvelle classe AlloCineVenue qui porte la logique de savoir si un lieu est connu d'AlloCine.
> (PC-15576)[API] Bug: fix allocine provider missing for venue without siret

- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/mails/__init__.py
- api/tests/core/bookings/test_api.py
- api/tests/routes/native/v1/offers_test.py
- api/tests/scheduled_tasks/commands_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14131 
Impossible de reproduire l'erreur mais cette PR devrait, on l'espère, le corriger :
1. il manquait des informations dans la requête et on a donc supprimé les load_only et ajouté des jointures ;
2. supprimé l'enregistrement des emails parce que
* on va bientôt supprimer cette table qui ne nous sert plus à rien ;
* cela induit un `commit` qui créé du bazar
> [API][FIX] PC 14131 fix stuff again and again

- api/requirements.txt
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15625
Le safety check montre une vulnérabilité de la librairie MyJWT.
Montée de version de la librairie en version 2.4.0
> (PC-15625)[API] chore: upgrade PyJWT library

- api/src/pcapi/core/offerers/api.py
- api/tests/core/offerers/test_api.py
It ended *all* entries of the table, not only the line that
corresponded to the requested business unit. Fortunately, it was not
called too often...
> (BSR)[API] fix: Fix `delete_business_unit()`

- api/src/pcapi/admin/custom_views/admin_user_view.py
- api/src/pcapi/admin/custom_views/partner_user_view.py
- api/src/pcapi/admin/custom_views/pro_user_view.py
- api/src/pcapi/core/fraud/exceptions.py
- api/src/pcapi/core/subscription/api.py
- api/src/pcapi/core/subscription/models.py
- api/src/pcapi/core/subscription/phone_validation/api.py
- api/src/pcapi/core/subscription/phone_validation/exceptions.py
- api/src/pcapi/core/users/api.py
- api/src/pcapi/core/users/email/update.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/utils.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/native/v1/authentication.py
- api/src/pcapi/scripts/offerer/import_offerer_from_csv.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/permissions_test.py
- api/tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14691
Permettre de débloquer un jeune dans son parcours d'inscription lorsqu'il a des soucis avec la reception des SMS de validation
- Ajout d'un endpoint permettant de renvoyer un code de validation sans date d'expiration (pour les jeunes qui recoivent les SMS avec un grand délai)
- Ajout d'un endpoint permettant d'ignorer létape de validation du numéro de téléphone (pour les jeunes qui ne reçoivent pas du tout les SMS)
nope
> Pc 14691 phone manual validation

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15531
Ajouter les informations manquantes dans 2 endpoints:
- `backoffice/public_accounts/{user_id}`: adresse, code postal et vile
- `backoffice/public_accounts/{user_id}/credit`: date de création du credit
RAS
RAS
RAS
> (PC-15531)[API] feat: add missing informations on some endpoints

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/templates/invoices/invoice.html
- api/tests/core/finance/test_api.py
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14745
Ajout d'un tableau dans le justificatif de remboursement avec un detail des remboursement par lieu.
[01062022-F220000245-Justificatif-de-remboursement-pass-Culture.pdf](https://github.com/pass-culture/pass-culture-main/files/8821735/01062022-F220000245-Justificatif-de-remboursement-pass-Culture.pdf)
> [PC-14745][PRO] - Add reimbursment details by venue

- api/src/pcapi/admin/custom_views/booking_view.py
- api/src/pcapi/admin/custom_views/mixins/suspension_mixin.py
- api/src/pcapi/core/bookings/api.py
- api/src/pcapi/core/bookings/exceptions.py
- api/src/pcapi/core/bookings/validation.py
- api/src/pcapi/routes/error_handlers/bookings_error_handlers.py
- api/src/pcapi/routes/native/v1/account.py
- api/src/pcapi/routes/pro/bookings.py
- api/tests/core/bookings/test_api.py
- api/tests/core/bookings/test_validation.py
- api/tests/routes/pro/get_booking_by_token_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14678
**Nettoyage**
Utiliser des erreurs génériques plutôt que des erreurs héritant de `ApiErrors` dans `pcapi/core/bookings/validation.py`.
Ceci est la première étape. Il en reste encore un peu. Pas eu le temps de terminer, en même temps... ce sera plus simple à relire et ça permet d'avoir des exemples à reprendre une fois corrigé et validé.
> (PC-14678)[API] feat: use generic validation errors

- .github/workflows/mypy-cop.yml
- api/mypy_cop.sh
Before this commit, we would get a comment about "mypy ignore count"
being stable on each pull request. This was noisy and not very useful.
Now we get a comment in a pull request only if there are more or less
ignore's than master or, if so, when a further commit makes the count
equal to what we have on master (i.e. when we got from 10 to 8
ignore's, and then back to 10, or the other way around).
> (BSR)[API] ci: Do not add mypy cop report comment if ignore count does not change

- api/requirements.txt
We had pinned email-validator version because they banned example.com from their valid domain names in test environments.
They went back on this decision, hence we can unpin this dependency (which is, in fact, an undirect dependency due to Pydantic)
> (BSR)[API] chore: unpin email validator version

- api/requirements.txt
- api/src/pcapi/core/offers/exceptions.py
- api/tests/core/offers/test_exceptions.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15725
pgcli est un outils en ligne de commande que nous utilisons a la main. Il n'y a aucune raison de pin sa version (+ sa version était vraiment vieille)
> (PC-15725)[API] chore: update pgcli version and unpin it

- helmfile.yaml
Version 0.11.9 forbids concurrent cronjobs by default. See pass-culture/pcapi-chart@e539f358ffc36fe49dc1a368748252825a5912d9.
> (BSR)[API] ci: Bump Helm chart to 0.11.9

- pro/src/core/OfferEducational/constants.ts
- pro/src/ui-kit/form/MultiSelectAutoComplete/MultiSelectAutocomplete.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15730
Réparer le bug qui rend la sélection d'une catégorie impossible sur Firefox
> (PC-15730)[PRO] fix: prevent Multiselect from writing Formik state on each click outside

- api/tests/scheduled_tasks/commands_test.py
Problème : le test créait trois `IndividualBooking` et partait du principe qu'ils seraient sélectionnés dans le bon ordre, ce qui n'était pas tout le temps le cas.
Fix : n'en créer qu'un, les deux autres n'apportaient de toute manière pas grand chose.
> (BSR)[API] fix: flaky test

- api/mypy_cop.sh
Something like:
<red-cross> mypy cop report: 10 (master) ↗ 20 (your branch)
... where `<red-cross>` is an image of a, yes, a red cross.
---
Cf.  plus bas sur cette PR pour une démo des 3 types de message (augmentation, baisse ou stable).
GitHub convertit `↗` en ↗ et je trouve ça moyennement lisible. Au début j'avais juste mis une simple flèche "→", peut-être que finalement c'est mieux ?
Autre proposition : on peut évidemment trouver d'autres emojis si certain(e)s préfèrent : :champagne: :tada: :finnadie: etc. mais leur sens me semble moins évident qu'une coche verte et une croix rouge, à mon avis.
> (BSR)[API] test: Make "mypy cop" report more concise

- api/src/pcapi/core/users/api.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/tests/core/users/test_api.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14982
Ajouter un endpoint qui permet de récupérer l'historique des opérations réalisées sur un compte jeune/grand-public
- ajout de la fonction `pcapi.core.users.api.public_account_history`
- ajout de la route `GET public_accounts/<int:user_id>/logs` dans `pcapi.routes.backoffice.accounts`
- pas mal de nettoyages (surtout sur les imports)
RAS
> Pc 14982 public user history

- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offers/models.py
- api/src/pcapi/models/accessibility_mixin.py
- api/src/pcapi/models/offer_mixin.py
- api/src/pcapi/routes/adage_iframe/serialization/offers.py
- api/src/pcapi/routes/native/v1/serialization/common_models.py
- api/src/pcapi/routes/native/v1/serialization/offerers.py
- api/src/pcapi/routes/serialization/collective_offers_serialize.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/patch_collective_offer_test.py
- api/tests/routes/pro/patch_educational_offer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10707 
Factoriser le code d'accessibilité côté modèles SQLA et Pydantic : les lieux et les offres ont toujours les mêmes quatre champs, inutiles de maintenir des copier/coller partout. Cela évitera de se retrouver avec des inconsistances.
> PC 10707 refactor accessibility

- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/search/backends/algolia.py
- api/tests/core/offerers/test_api.py
- api/tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15229
Lors de l'indexation d'un lieu, on a récemment ajouté un champ nommé `is_eligible_for_strict_search`. Celui-ci était trop flou et cette PR vient donc procéder à quelques renommages : ce champ ainsi que la fonction associée.
Le FF reste tel quel parce que c'est moins important.
> (PC-15229)[API] feat: rename eligible for strict search

- api/src/pcapi/core/finance/api.py
- api/src/pcapi/templates/invoices/invoice.html
- api/tests/core/finance/test_api.py
- api/tests/files/invoice/rendered_invoice.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15794
Les offres duo n'étaient comptées qu'une seule fois. Le design des sommes n'était pas de norme française
[Exemple de justif](https://storage.googleapis.com/passculture-metier-ehp-staging-assets/invoices/IhDFngSDUKntBEj26VCW_lRb6oEXLb94D-GtMVO91Ps/17062022-F220041150-Justificatif-de-remboursement-pass-Culture.pdf)
- _A destination des Data Analysts, exposer le résultat …
> [PC-15794] fix: Invoice shows wrong booked amount when isDuo offers exists

- api/src/pcapi/admin/custom_views/offer_view.py
- api/src/pcapi/core/bookings/repository.py
- api/src/pcapi/core/educational/models.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/finance/repository.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/core/offers/repository.py
- api/src/pcapi/core/users/models.py
- api/src/pcapi/core/users/repository.py
- api/src/pcapi/domain/admin_emails.py
- api/src/pcapi/models/needs_validation_mixin.py
Filtering on `Model.isValidated` is clearer than `Model.validationToken.is_(None)`.
Suggested by @prouzet.
> (BSR)[API] feat: Add `NeedsValidationMixin.isValidated` hybrid property

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220620T174806_cb1d904c149d_add_dms_token_column_to_venue_table.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/scripts/venue/add_dms_token_to_each_venue.py
- api/tests/core/offerers/test_api.py
- api/tests/scripts/venue/test_add_dms_token_to_each_venue.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15595
Ajouter un identifiant unique servant à identifier les démarches DMS concernant un lieu.
- Ajout de colonne
- Modification de factory
- Génération de ce `dms_token` lors d'une création de lieu
- Ajout d'un script de rattrapage
12 caractères hexadécimaux soit 48 bits semblent être suffisants pour éviter les conflits. On tentera néanmoins 10 générations avant de lever une erreur.
- Ajout d'une colonne de type `TEXT` `dms_token` à la table `venue`
> (PC-15595) add dms_token to Venue

- api/src/pcapi/local_providers/local_provider.py
Modifier la valeur par défaut d'un booléen : de `False` à `True`.
Dans ce contexte (`local_provider`), on veut que les images envoyées soient enregistrées sans vérification sur le ratio, juste le strict minimum (transformation en jpeg pour commencer).
La valeur de cette méthode est utilisée par `_save_same_thumb_from_thumb_count_to_index` qui appelle `create_thumb` à son tour et s'en sert pour le paramètre `keep_ratio` (qu'on veut donc à `True` pour ne pas avoir de vérification poussée).
> (PC-FIX)[API] fix: local provider thumbs: keep ratio by default

- api/tests/sandboxes/scripts/industrial/test_save_industrial_sandbox.py
Recent (and not so recent) changes have been made to the sandbox.
Since this test is rarely run manually, it was out-of-date.
> (BSR)[API] test: Update sandbox test

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220621T111911_363db8d498a7_add_venue_links.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/repository/clean_database.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py
The BusinessUnit model will be replaced by two separate notions:
- the pricing point: the venue against which we price a booking. It
may be the venue itself or another venue. The pricing point of a
venue MUST have a SIRET. Once a pricing point has been selected,
it should not change.
- the reimbursement point: the venue that holds the bank account
information (through the `bank_information` relationship table)
that should be used when reimbursing bookings of a venue. The
reimbursement point of a venue may change with time.
We store the links between a venue and its pricing and reimbursement
points in two specific tables: `VenuePricingPointLink`,
`VenueReimbursementPointLink` (as we did with `BusinessUnitVenueLink`).
Contrary to what we did with `Venue.businessUnitId`, we do not store
the …
> (PC-15592)[API] feat: Prepare moving away from business units

- .github/workflows/mypy-cop.yml
On détectait mal les commentaires, et donc on ajoutait toujours un commentaire (au lieu de mettre à jour le commentaire existant).
> Correction de la détection des commentaires dans mycop

- api/src/pcapi/admin/base_configuration.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14717
Pouvoir se connecter à Flask Admin sans passer par le SSO Google sur la machine de dev locale.
- création automatique d'un utilisateur admin en local à la première connexion à Flask Admin
- Un peu de refacto pour utiliser une fonction de création d'utilisateur de l'api users, plutôt que le faire en local.
> (PC-14717)[API] feat: connect to flask admin without google sso in development env

- api/src/pcapi/alembic/versions/20220620T174806_cb1d904c149d_add_dms_token_column_to_venue_table.py
- api/src/pcapi/core/offerers/api.py
- api/src/pcapi/core/offerers/factories.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/scripts/venue/add_dms_token_to_each_venue.py
- api/tests/core/offerers/test_api.py
- api/tests/scripts/venue/test_add_dms_token_to_each_venue.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15595
Passer la nom de la colonne `venue.dms_token` en camelcase: `dmsToken`
Edition de la migration (seulement jouée en testing) et du code
- la colonne `venue.dms_token `sera finalement nommée `venue.dmsToken`
> (PC-15595)[API] refactor: change dms_token column name to camelcase

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220622T140243_b9deaf12993c_set_cashflowbatch_label_not_nullable.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/models.py
Existing rows have been populated a few weeks ago.
> (BSR)[API] feat: Make CashflowBatch.label not nullable

- pro/src/components/layout/Tutorial/__specs__/TutorialDialog.spec.jsx
- pro/src/components/pages/Home/__specs__/Homepage.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/BankInformationFields/__specs__/BusinessUnitField.spec.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
- pro/src/new_components/RouteLeavingGuardOfferCreation/__specs__/RouteLeavingGuardOfferCreation.spec.tsx
- pro/src/routes/Bookings/__specs__/BookingsRecap.spec.tsx
- pro/src/screens/OfferEducational/__specs__/OfferEducationalCreationOfferTypeStep.spec.tsx
- pro/src/screens/OfferEducational/__specs__/OfferEducationalCreationOffererStep.spec.tsx
Retrait des `await` sur les methods rtl `getBy*` et `queryBy*` car celle-ci sont synchrones.
> (bsr)[PRO] rtl await in test

- pro/src/ui-kit/form/Select/Select.module.scss
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14916
`$ yarn storybook`
storybook locale: http://localhost:6006/?path=/story/ui-kit-forms-select--formik-field
Le champs est mal aligné sur firefox: 
fix:
> (PC-14916)[PRO] fix: ui-kit: Select: fix vertical align

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220622T143904_d6082bf14ca2_user_isactive_non_nullable_step1.py
- api/src/pcapi/alembic/versions/20220622T143905_090834b497b7_user_isactive_non_nullable_step4.py
- api/src/pcapi/alembic/versions/20220622T143905_905c3b79223a_user_isactive_non_nullable_step3.py
- api/src/pcapi/alembic/versions/20220622T143905_d12acf29a74d_user_isactive_non_nullable_step2.py
- api/src/pcapi/core/users/external/__init__.py
- api/src/pcapi/core/users/models.py
The column is now inherited from `DeactivableMixin`, which defines the
column as non nullable. All rows of the "user" table already validates
this new constraint.
> (BSR)[API] feat: Make `User.isActive` non nullable

- api/src/pcapi/connectors/dms/serializer.py
- api/src/pcapi/core/fraud/api.py
- api/src/pcapi/core/fraud/factories.py
- api/src/pcapi/core/fraud/models.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/routes/external/users_subscription.py
- api/tests/core/fraud/test_api.py
- api/tests/core/subscription/dms/test_api.py
- api/tests/core/subscription/test_api.py
- api/tests/core/users/test_api.py
- api/tests/routes/external/user_subscription_test.py
- api/tests/scripts/beneficiary/fixture.py
- api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15343
Empêcher le downgrade de FraudCheck de OK à KO pour Ubble et DMS.
Ceci est causé par l'appel des webhooks à peu de temps d'intervalle. Lorsque le deuxième appel d'un statut "accepté" arrive, le FraudCheck peut avoir un code d'erreur "ALREADY_BENEFICIARY".
Dans le cas de DMS, on met en place la règle suivante : si le FraudCheck et déjà OK, on arrête le workflow. Si le FraudCheck est KO, on continue quand même car il se peut que l'instructeur revienne sur son choix.
Pour Ubble, les status OK, KO, CANCELLED, SUSPICIOUS sont considérés comme statuts finaux.
Pour Educonnect, on crée un nouveau fraudCheck à chaque fois qu'il y a un nouvel appel, donc on va garder ce processus.
- Branche : …
> (PC-15343) Ensure fraud check idempotency

- pro/src/components/pages/Home/Venues/Venue.scss
it have more than 90char without whitespace
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15387
> (PC-15387)[PRO] fix: crop venue name when

- pro/src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/__specs__/VenueEdition.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/IdentifierFields.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15893
Ajouter `:` au label `Label du Ministère de la Culture ou du CNC` dans les pages de céation/édition d'un lieu
> (PC-15893)[PRO] fix: add colon to venue label

- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/ReimbursementPoint/ReimbursementPoint.module.scss
Fix la marge trop grande entre le bouton `Ajouter des coordonnées bancaires` et le séparateur `ou`
> (PC-15630)[PRO] fix: margin between add cb button and or separator

- api/src/pcapi/core/offerers/repository.py
- api/src/pcapi/routes/pro/offerers.py
- api/src/pcapi/routes/serialization/offerers_serialize.py
- api/tests/routes/pro/get_available_reimbursement_points_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15953
Ajout d'une route get_available_reimbursement_points() permettant de lister les lieux pouvant servir de point de remboursement à un lieu spécifique.
- Ajout de modèles Pydantic et sérialization
- La liste des lieux en retour est **triée** par `publicName` (ou `name` si `publicName` est absent)
N/A
> (PC-15953) Add route to get available reimbursement points

- api/src/pcapi/core/permissions/api.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/auth.py
- api/src/pcapi/routes/backoffice/permissions.py
- api/tests/routes/backoffice/accounts_test.py
- api/tests/routes/backoffice/auth_test.py
- api/tests/routes/backoffice/permissions_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16001
lot de 4 corrections (en 4 commits):
- le endpoint de liste des permissions renvoi le descriptif de chaque permission plutôt que des noms d'Enum
- un problème d’authentification au backoffice renvoie maintenant une 400 avec un message d’erreur au lieu d’une 500
- le endpoint de suppression de rôle renvoi le rôle supprimé.
- le endpoint de mise à jour d’un compte public utilise maintenant la méthode PUT (au lieu de POST)
RAS
RAS
RAS
> Pc 16001 misc back fixes for backoffice

- api/alembic_version_conflict_detection.txt
- api/src/pcapi/alembic/versions/20220629T105234_80c915a0b453_pricing_nullable_business_unit_id_and_siret.py
- api/src/pcapi/core/educational/repository.py
- api/src/pcapi/core/finance/api.py
- api/src/pcapi/core/finance/factories.py
- api/src/pcapi/core/finance/models.py
- api/src/pcapi/core/offerers/models.py
- api/src/pcapi/models/feature.py
- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
- api/tests/core/finance/test_api.py
- api/tests/core/finance/test_integration.py
Commits à relire séparément. Le gros consiste à ajouter un feature flag `USE_PRICING_POINT_FOR_PRICING`, et à modifier le comportement du code de valorisation selon la valeur.
À vue de nez, je pense qu'on pourrait tester la bascule comme suit : 
1. On remplit la table `PricingPointVenueLink` et on migre les `Pricing` (pour remplir leur `Pricing.pricingPointId`).
2. On coupe le cron `price_bookings` (il y a déjà un feature flag pour ça).
3. On exporte les Pricing à l'état `VALIDATED` (non inclus dans le remboursement, donc).
4. On les supprime.
5. On active le feature flag `USE_PRICING_POINT_FOR_PRICING`.
6. On réactive le cron `price_booking`.
7. On vérifie qu'on a les mêmes valorisations : les mêmes réservations sont valorisées, avec les mêmes valeur (plus d'éventuelles réservations qui …
> (PC-15596)[API] Utiliser les points de valorisation (à la place des business units) pour la valorisation

- api/src/pcapi/local_providers/titelive_things/titelive_things.py
- api/src/pcapi/models/product.py
- api/src/pcapi/repository/product_queries.py
- api/tests/core/providers/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15062
Ne pas synchroniser les offres quand le produit correspondant a un nom en "xxx" (le libre est pas encore disponible ou ne l'est plus).
- Lors de la synchro, on exclu les produits dont le nom est xxx, du coup les offres correspondantes sont rejetées
- Un peu de BSR en typant les fonctions de Product
> (PC-15062)[API] feat: stop synchronise xxx named offers

- api/src/pcapi/alembic/script.py.mako
That way, the generated migration file clearly mentions the branch:
"""Add blob.frobul
"""
[...]
revision = 'abcdef123'
[...]
... which helps when (re)viewing code. The branch was not included in
the doctring because `alembic history` already shows it and it would
then appear twice:
363db8d498a7 -> 3a02357e17ba (pre) (head), create_venue_educational_status
cb1d904c149d -> 363db8d498a7 (pre), Add venue_pricing_point_link
Getting the name of the branch is a bit convoluted. I could not find a
better way, given what's provided to the template.
Suggested by François.
> (BSR)[API] Mentionner "pre" ou "post" dans le fichier de migration Alembic

- api/src/pcapi/core/finance/api.py
- api/tests/core/finance/test_api.py
When `generate_cashflows()` fails or is interrupted, we want a simple
way to proceed from where we stopped and re-use the last batch. This
can now be done with:
batch_id = 12345
batch = CashflowBatch.query.get(batch_id)
api._generate_cashflows(batch)
generate_payment_files(batch_id)
> (BSR)[API] refactor: Refactor `generate_cashflows()` for better reusability

- api/src/pcapi/core/fraud/dms/api.py
- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/messages.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15015
Update après retour de validation: envoyer les messages concernant l'éligibilité ET les erreurs de dans les champs de formulaires via la messagerie DMS
None
> PC-15015 send eligibility msg with parsing errors

- api/src/pcapi/routes/serialization/venues_serialize.py
- api/tests/routes/pro/get_venue_test.py
Corriger et améliorer la sérialisation pour `get_venue()`
- Corrige une typo
- Récupère l'attribut `reimbursementPointId` directement au niveau de `VenueReimbursementPointLink`, au lieu d'appeler la relation
- Ajoute des tests
N/A
N/A
> (BSR) Fix typo and remove unnecessary query

- api/src/pcapi/connectors/dms/models.py
- api/src/pcapi/connectors/dms/serializer.py
- api/tests/connectors/dms/serializer_test.py
- api/tests/scripts/beneficiary/fixture.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15325
Etre résilient aux changements des formulations des questions du formulaire DMS
- Au lieu de matcher sur toute la question, on cherche des mots clefs 
None
> PC-15325 use keywords for dms label matching

- api/src/pcapi/core/users/api.py
- api/src/pcapi/models/__init__.py
- api/src/pcapi/routes/backoffice/accounts.py
- api/src/pcapi/routes/backoffice/serialization.py
- api/src/pcapi/routes/backoffice/utils.py
- api/src/pcapi/utils/db.py
- api/tests/routes/backoffice/accounts_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15812
Ajouter un mécanisme de pagination au endpoint de recherche de compte jeune/grand-public qui puisse servir de modèle pour la pagination des autres endpoints qui retournent des listes.
- Ajout d'un modèle pydantic `PaginableQuery` qui sert de base pour les paramètre attendus par le endpoint:
- `page` est le numéro de la page demandée
-  `perPage` est le nombre d'éléments par page
- `sort` est une chaine qui contient, séparés par des virgules,  les noms des champs selon lesquels trier, éventuellement préfixés par un `-` pour trier dans le sens décroissant.
- `PublicAccountSearchQuery` hérite de `PaginableQuery`
- ajout d'une fonction `get_ordering_clauses` pour créer une liste de paramètres à donner à la méthode …
> (PC-15812)[API] feat: backoffice - add pagination to public account search

- api/src/pcapi/core/subscription/dms/api.py
- api/src/pcapi/core/subscription/messages.py
- api/tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15969
Reformuler le message à l'utilisateur en cas de date de naissance non éligible. 
- None 
> (PC-15969)[API] fix: remove link to dms in dms message (user is already on dms)

- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/ReimbursementPoint/ReimbursementPoint.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/ReimbursementPoint/__specs__/ReimbursementPoint.spec.jsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/utils/formatVenuePayload.js
Affichage des points de remboursements dans la liste déroulante de la section coordonnées bancaire.
Point notable : modification de la route (on récupère les points de remboursement et non plus les business Unit)
Conséquence : Quand on poste l'édition du lieu on ne poste plus le businessUnitId mais le reimbursementPointId
> (PC-15637)[PRO] feat: display reimbursement point with venue name

- helmfile.yaml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16081
Upgrade de la version de helm en 0.12.2 pour testin,staging,integration et production
> [PC-16081] Upgrade pcapi helm charts version to 0.12.2

- pro/src/components/pages/Offers/Offer/Confirmation/Confirmation.jsx
- pro/src/components/pages/Offers/Offer/Confirmation/__specs__/Confirmation.spec.jsx
- pro/src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
- pro/src/screens/OfferIndividual/Summary/StockEventSection/StockEventSection.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16043
1er commit : Correction "spinner infini" quand on clique sur "Créer une nouvelle offre" sur la page de confirmation après en avoir créée une. Petite regression : Si on arrive sur le formulaire en ayant juste un offerId en queryString, quand on cliquera sur "Créer une nouvelle offre", on aura l'offererId et la venueId par défaut. Ces infos ne passent plus dans le formulaire des stocks et n'est plus récupéré dans la page de confirmation. Quick & dirty mais pas trop le temps
2e commit : les stocks pouvaient être modifiés mais le prix n'était pas à jour
- _Explications sur …
> (PC-16043)[PRO] fix: new offer creation from confirmation

- api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
Créer un lieu numérique manquant dans la sandbox afin que l'AC de la structure puisse créer des offres numériques.
édition de `create_specific_invoice()
> (BSR)[API]fix: add missing virtual venue in sandbox

- pro/src/new_components/OfferBreadcrumb/OfferBreadcrumb.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16043
Nous ne voulons plus de stepper sur notre page d'édition des offres indiv. 
Ce commit rétablit le stepper pour les offres collectives
- Commit(s) : …
> (PC-16043)[PRO] fix: CollectiveOffer breadcrumb should always be visible

- pro/src/core/Offers/adapters/__specs__/useGetOffer.spec.ts
- pro/src/core/Offers/adapters/serializers.ts
- pro/src/core/Offers/types.ts
- pro/src/screens/OfferIndividual/Summary/StockEventSection/StockEventItem/StockEventItem.tsx
- pro/src/screens/OfferIndividual/Summary/StockThingSection/StockThingSection.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16108
Les types qui avaient été définis dans le front pour beginningDatetime et bookingLimitDatetime n'étaient pas les bons (typés en Date). Dans la PR de suppression de l'ancien générateur api, il y a eu une refacto pour transformer les string recues par le back en Date. Or une des fonction qui utilise ces date ne fonctionne qu'avec une string et non une date, ce qui causait le bug. On ne s'en est pas rendu compte au moment de la refacto car le fichier étant écrit en javascript, il n'y a pas d'erreur relevées au moment de l'analyse statique faite par typescript
> (PC-16108)[PRO] fix: date type use in components

- api/src/pcapi/core/offers/api.py
- api/src/pcapi/core/offers/validation.py
- api/src/pcapi/routes/serialization/offers_serialize.py
- api/tests/core/offers/test_api.py
- api/tests/routes/pro/patch_collective_offer_template_test.py
- api/tests/routes/pro/post_offer_test.py
Rendre la propriété `subcategory_id` obligatoire dans le endpoint de création d'offre.
Ajout de typage.
> (BSR)[API] bsr: turn subcategory mandatory for offer creation

- api/src/pcapi/core/finance/factories.py
- api/tests/core/finance/test_api.py
There is no Pricing that is related to an "educational booking" (a
Booking linked to an EducationalBooking):
=> select count(pricing.id) from pricing
join booking on booking.id=pricing."bookingId"
where booking."educationalBookingId" is not null;
0
They have been migrated as Pricings that are linked to a
CollectiveBooking.
We can thus get rid of EducationalPricingFactory. Also, we can merge
tests and just include a few CollectiveBooking in the general-purpose
test method.
> (BSR)[API] test: Simplify collective booking-related tests of cashflow generation

- backoffice/src/resources/PublicUsers/Components/UserDetailsCard.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16102
Correction d'affichage du label "date de naissance" qui recouvre la valeur ou le placeholder.
> (PC-16012)[BO-FRONT] Fix: birthday label overlap placeholder

- pro/src/components/layout/InternalBanner/InternalBanner.tsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx
- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/__specs__/ReimbursementFields.spec.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15823
Afficher une bannière si la structure ne possède pas de lieu avec SIRET et qu'un lieu sans SIRET essaie d'ajouter des coordonnées bancaires
> Pc 15823 pro reimbursement display banner if offerer has no venue with siret

- pro/src/components/pages/Offerers/Offerer/VenueV1/fields/ReimbursementPoint/ReimbursementPoint.jsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15639
Ne pas afficher de pop-in lors de l'ajout de coordonnées bancaires si le lieu possède un siret
> (PC-15639)[PRO] fix: dont display popin if venue has siret

- .githooks/pre-commit
Configuration of mypy and pylint have been moved to
`pyproject.toml` (see a1ab0590cab79819eddd7ee161996874201ba234 and
d8feeda8331560a37afb75f32762670ea08e8d3c). No need to specify that file.
> (BSR)[API] fix: Fix location of configuration files in pre-commit hook

- api/src/pcapi/core/bookings/external/booking_notifications.py
- api/src/pcapi/scheduled_tasks/commands.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14328
Utiliser `argument`/`nargs`, parce que `option` avec `type=list` ne fonctionne pas comme prévu : `--departments=123` va renvoyer `("1", "2", "3")`.
Il faudra ensuite modifier la manière dont est utilisée la commande.
> (PC-14328)[API] feat: click: use nargs instead of option

- api/pyproject.toml
Some modules are unnecessarily listed here. Some modules are not used
anymore and/or have never been used (e.g. lxml and spidev).
> (BSR)[API] chore: Clean up "extension-pkg-whitelist" pylint option

- api/src/pcapi/use_cases/save_venue_bank_informations.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16089
check_offerer() ne doit pas être appelé pour un dossier de procédure V4 puisque le champ siret est facultatif.
> (PC-16089)[API] fix: allow empty siret field in bank info  V4 procedure

- .github/workflows/update-api-client.yml
Temps gagné avec le cache yarn : ~30s
Temps gagné avec la parallélisation : ~ 1m
> WIP (BSR) cache yarn packages in update-api-client workflow

- api/src/pcapi/domain/demarches_simplifiees.py
- api/src/pcapi/use_cases/save_venue_bank_informations.py
- api/tests/domain/demarches_simplifiees_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16089
Corriger l'erreur de siret absent dans un dossier de procédure CB v4
- Mieux traiter la réponse de l'API DMS en fonction de la procédure
- Corriger le test paramétré `ParseRawBicDataTest`
> (PC-16089)[API] fix: allow empty siret field in bank info V4 procedure

- api/src/pcapi/core/offerers/api.py
- api/tests/utils/pdf_creation_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16228
Résout une erreur levée quand le front renvoie `reimbursementPointId` (même `null`) dans le formulaire d'édition de lieu.
> (PC-16228)[API]fix: edit update_venue

- pro/src/components/pages/Offers/Offer/Offer.scss
- pro/src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferForm.jsx
- pro/src/components/pages/Offers/Offer/Stocks/StockItem/domain.js
- pro/src/core/Offers/adapters/__specs__/useGetOffer.spec.ts
- pro/src/core/Offers/adapters/serializers.ts
- pro/src/core/Offers/types.ts
- pro/src/routes/OfferIndividualSummary/serializer.ts
- pro/src/screens/OfferIndividual/Summary/OfferSection/OfferSection.tsx
- pro/src/screens/OfferIndividual/Summary/StockEventSection/StockEventItem/StockEventItem.tsx
- pro/src/screens/OfferIndividual/Summary/StockEventSection/StockEventSection.tsx
- pro/src/screens/OfferIndividual/Summary/Summary.tsx
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16218
Affichage des stocks par date décroissante sur la page de récap + Affichage de l'heure de l'évènement en fonction du département du lieu ayant créé l'offre.
- PR : `(PC-XXX) Description rapide …
> (PC-16218)[PRO] fix: display right timezone time depending on departement

- .githooks/pre-commit
A un moment corriger les tests a la main c'est lourd (en plus d'être innutile) cette pr vise a enlever la validation mypy des fichiers de tests pour le pre-commit hook (sachant qu'ils sont deja exclus dans quality-api)
> (BSR) remove mypy validation on test files from precommit hoog

- pro/src/components/pages/Offers/Offer/Stocks/EventStocks.jsx
- pro/src/components/pages/Offers/Offer/Stocks/StockItem/domain.js
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16274
sur cette page: https://pro.testing.passculture.team/offre/BEYQ/individuel/recapitulatif
le click sur le lient "modifier les stock" provoquait une erreur.
Le stock etant un produit, la propriété "beginningDate" n'etait pas calculé.
A present le code ignore ce calcule lorsque la propriété n'est pas défini
> (PC-16274)[PRO] fix: do not compute time for product stocks
