pass-culture/pass-culture-main

pro/src/components/StocksEventList/StocksEventList.tsx
pro/src/components/StocksEventList/__specs__/StocksEventList.spec.tsx
pro/src/ui-kit/Pagination/Pagination.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21262
_Divers bug fixs liés à la pagination
-> quand la page max était dépassé on pouvait l'augenter à volonté
-> le select sur une checkbox selectionné toutes les lignes à la même position
-> idem pour la suppression
-> après suppression on pouvait se retrouver sur une page vide à la pagination dépassée (page 3/2 par exemple)
-> après suppression, lorsqu'il ne restait plus qu'une page on pouvait se retrouver sur une page vide en étant softlock (il n'y avait plus de bouton de pagination)

(PC-21262)[PRO] fix: various bugs with pagination in recurrence

---

api/src/pcapi/core/offers/factories.py

Les `*StockFactory` sont utilisés dans nos sandbox mais génèrent des dates trop précises avec des secondes et millisecondes. 
Cette précision n'est pas atteignable en utilisant le front, ce qui amène à une mauvaise reconnaissance des champs qui ont changés comme
```python
if beginning_datetime not in (UNCHANGED, stock.beginningDatetime):
modifications["beginningDatetime"] = beginning_datetime
```

(BSR)[API] fix: offer factory datetime precision

---

pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/updateIndividualOffer.spec.ts
pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21570
La modification du `bookingEmail` n'est pas autorisé pour les offres Allociné, donc il faut le sérialiser en `undefined` quand il n'apparait pas dans le formulaire, càd quand `sentValues.receiveNotificationEmails` vaut `undefined` plutôt que `false`

(PC-21570)[PRO] fix: patch offer arg serialization

---

pro/src/screens/SignupJourneyForm/Offerers/Offerers.tsx
pro/src/screens/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21493
- Afficher dans la liste des lieu, le publicName au lieu du name

(PC-21493)[PRO] fix: display public name or name if public name is not set

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230411T140035_4bec5e4e7ee7_add_password_to_cgr_cinema_details.py
api/src/pcapi/connectors/cgr/cgr.py
api/src/pcapi/core/providers/factories.py
api/src/pcapi/core/providers/models.py
api/tests/connectors/cgr/api_cgr_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21655
- Ajouter une colonne `password` dans la table `CGRCinemaDetails`

(PC-21655)[API] feat: Add CGR password column in CGRCinemaDetails

---

pro/src/screens/OfferType/OfferType.tsx

Après avoir déshumanisé la route "/collective/offers" il restait un appel sur le hub de création d'offre

(BSR)[PRO] fix: dehumanize /collective/offers call

---

.github/workflows/tests-pro.yml
pro/src/screens/VenueForm/__specs__/serializers.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21346
Exemple de run qui échoue, il y a un report et les screenshots sont sauvegardés : https://github.com/pass-culture/pass-culture-main/actions/runs/4617537799?pr=5990
Exemple de run en succès : cf check CI ci dessous

(PC-21346)[PRO] ci: run e2e tests in GitHub Actions

---

pro/src/pages/Offers/Offers/ActionsBar/ActionsBar.tsx
pro/src/pages/Offers/Offers/ActionsBar/ConfirmDialog/DeactivationConfirmDialog/DeactivationConfirmDialog.tsx
pro/src/pages/Offers/Offers/ActionsBar/ConfirmDialog/DeactivationConfirmDialog/__specs__/DeactivationConfirmDialog.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21022
Changer le wording de la popin lorsqu'on souhaite désactiver une offre ou plusieurs offres collectives depuis la page de liste d'offre
Avant : 
Après : 

(PC-21055)[PRO] feat: change wording deactive offer popin

---

api/src/pcapi/alembic/versions/20230407T095241_515b8245129f_remove_old_search_indexes.py
api/src/pcapi/core/providers/commands.py
api/src/pcapi/core/providers/tasks.py

The `synchronize_venue_providers_apis` cron enqueues a lot of tasks
within a short time period, generating a lot of same-looking logs that
differ only by the `venue_provider_ids` argument, which is not helpful
if we are looking for a particular provider.

(BSR)[API] feat: Betters logs for `synchronize_venue_providers_task`

---

pro/src/pages/Signup/SignupContainer/SignupContainer.tsx
pro/src/pages/Signup/SignupContainer/SignupForm.tsx
pro/src/pages/Signup/SignupContainer/__specs__/SignupContainer.spec.tsx
pro/src/pages/Signup/__specs__/Signup.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21616
- Wording titre page : Créer votre compte professionnel → Créer votre compte
- Ordre des champs (faire remonter Nom et prénom avant) : 
Nom
Prénom
Adresse mail
Mot de passe
Téléphone

(PC-21616)[PRO] refactor: sign up title wording and field order

---

pro/src/screens/OfferIndividual/StocksEventCreation/RecurrenceForm.tsx
pro/src/screens/OfferIndividual/StocksEventCreation/__specs__/RecurrenceForm.spec.tsx
pro/src/screens/OfferIndividual/StocksEventCreation/form/validationSchema.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21739
Une incompréhension a mené a des stocks créés en plusieurs fois, petit fix et amélioration pour que l'utilisateur comprenne qu'il faut des catégories de prix différentes.
- Ajout d'une erreur sur le champ Tarif (le screen le montre pas mais l'erreur est sur les 2 champs)
- Cacher le bouton "Ajouter d'autres places et tarifs" quand le nombre de tarif séléctionnés est = au nombre de tarif dispo

(PC-21739)[PRO] fix: only distinct price categories are allowed in event reccurency Form

---

pro/src/screens/SignupJourneyForm/Offerer/Offerer.module.scss
pro/src/screens/SignupJourneyForm/Offerer/Offerer.tsx
pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21619
Bannière “À savoir” 
- “Votre structure dépend d’un autre SIRET ?” → “Vous êtes un équipement d’une collectivité ou d'un établissement public ?”
- “Renseignez le SIRET de la collectivité[…] auquel vous êtes rattaché.” → “Renseignez le SIRET de la structure à laquelle vous êtes rattaché.”
-  ajout d’un lien externe qui redirige vers la FAQ : Label : “En savoir plus”(lien :  )

(PC-21619)[PRO] feat: wording and add link to new onboarding offerer page banner

---

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21769
De la même manière que dans le ticket PC-21578, l'équipe marketing souhaite utiliser le tag défini dans Sendinblue, plutôt que celui défini dans le backend, pour les emails 257 et 78 (prod).

(PC-21769)[API] feat: Do not tag transactional emails 257 and 78 to Sendinblue - tagged in SiB by marketing

---

pro/src/screens/SignupJourneyForm/Validation/Validation.module.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21620
- Corriger le padding dans les deux blocs gris
- 20px -> 16px

(PC-21620)[PRO] fix: validation informations padding

---

pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.module.scss
pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx
pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx
pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveVenueInformations.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21567
Afficher un message indiquant que la demande a été classée sans suite le cas échéant. 
BSR : Si le lieu à une démarche en cours (non acceptée) mais possède déjà un adageId, on affiche un message en ce sens et non plus la timeline 
Cas classée sans suite 
Choisir la structure `eac_sans_suite` puis modifier le lieu `accepted_dms eac_sans_suite`

(PC-21567)[PRO] feat: handle dropped by dms status

---

helmfile.yaml

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21511
Une nouvelle registry a été créé depuis le 30/03 et doit être maintenant utilisé par le helmfile
Les versions 0.17.4 à 0.19.5 sont actuellement bien présentes sur cette registry

(PC-21511) fix(helm): Helm chart should be on pass-culture-helm-registry

---

helmfile.yaml

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21511
Le Chart helm n'était pas complètement fonctionnel, il manquait notamment un SA pour une partie du backoffice afin que le replica soit up
Rajout de la création d'un SA et bump de la version du helm Chart

(PC-21511) fix(helm): Deployment for backoffice should have a service account

---

api/src/pcapi/routes/backoffice_v3/offers.py
api/tests/routes/backoffice_v3/offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21771
Réindexer une ou plusieurs offres lors de l'édition simple ou multiple, via le backoffice.

(PC-21771)[API] fix: bo: reindex offers on (batch) update

---

api/src/pcapi/routes/backoffice_v3/i18n.py
api/tests/routes/backoffice_v3/accounts_test.py

Ajouter un wording pour la modification de `validatedBirthDate` sur un compte jeune

(BSR)[API] fix: fix info modified history on public accounts

---

api/src/pcapi/routes/serialization/venues_serialize.py
api/tests/routes/pro/get_venues_test.py
pro/src/apiClient/v1/models/VenueListQueryModel.ts
pro/src/apiClient/v1/services/DefaultService.ts
pro/src/core/Bookings/adapters/getVenuesAdapter.ts
pro/src/core/Venue/adapters/getOfferIndividualVenuesAdapter/__specs__/useOfferIndividualVenues.spec.ts
pro/src/core/Venue/adapters/getOfferIndividualVenuesAdapter/getOfferIndividualVenuesAdapter.ts
pro/src/core/Venue/adapters/getOfferIndividualVenuesAdapter/useOfferIndividualVenues.ts
pro/src/core/Venue/adapters/getVenuesForOffererAdapter/__specs__/getVenuesForOffererAdapter.spec.ts
pro/src/core/Venue/adapters/getVenuesForOffererAdapter/getVenuesForOffererAdapter.ts
pro/src/pages/OfferIndividualWizard/__specs__/OfferIndividualWizard.spec.tsx
pro/src/pages/OfferIndividualWizard/__specs__/OfferIndividualWizardAdmin.spec.tsx

It's been a no-op since b67f15e0be2ade5795f653531119489ad8aa4c45.

(BSR)[PRO] chore: Suppression de `VenueListQueryModel.validatedForUser`

---

pro/jest.config.js
pro/package.json
pro/src/pages/AdageIframe/app/App.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/SearchBox/SearchBox.scss
pro/src/pages/AdageIframe/index.scss
pro/yarn.lock

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20893
Supprimer la dépendance fontsource/barlow que l'on utilise dans adage.

(PC-20893)[PRO] chore: remove adage fontbarlow package

---

api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_multiple_field.html

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21787
Restore la class tom select pour que l'input `select_multiple_field.html` soit aussi initialisé avec tom select
On s'y perds encore, p-e il faudrait le renommer en `tom_select_field_static` ?
NA
NA

(PC-21787)[API] fix: restore tom select class on select multiple field

---

api/src/pcapi/core/external/zendesk.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21773
Dans le cadre du chantier technique consistant à enlever les références à l'environnement (ici dans le client Zendesk):
- Ajout d'une variable d'environnement pour activer/désactiver l'envoi de requêtes à Zendesk. Il est désactivé par défaut. …

(PC-21773)[API] refactor: Add env var to enable/disable requests to Zendesk

---

pro/src/screens/SignupJourneyForm/Validation/Validation.module.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21620
- La marge entre le bloc gris et le texte interieur doit être de 16px
- Corriger la marge en bas du bloc

(PC-21620)[PRO] fix: ui returns margin bottom

---

pro/src/components/SignupJourneyBreadcrumb/__specs__/SignupJourneyBreadcrumb.spec.tsx
pro/src/context/SignupJourneyContext/SignupJourneyContext.tsx
pro/src/screens/SignupJourneyForm/Activity/ActivityForm.tsx
pro/src/screens/SignupJourneyForm/Activity/__specs__/ActivityForm.spec.tsx
pro/src/screens/SignupJourneyForm/Activity/__specs__/ActivityScreen.spec.tsx
pro/src/screens/SignupJourneyForm/Activity/constants.ts
pro/src/screens/SignupJourneyForm/Activity/validationSchema.tsx
pro/src/screens/SignupJourneyForm/Offerers/Offerers.tsx
pro/src/screens/SignupJourneyForm/Validation/Validation.tsx
pro/src/screens/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21517
Lors du submit de l'étape de validation du nouveau parcours d'onboarding:
- Ajouter createVenueWithoutSiret dans le cas d’une création de lieu sans SIRET
- Utiliser publicName à la place de name
- Utiliser venueTypeCode à la place devenueType
Pour accéder au nouveau parcours d'inscription:
Après la création d'un nouveau compte, juste après la connexion, sinon il faut se rendre à `/parcours-inscription`
En local ce n'est pas vraiment possible, donc il faut aller sur l'url directement, ou alors il faut supprimer via le backoffice les structures d'un compte en local, le pro par exemple
à la connexion, le parcours s'affichera
Il faut le FF: WIP_ENABLE_NEW_ONBOARDING
- …

(PC-21517)[PRO] feat: update submit new offerer datas

---

api/src/pcapi/domain/password.py
api/tests/domain/password_test.py
api/tests/routes/pro/post_change_password_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21621
Sur la page profile. Dans la section changement du mot de passe. Lorsque l’on rentre le “mot de passe actuel” avec une erreur (puis qu’on renseigne un nouveau mot de passe et valide la page) le message d’erreur sous le champs n’est pas le bon. Remplacer :
Ton ancien mot de passe est incorrect
PAR
Votre mot de passe actuel est incorrect
- Branche : PC-21621-wording-profile-msg
- PR : (PC-21621) [PRO] feat: Wording modification de mot de passe
- Commit(s) : (PC-21621) [PRO] feat: Wording modification de mot de passe

(PC-21621) [PRO] feat: Wording modification de mot de passe

---

pro/src/pages/ResetPassword/ChangePasswordForm/ChangePasswordForm.tsx
pro/src/pages/ResetPassword/__specs__/ResetPassword.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21499
Sur la page de réinitialisation du mot de passe, changer les wording suivants : 
- Remplacer “Créer un nouveau mot de passe” par “Définir un nouveau mot de passe”
- 
- SUPPRIMER la phrase “Saisissez le nouveau mot de passe”
- 
- Remplacer “Mon mot de passe” par “Votre mot de passe”
- 
- Remplacer “Envoyer” par “Valider”
- Branche : `PC-21499-wording-message-password`
- PR : `(PC-21499) Description rapide de l' US`
- Commit(s) : `(PC-21499)[PRO] Wording message corrections de mdp.

(PC-21499)[PRO] feat: Wording corrections de Réinitialisation du MDP

---

pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx
pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx
pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveVenueInformations.tsx
pro/src/components/VenueForm/EACInformation/NewEACInformation.tsx
pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.module.scss
pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx
pro/src/pages/Home/Venues/Venue.tsx
pro/src/pages/Home/Venues/VenueList.tsx
pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21780
Sur la homepage : 
- Ne pas afficher le bouton 'Suivre ma démarche en cours' et/ou 'Mes informations pour les enseignants' si le lieu à un adageId depuis plus de 30j 
- Si le FF WIP_ENABLE_NEW_OFFER_CREATION_JOURNEY n'est pas activé , afficher quand même le bouton 'Suivre ma démarche en cours'
Dans le suivi dms : 
- Fix le lien pour accèder aux informations pour les enseignants 
Creation de lieu 
- Afficher une bannière pour indiquer que le formulaire pour les informations pour les enseignants ne sera disponible qu'une fois le lieu créé

(Pc 21780)[PRO] eac retours recettes dev suivi dms

---

pro/src/pages/AdageIframe/app/AppLayout.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21828
Supprimer l'espace blanc en trop en haut de l'iframe adage 
Avant 
Après

(PC-21828)[PRO] fix: remove empty space in top of adage iframe

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230418T121413_298d82d25d41_offerer_provider.py
api/src/pcapi/alembic/versions/20230418T121548_ed3641db9970_offerer_provider.py
api/src/pcapi/alembic/versions/20230418T121721_f67ecae084d5_offerer_provider.py
api/src/pcapi/alembic/versions/20230418T121953_fba49261c75f_offerer_provider.py
api/src/pcapi/alembic/versions/20230418T122206_e9c5ec411702_offerer_provider.py
api/src/pcapi/alembic/versions/20230418T122247_7e3cb87c42ec_offerer_provider.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/core/providers/models.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21428
L'idée est de pouvoir relier un prestataire technique (Provider) à un offerer, c'est une demande légale. La structure associée au provider est celle qui a validée les CGU d'utilisation de l'api.
Une url de logo est ajoutée aux provider, ce logo sera stocké dans un bucket gcp et affiché sur le portail pro

(PC-21428)[API] feat: Link providers to offerers

---

pro/src/screens/OfferIndividual/StocksEventEdition/StockFormList/validationSchema.ts

`Yup.Schema.when` second argument is a callback that takes a list as an argument, not a scalar
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21832

(PC-21832)[PRO] fix: stock form validation schema

---

api/src/pcapi/core/external/attributes/api.py
api/src/pcapi/core/external/batch.py
api/src/pcapi/core/external/sendinblue.py
api/src/pcapi/routes/native/v1/cultural_survey.py
api/tests/core/external/batch_test.py
api/tests/core/external/sendinblue_test.py
api/tests/routes/native/v1/cultural_survey_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20492
Faire remonter les réponses à la question “avec ton pass Culture, tu aimerais…” sous forme de liste dans un nouvel attribut (il pourrait par exemple s’appeler “INTENDED_CATEGORIES”) dans Sendinblue et Batch

(PC-20492)[API] feat: Send projections from cultural survey to Sendinblue and Batch

---

api/src/pcapi/routes/pro/signup.py
api/tests/routes/pro/signup_pro_V2_test.py
api/tests/routes/pro/signup_pro_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21573
Ne pas enregistrer les flags firebase de A/B testing de _création d'offre_ lors de _l'inscription_ de l'utilisateur.

(PC-21573)[API] feat: do not save firebase flags during signup

---

pro/src/screens/SignupJourneyForm/Offerers/Offerers.tsx
pro/src/screens/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21612
- Wording
- Supprimer le siren affiché à l'utilisateur sur la page et sur la popin de rattachement
Pour tester:
- Avoir le FF: WIP_ENABLE_NEW_ONBOARDING
- En local, dans le fichier src/screens/SignupJourneyForm/Offerer/Offerer.tsx, dans le submit, ne garder que la ligne       `navigate('/parcours-inscription/structure/rattachement')` (l63)
- Se rendre à /parcours-inscription, et effectuer le parcours classique jusqu'à la page en question

(PC-21612)[PRO] refactor: wording and remove siren informations

---

api/src/pcapi/routes/backoffice_v3/docs/JSDOC.md
api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
api/src/pcapi/static/backofficev3/js/pc-backoffice-app.js

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21883
- Passage du csrf token via meta pour être configurer avec turbo frame
https://turbo.hotwired.dev/handbook/frames
- Usage du csrf token via le meta au lieu de via la balise script
- Ajout de hook turbo frame de navigation
- Modification du hook turbo frame après un frame load plutôt qu'un frame render
NA
Après ce commit, on peut enlever le `turbo="false"` sur le `<body />` pour activer la navigation turbo globalement.
NA

(PC-21883)[API] fix: store csrf in meta and add turbo event handlers for navigation

---

api/src/pcapi/routes/backoffice_v3/docs/JSDOC.md
api/src/pcapi/routes/backoffice_v3/templates/admin/feature_flipping.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
api/src/pcapi/static/backofficev3/js/addons/pc-confirm-modal.js

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21887
- Ajout d'un add on js qui s’occupera de détecter la non confirmation d'une modal et restaurera la valeur initial
- Utilisation de l'addon sur la modal de confirmation des features flips.
NA
NA
NA

(PC-21887)[API] fix: reset ff checked state if change not confirmed

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230419T131925_a93013fc9866_delete_usersuspension_table.py
api/src/pcapi/core/history/models.py
api/src/pcapi/core/users/constants.py
api/src/pcapi/core/users/models.py
api/src/pcapi/repository/clean_database.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21875
Suppression de la table inutilisée UserSuspension

(PC-21875)[API] chore: delete unused UserSuspension table

---

api/src/pcapi/routes/backoffice_v3/collective_offers.py
api/src/pcapi/routes/backoffice_v3/custom_reimbursement_rules.py
api/src/pcapi/routes/backoffice_v3/offers.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21731
Avoir un temps de réponse de moins de 5 secondes sur la recherche d’offres
Suppression de la recherche par le milieu du string pour être iso avec flask admin
NA
NA

(PC-21731)[API] fix: optimise offers queries

---

pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx
pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.tracker.spec.tsx
pro/src/pages/Home/Venues/Venue.tsx
pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21834
Afficher les boutons pour accéder au suivi de la démarche DMS pour les démarches refusé ou sans_suite
Utiliser les structure `eac_sans_suite` et `eac_refuse`

(PC-21834)[PRO] feat: display dms buttons when application is refused

---

api/src/pcapi/connectors/dms/models.py
api/src/pcapi/core/fraud/factories.py
api/src/pcapi/core/fraud/models.py
api/tests/core/subscription/dms/test_api.py
api/tests/routes/external/user_subscription_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14748
Changer la parsing de `registration_datetime` dans `DMSContent` pour le faire faire par le validateur pydantic sur le `draft_date` de DMSApplicationResponse.
- Ajout d'un formateur dans la classe DMSApplicationResponse pour l'attribute draft_date.
- PR : …

(PC-14748)[API] refactor: Parse registration_datetime with pydantic validator in DMSContent

---

api/src/pcapi/routes/backoffice_v3/__init__.py
api/src/pcapi/routes/backoffice_v3/collective_offer_templates.py
api/src/pcapi/routes/backoffice_v3/forms/collective_offer_template.py
api/src/pcapi/routes/backoffice_v3/templates/collective_offer_template/list.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
api/tests/routes/backoffice_v3/collective_offer_templates_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21412
Ajout de la page offres collectives vitrines
- Copier coller de `collective_offers.py`
- Modification du naming `collective_offers` -> `collective_offer_templates`
- Suppression du code adage du type:
```py
if collective_offer_template.institutionId is not None:
adage_client.notify_institution_association(serialize_collective_offer(collective_offer_template))
```
- Catégorie des offres collectives vitrines récupéré depuis la sous catégorie.
NA

(PC-21412)[API] feat: add collective offer template

---

api/src/pcapi/core/offerers/factories.py
api/src/pcapi/core/offerers/models.py
api/tests/core/offerers/test_models.py
api/tests/core/search/test_backend_algolia.py
api/tests/routes/pro/get_venue_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18868
déterminer une bannière par défaut pour chaque lieu qui n'en a pas en fonction de sa catégorie
- déclaration d'une hybrid_property bannerUrl (l'attribut de modèle `bannerUrl` est devenu `_bannerUrl`)
- Commit(s) : …

(PC-18868)[API] feat: add default venue banner according to venue category

---

pro/jest.setup.ts
pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
pro/src/screens/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21357
Supprimer 2 warnings jest whitelistés : 
- Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.%s
- Warning: Cannot update a component (`%s`) while rendering a different component (`%s`). To locate the bad setState() call inside `%s`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render%s

Pc 21357 remove warning cannot update component

---

pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.tsx
pro/src/pages/LostPassword/__specs__/LostPassword.spec.tsx
pro/src/pages/SignIn/SigninForm/SigninForm.tsx
pro/src/pages/SignIn/__specs__/SignIn.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21378
Sur la [page Mot de passe égaré](https://pro.testing.passculture.team/mot-de-passe-perdu) :
Remplacer le wording “égaré” par “oublié”. 
Remplacer le wording “Envoyer” du bouton par “Valider”
Retirer le mot “obligatoire” sur le champActuel
Sur la [page de connexion](https://pro.testing.passculture.team/connexion) remplacer le wording “égaré” par “oublié”
- Branche : PC-21378-wording-message-connexion
- Commit(s) : PC-21378 wording message connexion

PC-21378 wording message connexion

---

api/src/pcapi/core/offerers/api.py

ignore 6 messages mypy qui ne comprend pas ce qui se passe quand on utilise une hybrid_property

(BSR)[API] fix: ignore mypy warning about hybrid_property type

---

pro/src/screens/OfferType/OfferType.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21950
Fix le wording pour les offres vitrines. On affichait par erreur la valeur d'un FF dans la description du bouton

(PC-21950)[PRO] fix: fix wording in offer type selection

---

.github/workflows/tests-api.yml

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21953
Actuellement les Pytests Report ne donnent plus le résultat des pytests effectuées, ici on les réactive.
Depuis le passage au self-hosted le chemin d'accès au junit a changé

(PC-21953) fix(ci): Pytest should have always a report

---

.github/workflows/tests-api.yml

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21952
Accroitre le nombre de jobs pour pylint afin d'accélérer le run
Compte tenu de l'image utilisée pour les runners  nous pouvons augmenter le nombre de job jusqu'à 15, le job pylint passe  ainsi de 3min à 45 secondes

(PC-21952) feat(ci): Increase number of worker for pylint

---

pro/src/core/FirebaseEvents/constants.ts
pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.tracker.spec.tsx
pro/src/pages/Home/Venues/Venue.tsx
pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21893
Ajouter un tracker pour tracker le clic sur le bouton d'accès au suivi du référencement DMS depuis la home

(PC-21893)[PRO] feat: log event when clicking dms timeline link

---

api/src/pcapi/core/offerers/models.py
api/tests/core/offerers/test_models.py
api/tests/routes/pro/get_venue_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18868
correction de la construction des URLs de bannière par défaut pour les lieux
RAS
RAS
RAS

(PC-18868)[API] fix: fix default banner urls

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/users/api.py
api/src/pcapi/routes/pro/offerers.py
api/tests/core/offerers/test_api.py
api/tests/core/users/test_api.py
api/tests/routes/backoffice_v3/pro_users_test.py
api/tests/routes/pro/post_save_new_onboarding_data_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21938
- Dans le parcours actuel, le mail de bienvenue est déclenché post création de compte
- Dans le nouveau parcours d’inscription, le mail de bienvenue doit être déclenché post validation et création de l’espace.

(PC-21938)[API] modify welcome pro email triggers

---

pro/src/core/FirebaseEvents/constants.ts
pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
pro/src/screens/OfferEducationalStock/__specs__/OfferEducationalStock.spec.tsx

Ajouter un tracker à l'ouverture de la modal 6e/5e dans la création de stock collective

(PC-21795)[PRO] feat: log event when wrong students modal is displayed

---

pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/serializers.spec.ts
pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/updateIndividualOffer.spec.ts
pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts
pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.edition.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19125
- Problème d'envoi de formulaire lors de la mise à jour des modalités de retrait à la sélection du choix "Événement sans billet".
- Envoi null au lieu de undefined pour withdrawalDelay si c'est un événement sans billet.

(PC-19125)[PRO] fix: issue send withdrawalDelay as null instead of undefined

---

api/src/pcapi/utils/urls.py
api/tests/core/mails/transactional/pro/first_venue_approved_offer_to_pro_test.py
api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py
api/tests/core/mails/transactional/users/reported_offer_by_user_test.py
api/tests/utils/urls_test.py

Issues are experienced with redirection, so let's use numeric ids since all URL paths have now been migrated
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22011
Utiliser les id numériques, non humanisés, dans tous les liens depuis FA ou le backoffice vers PC Pro.
Toutes ces URL utilisent désormais l'id numérique, donc utilisons les plutôt que de gérer des soucis de redirection.

(PC-22011)[API] fix: use non-humanized ids in all links from the backoffice to PC Pro

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/factories.py
api/src/pcapi/core/users/api.py
api/tests/core/offerers/test_api.py
api/tests/routes/backoffice_v3/offerers_test.py
api/tests/routes/pro/signup_pro_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21206
Lors du rejet d’une structure, on désactive la structure
Si on valide une structure et que cette structure est désactivée, on active la structure
Si on passe en attente une structure et que cette structure est désactivée, on active la structure

(PC-21206)[API] feat: set offerer active when validated and vice versa

---

api/src/pcapi/routes/backoffice_v3/offers.py

Soit ça, soit rajouter une class `.alert-error` qui extends `.alert-danger`
Avoir le bon style sur l'alert d'erreur
NA
NA
NA

(BSR)[API] fix: alert error not displaying correctly

---

api/src/pcapi/routes/backoffice_v3/collective_offer_templates.py
api/src/pcapi/routes/backoffice_v3/forms/collective_offer_template.py
api/src/pcapi/routes/backoffice_v3/templates/home/home.html
api/tests/routes/backoffice_v3/collective_offer_templates_test.py
api/tests/routes/backoffice_v3/home_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21412
Activation du lien dashboard pour collective offer templates 
- trier par `createdDate` desc
- seulement les offres vitrines avec le statut `PENDING` 
- seulement pour les structures validées.
- Ajout du params `order` avec valeur par défaut `desc`
- Modification du params `sort` avec valeur par défaut `createdDate`.
NA

(PC-21412)[API] fix: add dashboard link to collective offer templates

---

api/src/pcapi/core/users/api.py
api/tests/core/users/test_api.py
api/tests/routes/backoffice_v3/accounts_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21415
Chercher une adresse email dans l'historique des changements d'email lors d'une recherche de compte jeune et grand public (dans le backoffice).

(PC-21415)[API] feat: bo: public account: search old email

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/serialization/offerers_serialize.py
api/tests/core/offerers/test_api.py
api/tests/routes/pro/post_save_new_onboarding_data_test.py
pro/src/apiClient/v1/models/SaveNewOnboardingDataQueryModel.ts
pro/src/screens/SignupJourneyForm/Validation/Validation.tsx
pro/src/screens/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21394
Utiliser l'adresse envoyée par le front lors du nouvel onboarding, au lieu d'appeler l'API Adresse sans input usager.
- Adaptation du modèle Pydantic et de la route `/offerers/new`

(PC-21394)[API] feat: use address from form during new onboarding

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py

(BSR)[API] fix: sandbox - null value in column "providerId"

---

api/src/pcapi/routes/backoffice_v3/collective_offers.py
api/src/pcapi/routes/backoffice_v3/templates/collective_offer/list.html
api/tests/routes/backoffice_v3/collective_offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22022
Ajouter la date de l'événement sur la page Offres collectives
- Ajout d'une colonne `Date de l'évènement` sur le tableau de la page `/backofficev3/pro/collective_offer`
NA
NA

(PC-22022)[API] fix: add begginingDatetime to collective offers table

---

api/src/pcapi/routes/backoffice_v3/providers/blueprint.py
api/src/pcapi/routes/backoffice_v3/providers/contexts/allocine.py
api/src/pcapi/routes/backoffice_v3/providers/contexts/base.py
api/src/pcapi/routes/backoffice_v3/providers/contexts/boost.py
api/src/pcapi/routes/backoffice_v3/providers/contexts/cgr.py
api/src/pcapi/routes/backoffice_v3/providers/contexts/cineoffice.py
api/src/pcapi/routes/backoffice_v3/providers/forms.py
api/src/pcapi/routes/backoffice_v3/templates/components/forms/tom_select_field.html
api/src/pcapi/routes/backoffice_v3/templates/providers/get/cgr.html
api/tests/routes/backoffice_v3/providers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21790
Ajout d'un CRUD pour les pivot CGR
Identique à celle de la page flask admin (ie: https://backend.testing.passculture.team/pc/back-office/cgr/)
- À discuter : Ajout de flash message pour l'utilisateur si l'API CGR est KO. (p-e pas souhaitable ?)
NA

(PC-21790)[API] feat: add CGR pivot CRUD

---

.github/workflows/deploy.yml

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21084
Le déploiement de adage ne doit plus s'effectuer sur le bucket pour les environments testing et staging
Modification de la CI pour ne trigger que l'environment production

(PC-21084) feat(ci): deploy adage front only for production environment

---

api/src/pcapi/routes/backoffice_v3/providers/blueprint.py
api/src/pcapi/routes/backoffice_v3/providers/forms.py
api/tests/routes/backoffice_v3/providers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21447
Les acteurs de la grande distribution, qui ont déjà un compte sur le pass Culture, vont avoir des `Providers` associés à leur compte : 
- Il faut pouvoir autoriser la liaison d'un `Provider` à un `Offerer` déjà existant
- La modification d'un `Provider` ne doit pas impacter l'`Offerer`

(PC-21447)[API] feat: allow new providers to be linked to existing offerer

---

pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/TicketWithdrawal.tsx
pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/__specs__/TicketWithdrawal.spec.tsx
pro/src/components/OfferIndividualForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx
pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts
pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.edition.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19125
- Corriger l'erreur lors de la mise à jour des modalités de retrait d'une offre
- Lorsque la valeur de withdrawalType est mise à jour, maj du champ wihdrawalDelay avec la bonne valeur

(PC-19125)[PRO] fix: on withdrawalType change set withdrawalDelay correct value

---

api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/core/offerers/test_models.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21611
Amélioration de l'UX des dossier DMS adage sur le détail d'un lieu.
- Sur un lieu, si le lieu a un dossier dms Adage, ajouter sous ID Adage:
- La “date de dépot dms Adage” si le statut du dossier dms adage n’est pas validé
- la “date de validation dms Adage” si le statut du dossier dms adage est validé
- Sur un lieu, si le lieu a un dossier dms Adage, ajouter sous “date de dépot DMS Adage”le statut du dossier DMS Adage, avec la liste des statuts disponibles:
- En construction
- En instruction
- Accepté
- Refusé
- Sans suite
- Sur un lieu s’il n’y a pas de dossier DMS Adage qui remonte ajouter “Pas de dossier DMS Adage”
- En profiter pour renommer “Référencement Adage” par “Peut créer une offre EAC”
NA
NA
- …

(PC-21611)[API] fix: improve UX adage status on venue

---

pro/src/hooks/useRedirectLoggedUser.ts
pro/src/pages/SignIn/__specs__/SignIn.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21920
- Ne plus afficher le tutoriel (page d'accueil) entre la page de connexion et la redirection vers le nouveau parcours

(PC-21920)[PRO] fix: doesn't display tutorial on new onboarding signin redirection

---

pro/src/screens/OfferIndividual/DialogStockDeleteConfirm/DialogStockEventDeleteConfirm.tsx
pro/src/screens/OfferIndividual/StocksEventEdition/__specs__/StockEventEdition.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21486
Quand on supprime un stock sur une offre qui a déjà des réservations on affiche une pop in. 
Attendu : 
changer le wording du bouton d’action principale. Remplacer “Supprimer” par “Confirmer la suppression”
http://localhost:3001/offre/individuelle/150/stocks, j'ai trouvé une offre qui marche,  donc je suis débloquée, mais j'ai jamais pu en créer une avec la réservation.
- [x ] La branche est bien nommée et les commits réfèrent le ticket Jira
- Branche : `PC-21486-wording-bouton-suppression`
- PR : `(PC-21486)[PRO] feat: Changement wording  bouton- Edition d'une offre`
- Commit(s) : `(PC-21486)[PRO] feat: Changement wording  bouton- Edition d'une offre`

(PC-21486)[PRO] feat: Changement wording  bouton- Edition d'une offre

---

pro/src/screens/SignupJourneyForm/Offerer/Offerer.tsx
pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22037
- Correctement rediriger l'utilisateur sur l'étape d'authentification après la validation du siret
- Offerer n'a pas le temps de se mettre à jour dans le contexte avant la redirection
- La redirection se passe lorsque la structure est mise à jour dans le state

(PC-22037)[PRO] fix: offerer redirection

---

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/__specs__/StocksProviderForm.spec.jsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22024
Modifier la modale de validation d'ajout de partenaire technique
Aller sur la page Lieu d’un lieu qui n’a pas de synchronisation (Club Dorothy par exemple)
Cliquer sur Synchroniser des offres
Choisir un provider
Voir la nouvelle modale lors de la synchronisation avec titelive ou avec tout provider nouvellement créé. 
- [x ] La branche est bien nommée et les commits réfèrent le ticket Jira
- Branche : `PC-22024-modale-validation`
- PR : `(PC-22024)[PRO] feat: Wording de modal de validation.`
- Commit(s) : `(PC-22024)[PRO] feat: Wording de modal de validation.`

(PC-22024)[PRO] feat: Wording de modal de validation.

---

pro/src/styles/components/pages/SignupConfirmation/_SignupConfirmation.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21784
- Centrer verticalement le message de la page de confirmation d'incription.

(PC-21784)[PRO] fix: center signup confirmation page vertially

---

api/src/pcapi/routes/backoffice_v3/templates/home/home.html

Replace `d-block` with `d-inline-block` to preserve inline display of btn icons
Restaure l'affichage inline block des boutons consulter/à venir
NA
NA

(BSR)[API] fix: landing cards buttons

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/providers/factories.py
api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
api/tests/core/offerers/test_api.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_models.py
api/tests/core/offers/test_repository.py
api/tests/core/providers/test_models.py
api/tests/local_providers/titelive_things_test.py
api/tests/routes/pro/get_providers_by_venue_test.py
api/tests/routes/public/individual_offers/v1/endpoints_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21720
Utilisation de la nouvelle méthode d'authentification des providers. 
Une clé doit être lié à un provider qui a des droits (un venueProvider) sur un lieu.

(PC-21720) feat: use new provider model for individual offer

---

pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/updateIndividualOffer.spec.ts
pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22128
- Erreur lors de l'envoi des données d'une offre invidivuel.
- Si withdrawalType est null ou undefined, withdrawalDelay = undefined, sinon null si withdrawalDelay est undefined

(PC-22128)[PRO] fix: serializer updateIndividualOffer

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230504T081500_b1ee65265887_add_venue_registration_table.py
api/src/pcapi/alembic/versions/20230504T085612_e6452b3c197d_add_venue_registration_venueid_fk.py
api/src/pcapi/alembic/versions/20230504T105244_4ed5060d7fd7_add_venue_registration_venueid_fk_2_2.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/models.py
api/tests/core/offerers/test_api.py
api/tests/routes/pro/post_save_new_onboarding_data_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21226
Enregistrer les nouvelles données (`target`, `webPresence`) sur le premier lieu créé pendant l'onboarding pro.
- Ajout d'une table `venue_registration`
- Modification de `create_from_onboarding_data()`
- Utilisation d'une colonne `Identity` au lieu d'une `Serial` pour la clé primaire de `venue_registration` cf https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial
- Ajout de la table `venue_registration` qui permet de stocker les urls fournies par un AC lors de l'onboarding, et le public visé (grand public, EAC, ou les 2)

(PC-21226)[API] store venue registration info

---

pro/src/screens/OfferType/OfferType.tsx
pro/src/screens/OfferType/__specs__/OfferType.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22146
FIx la création d'offre quand on passe par le bouton dans la liste des offres (compte non admin) 
Il manquait l'utilisation d'un id non humanisé sur un structure
BSR : fix l'affichage du spinner pour les offres non collectives

(PC-22146)[PRO] fix: use deshumanized id if query offerer is empty

---

api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
pro/src/apiClient/v1/models/CollectiveOfferVenueBodyModel.ts
pro/src/screens/OfferEducational/validationSchema.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22143
PR pour fix la duplication d'offre template. Le champs venueId devrait être nullable. En effet ce champs n'est renseigné que si le `Adresse où se déroulera l’évènement :` est `Dans votre lieu`

(PC-22143)[PRO] fix: venue id should be nullable in offer venue

---

pro/src/screens/Bookings/BookingsRecapTable/components/Table/Body/CollectiveTimeLine/CollectiveTimeLine.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22053
Changer le wording concernant le délai d'annulation pour une réservation au statut réservée quand le FF WIP_ENABLE_EAC_CANCEL_30_DAYS est activé

(PC-22053)[PRO] feat: change cancellation delay to 30days

---

api/src/pcapi/core/fraud/factories.py
api/src/pcapi/core/subscription/api.py
api/tests/routes/native/v1/subscription_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21896
Ne plus afficher de sous titre quand on a fini l'étape profil

PC-21896 remove profile subtitle when done

---

pro/src/pages/Offers/Offers/OffersTableBody/OffersTableBody.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22136
_Le match des checkbox avait lieu grâce aux ids, une partie était déshumanisés et pas les autres

(PC-22136)[PRO] fix: checkboxes in offers after deshumanization

---

api/src/pcapi/core/users/api.py
api/tests/core/users/test_api.py

Ajouter un comportement de flask admin dans le BO:
A la modification de la date de naissance, mettre à jour la date d'expiration du deposit si besoin. 
- cf: https://github.com/pass-culture/pass-culture-main/blob/ed210309a261de9e657f8c1bb92d7132153eabcc/api/src/pcapi/admin/custom_views/beneficiary_user_view.py#L318
- Ajouter cette logique dans `update_user_information`
- Branche : …

(BSR)[API] fix: update deposit expiration date when changing birth date

---

adage-front/src/apiClient/models/CollectiveOfferOfferVenue.ts
adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
adage-front/src/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/factories.py
api/src/pcapi/routes/adage_iframe/offers.py
api/src/pcapi/routes/adage_iframe/serialization/offers.py
api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/public/collective/serialization/offers.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/tests/routes/adage_iframe/get_collective_offer_template_test.py
api/tests/routes/adage_iframe/get_collective_offer_test.py
api/tests/routes/pro/post_collective_offers_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_public_test.py
api/tests/routes/public/collective/endpoints/post_collective_offer_public_test.py
pro/src/apiClient/adage/models/CollectiveOfferOfferVenue.ts
pro/src/apiClient/v1/models/CollectiveOfferVenueBodyModel.ts
pro/src/core/OfferEducational/constants.ts
pro/src/core/OfferEducational/types.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferVenue/__specs__/OfferVenue.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
pro/src/screens/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx
pro/src/screens/OfferEducational/validationSchema.ts
pro/src/utils/adageFactories.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22163
Stocker le champ `offerVenue["venueId"]` sous forme d'`int` et non plus `string` pour les offres collectives vitrines ou non

Pc 22163 eac fix collective offer venue id type

---

pro/src/screens/SignupJourneyForm/Activity/ActivityForm.module.scss
pro/src/screens/SignupJourneyForm/Activity/ActivityForm.tsx
pro/src/ui-kit/ListIconButton/ListIconButton.module.scss

…n and replace trash icon with listIconButton in activity page
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22088
- Utiliser le bouton listIconButton dans la page activité du nouveau parcours

(PC-22088)[PRO] refactor: activity page replace trashIcon with listIconButton

---

pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx
pro/src/pages/Offers/Offers/OffersStatusFiltersModal/OffersStatusFiltersModal.tsx
pro/src/pages/Offers/__specs__/Offers.spec.tsx
pro/src/screens/Bookings/BookingsRecapTable/components/Filters/FilterByBookingStatus/FilterByBookingStatus.tsx
pro/src/screens/Offers/__specs__/Offers.spec.tsx

Liste des offres - Modif de wording du filtre statut
Dans le tooltip qui s’affiche quand on clique sur le bouton statut : 
- remplacer le texte “Afficher les statuts” par “Afficher les offres”
- remplacer “Tous” par “Toutes”
- Faire cette modification à la fois côté individuel et collectif 
(Attention : la colonne s’appelle toujours bien Statut)
- Branche : `PC-21907-wording-filtre-statut`
- PR : `(PC-21907)[PRO] feat: wording de status`
- Commit(s) : `(PC-21907)[PRO] feat: wording de status`

(PC-21907)[PRO] feat: wording de status

---

api/src/pcapi/core/offers/exceptions.py
api/tests/core/offers/test_validation.py
api/tests/routes/public/individual_offers/v1/endpoints_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21456
Création d'offre - Modification du wording EAN
http://localhost:3001/offre/individuelle/295/creation/informations
Modifier le texte de l’erreur par : Une offre avec cet EAN existe déjà. Vous pouvez la retrouver dans l’onglet Offres. 
- Branche : `PC-21456-wording-EAN`
- PR : (PC-21456)[PRO] feat: Wording EAN, entrée 1234567890123.
- Commit(s) : (PC-21456)[PRO] feat: Wording EAN, entrée 1234567890123.

(PC-21456)[PRO] feat: Wording EAN, entrée 1234567890123.

---

api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/factories.py
api/tests/core/users/test_api.py
api/tests/routes/pro/post_user_pro_flags_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22100
Corriger une erreur d'insertion lors de l'enregistrement des flags, en bout de parcours d'inscription
- Corriger le commit
- Correction des tests et factory: la valeur du flag `BETTER_OFFER_CREATION` est une str au lieu de bool

(PC-22100)[API] fix: save user flags correctly

---

pro/src/styles/global/_page.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22047
- Corriger l'espacement en bas des pages de l'application PRO.
:warning: à tester sur firefox et chrome
Le margin bottom ne s'appliquait pas sur chrome, le padding à l'air de fonctionner sur chrome et firefox

(PC-22047)[PRO] fix: browser bottom space

---

api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22072
Afficher le label d'un lieu, s'il existe, sur la page de détails d'un lieu dans le backoffice.

(PC-22072)[BO] feat: show venue label

---

api/src/pcapi/admin/custom_views/many_offers_operations_view.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/permissions/models.py
api/src/pcapi/routes/backoffice_v3/__init__.py
api/src/pcapi/routes/backoffice_v3/multiple_offers/blueprint.py
api/src/pcapi/routes/backoffice_v3/multiple_offers/forms.py
api/src/pcapi/routes/backoffice_v3/templates/components/search/result.html
api/src/pcapi/routes/backoffice_v3/templates/components/search/result_form.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
api/src/pcapi/routes/backoffice_v3/templates/multiple_offers/search.html
api/src/pcapi/routes/backoffice_v3/templates/multiple_offers/search_result.html
api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_isbn.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
api/src/pcapi/static/backofficev3/scss/pc/pc.scss
api/src/pcapi/static/backofficev3/scss/pc/templates/multiple_offers/_search_results.scss
api/tests/core/offers/test_api.py
api/tests/routes/backoffice_v3/conftest.py
api/tests/routes/backoffice_v3/multiple_offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21526
Ajout d'une page permettant la recherche de produits/offres par ISBN afin de permettre les opérations sur ces offres : 
- ajouter des tags sur toutes les offres
- rendre le produit incompatible avec les CGU et désactiver les offres.
Il s'agit de la reprise d'une page de FA, dont on reprend du code et des tests.
Ajout dans la sandbox de produits avec des offres et des tags pour faciliter les tests dans l'interface, sur les ISBN : 9780000000001 à 9780000000004.

(PC-21526)[BO] feat: multiple offers operations from ISBN

---

pro/src/hooks/useAnalytics.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22199
Ajouter un early return si l'initialisation de firebase fail dans le hook useAnalytics. 
Tentative de correction pour certains utilisateurs qui voient le message suivant apparaitre en prod sur certaines pages 
Le message complet : 
> FirebaseError: Analytics: initializeAnalytics() cannot be called again with different options than those it was initially called with. It can be called again with the same options to return the existing instance, or getAnalytics() can be used to get a reference to the already-intialized instance.

(PC-22199)[PRO] fix: add early return if firebase init failed

---

api/src/pcapi/core/offerers/models.py

It should not be unique, at least 2 keys are needed to allow providers to change keys without downtime

(BSR)[API] fix: align apiKey index models.

---

api/tests/routes/pro/post_stocks_test.py

WIP_ENABLE_MULTI_PRICE_STOCKS was false by default and is now set to true (https://github.com/pass-culture/pass-culture-main/pull/6462)
I don't know why the first CI didn't catch it

(BSR)[API] fix: WIP_ENABLE_MULTI_PRICE_STOCKS is now true by default

---

api/src/pcapi/core/permissions/models.py

Redéfinir la contrainte d'unicité de la table `role_permission`, qui existe dans la base de données mais avait disparu du modèle dans le commit [a0688a75ae6a7b105da916c9824e2016e3b7ec58](https://github.com/pass-culture/pass-culture-main/commit/a0688a75ae6a7b105da916c9824e2016e3b7ec58)
J'ai conservé le nom de l'index existant en base afin de ne pas créer de migration de suppression et recréation.

(BSR)[API] fix: existing unique constraint on role_permission was missing in the model

---

api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/email/update.py
api/src/pcapi/core/users/models.py
api/src/pcapi/routes/backoffice_v3/accounts.py
api/tests/routes/backoffice_v3/accounts_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22067
Lors de la modification de l'email d'un compte jeune et grand public sur le backoffice :
1. ajouter la validation du changement en même temps dans l'historique des changements d'email (et pas seulement la première étape, changement en attente de validation) ;
2. ne plus envoyer d'email de confirmation (qui n'était pas utile et ne sera plus du tout pertinent avec 1.)
Ceci permettra d'avoir un ensemble plus cohérent. L'utilisateur du backoffice pouvait avoir l'impression que le changement d'email était bien validé et que tout était ok alors que l'historique des changements d'email disait le contraire : celle-ci n'est pas validée.
Ce qui pose quelques problèmes :
1. l'historique des modifications d'email risque de …

(PC-22067)[API] feat: bo: email update: mark as pending and validated

---

api/tests/alembic/check_db_schema.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22204
Corriger `check_db_schema.py` , qui n'utilisait pas la bonne définition du schéma de DB
Il faudra, avant de fusionner, corriger les incohérences et fusionner ces PR:

(PC-22204) fix check db models alignment

---

api/src/pcapi/core/offerers/api.py
api/tests/core/offerers/test_api.py

Ne pas appeler `trace_update` pour les informations de contact d'un lieu si celui-ci n'as pas de `VenueContact` associé. Sinon, la fonction utilise la cible par défaut, donc ici le lieu ce qui génère des erreurs du style : un lieu n'a pas de champ email.

(BSR)[API] fix: history: handle venue without existing contact

---

api/src/pcapi/routes/backoffice_v3/templates/multiple_offers/search_result.html
api/tests/routes/backoffice_v3/multiple_offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21526
Petite correction suite à la revue PO : le bouton pour rendre les offres incompatibles ne doit être affiché que si l'utilisateur a la permission sur l'action associée.

(PC-21526)[BO] fix: button displayed only if user has required permission

---

api/src/pcapi/routes/backoffice_v3/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice_v3/templates/collective_offer_template/list.html
api/src/pcapi/routes/backoffice_v3/templates/components/links.html
api/src/pcapi/routes/backoffice_v3/templates/offer/list.html

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22023
Sur les tableaux des offres individuelles, collectives et collectives vitrine, ajouter une nouvelle colonne avec une icône permettant d'ouvrir un nouvel onglet sur cette même page Offre avec le filtre fait sur le lieu de l’offre uniquement

(PC-22023)[BO] feat: an icon to open all offers for a venue from offers lists

---

api/src/pcapi/core/offers/exceptions.py
api/src/pcapi/core/offers/validation.py
api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/src/pcapi/routes/public/individual_offers/v1/endpoints.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_validation.py
api/tests/local_providers/titelive_things_test.py
api/tests/routes/pro/post_offer_test.py
api/tests/routes/public/individual_offers/v1/endpoints_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21946
This is the first (out of four) step to delete isbn.
Everytime we write an isbn we also write an ean.
Few changes : 
- Isbn is now validated like ean (13 digits)
- It will not be possible to create a Book with the same ean as a CD (this is a good thing)

(PC-21946)[API] feat: write isbn in ean

---

api/src/pcapi/routes/backoffice_v3/filters.py
api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22258
Mini bug dans le backoffice : les liens www.website.com étaient en lien relatif dans la fiche de détails d'un lieu, et donc en erreur 404 au clic, si l'AC n'a pas indiqué le protocole:// dans son adresse web.

(PC-22258)[BO] fix: add missing https:// in website link

---

api/src/pcapi/routes/backoffice_v3/forms/offerer.py
api/src/pcapi/routes/backoffice_v3/forms/venue.py
api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
api/src/pcapi/routes/backoffice_v3/templates/venue/list.html
api/src/pcapi/routes/backoffice_v3/utils.py
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21918
Ajout d'une page pour rechercher des lieux qui plus tard servira à ajouter des actions de traitement par lot
Créer une nouvelle page “Actions sur les lieux” dans le menu “Acteurs culturels”  
- Afficher un tableau des lieux  
- Avec de base aucune ligne sur le tableau  
- Avoir les colonnes suivantes :
- Venue id  
- Nom  + un lien qui mène vers le lieu du BO  
- Structure  + un lien qui mène vers la structure du BO  
- Label  
- Tags  
- Date de création du lieu  
- une visualisation de permanent/pas permanent, par exemple une colonne "Permanent" avec un tick pour si oui  
- Ajouter les filtres par : 
- Type de lieu (activité principale)  
- Par label  
- Par tag  
- Par région  
- Par département  
Cette page …

(PC-21918)[API] feat: add page action on venues 

---

api/src/pcapi/routes/pro/venue_providers.py
api/tests/routes/pro/post_venue_provider_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22283
We used to queue a synchronisation juste after the VenueProvider creation, for new providers (that are linked to an offerer) we don't want to queue a sync since they will use our APIs.
An error was triggered and the sync couldn't start (no problem, we don't want it to start) [Staging sentry](https://sentry.passculture.team/organizations/sentry/issues/413421/?project=5&referrer=slack)

(PC-22283)[PRO] fix: Do not synchronize new venue_providers after creation

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/commands.py
api/tests/core/bookings/test_api.py
api/tests/core/bookings/test_commands.py

Déplacer les offres automatiquement en réservations terminées après 30J si la sous catégorie est :
- Abonnement musée → `ABO_MUSEE`
- Carte musée → `CARTE_MUSEE`
- Abonnement bibliothèque → `ABO_BIBLIOTHEQUE`
- Abonnement médiathèque → `ABO_MEDIATHEQUE`
Et si le prix est `GRATUIT`
- Modification du script flask `archive_old_activation_code_bookings`
- Renommage de `archive_old_activation_code_bookings` en `archive_old_bookings` 
- Création d'une nouvelle cmd flask le temps de la transition
TODO: ajouter un ticket ops et un ticket backend pour plus tard supprimer l'ancienne cmd.
- PR Ajout initial du script `archive_old_activation_code_bookings` :  https://github.com/pass-culture/pass-culture-main/pull/5316
- PR …

(PC-21975)[API] feat: move to ended bookings when subcategories match

---

api/src/pcapi/core/users/api.py
api/tests/routes/backoffice_v3/accounts_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22269
Ajout de la rechercher par date de naissance et date de naissance validée

(PC-22269)[API] feat: add-search-by-birthdate-to-public-accounts

---

api/src/pcapi/routes/backoffice_v3/fraud.py
api/src/pcapi/routes/backoffice_v3/templates/fraud/blacklist_domain_name_summary.html
api/src/pcapi/routes/backoffice_v3/templates/fraud/domain_names.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
api/tests/routes/backoffice_v3/fraud_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22147
Un `.query` en trop et c'est le drame (une instruction supprimait toute la table au lieu de ne supprimer qu'une ligne de `blacklisted_domain_name`).
Au passage : renommer le titre de la page.

(PC-22147)[API] feat: bo: track blacklisted domain names

---

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22055
Fix le lien de Suivi dans le nouveau header adage pour ouvrir le lien dans adage et non dans l'iframe

(PC-22055)[PRO] fix: add target parent to track link in adage header

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/conftest.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22266
Prendre en compte les offres collectives vitrine dans les compteurs EAC de la page lieu du backoffice.

(PC-22266)[BO] fix: include collective offer templates in venue offers counters

---

api/src/pcapi/routes/backoffice_v3/offerers.py
api/src/pcapi/routes/backoffice_v3/templates/offerer/validation.html
api/tests/routes/backoffice_v3/offerers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22212
Correction du formulaire de mise en attente de structure par lots.
Cela permet de mettre l'initialisation des tags avec ceux communs aux structures sélectionnées, et restaurer leur éventuelle suppression.
Attention, le navigateur ne suit pas les redirections avec le code 400.

(PC-22212)[BO] fix: batch edition on offerers

---

pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22260
Avant
Après

(PC-22260)[PRO] fix: sticky bar being under components at z-index 0

---

api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/factories.py
api/src/pcapi/routes/native/v1/authentication.py
api/tests/core/users/test_api.py
api/tests/routes/native/v1/authentication_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22076
Cette PR a pour but de considérer un appareil comme appareil de confiance à la deuxième connexion sur cet appareil par un même utilisateur.
Cela permet d'avoir des users qui ont un appareil de confiance de manière automatique et rapide.

(PC-22076)[API] feat: Save device as trusted device on second login with same device

---

api/src/pcapi/scripts/install.py
api/src/pcapi/scripts/offer/fill_product_and_offer_ean.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21991
[x] Write isbn in isbn and ean when creating a product or an offer
[] Duplicate isbn in ean (We are here !)
[] Delete isbn keys and values from all products / offers
Script to copy every isbn in ean. This information is stored in a json field inside Offer or Product table. 
--- Old performance ---
ETA : 
For 100 000 with batches of 1000 : 
db.session.bulk_update_mappings -> 155s
db.session.add(product) V1 -> 86s
db.session.add(product) V2 -> 87s
For 100 000 with batches of 10000 : 
db.session.bulk_update_mappings -> 146s
db.session.add(product) V1 -> 78.3s
db.session.add(product) V2 -> 78.9s
There is around 3 733 340 products and more than 79 448 037 offers. 
The script should take ~0.8h for products and ~17h for …

(PC-21991)[API] script: to fill product.ean and offer.ean

---

api/src/pcapi/admin/custom_views/beneficiary_user_view.py
api/src/pcapi/core/external/attributes/api.py
api/src/pcapi/core/subscription/api.py
api/src/pcapi/core/subscription/ubble/api.py
api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/models.py
api/src/pcapi/core/users/repository.py
api/src/pcapi/routes/backoffice_v3/accounts.py
api/src/pcapi/routes/native/v1/serialization/account.py
api/src/pcapi/routes/public/booking_token/v2/serialization.py
api/tests/core/users/test_repository.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22219
La fonction permettant de trouver les utilisateurs auxquels envoyer un email pour leur anniversaire de 18 ans se basait sur l'attribut `dateOfBirth` alors que la property `birth_date` doit lui être privilégié pour gérer le désaccord éventuel entre la date de naissance déclarée et celle fournie par l'identity provider.
Changement des filtres sqlalchemy au profit d'un filtrage python ultérieur, permettant d'utiliser la property.
- _A …

(PC-22218) Use birth_date property when fetching newly eligible users

---

pro/src/screens/SignupJourneyForm/ConfirmedAttachment/ConfirmedAttachment.module.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22355
- Supprimer le margin top du bouton pour ne garder que le gap de 32px

(PC-22355)[PRO] fix: confirmed attachment button margin top

---

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/__specs__/CollectiveDataEdition.spec.tsx
pro/src/pages/Signup/SignupContainer/__specs__/SignupContainer.spec.tsx
pro/src/ui-kit/form/PhoneNumberInput/CodeCountrySelect/CountryCodeSelect.tsx
pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.module.scss
pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.tsx
pro/src/ui-kit/form/PhoneNumberInput/__specs__/PhoneNumberInput.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20384
- Regrouper champ indicatif téléphonique et téléphone dans un <fieldset>
- Mettre une <legend> (Téléphone (utilisé uniquement par l’équipe du pass Culture))
- Mettre 2 <label> cachés visuellement pour chacun des champs: Indicatif téléphonique et Numéro de téléphone
- Bien prendre en compte le premier caractère

(PC-20384)[PRO] refactor: phone number input

---

api/src/pcapi/core/search/backends/algolia.py
api/tests/core/search/test_serialize_algolia.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22307
Ajouter 3 infos concernant le lieu dans l'index des offres:
- l'adresse
- le code postal
- la ville
RAS
RAS
RAS

(PC-22307)[API] feat: add more venue data to Algolia offers index

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/constants.py
api/src/pcapi/core/external_bookings/boost/client.py
api/src/pcapi/core/external_bookings/cds/client.py
api/src/pcapi/core/external_bookings/cgr/client.py
api/src/pcapi/scheduled_tasks/commands.py
api/src/pcapi/utils/queue.py
api/tests/core/bookings/test_api.py
api/tests/core/external_bookings/boost/test_client.py
api/tests/core/external_bookings/cds/test_client.py
api/tests/core/external_bookings/cgr/test_client.py
api/tests/utils/queue_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21708
Annuler la réservation en cours en cas d'erreur avant l'enregistrement de la réservation pass Culture Afin d'éviter de bloquer des places sur la billetterie de ciné sans avoir la réservation sur le pass Culture et ne pas rembourser l’AC
- Créer une file Redis.
- Stocker les codes barres récupérés un appel de réservation dans la file Redis.
- Ajouter une commande qui vérifie si les code barres dans la file ont bien été sauvegarder en DB sans soucis, le cas contraire annuler la réservation auprès du cinéma.

(PC-21708)[API] feat: Redis external bookings

---

api/src/pcapi/templates/invoices/invoice.html
api/tests/core/finance/test_api.py
api/tests/files/invoice/rendered_invoice.html

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19449
Mettre le template de l'html de l'invoice au style

(PC-19449)[api] fix: invoice style pdf

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/commands.py
api/tests/core/bookings/test_api.py
api/tests/core/bookings/test_commands.py
pro/src/apiClient/v1/models/SiretInfo.ts

This reverts commit f986c6a4ce50b9d547f99ba46ae99e6f24565871.
Supprime l'archivation des offres gratuites de certaines sous catégories
Revert
Des nouvelles demandes métier sont apparues et nous ne voulons pas embarquer cela dans la MES de demain
NA

(PC-21975)[API] feat: move to ended bookings when subcategories match  (REVERT)

---

pro/src/screens/Bookings/BookingsRecapTable/components/CellsFormatter/BookingOfferCell.module.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22154
Ajout un overflow-wrap pour couper les mots trop long dans le nom des offres affichés dans la liste des résas collectives
**Avant :** 
**Après :**

(PC-22154)[PRO] fix: add overflow-wrap for collective booking name

---

api/src/pcapi/routes/backoffice_v3/collective_offer_templates.py
api/src/pcapi/routes/backoffice_v3/collective_offers.py
api/src/pcapi/routes/backoffice_v3/templates/collective_offer/list.html
api/src/pcapi/routes/backoffice_v3/templates/collective_offer_template/list.html
api/tests/routes/backoffice_v3/collective_offer_templates_test.py
api/tests/routes/backoffice_v3/collective_offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22019
Ajout de la validation et rejet en masse pour les offres collectives et les offres collectives vitrine
- Refacto du code existant pour permettre le traitement par lot
- Ajout d'un endpoint de validation et de rejet de traitement par lot pour les offres collectives
- Ajout d'un endpoint de validation et de rejet de traitement par lot pour les offres collectives vitrine
- Ajout d'un endpoint form modal pour la validation et rejet  de traitement par lot pour les offres
- Ajout d'un endpoint form modal pour la validation et rejet  de traitement par lot pour les offres collectives
- On vérifie avant que les offres n'ont pas déjà le status sinon on annule
- Si une offre rencontre un problème pendant la validation, on …

(PC-22019)[API] feat: add batch validate/reject on collective and collective offer template

---

api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
api/tests/routes/backoffice_v3/accounts_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22312
Ajout d'un warning quand un utilisateur a une adresse mail modifiée

(PC-22312)[API] feat: add icon when user has modified email

---

api/src/pcapi/routes/native/v1/serialization/banner.py
api/tests/routes/native/v1/banner_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22434
Changer le wording de la bannière de transition 17-18 pour les utilisateurs n'étant pas passés par DMS ou Ubble de "Confirme ton identité" à "Vérifie ton identité".
- PR : `(PC-XXX) Description …

(PC-22434)[API] fix: Change wording for banner on 17-18 transition

---

api/src/pcapi/routes/serialization/collective_stock_serialize.py
api/tests/routes/pro/post_collective_stock_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22192
Éviter de renvoyer laisser passer une erreur 500 dans les rares cas où un utilisateur chercher à créer, par erreur, un stock collectif avec un prix très élevé. On souhaite éviter de se retrouver avec une erreur remontée par la base de données, à cause d'une trop grande valeur (qui dépasse le maximum autorisé par `numeric(10,2)`).
Il s'agit avant tout d'une question d'UX : faire une vérification rapide et renvoyer un message d'erreur clair pour les rares cas où un stock a un prix trop élevé.

(PC-22192)[API] feat: collective: return 400 if stock price too high

---

api/src/pcapi/core/offerers/api.py
api/tests/core/offerers/test_api.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22265
PRO Onboarding: Envoyer le mail de bienvenue seulement dans le cas de la création de nouvelle structure (rattachement validé automatiquement).

(PC-22265)[API] feat: pro onboarding send welcome email only in the case of new offerer is created

---

api/src/pcapi/scripts/offer/fill_product_and_offer_ean.py

Like '978-2-811-61170-5'
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21991
jsonb -> text returns jsonb
jsonb ->> text returns text
I had problems with `::jsonb` cast while it should not be needed

(PC-21991)[API] fix: error if isbn contains invalid json

---

api/src/pcapi/core/educational/commands.py
api/src/pcapi/core/educational/utils.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22483
Modifier la commande `generate_fake_adage_token` : 
- Modifier l'url pour qu'elle corresponde à l'url de pro (l'iframe est désormais migrée dans ce dossier)
- Ajouter un flag `readonly` à la commande pour générer un token pour un utilisateur qui n'aurait des droits seulement en lecture
**Contexte sur les différents type d'utilisateurs adage  :** 
Sur adage on gère deux types d'utilisateurs désignés dans le code par les roles `readonly` ou `redactor`. Ces roles sont définis par la présence de la propriété `uai` dans le token d'authentification : 
- Si le token contient un uai l'utilisateur à le role de redactor (tout les droits : réservation, demande d'offre réservable, filtre en plus, etc ....)
- Sinon …

(PC-22483)[API] chore: modify generate_fake_adage_token to match new url

---

api/src/pcapi/routes/backoffice_v3/templates/home/home.html

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22430
Permettre à l'antifraude d'afficher en un clic les 1000 premières offres individuelles, collectives ou collectives vitrine en attente triées par ordre de la plus récente à la plus ancienne.

(PC-22430)[BO] Change offers order and limit on home links (antifraud)

---

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/DeleteVenueProviderButton/DeleteVenueProviderButton.tsx
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.module.scss
pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/__specs__/StocksProviderForm.spec.jsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22024
Manon Desbordes:  le bouton est devenu Supprimer la synchronisation. Remettre Continuer à la place.
Le lien est un bouton quaternary :
quaternary est à 12px et rouge
ternary est à 14px et noir
[15 h 24] Mais le design est à 12px et noir
2 texte est en noir de rouge
- Branche : PC-22024-modale-validation-lien
- PR : PC-22024 modale validation avec lien  et wording bouton
- Commit(s) : PC-22024 modale validation bouton

PC-22024 modale validation avec lien  et wording bouton

---

api/src/pcapi/routes/backoffice_v3/templates/components/forms/string_field.html
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21957
Permettre d'ajouter un SIRET à un lieu sans SIRET depuis le backoffice.
Seuls les utilisateurs du backoffice ayant la permission  “support pro avancé : déplacer un SIRET” pourront faire cette opération, ainsi que la modification de SIRET ; pour les autres, ce champ est désactivé dans la modale d'édition.
Les vérifications faites dans FA ont été reprises.

(PC-21957)[BO] feat: add SIRET in venue edition (for venue without SIRET)

---

pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx
pro/src/utils/collectiveApiFactories.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22482
Tentative de fix de la flakyness des tests unitaires `CollectiveOfferSummaryEdition.spec.tsx`. Il semblerait que le fait de ne pas mocker correctement le lieu retourné par `getVenue` cause des problèmes lors des tests

(PC-22482)[PRO] fix: fix CollectiveOfferSummaryEdition unit test flakyness

---

pro/src/components/NoData/NoData.tsx
pro/src/screens/Offers/__specs__/Offers.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22287
Sur la liste des offres quand aucune offre n’est créé, supprimer le point à la fin de la phrase “Vous n’avez pas encore créé d’offre”
Si tu te connectes en admin tu peux choisir différents lieux, je pense qu’il y en a au moins 1 qui a pas d’offres !
Ah non ça ne s’affiche pas ce message si on met un filtre
Dans ce fichier là : https://github.com/pass-culture/pass-culture-main/blob/bef6a54526871e7e5b42069faefa9a3e3890da33/pro/src/screens/Offers/Offers.tsx#L299
Tu peux remplacer {userHasNoOffers ? ( par {!userHasNoOffers ? (
[Offers.tsx](https://github.com/pass-culture/pass-culture-main/blob/bef6a54526871e7e5b42069faefa9a3e3890da33/pro/src/screens/Offers/Offers.tsx)
{userHasNoOffers ? ( …

(PC-22024)[PRO] feat: wording sur la liste des offres 

---

api/src/pcapi/routes/native/v1/authentication.py
api/tests/routes/native/v1/openapi_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22305
Swagger ments !
|Avant|Après|
|:--|:--|
|![image](https://github.com/pass-culture/pass-culture-main/assets/95220086/e725099b-2008-4f8e-83b3-ffb266fcc6ac)|![image](https://github.com/pass-culture/pass-culture-main/assets/95220086/48d599fa-13e9-465d-a2fa-97e92e5893b1)|

(PC-22305)[API] chore: refresh token can actually answer with 401

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/commands.py
api/src/pcapi/core/bookings/constants.py
api/src/pcapi/routes/native/v1/bookings.py
api/tests/core/bookings/test_api.py
api/tests/core/bookings/test_commands.py
api/tests/routes/native/v1/bookings_test.py

Force le passage du statut du booking à `USED`
Modification du script qui maj les anciennes résas
D'après le ticket https://passculture.atlassian.net/browse/PC-8359 , l'ajout de la colonne `displayAsUsed` était nécessaire pour afficher en résa en cours des offres consommés directement (deezer) alors que le statut est `USED`
Du coup l'archivage peut consommer et afficher en résa terminé via ce changement.
NA

(PC-21975)[API] fix: move old booking set status to used

---

api/src/pcapi/core/mails/transactional/__init__.py
api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
api/src/pcapi/core/mails/transactional/users/suspicious_login_email.py
api/src/pcapi/core/users/api.py
api/src/pcapi/routes/native/v1/account.py
api/src/pcapi/routes/native/v1/authentication.py
api/tests/core/mails/transactional/users/suspicious_login_email_test.py
api/tests/core/users/test_api.py
api/tests/routes/native/v1/account_test.py
api/tests/routes/native/v1/authentication_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21664
Notifier un utilisateur si un appareil qui n'est pas de confiance se connecte pour la première fois sur son compte.

(PC-21664)[API] feat: Send email when login is suspicious

---

pro/src/pages/AdageIframe/app/adapters/getEducationalInstitutionWithBudgetAdapter.ts
pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.module.scss
pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx
pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22110
SOUS FF : 
WIP_ENABLE_NEW_ADAGE_HEADER
Ajouter le budget restant dans le nouveau menu d'adage

(PC-22110)[PRO] feat: display budget in adage header menu

---

api/src/pcapi/core/educational/utils.py
api/src/pcapi/routes/adage_iframe/offers.py
api/tests/routes/adage_iframe/post_collective_request_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22445
Deux fix :
1. ne pas enregistrer le numéro de téléphone dans les logs;
2. `dict` est un chic type.

PC 22445 log create collective offer request

---

api/src/pcapi/local_providers/titelive.md

Actuellement, nous maintenant la documentation des fichiers titelive sur leur FTP via un markdown sur github.
Ceci oblige à réécrire le format fournis par titelive (initialement du `.doc`) et augmente le risque d'erreur.
La PR a pour but de rajouter un lien vers les fichiers originaux.
- Reformatage du markdown
NA
NA

(BSR)[API] fix: move titelive documentation to notion

---

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.module.scss
pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx
pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22556
Pour générer un lien adage en readonly : 
pc bash 
flask generate_fake_adage_token --readonly
Si l'utilisateur est connecté avec un rôle READONLY il ne verra pas le budget ainsi que le lien du header 'Pour mon établissement'

(PC-22556)[PRO] fix: hide element for readonly user

---

api/src/pcapi/connectors/dms/api.py
api/src/pcapi/utils/requests.py

That way, we will have logs of external GraphQL requests with their
duration.

(BSR)[API] feat: Make `gql` use our requests wrapper

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/constants.py
api/src/pcapi/routes/native/v1/bookings.py
api/tests/core/bookings/test_api.py
api/tests/core/bookings/test_commands.py
api/tests/routes/native/v1/bookings_test.py

Correction de la condition `displayAsEnded` pour les sous categories qui utilisaient l'enum au lieu de son id
Ajout d'un test
NA
NA

(PC-21975)[API] fix: displayAsEnded was incorrect

---

api/src/pcapi/core/search/backends/algolia.py
api/tests/core/search/test_serialize_algolia.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21824
Ajout d'un champ `_geoloc` aux offres collectives et au offres vitrines : ceci devrait permettre de rechercher les offres à l'intérieur d'un certain périmètre

(PC-21824)[API] feat: collective offers: add _geoloc field

---

api/src/pcapi/core/finance/api.py
api/tests/core/external/user_automations_test.py
api/tests/core/finance/test_api.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22492
Changer le calcul de la date d'expiration du crédit 18 ans pour qu'il soit à 23h59 UTC quelque soit le fuseau horaire.
- [ X La branche est bien nommée et les commits réfèrent le ticket Jira
- …

(PC-22492)[API] fix: Change deposit expiration date for 18yo to UTC

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230531T131439_69ef0222cdc8_add_venue_timezone.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/scripts/venue/populate_venue_timezone.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21778
Eviter de requêter la table `Offerer` plusieurs lorsque l'on filtre les offres avec des dates
La propriété hybride `timezone` du modèle `Venue` est surclassée en vraie colonne
Avec cette différence pour le test de la requête : 
<details>
```diff
diff --git a/api/tests/core/offers/test_repository.py b/api/tests/core/offers/test_repository.py
index 0d0af86874..052b4552ba 100644
--- a/api/tests/core/offers/test_repository.py
+++ b/api/tests/core/offers/test_repository.py
@@ -185,6 +185,7 @@ class GetCappedOffersForFiltersTest:
assert offer_in_cayenne.id in offers_id
assert offer_in_mayotte.id in offers_id
assert len(offers.offers) == 2
+        assert False
class WhenUserIsAdminTest: …
```

(PC-21778)[API] perf: move venue timezone from property to column

---

api/src/pcapi/core/educational/repository.py

`Venue.timezone` has been changed from a property to a column, see
2746c08182e09020a1119eb522296700589d44d8.

(BSR)[API] fix: Fix N+1 SQL queries in "/years/<year>/prebookings" route

---

api/src/pcapi/routes/native/v1/account.py
api/tests/routes/native/v1/openapi_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21816
Ajouter le response_model qui va bien au décorateur spectree de la route native/v1/profile/email_update/status
RAS
RAS
RAS

(PC-21816)[API] fix: add reponse_model to email_update/status route

---

api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22586
Correction d'une exception remontée par Sentry : 
`AttributeError: 'EditVirtualVenueForm' object has no attribute 'siret'`
https://sentry.passculture.team/organizations/sentry/issues/417045/

(PC-22586)[BO] fix: AttributeError: 'EditVirtualVenueForm' object has no attribute 'siret'

---

api/src/pcapi/admin/custom_views/many_offers_operations_view.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/backoffice_v3/forms/offer.py
api/src/pcapi/routes/backoffice_v3/multiple_offers/blueprint.py
api/src/pcapi/routes/backoffice_v3/multiple_offers/forms.py
api/src/pcapi/routes/backoffice_v3/offers.py
api/src/pcapi/routes/backoffice_v3/templates/multiple_offers/search_result.html
api/src/pcapi/routes/backoffice_v3/utils.py
api/src/pcapi/sandboxes/scripts/creators/data/create_data_thing_products.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py
api/tests/admin/custom_views/many_offers_operations_view_test.py
api/tests/core/offers/test_api.py
api/tests/routes/backoffice_v3/multiple_offers_test.py
api/tests/routes/backoffice_v3/offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22515
Utilisation des EAN à la place des ISBN pour :
Filtre pour la liste des offres individuelles
Actions groupées pour rejeté ou tagger des offres par isbn
Lorsqu'on supprimera la clé isbn de "jsonData" je repasserais sur les tests pour enlever les "isbn": "..."

(PC-22515)[API] feat: use ean backoffice

---

api/src/pcapi/core/search/backends/algolia.py
api/tests/core/search/test_serialize_algolia.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21945
Suppression de l'utilisation de extraData["isbn"] pour l'indexation algolia

(PC-21945)[API] feat: use ean for algolia indexing

---

pro/src/components/Notification/Notification.tsx
pro/src/components/Notification/__specs__/Notification.spec.jsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22537
- Ajouter le role aux notifications
- Default = success = status
- Success: status
- Error: alert
- Pending: progressbar

(PC-22537)[PRO] feat: use role for notifications

---

api/src/pcapi/routes/backoffice_v3/forms/venue.py
api/src/pcapi/routes/backoffice_v3/templates/venue/list.html
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22567
- Le tri par défaut est ID desc
- Ajouter un lien pour trier sur la date de création
- On utilisera l'ID pour determiner l'ordre, la date de création n'étant pas indexé
NA
NA

(PC-22567)[API] feat: add sort by id asc/desc to venue

---

pro/src/screens/Bookings/BookingsRecapTable/components/CellsFormatter/BookingStatusCell.tsx
pro/src/screens/Bookings/BookingsRecapTable/components/CellsFormatter/__specs__/BookingStatusCell.spec.jsx
pro/src/screens/Bookings/BookingsRecapTable/components/Filters/FilterByBookingStatus/FilterByBookingStatus.tsx
pro/src/screens/Bookings/BookingsRecapTable/components/Filters/__specs__/FilterByBookingStatus.spec.tsx
pro/src/screens/Bookings/BookingsRecapTable/utils/bookingStatusConverter.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21908
Wording des réservations, tags et statut.
Résultats (individuelles et collectives):
Dans le tooltip du filtre Statut : 
- Remplacer le wording “Afficher les statuts” par “Afficher les réservations”
- Mettre une Majuscule à chaque début de mot (Annulée, Confirmée…)
- Faire cette modif à la fois côté individuel et collectif
- côté individuel uniquement, mettre les éléments de la liste au féminin (annulée, confirmée…)
Dans la liste des réservations : 
- côté individuel uniquement mettre tous les tags des statuts au féminin (annulée, confirmée…)
- [x ] La branche est bien nommée et les commits réfèrent le ticket Jira
- Branche : PC-21908-wording-liste
- PR : (PC-21908) Wording des réservations, tags et statuts.
- …

(PC-21908)[PRO] feat: Wording des réservations, tags et statuts.

---

api/src/pcapi/routes/backoffice_v3/auth.py
api/tests/routes/backoffice_v3/auth_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22513
Permettre à tous les utilisateurs du backoffice d'accéder en ADMIN à PC Pro, quel que soit l'ordre de création du compte, connexion à PC pro ou backoffice.

(PC-22513)[BO] fix: ADMIN role for backoffice users (access to PC Pro)

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/users/models.py
api/src/pcapi/scripts/fix_pro_roles.py
api/tests/routes/backoffice_v3/offerers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22481
- Corriger les erreurs de transition entre PRO et NON_ATTACHED_PRO
- Script de rattrapage pour corriger les rôles pro ; testé en dry-run sur staging, il y a pas mal d'erreurs accumulées avec le temps

(PC-22481)[API] fix: PRO vs NON_ATTACHED_PRO roles

---

api/src/pcapi/core/providers/api.py
api/tests/core/providers/test_api.py

We sometimes get a price of zero for books that should not be free
(according to our product table). This happens when the library sets a
wrong price in their own software.
Before, we used to ignore the changes (both the new price and the new
quantity). Now we ignore the new price (and keep the previous price)
but we do update the quantity.

(BSR)[API] fix: Do not ignore quantity update on stock whose price is set to zero

---

pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20748
- Afficher la liste des points de valorisation disponibles avec comme info la raison sociale (name) au lieu du nom d’affichage (public name).

(PC-20748)[PRO] feat: use name instead of public name for princing point

---

api/src/pcapi/routes/native/v1/serialization/offers.py
api/tests/routes/native/v1/offers_test.py
api/tests/routes/native/v1/openapi_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22633
There is a warning about changing this route, is there a problem to add "ean" to offerExtraData fields ?
If it is the case i can only keep this part to copy ean in isbn field
```
if result.extraData.ean:
result.extraData.isbn = result.extraData.ean
```

(PC-22633)[API] feat: use ean instead of isbn

---

api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
api/tests/core/external_bookings/cds/test_client.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21670
- Ignorer les rangés quand toutes les places à 0 dans le calcul de la lettre du siège.
- Le `paramètre seatmapskipmissingseats` est limité seulement pour le cas du numéro du siège.
Le schéma de la salle en question dans le test ajouté:

(PC-21670)[API] fix: CDS ignore previous empty rows when compute seat number

---

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22686
Supprimer les tags des mails templates #825, #831, #823, #821, #824, #828 dans le backend afin de synchroniser les remontées des statistiques sur leur tag attribué directement dans Sendinblue.

(PC-22686)[API] feat: Do not tag transactional emails related to Ubble - tagged in SiB by marketing

---

api/src/pcapi/routes/backoffice_v3/individual_bookings.py
api/tests/routes/backoffice_v3/individual_bookings_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22508
Clarifier dans les tests que les règles métier sont bien validées lors de l'annulation ou la désannulation d'une réservation. Un message d'erreur est aussi clarifié (« valorisé ou remboursé »).

(PC-22508)[BO] test: better tests for cancel/uncancel booking rules

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230607T152412_ad2884071862_add_offer_idatprovider_index.py
api/src/pcapi/core/offers/models.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22640
Add index on offer.IdAtProvider. 
I don't have any thoughts on using idx_tableName_column or tableName_column.
We have a venueId, idAtProvider index that is currently not used for all synchros. 
We should also adapt all LocalProvider descendent classes to override `get_existing_pc_obj` to filter by venue if it exists. 
This index will still be usefull for titelive products synchronisation (books and maybe cds later).
The query is made here : https://github.com/pass-culture/pass-culture-main/blob/8e2b542b56e46bef00a27c1be6e72e7028508cca/api/src/pcapi/repository/providable_queries.py#L52
"event_idAtProviders_key" UNIQUE CONSTRAINT, btree ("idAtProviders") on table Product
and "stock_idAtProviders_key" UNIQUE …

(PC-22640)[API] feat: Add index on offer.IdAtProvider

---

api/src/pcapi/core/educational/repository.py
api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/tests/routes/pro/get_collective_offer_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/CollectiveOfferInstitutionModel.ts
pro/src/apiClient/v1/models/GetCollectiveOfferRequestResponseModel.ts

Add information regarding the collective offer request's institution.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22689
Renvoyer des informations plus détaillées au sujet de l'établissement concerné par le formulaire de contact au sujet d'une offre vitrine (collective).
Suppression de `load_only` pour la relation `educationalInstitution` puisqu'on a désormais de presque toutes les colonnes.

(PC-22689)[API] feat: eac (pro): add more detailed information

---

api/src/pcapi/routes/backoffice_v3/templates/venue/list.html
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22567
Ajout de la colonne `Nom d'usage` (aka `venue.publicName`) dans la liste des actions sur les lieux
NA
NA

(PC-22567)[API] fix: add column public name to venue

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/admin/custom_views/support_view/view.py
api/src/pcapi/alembic/versions/20230602T090227_54974ef1d55a_add_eligibility_type_to_fraud_reviews.py
api/src/pcapi/core/fraud/api.py
api/src/pcapi/core/fraud/models.py
api/src/pcapi/routes/backoffice_v3/accounts.py
api/src/pcapi/routes/backoffice_v3/filters.py
api/src/pcapi/routes/backoffice_v3/templates/accounts/get/details/personal_information_registration.html
api/src/pcapi/routes/backoffice_v3/templates/components/forms/field_list_field.html
api/src/pcapi/routes/backoffice_v3/templates/components/public_accounts/registration_steps.html
api/tests/routes/backoffice_v3/accounts_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22148
Ajouter les revues manuelles dans le tableau du parcours d'inscription jeunes.
- Ajout d'`eligibilityType` au modèle `BeneficiaryFraudReview`
- Création de la revue manuelle avec l'éligibilité associée + adaptation du code pour récupérer cette info (cf. `reviewed_eligibility` et `user_eligibility`)
- Tri par date et ajout aux tableaux du parcours d'inscription (par étape et global)
- **Testing :** un test a été ajouté pour tester que les revues manuelles sont bien ajoutées aux étapes du parcours d'inscription
- Je n'arrive pas encore à tester tous les cas (si un jeune est marqué comme pas éligible et que la revue manuelle est OK, checker que le jeune est bien noté comme éligible ?)
- Ajout d'`eligibilityType` au …

(PC-22148)[BO] Display fraud reviews in subscription steps

---

api/src/pcapi/alembic/versions/20230607T152412_ad2884071862_add_offer_idatprovider_index.py

Deployment failed on staging because it took too long: the index was
created (although in the "invalid" state) but the migration failed
(and was thus not recorded in `alembic_version`). When we tried to
deploy again, the migration was executed again, but failed because the
index already existed.

(BSR)[API] fix: Add "if not exists" on "offer_idAtProvider" index creation

---

api/src/pcapi/routes/backoffice_v3/forms/offerer.py
api/tests/routes/backoffice_v3/offerers_test.py

HOTFIX : Contournement temporaire pour éviter une erreur 502 Bad Gateway
dans l'attente de la correction du ticket https://passculture.atlassian.net/browse/PC-22720
25 résultats au lieu de 100 par défaut sur les rattachements à valider.

(BSR)[BO] fix: temporary hotfix: avoid 502 Bad Gateway on offerer attachments page

---

api/src/pcapi/routes/backoffice_v3/venues.py

Éviter de casser la page de détails d'un lieu du backoffice lorsque l'API DMS est en maintenance.
Erreur Sentry : https://sentry.passculture.team/organizations/sentry/issues/418168/

(BSR)[BO] fix: avoir crash in venue page when DMS in unavailable

---

api/src/pcapi/routes/backoffice_v3/venues.py

Éviter de casser la page de détails d'un lieu du backoffice lorsque l'API DMS est en maintenance.
Erreur Sentry : https://sentry.passculture.team/organizations/sentry/issues/418158/

(BSR)[BO] fix: avoid crash in venue page when DMS in unavailable

---

api/src/pcapi/routes/backoffice_v3/forms/venue.py
api/src/pcapi/static/backofficev3/js/addons/pc-postal-address-autocomplete.js
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22698
Dans l'édition manuelle d'une adresse de lieu (sans _autocomplete_), permettre de modifier également les coordonnées GPS du lieu : latitude et longitude.
Dans les tests, on ne peut pas tester la présence du champ, car l'état caché ou visible est du pur JS à l'exécution.

(PC-22698)[BO] fix: edit latitude and longitude in venue address manual edition

---

pro/src/components/Banner/BannerInvisibleSiren.tsx
pro/src/screens/SignupJourneyForm/Offerer/Offerer.tsx
pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx
pro/src/screens/SignupJourneyForm/Offerer/__specs__/OffererForm.spec.tsx
pro/src/screens/SignupJourneyForm/Offerer/validationSchema.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22642
- Ajout message spécifique aux AE qui n'ont pas souhaité rendre leur SIRET visible au moment de l'inscription

(PC-22642)[PRO] feat: add bannerInvisibleSiren to offerer siret validation 

---

api/src/pcapi/core/mails/transactional/pro/reset_password_to_pro.py
api/src/pcapi/core/mails/transactional/users/suspicious_login_email.py
api/src/pcapi/routes/native/v1/authentication.py
api/src/pcapi/utils/date.py
api/tests/core/mails/transactional/users/suspicious_login_email_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21665
Utiliser le bon fuseau horaire dans l'email envoyé à l'utilisateur pour le notifier d'une connexion suspicieuse.
Correction du typage de la fonction `utc_datetime_to_department_timezone` :
- La sous-fonction qui utilise la variable `departement_code` permet de gérer le cas où elle vaut `None`.

(PC-21665)[API] feat: Convert suspicious login email time to users timezone

---

api/src/pcapi/core/subscription/dms/commands.py

Ajouter des commandes pour activer un utilisateur et pour importer son dossier DMS
Le but est de simplifier la gestion manuelle de cas limites et a terme de rendre le support plus autonome pour ces cas
- Branche : …

(BSR)[API] feat: add commands to handle single applications for retry purposes

---

pro/src/pages/AdageIframe/app/ui-kit/MultiSelectAutoComplete/MultiSelectAutocomplete.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22735
Faire commencer la div des options du select au même endroit que le select
Avant : 
Après :

(PC-22735)[PRO] fix: select filter exceeds the iframe

---

api/src/pcapi/connectors/dms/api.py

Fetching the schema is only useful to:
- validate our request on the client side [1]: We don't catch
client-side validation errors, just like we don't catch server-side
ones. Thus, validating client side is not useful to us.
- handle custom scalars and enums [2]: DMS GraphQL API does not use
them.
We can thus avoid fetching the schema, which saves an HTTP
request (that takes between 300 and 600 ms) for each call to the
GraphQL API (since we do not reuse the GraphQL client, and the schema
was not cached).
[1] https://gql.readthedocs.io/en/stable/usage/validation.html
[2] https://gql.readthedocs.io/en/stable/usage/custom_scalars_and_enums.html

(BSR)[API] perf: Avoid extra HTTP request that fetches GraphQL schema

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/src/pcapi/routes/backoffice_v3/titelive/blueprint.py
api/tests/core/offers/test_api.py
api/tests/local_providers/titelive_things_test.py
api/tests/routes/backoffice_v3/titelive_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22752
Suite de la PR https://passculture.atlassian.net/browse/PC-22270 ou la table `product_whitelist` a été rajouté:
- Utilisation des `ean` de la table `product_whitelist` lors de la syncro `titelive_thing`.
- Utilisation des `ean` de la table `product_whitelist` lors de l'ajout dans la whitelist, pour mettre à jour `isGcuCompatible` et `isSynchronizationCompatible` des entités de la table `product`.
- Utilisation des `ean` de la table `product_whitelist` lors de la suppression de la whitelist, pour mettre à jour `isGcuCompatible` et `isSynchronizationCompatible` des entités de la table `product` si des offres avec bookings existent, sinon pour supprimer le produit.
NA
NA
NA
- Branche : …

(PC-22752)[API] feat: enable product_whitelist usage

---

api/src/pcapi/scripts/fill_fraud_review_eligibility_type.py
api/tests/scripts/fill_fraud_review_eligibility_type_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22650
Créer un script pour remplir la nouvelle colonne `eligibilityType`  du modèle `BeneficiaryFraudReview` (spécifique aux anciennes revues manuelles ayant le champ à `None`).
- Premier cas : les revues ont engendré dans la minute la création d'un crédit (`Deposit`) pour le jeune (récupération du type de crédit pour déduire l'éligibilité de la revue)
- Deuxième cas : à la date de la revue, le jeune avait moins de 18 ans -> éligibilité 15-17; sinon éligibilité 18 renseignée
- Création de tests

(PC-22650)[BO] Add script to fill eligibility of fraud reviews

---

api/src/pcapi/use_cases/save_venue_bank_informations.py

When we receive a webhook notification from DMS about a change on an
application, we validate the application and populate the annotation
if there is an error. But when the application does not have the
annotation field (which is likely for old annotations), the error is
raised and pollutes Sentry.
There is no point in raising the error when the application is draft:
there is nothing we can do. We'll just wait for the application to be
accepted or rejected.

(BSR)[API] feat: Do no raise error if DMS application is draft

---

api/src/pcapi/routes/backoffice_v3/templates/venue/get.html
api/src/pcapi/routes/backoffice_v3/templates/venue/list.html

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22721
- Ne pas afficher le nom d'usage dans la page d'un lieu s'il est définit à None ou si c'est un empty string.
- Dans la page Actions sur les lieux, ne rien afficher dans le tableau dans ce même cas

(PC-22721)[BO] Fix None or empty venue publicName

---

api/src/pcapi/connectors/cgr/cgr.py
api/src/pcapi/connectors/serialization/cgr_serializers.py
api/src/pcapi/core/external_bookings/cgr/client.py
api/src/pcapi/routes/public/booking_token/v2/serialization.py
api/tests/connectors/cgr/soap_definitions.py
api/tests/core/external_bookings/cgr/test_client.py
api/tests/routes/public/blueprint_v2_openapi_test.py
api/tests/routes/public/booking_token/v2/get_booking_by_token_v2_test.py
pro/src/apiClient/v2/models/GetBookingResponse.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22779
Fournir la date limite d'annulation lors de l'appel au webservice CGR.
Modification du payload XML 
Suppression de la modification de l'API CM qui ajoutait cet attribut.

(PC-22779)[API] feat: send cancellationLimitDate when booking CGR ticket

---

api/src/pcapi/routes/backoffice_v3/accounts.py
api/src/pcapi/routes/backoffice_v3/admin/bo_users_blueprint.py
api/src/pcapi/routes/backoffice_v3/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice_v3/pro.py
api/src/pcapi/routes/backoffice_v3/pro_users.py
api/src/pcapi/routes/backoffice_v3/templates/admin/bo_users.html
api/src/pcapi/routes/backoffice_v3/templates/components/search/result.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/accounts.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/admin.html
api/src/pcapi/routes/backoffice_v3/templates/layouts/pro.html
api/src/pcapi/routes/backoffice_v3/venues.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21855
Permettre de rechercher un compte jeune, un pro ou un utilisateur du backoffice à partir d'un champ directement dans la page de détails (à la même place que dans la page de résultats), afin d'éviter de retourner dans le menu à chaque rechercher.
Pas de test ajouté car les champs ajoutés dans les pages appellent les endpoints déjà largement testés.

(PC21855)[BO] feat: Make search field available even in details pages

---

api/src/pcapi/routes/backoffice_v3/accounts.py
api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
api/tests/routes/backoffice_v3/accounts_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22674
- Changer l'icône indiquant que l'email a déjà été changé, sur la page de détails d'un jeune
- N'afficher qu'une fois le changement d'email depuis le BO dans l'historique : pas besoin de stocker ce changement dans la table `action_history` puisqu'il est déjà dans la table `user_email_history`.

(PC-22674)[BO] fix: log email change only once in history + change icon

---

api/src/pcapi/core/subscription/models.py
api/src/pcapi/core/users/factories.py
api/src/pcapi/core/users/generator.py
api/src/pcapi/routes/backoffice_v3/user_generation/blueprint.py
api/src/pcapi/routes/backoffice_v3/user_generation/forms.py
api/tests/core/users/test_generator.py
api/tests/routes/backoffice_v3/user_generation_test.py
api/tests/routes/native/v1/banner_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22129
Permettre de choisir l'étape de souscription à laquelle un utilisateur est généré dans le backoffice.
Ajout de factories pour les utilisateurs
Ajout d'un champ dans le formulaire du générateur
- Commit(s) : …

(PC-22129)[API] feat: Add choice of subscription step when generating user

---

api/src/pcapi/connectors/titelive.py
api/src/pcapi/utils/cache.py
api/tests/connectors/titelive/titelive_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22753
Utilise redis pour stocker le JWT titelive d'une durée de validité de 5 minutes
NA
Un refresh token est également disponible dans un cookie de la réponse du login. Sa validité étant de 5 minutes, il ne sera pas implémenté au profit d'un nouveau login donc jwt.
NA

(PC-22753)[API] fix: improve titelive http api session using redis

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230616T081353_e84fda00f67c_make_venueprovider_idatprovider_nullable.py
api/src/pcapi/core/providers/api.py
api/src/pcapi/core/providers/models.py
api/tests/routes/pro/post_venue_provider_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22562
two commits to allow venues without siret to sync to new providers. 
The first commit might need to be hotfixed, the second commit is the long term fix. 
At first we will allow to create venueProvider with a dummy idAtProvider, once the column is nullable we will change this idAtProvider to a null value

(PC-22562)[API] feat: provider without siret

---

api/src/pcapi/connectors/serialization/cgr_serializers.py
api/src/pcapi/core/external_bookings/cgr/client.py
api/tests/connectors/cgr/soap_definitions.py
api/tests/core/external_bookings/cgr/test_client.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22779
Corriger le type XML du payload de réservation CGR
- Pour éviter un cast inopiné par `zeep`, les tests utilisent un `strftime()` avec un format explicite, au lieu de `isoformat()`, qui négligeait le séparareteur `T`

(PC-22779)[API] fix: use correct XML type and format

---

api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
api/tests/routes/backoffice_v3/accounts_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22805
Afficher date et heure d'expiration du crédit sur la page de détails d'un jeune bénéficiaire (s'il a effectivement un crédit).

(PC-22805)[BO] feat: show deposit expiration date in beneficiary details page

---

api/src/pcapi/routes/backoffice_v3/forms/search.py
api/src/pcapi/routes/backoffice_v3/offerers/forms.py
api/tests/routes/backoffice_v3/offerers_test.py
api/tests/routes/backoffice_v3/pro_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20651
Permettre les espaces à l'intérieur des SIREN/SIRET lors d'une recherche de structure ou lieu dans le backoffice.

(PC-20651)[BO] feat: search for offerer and venues by SIREN/SIRET with spaces

---

pro/src/components/Header/Header.jsx
pro/src/components/LegalInfos/LegalInfos.tsx
pro/src/pages/Signup/Signup.tsx
pro/src/ui-kit/Banners/BannerLayout/BannerLayout.tsx
pro/src/ui-kit/Banners/InternalBanner/InternalBanner.tsx
pro/src/ui-kit/SvgIcon/SvgIcon.tsx
pro/src/ui-kit/form/PasswordInput/PasswordInput.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22841
Rendre lisible la page de création de compte quand le css est désactivé

(PC-22841)[PRO] refactor: add default size for signup page icons

---

api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_venue_provider_and_external_bookings.py
api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
api/tests/local_providers/cinema_providers/boost/fixtures.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22657
- Synchro Boost: remplir l'attribut Stock.features avec les spécificités de la séances. Avec la prise en compte de VO/VF/3D.
- Ajout des spécificités de séances en sandbox pour les offres Boost.

(PC-22657)[API] feat: Boost synchro store showtimes version (VF/VO) and format (3D) in stock.features

---

api/src/pcapi/routes/backoffice_v3/individual_bookings.py
api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html
api/tests/routes/backoffice_v3/individual_bookings_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19698
En tant que support pro
J'aimerais valider/annuler en masse des réservations d’offres
Afin de gagner du temps 
Ajout de boutons “Valider” et “Annuler” en haut de l'écran. Par défaut ces boutons sont grisés et inactifs. Dès sélection d’au moins 2 réservations, ils deviennent actifs. 
Au clic sur “Valider”, l’ensemble des réservations sélectionnées passent au statut “VALIDATED”
Au clic sur “Annuler”, l’ensemble des réservations sélectionnées passent au statut “CANCELED”
Reporter les contrôles bloquants (ceux de Flask admin) lorsqu’on sélectionne une ou plusieurs réservations dont le statut n’est pas éligible au changement souhaité :
On ne peut pas valider une réservation individuelle si le stock est épuisé (ou …

(PC-19698) multi select on bookings

---

api/src/pcapi/core/users/email/__init__.py
api/src/pcapi/core/users/email/send.py
api/src/pcapi/core/users/email/update.py
api/src/pcapi/core/users/models.py
api/src/pcapi/routes/native/v1/account.py
api/src/pcapi/routes/native/v1/serialization/account.py
api/tests/routes/native/v1/account_test.py
api/tests/routes/native/v1/openapi_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22316
Confirming email update
Created a new route '/native/v1/profile/email_update/confirm'
la modification d'email est actuellement désactivé est les utilisateurs ont une limite de 24h pour finir la procédure. Il n'y a donc pas d'utilisateurs qui ont commencé la procédure et qui se retrouverons avec des problème avec la nouvelle procédure
ancienne procédure: un seul type de token avec uns seul clé redis associé qui stock un compteur du nombre de fois où la clé a été vérifié
nouvelle procédure:
Deux tokens différents sont générés à deux étapes différentes du changement d'email. les tokens ont chacun un clé redis associé qui est différentes. sur Redis on stock cette fois ci le token_jwt et pas juste un nombre. un fois …

Pc 22316 update email confirmation

---

api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py

Trier `Stock.features` pour la synchro CDS afin d'avoir toujours le même ordres d'attributs entre toutes les synchro.

(BSR)[API] feat: CDS sort features list to have always same order of features for all providers

---

api/src/pcapi/core/subscription/models.py
api/src/pcapi/core/users/generator.py
api/src/pcapi/routes/backoffice_v3/user_generation/blueprint.py
api/src/pcapi/routes/backoffice_v3/user_generation/forms.py
api/tests/core/users/test_generator.py
api/tests/routes/backoffice_v3/user_generation_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22800
Dans le formulaire de génération d'utilisateurs dans le backoffice, permettre de choisir la méthode d'identification par laquelle est passé l'utilisateur généré (le cas échéant).
- Ajout d'un champ dans le formulaire
- Remplacement des enum existantes par des nouvelles enum propre au module générateur d'utilisateur
- Nettoyage du code

[PC-22800] Choose Id provider at user generation in backoffice

---

api/src/pcapi/routes/backoffice_v3/serialization/venues.py
api/src/pcapi/routes/backoffice_v3/templates/venue/get/stats.html
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20853
Ajout des informations bancaires d'un lieu sur sa page détaillée :
- Point de remboursement (lien si ce n'est pas le lieu actuellement affiché)
- Siret de valorisation (lien si ce n'est pas celui du lieu actuel)
- BIC/IBAN du lieu affiché ou du lieu de remboursement

(PC-20853)[BO] Add new venue card with bank informations

---

api/src/pcapi/core/offerers/api.py
api/tests/routes/backoffice_v3/conftest.py
api/tests/routes/backoffice_v3/offerers_test.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22598
En tant que CT, j'aimerais voir si l’acteur a déjà créé des offres, afin de l’accompagner au mieux
Sur les pages structures et lieux, modifier le compteur des offres “inactives”
Dans le compteur des offres inactives ajouter : 
- Offre en brouillon : créé par l'acteur mais pas encore terminé
- Offre en attente : offre qui demande une validation côté conformité, en attente de validation/rejet
NA
NA

(PC-22598)[API] fix: add draft and pending offer to inactive count

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22491
Décocher la case `Les acteurs culturels de mon département` quand un filtre de lieu est présent dans l'iframe adage. 
Pour ajouter le filtre ajouter un paramètre `venue=<venueId>` dans l'url

(PC-22491)[PRO] feat: uncheck only in my department when venue filter

---

api/src/pcapi/core/users/api.py
api/src/pcapi/routes/native/v1/account.py
api/tests/core/users/test_api.py
api/tests/routes/native/v1/account_test.py
api/tests/routes/native/v1/openapi_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22547
Ajouter une date d'expiration au token utilisé pour la suspension/sécurisation de compte, pour ne pas pouvoir utiliser le token dans le lien reçu par mail après une semaine.

(PC-22547)[API] feat: Add expiration date to account suspension token

---

api/src/pcapi/core/users/email/update.py
api/tests/routes/native/v1/account_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22316
Corriger une syntax error: https://sentry.passculture.team/organizations/sentry/issues/418817/?environment=testing&query=is%3Aunresolved
- …

(PC-22316)[API] fix: use redis ex instead of exat to set token

---

api/src/pcapi/routes/internal/__init__.py
api/src/pcapi/routes/internal/e2e_ubble.py
api/tests/routes/internal/e2e_ubble_test.py
api/tests/routes/native/v1/openapi_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19326
Dans le cadre des tests end-to-end, il est pratique (voire nécessaire) de mocker l'identification via Ubble.
Ici, au lieu de simuler le vrai comportement d'Ubble qui prend un certain pour traiter les requêtes en asynchrone, une seule requête à la route suffit à avoir une réponse qui correspond au type d'erreur voulu.
- Ajout d'une route
- Appel des fonctions qui servent au workflow de l'identification via Ubble avec les infos de l'utilisateur
- Utilisation de la factory UbbleContentFactory pour obtenir un modèle de réponse d'Ubble.

(PC-19326)[API] feat: Add route to mock Ubble for e2e tests

---

pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/DuplicateOfferCell.tsx
pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/__specs__/DuplicateOfferCell.spec.tsx
pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22826
Changer le wording des boutons de duplication d'offre vitrine : 
Dupliquer -> Créer une offre réservable

(PC-22826)[PRO] fix: change duplicate template offer button wording

---

api/src/pcapi/core/educational/api/institution.py
api/src/pcapi/routes/adage_iframe/authentication.py
api/src/pcapi/routes/adage_iframe/educational_institution.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22943
Gérer les établissements non existant ou sans budget : 
- Si l'établissement n'existe pas dans notre BDD, il accède à l'iframe en mode READ_ONLY
- Si l'établissement n'a pas de budget, il peut accèder à l'iframe en mode REDACTOR mais voit un budget prévisionnel de 0

(PC-22943)[PRO] fix: handle institutions with no budget or not existing

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/validation.py
api/tests/core/offers/test_api.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22780
Fix du bug de modification d'offre ayant déjà un ean

(PC-22780) do not check ean if offer already has ean

---

pro/src/pages/AdageIframe/app/App.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22962
Fix la façon de générer le token Algolia pour les utilisateurs. Ce token ne doit pas contenir de caractères spéciaux. 
Note : à priori useId wrap un id alphanumérique entre les caractères `:` c'est donc le seul caractère qui devrait être remplacé en pratique

(PC-22962)[PRO] fix: remove special char from algolia user token

---

api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/routes/adage_iframe/offers.py
api/tests/conftest.py
api/tests/routes/adage_iframe/offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22940
Fix : créer un rédacteur lorsque celui-ci est manquant. Ceci ne doit se faire qu'au cas par cas. Ici, lors de la création d'une demande de contact au sujet d'une offre collective.
1. fusionner les deux classes de tests (Return200/Return400), c'est ce qui se fait ailleurs;
2. renommer le fichier de test pour quelque chose de plus standard et commun au reste des tests de l'api.

(PC-22940)[API] fix: eac: create redactor if missing

---

pro/src/pages/ResetPassword/ChangePasswordForm/ChangePasswordForm.tsx
pro/src/pages/ResetPassword/ChangePasswordForm/validationSchema.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22926
- Utiliser le même message de validation

(PC-22926)[PRO] fix: use password input preview message

---

api/src/pcapi/admin/custom_views/venue_view.py
api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/admin/custom_views/venue_view_test.py
api/tests/routes/backoffice_v3/venues_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21219
Corriger les problèmes d'indexation des lieu lors d'une édition par lot
- désindexation des lieux passés en non-permanent lors d'une édition par lot sur FlaskAdmin
- désindexation des lieux passés en non-permanent lors d'une édition par lot sur le backoffice v3
- indexation des lieux passés en permanent lors d'une édition par lot sur le backoffice v3
RAS
RAS

(PC-21219)[API] fix: manage venues indexing when batch edited

---

.github/workflows/update-api-client-template.yml

Lorsque le schema api change il faut générer les types pour le front avec `yarn generate:api:client` 
Avant un commit s'ajoutait avec les changements. On a repéré plusieurs défauts : 
- Un historique git pas joli
- Ca cache les checks et cause des erreurs aux merges [exemple](https://passcultureteam.slack.com/archives/CPZ7U1CNP/p1686652602040439)

(BSR) chore: Throw error on api client change needed instead of commit added

---

api/src/pcapi/routes/backoffice_v3/templates/collective_offer/details.html
api/tests/routes/backoffice_v3/collective_offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22981
En tant que PM
J'aimerais changer le nom des champs sur les offres collectives
Afin de homogéiniser avec les offres indiv
Dans une offre collective remplacer “etat” par “statut et “conformité” et “état”
NA

(PC-22981)[API] fix: correct collective offers labels

---

helmfile.yaml

This chart version enables a new port for Prometheus metrics.

(PC-23002)[API] build: Bump chart version on perf to 0.21.8

---

api/src/pcapi/core/users/email/update.py
api/tests/core/users/email/test_update.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22580
Suite à un BPMN, on corrige l'ordre des vérifications (token, email, etc) pour que ce soit cohérent pour le front et les utilisateurs
En cas de fail, on gère mieux le retry car les token ne sont expirés qu'en cas de succès
- CF strat tech du ticket
- None
- None

PC-22580 update 'change email' confirmation checks order

---

api/src/pcapi/core/mails/transactional/educational/eac_new_request_made_by_redactor_to_pro.py
api/tests/core/mails/transactional/educational/eac_new_request_made_by_redactor_to_pro_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23031
Ajouter les paramètres `OFFERER_ID` et `VENUE_ID` lors de l'envoie du mail indiquant une nouvelle demande d'offre réservable.

(PC-23031)[PRO] feat: add offerer id and venue id to new request mail

---

api/src/pcapi/admin/install.py
api/tests/admin/custom_views/admin_user_view_test.py
api/tests/admin/custom_views/api_key_view_test.py
api/tests/admin/custom_views/beneficiary_user_view_test.py
api/tests/admin/custom_views/booking_view_test.py
api/tests/admin/custom_views/boost_pivot_view_test.py
api/tests/admin/custom_views/category_view_test.py
api/tests/admin/custom_views/cgr_pivot_view_test.py
api/tests/admin/custom_views/cine_office_pivot_view_test.py
api/tests/admin/custom_views/criteria_view_test.py
api/tests/admin/custom_views/cultural_survey_view_test.py
api/tests/admin/custom_views/custom_reimbursement_rule_view_test.py
api/tests/admin/custom_views/feature_view_test.py
api/tests/admin/custom_views/many_offers_operations_view_test.py
api/tests/admin/custom_views/offer_view_test.py
api/tests/admin/custom_views/offerer_tag_category_view_test.py
api/tests/admin/custom_views/offerer_tag_view_test.py
api/tests/admin/custom_views/offerer_view_test.py
api/tests/admin/custom_views/partner_user_view_test.py
api/tests/admin/custom_views/pro_user_view_test.py
api/tests/admin/custom_views/support_view_test.py
api/tests/admin/custom_views/suspend_fraudulent_users_by_ids_test.py
api/tests/admin/custom_views/user_email_history_view_test.py
api/tests/admin/custom_views/user_offerer_view_test.py
api/tests/admin/custom_views/venue_provider_view_test.py
api/tests/admin/custom_views/venue_view_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22604
Décommission de Flask-admin, en commentant toutes les routes (sauf les offres et les règles de fraude)

(PC-22604)[API] feat: comment flask admin routes

---

api/src/pcapi/routes/backoffice_v3/user_generation/blueprint.py
api/tests/routes/backoffice_v3/user_generation_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22806
Empêcher la génération d'un utilisateur quand les options sélectionnées dans le formulaire sont incompatibles avec les règles métier.
https://github.com/pass-culture/pass-culture-main/assets/128476306/488d917f-aa14-4fce-90cb-2fdd17c01093

[PC-22806](API) feat: Validate with business rules

---

api/src/pcapi/core/providers/repository.py
api/src/pcapi/routes/public/collective/endpoints/venues.py
api/tests/routes/public/blueprint_v2_openapi_test.py
api/tests/routes/public/collective/endpoints/get_collective_offers_venues_test.py
pro/src/apiClient/v2/services/ApiOffresCollectivesBetaService.ts

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22994
Fix : récupérer les lieux depuis l'API collective doit maintenant se faire en se basant sur le fournisseur (_provider_) et non plus sur la structure (_offerer_).
Ce changement se fait via un FF, comme pour les offres.

(PC-22994)[API] fix: eac: collective api: providers not offerers

---

api/src/pcapi/routes/native/v1/serialization/offers.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/native/v1/offers_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23051
Ne plus remonter les stocks soft deleted dans la réponse de GET /offer/ID

(PC-23051)[API] fix: hide soft deleted stocks from offer response

---

.github/workflows/update-api-client-template.yml

Rendu ([visible ici](https://github.com/pass-culture/pass-culture-main/actions/runs/5376741422/jobs/9754305650?pr=7048) pour cette PR) :

(BSR)[API] ci: Show diff in GitHub Action if API client must be updated.

---

helmfile.yaml

Version 0.21.9 has the latest fixes to export metrics with Prometheus.

(BSR)[API] build: Use latest version of the Helm chart (Prometheus)

---

api/src/pcapi/core/offers/api.py
api/tests/core/offers/test_api.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23070
Actuellement, quand un produit existant passe en inéligible, nous ne resynchronisation pas aloglia pour ses offres.
Cette PR ajoute la re-synchro algolia
- Ajout d'appel de `search.async_index_offer_ids` pour :
- Quand le produit a au moins un booking 
- Quand le produit n'as pas de booking
NA
NA

(PC-23070)[API] fix: unsync offer from algolia on delete unwanted product

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/routes/backoffice_v3/filters.py
api/src/pcapi/routes/backoffice_v3/offer_validation_rules/blueprint.py
api/src/pcapi/routes/backoffice_v3/offer_validation_rules/forms.py
api/tests/routes/backoffice_v3/offer_validation_rules_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23054
- Correction d’un bug d’affichage lors de la modification de sous-règle type d’offre, où la liste des types n'était pas remplie.
- Trier les mots-clés par ordre alphabétique
- Trier les règles par ordre alphabétique
- Permettre d'écrire des noms de règle plus longs (256 max)
- Rajouter 4 types de sous-règles:
Sous-catégorie de l’offre collective
Sous-catégorie de l’offre collective vitrine
Catégorie de l’offre collective
Catégorie de l’offre collective vitrine

(PC-23054)[API] feat: add minor feats to offer validation rules

---

api/src/pcapi/connectors/titelive.py

Si la recherche est 404, cela envoi une erreur sur sentry.
La 404 n'étant pas une erreur que nous souhaitons remonter sur sentry, nous la passons en warning
NA
NA
NA

(BSR)[API] fix: decrease sentry error level when ean is 404

---

api/Dockerfile
api/entrypoint.sh
api/gunicorn.conf.py
api/requirements.txt
api/src/pcapi/app.py
api/src/pcapi/backoffice_app.py
api/src/pcapi/flask_app.py

Metrics are gathered by Flask through the `prometheus_flask_exporter`
library. For now, we gather the following basic metrics about HTTP
requests:
- request duration;
- number of requests;
- number of uncaught exceptions.
Labels are: HTTP method, URL route (e.g. `/venues/<id>` with literal
`<id>` to aggregate calls to this route for all venues) and HTTP
response code. These metrics and labels will probably be tweaked
later.
These metrics are exported by a server that is started by Gunicorn.
Port defaults to 5002.
All features (metrics gathering and export server) are controlled by
the `ENABLE_FLASK_PROMETHEUS_EXPORTER` environment variable. It is off
by default.

(PC-23002)[API] feat: Expose Flask metrics to Prometheus

---

api/src/pcapi/core/bookings/api.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22922
- Erreur Sentry sur la validité d'un code barre pour les réservations externes. 

(PC-22922)[API] fix: Barcode Error when cancel external booking

---

api/src/pcapi/connectors/dms/models.py
api/src/pcapi/core/educational/api/dms.py
api/tests/core/educational/api/test_update_dms_status.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23013
Ajout d'un reset de l'import DMS EAC dans le cas où il se bloque

(PC-23013)[API] feat: force reset when dms eac import is stuck

---

api/src/pcapi/scripts/rebuild_staging/anonymize.sql

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22931
Anonymiser les données du dossier Ubble des utilisateurs lors de la recopie de la BDD en staging.
Ajout de 2 instructions dans le script anonymise.sql.
La [doc](https://ubbleai.github.io/developer-documentation/#internationalization) Ubble nous dit d'utiliser les codes suivants :
- 11111111-1111-1111-1111-111111111111 pour un identification valide,
- 00000000-0000-0000-0000-000000000000 pour une identification invalide,
- 22222222-2222-2222-2222-222222222222 si non décidé.

PC-22931: Anonymise Ubble staging data

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230704T102119_05de9b01bf9b_rename_category_validation_attribute.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/routes/backoffice_v3/filters.py
api/tests/core/offers/test_api.py
api/tests/routes/backoffice_v3/offer_validation_rules_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23106
Fix les sous-règles impliquant les catégories d'offre

(PC-23106)[API] fix: fix category offer validation rule

---

api/src/pcapi/routes/public/individual_offers/v1/products.py
api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/tests/routes/public/individual_offers/v1/endpoints_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23129
Workers cannot access request contexted current_api_key.
https://sentry.passculture.team/organizations/sentry/issues/419621/?project=5&referrer=slack
Remove an unused field that we thought once was a good idea

(PC-23129)[API] fix create multiple ean on workers

---

pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/TicketWithdrawal.tsx
pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/__specs__/TicketWithdrawal.spec.tsx
pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/constants.ts
pro/src/components/OfferIndividualForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx
pro/src/core/Offers/constants.ts
pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.edition.spec.tsx
pro/src/screens/OfferIndividual/Summary/OfferSection/OfferSection.tsx

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23065
Dans le parcours de création d’offre, pour les types d’offres qui affichent la partie suivante 
Remplacer “Comment les billets, places seront-ils transmis ?“ par “Précisez la façon dont vous distribuerez les billets :”
remplacer “Évènement sans billet“ par “Aucun billet n’est nécessaire”
remplacer “Envoi par email“ par “Les billets seront envoyés par email”
remplacer “Retrait sur place (guichet, comptoir...)“ par “Les billets devront être retirés sur place (guichet, comptoir...)”
- Branche : `PC-23065-wording-methode`

(PR-23065)[PRO] feat: wording de méthode de transmission

---

pro/src/pages/Home/Homepage.scss

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18004
- 16px entre 'profil' et les informations
- 40px --> 32px entre le titre des sections

(PC-18004)[PRO] fix: spacing between section and profile title

---

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/ToggleVenueProviderStatusButton/ToggleVenueProviderStatusButton.tsx

the ts-expect-error hide 2 errors, price is not a string and providerId missing.
The second one was the bug
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-23129

(PC-23129)[API] fix: updateVenueProviderPayload body

---

api/src/pcapi/core/educational/models.py

Rajouter une porperty aux CollectiveOfferTemplate qui est utilisée par les règles de fraude

(BSR)[API] fix: add categoryid property to offer collective templates

---

api/src/pcapi/core/fraud/factories.py
api/src/pcapi/core/users/factories.py
api/tests/core/users/test_generator.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22956
Faire en sorte que les données générées aléatoirement pour les attributs de l'utilisateur soient aussi celles utilisées pour ses `beneficiaryFraudChecks` `PROFILE_COMPLETION` et `IDENTITY_CHECK`.
- Passer les attributs en paramètre des factories avec le deep context.

PC-22956 Make fraud checks consistent with user

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230703T131004_97cccec19d0e_remove_unused_backoffice_permission.py
api/src/pcapi/core/permissions/models.py
api/src/pcapi/routes/backoffice_v3/fraud.py
api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
api/tests/routes/backoffice_v3/conftest.py
api/tests/routes/backoffice_v3/fraud_test.py

https://passculture.atlassian.net/browse/PC-22980
Suppression de la permission backoffice ""suspendre en masse des comptes bénéficiaires/grand public" remplacé par “actions exclusives à l'équipe Fraude (jeune)”
- Remove permission
- Update référence
À mon sens, pas besoin d'écrire exceptionnellement de tests, ceux en place suffissent. Un contrôle de permission permet de vérifier que les routes fraudes ont obligatoirement et uniquement la permission "actions exclusives à l'équipe Fraude (jeune)"
Voir `UnauthorizedHelperBase` de `tests/routes/backoffice_v3/helpers/unauthorized.py`
- [] J'ai relu attentivement les migrations, en …

(PC-22980] feat: Delete unused backoffice permission by using another.

---

api/src/pcapi/routes/public/individual_offers/v1/products.py

current_api_key is defined in a context of a request, not in workers
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23129

(PC-23129)[API] fix: again, i went too fast and forgot a fix

---

.github/workflows/tests-main.yml

On a eu une plusieurs bug en testing, cela arrivait parcequ'une PR avec des commits méleangent de l'api et du pro et que le dernier commit comprends des modifs uniquement sur l'une des deux app est mergée. Seul le dernier commit est regardé pour savoir ce qu'on doit déployer -> Décalage de version entre le front et le back. 
Simple fix : toujours déployer les deux comme en staging/prod

(BSR) fix: always deploy both app on testing

---

api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23064
Pour les lieux ayant à la fois des coordonnées bancaires (`bankInformation`) ET un point de remboursement valide : le point de remboursement affiché dans l'onglet "Remboursements" et dans l'encadré à droite étaient différents.
En me basant sur ce qu'affiche PC pro dans les coordonnées bancaires des lieux en question, j'ai conclu que même si un lieu est porteur d'informations bancaires (`bankInformation`), un point de remboursement valable (`reimbursementPoint`) sera toujours préféré pour le remboursement.
J'ai donc modifié la façon de sélectionner le point de remboursement du lieu en me basant d'abord sur les `reimbursement_point_links` plutôt que sur ses `bankInformation`

(PC-23064)[BO] Fix different reimbursement points on venue page

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22750
Supprimer les offres collectives liées au lieu "eac_rejected" : elles ne devraient pas exister et ne peuvent pas être dupliquées, ce qui créé de la confusion.

(PC-22750)[API] feat: sandbox: eac: rm offers from eac_rejected offerer

---

.github/workflows/tests-main.yml

This reverts commit befb3d5e0d415e34c036599705e2dcd4d1f16b7c.
This didn't work because deploy-api needs "build api docker image on master" needs test-api to run. 
We will have to be smarter but i don't have time now

Revert "(BSR) fix: always deploy both app on testing"

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23174
Fix l'icone à côté de "en savoir plus" dans adage

(PC-23174)[PRO] fix: add default size for stroke icon in adage offer

---

api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/tests/local_providers/titelive_things_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22592
Migration de la version 11 à 19 du dossier ftp titelive
Les champs supprimés n'étaient pas utilisé ou sont devenus obselète (csr entre autre)
https://www.notion.so/passcultureapp/Mise-jour-de-titelive_things-synchronisation-version-2019-19-cddfb66ac8ee4e1bb935a40e7a8fa0e4
NA

(PC-22592)[API] fix: upgrade titelive ftp folder version from 11 to 19

---

pro/src/screens/OfferIndividual/StocksEventEdition/StockFormList/StockFormList.tsx
pro/src/screens/OfferIndividual/StocksEventEdition/StocksEventEdition.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23192

(PC-23192)[PRO] fix: do not partially reset filters on stocks deletion

---

api/src/pcapi/routes/adage_iframe/logs.py
api/src/pcapi/routes/adage_iframe/serialization/logs.py
api/tests/routes/adage_iframe/post_logs_test.py
pro/src/apiClient/adage/models/AdageHeaderLogBody.ts
pro/src/apiClient/adage/models/CatalogViewBody.ts
pro/src/apiClient/adage/models/CollectiveRequestBody.ts
pro/src/apiClient/adage/models/OfferIdBody.ts
pro/src/apiClient/adage/models/SearchBody.ts
pro/src/apiClient/adage/models/StockIdBody.ts
pro/src/pages/AdageIframe/app/App.tsx
pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx
pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/ContactButton.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/RequestFormDialog.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/__specs__/RequestFormDialog.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23189
Renomme le champs `AdageHeaderFrom` pour `iframe_from` dans les logs adage par soucis d'homogénéité pour la data

(PC-23189)[PRO] feat: rename AdageHeaderFrom to iframe_from for data

---

pro/src/ui-kit/Banners/BannerLayout/BannerLayout.tsx

- Corriger l'affichage de l'icône shadowTipsHelp dans la bannière info

(BSR)[PRO] fix: banner tips help icon viewbox

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230515T175443_ccacb677c93a_add_finance_event_table.py
api/src/pcapi/alembic/versions/20230614T154659_405f222670b2_add_pricing_finance_event_id.py
api/src/pcapi/alembic/versions/20230614T181345_c00fce7569d7_remove_booking_constraint_on_pricing.py
api/src/pcapi/alembic/versions/20230705T083544_9801fe92e7af_add_fk_on_pricing_event_id.py
api/src/pcapi/alembic/versions/20230705T084328_c1bd21cac4e9_add_fk_on_finance_event_booking_id.py
api/src/pcapi/alembic/versions/20230705T084518_1b0734e11842_add_fk_on_finance_event_collective_booking_id.py
api/src/pcapi/alembic/versions/20230705T084850_9e189b7f3fb1_add_fk_on_finance_event_venue_id.py
api/src/pcapi/alembic/versions/20230705T084951_eb8f028d2a9c_add_fk_on_finance_event_pricing_point_id.py
api/src/pcapi/alembic/versions/20230706T123053_097c6d306952_add_index_on_pricing_event_id.py
api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/commands.py
api/src/pcapi/core/finance/factories.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/core/finance/siret_api.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/models/feature.py
api/src/pcapi/repository/clean_database.py
api/src/pcapi/sandboxes/scripts/creators/data/create_data_bookings.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
api/tests/core/bookings/test_api.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_integration.py
api/tests/core/offerers/test_api.py
api/tests/core/offers/test_api.py

J'ai essayé de résumer l'idée dans le message de commit et d'indiquer par des commentaires de pull request les endroits qui sont des copies (ou presque) de l'actuel code (et qui donc présente probablement peu d'intérêt à être relu dans les détails).
À part ça, faut un peu se lancer dedans.  :) Suggestion :
- lire les modifications dans `core.bookings.api`, qui amènent aux nouvelles fonctions `core.finance.api.add_event()` et `cancel_latest_event()` ;
- jeter un oeil aux modèles.
Reste à faire : 
- écrire des tests pour les nouvelles fonctions ;
- modifier les migrations pour créer les clés étrangères dans des migrations séparées (cf. commentaire `FIXME (before merge)`) ;
- compléter les tests d'intégration ;
- adapter la sandbox, probablement.
---
This commit introduces the notion of …

(PC-22790) Ajout de FinanceEvent

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py

Before switching from the `price_bookings` to the `price_event()`
cronjob, we'll need to create a finance event for each used booking.
To ease that switch, `price_booking()` can already link the created
pricing to the finance event (if there is one).

(PC-22790)[API] feat: Make `price_booking()` link new pricing to finance event

---

api/src/pcapi/routes/public/books_stocks/serialization.py
api/tests/routes/pro/post_stocks_test.py

This bug appeared in this commit https://github.com/pass-culture/pass-culture-main/commit/0b1fdf116ce735cbce743f2b8615ec27adb22aad
quantity=0 means remaining_quantity=0 .
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23304

(PC-23304)[API] fix: allow stocks quantity to be 0

---

api/requirements.txt

See https://github.com/psf/requests/releases for the changelog.
Nothing notable, except:
- a security fix about `Proxy-Authorization` HTTP header (we were not
affected);
- an update of `urllib3`, whose changelog [1] does not contain anything
notable either.
[1] https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#what-are-the-important-changes

(BSR)[API] bump: Bump requests to 2.31.0

---

api/src/pcapi/routes/backoffice_v3/offer_validation_rules/blueprint.py
api/src/pcapi/routes/backoffice_v3/offer_validation_rules/forms.py
api/src/pcapi/routes/backoffice_v3/offer_validation_rules/utils.py
api/tests/routes/backoffice_v3/offer_validation_rules_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23066
- Ajout de filtres de recherche sur la page "Règles de validation d'offres"
- Structure
- Catégorie
- Sous-catégorie
- Recherche par mot clé via la search bar actuelle
- Fix d'un bug lié à l'ajout de règles de conformité sur le type d'offre "Offre collective" (lié à une faute de frappe dans le code)
- Formatage des mots clés d'une sous-règle avant l'enregistrement en base (passage en lowercase et sans accent) pour simplifier leur exploitation
- Un script sera à exécuter pour formater les anciens mots clés si besoin

(PC-23066)[BO] Add filters to offer validation rule search

---

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23318
Afficher un message d'erreur lorsque le champ "prix" est vide. (rollback de ce qui était présent avant modification)

(PC-23318)[PRO] fix: display required message for allocine price field 

---

api/src/pcapi/utils/rate_limiting.py

flask_limiter logs an error each time we get a request that has an
empty identifier:
Skipping limit: 10 per 1 minute. Empty value found in parameters.
This is logged from `flask_limiter.Limiter.__evaluate_limits()`. To
avoid that, we can provide a non-empty value. Since we don't really
need to rate-limit requests that don't provide any identifier, we
can use a UUID.
---
Erreur Sentry qu'on cherche à faire taire : https://sentry.passculture.team/organizations/sentry/issues/394199/

(BSR)[API] fix: Avoid flask_limiter error log with email_rate_limiter when email is empty

---

api/src/pcapi/routes/backoffice_v3/templates/admin/users_generator.html
api/src/pcapi/routes/backoffice_v3/user_generation/blueprint.py
api/tests/routes/backoffice_v3/user_generation_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22930
Quand l'utilisateur est généré, on génère en même temps un token de type ```EMAIL_VALIDATION``` pour ensuite afficher un lien vers l'app et se connecter directement.
Le choix a été fait d'utiliser ce type de token pour faciliter l'implémentation backend et ne pas apporter de modification au front.
Cela permet un cas d'usage tout à fait fonctionnel.
https://github.com/pass-culture/pass-culture-main/assets/128476306/a911f7de-23b5-446a-ac1c-394747ef249c

(PC-22930)[BO] feat: Add link to app in user generator

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230712T150744_08dfd555fca2_add_categories_tags_offre_lieux.py
api/src/pcapi/alembic/versions/20230713T111742_9f5e01a79b73_init_categories_tags_offre_lieux.py
api/src/pcapi/core/criteria/models.py
api/src/pcapi/routes/backoffice_v3/forms/tags.py
api/src/pcapi/routes/backoffice_v3/tags.py
api/src/pcapi/routes/backoffice_v3/templates/tags/list_tags.html
api/tests/routes/backoffice_v3/tags_test.py

Permettre l'ajout de catégories sur les tags offres et lieux à des fins de reporting.
https://passculture.atlassian.net/browse/PC-21648
Liste :
Édition :

Pc 21648 add categories tags offres lieux

---

api/src/pcapi/routes/native/v1/account.py
api/tests/routes/native/v1/account_test.py
api/tests/routes/native/v1/openapi_test.py

Retourner des 401 (au lieu de 404) pour faciliter la gestion des erreurs pour le front
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21255

(PC-21255)[API] fix: use correct api error codes when token is expired

---

api/src/pcapi/models/feature.py
api/src/pcapi/routes/public/booking_token/v1/endpoints.py
api/tests/routes/public/booking_token/v1/get_booking_by_token_test.py
api/tests/routes/public/booking_token/v1/patch_booking_by_token_test.py

This API was planned to be deactivated on 2023-07-01. Here we add a
feature flag that can be used to deactivate the API for a few weeks
before we finally delete the code.

(PC-23341)[API] feat: Add feature flag to activate/deactivate v1 of API Contremarque

---

api/src/pcapi/core/search/backends/algolia.py
api/tests/core/search/test_serialize_algolia.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23234
Inclure la description lors de la sérialisation des offres collectives.

(PC-23234)[API] feat: search: add description to collective offers

---

api/src/pcapi/utils/csr.py

Ajout d'un flag pour ne pas logger si on a un mauvais gtl_id et qu'on get le csr le plus proche.
Ceci afin d'éviter 4 millions de log lorsqu'on ajoutera les gtl_id a nos produits via un script.

(BSR)[API] fix: add logging flag to get_closest_csr

---

api/src/pcapi/routes/native/v1/favorites.py
api/src/pcapi/routes/native/v1/serialization/favorites.py
api/tests/routes/native/v1/favorites_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23222

(PC-23222)[API] feat: Set offerer's name as favorite's venue name for digital offers

---

api/src/pcapi/core/fraud/api.py
api/src/pcapi/core/fraud/models.py
api/src/pcapi/core/subscription/api.py
api/tests/core/fraud/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23050
Le ticket avait déjà été mergé mais l'implémentation était fausse : elle ne couvrait pas la user story décrite.
Cette PR enlève ce qui avait été fait pour le réimplémenter différemment : 
À la première PR on couvrait le cas d'un utilisateur doublement bénéficiaire dans `activate_beneficiary_if_no_missing_steps`, or cette fonction est appelée à de nombreux endroits et il est difficile de cerner son périmètre d'action. La preuve en est, la user story ne fonctionnait pas.
Ici on intègre ce cas de fraude à la validation des `FraudItems`, c'est-à-dire dès la réception des résultats de la vérification d'identité.

(PC-23050) Fix duplicate fraud detection

---

api/tests/core/users/test_generator.py

Le test `test_profile_completion_is_consistent_with_user_data`était flaky parce qu'on est jamais sûr de l'ordre dans lequel SQL nous renvoie les objets.
Ici on se fie plutôt à des fonctions existantes qui se chargent de faire le tri.

(BSR) fix: Fix flaky test_profile_completion_is_consistent_with_user_data

---

api/src/pcapi/routes/backoffice_v3/offers/blueprint.py
api/src/pcapi/routes/backoffice_v3/offers/forms.py
api/tests/routes/backoffice_v3/offers_test.py

Mettre la possibilité de trier par date de création sur l'écran Backoffice Offres individuelles quand on vient d'une recherche pré-filtrée (page d'accueil) :
Ticket Jira : https://passculture.atlassian.net/browse/PC-23320

(PC-23320)[BO] fix: preserve date created sort during offer search

---

api/src/pcapi/routes/adage/v1/blueprint.py

Version check is only useful for endpoints that are used by the
beneficiary app.

(BSR)[API] fix: Don't check client version on our "/adage" endpoints

---

pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageAdd/ButtonImageAdd.tsx
pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageEdit.tsx
pro/src/components/ImageUploader/ImageUploader.tsx
pro/src/components/OfferIndividualForm/ImageUploaderOffer/ImageUploaderOffer.tsx
pro/src/components/OfferIndividualForm/ImageUploaderOffer/__specs__/ImageUploaderOffer.tracker.spec.tsx
pro/src/components/VenueForm/ImageUploaderVenue/ImageUploaderVenue.tsx
pro/src/components/VenueForm/ImageUploaderVenue/__specs__/ImageUploaderVenue.tracker.spec.tsx
pro/src/components/VenueForm/VenueForm.tsx
pro/src/core/FirebaseEvents/constants.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23283
- Ajouter le tracker hasClickedAddImage lorsque l'utilisateur clique sur "Ajouter une image"

(PC-23283)[PRO] feat: add has clicked add image tracker

---

api/src/pcapi/routes/public/individual_offers/v1/bookings_serialization.py

Non-event bookings do not have a cancellation limit date.
--- 
Vu sur https://sentry.passculture.team/organizations/sentry/issues/420784/

(BSR)[API] fix: Fix serialization of non-event bookings in individual offers API

---

pro/src/components/ImageUploader/ButtonImageEdit/index.ts
pro/src/components/ImageUploader/ImageUploader.tsx
pro/src/components/ImageUploader/index.ts
pro/src/components/OfferIndividualForm/ImageUploaderOffer/ImageUploaderOffer.tsx
pro/src/components/OfferIndividualForm/ImageUploaderOffer/utils/buildInitialValues.ts
pro/src/components/VenueForm/ImageUploaderVenue/ImageUploaderVenue.tsx
pro/src/core/FirebaseEvents/constants.ts
pro/src/core/Offers/types.ts
pro/src/screens/OfferEducational/OfferEducationalForm/FormImageUploader/FormImageUploader.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21533
L’event HasUploadedImage est déclenché à l’upload de l’image (image de lieu car le tracker hasClickedOfferFormNavigation permet de tracker l'événement côté offre)

(PC-21533)[PRO] feat: add has upload image tracker for venue

---

pro/src/pages/Offerers/Offerer/VenueV1/fields/ApplicationBanner/ApplicationBanner.tsx
pro/src/pages/Offerers/Offerer/VenueV1/fields/ApplicationBanner/__specs__/ApplicationBanner.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23448
Vos remboursements seront rétroactifs une fois vos coordonnées bancaires ajoutées.” → validées.
Voir le dossier en cours” : 
- Lien de renvoi actuel : dossier DS
- Lien de renvoi souhaité : messagerie dossier DS (lien iso “Suivre mon dossier de CBs” situé dans le bloc prochaines étapes)

(PC-23448)[PRO] fix: wording and DS link in ApplicationBanner component

---

pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx
pro/src/components/OfferEducationalActions/__specs__/OfferEducationalActions.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23285
Screen

(PC-23285)[PRO] fix display publier sur adage button when pending

---

api/tests/routes/backoffice_v3/offerers_test.py

Ticket Jira (ou description si BSR) : fix du test `tests/routes/backoffice_v3/offerers_test.py::ListOffererTagsTest::test_list_offerer_tags`

(BSR)[BO] fix: fix flaky test

---

api/src/pcapi/utils/decorators.py
api/tests/connectors/api_boost_test.py

(PC-23048)[API] fix: typo in retry decorator+tests

---

api/src/pcapi/routes/backoffice_v3/venues.py
api/tests/routes/backoffice_v3/venues_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-23394
Pouvoir : 
-     faire les modifications sur les lieux, en ne faisant uniquement les modifications sur les tags
-     faire des modifications sur les lieux en faisant tags + lieu permanent
Il y avait un bug si on ne choisissait uniquement les tags sans les notions de lieux permanents/non permanents

(PC-23394) fix: allow modification only of venues tags

---

api/.env.integration

We should not send events to Amplitude on that environment. The logger
backend will thus be enough. But we need to customize the name of the
queue for Google Task (it defaults to "amplitude-queue-development",
which does not exist on the "integration" environment).

(BSR)[API] fix: Fix Amplitude configuration on integration

---

api/src/pcapi/core/users/api.py
api/src/pcapi/routes/native/v1/authentication.py
api/src/pcapi/routes/native/v1/serialization/authentication.py
api/src/pcapi/settings.py
api/tests/core/users/test_api.py
api/tests/routes/native/v1/authentication_test.py
api/tests/routes/native/v1/openapi_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21669

(PC-21669)[API] feat: Extend refresh token lifetime when logging in from trusted device

---

api/src/pcapi/routes/adage_iframe/serialization/redactor.py
api/tests/routes/adage_iframe/get_authenticate_test.py
pro/src/apiClient/adage/models/RedactorPreferences.ts
pro/yarn.lock

**Fix** `feedback_form_closed` peut être nul.
**Avant (contexte)**
Si aucune préférence n'a été enregistrée pour l'enseignant, la valeur par défaut (un objet JSON vide) sera remontée et utilisée lors de la sérialisation. La clé `feedback_form_closed` n'est donc pas présente et _pydantic_ génère une erreur.

(BSR)[API] fix: eac: field can be None

---

api/src/pcapi/core/fraud/factories.py

**Bug** test flaky à cause de la génération de noms de domaine. Deux objets de la table blacklisted_domain_name peuvent se retrouver avec le même nom, ce qui fait planter le test.
**Fix** utiliser une séquence afin d'éviter tout doublon.

(BSR)[BO] fix: use sequence not faker's domain_name

---

api/src/pcapi/core/users/factories.py
api/src/pcapi/core/users/generator.py
api/src/pcapi/routes/backoffice_v3/user_generation/blueprint.py
api/src/pcapi/routes/backoffice_v3/user_generation/forms.py
api/tests/core/users/test_generator.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22957
Ajouter la possibilité de créer un utilisateur qui a été bénéficiaire 15-17 et qui a maintenant 18 ans.
https://github.com/pass-culture/pass-culture-main/assets/128476306/1f6e2f56-31f3-4a6c-967b-fa230968fcb1

(PC-22957)[API] feat: Create option in generator for user in 17-18 transition

---

pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
pro/src/screens/OfferEducationalStock/__specs__/OfferEducationalStock.spec.tsx
pro/src/screens/OfferEducationalStock/validationSchema.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23282
A noter que lors de l'édition d'un offre qui n'avait pas de `priceDetail`, le bouton "Enregistrer" ne trigger la validation du formulaire (et donc le message d'erreur) que quand on est sur l'onglet Date & prix.

(PC-23282)[PRO] make priceDetail mandatory in collective offer form

---

api/src/pcapi/core/token/__init__.py
api/src/pcapi/core/users/email/update.py
api/src/pcapi/routes/native/v1/account.py
api/tests/core/users/email/test_update.py
api/tests/core/users/test_api.py
api/tests/routes/native/v1/account_test.py

- nettoyer le code pour supprimer le support des anciens tokens. 
- Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23343
contexte:
doit être merger au plutôt 24 heures après la mise en production  le temps que les anciens tokens disparaissent
- https://passculture.atlassian.net/browse/PC-23312
- https://passculture.atlassian.net/browse/PC-23344

Pc 23343 old tokens support email change

---

api/src/pcapi/core/mails/transactional/bookings/booking_confirmation_to_beneficiary.py
api/src/pcapi/core/mails/transactional/bookings/new_booking_to_pro.py
api/src/pcapi/core/offers/models.py
api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py
api/tests/core/mails/transactional/bookings/new_booking_to_pro_test.py

- ajouter les attribut (exemple: VO, Imax) à l'email de confirmation de réservation du côté jeune et du côté pro
- Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23356

Pc 23356 add features to booking confirmation email

---

api/src/pcapi/core/providers/api.py

`Offer` has an `idAtProvider` attribute, `Stock` has `idAtProviders`...

(BSR)[API] fix: Fix AttributeError in `_validate_stock_or_offer()`

---

api/src/pcapi/routes/backoffice_v3/finance/blueprint.py
api/src/pcapi/routes/backoffice_v3/finance/forms.py
api/src/pcapi/routes/backoffice_v3/templates/finance/incident/list.html
api/tests/routes/backoffice_v3/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21880
Apport de quelques fix sur la création d'incident, dont :
- Le montant final de l'incident (directement basé sur le montant du dernier `Pricing` facturé)
- Alignement du compteur d'incidents affichés sur la page globale
- Le wording du label sur le montant de l'incident
- Afficher uniquement l'origine de l'incident au lieu de tous les détails de l'incident dans la page globale

(PC-21880)[BO] fix incident amount on creation

---

api/src/pcapi/routes/backoffice_v3/offers/blueprint.py
api/src/pcapi/routes/backoffice_v3/offers/forms.py
api/src/pcapi/routes/backoffice_v3/utils.py
api/tests/routes/backoffice_v3/offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23484
- Ajout du filtre avancé sur la date limite de réservation d'une offre

(PC-23484)[BO] Add booking limit date to offers advanced search

---

api/src/pcapi/core/users/api.py
api/src/pcapi/routes/backoffice_v3/accounts.py
api/src/pcapi/utils/email.py
api/tests/core/users/test_api.py
api/tests/routes/backoffice_v3/accounts_test.py

Pour améliorer la rapidité de la recherche de bénéficiaire par adresse email. Nous regardons dans un premier temps s'il y a des utilisateurs avec l'email recherché. Si aucun résultat, nous recherchons dans la table d'historique des adresses emails. 
Ticket Jira : https://passculture.atlassian.net/browse/PC-23415
- [] J'ai ajouté des screenshots pour d'éventuels changements graphiques

(PC-23415)[BO] feat: user search by email, with or without email history

---

api/src/pcapi/scripts/rebuild_staging/anonymize.sql

These UUID were not valid version 4 UUIDs and were causing errors in
the back-office (in user account view) because Pydantic failed to
validate them.
First, let's check whether an UUID is valid:
>>> import uuid
>>> uuid.UUID(str(uuid.uuid4())).version
4
>>> print(uuid.UUID('11111111-1111-1111-1111-111111111111').version)
None
Oops. Let's try to keep those 1's to make it noticeable.
>>> uuid.UUID('11111111-1111-1111-1111-111111111111', version=4)
UUID('11111111-1111-4111-9111-111111111111')
>>> uuid.UUID('11111111-1111-4111-9111-111111111111').version
4
That's better. Thank you, Python.

(BSR)[API] fix: Use valid UUIDs in anonymize script upon staging rebuild

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/core/offers/test_repository.py
api/tests/routes/pro/get_offers_test.py
api/tests/routes/pro/patch_all_offers_active_status_test.py

Fix offer search when you search with beginningDate = endDate. 
PC pro sends the API dates not datetimes. To handle endDate correctly we have to set the time at 23:59.
I also cleaned the code to make it clear that dates are without time.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23558

(PC-23558)[PRO] fix: find offer on specific day

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts
pro/src/pages/AdageIframe/app/providers/FacetFiltersContextProvider.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23628
Valoriser la barre de recherche avec le nom du lieu quand l'utilisateur adage arrive depuis la carto
En local : 
FF à activer : `WIP_ENABLE_NEW_ADAGE_FILTERS`
Ajouter à la fin de l'url : `venue=[ID du lieu]`

(PC-23628)[PRO] feat: fill search bar with venue filter when valued

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230801T165116_4fb121d642ef_remove_feature_flag_enable_new_fraud_rules.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/models/feature.py
api/tests/core/offers/test_api.py
api/tests/routes/pro/patch_collective_offer_publication_test.py
api/tests/routes/pro/patch_collective_offer_template_publication_test.py

Retire le FF WIP_ENABLE_NEW_FRAUD_RULES qui est toujours à true depuis le démantèlement de Flask Admin
Suppresion sur les environnements : https://www.notion.so/passcultureapp/Manip-faire-pour-les-MES-MEP-MEI-1e3c8bc00b224ca18852be1d717c52e5
Ticket Jira: https://passculture.atlassian.net/browse/PC-23295

(PC-23295)[API] refactor: Remove WIP_ENABLE_NEW_FRAUD_RULES feature flag

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py

In `_delete_dependent_event_pricings()`, if we delete some pricings,
we should price the related finance events again. For this, their
status must go back from "priced" to "ready".

(BSR)[API] fix: Update status of dependent finance events in _delete_dependent_event_pricings

---

api/src/pcapi/core/subscription/api.py
api/tests/core/subscription/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23584

(PC-23584)[API] fix: Cancel and re-do HONOR_STATEMENT when eligibility difference detected

---

api/src/pcapi/models/feature.py
api/src/pcapi/routes/public/individual_offers/v1/events.py
api/tests/routes/public/individual_offers/v1/patch_event_test.py
api/tests/routes/public/individual_offers/v1/post_event_test.py

We don't want to allow partners to use the event api to create events with tickets, they will have to wait until our booking api is release. This is to avoid having a spike in support request. However we want to have beta testers, some are interested for free events

(PC-23454)[API] feat: do not allow events with tickets

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22377
Ajout du tracking des filtres adage quand une nouvelle requête algolia est lancée 
FF : WIP_ENABLE_NEW_ADAGE_FILTERS

(PC-22377)[PRO] feat: log filters on new algolia search

---

pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersInstitutionList/OffersInstitutionList.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OldOffersSearch.tsx
pro/src/pages/AdageIframe/app/components/SurveySatisfaction/SurveySatisfaction.tsx
pro/src/pages/AdageIframe/app/components/SurveySatisfaction/__specs__/SurveySatisfaction.spec.tsx

…or each env
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22637
Ticket sur adage : SOUS FF `WIP_ENABLE_SATISFACTION_SURVEY`
sauvegarder l'information en back lorsque l'utilisateur ferme l'enquête de satisfaction afin de qu'il ne l'a voit plus jamais

(PC-22637)[PRO] feat: survey satisfaction close iwth api call

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/offer_metadata.py
api/tests/core/offers/test_models.py
api/tests/core/offers/test_offer_metadata.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22144
Pour la structure, on est parti sur :
- Un produit ou événement
- Qui contient une offre [AggregateOffer](https://schema.org/AggregateOffer), avec un prix minimal, parce que c'est la seule information accessible depuis la webapp en mode déconnecté.

(PC-22144)[API] feat: Include price info in offers metadata

---

api/src/pcapi/core/finance/api.py

The dependent pricing that we would like to delete could already have
been cancelled. In that case, its event has been cancelled, too. If
so, we should not change the event status to `READY`. This can happen
when the booking has been marked as unused.

(BSR)[API] fix: Fix `_delete_dependent_event_pricings` functions

---

pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
pro/cypress/support/commands.ts
pro/cypress/support/index.d.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23361
Ajout des tests e2e pour le parcours d'inscription
[Capture vidéo du 02-08-2023 17:14:26.webm](https://github.com/pass-culture/pass-culture-main/assets/106379750/71ee7c62-a379-4472-bffa-f7e68f37c5af)
Il y a 2 tests qui se suivent:
- La création d'une structure avec un compte
- Un autre utilisateur qui renseigne le même SIRET, qui est redirigé vers la page de rattachement, mais qui choisit de créer sa structure.
- Le cas où l'utilisateur se rattache n'est pas pris en compte, car cette partie sera bientôt supprimée.

(PC-23361)[PRO] test: add e2e for signup journey

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230621T192232_49e118a9dd48_rm_collective_offer_ispublicapi.py
api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/educational/validation.py
api/src/pcapi/routes/public/collective/endpoints/offers.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_collective_api_provider.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
api/tests/routes/pro/get_all_collective_offers_test.py
api/tests/routes/pro/get_collective_offer_test.py
api/tests/routes/pro/patch_collective_offer_test.py
api/tests/routes/pro/patch_collective_stock_test.py
api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_public_offerer_test.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_public_provider_test.py
api/tests/routes/public/collective/endpoints/post_collective_offer_public_offerer_test.py

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21550
Suppression de la colonne `isPublicApi` de `collective_offer` : il faut dorénavant utiliser `provider`/`providerId` (si présent, cela correspondait au cas `isPublicApi == True` et à `isPublicApi == False` sinon).
Deux commits : un premier pour nettoyer le code, un second pour la migration.
La colonne est supprimée et transformée en propriété car le front en a encore besoin. On considère donc `isPublicApi` vaut True si l'offre (collective) a un `providerId`.

PC-21550 rm is public api

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23713
Fix le comportement du bouton voir plus d'offres de la liste des offres algolia 
Explication : la fonction refineNext ne semble pas fonctionner associé à un searchState défini dans InstantSearch (ce dernier bloque la page=1 ce qui empèche d'afficher plus de résultats)

(PC-23713)[PRO] fix: fix load more button

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230804T143314_b5652ab2625c_add_provider_url_column.py
api/src/pcapi/core/providers/models.py
api/src/pcapi/routes/backoffice_v3/providers/blueprint.py
api/src/pcapi/routes/backoffice_v3/providers/forms.py
api/src/pcapi/routes/backoffice_v3/templates/layouts/connected.html
api/src/pcapi/routes/backoffice_v3/templates/providers/get.html
api/tests/routes/backoffice_v3/providers_test.py

Add 2 columns to Provider table and to the create and edit form in backoffice_V3 "Synchronisation partenaires techniques"
bookingExternalUrl -> url to call when a booking is made 
cancelExternalUrl -> url to call to cancel a booking
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23030

(PC-23030)[API] feat: Add provider url columns for new booking API

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/backoffice_v3/titelive/blueprint.py
api/tests/routes/backoffice_v3/titelive_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23711
Après le rejet du 22 aout, si on décide de whitelister un produit le lendemain, on réactive les offres précédemment désactivées pour cet EAN.

(PC-23711)[API] fix: approve cgu rejected offers on whitelisting

---

api/README.md
api/src/pcapi/scripts/install.py

Ajouter les commandes de pcapi/core/users/commands.py à Flask
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23359

PC-23359 add users commands

---

pro/.storybook/main.ts

BSR
ça fixe storybook en local, 
mais je me demande si on devrait pas passser le param à False plutôt j'ai l'impression qu'on s'en sert pas
https://storybook.js.org/docs/react/writing-docs/autodocs

(BSR)[PRO] fix: storybook

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/ContactButton.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23651
Ajouter le queryId pour les différentes routes de tracking Adage : 
- Evénement de pré-réservation
- Evénement de contact
- Evénement de like
- Evénement de click sur le détail d'une offre

(PC-23651)[PRO] feat: add queryId to adage tracking events

---

api/src/pcapi/routes/adage_iframe/logs.py
api/src/pcapi/routes/adage_iframe/serialization/logs.py
api/tests/routes/adage_iframe/post_logs_test.py
pro/src/apiClient/adage/index.ts
pro/src/apiClient/adage/models/AdageBaseModel.ts
pro/src/apiClient/adage/services/DefaultService.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
pro/src/pages/AdageIframe/app/components/SurveySatisfaction/SurveySatisfaction.tsx
pro/src/pages/AdageIframe/app/components/SurveySatisfaction/__specs__/SurveySatisfaction.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23287
Logger l'information que l'utilisateur à ouvert le questionnaire de satisfaction sur Adage
FF à activer : WIP_ENABLE_SATISFACTION_SURVEY

Pc 23287 eac add tracker for satisfaction survey

---

pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx
pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/__specs__/ReimbursementFields.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23435
- Ne pas afficher la section "Coordonées bancaires" si le FF WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY est activé.

(PC-23435)[PRO] feat: hide ReimbursementPoint component if FF is active

---

.github/workflows/build-and-push-docker-images.yml
.github/workflows/build-on-tags.yaml
.github/workflows/reusable--build-and-tag.yml

Utiliser les runners self-hosted afin de contourner un souci sur les runners docker-cache.

(BSR) use self hosted runner in ci

---

api/src/pcapi/connectors/dms/models.py
api/src/pcapi/core/fraud/factories.py
api/src/pcapi/core/fraud/models.py
api/tests/core/subscription/dms/test_api.py
api/tests/routes/external/user_subscription_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22706
Le but est de
- formater dans la BDD les valeurs de `registration_datetime` dans les dossiers DMS (on passe en UTC).
- faire le formatage à l'écriture dans la BDD à partir de maintenant
Un petit [ticket](https://passculture.atlassian.net/browse/PC-23703) suivra pour changer la fonction `get_registration_datetime`qui n'aura plus de raison de parser la valeur.
Le script ne sera pas mergé.

PC-22706 Parse DMS registration_datetime

---

.github/workflows/build-and-push-docker-images.yml
.github/workflows/build-on-tags.yaml
.github/workflows/reusable--build-and-tag.yml

La cause de nos soucis de stockage est identifiée, nous pouvons repasser sur ces runners plus malins.

(BSR)ci: use docker-cache runner for docker build jobs

---

api/src/pcapi/scripts/offer/fill_product_and_offer_ean.py

Product and Offer jsonData column can contain null, "null" (as string) or a json object, nowadays null value is an empty object : {}.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22748

(PC-22748)[API] fix: script to delete isbn

---

api/src/pcapi/routes/backoffice_v3/offers/blueprint.py
api/tests/routes/backoffice_v3/offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23484
Le filtre sur le statut de l'offre impliquait une jointure caché (property). Donc à l'ajout d'un filtre supplémentaire lui aussi incluant une jointure sur le stock, une erreur survenait

(PC-23484)[BO] Fix advanced search on offer status

---

pro/yarn.lock

Ticket Jira (ou description si BSR) : update du yarn.lock suite à un comportement de type _edge case_ de dependabot
cf. https://passcultureteam.slack.com/archives/C04MZ0AKC0P/p1691683400077299?thread_ts=1691679131.475889&cid=C04MZ0AKC0P

(BSR)[PRO] build: update yarn.lock file

---

pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/__specs__/ReimbursementFields.spec.tsx

Corriger le test "should display pricing point section when venue has no siret" de ReimbursementFields.spec.tsx

(BSR)[PRO] fix: reimbursementField test

---

api/src/pcapi/domain/password.py
api/tests/domain/password_test.py
api/tests/routes/pro/post_change_password_test.py
api/tests/routes/pro/signup_pro_V2_test.py
api/tests/routes/pro/signup_pro_test.py
api/tests/routes/shared/post_new_password_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21161
Modification des messages d'erreur liés au mot de passe :
```
"Ton nouveau mot de passe est identique à l’ancien." → “Le nouveau mot de passe est identique à l’ancien.”
"Votre mot de passe actuel est incorrect" → “Le mot de passe actuel est incorrect.”
"Ton mot de passe doit contenir au moins :\n" → “Le mot de passe doit contenir au moins”
```

(PC-21161)[PRO] refactor: wording email errors

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230810T101608_72fa9c444b5a_add_finance_incident_to_action_history.py
api/src/pcapi/core/history/api.py
api/src/pcapi/core/history/models.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/backoffice_v3/finance/blueprint.py
api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get/details.html
api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get/details/history.html
api/tests/routes/backoffice_v3/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23566
Ajout de l'historique dans la page incident
- Deux types d'actions ajoutées : création et annulation d'incident
- A la création de l'incident, le commentaire dans l'historique est l'origine de la demande

(PC-23566)[BO] feat: Add history to finance incident detailed page

---

pro/src/core/OfferEducational/utils/buildDatetimesForStockPayload.ts
pro/src/screens/OfferIndividual/StocksEventCreation/form/onSubmit.ts
pro/src/screens/OfferIndividual/StocksEventEdition/StockFormList/StockFormList.tsx
pro/src/screens/OfferIndividual/StocksEventEdition/adapters/serializers.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23823
_ Fixer un bug sur l'enregistrement pour les timzone à l'ouest, la date était fixée un jour avant
Pour tous les fuseaux à l'ouest une journée était décrémentée 
on faisait un new Date('2023-11-12') interprété par Date comme une date à minuit -> avec le décalage horaire elle était fixé à un jour avant
en envoyant tous les paramètres new Date(year, month, day) -> new Date nous renvoit bien le jour qu'on veut
pour tester : mettre sa machine sur un fuseau horaire en moins une ou plus d'heure, essayer de modifier un stock event, la date du jour ne change pas
_ onChange date de début : enlever une feature cassé (aucune idée de comment la réparer) 
en gros quand on tape 1, 2 ou 3 dans le champ date la date …

(PC-23823)[PRO] fix: error in timezone for stockEvents serialization

---

api/src/pcapi/core/permissions/models.py

Ceci évite les erreurs quand on bisect car le role en bdd n'existe pas dans notre enum

(BSR)[API] fix: permissions can be missing

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/external_bookings/exceptions.py
api/src/pcapi/core/external_bookings/serialize.py
api/src/pcapi/core/providers/repository.py
api/src/pcapi/routes/native/v1/bookings.py
api/src/pcapi/routes/native/v1/offers.py
api/tests/core/bookings/test_api.py
api/tests/routes/native/v1/bookings_test.py

Add a call to an external API in case it is configured in the provider when a user book an offer
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23606

(PC-23606)[API] feat: call external API if a stock is linked to a provider

---

api/src/pcapi/core/fraud/models.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23703
Suite de cette [PR](https://github.com/pass-culture/pass-culture-main/pull/7619).

PC-23703 no more parsing in get registration datetime

---

pro/yarn.lock

fix yarn lock that breaks update-api-client workflow

(BSR)[PRO] fix: yarn lock

---

pro/src/ui-kit/form/MultiSelectAutoComplete/MultiSelectAutocomplete.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23844
- Corriger le problème affichant une Stack Trace à l'utilisateur si celui-ci écris un caractère qui spécial utilisé par les regex.
Le problème à été corrigé pour le le SelectAutocomplete avec ce ticket PC-23636.
En revanche, il a été déplacé sur le MultiSelectAutocomplete.

(PC-23844)[PRO] fix: MultiSelectAutocomplete stack trace

---

api/src/pcapi/core/fraud/models.py
api/src/pcapi/core/fraud/ubble/constants.py
api/src/pcapi/core/subscription/ubble/models.py
api/src/pcapi/routes/internal/e2e_ubble.py
api/tests/routes/native/v1/openapi_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23883
Supprimer `BLURRY_VIDEO` qui est maintenant remplacé par `BLURRY_DOCUMENT_VIDEO` suite à l'exécution du [script de transition](https://github.com/pass-culture/pass-culture-main/pull/7756).

(PC-23883)[API] chore: Remove blurry_video from FraudReasonCodes

---

api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/external_bookings/boost/client.py
api/src/pcapi/core/external_bookings/cds/client.py
api/src/pcapi/core/external_bookings/cgr/client.py
api/src/pcapi/core/external_bookings/ems/client.py
api/src/pcapi/core/external_bookings/models.py
api/src/pcapi/utils/cinema_providers.py
api/tests/core/offers/test_api.py
api/tests/utils/cinema_providers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23524
Utiliser `str` pour  `film_id` récupérer à partir de `Offer.idAtProvider` pour supporter les ids alphanumériques.

(PC-23524)[API] feat: Cinema Syncho use str as return type for get film id from uuid insted of int

---

pro/src/components/Dialog/ConfirmDialog/__specs__/ConfirmDialog.spec.tsx
pro/src/screens/Desk/ButtonInvalidateToken/__specs__/ButtonInvalidateToken.spec.tsx
pro/src/screens/Desk/__specs__/Desk.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23953
Ajouter les tests pour le bouton Invalider la contremarque de la page Guichet.

Pc 23953 add test for desk invalidate button

---

api/src/pcapi/core/offerers/validation.py
api/tests/core/offerers/test_api.py
api/tests/routes/pro/patch_venue_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-23956

(PC-23956)[API] fix: venue name and siret should not be editable from pro account

---

api/src/pcapi/routes/pro/offerers.py
api/src/pcapi/routes/serialization/offerers_serialize.py
api/tests/routes/pro/post_offerer_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/PostOffererResponseModel.ts
pro/src/apiClient/v1/services/DefaultService.ts
pro/src/pages/Offerers/OffererCreation/__specs__/OffererCreation.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23845

(PC-23845)[API] fix: Return only name and siren when create offerer

---

api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/pro/get_offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23907
La serialization des dates de stock dans getOffers ne se faisait plus en utc suite à une refacto -> correction + test

 (PC-23907)[API] fix: date stock serialization in get offers 

---

pro/src/components/AdageButtonFilter/AdageButtonFilter.tsx
pro/src/components/AdageButtonFilter/__specs__/AdageButtonFilter.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23759
Affichage des dialogs en décalé pour rentrer à 100% dans l'écran. Par ex ici le dropdown lié au bouton Catégorie ne s'ouvre pas aligné à gauche du bouton mais décalé pour entrer à 100% dans la largeur du document.
A noter :
- On utilise la largeur du document et pas de la window parce qu'on est dans une iframe sur ADAGE
- J'ai choisi d'utiliser un state de décalage qui re-render le component quand la modal s'ouvre (donc double render à chaque ouverture), plutôt que mettre à jour l'attribut HTML de la modal directement dans le useEffect. Je trouve ça plus dans la logique React mais je peux me tromper.
Pour reproduire : 
- Activer le FF "WIP_ENABLE_NEW_ADAGE_FILTERS"
- Commenter le "max-width: 80%" dans …

(PC-23759)[PRO] open dialog modals within screen

---

pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx
pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/__specs__/FormParticipants.spec.tsx
pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/useParticipantsOptions.ts
pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23858
Pour reproduire : 
- Créer une offre collective réservable -> la checkbox "Tous les niveaux" ne devrait pas apparaître
- La checkbox devrait toujours apparaître sur les offres vitrines

(PC-23858)[PRO] hide all participants checkbox in bookable offer

---

pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.module.scss
pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx
pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23311
Il faut le FF **`WIP_ENABLE_NEW_USER_OFFERER_LINK`**
Status -> Statut
Espacement entre le séparateur de la section et “email” : 24px → 16px
Espacement entre titre “Ajout de collaborateurs” et texte : 16px → 8px
Espacement entre texte “Vous pouvez ajouter…” et composant Adresse email : 16px → 24px
Plus de 5 lignes de collaborateurs → le CTA “Voir plus” n’apparait pas
- [ X] J'ai ajouté des screenshots pour d'éventuels changements graphiques

(PC-23311)[PRO] fix: ui returns and add display all members button

---

pro/src/pages/Signup/SignupContainer/SignupForm.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23782
Nous avions oublié d'ajouter le hook à la page d'inscription pour focus l'utilisateur sur le premier champ avec une erreur.

(PC-23782)[PRO] fix: add scroll and focus to first error in signup

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230822T181748_1112f930c271_add_new_value_to_collectivebookingcancellationreasons_enum.py
api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/routes/backoffice_v3/collective_bookings.py
api/src/pcapi/routes/public/collective/endpoints/bookings.py
api/tests/routes/public/blueprint_v2_openapi_test.py
api/tests/routes/public/collective/endpoints/bookings_test.py
pro/src/apiClient/v1/models/CollectiveBookingCancellationReasons.ts
pro/src/apiClient/v2/services/ApiOffresCollectivesService.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23774
Nouvelle route pour l'API publique collective : annuler une réservation collective.
La fonction chargée de l'annulation est celle qui a été développée pour le backoffice.
Je me suis permis de renommer cette fonction puisqu'avec cette PR, celle-ci peut-être appelée par plusieurs types de clients (internes via le backoffice, ou externes via l'api publique).

(PC-23774)[API] feat: public api: cancel collective booking

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230821T133120_0801acf4c79d_booking_finance_incident_nullable_beneficiary.py
api/src/pcapi/core/finance/factories.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/routes/backoffice_v3/finance/blueprint.py
api/src/pcapi/routes/backoffice_v3/finance/validation.py
api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html
api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get/details.html
api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get/details/bookings.html
api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get/details/collective_bookings.html
api/src/pcapi/routes/backoffice_v3/templates/finance/incident/list.html
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
api/tests/routes/backoffice_v3/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23784
- Ajout de la création d'incident depuis une réservation collective
- Le champ 'montant de l'incident' est désormais toujours enable qu'il s'agisse d'un trop perçu ou d'un trop perçu partiel (le process étant exactement le même pour les deux)
- Création d'un fichier dédié à la validation, certaines logiques se répétaient et devenant gourmandes en place
- Création/adaptation des tests
- Passage du champ bénéficiaire d'un booking incident à nullable + ajout d'une contrainte (champ nécessaire si concerne une réservation individuelle)
- Ajout de l'information "montant remboursé à l'acteur" (sans doute mieux pour avoir une idée de montant à saisir pour l'incident)
- Ajout de la validation du montant (en …

(PC-23784)[BO] feat: Collective booking incident creation

---

api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/routes/public/collective/endpoints/bookings.py
api/tests/routes/public/collective/endpoints/bookings_test.py

Fix : envoyer deux emails lorsqu'une réservation collective est annulée via l'api collective. L'un à l'enseignant et l'autre à l'acteur culturel.

(BSR)[API] fix: public API: cancel booking: send emails

---

pro/src/components/StocksEventList/stocksFiltering.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24012
même problème qu'avant, le new Date mettait la date un jour avant
fix en faisant new Date(year, month, day)

(PC-24012)[PRO] fix: stock filtering by date in western timezone

---

pro/src/core/Bookings/utils.ts
pro/src/screens/Bookings/Bookings.tsx
pro/src/screens/OfferIndividual/StocksEventEdition/StockFormList/StockFormList.tsx
pro/src/screens/OfferIndividual/StocksEventEdition/adapters/serializers.ts
pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx
pro/src/screens/OfferIndividual/StocksThing/adapters/serializers.ts
pro/src/utils/date.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24056
5 bugs:
- serialization de la recherche des reservations -> inutile de passer en UTC maintenant (on envoit la bonne date au back)
- StockEventEdition : serialization de bookingLimitDatetime (même problème qu'avant pour les UTC - qqch on enregistré un jour avant)
- StockEventEdition :  calcul de la maxDate possible de bookingLimitDate -> on indiquait un jour trop tôt
- StockThing, bookingLimitDate, serialization (enregistrmeent un jour avant)
- StockThing, bookingLimitDate, calcul de maxDate

(PC-24056)[PRO] fix: timezone resrvations & Stocks limit date

---

api/src/pcapi/routes/public/individual_offers/v1/products.py
api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py

This can be done because there is a unique key (the ean) to find an offer. There shouldn't be 2 offers with the same EAN.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23856

(PC-23856)[API] feat: allow provider to edit offers from other providers

---

api/src/pcapi/routes/adage_iframe/authentication.py
api/src/pcapi/routes/adage_iframe/security.py
api/src/pcapi/routes/adage_iframe/serialization/adage_authentication.py
api/tests/routes/adage_iframe/get_authenticate_test.py
api/tests/routes/adage_iframe/utils_create_test_token.py
pro/src/apiClient/adage/models/AuthenticatedResponse.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24132
Renvoyer les coordonnées de l'établissement du rédacteur de projet ou du chef d'établissement lors de l'authentification. Ces informations sont contenues dans le JWT généré par Adage.

(PC-24132)[API] feat: adage iframe: return lat&lon from JWT auth token

---

api/src/pcapi/routes/pro/offerers.py
api/src/pcapi/routes/serialization/offerers_serialize.py
api/tests/routes/pro/post_save_new_onboarding_data_test.py
pro/src/apiClient/v1/services/DefaultService.ts
pro/src/screens/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx

Ticket Jira : https://passculture.atlassian.net/browse/PC-24140

(PC-24140)[API] fix: Return only name and siren when a user asks for attachment using new onboarding

---

.github/workflows/build-on-tags.yaml

Il semble qu'enlever la section output face planter le job : https://github.com/pass-culture/pass-culture-main/actions/runs/6036129729

(FIX) fix build-on-tags ci

---

pro/src/core/FirebaseEvents/constants.ts
pro/src/pages/Home/Offerers/OffererDetails.tsx
pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24015
- Ajout d'un tracker au clic sur le bouton "Inviter" de la page d'accueil.
- FF à activer: WIP_ENABLE_NEW_USER_OFFERER_LINK

(PC-24015)[PRO] feat: add tracker in offerer for invite member button

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/models.py
api/tests/routes/pro/post_stocks_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24137

(PC-24137)[API] fix: keep bookings ongoing when stock is no longer free 

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py

Litterally the same commit that f188be39b8e542537d0335954c3733cb1b26b33b but moving the snippet upper in the execution so that bug won't happen either in `_get_pricing_point_link`

(BSR)[API] fix: Handle bookings recently marked as unused

---

api/src/pcapi/core/bookings/repository.py
api/src/pcapi/routes/public/booking_token/v2/endpoints.py
api/tests/core/bookings/test_repository.py

`find_by()` used to accept optional arguments. Since the deletion of
the "API contremarque v1" (4877abe3795a30cfdd27), the usage is much
simpler. In fact, we can move the function next to the routes that use
it, and thus avoid having a "core" function that raises an 404 error.

BSR)[API] refactor: Get rid of `bookings.repository.find_by()`

---

api/src/pcapi/routes/backoffice_v3/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice_v3/pro_users/blueprint.py
api/src/pcapi/routes/backoffice_v3/venues/blueprint.py

En haut des pages de détails pro dans le backoffice, la barre de recherche revient sur « Structure » par défaut au lieu de garder le type de l'objet affiché.

(BSR)[BO] fix: default pro search type in backoffice pro details pages

---

pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.module.scss
pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24040
Fix la taille et la couleur de l'icone dans le suivi dms d'un lieu. 
Pour voir cette étape : 
- Edition d'un lieu avec adageId et date d'ajout dans adage depuis plus de 30 jours
- Lieu correspondant dans la sandbox accepted_dms eac_complete_30+d
| Avant  | Après |
| ------ | ------ |
| ![image](https://github.com/pass-culture/pass-culture-main/assets/71768799/2c9b0902-086a-43f5-bc05-a0c5a95d9612) | ![Capture d’écran 2023-09-07 à 08 49 18](https://github.com/pass-culture/pass-culture-main/assets/71768799/584deafa-c337-46a6-ac35-ab18a6c74e77) |

(PC-24040)[PRO] fix: set icon size in color for added in adage step

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24244
Ajout d'un critère de tri supplémentaire pour les résultats de recherche Algolia. 
Désormais les offres seront affichées selon les règles d'importance suivantes : 
1. la date de création (paramètre défini dans algolia)
2. le type d’intervention : il faut d’abord afficher les acteurs qui proposent des sorties dans leur lieux. Ce qui correspond au filtre de recherche “sortie chez un partenaire culturel” et à la case “dans votre lieu” ou “autre” dans la création d’offre.

(PC-24244)[PRO] feat: add weight to event address type in algolia search

---

.github/update-jira-issues.sh
.github/workflows/update-jira-issues.yml

Renommer les pas beau "OPS" dans Jira. L'impact est ddonc ici de modifier les tests d'une action github et d'un sh utilisant, à tord, un libellé.

(BSR) modify_issue_type_for_infra_team

---

api/src/pcapi/scripts/rebuild_staging/anonymize.sql
api/src/pcapi/settings.py

Mettre l'url du mock de l'api charlie dans la sandbox testing et dans le script d'anonymization en staging
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24023

(PC-24203) set charlie booking and cancel url for ehp

---

api/src/pcapi/core/users/api.py
api/tests/core/users/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24202

(PC-24202)[API] feat: Send reset password email when unsuspending user suspended for suspicious login

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/search/backends/algolia.py
api/tests/core/search/test_serialize_algolia.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23864
Fix : les coordonnées utilisées lors de l'indexation des offres collectives (et offres vitrines) étaient celles de l'adresse de facturation. Or, à la création de l'offre, un acteur culturel peut spécifier un lieu dans lequel aura lieu celle-ci : les informations sont dans la colonne `offerVenue` et sous la clé `venueId` (qui sera nulle si l'information n'a pas été fournie à la création).
Cette PR vise à donc à aller chercher ce lieu si l'information existe et utiliser le lieu qui sert pour la facturation dans le cas contraire.

(PC-23864)[API] fix: search: collective offers _geoloc

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/studentsOptions.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24119
**FF à activer :**
- WIP_ENABLE_ADAGE_GEO_LOCATION
- WIP_ENABLE_NEW_ADAGE_HEADER
- WIP_ENABLE_NEW_ADAGE_FILTERS
**Objectif :**
Revue de l'interface et des interactions des filtres adage.
**Réalisation :**
- Réorganisation des options dans le select Niveau Scolaire pour avoir Collège et Lycée avant CAP. Création d'une prop `sortOptions` dans le multiselect donnant une fonction de sort et ainsi éviter le tri par défaut qui impose un ordre alphabétique des options invalide dans le cas du Niveau Scolaire.
- Pour le multiselect de localisation (avec sous menu), ajout d'une condition dans le `onReset` pour ne pas fermer la modal dans ce cas. Ainsi la modal reste ouverte mais son contenu devient le choix des …

(PC-24119)[PRO] review adage filters

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230803T154405_1f3334d5aee5_add_new_validation_status_user_offerer.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/factories.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/core/offerers/repository.py
api/src/pcapi/models/validation_status_mixin.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/templates/components/badges.html
api/tests/core/offerers/test_api.py
api/tests/core/offerers/test_models.py
api/tests/routes/backoffice/offerers_test.py
api/tests/routes/pro/signup_pro_test.py

Lors d'un rejet ou la suppression d'un compte pro rattaché à une structure, on garde dorénavant en base de données la relation afin d'afficher ce rejet dans la liste des comptes Pro. 
Le statut de relation passe à REJECTED ou DELETED. 
Un log d'action de rejet ou suppression est rattaché sur le compte pro.
Changement validé par la Data.
Ticket Jira : https://passculture.atlassian.net/browse/PC-23045

(PC-23045)[API] feat: Preserve user-offerer link when user is rejected

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/public/collective/endpoints/venues.py
api/src/pcapi/routes/public/individual_offers/v1/products.py
api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/src/pcapi/routes/public/serialization/venues.py
api/tests/routes/public/blueprint_v2_openapi_test.py
api/tests/routes/public/collective/endpoints/get_collective_offers_venues_test.py
pro/src/apiClient/v2/index.ts
pro/src/apiClient/v2/models/GetOffererVenuesResponse.ts
pro/src/apiClient/v2/models/GetOfferersVenuesQuery.ts
pro/src/apiClient/v2/models/GetOfferersVenuesResponse.ts
pro/src/apiClient/v2/models/OffererResponse.ts
pro/src/apiClient/v2/services/ApiOffresCollectivesService.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24145
Ajouter une route `offerer_venues` à l'api publique collective.
Le but est d'avoir les deux mêmes routes côtés apis individuelle et collective. En attendant de les unifier un jour...

(PC-24145)[API] feat: add offerer_venues to collective api

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/finance/api.py
api/tests/core/bookings/test_api.py
api/tests/core/finance/test_api.py
api/tests/core/offers/test_api.py

Commits à relire séparément.
Le 3ème commit a un test qui échoue (et que j'ai donc commenté). C'est un problème dû à `pytest_flask_sqlalchemy` : il introduit plein de SAVEPOINT (qui n'existe pas hors des tests), donc le ROLLBACK revient au dernier SAVEPOINT (surnuméraire), au lieu de revenir au premier BEGIN. Concrètement, dans ce test, on ne rollbacke pas jusqu'au bon endroit. En réalité, quand j'exécute le code du test dans une session Python hors des tests, tout fonctionne : le ROLLBACK se fait correctement.

(BSR)[API] fix: Fix `_cancel_booking()` when booking is already used

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/external_bookings/exceptions.py
api/tests/core/bookings/test_api.py

Cette PR a pour but de catcher l'erreur si on essaie d'annuler un billet et que l'api externe renvoie une erreur parceque le billet est déjà annulé.
On log l'erreur pour avoir une trace (ça reste un comportement anormal) et on ne renvoie pas d'erreur afin de bien noter le booking cancelled en bd.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24127

(PC-24127) catch error if cancel ticket api returns error for already cancelled ticket

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/constants.py
api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/external_bookings/boost/client.py
api/src/pcapi/core/external_bookings/cds/client.py
api/src/pcapi/core/external_bookings/cgr/client.py
api/tests/core/bookings/test_api.py

Appeler l'api de billeterie externe afin d'annuler tout billet non relié à une réservation dans note base de données
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24149

(PC-24149): cancel barcodes with unstored external booking

---

api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/tests/local_providers/titelive_things_test.py

Titelive envoie des produits avec gtl_id < 8 caractères, or, nous avons besoin de nous baser sur les 2 premiers caractères pour connaitre la catégorie.
Ticket Jira : https://passculture.atlassian.net/browse/PC-23762

(PC-23762)[API] fix: Titelive does not add zeros to the left on GTL id

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230912T153108_b09c37d295a9_add_notification_external_url_column_to_provider_table.py
api/src/pcapi/core/providers/models.py
api/src/pcapi/routes/backoffice/providers/blueprint.py
api/src/pcapi/routes/backoffice/providers/forms.py
api/tests/routes/backoffice/providers_test.py

Ajouter la colonne notification external url à la table provider:
Cette url va être appelée avec les données de la réservation lorsqu'un jeune effectue une réservation ou à chaque annulation de réservation
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24394

(PC-24394)[API] feat: add notification external url column to provider

---

pro/src/hooks/useNewIndividualOfferType.ts
pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx
pro/src/pages/Offers/__specs__/Offers.spec.tsx
pro/src/screens/OfferType/OfferTypeIndividual/OfferTypeIndividual.tsx
pro/src/screens/OfferType/OfferTypeIndividual/__specs__/OfferTypeIndividual.spec.tsx
pro/src/screens/OfferType/__specs__/OfferType.navigation.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24381
- implem de l'AB testing pour le hub individual offer
-> le paramètre PRE_SELECTED_CATEGORIES est récupéré de firebase remoteConfig

(PC-24381)[PRO] feat: implement AB testing for new individual hub

---

api/src/pcapi/routes/serialization/offerers_serialize.py
pro/src/apiClient/v1/models/GetOffererResponseModel.ts

dsToken can be null until the field is populated

(BSR)[API] fix: testing homepage

---

api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/tests/routes/public/individual_offers/v1/get_event_dates_test.py

Code inutile depuis la migration des tarifs des offres évènements.

(BSR)[API] fix: delete event price retrocompatibility code

---

.github/workflows/build-on-tags.yaml

Actuellement le job build-on-tags.yaml s'exécutent à chaque push alors qu'il ne doit être joué que sur les tags de release.

(BSR)[CI]: Limit build-on-tags to tag only

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/domain/pro_offers/offers_recap.py
api/src/pcapi/routes/backoffice/finance/blueprint.py
api/src/pcapi/routes/public/individual_offers/v1/bookings_serialization.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/core/offers/test_models.py
api/tests/routes/pro/get_offer_test.py
pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
pro/src/screens/OfferIndividual/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.edition.spec.tsx
pro/src/utils/apiFactories.ts

Ajout d'une propriété `isActivable` sur les offres pour informer le front qu'une offre n'est plus activable en cas de suppression d’une synchronisation
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23772

(PC-23772)[API] feat: add isActivable on Offer

---

api/.env.integration

Ne pas faire d'appels d'API vers Zendesk Sell dans l'environnement integration

(BSR) fix: do not call Zendesk Sell in integration env

---

pro/src/pages/Offerers/Offerer/OffererDetails/OffererDetails.tsx
pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx
pro/src/screens/VenueForm/VenueFormScreen.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24280
- Cacher le dmsToken sur la page des lieux avec le FF `WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY` activé

(PC-24280)[PRO] feat: Hide venues dmsToken from venue page with FF enabled.

---

api/src/pcapi/algolia_settings_collective_offers.json
pro/package.json
pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx
pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx
pro/src/pages/AdageIframe/app/components/OffersForInstitution/__specs__/OffersForMyInstitution.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.module.scss
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx
pro/yarn.lock

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24115
Afficher des suggestions de lieux dans la barre de recherche Adage. 
**Subtilité tech :** 
On ajoute dans la config algolia un attributeForDistinct pour grouper les offres par lieux lors de la proposition de suggestions. Il faut donc désactiver ce paramètrage pour les autres recherche (`distinct=false`)
FF à activer : WIP_ENABLE_SEARCH_HISTORY_ADAGE

(PC-24115)[PRO] feat: add venue suggestions for adage autocomplete

---

api/src/pcapi/core/subscription/api.py
api/tests/core/subscription/test_api.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24193
L'update de la date de naissance lors d'une vérification d'identité se base toujours sur l'éligibilité de l'utilisateur à un upgrade.
Seulement maintenant, on se base sur la date actuelle de l'utilisateur et non plus sur celle reçue par le fournisseur d'identité.

(PC-24193)[API] fix: Change condition for birth date update

---

pro/src/components/SkipLinks/SkipLinks.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24224

(PC-24224)[PRO] fix: skipLinks should always be left side

---

pro/src/components/MultiDownloadButtonsModal/MultiDownloadButtonsModal.module.scss
pro/src/ui-kit/Button/Button.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23990
Avant
Après

(PC-23990)[PRO] fix: Boutons - adapter la hauteur quand le texte passe sur 2 lignes

---

pro/src/ui-kit/form/shared/FieldError/FieldError.tsx
pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23778
Toujours afficher une div, même vide pour les erreurs des input

(PC-23778)[PRO] feat: role alert for input error

---

api/src/pcapi/core/search/__init__.py
api/src/pcapi/core/search/commands/indexation.py
api/src/pcapi/scripts/full_index_offers.py
api/tests/core/search/test_api.py
api/tests/core/search/test_commands_indexation.py
api/tests/core/search/test_serialize_algolia.py

Changer le calcul des réservations des 30 derniers jours si l'offre a un ean. Dans ce cas on prend en compte les résas nationales.
Exposer une commande flask pour réindexer les offres concernées (chaque jour)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23439

Pc 23439 calculate last bookings count by ean

---

api/src/pcapi/routes/serialization/offerers_serialize.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24280
- Rajout du prefix "PRO" pour les dsToken pour les offerers aussi.

(PC-24280)[API] fix: Handle dsToken prefix for offerers.

---

pro/src/screens/OfferIndividual/Informations/Informations.tsx
pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.RouteLeavingGuard.spec.tsx
pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.creation.spec.tsx
pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.draft.spec.tsx
pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.edition.spec.tsx
pro/src/screens/OfferType/OfferType.tsx
pro/src/screens/OfferType/__specs__/OfferType.spec.tsx
pro/src/screens/OfferType/types.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23937
- ne pas préselectionner de choix de catégorie dans le hub
- ajouter sous-categorie dans tracking du hub
- ajouter sous-categorie dans tracking création offre (page information)
- appeler postProFlags quand on utilise la feature

(PC-23937)[PRO] feat: tracking ab testing individual offer

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/search/backends/algolia.py

What we send to Algolia when reindexing an offer does not depend on
`Venue.criteria` or contact data (e-mail, website, etc.). Thus,
changing these characteristics of a venue should not trigger a
re-indexation of the offers of this venue.

(BSR)[API] perf: Do not reindex offers when venue criteria or contact data change

---

api/src/pcapi/core/search/__init__.py
api/src/pcapi/scripts/full_index_offers.py
api/tests/core/search/test_api.py

Corriger une erreur sur master: une fonction non existante est appelée dans full_reindex_offers

(BSR)[API] fix: fix error on full_index_offers. Use same logis as reindex_offer_ids

---

api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/bookings/models.py
api/src/pcapi/core/external/commands/update_sendinblue_pro_attributes.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/repository.py
api/src/pcapi/core/fraud/api.py
api/src/pcapi/core/history/models.py
api/src/pcapi/core/offerers/repository.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/offers/repository.py
api/src/pcapi/core/providers/api.py
api/src/pcapi/core/providers/commands.py
api/src/pcapi/core/search/__init__.py
api/src/pcapi/core/subscription/ubble/archive_past_identification_pictures.py
api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/models.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/offerers/validation_repository.py
api/src/pcapi/scripts/subscription/dms/handle_deleted_dms_applications.py

Depuis Sqlalchemy 1.4, certaines fonctions ont été renomées
cf. https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-8dd50c1cc4d512bf97b23fb0243619af
Petite PR facile pour renomer chez nous

Bsr update sqla deprecated fields names (#5429)

---

api/src/pcapi/repository/repository.py

These except clauses were useful before Pydantic was used. Now
Pydantic should validate most input and we should very rarely
get an exception when calling `commit()`. If an exception is
raised, it's probably because we forgot to validate input and
we should fix that.
Once errors are logged and then fixed, we'll know if we can remove
this error handling (or maybe move it to route error handlers).

(BSR)[API] feat: Add logs in `repository.save` on error

---

api/src/pcapi/alembic/script.py.mako

Apparently, my previous comment was not clear enough.

(BSR)[API] docs: Clearer comment in docstring of Alembic migration file template

---

api/src/pcapi/core/offers/models.py

limiter le nombre maximal de stocks à créer à 2500 afin de ne pas surcharger algolia qui n'accepte que 100ko de données
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24285

(PC-24285)[API] feat: limit number of stocks per offer to 2500

---

pro/src/pages/Home/Venues/Venue.tsx
pro/src/pages/Offers/utils/queryParamsFromOfferer.ts
pro/src/screens/OfferType/OfferType.tsx
pro/src/screens/OfferType/__specs__/OfferType.navigation.spec.tsx

BSR
réparer erreur sur les urls : 
- `&numerique=undefined` ou `&numerique=null` pas très beau et inutilisé
- `&offer-type=` quand il n"y en a pas besoin
+ petite refacto de l'url de création d'offre indiv

(BSR)[PRO] fix: remove errors in url

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230920T150335_2edee580308f_delete_event_qrcode_and_new_venue_pages_ff.py
api/src/pcapi/core/offers/validation.py
api/src/pcapi/models/feature.py
api/src/pcapi/routes/native/v1/settings.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_validation.py
api/tests/routes/native/v1/settings_test.py

Suppression des FF PRO_DISABLE_EVENTS_QRCODE et ENABLE_NEW_VENUE_PAGES
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24357

(PC-24357)[API] refactor: delete event qrcode and new venue pages ff

---

api/src/pcapi/routes/backoffice/templates/layouts/connected.html

Corriger une permission permettant de voir les liens vers les partenaires techniques dans le menu du backoffice

(BSR)[BO] fix: permission to see tech partners items in menu

---

api/src/pcapi/core/external/attributes/api.py
api/src/pcapi/core/subscription/ubble/archive_past_identification_pictures.py

The comment says: "Watch logs to find errors during archive". Well,
there won't be much to watch if we don't log anything...

(BSR)[API] feat: Log errors in `archive_past_identification_pictures()`

---

api/src/pcapi/routes/native/v1/api_errors/account.py
api/src/pcapi/serialization/decorator.py
api/tests/serialization/serialization_decorator_test.py

Routes that expected a non-empty body raised an HTTP 500 error when
the client did not send the proper "Content-Type: application/json"
HTTP header. Now these routes return a 400.
---
Exemples d'erreur, actuellement : 
- https://sentry.passculture.team/organizations/sentry/issues/425963
- https://sentry.passculture.team/organizations/sentry/issues/426748
---
... et 1 commit supplémentaire de nettoyage au passage.

(BSR)[API] fix: Return HTTP 400, not 500, when content-type is not JSON

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230906T130321_aae5aa12b1c1_update_finance_event_constraints.py
api/src/pcapi/core/bookings/api.py
api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/domain/reimbursement.py
api/src/pcapi/routes/backoffice/finance/blueprint.py
api/src/pcapi/routes/backoffice/finance/validation.py
api/tests/core/finance/test_api.py
api/tests/routes/backoffice/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24002
- Création d'événements de finance lors de la validation d'un incident.
- Adaptation de `_price_event()` permettant de valoriser un `FinanceEvent`, pour prendre en charge les incidents
- Adaptation du modèle `FinanceEvent` pour pouvoir le lier à un `FinanceIncident`

(PC-24002)[BO] feat: incident finance events

---

api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/utils.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23801
Annule la PR https://github.com/pass-culture/pass-culture-main/pull/8211 car le nombre de résultats n'est pas satisfaisant : `.limit(100)` s'applique sur les lignes renvoyées par postgresql avec les jointures, ce qui est parfois loin de faire 100 offres (parfois seulement 4).
Une autre solution sera trouvée mais dans l'attente, _hotfix_ de retour en arrière pour la prochaine MEP.
On garde cependant, dans un commit séparé, les améliorations/restaurations de tests auto.
Le premier commit est strictement l'annulation de celui de la PR 8211.
Le second commit remet exactement tout le contenu du fichier de test de ladite PR.
Rien d'autre nouveau.

(PC-23801)[BO] revert: fix timeout when using advanced search in individual offers

---

api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/pro/get_all_collective_offers_test.py
api/tests/routes/pro/get_collective_offer_test.py
api/tests/routes/pro/get_offers_test.py
pro/src/apiClient/adage/models/AdageHeaderLink.ts
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/CollectiveOfferDisplayedStatus.ts
pro/src/apiClient/v1/models/ListCollectiveOffersQueryModel.ts
pro/src/apiClient/v1/models/ListOffersQueryModel.ts
pro/src/apiClient/v1/services/DefaultService.ts
pro/src/pages/CollectiveOffers/adapters/getFilteredCollectiveOffersAdapter.ts
pro/src/pages/Offers/adapters/getFilteredOffersAdapter.ts
pro/src/screens/CollectiveOfferVisibility/CollectiveOfferVisibility.tsx
pro/src/screens/OldCollectiveOfferVisibility/OldCollectiveOfferVisibility.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-PC-24392
Les valeurs attendues pour le filtre semblent avoir changé.
Cette PR vient utiliser l'enum qui correspond aux valeurs auxquelles s'attend le portail pro.
Les fonctions de filtres utilisent un statut de type str au lieu d'un enum, je n'ai pas creusé plus.

PC-24392-fix_status_filter(API) fix: portail pro: réparer le filtre des statuts des offres

---

pro/src/components/CollectiveOfferSummary/components/CollectiveOfferVenueSection/CollectiveOfferVenueSection.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24572
Dans la page récap d'une offre le nom du lieu n'est pas affiché si le nom publique est vide alors que dans ce cas on devrait affiché la raison sociale.

(PC-24572)[PRO] fix: display venue name if venue has no public name

---

pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx
pro/src/screens/IndividualOffer/StocksEventCreation/__specs__/StocksEventCreation.spec.tsx
pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
pro/src/screens/IndividualOffer/constants.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24638
limiter la création de stocks à 2500

(PC-24638)[PRO] feat: limit MAX_STOCKS_PER_OFFER to 2500

---

api/src/pcapi/core/users/api.py
api/tests/routes/backoffice/users_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24503

(PC-24503)[BO] fix: remove backoffice profile and roles when a PC user is suspended

---

api/src/pcapi/core/providers/commands.py

Commande déjà approuvée dans [ma dernière PR](https://github.com/pass-culture/pass-culture-main/pull/8162) et recettée à travers `pc -e staging python`. Je l'ai retirée de la PR parce que ce n'est pas une commande à vocation à être appelée plusieurs fois. Je la rajoute parce qu'elle est tellement longue (48h) qu'il faut pouvoir la `disown`.
Les EANs déjà présents en base de données ne sont pas réécrits mais juste loggés.
Ce commit sera revert une fois la commande exécutée.

(PC-24089)[API] feat: temporarily add import titelive music csv command

---

.github/workflows/release--build-hotfix.yml

Les sourcemaps n'étaient pas uploadés sur Sentry lorsque la release est un hotfix et que c'est l'env de production... un oubli dans la config.

(BSR)[PRO] fix: Sentry sourcemaps release for hotfixes

---

api/src/pcapi/routes/public/individual_offers/v1/events.py
api/tests/routes/public/individual_offers/v1/post_event_test.py

Permettre la création d'evennement in_app indépendamment du FF
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24509

(PC-24509)[API] feat: allow create in app event with disabled FF

---

api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/routes/adage_iframe/serialization/offers.py
api/src/pcapi/routes/public/collective/serialization/offers.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/tests/routes/adage_iframe/get_collective_offer_test.py
pro/src/apiClient/v1/models/GetOffererBankAccountsResponseModel.ts
pro/src/apiClient/v1/models/ManagedVenues.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24654
1. Ne plus permettre d'avoir des venueId égaux à "" pour collective_offer.offerVenue->>venueId lors de la création.
2. Gérer les données existantes en transformant les "" en None lors de la sérialisation.

(PC-24654)[EAC] fix: collectiveOffer.offerVenue->>venueId ne devrait jamais être égal = ""

---

api/tests/routes/adage_iframe/get_collective_offer_test.py

L'appel à assert_no_duplicated_queries n'était pas nécessaire et aurait dû
être supprimé.

(BSR) fix: rm assert_no_duplicated_queries call

---

helmfile.yaml

Ticket Jira: https://passculture.atlassian.net/browse/PC-24641
Afin de pouvoir migrer vers le nouveau load balancer avec cloud armor, nous devons déployer des nouveaux ingress qui utilisent la nouvelle ingress class qui est exposé par le load-balancer global.

(PC-24641)[pcapi]: Bump chart version for cloud armor migration on staging, perf, ops

---

api/src/pcapi/routes/adage_iframe/logs.py
api/src/pcapi/routes/adage_iframe/serialization/logs.py
api/tests/routes/adage_iframe/post_logs_test.py
pro/src/apiClient/adage/index.ts
pro/src/apiClient/adage/models/SuggestionType.ts
pro/src/apiClient/adage/models/TrackingAutocompleteSuggestionBody.ts
pro/src/apiClient/adage/services/DefaultService.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24516
LIEN VERS LE JIRA : https://passculture.atlassian.net/jira/software/c/projects/PC/boards/67/backlog?view=detail&selectedIssue=PC-24516&issueLimit=100
demande métier : Tracker à chaque fois que l’enseignant sélectionne un élément de la suggestion et distinguer quel type de suggestion.

(PC-24516)[API] feat: log tracking autocompletion

---

api/src/pcapi/core/mails/__init__.py
api/src/pcapi/core/mails/backends/base.py
api/src/pcapi/core/mails/backends/logger.py
api/src/pcapi/core/mails/backends/sendinblue.py
api/src/pcapi/core/mails/backends/testing.py
api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/templates/components/public_accounts/registration_steps.html
api/src/pcapi/tasks/serialization/sendinblue_tasks.py
api/tests/core/mails/tests.py

2 commits à relire séparément (+ 1 commit de correction de typo),  qui traite de la même chose.
Accepter une liste ou `None` est fastidieux. On doit alors gérer ces 2 types (notamment quand on souhaite itérer, compléter, etc.). N'accepter qu'une liste (et jamais `None`) rend la manipulation plus simple. On pourra toujours envoyer une liste vide si l'on ne veut pas de valeur. (Dans cette PR, il n'y a pas d'intérêt à distinguer `None` d'une liste vide.)

(BSR)[API] Typage : Passage des arguments de type liste/séquence nullable en liste/séquence normale

---

api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py
api/tests/routes/backoffice/helpers/post.py
api/tests/routes/backoffice/users_test.py

Petite correction suite à une erreur Sentry rencontrée sur testing, liée à https://passculture.atlassian.net/browse/PC-24503

(PC-24503)[BO] fix: AttributeError after an admin user is supended 

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py
api/src/pcapi/routes/backoffice/templates/multiple_offers/search_result.html
api/tests/core/offers/test_api.py
api/tests/routes/backoffice/multiple_offers_test.py

Sur la page Opérations sur plusieurs offres : 
Changement de la manière de calculer isCguCompatible en prenant l'ean d'un seul et unique produit
Affiche la notion isSynchronisableCompatible
Ticket Jira : https://passculture.atlassian.net/browse/PC-24258

(PC-24258)[BO] feat: display isSynchronisableCompatible

---

pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/StocksQueryModel.ts
pro/src/apiClient/v1/services/DefaultService.ts

BSR
la ci n'a plus l'air d'updaté l'api client automatiquement en attendant j'ai lancé la commande à la main
https://github.com/pass-culture/pass-culture-main/actions/runs/6325619218/job/17178721349
```
$ ./scripts/generate_api_client_local.sh
{
stack: 'ResolverError: Error downloading http://localhost/v2/openapi.json \n' +
'socket hang up\n' +
'    at /runner/_work/pass-culture-main/pass-culture-main/pro/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js:127:16',
code: 'ERESOLVER',
message: 'Error downloading http://localhost/v2/openapi.json \nsocket hang up',
source: 'http://localhost/v2/openapi.json',
path: null,
toJSON: [Function: toJSON],
ioErrorCode: 'ECONNRESET',
name: 'ResolverError',
footprint: 'null+http://localhost/v2/openapi.json+ERESOLVER+Error downloading …
```

(BSR)[PRO] fix: realign open api client

---

.github/workflows/tests-api.yml
.github/workflows/tests-main.yml

Before this commit, on a push event on the "master" branch, we always
built and deployed the backend (API), whether or not the "api" folder
was changed, and whether or not the backend tests were successful.
Now the "deploy-to-testing" step requires backend tests to be
successful (or skipped if the backend code did not change).
Also, we now deploy the backend only if it has changed. Ditto for the
frontend.
Finally, we do not need the "build-api" step anymore, since
"tests-api" already builds a Docker image.

(BSR)[API] ci: Check backend (API) tests before deploying on testing

---

api/src/pcapi/core/offers/exceptions.py
api/src/pcapi/routes/public/individual_offers/v1/events.py
api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/tests/routes/public/individual_offers/v1/get_event_test.py
api/tests/routes/public/individual_offers/v1/patch_event_test.py
api/tests/routes/public/individual_offers/v1/post_event_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24670
We had 4 tickets withdrawal types, we only want API users to create offers without tickets or offers linked to their stocks through charlie api.

(PC-24670)[API] feat: only allow in_app (ie: charlie API) or no_tickets offers for individual offer API

---

api/src/pcapi/routes/adage_iframe/offers.py
api/tests/routes/adage_iframe/get_collective_offer_template_test.py
api/tests/routes/adage_iframe/get_collective_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24770
Bug: suite à l'ajout du champ isFavorite dans la réponse des offres
collectives et vitrines, seuls les rédacteurs de projet pouvaient accéder à
ces ressources.
Pour savoir si l'offre a été mise en favori par l'utilisateur, on va le
chercher en base données puis on regarde s'il a l'offre en favori ou non.
Le problème est que les utilisateurs (authentifiés) ne sont pas toujours des
rédacteurs de projets et n'ont donc pas toujours un compte en base. Et l'on
répondait, à tort, avec une erreur 403.
J'ai ajouté deux commits : 
le premier pour corriger une faute dans le nom d'une fonction de fixture.
le second pour ajouter une petite _refacto_.

(PC-24770)[ADAGE] fix: permettre aux non-rédacteurs de projets de voir des offres

---

api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
api/src/pcapi/core/external_bookings/cds/client.py
api/tests/core/external_bookings/cds/test_client.py

Code (including typing annotations) is clearer that way.

(BSR)[API] refactor: Make `CineDigitalServiceAPI.get_hardcoded_setmap()` return a list, not JSON

---

pro/src/components/IndividualOfferForm/UsefulInformations/TicketWithdrawal/__specs__/TicketWithdrawal.spec.tsx
pro/src/components/IndividualOfferForm/UsefulInformations/TicketWithdrawal/constants.ts

https://passculture.atlassian.net/browse/PC-24612
Modifier l'intitulé de la 4ème option de modalité de retrait:
Branche: PC-24612-style-retrait

(PC-24612)[PRO] feat: ajout label et direction d'affichage ON_SITE

---

api/src/pcapi/utils/image_conversion.py
api/tests/utils/image_conversion_test.py

J'en ai profité pour *inline* une fonction qui n'était utilisée qu'à
un seul endroit. **Il y a donc 2 commits, à relire séparément.**
Je n'ai pas ajouté de test pour la correction du bug (la gestion du
SyntaxError) car je n'ai pas réussi à reproduire. Mais c'est un vrai
bug qu'on voit [sur Sentry](https://sentry.passculture.team/organizations/sentry/issues/427666/events/0e2256250f5b4c1796f79dd1a1201014/?project=5).

(BSR)[API] fix: Handle SyntaxError thrown by PIL

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24662
On ne souhaite pas afficher la bannière de satisfaction sur adage si l'utilisateur connecté à le rôle READONLY

(PC-24662)[PRO] fix: satisfaction banner readonly

---

.github/workflows/deploy-pro-pr-version-generic.yml
.github/workflows/node-run-command.yml
.github/workflows/tests-pro.yml

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24761
Fix :
- idéalement il aurait fallu l'inverse, cache `~/.cache/yarn` et ne pas cache `node_modules` et rajouter `--prefer-offline` sur les commande `yarn install --immutable` 
- Mais pour une raison que j'ignore, le tar se passe pas bien avec le cache, et cela pose problème quand on récupère l'archive
- `node_modules` seul ne fonctionnait pas bien, pareil pour `pro/node_modules`, le contenu du dossier était vide, donc je remplace par `**/node_modules`
- pareil l'archive n'incluais pas les sous dossier autrement, et l'archive était ridiculement petite.

(PC-24761)[PRO] ci: fix use gcs runner cache

---

api/src/pcapi/core/fraud/models.py
api/src/pcapi/core/users/factories.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_app_users.py
api/tests/routes/backoffice/accounts_test.py
api/tests/sandboxes/scripts/create_industrial_app_users_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-24451

(PC-24451)[BO] fix: Underage Ubble identification should no longer be valid for Age-18 if not credited

---

api/src/pcapi/core/offerers/api.py
api/tests/routes/pro/post_save_new_onboarding_data_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24690
La validation automatique des structures en integration ne fonctionnait plus, semble-t-il, depuis le passage au nouveau parcours d'inscription.

(PC-24690)[PRO] fix: auto-validate offerer in integration environment

---

api/src/pcapi/scripts/install.py
api/src/pcapi/scripts/offer/fix_offer_data_titelive.py
api/src/pcapi/scripts/offer/fix_product_gtl_id_titelive.py

Une commande Flask corrige les gtl_id inférieur à 8 caractères pour les compléter avec des zéros à gauche.
Une commande Flask ajout les gtl_id, csr_id et code_clil des produits sur les offres qui n’en ont pas. Ça n'était pas automatiquement copié dans les premiers imports des produits Titelive, maintenant, c'est le cas.
L'intérêt d'utiliser des commandes Flask est que nous pourrons suivre les logs et donc l'avancement du rattrapage via GCP.
Ticket Jira : https://passculture.atlassian.net/browse/PC-23763

(PC-23763)[API] fix: Script copy 3 ids from product data to offer data

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
api/src/pcapi/scripts/rebuild_staging/anonymize.sql

ajout de la clé de chiffrement hmac au script d'anonimisation et aux données de la sandbox 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24719

(PC-24719) add hmac key to sandbox and decoding in mock api

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20230929T140843_ba42ea4318a0_patch_individual_offerer_subscription.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/backoffice/offerers/forms.py
api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/src/pcapi/routes/backoffice/templates/offerer/get/details/individual_subscription.html
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_individual_offerers.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_tags.py
api/tests/routes/backoffice/conftest.py
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-24788
En supprimant les champs demandés dans le ticket, petit rééquilibrage des colonnes :

(PC-24788)[BO] feat: In AE tab, use Adage tag instead of individual/collective switches

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py

The pricing ordering date cannot be based on the booking validation
date. That date is likely to be earlier than other bookings that
already have been reimbursed. The `price-financee-events` cron would
then fail because it would try to re-price later bookings and would
not be able to delete their pricings.
Instead, we should use the date of the validation of the incident
(which is the date of the creation of the event, and is thus safe to
use).
---
Le bug est visible dans ces 2 entrées Sentry sur staging : [ici](https://sentry.passculture.team/organizations/sentry/issues/428277/events/7408e19631d44abf88dadd3ff4aa9cc6/) et [là](https://sentry.passculture.team/organizations/sentry/issues/428277/events/db8cd621c6db43c48caca283085cdbef/).

(BSR)[API] fix: Fix `FinanceEvent.pricingOrderingDate` for finance incidents

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
pro/src/utils/__specs__/getDistance.spec.tsx
pro/src/utils/getDistance.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24210
Améliorer l'affichage des distances dans les offres Adage. On reprend le code utilisé côté jeune qui permet d'affiner l'affichage en fonction de la distance. 
[Lien du code côté jeune](https://github.com/pass-culture/pass-culture-app-native/blob/cb1f285d24cba635ca45be3bdf560a9d2bc5469f/src/libs/parsers/formatDistance.ts)
- Créer une offre réservable sur un lieu éligible adage (par ex `accepted_dms eac_complete_30+d`)
- Changer l'adresse de ce lieu pour ajuster la distance des différentes offres créées
- La localisation de l'utilisateur du collège robert doisneau est la suivante : (48.8566, 2.3522) Hotel de ville de Paris

(PC-24210)[PRO] feat: improve distance display in adage

---

.github/workflows/tests-pro.yml

BSR
les tests e2e semblent suffisemment stable maintenant, ils peuvent faire échouer la ci, 
motivé par un bug qu'un aurait vu plus tôt si ça avait été le cas : 
https://passculture.atlassian.net/browse/PC-24821

(BSR)[PRO] ci: e2e are stable enough they can make ci fail

---

api/src/pcapi/core/educational/validation.py
api/tests/routes/public/collective/endpoints/post_collective_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24847
La fonction de validation génère des ApiError en cas d'erreur... sauf dans un cas où une ValueError est générée. Cette dernière n'est pas gérée et cela se termine en erreur 500.
Ceci est un fix rapide, on pourrait (devrait ?) déplacer toute cette validation au niveau d'un modèle pydantic afin de se simplifier la vie et de laisser spectree/pydantic/flask gérer tous seuls les erreurs 400.

(PC-24847)[EAC] fix: ne pas générer un mélange d'ApiError et de ValueError

---

pro/src/pages/IndividualOfferWizard/__specs__/IndividualOfferWizard.spec.tsx
pro/src/screens/OfferType/__specs__/OfferType.spec.tsx

On a prévu de résoudre ces tests Flaky le 16 octobre avec Hugo lors de la journée de dette. En attendant, on skip, le taux d'echec de la CI est beaucoup trop élevé => faire attention sur ce composant (ou de-skip les tests en local quand on y touche) le temps qu'on corrige le test

(BSR)[PRO] fix: skip flaky tests

---

api/src/pcapi/routes/backoffice/forms/utils.py
api/src/pcapi/routes/backoffice/offerers/forms.py

Fix : Quand on a préservé le status supprimé sur le rattachement d'un pro à une structure, on a fait un effet de bord sur les statuts de validation d'une structure sur le BO.

(PC-23045)[BO] fix: validation status Offerer can't be DELETED

---

api/src/pcapi/routes/public/collective/endpoints/offers.py
api/tests/routes/public/collective/endpoints/get_collective_offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24850
Si l'offre collective n'a pas de provider, alors offer.provider.id génère une erreur ('NoneType' object has no attribute 'id').
Fix: accéder directement à l'id du provider.

(PC-24850)[EAC] fix: offer.providerId pas offer.provider.id

---

api/src/pcapi/workers/decorators.py
api/src/pcapi/workers/worker.py

En désactivant toutes les offres d'un lieu on a ces logs :
```
INFO:pcapi.flask_app:HTTP request at /offers/all-active-status
INFO:pcapi.core.offers.api:Batch update of offers
INFO:pcapi.core.offers.api:Offers has been deactivated
INFO:pcapi.workers.decorators:Enqueue job update_all_offers_active_status_job
```

(BSR)[API] feat: allow job.delay() calls in local environment

---

api/src/pcapi/alembic/versions/20230928T130528_14e9b22809ef_add_hmac_key_column_to_provider_table.py

The comment is shown when running `alembic history` (among other
places). Having more than one line makes the output hard to read:
$ alembic history
bdb5f7cdd367 -> 14e9b22809ef (pre) (head), Add hmac key column to provider table
This key will be used to sign the payload send to providers in charlie api
ef07f9582155 -> bdb5f7cdd367 (pre), Add column `experienceDetails` in individual_offerer_subscription table
Now it's clearer:
$ alembic history | head -n 2
bdb5f7cdd367 -> 14e9b22809ef (pre) (head), Add `provider.hmacKey` column
ef07f9582155 -> bdb5f7cdd367 (pre), Add column `experienceDetails` in individual_offerer_subscription table

(BSR)[API] style: Make Alembic migration 14e9b22809ef comment a one-liner

---

api/src/pcapi/core/users/api.py
api/tests/routes/shared/post_new_password_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24257

(PC-24257)[API] fix: Set User.validationToken to None when validte email after a password reset

---

api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/tests/routes/pro/get_collective_offer_test.py
api/tests/routes/public/collective/endpoints/get_collective_offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24885
Ne plus permettre d'avoir des venueId égaux à "" pour collective_offer.offerVenue->>venueId lors de la création.
Gérer les données existantes en transformant les "" en None lors de la sérialisation.
Il manquait le fix pour le portail pro dans la précédente PR : https://github.com/pass-culture/pass-culture-main/pull/8351

PC-24654: EAC: fix: collectiveOffer.offerVenue->>venueId ne devrait jamais être égal = "" (suite)

---

api/src/pcapi/models/feature.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24822
Ajouter un FF  `WIP_ENABLE_DATES_OFFER_TEMPLATE` pour activer l'ajout de dates pour les offres collectives vitrines.

(PC-24822)[API] feat: add ff for date in offer template

---

api/src/pcapi/routes/public/collective/endpoints/offers.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24904
Bug: lorsqu'un utilisateur essaie de mettre à jour une offre collective via l'API publique, si educationalPriceDetail est renseigné mais nul, tout plante (erreur 500) à cause d'une ValueError non gérée.
Le problème est que le contrôleur ajoute un champ priceDetail dont on sait quoi faire (c'est une colonne du stock collectif) uniquement si educationalPriceDetail n'est pas nul. Dans le cas contraire... la variable new_values dont on se sert pour tout mettre à jour utilise un champ educationalPriceDetail dont personne ne sait quoi faire et qui génère une ValueError.
Fix: toujours générer un priceDetail à partir du educationalPriceDetail.

(PC-24904)[EAC] API collective: fix: toujours mettre un priceDetail

---

api/src/pcapi/core/offers/models.py
api/src/pcapi/models/providable_mixin.py

Lorsqu'on lance mypy (v.1.5.1) en local, on a un bug dû à l'utilisation de @declared_attr 
C'est un bug de mypy > 1.4.0 documenté [ici](https://github.com/sqlalchemy/sqlalchemy/issues/10282)
Avec les modifications effectuées dans cette PR, on évite l'erreur lors des hooks de pre-commit 
(mais si on lance `mypy src/pcapi/workers`, ou n'importe quoi d'autre que `workers` qui ne soit pas `core`  le bug est toujours là)

(BSR) fix: internal error on mypy

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231004T192225_5f59d1bc65a3_add_custom_reimbursement_rule_amount_in_eurocents.py
api/src/pcapi/alembic/versions/20231004T193123_f72b113cfe59_populate_custom_reimbursement_rule_amount_in_eurocents.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/models.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_commands.py

`CustomReimbursementRule.amount` is the last model column where we
store euros and not eurocents. This commit is the first step in
storing eurocents in the `amount` column.
-> step 1: add `amountInEurocents` and write in both `amount` and
`amountInEurocents`. Also, populate `amountInEurocents`
for existing rows.
step 2: use `amountInEuroCents` column instead of `amount`.
step 3: store eurocents in `amount` column.
step 4: use `amount` column.
step 5: drop `amountInEuroCents` column.

(BSR)[API] refactor: Add `CustomReimbursementRule.amountInEurocents`

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24928
**Objectif**
Correction du bug suivant : quand on recherche par mot clé les offres adage, le cache des offres est affiché à la place d'afficher les offres reçues.
**A noter**
La syntaxe `.filter((offer): offer is HydratedOffer => !!offer)` semble nécessaire pour que typescript comprenne que les offers ne seront pas `undefined` dans le map du JSX. J'ai pas trouvé plus propre mais peut-être bien que c'est possible ?

(PC-24928)[PRO] fix: Fix dont display all cached adage offers.

---

api/src/pcapi/core/finance/factories.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/finance/blueprint.py
api/src/pcapi/routes/backoffice/finance/forms.py
api/src/pcapi/routes/backoffice/finance/validation.py
api/src/pcapi/routes/backoffice/templates/finance/incident/get/details/bookings.html
api/src/pcapi/routes/backoffice/templates/finance/incident/get/details/collective_bookings.html
api/src/pcapi/routes/backoffice/templates/finance/incident/get/general.html
api/src/pcapi/routes/backoffice/templates/finance/incident/list.html
api/tests/routes/backoffice/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24138
Correction du wording lors de la création de l'incident : 
- Le montant saisi est le montant à récupérer (vu avec Charline/Solène)
Correction de la valeur de `newTotalAmount` du modèle `BookingFinanceIncident`
Le `newTotalAmount` étant la nouvelle valorisation d'un booking, dans le cas d'un trop percu total sa valeur est de 0.

(PC-24138)[BO] fix: incident informations and partial incident pricing

---

pro/src/components/Breadcrumb/Breadcrumb.tsx
pro/src/components/Breadcrumb/__specs__/Breadcrumb.spec.tsx
pro/src/components/Breadcrumb/types.ts
pro/src/components/Callout/AddBankAccountCallout.tsx
pro/src/components/Callout/LinkVenueCallout.tsx
pro/src/components/Callout/PendingBankAccountCallout.tsx
pro/src/components/ReimbursementsBreadcrumb/ReimbursementsBreadcrumb.tsx
pro/src/components/ReimbursementsBreadcrumb/ReimbursmentsBreadcrumb.module.scss
pro/src/components/ReimbursementsBreadcrumb/constants.ts
pro/src/components/VenueForm/VenueForm.tsx
pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
pro/src/pages/Home/Venues/Venue.tsx
pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx
pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx
pro/src/pages/Reimbursements/BankInformations/BankInformations.module.scss
pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx
pro/src/pages/Reimbursements/BankInformations/__specs__/BankInformations.spec.tsx
pro/src/pages/Reimbursements/Reimbursements.tsx
pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24342
Ajouter un filtre sur la page informations-bancaires pour séléctionner une structure et mettre à jour les informations.
Activer le FF: WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY
url: remboursements/informations-bancaires

(PC-24342)[PRO] feat: add offerer filter for bank information

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offers_with_activation_codes.py

BSR
il manquait un user_offerer  pour les offres avec codes d'activation, le formaulaire d'offre ne s'affichait donc pas pour ce lieu

(BSR)[API] fix: add user_offerer in sandbox to match reality

---

api/src/pcapi/routes/backoffice/templates/accounts/get/general.html
api/src/pcapi/routes/backoffice/templates/admin/users_generator.html

Éviter l'affichage "Addresse None" comme sur cette capture d'écran :

(BSR)[BO] fix: avoid displaying "Address: None"

---

api/src/pcapi/repository/clean_database.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24979
to resolve bug https://sentry.passculture.team/organizations/sentry/issues/429061/?environment=testing&project=5&query=+server_name%3Adeploy-sandbox-%2A&statsPeriod=24h

(PC-24979)[API] fix: clean_all_database needed to delete CollectiveOfferEducationalRedactor and CollectiveOfferTemplateEducationalRedactor

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/exceptions.py
api/src/pcapi/local_providers/local_provider.py
api/src/pcapi/local_providers/provider_manager.py
api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/tests/core/offers/test_api.py
api/tests/local_providers/titelive_things_test.py

Quand un produit Titelive est rejeté pour cause d'incompatibilité avec les CGU, si le lendemain lors de la synchro de nuit (lecture du FTP), le produit est correct vis-à-vis des CGU, il faut le réactiver, les offres associés aussi.
Ticket Jira : https://passculture.atlassian.net/browse/PC-24752

(PC-24750)[API] feat: reapprove product and offers rejected for bad cgu

---

pro/src/ui-kit/form/shared/BaseInput/BaseInput.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24816
- Correction du style du bouton pour afficher le mot de passe qui a été cassé au passage du fichier `BaseInput.scss` en module.

(PC-24816)[PRO] style: Center the input button inside the input.

---

.github/workflows/check-folder-changes.yml
.github/workflows/tests-api.yml
.github/workflows/tests-main.yml

Objectif :
- quand un fichier du dossier `pro/` est modifié, on lance les tests
pro "classiques" (unit tests, qualité, etc.) et les tests pro
end-to-end
- quand un fichier du dossier `api/` est modifié, on lance les tests
backend (unit tests, qualité, etc.) et les tests pro end-to-end
Exemples d'exécutions des tests : 
- modification de "api" et de "pro" : https://github.com/pass-culture/pass-culture-main/actions/runs/6454946983?pr=8426
- modification de "api" seulement : https://github.com/pass-culture/pass-culture-main/actions/runs/6456456320?pr=8426
- modification de "pro" seulement : https://github.com/pass-culture/pass-culture-main/actions/runs/6456713579?pr=8426
- aucune modification (ni "api", ni "pro") : https://github.com/pass-culture/pass-culture-main/actions/runs/6456989756?pr=8 …

ci: Lancer seulement les tests nécessaires, selon les fichiers ("pro/" ou "api/") modifiés

---

api/src/pcapi/sandboxes/scripts/creators/data/create_data_offerers_with_pro_users.py

Some users literally had "{first_name}_data.xxx@xxx.xxx", where
`{first_name}` was not interpolated.

(BSR)[API] test: Fix some e-email addresses in data sandbox

---

api/src/pcapi/connectors/api_recaptcha.py
api/tests/connectors/api_recaptcha_test.py

The reCAPTCHA API sometimes returns a 50x response (or it may
timeout). These errors were not caught and we ended up serving a 500
error response.
Now we re-raise these errors as exceptions that are caught by the
caller and properly turned into a user-facing message that more or
less says: "try again".
---
Plus un commit de simplification de l'usage de `override_settings`, au
passage.

(PC-25009)[API] fix: Handle reCAPTCHA network errors

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231009T092610_631df26e514b_add_last_author_validation_or_rejection_on_collective_offer_table.py
api/src/pcapi/alembic/versions/20231009T092625_8347a72b24d0_add_last_author_validation_or_rejection_on_collective_template_offer_table.py
api/src/pcapi/alembic/versions/20231009T092805_654f1c1c4da3_add_last_author_validation_or_rejection_on_offer_table.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/educational/repository.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/src/pcapi/models/offer_mixin.py
api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py
api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py
api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/templates/collective_offer/details.html
api/src/pcapi/routes/backoffice/templates/components/links.html
api/src/pcapi/routes/backoffice/templates/offer/details.html
api/src/pcapi/routes/backoffice/templates/offer/list.html
api/src/pcapi/routes/backoffice/titelive/blueprint.py
api/src/pcapi/routes/public/individual_offers/v1/products.py
api/src/pcapi/scripts/reject_cgu_incompatible_offers.py
api/tests/core/offers/test_api.py
api/tests/routes/backoffice/collective_offer_templates_test.py
api/tests/routes/backoffice/collective_offers_test.py
api/tests/routes/backoffice/offers_test.py
api/tests/routes/backoffice/titelive_test.py
api/tests/routes/pro/patch_collective_offer_publication_test.py
api/tests/routes/pro/patch_collective_offer_template_publication_test.py
api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py

Crée une page avec le détail d'une offre individuelle avec un onglet stock et historique.
L'historique reprend l'auteur de la validation ou du rejet de l'offre.
Ticket Jira : https://passculture.atlassian.net/browse/PC-24436
Stocks :
Historique :

(PC-24436)[BO] feat: create individual offer detail page and store validation or rejection author

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231005T141351_385e5ea25130_add_debit_note_forcing_to_finance_incident.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/routes/backoffice/finance/blueprint.py
api/src/pcapi/routes/backoffice/finance/forms.py
api/tests/routes/backoffice/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24758
Ajout du choix sur la stratégie de compensation (récupération sur les prochains justificatifs OU génération d'une note de débit à la validation) dans la modale de validation d'un incident.
Enregistrement de ce choix dans un nouveau champ du modèle `FinanceIncident` nommé `forceDebitNote`. 
Cette donnée sera lu lors de la génération des documents de paiement, et donnera suite à la génération ou non d'une note de débit.
On peut également envisager un bouton annulant ce choix de génération d'une note de débit (en cas d'erreur utilisateur par exemple) passant ce champ à `False`.

(PC-24758)[BO] feat: Add debit note choice to incident validation

---

api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/templates/offer/details.html
api/tests/routes/backoffice/offers_test.py

Ajout un bouton sur le détail d'une offre pour resynchroniser l'offre dans algolia
Ticket Jira : https://passculture.atlassian.net/browse/PC-24623

(PC-24623)[BO] feat: button index offer in algolia from offer page

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/studentsOptions.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/utils.spec.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24964
Envoyer des valeurs compréhensibles par la data lors du tracking des filtres : 
- Pour les domaines : envoyer le label plutôt que l'id
- Pour le niveau scolaire, le parsing côté GCP semble détecter la valeur comme un float. On ajoute donc une table de correspondance pour simplifier la valeur envoyée. 
Changer le filtre `Domaines artistiques` ou `Niveau scolaire` dans l'iframe Adage, et regarder l'appel réseau `tracking-filter`

(PC-24964)[PRO] feat: send label instead of value for domains

---

.github/workflows/deploy.yml

Problème remontée dans le canal slack : https://passcultureteam.slack.com/archives/C01CTV65S3A/p1697094435850889
Cela devrait faire en sorte qu'une erreur lors des pre/post migrations plante la CI au lieu d'échouer silencieusement.
Exemple d'une commande qui fail hors du pod : https://github.com/pass-culture/pass-culture-main/actions/runs/6493126545/job/17633457397
Exemple d'une commande qui fail dans le pod : https://github.com/pass-culture/pass-culture-main/actions/runs/6493266593/job/17633881304

(BSR)[API] ci: fix silent error on db migrations

---

api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/tests/routes/public/individual_offers/v1/get_product_by_ean_test.py

No offer can be created without accessiblity with this API but a case can happen if a provider tries to get an old offer (from another provider and api) by ean.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25025

(PC-25025)[API] chore: public offer api - allow to return offer without accessibility

---

api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/core/finance/utils.py
api/src/pcapi/domain/reimbursement.py
api/tests/core/finance/test_models.py
api/tests/domain/reimbursement_test.py

Objectif : faire en sorte de toujours manipuler des centimes avant de
stocker `Pricing.amount`.
Changement précédé de 2 commits de simplification/clarification du
code et des tests.
Prochaine étape (dans une autre pull request, à venir après celle-ci)
: faire en sorte que `CustomReimbursementRuleTest.amount` soit un
montant en centimes et non plus en euros comme actuellement, par souci
d'homogénéité avec tous les autres montants stockés dans les modèles
de `core.finance`.

(BSR)[API] refactor: Make `ReimbursementRule.apply()` return eurocents

---

.github/workflows/tests-pro-e2e.yml

I have had a case where the step was still running after more than an
hour. Patience is a virtue... but if the server is not ready within 2
minutes, there is probably something wrong and the server is unlikely
to suddenly become available.
---
L'option `timeout` est en millisecondes, cf. [doc](https://github.com/marketplace/actions/wait-on#timeout).

(BSR)[PRO] ci: Add timeout when waiting for backend migrations in E2E pro tests

---

api/src/pcapi/repository/providable_queries.py
api/tests/core/bookings/test_api_race_condition.py

dnBookedQuantity inconsistencies appears during race condition between synchronize_.*_stocks
and booking of a user.
Specifically, when a booking on a stock occurs when its synchronization is in progress.
During the booking dnBookedQuantity is updated at its right value, and then, at the end of the
synchronization, dnBookedQuantity has is old value back (and Stock.quantity correctly updated)
What is happening:
-- Synchronization
Stock fetched quantity=10 and dnBookedQuantity=0
-- Booking
Stock fetched quantity=10 and dnBookedQuantity=0
dnBookedQuantity updated to 1
Stock is commited into DB with quantity=10, dnBookedQuantity=1
-- Synchronization
Quantity updated to 5
Stock is commited into BD with quantity=5, dnBookedQuantity=0
Corrige: …

(PC-24294)[API] fix: Handle stock race condition between booking and synchronization

---

api/src/pcapi/routes/backoffice/finance/blueprint.py
api/src/pcapi/routes/backoffice/finance/forms.py
api/tests/routes/backoffice/finance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25076
Quelques petits fix sur les incidents :
- Pouvoir saisir le montant avec une virgule
- Afficher le bon montant dans la popin de validation (et formater le montant)
- Afficher dans l'historique le choix de récupérer le montant sur les prochaines réservations

(PC-25076)[BO] fix: incident validation popin and amount field locale

---

api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/tests/local_providers/titelive_things_test.py

Quand on crée un product, `Product().isGcuCompatible` est None avant persistance puis True par défaut, on ne doit pas les considérer comme à approuver.
Remontée cette nuit en Staging : https://sentry.passculture.team/organizations/sentry/issues/437878/?project=5&referrer=slack
Ticket Jira : https://passculture.atlassian.net/browse/PC-24752

(PC-24752)[API] fix: [Titelive] product not found on product created

---

api/tests/core/mails/transactional/bookings/booking_confirmation_to_beneficiary_test.py
api/tests/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary_test.py

Tests were failing because the user's deposit expired yesterday,
forbidding the user to book. But in fact we don't really need
to use `freeze_time()` here.
If you're reading this in 2032 and the test fails because the event is
in the past: I'm sorry. Contact me and I'll apologize with a drink. :)

(BSR)[API] test: Remove unnecessary `freeze_time()`

---

api/src/pcapi/domain/demarches_simplifiees.py
api/tests/domain/demarches_simplifiees_test.py

Fields names can be covered by a naming convention and a mistake is easily fixed.
Fields ids change if a field is deleted/added which can’t be fixed.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24660

(PC-24660)[API] feat: Relying on DS fields names rather than their ids

---

api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/factories.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list.html
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_models.py
api/tests/routes/backoffice/custom_reimbursement_rules_test.py

`CustomReimbursementRule.amount` is one the last model columns (in
`core.finance`) where we store euros and not eurocents. This commit is
the second step in storing eurocents in the `amount` column.
```
step 1: add `amountInEurocents` and write in both `amount` and
`amountInEurocents`. Also, populate `amountInEurocents`
for existing rows.
-> step 2: use `amountInEuroCents` column instead of `amount`.
step 3: store eurocents in `amount` column.
step 4: use `amount` column.
step 5: drop `amountInEuroCents` column.
```

(BSR)[API] refactor: Use `CustomReimbursementRule.amountInEurocents`

---

api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/finance/factories.py
api/tests/core/educational/api/test_booking.py

The fix is similar to b91a9b1419feec67d81: the cancellation date of
the booking must have been set for `add_event()` to use it.
---
Ticket : https://passculture.atlassian.net/browse/PC-25129

(PC-25129)[API] fix: Fix `cancel_collective_booking()` when booking is used

---

api/src/pcapi/sandboxes/scripts/creators/data/create_data_event_stocks.py
api/src/pcapi/sandboxes/scripts/creators/data/create_data_thing_stocks.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_stocks.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_stocks.py

BSR
- bien utiliser StockEventFactory pour créer des StocksEvent
- j'en ai profité pour utiliser aussi  StockThingFactory pour les thing (dès fois que ça diverge)

(BSR)[API] fix: in sandbox data stocks event did not have priceCategory

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231012T160704_8425db0af4c1_add_start_end_interval_to_collective_offer_template.py
api/src/pcapi/core/educational/api/offer.py
api/src/pcapi/core/educational/exceptions.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/tests/routes/pro/patch_collective_offer_template_test.py
api/tests/routes/pro/post_collective_offers_template_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/DateRangeModel.ts
pro/src/apiClient/v1/models/DateRangeOnCreateModel.ts
pro/src/apiClient/v1/models/PatchCollectiveOfferTemplateBodyModel.ts
pro/src/apiClient/v1/models/PostCollectiveOfferTemplateBodyModel.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24579
Ajout de dates de début et de fin aux offres vitrines (collectives). Une offre vitrine ne peut pas avoir plus de 10 paires de dates et chacune doit au minimum avoir un début (la fin est optionnelle).
1. Petite refacto pour le champ `price_detail`/`priceDetail` dans les modèles _pydantic_.
2. Refacto des tests: ajout de _fixture_ pour supprimer du code dans les méthodes de tests, simplification de quelques tests, suppression d'un ou deux tests qui ne semblaient pas vitaux et difficiles à comprendre (que teste-t-on ? Quelle est la réelle différence avec le précédent ?), renommage de méthodes pour mieux faire ressortir le cas de test.

(PC-24579)[ADAGE] ajout de dates de début et de fin pour les offres vitrines

---

api/src/pcapi/routes/backoffice/providers/forms.py

Changer le nom du champs de la clé de chiffrement hmac pour éviter la confusion entre clé api et clé de signature

(BSR)[API] feat: change hmac key name on backoffice frontend

---

pro/src/pages/Offers/Offers/OfferItem/Cells/CollectiveOfferStatusCell/CollectiveOfferStatusCell.module.scss
pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingStatusCell.module.scss
pro/src/screens/Bookings/BookingsRecapTable/utils/BookingStatus.module.scss

Changer la couleur pour le status "préréservé" car le contraste jaune/blanc est peu visible dans la page offre collective et réservation collective
Avant : 
Après:

(PC-24605)[PRO] fix: booking and offer status pending change color

---

api/src/pcapi/core/offers/exceptions.py
api/src/pcapi/core/offers/validation.py
api/tests/core/offers/test_validation.py
api/tests/routes/pro/patch_offer_test.py

Dans cette PR on veut rendre possible de créer une offre avec un widthrawal type même si la sous catégories ne fait pas partie des WITHDRAWABLE_SUBCATEGORIES.
Ceci est fait parce que depuis l'api publique, un provider peut créer une offre avec un withdrawal type dans tous les cas, mais depuis le front, afin de simplifier le formulaire de création d'offer, on ne permet pas à l'utilisateur de selectionner le withdrawal type si l'offre n'est pas withdrawable.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25085

(PC-25085) should always be able to create offer with widthrawal type

---

pro/src/components/Notification/__specs__/Notification.spec.tsx

L'assert sur le get du texte de la notif n'a pas besoin d'être async, ce qui retarde l'assert et risque de le faire fail car la notif peut disparaitre

(BSR)[PRO] fix: remove async assert in notification test

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/serialize.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/core/offers/test_api.py
api/tests/routes/pro/get_stocks_stats_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/StockStatsResponseModel.ts
pro/src/apiClient/v1/services/DefaultService.ts

On veut créer une route GET pour stocks/<offer_id>/stocks-stats qui renvoie les données des stocks suivantes pour une offre : 
- beginningDatetime du stock le plus ancien
- beginningDatetime du stock le plus récent
- le nombre total de stock
- la quantité restante
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24417

(PC-24417)[API] feat: add route for stock stats

---

pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25257
Le lien vers le détail d'une offre collective depuis la liste des réservations ne fonctionnait pas. On ajoutait un T- devant l'id alors que toutes réservations collectives ne peut être lié qu'à une offre réservable et non vitrine (template)

(PC-25257)[PRO] fix: fix collective offer link in bookings

---

pro/src/pages/AdageIframe/app/App.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts
pro/src/pages/AdageIframe/app/providers/FacetFiltersContextProvider.tsx
pro/src/utils/__specs__/facetFilters.spec.ts
pro/src/utils/facetFilters.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25153
Ne plus avoir de valeur par défaut pour le filtre "Localisation des partenaires" sur adage
Avant le département de l'utilisateur connecté était automatiquement dans le filtre

(PC-25153)[PRO] feat: delete default value of localisation filter

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/src/pcapi/workers/update_stocks_job.py
api/tests/core/offers/test_repository.py
api/tests/routes/pro/delete_filtered_stocks_test.py
api/tests/routes/pro/get_stocks_test.py
pro/src/apiClient/v1/models/DeleteFilteredStockListBody.ts
pro/src/apiClient/v1/models/StocksQueryModel.ts
pro/src/apiClient/v1/services/DefaultService.ts

On veut que la route GET pour offer/<offer_id>/stocks nous renvoie 
- le nombre de stocks filtrés (ou le total des stocks dispo pour l'offre en question si on ne filtre pas les stocks)
- la liste des stocks paginés (+ filtrés le cas échéant)
Et dans la query GET, on rajoute le numéro de page & la limite par page
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24988

(PC-24988)[API] feat: update offer stocks route to show total stocks

---

api/src/pcapi/alembic/versions/20231012T160704_8425db0af4c1_add_start_end_interval_to_collective_offer_template.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/core/offers/api.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
api/src/pcapi/serialization/utils.py
api/tests/routes/pro/patch_collective_offer_template_test.py
api/tests/routes/pro/post_collective_offers_template_test.py

Ticket Jira d'origine (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24579
Les dates de débuts et de fin des offres vitrines ([ajoutées tout récemment](https://github.com/pass-culture/pass-culture-main/pull/8513)) n'acceptent pas les _datetimes_ sous forme de texte avec un Z à la fin (➡️ UTC).
Le problème est que l'on se retrouvait à comparer des _datetimes_ sans _timezone_ avec d'autres qui en ont, ce qui créé des erreurs. Ces comparaisons se font lors de la validation des dates (par exemple, le début ne doit pas être avant la fin).

(bsr) eac: fix offer template dates tz

---

pro/src/screens/OfferType/IndividualOfferType/IndividualOfferType.tsx
pro/src/screens/OfferType/OfferType.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25303
cassé à cause de ça
```
@media (min-width: size.$tablet) {
.form-layout {
&-row.inline-group {
flex-wrap: unset;
}
}
}
```
le flex-flow: wrap était écrasé
réparé en enlevant FormLayout.Row qui n'avait pas l'ai d'apporter grand chose ici
après :
avant :

(PC-25303)[PRO] style: fix subcategory choice in desk

---

pro/src/pages/Reimbursements/BankInformations/BankInformations.module.scss
pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24342

(PC-24342)[PRO] style: remove bank accounts section when no bank account and link position

---

pro/src/components/LegalInfos/LegalInfos.tsx

Enlever une info en double, comme on a indiqué dans l'intitulé du lien que le contact se fait par mail il n'est pas nécessaire d'avoir le alt sur le picto

(BSR)[PRO] fix: remove double label from icon

---

api/src/pcapi/routes/native/v1/authentication.py
api/src/pcapi/routes/pro/users.py
api/src/pcapi/routes/shared/passwords.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24624

(PC-24624)[API] refactor: remove support for old reset password token

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231018T075947_00c2e096a1ac_change_type_of_custom_reimbursement_rule_amount.py
api/src/pcapi/alembic/versions/20231018T082411_6025fbc18ebb_copy_custom_reimbursement_rule_amount_in_eurocents_to_amount.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/factories.py
api/src/pcapi/core/finance/models.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_commands.py

`CustomReimbursementRule.amount` is one the last model columns (in
`core.finance`) where we store euros and not eurocents. This commit is
the third step in storing eurocents in the `amount` column.
step 1: add `amountInEurocents` and write in both `amount` and
`amountInEurocents`. Also, populate `amountInEurocents`
for existing rows.
step 2: use `amountInEuroCents` column instead of `amount`.
-> step 3: store eurocents in `amount` column.
step 4: use `amount` column.
step 5: drop `amountInEuroCents` column.

(BSR)[API] refactor: Store eurocents in `CustomReimbursementRule.amount`

---

pro/package.json
pro/yarn.lock

BSR
retirer le warning critical de babel/traverse
https://github.com/advisories/GHSA-67hx-6x53-jw92
`yarn audit` pour vérifier

(BSR)[PRO] bump: babel/traverse

---

pro/src/ui-kit/form/EmailSpellCheckInput/EmailSpellCheckInput.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25357
Afficher le message d'erreur sous le champ email quand on quitte le champ en n'ayant encore rien saisi dedans

(PC-25357)[PRO] fix: display error message on email inscription field

---

api/src/pcapi/utils/image_conversion.py
api/tests/utils/image_conversion_test.py

Permet de résoudre l'`OSError`  qui est levée dans le cas où on crée une miniature à partir d'une image tronquée. 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25316

(PC-25316)[API] fix: error for truncated image

---

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx
pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23419
Avant la condition d'affichage était par rapport à bankAccount.isActive, sauf que dès qu'il est en construction, cette valeur est à True.
Maintenant, la condition se base sur le statut directement.

(PC-23419)[PRO] fix: display pending section in ReimbursementBankAccount when status is ongoing or on draft

---

api/src/pcapi/routes/public/individual_offers/v1/events.py
api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/tests/routes/public/individual_offers/v1/get_event_test.py
api/tests/routes/public/individual_offers/v1/patch_event_test.py
api/tests/routes/public/individual_offers/v1/post_event_test.py

use a boolean instead of null | dict
There is one user of this API that will be impacted. I sent him an email, he created free offers (without tickets), he will be able to handle this change.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24919

(PC-24919)[API] feat: event API simplify ticket field

---

pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplication.module.scss

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25048
Fix l'affichage des images par défaut pour les offres vitrines dans l'écran de duplication

(PC-25048)[PRO] fix: remove useless padding for offer image

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231023T155523_a98c6b643561_create_index_on_last_validation_author_fkey_on_offer_table.py
api/src/pcapi/alembic/versions/20231023T172057_00d812005230_create_index_on_last_validation_author_fk_on_collective_offer_table.py
api/src/pcapi/alembic/versions/20231023T204024_80ee25f3632d_create_index_on_last_validation_author_fk_on_collective_offer_template_table.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/models/offer_mixin.py

Quand on supprime un utilisateur, l'action de mettre à null la colonne lastValidationAuthor de la table offer nécessite de parcourir toute la table visiblement, c'est très couteux en production.
On a essayé de changer la clé étrangère, mais la solution la plus simple semble être l'index sur la clé étrangère.
L'index sera mis à la main en staging et production, d'où if not exists
Ticket Jira : https://passculture.atlassian.net/browse/PC-25337

(PC-25337)[BO] fix: add index on last validate author fk for delete user

---

api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/routes/pro/get_stocks_stats_test.py
pro/src/apiClient/v1/models/StockStatsResponseModel.ts
pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx
pro/src/screens/IndividualOffer/StocksSummaryScreen/StocksSummaryScreen.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/RecurrenceSection/RecurrenceSection.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/RecurrenceSection/__specs__/RecurrenceSection.spec.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/StockSection.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/StockThingSection/StockThingSection.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/StockThingSection/__specs__/StockThingSection.spec.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/__specs__/StockSection.spec.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/__specs__/getStockWarningText.spec.tsx
pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25414
API:
_ réparer serialization (camelCase + UTC)
PRO:
_ refacto summary  stocksThing (enlever des choses inutiles)
_ utilser getStats dans le summary Stock Event (on en a besoin dans le composant au dessus StockSection qui gère les messages d'erreur en cas de pas de stocks par exemple)

(PC-25414)[PRO/API] feat: use new route in event creation summary

---

pro/src/screens/IndividualOffer/StocksSummaryScreen/StocksSummaryScreen.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/StockSection.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/StockThingSection/StockThingSection.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/StockThingSection/__specs__/StockThingSection.spec.tsx
pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25414
-> réparer mon commit d'hier : certaines sous-catégories things peuvent bien être duo !!
exemple : ESCAPE_GAME, CARTE_MUSEE ou ABO_MUSEE
en création :
en édition :

(PC-25414)[PRO] fix: summary stock thing, some subcategories CAN be duo

---

api/src/pcapi/alembic/script.py.mako
api/src/pcapi/alembic/versions/20231025T015954_2a720f939c92_add_formats_to_collective_offers_and_templates.py

... et correction de la docstring d'une migration récente qui a ce problème.

(BSR)[API] docs: Mentionner que la docstring d'une migration doit tenir en une ligne

---

pro/src/screens/CollectiveOfferVisibility/CollectiveOfferVisibility.tsx
pro/src/screens/CollectiveOfferVisibility/__specs__/CollectiveOfferVisibility.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25421
Supprimer les suggestions d'enseignants quand on change d'établissement sur la page visibilité. 
Pour tester le seul établissement avec des enseignants en local est l'établissement avec l'uai 0470009E
[Description du bug avec vidéo ](https://www.notion.so/passcultureapp/New-bug-Staging-R-manence-du-r-sultat-de-recherche-d-un-prof-ff4b0ec2c7554bc2a7fd07eb08360b20)
**Screen de la page associée :**

(PC-25421)[PRO] fix: clear teacher suggestion on institution change

---

api/src/pcapi/core/educational/models.py
api/src/pcapi/routes/adage_iframe/serialization/offers.py

Fix : si `dateRange` est vide, `start` et `end` doivent renvoyer `None`.

(BSR)[EAC] fix: start/end dates only if dateRange not null

---

api/src/pcapi/routes/serialization/collective_offers_serialize.py
pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts
pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts
pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts

**Contexte**
Les offres collectives et vitrines ne sont plus obligées d'avoir des sous-catégories depuis https://github.com/pass-culture/pass-culture-main/pull/8641. Elles seront progressivement remplacées par des _formats_.
**Bug**
Certains modèles de réponse exigeaient encore une sous-catégorie (obligatoire) ce qui pose des soucis puisque la prochaine version du portail pro ne va plus renseigner de sous-catégorie mais directement des formats.

(BSR)[API] fix: missing: nullable subcategory

---

api/src/pcapi/connectors/dms/api.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/routes/backoffice/__init__.py
api/src/pcapi/routes/backoffice/bank_account/blueprint.py
api/src/pcapi/routes/backoffice/forms/search.py
api/src/pcapi/routes/backoffice/pro.py
api/src/pcapi/routes/backoffice/templates/bank_account/get.html
api/src/pcapi/routes/backoffice/templates/bank_account/get/history.html
api/src/pcapi/routes/backoffice/templates/bank_account/get/linked_venues.html
api/src/pcapi/routes/backoffice/templates/components/search/result.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card_bank_account.html
api/src/pcapi/routes/backoffice/venues/blueprint.py
api/src/pcapi/routes/backoffice/venues/serialization.py
api/tests/routes/backoffice/bank_account_test.py

Affiche le detail d'un compte bancaire, retrouvable via la recherche d'un acteur culturel.
L'onglet Remboursements n'a plus à faire, faute de nouveau modèle.
Ticket Jira : https://passculture.atlassian.net/browse/PC-24808
Page sans DMS:
Historique : 
Avec DMS :

(PC-24808)[BO] feat: add bank account detail page

---

api/src/pcapi/core/educational/api/booking.py
api/src/pcapi/core/finance/repository.py
api/tests/core/bookings/test_api.py
api/tests/core/bookings/test_validation.py
api/tests/core/finance/test_repository.py
api/tests/routes/backoffice/individual_bookings_test.py
api/tests/routes/public/booking_token/v2/get_booking_by_token_v2_test.py
api/tests/routes/public/booking_token/v2/patch_booking_keep_by_token_test.py
api/tests/routes/public/individual_offers/v1/get_booking_test.py
api/tests/routes/public/individual_offers/v1/patch_cancel_booking_by_token_test.py
api/tests/routes/public/individual_offers/v1/patch_validate_booking_by_token_test.py

1. Instances of Pricing have been generated for old-style Payment, we
don't need to look at Payment anymore.
2. Look at the status of the booking first. If it says "reimbursed",
no need to waste an SQL query to look at pricings.

(BSR)[API] refactor: Simplify `finance.repository.has_reimbursement()`

---

api/src/pcapi/scripts/check_pre_migrations.py
api/src/pcapi/scripts/install.py

This command checks that all pre-deployment migrations have been
applied. It will be used as a guard before deploying new code during a
deployment.
---
Démo :
```
$ alembic downgrade pre@-1
[...]
INFO  [alembic.runtime.migration] Running downgrade 2a720f939c92 -> 45372e34d18c, blablabla
$ flask check_pre_migrations
ERR: Missing pre-deployment migrations: last revision is 2a720f939c92, but database is at 45372e34d18c
$ echo $?
1
$ alembic upgrade pre@head
[...]
INFO  [alembic.runtime.migration] Running upgrade 45372e34d18c -> 2a720f939c92, blablabla
$ flask check_pre_migrations
OK
$ echo $?
0
```

(PC-25446)[API] feat: Commande Flask `check_pre_migrations`

---

pro/src/pages/Desk/__specs__/Desk.spec.tsx

On remplace un `await screen.findByText` qui n'est pas nécessaire par un `screen.getByText` => comme on ne wrap pas le expect dans une promesse celui-ci n'est pas retardé donc moins de risque de race condition

(BSR)[PRO] fix: improve test flakyness

---

api/src/pcapi/routes/public/individual_offers/v1/products.py

It seems that bigquery (or the way the data team uses it) cannot extract lists.
We changed that to have a string of eans separated by commas

(BSR)[API] fix: the data team can't extract data from a list

---

api/src/pcapi/core/educational/api/national_program.py
api/src/pcapi/routes/public/collective/endpoints/offers.py
api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24954
Lors de la mise à jour d'une offre collective, si l'identifiant du dispositif national est inconnu, une erreur survient et n'est pas gérée.
Cette PR propose un fix rapide mais il serait pas mal de remettre à plat ces différentes routes et trouver un moyen de mieux gérer ces différents types d'erreurs.

(PC-24954)[EAC] fix: pg error: handle foreign key error

---

api/src/pcapi/core/bookings/api.py
api/tests/routes/backoffice/individual_bookings_test.py

- en cas d’annulation d’une réservation avec code d’activation depuis le BO 
- modifier la liste des codes d’activation pour supprimer ce code d’activation
- modifier le stock de l’offre pour diminuer la quantité de 1 
Il peut donc arriver que le stock initial soit différent du stock final + réservation
-> suite aux discussions, on choisit de ne pas supprimer les codes d'activation afin de pouvoir garder une trace.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24105

(PC-24105)[API] fix: handle booking cancelation from BO 

---

pro/src/components/CollectiveOfferSummary/__specs__/CollectiveOfferSummary.spec.tsx
pro/src/components/CollectiveOfferSummary/components/CollectiveOfferTypeSection/CollectiveOfferTypeSection.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferSummary/OfferSummary.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24862
Afficher le format à la place de la sous-catégorie dans le résumé d'une offre collective après création/édition et sur les fiches d'offres sur Adage
FF à activer : WIP_ENABLE_FORMAT

Pc 24862 eac display format for collective offer

---

pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
pro/src/screens/IndividualOffer/StocksEventEdition/hasChangesOnStockWithBookings.ts
pro/src/screens/IndividualOffer/StocksEventEdition/submitToApi.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25428
quand on modifiait les stocks event on envoyait tous les stocks dans le payload,
on n'envoit plus que les stocks modifiés

(PC-25428)[PRO] refactor: only put only edited stocks event in payload

---

api/src/pcapi/algolia_settings_collective_offers.json
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/utils.spec.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24864
Ajouter le filtre formats dans les filtres adage. (Une fois le FF activé on affiche plus le filtre sous-catégorie)
FF à activer : `WIP_ENABLE_FORMAT`

(PC-24864)[PRO] feat: add formats adage filter

---

api/pyproject.toml

Résoud le bug de l'utilisation de _mypy_ avec version > 1.4 dû à l'utilisation de @declared_attr
La doc [mypy](https://passcultureteam.slack.com/archives/C063RA5LS6A/p1698917043797779) là dessus:
```
self.preserve_asts = False
```
On a fait un test sur la taille du cache _mypy_ qui est passé de 60Mo à 69Mo (sans augmenter ensuite lorsqu'on modifie des fichiers dans src/ )

(BSR) fix: set preserve-asts to true to fix local mypy bug

---

api/src/pcapi/core/search/backends/algolia.py

Finalement, un seul `type: ignore` en moins.
Les résultats sont forcément des str, mais il faut un peu l'expliciter à mypy, si je ne m'abuse.

(BSR)[API] refactor: more explicit str type in algolia serialization

---

api/tests/core/mails/transactional/users/ubble_ko_reminder_test.py

Le test `should_notify_users_after_sending_an_email` était flaky. On utilise maintenant des `set` pour comparer les listes d'ids.

(BSR)[API] fix: make test for ubble reminders not flaky

---

api/src/pcapi/routes/backoffice/templates/accounts/get/general.html
api/tests/routes/backoffice/accounts_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24373

(PC-24373)[BO] feat: show suspension reason on top of user details page

---

api/src/pcapi/core/offers/exceptions.py
api/src/pcapi/core/offers/validation.py
api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/routes/pro/stocks.py
api/src/pcapi/routes/public/individual_offers/v1/events.py
api/src/pcapi/routes/public/individual_offers/v1/products.py
api/tests/core/educational/api/test_edit_collective_offer_stock.py
api/tests/core/educational/test_api.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_validation.py
api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py

Rejected or pending offers are not editable, this broke our product ean API.
The idea is to have a non blocking error for this API
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25579

(PC-25579)[API] chore: create check offer status exception

---

api/src/pcapi/core/offers/validation.py

J'aimerais trouver un moyen de faire en sorte qu'un test échoue (et qu'on arrête de s'en rendre compte en testing avec un peu de chance).
Erreur sentry : https://passcultureteam.slack.com/archives/C03QA34JQG3/p1699258817604369
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25600

(PC-25600)[API] fix: we can't access requests context from api

---

pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/__specs__/FiltersTags.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/utils.spec.ts
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts
pro/src/utils/__specs__/facetFilters.spec.ts
pro/src/utils/facetFilters.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25248
Afficher un tag lieu quand on arrive de la cartographie Adage ou qu'on clique sur une suggestion de l'autocomplete
Pour tester l'arrivée depuis la carto, ajouter `&venue=[VENUE_ID]` dans l'url de l'iframe adage 
_Note : Le coverage manquant concerne le code plugin algolia, non testé comme expliqué par le commentaire du istanbul ignore_
**Screen**

(PC-25248)[PRO] feat: add venue tag

---

api/src/pcapi/routes/backoffice/accounts/blueprint.py
api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py
api/src/pcapi/routes/backoffice/pro.py
api/src/pcapi/routes/backoffice/templates/accounts/get/general.html
api/src/pcapi/routes/backoffice/templates/bank_account/get.html
api/src/pcapi/routes/backoffice/templates/components/search/result.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card_bank_account.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card_offerer.html
api/src/pcapi/routes/backoffice/templates/components/search/result_card_venue.html
api/src/pcapi/routes/backoffice/templates/finance/invoices/get.html
api/src/pcapi/routes/backoffice/templates/layouts/base.html
api/src/pcapi/routes/backoffice/templates/offerer/get.html
api/src/pcapi/routes/backoffice/templates/pro_user/get.html
api/src/pcapi/routes/backoffice/templates/venue/get.html
api/src/pcapi/static/backoffice/js/addons/pc-strip-query-string.js
api/tests/routes/backoffice/accounts_test.py
api/tests/routes/backoffice/helpers/url.py
api/tests/routes/backoffice/pro_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-25433
- corrections :
- suivre dans ces _trackers_ les pages affichées comme unique résultat de recherche
- envoyer la bonne position lorsqu'on clique sur un résultat au-delà de la page 1 (ça revenait à 0 à chaque page)
- améliorations : 
- un peu de factorisation dans les liens
- à l'affichage, retirer les _query params_ de l'URL dans la barre d'adresse pour permettre de copier/coller un lien propre qui ne ré-enverra pas les _trackers_ de recherche

(PC-25433)[BO] fix: pro search trackers for analytics

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231106T142559_55e87bc5d320_remove_custom_reimbursement_rule_amount_in_eurocents.py
api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/factories.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list.html
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
api/tests/core/finance/test_api.py
api/tests/core/finance/test_commands.py
api/tests/core/finance/test_models.py
api/tests/routes/backoffice/custom_reimbursement_rules_test.py

`CustomReimbursementRule.amount` is one the last model columns (in
`core.finance`) where we store euros and not eurocents. This commit is
the third step in storing eurocents in the `amount` column.
step 1: add `amountInEurocents` and write in both `amount` and
`amountInEurocents`. Also, populate `amountInEurocents`
for existing rows.
step 2: use `amountInEuroCents` column instead of `amount`.
step 3: store eurocents in `amount` column.
-> step 4: use `amount` column.
step 5: drop `amountInEuroCents` column.
---
Cette PR sera mergée après la MEP de l'étape 3 (lundi 30).

(BSR)[API] refactor: Use `CustomReimbursementRule.amount` instead of `amountInEuroCents"

---

api/src/pcapi/app.py

Faciliter l'utilisation du live debugger
En activant le debugging dans la config, on se retrouve avec flask qui se déconecte après quelque secondes du debugger et il faut relancer à plusieurs reprises.
Ce comportement est du au `use_reloader` (qui permet de faire le hot relaod) qui est instable
https://flask.palletsprojects.com/en/2.2.x/debugging/#external-debuggers

(BSR)[API] feat: simplify using live debugging

---

api/src/pcapi/routes/pro/collective_stocks.py
api/tests/routes/pro/patch_collective_stock_test.py

catch RejectedOrPendingOfferNotEditable error for PATCH /collective/stocks route

(BSR)[API] fix: catch non-updatable error when editing collective stock

---

.github/workflows/tests-pro-e2e.yml

Send a notification in #dev slack channel if e2e tests fails during a merge

(BSR)[PRO] fix: add a notification if e2e tests fails during a merge

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24865
SOUS FF : `WIP_ENABLE_FORMAT`
Au lieu d'afficher les catégories, on remplace avec la valeur du format, au clic on sélectionne la valeur dans le select Format

(PC-24865)[PRO] feat: add format to autocomplete suggestion

---

api/.vscode/extensions.json
api/.vscode/settings.json

Mise à jour des settings vscode dépréciés
Ajout des extensions recommandées qui remplacent ces settings (black, mypy, pylint)

(BSR) chore: update vscode settings made obsolete by the latest version

---

api/src/pcapi/routes/public/individual_offers/v1/products.py
api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py

Our product database has flaws. Multiples products exists and we didn't filter them enough. There is a unique constraint on idAtProviders ensuring that we only have one product by ean returned.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25630

(PC-25630)[API] fix: UniqueViolation error on create_offer_from_product

---

api/src/pcapi/routes/serialization/offers_serialize.py

On veut renvoyer une 400 si la page dans la requête GET stocks est <1
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25617

(PC-25617)[API] feat: get stocks sends 400 when page is <1

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/serialization/offers_serialize.py
api/tests/core/offers/test_repository.py
api/tests/routes/pro/get_offer_test.py
pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts

On rajoute un champ "bookingCount" dans la route get offer afin de renvoyer le nombre de réservations pour une offre
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25351

(PC-25351)[API] feat: add bookings count to get offer route

---

api/src/pcapi/routes/backoffice/templates/pro_user/get/details/user_offerer.html
api/tests/routes/backoffice/pro_users_test.py

Ajout le statut de la structure dans l'onglet rattachement aux structures d'un compte pro
Ticket Jira : https://passculture.atlassian.net/browse/PC-25297

(PC-25297)[BO] feat: Add status structure on pro user details

---

pro/cypress.config.ts

La plupart des échecs ont l'air d'être dus à un timeout sur la route patchOffer qui prend plus de 5 secondes (le timeout par défaut est de 5s)

(BSR)[PRO] fix: increase e2e request timeout

---

api/src/pcapi/core/finance/api.py

Ticket Jira (ou description si BSR) : il faut utiliser `ex` et pas `ttl` dans un redis_client

(BSR)[BO] fix: use ex not ttl in redis client

---

api/src/pcapi/routes/external/sendinblue.py
api/tests/routes/external/sendinblue_test.py

Commits à relire séparément. Il y avait _aussi_ un bug dans les tests
(ce qui a fait qu'on n'a pas vu le bug dans l'implémentation).

(BSR)[API] Correction de la vérification de l'IP source sur les webhooks Brevo (ex-SendinBlue)

---

.github/workflows/tests-main.yml

Currently (before this commit), when building the Docker image for a
branch (for a pull request), the "checkout" GitHub Action checks out
the latest commit of the branch and merges it to the target branch
(usually master). In other words, the content of the Docker image is
not exactly what is in the branch.
This is the default behaviour of the "checkout" GitHub Action.
This is not what we want. We want the Docker image to contain exactly
what is in the branch. This behaviour is documented here:
https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
Note that the bug did not affect "version tags" (such as v261). In
that case, the GitHub Action properly checks out a specific commit.

(BSR)[API] ci: Build Docker image from the branch, not from its merged state

---

app-engine/image-resizing/requirements.txt

Suite à l'apparition de l'erreur :
```
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
```
sur le service image-resizing, il faut pour l'instant limité la version de werkzeug qui est installée avec Flask.

(BSR) fix: Upgrade flask to support werkzeug 3

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231113T164908_c56e5591f7b5_add_sso.py
api/src/pcapi/core/users/factories.py
api/src/pcapi/core/users/models.py
api/src/pcapi/core/users/repository.py
api/src/pcapi/models/feature.py
api/src/pcapi/routes/native/v1/authentication.py
api/src/pcapi/routes/native/v1/serialization/authentication.py
api/tests/routes/native/v1/authentication_test.py
api/tests/routes/native/v1/openapi_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25116
Page Notion : https://www.notion.so/passcultureapp/Spike-Implications-Backend-946b686524e7444b944add8c506ac3fe
Le SSO Google a déjà en partie été implémenté par le backoffice. La librairie utilisée est [Flask OAuth Client - Authlib 1.2.1 documentation](https://docs.authlib.org/en/latest/client/flask.html#routes-for-authorization).
Authlib valide pour nous le token Google et nous retrouvons l'utilisateur à travers son email dans notre base de donnée `User`.
Une simple table `single_sign_on` qui pointe vers `user` :
Cette implémentation permet :
- d’éviter d’ajouter une colonne dans la table `user` qui est déjà très chargée et qui risque de devoir être fait manuellement au vu de la taille de la table
- …

(PC-25116)[API] feat: add google sso for jeune app

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231103T145654_997fff1573da_populate_cgr_password_column_with_encrypted_values.py
api/src/pcapi/connectors/cgr/cgr.py
api/src/pcapi/core/providers/factories.py
api/src/pcapi/routes/backoffice/pivots/contexts/cgr.py
api/tests/connectors/cgr/api_cgr_test.py
api/tests/routes/backoffice/pivots_test.py

1/3
(pre) Create `encryptedPassword` column
Make the code write into that column
(post) Populate that column with existing data
(post) Make that column non-nullable
2/3
Make the code read `encryptedPassword` column
Make the code write encrypted values into `password` column
(post) Populate `password` column with encrypted values from `encryptedColumn`
3/3
Make the code read&write into `password` column
(post) Detete `encryptedPassword` column
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25041

(PC-25760)[API] feat: cipher CGR sensitive data 2/3

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/core/offers/validation.py
api/src/pcapi/routes/pro/stocks.py
api/tests/routes/pro/post_stocks_test.py

On veut renvoyer au front dans le bon champ l'erreur créé lors de la validation du prix (s'il est négatif ou > 300€) lors de l'édition d'un stock.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24828

(PC-24828)[API] feat: Send correct price error to front

---

pro/src/core/OfferEducational/utils/__specs__/createOfferPayload.spec.ts
pro/src/core/OfferEducational/utils/createOfferPayload.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25737
WIP_ENABLE_DATES_OFFER_TEMPLATE
**Objectif**
Ne pas set les dates d'une offre template quand on la crée depuis une autre offre.

(PC-25737)[PRO] duplicate template offer without dates

---

pro/src/pages/Home/Homepage.tsx
pro/src/pages/Home/Offerers/Offerers.tsx
pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx
pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.tracker.spec.tsx
pro/src/pages/Home/Venues/Venue.tsx
pro/src/pages/Home/Venues/VenueList.tsx
pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx
pro/src/pages/Home/Venues/__specs__/Venue.tracker.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24282
Sous FF, remplace le bouton "Renseigner des coordonées bancaires" par "Ajouter un compte bancaire" qui redirige vers `remboursements/informations-bancaires`
Ce bouton s'affiche s'il n'y a pas d'offre créée, et s'il n'y a pas de compte bancaire au sein de la structure

(PC-24282)[PRO] feat: update reimbursement link display conditions

---

api/src/pcapi/routes/pro/collective_offers.py
api/src/pcapi/routes/serialization/collective_offers_serialize.py
pro/src/apiClient/v1/models/ListCollectiveOffersQueryModel.ts
pro/src/apiClient/v1/services/DefaultService.ts
pro/src/core/Offers/constants.ts
pro/src/core/Offers/types.ts
pro/src/core/Offers/utils/serializer.ts
pro/src/pages/CollectiveOffers/CollectiveOffers.tsx
pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx
pro/src/pages/CollectiveOffers/adapters/getFilteredCollectiveOffersAdapter.ts
pro/src/screens/CollectiveOfferSelectionDuplication/__specs__/CollectiveOfferSelectionDuplicationScreen.spec.tsx
pro/src/screens/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx
pro/src/screens/OfferType/__specs__/OfferType.spec.tsx
pro/src/screens/Offers/SearchFilters/SearchFilters.tsx
pro/src/screens/Offers/__specs__/Offers.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25622
WIP_ENABLE_FORMAT
**Objectif**
Remplacer le filtre des catégories par le filtre des formats dans la page de la liste des offres collectives sur pro.
**A noter**
L'api a été initialement prévue pour recevoir une liste de filtres format dans l'appel au GET des offres collectives, mais on l'utilise avec un string en attendant d'avoir trouvé une solution à la sérialization d'une liste dans les query params d'une requete GET.

(PC-25622)[PRO] replace cat filter with format

---

api/src/pcapi/connectors/big_query/queries/offerer_stats.py

La requête big query pour récupérer les top offres par offerer renvoie des données dans un ordre qui semble aléatoire car elle est trié par consult_rank, que j'avais supposait triait la table par nombre de vues. Sauf que le champs contient des données pas cohérent avec cette hypothèse:
On trie alors dans cette par nombre de vues directement

(BSR)[API] fix: offerer stats top offers order

---

api/src/pcapi/routes/adage_iframe/serialization/logs.py
pro/src/apiClient/adage/models/AdageHeaderLink.ts
pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25542
SOUS FF : `WIP_ENABLE_DISCOVERY`
Ajout du tracker pour l'onglet "Découvrir" sur adage

(PC-25542)[PRO] feat: tracking adage discovery tab

---

api/src/pcapi/connectors/sirene.py
api/tests/connectors/sirene_test.py

We often make multiple consecutive calls to the Sirene API with the
same SIREN or SIRET. It makes sense to cache its responses.
The implementation is voluntarily dumb and makes an extra JSON
decoding and encoding round upon a cache miss. But the code is much
simpler this way.
---
Ticket : https://passculture.atlassian.net/browse/PC-25796

(PC-25796)[API] feat: Cache responses from Sirene API

---

pro/src/components/SkipLinks/SkipLinks.tsx
pro/src/index.html

Faire en sorte que la bannière de cookie soit le premier élément accessible à la navigation clavier.

(BSR)[PRO] feat: Moved the orejime block to make it keyboard accessible.

---

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25823
Lorsqu'on faisait une recherche textuelle sans utiliser l'autocomplete, le texte de recherche ne se supprimait pas pour la nouvelle recherche lorsqu'on sélectionnait un partenaire culturel depuis l'autocomplete ni dans le tracker de recherche

(PC-25823)[PRO] fix: search by partner in adage with autocomplete

---

api/src/pcapi/core/offers/api.py
api/src/pcapi/local_providers/titelive_thing_descriptions/titelive_thing_descriptions.py
api/src/pcapi/local_providers/titelive_things/titelive_things.py
api/tests/core/offers/test_api.py
api/tests/local_providers/titelive_descriptions_test.py
api/tests/local_providers/titelive_things_test.py

En attendant l'uniformisation des données communes des offres et produits.
Lorsque l'on intégre un produit Titelive, par la suite on créé des offres sur ces produits lors la synchro mise en place par les acteurs culturels.
Quand les infos d'un produit est mis à jour par Titelive, il faut mettre les offres associées.
Ticket Jira : https://passculture.atlassian.net/browse/PC-25727

(PC-25727)[API] feat: Titelive copy product data to offers data

---

api/src/pcapi/core/external_bookings/api.py
api/src/pcapi/core/providers/factories.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_collective_api_provider.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
api/src/pcapi/sandboxes/scripts/sandbox_industrial.py

BSR : 
Trying to fix synchronisation errors + always disable external bookings on testing

(BSR)[API] fix: venueProvider types in sandbox + disable external bookings on testing

---

api/src/pcapi/scripts/temp_vinyls_catchup.py

Les cd et vinyls ont été séparés en CD et Vinyls dans les sous-catégories.
Tout ce qui est synchro à été géré (Titelive par exemple)
Mais toutes les offres créées à la main par les acteurs ne l'ont pas été. Ce script vis à rattraper une majorité de ces offres sur le postulat simple: "S'il y a Vinyl dans le nom de l'offres, c'est certainement un Vinyl"
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25314

(PC-25314)[API] chore: add script to move non-synced vinyls to their subcategory

---

pro/src/pages/AdageIframe/app/App.tsx
pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.module.scss
pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/DomainsCard.module.scss
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/DomainsCard.tsx
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/__specs__/DomainsCard.spec.tsx
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/assets/circles.svg
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/assets/ellipses.svg
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/assets/pills.svg
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/assets/rectangles.svg
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/assets/squares.svg
pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/assets/triangles.svg
pro/src/pages/AdageIframe/app/components/AdageDiscovery/__specs__/AdageDiscovery.spec.tsx
pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx
pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
pro/src/pages/AdageIframe/app/providers/FacetFiltersContextProvider.tsx
pro/src/pages/AdageIframe/app/providers/FiltersContextProvider.tsx
pro/src/utils/__specs__/facetFilters.spec.ts
pro/src/utils/facetFilters.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25389
Sous FF : `WIP_ENABLE_DISCOVERY`
Création du composant pour les domaines artistiques de la page découverte sur adage

(PC-25389)[PRO] feat: eac add artistic domain playlist

---

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx
pro/src/pages/Reimbursements/BankInformations/__specs__/BankInformations.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25626
Ajout tracket au clique sur le bouton "Ajouter un compte bancaire" sur la page `remboursements/informations-bancaires`

(PC-25626)[PRO] feat: add tracker for add bank account button

---

pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx
pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/CardOffer.module.scss
pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/CardOffer.tsx
pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/__specs__/CardOffer.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInfos/OffersInfos.module.scss
pro/src/pages/AdageIframe/app/components/OffersInfos/OffersInfos.tsx
pro/src/pages/AdageIframe/app/components/OffersInfos/__specs__/OffersInfos.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
pro/src/pages/AdageIframe/app/subRoutesAdage.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25637
`SOUS FF : WIP_ENABLE_DISCOVERY`
Préparer la page qui permettra d'afficher les détails d'une offre en particulier, lorsqu'on clique sur une offre qui est sur la page découverte, redirection sur une page dédiée à l'offre

(PC-25637)[PRO] feat: add layout offer adage

---

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx
pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25642
Page remboursements/informations-bancaires, bouton "Rattacher un lieu"
Il faut un lieu avec un compte bancaire, avec aucun lieu de la structure rattaché à un compte bancaire.

(PC-25642)[PRO] refactor: add tracker for venue attach button 

---

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py
api/tests/routes/backoffice/offerers_test.py

Tant qu'un utilisateur invité n'a pas cliqué sur le lien de validation de sa création de compte reçu par mail, il n'est pas rattaché à une structure. (Non présence d'un UserOfferer)
Du coup, quand il créait son compte utilisateur, la ligne d'invitation disparaissait du BO durant ce laps de temps.
Ticket Jira : https://passculture.atlassian.net/browse/PC-25243

(PC-25243)[BO] fix: Display invitation until user has validated account

---

pro/src/beamer.ts
pro/src/custom_types/window.d.ts
pro/src/index.html

Hypothèse de cause (qui sera vérifiée très vite quand ce sera en prod vu qu'il y a 1000 occurrences de l'erreur par jour) : le check de CSP via hash ne marche pas dans certains cas sur Firefox (probablement un bug navigateur).
En passant par un fichier chargé via url, on évite de passer par le hash potentiellement problématique. Je compte envoyer ça en prod et si effectivement l'erreur ne se produit plus je retirerai le hash manuel dans la déclaration des CSP

(BSR)[PRO] fix: beamer config is undefined

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231116T114911_f81aecdc3793_add_formats_to_validation_attributes.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/routes/backoffice/filters.py
api/src/pcapi/routes/backoffice/offer_validation_rules/blueprint.py
api/src/pcapi/routes/backoffice/offer_validation_rules/forms.py
api/src/pcapi/utils/custom_logic.py
api/tests/core/offers/test_api.py
api/tests/routes/backoffice/offer_validation_rules_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25836
Fix : permettre de mettre à jour les règles de fraude concernant les offres collectives.
Problème : les formats sont des listes et en l'état les règles disponibles ne permettent pas de manipuler des ensembles.
Les deux nouvelles règles ajoutées (`one of` et `not one of`) permettent de vérifier qu'aucune des valeur indiquée n'est présente parmi les formats (par exemple) de l'offre.

(PC-25836)[API] fix: fraud: add [not] one of rule

---

api/src/pcapi/core/search/commands/indexation.py
api/src/pcapi/core/search/staging_indexation.py
api/tests/core/search/test_commands_indexation.py

- on est limité sur le nombre d'offres à reindéxer sur staging
- choisir une sous partit à reindéxer aléatoirement n'assure pas d'avoir un échantillon représentatif
- on a choisis d'ajouter une commande pour sélectionner un échantillon représentatif à indexer

(BSR)[API] feat: add command to selectively index offers staging

---

api/src/pcapi/routes/backoffice/venues/blueprint.py
api/src/pcapi/routes/backoffice/venues/forms.py
api/tests/routes/backoffice/venues_test.py

Bouton : Afficher uniquement les structures validées sur la page Actions sur les lieux
Ticket Jira : 
Par défaut:
Avec une recherche
Pas uniquement les structures validées :

(PC-25690)[BO] feat: add filter only validated offerer on list venues

---

api/src/pcapi/core/users/api.py
api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py
api/src/pcapi/routes/backoffice/pro_users/blueprint.py
api/tests/routes/backoffice/admin_test.py
api/tests/routes/backoffice/pro_users_test.py

We have several permissions: manage admin users, manage pro users, manage young users; admin should not be able to update any user without the appropriate permission.
Issue was reported by hunter thibaut670 using pass Culture Bug Bounty
Ticket Jira : https://passculture.atlassian.net/browse/PC-25879

(PC25879)[BO] fix: beneficiary or pro user could be modified from BO users management

---

api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/pro/offerers.py
api/src/pcapi/routes/serialization/offerers_serialize.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerers_stats.py
api/tests/core/external/offerer_stats_test.py
pro/src/apiClient/v1/index.ts
pro/src/apiClient/v1/models/GetOffererStatsResponseModel.ts
pro/src/apiClient/v1/models/OffererStatsDataModel.ts
pro/src/pages/Home/StatisticsDashboard/MostViewedOffers.tsx
pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx
pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25906
Fill missing data for offerer with no views on their offers. This query will be executed at most once a day for an offerer.
For offerer without data in bigquery, it took around 0.3s.
I also changed the serialization to be more clear: 
if lastSync date is None there has never been a sync
if lastSync > 24h a new sync will be done
if lastSync < 24h no sync will be done for now
if dailyViews and topOffers are empty arrays, it means there is nothing to display (only the lastSync param should be used to know the sync state)

(PC-25906)[API|PRO] fix: homepage views per offer table

---

pro/src/pages/Home/Venues/Venue.tsx
pro/src/pages/Home/Venues/VenueStat.scss
pro/src/pages/Home/Venues/VenueStat.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25553
Suite à l'audit RGAA - page d'accueil, critère 9.3  Dans chaque page web, chaque [liste](https://ara.numerique.gouv.fr/ressources/glossaire#listes) est-elle correctement structurée ?
la recommandation est de mettre les stats dans une liste
Au niveau graphique et fonctionnel, rien ne devrait changer

(PC-25553)[PRO] refactor: turn stats into a list

---

pro/src/screens/IndividualOffer/SummaryScreen/StockSection/RecurrenceSection/RecurrenceSection.tsx
pro/src/screens/IndividualOffer/SummaryScreen/StockSection/RecurrenceSection/__specs__/RecurrenceSection.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25524
Branche: PC-25524-offres-creation-event
Remplacer query by get.
Consulter Récapitulatif  de création des offres-événements. 
Code: RecurrenceSection, Stock Summary Event '0 ' - stocks affiche "Illimitée". 
→ si remainingQuantity = 0 il faut afficher '0' dans ce cas et ajouter le test qui le prouve.
Logique:
Pour javascript '0' est considéré comme null ou undefined.
toto = null
toto ? "zero" : "pas zero"
==> pas zero
toto = 0
toto ? "zero" : "pas zero"
==> pas zero
toto = 2
toto ? "zero" : "pas zero"
==> zero
RecurrenceSection.tsx , RecurrenceSection.spec.tsx  
1. Définition de stocksStats avec remainingQuantity et stockCount à zéro pour simuler un cas où la quantité est `nulle`.
2. Rendu du composant …

(PC-25524)[PRO] feat: ajout de new test pour réca d'offre

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/pro/offers.py
api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py
api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues_with_timezone.py
api/src/pcapi/workers/update_stocks_job.py
api/tests/core/offers/test_api.py
api/tests/core/offers/test_repository.py
api/tests/routes/pro/get_stocks_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25909
Des stocks event à la même heure mais à cheval sur l'heure d'été et l'heure d'hiver,  ne sont donc pas stockés à la même heure en UTC dans la bdd, le filtre tel qu'il était implémenté ne renvoyait donc pas tous les résultats (hélas),
exemple:  heure d'hiver `2024-03-30T   + 14:54  +  :00Z` heure d'été `2024-03-31T   +  13:54  +   :00Z`
le front envoie  heure + minutes en paramètres, il  l'a préalablement traduit en UTC, 
en recevant le paramètre l'api la serialize en un datetime.time object
on veut faire comprendre à la requête get_filtered_stocks, de bien nous ramener tous les stocks 
Je ne suis absolument pas à l'aise avec les timezone / heure d'été, et pas tellement avec le back :)
J'ai donc …

 (PC-25909)[API] fix: handle winter & summer time in get_filtered_stocks

---

api/src/pcapi/routes/backoffice/bookings/forms.py
api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html
api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
pro/src/components/CollectiveOfferSummary/components/CollectiveOfferLocationSection/CollectiveOfferLocationSection.tsx
pro/src/components/CollectiveOfferSummary/components/CollectiveOfferLocationSection/__specs__/CollectiveOfferLocationSection.spec.tsx

Both forms are correct but we should use one consistently, not both.
See 55d5298c3207044ae78e6f65f2db0e14cfbb3780 and 206bede290a1a3135119c6c6eeb05be21f6b3247 for precedents.

(BSR)[PRO] chore: Spell it "évènement", not "événement"

---

pro/src/components/Breadcrumb/Breadcrumb.module.scss
pro/src/components/Breadcrumb/Breadcrumb.tsx
pro/src/components/Breadcrumb/__specs__/Breadcrumb.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersFavorites/OffersFavorites.tsx
pro/src/pages/AdageIframe/app/components/OffersInfos/OffersInfos.module.scss
pro/src/pages/AdageIframe/app/components/OffersInfos/OffersInfos.tsx
pro/src/pages/AdageIframe/app/components/OffersInfos/__specs__/OffersInfos.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
pro/src/ui-kit/Button/ButtonLink.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25636
- WIP_ENABLE_DISCOVERY
- Aller sur adage et entrer dans l'url: `.../adage-iframe/decouverte/offre/1?token=...` pour afficher une offre qui implémente le fil d'Ariane
**Objectif**
Créer un nouveau component `Breadcrumb.tsx` qui affiche un fil d'Ariane, et l'implémenter dans les pages info des offres Adage. Le 2ème commit corrige la structure de les la liste des offres adage pour que on ait ul > li (et pas de li quand on n'a pas de liste).

(PC-25636)[PRO] breadcrumb component adage

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231122T173518_e0e253e1dca7_delete_collective_booking_booking_id.py
api/src/pcapi/core/educational/models.py

This column was used to ease the migration from the former
`EducationalBooking` model. The column is not used anymore.

(BSR)[API] chore: Delete unused `CollectiveBooking.bookingId` column

---

api/src/pcapi/scripts/rebuild_staging/anonymize.sql

BSR : la table offerer_invitation en staging contient toujours les emails des pros invités à être rattachés à une structure en clair.
ça me semble compliqué de garder le lien `offerer_invitation.email -> user.email du compte pro créé` lors de l'anonymisation, mais ça pourrait se faire si le besoin est exprimé

(BSR)[API] fix: anomymize offerer_invitation

---

api/src/pcapi/workers/logger.py

We seem to have issues on the "low" queue. Being able to filter
related logs would be helpful.

(BSR)[API] feat: Log queue name for rq-based asynchronous jobs

---

pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx
pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24278
- Notification de succès ou d'erreur à l'envoi du formulaire.

(PC-24278)[PRO] feat: Added notifications on success and failure.

---

api/src/pcapi/core/offerers/repository.py
api/tests/routes/pro/get_offerer_test.py

It’s useless here and moreover, the `correlate` instruction is ignore, thus we end up joining over all bankAccounts and all Offerers

(BSR)[API] fix: Remove useless join

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231123T163324_d158e4b24ff2_alter_user_nullable_password.py
api/src/pcapi/connectors/google_oauth.py
api/src/pcapi/core/users/api.py
api/src/pcapi/core/users/exceptions.py
api/src/pcapi/core/users/models.py
api/src/pcapi/repository/clean_database.py
api/src/pcapi/routes/native/v1/account.py
api/src/pcapi/routes/native/v1/authentication.py
api/src/pcapi/routes/native/v1/serialization/account.py
api/src/pcapi/routes/native/v1/serialization/authentication.py
api/tests/core/users/test_models.py
api/tests/routes/native/v1/account_test.py
api/tests/routes/native/v1/authentication_test.py
api/tests/routes/native/v1/openapi_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25588
Le code de création de comptes a été repris avec quelques modifications : 
- la nouvelle route ne demande pas le mot de passe ni l'email de l'utilisateur
- l'email est récupéré du jeton Google que l'on reçoit
- le lien entre `User` et `SingleSignOn` est automatiquement créé dans `create_account`
- une contrainte en base de donnée a été rajoutée pour forcer la présence de soit `password` soit un `single_sign_on`
Sur une base de donnée propre, et la configuration en local pour utiliser l'oauth google :
```
pass-culture-main/api on  PC-25588-create-account-through-sso [⇡] via pass-culture-main 
➜ google_code="4/0AfJohXmzyj7UTUtRAY98ojUFWY7xwgADcsRCgGZFhr4sf3-VeAHqlVvrDASvAj4sq4Ea2Q"
pass-culture-main/api …
```

(PC-25588)[API] feat: add account creation through sso

---

pro/src/components/Breadcrumb/Breadcrumb.tsx
pro/src/components/Breadcrumb/__specs__/Breadcrumb.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26039
Changer l'aria label pour le fil d'ariane de "Fil d'Ariane" à "Vous êtes ici:"
Pourquoi ? 
Les technologies d’assistances doivent annoncer le type de navigation quand on navigue sur un fil d’Ariane. Le nom “Fil d’Ariane“ n'étant pas super explicite, on préfère “Vous êtes ici : “ comme dans https://www.service-public.fr/

(PC-26039)[PRO] feat: change aria-label in breadcrumb

---

api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py
api/tests/routes/backoffice/offerers_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-25885
- Sur la page structure à valider, mettre par défaut le filtre à “nouveau”
retirer “en attente”
- Sur les rattachements à valider, mettre par défaut le filtre à “nouveau”
retirer “en attente"

(PC-25885)[BO] feat: only New status on offerer page to be validated

---

api/src/pcapi/alembic/versions/20231123T163324_d158e4b24ff2_alter_user_nullable_password.py

It should be a single line, otherwise it breaks the output of `alembic
history` (among other commands).

(BSR)[API] chore: Fix docstring of Alembic migration (single line)

---

api/src/pcapi/connectors/ems.py
api/src/pcapi/core/external_bookings/boost/client.py
api/src/pcapi/core/external_bookings/cds/client.py
api/src/pcapi/core/external_bookings/ems/exceptions.py
api/src/pcapi/domain/allocine.py
api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py
api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py
api/tests/domain/allocine_test.py
api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py
api/tests/local_providers/cinema_providers/cgr/cgr_stocks_test.py
api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py

Failing to fetch a movie poster should not break anything. Just log
and continue as if there was no movie poster.

(BSR)[API] fix: Handle 404 when fetching movie posters

---

pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx
pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24281 
Fix l'affichage de la pop-in lors de la création d'une première offre individuelle
On veut afficher la pop-in selon les conditions suivantes quand le FF WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY est actif : 
- La structure n'a pas encore d'offre payantes 
- La structure n'a pas de compte bancaire (validé ou en cours) 
- L'offre entrain d'être créée est payante

(PC-24281)[PRO] fix: fix conditions to display first offer modal

---

api/src/pcapi/core/search/__init__.py
api/src/pcapi/core/search/commands/indexation.py

**Commits à relire séparément** (j'en ai profité pour faire un peu de nettoyage).
Message du commit principal ::
We have two queues for each kind of resource to index (individual
offers, venues, collective offers, collective offer templates): the
main queue and an error queue. For each kind of resource, we regularly
pop from the main queue and try to send an indexation command to
Algolia. If it fails (network issue or, more commonly, an error when
trying to serialize our object for Algolia), we move the resource to
the error queue. We regularly do the same for items in the error
queue.
Until now, when an error occurred when processing the error queue, we
only log a warning, which was not visible in Sentry. We do monitor the
size of the queues, but it only tells us that there has been an …

(BSR)[API] Meilleurs logs en cas d'erreur d'indexation

---

api/src/pcapi/connectors/big_query/queries/offerer_stats.py
api/src/pcapi/core/offerers/api.py
api/src/pcapi/core/offerers/models.py
api/src/pcapi/routes/pro/offerers.py
api/src/pcapi/routes/serialization/offerers_serialize.py
api/tests/core/external/offerer_stats_test.py
api/tests/routes/pro/get_offerer_stats_test.py
pro/src/apiClient/v1/models/OffererStatsDataModel.ts
pro/src/pages/Home/StatisticsDashboard/MostViewedOffers.tsx
pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx
pro/src/pages/Home/StatisticsDashboard/__specs__/MostViewedOffers.spec.tsx
pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx

Fixer le calcul des données de consultations des 30 derniers jours de l'offerer
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26085

(PC-26085): fix offerer stats total views for last 30 days

---

api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py
api/src/pcapi/utils/cinema_providers.py
api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26002

(PC-26002)[API] fix: CDS synchro - use venue id in movie uuid instead of venue siret

---

api/src/pcapi/core/finance/api.py
api/src/pcapi/core/finance/models.py
api/src/pcapi/core/finance/utils.py
api/src/pcapi/models/feature.py
api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html
api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
api/src/pcapi/templates/invoices/invoice.html
api/tests/core/finance/test_api.py
api/tests/core/finance/test_utils.py
api/tests/files/invoice/rendered_invoice.html
api/tests/routes/backoffice/collective_bookings_test.py
api/tests/routes/backoffice/individual_bookings_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24452
Ajout de la notion d'incidents dans le justificatif de remboursement. Quelques modifications à noter : 
- Typo "montant remboursé" -> réservations
- Si incident -> "Incidents"
- Si incident, précision que le détail des offres remboursées inclut le montant des incidents
- Le type de PricingLine nouvellement ajouté (`OFFERER_RETRIEVAL`) a été retiré. Dans le cas d'un incident, on souhaite tout de même récupérer le montant de la contribution, on utilisera alors `OFFERER_CONTRIBUTION`, simplement le montant sera négatif
Correctif apporté sur les `PricingLine` générés lors d'un incident de finance partiel (événement de type `new-price`). Création de deux lignes, la première représentant le nouveau montant …

(PC-24452)[API] feat: Add finance incident in payment file

---

pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.module.scss
pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24362
- La largeur des deux modals doit être identique.

(PC-24362)[PRO] style: Both dialogs should have the same width.

---

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx
pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25631
Ajouter un tracker au clic sur le bouton "Suivre le dossier" de la page Informations bancaires

(PC-25631)[PRO] feat: track click on follow up bank account click

---

pro/scripts/customRequest.ts
pro/src/apiClient/adage/core/request.ts
pro/src/apiClient/v1/core/request.ts
pro/src/apiClient/v2/core/request.ts
pro/src/app/AppRouter/routesMap.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25794
on modifie la customRequest pour intercepeter les `401 - Unauthrized` et rediriger vers le login dans ce cas
comme un appel à users/current est toujours fait en arrivant sur l'app on veut l'exclure de la redirection automatique (pour ne pas redirgier sur les pages publiques)
(supprimez vos cookies pour tester)
Pour adage, 
A vérifier, mais d'après ce que j'ai compris adage ne throw pas des 401 mais des 403 quand le token n'est pas bon, 
j'imagine qu'on voudrait rediriger vers une page d'erreur dans ce cas (si j'ai compris ça signifie que le token d'adage a changé, ça devrait être rare)
pas trop sûr de la repoduction mais j'ai vu deux types de pages d'erreur sur adage :

(PC-25794)[PRO] feat: redirect user on login page when his session has expired

---

pro/src/screens/IndividualOffer/StocksThing/StockThing.module.scss
pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25762
Branche: PC-25762-style-onglet-stock
Bien aligné l’ensemble des champs :
- Réduire la taille du champ quantité.
- Réduire la taille du champ date d’expiration.
- Jusqu'à avoir assez de place pour faire tenir “date limite de réservation” sur une ligne.

(PC-25762)[PRO] feat: Mise à jour du style des champs de stock

---

pro/src/pages/AdageIframe/app/components/AdageDiscovery/__specs__/AdageDiscovery.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26113
**Objectif**
Le test sur l'appel au log data quand on atteint la fin d'une playlist dans la découverte semble ne pas fonctionner parfois dans la ci. J'ai changé le mock du hook de visibilité des éléments pour couvrir l'ensemble des appels à useIsElementVisible de la page découverte.

(PC-26113)[PRO] fix: Flaky test in AdageDiscovery.spec.tsx

---

api/src/pcapi/core/educational/models.py

With the formats field, subcategories are not filled any longer. Anything expecting subcategories to be not null fails and must be dealt with.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26118

(PC-26118)[ADAGE] fix: deal with null subcategories

---

api/src/pcapi/routes/pro/stocks.py
api/tests/routes/pro/post_stocks_test.py

Fix suite à la revue PM, la duplication d'offres datées n'est plus possibles avec une catégorie de prix non nulle 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25708

(PC-25708)[API] fix: duplication for price category

---

api/tests/core/bookings/test_models.py
api/tests/core/finance/test_api.py
api/tests/core/offerers/test_models.py
api/tests/core/offers/test_api.py
api/tests/core/reference/test_models.py
api/tests/core/users/backoffice/test_api.py
api/tests/models/feature_test.py
api/tests/routes/backoffice/conftest.py
api/tests/routes/backoffice/users_test.py
api/tests/routes/pro/get_offerer_test.py

Most of the time, we only need to tell SQLAlchemy to perform an UPDATE
or INSERT queries, not a COMMIT.

(BSR)[API] test: Do not use `commit()` when not necessary

---

pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx
pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24278
- Les bouton d'enregistrement et tout (dé)selectionner ne sont jamais disabled.

(PC-24278)[PRO] fix: Displaying fixes.

---

api/src/pcapi/routes/backoffice/autocomplete.py
api/src/pcapi/static/backoffice/js/addons/pc-tom-select-field.js
api/tests/routes/backoffice/autocomplete_test.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-25745
Cette structure à l'id 207, mais un nom et siren ne contenant pas 207 :
J'ai été obligé de modifier la déclaration tom-select en cas d'auto-complète, car le composant refait une recherche par défaut sur le label de l'option. Même si ça s'applique à tous les écrans utilisant un auto-complète, ça ne me semble pas problématique dans la plupart des cas.

(PC-25745)[BO] feat: Search by id offerer or id venue in autocompletion

---

api/tests/routes/backoffice/collective_offers_test.py

Accessing the offer in the test setup put it in SQLAlchemy session.
Then when the route tried to load it, no SQL query was performed, so
that made 3 SQL queries. In reality, the offer is fetched from the
database, so 4 SQL queries are made.
Note that this test passed when it was run on its own, but failed when
all module tests were run. And it did not fail before a2410a7dad64351,
which does not look related). I don't know why.

(BSR)[API] test: Fix assert_num_queries

---

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx
pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx
pro/src/screens/SignupJourneyForm/Validation/Validation.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26104
Page informations bancaires
Si je décoche un lieu ou que j’en coche un nouveau mais que l’AC n’enregistre pas : 
Au clic sur la croix 
Au clic en dehors de la pop in 
-> la pop in warning s’affiche

(PC-26104)[PRO] fix: display warning pop in on dialog dismiss

---

pro/src/components/StocksEventList/StocksEventList.tsx
pro/src/pages/Offers/Offers/OfferItem/Cells/OfferRemainingStockCell/OfferRemainingStockCell.tsx
pro/src/screens/IndividualOffer/StocksEventCreation/form/onSubmit.ts
pro/src/utils/pluralize.ts

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25521
(https://pro.testing.passculture.team/offres?nom-ou-isbn=1000)
- le chiffre de la colonne stock;
- le nombre de dates sous le titre de l’offre;
- la vue Récap de l’offre;
- le message d’ajout ou de suppression d’occurrences (toaster).
**Mais pluralize est modifiée  pour que ça affecte tous les endroits où elle est utilisée d'un coup (37 endroits dans 13 fichiers).** 
Branche: PC-25521-wording-espace-stock

(PC-25521)[PRO] feat: Format de nombre pluralize

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231201T105425_76109536b81c_remove_feature_flag_enable_new_user_offerer_link.py
api/src/pcapi/core/users/api.py
api/src/pcapi/models/feature.py
api/src/pcapi/routes/pro/offerers.py
api/tests/routes/pro/get_offerer_members_test.py
api/tests/routes/pro/post_offerer_invite_member_test.py
pro/src/pages/Home/Offerers/OffererDetails.tsx
pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx
pro/src/pages/Offerers/Offerer/OffererDetails/OffererDetails.tsx
pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23442
- Retrait du FF pour le nouveau parcours d'invitation.

(PC-23442)[API/PRO] chore: Remove WIP_ENABLE_NEW_USER_OFFERER_LINK FF.

---

api/src/pcapi/connectors/big_query/queries/offerer_stats.py
api/src/pcapi/core/offerers/api.py
api/tests/core/external/offerer_stats_test.py

La data nous renvoie une donnée par jour pour les jours où l'offerer a eu des vues, dans cette PR on remplie les trous afin d'afficher les stats corrects pour l'offerer
EX:
Si la data nous renvoie:
09/09/23: 10 vues
09/11/23: 100 vues
le graph fait une interpolation et lisse la courbe, affichant alors des données fausses, en plus le graph s'arrête au 09/11/23
Après cette PR le graph s'arretera tous le temps à la veille de la mise à jour (car les données de la data sont toujours décalés d'un jour)
on aura alors:
09/09/23: 10 vues
10/09/23: 10 vues
.
.
.
09/11/23: 100 vues
10/11/23: 100 vues
.
.
. 
yesterday: 100 vues
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26186

(PC-26186)[API] fix: fill the gaps in the stats provided from big query

---

pro/src/pages/Reimbursements/Reimbursements.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26051
Espacement entre tabs et contenu 64px -> 32px

(PC-26051)[PRO] style: move ReimbursementsTabs to avoid gap and margin bottom

---

api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py
api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26212
Ajout de la colonne de format à la liste des offres vitrine dans le backoffice.

(PC-26212)[BO] fix: add format column to the collective offer template page

---

api/src/pcapi/routes/public/individual_offers/v1/products.py

This was useful to easily debug this error but it was the expected behavior. Log an info instead of an exception

(BSR)[API] fix: mute RejectedOrPendingOfferNotEditable error for public api

---

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_venue_provider_and_external_bookings.py

They looks like the last errors on testing related to sandbox data.

(BSR)[API] fix: deactivate cinema venueProvider by default

---

api/src/pcapi/connectors/big_query/queries/adage_playlists.py
api/src/pcapi/core/educational/commands.py
api/src/pcapi/routes/adage_iframe/playlists.py
api/tests/routes/adage_iframe/playlist_test.py

- `institution_id` are string in BigQuery model. We need to cast them to str to avoid malformed queries
- `collective_offer_id` is used by data instead of `offer_id`.
- small typo
- We need the distance to the venue to be returned in any case for new template collective offers but only add the distance from the offer and the institution if it is performed at the offerer's venue.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26271

(PC-26271)[ADAGE] fix: various fixes on adage's playlist

---

pro/src/components/Address/Address.tsx
pro/src/components/Address/__specs__/Address.spec.tsx

Petite correction du front pour récupérer le bon champ de BAN ID
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25824

(PC-25824)[API] link ban id to correct field in front

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231207T101155_1ce7e6391919_delete_adage_favorite_ff.py
api/src/pcapi/models/feature.py
pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx
pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersFavorites/__specs__/OffersFavorites.spec.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26110
**Objectif**
Suppression du FF qui autorise l'affichage des favoris dans adage (onglet du header, bouton favoris sur les offres, page des favoris)

(PC-26110)[PRO] refactor: Remove WIP_ENABLE_LIKE_IN_ADAGE ff.

---

api/src/pcapi/routes/adage_iframe/serialization/playlists.py
pro/src/apiClient/adage/models/LocalOfferersPlaylistOffer.ts

passer la serialization en camel case pour la dernière route de playlist pour la page découverte d'Adage.

(BSR)[ADAGE] fix: use camel case in adage playlist

---

api/src/pcapi/core/offerers/repository.py
api/tests/routes/pro/get_offerer_stats_v2_test.py

Avec le join sur la table stock, sans le distinct on se retrouve à compter le nombre de stocks
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25706

(PC-25706)[API] fix: count distinct offers

---

api/src/pcapi/core/bookings/models.py
api/src/pcapi/core/educational/models.py
api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py
api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
api/tests/routes/backoffice/finance_test.py

`pricing` was too vague for a property that excluded some pricing
statuses. In fact, this property is only used to show the reimbursed
amount in the back-office, so `processed` pricings should be included
as well. Ditto for the `cashflow` property.

(BSR)[API] style: Rename `Booking.pricing` property as `reimbursement_pricing`

---

api/src/pcapi/routes/backoffice/offers/blueprint.py
api/src/pcapi/routes/backoffice/templates/components/links.html

Lorsqu'on clique sur un id d'offre dans la page de réservation, aller directement à la page de détails de l'offre, plutôt que la recherche filtrée par cet id (c'était bien quand on n'avait pas la page offre :)).

(BSR)[BO] feat: offer link directly to details page

---

api/src/pcapi/core/finance/api.py
api/tests/core/finance/test_api.py

Ticket Jira : https://passculture.atlassian.net/browse/PC-26300
Permettra peut-être de corriger à [cette erreur Sentry](https://sentry.passculture.team/organizations/sentry/issues/377455/?project=5&query=is%3Aunresolved+no+registration+date&statsPeriod=14d)

(PC-26300)[API] fix: Recredit user registered at 14 and credited at 15

---

api/src/pcapi/core/educational/api/venue.py
api/src/pcapi/core/educational/repository.py
api/tests/routes/adage/v1/get_all_bookings_per_year_test.py
api/tests/routes/adage/v1/get_all_venues_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26365
`/adage/v1/years/9/prebookings` :  [sentry](https://sentry.passculture.team/organizations/sentry/performance/api:d6ac9aa83b1845a09a108919d4b2f2a3/?environment=production&project=5&query=transaction.duration%3A%3C15m+http.method%3AGET&statsPeriod=7d&transaction=adage_v1.get_all_bookings_per_year&unselectedSeries=p100%28%29#request)
`/adage/v1/venues`: [sentry](https://sentry.passculture.team/organizations/sentry/performance/api:95ef4487f22f43418b1964b69559d785/?environment=production&project=5&query=transaction.duration%3A%3C15m+http.method%3AGET&statsPeriod=7d&transaction=adage_v1.get_all_venues&unselectedSeries=p100%28%29)

(PC-26365)[API] fix: N+1 issues

---

api/src/pcapi/core/offers/repository.py
api/src/pcapi/routes/pro/offers.py
api/tests/core/external/compliance_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25991
Lié au ticket jira 24965, lorsqu'on va retirer les stocks de la route GET offers, on n'aura plus besoin de la jointure sur les stocks (?)

(PC-25991)[API] refactor: optimise get offer by id query

---

api/src/pcapi/routes/backoffice/templates/layouts/base.html

Ticket Jira (ou description si BSR) : fix la favicon du BO quand on affiche une page d'erreur

(BSR)[BO] fix: handle favicon in bo error pages

---

api/src/pcapi/routes/adage_iframe/playlists.py
api/src/pcapi/routes/adage_iframe/serialization/offers.py
api/src/pcapi/routes/adage_iframe/serialization/playlists.py
api/tests/routes/adage_iframe/playlist_test.py
pro/src/apiClient/adage/models/LocalOfferersPlaylistOffer.ts

Renvoyer une distance avec un seul chiffre après la virgule.
Il y a deux possibilités : soit formater la valeur au niveau de la réponse de la requête Big query, soit au niveau du contrôleur. La seconde option a été choisie puisqu'il y perte d'informations et que les deux sont comparables en terme de complexité (la première était sûrement un tout petit peu plus simple).

(BSR)[EAC] feat: playlists: format distances

---

.github/workflows/tests-pro-e2e.yml

- Les vidéos sont maintenant dans des dossiers par branche et par commit.

(BSR)[PRO] ci: Change the e2e videos path for more usability.

---

api/src/pcapi/backoffice_app.py
api/src/pcapi/flask_app.py
api/src/pcapi/routes/adage/security.py
api/src/pcapi/routes/adage_iframe/security.py
api/src/pcapi/routes/error_handlers/bookings_error_handlers.py
api/src/pcapi/routes/error_handlers/generic_error_handlers.py
api/src/pcapi/routes/error_handlers/thumbnails_error_handlers.py
api/stubs/flask/app.pyi

We set a `generate_error_response()` function on each app (the
"regular" app and the "back-office" app). This helps with the
implementation of error handlers. But mypy does not like that.
By declaring this attribute in the typing stub for `Flask`,
mypy accepts our setting and accessing the attribute.
(This is similar to what was done for `app.redis_client` in 0524dbd392863353305e7ac3dea4d198a3b7dd14.)

(BSR)[API] chore: Avoid mypy warnings about `app.generate_error_response()`

---

api/src/pcapi/scripts/beneficiary/import_test_users.py
api/tests/scripts/beneficiary/import_test_users_test.py

Some code (used only for underage beneficiary, which was not
automatically tested) compares the birth date with a date. This
comparison fails when the birth date is a `datetime` object. It
must be a `date` object.

(BSR)[API] fix: Fix import of underage beneficiaries

---

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx
pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26313
- Si aucun lieu (physique - avec ou sans offre - ou numérique - avec offre) n’est rattaché au compte bancaire en question → affichage de la phrase “Aucun lieu n’est rattaché à ce compte bancaire.”
- Si 1 ou plusieurs lieux (physique - avec ou sans offre - ou numérique - avec offre) n’est pas rattaché au compte bancaire en question → affichage de la phrase “Certains de vos lieux ne sont pas rattachés”
- Si tous les lieux (physique - avec ou sans offre - ou numérique - avec offre) de la structure sont déjà rattachés à un ou plusieurs comptes bancaires, autres que le compte bancaire en question → affichage de la phrase “Aucun lieu n’est rattaché à ce compte bancaire. Désélectionnez un lieu déjà rattaché …

(PC-26313)[PRO] fix: update conditional wording rendering

---

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx
pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26312
- Changement des conditions d'affichage de l'icône "!".

(PC-26312)[PRO] feat: Change condition displaying of the "!" icon.

---

api/src/pcapi/routes/public/individual_offers/v1/serialization.py
api/tests/routes/public/individual_offers/v1/get_event_test.py
api/tests/routes/public/individual_offers/v1/get_events_test.py

Some data were missing from offers (musicSubType), fallback to 'OTHER' in this case. 
We also had a bug for offers not created from this API, withdrawalType is either None or IN_APP for offers created from apis.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26456

(PC-26456)[API] fix : public individual API get_event(s) routes

---

api/alembic_version_conflict_detection.txt
api/src/pcapi/alembic/versions/20231128T192124_98681bf3c6b2_add_allocine_id_as_product_index.py
api/src/pcapi/core/offers/models.py
api/src/pcapi/core/providers/allocine_movie_list.py
api/tests/domain/allocine_test.py
api/tests/domain/fixtures.py
api/tests/providers/allocine_movie_list_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25874
Dans la classe `OfferExtraData`, les champs `cast` et `countries` étaient typés en `str` et passent en `list[str]`. Cependant, en base ils sont déjà tous enregistrés au format `list[str]` (au moins en staging).

PC-25874 upsertion of movies catalogue

---

api/src/pcapi/routes/backoffice/offers/forms.py
api/tests/routes/backoffice/offers_test.py

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23795

(PC-23795)[BO] fix: permit to use coma in edit stock  price
