pro/src/styles/components/layout/_CookieModals.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23345
=> (PC-23345)[PRO] style: Remove box-shadow from orejime sliders.

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23305
Création d’un feature flag pour la nouvelle façon de rajouter des collaborateurs sur le portail pro.
=> (PC-23305)[API] feat: Add new user offerer link feature flag.

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.tsx
Correction du build qui ne passe plus sur master.
=> (BSR)[PRO] fix: fix build issues.

pro/src/components/AdageButtonFilter/AdageButtonFilter.tsx, pro/src/components/AdageButtonFilter/__specs__/AdageButtonFilter.spec.tsx, pro/src/components/OfferIndividualForm/ImageUploaderOffer/ImageUploaderOffer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/ModalFilterLayout/ModalFilterLayout.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/NoResultsPage.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/NoResultsPage.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/OldNoResultsPage.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/__specs__/NoResultsPage.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22891
Ajout d'un bouton qui permet de supprimer tout les filtres existants
=> (PC-22891)[PRO] feat: add clear all filter button in adage

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230724T093020_c1c137b863fe_add_preferences_jsonb_to_educational_redactor.py, api/src/pcapi/core/educational/api/redactor.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/adage_iframe/__init__.py, api/src/pcapi/routes/adage_iframe/authentication.py, api/src/pcapi/routes/adage_iframe/redactor.py, api/src/pcapi/routes/adage_iframe/serialization/adage_authentication.py, api/src/pcapi/routes/adage_iframe/serialization/redactor.py, api/tests/routes/adage_iframe/get_authenticate_test.py, api/tests/routes/adage_iframe/redactor_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/AuthenticatedResponse.ts, pro/src/apiClient/adage/models/RedactorPreferences.ts, pro/src/apiClient/adage/services/DefaultService.ts
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22904
Enregistrer le fait que l'utilisateur ne souhaite plus voir le formulaire. Et renvoyer cette information lorsqu'il se connecte pour ne plus le lui afficher.
=> PC 22904 save redactor preferences

pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.module.scss, pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.tsx, pro/src/ui-kit/Hero/Hero.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-20453
fix ui
Après :
Avant:
=> (PC-20453)[PRO] fix: ui in LostPassword

api/src/pcapi/core/bookings/api.py, api/src/pcapi/routes/native/v1/bookings.py, api/src/pcapi/routes/native/v1/serialization/bookings.py, api/tests/routes/native/v1/bookings_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23450
=> PC-23450 add email contact to bookings

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230721T065239_48013aa5a395_remove_ff_allow_idcheck_registration_for_educonnect_eligible.py, api/src/pcapi/core/subscription/api.py, api/src/pcapi/models/feature.py, api/tests/core/subscription/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23199
=> (PC-23199)[API] feat: Remove FF ALLOW_IDCHECK_REGISTRATION_FOR_EDUCONNECT_ELIGIBLE

pro/package.json, pro/src/index.html, pro/tsconfig.json, pro/vite.config.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23338
début de la conf de vite
=> Pc 23338 vite config

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFiltersTags/OfferFiltersTags.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OldOfferFilters.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/NoResultsPage.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/SearchBox/SearchBox.scss, pro/src/pages/AdageIframe/app/ui-kit/MultiSelectAutoComplete/MultiSelectAutocomplete.scss, pro/src/pages/AdageIframe/app/ui-kit/Pellet/Pellet.scss, pro/src/styles/index.scss, pro/src/styles/mixins/_layout.scss, pro/vite.config.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23334
=> Pc 23334 vite css

api/requirements.txt, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/email/update.py, api/tests/core/token/test_token.py, api/tests/core/users/email/test_update.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23216
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23312
-Ajouter une couche d'abstraction au système de gestion des tokens https://www.notion.so/passcultureapp/Harmoniser-la-gestion-des-tokens-dans-le-backend-583e1947bb554c0fb2833d1f48b864cc?pvs=4
-Remplacement du token de confirmation de changement d'email par la nouvelle abstraction Token
=> Pc 23216 abstraction tokens

infra/pc_scripts/start_backend.sh
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23521
=> (PC-23521) fix: Parsing docker-compose version

api/src/pcapi/routes/adage_iframe/__init__.py, api/src/pcapi/routes/adage_iframe/academies.py, api/src/pcapi/routes/adage_iframe/serialization/academies.py, api/tests/routes/adage_iframe/academies_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/AcademiesResponseModel.ts, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23275
Ajout d'une route qui renvoie toutes la liste des académies.
=> PC 23275 academies

api/src/pcapi/routes/backoffice_v3/offer_validation_rules/blueprint.py, api/src/pcapi/routes/backoffice_v3/offer_validation_rules/forms.py, api/src/pcapi/routes/backoffice_v3/offer_validation_rules/utils.py, api/tests/routes/backoffice_v3/offer_validation_rules_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23470
=> (PC-23470)[API] feat: add and redo keyword search in validation rules

api/src/pcapi/core/token/__init__.py
remove unused method Token.get_token()
=> Bsr remove unused method token get token

api/src/pcapi/algolia_settings_venues.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23428
=> (PC-23428)[ALGOLIA] feat: Do not search in venue description

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23525
=> (PC-23525)[PRO] feat: Add feature flag to be used to enable the national system in collective offers

pro/src/screens/OfferIndividual/StocksEventCreation/RecurrenceForm.tsx, pro/src/screens/OfferIndividual/StocksEventEdition/StocksEventEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23563
=> (PC-23563)[PRO] fix: date not added in event edition

pro/src/core/Venue/utils.ts, pro/src/styles/global/_font_faces.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23522
- Correction des chargement des fonts avec vite.
=> (PC-23522)[PRO] fix: Fix fonts loading, and import error.

api/.env.testauto, api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230712T140528_60d5208fd945_add_ems_cinema_details.py, api/src/pcapi/alembic/versions/sql/schema_init.sql, api/src/pcapi/connectors/ems.py, api/src/pcapi/connectors/serialization/ems_serializers.py, api/src/pcapi/core/external_bookings/ems/exceptions.py, api/src/pcapi/core/providers/constants.py, api/src/pcapi/core/providers/factories.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/local_providers/__init__.py, api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/src/pcapi/local_providers/install.py, api/src/pcapi/local_providers/provider_manager.py, api/src/pcapi/scheduled_tasks/commands.py, api/src/pcapi/settings.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py, api/tests/local_providers/cinema_providers/ems/fixtures.py, api/tests/routes/pro/get_providers_by_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22135
Lancer la synchronisation initiale (version = 0) des cinémas EMS
=> (PC-22135): EMS initial synchronization

api/src/pcapi/local_providers/titelive_things/titelive_things.py, api/tests/local_providers/titelive_things_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23585
RDP bugs: https://www.notion.so/passcultureapp/CRON-titelive_things-en-chec-depuis-le-20-juillet-2023-ea540797a16f445aa8ba41373ca068d2
=> (PC-23585)[API] fix: synchro titelive_things add new column

api/src/pcapi/local_providers/titelive_things/titelive_things.py
Ticket Jira (ou description si BSR) : https://github.com/pass-culture/pass-culture-main/pull/7529/files
=> (BSR)[API] fix: titelive logging mismatch args

pro/src/screens/OfferIndividual/Summary/Summary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23357
changement d'icône pour la popin de redirection après création d'une première offre
=> (PC-23357)[PRO] fix: change cancel icon in summary redirect dialog

api/src/pcapi/routes/backoffice_v3/templates/admin/users_generator.html
BSR : Dans le générateur d'utilisateurs, ouvrir le lien pour se connecter à l'app dans un nouvel onglet
https://github.com/pass-culture/pass-culture-main/assets/128476306/44324f14-d2ab-41ad-b891-7ad6a3ac04e0
=> (BSR)[BO] feat: Open link to app in new tab

pro/src/screens/OfferIndividual/Summary/OfferSection/OfferSection.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.tsx
We should only use EAN-13 instead of EAN
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22568
=> (PC-22568)[PRO] fix: use EAN-13 string

api/src/pcapi/routes/public/collective/endpoints/categories.py, api/src/pcapi/routes/public/collective/endpoints/domains.py, api/src/pcapi/routes/public/collective/endpoints/educational_institutions.py, api/src/pcapi/routes/public/collective/endpoints/offers.py, api/src/pcapi/routes/public/collective/endpoints/students_levels.py, api/src/pcapi/routes/public/collective/endpoints/venues.py, api/tests/routes/public/blueprint_v2_openapi_test.py, pro/src/apiClient/v2/AppClientV2.ts, pro/src/apiClient/v2/index.ts, pro/src/apiClient/v2/services/ApiOffresCollectivesService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23321
Suppression du tag BETA des routes de l'api collective publique;
=> (PC-23321)[API] feat: collective public API: rm BETA from tag

api/src/pcapi/routes/public/individual_offers/v1/blueprint.py, api/src/pcapi/serialization/decorator.py, api/tests/conftest.py, api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py, api/tests/serialization/serialization_decorator_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22991
=> (PC-22991)[API] fix: silence json invalid error only for CM v2 api

pro/src/components/AdageButtonFilter/AdageButtonFilter.tsx, pro/src/components/AdageButtonFilter/__specs__/AdageButtonFilter.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/ModalFilterLayout/ModalFilterLayout.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OldOfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/NoResultsPage.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/__specs__/NoResultsPage.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OldOffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OldOffersSearch.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/utils.spec.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22894
Ajout du filtre Type d'intervention sur adage
lien de [test](https://pc-pro-testing--pr7462-pc-22894-event-locat-08a8k6lx.web.app/adage-iframe?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaXZpbGl0ZSI6Ik0uIiwibm9tIjoiVEVTVCIsInByZW5vbSI6IkNPTVBURSIsIm1haWwiOiJjb21wdGUudGVzdEBlZHVjYXRpb24uZ291di5mciIsInVhaSI6IjA1NjAwNzFZIiwiZXhwIjoxNjkwNTkwMTg0fQ.hfikTSRxud70tK3SHz81tASCvI2WiiIdnCosxq-mwE61pgA1GTEIho1rCrelDHLn-W0Rf6blhPB4VirIGNvYFF60HxzsIEY0ANwGpRtPPnIwQTWJf_SQtYEBpQ9UTSuKh78vP83FppROCW72mhkgH_OS3NCPaPPzl-JAnAw4dEdc_-dOi5BuGZvrANgJeg7EFWoc3_n3018nm9-OPiLMg1d28GgKsuSUvOUZ_8vy2l6ebDJDXuznMdI3yCWkLr6rFFbMuBDairZQ9M_kmEdVlD5j-767ZuX1JGy4wYjYkCoqAyKkcm--WxUFoc0Ufuh9v4Cfbgo9MEEFhm_30KfIWQ)
=> (PC-22894)[PRO] feat: add event location filter in adage

.github/workflows/build-on-tags.yaml, .github/workflows/deploy-pro-pr-version-generic.yml, .github/workflows/release--build-hotfix.yml, .github/workflows/release--build.yml, pro/vite.config.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23336
=> (PC-23336)[PRO] chore: upload sourcemaps to Sentry

api/src/pcapi/core/users/models.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23557
=> PC 23557 fix chomeur wording

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23496
Créer le FF pour l'ajout d'une aide diffuse sur adage
`FF : WIP_ENABLE_DIFFUSE_HELP`
=> (PC-23496) feat: add diffuse help adage ff

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/screens/Bookings/BookingsRecapTable/components/CellsFormatter/CellFormatter.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23243
Fix sur les icones de la liste de réservations collectives et des offres adages
=> (PC-23243)[PRO] fix: fix ui icons

api/src/pcapi/routes/backoffice_v3/templates/pivots/get/boost.html, api/src/pcapi/routes/backoffice_v3/templates/pivots/get/cgr.html, api/src/pcapi/routes/backoffice_v3/templates/pivots/get/cineoffice.html, api/tests/routes/backoffice_v3/pivots_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23600
=> (PC-23600)[BO] fix: Do not show passwords/API keys in "pivot" pages

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/NoResultsPage/__specs__/NoResultsPage.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/utils.spec.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts, pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.tsx, pro/src/ui-kit/form/AdageMultiselect/__specs__/AdageMultiselect.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23612
=> (PC-23612)[PRO] Add categories multiselect to adage filters

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/local_providers/titelive_things/titelive_things.py, api/src/pcapi/routes/backoffice_v3/multiple_offers/blueprint.py, api/src/pcapi/routes/backoffice_v3/offers/blueprint.py, api/src/pcapi/routes/backoffice_v3/titelive/blueprint.py, api/tests/core/offers/test_api.py, api/tests/local_providers/titelive_things_test.py, api/tests/routes/backoffice_v3/titelive_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23619
=> (PC-23619)[API] fix: refactor to keep one fn to reject products

pro/src/screens/EmailChangeValidation/EmailChangeValidation.module.scss, pro/src/screens/EmailChangeValidation/EmailChangeValidation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22318
PRO - Changement d'email - Changement de style de Font
PC-22318-email-style-font
=> (PC-22318)[PRO] feat: Email Change Validation Style

api/src/pcapi/core/subscription/api.py, api/tests/core/subscription/ubble/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23582
=> (PC-23582)[API] fix: Replace birth date by id provider's when eligible for beneficiary upgrade

api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/tests/routes/public/individual_offers/v1/get_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23127
=> (PC-23127) return error if the offer id is not found

pro/src/components/AdageButtonFilter/AdageButtonFilter.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23581
=> (PC-23581)[PRO] feat: Rework adage filters list to fit in adage frame.

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/ui-kit/form/TextInput/TextInput.stories.tsx, pro/src/ui-kit/form/TextInput/TextInput.tsx, pro/src/ui-kit/form/shared/BaseInput/BaseInput.module.scss, pro/src/ui-kit/form/shared/BaseInput/BaseInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23391
Surement des choses à revoir sur la partie BaseInput pour l'ajout du leftIcon. J'ai essayé de laisser la structure existante, mais ça vaudrait surement le coup de séparer explicitement les containers des leftIcon, rightIcon et rightButton.
=> (PC-23391)[PRO] update searchbar adage offers

pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23386
Clear l'input de la modal des filtres adage à la fermeture/ouverture de la modal
FF : WIP_ENABLE_NEW_ADAGE_FILTERS
=> (PC-23386)[PRO] feat: clear adage modal input value on close

api/src/pcapi/scripts/offer/fill_product_and_offer_ean.py
During the migration from isbn to ean we went a little too far
=> (BSR)[API] fix: do not delete ean but isbn

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23673
Contexte : Lorsqu'on arrive depuis la carto adage on valorise la barre de recherche avec le nom du lieu. 
Fix :
=> (PC-23673)[PRO] fix: reinit initial query on resetform

api/src/pcapi/validation/routes/users_authentifications.py, api/tests/validation/routes/users_authentifications_test.py
block unactive providers from calling modification apis
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23230
=> (PC-23230) block unactive providers from accessing api

pro/src/components/Tutorial/Step/ManageBookings.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23603
=> (PC-23603)[PRO] fix: tutorial calendar icon width

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23653
Créer un FF pour le fléchage d'une offre à un établissement
=> (PC-23653)[PRO] feat: create ff offer to institution

api/src/pcapi/core/providers/repository.py, api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/src/pcapi/local_providers/provider_manager.py, api/src/pcapi/scheduled_tasks/commands.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py, api/tests/local_providers/cinema_providers/ems/fixtures.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23548
=> (PC-23548)[API] feat: Handle EMS version sync

api/src/pcapi/algolia_settings_venues.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23683
- [X ] J'ai écrit les tests nécessaires
- [X ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [X ] J'ai ajouté des screenshots pour d'éventuels changements graphiques
=> (PC-23683)[ALGOLIA] feat: Create 2 index replicas for venues

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/backoffice_v3/multiple_offers/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23619
=> (PC-23619)[API] fix: reject_inappropriate_products SQL optimization and fix

api/src/pcapi/core/offers/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23619
=> (PC-23619)[API] fix: reject_inappropriate_products SQL optim fix

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
This will the migration to `PRICE_EVENTS`.
=> (BSR)[API] fix: Update `FinanceEvent.status` in `price_booking()`

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23713
PR pour corriger le type check sur pro. 
La fonction setQuery n'est plus utilisée
=> (PC-23713)[PRO] fix: remove setQuery, not used anymore

pro/src/screens/OfferIndividual/StocksEventCreation/form/validationSchema.ts, pro/src/screens/OfferIndividual/StocksEventEdition/StockFormList/validationSchema.ts, pro/src/screens/OfferIndividual/StocksThing/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23368
=> (PC-23368)[PRO] feat: add max stocks validation

api/tests/core/bookings/test_models.py
Fix un test ou l'user n'a pas assez de crédit sur ma branche
[test](https://github.com/pass-culture/pass-culture-main/actions/runs/5782374096/job/15669135345?pr=7638) / [pr](https://github.com/pass-culture/pass-culture-main/pull/7638)
=> (BSR)[API] fix: unit test with insufficient credit

api/src/pcapi/core/offers/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23619
=> (PC-23619)[API] fix: remove unecessary commit

api/src/pcapi/models/feature.py, pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23399
=> (PC-23399)[PRO] feat: add new bank details journey FF

api/src/pcapi/routes/backoffice_v3/accounts.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23721
=> (PC-23721)[API] fix: add logging for user 2602428

api/src/pcapi/core/offers/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23722
=> (PC-23722)[API] fix: sentry error 422201

api/src/pcapi/core/mails/transactional/users/suspicious_login_email.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/core/mails/transactional/users/suspicious_login_email_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22840
=> (PC-22840)[API] feat: Send reset password token in suspicious login email

api/tests/routes/public/individual_offers/v1/post_product_test.py
Ajouter un order by pour les offres pour enlever rendre le test déterministe
=> (BSR)[API] test: order offers in post products test

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesServerError.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23708
AVANT :
APRES :
=> (PC-23708)[PRO] fix: reimbursment icon

pro/src/components/SkipLinks/SkipLinks.module.scss, pro/src/pages/CookiesFooter/CookiesFooter.module.scss, pro/src/pages/Errors/Unavailable/Unavailable.module.scss, pro/src/pages/Errors/Unavailable/Unavailable.tsx, pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.module.scss, pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.tsx, pro/src/pages/LostPassword/LostPassword.module.scss, pro/src/pages/LostPassword/LostPassword.tsx, pro/src/pages/ResetPassword/ChangePasswordForm/ChangePasswordForm.module.scss, pro/src/pages/ResetPassword/ChangePasswordForm/ChangePasswordForm.tsx, pro/src/pages/ResetPassword/ResetPassword.module.scss, pro/src/pages/ResetPassword/ResetPassword.tsx, pro/src/pages/SignIn/SignIn.tsx, pro/src/pages/SignIn/Signin.module.scss, pro/src/pages/SignIn/SigninForm/SigninForm.tsx, pro/src/pages/Signup/Signup.module.scss, pro/src/pages/Signup/Signup.tsx, pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.module.scss, pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.tsx, pro/src/pages/Signup/SignupContainer/SignupContainer.module.scss, pro/src/pages/Signup/SignupContainer/SignupContainer.tsx, pro/src/pages/Signup/SignupContainer/SignupForm.tsx, pro/src/pages/Signup/SignupUnavailable/SignupUnavailable.module.scss, pro/src/pages/Signup/SignupUnavailable/SignupUnavailable.tsx, pro/src/screens/EmailChangeValidation/EmailChangeValidation.module.scss, pro/src/screens/EmailChangeValidation/EmailChangeValidation.tsx, pro/src/styles/components/layout/_Logo.scss, pro/src/styles/global/_page.scss, pro/src/styles/mixins/_layout.scss, pro/src/styles/variables/_size.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23378
refacto html / css + responsive de 
sign in
parcours sign up
sign up unavailable
/erreur/indisponible
parcours lostpassword
=> (PC-23378)[PRO] feat: responsive signin, signup & LostPassword

api/src/pcapi/routes/backoffice_v3/templates/tags/list_tags.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23440
=> (PC-23440)[BO] fix: Description column width for offer criterion list

api/src/pcapi/repository/clean_database.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23732
=> (PC-23732)[API] fix: delete product_whitelist in clean_all_database

api/src/pcapi/domain/demarches_simplifiees.py, api/tests/connector_creators/demarches_simplifiees_creators.py, api/tests/domain/demarches_simplifiees_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23731
=> (PC-23731) Clean dms_token field when handling bank info applications

api/src/pcapi/routes/backoffice_v3/forms/fields.py, api/src/pcapi/routes/backoffice_v3/pivots/forms.py, api/src/pcapi/routes/backoffice_v3/templates/components/forms/string_field.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23724
=> (PC-23724)[API] fix: use password fields for passwords

api/src/pcapi/repository/clean_database.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23740
=> (PC-23740)[API] fix: add missing fraud_models BlacklistedDomainName,OrphanDmsApplication

api/src/pcapi/routes/native/v1/authentication.py, api/src/pcapi/routes/native/v1/serialization/authentication.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23121
=> (PC-23121)[API] feat: Create access and refresh token on reset password success

api/src/pcapi/core/categories/subcategories_v2.py, api/src/pcapi/sandboxes/scripts/creators/data/create_data_thing_products.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23430
=> (PC-23430)[API] feat: add-data-with-gtl-to-sandbox

api/src/pcapi/routes/backoffice_v3/titelive/blueprint.py, api/tests/core/offers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23711
=> (PC-23711)[API] fix: revalidate rejected product on whitelisting

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/ClosedSatisfactionSurvey.ts, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23376
=> (PC-23376)[API] feat: endpoint log sat survey

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_venue_provider_and_external_bookings.py
- Ajouter des objets liés au provider EMS dans la sandbox.
- Refactoring
=> (BSR)[API]feat: create EMS-related objects and refactor in sandbox

api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/backoffice_v3/collective_bookings.py, api/src/pcapi/routes/backoffice_v3/forms/collective_booking.py, api/src/pcapi/routes/backoffice_v3/forms/individual_booking.py, api/src/pcapi/routes/backoffice_v3/individual_bookings.py, api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice_v3/templates/components/copy_link.html, api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html, api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html, api/src/pcapi/routes/pro/bookings.py, api/src/pcapi/static/backofficev3/js/addons/pc-clipboard.js, api/tests/routes/backoffice_v3/collective_bookings_test.py, api/tests/routes/backoffice_v3/conftest.py, api/tests/routes/backoffice_v3/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22768
=> (PC-22768)[BO] feat: permit bookings download from backoffice

api/src/pcapi/core/offers/api.py, api/tests/routes/backoffice_v3/multiple_offers_test.py
=> (BSR)[API] fix: flacky test

api/src/pcapi/core/providers/titelive_gtl.py, api/src/pcapi/core/providers/titelive_utils.py, api/src/pcapi/local_providers/titelive_things/titelive_things.py, api/tests/core/providers/test_titelive_gtl.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22592
=> (PC-22592)[API] fix: continue if gtl not present

api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/src/pcapi/local_providers/provider_manager.py, api/src/pcapi/workers/venue_provider_job.py, api/tests/local_providers/provider_manager_test.py, api/tests/routes/pro/post_venue_provider_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23654
=> (PC-23654)[API] EMS create venue provider synch

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/__specs__/AllocineProviderForm.spec.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderFormDialog/AllocineProviderFormDialog.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderParamaters/AllocineProviderParameters.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderForm/CinemaProviderForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderForm/__specs__/CinemaProviderForm.spec.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderFormDialog/CinemaProviderFormDialog.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/CinemaProviderParameters/CinemaProviderParameters.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/__specs__/StocksProviderForm.spec.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProviderForm/VenueProviderForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23453
rajouter un paramètre "saved" au tracking des synchros
=> (PC-23453)[PRO] feat: add param to synchro tracking

pro/src/screens/OfferIndividual/Informations/Informations.tsx, pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.creation.spec.tsx, pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.draft.spec.tsx, pro/src/screens/OfferIndividual/PriceCategories/PriceCategories.tsx, pro/src/screens/OfferIndividual/PriceCategories/__specs__/PriceCategories.submit.spec.tsx, pro/src/screens/OfferIndividual/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/OfferIndividual/StocksEventCreation/__specs__/StocksEventCreation.spec.tsx, pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx, pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.draft.spec.tsx, pro/src/screens/OfferIndividual/StocksThing/adapters/upsertStocksThingAdapter.tsx, pro/src/screens/OfferIndividual/Summary/__specs__/Summary.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23379
=> (PC-23379)[PRO] feat: remove save draft message

pro/src/pages/Errors/NotFound/NotFound.module.scss, pro/src/pages/Errors/NotFound/NotFound.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23734
=> (PC-23734)[PRO] fix: design page not found

pro/src/app/AppRouter/subroutesOfferIndividualWizardMap.tsx, pro/src/hooks/usePageTitle.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23486
=> (PC-23486)[PRO] fix: title page of offre creation

pro/src/screens/SignupJourneyForm/Offerers/Offerers.module.scss, pro/src/screens/SignupJourneyForm/Offerers/Offerers.tsx, pro/src/screens/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23322
=> (PC-23322)[PRO] feat: Displaying changes for new offerer link feature.

api/src/pcapi/routes/backoffice_v3/home.py, api/src/pcapi/routes/backoffice_v3/templates/home/home.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_tags.py, api/tests/routes/backoffice_v3/home_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-22734
=> (PC-22734)[BO] feat: add counter for offerers waiting for fraud

api/src/pcapi/core/finance/exceptions.py, api/src/pcapi/routes/backoffice_v3/finance/blueprint.py, api/src/pcapi/routes/backoffice_v3/templates/components/forms/textarea_field.html, api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get.html, api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get/general.html, api/tests/routes/backoffice_v3/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22756
=> (PC-22756)[BO] feat: Cancel finance incident from incident detail view

api/src/pcapi/core/users/api.py
fix du bug en testing qui envoi les email aux comptes qui ont été ensuite unsuspended:
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23359
=> (PC-23359)[API] fix: send email to only accounts that haven't been unsuspended

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/core/offerers/test_api.py, pro/src/apiClient/v1/models/SaveNewOnboardingDataQueryModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23286
=> (PC-23286)[API] fix: handle empty address during onboarding

api/src/pcapi/core/educational/api/national_program.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/src/pcapi/routes/serialization/national_programs.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py, api/tests/routes/adage_iframe/get_collective_offer_test.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_collective_offer_template_test.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/patch_collective_offer_template_test.py, api/tests/routes/pro/patch_collective_offer_test.py, api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/CollectiveOfferResponseModel.ts, pro/src/apiClient/adage/models/CollectiveOfferTemplateResponseModel.ts, pro/src/apiClient/adage/models/NationalProgramModel.ts, pro/src/apiClient/v1/models/CollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts
Renvoyer l'id et le nom du dispositif national, au lieu de l'id uniquement.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23530
=> (PC-23530)[API] fix: national program: object with name and id

api/src/pcapi/core/fraud/models.py, api/src/pcapi/core/fraud/ubble/constants.py, api/src/pcapi/core/subscription/ubble/api.py, api/src/pcapi/core/subscription/ubble/models.py, api/tests/core/subscription/ubble/test_api.py, api/tests/routes/external/user_subscription_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23516
=> (PC-23516)[API] fix: Change Ubble error code for blurry video

api/src/pcapi/routes/backoffice_v3/collective_bookings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22727
=> (PC-22727)[BO] fix: fix colletive booking download link

pro/src/core/OfferEducational/adapters/__specs__/getNationalProgramAdapter.spec.ts, pro/src/core/OfferEducational/adapters/getCollectiveOfferFormDataAdapter.ts, pro/src/core/OfferEducational/adapters/getNationalProgramAdapter.ts, pro/src/core/OfferEducational/constants.ts, pro/src/core/OfferEducational/types.ts, pro/src/core/OfferEducational/utils/computeInitialValuesFromOffer.ts, pro/src/core/OfferEducational/utils/createOfferFromBookableOffer.ts, pro/src/core/OfferEducational/utils/createOfferFromTemplate.ts, pro/src/core/OfferEducational/utils/createOfferPayload.ts, pro/src/pages/CollectiveOfferCreation/CollectiveOfferCreation.tsx, pro/src/pages/CollectiveOfferCreation/__specs__/CollectiveOfferCreation.spec.tsx, pro/src/pages/CollectiveOfferEdition/CollectiveOfferEdition.tsx, pro/src/pages/CollectiveOfferEdition/utils/__specs__/createPatchOfferPayload.spec.ts, pro/src/pages/CollectiveOfferEdition/utils/createPatchOfferPayload.ts, pro/src/pages/CollectiveOfferFromRequest/CollectiveOfferFromRequest.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/DuplicateOfferCell.tsx, pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplicationScreen.tsx, pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx, pro/src/screens/OfferEducational/OfferEducational.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx, pro/src/screens/OfferEducational/__specs__/OfferEducationalCreationOfferTypeStep.spec.tsx, pro/src/screens/OfferEducational/__tests-utils__/defaultProps.ts, pro/src/screens/OfferEducational/useOfferEducationalFormData.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23483
Ajout d'un champ dispositif national lors de la création/édition d'offres collectives 
FF à activer : WIP_ENABLE_NATIONAL_SYSTEM
=> (PC-23483)[PRO] feat: add national system in collective offer creation

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferDetails.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23531
Pour reproduire :
- Aller sur les offres de l'interface adage
- Activer le FF WIP_ENABLE_NATIONAL_SYSTEM
=> (PC-23531)[PRO] feat: Add national program info in adage offer details.

api/tests/tasks/decorator_test.py
Less mocks, more comments, more chouquettes.
---
Bonus : Les tests passent désormais avec `spectree` version 0.7.2 (actuelle) et 1.2.0 (la dernière).
=> (BSR)[API] test: Rewrite tests of the `task` decorator for clarity

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
Ajouter des données de tests
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23610
=> (PC-23610): add new sandbox data

api/src/pcapi/core/token/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23219
=> (PC-23219)[API] feat: trace token usage

api/src/pcapi/core/users/api.py, api/tests/core/users/test_api.py
managing the edge case of multiple suspensions:
the following case was not handeled correctly: suspend(reason = upon_user_request) --> unsuspend --> suspend(reason = other_reason)
the suspenstion would of been detected because the filtering was executed before the distinct in the query.
now we filter after selecting distinct elements
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23359
=> Pc 23359 send email 10 days before account deletion multiple suspensions edge case

pro/src/components/VenueForm/VenueForm.tsx, pro/src/pages/Bookings/NoBookingsForPreFiltersMessage/NoBookingsForPreFiltersMessage.scss, pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/__specs__/ReimbursementFields.spec.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
=> (BSR)[PRO] fix: reimbursement test

api/src/pcapi/connectors/ems.py, api/src/pcapi/connectors/serialization/ems_serializers.py, api/src/pcapi/core/external_bookings/ems/client.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/src/pcapi/utils/cinema_providers.py, api/tests/core/external_bookings/ems/test_client.py, api/tests/core/offers/test_api.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py, api/tests/utils/cinema_providers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23524
=> (PC-23524)[API] EMS check showtimes availability

pro/src/screens/OfferIndividual/StocksThing/StocksThing.tsx, pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23800
=> (PC-23800)[PRO] Mettre le radio des boutons radio à gauche

api/src/pcapi/core/fraud/models.py, api/src/pcapi/core/fraud/ubble/constants.py, api/src/pcapi/core/subscription/ubble/api.py, api/src/pcapi/core/subscription/ubble/models.py
=> (PC-23516)[API] fix: Re-add BLURRY_VIDEO in FraudReasonCode for transtion with BLURRY_DOCUMENT_VIDEO

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23578
=> (PC-23578)[API] feat: add FF WIP_CATEGORY_SELECTION

pro/src/pages/SignIn/Signin.module.scss, pro/src/pages/Signup/SignupContainer/SignupContainer.module.scss, pro/src/styles/mixins/_layout.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23378
3 bugs:
-padding enlevé pour les tailles > tablet
- inverser les boutons du sign up
- marge blanche autour du logo dans le sign in quand la taille de l'écran était plus petite que le contenu à droite
=> (PC-23378)[PRO] fix: design with responsive

api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_offers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_products.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23562
=> Pc 23562 exploitation visa algolia

api/src/pcapi/core/token/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23219
=> (PC-23219)[API] fix: log token ActionType.value instead of ActionType

pro/src/ui-kit/Button/Button.module.scss
=> (BSR)[PRO] fix: button ui

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23746
=> (PC-23746)[PRO] feat: Add FF for adage filters geoloc.

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23679
=> (PC-23679)[API] feat: add-venue-creation-date-to-algolia

api/src/pcapi/core/users/factories.py, api/src/pcapi/routes/backoffice_v3/serialization/accounts.py, api/tests/routes/backoffice_v3/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23794
=> (PC-23794)[BO] fix: unknown action in email history

api/src/pcapi/core/users/api.py, api/src/pcapi/scheduled_tasks/commands.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21671
[PR pour ajouter le cron en testing](https://github.com/pass-culture/pass-culture-deployment/pull/253)
=> (PC-21671)[API] feat: Delete login device history older than 13 months

pro/src/components/Header/Header.scss, pro/src/components/Header/Header.tsx, pro/src/components/Header/__specs__/Header.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23820
- ajout d'un aria-label="Menu principal" sur la balise <nav>
- structuration du menu dans une liste
=> (PC-23820)[PRO] fix: accessibility main menu

pro/src/hooks/__specs__/useScrollToFirstErrorAfterSubmit.spec.tsx, pro/src/hooks/useScrollToFirstErrorAfterSubmit.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23782
=> (PC-23782)[PRO] feat: give focus to first input in error in forms

api/tests/routes/backoffice_v3/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23566
La CI fail sur le test qui permet de check l'ordre d'affichage des ActionHistory. Un order_by est pourtant bien défini, j'ai ajouté un plus grand delta entre l'action de création de l'incident et son annulation.
=> (PC-23566)[BO] fix: ci test

api/tests/routes/backoffice_v3/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23566
fix : test d'un order by flaky
=> (PC-23566)[BO] fix: test_get_incident_history rows order

api/src/pcapi/routes/backoffice_v3/accounts.py
This reverts commit 38464a5a421cda2c2dcceb13a68c04dc1fd56f1c.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23721
=> (PC-23721)[API] fix: add logging for user 2602428 [revert]

pro/src/pages/Offers/Offers/OffersStatusFiltersModal/OffersStatusFiltersModal.tsx, pro/src/screens/Bookings/BookingsRecapTable/components/Filters/FilterByBookingStatus/FilterByBookingStatus.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23832
=> (PC-23832)[PRO] refactor: add fieldset and legend to OfersStatus and filter bookingStatus

api/src/pcapi/core/external/sendinblue.py, api/src/pcapi/core/users/email/update.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23799
=> (PC-23799)[API] fix: give correct list and marketing choices when updating email

api/src/pcapi/core/offerers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23614
=> (PC-23614)[API] feat: change pictures names to use the new pictures

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice_v3/templates/components/search/result_card_venue.html, api/tests/routes/backoffice_v3/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23478
=> (PC-23478)[BO] feat: show offerer name on venue search results

pro/src/pages/Offers/Offers/ActionsBar/ActionsBar.tsx, pro/src/pages/Offers/Offers/ActionsBar/__specs__/ActionsBar.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23819
=> (PC-23819)[PRO] feat: add role status to offers count

pro/package.json, pro/src/components/ImageEditor/ImageEditor.module.scss, pro/src/components/ImageEditor/ImageEditor.stories.tsx, pro/src/components/ImageEditor/ImageEditor.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/ModalImageCrop.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx, pro/src/hooks/index.ts, pro/src/hooks/useEffectUnmount.tsx, pro/src/ui-kit/form/Slider/Slider.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23747
Changer le composant Slider utilisé dans l'édition d'image pour utiliser celui de l'ui-kit.
=> (PC-23747)[PRO] chore: change slider to use ui-kit one in ImageEditor

pro/src/pages/Offers/Offers/OffersStatusFiltersModal/OffersStatusFiltersModal.tsx, pro/src/pages/Offers/Offers/OffersTableHead/StatusFiltersButton.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23818
=> (PC-23818)[PRO] feat: add accessibility role for status in offers

pro/src/pages/Offers/Offers/ActionsBar/ActionsBar.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22286
=> (PC-22286)[PRO] fix: irritant design sur l'action bar des offres

pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-18677
=> (PC-18677)[PRO] fix: irritant design margin des checkboxs

pro/src/screens/OfferIndividual/StocksThing/ActivationCodeFormDialog/ActivationCodeFormDialog.module.scss, pro/src/screens/OfferIndividual/StocksThing/ActivationCodeFormDialog/ActivationCodeFormDialog.tsx, pro/src/screens/OfferIndividual/StocksThing/ActivationCodeFormDialog/ActivationCodesUploadInformationDescription.tsx, pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-19173
=> (PC-19173)[PRO] fix: irritant design modale codes d'activation

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23880
Fix sandbox data
=> (PC-23880)[API] fix: price_category for provided events

api/src/pcapi/core/offers/exceptions.py, api/tests/routes/pro/patch_offer_test.py, api/tests/routes/public/individual_offers/v1/post_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23880
Use a more understandable wording
=> (PC-23880)[API] fix: withdrawalType error wording

api/src/pcapi/connectors/beneficiaries/ubble.py, api/src/pcapi/core/fraud/ubble/api.py, api/src/pcapi/core/fraud/ubble/constants.py, api/src/pcapi/core/mails/transactional/users/ubble/constants.py, api/src/pcapi/core/subscription/ubble/api.py, api/src/pcapi/core/subscription/ubble/messages.py, api/tests/core/subscription/test_factories.py, api/tests/core/subscription/ubble/test_api.py, api/tests/routes/external/user_subscription_test.py, api/tests/routes/native/v1/account_test.py
=> Pc 23515 fix prioritized ubble error code

api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-17640
=> (PC-17640)[API] chore: Remove dateOfBirth from UserResponseProfile

api/src/pcapi/repository/clean_database.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23808
ajout de national_program à la sandbox
=> (PC-23808)[API] test: add national_program to sandbox

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Correction d'erreurs de typage reportées par mypy dans l'intégration continue.
=> (BSR)[API] fix: typing issue reported by mypy

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230817T152439_b93e190cb690_add_venue_bookingemail_index.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice_v3/pro_users/blueprint.py, api/tests/routes/backoffice_v3/pro_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23867
>  On fait une recherche par email à chaque mise à jour des attributs pro sur Sendinblue (appel d'update_external_pro).
=> (PC-23867)[API] fix: add venue.bookingEmail index

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/routes/backoffice_v3/collective_bookings.py, api/src/pcapi/routes/backoffice_v3/forms/collective_booking.py, api/src/pcapi/routes/backoffice_v3/forms/individual_booking.py, api/src/pcapi/routes/backoffice_v3/individual_bookings.py, api/tests/core/bookings/test_api.py, api/tests/core/finance/test_integration.py, api/tests/routes/backoffice_v3/collective_bookings_test.py, api/tests/routes/backoffice_v3/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-22352
Réservation individuelle :
Réservation collective :
=> (PC-22352)[BO] feat: ask for a reason when a booking is canceled

api/src/pcapi/routes/backoffice_v3/forms/venue.py, api/src/pcapi/routes/backoffice_v3/venues.py, api/tests/routes/backoffice_v3/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23477
=> (PC-23477)[BO] feat: edit venue type from backoffice venue page

api/src/pcapi/core/offers/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23807
=> (PC-23807)[API] feat: add titelive synced products sandbox

api/src/pcapi/core/users/email/update.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23289
=> (PC-23289)[API] feat: keep user connected after email change

pro/src/pages/Desk/adapters/__specs__/getBooking.spec.ts, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23947
Ajouter des tests pour l'adapteur getBooking utilisé dans le composant Desk.
=> (PC-23947)[PRO] test: add test for getBooking adapter

pro/src/screens/Bookings/BookingsRecapTable/components/Filters/FilterByOmniSearch/FilterByOmniSearch.module.scss, pro/src/screens/Bookings/BookingsRecapTable/components/Filters/FilterByOmniSearch/FilterByOmniSearch.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23833
=> (PC-23833)[PRO] fix: add legend, fieldset and hidden labels in omnisearch filters for A11y

api/src/pcapi/routes/public/collective/__init__.py, api/src/pcapi/routes/public/collective/endpoints/bookings.py, api/src/pcapi/routes/public/collective/serialization/bookings.py, api/src/pcapi/routes/public/collective/serialization/educational_years.py, api/tests/routes/public/blueprint_v2_openapi_test.py, api/tests/routes/public/collective/endpoints/bookings_test.py, pro/src/apiClient/v2/index.ts, pro/src/apiClient/v2/models/CollectiveBookingResponseModel.ts, pro/src/apiClient/v2/models/CollectiveBookingStatus.ts, pro/src/apiClient/v2/models/EducationalYearModel.ts, pro/src/apiClient/v2/services/ApiOffresCollectivesService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23648
Nouvelle route : renvoyer les information concernant une offre collective.
=> (PC-23648)[API] feat: public collective: get booking (new)

pro/src/screens/OfferIndividual/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/OfferIndividual/StocksEventCreation/__specs__/StocksEventCreation.spec.tsx, pro/src/screens/OfferIndividual/StocksEventEdition/StocksEventEdition.tsx, pro/src/screens/OfferIndividual/StocksEventEdition/__specs__/StockEventEdition.spec.tsx, pro/src/screens/OfferIndividual/StocksEventEdition/adapters/upsertStocksEventAdapter.tsx, pro/src/screens/OfferIndividual/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23571
=> (PC-23571)[PRO] feat: add warning when too many stocks are created

pro/src/pages/Reimbursements/ReimbursementsDetails/DetailsFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/screens/Bookings/PreFilters/FilterByBookingStatusPeriod/FilterByBookingStatusPeriod.module.scss, pro/src/screens/Bookings/PreFilters/FilterByBookingStatusPeriod/FilterByBookingStatusPeriod.tsx, pro/src/screens/Bookings/PreFilters/FilterByBookingStatusPeriod/FilterByStatus.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.tsx, pro/src/styles/global/_forms.scss, pro/src/ui-kit/form/PeriodSelector/PeriodSelector.module.scss, pro/src/ui-kit/form/PeriodSelector/PeriodSelector.tsx, pro/src/ui-kit/form/PeriodSelector/__specs__/PeriodSelector.spec.tsx, pro/src/ui-kit/form/shared/BaseInput/BaseInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23294
=> (PC-23294)[PRO] fix: add legend, fieldset and hidden labels in search filters for A11y

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/external_bookings/exceptions.py, api/src/pcapi/core/external_bookings/serialize.py, api/src/pcapi/routes/native/v1/bookings.py, api/tests/routes/native/v1/bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23607
When we book an offer that is linked to a provided offer we call an external API then update the remaining quantity of the stock
=> (PC-23607)[API] feat: update stock quantity on external stock response

api/src/pcapi/routes/public/individual_offers/v1/products.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22506
=> (PC-22506) bulk save stock in post products apis

pro/src/components/OfferIndividualForm/Notifications/__specs__/Notifications.spec.tsx, pro/src/components/OfferIndividualForm/Notifications/validationSchema.ts, pro/src/components/OfferIndividualForm/UsefulInformations/validationSchema.ts, pro/src/components/UserEmailForm/validationSchema.ts, pro/src/components/VenueForm/Contact/validationSchema.ts, pro/src/core/shared/utils/__specs__/parseAndValidateFrenchPhoneNumber.spec.ts, pro/src/core/shared/utils/parseAndValidateFrenchPhoneNumber.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/__specs__/RequestFormDialog.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/validationSchema.ts, pro/src/pages/LostPassword/validationSchema.ts, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/validationSchema.ts, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/validationSchema.ts, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/__specs__/CollectiveDataEdition.spec.tsx, pro/src/pages/SignIn/SigninForm/validationSchema.ts, pro/src/pages/Signup/SignupContainer/__specs__/validationSchema.spec.ts, pro/src/pages/Signup/SignupContainer/validationSchema.ts, pro/src/screens/OfferEducational/OfferEducationalForm/FormNotifications/__specs__/FormNotifications.spec.tsx, pro/src/screens/OfferEducational/validationSchema.ts, pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.tsx, pro/src/ui-kit/form/PhoneNumberInput/__specs__/PhoneNumberInput.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23780
=> (PC-23780)[PRO] refactor: update phoneNumber and email error message wording

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230822T153643_f891eee42f86_remove_ff_wip_enable_new_titelive_eligibility_filters.py, api/src/pcapi/local_providers/titelive_things/titelive_things.py, api/src/pcapi/models/feature.py, api/tests/local_providers/titelive_things_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23474
=> (PC-23474)[API] fix: remove unused titelive feature flip

api/src/pcapi/routes/backoffice_v3/pro.py, api/src/pcapi/routes/backoffice_v3/utils.py, api/tests/routes/backoffice_v3/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23694
=> (PC-23694)[BO] feat: add logs to pro search on bo

api/src/pcapi/routes/adage_iframe/redactor.py, api/tests/routes/adage_iframe/post_save_redactor_preference_test.py
resolve bug to return 400 only if no authentification email
=> (PC-23881)[API] fix: can't close satisfaction survey on adage in read only

api/tests/routes/pro/get_offers_test.py
=> (BSR)[API] fix: test get offers

pro/src/screens/SignupJourneyForm/Offerers/Offerers.module.scss, pro/src/screens/SignupJourneyForm/Offerers/Offerers.tsx, pro/src/screens/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23322
FF nécessaire: WIP_ENABLE_NEW_USER_OFFERER_LINK
- Supprimer la banière d'information `Vous souhaitez rejoindre cet espace ?`
- Corriger le style du titre
=> (PC-23322)[PRO] fix: remove banner and fix title style

api/src/pcapi/routes/backoffice_v3/offerers/validation_repository.py, api/tests/routes/backoffice_v3/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23998
=> (PC-23998)[BO] fix: remove multiple joins on same table

pro/src/components/AdageButtonFilter/AdageButtonFilter.module.scss, pro/src/components/AdageButtonFilter/AdageButtonFilter.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23869
Pour reproduire : 
- Activer le FF `WIP_ENABLE_NEW_ADAGE_FILTERS`
Avant :
Après :
=> (PC-23869)[PRO] feat: Rework adage filters styles and display.

pro/src/components/Newsletter/Newsletter.module.scss, pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23783
=> (PC-23783)[PRO] fix: buttonLink icon position

pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23900
FF à activer: **WIP_ENABLE_NEW_USER_OFFERER_LINK**
Ajouter un bouton au niveau de l'offre qui redirige l'utilisateur vers la section "Collaborateurs" de la page de la structure.
=> (PC-23900)[PRO] feat: add invite member button to offererDetails

pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.module.scss, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23836
=> (PC-23836)[PRO] refactor: replace h4 by title4 style in VenueOfferSteps

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_members_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetOffererMemberResponseModel.ts, pro/src/apiClient/v1/models/OffererMemberStatus.ts, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23310
=> (PC-23310)[API] feat: get offerer members route

api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23977
=> (PC-23977)[API] feat: Add deposit activation date to user profile

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_offerer_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22278
=> (PC-22278) make siren field only accept 9 characters siren

pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24057
=> (PC-24057)[PRO] fix: button icon alignement

api/src/pcapi/core/mails/transactional/users/ubble/subscription_document_error.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24006
=> (PC-24006)[API] feat: Change default email for ubble reason code

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23959
=> Pc 23959 add postal code to algolia

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py, api/src/pcapi/settings.py, api/tests/core/offers/test_validation.py, api/tests/routes/native/v1/bookings_test.py, api/tests/routes/native/v1/openapi_test.py, api/tests/routes/pro/post_offer_test.py, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/post_event_test.py, api/tests/routes/public/individual_offers/v1/utils.py, pro/src/apiClient/v1/models/WithdrawalTypeEnum.ts, pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/TicketWithdrawal.tsx, pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/__specs__/TicketWithdrawal.spec.tsx, pro/src/components/OfferIndividualForm/UsefulInformations/TicketWithdrawal/constants.ts, pro/src/core/Offers/constants.ts, pro/src/screens/OfferIndividual/Summary/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23880
New withdrawal type 'in_app'. Only available for event offers created from the api. 
The first commits contains a little bit of javascript.
=> (PC-23880)[API|PRO] feat: add 'in app' withdrawal mode

pro/src/pages/Signup/SignUpValidation/SignUpValidation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24061
=> (PC-24061)[PRO] fix: remove notify in useEffect to avoid double  validateUser request

pro/src/pages/Home/Offerers/OffererDetails.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23900
FF WIP_ENABLE_NEW_USER_OFFERER_LINK
=> (PC-23900)[PRO] fix: offerer invite member link

pro/src/components/VenueForm/Contact/validationSchema.ts, pro/src/pages/Signup/SignupContainer/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23780
=> (PC-23780)[PRO] fix: email error message

pro/src/pages/SignIn/SignIn.tsx, pro/src/pages/SignIn/__specs__/SignIn.spec.tsx, pro/src/pages/Signup/SignUpValidation/SignUpValidation.tsx, pro/src/pages/Signup/SignUpValidation/__specs__/SignupValidation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24074
Réparer la page blanche sur la page de connexion après la validation du compte utilisateur
https://passcultureteam.slack.com/archives/C01APVCG22J/p1693216367534649?thread_ts=1692896293.283019&cid=C01APVCG22J
=> (PC-24074)[PRO] refactor: use Navigate component

api/src/pcapi/core/users/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23851
=> Pc 23851 bug update birth date

api/src/pcapi/core/finance/siret_api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice_v3/filters.py, api/src/pcapi/routes/backoffice_v3/forms/fields.py, api/src/pcapi/routes/backoffice_v3/templates/components/forms/switch_boolean_field.html, api/src/pcapi/routes/backoffice_v3/templates/components/turbo/lazy_modal.html, api/src/pcapi/routes/backoffice_v3/templates/components/turbo/modal_form.html, api/src/pcapi/routes/backoffice_v3/templates/offer_validation_rules/list_rules.html, api/src/pcapi/routes/backoffice_v3/templates/venue/get/stats.html, api/src/pcapi/routes/backoffice_v3/venues/blueprint.py, api/src/pcapi/routes/backoffice_v3/venues/form.py, api/tests/core/offerers/test_models.py, api/tests/routes/backoffice_v3/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23970
=> (PC-23970)[BO] feat: Action to remove pricing point for a venue without SIRET

api/src/pcapi/core/fraud/ubble/constants.py, api/src/pcapi/core/mails/transactional/users/ubble/reminder_emails.py, api/tests/core/mails/transactional/users/ubble_ko_reminder_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24031
=> (PC-24031)[API] feat: Add Ubble KO codes to reminders

api/tests/routes/pro/post_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23827
=> Pc 23827 price change free to priced bug fix

api/src/pcapi/routes/backoffice_v3/pro.py, api/tests/routes/backoffice_v3/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24092
=> (PC-24092)[BO] feat: rework pro search tracker in bo

api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/tests/routes/public/individual_offers/v1/get_event_dates_test.py, api/tests/routes/public/individual_offers/v1/get_events_test.py, api/tests/routes/public/individual_offers/v1/get_products_test.py
paginer par index les routes get des apis events et products
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23627
=> (PC-23627): paginate by index events and products apis

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230828T143954_ac3a0966b6c7_change_venue_provider_dummy_id_at_provider_to_null.py, api/src/pcapi/core/providers/api.py, api/src/pcapi/core/providers/exceptions.py, api/src/pcapi/routes/serialization/venue_provider_serialize.py, pro/src/apiClient/v1/models/VenueProviderResponse.ts
Autoriser les valeurs nuls dans la colonne venueIdAtOfferProvider de la table vennue_provider
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24011
=> (PC-24011) make venueIdAtOfferProvider column in venue_provider

pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.module.scss, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23886
WIP_ENABLE_NEW_USER_OFFERER_LINK
=> (PC-23886)[PRO] feat: get member invitation status

api/src/pcapi/core/mails/transactional/pro/offer_validation_to_pro.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/routes/backoffice_v3/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice_v3/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice_v3/offers/blueprint.py, api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py, api/tests/routes/backoffice_v3/collective_offer_templates_test.py, api/tests/routes/backoffice_v3/collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23150
=> (PC-23150)[BO] feat: add new mails for rejected offers

api/src/pcapi/core/subscription/ubble/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24117
=> (PC-24117)[API] fix: Change wording for default Ubble error

api/src/pcapi/routes/backoffice_v3/accounts/form.py, api/src/pcapi/routes/backoffice_v3/templates/components/history/actions.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24109
=> (PC-24109)[BO] feat: allow longer manual review comment

pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24039
8d98e-124b-40a5-9df1-8e7534882427)
=> (PC-24039)[PRO] fix: offerer next step style

pro/src/pages/ResetPassword/ResetPassword.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24096
Recentrer verticalement le bloc
=> (PC-24096)[PRO] fix: design set new password

api/src/pcapi/core/mails/transactional/pro/offer_validation_to_pro.py, api/tests/core/mails/transactional/pro/offer_validation_to_pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23150
=> Pc 23150 add new mails for offer rejection

api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_offers_test.py, pro/src/apiClient/v1/models/ListCollectiveOffersQueryModel.ts, pro/src/apiClient/v1/models/ListOffersOfferResponseModel.ts, pro/src/apiClient/v1/models/ListOffersQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/pages/OfferIndividualWizard/__specs__/OfferIndividualWizard.spec.tsx, pro/src/pages/OfferIndividualWizard/__specs__/OfferIndividualWizardAdmin.spec.tsx, pro/src/screens/OfferIndividual/StocksEventEdition/__specs__/StockEventEdition.spec.tsx, pro/src/screens/OfferIndividual/StocksThing/__specs__/StocksThing.edition.spec.tsx
valider le status de l'offre dans l'url
=> (PC-23790) fix: validate offer status

pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts, pro/src/screens/SignupJourneyForm/Offerers/Offerers.module.scss, pro/src/screens/SignupJourneyForm/Offerers/Offerers.tsx, pro/src/screens/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23979
[Capture vidéo du 29-08-2023 16:14:09.webm](https://github.com/pass-culture/pass-culture-main/assets/106379750/5a225dd3-bc55-4fff-8bf5-397fa101e51d)
=> (PC-23979)[PRO] refactor: rollback attachment button under FF and add e2e test

api/src/pcapi/algolia_settings_venues.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24107
- [X ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [X ] J'ai ajouté des screenshots pour d'éventuels changements graphiques
=> (PC-24107)[ALGOLIA] Change type of replica index

pro/cypress/e2e/createAccount.cy.ts
=> (BSR)[PRO] fix: e2e createAccount

api/src/pcapi/routes/public/collective/__init__.py, api/src/pcapi/routes/public/collective/endpoints/national_programs.py, api/tests/routes/public/blueprint_v2_openapi_test.py, api/tests/routes/public/collective/endpoints/national_programs_test.py, pro/src/apiClient/v2/index.ts, pro/src/apiClient/v2/models/ListNationalProgramsResponseModel.ts, pro/src/apiClient/v2/models/NationalProgramModel.ts, pro/src/apiClient/v2/services/ApiOffresCollectivesService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23717
Renvoyer la liste des dispositifs nationaux. Sur l'API publique collective.
=> (PC-23717)[API] feat: collective api: return known national programs

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230830T095656_eff2f403eaac_create_table_collectiveoffereducationalredactor_and_.py, api/src/pcapi/core/educational/api/favorites.py, api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/adage_iframe/__init__.py, api/src/pcapi/routes/adage_iframe/favorites.py, api/src/pcapi/routes/adage_iframe/serialization/favorites.py, api/tests/core/offerers/test_api.py, api/tests/routes/adage_iframe/post_favorite_offer_test.py, api/tests/routes/adage_iframe/post_favorite_template_test.py, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23987
recreate PR
=> (PC-23987)[API] feat: add favorite for adage user to offer and template

api/src/pcapi/core/mails/transactional/pro/offerer_attachment_invitation.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/exceptions.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/core/mails/transactional/pro/offerer_attachment_invitation.py, api/tests/core/offerers/test_api.py, api/tests/routes/pro/post_offerer_invite_member_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/InviteMemberQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23309
- S'aligner au front pour inviter qu'un seul email à la fois.
- Ajout de tests et refacto.
- Update du client front.
- Ajout des templates brevo, et envoyer les mails d'invitation selon le cas de l'invité.
=> (PC-23309)[API] link offerer mails

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230828T143230_62cd1889b6ac_add_extra_info_column_on_external_booking_table.py, api/src/pcapi/connectors/ems.py, api/src/pcapi/connectors/serialization/ems_serializers.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/external_bookings/ems/client.py, api/src/pcapi/core/external_bookings/factories.py, api/src/pcapi/core/external_bookings/models.py, api/tests/core/bookings/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23113
=> (PC-23113)[API] feat: EMS annulation

pro/src/pages/Signup/SignupContainer/SignupContainer.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24164
Alors que le mot de passe est valide, le message ne se met pas à jour
=> (PC-24164)[PRO] fix: signupContainer form password validation

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230831T143423_41c2cf970790_add_titelive_epagine_provider.py, api/src/pcapi/connectors/titelive.py, api/src/pcapi/core/providers/constants.py, api/src/pcapi/core/providers/factories.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/local_providers/install.py, api/tests/connectors/titelive/titelive_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24088
=> (PC-24088)[API] feat: add titelive epagine synchro logs

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/external_bookings/serialize.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/native/v1/bookings.py, api/src/pcapi/routes/public/booking_token/v2/endpoints.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py, api/tests/core/bookings/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/public/booking_token/v2/patch_cancel_booking_by_token_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23880
Call a distant server to cancel a booking
=> (PC-23880)[API] fix: cancel external bookings

pro/src/core/FirebaseEvents/constants.ts, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24017
Ajout d'un tracker au clic sur le bouton "Ajouter un collaborateur" de la page d'une structure
FF à activer: WIP_ENABLE_NEW_USER_OFFERER_LINK
=> (PC-24017)[PRO] feat: add tracker for add collaborator button

api/src/pcapi/routes/pro/stocks.py
Alow creating stocks when soft deleted
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24124
=> (PC-24124)[PRO] fix: allow creating stocks when soft deleted

pro/src/core/FirebaseEvents/constants.ts, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24019
Ajout d'un tracker au clic sur le bouton "Inviter" de la page d'une structure
FF à activer: WIP_ENABLE_NEW_USER_OFFERER_LINK
=> (PC-24019)[PRO] feat: add invite collaborator tracker offerer

api/src/pcapi/connectors/ems.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23113
=> (PC-23113)[API] fix: Handling null response when cancelling a booking

api/src/pcapi/routes/backoffice_v3/templates/venue/get.html, api/src/pcapi/routes/backoffice_v3/venues/blueprint.py, api/tests/routes/backoffice_v3/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24151
=> (PC-24151)[BO] feat: show provider and last sync date in venue page

api/src/pcapi/core/mails/transactional/users/email_address_change_confirmation.py, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/core/mails/transactional/test_send_transactional_email.py, api/tests/core/mails/transactional/users/email_address_change_confirmation_test.py, api/tests/routes/backoffice_v3/accounts_test.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/authentication_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23634
=> (PC-23634)[API] feat: Use new token class in email validation

api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/external_bookings/serialize.py, api/src/pcapi/routes/native/v1/bookings.py, api/tests/routes/native/v1/bookings_test.py
fixer un nombre de caractères maximum pour le code barre et le numéro de place sur la réponse de l'api externe pour l'api charlie
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24129
=> (PC-24129) set maximum number of characters for charlie api

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/stocks.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/tests/routes/public/individual_offers/v1/patch_date_test.py
prévenir le bénéficiaire lorsque la date d'événement est modifée
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24111
=> (PC-24111) prévenir le bénéficiaire lorsque la date d'événement est modifée

api/src/pcapi/routes/backoffice_v3/pro_users/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24201
=> (PC-24201)[BO] fix: add commit to pro user deletion

pro/src/components/SkipLinks/SkipLinks.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23781
Ne plus afficher une liste si il y a qu'un seul élément
Ajouter le aria-label à la nav
=> (PC-23781)[PRO] feat: add aria-label and dont show list for one element

pro/src/components/LegalInfos/LegalInfos.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24104
Objectif : 
Souligner les liens en dessous du formulaire d'inscription pour les rendre plus accessibles.
=> (PC-24104)[PRO] style: Underline pink links under signup form for a11Y.

api/src/pcapi/routes/native/v1/serialization/subscription.py, api/src/pcapi/routes/native/v1/subscription.py, api/tests/routes/native/v1/openapi_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24113
=> (PC-24113)[API] feat: Add maintenance page type to stepper route

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/offers/models.py, api/tests/core/bookings/test_api.py, api/tests/core/bookings/test_commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24137
=> Pc 24137 archive after 30 days even in mo longer free

pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24157
WIP_ENABLE_NEW_USER_OFFERER_LINK
=> (PC-24157)[PRO] fix: email attachment invitatio width

api/src/pcapi/core/permissions/models.py, api/src/pcapi/routes/backoffice_v3/templates/pro_user/get.html, api/src/pcapi/routes/backoffice_v3/users/blueprint.py, api/src/pcapi/routes/backoffice_v3/utils.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice_v3/conftest.py, api/tests/routes/backoffice_v3/helpers/unauthorized.py, api/tests/routes/backoffice_v3/pro_users_test.py, api/tests/routes/backoffice_v3/users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24085
=> (PC-24085)[BO] feat: Review permissions to suspend users

.github/workflows/deploy.yml
Ajouter une tâche de pre-migration dans la CI dans l'optique de sortir les migrations du chart helm.
=> (BSR): Add pre-migration task in CI

api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/backoffice_v3/pivots/contexts/__init__.py, api/src/pcapi/routes/backoffice_v3/pivots/contexts/cgr.py, api/src/pcapi/routes/backoffice_v3/pivots/contexts/ems.py, api/src/pcapi/routes/backoffice_v3/pivots/forms.py, api/src/pcapi/routes/backoffice_v3/templates/pivots/get.html, api/src/pcapi/routes/backoffice_v3/templates/pivots/get/ems.html, api/tests/routes/backoffice_v3/pivots_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23314
=>  (PC-23314)[BO] feat: Add EMS pivot page 

api/src/pcapi/routes/backoffice_v3/bookings/form.py, api/src/pcapi/routes/backoffice_v3/bookings/helpers.py, api/src/pcapi/routes/backoffice_v3/collective_bookings/blueprint.py, api/src/pcapi/routes/backoffice_v3/collective_bookings/form.py, api/src/pcapi/routes/backoffice_v3/individual_bookings/blueprint.py, api/src/pcapi/routes/backoffice_v3/individual_bookings/form.py, api/src/pcapi/routes/backoffice_v3/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice_v3/templates/individual_bookings/list.html, api/tests/routes/backoffice_v3/collective_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24108
Première étape de réduction du code dupliqué sur la recherche des réservations individuelles et collectives.
En l'occurrence, mutualisation du formulaire de recherche des réservations et factorisation de l'appel aux données.
Le formulaire diffère encore des choix de la plage de dates, j'ai vu avec Solène, on a uniformisé la recherche par date de création : tous en DateRangePicker.
D'autres optimisations viendront dans d'autres PR et sont listées dans le Jira
Les tests déjà en place n'ont pas échoué, le refactoring me semble donc transparent
=> (PC-24108)[BO] refactor: merge get booking individual or collective

api/src/pcapi/routes/public/individual_offers/v1/products.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23856
=> (PC-23856)[API] fix: current_api_key does not exists in this context

api/src/pcapi/routes/backoffice_v3/bookings/helpers.py
Corrige une erreur introduit durant le refactoring de la recherche des réservations
=> (PC-24108)[BO] fix: error introduced during reservation search refactor

api/src/pcapi/connectors/ems.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24235
=> (PC-24235)[API] feat: Monitor EMS time response

api/src/pcapi/routes/backoffice_v3/finance/blueprint.py, api/src/pcapi/routes/backoffice_v3/templates/finance/incident/get/general.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23813
=> (PC-23813)[BO] feat: Display incident new total amount sum in details view

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230906T073247_9d1128058b6d_remove_national_program_feature_flag.py, api/src/pcapi/models/feature.py, pro/src/components/CollectiveOfferSummary/__specs__/CollectiveOfferSummary.spec.tsx, pro/src/components/CollectiveOfferSummary/components/CollectiveOfferTypeSection/CollectiveOfferTypeSection.tsx, pro/src/core/OfferEducational/adapters/getCollectiveOfferFormDataAdapter.ts, pro/src/core/OfferEducational/utils/createOfferFromBookableOffer.ts, pro/src/core/OfferEducational/utils/createOfferFromTemplate.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferDetails.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx, pro/src/pages/CollectiveOfferCreation/CollectiveOfferCreation.tsx, pro/src/pages/CollectiveOfferCreation/__specs__/CollectiveOfferCreation.spec.tsx, pro/src/pages/CollectiveOfferEdition/CollectiveOfferEdition.tsx, pro/src/pages/CollectiveOfferFromRequest/CollectiveOfferFromRequest.tsx, pro/src/pages/CollectiveOfferFromRequest/__specs__/CollectiveOfferFromRequest.spec.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/DuplicateOfferCell.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/__specs__/DuplicateOfferCell.spec.tsx, pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplicationScreen.tsx, pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx, pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx, pro/src/screens/OfferEducational/useOfferEducationalFormData.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23527
Supprimer le FF `WIP_ENABLE_NATIONAL_SYSTEM`
Contexte : 
Feature flag activant la possibilité d'ajouter un dispositif national sur les offres collectives (vitrine ou non). 
Parcours à tester : 
- Création/Edition/Duplication d'offres collectives (vitrine ou non)
=> Pc 23527 eac remove national system ff

api/src/pcapi/core/mails/transactional/users/ubble/constants.py, api/src/pcapi/core/mails/transactional/users/ubble/reminder_emails.py, api/src/pcapi/core/mails/transactional/users/ubble/subscription_document_error.py, api/src/pcapi/core/subscription/commands.py, api/src/pcapi/core/subscription/ubble/models.py, api/tests/core/mails/transactional/users/ubble_ko_reminder_test.py, api/tests/core/subscription/ubble/test_api.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24160
=> Pc 24160 fix ubble reminders templates

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230906T095014_3ce98448ac72_FAKE_update_role_names.py, api/src/pcapi/alembic/versions/20230907T084743_f2f67d2fb7f3_update_role_names.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21913
Round 2, pour éviter des problèmes de migration
=> (PC-21913)[BO] feat: rename some role names

pro/src/screens/OfferEducational/OfferEducationalForm/FormVenue/FormVenue.tsx, pro/src/screens/OfferType/OfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24292
Changer le lien pour faire une demande de référecement DMS
Lien accessible à la création d'offre collective lorsque le lieu n'est pas éligible
=> (PC-24292)[PRO] feat: change dms creation link in offerType and formVenue

api/src/pcapi/routes/backoffice_v3/auth.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21913
=> (PC-21913)[BO] feat: unrecognized google group names don't crash

pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/adapters/__specs__/postInviteMemberAdapter.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/adapters/postInviteMemberAdapter.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24180
WIP_ENABLE_NEW_USER_OFFERER_LINK
=> (PC-24180)[PRO] feat: add adapter for inviteMember and notify correct messages

.git-blame-ignore-revs
Ne pas avoir l'historique de git blame pollué par une refacto inintéressante.
=> (BSR)[BO] feat: add bov3 removal to git blame ignore

api/src/pcapi/core/fraud/api.py, api/src/pcapi/core/mails/transactional/users/fraud_emails.py, api/src/pcapi/core/subscription/api.py, api/tests/core/mails/transactional/users/fraud_email_test.py, api/tests/core/subscription/test_api.py, api/tests/scripts/beneficiary/fixture.py, api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22449
=> Pc 22449 19yo dms requires manual fraud review

api/src/pcapi/core/fraud/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22449
=> (PC-22449)[API] refactor: Remove unused imports in fraud.api

pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/AttachmentInvitations.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24182
FF: WIP_ENABLE_NEW_USER_OFFERER_LINK
J’ajoute un collaborateur 
→ il est le premier qui s’affiche dans la liste des collaborateurs dont le statut est en attente (il s’affiche tout en haut de la liste).
=> (PC-24182)[PRO] feat: order member list by status and alphabetical order

api/src/pcapi/core/users/api.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24197
=> (PC-24197)[API] feat: Change user password when suspended for suspicious login

pro/src/screens/OfferIndividual/StocksEventCreation/StocksEventCreation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24245
=> (PC-24245)[PRO] fix: do not allow submit during submitting

api/src/pcapi/routes/adage_iframe/favorites.py, api/tests/routes/adage_iframe/delete_favorite_offer_test.py, api/tests/routes/adage_iframe/delete_favorite_template_test.py, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23988
=> (PC-23988)[API] feat: endpoints to delete collective offer and template favorite

api/src/pcapi/routes/pro/signup.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24118
=> (PC-24118)[API] feat: add rate limit by ip on pro signup route

api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/core/educational/models.py, api/tests/core/educational/api/test_institution.py, api/tests/core/educational/test_models.py, api/tests/routes/adage_iframe/get_educational_institution_with_budget_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24334
=> PC-24334-fix_remaining_credit(EAC): fix: calcul du budget restant d'un établissement

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23829
=> (PC-23829)[API] feat: add feature flag on reservation for offer

pro/src/pages/OfferIndividualWizard/__specs__/OfferIndividualWizard.spec.tsx
Essayer de réparer un test instable
=> (BSR)[PRO] fix: waitFor condition to try to fix shaky test

pro/package.json, pro/src/core/OfferEducational/utils/createOfferFromTemplate.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx, pro/src/pages/Offers/OffersRoute.tsx, pro/src/screens/OfferEducational/__specs__/OfferEducationalCreationOfferTypeStep.spec.tsx, pro/src/screens/OfferIndividual/Informations/__specs__/InformationsScreen.edition.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/Offerer.tsx, pro/src/ui-kit/Button/ButtonLink.tsx, pro/src/ui-kit/Button/__specs__/ButtonLink.spec.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23942
SOUS FF : `WIP_ENABLE_SEARCH_HISTORY_ADAGE`
On souhaite pouvoir visualiser les anciennes recherches que l'on a effectué, on peut aussi tous les supprimer
=> (PC-23942)[PRO] feat: adage search history

api/src/pcapi/connectors/titelive.py, api/src/pcapi/core/providers/titelive_api.py, api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24103
=> (PC-24103)[API] feat: handle thumbnails for titelive epagine synchro

api/src/pcapi/algolia_settings_collective_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23693
Mise à jour de la configuration Algolia des offres collectives
=> (PC-23693)[API] feat: algolia config update (collective offers)

.github/workflows/deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24242
=> (PC-24242) feat(ci): Run alembic post migration in ci

api/src/pcapi/routes/public/individual_offers/v1/products.py
Logguer les ean non trouvé sur la route post de création de produits par ean
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24204
=> (PC-24204) feat: log not found eans in products creation api

api/src/pcapi/core/offerers/api.py, api/tests/routes/pro/get_offerer_members_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24317
=> (PC-24317)[API] feat: sort members by status and emails in get offerer members

api/src/pcapi/routes/native/v1/authentication.py, api/src/pcapi/routes/native/v1/serialization/authentication.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24049
=> (PC-24049)[API] feat: Add recaptcha in signin

api/src/pcapi/core/mails/transactional/users/email_address_change_confirmation.py, api/src/pcapi/core/subscription/phone_validation/api.py, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/native/v1/account.py, api/tests/core/subscription/phone_validation/test_api.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23635
=> Pc 23635 phone validation token

pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23433
- Changements de texte avec le FF `WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY` d'activé.
=> (PC-23433)[PRO] feat: Wording changes with the FF enabled.

pro/src/pages/Home/Venues/Venue.scss, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23983
=> (PC-23983)[PRO] feat: Hide button when `WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY` is enabled.

api/src/pcapi/routes/backoffice/docs/JSDOC.md, api/src/pcapi/routes/backoffice/templates/layouts/base.html, api/src/pcapi/static/backoffice/js/addons/pc-form.js
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24139
=> (PC-24139)[BO] feat: forbid to submit a form multiple times.

api/src/pcapi/core/external/batch.py, api/src/pcapi/core/fraud/ubble/constants.py, api/src/pcapi/core/subscription/ubble/api.py, api/tests/core/subscription/ubble/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24036
=> (PC-24036)[API] feat: Add immediate reminder for Ubble retryable ko

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/cgr/client.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24080
=> (PC-24080)[API] fix: Log possible inconsistencies between our data and theirs

api/src/pcapi/scripts/backoffice_users/add_permissions_to_staging_specific_roles.py
Ticket Jira (ou description si BSR) : Réparer le script concerné
=> (BSR)[BO] fix: use correct role names for script

api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/src/pcapi/routes/public/individual_offers/v1/constants.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py
Ajouter les réponses possibles de l'api avec une description pour l'api d'offre individuelle
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23103
=> (PC-23103) add responses to indivual offer api doc

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23045
Correction des erreurs mypy sur master
=> (PC-23045)[API] fix: errors reported by mypy

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/routes/public/collective/serialization/offers.py, api/tests/routes/public/blueprint_v2_openapi_test.py, api/tests/routes/public/collective/endpoints/get_collective_offer_public_provider_test.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py, api/tests/routes/public/collective/endpoints/post_collective_offer_test.py, pro/src/apiClient/v2/models/GetPublicCollectiveOfferResponseModel.ts, pro/src/apiClient/v2/models/PatchCollectiveOfferBodyModel.ts, pro/src/apiClient/v2/models/PostCollectiveOfferBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24178
1. Permettre de renseigner le dispositif national lors de la création ou de l'édition d'une offre collective via l'api publique.
2. Ajouter cette information dans le modèle de réponse des offres collectives.
=> (PC-24178)[API] fix: collective api: add national program

pro/src/screens/OfferType/OfferType.module.scss, pro/src/screens/OfferType/OfferTypeIndividual/OfferTypeIndividual.tsx, pro/src/screens/OfferType/OfferTypeIndividual/__specs__/OfferTypeIndividual.spec.tsx, pro/src/screens/OfferType/__specs__/OfferType.navigation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27769
activer WIP_CATEGORY_SELECTION
créer une offre en venant d'un lieu
=> (PC-27769)[PRO] fix: improve design on new individual hub

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230911T132450_beb392b1584a_add_offerer_ds_token_column.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerers_with_pro_users.py, api/src/pcapi/scripts/offerer/generate_dms_tokens.py, api/tests/routes/pro/get_offerer_test.py, pro/src/apiClient/v1/models/GetOffererResponseModel.ts, pro/src/core/Offerers/types.ts, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/__specs__/CreationLinks.spec.tsx, pro/src/pages/Home/Offerers/__specs__/CreationLinks.tracker.spec.tsx, pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/Offerer.spec.ts, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24311
- Ajout de la colonne dmsToken à la table Offerer
- Ajout du script de rattrapage
- Changement de la vue pour le front.
=> (PC-24311)[API] feat: Added dsToken to offerer table.

pro/src/pages/Offerers/Offerer/OffererDetails/Offerer.ts, pro/src/pages/Offerers/Offerer/OffererDetails/OffererDetails.module.scss, pro/src/pages/Offerers/Offerer/OffererDetails/OffererDetails.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24280
- Affichage du token ds côté front sur la page structure.
=> Pc 24280 offerer dms

api/src/pcapi/core/permissions/models.py, api/src/pcapi/routes/backoffice/pivots/blueprint.py, api/src/pcapi/routes/backoffice/providers/blueprint.py, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/pivots_test.py, api/tests/routes/backoffice/providers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24155
=> (PC-24155)[BO] feat: new permission MANAGE_TECH_PARTNERS

pro/src/pages/Offerers/Offerer/OffererDetails/Offerer.ts, pro/src/pages/Offerers/Offerer/OffererDetails/OffererDetails.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx
Correction du bug sur master + cas dsToken null.
=> (BSR)[PRO] feat: fix: Fixed dsToken type and handle null type.

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230908T134502_884b3016640c_add_bank_account_table.py, api/src/pcapi/alembic/versions/20230911T155328_6ad1b6cb8328_add_venue_bank_account_link.py, api/src/pcapi/core/finance/factories.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/tests/core/finance/test_models.py, api/tests/core/offerers/test_api.py, api/tests/core/offerers/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23401
=> (PC-23401)[API] feat: Add new finance models

api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24443
=> (PC-24443)[API] fix: EMS convernt local beginning datetime to UTC

api/src/pcapi/core/categories/subcategories_v2.py, api/tests/routes/pro/post_offer_test.py
(new general terms of use)
Ticket Jira : https://passculture.atlassian.net/browse/PC-24198
=> (PC-24198)[API] feat: disable subcategory BON_ACHAT_INSTRUMENT

api/src/pcapi/connectors/ems.py, api/src/pcapi/core/bookings/api.py, api/tests/core/external_bookings/ems/test_client.py, api/tests/routes/native/v1/bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24407
[PR front](https://github.com/pass-culture/pass-culture-app-native/pull/5283)
->
=> (PC-24407)[API] feat: Handle sold-out showtime case when booking one

api/src/pcapi/routes/backoffice/users/blueprint.py, api/tests/routes/backoffice/users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24439
=> (PC-24439)[BO] fix: permission to suspend/unsuspend user

pro/src/hooks/useNewIndividualOfferType.ts, pro/src/screens/OfferType/OfferTypeIndividual/OfferTypeIndividual.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24381
- il ne fallait pas oublier d'ajouter la variable au tableau de dépendances du useEffect...
=> (PC-24381)[PRO] fix: ab testing for new individual hub

pro/src/pages/LostPassword/LostPassword.module.scss, pro/src/pages/LostPassword/LostPassword.tsx, pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23778
=> (PC-24225)[PRO] fix: min height of lost password and signup layout

pro/src/pages/Home/Venues/Venue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24385
Déplacer le aria-label sur l'icone pour les fleches déplier sur la home
=> (PC-24385)[PRO] refactor: move aria-label to home fold arrow icon

pro/src/pages/Offers/Offers/OffersTableHead/OffersTableHead.tsx, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss, pro/src/ui-kit/form/Checkbox/Checkbox.stories.tsx, pro/src/ui-kit/form/Checkbox/Checkbox.tsx, pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.stories.tsx, pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.tsx, pro/src/ui-kit/form/CheckboxGroup/CheckboxGroupItem.tsx, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.stories.tsx, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24194
Ajout de la outline noire sur tous les types de checkbox/radio du ui-kit 
EDIT nouveaux screens à jour :
=> (PC-24194)[PRO] style: update checkbox/radio focus state

pro/src/components/Banner/BannerRGS.tsx, pro/src/components/OfferIndividualForm/Categories/Categories.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/CookiesFooter/CookiesFooter.tsx, pro/src/pages/Home/ProfileAndSupport/Support.tsx, pro/src/pages/Signup/SignupContainer/OperationProcedures/OperationProcedures.tsx, pro/src/screens/OfferIndividualConfirmation/OfferIndividualConfirmation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24226
=> (PC-24226)[PRO] feat: don't duplicate info in alt

api/src/pcapi/core/offerers/models.py, pro/src/apiClient/v1/models/VenueTypeCode.ts
Modification de la description des "DISTRIBUTION_STORE"
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-19994
=> (PC-19994)[API] feat: changed distribution dropdown description

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24483
=> (PC-24483)[API] fix: Check user age just before recredit

pro/yarn.lock
Le job github "update-api-client" échoue sur toutes les branches : 
https://github.com/pass-culture/pass-culture-main/actions/runs/6232129295/job/16914750137?pr=8242
=> (BSR)[PRO] fix: update api client task failed

api/src/pcapi/core/educational/api/favorites.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/adage_iframe/authentication.py, api/src/pcapi/routes/adage_iframe/serialization/adage_authentication.py, api/tests/core/educational/api/test_favorites.py, api/tests/routes/adage_iframe/get_authenticate_test.py, pro/src/apiClient/adage/models/AuthenticatedResponse.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24263
=> PC-24263-redactor_favorites_count(EAC): feat: renvoyer le nombre total de favoris d'un utilisateur

pro/src/pages/Offers/Offers/Offers.tsx, pro/src/screens/Offers/NoResults/NoResults.tsx, pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24388
=> (PC-24388)[PRO] fix: change reset filters to button

pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss
- (PC-24391)[PRO] feat: keep title offer in black when deactivated
- (PC-24391)[PRO] fix: focus on list offer checkboxes
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24391
=> (PC-24391)[PRO] feat: leave offer title color black when deactivated

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24540
=> (PC-24540)[API] feat: Add feature flag for mock Ubble

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230906T152100_eade6ec3120d_make_cgr_password_not_nuallable.py, api/src/pcapi/connectors/cgr/cgr.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/settings.py, api/tests/connectors/cgr/api_cgr_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23618
=> (PC-23618)[API] Remove CGR_PASSWORD_SECRET & CGR_API_URL

.github/workflows/update-api-client-template.yml
Résoud https://passcultureteam.slack.com/archives/C04MZ0AKC0P/p1691679131475889
=> (BSR)[PRO] fix: do not fail update-api-client when yarn.lock changes

.github/workflows/update-api-client-template.yml
=> (BSR)[PRO] ci: Add a flag path

api/src/pcapi/connectors/beamer.py, api/src/pcapi/tasks/CONTRIBUTING.md, api/src/pcapi/tasks/__init__.py, api/tests/connectors/beamer_test.py
Lien du ticket Jira : https://passculture.atlassian.net/browse/PC-24548
=> (PC-24548)[API] fix: beamer cloud task

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/utils.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23801
=> (PC-23801)[BO] fix: timeout when using advanced search in individual offers

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py, api/src/pcapi/scripts/rebuild_staging/anonymize.sql, api/src/pcapi/settings.py
ajout de l'url de notification de l'api externe aux données de la sandbox et script d'anonymisation
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24401
=> (PC-24401)[API] feat: add external api notification url to sandbox data

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24574
=> (PC-24574)[API] fix: only active reimbursement points in generated csv list

api/src/pcapi/routes/backoffice/templates/layouts/connected.html
Ticket Jira (ou description si BSR) : rajouter une permission requise à l'affichage du lien vers la page des actions sur les lieux
=> (BSR)[BO] fix: add required permission to acces venue page

pro/src/components/Callout/Callout.module.scss, pro/src/components/Callout/Callout.stories.tsx, pro/src/components/Callout/Callout.tsx, pro/src/components/Callout/__specs__/Callout.spec.tsx, pro/src/components/Callout/types.ts, pro/src/styles/variables/_colors.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24441
Préparation des prochains types de banières.
=> (PC-24441)[PRO] feat: Preparing for the new banner types.

api/src/pcapi/routes/public/individual_offers/v1/products.py, api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23891
=> (PC-23891)[API] feat: add physical music subcategory migration commands

api/.env.integration, api/.env.staging, api/src/pcapi/connectors/beamer.py, api/tests/connectors/beamer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24548
=> (PC-24548)[API] fix: beamer handling of venue attributes

pro/src/components/Tutorial/Step/CreateVenue.tsx, pro/src/components/TutorialDialog/__specs__/TutorialDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24484
Wording sous FF: WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY dans la deuxième étape du tutoriel
=> (PC-24484)[PRO] feat: add wording in create venue tutorial step under FF

api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/utils/urls.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24344
=> (PC-24344)[BO] feat: link to PC pro offers from offerers details page

api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/routes/backoffice/utils.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24595
=> (PC-24595)[BO] fix: user name and link missing in offerey history with 'deleted' action

api/src/pcapi/core/users/api.py
Correction de la génération des dsToken à l'import des utilisateurs.
=> (BSR)[API] fix: Fix dsToken generation for imported users.

api/src/pcapi/routes/backoffice/templates/venue/get.html
Ticket Jira (ou description si BSR) : C'est plus joli avec du rose
=> (BSR)[BO] feat: make the trashcan pink

api/src/pcapi/tasks/decorator.py
2 commits à relire séparément.
=> (BSR)[API] Décorateur "@task" : rendre le body (payload) obligatoire et corriger les annotations de type

api/src/pcapi/core/mails/transactional/pro/reset_password_to_pro.py, api/src/pcapi/core/mails/transactional/users/reset_password.py, api/src/pcapi/core/mails/transactional/users/suspicious_login_email.py, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/email/update.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/user_generation/blueprint.py, api/src/pcapi/routes/native/v1/authentication.py, api/src/pcapi/routes/pro/users.py, api/src/pcapi/routes/shared/passwords.py, api/src/pcapi/sandboxes/scripts/getters/pro_11_lost_password.py, api/src/pcapi/sandboxes/scripts/utils/helpers.py, api/tests/core/mails/transactional/users/email_address_change_test.py, api/tests/core/mails/transactional/users/reset_password_test.py, api/tests/core/mails/transactional/users/suspicious_login_email_test.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/pro/get_user_token_test.py, api/tests/routes/shared/post_reset_password_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23633
=> Pc 23633 use new token for reset password

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24632
Sous ff : `WIP_ENABLE_SEARCH_HISTORY_ADAGE`
à tester sur adage 
HOTFIX : Ne pas afficher le footer car le lien n'est pas encore disponible et ajouter un "s" à Partenaire culturels
=> (PC-24632)[PRO] fix: comment footer and add s to autocomplete wording

pro/src/components/Callout/Callout.module.scss, pro/src/components/Callout/Callout.stories.tsx, pro/src/components/Callout/Callout.tsx, pro/src/styles/variables/_colors.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24441
Retours graphiques sur les nouveaux types de bannières.
=> (PC-24441)[PRO] feat: New banner types fixes.

api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/get_venues_test.py
Ajout du type de lieu dans la réponse de la route pro des lieux
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24608
=> (PC-24608)[API] feat: add venue type in route response

api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/serialization/finance_serialize.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerers_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23405
=> (PC-23405)[API] feat: Add Offerer business properties

api/src/pcapi/core/mails/transactional/__init__.py, api/src/pcapi/core/mails/transactional/pro/venue_needs_picture.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24465
=> (PC-24465)[BO] feat: send mail if venue set permanent with no thumb

api/src/pcapi/core/permissions/models.py, api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/admin_test.py, api/tests/routes/backoffice/conftest.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24627
=> (PC-24627)[BO] feat: new permission to read admin accounts

api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Il manquait la recherche avec seulement une date de début d'événement ou uniquement une date de fin.
Ticket Jira : https://passculture.atlassian.net/browse/PC-24274
=> (PC-24108)[BO] fix: improve tests get booking by event date

pro/src/apiClient/v1/models/GetOffererBankAccountsResponseModel.ts, pro/src/apiClient/v1/models/ManagedVenues.ts
=> (BSR)[PRO] fix: Add missing items to match the API

api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/pro/signup.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/routes/serialization/users.py, api/tests/core/offerers/test_api.py, api/tests/routes/pro/post_save_new_onboarding_data_test.py, api/tests/routes/pro/signup_pro_V2_test.py, pro/src/apiClient/v1/models/ProUserCreationBodyV2Model.ts, pro/src/apiClient/v1/models/SaveNewOnboardingDataQueryModel.ts, pro/src/hooks/useInitReCaptcha.ts, pro/src/pages/LostPassword/LostPassword.tsx, pro/src/pages/ResetPassword/ResetPassword.tsx, pro/src/pages/Signup/SignupContainer/SignupContainer.tsx, pro/src/pages/Signup/SignupContainer/__specs__/SignupContainer.spec.tsx, pro/src/pages/Signup/SignupContainer/constants.ts, pro/src/screens/SignupJourneyForm/Validation/Validation.tsx, pro/src/screens/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx, pro/src/utils/recaptcha.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24535
- Mise en place de recaptcha pour deux routes.
=> Pc-24534 re captcha

api/src/pcapi/core/finance/commands.py, api/src/pcapi/models/pc_object.py, api/src/pcapi/routes/error_handlers/generic_error_handlers.py, api/src/pcapi/routes/serialization/serializer.py, api/src/pcapi/utils/human_ids.py, api/tests/core/finance/test_commands.py, api/tests/models/pc_object_test.py, api/tests/routes/pro/get_collective_booking_test.py, api/tests/routes/pro/get_collective_offer_template_test.py, api/tests/routes/serialization/dictifier_test.py
=> (BSR)[API] chore: remove now unused humanized methods

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/pro.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/search/result.html, api/src/pcapi/routes/backoffice/templates/components/search/result_card.html, api/src/pcapi/routes/backoffice/templates/components/search/result_card_offerer.html, api/src/pcapi/routes/backoffice/templates/components/search/result_card_venue.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24177
=>  (PC-24177)[BO] feat: Tracker recherche Acteurs Culturels

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py
Lien du ticket Jira : https://passculture.atlassian.net/browse/PC-23807
=> (PC-23807)[API] feat: add thumbnails for titelive music in sandbox

pro/src/components/StocksEventList/StocksEventList.module.scss, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/components/StocksEventList/stocksFiltering.ts, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/form/__specs__/onSubmit.spec.ts, pro/src/screens/IndividualOffer/StocksEventCreation/form/onSubmit.ts, pro/src/screens/IndividualOffer/StocksEventEdition/EventCancellationBanner.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx, pro/src/screens/IndividualOffer/StocksSummary/RecurrenceSummary.tsx, pro/src/screens/IndividualOffer/StocksSummary/StocksSummary.module.scss, pro/src/screens/IndividualOffer/StocksSummary/StocksSummary.tsx, pro/src/screens/IndividualOffer/Summary/StockSection/StockSection.tsx, pro/src/utils/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24423
=> (PC-24423)[PRO] feat: Remplacement de la partie "dates et capacités" au format texte par la vue en liste paginée

pro/src/ui-kit/Tag/Tag.stories.tsx, pro/src/ui-kit/Tag/Tag.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24706
Migrer la story du composant tag vers la norme csf3
=> (PC-24706)[PRO] chore: move tag story to csf3

pro/src/pages/AdageIframe/app/components/OffersFavorites/__specs__/OffersFavorites.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24756
**Objectif**
Correction de l'import qui casse le lint des fichiers ts dans la pipeline de déploiement.
=> (PC-24756)[PRO] fix: Fix import userEvent in OffersFavorites.spec.tsx

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py
=> (BSR)[API] feat: upgrade thumb builder for sandbox

pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/components/IndividualOfferBreadcrumb/IndividualOfferBreadcrumb.tsx, pro/src/components/IndividualOfferBreadcrumb/__specs__/IndividualOfferBreadcrumb.spec.tsx, pro/src/components/IndividualOfferBreadcrumb/constants.ts, pro/src/components/IndividualOfferForm/ImageUploaderOffer/__specs__/ImageUploaderOffer.tracker.spec.tsx, pro/src/components/IndividualOfferForm/__specs__/IndividualOfferForm.spec.tsx, pro/src/components/StocksEventList/__specs__/StocksEventList.spec.tsx, pro/src/core/Offers/utils/__specs__/getIndividualOfferUrl.spec.ts, pro/src/core/Offers/utils/getIndividualOfferUrl.ts, pro/src/pages/IndividualOfferWizard/BookingsSummary/BookingsSummary.tsx, pro/src/pages/IndividualOfferWizard/Confirmation/__specs__/Confirmation.spec.tsx, pro/src/pages/IndividualOfferWizard/PriceCategories/__specs__/PriceCategories.spec.tsx, pro/src/pages/IndividualOfferWizard/Stocks/__specs__/Stocks.spec.tsx, pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.tsx, pro/src/screens/IndividualOffer/BookingsSummary/__specs__/BookingsSummary.spec.tsx, pro/src/screens/IndividualOffer/Informations/__specs__/InformationsScreen.RouteLeavingGuard.spec.tsx, pro/src/screens/IndividualOffer/Informations/__specs__/InformationsScreen.creation.spec.tsx, pro/src/screens/IndividualOffer/Informations/__specs__/InformationsScreen.draft.spec.tsx, pro/src/screens/IndividualOffer/Informations/__specs__/InformationsScreen.edition.spec.tsx, pro/src/screens/IndividualOffer/Informations/__specs__/InformationsScreen.spec.tsx, pro/src/screens/IndividualOffer/PriceCategoriesSummary/__specs__/PriceCategoriesSummary.spec.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StocksEventEdition.RouteLeavingGuard.spec.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StocksEventEdition.tracker.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.RouteLeavingGuard.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.draft.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/screens/IndividualOffer/Summary/__specs__/Summary.spec.tsx, pro/src/screens/IndividualOffer/Template/__specs__/Template.spec.tsx, pro/src/utils/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23830
=> (PC-23830)[PRO] feat: Ajouter un onglet vide "Réservations" aux onglets

.github/workflows/update-api-client-template.yml, pro/scripts/generate_api_client_local.sh
BSR
- l'étape `Check if there are changes` n'était pas joué dans le bon dossier (pro) la condition suivante était toujours fausse
tests et succès ici : https://github.com/pass-culture/pass-culture-main/actions/runs/6328866635/job/17187970745?pr=8406
- le script `pro/scripts/generate_api_client_local.sh` pouvait fail sans retourner le bon statut
- retry on error :
-> test quand ça fail : https://github.com/pass-culture/pass-culture-main/actions/runs/6337289029/job/17212064613?pr=8406
-> test quand ça fail & réussit (coup de chance ça!) : https://github.com/pass-culture/pass-culture-main/actions/runs/6337350670/job/17212260433?pr=8406
```
$ ./scripts/generate_api_client_local.sh
{
stack: 'ResolverError: Error downloading http://localhost/v2/openapi.json \n' +
'socket hang up\n' +
'    at …
```
=> (BSR)[PRO] ci: fix pro update api client

api/src/pcapi/routes/adage_iframe/favorites.py, api/src/pcapi/routes/adage_iframe/redactor.py, api/src/pcapi/routes/adage_iframe/security.py, api/src/pcapi/routes/adage_iframe/serialization/adage_authentication.py, api/tests/routes/adage_iframe/post_save_redactor_preference_test.py, api/tests/routes/adage_iframe/security.py
ATTENTE DES TICKETS FAVORIES AVANT CONTINUER LE TRAVAIL
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24179
=> (PC-24179)[API] refactor: authenticated_authentification's mail can't be None

api/src/pcapi/core/finance/api.py
We were logging errors when a non-used booking was cancelled. In that
case, there is no event (because the booking has never been used).
We must not log an error.
=> (BSR)[API] fix: Better error check in `cancel_latest_event()`

.github/workflows/deploy-pro-pr-version-generic.yml, .github/workflows/node-quality-check.yml, .github/workflows/node-run-command.yml, .github/workflows/node-type-check.yml, .github/workflows/tests-pro.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24761
=> (PC-24761)[PRO] ci: use gcs runner cache

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py, api/src/pcapi/sandboxes/scripts/creators/industrial/utils.py
=> Bsr upgrade sandbox

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/Callout.tsx, pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/PendingBankAccountCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx, pro/src/components/Callout/__specs__/Callout.spec.tsx, pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx, pro/src/components/Callout/__specs__/PendingBankAccountCallout.spec.tsx, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx, pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24267
- Petit refactor de la gestion du mode "titre uniquement" des bannière.
- Affichage de la bannière suivi de dossier DS.
=> (PC-24267)[PRO] feat: track ds application banner.

api/src/pcapi/core/finance/siret_api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/permissions/models.py, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/backoffice/venues/form.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py, api/tests/core/finance/test_siret_api.py, api/tests/core/offerers/test_models.py, api/tests/routes/backoffice/helpers/html_parser.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24538
=> (PC-24538)[BO] feat: remove SIRET from a venue

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/educational/models.py, api/tests/core/bookings/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24711
=> (PC-24711)[API] fix: reimbursement rate

api/src/pcapi/core/categories/subcategories_v2.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/serialization/utils.py, api/tests/routes/pro/get_categories_test.py, api/tests/routes/public/individual_offers/v1/get_event_categories_test.py
Lien du ticket Jira : https://passculture.atlassian.net/browse/PC-24655
=> (PC-24655)[API] feat: add get event categories route

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24697
Ajouter les suggestions dans l'historique de recherche quand on clique dessus
=> (PC-24697)[PRO] feat: add suggestion to history on click

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230928T130528_14e9b22809ef_add_hmac_key_column_to_provider_table.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/backoffice/providers/blueprint.py, api/src/pcapi/routes/backoffice/providers/forms.py, api/src/pcapi/routes/backoffice/templates/components/forms/string_field.html
Ajout d'une clé hmac à la table provider qui est générée automatiquement à la création d'un provider
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24717
=> (PC-24717): add hmac key column

pro/src/components/IndividualOfferForm/utils/__specs__/setInitialFormValues.spec.ts, pro/src/core/Offers/adapters/getIndividualOfferAdapter/__specs__/serializers.spec.ts, pro/src/core/Offers/adapters/getIndividualOfferAdapter/serializers.ts, pro/src/core/Offers/types.ts, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx, pro/src/screens/IndividualOffer/IndivualOfferLayout/__specs__/IndivualOfferLayout.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/__specs__/serializer.spec.ts, pro/src/utils/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21354
Ne pas afficher le bouton activer si l'offre n'est pas publiable
=> (PC-21354)[PRO] feat: hide activate button when offer is not activable

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/Callout.module.scss, pro/src/components/Callout/Callout.tsx, pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/PendingBankAccountCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx, pro/src/components/Callout/__specs__/Callout.spec.tsx, pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx, pro/src/components/Callout/__specs__/PendingBankAccountCallout.spec.tsx, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx, pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24297
- Affichage d'une bannière quand l'offerer a des lieux qui ne sont pas liés à des comptes bancaires.
=> (PC-24297)[PRO] feat: Display a banner for venues without bank account.

pro/src/pages/Offers/Offers/OfferItem/Cells/BookingLinkCell/BookingLinkCell.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/DeleteDraftCell/DeleteDraftCell.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/DuplicateOfferCell.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/EditOfferCell/EditOfferCell.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/EditStocksCell/EditStocksCell.tsx, pro/src/screens/SignupJourneyForm/Activity/ActivityForm.tsx, pro/src/ui-kit/Button/Button.tsx, pro/src/ui-kit/ListIconButton/ListIconButton.stories.tsx, pro/src/ui-kit/ListIconButton/ListIconButton.tsx, pro/src/ui-kit/Tooltip/Tooltip.module.scss, pro/src/ui-kit/Tooltip/Tooltip.tsx, pro/src/ui-kit/Tooltip/useTooltipProps.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24189
- implement onMouseOver onMouseOut onFocus onBlur onKeyDown for Tooltip
on parent to be accessible
=> (PC-24189)[PRO] feat: make Tooltip accessible

pro/src/ui-kit/Tooltip/Tooltip.stories.tsx, pro/src/ui-kit/Tooltip/__specs__/Tooltip.spec.tsx, pro/src/utils/__specs__/getLabelString.spec.tsx
=> (BSR)[PRO] fix: ts errors on tooltip

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
=> (BSR)[API] Correction + simplification de `cancel_latest_event()`

api/src/pcapi/core/external_bookings/ems/client.py, api/tests/core/offers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24804
Corrige cette issue : https://sentry.passculture.team/organizations/sentry/issues/428040
=> (PC-24804)[API] fix: Handle sold out EMS case on `get_offer`

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20230929T120236_d41989bc9019_add_bank_account_id_column_to_action_history_table.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/repository.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/history/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/LinkVenueToBankAccountBodyModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24313
=> (PC-24313)[API] feat: Allow users of an offerer to link venues to a bank account

pro/package.json, pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx, pro/src/pages/IndividualOfferWizard/Confirmation/__specs__/Confirmation.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx, pro/src/vitest.setup.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21359
=> (PC-21359)[PRO] refactor: remove navigation changes warning from exceptions list

pro/src/ui-kit/Tooltip/useTooltipProps.ts
=> (BSR)[PRO] fix: tooltip should not be displayed by default

README.md, pro/README.md
BSR
- enlever du code déprécié du readme de main
- rajouter un lien vers le readme de pro
- rajouter un cas de "troubleshooting" dans le readme de pro
=> (BSR)[PRO] docs: update main readme & pro readme

api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_event_show_types_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-24657
=> (PC-24657)[API] feat: add get show types route to individual api

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/offers/test_repository.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/StocksOrderedBy.ts, pro/src/apiClient/v1/models/StocksQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24658
=> (PC-24658)[API] feat: add order by several fields for stocks route

api/src/pcapi/core/mails/transactional/pro/reset_password_to_pro.py, api/src/pcapi/core/mails/transactional/users/reset_password.py, api/src/pcapi/core/mails/transactional/users/suspicious_login_email.py, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/user_generation/blueprint.py, api/src/pcapi/routes/native/v1/authentication.py, api/src/pcapi/routes/pro/users.py, api/src/pcapi/routes/shared/passwords.py, api/tests/core/mails/transactional/users/email_address_change_test.py, api/tests/core/mails/transactional/users/reset_password_test.py, api/tests/core/mails/transactional/users/suspicious_login_email_test.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/pro/get_user_token_test.py, api/tests/routes/shared/post_reset_password_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24817
Post mortem pour ce bug à venir
=> Fix pro reset password (revert)

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/users/blueprint.py, api/tests/routes/backoffice/users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24664
=> (PC-24664)[BO] feat: change permission to suspend/unsuspend BO users

api/src/pcapi/core/providers/titelive_music_search.py, api/tests/providers/titelive_search_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-24090
=> (PC-24090)[API] fix: titelive music search test

pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24821
bookingsQuantity ne doit pas être envoyé dans le payload
=> (PC-24821)[PRO] fix: stock event creation

api/requirements.txt
=> (BSR)[API] feat: fix pylint to 2.17.7

pro/src/components/IndividualOfferBreadcrumb/IndividualOfferBreadcrumb.tsx, pro/src/components/IndividualOfferBreadcrumb/__specs__/IndividualOfferBreadcrumb.spec.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24421
=> (PC-24421)[PRO] fix: booking tab problems

pro/src/app/AppRouter/routesMap.tsx, pro/src/app/AppRouter/subroutesReimbursements.tsx, pro/src/components/Breadcrumb/Breadcrumb.module.scss, pro/src/components/Breadcrumb/Breadcrumb.tsx, pro/src/components/Breadcrumb/__specs__/Breadcrumb.spec.tsx, pro/src/components/Breadcrumb/types.ts, pro/src/components/ReimbursementsBreadcrumb/ReimbursementsBreadcrumb.tsx, pro/src/components/ReimbursementsBreadcrumb/constants.ts, pro/src/context/ReimbursementContext/ReimbursementContext.tsx, pro/src/pages/Reimbursements/BankInformations/BankInformations.module.scss, pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/BankInformations/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/Reimbursement.scss, pro/src/pages/Reimbursements/Reimbursements.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx, pro/src/pages/Reimbursements/__specs__/Reimbursements.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23403
Activer le FF: WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY
url: `remboursements/informations-bancaires`
=> (PC-23403)[PRO] feat: create bank information page

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/tests/routes/public/individual_offers/v1/delete_date_test.py, api/tests/routes/public/individual_offers/v1/get_booking_test.py, api/tests/routes/public/individual_offers/v1/get_bookings_test.py, api/tests/routes/public/individual_offers/v1/get_event_dates_test.py, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/get_events_test.py, api/tests/routes/public/individual_offers/v1/get_offerer_venue_test.py, api/tests/routes/public/individual_offers/v1/get_product_by_ean_test.py, api/tests/routes/public/individual_offers/v1/get_product_test.py, api/tests/routes/public/individual_offers/v1/get_products_test.py, api/tests/routes/public/individual_offers/v1/patch_cancel_booking_by_token_test.py, api/tests/routes/public/individual_offers/v1/patch_date_test.py, api/tests/routes/public/individual_offers/v1/patch_event_test.py, api/tests/routes/public/individual_offers/v1/patch_price_category_test.py, api/tests/routes/public/individual_offers/v1/patch_product_test.py, api/tests/routes/public/individual_offers/v1/patch_validate_booking_by_token_test.py, api/tests/routes/public/individual_offers/v1/post_dates_test.py, api/tests/routes/public/individual_offers/v1/post_event_test.py, api/tests/routes/public/individual_offers/v1/post_price_categories_test.py, api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py, api/tests/routes/public/individual_offers/v1/utils.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24787
=> (PC-24787)[API] fix: inactive venue provider shouldn't do anything

.github/workflows/release--deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24793
=> (PC-24793)[deploy] ci: deploy production and integration together

pro/src/core/Offers/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24612
But: Voir le nouveau wording dans la page Récap
'Les billets seront affichés dans l’application'
Branche: PC-24612-style-retrait2
=> (PC-24612)[PRO] feat: text de message

pro/src/ui-kit/form/Slider/Slider.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24004
**Objectif**
Ajouter du texte autour des bornes min et max du slider pour expliciter le sens de ces valeurs aux technologies d'assistance.
=> (PC-24004)[PRO] feat: Make slider min max value accessible.

.github/workflows/release--deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24793
=> (PC-24793)[deploy] ci: deploy production and integration together without ternary

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231004T090642_d01ad12d4c78_drop_unused_columns_from_offer.py, api/src/pcapi/alembic/versions/20231004T090833_06ebfa9392fa_drop_unused_columns_from_product.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/models/CONTRIBUTING.md, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, pro/src/apiClient/v1/models/PatchOfferBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24854
=> (PC-24854)[API] refactor: remove unused columns from Product and Offer

pro/src/pages/AdageIframe/app/components/DiffuseHelp/DiffuseHelp.module.scss, pro/src/pages/AdageIframe/app/components/DiffuseHelp/DiffuseHelp.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24456
Modification du wording et de l'interface de l'aide diffuse dans Adage : 
- Suppression de l'image en background
- Ajout d'un icone à gauche du titre 
- Modification du wording 
Activer le FF : WIP_ENABLE_DIFFUSE_HELP
Lancer au moins une recherche
=> (PC-24456)[PRO] feat: modify difuse help ui and wording

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24777
Tracker le click sur les suggestions de l'autocomplete sur adage 
_Pas de tests à cause de l'abstraction des plugins Algolia_
=> (PC-24777)[PRO] feat: log suggestion click in adage

api/src/pcapi/routes/public/individual_offers/v1/blueprint.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/serialization/utils.py, api/tests/routes/public/individual_offers/v1/get_bookings_test.py, api/tests/routes/public/individual_offers/v1/get_product_by_ean_test.py, api/tests/routes/public/individual_offers/v1/patch_date_test.py, api/tests/routes/public/individual_offers/v1/patch_price_category_test.py, api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24835
=> (PC-24835)[API] fix: do not allow price gt 300

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/external_bookings/exceptions.py, api/src/pcapi/core/external_bookings/serialize.py, api/tests/core/bookings/test_api.py, api/tests/routes/native/v1/bookings_test.py, api/tests/routes/public/booking_token/v2/patch_cancel_booking_by_token_test.py
permettre à l'api charlie de rendre la quantité de stock restante illimitée
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24507
=> (PC-24507) allow providers to make stock unlimited

api/src/pcapi/connectors/cgr/cgr.py, api/src/pcapi/core/external_bookings/cgr/client.py, api/tests/core/bookings/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24669
=> (PC-24669)[API] fix: Handle timeout while booking an offer on CGR side

api/src/pcapi/routes/backoffice/collective_offers/forms.py
Les attributs de ce formulaire de recherche offres collectives sont les mêmes dans une classe formulaire générique
=> (BSR)[BO] fix: Remove duplicate code Get Collective Offer Form

api/src/pcapi/core/mails/transactional/pro/reset_password_to_pro.py, api/src/pcapi/core/mails/transactional/users/reset_password.py, api/src/pcapi/core/mails/transactional/users/suspicious_login_email.py, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/user_generation/blueprint.py, api/src/pcapi/routes/native/v1/authentication.py, api/src/pcapi/routes/pro/users.py, api/src/pcapi/routes/shared/passwords.py, api/tests/core/mails/transactional/users/email_address_change_test.py, api/tests/core/mails/transactional/users/reset_password_test.py, api/tests/core/mails/transactional/users/suspicious_login_email_test.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/pro/get_user_token_test.py, api/tests/routes/shared/post_new_password_test.py, api/tests/routes/shared/post_reset_password_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23633
on a revert les deux commits associés à cause du bug en prod cette PR reprend les mêmes changement et prend en compte le reset password côté pro
La PR introduisant le bug: https://github.com/pass-culture/pass-culture-main/pull/8210
La PR de revert https://github.com/pass-culture/pass-culture-main/pull/8496
=> (PC-23633)[API] replace reset password token

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231005T135026_c5009a056b16_offer_product_id_nullable.py, api/src/pcapi/core/offers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24868
This is necessary to allow offers to be created without product
=> (PC-24868)[API] chore: alter offer.productId nullable

.github/workflows/deploy.yml, helmfile.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24887
Tied to https://github.com/pass-culture/pcapi-chart/pull/50
merge this one in 2nd
=> (PC-24887)[api] ci: alembic migrations do not continue on error

api/src/pcapi/core/mails/transactional/users/fraud_emails.py, api/src/pcapi/core/subscription/api.py, api/src/pcapi/core/subscription/dms/api.py, api/tests/core/subscription/test_api.py, api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22449
=> PC-22449 Fix sending email to fraud to validate 19yo accepted DMS application

pro/src/app/AppRouter/subroutesReimbursements.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx
- Condition pour afficher des bannières
- Correction d'une route
=> (BSR)[PRO] fix: Fix FF condition and routing issues.

api/src/pcapi/static/backoffice/js/addons/pc-form.js
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24837
=> (PC-24837)[BO] fix: reactivate form buttons when using back button.

api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24805
=> (PC-24805)[BO] feat: add copy id for beneficiary user

api/src/pcapi/routes/public/individual_offers/v1/constants.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_event_show_types_test.py, api/tests/routes/public/individual_offers/v1/get_music_types_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-24656
=> (PC-24656)[API] feat: add music types route in individual api

.github/workflows/deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24921
=> (PC-24921) fix(ci): Add retry for pre post migration

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24869
=> (PC-24869)[API] feat: Log in the history USER_OFFERER_NEW action when a user accept an offerer invitation

.github/workflows/tests-main.yml, .github/workflows/tests-pro-e2e.yml, .github/workflows/tests-pro.yml
Lancement des tests E2E sur master plutôt que dans les PRs
=> (BSR)[PRO] ci: run e2e tests on master branch

api/src/pcapi/core/offers/exceptions.py, api/tests/routes/public/individual_offers/v1/delete_date_test.py, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24589
=> (PC-24589) cannot delete stock

api/src/pcapi/alembic/versions/20231004T090642_d01ad12d4c78_drop_unused_columns_from_offer.py, api/src/pcapi/alembic/versions/20231004T090833_06ebfa9392fa_drop_unused_columns_from_product.py
Ticket Jira (ou description si BSR) : Pas de non nullable dans le downgrade, sinon ça casse tout
=> (BSR)[API] refactor: remove non null from downgrade

pro/src/components/Address/__specs__/Address.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OldOffersSearch.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx, pro/src/pages/Offerers/OffererCreation/__specs__/OffererCreation.spec.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementDetails.spec.tsx, pro/src/pages/SignIn/__specs__/SignIn.spec.tsx, pro/src/screens/IndividualOffer/ActionBar/ActionBar.tsx, pro/src/screens/IndividualOffer/ActionBar/__specs__/ActionBar.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.edition.spec.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/__specs__/PriceCategories.RouteLeavingGuard.spec.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormNotifications/__specs__/FormNotifications.spec.tsx, pro/src/screens/SignupJourneyForm/Activity/__specs__/ActivityForm.spec.tsx, pro/src/screens/SignupJourneyForm/Activity/__specs__/ActivityScreen.spec.tsx, pro/src/screens/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx, pro/src/screens/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationScreen.spec.tsx, pro/src/screens/SignupJourneyForm/ConfirmedAttachment/__specs__/ConfirmedAttachment.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/__specs__/OffererForm.spec.tsx, pro/src/screens/SignupJourneyForm/Offerers/__specs__/Offerers.spec.tsx, pro/src/screens/SignupJourneyForm/Welcome/__specs__/Welcome.spec.tsx, pro/src/screens/VenueForm/__specs__/VenueFormScreen.spec.tsx, pro/src/ui-kit/form/EmailSpellCheckInput/__specs__/EmailSpellCheckInput.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24925
Revenir vers le readonly sur les étapes dédition
=> (PC-24925)[PRO] feat: in edition cancel on offer go back to summary

api/src/pcapi/routes/backoffice/criteria/blueprint.py, api/src/pcapi/routes/backoffice/criteria/form.py, api/src/pcapi/routes/backoffice/templates/tags/list_tags.html, api/tests/routes/backoffice/tags_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24635
=> (PC-24635)[BO] feat: pagination on offer/venue tags list

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24723
ouvrir un lien dans un nouvel onglet
=> (PC-24723)[PRO] feat: open provider help in new page

pro/src/screens/IndividualOffer/ActionBar/ActionBar.module.scss, pro/src/screens/IndividualOffer/ActionBar/ActionBar.tsx, pro/src/screens/IndividualOffer/ActionBar/__specs__/ActionBar.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24830
=> (PC-24830)[PRO] feat: add draft indicator to actionbar

api/src/pcapi/flask_app.py, api/src/pcapi/routes/external/sendinblue.py, api/tests/routes/external/sendinblue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24901
=> (PC-24901)[BO] feat: handle multiple ips in sib webhook

pro/src/components/IndividualOfferForm/utils/__specs__/setFormReadOnlyFields.spec.ts, pro/src/components/IndividualOfferForm/utils/setFormReadOnlyFields.ts, pro/src/styles/variables/_colors.scss, pro/src/styles/variables/_forms.scss, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24789
=>  (PC-24789)[PRO] style: update radioButton + refacto setFormReadOnlyFields

api/src/pcapi/connectors/notion.py, api/src/pcapi/core/providers/titelive_api.py, api/src/pcapi/local_providers/provider_manager.py, api/tests/local_providers/provider_manager_test.py, api/tests/providers/titelive_search_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-24532
=> (PC-24532)[API] feat: log titelive music sync errors to notion

api/src/pcapi/routes/backoffice/bookings/form.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/search_utils.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24181
=> (PC-24181)[BO] feat: search for bookings by list of tokens

pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.tsx
BSR
un id inutile au phoneNumber cassé les tests (le htmlFor avec le label ne fonctionnait plus)
=> (BSR)[PRO] fix: SignupContainer tests

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx
- Supression d'un use effect inutile.
=> (BSR)[PRO] refactor: Cleaning not needed use effect.

pro/src/screens/Bookings/BookingsRecapTable/BookingsRecapTable.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/BookingsTable.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingsTable.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/IndividualBookingsTable.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/__specs__/IndividualBookingsTable.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/NoFilteredBookings.tsx, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/__specs__/NoFilteredBookings.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/index.ts, pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.module.scss, pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.tsx, pro/src/screens/IndividualOffer/BookingsSummary/__specs__/BookingsSummary.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24935
=> (PC-24935)[PRO] fix: add empty filters message

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/delete_stocks_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/DeleteStockListBody.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24303
=> (PC-24303)[API] feat: add delete_stocks for multiple stocks route

pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx, pro/src/screens/OfferType/CollectiveOfferType/CollectiveOfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24989
- Changer un wording sur l'écran carrefour : supprimer 'ni date, ni prix'
- Supprimer une banner dans le formulaire d'offre collective (création/édition)
FF à activer pour voir ces modifs : `WIP_ENABLE_DATES_OFFER_TEMPLATE`
**Changement de wording**
**Bannière à supprimer**
=> (PC-24989)[PRO] feat: change wording for offer template

api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/src/pcapi/workers/update_stocks_job.py, api/tests/core/offers/test_api.py, api/tests/routes/pro/delete_filtered_stocks_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/DeleteFilteredStockListBody.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24304
=> (PC-24304)[API] feat: create delete_all_filtered_stocks route

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/utils/_constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24723
wording
=> (PC-24723)[PRO] feat: change select provider default option

helmfile.yaml
Ticket Jira : https://passculture.atlassian.net/browse/PC-24814
=> (PC-24814)[pcapi]: bump chart version to use new ingress for global lb on production and integration

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/sonar-project.properties, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/OfferFavoriteBody.ts, pro/src/apiClient/adage/services/DefaultService.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/OfferFavoriteButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/__specs__/OfferFavoriteButton.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25037
Tracker le clic sur le bouton favori dans adage. 
FF à activer pour tester : WIP_ENABLE_LIKE_IN_ADAGE
=> Pc 25037 eac log add remove favorite

api/src/pcapi/routes/pro/bookings.py, api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/src/pcapi/routes/public/individual_offers/v1/bookings_serialization.py, api/src/pcapi/routes/serialization/bookings_recap_serialize.py, api/tests/routes/pro/get_all_bookings_test.py, api/tests/routes/public/individual_offers/v1/get_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-24825
=> (PC-24825)[API] fix: status code 400 when incorrect date is received

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/post_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24835
=> (PC-24835)[API] fix: allow 300 € offers

api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/providers/allocine_venue_provider.py, api/src/pcapi/models/providable_mixin.py
J'espérais résoudre le problème de mypy en résolvant les `type: ignore`, mais c'est pas suffisant.
Du coup j'ai quand même enlevé des `type: ignore`, donc je push :)
=> (BSR)[API] fix: remove declared_attr type:ignore

api/src/pcapi/routes/backoffice/templates/offer/details.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-24623
Avant
Après
=> (PC-24623)[BO] fix: move button index offer in algolia on offer page

api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/form.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25046
=> (PC-25046)[BO] feat: restore choice of booking cancellation reason

api/src/pcapi/routes/backoffice/pivots/contexts/boost.py, api/src/pcapi/routes/backoffice/pivots/contexts/cineoffice.py
=> (BSR)[API] feat: Use suitable flash for successful operation

api/src/pcapi/routes/adage_iframe/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24982
created an endpoint tracking adage map for frontend dev
=> (PC-24982)[API] feat: endpoint tracking adage map

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24297
- Wording fixes.
- Conditionnal banner displaying.
=> Pc 24297 fixes

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23403
- Correction de la condition du variant du bouton.
=> (PC-23403)[PRO] fix: Change the variant condition.

api/src/pcapi/routes/backoffice/templates/components/search/result_card_venue.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-24973
=> (PC-24973][BO] feat: offerer link on venue card results

pro/src/components/IndividualOfferForm/Categories/Categories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24952
=> (PC-24952)[PRO] fix: persistent error in cate/subcategory in offer form

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/PendingBankAccountCallout.tsx, pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx, pro/src/components/Callout/__specs__/PendingBankAccountCallout.spec.tsx, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24267
- Affichage conditionnel de la bannière
=> (PC-24267)[PRO] feat: Conditional banner displaying.

pro/cypress/e2e/createOffer.cy.ts, pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingDateCell.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingDateCell.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/__specs__/BookingDateCell.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/__specs__/BookingOfferCell.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/IndividualBookingsTable.tsx, pro/src/utils/apiFactories.ts, pro/src/utils/formatPrice.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25033
changer les infos sur les tarifs de place pour les offres indiv :
+ un non braking space dans la fonction formatPrice
=> (PC-25033)[PRO] feat: move tarif informations in bookings

pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/core/FirebaseEvents/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24667
=> (PC-24667)[PRO] fix: Remplacer les events de navigation dans la créa d'offres par de nouveaux events

pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25081
=> (PC-25081)[PRO] fix: bookings summary date filters

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231012T143850_603064a3b53f_delete_booking_tab_ff.py, api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23637
=> (PC-23637)[PRO] feat: Ajout du feature flag WIP_HOME_STATS

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231009T092610_631df26e514b_add_last_author_validation_or_rejection_on_collective_offer_table.py, api/src/pcapi/alembic/versions/20231009T092625_8347a72b24d0_add_last_author_validation_or_rejection_on_collective_template_offer_table.py, api/src/pcapi/alembic/versions/20231009T092805_654f1c1c4da3_add_last_author_validation_or_rejection_on_offer_table.py, api/src/pcapi/alembic/versions/20231013T105058_64f6f0c48964_validate_collective_offer_validation_author_fkey_on_collective_offer_table.py, api/src/pcapi/alembic/versions/20231013T105113_8f4c9a84efa0_validate_collective_offer_template_validation_author_fkey_on_collective_offer_.py, api/src/pcapi/alembic/versions/20231013T105150_b397aa305b2e_validate_offer_validation_author_fkey_on_offer_table.py
Hotfix : Problème de timeout lors de la MES : https://github.com/pass-culture/pass-culture-main/actions/runs/6494469116/job/17640294257
Ticket Jira https://passculture.atlassian.net/browse/PC-24436
=> (PC-24436)[BO] fix: timeout creation foreign key offer.lastAuthor

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bank_accounts.py, api/tests/routes/pro/get_offerer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23419
=> (PC-23419)[API] feat: Add sandbox use cases + handle CollectiveOffers for venues with non free offers

api/src/pcapi/routes/backoffice/filters.py
Ticket Jira https://passculture.atlassian.net/browse/PC-25046 implémenté dans l'itération de cette MES.
https://sentry.passculture.team/organizations/sentry/issues/458439/?project=5
=> (PC-25046)[BO] fix: cancellation reason may be None

pro/src/components/AdageButtonFilter/AdageButtonFilter.module.scss, pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24957
On avait perdu le cursoir "main" pour les bouton
=> (PC-24957)[PRO] fix: button cursor pointer

api/.env.testauto, api/src/pcapi/connectors/beneficiaries/ubble.py, api/tests/connectors/beneficiaries/ubble_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24325
[La PR côté mock Ubble](https://github.com/pass-culture/mock-ubble/pull/23)
=> (PC-24325)][API] feat: Decide to call real or mock by checking mock result first

pro/src/components/Notification/Notification.tsx, pro/src/components/Notification/__specs__/Notification.spec.tsx, pro/src/context/IndividualOfferContext/IndividualOfferContext.tsx, pro/src/hooks/useNotification.ts, pro/src/pages/IndividualOfferWizard/__specs__/IndividualOfferWizard.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24728
=> (PC-24728)[PRO] fix: test flaky IndividualOfferWizard

.github/workflows/tests-pro.yml, pro/.eslintrc.js, pro/src/screens/OfferType/CollectiveOfferType/CollectiveOfferType.tsx, pro/src/screens/OfferType/IndividualOfferType/IndividualOfferType.tsx, pro/src/screens/OfferType/OfferType.tsx, pro/src/screens/OfferType/__specs__/OfferType.navigation.spec.tsx, pro/src/screens/OfferType/__specs__/OfferType.spec.tsx, pro/src/store/testUtils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24762
**Améliorations effectuées :**
- On enlève le code inutile avec des mockResolvedValue qui sont appelés alors qu'il sont déjà dans le beforeEach
- On utilise que des mockResolvedValue**Once** quand on surcharge les mocks déjà déclarés
- On await tout ce qui est des promesses
- On a ajouté une règle eslint en mode warning pour détecter ça (cf screenshot)
=> (PC-24762)[PRO] fix: Test flaky - OfferType.spec.tsx

pro/src/pages/Desk/Desk.tsx, pro/src/pages/Desk/__specs__/Desk.spec.tsx, pro/src/pages/Desk/adapters/__specs__/getBooking.spec.ts, pro/src/pages/Desk/adapters/getBooking.ts, pro/src/pages/Desk/adapters/submitToken.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25122
Refacto des then en async/await pour le composant Desk.tsx
Correction du test flaky
=> (PC-25122)[PRO] refactor: Desk async await and fix flaky test

api/requirements.txt
cf. https://passculture.atlassian.net/browse/PC-25149 pour des détails et un exemple de rendu.
=> (PC-25149)[API] chore: Bump weasyprint

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231012T141351_d968ffd57c40_set_mediation_author_as_null_when_user_deleted.py, api/src/pcapi/alembic/versions/20231013T080519_a09a9a890bcb_validate_constraint_on_mediation_author.py, api/src/pcapi/core/offers/models.py, api/tests/routes/backoffice/pro_users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24955
https://sentry.passculture.team/organizations/sentry/issues/429008/
=> (PC-24955)[API] fix: IntegrityError when a pro user who authored a mediation is deleted

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25027
=> (PC-25027)[API] feat: set some FF to true in Testing

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.module.scss, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23638
=> (PC-23638)[PRO] feat: add statistics dashboard component

pro/src/ui-kit/form/TextInput/TextInput.tsx, pro/src/ui-kit/form/TextInput/__specs__/TextInput.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25083
=> (PC-25083)[PRO] fix: a11y tabbing out of a number input

pro/src/store/testUtils.ts, pro/src/ui-kit/form/TextInput/__specs__/TextInput.spec.tsx
BSR
réparer la quality (merge simultané au moment du merge de changement de conf prettier sur arrowParens
=> (BSR)[PRO] fix: quality (arrowParens)

api/src/pcapi/routes/backoffice/venues/blueprint.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-21403
=> (PC-21403)[BO] fix: target for venue modal error message

api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/backoffice/venues/form.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24974
=> (PC-24974)[BO] feat: filter list of venues on managing offerer

.git-blame-ignore-revs, api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231011T130519_74409447111a_add_index_on_stock_booking_limit_datetime.py, api/src/pcapi/alembic/versions/20231011T130845_56d7319f1713_add_index_on_stock_beginning_datetime.py, api/src/pcapi/alembic/versions/20231011T130900_cbd37c328f46_drop_old_index_on_stock_beginning_datetime.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/offerer/offerer_tag.html, api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/src/pcapi/routes/backoffice/templates/tags/list_tags.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-23801
=> (PC-23801)[BO] perf: fix timeout in advanced search for individual offers

.github/workflows/tests-main.yml
fix concurrency issue when we merged on master
=> (BSR)[ci] fix concurrency issue when we merged on master

pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss, pro/src/components/Dialog/ConfirmDialog/ConfirmDialog.module.scss, pro/src/components/DialogBox/DialogBox.module.scss, pro/src/components/FormLayout/FormLayout.module.scss, pro/src/pages/Offers/Offers/OfferItem/Cells/ThumbCell/ThumbCell.tsx, pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss, pro/src/pages/Offers/Offers/Offers.module.scss, pro/src/pages/Offers/Offers/Offers.scss, pro/src/pages/Offers/Offers/Offers.tsx, pro/src/pages/Offers/Offers/OffersTableHead/OffersTableHead.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.module.scss, pro/src/screens/Offers/__specs__/Offers.spec.tsx, pro/src/styles/variables/_size.scss, pro/src/ui-kit/Thumb/Thumb.module.scss, pro/src/ui-kit/Thumb/Thumb.tsx
- (PC-24511)[PRO] feat: responsive offer table
- (PC-24511)[PRO] feat: move Tout selectionner out of table head
- (PC-24511)[PRO] feat: responsive search filters
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24511
=> (PC-24511)[PRO] feat: offer table responsive

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/authentication_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-24208
=> (PC-24208)[API] feat: limit suspicious login mails per day

pro/src/pages/AdageIframe/app/App.tsx, pro/src/screens/IndividualOffer/BookingsSummary/BookingsSummary.tsx, pro/src/screens/IndividualOffer/BookingsSummary/__specs__/BookingsSummary.spec.tsx
=> (BSR)[PRO] feat: add number of bookings in bookings summary

api/src/pcapi/routes/backoffice/templates/components/search/result_card_offerer.html, api/tests/routes/backoffice/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24971
=> (PC-24971)[BO] feat: add postal code and city on offerer search result

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/HomepageBreadcrumb.tsx, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23638
=> (PC-23638)[PRO] feat: V1 - Je vois le titre "présence sur le pass Culture" + CTA créer une offre

pro/src/components/IndividualOfferForm/Categories/Categories.tsx, pro/src/components/IndividualOfferForm/Categories/__specs__/Categories.spec.tsx, pro/src/components/IndividualOfferForm/IndividualOfferForm.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/UsefulInformations.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx, pro/src/components/IndividualOfferForm/__specs__/IndividualOfferForm.BannerAddVenue.spec.tsx, pro/src/components/IndividualOfferForm/__specs__/IndividualOfferForm.spec.tsx, pro/src/components/IndividualOfferForm/utils/__specs__/getFilteredVenueList.spec.ts, pro/src/components/IndividualOfferForm/utils/__specs__/setDefaultInitialFormValues.spec.ts, pro/src/components/IndividualOfferForm/utils/__specs__/setInitialFormValues.spec.ts, pro/src/components/IndividualOfferForm/utils/buildSubCategoryFields.ts, pro/src/components/IndividualOfferForm/utils/getFilteredVenueList.ts, pro/src/components/IndividualOfferForm/utils/setDefaultInitialFormValues.ts, pro/src/components/IndividualOfferForm/utils/setInitialFormValues.ts, pro/src/context/IndividualOfferContext/IndividualOfferContext.tsx, pro/src/context/IndividualOfferContext/adapters/getWizardData/__specs__/getWizardData.spec.ts, pro/src/context/IndividualOfferContext/adapters/getWizardData/getWizardData.ts, pro/src/core/Offers/adapters/useGetCategories.ts, pro/src/core/Offers/types.ts, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.RouteLeavingGuard.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.creation.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.edition.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/utils/filterCategories/__specs__/filterCategories.spec.ts, pro/src/screens/IndividualOffer/InformationsScreen/utils/filterCategories/filterCategories.ts, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/__specs__/serializer.spec.ts, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/serializer.ts, pro/src/screens/OfferType/IndividualOfferType/IndividualOfferType.tsx, pro/src/utils/getOfferConditionalFields.ts, pro/src/utils/individualApiFactories.ts
Use backend types instead of custom types
=> (BSR)[PRO] refactor: use backend types (part 2)

.github/workflows/update-jira-issues.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25087
Exemple de worfklow qui montre que ça devrait marcher : https://github.com/pass-culture/pass-culture-main/actions/runs/6575209214/job/17861832733
=> (PC-25087) secret manager jira update issues

api/src/pcapi/flask_app.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/external/sendinblue.py
Commits à relire séparément. À inclure dans un hotfix pour la prochaine MEP.
Le code a été testé sur l'environnement "perf".
=> Adaptation au load balancer L7 et arrêt de l'utilisation de `X-Forwarded-For`

api/src/pcapi/flask_app.py
=> (BSR)[API] ci: Remove unused import

api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/search/result.html, api/tests/routes/backoffice/admin_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25296
=> (PC-25296)[BO] fix: exception when invalid search in BO users

api/src/pcapi/core/external_bookings/serialize.py, api/tests/tasks/external_api_booking_notification_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25031
=> (PC-25031) external booking serializer price when offer for product

.github/workflows/tests-pro.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25088
=> (PC-25088) feat(ci): Use secret manager to stock secrets

.github/workflows/tests-pro.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25088
=> (PC-25088) fix(ci): Remove space after variable

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231019T152226_d12371e730c9_.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/commands/indexation.py, api/src/pcapi/scripts/full_index_offers.py, api/tests/core/search/test_api.py, api/tests/core/search/test_commands_indexation.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24989
=> (PC-24898)[API] feat: add last 30 days booking column to database

.github/CODEOWNERS
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25325
=> (PC-25325) Feat: ajouter codeowner pour groupe github sherif-devlead

api/src/pcapi/routes/serialization/serializer.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/src/pcapi/sandboxes/scripts/utils/storage_utils.py, api/src/pcapi/scheduled_tasks/decorators.py, api/src/pcapi/scheduled_tasks/logger.py, api/src/pcapi/scripts/provider/check_provider_api.py, api/src/pcapi/tasks/cloud_task.py, api/src/pcapi/utils/custom_logic.py
Ticket Jira (ou description si BSR) : typer des signatures de fonctions
=> fix some mypy errors

api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/adage_iframe/offers.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py, api/tests/routes/adage_iframe/get_favorites_test.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_collective_offer_template_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/CollectiveOfferTemplateResponseModel.ts, pro/src/apiClient/adage/models/TemplateDatesModel.ts, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts, pro/src/apiClient/v1/models/TemplateDatesModel.ts, pro/src/core/OfferEducational/adapters/__specs__/getStockCollectiveOfferTemplateAdapter.spec.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx, pro/src/pages/CollectiveOfferFromRequest/__specs__/CollectiveOfferFromRequest.spec.tsx, pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx, pro/src/utils/adageFactories.ts, pro/src/utils/collectiveApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24577
=> (PC-24577)[API] feat: get pro and adage backend collective offer template must return date start and end

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py, pro/src/pages/Offers/Offers/OfferItem/Cells/OfferInstitutionCell/OfferInstitutionCell.tsx, pro/src/pages/Offers/Offers/OfferItem/__specs__/OfferItem.spec.tsx
Si le nom de l'établissement n'est pas défini, afficher le sigle et le nom de la ville à la place
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25256
=> Pc 25256 sigle and city offer cell

api/.vscode/launch.json
Fixer le remote root dans la config du debugger sur vs code
=> (BSR)[API] fix: fix vs code config to allow live debugging

api/src/pcapi/routes/native/v1/account.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24727
=> (PC-24727)[API] refactor: remove support for old suspicious login tokens

api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/offers.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/tests/routes/adage_iframe/get_all_offers_linked_to_uai_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/ListCollectiveOffersResponseModel.ts, pro/src/apiClient/adage/services/DefaultService.ts
… linked
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24763
https://passculture.atlassian.net/jira/software/c/projects/PC/boards/67/backlog?view=detail&selectedIssue=PC-24763&issueLimit=100
FOR ELIGIBLE OFFER ONLY 
all collective offer(s) linked to the institutionId (uai) must be return
=> (PC-24763)[API]feat: endpoint returning for uai the collective offer(s) linked

api/src/pcapi/core/geography/models.py
=> (BSR) [API]: fix type hint Geometry field

pro/src/pages/Home/Venues/Venue.module.scss, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx, pro/src/pages/Home/Venues/__specs__/Venue.tracker.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24993
=> (PC-24933)[PRO] feat: add API tag for venues with provider

helmfile.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25148
=> (PC-25148) feat(monitoring): add label for jobs

pro/src/screens/IndividualOffer/StocksSummaryScreen/StocksSummaryScreen.tsx
=> (BSR)[PRO] fix: empty stocks summary page

api/src/pcapi/core/external_bookings/cgr/client.py, api/tests/core/offers/test_api.py, api/tests/local_providers/cinema_providers/cgr/fixtures.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25350
=> (PC-25350)[API] fix: Handle no remaining places CGR case

api/src/pcapi/core/external/compliance_backends/compliance.py, api/tests/core/external/compliance_test.py
Ticket Jira (ou description si BSR) : ajouter des logs à la cloud task compliance, car mettre les infos dans l'exception ne les fait pas remonter dans les logs
=> (BSR)[BO] feat: add logs to compliance cloud task

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/patch_product_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25032
=> (PC-25032) Allow more categories offer creation on individual api

api/src/pcapi/core/external_bookings/serialize.py
Fix bug while booking offer, cannot send notification because price category does not exist on products
=> (BSR)[API] feat: fix priceCategory id null if product

pro/src/screens/Bookings/BookingsRecapTable/BookingsRecapTable.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/IndividualBookingsTable.tsx, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/NoFilteredBookings.module.scss, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/NoFilteredBookings.tsx, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/__specs__/NoFilteredBookings.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/__specs__/BookingsRecapTable.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25327
Ici nous cherchons des réservations de deux façons :
1. Recherche là haut de la page par dates etc. C'est le Niveau 1.
S'il n'y a pas des reservations, popin1 de pas des résultas apparait (elle est faite).
2. Recherche dans le champs de recherche  de PR, qui se trouve au déçue des entêtes. Recherche cette fois  se passe par lettre.
Niveau 2.
S'il n'y a pas des reservations, popin2 de pas des résultas apparait. 
Il faut la styler en même façon que popin1.
Il faut  aussi cacher les entêtes et le compteur. 
Mettre à jour le style des messages: Aucune réservation trouvée pour votre recherche ?
Donc ajouter  title4, new bouton ButtonVariant.TERNARYPINK, texte etc.
Branche: PC-25327-resa-entete
=> (PC-25327)[PRO] feat: new norésa style

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25403
=> (PC-25403)[BO] fix: ArgumentError when advanded search query has an empty or invalid filter

pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25395
=> (PC-25395)[PRO] feat: disabled button after submit in recurrence

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24356
Fix d'une première solution à ce ticket, permettant de mettre à jour le prix/nombre de tickets d'une offre collective à partir du moment où celle-ci n'a pas de pricing.
=> (PC-24356)[BO] fix: Collective offer price editing

pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25413
=> (PC-25413)[PRO] feat: add loader in recurrence submit button

pro/src/pages/Offerers/Offerer/OffererDetails/OffererDetails.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24813
Retirer l'id de DS de la page structure
=> (PC-24813)[PRO] refactor: remove ds token from offerer page

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/models/AdageBaseModel.ts, pro/src/apiClient/adage/models/AdageHeaderLogBody.ts, pro/src/apiClient/adage/models/CatalogViewBody.ts, pro/src/apiClient/adage/models/CollectiveRequestBody.ts, pro/src/apiClient/adage/models/OfferFavoriteBody.ts, pro/src/apiClient/adage/models/OfferIdBody.ts, pro/src/apiClient/adage/models/SearchBody.ts, pro/src/apiClient/adage/models/StockIdBody.ts, pro/src/apiClient/adage/models/TrackingAutocompleteSuggestionBody.ts, pro/src/apiClient/adage/models/TrackingFilterBody.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/ContactButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/OfferFavoriteButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/__spec__/PrebookingButton.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24963
Ajouter un paramètre au route de tracking sur adage pour savoir si ça vient de la suggestion des résultats quand 0 résultat
=> Pc 24963 tracking page 0 resultat

.github/workflows/tests-main.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25089
Exemple de workflow ou ça fonctionne : https://github.com/pass-culture/pass-culture-main/actions/runs/6642466582
=> (PC-25089) secret manager tests main

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25388
=> (PC-25388)[PRO] feat: Add the FF for the discovery in adage.

pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine/CollectiveTimeLine.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine/__specs__/CollectiveTimeLine.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24477
=> (PC-24477)[PRO] feat: update collective timeline waiting missing bank info wording and link

api/src/pcapi/routes/backoffice/templates/components/search/result_card.html, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25334
=> (PC-25334)[BO] feat: show birth date instead of phone number on result card

api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25333
=> (PC-25333)[BO] feat: change stock counters for individual offers

api/src/pcapi/routes/backoffice/templates/offer/details.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24849
=> (PC-24849)[BO] feat: show compliance score on offer details page

api/src/pcapi/routes/backoffice/admin/forms.py, api/tests/routes/backoffice/admin_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25296
(seconde PR suite à un autre bug mentionné en commentaire)
=> (PC-25296)[BO] fix: pagination in admin users search page

pro/src/pages/Home/Homepage.scss, pro/src/pages/Home/OffererStats/OffererStats.module.scss, pro/src/pages/Home/OffererStats/OffererStats.tsx, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/Venues/VenueStat.scss, pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24552
Page d'accueil responsive, essayer de rendre sa visible pour téléphone, tablette, petit écran
=> (PC-24552)[PRO] feat: Make home page responsive

pro/src/components/StocksEventList/FilterResultsRow.tsx, pro/src/components/StocksEventList/NoResultsRow.tsx, pro/src/components/StocksEventList/StocksEventList.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25399
1.  Ajout d'un espace entre les centaines et les milliers: '12 345' au lieu de '12345'. 
2.  Correction de mot 'occurrence'  qui se trouve à coté des chiffres et  aussi 'Aucune occurrence trouvée'. 
Donc dans cette appli il n'y a plus  des  mots sans 'R'.
Branche: PC-25399-occurrences-espace-chiffres
Cas de l'occurrence(s):
Pendant de la création d'offre:
Occurrences:
=> (PC-25399)[PRO] feat: Wording de 'occurRences'

.github/workflows/tests-main.yml
Correction de ce genre d'erreur dans la CI : https://github.com/pass-culture/pass-culture-main/actions/runs/6665083895
=> (PC 25089) fix token test main

api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_test.py, pro/src/apiClient/v1/models/GetOffererVenueResponseModel.ts, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/Venues/VenueList.tsx, pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx, pro/src/pages/Home/Venues/__specs__/Venue.tracker.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/Venues/VenueItem/__specs__/VenueItem.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx, pro/src/utils/apiFactories.ts
=> (BSR)[API] feat: Add hasVenueProviders bool on `offerers/{id}` response

.github/workflows/release--deploy.yml
Ticket Jira : https://passculture.atlassian.net/browse/PC-25092
Un run de test / validation a été lancé ici : https://github.com/pass-culture/pass-culture-main/actions/runs/6655008759/job/18084288138
=> (PC-25092)[CI] Remove github secret from release--deploy.yml

api/src/pcapi/core/offers/validation.py
Fixer le bug de création de stocks qui casse car le route prend trop de temps
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25438
=> (PC-25438)[API] fix: fix bulk create stocks takes too long

pro/src/components/VenueForm/ReimbursementPoint/ReimbursementPoint.tsx, pro/src/components/VenueForm/VenueForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/__specs__/ReimbursementFields.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25479
=> (PC-25479)[PRO] fix: scrollIntoView not necessary anymore

pro/src/pages/Logout/Logout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25481
=> (PC-25481)[PRO] fix: do not call Beamer.destroy twice

pro/src/utils/cookieConsentModal.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25492
=> (PC-25492)[PRO] fix: orejime cookie error promise

pro/src/hooks/useAnalytics.ts, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25504
Ajout d'un test pour voir le nombre de fois que pro_flags est appelé et changement de la dépendance du useEffect
=> (PC-25504)[PRO] fix: pro flags call multiple time

api/src/pcapi/core/history/api.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/src/pcapi/routes/pro/users.py, api/src/pcapi/scripts/history/fix_action_history_modified_info.py, api/tests/core/history/test_api.py, api/tests/core/offerers/test_api.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/routes/backoffice/venues_test.py, api/tests/routes/pro/patch_user_identity_test.py, api/tests/routes/pro/patch_user_phone_test.py, api/tests/routes/pro/patch_venue_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24629
=> (PC-24629)[API] fix: venue history

api/src/pcapi/routes/backoffice/home.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/templates/home/home.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24726
=> (PC-24726)[BO] feat: search offers by validation status without advanced search

pro/src/app/AppRouter/routesMap.tsx, pro/src/pages/Reimbursements/Reimbursement.module.scss, pro/src/pages/Reimbursements/ReimbursementBanners.module.scss, pro/src/pages/Reimbursements/Reimbursements.tsx, pro/src/pages/Reimbursements/ReimbursementsBanners.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25511
=> (PC-25511)[PRO] fix: multiple api call in reimbursement page

api/src/pcapi/routes/public/individual_offers/v1/products.py, api/tests/routes/public/individual_offers/v1/get_product_by_ean_test.py
Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25311
=> (PC-25311) throw error if venue id is wrong

api/src/pcapi/repository/clean_database.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerers_stats.py
Ajout des statistiques de l'offerer à la sandbox
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25255
=> (PC-25255)[API] feat: add offerer stats sandbox data

.github/workflows/deploy.yml
Ticket Jira : https://passculture.atlassian.net/browse/PC-25093
=> (PC-25093)[ci] Replace github secret by secret manager in deploy.yml

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_products_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25346
=> (PC-25346)fix: allow 1000+ char offers to be returned to user

pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementDetails.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25513
=> (PC-25513)[PRO] fix: multiple api call in reimbursement details

pro/src/pages/Home/Homepage.scss, pro/src/pages/Home/HomepageBreadcrumb.tsx, pro/src/pages/Home/Venues/Venue.scss, pro/src/pages/Home/Venues/Venue.tsx
=> (BSR)[PRO] fix: small fixes on homepage

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25304
=> (PC-25304)[BO] fix: regressions in beneficiary search performance

api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/bank_accounts.html, api/src/pcapi/utils/urls.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24809
=> (PC-24809)[BO] feat: add bank accounts tab on offerer details page

api/src/pcapi/core/offers/api.py, api/tests/core/offers/test_api.py
=> (PC-25519)[API] feat: change stocks stats to return correct remainingQuantity

pro/scripts/customRequest.ts, pro/src/apiClient/adage/core/request.ts, pro/src/apiClient/v1/core/request.ts, pro/src/apiClient/v2/core/request.ts
BSR
j'ai mergé la pr Fail to fetch un peu vite je n'avais pas vu qu'il restait des erreurs de type
fix : dans un catch error et de type any ou Unknown et non Error -> on vérifie que c'est une Error (qui a donc un message)
=> (BSR)[PRO] fix: type error on Error in request

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24475
=> (PC-24475)[PRO] refactor: wording invoice filter label

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/templates/accounts/search.html, api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24496
=> (PC-24496)[BO] feat: remove search by birth date

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25374
=> PC-25374)[API] feat:  create test case sanbox and add gtl data to it

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231031T145337_389e0a92925f_update_action_history_constraint.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/history/models.py, api/src/pcapi/routes/backoffice/bank_account/blueprint.py, api/src/pcapi/routes/backoffice/bank_account/forms.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/bank_account/get.html, api/tests/routes/backoffice/bank_account_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25278
=> (PC-25278)[BO] feat: edit bank account label

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice/forms/search.py, api/src/pcapi/routes/backoffice/pro.py, api/src/pcapi/utils/human_ids.py, api/tests/routes/backoffice/bank_account_test.py, api/tests/routes/backoffice/pro_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25036
Note : le code pour la fonction `dehumanize` dans human_ids.py a été repris sans modification dans l'historique git ; commit 90353fa6199c81ce69dd60f842d2a3b2b63e12e7.
=> (PC-25036)[BO] feat: search for bank account

api/src/pcapi/routes/serialization/offerers_serialize.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/OfferImage.ts, pro/src/apiClient/v1/models/TopOffersResponseData.ts
Fix offerer stats image top offers image serialization
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23889
=> (PC-23889) get offerer stats api

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/__specs__/FiltersTags.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24983
Ajout de tags pour les filtres de recherche Adage 
**Screen**
=> Pc 24983 eac add tags for adage filters

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24475
Wording page justificatifs de remboursements
=> (PC-24475)[PRO] fix: wording depending new bank details journey ff

.github/workflows/reusable--build-and-tag.yml
Fix de la mauvaise notification quand on crée une release.
J'ai essayé de testé ici : 
https://github.com/pass-culture/pass-culture-main/actions/runs/6732238523 #run echoué
https://github.com/pass-culture/pass-culture-main/actions/runs/6732252429 #run réussi
=> (BSR)[ci] fix notification issue

api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py
=> (BSR)[API] refactor: don't use reduce on set.intersection

api/src/pcapi/connectors/titelive.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/external_bookings/ems/client.py, api/src/pcapi/core/external_bookings/serialize.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/mails/backends/sendinblue.py, api/src/pcapi/core/mails/models.py, api/src/pcapi/core/reference/models.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/domain/price_rule.py, api/src/pcapi/domain/titelive.py, api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py, api/src/pcapi/local_providers/titelive_thing_descriptions/titelive_thing_descriptions.py, api/src/pcapi/local_providers/titelive_thing_thumbs/titelive_thing_thumbs.py, api/src/pcapi/local_providers/titelive_things/titelive_things.py, api/src/pcapi/repository/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py, api/tests/connectors/titelive/titelive_test.py, api/tests/core/mails/tests.py, api/tests/core/offers/test_api.py
=> Bsr remove type ignores no untyped def

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24356
=> (PC-24356)[BO] fix: pricing condition on collective offer price update

api/tests/routes/public/booking_token/v2/patch_booking_keep_by_token_test.py, api/tests/routes/public/booking_token/v2/patch_booking_use_by_token_test.py
=> (BSR)[API] Tests de l'API Contremarque : Suppression d'un test inutile, clarification de quelques tests

api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py
Simplifier un peu ces usages de set() et de list()
=> (BSR)[API] refactor: remove some sets shenanigans

api/src/pcapi/connectors/serialization/titelive_serializers.py, api/src/pcapi/core/providers/titelive_music_search.py, api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24090
=> (PC-24090)[API] fix: allow empty titelive music codesupport

api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/templates/venue/get/stats.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/core/offerers/test_models.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24810
=> (PC-24810)[BO] feat: add bank account info on venue details page

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25374
=> (PC-25374)[API] fix: fix bug faker in test cases sandbox

pro/src/components/Breadcrumb/Breadcrumb.module.scss, pro/src/components/Breadcrumb/Breadcrumb.stories.tsx, pro/src/components/Breadcrumb/Breadcrumb.tsx, pro/src/components/Breadcrumb/__specs__/Breadcrumb.spec.tsx, pro/src/ui-kit/Hero/Hero.stories.tsx, pro/src/ui-kit/Hero/Hero.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25167
=> (PC-25167)[PRO] refactor: migrate 2 stories

api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/finance/generate_invoices_blueprint.py, api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/pivots/contexts/boost.py, api/src/pcapi/routes/backoffice/pivots/contexts/cgr.py, api/src/pcapi/routes/backoffice/pivots/contexts/cineoffice.py, api/src/pcapi/routes/backoffice/pivots/contexts/ems.py, api/src/pcapi/routes/backoffice/pivots/forms.py, api/src/pcapi/routes/backoffice/titelive/blueprint.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25574
=> (PC-25574)[BO] fix: missing background color on alert message

helmfile.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25539
Add new label for cronjob on staging/integration/ops/perf
=> (PC-25539) feat(prometheus): bump chart version

api/src/pcapi/routes/public/individual_offers/v1/serialization.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25386
=> (PC-25386) venue id field description in offers query params

pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/components/StocksEventList/__specs__/StocksEventList.spec.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/form/onSubmit.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24751
=> (PC-24751)[PRO] feat: improve stock deletion by using new routes

pro/src/ui-kit/Toggle/Toggle.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25170
=> (PC-25170)[PRO] refactor: migrate Toggle story

pro/src/ui-kit/Banners/Banner/Banner.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25171
Migrer la story du composant Banner
=> (PC-25171)[PRO] refactor: move banner story to csf3

.github/workflows/tests-api.yml
Ticket Jira: https://passculture.atlassian.net/browse/PC-25090
=> (PC-25090)[ci] Remove github secret from tests-api.yml

.github/workflows/reusable--build-and-tag.yml
Add an elif to manage cancelled workflows
=> (BSR)[ci] Fix notification for cancelled releases

api/src/pcapi/local_providers/allocine/allocine_stocks.py, api/tests/local_providers/allocine_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25341
=> (PC-25341)[API] feat: create a unique offer for VO/VF for allocine

api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_product_categories_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25409
=> (PC-25409)[API] feat: add route to get product subcategories

api/src/pcapi/core/bookings/api.py, api/tests/core/bookings/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25331
=> (PC-25331)[API] feat: catch charlie api notification exceptions

api/src/pcapi/connectors/big_query/queries/offerer_stats.py, api/src/pcapi/core/offerers/api.py
=> (BSR)[API] fix: top offers contains all offers

api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25515
=> (PC-25515)[API] fix: EMS synch create duo offers if duo offers option was selected by user

.github/workflows/reusable--build-and-tag.yml
Fix https://github.com/pass-culture/pass-culture-main/actions/runs/6796640611/job/18477322108#step:5:26
=> (BSR)[ci] Fix bash syntax issue

pro/src/pages/IndividualOfferWizard/Stocks/Stocks.tsx, pro/src/pages/IndividualOfferWizard/Stocks/__specs__/Stocks.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.RouteLeavingGuard.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/submitToApi.ts, pro/src/screens/IndividualOffer/StocksThing/utils/__specs__/buildInitialValues.spec.ts, pro/src/screens/IndividualOffer/StocksThing/utils/__specs__/setFormReadOnlyFields.spec.ts, pro/src/screens/IndividualOffer/StocksThing/utils/buildInitialValues.ts, pro/src/screens/IndividualOffer/StocksThing/utils/setFormReadOnlyFields.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25420
=> (PC-25420)[PRO] refactor: use getStock for things

api/.env.development, api/.env.testing, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/src/pcapi/sandboxes/scripts/sandbox_industrial.py, api/src/pcapi/sandboxes/scripts/save_sandbox.py, api/src/pcapi/scripts/sandbox.py, api/src/pcapi/settings.py
Cette PR fait 3 choses: 
- Autoriser la commande de lancement de la sandbox uniquement en testing et local
- Réindexer les éléments après lancement de la sandbox
- Prendre en compte les retours post-merge de [cette PR](https://github.com/pass-culture/pass-culture-main/pull/8963) cc @mageoffray  
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25374
None
=> PC-25374 update test cases sandbox

api/src/pcapi/routes/public/individual_offers/v1/products.py
Fix swagger description
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25409
=> (PC-25409) get product categories route swagger description

pro/src/ui-kit/Button/Button.stories.tsx, pro/src/ui-kit/Button/Button.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25166
Migration storybook composant Button
=> (PC-25166)[PRO] refactor: Button story

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_stocks_test.py, pro/src/apiClient/v1/models/GetStocksResponseModel.ts, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
Ajoute un paramètre hasStocks à la route GET stocks 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25599
=> (PC-25599)[API] feat: add hasStocks to get stocks route

api/src/pcapi/connectors/serialization/ems_serializers.py, api/tests/local_providers/cinema_providers/ems/fixtures.py
=> (BSR)[API] fix: Handle empty string as allocine_id

pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/components/StocksEventList/__specs__/StocksEventList.spec.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/adapters/serializers.ts, pro/src/utils/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24751
=> (PC-24751)[PRO] fix: use correct timezone when sending time

pro/src/pages/Home/StatisticsDashboard/CumulatedViews.tsx, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.module.scss, pro/src/ui-kit/chartGlobals.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23645
=> (PC-23645)[PRO] fix: improve chart design

pro/src/pages/IndividualOfferWizard/Stocks/__specs__/Stocks.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx
Suite à la modif en backend de stock_count en stockCount et de l'ajout de hasStock, modification de deux champs en front
=> (BSR)[PRO] fix: update stock_count and add hasStocks

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231106T155758_4110ad29566e_remove_audit_table_function.py, api/src/pcapi/alembic/versions/20231106T173335_24afb3d5f6af_remove_recommendation_functions.py
Commits à relire séparément. Désolé pour les nostalgiques.
=> (BSR)[API] Suppression de vieilles fonctions PostgreSQL inutiles

api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/collective_bookings.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-24801
=> (PC-24801)[BO] feat: link to collective booking search from incident details

api/src/pcapi/core/external_bookings/serialize.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25656
=> (PC-25656)[API] fix: allow empty booking confirmation datetime

api/src/pcapi/core/offers/offer_metadata.py, api/tests/core/offers/test_offer_metadata.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22120
=> (PC-22120)[API] feat: Add metadata for books

api/src/pcapi/connectors/api_recaptcha.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/connectors/api_recaptcha_test.py, api/tests/routes/native/v1/authentication_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24336
=> (PC-24336)[API] feat: make recaptcha token mandatory for native sign in

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231109T141601_7e51a47a52ef_remove_wip_backoffice_enable_redirect_single_result_ff.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/pro.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/pro_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25505
=> (PC-25505)[BO] chore: Remove feature flag WIP_BACKOFFICE_ENABLE_REDIRECT_SINGLE_RESULT

pro/package.json, pro/src/core/shared/utils/parseAndValidateFrenchPhoneNumber.ts, pro/src/ui-kit/form/PhoneNumberInput/utils/__specs__/getPhoneNumberInputAndCountryCode.spec.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24525
=> (PC-24525)[PRO] fix: detect Reunion country code phone number

api/src/pcapi/core/subscription/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/src/pcapi/settings.py, api/src/pcapi/workers/apps_flyer_job.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25520
=> (PC-25520)[API] feat: Send apps flyer event when user becomes beneficiary

pro/src/index.tsx, pro/src/sentry.ts
=> (BSR)[PRO] fix: add Sentry ignore errors

pro/src/utils/localStorageAvailable.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25731
=> (PC-25731)[PRO] fix: make localStorageAvailable more robust

pro/src/screens/OffererStats/OffererStatsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25728
https://sentry.passculture.team/organizations/sentry/issues/730406/?environment=staging&environment=production&project=2&query=is%3Aunresolved+Cannot+read+properties+of+undefined+%28reading+%27value%27%29&statsPeriod=14d
https://sentry.passculture.team/organizations/sentry/issues/422407/?environment=staging&environment=production&project=2&query=is%3Aunresolved+Cannot+read+properties+of+undefined+%28reading+%27value%27%29&statsPeriod=14d
https://sentry.passculture.team/organizations/sentry/issues/419233/?environment=staging&environment=production&project=2&query=is%3Aunresolved+Cannot+read+properties+of+undefined+%28reading+%27value%27%29&statsPeriod=14d
=> (PC-25728)[PRO] fix: offererStats and SelectAutocomplete property of undefined

.github/workflows/tests-api.yml
=> (BSR)[API] fix: use same sha for all jobs

pro/src/sentry.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25740
=> (PC-25740)[PRO] fix: update ignore sentry list

pro/src/screens/OffererStats/OffererStatsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25730
=> (PC-25730)[PRO] fix: add check on array length

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231113T141213_c3eff57a0838_remove_ff_wip_eac_enable_new_authentication_public_api.py, api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25726
delete feature flag WIP_EAC_ENABLE_NEW_AUTHENTICATION_PUBLIC_API
and from database
=> (PC-25726)[API] refactor: delete feature flag WIP_EAC_ENABLE_NEW_AUTHENTICATION_PUBLIC_API

api/src/pcapi/alembic/versions/20231113T141213_c3eff57a0838_remove_ff_wip_eac_enable_new_authentication_public_api.py
Ticket Jira (ou description si BSR) : réparer la CI
=> (BSR)[API] fix: fix black of this file

.github/workflows/deploy-app-engine-image-resizing.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25698
=> (PC-25698) ci: fix image resizing workflow

api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py
Ticket Jira (ou description si BSR) : modification du nom des variables dans la route get stocks pour mieux comprendre le code + utilisation de la fonction to_camel dans la serialisation
=> (BSR)[API] refactor: changed camelcase and stocks_count

pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardVenue/CardVenue.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardVenue/CardVenue.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardVenue/__specs__/CardVenue.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/AdageIframe/app/subRoutesAdage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25548
Ajout d'un composant carte lieu, pour la découverte
Au clic sur la carte on redirige l'utilisateur vers la recherche pré-filtré sur le lieu 
**Screen**
=> Pc 25548 eac add venue card component

pro/src/pages/Home/Offerers/VenueCreationLinks.tsx, pro/src/pages/Home/StatisticsDashboard/MostViewedOffers.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25724
=> (PC-25724)[PRO] fix: small ui fixes for stats dashboard

pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/CardOffer.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/CardOffer.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/__specs__/CardOffer.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/OfferFavoriteButton.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25620
Ajouter le bouton favori, sur les cartes offres de la page adage Découverte. 
BSR : Modification du type des offres pour être au plus près de l'API. On aura comme cela peut de modifications à faire une fois l'API modifiée. 
**Screen**
=> (PC-25620)[PRO] feat: Add favorite icon to card offer

api/requirements.txt, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/validation.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_beneficiary.py, api/src/pcapi/core/mails/transactional/bookings/booking_confirmation_to_beneficiary.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/domain/allocine.py, api/src/pcapi/local_providers/allocine/allocine_stocks.py, api/src/pcapi/local_providers/provider_api/synchronize_provider_api.py, api/src/pcapi/local_providers/titelive_thing_descriptions/titelive_thing_descriptions.py, api/src/pcapi/repository/user_queries.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/pro/collective_bookings.py, api/src/pcapi/routes/pro/venues.py, api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/src/pcapi/tasks/cloud_task.py, api/src/pcapi/utils/custom_keys.py, api/src/pcapi/utils/custom_logic.py, api/src/pcapi/utils/date.py, api/src/pcapi/utils/db.py, api/src/pcapi/utils/mailing.py
=> (BSR)[API] chore: Remove useless mypy type ignore

api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25749
En lecture seule :
=> (PC-25749)[BO] feat: read-only access to the lists of offerers and attachments to validate

api/src/pcapi/routes/pro/users.py, api/src/pcapi/routes/serialization/users.py, api/tests/routes/pro/patch_validate_email_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25024
=> (PC-25024)[API] refactor: clean legacy PRO email change validation

api/rebuild_staging.sh, api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/external_bookings/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25719
=> (PC-25719)[API] feat: Disable external bookings during rebuild_staging

api/src/pcapi/core/offers/offer_metadata.py, api/tests/core/offers/test_offer_metadata.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25732
=> (PC-25732)[API] feat: Add metadata for books

pro/public/.well-known/security.txt
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25802
=> (PC-25802)[PRO] build: add security.txt asset

pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts
Skip le test E2E en attendant de trouver une solution
=> (BSR)[PRO] fix: disable e2e signupJourneyCreateOfferer

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx, pro/src/core/FirebaseEvents/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25625
Tracker au niveau du lien de redirection de la bannière qui redirige vers remboursements/informations-bancaires
=> (PC-25625)[PRO] feat: add tracker for AddBankAccount banner link

api/src/pcapi/core/external/compliance.py, api/src/pcapi/core/external/compliance_backends/base.py, api/src/pcapi/core/external/compliance_backends/compliance.py, api/src/pcapi/core/external/compliance_backends/test.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/static/backoffice/scss/pc/_base.scss, api/tests/core/external/compliance_test.py, api/tests/routes/backoffice/helpers/html_parser.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24848
=> (PC-24848)[BO] feat: show compliance reasons for potential rejection

api/src/pcapi/core/offerers/api.py
https://sentry.passculture.team/organizations/sentry/issues/784161/?project=5
=> (BSR)[PRO] fix: UnboundLocalError: local variable 'venue' referenced before assignment

pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx, pro/src/core/FirebaseEvents/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25649
Ajout du tracker HasClickedAddVenueToBankAccount au clique sur le lien de la bannière :"Gérer le rattachement de mes lieux"
=> (PC-25649)[PRO] feat: tracker add venue to bank account

pro/src/ui-kit/Divider/Divider.stories.tsx, pro/src/ui-kit/Divider/Divider.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25172
=> (PC-25172)[PRO] feat: Migrate Divider story

api/src/pcapi/routes/backoffice/__init__.py, api/src/pcapi/routes/backoffice/external/zendesk_sell/blueprint.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/routes/backoffice/zendesk_sell_tests.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24643
=> (PC-24643)[BO] feat: Zendesk Sell Sync Button for Offerer and Venues

api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html
Correction petite erreur
Ticket Jira : https://passculture.atlassian.net/browse/PC-25243
=> (PC-25243)[BO] fix: offerer invitation user id

api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py
=> (BSR)[API] tests: fix flaky by using sets

api/src/pcapi/core/external_bookings/api.py, api/tests/routes/native/v1/bookings_test.py
I also added a logger.exception. It might spam integration channel but at the moment we want to be aware of it.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25580
=> (PC-25580)[API] fix: better error handling for booking creation

pro/src/ui-kit/InfoBox/InfoBox.stories.tsx, pro/src/ui-kit/InfoBox/InfoBox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25173
=> (PC-25173)[PRO] feat: migrate InfoBox story

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/search/commands/indexation.py, api/tests/core/educational/test_api.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25603
=> (PC-25603)[API] fix: offer template with end date in the past dont expire

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_product_categories_test.py
Enlever showsubtype des champs demandés dans l'api public
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25409
=> (PC-25409) remove showsubtype from categories conditional fields

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231019T132045_705d56381bae_add_bank_account_status_history_table.py, api/src/pcapi/core/finance/factories.py, api/src/pcapi/core/finance/models.py, api/tests/core/finance/test_models.py, pro/src/apiClient/v1/models/BankAccountApplicationStatus.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24709
=> (PC-24709)[API] feat: Keep tracks of bank accounts status history

pro/src/components/Callout/Callout.stories.tsx, pro/src/ui-kit/Timeline/Timeline.stories.tsx, pro/src/ui-kit/Timeline/Timeline.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25176
Migrer les stories des composants Callout et Timeline
=> Pc 25176 migrate stories callout timeline

api/src/pcapi/routes/adage_iframe/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25544
=> (PC-25544)[API] feat: tracking event has_seen_all_playlists

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx, pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx, pro/src/core/FirebaseEvents/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25639
Tracker boutont "Modifier" page remboursements/informations-bancaires
=> (PC-25639)[PRO] feat: add tracker for change venue attachment button

api/src/pcapi/algolia_settings_offers.json
Ticket Jira: https://passculture.atlassian.net/browse/PC-25633
=> (PC-25633)[API] feat: add artisrt and ean to algolia facets

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25375
=> (PC-25375)[API] feat: add offers from all categories to sandbox

api/src/pcapi/scripts/install.py
Installer une commande flask préalablement ajoutée au repo.
=> (PC-25719)[API] fix: install missing command

api/src/pcapi/routes/native/v1/authentication.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25911
=> (PC-25911)[API] feat: Use different redirect_uri for native sso

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/src/pcapi/validation/models/generic.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/pro/patch_publish_offer_test.py, pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25650
=> (PC-25650)[API] feat: Add `Offer.isNonFreeOffer` property

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25401
=> (PC-25401)[API] feat: add offers with different author cases to sandbox

pro/src/ui-kit/form/Select/Select.tsx, pro/src/ui-kit/form/Select/SelectInput.stories.tsx, pro/src/ui-kit/form/Select/SelectInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25175
=> (PC-25175)[PRO] chore: migrate story Select

api/src/pcapi/sandboxes/scripts/creators/big/__init__.py, api/src/pcapi/sandboxes/scripts/creators/big/create_books.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25378
=> (PC-25378)[API] feat: add 10 000 books to the sandbox

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25972
Erreur Sentry : https://sentry.passculture.team/organizations/sentry/issues/862582/
=> (PC-25972)[BO] fix: AttributeError: 'NoneType' object has no attribute 'Offerer'

pro/src/ui-kit/Tooltip/Tooltip.stories.tsx, pro/src/ui-kit/Tooltip/Tooltip.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25174
=> (PC-24671)[PRO] refactor: migrate Tooltip story

pro/src/screens/UserProfile/UserEmail/UserEmail.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25812
Branche: PC-25812-label-email
=> (PC-25812)[PRO] feat: Wording de champ adresse email

pro/src/pages/Bookings/ChoosePreFiltersMessage/ChoosePreFiltersMessage.module.scss, pro/src/pages/Bookings/ChoosePreFiltersMessage/ChoosePreFiltersMessage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25436
Ajout de nouveau svg.
Branche: PC-25436-reservations-icone2
=> (PC-25436)[PRO] feat: Wording de no reservation

.github/workflows/deploy-pro-pr-version-generic.yml, .github/workflows/node-run-command.yml, .github/workflows/tests-pro.yml
=> (BSR)[PRO] fix: update cache action with tagged version

pro/src/ui-kit/form/TextArea/TextArea.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25180
=> (PC-25180)[PRO] refactor: migrate Textarea story

pro/src/components/DialogBox/DialogBox.stories.tsx, pro/src/components/DialogBox/DialogBox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25181
=> (PC-25181)[PRO] refactor: migrate DialogBox story

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/reference/models.py, api/src/pcapi/utils/db.py
cf. commits à relire séparément
=> (BSR)[API] Correction dans `_generate_invoice()` et ajout de logs

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/conf.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/history/models.py, api/src/pcapi/core/offerers/models.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24003
=>  (PC-24003)[BO] feat: Cashflow generation for incidents

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Reporter aussi les filtres de préférence quand on vient d'un autre lien
Ticket Jira : https://passculture.atlassian.net/browse/PC-25431
=> (PC-25431)[BO] feat: Preserve preferences during search pro

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/routes/public/collective/endpoints/offers.py, api/src/pcapi/routes/public/collective/serialization/offers.py, api/tests/routes/public/blueprint_v2_openapi_test.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py, api/tests/routes/public/collective/endpoints/post_collective_offer_test.py, pro/src/apiClient/v2/index.ts, pro/src/apiClient/v2/models/EacFormat.ts, pro/src/apiClient/v2/models/PatchCollectiveOfferBodyModel.ts, pro/src/apiClient/v2/models/PostCollectiveOfferBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25767
Ajout des formats lors de la création et de l'édition d'une offre collective.
=> (PC-25767)[API] feat: public collective api: add formats

pro/src/ui-kit/SubmitButton/SubmitButton.stories.tsx, pro/src/ui-kit/SvgIcon/SvgIcon.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25182
=> (PC-25182)[PRO] refactor: migrate SvgIcon & SubmitButton stories

pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/CardOffer.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardOffer/__specs__/CardOffer.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardVenue/CardVenue.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/CardVenue/__specs__/CardVenue.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/DomainsCard.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/__specs__/DomainsCard.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/__specs__/AdageDiscovery.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25695
Ajouter un tracking lorsqu'on clique sur un élément d'une playlist
=> (PC-25695)[PRO] feat: add tracking for each playlist with element click

api/src/pcapi/core/external_bookings/serialize.py, api/src/pcapi/core/providers/factories.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/routes/native/v1/bookings.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_products.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_ean.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/bookings/test_api.py, api/tests/core/providers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25031
Fix 2 bugs and product sandbox data logic. We still need to delete some Products in the sandbox (like products for events offer or for "manually" created offers ).
=> (PC-25031)[API] fix : charlie things notif

api/src/pcapi/core/external_bookings/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25719
Promis, j'ai double-vérifié en local cette fois-ci !
=> (PC-25719)[API] fix: disable_external_bookings (again)

pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24281
- Correction de wording.
=> (PC-24281)[PRO] feat: Wording fixes.

api/src/pcapi/connectors/dms/serializer.py, api/src/pcapi/domain/demarches_simplifiees.py, api/src/pcapi/use_cases/save_venue_bank_informations.py, api/tests/connector_creators/demarches_simplifiees_creators.py, api/tests/domain/demarches_simplifiees_test.py, api/tests/use_cases/save_venue_bank_informations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25959
=> (PC-25959)[API] fix: Don’t overwrite compliance annotations

.github/workflows/deploy-maintenance-site.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25997
Exemple que ça fonctionne : https://github.com/pass-culture/pass-culture-main/actions/runs/6972121772
=> (PC-25997)[API] chore: delete maintenance deploy production tag

api/src/pcapi/core/users/repository.py, api/src/pcapi/routes/shared/passwords.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25738
=> (PC-25738)[API] refactor: Remove legacy token for PRO new password

api/src/pcapi/core/users/factories.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25378
après avoir mergé le changement nécéssaire au ticket on a relancer la sandbox industrial puis la sandbox big avec -c false
La sandbox essayez de créer un bénéficiaire avec un email existant: la sequence reprenait de 0 quand on lançait une nouvelle sandbox.
=> Pc 25378 Fix can launch sandbox without clear

api/src/pcapi/core/offerers/api.py
Cette ligne supprimée cause la fonction à rester bloquée dans quelques cas
=> (BSR)[API] fix: remove db session add all

.github/workflows/deploy-pro-pr-version-generic.yml, .github/workflows/node-run-command.yml, .github/workflows/tests-pro.yml
=> (BSR) fix action gcs cache to v1.0.1

pro/src/ui-kit/form/Checkbox/Checkbox.stories.tsx, pro/src/ui-kit/form/Checkbox/Checkbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25179
Migrer la story Checkbox
=> (PC-25179)[PRO] refactor: migrate checkbox story

pro/src/components/HelpLink/HelpLink.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25178
Migrer la story HelpLink
=> (PC-25178)[PRO] refactor: migrate help link story

api/src/pcapi/core/offerers/api.py, api/tests/core/external/offerer_stats_test.py
=> (BSR)[API] fix: remove request to get last created offers

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/core/mails/transactional/users/reset_password.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/shared/passwords.py, api/tests/core/mails/transactional/users/reset_password_test.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25913
=> (PC-25913)[API] feat: Use different reset password template for suspicious login

pro/src/components/VenueForm/VenueForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25905
- Le scroll vers la partie des remboursements est remis.
=> (PC-25905)[PRO] fix: Added back wrongly removed scroll.

api/src/pcapi/connectors/dms/api.py, api/src/pcapi/connectors/dms/graphql/pro/get_bank_info_status.graphql, api/tests/routes/backoffice/bank_account_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26013
=> (PC-26013)[BO] fix: DMS bank account validation date displayed was wrong for archived applications

pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25828
Ajouter le lien du questionnaire pour la découverte
=> (PC-25828)[PRO] feat: add qualtrics link for discovery

api/src/pcapi/connectors/dms/api.py, api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26017
=> (PC-26017)[API] fix: PRO DS improve bank info applications handling

api/src/pcapi/core/finance/api.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/tests/core/finance/test_api.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25657
Ajout de données dans la sandbox :
- Des offres collectives au statut USED dont la date d'événement est dépassée de plusieurs jours
- Un incident total ET un incident partiel sur la structure avec justificatif copieux, présents dans le justificatif de remboursement (à confirmer après passage de la PR cashflow ou intégration des incidents aux justificatifs de remboursement)
=> (PC-25657)[BO] feat: Add data to sandbox

api/src/pcapi/core/educational/models.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26042
=> (PC-26042)[API] fix: empty offer's dateRange in hasEndDatePassed

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24362
- Dialogue de confirmation quand un utilisateur change les liens entre les lieux et les comptes bancaires puis appuie sur le bouton annuler.
=> Pc 24362 cancel not saving dialog

api/src/pcapi/core/finance/models.py, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/list.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25596
=> (PC-25596)[BO] feat: Add isClosed property to FinanceIncident

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23423
- Ajout d'une popin de confirmation en cas de dé sélection d'un lieu.
=> Pc 23423 unlink venue dialog
