pass-culture/pass-culture-main

pro/src/pages/Offerers/Offerer/VenueV1/fields/ReimbursementFields/ReimbursementFields.tsx
- Correction suite à un commentaire [ici](https://github.com/pass-culture/pass-culture-main/pull/9298#discussion_r1407407334) pour vérifier que le node n'est pas null.
=> (BSR)[PRO] fix: Fix issue where the node is null.

pro/src/core/FirebaseEvents/constants.ts, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25640
- Tracker la sauvegarde des lieux pour les comptes bancaires.
=> (PC-25640)[PRO] feat: Track bank account venues saving.

api/src/pcapi/utils/regions.py, api/tests/core/search/test_serialize_algolia.py
A fix was tried in 61611958de but was not enough (and poorly tested).
Ticket Jira d'origine : PC-25045. Je ne le mentionne pas dans le
message de commit ou dans le titre de la pull request, de peur de
casser quelque chose dans l'intégration entre Jira et Git...
=> (BSR)[API] fix: Fix indexation of collective offers in Monaco

pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25640
- Correction du tracker utilisé à l'enregistrement.
=> (PC-25640)[PRO] fix: Fix bank account venues saving tracker.

api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/bookings.py, api/src/pcapi/routes/adage_iframe/logs.py
suppression de directives `ignore` à destination de mypy sur les logs adage.
=> (BSR)[ADAGE] chore: improve adage's logs typing

pro/cypress/e2e/createEventIndividualOffer.cy.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26114
**Objectif**
Corriger le format des prix, suite à l'utilisation de l'api internationalisation dans la fonction de formatage des prix.
=> (PC-26114)[PRO] fix: Price format in e2e tests

api/src/pcapi/core/educational/adage_backends/serialize.py, api/src/pcapi/routes/adage/v1/serialization/prebooking.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py
Fix : une offre collective peut ne pas avoir de sous-catégorie (depuis peu).
=> (BSR)[EAC] fix: adage iframe: subcategory can now be null

pro/src/components/Callout/Callout.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26054
- Enlever le border des bannières
=> (PC-26054)[PRO] style: Callout without borders.

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231129T105419_e7f8b2b66df7_drop_cgr_encrypted_password_cgr_column.py, api/src/pcapi/connectors/cgr/cgr.py, api/src/pcapi/core/providers/factories.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/backoffice/pivots/contexts/cgr.py, api/tests/connectors/cgr/api_cgr_test.py
1/3
(pre) Create encryptedPassword column
Make the code write into that column
(post) Populate that column with existing data
(post) Make that column non-nullable
2/3
Make the code read encryptedPassword column
Make the code write encrypted values into password column
(post) Populate password column with encrypted values from encryptedColumn
3/3
Make the code read&write into password column
(post) Detete encryptedPassword column
=> (BSR)[API] feat: cipher CGR sensitive data 3/3

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_stats_v2_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetOffererV2StatsResponseModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25706
=> (PC-25706) add offerer stats v2 route

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231128T161236_b13e003de3a9_remove_pro_stock_pagination_ff.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/pro/stocks.py, api/src/pcapi/routes/public/books_stocks/serialization.py, api/tests/core/offers/test_repository.py, api/tests/routes/pro/get_stocks_test.py, api/tests/routes/pro/post_stocks_test.py, pro/src/apiClient/v1/models/StocksResponseModel.ts, pro/src/screens/IndividualOffer/StocksEventCreation/__specs__/StocksEventCreation.spec.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/form/__specs__/onSubmit.spec.ts, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/adapters/upsertStocksEventAdapter.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/adapters/__specs__/upsertStocksThingAdapter.spec.tsx
On supprime le FF afin de passer la création/modification des stocks sur la route paginée offer/ stocks
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25945
=> (PC-25945)[API] feat: remove pagination FF

api/src/pcapi/models/feature.py
=> (BSR)[API] fix: Disable incident feature flag by default

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26065
**Objectif**
Ajouter un FF qui sera utilisé pour activer les différentes interfaces liées à l'initiative "Marseille en grand" en début d'année.
=> (PC-26065)[PRO] feat: Create WIP_ENABLE_MARSEILLE FF

api/src/pcapi/connectors/api_allocine.py, api/src/pcapi/connectors/serialization/allocine_serializers.py, api/src/pcapi/domain/allocine.py, api/src/pcapi/local_providers/allocine/allocine_stocks.py, api/src/pcapi/utils/requests.py, api/tests/connectors/api_allocine_test.py, api/tests/domain/allocine_test.py, api/tests/domain/fixtures.py, api/tests/local_providers/allocine_stocks_test.py
Tickets Jira : 
- https://passculture.atlassian.net/browse/PC-25891
- https://passculture.atlassian.net/browse/PC-25902
=> PC-25891 Add Allocine movieList endpoint handling

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/tests/core/finance/test_api.py, api/tests/routes/backoffice/collective_offers_test.py
Most calls to this function do not require a commit.
=> (BSR)[API] refactor: Remove `commit` argument from `add_event()`

.github/workflows/deploy-app-engine-image-resizing.yaml, .github/workflows/reusable--build-and-tag.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26164
=> (PC-26164) feat: add sha or tag in version.txt image-resizing

.github/workflows/deploy-app-engine-image-resizing.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26164
=> (PC-26164) fix: use sha in version.txt image-resizing testing

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231130T144208_59ecb650a586_change_constraint_for_role_permissions_changed.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/history/models.py, api/src/pcapi/core/permissions/api.py, api/src/pcapi/routes/backoffice/admin/blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/admin/roles.html, api/src/pcapi/routes/backoffice/templates/admin/roles_history.html, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/tests/routes/backoffice/admin_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25246
test front succes ->
=> (PC-25246)[API] feat: added history on permission modification

pro/src/ui-kit/Tabs/Tabs.module.scss, pro/src/ui-kit/Tabs/Tabs.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26051
=> (PC-26051)[PRO] style: spacing label with icon

pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.tsx, pro/src/components/IndividualOfferNavigation/LabelBooking/LabelBooking.module.scss, pro/src/components/IndividualOfferNavigation/LabelBooking/LabelBooking.tsx, pro/src/components/IndividualOfferNavigation/LabelBooking/__specs__/LabelBooking.spec.tsx, pro/src/components/Stepper/Stepper.tsx, pro/src/core/Offers/adapters/getIndividualOfferAdapter/__specs__/serializers.spec.ts, pro/src/core/Offers/adapters/getIndividualOfferAdapter/serializers.ts, pro/src/core/Offers/types.ts, pro/src/utils/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24884
=> (PC-24884)[PRO] feat: add booking count on recap page

pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.module.scss, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26119
=> (PC-26119)[PRO] feat: hide top offers if no top offers

pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx, pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/Venues/VenueList.tsx, pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx, pro/src/pages/Home/Venues/__specs__/Venue.tracker.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24282
Affichage du bouton "afficher un compte bancaire" sur la page d'accueil
1er lieu:
Si aucun compte bancaire à l'échelle de la structure
Si aucune offre TOUT COURT
2nd lieu et les autres:
Si aucun compte bancaire à l'échelle de la structure
Si aucune offre PAYANTE à l'échelle de la structure
=> (PC-24282)[PRO] fix: display homepage add bank account button

.github/workflows/deploy-app-engine-image-resizing.yaml, .github/workflows/deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26231
=> (PC-26231) ci: fix app engine ehp/prod service account deploy

.github/workflows/tests-main.yml
https://passcultureteam.slack.com/archives/C01CTV65S3A/p1701700770877329
Le déploiement a l'air de bien fonctioner : https://github.com/pass-culture/pass-culture-main/actions/runs/7089721268 C'est moi qui ai coupé pour ne pas aller au bout
=> (BSR)[API] ci: always deploy api and pro on master

api/src/pcapi/connectors/dms/serializer.py, api/src/pcapi/core/finance/ds.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/finance/utils.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/domain/demarches_simplifiees.py, api/src/pcapi/models/feature.py, api/src/pcapi/use_cases/save_venue_bank_informations.py, api/tests/connector_creators/demarches_simplifiees_creators.py, api/tests/core/finance/test_utils.py, api/tests/use_cases/save_venue_bank_informations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25759
=> (PC-25759)[API] feat: Handle DSv4 and DSv5 context in new bankAccount journey

api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/collective_bookings.html, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/tests/routes/backoffice/finance_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25536
=> (PC-25536)[BO] feat: rework displayed status to match those used on pro

api/src/pcapi/connectors/dms/serializer.py, api/src/pcapi/domain/demarches_simplifiees.py, api/src/pcapi/use_cases/save_venue_bank_informations.py, api/tests/domain/demarches_simplifiees_test.py, api/tests/use_cases/save_venue_bank_informations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26035
=> (PC-26035)[API] feat: DS BankInformation avoid unnecessary http calls

api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-26263
=> (PC-26263)[BO] fix: columns in individual bookings list when WIP_ENABLE_FINANCE_INCIDENT is disabled

api/src/pcapi/scripts/update_allocine_offers_price_categories.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26121
=> (PC-26121)[API] fix: re-attach price categories to new allocine offers

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/collective_offers.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/patch_collective_offer_publication_test.py, api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26028
=> (PC-26028)[API] feat: Add `isNonFreeOffer` field on publish collective route

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231205T094136_9b8702ecd055_remove_offereid_unique_constraint_on_bank_information_table.py, api/src/pcapi/core/finance/models.py, api/tests/connector_creators/demarches_simplifiees_creators.py, api/tests/infrastructure/repository/bank_informations/bank_informations_sql_repository_test.py, api/tests/use_cases/save_venue_bank_informations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26038
=> (PC-26038)[API] feat: Make offerer have more than one BankInformation

pro/src/ui-kit/NotificationToaster/Notification.stories.tsx, pro/src/ui-kit/NotificationToaster/NotificationToaster.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25186
=> (PC-25186)[PRO] refactor: migrate notificationToaster story

api/src/pcapi/core/providers/titelive_api.py, api/tests/connectors/titelive/fixtures.py, api/tests/providers/titelive_search_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24090
=> (PC-24090)[API] fix: definition of a filled titelive music page

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/commands.py, api/src/pcapi/core/users/models.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25666
=> (PC-25666)[API] feat: add anonymization for beneficiary users

.github/workflows/tests-main.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25450
=> (PC-25450)[API] ci: Start test all the time on maint branches

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26183
=> (PC-26183)[API] fix: accounting software does not support semicolon in CSV values

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26071
=> (PC-26071)[API] feat: Change email template for booking reminder

pro/src/ui-kit/ListIconButton/ListIconButton.stories.tsx, pro/src/ui-kit/ListIconButton/ListIconButton.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25187
=> (PC-25187)[PRO] refactor: migrate ListButtonIcon story

pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26232
=> (PC-26232)[PRO] fix: remove target blank from offer links in booking table

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/repository.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26005
=> (PC-26005)[API] feat: Don't link venue to bankAccount if no pricingPoint exists

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/commands.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_gdpr_users.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25927
Mais en fait cette PR est pour corriger les petites erreurs suite au test de l'anonymisation sur testing
=> (PC-25927)[API] fix: Misc. fixes around anonymization after checking on testing

.github/workflows/tests-main.yml
Fix missing quote to allow tests run
=> (BSR) fix(ci): Add missing quote

.github/workflows/tests-main.yml
=> (BSR)[API] ci: remove extraneous brackets

api/src/pcapi/routes/pro/stocks.py, api/tests/routes/pro/post_stocks_test.py
Pour HF en prod 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26287
=> (PC-26287)[API] fix: price modification for product with no duplication

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx, pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/PricingPointDialog.tsx, pro/src/pages/Reimbursements/BankInformations/__specs__/LinkVenuesDialog.spec.tsx, pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23432
Fix la pop-in SIRET de valorisation : 
- Lorsqu'on fermait la pop-in, le bouton `sélectionner un siret` aparraissait de nouveau alors qu'on venait d'ajouter un pricing point
- Impossible de fermer la pop-in SIRET de valorisation
=> Pc 23432 pro update pricing point on close

api/src/pcapi/connectors/big_query/queries/__init__.py, api/src/pcapi/connectors/big_query/queries/last_30_days_booking.py, api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/commands/indexation.py, api/tests/core/search/test_api.py, api/tests/core/search/test_commands_indexation.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25834
=> (PC-25834)[API] feat: Use big query to get last 30 days bookings

pro/src/pages/Home/StatisticsDashboard/OfferStats.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingOfferCell.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/form/onSubmit.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26302
=> (PC-26302)[PRO] fix: quand le titre de l'offre est trop long il déborde sur la colone d'à côté

api/poetry.lock, api/pyproject.toml, api/src/pcapi/flask_app.py, api/src/pcapi/utils/sentry.py
Nothing notable in the changelog: https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md
=> (BSR)[API] chore: Bump sentry-sdk

pro/src/components/Newsletter/Newsletter.module.scss, pro/src/components/Newsletter/Newsletter.tsx, pro/src/styles/variables/_z-index.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26253
Fix la zone cliquable de la bannière Newsletter
=> (PC-26253)[PRO] fix: fix newsletter link

pro/src/ui-kit/IconLinkBox/IconLinkBox.stories.tsx, pro/src/ui-kit/IconLinkBox/IconLinkBox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25189
=> (PC-25189)[PRO] refactor: migrate iconlinkbox stories

api/src/pcapi/routes/adage_iframe/playlists.py
Intended for testing and development only.
Since data can not generate consistent set for testing, we end up with empty playlists.
To be able to perform user validation both localy and in testing the backend will return a random set of *existing* collective offers / collective offer templates / venues depending on the requested playlist
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26336
=> (PC-26336)[ADAGE] feat: fake data for playlists in testing

api/src/pcapi/core/bookings/repository.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-24163
=> (PC-24163)[BO] feat: export bookings from offer

api/Dockerfile, api/README.md, api/pyproject.toml, api/setup.cfg
Passer de la version 3.10 de Python à la version 3.11
=> (BSR)[API] build: Upgrade Python to 3.11

.github/dependabot.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26346
=> (PC-26346)[API] feat: Update dependabot configuration

pro/cypress/e2e/createEventIndividualOffer.cy.ts, pro/cypress/e2e/createThingIndividualOffer.cy.ts, pro/cypress/e2e/signupJourneyCreateOfferer.cy.ts, pro/cypress/support/commands.ts, pro/cypress/support/index.d.ts, pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss, pro/src/components/SummaryLayout/SummaryLayout.module.scss, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.module.scss, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/ui-kit/Tabs/Tabs.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24836
**Objectif**
Rendre responsive la page de résumé d'une offre individuelle.
=> (PC-24836) responsive offer summary

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx, pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26327
Ajouter le lien sur le bouton `Suivre le dossier`
=> (PC-26327)[PRO] feat: add link to follow bank account

api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/src/pcapi/sandboxes/scripts/sandbox_industrial.py
Ticket Jira  https://passculture.atlassian.net/browse/PC-26368
=> (PC-26368)[API] refactor: Move function from industrial to test cases sandbox

api/src/pcapi/routes/public/collective/endpoints/offers.py, api/src/pcapi/routes/public/collective/serialization/offers.py, api/tests/routes/public/blueprint_v2_openapi_test.py, api/tests/routes/public/collective/endpoints/get_collective_offer_public_provider_test.py, api/tests/routes/public/collective/endpoints/offers_test.py, pro/src/apiClient/v2/models/GetPublicCollectiveOfferResponseModel.ts, pro/src/apiClient/v2/services/ApiOffresCollectivesService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26293
=> (PC-26293) collective public api fix missing formats

api/src/pcapi/models/feature.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_test.py, pro/src/apiClient/v1/models/GetOffererVenueResponseModel.ts, pro/src/pages/Offerers/Offerer/OffererDetails/Venues/VenueItem/__specs__/VenueItem.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.tsx, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26285
=> (PC-26285)[PRO] feat: Ajout de isPermanent/image de la venue dans GetOffererVenueResponseModel

pro/src/components/Callout/Callout.stories.tsx, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.stories.tsx, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25184
=> (PC-25184)[PRO] refactor: cleanup RadioButtonWithImage story

pro/src/ui-kit/Pagination/Pagination.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25185
=> (PC-25185)[PRO] refactor: cleanup Pagination story

api/src/pcapi/core/offers/api.py, api/tests/core/offers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26296
=> (PC-26296)[API] feat: track price changed in stocks

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231206T103924_3ab07dc09e34_add_deactivable_mixin_to_validation_rules.py, api/src/pcapi/alembic/versions/20231206T104919_34eb58880f79_add_offer_validation_rule_to_action_history.py, api/src/pcapi/alembic/versions/20231207T140635_2e4475aaf41d_add_rule_id_to_action_history_constraint.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/history/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offer_validation_rules/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/src/pcapi/routes/backoffice/templates/offer_validation_rules/history.html, api/src/pcapi/routes/backoffice/templates/offer_validation_rules/list_rules.html, api/src/pcapi/routes/backoffice/templates/offer_validation_rules/sub_rules_extra_row.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offer_validation_rules.py, api/tests/core/history/test_factories.py, api/tests/routes/backoffice/offer_validation_rules_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24634
=> (PC-24634)[API] feat: add history to offer validation rules

pro/src/components/Newsletter/Newsletter.module.scss, pro/src/pages/Home/Homepage.module.scss, pro/src/pages/Home/Homepage.scss, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/OffererDetails.module.scss, pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/Venues/Venue.module.scss, pro/src/pages/Home/Venues/Venue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25554
Fin du responsive page d'accueil
Migration du fichier scss vers module
Refactor OffererDetails
- Suppression des tabs sur mobile
- Suppression de l'icône mail de la bannière sur mobile
=> (PC-25554)[PRO] style: offerer select and button responsive

.github/workflows/deploy-app-engine-image-resizing.yaml
=> (PC-26448)[API] ci: fix missing need statement

pro/cypress/e2e/cookieBanner.cy.ts, pro/sonar-project.properties
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25621
- Tests E2E cypress de la bannière de cookies
=> (PC-25621)[PRO] test: Cookie banner tests.

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26237
Ouvrir le lien `Suivre le dossier` dans un nouvel onglet
=> (PC-26237)[PRO] fix: record follow up link open in new tab

pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/validationSchema.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25961
=> (PC-25961)[PRO] fix: do not validate stock if it is empty in edition

pro/src/components/Banner/BannerRGS.tsx, pro/src/components/Banner/__specs__/BannerRGS.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25754
Branche: PC-25754-callout-signin
=> (PC-25754)[PRO] style: Ajout Callout à signin page

api/src/pcapi/routes/pro/users.py, api/src/pcapi/routes/serialization/users.py, api/src/pcapi/settings.py, api/tests/routes/pro/signin_test.py, pro/src/apiClient/v1/models/LoginUserBodyModel.ts
Add settings with whitelisted email adress to skip recaptcha check. 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26460
=> (PC-26460)[API] fix: add whitelist for recaptcha signin

api/src/pcapi/core/external/zendesk_sell_backends/testing.py, api/src/pcapi/core/external/zendesk_sell_backends/zendesk_sell.py, api/src/pcapi/routes/backoffice/external/zendesk_sell/blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/tests/core/external/zendesk_sell_test.py, api/tests/routes/backoffice/helpers/html_parser.py, api/tests/routes/backoffice/zendesk_sell_tests.py, api/tests/routes/pro/patch_venue_test.py, api/tests/routes/pro/post_venue_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26370
=> (PC-26370)[BO] fix: Zendesk Sell synchronization (fix and test)

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py, pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.stories.tsx
Reporter sur la sandbox de testing une modification faite sur des données de production en production
Ticket Jira : https://passculture.atlassian.net/browse/PC-26449
=> (PC-26449)[ADAGE] feat: update domains in testing

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/serialization/collective_bookings_serialize.py, api/tests/routes/pro/get_collective_booking_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/CollectiveBookingBankAccountStatus.ts, pro/src/apiClient/v1/models/CollectiveBookingByIdResponseModel.ts, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine/CollectiveTimeLine.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine/__specs__/CollectiveTimeLine.spec.tsx, pro/src/utils/collectiveApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24843
=> (PC-24843)[API] feat: Adapt `GET /collective/booking/{id}` to new bank account journey

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/core/users/test_api.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-22419
=> (PC-22419)[API] fix: do not deactivate anonymized users

pro/src/screens/SignupJourneyForm/Validation/Validation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25758
Branche: PC-25758-callout-2inscription
Parcours siret, étape 3-validation, en bah.
=> (PC-25758)[PRO] style: Ajout de callout sur validation de siret

api/src/pcapi/core/providers/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25941
PR côté pass-culture-deployment : https://github.com/pass-culture/pass-culture-deployment/pull/296
=> (PC-25941)[API] feat: add flask command for allocine products synchronization

api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offer_test.py, pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26399
=> (PC-26399)[API] feat: add has_stocks to GET offer route

api/tests/core/bookings/test_repository.py
=> (BSR)[API] fix: flaky tests considering useless freezetime usage

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26242
=> (PC-26242)[API] feat: backoffice offer display author link

pro/scripts/customRequest.ts, pro/src/apiClient/adage/core/request.ts, pro/src/apiClient/v1/core/request.ts, pro/src/apiClient/v2/core/request.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26358
Fix pour empêcher la page de connexion de se recharger quand les identifiants saisies sont incorrects
=> (PC-26358)[PRO] fix: remove unnecessary redirection on signin error

api/tests/routes/native/v1/authentication_test.py
=> (BSR)[API] fix: fix sso test

api/src/pcapi/sandboxes/scripts/creators/data/create_data_event_products.py, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_app_users.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_products.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/src/pcapi/sandboxes/scripts/mocks/event_mocks.py, api/tests/sandboxes/scripts/create_industrial_app_users_test.py
2 commits, à relire séparément. J'en ai profité pour corriger un petit bug dans la sandbox en voyant une erreur lors de l'exécution de la sandbox.
=> (BSR)[API] feat: Remove activation offers from sandbox

api/src/pcapi/routes/backoffice/templates/components/links.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26087
avant: 
après:
=> (PC-26087)[BO] feat: add picto for link to PRO and change picot for links to BO

api/src/pcapi/routes/public/booking_token/v2/endpoints.py, api/tests/routes/public/blueprint_v2_openapi_test.py, pro/src/apiClient/api.ts, pro/src/apiClient/v2/AppClientV2.ts, pro/src/apiClient/v2/index.ts, pro/src/apiClient/v2/services/DPrCiEApiContremarqueService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23824
=> (PC-23824)[API] feat: Add deprecation warning for CM API V2

api/src/pcapi/scripts/provider/bulk_create_venue_provider.py
Script to bulk activate providers on venues
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26258
=> (PC-26258)[API] feat: new script to create venue_providers

api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26182
=> (PC-26182)[BO] feat: add all tags to offerer list page

pro/src/app/AppRouter/findCurrentRoute.ts, pro/src/app/AppRouter/routesMap.tsx, pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx, pro/src/app/AppRouter/subroutesReimbursements.tsx, pro/src/app/AppRouter/subroutesSignupJourneyMap.tsx, pro/src/app/AppRouter/subroutesSignupMap.tsx, pro/src/pages/IndividualOfferWizard/IndividualOfferWizard.tsx, pro/src/pages/IndividualOfferWizard/__specs__/IndividualOfferWizard.spec.tsx, pro/src/pages/IndividualOfferWizard/__specs__/IndividualOfferWizardAdmin.spec.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/Reimbursements.spec.tsx, pro/src/pages/Signup/Signup.tsx, pro/src/pages/Signup/__specs__/Signup.spec.tsx, pro/src/pages/SignupJourneyRoutes/SignupJourneyRoutes.tsx, pro/src/pages/SignupJourneyRoutes/__specs__/SignupJourneyRoutes.spec.tsx, pro/src/pages/SignupJourneyRoutes/__specs__/SignupJourneyRoutes.trackers.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx
Pour préparer le lazy load des sous routes du IndividualOfferWizard, il faut utiliser le pattern avec Outlet (sinon le lazy load ne marche pas)
=> (BSR)[PRO] refactor: use outlet pattern for subrouters

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231215T083802_562ae6d8be2f_venue_can_be_linked_to_only_one_bank_account_at_a_time.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/exceptions.py, api/src/pcapi/core/finance/repository.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/pro/offerers.py, api/tests/routes/backoffice/bank_account_test.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26410
=> (PC-26410)[API] feat: Update bank account venues links Check if venue isn't already linked and add db constraint

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_events_test.py, api/tests/routes/public/individual_offers/v1/get_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26545
Fix get product/event routes
=> (PC-26545)[API] fix: GET offers with price > 300 €

api/tests/routes/public/individual_offers/v1/get_product_test.py
=> (BSR)[API] fix: test result was wrong

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/core/offers/models.py
La requête faite par le serveur ressemble à ça:
```plpgsql
SELECT DISTINCT offer.id AS offer_id
FROM offer
JOIN venue ON venue.id = offer."venueId"
JOIN stock ON offer.id = stock."offerId"
WHERE venue."managingOffererId" = %(managingOffererId_1) s
AND offer.validation = %(validation_1) s
AND offer."isActive"
AND offer.validation = %(validation_2) s
AND NOT (
stock."beginningDatetime" IS NOT NULL
AND stock."beginningDatetime" <= now()
OR stock."bookingLimitDatetime" IS NOT NULL
AND stock."bookingLimitDatetime" <= now()
)
AND NOT (
stock."isSoftDeleted"
OR stock."beginningDatetime" IS NOT NULL
AND stock."beginningDatetime" <= now()
OR CASE
WHEN (stock.quantity IS NULL) THEN NULL
ELSE stock.quantity - stock."dnBookedQuantity"
END IS NOT NULL
AND CASE
WHEN (stock.quantity IS NULL) THEN NULL …
```
=> (PC-25664) vérifier l'existance de stock avec exists au lieu d'une jointure

api/src/pcapi/routes/backoffice/forms/search.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23416
=> (PC-23416)[API] feat: add card down right when search offerer

api/pyproject.toml
=> (BSR)[API] Suppression d'un vieux "filterwarnings"

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25988
=> (PC-25988)[API] fix: fix showType and musicType in sandbox

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/templates/bank_account/get/linked_venues.html, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/templates/venue/get/history.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26539
=> (PC-26539)[BO] feat: show public name for a venue prior to administrative name

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231214T141716_d5e7a47d4991_add_educational_institution_program_tables.py, api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/authentication.py, api/src/pcapi/routes/adage_iframe/serialization/adage_authentication.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py, api/tests/routes/adage_iframe/get_authenticate_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/AuthenticatedResponse.ts, pro/src/apiClient/adage/models/EducationalInstitutionProgramModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26195
1. Ajout d'un nouveau modèle qui permet d'enregistrer des programmes nationaux pour des établissements scolaires.
2. Remonter la liste de ces programmes lorsque l'utilisateur s'authentifie (on renvoie ceux de son établissement).
=> (PC-26195)[EAC] feat: add educational institution programs

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231220T131344_64a8f6cecea6_add_author_in_collective_offer_and_template.py, api/src/pcapi/alembic/versions/20231220T131611_d727060b1531_activate_constraint_collective_offer_and_template_authorid_fkey.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py, api/tests/routes/backoffice/collective_offer_templates_test.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/pro/post_collective_offers_template_test.py, api/tests/routes/pro/post_collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26243
=> (PC-26243)[API]feat: backoffice collective offer and template display creator

api/src/pcapi/routes/public/individual_offers/v1/events.py
if an error occured during the modification of a price category the generic error message is returned to the user
https://sentry.passculture.team/organizations/sentry/issues/1229905/?project=5&referrer=slack
=> (PC-26562)[API] fix: show to user which error he got

pro/src/pages/Home/Venues/Venue.module.scss, pro/src/pages/Home/Venues/Venue.tsx
=> (PC-26274)[PRO] fix: ui when venue name is too long

pro/src/pages/Home/Offerers/PartnerPages.module.scss, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Venues/Venue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26276
=> (PC-26276)[PRO] fix: change wording for partner page selector

api/src/pcapi/core/offerers/repository.py, api/tests/routes/pro/get_offerer_stats_v2_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26326
Fix de la requête sur [cette PR](https://github.com/pass-culture/pass-culture-main/pull/9555)
=> (PC-26326) fix collective offer count, get offres with no stocks

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/mails/transactional/__init__.py, api/src/pcapi/core/mails/transactional/pro/venue_bank_account_link_deprecated.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23424
=> (PC-23424)[API] feat: PRO email notification when deprecate venue bank account link

pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26410
- Correction du curseur quand la checkbox est désactivée.
=> (PC-26410)[PRO] feat: Fixed disabled state for link dialog.

pro/src/components/Dialog/Dialog/Dialog.module.scss, pro/src/components/DialogBox/DialogBox.module.scss, pro/src/components/FormLayout/FormLayout.module.scss, pro/src/components/ImageEditor/ImageEditor.tsx, pro/src/components/ImagePreview/ImagePreview.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/ModalImageCrop.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageUploadBrowser/ModalImageUploadBrowser.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageUploadConfirm/ModalImageUploadConfirm.module.scss, pro/src/components/ReimbursementPointDialog/ReimbursmentPointDialog.module.scss, pro/src/components/Tutorial/Step/ManageBookings.tsx, pro/src/components/Tutorial/Step/Step.module.scss, pro/src/components/Tutorial/Tutorial.module.scss, pro/src/components/TutorialDialog/TutorialDialog.module.scss, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderFormDialog/AllocineProviderFormDialog.module.scss, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/DeleteVenueProviderDialog/DeleteVenueProviderDialog.module.scss, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/ToggleVenueProviderStatusDialog/ToggleVenueProviderStatusDialog.module.scss, pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.module.scss, pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/PricingPointDialog.module.scss, pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss, pro/src/screens/IndividualOffer/StocksThing/ActivationCodeFormDialog/ActivationCodeFormDialog.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26546
Responsive pour les popin.
Après discussion, elles seront centrées pour le moment.
=> (PC-26546)[PRO] style: dialog responsive

api/src/pcapi/routes/backoffice/autocomplete.py, api/tests/routes/backoffice/autocomplete_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26513
=> (PC-26513)[API] feat: (backoffice) action venue allow search tag by id when editing

api/src/pcapi/core/offerers/api.py, api/src/pcapi/scripts/install.py, api/tests/core/external/offerer_stats_test.py, api/tests/core/offerers/test_update_offerer_stats.py
Supprimer l'ancien système de mise à jour des stats v1 au profit de celui ci: https://github.com/pass-culture/pass-culture-main/pull/9666
https://passculture.atlassian.net/browse/PC-26159
=> (BSR)[API] refactor: remove old stas v1 code

pro/src/components/Banner/OfferRefundWarning.tsx, pro/src/components/Banner/WithdrawalReminder.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/UsefulInformations.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24834
Ajouter l'indication que les liens s'ouvre dans une nouvelle fenêtre dans la page de création d'offre (première étape)
=> (PC-24834)[PRO] feat: offer creation -  add new window info on links

.github/workflows/build-and-push-docker-images.yml, .github/workflows/dependabot-auto-merge.yml, .github/workflows/deploy-app-engine-image-resizing.yaml, .github/workflows/deploy.yml, .github/workflows/node-quality-check.yml, .github/workflows/node-type-check.yml, .github/workflows/release--build-hotfix.yml, .github/workflows/release--build.yml, .github/workflows/release--deploy.yml, .github/workflows/reusable--build-and-tag.yml, .github/workflows/tests-api.yml, .github/workflows/tests-main.yml, .github/workflows/tests-pro-e2e.yml, .github/workflows/tests-pro.yml
=> (BSR) ci: remove all inherit

.github/workflows/build-and-push-docker-images.yml, .github/workflows/dependabot-auto-merge.yml, .github/workflows/deploy-app-engine-image-resizing.yaml, .github/workflows/deploy.yml, .github/workflows/reusable--build-and-tag.yml, .github/workflows/tests-api.yml, .github/workflows/tests-main.yml, .github/workflows/tests-pro-e2e.yml, .github/workflows/tests-pro.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/BSR
Github token should not be a input
=> (BSR) fix(ci): Github token should not be a input

.github/workflows/build-and-push-docker-images.yml, .github/workflows/configure-live-channel-pro-generic.yml, .github/workflows/deploy-app-engine-image-resizing.yaml, .github/workflows/deploy-pro-pr-version-generic.yml, .github/workflows/deploy-pro-pr-version.yml, .github/workflows/deploy.yml, .github/workflows/mypy-cop.yml, .github/workflows/release--build-hotfix.yml, .github/workflows/release--build.yml, .github/workflows/release--deploy.yml, .github/workflows/reusable--build-and-tag.yml, .github/workflows/tests-api.yml, .github/workflows/tests-main.yml, .github/workflows/update-api-client-template.yml, .github/workflows/update-jira-issues.yml
=> (BSR) ci: remove github secrets from all workflows

.github/workflows/ping_data_team.yml
=> (BSR) ci: remove last github secret

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231222T110640_a1500ef1ad7c_add_student_levels_values.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/public/collective/serialization/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/src/pcapi/routes/shared/collective/serialization/offers.py, api/tests/routes/pro/post_collective_offers_test.py, pro/src/apiClient/adage/models/StudentLevels.ts, pro/src/apiClient/v1/models/StudentLevels.ts, pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/__specs__/FormParticipants.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26272
Ajout de deux niveaux scolaires spéciaux liés au programme Marseille en grand.
Ceux-ci ne sont accessibles que si le FF est activé : le validateur en prend compte.
Factorisation de certains tests : éviter les copier/coller qui ne permettent pas de voir facilement quelle est le contexte spécifique du test (quelles combinaisons de valeurs particulières envoyées).
=> (PC-26272)[EAC] feat: add primary school levels

.github/workflows/reusable--build-and-tag.yml
=> (BSR) fix slack message

api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offer_test.py, pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts, pro/src/pages/IndividualOfferWizard/__specs__/IndividualOfferWizard.spec.tsx, pro/src/pages/IndividualOfferWizard/__specs__/IndividualOfferWizardAdmin.spec.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24965
=> (PC-24965)[API] refactor: remove stocks from GET offer route

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/Offerers/PartnerPage.module.scss, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26277
Derrière le FF WIP_PARTNER_PAGE, "Lieu non dit" est une structure avec un lieu permanent qui permet de voir le bloc pages partenaires
=> (PC-26277)[PRO] feat: add partner page block

api/src/pcapi/routes/pro/offerers.py, api/tests/routes/pro/get_offerer_stats_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26622
=> (PC-26622)[API] fix: return null if no data for top offers

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_venue_provider_and_external_bookings.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offers_with_ean.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26563
=> (PC-26563) add venue type for libraries and cinemas in sandbox

api/src/pcapi/core/mails/transactional/pro/bank_account_validation.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/use_cases/save_venue_bank_informations.py, api/tests/use_cases/save_venue_bank_informations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25119
=> (PC-25119)[API] feat: Bank account validated email notification

pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/form/recurrenceUtils.ts, pro/src/utils/date.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24965
Résoud les 2 retours remontés dans le ticket jira + un bug de date trouvé au passage
=> (PC-24965)[PRO] fix: offer.hasStocks not being updated when inserting stocks

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_product_categories_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25409
=> (PC-25409)[API] add url field to relevant product categories

api/src/pcapi/routes/public/individual_offers/v1/constants.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/post_image_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26532
=> (PC-26532)[API] feat: Route to save binary image

api/src/pcapi/repository/clean_database.py, api/src/pcapi/sandboxes/scripts/save_sandbox.py
Reset id sequence on sandbox clean. Ids will be more consistant (there is some randomness on sandbox generation).
=> (BSR)[API] fix: reset id sequence on sandbox clean

api/.vscode/settings.json, api/src/pcapi/core/providers/api.py, api/src/pcapi/routes/backoffice/providers/blueprint.py, api/tests/routes/backoffice/providers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26060
=> (PC-26060) disable all offers linked to provider when provider is disabled

.github/workflows/build-and-push-docker-images.yml, .github/workflows/check-folder-changes.yml, .github/workflows/configure-live-channel-pro-generic.yml, .github/workflows/deploy-app-engine-image-resizing.yml, .github/workflows/deploy-maintenance-site.yml, .github/workflows/deploy-pro-pr-version-generic.yml, .github/workflows/deploy.yml, .github/workflows/mypy-cop.yml, .github/workflows/release--build-hotfix.yml, .github/workflows/release--build.yml, .github/workflows/release--deploy.yml, .github/workflows/reusable--build-and-tag.yml, .github/workflows/storybook.yml, .github/workflows/tests-api.yml, .github/workflows/tests-pro-e2e.yml, .github/workflows/tests-pro.yml, .github/workflows/update-api-client-template.yml
https://github.com/actions/checkout/releases
=> (BSR) ci: update action checkout to v4

pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26284
=> (PC-26284)[PRO] feat: add tracker to button image add in partner block

api/src/pcapi/routes/pro/stocks.py, api/tests/routes/pro/post_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26639
=> (PC-26639)[API] fix: change of quantity for a stock

api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_several_venues.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26611
=> (PC-26611) change sandbox venues, set venue type and ispermanenet

api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/src/pcapi/routes/backoffice/templates/bank_account/get.html, api/src/pcapi/routes/backoffice/templates/collective_offer/details.html, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/pro_user/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-26600
=> (PC-26600)[BO] feat: copy ID to clipboard from details page

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_update_jira_issues.yml
=> (BSR) ci: mv update_jira_issues into main workflow

api/tests/core/bookings/test_repository.py
The test was accessing `User.deposits[0]`, which is not deterministic
(because the relationship is not sorted). It could return the oldest
or the newest deposit, which is why this test sometimes failed.
In fact, the test was overly complicated for a function that just has
two filters on the deposit it and the booking status (which was not
tested, actually).
Also, the name of the test should probably contain the name of the
function under test, instead of something that looks like the name of
a function... which does not exist.
I know, I'm a boring person.
=> (BSR)[API] test: Fix flaky test_get_deposit_booking and rename it

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
=> (BSR) ci: typo in test e2e

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231228T112309_ec0f52ada8fa_add_bank_information_column_to_cashflow_table.py, api/src/pcapi/alembic/versions/20231228T144621_48e05c743111_copy_bank_account_to_bank_information_in_cashflow.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/factories.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/finance/repository.py, api/src/pcapi/templates/invoices/invoice.html, api/tests/core/finance/test_api.py, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/finance_test.py, api/tests/routes/backoffice/individual_bookings_test.py, api/tests/routes/backoffice/venues_test.py, api/tests/routes/pro/get_invoices_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26402
=> (PC-26402)[API] refactor: Rename Cashflow.bankAccount column to Cashflow.bankInformation step 1

.github/workflows/dev_on_workflow_tests_api.yml
=> (BSR) ci: typo tests api

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR) ci: move mypycop to main workflow

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_deploy_storybook.yml, .github/workflows/dev_on_workflow_mypy_cop.yml
=> (BSR) ci: mv storybook to main workflow

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
=> (BSR) ci: test fix e2e

api/src/pcapi/core/search/backends/algolia.py
These logs could ease debugging.
=> (BSR)[API] feat: Add logs in `AlgoliaBackend._pop_ids_from_queue()`

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
=> (BSR) ci: fix e2e

api/poetry.lock, api/pyproject.toml, api/src/pcapi/flask_app.py, api/src/pcapi/utils/rate_limiting.py, api/tests/utils/rate_limiting_test.py
Commits à relire séparément. J'ai fait un commit séparer pour simplifier le typage.
=> (BSR)[API] bump: Bump flask-limiter to 3.5.0

pro/cypress/e2e/updateVenue.cy.ts, pro/cypress/support/commands.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26283
=> (PC-26283)[PRO] test: add basic e2e test for partner pages

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26531
Passer vitest en version 1.1.1
=> (PC-26531)[PRO] bump: upgrade vitest to version 1.1.1

.github/workflows/dev_on_workflow_dependabot_auto_merge.yml
=> (BSR) ci: dependabot workflow refacto

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240102T153345_a10993ffc712_.py, api/src/pcapi/core/educational/api/venue.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/search/__init__.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/offerers/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24683
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25931
=> Pc 24683 use google maps imported image

.github/workflows/dev_on_workflow_build_and_tag.yml
=> (BSR) ci: refacto build_and_tag.yml

.github/workflows/dev_on_workflow_build_and_push_docker_images.yml
=> (BSR) ci: refacto build and push docker image

.github/workflows/dev_on_dispatch_release_build.yml, .github/workflows/dev_on_dispatch_release_build_hotfix.yml, .github/workflows/dev_on_dispatch_release_deploy.yml
=> (BSR) ci: typo and format dispatch workflows

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR) ci: format style main workflow

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240102T141914_16ebdf83377e_add_elementary_student_level.py, api/src/pcapi/core/educational/models.py, pro/src/apiClient/adage/models/StudentLevels.ts, pro/src/apiClient/v1/models/StudentLevels.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/__specs__/FormParticipants.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26191
=> (PC-26191)[API] fix: wording for elementary schools

pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOfferPlaylist/NewOfferPlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/VenuePlaylist.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26676
Avant : 
Après :
=> (PC-26676)[PRO] feat: add bold to discovery title

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_ping_data_team.yml
=> (BSR) ci: ping data team in main workflow

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/backoffice/templates/venue/get/invoices.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/static/backoffice/js/addons/pc-batch-action-form.js, api/src/pcapi/static/backoffice/js/addons/pc-table-multi-select.js, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25982
=> (PC-25982)[BO] feat: add reimbursement details export to invoices tab

api/README.md
=> (BSR)[API] fix: fix python version in readme

api/tests/routes/pro/get_offerer_test.py
=> (BSR)[API] fix: flaky test

api/src/pcapi/core/finance/siret_api.py, api/src/pcapi/core/offerers/api.py, api/tests/core/finance/test_siret_api.py, api/tests/core/offerers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26637
=> (PC-26637)[BO] fix: remove SIRET

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240103T152707_ea0a25aef628_add_bank_account_to_invoice.py, api/src/pcapi/core/finance/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26403
=> (PC-26403)[API] feat: Add bank_account fkey to invoice

api/src/pcapi/core/fraud/models.py, api/src/pcapi/core/fraud/ubble/constants.py, api/src/pcapi/core/subscription/ubble/models.py, api/tests/core/mails/transactional/users/ubble_ko_reminder_test.py, api/tests/core/subscription/ubble/test_api.py, api/tests/routes/external/user_subscription_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26506
=> (PC-26506)[API] feat: add new ubble error details

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25017
=> (PC-25017)[API] feat: add QA beneficiary account in test case sandbox

.github/workflows/dev_on_dispatch_release_build.yml, .github/workflows/dev_on_dispatch_release_build_hotfix.yml
=> (BSR) ci: add permissions: write-all to build/deploy workflows

pro/src/pages/Home/Offerers/OffererDetails.module.scss, pro/src/pages/Home/Offerers/OffererDetails.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26696
Avant
Après
=> (PC-26268)[PRO] fix: grow offerer select if name is too small

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR)[PRO] ci: fix deploy validation pro

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26701
exemple : https://github.com/pass-culture/pass-culture-main/actions/runs/7408319216/job/20156439193?pr=9979
=> (PC-26701) ci: run e2e on ubuntu-latest

.github/workflows/dev_on_workflow_update_api_client_template.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26705
=> (PC-26705)[PRO] ci: use ubuntu-latest to generate api client

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferDetails/OfferDetails.tsx
Supprimer la partie Contact lorsqu'on ouvre l'offre pour en savoir plus
Avant :
Après :
=> (PC-26395)[PRO] feat: delete section contact in offer adage

.github/workflows/dev_on_workflow_update_api_client_template.yml
=> (BSR)[PRO] ci: fix update api client

api/src/pcapi/core/users/factories.py, api/src/pcapi/sandboxes/scripts/creators/allocine/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bank_accounts.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_venue_provider_and_external_bookings.py
Ajout d'users dans la sandbox industrial pour les avoir en testing avec les emails suivants : "api@example.com" et "activation@example.com"
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26609
=> (PC-26609)[API] feat: add api, retention and activation users to testing

api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/get_venue_test.py, api/tests/routes/pro/patch_venue_test.py, pro/src/apiClient/v1/models/GetVenueResponseModel.ts, pro/src/apiClient/v1/models/PostVenueBodyModel.ts, pro/src/components/VenueForm/types.ts, pro/src/core/Venue/adapters/getVenueAdapter/serializers.ts, pro/src/core/Venue/types.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26704
=> (PC-26704)[API] fix: avoid empty banId on venue update

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26661
- [X ] J'ai écrit les tests nécessaires
- [X ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [X ] J'ai ajouté des screenshots pour d'éventuels changements graphiques
=> (PC-26661)[ALGOLIA] Change configuration of reranking

pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageAdd/ButtonImageAdd.module.scss, pro/src/pages/Home/Offerers/PartnerPage.module.scss, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26277
=> (PC-26277)[PRO] fix: ui changes to partner block

.github/workflows/dev_on_push_workflow_main.yml
=> (BSR) ci: fix dependanbot

.github/workflows/dev_on_dispatch_release_build_hotfix.yml
=> (BSR)[PRO] build: fix cache_bucket_name being in secrets

api/pyproject.toml, infra/pc_scripts/test_backend.sh, pc
Ticket Jira : https://passculture.atlassian.net/browse/PC-26774
=> (PC-26774)[API] chore: split pc test-backend / pc test-backoffice

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_ping_data_team.yml
=> (BSR) ci: fix ping data team

api/src/pcapi/core/fraud/models.py, api/tests/routes/external/user_subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26698
=> (PC-26698)[API] feat: add new ubble reason codes

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/exceptions.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/finance/forms.py, api/src/pcapi/routes/backoffice/finance/validation.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24946
=> (PC-24946)[BO] feat: permit to create a commercial gesture in bo

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py
Add sentry tag for external bookings
=> (BSR)[API] feat: add sentry tag for external bookings

api/tests/core/bookings/test_api.py, api/tests/core/educational/test_repository.py, api/tests/core/finance/test_api.py, api/tests/core/fraud/test_api.py, api/tests/core/offerers/test_api.py, api/tests/core/providers/test_api.py, api/tests/core/token/test_token.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26762
=> (PC-26762)[API] chore: remove some freeze_times from tests

api/src/pcapi/core/mails/transactional/pro/email_validation.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/pro/validate.py, api/src/pcapi/validation/routes/validate.py, api/tests/core/mails/transactional/pro/email_validation_test.py, api/tests/routes/pro/signup_pro_V2_test.py, api/tests/routes/pro/validate_user_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25030
=> (PC-25030)[API] feat: Replace user validationToken by Token

pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.module.scss, pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/__specs__/OffersForMyInstitution.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26355
Ajouter un titre h1 et une bannière sur la page "Pour mon établissement" sur adage
Avant : 
Après :
=> (PC-26355)[PRO] feat: add title and banner for my institution page

pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageAdd/ButtonImageAdd.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageAdd/ButtonImageAdd.tsx, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx, pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx, pro/src/pages/Home/venueUtils.ts, pro/src/screens/IndividualOffer/StocksEventCreation/form/onSubmit.ts, pro/src/utils/getLastCollectiveDmsApplication.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26281
=> (PC-26281)[PRO] fix: adage dms application conditions

pro/src/app/AppRouter/routesMap.tsx, pro/src/app/AppRouter/subroutesReimbursements.tsx, pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx, pro/src/components/Header/Header.tsx, pro/src/components/Header/__specs__/Header.spec.tsx, pro/src/components/Tutorial/Step/ManageBookings.tsx, pro/src/pages/Reimbursements/Reimbursements.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26324
passer Remboursement en Gestion Financière
(menu / bannières / tuto)
pas de FF
=> (PC-26324)[PRO] feat: change Remboursement to Gestion financière

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/core/external/commands/update_sendinblue_batch_attributes.py, api/src/pcapi/core/external/commands/update_sendinblue_pro_attributes.py, api/src/pcapi/core/users/api.py, api/src/pcapi/scripts/fix_suspended_external_users.py, api/tests/core/users/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26728
=> (PC-26728)[API] feat: do not synchronize externally suspended users

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/accounts/forms.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26647
=> (PC-26647)[BO] feat: filter search accounts by credit

api/src/pcapi/routes/backoffice/autocomplete.py, api/tests/routes/backoffice/autocomplete_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26796
=> (PC-26796)[BO] feat: show offerer id or venue id in autocomplete results

api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/core/offerers/test_api.py, pro/src/apiClient/v1/models/PostVenueBodyModel.ts, pro/src/components/Address/types.ts, pro/src/core/Venue/adapters/getSiretDataAdapter.ts, pro/src/screens/SignupJourneyForm/Offerer/Offerer.tsx, pro/src/screens/SignupJourneyForm/Validation/Validation.tsx, pro/src/screens/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26813
- Valoriser le banId du lieu lors de l'inscription d'une nouvelle structure 
- Rendre optionnel le banId dans le modèle de l'API pour gérer les edges cases possibles
=> Pc 26813 value ban id when creating new offerer

pro/src/screens/OfferType/OfferType.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25016
=> (PC-25016)[PRO] feat: creation d'offre step 1 responsive

pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.module.scss, pro/src/components/Stepper/Stepper.module.scss, pro/src/pages/IndividualOfferWizard/Offer/__specs__/Offer.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25953
=> (PC-25253)[PRO] feat: stepper creation d'offre responsive

api/tests/core/offers/test_repository.py, api/tests/core/users/test_api.py, api/tests/core/users/test_repository.py, api/tests/scripts/beneficiary/handle_inactive_dms_applications_test.py, api/tests/scripts/beneficiary/import_dms_accepted_applications_test.py, api/tests/scripts/booking/handle_expired_bookings_test.py, api/tests/tasks/cultural_survey_task_test.py, api/tests/utils/pdf_creation_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26762
=> (PC-26762)[API] refactor: remove freeze_time when possible

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231124T144345_025c622f64f8_update_deposit_calculation.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/routes/backoffice/finance/validation.py, api/tests/core/users/test_models.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24008
=> PC-24008 update deposit after incident validation

.github/workflows/dev_on_workflow_build_and_push_docker_images.yml
=> (BSR)[API] ci: remove duplicate checkout

pro/src/components/IndividualOfferForm/Informations/__specs__/Informations.spec.tsx, pro/src/components/IndividualOfferForm/Informations/__specs__/validationSchema.spec.tsx, pro/src/components/IndividualOfferForm/Informations/index.ts, pro/src/components/IndividualOfferForm/Informations/validationSchema.ts, pro/src/components/IndividualOfferForm/__specs__/IndividualOfferForm.BannerAddVenue.spec.tsx, pro/src/components/IndividualOfferForm/__specs__/IndividualOfferForm.spec.tsx, pro/src/components/IndividualOfferForm/index.ts, pro/src/components/IndividualOfferForm/validationSchema.ts, pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26288
=> (PC-26288) allow description of more than 1000 characters for syncronized offers

pro/src/pages/Signup/SignupContainer/OperationProcedures/OperationProcedures.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25755
Branche: PC-25755-callout-signup
=> (PC-25755)[PRO] style: Ajout de Callout sur signup

api/src/pcapi/connectors/dms/serializer.py, api/src/pcapi/core/finance/ds.py, api/tests/core/finance/test_ds.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26805
=>  (PC-26805)[API] fix: Fix DS datetime tz awareness 

pro/src/pages/Home/Offerers/OffererDetails.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24554
Ajout d'un title sur le champs de sélection des structures de la page d'accueil
=> (PC-24554)[PRO] feat: add label for home offerer select

api/src/pcapi/connectors/dms/serializer.py, api/src/pcapi/core/finance/ds.py, api/tests/core/finance/test_ds.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26805
=>  (PC-26805)[API] feat: Add automatic mark_without_continuation missing case

api/src/pcapi/core/offers/repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26788
Use exists instead of joining a table to know if a stock exists for given time period. This seems to greatly improve performance on staging.
For these sentry timeout : [link1](https://sentry.passculture.team/organizations/sentry/issues/423864/events/aec6bad4c67f41ea88a494266555437c/?environment=production&project=5&statsPeriod=90d) [link2](https://sentry.passculture.team/organizations/sentry/issues/423864/events/d7bdaa97399e41b48156e2e1a4aff6b0/?environment=production&project=5&statsPeriod=90d)
With join 
link 1 Time: 62 Lignes en 226.614s
link 2 SELECT 736 Time: 222.637s (3 minutes 42 seconds), executed in: 222.077s (3 minutes 42 seconds)
With exists 
link 1 SELECT 62 Time: 0.147s
link 2 SELECT 736 …
=> (PC-26788)[API] feat: use exists instead of joining a table

pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26871
Ajout d'une phrase dans le Callout de la page Pour mon établissement sur adage
=> (PC-26871)[PRO] feat: change wording in adage page my institution

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx, pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx, pro/src/pages/Home/Venues/Venue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26277
Correction du lien qui pouvait avoir un offerer undefined + un mauvais affiché quand le FF banking details était activé
=> (PC-26277)[PRO] fix: partner pages display

api/src/pcapi/routes/public/individual_offers/v1/products.py
Fix public api product creation and image upload both released on monday.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25032
=> (PC-25032)[API] fix: public API product creation and image upload

pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/__specs__/OffersForMyInstitution.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26880
Avoir la bannière Callout qui s'affiche lorsqu'il n'y a pas de résultat mais aussi quand il y en a.
=> (PC-26880)[PRO] fix: change callout position in page for my institution

.github/workflows/dev_on_workflow_ping_data_team.yml
=> (BSR) ci: fix pr url #db-changes

.github/workflows/dev_on_push_workflow_main.yml
This reverts commit b5016aa229f22392b46ce00d4715c6366b3d1627.
=> (BSR) fix: Revert "improve GHA concurrency syntax"

pro/src/apiClient/adage/models/VenueResponse.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26689
Fix : mise à jour du client front (pas réaliser lors de la PR principale)
=> (PC-26689)[EAC] fix: missing adage client update (front)

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26834
- Changement de `Remboursements` à `Gestion financière`
=> (PC-26834)[PRO] feat: Wording changes.

pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25194
Migration de la story FieldLayout.
=> (PC-25194)[PRO] feat: Migrate FieldLayout.

api/src/pcapi/routes/backoffice/templates/components/search/base.html, api/src/pcapi/routes/backoffice/templates/layouts/accounts.html, api/src/pcapi/static/backoffice/scss/pc/_forms.scss
Ticket Jira : https://passculture.atlassian.net/browse/PC-26647
Correction suite à une remarque UX de @elizoturner sur petit écran
=> (PC-26647)[BO] fix: accounts search for smaller screen

pro/.eslintrc.cjs, pro/src/components/VenueForm/Informations/SiretOrCommentFields/SiretOrCommentFields.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/__specs__/OfferCard.spec.tsx, pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx, pro/src/pages/Home/Offerers/__specs__/VenueCreationLinks.spec.tsx, pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx, pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/ui-kit/form/RadioButton/RadioButton.stories.tsx, pro/src/ui-kit/form/RadioGroup/RadioGroup.stories.tsx
Suppression de certains warnings et passage des règles en erreur
=> (BSR)[PRO] fix: change eslit rules from warn to error

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26282
1ère partie du ticket qui est pour l'instant uniquement de la refacto iso-fonctionnelle sur le sélecteur de structures
=> (PC-26282)[PRO] refactor: use react-router loader + search params as state

pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx, pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/venueUtils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26277
Oubli de la PR précédente, il y avait un autre endroit où la condition devait être modifié (composant Venue). Pour régler le pb définitivement, j'ai extrait les conditions dans des fonctions
=> (PC-26277)[PRO] refactor: venue steps conditions

pro/src/ui-kit/form/TimePicker/TimePicker.stories.tsx, pro/src/ui-kit/form/TimePicker/TimePicker.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25190
Migration de la story TimePicker
=> (PC-25190)[PRO] feat: storybook timepicker

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240102T140123_b5ae2a2f7d59_add_venue_to_custom_reimbursement_rules.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/exceptions.py, api/src/pcapi/core/finance/factories.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/finance/validation.py, api/src/pcapi/domain/reimbursement.py, api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/custom_reimbursement_rule/blueprint.py, api/src/pcapi/routes/backoffice/custom_reimbursement_rule/forms.py, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/custom_reimbursement_rules/list.html, api/tests/core/finance/test_api.py, api/tests/core/finance/test_models.py, api/tests/core/finance/test_repository.py, api/tests/core/finance/test_validation.py, api/tests/domain/reimbursement_test.py, api/tests/routes/backoffice/autocomplete_test.py, api/tests/routes/backoffice/custom_reimbursement_rules_test.py, api/tests/routes/pro/get_reimbursements_csv_test.py, api/tests/routes/serialization/reimbursement_csv_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25962
=> (PC-25962)[API] feat: add custom reimbursement rules on venues

pro/src/components/FormLayout/FormLayoutSection.tsx, pro/src/screens/OfferType/OfferType.module.scss, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24693
Corrections A11y de la page initiale de création d'offres.
=> Pc 24693 offer wizzard a11y

api/tests/routes/public/collective/endpoints/bookings_test.py, api/tests/routes/public/collective/endpoints/get_collective_offer_public_provider_test.py, api/tests/routes/public/collective/endpoints/get_collective_offers_test.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py, api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26762
=> (PC-26762)[API] refactor: remove freezegun in public.collective.endpoints tests

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26718
=> (PC-26718)[API] feat: add venues to sandbox to aid graphical validation

pro/src/ui-kit/form/TextInput/TextInput.stories.tsx, pro/src/ui-kit/form/TextInput/TextInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25192
=> (PC-25192)[PRO] refactor: migrate TextInput story

pro/src/ui-kit/form/Slider/Slider.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25193
=> (PC-25193)[PRO] refactor: migrate Slider story

pro/src/app/AppRouter/routesMap.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25952
- Synchronisation des titres des pages pour les offres collectives.
=> (PC-25952)[PRO] feat: Changing the titles of collective offers pages.

.github/workflows/dev_on_workflow_update_api_client_template.yml
Read more : https://github.com/jitterbit/get-changed-files/issues/11#issuecomment-854657301
=> (BSR) ci: fix generate api template

pro/src/styles/components/layout/_CookieModals.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25785
- Style des boutons au focus sur la modal des cookies.
=> (PC-25785)[PRO] style: Focus state style for cookie modal buttons.

pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/screens/IndividualOffer/SummaryScreen/StockSection/RecurrenceSection/RecurrenceSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26707
Branche: PC-26707-offers-style-espace
=> (PC-26707)[PRO] style: création d'offre 3 et 4, ajout des espaces

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/factories.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24996
Adaptation des extractions "payment_details" et "invoice" en y ajoutant la notion d'incidents.
+ changements demandés par David
=> Pc 24996 add finance incident to invoice / payment detail csv

api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html
Ticket Jira : https://passculture.atlassian.net/browse/PC-26941
=> (PC-26941)[BO] feat: add links to collective offers and bookings in offerer and venue pages

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240104T164121_945ba5efc72f_add_bank_account_to_cashflow.py, api/src/pcapi/core/finance/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26636
=> (PC-26636)[API] feat: Add bank account to cashflow

pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-[PC-26851]
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-[PC-26839]
Branche: PC-15373-callout-biennumerique-recap
Info de Lieu:
[PC-26851]: https://passculture.atlassian.net/browse/PC-26851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PC-26839]: https://passculture.atlassian.net/browse/PC-26839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-15373)[PRO] style: callout de bien numerique, récapitulatif

pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26960
Ajout d'une phrase dans le Callout de la page Pour mon établissement sur adage
=> (PC-26960)[PRO] fix: wording for my institution

api/poetry.lock, api/pyproject.toml
- Supprimer des dépendances directes superflues
- traiter un warning de la lib `executing`
=> (BSR) build: remove some direct dependencies

pro/src/screens/OfferEducationalStock/__specs__/OfferEducationalStock.spec.tsx, pro/src/screens/OfferEducationalStock/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26903
Le message d'erreur s'affichait même si l'heure était à 17h alors qu'il était 12h le même jour
=> (PC-26903)[PRO] fix: hours in same day not working

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/commands.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/mails/transactional/finance_incidents/finance_incident_notification.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25840
Note : cette PR reprend les emails créés par @charlesmorelpc dans la PR https://github.com/pass-culture/pass-culture-main/pull/9741
=> (PC-25840)[API] feat: send email to pro and beneficiary when a finance incident is validated

api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general.html, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25324
Adaptation des incidents de finance au nouveau système de compte bancaire (derrière feature flag) :
- Affichage du compte bancaire dans la page incident
- Adaptation du wording dans la modale de validation d'un incident
=> [BO] feat: adapt finance incidents to new bank details journey

api/tests/routes/backoffice/finance_test.py
fix conflict between commits 5b7bfb6c and f15bba50
=> (BSR)[BO] fix tests ; conflict between commits 5b7bfb6c and f15bba50

api/src/pcapi/core/finance/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_incidents.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25790
=> (PC-25790)[API] feat: add finance incidents to sandbox

api/src/pcapi/core/offerers/api.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_tags.py, api/src/pcapi/settings.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25602
=> (PC-25602)[API] feat: add epn autotagging to offerers

api/src/pcapi/core/categories/subcategories_v2.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26957
=> (PC-26957)[API] feat: rename cinema search group

api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/details.html, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_complex_offers.py, api/src/pcapi/static/backoffice/scss/pc/pc.scss, api/src/pcapi/static/backoffice/scss/pc/templates/_offer.scss, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26055
=> Pc 26055 rpa more informations individual offers

api/src/pcapi/routes/native/v1/serialization/account.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25585
=> (PC-25585)[API] feat: add hasPassword to user profile response

pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx, pro/src/components/VenueForm/VenueForm.tsx, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/screens/VenueForm/VenueFormScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26975
- les cas d'affichage de la partie collective de la page partenaire n'était pas exactemetn les bons
- privilégier le public name pour la venue
=> (PC-26975)[PRO] fix: partner page do not display right collective case

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240105T162035_2cc0a6822cf8_make_reimbursement_point_id_nullable_on_cashflow_and_invoice.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/offerers/factories.py, api/tests/core/finance/test_api.py, api/tests/core/offerers/test_api.py, api/tests/core/offerers/test_models.py, api/tests/routes/pro/get_offerer_test.py, api/tests/routes/pro/get_offerers_bank_accounts_test.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24350
=> (PC-24350)[API] feat: generate cashflows with bank accounts

api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/templates/venue/get/stats.html, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26927
=> (PC-26927)[API] feat: add ff to hide bank information in BO

pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx
BSR
réparer un problème de qualitey (j'apporterai des croissants)
=> (BSR)[PRO] chore: fix quality (dead-code)

api/src/pcapi/core/finance/repository.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-27155
Sentry : https://sentry.passculture.team/organizations/sentry/issues/1259115/
Durée de la même requête que l'erreur, sur staging :
Avant : `0:01:29.018856`
Après : `0:00:00.092859`
=> (PC-27155)[BO] perf: fix timeout when downloading reimbursement details

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26282
=> (PC-26282)[PRO] feat: save offerer and venue id on homepage

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferShareLink/OfferShareLink.tsx
Ticket Jira : https://passculture.atlassian.net/browse/PC-27470
=> (PC-27470)[PRO] feat: update wording for collective offer sharing

.github/workflows/dev_on_workflow_deploy.yml
Run and use should not be used at the same time
https://github.com/pass-culture/pass-culture-main/actions/runs/7607969783
=> (BSR)) fix wrong workflow

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240110T165515_b429bc5435d6_create_playlists.py, api/src/pcapi/connectors/big_query/queries/adage_playlists.py, api/src/pcapi/core/educational/api/playlists.py, api/src/pcapi/core/educational/commands.py, api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/repository/clean_database.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/core/educational/api/test_playlists.py, api/tests/routes/adage_iframe/playlist_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26658
=> [PC-26658] ne pas utiliser les requetes big query pour les playlists adage - lot 2

api/src/pcapi/core/offerers/repository.py, api/tests/routes/pro/get_offerers_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27018
=> (PC-27018)[API] feat: Most recent bank accounts should appear first

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Erreur Sentry : https://sentry.passculture.team/organizations/sentry/issues/1258999/?project=5&referrer=slack
L'erreur se produisait suite à la validation d'un incident trop perçu TOTAL, qui engendrait l'annulation de la réservation.
Avec cette réservation annulée, il était impossible de récupérer la règle de remboursement (erreur dateUsed `None`).
Désormais, si un événement de finance concerne un incident, alors la règle associée au nouveau pricing est celle du pricing original.
=> (BSR)[API] fix: Fix pricing event on total overpayment booking

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240117T154124_ca50ad3c3fd6_add_accessibility_provider_table.py, api/src/pcapi/core/offerers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26564
=> (PC-26564)[API] feat: add table AccessibilityProvider to Offerer models

api/src/pcapi/core/search/backends/algolia.py
Unique dates and prices will do. This make the serialization smaller,
especially for offers that have many stocks.
=> (BSR)[API] feat: Lighter offer serialization for offers

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/templates/accounts/search.html, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/pro_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-27172
=> (PC-27172)[BO] feat: search user accounts by list of ids

pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/Cells/BookingStatusCellHistory.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26082
Ajouter un ul autour du li dans l'historique des réservations, si il n'y a pas d'élément, ne pas mettre de ul ni de li
=> (PC-26082)[PRO] fix: a11y tooltip booking history ul around li

pro/src/components/Banner/BannerReimbursementsInfo.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26998
Branche: PC-26998-callout-gestion-financiere
Résultat est en haut de l'image:
=> (PC-26998)[PRO] style: Ajout de Callout, Gestion financière

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/mails/transactional/pro/invoice_available_to_pro.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/tasks/finance_tasks.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_integration.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24351
=> (PC-24351)[API] feat: generate invoices cbv5

pro/sonar-project.properties
Faire en sorte que Sonar Cloud n'analyse pas la duplication de code sur les fichiers de tests
=> (BSR)[PRO] ci: do not check duplication in test files

pro/src/components/StocksEventList/SortArrow.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26080
Sur la page réservation, les flèches présentes dans le header du tableau sont cliquables, il y avait un bouton qui contenait des divs, on change les divs par des span
=> (PC-26080)[PRO] feat: change div to span in button sort reservation page

pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/utils/sendSentryCustomError.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26964
Sentry error example :
=> (PC-26964)[PRO] feat: Send error message to sentry

pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26063
Ajouter la pseudo-class indeterminate dans le BaseCheckbox (le design n'est normalement pas impacté)
=> (PC-26063)[PRO] feat: add indeterminate pseudo class for checkbox

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240124T093045_6993f48deb4b_add_index_offer_authorid.py, api/src/pcapi/alembic/versions/sql/schema_init.sql, api/src/pcapi/core/offers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27552
=> (PC-27552)[API] chore: Clean inconsitencies between models definitions and db schemes

pro/src/screens/OfferEducational/OfferEducationalForm/FormVenue/FormVenue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27539
=> (PC-27539)[PRO] refactor: description du lieu de rattachement

pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.module.scss, pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25232
Dans la liste des icones pour l'accessibilité dans la création/edition des offres 
Passer les<img dans le BaseCheckbox en SvgIcon
Ajouter le alt dans le svgicon
=> (PC-25232)[PRO] feat: alt svg accessibility

pro/src/components/Stepper/Stepper.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25015
Passer de l'utilisation d'une balise <ul> à une balise <ol> pour le stepper
=> (PC-25015)[PRO] feat: change ul to ol for stepper

pro/src/components/Stepper/Stepper.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26247
=> (PC-26247)[PRO] style: Make stepper next step color contrast accessible.

.github/workflows/dev_on_workflow_update_api_client_template.yml
=> (BSR)[API] ci: fix docker layer cache

pro/src/pages/Desk/Desk.module.scss, pro/src/pages/Desk/Desk.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27015
Branche: PC-27015-callout-guichet
- Wording sur le lien.
- Ajout d'une icon de "icon: fullLinkIcon".
Info: c’est que celui vers l’externe est carré et celui vers l’interne est la flèche ronde.
=> (PC-27015)[PRO] style: Ajout Callout - page du guichet

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27527
Création d'un nouveau ff pour l'ajout du nouveau design de la page offre vitrine/reservable sur adage
=> (PC-27527)[API] feat: new ff NEW_ADAGE_OFFER_DESIGN

pro/src/components/IndividualOfferForm/Informations/Informations.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25018
Ajouter une balise abbr pour expliciter le terme EAN dans la création d'offre indiv
=> (PC-25018)[PRO] feat: add abbr for label input EAN in offer creation

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx, pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27550
=> (PC-27550)[PRO] refactor: remove wording from rattachement banner

api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerers_stats.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_providers_for_apis.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26160
=> (PC-26160)[API] feat: add offerer stats for sandbox

pro/src/ui-kit/form/shared/BaseInput/BaseInput.stories.tsx, pro/src/ui-kit/form/shared/BaseRadio/BaseRadio.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25197
Migration des stories BaseInput et BaseRadio
=> (PC-25197)[PRO] refactor: migrate stories baseinput and baseradio

pro/src/screens/IndividualOffer/SummaryScreen/StockSection/RecurrenceSection/RecurrenceSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27523
Branche: PC-27523-style-recap-dates-espace
=> (PC-27523)[PRO] style: formatage de nbr dates, récap

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231117T162308_4f738fc2e54a_add_not_null_constraint_on_pricing_eventId_step_4_of_4.py, api/src/pcapi/alembic/versions/20231117T162308_c1a24da729e5_add_not_null_constraint_on_pricing_eventId_step_2_of_4.py, api/src/pcapi/alembic/versions/20231117T162308_c2bc7c46f7a5_add_not_null_constraint_on_pricing_eventId_step_3_of_4.py, api/src/pcapi/alembic/versions/20231117T162308_ec9e39ae7940_add_not_null_constraint_on_pricing_eventId_step_1_of_4.py, api/src/pcapi/core/finance/factories.py, api/src/pcapi/core/finance/models.py, api/tests/core/finance/test_api.py, api/tests/core/offers/test_api.py, api/tests/routes/backoffice/finance_test.py, api/tests/scripts/booking/delete_cancelled_bookings_test.py
Migrations have been generated by `bin/alembic_add_not_null_constraint.py`.
=> (BSR)[API] feat: Add NOT NULL constraint on `pricing.eventId`

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/tests/routes/pro/get_reimbursements_csv_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24283
=> (PC-24283)[API] feat: Adapt `reimbursements/csv` route for new bank account journey

api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_music_types_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27475
=> (PC-27475)[API] feat: add gtl id to get music types route

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_tests_pro_e2e.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25752
Exemple CI : https://github.com/pass-culture/pass-culture-main/actions/runs/7670617104/job/20907333653
=> (PC-25752)[pro] ci: do not build pcapi image for e2e

api/src/pcapi/core/finance/factories.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_siret_api.py, api/tests/routes/backoffice/venues_test.py
Plusieurs commits, plus ou moins indépendants...
=> (BSR)[API] Correction dans les tests relatifs aux PricingFactory et FinanceEventFactory

pro/src/components/Header/Header.scss, pro/src/components/Header/Header.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26863
=> (PC-26863)[PRO] feat: add active state in main nav

pro/src/ui-kit/form/RadioGroup/RadioGroup.stories.tsx, pro/src/ui-kit/form/RadioGroup/RadioGroup.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25201
Migrer la story du composant RadioGroup
=> (PC-25201)[PRO] refactor: migrate radioGroup story

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_schedule_prepare_cache_weekly.yml, .github/workflows/dev_on_workflow_build_and_push_docker_images.yml, .github/workflows/dev_on_workflow_update_api_client_template.yml, pro/package.json, pro/scripts/generate_api_client_local.sh, pro/scripts/generate_api_client_local_without_docker.sh
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27639
=> (PC-27639) ci: pull image in update api client template

pro/scripts/generate_api_client_local.sh
=> (BSR) ci: fix api client script

api/src/pcapi/core/finance/api.py, api/src/pcapi/tasks/finance_tasks.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26406
=> (PC-26406)[API] feat: Handle remaining `reimbursementPoint` usage for new bank account journey

api/src/pcapi/core/providers/allocine_movie_list.py, api/src/pcapi/local_providers/install.py, api/tests/providers/allocine_movie_list_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27514
Le premier commit est un cherry-pick de [celui-ci](https://github.com/pass-culture/pass-culture-main/commit/883cb62ee66baf0f2943ec17409bac5c3e6a2820), qui avait été revert [ici](https://github.com/pass-culture/pass-culture-main/pull/10313/commits/1f4212a119c2620fc2d1c87a12174625f9c83e5d).
=> Pc 27514 change idatproviders for allocine products

api/tests/core/finance/test_api.py
=> (BSR)[API] fix: Failing due to misuse of the PricingFactory

pro/package.json, pro/yarn.lock
- Supression de la version de jackspeak.
=> (BSR)[PRO] feat: remove pinned version for jackspeak.

pro/src/pages/Reimbursements/BankInformations/BankInformations.module.scss, pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27619 
Changer le style du titre la page **Informations bancaires** de `title 2 -> title 3
`
=> (PC-27619)[PRO] fix: change Bank informations title style

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240130T153836_9607ada7a6b6_delete_search_history_adage_ff.py, api/src/pcapi/models/feature.py, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27694
**Objectif**
Supprimer le ff WIP_ENABLE_SEARCH_HISTORY_ADAGE et au passage suppression de code commenté qui va sans doute jamais voir le jour 😢
=> (PC-27694)[PRO] feat: Remove FF WIP_ENABLE_SEARCH_HISTORY_ADAGE

api/src/pcapi/core/offerers/api.py, api/tests/routes/backoffice/pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27736
=> (PC-27736)[BO] fix: don't crash on white space offerer searchs

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/pro/finance.py, api/src/pcapi/routes/serialization/finance_serialize.py, api/tests/routes/pro/get_bank_accounts_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/FinanceBankAccountListResponseModel.ts, pro/src/apiClient/v1/models/FinanceBankAccountResponseModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27581
=> (PC-27581)[API] feat: Add get bank accounts pro route

api/src/pcapi/core/providers/api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27723
=> (PC-27723)[API] fix: logs parameters

pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.module.scss, pro/src/pages/Offerers/Offerer/VenueV1/fields/PricingPoint/PricingPoint.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27676 (https://passculture.atlassian.net/browse/PC-27676)
Branche: PC-26839-siret-callout
=> (PC-27676)[PRO] style: callout de siret, l'espace du haut

api/src/pcapi/validation/routes/users_authentifications.py
=> (BSR)[API] feat: log CM V2 api calls

pro/src/components/ImageUploadBrowserForm/ImageUploadBrowserForm.tsx, pro/src/screens/IndividualOffer/StocksThing/ActivationCodeFormDialog/AddActivationCodeForm.tsx, pro/src/ui-kit/form/shared/BaseFileInput/BaseFileInput.stories.tsx, pro/src/ui-kit/form/shared/BaseFileInput/BaseFileInput.tsx, pro/src/ui-kit/form/shared/BaseFileInput/index.ts, pro/src/ui-kit/form/shared/index.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25198
=> (PC-25198)[PRO] refactor: Migrer la stories BaseFileInput

api/tests/routes/pro/get_reimbursements_csv_test.py
=> (BSR)[API] fix: Flaky test on the 1st of the month

api/src/pcapi/connectors/serialization/allocine_serializers.py, api/src/pcapi/core/providers/allocine_movie_list.py, api/src/pcapi/domain/book_types.py, api/tests/providers/allocine_movie_list_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27514
=> (PC-27514)[API] fix: make some allocine movie fields nullable

pro/src/pages/Signup/SignupContainer/OperationProcedures/OperationProcedures.module.scss, pro/src/pages/Signup/SignupContainer/OperationProcedures/OperationProcedures.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25755
Branche: PC-25755-callout-signup-css
=> (PC-25755)[PRO] style: Ajout de l'espace à callout du haut, inscription

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26160
=> (PC-26160)[API] fix: offerer stats daily views order

pro/src/components/IndividualOfferForm/Informations/Informations.tsx, pro/src/ui-kit/form/DurationInput/DurationInput.stories.tsx, pro/src/ui-kit/form/DurationInput/DurationInput.tsx, pro/src/ui-kit/form/DurationInput/__specs__/DurationInput.spec.tsx, pro/src/ui-kit/form/DurationInput/index.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25205
=> (PC-25205)[PRO] refactor: Migrer la stories DurationInput

api/src/pcapi/routes/native/v1/authentication.py, api/tests/routes/native/v1/authentication_test.py
we trust the OpenID provider email verification
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27769
=> (PC-27769)[API] feat: validate user email on successful sso

api/src/pcapi/routes/native/v1/account.py, api/tests/routes/native/v1/account_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27751
=> (PC-27751)[API] feat: connect user on sso account creation

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27569
Supprimer un dispositif national de la sandbox.
=> (PC-27569)[EAC] feat: rm national program from sandbox

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27524
Supprimer le domaine "Gastronomie et arts du goût" de la sandbox, suite à une légère refont des domaines.
=> (PC-27524)[EAC] feat: rm replaced domain

api/src/pcapi/routes/native/v1/authentication.py, api/tests/routes/native/v1/authentication_test.py
to avoid complex logic in native app error handling
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27768
=> (PC-27768)[API] refactor: single sign on error codes

pro/src/ui-kit/form/DatePicker/DatePicker.stories.tsx, pro/src/ui-kit/form/DatePicker/DatePicker.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25206
Migrer la story du composant DatePicker  
https://pass-culture.github.io/pass-culture-main/?path=/story/ui-kit-forms-datepicker--without-label
=> (PC-25206)[PRO] refactor: migrate DatePicker story

pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.stories.tsx, pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25207
Migrer la story CheckboxGroup
https://pass-culture.github.io/pass-culture-main/?path=/story/ui-kit-forms-checkboxgroup--default
=> (PC-25207)[PRO] refactor: migrate CheckboxGroup story

api/src/pcapi/domain/music_types.py, api/src/pcapi/routes/pro/offers.py, api/tests/routes/pro/get_offers_music_genres_test.py, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27766
=> (PC-27766)[API] feat: create event eligible music types route

api/src/pcapi/core/finance/api.py, api/src/pcapi/templates/invoices/invoice.html, api/src/pcapi/templates/invoices/invoice_legacy.html, api/tests/core/finance/test_api.py, api/tests/core/finance/test_integration.py, api/tests/files/invoice/rendered_invoice_legacy.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23431
=> (PC-23431)[API] feat: Invoice template for new bank details journey

api/src/pcapi/routes/institutional/playlist.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
```
➜ curl --silent localhost:5001/institutional/playlist/home_site_instit | jq '.[] | {name: .name, image_url: .image.url}'
{
"name": "Offre 1 de la playlist du site institutionnel",
"image_url": "http://localhost/storage/thumbs/mediations/AE"
}
{
"name": "Offre 2 de la playlist du site institutionnel",
"image_url": "http://localhost/storage/thumbs/mediations/A9"
}
{
"name": "Offre 3 de la playlist du site institutionnel",
"image_url": "http://localhost/storage/thumbs/mediations/AM"
}
{
"name": "Offre 4 de la playlist du site institutionnel",
"image_url": "http://localhost/storage/thumbs/mediations/AQ"
}
{
"name": "Offre 5 de la playlist du site institutionnel",
"image_url": …
```
=> (PC-27669)[API] feat: add institutional website playlist in sandbox

pro/scripts/customRequest.ts, pro/src/apiClient/adage/core/request.ts, pro/src/apiClient/v1/core/request.ts, pro/src/apiClient/v2/core/request.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27790
we wanna reject request when network error 
(we remove it to fix an error sentry here https://github.com/pass-culture/pass-culture-main/pull/8917/commits/d3f5ececb1d61a23acd0ca8be1f1303e9f363001)
=> (PC-27790)[PRO] feat: avoid infinite loading when api is not reachable

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/finance/repository.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/custom_reimbursement_rule/blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/native/v1/favorites.py, api/src/pcapi/utils/login_manager.py, api/src/pcapi/validation/routes/users_authorizations.py, api/tests/core/bookings/test_api.py, api/tests/core/reference/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27805
=> (PC-27805)[API] chore: Reduce SQLAlchemy warnings

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240131T132549_d787e69663b1_add_opening_hours_table.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/src/pcapi/utils/date.py, api/tests/core/offerers/test_api.py, api/tests/routes/pro/get_venue_test.py, api/tests/routes/pro/get_venues_test.py, pro/src/apiClient/v1/models/GetVenueResponseModel.ts, pro/src/core/Venue/adapters/__specs__/useGetVenue.spec.ts, pro/src/screens/VenueForm/__specs__/VenueEditionFormScreen.spec.tsx, pro/src/utils/collectiveApiFactories.ts, pro/src/utils/individualApiFactories.ts
- Ajout d'une table OpeningHours
- Ajout des opening hours à la route GET de venue
- ajout de la timezone à la route GET Venue
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26612
Page Notion : https://www.notion.so/passcultureapp/Page-Partenaire-Backend-5e3429a3763149fb8f68e60e959bc1c5?pvs=4
=> (PC-26612)[API] feat: add OpeningHours table

pro/src/app/AppRouter/subroutesIndividualOfferWizardMap.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25014
=> (PC-25014)[PRO] fix: offer creation title

pro/src/ui-kit/form/DatePicker/DatePicker.tsx, pro/src/ui-kit/form/MultiSelectAutoComplete/MultiSelectAutocomplete.tsx, pro/src/ui-kit/form/Select/Select.tsx, pro/src/ui-kit/form/SelectAutoComplete/SelectAutocomplete.tsx, pro/src/ui-kit/form/TextArea/TextArea.tsx, pro/src/ui-kit/form/TextInput/TextInput.tsx, pro/src/ui-kit/form/TimePicker/TimePicker.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25228
=> (PC-25228)[PRO] fix: add aria-required to fields

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/tests/routes/backoffice/conftest.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-27832
=> (PC-27832)[BO] fix: counter for "Présence CB dans les lieux"

api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/v1/offers_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27802
- ~[ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data~
- ~[ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques~
=> (PC-27802)[API] feat: add venue bannerurl to offer route

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/tasks.py, api/tests/core/offerers/test_api.py, api/tests/core/offerers/test_commands.py, api/tests/core/offerers/test_tasks.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27712
=> (PC-27712)[API] feat: auto rejected offerer if siren-caduc and status pending

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/pro/finance.py, api/src/pcapi/routes/serialization/finance_serialize.py, api/tests/core/finance/test_repository.py, api/tests/routes/pro/get_invoices_v2_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/InvoiceListV2QueryModel.ts, pro/src/apiClient/v1/models/InvoiceListV2ResponseModel.ts, pro/src/apiClient/v1/models/InvoiceResponseV2Model.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24476
=> (PC-24476)[API] feat: add v2 /finance/invoices route to get invoices by bank accounts

.github/workflows/dev_on_workflow_tests_api.yml, api/.squawk.toml, api/Dockerfile, api/src/pcapi/alembic/CONTRIBUTING.md, api/src/pcapi/alembic/run_migrations.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26775
Un exemple de migration refusée par squawk peut être trouvée dans la PR #6399
=> (PC-26775)[API] feat: add alembic migration linting

pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25372
améliorer reponsive de la page
=> (PC-25372)[PRO] feat: page confirmation responsive

api/src/pcapi/routes/backoffice/pro/forms.py, api/tests/routes/backoffice/pro_test.py
Complément au ticket Jira : https://passculture.atlassian.net/browse/PC-26990
=> (PC-26990)[BO] fix: create offerer with non-existing SIRET

api/src/pcapi/core/finance/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/finance/forms.py, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/list.html, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21878
=> (PC-21878)[API] feat: backoffice create filter on incident page

api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py, api/src/pcapi/core/search/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27688
BSR - on ignorer l'erreur lié à image ratio et on print combien de fois c'est arrivé. l'erreur n'est pas prévu d'être géré pour le moment
=> (PC-27688)[API] feat: reindex venues after banner synchronization with google places

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240208T094934_d02672d59311_add_venue_provider_date_created.py, api/src/pcapi/core/providers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27850
=> (PC-27850)[API] feat: Add venue_provider dateCreated column

api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/public/collective/endpoints/bookings.py, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26646
- [] J'ai écrit les tests nécessaires
=> (PC-26646)[BO] style: Change the error message when cancelling an already refunded booking

api/src/pcapi/core/mails/transactional/users/online_event_reminder.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25410
Update suite à [ce commentaire](https://github.com/pass-culture/pass-culture-main/pull/10579#discussion_r1483000984) sur une PR déjà mergée
=> (PC-25410)[API] perf: improve sql to avoid duplicated joins

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27870
=> (PC-27870)[PRO] fix: log error when format fails in InvoiceTable

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/backoffice/bank_account/blueprint.py, api/src/pcapi/routes/backoffice/templates/bank_account/get.html, api/src/pcapi/routes/backoffice/templates/bank_account/get/invoices.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/routes/backoffice/bank_account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26381
=> (PC-26381)[BO] feat: add invoices to bank account page on bo

api/src/pcapi/tasks/cloud_task.py
2 commits, peuvent être relus séparément.
=> (BSR)[API] Améliorations sur notre client Google Cloud Tasks : timeout + log

api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27892
=> (PC-27892)[API] fix: fix flaky test on incident_fixture where id booking and incident can be the same

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240206T105319_d118574a7888_add_is_visible_in_app.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/routes/pro/get_offerer_test.py, pro/src/apiClient/v1/models/GetOffererVenueResponseModel.ts, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26286
=> (PC-26286)[API] feat: add isVisibleInApp to GetOffererVenueResponseModel

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27887
=> (PC-27887)[API] fix: Add check for debit not to avoid exception

pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/ClassroomPlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/__specs__/ClassroomPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/VenuePlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/__specs__/VenuePlaylist.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27718
=> (PC-27718)[ADAGE] feat: wording on discovery page

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27793
=> (PC-27793)[API] feat: disable algolia dynamic re-ranking

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240125T155224_04caadcaa652_add_index_to_institution_name.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/forms.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/utils.py, api/tests/routes/backoffice/autocomplete_test.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27017
=> (PC-27017)[BO] feat: add advanced search to collective offers

pro/src/pages/Bookings/NoBookingsForPreFiltersMessage/NoBookingsForPreFiltersMessage.tsx, pro/src/pages/Bookings/__specs__/BookingsRecap.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/NoFilteredBookings.tsx, pro/src/screens/Bookings/BookingsRecapTable/NoFilteredBookings/__specs__/NoFilteredBookings.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/__specs__/BookingsRecapTable.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26492
=> (BSR)[PRO] fix: wording on bookins no data message

pro/package.json, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/store/rootReducer.ts, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26950
=> (PC-26950)[PRO] chore: upgrade reselect

api/src/pcapi/routes/public/individual_offers/v1/products.py
It should not have been merged, i just wanted to test it.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27908
=> (PC-27908)[API] fix: do not use atomic for now

api/src/pcapi/core/offers/factories.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/offers/test_factories.py
=> (BSR)[API] feat: productFactory takes subcategory into account to generate extradata

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/pro/venues.py, api/src/pcapi/routes/serialization/base.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/patch_venue_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/EditVenueBodyModel.ts, pro/src/apiClient/v1/models/VenueOpeningHoursModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27144
=> (PC-27144)[API] feat: add opening hours to PATCH venues

api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py, api/tests/routes/adage_iframe/get_collective_offer_test.py, api/tests/routes/adage_iframe/get_favorites_test.py, api/tests/routes/adage_iframe/playlist_test.py, pro/src/apiClient/adage/models/OfferVenueResponse.ts
Required for the new offer page in Adage to display the venue's picture.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27930
=> (PC-27930)[API] feat: include bannerUrl for venue in CollectiveOfferResponseModel

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/backoffice/bank_account/blueprint.py, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/tests/routes/backoffice/bank_account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24278
=> (PC-24278)[API] feat: Add venue.common_name/venue.id in the BankAccount modification history

api/src/pcapi/local_providers/chunk_manager.py, api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py, api/src/pcapi/local_providers/local_provider.py, api/src/pcapi/repository/providable_queries.py, api/src/pcapi/utils/cinema_providers.py, api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py, api/tests/utils/cinema_providers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27791
=> (PC-27791)[API] feat: Do not build `idAtProviders` with showtime

api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27874
=> (PC-27874)[API] fix: send city and postal code to gmaps when synchronizing banner

api/src/pcapi/sandboxes/scripts/creators/data/create_data_thing_products.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27945
=> (PC-27945)[API] fix: remove Product.url occurence in data sandbox

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27828
=> (PC-27828)[BO] fix: Batch Validate Bookings Form correction

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240215T092219_88d300a290b1_delete_adage_discovery_ff.py, api/src/pcapi/models/feature.py, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27912
**Objectif**
Supprimer le FF d'affichage de la page découverte d'adage.
=> (PC-27912)[PRO] feat: Remove adage discovery FF.

api/src/pcapi/connectors/api_allocine.py, api/src/pcapi/domain/allocine.py, api/tests/connectors/api_allocine_test.py, api/tests/connectors/fixtures.py
- Gestion des erreurs de validation pouvant survenir avec le endpoint /movieList.
- Log de l'id allociné si possible
=> BSR Enhance api allocine logs

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py
Since we now have a unicity constraint on adageId, the sandbox needs to produce unique adageId
=> (BSR)[API] fix: remove sandbox duplicated adageId

api/src/pcapi/core/finance/api.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27980
=> (PC-27980)[API] fix: Check Venue.bookingEmail before trying to send bank account link deprecation email

api/src/pcapi/connectors/ftp_titelive.py, api/src/pcapi/core/users/repository.py, api/src/pcapi/local_providers/local_provider.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py, api/src/pcapi/utils/date.py
Commits à relire indépendamment.
=> (BSR)[API] Suppression de vieux FIXME

pro/src/screens/SignupJourneyForm/Offerer/__specs__/OffererForm.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/validationSchema.tsx
Ticket Jira : https://passculture.atlassian.net/browse/PC-28016
=> (PC-28016)[PRO] fix: error message when SIRET is not visible

pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/ModalImageCrop.tsx, pro/src/pages/Bookings/__specs__/BookingsRecap.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx, pro/src/screens/Bookings/PreFilters/FilterByEventDate.tsx, pro/src/screens/Bookings/PreFilters/FilterByVenue.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27905
=> (PC-27905)[PRO] fix: flag optional filters as optional

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240216T134646_6d2971ccc616_remove_favorite_mediationid_foreign_key.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/native/v1/favorites.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27803
=> (PC-27803)[API] feat: remove foreign key Favorite.mediationId from favorite

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx, pro/src/pages/Reimbursements/__specs__/Reimbursements.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27975
- Mettre à jour l'offerer dans le localStorage quand on change d'utilisateur
- Utiliser l'offerer du contexte pour filtrer les comptes bancaires et les lieux des pages de remboursements
=> Pc 27975 pro update user offerer on login

pro/src/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.tsx, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27906
=> (PC-27906)[PRO] fix: callout link

pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/serializer.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27919
=> (PC-27919)[API] feat: check if music type and subtype are falsy

pro/src/app/AppRouter/routesMap.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24694
Changer le titre du hub
=> (PC-24694)[PRO] feat: change hub title

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240219T095923_e9ed5b8f1267_add_updateDate_to_google_places_info.py, api/src/pcapi/alembic/versions/20240219T100248_ed4a0376eefe_make_placeId_nullable_in_google_places_info.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25942
=> Pc 25942 do not synchronize venues with gmaps after 3 fails

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/tests/routes/backoffice/helpers/post.py, api/tests/routes/backoffice/offers_test.py
- repository.save() or commit() within the loop causes new select queries to refresh data (without joinedload)
- repository.save() calls entity validators, which checks venue.isVirtual when object is an offer
Ticket Jira : https://passculture.atlassian.net/browse/PC-28063
=> (PC-28063)[BO] fix: many N+1 SQL queries in batch_edit_offer

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-27942
Même rendu que dans la liste de la page « Action sur les lieux ».
=> (PC-27942)[BO] feat: show isPermanent in the list of managed venues

api/src/pcapi/core/search/__init__.py, api/tests/core/search/test_api.py, api/tests/core/search/test_commands_indexation.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27913
=> (PC-27913)[API] fix: fix last 30 days booking reindexation batching problem

api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/patch_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27727
=> (PC-27727)[API] feat: allow edit offer description from api

api/src/pcapi/core/users/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-18552
=> (PC-18552)[API] test: add weird young user status scan command

api/src/pcapi/connectors/serialization/allocine_serializers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28079
=> Pc 28079 add laser to allocine projection modes

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28078
=> (PC-28078)[API] feat: add allocine id to offers in algolia

api/src/pcapi/core/bookings/validation.py, api/src/pcapi/routes/public/booking_token/v2/endpoints.py, api/tests/core/bookings/test_api.py, api/tests/core/bookings/test_validation.py, api/tests/routes/public/individual_offers/v1/patch_cancel_booking_by_token_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28091
=> (PC-28091) throw different error if cancelling a used or reimbursed booking

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28032
=> (PC-28032)[API] tests: improve creation of allocine venues

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27996
=> (PC-27996)[PRO] feat: some involve on invoices table

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/factories.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27852
- Fix duplication de lignes dans extraction csv invoice
- Fix signe du pricing line généré sur un incident trop percu partiel
=> (PC-27852)[API] fix: invoice file line duplication

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240221T153023_04c2660a8169_remove_ff_wip_partner_page.py, api/src/pcapi/models/feature.py, pro/cypress/e2e/updateVenue.cy.ts, pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx, pro/src/pages/Home/Venues/VenueList.tsx, pro/src/pages/Home/Venues/__specs__/VenueList.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23616
- retirer FF WIP_PARTNER_PAGE
=> (PC-26316)[PRO] remove ff WIP_PARTNER_PAGE

pro/src/screens/VenueForm/VenueEditionFormScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27681
=> (PC-27681)[PRO] fix: hide visibility status for non permanent venues

api/src/pcapi/core/users/api.py
Fixer l'erreur sentry: https://sentry.passculture.team/organizations/sentry/issues/1328075/?project=5&referrer=slack
=> (BSR)[API] fix: add birth date to integration beneficiary

pro/src/components/Banner/BannerInvisibleSiren.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/EventCancellationBanner.tsx, pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28008
=> (PC-28008)[PRO] fix: external links

pro/src/components/ActionsBarSticky/ActionsBarSticky.stories.tsx, pro/src/components/ActionsBarSticky/ActionsBarSticky.tsx
BSR
réparer la story
+ la migrer du coup
=> (BSR)[PRO] fix: story ActionBarSticky

api/src/pcapi/core/permissions/models.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/templates/accounts/get/general.html, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/backoffice/conftest.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27488
=> (PC-27488)[BO]feat: button to anonymise user not beneficiary

api/src/pcapi/core/search/__init__.py, api/tests/core/search/test_api.py, api/tests/core/search/test_commands_indexation.py
=> (BSR)[API] fix: repare flacky tests on master

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28086
**Objectif**
Créer le FF pour le chantier de personnalisation du formulaire de contact.
=> (PC-28086)[PRO] feat: Add WIP_ENABLE_COLLECTIVE_CUSTOM_CONTACT FF.

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/serialization/users.py, api/tests/core/users/test_models.py, api/tests/routes/pro/get_collective_booking_test.py, api/tests/routes/pro/get_offerers_bank_accounts_test.py, api/tests/routes/pro/get_reimbursements_csv_test.py, api/tests/routes/pro/get_user_profile_test.py, api/tests/routes/pro/signin_test.py, pro/src/apiClient/v1/models/SharedCurrentUserResponseModel.ts, pro/src/apiClient/v1/models/SharedLoginUserResponseModel.ts
Unused since e5bbfae16aaeeeff945d7df4d1565e60c6f51faa.
=> (BSR)[API,PRO] chore: Remove `hasPhysicalVenues` from User response model

api/src/pcapi/core/external/batch.py, api/src/pcapi/routes/external/sendinblue.py, api/tests/core/external/batch_test.py, api/tests/core/external/external_users_test.py, api/tests/scripts/external_users/batch_update_users_attributes_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26819
=> (PC-26819)[API] feat: send marketing_email_subscription to Batch

api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/forms/string_field.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28029
=> (PC-28029)[BO] fix: Create incident from multiple bookings form

api/src/pcapi/core/providers/allocine_movie_list.py, api/src/pcapi/local_providers/allocine/allocine_stocks.py, api/tests/domain/fixtures.py, api/tests/local_providers/allocine_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28155
=> (PC-28155)[API] feat: create missing products from allocine stocks synchro

api/src/pcapi/connectors/entreprise/sirene.py, api/src/pcapi/core/offerers/models.py, api/tests/connectors/sirene_test.py, api/tests/core/offerers/test_models.py
Unused since the removal of Flask-Admin in bfa484e5c5e43f66c448b363d0ac1db0688d4b11.
=> (BSR)[API] chore: Remove unused `Offerer.legal_category`

pro/src/components/FormLayout/FormLayout.module.scss, pro/src/components/FormLayout/FormLayout.stories.tsx, pro/src/components/FormLayout/FormLayout.tsx, pro/src/components/ImageUploader/ImageUploader.tsx, pro/src/components/IndividualOfferForm/ImageUploaderOffer/ImageUploaderOffer.module.scss, pro/src/components/IndividualOfferForm/ImageUploaderOffer/ImageUploaderOffer.tsx, pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesForm.tsx, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25230
**Objectif**
Rendre responsive les blocs infos (globalement même si c'est dans la cadre du formulaire de création d'offre)
=> Pc 25230 form info block responsive

pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx, pro/src/pages/Home/Venues/__specs__/Venue.tracker.spec.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine/CollectiveTimeLine.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveTimeLine/__specs__/CollectiveTimeLine.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx, pro/src/screens/Offers/RedirectToBankAccountDialog.tsx
Petit nettoyage constaté au passage
=> (BSR)[PRO] refactor: delete useless url part

api/src/pcapi/routes/backoffice/templates/offer/details.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28160
=> (PC-28160)[API] fix: None as description in backoffice if offer has no description

api/src/pcapi/core/offers/api.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28110
=> (PC-28110)[BO] fix: IntegrityError after moving an event offer

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27961
=> (PC-27961)[API] fix: payment file line duplication

pro/cypress/e2e/createVenue.cy.ts, pro/cypress/e2e/updateVenue.cy.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27683
cf notion: https://www.notion.so/passcultureapp/Tests-end-2-end-319fe8c496a64cb08ac80b0239e2e024
-> mais il y a avait pas vraiment d'info dessus :p 
+ un bug trouvé sur les venue sans siret
=> (PC-27683)[PRO] improve e2e

pro/src/screens/SignupJourneyForm/Validation/Validation.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28047
Contenir les url trop longues dans le bloc Activité
=> (PC-28047)[PRO] fix: wrap url when too long in signup journey

pro/cypress/e2e/createVenue.cy.ts, pro/src/components/VenueForm/Informations/Informations.tsx, pro/src/components/VenueForm/Informations/SiretOrCommentFields/SiretOrCommentFields.tsx, pro/src/components/VenueForm/VenueCreationForm.tsx, pro/src/screens/VenueForm/VenueEditionFormScreen.tsx, pro/src/screens/VenueForm/__specs__/VenueEditionFormScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28191
La valeur comparée n'était pas une chaine vide mais null, le boolean n'était donc pas de la bonne valeur
- et qq petits nettoyage au passage
=> (PC-28191)[PRO] fix update venue

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/pro/finance.py, api/src/pcapi/routes/serialization/finance_serialize.py, api/tests/core/finance/test_repository.py, pro/src/apiClient/v1/models/InvoiceListV2QueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27926
- Filtrer les invoices par structure par défaut sur la page des justificatifs
- Afficher les filtres disabled quand aucun invoice n'est disponible pour la structure sélectionnée
=> (PC-27926)[API] feat: add offerer_id param to getInvoicesV2 route

pro/cypress/e2e/createVenue.cy.ts
=> (BSR)[PRO] fix: e2e create venue not enough random

pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageEdit.tsx, pro/src/components/VenueForm/VenueEditionForm.tsx, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/VenueEdition/VenueEditionHeader.module.scss, pro/src/pages/VenueEdition/VenueEditionHeader.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27680
=> (PC-27680)[PRO] fix: venue header

api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/email/update.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v2/account.py, api/src/pcapi/routes/native/v2/serialization/account.py, api/tests/core/users/email/test_update.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v2/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27990
=> (PC-27990)[API] feat: add email change confirmation v2 route

pro/src/components/Banner/WithdrawalReminder.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27740
=> (PC-27740)[PRO] style: Ajout Callout - création d'offre, bien physique

pro/src/app/App/App.tsx, pro/src/app/__specs__/App.spec.tsx
This reverts commit a1ae8bba7285ccb8fd8f0401952a13e2d9428e53.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28224
Revert la redirection des utisateurs non rattaché vers le parcours d'inscription. La solution proposée ne fonctionne pas, en attente d'un fix futur
=> Revert "(PC-28224)[PRO] fix: redirect non rattached pro to onboarding"

api/src/pcapi/core/users/repository.py, api/tests/core/users/test_repository.py
Description : voir docstring dans le code.
=> (BSR) fix: fix test on leap year

.githooks/pre-commit, api/README.md, api/src/pcapi/alembic/env.py, api/src/pcapi/alembic/run_migrations.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28121
- checkout cette PR
- ajouter `text: str = Column(Text, index=True)` dans une table et générer la migration Alembic
- essayer de commit et ne pas pouvoir à cause du hook de pre-commit
=> (PC-28121)[API] feat: add squawk to pre-commit hook

api/src/pcapi/core/educational/api/adage.py, api/src/pcapi/core/educational/api/address.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/factories.py, api/tests/core/educational/api/test_address.py, api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27038
Mises à jour de la table adage_venue_address lors de la synchronisation des lieux adage.
=> (PC-27038)[EAC] feat: sync: add/update/delete venue addresses

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28056
=> (PC-28056[Algolia] Reactivate reranking

pro/src/ui-kit/form/shared/FieldSetLayout/FieldSetLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/27962
https://stackoverflow.com/questions/34300154/is-aria-required-allowed-on-radio-buttons-or-checkboxes
https://www.w3.org/TR/wai-aria/states_and_properties#aria-required
=> (PC-27962)[PRO] feat: aria-required on fieldset for group

api/src/pcapi/core/users/factories.py, api/tests/core/subscription/test_api.py
=> (BSR) fix: fix dms test on leap year

api/src/pcapi/routes/backoffice/venues/forms.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28277
=> (PC-28277)[BO] fix: add correct validation on update venue name

api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28280
=> (PC-28280)[API] fix: Catch network errors

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240228T163014_c8e741468d2a_remove_feature_flag_wip_behind_l7_load_balancer.py, api/src/pcapi/flask_app.py, api/src/pcapi/models/feature.py, api/stubs/flask/app.pyi, api/tests/test_flask_app.py
Suppression d'un feature flag... et suppression de 3 "type: ignore" au
passage, en bonus, parce que c'est vendredi.
Ticket : https://passculture.atlassian.net/browse/PC-27484
=> (PC-27484)[API] chore: Remove WIP_BEHIND_L7_LOAD_BALANCER feature flag

app-engine/image-resizing/main.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28290
=> (PC-28290)[APP-ENGINE] feat: add better logs to image resizing

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28178
- Créer le FF pour l'A/B test de la nouvelle navigation.
=> (PC-28178)[API] feat: Creating the WIP_ENABLE_NEW_NAV_AB_TEST FF.

pro/src/pages/Offers/Offers/Offers.scss, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27996
pour tester : 
compte [activation@example.com](mailto:activation@example.com)
structure copieux + coordonnées bancaires
WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY activé
=> (PC-27996)[PRO] feat: design ajustments in invoices table

pro/src/pages/Home/Offerers/OffererBanners.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28308
Fix des liens externes des bannières afficher sur la page d'accueil
=> (PC-28308)[PRO] fix: add missing isExternal to offerer banners

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28152
=> (PC-28152)[API] fix: Debit note not generated

pro/src/components/ImageEditor/ImageEditor.tsx, pro/src/components/ImagePreview/ImagePreview.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/ModalImageCrop.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27725
-> au final fait en js à cause de l'AvatrEditor qui fonctionne comme ça
encore des petits défaut pour la preview
=> (PC-27725)[PRO] offer image upload dialog responsive

api/src/pcapi/core/users/factories.py, api/src/pcapi/routes/native/v1/authentication.py, api/tests/routes/native/v1/authentication_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25594
=> (PC-25594)[API] feat: Raise error on password change when user has no password

api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/email/update.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v2/account.py, api/src/pcapi/routes/native/v2/serialization/account.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v2/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27997
=> (PC-27997)[API] feat: add email update status v2 route

api/src/pcapi/core/users/email/update.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/native/v2/account.py, api/src/pcapi/routes/native/v2/serialization/account.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v2/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28121
=> (PC-28121)[API] feat: add new email selection route

pro/yarn.lock
Mise à jour de browserslist-db.
=> (BSR)[PRO] bump: update browserslist db.

api/src/pcapi/core/users/email/update.py, api/src/pcapi/core/users/models.py, api/tests/routes/native/v2/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28275
=> (PC-28275)[API] feat: make email update cancellation compatible with v2

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240229T161142_fa4755bb92f0_update_collective_offer_contact_constraints.py, api/src/pcapi/core/educational/adage_backends/serialize.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/patch_collective_offer_template_test.py, pro/src/apiClient/adage/models/CollectiveOfferTemplateResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts, pro/src/components/CollectiveOfferSummary/components/CollectiveOfferContactSection/CollectiveOfferContactSection.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/ContactButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/RequestFormDialog.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28315
=> (PC-28315)[API] fix: rework pro contact options

pro/src/screens/IndividualOffer/StocksEventCreation/HelpSection/HelpSection.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28357
=> (PC-28357)[PRO] feat: responsive Booking HelpSection

pro/src/components/FormLayout/FormLayoutDescription.tsx, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27743
=> (PC-27743)[PRO] style: Ajout de Callout, créa d'offre, étape deux

pro/src/components/IndividualOfferForm/Categories/Categories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27738
=> (PC-27738)[PRO] style: Ajout de Callout, créa d'offre, étape un

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28279
=> (PC-28279)[BO] feat: Delete venue formerly set as pricing point, without pricing

pro/cypress/e2e/portal_not_connected/switchBetweenSignupAndSignIn.cy.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28345
=> (PC-28345)[PRO] test:switch between page signin and signup

pro/src/components/AdageButtonFilter/AdageButtonFilter.stories.tsx, pro/src/components/ConstraintCheck/ConstraintCheck.stories.tsx, pro/src/components/ConstraintCheck/ConstraintCheck.tsx, pro/src/components/Dialog/ConfirmDialog/ConfirmDialog.stories.tsx, pro/src/components/Dialog/RedirectDialog/RedirectDialog.stories.tsx, pro/src/components/ImageEditor/ImageEditor.stories.tsx, pro/src/components/ImageEditor/ImageEditor.tsx, pro/src/components/ImageUploader/ImageUploader.stories.tsx, pro/src/components/OfferAppPreview/OfferAppPreview.stories.tsx, pro/src/components/OfferAppPreview/OfferAppPreview.tsx, pro/src/components/PreferredOrientation/PreferredOrientation.stories.tsx, pro/src/components/PreferredOrientation/PreferredOrientation.tsx, pro/src/components/Stepper/Stepper.stories.tsx, pro/src/ui-kit/BoxRounded/BoxRounded.stories.tsx, pro/src/ui-kit/BoxRounded/BoxRounded.tsx, pro/src/ui-kit/Button/ButtonLink.stories.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25208
Migration de plusieurs storybook
=> (PC-25208)[PRO] refactor: migration storybook

pro/src/pages/VenueEdition/VenueEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28381
Changer la structure sélectionnée dans le context et le localStorage quand on arrive sur la page d'un lieu. 
**Contexte** 
Quand on arrive sur la page lieu depuis le BO par exemple, on souhaite que la structure sélectionnée dans le contexte change pour avoir les bonnes données affichées dans la page gestion financière et assurée une cohérence dans la navigation.
=> (PC-28381)[PRO] feat: change selected offererId on venue page

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240301T135957_e82695d3ec03_add_price_index_on_collectice_stock.py, api/src/pcapi/alembic/versions/20240301T140521_2eee70a08b61_add_price_index_on_stock.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/forms.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/utils.py, api/tests/routes/backoffice/collective_offers_test.py, api/tests/routes/backoffice/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27939
//////////////////////////////
convenue avec Raphael -> condition _bookable
/////////////////////////////
ajout des tables en staging
index price dans collective_stock
Time: 1.317s (1 second), executed in: 1.316s (1 second)
index price dans stock
Time: 548.330s (9 minutes 8 seconds), executed in: 548.330s (9 minutes 8 seconds)
=> (PC-27939)[BO] feat: filter offer and collective offer by price 

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28267
=> (PC-28267)[API] feat: add FF WIP_OPENING_HOURS

pro/src/screens/OfferType/CollectiveOfferType/CollectiveOfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28353
=> (PC-28353)[PRO] fix: eac link

pro/src/screens/IndividualOffer/IndivualOfferLayout/OfferStatusBanner/OfferStatusBanner.module.scss, pro/src/screens/IndividualOffer/IndivualOfferLayout/OfferStatusBanner/OfferStatusBanner.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27755
=> (PC-27755)[PRO] style: Ajout de Callout bleu "info", édition d'offre

pro/src/pages/Reimbursements/ReimbursementsBanners.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28831
Changer l'id de la structure sélecitonnée dans la home quand on arrive sur la page de Gestion financière depuis le BO par exemple avec un offererId dans l'url
=> (PC-28381)[PRO] feat: change offerer id in context on reimbursement page

pro/src/components/SideNavLinks/SideNavLinks.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27146
Fix ui de la side nav : 
- Modifier l'etat focus des onglets 
- Ajouter du radius sur la border-right quand l'état de l'onglet est actif
=> Pc 27146 fix UI side nav

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27996
tableau des remboursements, le retour, fait avec Martin cette fois ci !
=> (PC-27996)[PRO] fix: style of invoice table

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240304T100701_1be3db2bd7b9_create_index_on_venue_departement_code.py, api/src/pcapi/alembic/versions/20240304T132002_c7a4d9de4c48_create_index_on_user_unaccent_full_name.py, api/src/pcapi/alembic/versions/20240304T142603_3a8d3a5b86b2_create_index_on_offerer_unaccent_name.py, api/src/pcapi/alembic/versions/20240304T142604_640cb4c5d424_create_index_on_offerer_unaccent_city.py, api/src/pcapi/alembic/versions/20240304T155105_73468507305b_create_index_on_venue_unaccent_name.py, api/src/pcapi/alembic/versions/20240304T155106_23fa7b1b692e_create_index_on_venue_unaccent_public_name.py, api/src/pcapi/core/educational/api/venue.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/models/has_address_mixin.py, api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/routes/backoffice/pivots/contexts/allocine.py, api/src/pcapi/routes/backoffice/pivots/contexts/base.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28331
References:
https://peterullrich.com/unaccented-name-search-with-postgres-and-ecto
https://stackoverflow.com/questions/11005036/does-postgresql-support-accent-insensitive-collations
Commits à relire séparément pour faciliter la compréhension.
=> (PC-28331)[API] perf: fix indexes for search from the backoffice

api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28211
**Cette PR vient à la suite de la PR #11063 .**
After fixing indexed search in PC-28331, query plan with UNION vs OR on staging shows that OR is now much more faster.
```
EXPLAIN
SELECT booking.id AS booking_id, booking."dateCreated" AS "booking_dateCreated", booking."dateUsed" AS "booking_dateUsed", booking."stockId" AS "booking_stockId", booking."venueId" AS "booking_venueId", booking."offererId" AS "booking_offererId", booking.quantity AS booking_quantity, booking.token AS booking_token, booking."userId" AS "booking_userId", booking.amount AS booking_amount, booking."priceCategoryLabel" AS "booking_priceCategoryLabel", booking."cancellationDate" AS "booking_cancellationDate", booking."displayAsEnded" AS …
```
=> (PC-28211)[BO] fix: timeout when searching for bookings with free text

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240228T140741_17bbd580c848_add_last_validation_price_column_to_offers.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/tests/core/offers/test_api.py, api/tests/routes/backoffice/offers_test.py, api/tests/routes/pro/patch_publish_offer_test.py, api/tests/routes/pro/post_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28255
=> (PC-28255)[BO] feat: add lastValidationPrice to thing offers

api/src/pcapi/core/categories/subcategories_v2.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27952
=> (PC-27952)[API] feat: rename native categories labels

pro/src/screens/IndividualOffer/IndivualOfferLayout/OfferStatusBanner/OfferStatusBanner.module.scss, pro/src/screens/IndividualOffer/IndivualOfferLayout/OfferStatusBanner/OfferStatusBanner.tsx
Ces tickets sont ensemble car leurs callouts se trouvent dans le même fichier, pour éviter des conflits.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27756 
-> callout de recap-offre-refusee, variant={CalloutVariant.ERROR} (rouge)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27754 
-> callout de recap-offre-en attente de validation, variant={CalloutVariant.INFO}  (bleu)
=> (PC-27756)[PRO] style: Ajout de 2 Callout, édition de récap

api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py, api/tests/local_providers/cinema_providers/cgr/cgr_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25896
=> Pc 25896 synchronize cgr offers with allocine products

api/src/pcapi/core/educational/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27989
=> (PC-27989)[ADAGE] feat: add cron to sync offerer's allowedOnAdage

pro/src/app/AppRouter/routesMap.tsx, pro/src/pages/VenueEdition/subroutesVenueEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27682
=> (PC-27682)[PRO] fix: page titles

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240308T135307_8d5148b6b128_remove_ff_wip_adage_satisfaction_survey.py, api/src/pcapi/alembic/versions/20240308T143042_4df45e259f14_rmove_ff_wip_adage_diffuse_help.py, api/src/pcapi/models/feature.py, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27909
**Objectif**
Supprimer les FF WIP_ENABLE_SATISFACTION_SURVEY et WIP_ENABLE_DIFFUSE_HELP
=> Pc 27909 delete adage ff

pro/cypress/e2e/portal_not_connected/connexionPageConformityTest.cy.ts, pro/cypress/e2e/portal_not_connected/switchBetweenConnexionAndInscriptionTest.cy.ts, pro/cypress/support/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28431
=> (PC-28431)[PRO] test: verify connexion page conformity

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28442
=> (PC-28442)[API] feat: change gtls indexation on algolia

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240301T144157_ccd86b897e7a_create_user_pro_new_nav_state_table.py, api/src/pcapi/core/users/factories.py, api/src/pcapi/core/users/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bank_accounts.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_pro_users.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28174
=> (PC-28174)[API] feat: add UserProNewNavState table

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py, api/src/pcapi/connectors/entreprise/models.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/entreprise_info_rcs.html, api/tests/connectors/api_entreprise_test.py, api/tests/connectors/api_entreprise_test_data.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28454
Erreurs Sentry:
- https://sentry.passculture.team/organizations/sentry/issues/1506979/?project=5
- https://sentry.passculture.team/organizations/sentry/issues/1507057/?project=5
- https://sentry.passculture.team/organizations/sentry/issues/1507379/?project=5
=> (PC-28454)[API] fix: possible null values in the response from API Entreprise

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28457
Erreur Sentry : https://sentry.passculture.team/organizations/sentry/issues/1400573/?project=5
=> (PC-28457)[BO] fix: do not show 'Données Entreprise' tab for venues without SIRET

pro/src/pages/Home/Offerers/OffererDetails.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28423
Fix l'alignement des boutons `Inviter` | `Modifier` sur la page d'accueil
=> (PC-28423)[PRO] fix: fix offerer details button alignment

api/src/pcapi/routes/backoffice/templates/accounts/search.html, api/src/pcapi/routes/backoffice/templates/admin/roles.html, api/src/pcapi/routes/backoffice/templates/admin/users_generator.html, api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html, api/src/pcapi/routes/backoffice/templates/components/forms/select_multiple_field.html, api/src/pcapi/routes/backoffice/templates/components/history/view.html, api/src/pcapi/routes/backoffice/templates/finance/invoices/get.html, api/src/pcapi/routes/backoffice/templates/fraud/blacklist_domain_name_summary.html, api/src/pcapi/routes/backoffice/templates/home/home.html, api/src/pcapi/routes/backoffice/templates/home/login.html, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/routes/backoffice/templates/layouts/error.html, api/src/pcapi/routes/backoffice/templates/multiple_offers/search_result.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/offer_validation_rules/list_rules.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/individual_subscription.html, api/src/pcapi/routes/backoffice/templates/offerer/user_offerer_validation.html, api/src/pcapi/routes/backoffice/templates/offerer/validation.html, api/src/pcapi/routes/backoffice/templates/pivots/get/common.html, api/src/pcapi/routes/backoffice/templates/pro/get.html, api/src/pcapi/routes/backoffice/templates/pro/search.html, api/src/pcapi/routes/backoffice/templates/providers/get.html, api/src/pcapi/routes/backoffice/templates/tags/list_tags.html, api/src/pcapi/routes/backoffice/templates/titelive/search_result.html, api/src/pcapi/routes/backoffice/templates/venue/list.html
Reformatage des _templates jinja_ du backoffice avec la version actuelle de djlint.
Cela nous évitera des différences dans des commits fonctionnels.
=> (BSR)[BO] chore: update djlint fomatting

pro/cypress/e2e/createVenue.cy.ts, pro/cypress/e2e/updateVenue.cy.ts, pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx, pro/src/components/AccessibilitySummarySection/index.ts, pro/src/components/CollectiveOfferSummary/components/CollectiveOfferAccessibilitySection/CollectiveOfferAccessibilitySection.tsx, pro/src/components/SummaryLayout/SummaryLayout.module.scss, pro/src/components/SummaryLayout/SummarySection.tsx, pro/src/components/SummaryLayout/SummarySubSection.tsx, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.module.scss, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx, pro/src/utils/collectiveApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28265
=> (PC-28265)[PRO] feat: add readonly page for venue edition

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/api.py, api/tests/connectors/acceslibre/acceslibre_test.py, api/tests/connectors/acceslibre/fixtures.py, api/tests/core/offerers/test_api.py
L'appel à la route GET api/erps/{slug}/widget est encore en recette  côté acceslibre, cependant elle sera mise en prod prochainement. L'appel à cette route n'étant pas prévu d'ici là, on peut merger ce ticket
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27026
=> (PC-27026)[API] feat: add get accessibility infos from acceslibre data

pro/src/app/AppRouter/routesMap.tsx, pro/src/components/Footer/Footer.tsx, pro/src/components/Footer/__specs__/Footer.spec.tsx, pro/src/pages/Sitemap/Sitemap.module.scss, pro/src/pages/Sitemap/Sitemap.tsx, pro/src/pages/Sitemap/__specs__/Sitemap.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26620
Ajout de la page `Plan du site` 
**Screen**
=> (PC-26620)[PRO] feat: add sitemap

api/src/pcapi/connectors/dms/graphql/beneficiaries/get_single_application_details.graphql, api/src/pcapi/connectors/dms/models.py, api/src/pcapi/connectors/dms/serializer.py, api/tests/connectors/dms/schema.py, api/tests/connectors/dms/serializer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28072
=> (PC-28072)[API] fix: Use beneficiary user's email when DMS procedure is made by representative

api/tests/core/bookings/test_api.py, api/tests/core/subscription/dms/test_api.py, api/tests/routes/pro/get_stocks_test.py
=> (BSR)[API] chore: Remove useless `freezegun` usage

pro/src/components/IndividualOfferForm/Categories/Categories.tsx, pro/src/components/IndividualOfferForm/__specs__/IndividualOfferForm.BannerAddVenue.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27738 Info se trouve dans commentaire du ticket
=> (PC-27738)[PRO] style: Ajout de style aux Callout, ajustement

api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/add_accessibility_compliance_to_venues.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28323
=> (PC-28323) feat: add a11y info for venues in sandbox

pro/.eslintrc.cjs, pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx
Ajouter des règles eslint pour avoir une config optimale (cf parking)
=> (BSR)[PRO] refactor: improve eslint config

pro/src/app/AppLayout.tsx, pro/src/app/__specs__/AppLayout.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28233
Ajouter le trap focus sur le menu de navigation latérale en mode responsive
=> (PC-28233)[PRO] feat: add trap focus for responsive side nav

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240312T115519_1ac22a2f313e_eac_collective_offer_teamplte_contactform_default_form_null.py, api/src/pcapi/core/educational/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28448
=> (PC-28448)[EAC] fix: tmplate.contactForm.default: 'form' -> null

pro/src/hooks/useAdapter.ts, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataEdition.module.scss, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataEdition.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataEditionReadOnly.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/__specs__/CollectiveDataEdition.spec.tsx, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28266
=> (PC-28266)[PRO] feat: read only collective

api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_individual_offerers.py, api/tests/routes/backoffice/autocomplete_test.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-27932
=> (PC-27932)[BO] feat: filter offerers to validate by instructor

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240307T153355_b1c9eff03366_add_offer_price_limitation_rule_table.py, api/src/pcapi/core/offers/factories.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/__init__.py, api/src/pcapi/routes/backoffice/offer_price_limitation_rules/blueprint.py, api/src/pcapi/routes/backoffice/offer_price_limitation_rules/forms.py, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/src/pcapi/routes/backoffice/templates/offer_price_limitation_rules/list_rules.html, api/src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offer_price_limitation_rules.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/routes/backoffice/offer_price_limitation_rules_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28238
=> (PC-28238)[BO] feat: add OfferEditionRules to db and BO

pro/src/components/FormLayout/FormLayoutDescription.tsx, pro/src/screens/IndividualOffer/StocksThing/StockThing.module.scss, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27743 (voir commentaires)
=> (PC-27743)[PRO] style: Ajout de style aux Callout, ajustement

pro/src/components/CollectiveOfferSummary/__specs__/CollectiveOfferSummary.spec.tsx, pro/src/components/CollectiveOfferSummary/components/CollectiveOfferContactSection/CollectiveOfferContactSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28512
=> (PC-28512)[PRO] fix: typo in collective offer contact summary

api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py
Ticket Jira (ou description si BSR) :BSR
l'objectif de créer une entrée pour les lieux non trouvé sur google maps. puisqu'on ce base sur cette table pour ne pas synchronisés les lieux pour les quels la synchronisation a fail 3 fois de suite.
=> (BSR)[API] fix: create a google places info entry when no associated place is found

api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28084
=> (PC-28084)[BO] feat: add actionhistory when edit multiple venues permanent or not

api/src/pcapi/routes/backoffice/admin/blueprint.py, api/src/pcapi/routes/backoffice/templates/admin/subcategories.html, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/tests/routes/backoffice/admin_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28364
=> (PC-28364)[BO] feat: add page for list of category and subcategory

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py, api/src/pcapi/sandboxes/scripts/mocks/accessibility_mocks.py, api/tests/connectors/acceslibre/acceslibre_test.py
1er commit de refacto pour corriger une petite coquille de traduction
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28039
=> (PC-28039)[API] feat: add external accessibility data to sandbox

pro/src/pages/VenueCreation/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx, pro/src/pages/VenueCreation/OpeningHoursReadOnly/utils.ts, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.module.scss, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx, pro/src/pages/VenueEdition/setInitialFormValues.ts, pro/src/pages/VenueEdition/types.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28272
- avoir les boutons + les jours qui apparaissent
=> Pc 28272 form opening hours days

pro/src/components/SummaryLayout/SummaryLayout.module.scss, pro/src/pages/Home/Offerers/PartnerPage.module.scss, pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx, pro/src/pages/Home/Offerers/PartnerPageIndividualSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27685
- ajouter une mini marge
=> (PC-27685)[PRO] fix: ui details on summary component

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/models/feature.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/pro/post_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28483
=> (PC-28483)[API] feat: add price limitation to stock upsertion

pro/src/app/AppRouter/routesMap.tsx
Le title était undefined pendant un court instant en allant sur `/`
=> (BSR)[PRO] fix: undefined page title

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/routes/pro/bookings.py, api/src/pcapi/routes/serialization/bookings_recap_serialize.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/BookingStatusFilter.ts, pro/src/apiClient/v1/models/ExportBookingsQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28129
=> (PC-28129)[API] feat: add route to get bookings by status csv or excel

api/src/pcapi/core/educational/commands.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28543
=> (PC-28543)[API] fix: commit while allowedOnAdage is updated

api/pyproject.toml, api/src/pcapi/core/finance/conf.py, api/src/pcapi/core/subscription/ubble/archive_past_identification_pictures.py, api/src/pcapi/core/users/models.py, api/src/pcapi/models/api_errors.py, api/src/pcapi/utils/secrets.py
This will be the default in a future mypy release.
See https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-local-partial-types
=> (BSR)[API] ci: Eable "local_partial_types" in mypy

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/exceptions.py, api/src/pcapi/routes/pro/users.py, api/tests/core/users/test_api.py, api/tests/routes/pro/post_user_new_pro_nav_test.py, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28470
=> (PC-28470)[API] feat: add new-pro-nav route

pro/cypress/e2e/createThingIndividualOffer.cy.ts, pro/src/pages/VenueEdition/VenueEditionHeader.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-277725
=> (PC-27725)[PRO] fix: image uploader size on small screen

api/src/pcapi/local_providers/titelive_things/titelive_things.py, api/tests/local_providers/titelive_things_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28591
=> (PC-28591)[API] feat: check 18+ readers info only on gtls

pro/.storybook/preview-head.html
- Tentative de correction des urls sur le storybook en prod.
=> (BSR)[PRO] fix: Fixing fonts import for storybook.

pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.module.scss, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28272
- ajustemeent design
- ne l'affiché que pour les lieux permanents
=> (PC-28272)[PRO] feat: adjustment for OpeningHoursForm

pro/src/app/AppLayout.module.scss, pro/src/components/Footer/Footer.module.scss, pro/src/components/Header/Header.module.scss, pro/src/components/SideNavLinks/SideNavLinks.module.scss, pro/src/styles/variables/_z-index.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26866
- Ajout de la version mobile du footer.
- Le top menu et la side nav doivent rester en position fixe.
=> (PC-26866)[PRO] feat: New footer fixes.

api/src/pcapi/routes/native/v1/serialization/offerers.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/scripts/subscription/dms/handle_deleted_dms_applications.py
The standard library has all we need.
=> (BSR)[API] chore: Remove useless import of typing-extension package

api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/serialization/venue_provider_serialize.py, api/tests/core/providers/test_models.py, api/tests/routes/pro/get_venue_providers_test.py, api/tests/routes/pro/post_venue_provider_test.py, pro/src/apiClient/v1/models/VenueProviderResponse.ts, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProviderItem/VenueProviderItem.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx
Delete a costly query that doesn't give much information (and a real pain for users with lots of synchronized offers).
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28622
=> (PC-28622)[API] chore: remove costly count

api/src/pcapi/scripts/rebuild_staging/anonymize.sql
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28443
=> (PC-28443)[API] fix: deactivate offers related to venues with deactivated synchro

api/README.md
Complète le README afin de pouvoir lancer l'app **et les tests** sans docker en local
=> (BSR)[API] feat: explicit database initialization in readme to run app without docker

pro/cypress/e2e/updateVenue.cy.ts
=> (BSR)[PRO] fix: e2e flakyness

pro/package.json, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataEdition.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/__specs__/CollectiveDataEdition.spec.tsx, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/__specs__/VenueEdition.spec.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx, pro/src/utils/renderWithProviders.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28561
Installer SWR et l'utiliser pour la récupération des venues
=> (PC-28561)[PRO] feat: install swr / useSwr in venue edition

api/Dockerfile, helmfile.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28579
=> (PC-28579)[API] feat: add google-cloud-sdk to pcapi-console

api/src/pcapi/routes/backoffice/admin/blueprint.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28666
=> (PC-28666)[BO] fix: fix bug redirection in get_subcategories

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/routes/pro/bookings.py, api/src/pcapi/routes/serialization/bookings_recap_serialize.py, api/tests/core/bookings/test_repository.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/BookingsExportQueryModel.ts, pro/src/apiClient/v1/models/BookingsExportStatusFilter.ts, pro/src/apiClient/v1/models/ExportBookingsQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28130
=> (PC-28130)[API] feat: fill csv and excel export with bookingss data

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28404
Réindexer les offres vitrines dans la sandbox (industrial).
=> (PC-28404)[EAC] feat: sandbox: reindex all offer templates

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/__init__.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/fill.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28260 
Mises à jour de la sandbox, côté eac : 
1. correction d'un id adage ;
2. simulation d'une synchronisation des données des playlists.
=> PC 28260 eac clean update sandbox

api/src/pcapi/connectors/dms/graphql/pro/get_bank_info_applications.graphql, api/src/pcapi/connectors/dms/serializer.py, api/src/pcapi/domain/demarches_simplifiees.py, api/tests/connector_creators/demarches_simplifiees_creators.py, api/tests/domain/demarches_simplifiees_test.py, api/tests/use_cases/save_venue_bank_informations_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28537
=> (PC-28537)[API] feat: Handle pending corrections status for bank account

pro/src/pages/VenueCreation/CollectiveDmsTimeline/CollectiveDmsTimeline.tsx, pro/src/pages/VenueCreation/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28596
- retirer une double info
=> (PC-28596)[PRO] fix: remove double info adage accepted

pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28673
Supprimer le titre facture de la page des justificatifs de remboursements
=> (PC-28673)[PRO] fix: remove unwanted title in invoices page

api/src/pcapi/core/categories/subcategories_v2.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26732
=> (PC-26732)[API] feat: rename native category

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28546
=> (PC-28546)[API] feat: add venue adress to algolia

api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28628
=> (PC-28628)[API] feat: crop venue banner images received from gmaps

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240318T153914_1a30851c9eac_add_offer_address_models.py, api/src/pcapi/alembic/versions/20240318T161926_afa2a84f772d_add_offer_offerer_address_id_column.py, api/src/pcapi/alembic/versions/20240318T162637_fe5b67e9e72b_add_offer_offerer_address_fk_constraint.py, api/src/pcapi/alembic/versions/20240319T142438_5c90621be933_add_stock_offerer_address_id_column.py, api/src/pcapi/alembic/versions/20240319T142826_3de57d5476d5_add_stock_offerer_address_fk_constraint.py, api/src/pcapi/core/geography/factories.py, api/src/pcapi/core/geography/models.py, api/src/pcapi/core/offers/models.py, api/tests/core/geography/test_models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26141
=> (PC-26141)[API] feat: Add offer/address  models

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27028
-> But de cette commande: être ajoutée dans la crontab pour tourner toutes les semaines (à date, sur ~17k venues permanentes) 
Ajout du cas où une entrée est supprimée côté acceslibre : on relance un match avec notre lieu
=> (PC-27028)[API] feat: command to fetch acceslibre data

pro/src/components/Dialog/ConfirmDialog/ConfirmDialog.tsx, pro/src/components/Dialog/ConfirmDialog/__specs__/ConfirmDialog.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOffer.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/AdageOfferInstitutionPanel.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/__specs__/AdageOfferInstitutionPanel.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/__specs__/AdageOffer.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingModal.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28534
Adapter l'offre réservable qui s'affiche sur adage pour l'utiliser en mode preview
=> (PC-28534)[PRO] feat: adapt offer bookable for preview

api/tests/core/offerers/test_synchronize_venues_banners_with_google_places.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28628
=> Pc 28628 crop gmaps venue banner

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/managed_venues.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28568
=> (PC-28568)[API]feat: Numéro de dossier DMS adage sur la page structure

api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28576
=> (PC-28576)[BO]feat: DMS adage folder displayed on venue

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28620
**Objectif**
Créer le ff pour la nouvelle manière d'afficher les offres dans la recherche ADAGE.
=> (PC-28620)[API] feat: Create FF WIP_ENABLE_ADAGE_VISUALIZATION

pro/src/components/NewNavReview/NewNavReview.module.scss, pro/src/components/NewNavReview/NewNavReview.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28188 
Fix ui pour la bannière de review : 
- Ajout de bordure
- Changement de couleur de picto
- changement de wording : `version` -> `interface`
=> (PC-28188)[PRO] fix: ui fixes for naw nav review banner

api/src/pcapi/domain/book_types.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28507
=> (PC-28507)[API] refactor: uniformize book tree wordings

api/src/pcapi/core/mails/transactional/pro/invoice_available_to_pro.py, api/tests/core/finance/test_integration.py, api/tests/core/mails/transactional/pro/invoice_available_to_pro_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28648
=> (PC-28648)[API] fix: send mail to all linked venues

pro/src/app/AppLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28188
La condition actuelle ne prenait pas en compte que `currentUser` pouvait être null si l'utilisateur n'était pas connecté
=> (PC-28188)[PRO] fix: fix nav review banner display condition

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_serialize_algolia.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27494
=> (PC-27494)[API] feat: make allocineId a distinct value for Algolia

pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx, pro/src/pages/VenueEdition/OpeningHoursReadOnly/__specs__/OpeningHoursReadOnly.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28625
=> (PC-28625)[PRO] feat: add no OpeningHours information

api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/get_venue_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/AccessibilityDataModel.ts, pro/src/apiClient/v1/models/GetVenueResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27490
=> (PC-27490)[API] feat: add accessibility data to GET venues

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28735
=> (PC-28735)[API] fix: make sure every pricing is taken into account

api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/get_venue_test.py, api/tests/routes/pro/patch_venue_test.py, pro/src/apiClient/v1/models/GetVenueResponseModel.ts, pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx, pro/src/pages/VenueEdition/OpeningHoursReadOnly/__specs__/OpeningHoursReadOnly.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28696
=> (PC-28696)[API] feat: update venueOpeningHours serialization

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/serialization/users.py, api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/core/users/test_api.py, api/tests/scripts/beneficiary/import_test_users_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28663
Testé en environnement de dev local à partir de la commande `flask import_test_users` avec un extrait de l'export CSV du fichier de référence.
=> (PC-28663)[API] test: Create venue and bank account with staging pro test accounts

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28796
=> (PC-28796)[BO] fix: 'Présence CB dans les lieux' counters with new bank accounts

api/src/pcapi/routes/backoffice/venues/forms.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28635
=> (PC-28635)[BO] refactor: Change commentaire interne by commentaire qui apparaitra sur le lieu when deleting a siret

api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/badges.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/static/backoffice/scss/pc/_variables.scss, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28177
=> (PC-28177)[BO] feat: Add new nav/old nav tags on offerer page

pro/src/components/FormLayout/FormLayoutDescription.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss, pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.tsx, pro/src/screens/IndividualOffer/StocksThing/StockThing.module.scss, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28376
Dates:
Stock:
=> (PC-28376)[PRO] style: add words* at form offre, dates

pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.tsx, pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.module.scss, pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx, pro/src/components/SummaryLayout/SummaryLayout.module.scss, pro/src/components/SummaryLayout/SummarySubSection.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOffer.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/AdageOfferInstitutionPanel.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/AdagePreviewLayout.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/__specs__/AdagePreviewLayout.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingModal.tsx, pro/src/pages/CollectiveOfferPreviewEdition/CollectiveOfferPreviewEdition.tsx, pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.module.scss, pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx, pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28532
Ajouter un lien pour l'aperçu de l'offre réservable lors de l'édition d'une offre réservable
=> (PC-28532)[PRO] feat: edition preview for bookable offer

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240306T154447_166608debd4c_add_search_offer_last_profider_id_index.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/routes/backoffice/autocomplete.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/routes/backoffice/utils.py, api/tests/routes/backoffice/autocomplete_test.py, api/tests/routes/backoffice/offers_test.py
=> (PC-28085)[BO] feat: filter individual offers on providers

pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx, pro/src/components/CollectiveOfferSummary/components/CollectiveOfferAccessibilitySection/CollectiveOfferAccessibilitySection.tsx, pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageEdit.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageEdit.tsx, pro/src/components/ImageUploader/ImageUploader.module.scss, pro/src/pages/VenueEdition/VenueEditionHeader.module.scss, pro/src/pages/VenueEdition/VenueEditionHeader.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/form/__specs__/onSubmit.spec.ts, pro/src/screens/IndividualOffer/StocksEventCreation/form/__specs__/recurrenceUtils.spec.ts, pro/src/screens/IndividualOffer/StocksEventCreation/form/onSubmit.ts, pro/src/screens/IndividualOffer/StocksEventCreation/form/recurrenceUtils.ts, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28722
=> (BSR)[PRO] fix: rationalize aspect ratios

api/tests/core/offers/test_api.py, api/tests/routes/pro/post_stocks_test.py
BSR
- reproduire le changement de l'erreur
=> (BSR)[API] fix: test priceCategoryRule

pro/src/screens/IndividualOffer/StocksEventEdition/__specs__/StockEventEdition.spec.tsx
Correction des tests sur master
=> (BSR)[PRO] fix: tests on master

pro/src/pages/IndividualOfferWizard/PriceCategories/PriceCategories.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesForm.module.scss, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesForm.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28255
=> Pc 28355 responsive price category

api/src/pcapi/connectors/cgr/cgr.py, api/src/pcapi/connectors/cgr/exceptions.py, api/src/pcapi/core/external_bookings/cgr/exceptions.py, api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/tests/connectors/cgr/api_cgr_test.py, api/tests/core/external_bookings/cgr/test_client.py
Ticket Jira (ou description si BSR) : The TODO requested it, I obliged
=> (BSR)[API] chore: move cgr exception

api/src/pcapi/models/feature.py, api/src/pcapi/scripts/install_data.py, api/tests/models/feature_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28828 
Vérification de l'existence des feature flags
=> (PC-28828)[API] chore: feature flag completness

api/src/pcapi/core/educational/api/playlists.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/routes/adage_iframe/playlist_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28468
=> (PC-28468) probleme de localisation page decouverte

api/versionning, api/versionning_utils/all_versions.sh, api/versionning_utils/find_route.sh, api/versionning_utils/highest_version.sh
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28380
=> Scripts for finding versions of a route

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/badges.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28792
=> (PC-28792)[BO] feat: add new nav tags to venue details

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py, api/tests/connectors/api_entreprise_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-255855
Erreur Sentry : https://sentry.passculture.team/organizations/sentry/issues/1521706/
=> (PC-28855)[API] fix: API Entreprise: redis lock expiration must be > 0

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/api/stock.py, api/src/pcapi/core/educational/exceptions.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/collective_offers.py, api/src/pcapi/routes/pro/collective_stocks.py, api/src/pcapi/routes/public/collective/endpoints/offers.py, api/tests/routes/pro/patch_collective_offer_test.py, api/tests/routes/pro/post_collective_stock_test.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
Ticket Jira (ou description si BSR) : The FIXMEs indicated the code was now useless
=> (BSR)[API] chore: remove some obsolete code about 6eme and 5eme

pro/src/pages/VenueEdition/OpeningHoursForm/HourLine.tsx, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.module.scss, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28274
=> (PC-28274)[PRO] feat: OpeningHoursForm responsive

pro/src/pages/Desk/Desk.tsx, pro/src/pages/Desk/__specs__/Desk.spec.tsx, pro/src/pages/Reimbursements/ReimbursementsDetails/DetailsFilters.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoicesFilters.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementDetails.spec.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx, pro/src/screens/OffererStats/OffererStatsScreen.tsx, pro/src/screens/OffererStats/__specs__/OffererStatsScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28680
=> (PC-27743)[PRO] style: Delete stars from labels

pro/package.json, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28609
=> (PC-28609)[PRO] build: bump vitest to 1.4.0

pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx
Revert d'une optimisation non nécessaire générant de la complexité dans le code
=> (BSR)[PRO] refactor: simplify venue selection code

api/src/pcapi/core/users/models.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/templates/pro_user/get.html, api/tests/routes/backoffice/pro_users_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28793
=> (PC-28793)[BO] feat: Add new/old nav tags to user details page

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240328T143829_0403f97207ba_make_cinema_provider_pivot_venueid_non_nullable.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/backoffice/pivots/forms.py, api/tests/routes/backoffice/pivots_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28874
=> (PC-28874)[BO] feat: venueId of CinemaProviderPivot is now mandatory

pro/src/components/Callout/Callout.module.scss, pro/src/components/ReimbursementsTabs/ReimbursementsTabs.module.scss, pro/src/pages/Home/Venues/Venue.module.scss, pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28713
Changement de couleur sur certains composants du portail pro, pour préparer la mise en place de thèmes. 
Changement de la couleur de l'icone :  primary -> error
| Avant | Après |
| :----: | :-----: |
| ![Capture d’écran 2024-03-29 à 08 25 29](https://github.com/pass-culture/pass-culture-main/assets/71768799/278e3661-ee7a-453e-acf9-7f4ad0c39b16) | ![Capture d’écran 2024-03-29 à 08 25 51](https://github.com/pass-culture/pass-culture-main/assets/71768799/0e0451f0-237a-4264-b3fc-a05bcffcb2f5) |
Changement de la couleur de l'icone :  primary -> error
| Avant | Après |
| :----: | :-----: |
| ![Capture d’écran 2024-03-29 à 08 29 03](https://github.com/pass-culture/pass-culture-main/assets/71768799/8058d8 …
=> (PC-28713)[PRO] feat: change callout error icon color

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28862
=> (PC-28862)[PRO] feat: add WIP_ACCESLIBRE feature flag

api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/finance/validation.py, api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/components/forms/string_field.html, api/src/pcapi/routes/backoffice/templates/components/turbo/modal_empty_form.html, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/src/pcapi/static/backoffice/js/addons/pc-batch-action-form.js, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28778
Validation en amont du formulaire de création des incidents de trop perçu.
- Vérification du montant:
- Affichage de messages d'erreur au lieu du formulaire :
=> (PC-28778)[BO] feat: finance - improve overpayment incident creation uix

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240322T125349_374e35815645_collective_offer_contact_email_nullable.py, api/src/pcapi/core/educational/adage_backends/serialize.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/public/collective/serialization/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/post_collective_offers_test.py, pro/src/apiClient/adage/models/CollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/PostCollectiveOfferBodyModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28707
=> (PC-28707)[API] fix: collective offer creation from template

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/BankAccountHasPendingCorrectionCallout.tsx, pro/src/components/Callout/LinkVenueCallout.tsx, pro/src/components/Callout/__specs__/BankAccountHasPendingCorrectionCallout.spec.tsx, pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx, pro/src/components/ReimbursementsTabs/ReimbursementsTabs.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28464
- Corrections wording et design
=> (PC-28464)[PRO] feat: Bank account details changes if needs corrections.

api/src/pcapi/routes/backoffice/pivots/contexts/allocine.py, api/src/pcapi/routes/backoffice/pivots/contexts/base.py, api/tests/routes/backoffice/pivots_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28771
=> Pc 28771 delete allocine pivot from bo

api/src/pcapi/core/offerers/api.py, api/tests/routes/pro/post_save_new_onboarding_data_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28837
=> (PC-28837)[API] test: enable EAC for any new offerer in integration

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/constants.py, api/src/pcapi/core/offerers/validation.py, api/tests/routes/pro/patch_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28623
=> (PC-28623)[API] fix: allow update venue without updating venue accessibility

api/src/pcapi/algolia_settings_offers.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28820
=> (PC-28820)[API] feat: Disable dynamic reranking

pro/src/sentry.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28934
=> (PC-28934)[PRO] fix: google recaptcha triggering sentry error

api/src/pcapi/routes/public/individual_offers/v1/products.py, api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
Fix logs message and add missing informations
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28942
=> (PC-28942)[API] fix: public ean api exception name in logs

.github/workflows/dev_on_dispatch_release_build_hotfix.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28930
=> (PC-28930)[release] fix slack notification build bis

.github/workflows/templates/post-upgrade-job.yaml, .github/workflows/templates/pre-upgrade-job.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28954
=> (PC-28954) ci: disable migration retries

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/offerers/api.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py, api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28550
Fix : ne pas permettre l'envoi de requête vers l'API Adage en intégration (toutes les structures sont considérées comme étant autorisées à créer des offres collectives).
=> (PC-28550)[EAC] fix: public api: integration: disable requests to adage

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28867
=> (PC-28867)[API] feat: redo down payments file with ministries

pro/src/pages/VenueEdition/OpeningHoursForm/HourLine.tsx, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28894
ça me semble pas ouf, si quelqu'un a une meilleure idée !
=> (PC-28894)[PRO] feat: errors in OpeningHoursForm dont extends field

pro/src/pages/VenueEdition/OpeningHoursForm/HourLine.tsx, pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.module.scss, pro/src/pages/VenueEdition/OpeningHoursForm/__specs__/OpeningHoursForm.spec.tsx, pro/src/ui-kit/form/TimePicker/TimePicker.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28273
=> (PC-28273)[PRO] feat: add mins to hour timepickers

pro/.eslintrc.cjs, pro/src/components/ImageUploadBrowserForm/ImageUploadBrowserForm.tsx, pro/src/components/OfferEducationalActions/OfferEducationalActions.tsx, pro/src/components/UserEmailForm/UserEmailForm.tsx, pro/src/components/UserIdentityForm/UserIdentityForm.tsx, pro/src/components/UserPasswordForm/UserPasswordForm.tsx, pro/src/components/UserPhoneForm/UserPhoneForm.tsx, pro/src/hooks/useAnalytics.ts, pro/src/hooks/useGetBitmap.ts, pro/src/pages/CollectiveOfferStockEdition/CollectiveOfferStockEdition.tsx, pro/src/pages/EmailChangeValidation/EmailChangeValidation.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx, pro/src/pages/Offers/OffersRoute.tsx, pro/src/pages/Signup/SignupContainer/SignupContainer.tsx, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/ToggleVenueProviderStatusButton.tsx, pro/src/screens/CsvTable/CsvTable.tsx
=> (BSR)[PRO] refactor: remove then calls and promote floating promises warning to error

pro/src/screens/OfferEducational/OfferEducationalForm/FormVenue/FormVenue.module.scss, pro/src/screens/OfferEducational/OfferEducationalForm/FormVenue/FormVenue.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28799
=> (PC-28799)[PRO] style: Ajout de callout, étape un, Lieu *

.github/workflows/dev_on_dispatch_release_build.yml
=> (BSR)[deploy] fix slack notification

pro/src/components/IndividualOfferForm/IndividualOfferForm.tsx, pro/src/components/ScrollToFirstErrorAfterSubmit/ScrollToFirstErrorAfterSubmit.tsx, pro/src/components/ScrollToFirstErrorAfterSubmit/__specs__/ScrollToFirstErrorAfterSubmit.spec.tsx, pro/src/hooks/index.ts, pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.tsx, pro/src/pages/ResetPassword/ChangePasswordForm/ChangePasswordForm.tsx, pro/src/pages/SignIn/SigninForm.tsx, pro/src/pages/Signup/SignupContainer/SignupForm.tsx, pro/src/pages/VenueCreation/VenueCreationForm.tsx, pro/src/pages/VenueEdition/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx, pro/src/pages/VenueEdition/OpeningHoursReadOnly/__specs__/OpeningHoursReadOnly.spec.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueSettings/VenueSettingsForm.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28273
=> (PC-28273)[PRO] feat: scroll to first error in venue edition

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/commands.py, api/tests/connectors/acceslibre/acceslibre_test.py, api/tests/connectors/acceslibre/fixtures.py, api/tests/routes/pro/get_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28981
=> (PC-28981)[API] fix: command to synchronize acceslibre

api/src/pcapi/connectors/serialization/acceslibre_serializers.py, api/tests/routes/pro/get_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29018
=> (PC-29018)[API] fix: attribute error on serialization if no externalAccessibilityData

pro/src/pages/IndividualOfferWizard/Offer/Offer.tsx, pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29020
=> (PC-29020)[PRO] fix: Création d'offre indiv impossible depuis la page offre - rafraîchissement intempestif des catégories

pro/src/pages/AdageIframe/app/components/UnauthenticatedError/UnauthenticatedError.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29028
=> (PC-29028)[ADAGE] fix: remove wrong email from adage error page

api/src/pcapi/routes/native/v1/serialization/recommendation.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/recommendation_test.py
Les commits peuvent être relus séparément, j'en ai profité pour ajouter et améliorer les tests.
=> (BSR)[API] feat: Accept and forward camelCase'd data in Recommendation API proxy routes

api/src/pcapi/domain/book_types.py, api/tests/domain/book_types_test.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29033
=> (PC-29033)[API] feat: re-add old GTL to book tree

api/src/pcapi/routes/backoffice/autocomplete.py, api/tests/routes/backoffice/autocomplete_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29036
=> (PC-29036)[BO] fix: autocomplete was available without authentication

.github/workflows/dev_on_dispatch_release_build_hotfix.yml
=> (BSR) ci: fix slack notif hotfix

pro/src/sentry.ts
Check https://github.com/getsentry/sentry-javascript/issues/3440
=> (BSR)[PRO] fix: ignore Sentry error when Outlook scans link

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28801
Upgrade downshift
=> (PC-28801)[PRO] feat: upgrade downshift

api/src/pcapi/core/educational/factories.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_institutions.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_incidents.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28856
Suppression d'établissements scolaires inutiles de la _sandbox industrial_ : certains étaient explicitement créés, d'autres l'étaient plus probablement par mégarde (via la création d'une réservation collective).
Nouvelle manière de générer l'email de contact d'un établissement, à partir de son nom et de sa ville. Ceci permet de ne pas avoir toujours la même adresse.
=> (PC-28856)[EAC] feat: sandbox: do not create too many institutions

pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx, pro/src/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx, pro/src/components/SummaryLayout/SummarySection.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.module.scss, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx, pro/src/pages/VenueCreation/Accessibility/Accessibility.module.scss, pro/src/pages/VenueCreation/Accessibility/Accessibility.tsx, pro/src/pages/VenueCreation/VenueCreationForm.tsx, pro/src/pages/VenueCreation/VenueFormActionBar/VenueFormActionBar.module.scss, pro/src/pages/VenueCreation/VenueFormActionBar/VenueFormActionBar.tsx, pro/src/pages/VenueCreation/VenueFormActionBar/__specs__/VenueFormActionBar.spec.tsx, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreCollapse.module.scss, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreCollapse.tsx, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.module.scss, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.tsx, pro/src/pages/VenueEdition/AccesLibreSection/__specs__/AccesLibreCollapse.spec.tsx, pro/src/pages/VenueEdition/AccesLibreSection/__specs__/AccesLibreSection.spec.tsx, pro/src/pages/VenueEdition/VenueEdition.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionFormScreen.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx, pro/src/pages/VenueEdition/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28864
=> (PC-28864)[PRO] feat: affichage Accès libre dans le front

api/src/pcapi/core/finance/api.py, api/tests/routes/backoffice/collective_offer_templates_test.py, api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira (ou description si BSR) : de vieux FIXME/TODO à enlever
=> Bsr clean some todo and fixme in bo

pro/src/components/IndividualOfferForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28276
=> (PC-28276)[PRO] fix: include uppercase in mail validation

api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py, api/src/pcapi/core/external_bookings/models.py, api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py, api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py, api/tests/local_providers/cinema_providers/cds/fixtures.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25895
=> PC-25895 synchronize cds offers with allocine products

pro/src/app/AppLayout.module.scss, pro/src/app/AppLayout.tsx, pro/src/components/Footer/Footer.module.scss, pro/src/components/Header/Header.module.scss, pro/src/components/NewNavReview/NewNavReview.module.scss, pro/src/components/SideNavLinks/SideNavLinks.module.scss, pro/src/screens/Bookings/Bookings.tsx, pro/src/screens/Offers/Offers.tsx, pro/src/styles/variables/_colors.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28396 
Divers ajustements graphiques pour la nouvelle interface du portail pro : 
- Suppression des shadow et ajout de bordures à la place 
- Ajout d'une couleur de fond 
- Ajustement du positionnement du contenu principal (32px à droite de la nav) 
- Ajustement de la taille de l'outline de l'état focus des liens de la side nav
- Changement de couleur des liens actifs de la side nav 
- Changements des titres des pages offres/réservations lorsque la nouvelle interface est active
=> Pc 28396 pro new interface UI fixes

pro/src/pages/VenueCreation/Accessibility/Accessibility.tsx, pro/src/pages/VenueCreation/Accessibility/__specs__/Accessibility.spec.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28864
=> (PC-28864)[PRO] fix: hide callout behind FF

api/src/pcapi/core/offerers/models.py, api/src/pcapi/utils/date.py, api/tests/routes/pro/get_venue_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28900
=> Qds pc 28900 sort opening hours

pro/src/screens/OfferType/CollectiveOfferType/CollectiveOfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28945
=> (PC-28945)[PRO] style: Ajout de Callout, création d'offre

pro/src/components/Banner/BannerInvisibleSiren.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28994
=> (PC-28994)[PRO] style: Callout ERROR de l'incription SIRET

.github/workflows/dev_on_dispatch_release_build.yml, .github/workflows/dev_on_dispatch_release_build_hotfix.yml
2 commits à relire séparément. Cf. le message de chaque commit pour l'explication.
=> (BSR)[API] Corrections dans la notification Slack de build (pose d'un tag)

api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/email/update.py, api/src/pcapi/routes/native/v1/authentication.py, api/src/pcapi/routes/native/v2/account.py, api/src/pcapi/routes/native/v2/serialization/account.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/native/v2/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28723
=> (PC-28723)[API] feat: require password for email change

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/validation.py, api/tests/core/offers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-29079
=> (PC-29079)[API] feat: add tracker to monitor prices blocked by price limitation rules

pro/src/app/AppLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29150
Ne pas ajouter un espace supplémentaire si l'utilisateur est éligible mais n'a pas encore activé la nouvelle interface
=> (PC-29150)[PRO] fix: fix spacing between header/content

pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreCollapse.tsx, pro/src/pages/VenueEdition/AccesLibreSection/__specs__/AccesLibreCollapse.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28864
=> (PC-28864)[PRO] feat: change default open value of collapse

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/__specs__/AdagePreviewLayout.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/__spec__/PrebookingButton.spec.tsx, pro/src/pages/AdageIframe/app/hooks/useAdageUser.ts, pro/src/pages/AdageIframe/app/providers/AdageUserContext.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27647
On souhaite que le nombre à la suite de "Pour mon établissement" dans le header ADAGE soit dynamique
=> (PC-27647)[PRO] feat: dynamic institution number header in adage

api/src/pcapi/core/offers/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offer_validation_rules/blueprint.py, api/src/pcapi/routes/backoffice/offer_validation_rules/forms.py, api/src/pcapi/routes/backoffice/templates/offer_validation_rules/sub_rules_extra_row.html, api/tests/core/offers/test_api.py, api/tests/routes/backoffice/offer_validation_rules_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28968
=> (PC-28968)[BO] feat: add validation rule on venues

api/src/pcapi/local_providers/cinema_providers/ems/ems_stocks.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25894
=> PC-25894 synchro ems stocks with allocine catalogue

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/__spec__/PrebookingButton.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx, pro/src/styles/variables/_themes.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28840
SOUS FF : WIP_ENABLE_ADAGE_VISUALIZATION
Ajouter un bandeau rouge au dessus de l'offre réservable (onglet Pour mon établissement sur adage)
=> (PC-28840)[PRO] feat: adage offer not template new headband

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/commands.py, api/tests/connectors/acceslibre/acceslibre_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29099
=> (PC-29099)[API] fix: connection error handling in sync acceslibre

pro/src/screens/SignupJourneyForm/Offerer/Offerer.module.scss
Parcours inscription page Renseigner le SIRET.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28994
=> (PC-28994)[PRO] style: Ajout margin top, page SIRET

pro/src/app/AppLayout.module.scss, pro/src/app/AppLayout.tsx, pro/src/components/Footer/Footer.module.scss, pro/src/components/SignupJourneyFormLayout/SignupJourneyFormLayoutContent.module.scss, pro/src/components/Tutorial/Tutorial.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28996
Divers fix graphique pour la nouvelle interface 
- Ajustements des marges du content en mode responsive 
- Ajustements des marges dans le parcours d'inscription 
- Ne pas afficher le footer dans le parcours d'inscription
- Ferrage du footer à gauche au même niveau que le content 
- Ne pas afficher la dernière étape du tuto pour la nouvelle interface (cette étape affichait l'ancien header)
=> Pc 28996 pro fix signup journey with new nav

api/src/pcapi/connectors/beamer.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/commands.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28776
=> (PC-28776)[API] feat: add GPRD pro anonymization

api/src/pcapi/routes/pro/venue_providers.py, api/src/pcapi/routes/serialization/venue_provider_serialize.py, api/src/pcapi/validation/routes/users_authorizations.py, pro/src/apiClient/v1/models/PostVenueProviderBody.ts, pro/src/apiClient/v1/models/VenueProviderResponse.ts
Les commits peuvent être relus séparément.
=> (BSR)[API] Encore un peu de nettoyage dans les vues relatives aux providers

pro/src/hooks/useAnalytics.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29182
Ajouter l'id de la structure selectionnée dans les logs firebase
=> (PC-29182)[PRO] feat: add offerer_id to firebase log

pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx, pro/src/pages/VenueCreation/Accessibility/Accessibility.tsx, pro/src/pages/VenueCreation/Accessibility/__specs__/Accessibility.spec.tsx, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/pages/VenueEdition/VenueEditionReadOnly.tsx, pro/src/pages/VenueEdition/__specs__/VenueEditionFormScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28865
=> (PC-28865)[PRO] fix: wordings and links

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240411T121621_ed9648801317_add_validationauthor_column_for_booking_table.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/src/pcapi/routes/public/booking_token/v2/endpoints.py, api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/tests/core/bookings/test_api.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_integration.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28787
=> (PC-28787)[BO] feat: author display in status when booking used

pro/src/hooks/useAnalytics.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29182
Fix la condition pour set l'offerer_id dans les logs firebase pour éviter que ca crash quand firebase n'est pas encore initialisé sur pc pro
=> (PC-29182)[PRO] fix: fix condition when seting offerer_id in firebase

pro/src/components/Banner/BannerReimbursementsInfo.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28500
=> (PC-28500)[PRO] feat: change Reimbursment callout text

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29099
Petites améliorations pour améliorer l'execution du script + amélioration de la commande de ratrappage
=> (PC-29099)[API] feat: improve command to sync acceslibre

pro/src/pages/Home/WelcomeToTheNewBetaBanner/WelcomeToTheNewBetaBanner.module.scss
Reviewed [here](https://github.com/pass-culture/pass-culture-main/pull/11703)
=> (PC-28552)[PRO] feat: Beta test banner.

api/src/pcapi/core/users/api.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26619
=> (PC-26619)[API] feat: clear user single sign on on email change

.github/workflows/dev_on_dispatch_release_build.yml, .github/workflows/dev_on_dispatch_release_build_hotfix.yml, .github/workflows/dev_on_dispatch_release_deploy.yml
Améliorer les messages postés sur Slack par nos actions GH
Commits à relire séparément
=> (BSR) Edit CI slack notifications

api/src/pcapi/core/users/api.py, api/tests/routes/native/v1/account_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29013
=> (PC-29013)[API] feat: Add log on notification subscription update

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/sandboxes/scripts/creators/data/create_data_venues.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_incidents.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_venues.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_offerer_with_several_venues.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_integration.py, api/tests/core/offerers/test_api.py, api/tests/routes/pro/get_invoices_v2_test.py, api/tests/routes/pro/get_offerer_test.py, pro/cypress/e2e/adageDiscovery.cy.ts, pro/src/pages/AdageIframe/app/components/AdageDiscovery/VenueCard/VenueCard.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29007
=> (PC-29007)[API] chore: remove reimbursement point stuff from sandbox

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29187
=> PC-29187 : Deploy pcapi with argocd

api/src/pcapi/core/offerers/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29023
=> (PC-29023)[API] feat: add log error in case of missing data
