.github/workflows/deploy-pro-pr-version-generic.yml, config/run_envs/integration, config/run_envs/production, config/run_envs/staging
It's not used anymore.
---
J'ai du mal à voir quand on a arrêté d'utiliser cette variable... En
tout cas, je ne trouve pas où elle est utilisée actuellement.
=> (BSR)[PRO] ci: Remove unused export of `ENVIRONMENT_NAME` environment variable

pro/src/pages/AdageIframe/app/App.tsx, pro/src/pages/AdageIframe/app/components/OffersInfos/OffersInfos.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26450
Lorsqu’on clique sur un domaine artistique dans la page découverte, on est bien redirigé avec le bon tag, mais la recherche ne correspond pas au tag choisi, on veut avoir directement les bons résultats sans cliquer sur rechercher après la redirection
=> (PC-26450)[PRO] fix: playlist domains on redirect data not filtered

pro/src/pages/Home/Homepage.module.scss, pro/src/pages/Home/Homepage.tsx, pro/src/pages/SignIn/SignIn.tsx, pro/src/pages/SignIn/Signin.module.scss
Le sélecteur `h1` dans `SignIn.module.scss` débordait sur les autres pages. A cause du lazyload, ce selecteur n'est plus chargé sur la homepage, créant un bug de marge.
=> on ne doit pas mettre de selecteur HTML dans le scss scopé
=> (BSR)[PRO] fix: margin below title

pro/src/apiClient/adresse/apiAdresse.ts, pro/src/components/VenueForm/Informations/__specs__/Informations.spec.tsx, pro/src/core/Venue/adapters/getSiretDataAdapter.ts, pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26226
-  si la géolocalisation de l’adresse du SIRET n’est pas trouvée via API Adresse, on refait une requête pour récupérer le géocodage du centroïde de la commune aka les coordonnées du centre de la commune, et on crée le Venue avec ces informations
=> (PC-26226)[PRO] feat: If no coordinates, get the municipality centroid.

pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.tsx, pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26314
edge case:
Lorsque la structure n'a pas de lieu, et que l'utilisateur a créé un compte bancaire, ne pas afficher de message ou de bouton de rattachement d'un lieu.
Censé rendre ça:
=> (PC-26314)[PRO] refactor: no bank information if no venue

api/rebuild_staging.sh
This command is designed to find and reindex a variety of offers to always have relevant stuff in staging research
Testé en staging. Malheureusement c'est long (30 min)
En revanche ça répond à un besoin PM et QA important. 
Proposition si c'est trop long: retirer la réindexation qui est faite actuellement (dans le script rebuild du repo infra) et la remplacer par celle-ci, qui est plus complète
=> (BSR)[API] build: run index_offers_staging in rebuild_staging

api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/constants.py, api/src/pcapi/routes/native/v1/authentication.py, api/src/pcapi/routes/native/v1/serialization/authentication.py, api/tests/routes/native/v1/authentication_test.py, api/tests/routes/native/v1/openapi_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26070
<details>
<summary>Code source</summary>
```
sequenceDiagram
participant Google
participant App
participant Backend
App ->>+ Backend: GET /oauth/state
Backend ->> Backend: Génération et sauvegarde du token de state oauth
Backend -->>- App: Envoi du state
Note over App: L'app ne stocke pas le state
App ->>+ Google: Connexion SSO (manuelle)<br/>Envoi du state reçu
Google -->>- App: Envoi du code d'autorisation<br/>Envoi du state reçu
App ->>+ Backend: Envoi du code d'autorisation (POST /google/authorize)<br/>Envoi du state reçu
Note over App: Le state envoyé est celui reçu de Google
Backend ->> Backend: Validation du state
Backend ->>+ Google: Validation du code d'autorisation
Google -->>- Backend: Envoi …
```
=> (PC-26070)[API] feat: add csrf attack prevention for google sso

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.module.scss, pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.module.scss, pro/src/styles/variables/_size.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26266
**Objectif**
Faire le minimum vital pour que les offres de la recherche adage ne sortent pas de l'écran sur les plus petites tailles. Et ajout d'un scroll dans le header pour contenir la largeur de l'écran quelle que soit la taille de l'appareil.
**A noter**
J'ai mis les breakpoints des `size` en rem dans le premier commit.
=> (PC-26266)[PRO] adage offer responsive

api/src/pcapi/routes/adage_iframe/playlists.py
and for devel.
Since we can't get data from BigQuery that matches the testing sandbox, we'll skip the condition about BigQuery returning empty set.
Longer reason is that BigQuery has the staging's ids and they don't match the collective offers / templates / venues found in testing. Bottom line, objects are not found and nothing is returned, but since we had ids the previous condition failed us.
=> (BSR)[ADAGE] feat: always return valid data for playlists in testing

api/src/pcapi/tasks/amplitude_tasks.py, api/tests/core/bookings/test_api.py, api/tests/routes/native/v1/subscription_test.py, api/tests/routes/saml/educonnect_test.py
All backends expect the user id to be an integer, which is what we get
from `payload.user_id`. So we should not convert it to a string here.
Only the real backend (that talks to Amplitude HTTP API) needs the
user id to a string, and it already converts it.
This did not cause any bug.
=> (BSR)[API] fix: Remove unwanted user id int-to-str conversion in `amplitude_tasks.track_event()`

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/backoffice/multiple_offers/forms.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/titelive/forms.py, api/src/pcapi/routes/backoffice/utils.py, api/src/pcapi/utils/string.py
Improve offer search by EAN
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26500
It should improve theses cases : https://sentry.passculture.team/organizations/sentry/issues/423864/events/563bcb3ff7d942ea9aa981ed396f10c7/?environment=production&project=5&statsPeriod=90d or https://sentry.passculture.team/organizations/sentry/issues/423864/events/e0924dc894464c9fbc94f09b692f2b91/?environment=production&project=5&statsPeriod=90d
In staging a 13 digits search took around 150.200s (for a cultura user). 
It is now around 3s
The full text search is improving, but might still timeout. It wen from 130s to 70s (for same user and keyword `guitare shiver` )
=> (PC-26500)[API] perf: search offer by ean if a string with 13 digit is provided

api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offerers/repository.py, api/tests/routes/pro/get_offerer_stats_v2_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26326
On veut compter comme offre publié les offres: Publiés, pré-réservées et réservées, pour les offres en attentes, on comptes les offres en statut en attente
Le OfferStatus dans le flux est calculé avec une hybrid property dans la table CollectiveOffer
=> (PC-26326) count published and pending collective offers

api/src/pcapi/connectors/big_query/queries/adage_playlists.py, api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/routes/adage_iframe/authentication.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/routes/adage_iframe/playlist_test.py
We want to filter more strongly on institution that are inside big cities where there are more offers than on country side.
Ticket Jira : https://passculture.atlassian.net/browse/PC-26524
=> (PC-26524)[ADAGE] fix: filter local offerers per density

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/tests/core/external/external_users_test.py, api/tests/routes/native/v1/account_test.py
User may receive transactional push notifications, which must use up-to-date information
Ticket Jira : https://passculture.atlassian.net/browse/PC-26499
=> (PC-26499)[API] fix: update Batch attributes even if marketing push is disabled

api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/routes/adage_iframe/playlist_test.py, pro/src/apiClient/adage/services/DefaultService.ts
Somehow this sliped through our reviews and ended with empty playlist on staging.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26548
=> (PC-26548)[ADAGE] fix: returns template offers for local adage playlist

api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/core/search/backends/base.py, api/src/pcapi/core/search/commands/indexation.py, api/tests/core/search/test_backend_algolia.py
Every night (and sometimes during the day), we have a surge of offers
that are reindexed, when stocks are synchronized by partners. Whenever
an offer must be reindexed, we request the reindexation of the
corresponding venue because it may start or stop to be eligible for
search. Since each venue usually have many offers to reindex, we
usually request the reindexation of the same venue multiple times.
Until 25d3e964f20aef819aa6c50d2c3266a0543cefd7, that was not an issue
because the venue indexation queue was stored as a Redis set. Now it's
stored as a list [*]. Thus, requesting the indexation of the same
venue multiple times fills up the queue with duplicate venue ids. And
the queue grows very, very large.
Until we find a solution (most probably by moving back from lists to
sets, see [*]), …
=> (PC-26551)[API] fix: Add `remove_duplicates_from_venue_indexation_queue` cronjob

api/src/pcapi/routes/pro/stocks.py, api/tests/routes/pro/post_stocks_test.py
Quand on update/edit un stock, si le stock existe déjà dans l'offre mais qu'on a une quantité différente, on ajoute cette quantité plutôt que de ne rien faire.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26246
=> (PC-26246)[API] feat: change quantity when updating existing stock

api/src/pcapi/scripts/provider/bulk_create_venue_provider.py
```
>>> test = [1, 2]
>>> set(test)
{1, 2}
>>> {test}
File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```
=> (BSR)[API] fix: cast list to set

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20231219T173827_faed981725fd_change_ban_id_to_text.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/serialization/base.py, api/tests/routes/pro/post_venue_test.py
Migration de la colonne banId dans Venue, comme la taille du ban Id est indéterminée, on utilise désormais un champ Text()
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26549
=> (PC-26549)[API] feat: migrate banId column from String to Text

api/src/pcapi/core/search/commands/indexation.py
Not strictly necessary, but the decorator provide automatic start and
end logs, which are nice to determine the duration of each occurrence
of the cronjob.
=> (BSR)[API] fix: Add missing decorator to indexation cronjobs

api/src/pcapi/core/educational/factories.py
Since it is added in the migration, that should not be also created in the sandbox unless it does not already exists.
Linked to commit 70cbd97
=> (BSR)[API] fix: don't create marseille en grand if it already exists

api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/backoffice/venues/forms.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25692
test en local : 
AVEC id : 
AVEC ids:
avec nom:
=> (PC-25692)[API] feat: backoffice allow searching ids or name of venue to filter venue in the action page

api/src/pcapi/core/search/__init__.py
We used python's tracemalloc profiler to track down our memory usage in this function Turns out loading 1_000 products can easily take 400M of memory. Tuning it down at 100 (40M) makes it much more managable for our cron job
We followed the doc here for the profiling: https://docs.python.org/3/library/tracemalloc.html#record-the-current-and-peak-size-of-all-traced-memory-blocks
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25834
=> (PC-25834)[API] fix: use less memory per batch in cron

api/src/pcapi/connectors/sirene.py, api/src/pcapi/core/offerers/tasks.py, api/tests/connectors/sirene_test.py, api/tests/core/offerers/test_commands.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25964
Lorsqu'on vérifie si les structure sont encore actives, vérifier aussi les structures non diffusibles
=> (PC-25964)[API] feat: also check non public SIREN when checking every active offerers

api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/pivots/contexts/cgr.py, api/src/pcapi/routes/backoffice/pivots/contexts/ems.py, api/src/pcapi/routes/backoffice/pivots/forms.py, api/src/pcapi/routes/backoffice/venues/blueprint.py
Les messages flash d'erreurs dans la backoffice sont tous en "warning" (couleur orange).
Cette PR homogénéise en changeant les quelques-uns restés en "error".
=> (BSR)[BO] chore: all flash messages in BO have 'warning' color

api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/get_events_test.py
New item added to the list of "clean offer table".
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26596
=> (PC-26596)[API] fix: return offers without showSubType

api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/tests/routes/public/individual_offers/v1/patch_event_test.py, api/tests/routes/public/individual_offers/v1/patch_product_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25032
Release product API now we know what we want to do.
There was problems with having a bulk creation/edition route. The payload can become really big in case images are uploaded, we also had a bad error management. If an error occurs after pydantic validation it would not be specific (the user don't know wich offer caused the error). 
Keep it simple until users complains.
=> (PC-25032)[API] fix: open api to new categories

.github/workflows/storybook.yml
Currently dependabot is not able to deploy [storybook](https://github.com/pass-culture/pass-culture-main/actions/runs/7337863246/job/19981100599). If we refers to this [section ](https://github.com/JamesIves/github-pages-deploy-action) we should allow content: write to let him deploy
=> (BSR) Add permission to allow dependabot to build storybook

api/rebuild_staging.sh
Reverts pass-culture/pass-culture-main#9638
la commande index_offers_staging prend beaucoup de temps, on revert le temps de fix le problem.
=> (BSR)[API] revert: stop runing index_offers_staging in rebuild_staging

api/src/pcapi/routes/serialization/offerers_serialize.py, pro/src/apiClient/v1/models/GetOffererVenueResponseModel.ts, pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageAdd/ButtonImageAdd.module.scss, pro/src/components/ImageUploader/ImageUploader.tsx, pro/src/components/VenueForm/ImageUploaderVenue/ImageUploaderVenue.tsx, pro/src/components/VenueForm/VenueForm.tsx, pro/src/pages/Home/Offerers/PartnerPage.module.scss, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/Venues/__specs__/Venue.spec.tsx, pro/src/pages/Home/Venues/__specs__/Venue.tracker.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26278
Derrière le FF WIP_PARTNER_PAGE, "Lieu non dit" est une structure avec un lieu permanent qui permet de voir le bloc pages partenaires
=> (PC-26278)[PRO] feat: V1 - Dans le bloc page partenaire, lorsque je clique sur l'image du lieu je peux en uploader une nouvelle

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/OfferInfos.tsx, pro/src/pages/AdageIframe/app/components/OffersFavorites/OffersFavoritesNoResult/OffersFavoritesNoResult.tsx, pro/src/pages/AdageIframe/app/components/OffersFavorites/__specs__/OffersFavorites.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/ModalFilterLayout/ModalFilterLayout.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/studentsOptions.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx, pro/src/pages/AdageIframe/app/constants.tsx, pro/src/pages/AdageIframe/app/providers/FacetFiltersContextProvider.tsx, pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26191
Si le FF : WIP_ENABLE_MARSEILLE est activé et que le compte sur lequel on est connecté appartient au programme de Marseille en Grand, on redirige vers la page de recherche au lieu de la page découverte et on pré-filtre le niveau scolaire sur les deux nouveaux niveaux
Pour tester : 
- aller sur adage en testing, choisir un directeur d'école à marseille, prendre son token et l'ajouter à la fin du lien généré dans la pr
=> Pc 26191 adage marseille redirect

.githooks/pre-push
In addition to the server-side branch protection, this hook prevents  admins from inadvertently pushing to master
=> (BSR) fix: pre-push git hook

pro/src/pages/Home/StatisticsDashboard/OfferStats.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/OfferStats.spec.tsx, pro/src/pages/Offers/domain/getOffersCountToDisplay.ts
Cf https://passcultureteam.slack.com/archives/C02BSV8DHU0/p1703856412196479
=> (BSR)[PRO] feat: display same offer count in stats as in offer list

api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offer_templates_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/collective_offers/forms.py, api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer/details.html, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html, api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/collective_offer_templates_test.py, api/tests/routes/backoffice/collective_offers_test.py
Replace them by formats.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26100
Suppression des filtres Catégories sur le backoffice : pages des offres collective et vitrines, ainsi que sur la page des réservations collectives.
Les tests ont en toute logique été mis à jour : les offres créées n'ont plus de sous-catégories, que des formats.
=> (PC-26100)[BO] feat: rm categories filters

api/tests/core/finance/test_api.py
This test failed when run at the beginning of the year, because the
"used date" of a collective was set to a few days before, possibly the
previous year. The calculated revenue of pricings would be wrong.
=> (BSR)[API] test: Fix flaky tests/core/finance/test_api.py::PriceEventTest::test_accrue_revenue

api/tests/routes/public/individual_offers/v1/patch_date_test.py, api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py
Flaky tests because a 18yo beneficiary from 01/01/2022 doesn't have anymore credit
=> (BSR)[API] fix: public api flaky tests

api/src/pcapi/core/categories/subcategories_v2.py
ean is required for LIVRE_AUDIO_PHYSIQUE but not for TELECHARGEMENT_MUSIQUE
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25032
=> (PC-25032)[API] fix: subcategories ean conditional_fields

pro/src/pages/Home/Offerers/PartnerPage.module.scss, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.module.scss, pro/src/pages/Home/VenueOfferSteps/VenueOfferSteps.tsx, pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.spec.tsx, pro/src/pages/Home/VenueOfferSteps/__specs__/VenueOfferSteps.tracker.spec.tsx, pro/src/pages/Home/Venues/Venue.tsx, pro/src/pages/Home/venueUtils.ts, pro/src/ui-kit/Button/Button.tsx, pro/src/ui-kit/Button/ButtonLink.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26279
Il n'y a pas de lieu permanent avec des next steps dans la sandbox (on a un ticket back pour changer la sandbox), ma reco est de checkout en local et manuellement changer un lieu qui a des next steps en permanent en settant isPermanent = true
=> (PC-26279)[PRO] feat: ajout des nouvelles étapes au bloc page partenaire

pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/VenuePlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/__specs__/VenuePlaylist.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26650
WIP_ENABLE_DISCOVERY
**Objectif**
Modifier les noms des playlists de la page découverte d'adage.
=> (PC-26650)[PRO] feat: Wording on adage discovery playlist names.

api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/templates/collective_offer/details.html, api/src/pcapi/routes/backoffice/templates/components/links.html, api/tests/routes/backoffice/collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26056
l'image de l'exemple ne montre pas l'enseignant car l'offre en question n'en a pas, cependant dans une utre offre on peut voir le nom et prenom de l'enseignant
=> (PC-26056)[API] feat: backoffice add information on collective offer

api/src/pcapi/core/external/attributes/api.py, api/src/pcapi/tasks/beamer_tasks.py, api/src/pcapi/tasks/sendinblue_tasks.py
The marketing team is ok to have 12 hours old data. It will greatly reduce our calls to Brevo and Beamer.
This will only impact pro attributes.
10 // 12 ->> 0
13 // 12 ->> 1
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26651
=> (PC-26651)[API] perf: bump beamer and brevo delay to 12 hours

.github/workflows/dev_on_push_workflow_main.yml
It's supposed to be run on feature branches only to warn when the
number of mypy's "type: ignore" comments increases in the related pull
requests.
=> (BSR)[API] ci: Do not run mypy-cop on master branch

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py, api/src/pcapi/routes/backoffice/bank_account/blueprint.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/users/blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/offerers_test.py
An exception was reported in production when offerer deletion was initiated one second after user_offerer soft deletion request: `Unexpected database error on method=POST url=https://backoffice.passculture.team/pro/offerer/34633/users/46617/delete: IntegrityError('(psycopg2.errors.ForeignKeyViolation) insert or update on table "action_history" violates foreign key constraint "action_history_offererId_fkey"\nDETAIL:  Key (offererId)=(34633) is not present in table "offerer".\n')`
So this commit ensures that concurrent actions on Offerer, Venue, User do not cause exception in the slowest. Not all potential exceptions are covered, but only these objects which have "Delete" button in BO.
Fix verified locally with temporary sleep() in user_offerer soft deletion request.
See: …
=> (PC-26662)[BO] fix: IntegrityError when object deletion is faster than another action

pro/src/components/Banner/OfferRefundWarning.tsx, pro/src/components/Banner/WithdrawalReminder.tsx, pro/src/components/IndividualOfferForm/Categories/Categories.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/UsefulInformations.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx, pro/src/ui-kit/InfoBox/InfoBox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24834
Enlever les aria-label indiquant "Nouvelle fenêtre" pour mettre ces informations dans le alt du svg 
(sur la page création d'offre)
=> (PC-24834)[PRO] fix: move new window info to svg alt

api/src/pcapi/connectors/big_query/testing_backend.py
with:
```
def foo():
yield
```
list(foo()) is [None] where an empty list was expected.
Corriger un plantage de backend de simulation BigQuery en environnement de développement
=> (BSR)[ADAGE] fix: returns empty results for the fake BigQuery backend

.github/workflows/dev_on_push_workflow_main.yml
Follow-up of 5eeac027859c1c4900c9369809, this time without the typo.
=> (BSR)[API] ci: Do not run mypy-cop on master branch (for real)

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240103T140021_b9f04189f351_remove_cashflow_foreign_key_bank_account.py, api/src/pcapi/alembic/versions/20240104T075421_71effb72345c_make_cashflow_bank_account_column_nullable.py, api/src/pcapi/core/finance/models.py, api/tests/core/finance/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26635
Étape 2/3 ([étape 1/3](https://github.com/pass-culture/pass-culture-main/pull/9847)) qui sera mergée après la MEP v272
=> (PC-26635)[API] [MERGE AFTER MEP v262] feat: Remove Cashflow.bankAccount foreign key

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240105T113037_2b2059710c60_delete_unused_stock_columns.py, api/src/pcapi/core/offers/models.py
Delete `numberOfTickets`, `educationalPriceDetail` and `rawProviderQuantity`  from `stock` table
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26731
=> (PC-26731)[API] fix: delete legacy columns from stock

pro/src/components/OfferEducationalActions/__specs__/OfferEducationalActions.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/__specs__/ClassroomPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOfferPlaylist/__specs__/NewOfferPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/__specs__/VenuePlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/__specs__/AdageDiscovery.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx, pro/src/pages/AdageIframe/app/components/SurveySatisfaction/__specs__/SurveySatisfaction.spec.tsx, pro/src/pages/CollectiveOfferFromRequest/__specs__/CollectiveOfferFromRequest.spec.tsx, pro/src/pages/CollectiveOfferStockCreation/__specs__/CollectiveOfferStockCreation.spec.tsx, pro/src/pages/OffererStats/__specs__/OffererStats.spec.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/DuplicateOfferCell/__specs__/DuplicateOfferCell.spec.tsx, pro/src/pages/Reimbursements/BankInformations/__specs__/LinkVenuesDialog.spec.tsx, pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx, pro/src/screens/CollectiveOfferVisibility/__specs__/CollectiveOfferVisibility.spec.tsx, pro/src/screens/OfferType/__specs__/OfferType.spec.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26749
**Objectif**
Corriger l'erreur de type dans les fichiers de tests au moment du mock du hook useNotification.
**A noter**
Problème du type retourné par `...vi.importActual('hooks/useNotification')` dans le cas d'un hook qui retourne un `useMemo`.
L'erreur est apparue entre la version v1.1.0 et v1.1.3 de vitest. J'ai ajouté un "as" pour forcer le type retourné par importActual. Et j'ai retiré les // ts-expect-error qu'on avait à certains autres endroits.
=> (PC-26749)[PRO] fix: Fix types when spying on usenotification.

pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/__specs__/OfferCard.spec.tsx
To be consistent with what's in the detailed offer page.
Ticket Jira : https://passculture.atlassian.net/browse/PC-26652
=> (PC-26652)[ADAGE] feat: display dist from user to offer's venue in playlists

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_venues.py, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx, pro/src/components/Callout/__specs__/LinkVenueCallout.spec.tsx, pro/src/components/RouteLeavingGuardCollectiveOfferCreation/__specs__/utils.spec.ts, pro/src/components/RouteLeavingGuardCollectiveOfferCreation/utils/index.ts, pro/src/pages/CollectiveOfferStockCreation/__specs__/CollectiveOfferStockCreation.spec.tsx, pro/src/pages/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx, pro/src/pages/CollectiveOfferSummaryCreation/__specs__/CollectiveOfferSummaryCreation.spec.tsx, pro/src/pages/CollectiveOfferVisibility/__specs__/CollectiveOfferCreationVisibility.spec.tsx, pro/src/pages/Reimbursements/BankInformations/__specs__/BankInformations.spec.tsx, pro/src/screens/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/screens/OfferEducational/useCollectiveOfferFromParams.tsx, pro/src/screens/Offers/RedirectToBankAccountDialog.tsx, pro/src/screens/Offers/__specs__/RedirectToBankAccountDialog.tracker.spec.tsx, pro/src/utils/apiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26068
- Afficher la pop in de redirection à la fin du parcours de création d'offres collectives.
- Activer le FF `WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY`
- Sélectionner la structure 'eac_with_no_offer' (relancer la sandbox pour générer cette structure)
- Créer une offre collective gratuite (prix = 0) -> la pop-in ne doit pas s'afficher
- Créer une offre collective payante (prix > 0) -> la pop-in devrait s'afficher
- Créer une deuxième offre collective payante -> la pop-in ne s'affiche plus
=> (PC-26068)[PRO] feat: Display redirect dialog after offer publishing.

pro/src/pages/Reimbursements/BankInformations/LinkVenuesDialog.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26604
Adjuster la taille de la pop-in de rattachement quand il y une bannière
=> (PC-26604)[PRO] fix: adjust heigt when dialog has banner

.github/dependabot.yml
- Dependabot ne doit plus rebase automatiquement chaque jour ou après chaque autre bump de depéndance: [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy)
- Dependabot peut ouvrir jusqu'à 15 PRs, pour tenir compte des PRs longues à merger
=> Edit dependabot options

api/src/pcapi/routes/backoffice/auth.py
J'ai reconstruit l'image docker du backend principal mais j'ai oublié de reconstruire l'image du backoffice.
Cette PR répare bien la connexion du backoffice pour authlib 1.3
=> (BSR)[BO] fix: authlib version bump breaking change

pro/src/components/IndividualOfferForm/utils/setInitialFormValues.ts, pro/src/context/IndividualOfferContext/IndividualOfferContext.tsx, pro/src/core/Offers/adapters/getIndividualOfferAdapter/__specs__/serializers.spec.ts, pro/src/core/Offers/adapters/getIndividualOfferAdapter/serializers.ts, pro/src/core/Offers/types.ts, pro/src/pages/IndividualOfferWizard/Confirmation/__specs__/Confirmation.spec.tsx, pro/src/pages/IndividualOfferWizard/Offer/__specs__/Offer.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.RouteLeavingGuard.spec.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.edition.spec.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/__specs__/serializer.spec.ts, pro/src/screens/IndividualOffer/SummaryScreen/SummaryScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/__specs__/SummaryScreen.spec.tsx, pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.tsx, pro/src/utils/individualApiFactories.ts
On enlève un champ qui est redondant avec `offer.venue.id`
Check fonctionnel : sur la création d'offre indiv, si on crée la 1ère offre payante sur une structure qui n'a pas de compte bancaire, on voit la modale qui propose de rediriger vers le compte bancaire s'afficher
=> (BSR)[PRO] refactor: remove venueId from IndividualOffer

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage/v1/serialization/prebooking.py, api/tests/routes/adage/v1/confirm_prebooking_test.py, api/tests/routes/adage/v1/conftest.py, api/tests/routes/adage/v1/get_all_bookings_per_year_test.py, api/tests/routes/adage/v1/get_educational_bookings_test.py, api/tests/routes/adage/v1/get_educational_institution_test.py, api/tests/routes/adage/v1/get_prebookings_test.py, api/tests/routes/adage/v1/refuse_prebookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25882 
api adage (v1)
ajout de deux informations aux réponses des routes concernant les pré-réservations : 1. identifiant du lieu et 2. nom de la structure.
Amélioration et factorisations de fonctions qui vont chercher des réservations en base de données.
Factorisation de code de test : ajout (principalement) de fonctions qui permettent de générer le `dict` attendu dans la réponse. Cela évite d'avoir plein de fois le même objet dans plein de fichier de tests différents. Cela permettra à l'avenir de n'avoir à mettre à jour qu'un fonction de test, au lieu d'aller chercher toutes les fonctions de tests qui vérifient en détail le JSON de la réponse.
=> PC 25882 adage add venue ids offerer name

.github/workflows/dev_on_push_workflow_main.yml
Amélioration du workflow `dev_on_push_workflow_main`
- modification de la syntaxe de `concurrency` globale cf [cette syntaxe de SO](https://stackoverflow.com/a/75403978)
- ajout d'une `concurrency` au niveau du job `deploy-to-testing`
Ainsi, chaque push sur une branche de PR annulera le workflow en cours, mais sur `master` et `maint/*` , un job `deploy-to-testing` pourra finir de s'exécuter et le plus récent en date sera préservé.
Doc GHA sur `concurrency`: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Impacts:
- Lors des merges, les tests d'un workflow en cours ne seront plus annulés
- Les déploiements sur testing ne seront pas annulés si un 2e workflow est démarré, et le déploiement sera mis en attente.
Si un 3e est démarré, le premier …
=> (BSR) ci: improve GHA concurrency syntax

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/sonar-project.properties, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/TrackingShowMoreBody.ts, pro/src/apiClient/adage/services/DefaultService.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26362
Ajouter une route de tracking pour pouvoir l'utiliser côté front sur le bouton "Voir plus" sur adage
=> (PC-26362)[API] feat: add route tracking search adage button show more

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/tasks.py, api/src/pcapi/core/permissions/api.py, api/src/pcapi/core/providers/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/email/update.py, api/src/pcapi/local_providers/provider_manager.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/admin/bo_users_blueprint.py, api/src/pcapi/routes/backoffice/bank_account/blueprint.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/fraud/blueprint.py, api/src/pcapi/routes/backoffice/offer_validation_rules/blueprint.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/providers/blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/pro/users.py, api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/core/history/test_api.py, api/tests/core/offerers/test_api.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/venues_test.py
Refactor de la fonction `log_action` pour en faire une fonction qui ajoute une action dans la table `ActionHistory` sans faire de commit par défaut. Ce qui pousse à faire un `db.session.commit()` en dehors de la fonction pour être sûr qu'on enregistre tous les objets dans la même transaction et éviter d'avoir des incohérences dans l'historique. 
Ticket Jira : https://passculture.atlassian.net/browse/PC-26763
=> (PC-26763)[API] chore: log_action refactoring

api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/src/pcapi/routes/backoffice/templates/venue/get.html
Ajout de liens vers les pages "Offres" et "Offres individuelles" dans les pages "Acteurs culturels" et "Lieux".
Ticket Jira : https://passculture.atlassian.net/browse/PC-25360
- Acteurs culturels :
- Lieux :
=> (PC-25360)[BO] feat: add links to related offers in offerer and venue pages

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240109T104132_65a8910cf1db_no_partial_collective_incident.py, api/src/pcapi/core/finance/factories.py, api/src/pcapi/core/finance/models.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_models.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-25094
- recrédit d'un établissement scolaire après validation d'un incident (total) sur une offre collective
- renforcement de la contrainte : le métier n'autorise pas d'incident partiel sur une offre collective
=> (PC-25094)[API] test: recredit educational institution after collective incident

.github/workflows/dev_on_push_workflow_main.yml
Le job update api client doit être lancé aussi quand les dépendances front changent : si `openapi-typescript-codegen` est mis à jour, cela peut casser le schéma d'API et on doit le vérifier.
[cf discussion sur Slack](https://passcultureteam.slack.com/archives/CPZ7U1CNP/p1704874588259529)
=> (BSR)[PRO] ci: trigger api client job when frontend deps change

.github/workflows/dev_on_workflow_ping_data_team.yml
Version 2 has a fix that trims the URL of the pull request. Otherwise
it contains a trailing trailing newline character. When the "Slack
notification" step includes it, it generates an invalid JSON payload.
---
Ça corrige le workflow GitHub "ping_data_team". Exemple de run où l'on voit l'erreur : https://github.com/pass-culture/pass-culture-main/actions/runs/7474653749/job/20341281390
Je ne sais pas tester la correction, mais ça ne devrait pas être pire que l'état actuel. :)
=> (BSR)[API] ci: Bump version of "kceb/pull-request-url-action" GitHub action

api/src/pcapi/core/offers/repository.py, api/src/pcapi/infrastructure/repository/pro_offers/offers_recap_domain_converter.py, api/tests/core/offers/test_repository.py
first commit : only load used columns. See next screenshot, left is before.
For this user 1173909 (soculture) on staging in went from 4.5s to 0.7 . I'm afraid it will hide some n+1 queries. Before merging i want to know how i can track this on .. sentry?
=> (PC-26788)[API] perf : improve pro list offers search

api/tests/utils/pdf_creation_test.py
We will soon upgrade to a recent version of Weasyprint. Starting from
Weasyprint 59.0, metadata does not appear in clear in the generated
PDF file anymore. It could be because of optimizations that were
shipped in that version, or some other reason. Anyway, our tests
cannot easily check that the metadata is included in a generated PDF
file. We would have to parse the PDF, and we don't want to. We don't
do anything complicated with our PDF metadata, so we can rely on
Weasyprint to correctly handle metadata (which it does) and not have
any specific test.
Also, the test was flaky: we look for the startup time (with second
precision) of the test in the generated PDF. If it took too much
time (or if we were just unlucky enough that the generation spanned
over 2 seconds), the creation and/or …
=> (BSR)[API] test: Remove test of PDF metadata

pro/src/pages/Bookings/NoBookingsForPreFiltersMessage/NoBookingsForPreFiltersMessage.tsx, pro/src/pages/Bookings/__specs__/BookingsRecap.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26492
Changer le wording du CTA “Réinitialiser les filtres” pour “Afficher toutes les réservations”
Branche: PC-26492-wording-reservation-cta2
=> (PC-26492)[PRO] style: wording de récap de no réservation

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/offers/forms.py, api/src/pcapi/utils/regions.py, api/tests/routes/backoffice/offers_test.py
Ajout du champ "Région" dans la liste des filtres de la recherche avancée dans la page "Offres individuelles"
Ticket Jira : https://passculture.atlassian.net/browse/PC-26814
=> (PC-26814)[BO] feat: add 'region' to advanced filters in offer page

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240110T153011_f0fbdcf9961d_delete_wip_enable_dates_offers_template_ff.py, api/src/pcapi/models/feature.py, pro/src/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx, pro/src/components/CollectiveOfferSummary/__specs__/CollectiveOfferSummary.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferSummary/OfferSummary.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferSummary/__specs__/OfferSummary.spec.tsx, pro/src/screens/OfferEducational/OfferEducational.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/__specs__/FormDates.spec.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/__specs__/OfferEducationalForm.spec.tsx, pro/src/screens/OfferEducational/validationSchema.ts, pro/src/screens/OfferType/CollectiveOfferType/CollectiveOfferType.tsx, pro/src/screens/OfferType/__specs__/OfferType.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26826
**Objectif**
Supprimer le FF qui affiche quand il est actif la section dates dans le formulaire d'une offre vitrine
=> (PC-26826)[PRO] feat: Delete WIP_ENABLE_DATES_OFFER_TEMPLATE FF

api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/api/favorites.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/api/stock.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/core/search/commands/indexation.py, api/src/pcapi/routes/adage_iframe/offers.py, api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/sandboxes/scripts/creators/data/create_data_search_objects.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_search_objects.py, api/src/pcapi/scripts/full_index_collective_offers.py, api/tests/core/educational/api/test_favorites.py, api/tests/core/educational/test_api.py, api/tests/core/search/test_backend_algolia.py, api/tests/core/search/test_commands_indexation.py, api/tests/core/search/test_serialize_algolia.py, api/tests/routes/adage_iframe/get_all_offers_linked_to_uai_test.py, api/tests/routes/adage_iframe/get_authenticate_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26353
La PR initiale désactivait l'indexation des offres collectives réservables mais, ce faisant, l'onglet "dans mon établissement", qui utilise l'indexation, ne marche plus.
PR initiale: https://github.com/pass-culture/pass-culture-main/pull/9899
=> revert [PC-26353] do not index collective offers anymore

api/src/pcapi/connectors/serialization/titelive_serializers.py, api/src/pcapi/connectors/titelive.py, api/src/pcapi/core/providers/titelive_api.py, api/src/pcapi/scheduled_tasks/titelive_commands.py, api/tests/providers/titelive_search_test.py
Faciliter le rattrapage de la synchro Titelive musique et acceptation d'un nouveau champ nullable
=> (BSR)[API] fix: make titelive music sync more robust

.github/workflows/dev_on_push_workflow_main.yml
S'assurer que les concurrency groups sont bien distincts, car GHA ne prévient pas en cas de conflit.
Seul une interrogation via API permet de le remarquer
```
➜ gh run view 7476235346
* dbaty/fix_ping_data_gh_action 1 [on_push] Initiate workflow #10127 · 7476235346
Triggered via pull_request about 20 hours ago
JOBS
X Check api folder changes / Check folder changes in 0s (ID 20346159045)
X Check db migration folder changes / Check folder changes in 0s (ID 20346159457)
X Check maintenance-site folder changes / Check folder changes in 0s (ID 20346159954)
X Check pro folder changes / Check folder changes in 0s (ID 20346160358)
X Reset cache on master on dependency update / Update API Client template in 0s (ID 20346160652)
* Update Jira issue / issue-number (ID 20346161028)
X Update api client …
```
=> (BSR)[API] ci: edit concurrency group namings

api/src/pcapi/routes/adage_iframe/serialization/venues.py, api/tests/routes/adage_iframe/get_venue_by_id_test.py, api/tests/routes/adage_iframe/get_venue_by_siret_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26689
Ajout d'un champ adageId à la route `/adage-iframe/venues/{venue_id}`.
=> (PC-26689)[EAC] feat: adage iframe: add adageId to /venues route

api/src/pcapi/core/users/api.py, api/tests/core/users/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26897
1) Un code absent ne peut pas causer de bugs
2) le cas n'est plus possible a créer avec le schéma de db actuel (le champ updatedAt est toujours remplis en pratique)
3) l'anonymisation de ce champ est inutile puisqu'il portera TOUJOURS la date de l'anonymisation qui ne permet pas de ré identifier le jeune.
=> (PC-26897)[API] fix: error when updating a beneficiary_fraud_check which was never touched

api/src/pcapi/backoffice_app.py, api/src/pcapi/core/permissions/api.py, api/src/pcapi/core/testing.py, api/src/pcapi/flask_app.py, api/src/pcapi/repository/__init__.py, api/src/pcapi/repository/repository.py, api/src/pcapi/routes/backoffice/admin/blueprint.py, api/src/pcapi/routes/error_handlers/bookings_error_handlers.py, api/src/pcapi/routes/error_handlers/generic_error_handlers.py, api/src/pcapi/routes/error_handlers/thumbnails_error_handlers.py, api/tests/conftest.py, api/tests/repository/test_transaction.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23753
Le but est d'avoir un système de gestion des transactions pour faire correspondre au cycle de vie d'une requête http.
```python
@public_api.route("/check/transactions", methods=["POST"])
@repository.transaction()
def check_transactions():
import uuid
from flask import request
from pcapi.core.users.models import UserSession
from pcapi.repository import repository
s = UserSession()
s.userId = 1
s.uuid = uuid.uuid4()
repository.save(s, commit=False)
if "raise" in request.args:
raise ValueError("an horrible error occurs, let's rollback, shall we?")
return "OK", 200
```
Actuellement, un appel `POST /check/transaction?raise=3` commit quand même le `UserSession` alors qu'il devrait rollback
Réecrire le …
=> (PC-23753)[API] feat: make @transaction() transactional

pro/src/components/Callout/AddBankAccountCallout.tsx, pro/src/components/Callout/__specs__/AddBankAccountCallout.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26875
- Ne pas afficher la bannière si un compte en banque est en attente de validation.
=> (PC-26875)[PRO] feat: Do not display the banner if pending bank account.

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/offers/api.py, api/tests/core/finance/test_api.py
Also, the name of the function should make its intent clearer than its
code for callers that don't need to know the details.
=> (BSR)[API] refactor: Add `force_event_repricing()` to avoid call to private function

pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26827
La barre de scroll s'affichait directement à la fin de l'élément le plus long de la liste, on change pour qu'il soit au fond de la div quelque soit l'élément 
Avant : 
Après :
=> (PC-26827)[PRO] fix: checkbox filter adage width

api/src/pcapi/core/history/models.py, api/src/pcapi/core/mails/transactional/finance_incidents/finance_incident_notification.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/general.html, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24841
:warning: Le mail concerne à chaque fois une offre de l'incident, si ce dernier porte sur 3 offres alors 3 mails seront envoyés à l'acteur :warning: 
Nous avons soumis l'idée de lister ces offres dans un seul mail, Nine étudie cette possibilité
Aussi le template fait mention de l'annulation d'un événement, il ne concerne donc pour l'instant que les trop perçus totaux
Ajout du bouton sur la note de débit (annulation ou activation)
Envoi de mail conditionnel
=> (PC-24841)[BO] feat: Force debit note button

pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/Offerers/__specs__/OffererDetails.spec.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24554
Remplacer `Sélectionner la structure` par `Structure` dans le aria-label de sélection d'une strcutrue de la page d'accueil. En effet inutile de repriser dans le aria-label la nature du champs HTML
=> (PC-24554)[PRO] fix: remove unecessary select in aria label

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26674
Lorsque l'établissement fait partie de Marseille en grand, il y a deux nouvelles valeurs dans le filtre Niveau scolaire, que l'on trie pour afficher sa de la petite classe à la plus grande (primaire -> cap 2eme année), lorsqu'on sélectionne une classe elle se retrouve tout en haut de la liste mais lorsqu'on la décoche et qu'on ferme la modal de filtre, elle doit reprendre sa place initial, ce n'était plus le cas car on modifiait directement l'objet des niveaux scolaire
=> (PC-26674)[PRO] fix: sort studentLevel when MeG activated

api/src/pcapi/connectors/titelive.py, api/tests/connectors/titelive/titelive_test.py
Products created by a provider should have a lastProviderId set
Since the product table is messy our apis filters products with a lastProvider not null to create offers. Theses whitelisted products could not be used.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26932
To fix data after deployment of this fix we could run (id=9 is generic titelive provider) : 
```
staging> select count(*) from product_whitelist
+-------+
| count |
|-------|
| 52    |
+-------+
SELECT 1
Time: 0.008s
select count(*) from product where "idAtProviders" is not null and "lastProviderId" is null and "jsonData"->>'ean' in (select ean from product_whitelist);
+-------+
| count |
|-------|
| 52    |
+-------+
SELECT 1
Time: 0.013s
staging> update product set "lastProviderId"=9 …
```
=> (PC-26932)[API] fix: link product to provider from backoffice

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/patch_collective_offer_template_test.py
This will enable permanent collective offers templates.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26929
=> (PC-26929)[API] feat: allow empty dates for collective offer templates

pro/src/pages/Bookings/NoBookingsForPreFiltersMessage/NoBookingsForPreFiltersMessage.tsx, pro/src/pages/Bookings/__specs__/BookingsRecap.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26492
Revue UI : Le wording du CTA sur l’onglet réservation des pages offres est toujours “Réinitialiser les filtres” et non “Afficher toutes les réservations”
Branche: PC-26492-wording-reservation-cta3
=> (PC-26492)[PRO] style: wording de noreservations

pro/src/components/CollectiveOfferSummary/components/CollectiveOfferDateSection/CollectiveOfferDateSection.tsx, pro/src/components/CollectiveOfferSummary/components/CollectiveOfferDateSection/__specs__/CollectiveOfferDateSection.spec.tsx, pro/src/core/OfferEducational/constants.ts, pro/src/core/OfferEducational/types.ts, pro/src/core/OfferEducational/utils/__specs__/createOfferPayload.spec.ts, pro/src/core/OfferEducational/utils/computeInitialValuesFromOffer.ts, pro/src/core/OfferEducational/utils/createOfferPayload.ts, pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferSummary/OfferSummary.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferSummary/__specs__/OfferSummary.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/OffersInstantSearch.spec.tsx, pro/src/pages/CollectiveOfferEdition/utils/__specs__/createPatchOfferPayload.spec.ts, pro/src/pages/CollectiveOfferEdition/utils/createPatchOfferPayload.ts, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/FormDates.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/__specs__/FormDates.spec.tsx, pro/src/screens/OfferEducational/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26198
**Objectif**
Dans le formulaire d'une offre vitrine collective, ajouter un radio button pour choisir si l'offre est permanente (pas de dates) ou si elle a des dates précises (fonctionnement actuel). Aussi adaptation du text dans le résumé d'une offre et dans adage pour les offres permanentes.
**A vérifier**
- Créer une offre vitrine collective : voir le radio button par défaut sur "permanente" - l'offre est valide quand soit elle est permanente soit elle a des dates inscrites
- Update une offre vitrine colelctive qui a des dates : le radio button est par défaut sur les dates
- Update une offre vitrine colelctive qui est permanente : le radio button est par défaut sur "permanente"
- Après création d'une …
=> Pc 26198 template offer no dates

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26864
- Le ff `WIP_ENABLE_PRO_SIDE_NAV` est créé pour la nouvelle navigation latérale.
=> (PC-26864)[API] feat: Create the new `WIP_ENABLE_PRO_SIDE_NAV` FF.

api/src/pcapi/core/offerers/models.py
BSR: on ne va finalement pas rendre la colonne banId non nullable (car il existe des lieux permanents non virtuels qui n'ont pas de banId , par exemple ceux situés à st-pierre et miquelon )
=> (BSR)[API] refactor: remove fixme that has been abandonned

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240108T101350_232786daf672_add_rurality_level_to_institution.py, api/src/pcapi/connectors/big_query/queries/adage_playlists.py, api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/core/educational/commands.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/adage_iframe/authentication.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/core/educational/test_api.py, api/tests/routes/adage_iframe/get_authenticate_test.py
In order to cut costs, we do store the institution rurality level within the database instead of using BigQuery for that.
=> (PC-26658)[API] feat: don't use BigQuery to get the institution rurality level

api/src/pcapi/core/external/batch.py, api/src/pcapi/core/mails/transactional/users/ubble/reminder_emails.py, api/src/pcapi/notifications/push/__init__.py, api/src/pcapi/notifications/push/backends/batch.py, api/src/pcapi/notifications/push/backends/logger.py, api/src/pcapi/notifications/push/backends/testing.py, api/src/pcapi/tasks/batch_tasks.py, api/tests/core/mails/transactional/users/ubble_ko_reminder_test.py
Il existe un délai après un KO Ubble après lequel l'utilisateur reçoit une notification Batch. Ce délai étant actuellement géré par le backend **et** par l'interface web Batch, celui du backend est inutile.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24894
=> (PC-24894)[API] fix: remove bulk Batch event tracking

pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.module.scss, pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.tsx, pro/src/components/CollectiveOfferLayout/__specs__/CollectiveOfferLayout.spec.tsx, pro/src/pages/CollectiveOfferCreation/__specs__/CollectiveOfferCreation.spec.tsx, pro/src/pages/CollectiveOfferStockCreation/__specs__/CollectiveOfferStockCreation.spec.tsx, pro/src/pages/CollectiveOfferSummaryCreation/__specs__/CollectiveOfferSummaryCreation.spec.tsx, pro/src/pages/CollectiveOfferVisibility/__specs__/CollectiveOfferCreationVisibility.spec.tsx, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.module.scss, pro/src/screens/IndividualOffer/IndivualOfferLayout/IndivualOfferLayout.tsx, pro/src/screens/IndividualOffer/IndivualOfferLayout/__specs__/IndivualOfferLayout.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26976
Avec le plugin HeadingsMap, vérifier que le nom de l’offre est bien inclus dans le titre de niveau 1, sur les parcours de création et de modification d’offre collective et individuelle
Au niveau graphique l'affichage devrait être iso
=> (PC-26976)[PRO] fix: title hierarchy - move offer name into h1

api/src/pcapi/routes/pro/collective_offers.py, api/src/pcapi/routes/serialization/educational_redactors.py, pro/src/apiClient/v1/models/EducationalRedactor.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26468
Fix : le champ `gender` (`civilite`) n'est optionnel. Il s'agissait d'une erreur de documentation : dans la pratique, cette information peut être nulle.
=> (PC-26468)[EAC] fix: adage: gender ("civilite") can be null

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/models/PlaylistBody.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26712
Ajout d'un champ `index` (optionnel par soucis de rétrocompatibilité).
=> (PC-26712)[EAC] feat: adage iframe logs: add index field

pro/src/pages/Offerers/OffererCreation/OffererCreation.tsx, pro/src/pages/Offerers/OffererCreation/__specs__/OffererCreation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26962
Empêcher l'utilisateur de soumettre plusieurs fois le formulaire de création de structure. 
Solution tech : disable le bouton pendant l'appel API à la route de création
Screen
=> (PC-26962)fix: prevent user to submit offerer creation multiple times

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Miroring `generate_reimbursement_points_file` of the old journey, considering slight changes
asked by the accounting department
Other tests cover that part of the code (ones about `generate_payment_files`)
however they're about larger feature and includes calls to `generate_cashflows`
which is not yet handle in the new journey. Thoses tests will ported to the new
journey at the same time than `generate_cashflows`
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26400
=> (PC-26400)[API] feat: Make `generate_bank_accounts_file` for the new Bank Account journey

pro/package.json, pro/src/components/ReimbursementBankAccount/__specs__/ReimbursementBankAccount.spec.tsx, pro/src/components/VenueForm/CollectiveVenueInformations/CollectiveDmsTimeline/__specs__/CollectiveDmsTimeline.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/__specs__/ClassroomPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOfferPlaylist/__specs__/NewOfferPlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/VenuePlaylist/__specs__/VenuePlaylist.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/__specs__/AdageDiscovery.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26946
**Objectif**
Upgrade de happy-dom qui a une nouvelle version majeure. Suppression des utilisations de happy-dom qui semblent inutiles, et màj des `location.pathname` qui ont maintenant la valeur correspondant au Router.
=> (PC-26946)[PRO] feat: Upgrade happy-dom.

api/src/pcapi/core/educational/api/institution.py, api/src/pcapi/routes/adage_iframe/authentication.py, api/src/pcapi/routes/adage_iframe/offers.py, api/src/pcapi/routes/adage_iframe/serialization/adage_authentication.py, api/tests/routes/adage_iframe/get_collective_offers_for_my_institution.py, pro/src/apiClient/adage/services/DefaultService.ts
This API will make it possible to get rid of the use of Algolia to list the offers made for a given institution.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26920
=> (PC-26920)[ADAGE] feat: add API to get collective offers for institution

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240117T111957_fc7dd42a29ac_add_index_on_booking_cancellation_reason.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/tests/routes/backoffice/individual_bookings_test.py
- Ajout d'un index sur la colonne `cancellationReason` de la table `booking`
- Ajout d'un filtre `Raison d'annulation` dans la page `Réservations individuelles` : 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26795
=> (PC-26795)[BO] feat: all 'cancellation reason' filter to individual bookings page

pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.module.scss, pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/__specs__/OffersForMyInstitution.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26925
**Objectif**
Replacer l'appel à algolia dans la page Mon établissement d'adage par un appel à la nouvelle api backend qui renvoit directement la liste des offres concernées.
=> (PC-26925)[PRO] feat: Use api to get adage offers for my institution.

api/src/pcapi/alembic/run_migrations.py
Toujours renvoyer un exit code différent de 0 en cas d'échec des migrations.
Testé avec une migration incluant
```python
def upgrade() -> None:
raise OperationalError("", None, None)
```
```shell
➜ alembic upgrade post@head
WARNI [pcapi.alembic.run_migrations] Alembic will use a DB connection with these settings: lock_timeout = 5000 ms, statement_timeout = 60000 ms
WARNI [pcapi.alembic.run_migrations] Running migrations: attempt 1/1
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade fadf7f6f4c60 -> f21a18bd0d27, test
WARNI [pcapi.alembic.run_migrations] OperationalError: None
WARNI [pcapi.alembic.run_migrations] [SQL: ]
FAILURE: Migrations failed to be run.
➜ echo …
```
=> (BSR)[API] feat: exit with a non-zero code if alembic upgrade fails

api/src/pcapi/routes/backoffice/offers/blueprint.py
With distinct, query nevers returns when called in staging console:
SELECT DISTINCT offer.id AS id
FROM offer
WHERE (offer."jsonData" ->> 'showSubType') IN ('105')
LIMIT 100;
Without distinct, results are returned in 55 ms:
SELECT offer.id AS id
FROM offer
WHERE (offer."jsonData" ->> 'showSubType') IN ('105')
LIMIT 100;
Suite au test du Ticket Jira sur staging : https://passculture.atlassian.net/browse/PC-25819
=> (PC-25819)[BO] fix: timeout when searching for offers

pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPageCollectiveSection.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26975
un cas n'était pas bon : le dossier dms peut être accepté MAIS l'acteur n'a pas encore d'adage id et ne peut donc pas encore créer d'offres collective : dans ce cas on veut afficher le bloc "en cours de référencement"
+ séparation des tests pour que ça soit plus clair
=> (PC-26975)[PRO] fix: eac case for partner bloc in home

.github/workflows/dev_on_workflow_deploy.yml, .github/workflows/templates/post-upgrade-job.yaml, .github/workflows/templates/pre-upgrade-job.yaml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27154
Use jobs native retry to avoid running two jobs for playing migrations
=> (PC-27154) fix(ci): remove retry for pre and post migration but had job retry

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240122T164604_5da6795c25fa_make_accessibilityprovider_venueid_and_externalaccessibilityproviderid_unique.py, api/src/pcapi/core/offerers/models.py
Comme cette table (AccessibilityProvider) est nouvelle, inutilisée et vide je me suis permis de me passer de l'ajout d'un index CONCURRENTLY
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27515
=> (PC-27515)[API] feat: add unicity to AccessibilityProvider ID and VenueId

api/src/pcapi/core/search/__init__.py
We did not pass `from_error_queue` to `reindex_offer_ids()`, which
caused `_log_indexation_error()` to always log at the INFO level.
However, we want to log at the ERROR (exception) level when processing
the error queue.
=> (BSR)[API] fix: Fix log level of offer indexation errors for error queue

api/bin/pgcli-wrapper.sh, api/etc/pgcli.ini
3 commits, à relire séparément :
- ajout d'un fichier de configuration minimal (pour éviter
l'avertissement relatif à "keyring" qui apparaît au démarrage de
pgcli depuis qu'on est passé à Poetry).
- déplacement des options définies dans "pgcli-wrapper.sh"
- configuration de pgcli pour rejeter les requêtes "destructives"
(`insert`, `delete`, `update`, `alter table`, etc.) si une
transaction n'est pas en cours.
Cf. messages de commit pour plus de détails.
=> (BSR)[API] Ajout d'un fichier de configuration pour pgcli

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25654
Fix: les bannières offerer ne s'affichent plus quand la structure est en cours de rattachement
=> (PC-25654)[PRO] fix: error for offerer banner in homepage

api/src/pcapi/notifications/sms/__init__.py, api/src/pcapi/notifications/sms/backends/logger.py, api/src/pcapi/notifications/sms/backends/sendinblue.py, api/src/pcapi/notifications/sms/backends/testing.py
It's always True and, actually, never used.
See 5b7bfb6c6f854b15c895bacb3a5 for a similar changes for mails.
=> (BSR)[API] refactor: Remove return value of `send_transactional_sms`

api/src/pcapi/core/finance/api.py, api/src/pcapi/templates/invoices/invoice.html, api/tests/core/finance/test_api.py, api/tests/files/invoice/rendered_invoice.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26537
- Ajout de deux colonnes manquantes concernant les incidents de finance dans le justificatif de remboursement.
- Ajout d'un incident collectif dans les tests
=> (PC-26537)[API] fix: add missing incident columns in invoice file

api/etc/pgcli.ini
Enregistrer une named query dans la config pgcli afin de trouver les transactions longues.
On l'invoque ainsi: `\n long_transactions`
(@xordoquy a la paternité de la syntaxe de la requête)
=> (BSR)[API] feat: add named query to find long-running SQL transactions

pro/src/components/Breadcrumb/Breadcrumb.module.scss, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27170
**Objectif**
S'assurer que les boutons des offres ne sortent pas de l'écran jusqu'à 320px. Et s'assurer que tous les liens de la navbar sont visibles jusqu'à 320px.
=> Pc 27170 adage responsive small screen

pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferSummary/components/CollectiveOfferTypeSection/CollectiveOfferTypeSection.tsx, pro/src/components/OfferEducationalActions/OfferEducationalActions.module.scss, pro/src/screens/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormVenue/FormVenue.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx, pro/src/screens/OfferEducational/__specs__/OfferEducationalCreationOffererStep.spec.tsx, pro/src/screens/OfferEducational/__specs__/OfferEducationalEdition.spec.tsx, pro/src/screens/OfferEducational/__specs__/OfferEducationalEventAddressStep.spec.tsx, pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx, pro/src/ui-kit/Tabs/Tabs.tsx, pro/src/ui-kit/form/CheckboxGroup/CheckboxGroup.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26241
Changement ux ui sur les pages de création et d'édition d'une offre vitrine ou réservable
- Retirer le Tabs "Détails de l'offre" pour une offre vitrine
- Ajouter une partie Informations artistiques
- Changement du wording de la barre d'action "Enregistrer" > "Enregistrer les modifications"
- Réduire la zone de clic des checkbox
=> (PC-26241)[PRO] fix: uxui creation edition eac offer

pro/.stylelintrc.json, pro/src/components/SkipLinks/SkipLinks.module.scss, pro/src/styles/variables/_size.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25784
**Objectif**
Rendre la outline du focus des skiplink visible. Elle était noir sur bleu marine et je l'ai mise en blanc 👍 
**A noter**
J'ai aussi retiré la règle `scss/operator-no-newline-after` qui est en conflit avec la longueur maximale des lignes définie par prettier. Cette règle semble concerner des cas assez marginaux : https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/operator-no-newline-after/README.md
=> (PC-25784)[PRO] style: Make skiplink outline visible.

.github/workflows/dev_on_workflow_check_folder_changes.yml
Deleted files were ignored. For example, when a file in "api/" was
deleted, tests were not executed. We would like to execute tests when
files are deleted.
As per the docs (https://github.com/tj-actions/changed-files#outputs-):
any_changed: includes a combination of all added, copied, modified
and renamed files (ACMR)
any_modified: includes a combination of all added, copied,
modified, renamed, and deleted files (ACMRD).
=> (BSR)[API] fix: Detect deleted files in `check_folder_changes` workflow

pro/src/components/SkipLinks/SkipLinks.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27587
**Objectif**
Après mes dernières modifs de clean de style sur les liens d'évitement, le lien apparait toujours visible sur la page d'accueil. Ce commit corrige la position du menu d'évitement.
=> (PC-27587)[PRO] fix: Skiplink is always visible on home page.

pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27040
Quand on changeait de lieu sur la home pour le bloc page partenaire, l'image n'était pas mise à jour
pour tester: 
- activer WIP_PARTNER_PAGE
- mettre ses lieu en isPermanent = true
=> (PC-27040)[PRO] fix: image do not change with venue in PartnerPage in Home

api/src/pcapi/connectors/big_query/queries/__init__.py, api/src/pcapi/connectors/big_query/queries/adage_playlists.py, api/src/pcapi/core/educational/api/playlists.py, api/src/pcapi/core/educational/commands.py, api/src/pcapi/core/educational/factories.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/core/educational/api/test_playlists.py, api/tests/routes/adage_iframe/playlist_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26958
Ne plus faire appel à BQ à chaque requête d'une des _playlist_ Adage (page de découverte).
Une précédente PR avait mis en place tout le nécessaire et celle-ci la complète en ajoutant la synchronisation des données pour les _playlists_ des nouvelles offres et des lieux à proximité. Les deux routes qui faisaient appel à BQ vont maintenant chercher les données dans notre base.
=> (PC-26958)[EAC] feat: synchronize two playlists data

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/serialization/reimbursement_csv_serialize.py, api/tests/routes/backoffice/venues_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26335
Adaptation du fichier "details des remboursements" téléchargeable sur la page d'un lieu.
=> (PC-26335)[BO] feat: Add finance incident to reimbursement details csv

api/.env.integration, api/.env.production, api/src/pcapi/routes/internal/testing.py, api/tests/routes/internal/testing_test.py, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27004
Pour permettre les test e2e pour l'_iframe_ adage, le client front aura besoin d'un token adage valide. Cette PR ajoute une route qui en renvoie un et qui n'est accessible que si le FF `ENABLE_TEST_ROUTES` est activé.
=> (PC-27004)[EAC] feat: e2e route: get adage (fake) token

api/src/pcapi/routes/backoffice/templates/components/forms/search_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/select_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/select_with_placeholder_value_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/string_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/textarea_field.html
- Les champs "required" définis dans les formulaires Flasks n'empêchaient pas le submit du formulaire.
=> (BSR)[BO] fix: prevent form submit when required fields

api/src/pcapi/utils/human_ids.py, api/tests/utils/human_ids_test.py
Passing garbage to `dehumanize()` could raise unhandled exceptions. I
managed to generate a UnicodeDecodeError, but I am sure we can
generate other exceptions. Catching a generic exception is the best
defense.
---
Erreur vue dans le back-office : https://sentry.passculture.team/organizations/sentry/issues/1257360/
=> (BSR)[API] fix: Handle garbage in `human_ids.dehumanize()`

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
And removing SIRET column, because it doesn't make sense in the new bank account journey context, since a bank account can be link to multiples venues and thus sirets.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26400
=> (PC-26400)[API] feat: Add offerer SIREN column in bank accounts files

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/tests/core/offers/test_api.py
Remove a check that was executed once by offer to create and could takes up to 3/4 of execution time (see the autogrouped queries [here](https://sentry.passculture.team/organizations/sentry/performance/api:a5d1c196a8914071b4aa0a34f851d468/?environment=production&project=5&query=transaction.duration%3A%3C15m&statsPeriod=90d&transaction=pcapi.routes.public.individual_offers.v1.products._create_or_update_ean_offers&unselectedSeries=p100%28%29))
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27556
=> (PC-27556) perf: remove useless check 

pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27640
- utiliser le public name (nom d'usage) de la venue dans le select des page partenaires sur la Home
pour tester:
activer WIP_PARTNER_PAGE
mettre ses lieu en isPermanent = true
=> (PC-27640)[PRO] fix: prefer public name in pagePartner select in Home

api/src/pcapi/routes/backoffice/templates/components/forms/field_list_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/form_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/string_field.html, api/src/pcapi/routes/backoffice/templates/components/forms/tom_select_field.html, api/src/pcapi/static/backoffice/js/addons/pc-field-list.js
Alignement des champs des filtres de la recherche avancée dans la page des offres.
Avant:
Après:
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26985
=> (PC-26985)[BO] fix: correctly align advanced search filters in offers page

api/poetry.lock, api/pyproject.toml, api/src/pcapi/flask_app.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26488
New exporter to monitor rq jobs.
Inspired by flask documentation about [application dispatching.](https://flask.palletsprojects.com/en/3.0.x/patterns/appdispatch/)
GET http://localhost:5001/rq_metrics returns : 
```
python_gc_objects_collected_total{generation="0"} 58064.0
python_gc_objects_collected_total{generation="1"} 7686.0
python_gc_objects_collected_total{generation="2"} 146.0
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
python_gc_collections_total{generation="0"} 1529.0
python_gc_collections_total{generation="1"} 138.0
python_gc_collections_total{generation="2"} 9.0 …
```
=> (PC-26488)[API] feat: Add rq-exporter

pro/src/.env.integration, pro/src/.env.production, pro/src/.env.staging, pro/src/.env.testing, pro/src/index.html, pro/src/utils/config.ts
…in index.html.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26930
**Objectif**
Le `Content-Security-Policy-Report-Only` n'est pas supporté dans une balise `<meta>`, il faut que ce Header soit ajouté dans les réponses HTTP côté back. Cette PR supprime donc l'ajout de la balise.
=> (PC-26930)[PRO] fix: Remove CSP REPORT ONLY from meta tag in index.html

api/src/pcapi/core/offers/models.py
BSR: résolution de deux cas dans les models de offers ou on utilisait case avec une liste de cas au lieu de les passer en arguments positionnels.
Je n'ai fait que ces deux la (alors qu'il y en a plein d'autres) car c'était le deux seuls pour lesquels j'avais des warnings et je ne sais pas a quel point ces choses la sont testés.
le warning concerné:
```
pc-backoffice    | WARNING:py.warnings:/usr/src/app/src/pcapi/core/offers/models.py:247: RemovedIn20Warning: The "whens" argument to case(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.  (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
pc-backoffice    |   return sa.case([(cls.quantity.is_(None), None)], else_=(cls.quantity - cls.dnBookedQuantity))
```
=> (BSR)[API] chore: resolve some sqlalchemy2 warnings

pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx, pro/src/screens/IndividualOffer/InformationsScreen/__specs__/InformationsScreen.creation.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27618
Corriger un bug qui faisait que le lieu n'était pas vraiment sélectionné par défaut dans le formulaire de création d'offre pour les acteurs non admin avec plusieurs structures
=> (PC-27618)[PRO] fix: offer creation when several offerer does not select venue by default

api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/routes/backoffice/accounts_test.py
502 Bad Gateway on user id=2956859
All data joinedload: SQL query returned 48216 rows Query with all data except bookings: 1176 rows (depends on data) Query for bookings and joined data: 41 rows (number of bookings)
Remaining joined query could be optimized, but this is a first quick win for this page to be fetched in less than one second.
Ticket Jira : https://passculture.atlassian.net/browse/PC-27691
Testé dans la console python sur staging avec succès
=> (PC-27691)[BO] fix: timeout when loading account details page

api/src/pcapi/domain/movie_types.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27464
ça ressemble à un breaking change, mais ce champs est relativement nouveau et pas encore utilisé par l'app. On le modifie justement à la demande des devs fronts, pour être cohérent avec les autres champs (e.g. `musicType`)
=> PC-27464 add genres by label in offer

pro/src/app/AppLayout.tsx, pro/src/pages/EmailChangeValidation/EmailChangeValidation.tsx, pro/src/pages/LostPassword/LostPassword.module.scss, pro/src/pages/LostPassword/LostPassword.tsx, pro/src/pages/ResetPassword/ResetPassword.module.scss, pro/src/pages/ResetPassword/ResetPassword.tsx, pro/src/pages/SignIn/SignIn.tsx, pro/src/pages/SignIn/Signin.module.scss, pro/src/pages/Signup/Signup.module.scss, pro/src/pages/Signup/Signup.tsx, pro/src/pages/SignupJourneyRoutes/SignupJourneyRoutes.tsx, pro/src/screens/EmailChangeValidation/EmailChangeValidation.module.scss, pro/src/screens/EmailChangeValidation/EmailChangeValidation.tsx, pro/src/styles/global/_page.scss, pro/src/styles/mixins/_layout.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27368
Déplacer SkipLinks pour qu'il ne soit plus que dans AppLayout et pas dans les sous-pages (ex: Signin). L'objectif est de simplifier le composant AppLayout en vu de la refonte. 
Vérifier le bonne affichage des pages suivantes (responsive ou non), ainsi que l'affichage du menu d'évitement sur ces pages : 
- Connexion
- Inscription
- Mot de passe oublié
- Changement de mot de passe
- Parcours d’inscription 
- Accueil
=> (PC-27638)[PRO] refactor: move all skiplinks to app layout

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26951
Mise à jour de la dépendance : stylelint-config-standard-scss
Pas de changement impactant de notre côté : [lien vers le changelog](https://github.com/stylelint-scss/stylelint-config-standard-scss/blob/HEAD/CHANGELOG.md)
=> (PC-26951)[PRO] chore: upgrade stylelint-config-standard-scss

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240126T144443_d3bd3af52558_restart_bank_account_id_seq.py
The sequence was initially set to start at 100_000 to ensure a perfect match between a reimbursementPoint.id in the old bankInformation journey and a soon-to-be bankAccount.id in the new journey. This is all for accounting reasons and there can be any mismatch
However, there's already venues holding bankInformation (i.e. reimbursementPoint) where id goes beyong 100_000
Hence restarting at 200_000.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27613
=> (PC-27613)[API] feat: Restart bank_account_id_seq at 200_000

api/src/pcapi/core/offers/validation.py, api/tests/routes/public/individual_offers/v1/delete_date_test.py
We should be able to delete unbooked stocks from offer with tickets (withdrawalType=IN_APP)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27668
=> (PC-27668)[API] fix: allow deletion of unbooked stocks with tickets

api/src/pcapi/core/bookings/factories.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py, api/tests/core/finance/test_api.py, api/tests/core/offers/test_api.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/finance_test.py, api/tests/routes/backoffice/offers_test.py, api/tests/routes/public/individual_offers/v1/get_booking_test.py, api/tests/routes/public/individual_offers/v1/get_bookings_test.py, api/tests/routes/public/individual_offers/v1/patch_cancel_booking_by_token_test.py, api/tests/routes/public/individual_offers/v1/patch_validate_booking_by_token_test.py
`Booking.venue` is denormalized from `Booking.stock.offer.venue`.
Users of the factory who provide it directly probably expect that it
will set the venue of the offer, but it does not. Now an error is
raised which should make that clear.
=> (BSR)[API] test: Forbid directly passing `venue` to `BookingFactory`

api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/adage_iframe/get_collective_offer_template_test.py, api/tests/routes/adage_iframe/get_collective_offer_test.py, api/tests/routes/adage_iframe/get_favorites_test.py, api/tests/routes/pro/get_collective_offer_test.py, api/tests/routes/pro/patch_collective_offer_test.py, api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py, pro/src/apiClient/adage/models/CollectiveOfferResponseModel.ts, pro/src/apiClient/adage/models/CollectiveOfferTemplateResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferResponseModel.ts, pro/src/apiClient/v1/models/GetCollectiveOfferTemplateResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27536
Ajout d'un champ `isTemplate` aux réponses (_iframe_ adage et portail pro) qui concernent les offres collectives (vitrines ou non).
=> (PC-27536)[EAC] feat: add isTemplate to offers response models

api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/tests/routes/backoffice/offers_test.py
Amélioration des bulles de la recherche avancée dans la page des offres individuelles :
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26985
=> (PC-26985)[BO] feat: add informations in advanced search filters' bubbles in offer page

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/TrackingCTAShareBody.ts, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27532
Ajoute d'une route (iframe adage) afin d'ajouter un log de suivi pour le CTA de partage d'offre.
=> (PC-27532)[EAC] feat: iframe: logs: new route: share cta

api/tests/routes/backoffice/venues_test.py
The test failed when run between 4:00 and 5:00 UTC, because the
calculated last sync date was then between 23:00 and 0:00 UTC and the
date of the day was thus different in UTC and in CET.
We usually don't run tests during the night... but the CI runned pull
requests created by Dependabot around 3:00 UTC and this test always
failed.
=> (BSR)[API] test: Fix flaky test_get_venue_with_provider

pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderMenu/AdageHeaderMenu.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27560
Activer la couleur dans le header : 
exemple:
je suis sur la découverte, je clique sur une offre qui me redirige sur une page dédiée contenant /découverte/offerid/2 on veut que le header s'active pour Découverte
pour le lien de partage, si l'on est pas admin, nous aurons /recherche/offerid/2 dans ce cas, le header est activé pour Rechercher
=> (PC-27560)[PRO] feat: active header for subroutes adage

pro/src/components/UserPasswordForm/validationSchema.ts, pro/src/ui-kit/BoxRounded/BoxRounded.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21623
Branche: PC-21623-profil-mdp-wording
- Changer le spacing vertical entre les blocs : 16 px.
- Changer le border radius des blocs : 6 px.
- Ajouter un message générique: “Veuillez renseigner votre nouveau mot de passe”.
=> (PC-21623)[PRO] style: wording et modif des blocks, profil

pro/src/pages/Offers/Offers/OfferItem/Cells/BookingLinkCell/BookingLinkCell.tsx, pro/src/ui-kit/ListIconButton/ListIconButton.module.scss, pro/src/ui-kit/ListIconButton/ListIconButton.tsx, pro/src/ui-kit/Tooltip/Tooltip.module.scss, pro/src/ui-kit/Tooltip/Tooltip.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27672
**Objectif**
S'assurer que tous les boutons `ListIconButton` ont le même style.
**Réalisation**
Ajouter les classes sur le `ListIconButton` dans le cas ou il est `isExternal`. Et au passage j'ai réaligné les styles du bouton [avec la maquette](https://www.figma.com/file/AEXCkb4KbUyPmB4BRFa88s/PRO---Library?type=design&node-id=8112-100762&mode=dev), et j'ai mis des spans dans les `Tooltip` à la place des divs (https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)
=> (PC-27672)[PRO] style: Fix style of ListIconButton isExternal element

pro/src/core/OfferEducational/utils/__specs__/computeInitialValuesFromOffer.spec.ts, pro/src/core/OfferEducational/utils/computeInitialValuesFromOffer.ts, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/FormDates.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/__specs__/FormDates.spec.tsx, pro/src/utils/__specs__/date.spec.ts, pro/src/utils/date.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26938
**Objectif**
- A la création d'une offre vitrine collective, lorsqu'on choisit des dates spécifiques, voir les dates de début et de fin pré-remplies à aujourd'hui
- Quand on modifie la date de début, mettre à jour la date de fin à la même valeur que la date de début
**A noter**
Au passage ajout de 2 fonctions qui permettent de préciser le formattage le + approprié pour un input HTML sans se baser sur une constante d'affichage. Voir le commentaire des retours de Marie.
=> (PC-26938)[PRO] feat: Prefill template offer creation dates.

pro/src/screens/OfferEducational/OfferEducationalForm/FormDates/__specs__/FormDates.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27759
**Objectif**
Corriger le test unitaire qui fail après le merge du nouveau formulaire FormDates qui a encore des labels d’inputs sans le “*” dans les tests.
=> (PC-27759)[PRO] fix: Date de début in formsDates now have an asterisk.

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferShareLink/OfferShareLink.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferShareLink/__specs__/OfferShareLink.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27531
**Objectif**
Ajouter un log au moment ou un utilisateur clique sur le bouton de partage d'une offre dans la liste des offres adage
=> (PC-27531)[PRO] feat: Add tracker log to adage offer share button click.

pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/Offerers.tsx, pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPages.tsx, pro/src/pages/Home/Offerers/__specs__/Offerers.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPage.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPages.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27040
Fix image page partenaire
-> quand on vient d'uploader une image, il faut ré-appeler les venue (et donc l'offerer) pour que la venue se mette à jour (et que l'image ne disparaisse pas)
=> (PC-27040)[PRO] fix: image just uploaded disapears for partners in home

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/repository.py
Now that we have a "not null" constraint on `Pricing.event`, we can
replace outer joins by inner joins.
=> (BSR)[API] feat: Simplify joins on `Pricing.event`

api/Dockerfile
This should detect inconsistencies between `pyproject.toml` and
`poetry.lock`, and will thus refuse to build the Docker image if an
unwanted changed has been added to `pyproject.toml` (without
corresponding changes to `poetry.lock`).
This is mostly useful for local builds, since this check is already
done by a GitHub workflow when building the image for testing and
other environments.
---
Exemple en local : 
```
$ ../pc start-backend
[...]
=> [backoffice builder 5/9] RUN pip install poetry                                                                                                                                     [...]
=> ERROR [backoffice builder 7/9] RUN poetry check --lock …
```
=> (BSR)[API] feat: Run `poetry check` when building Docker image

api/src/pcapi/utils/urls.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27001
lorsqu’on est sur la page structure, ça nous envoie vers le lien exterieur suivant : https://passculture.pro/offres?structure=10381&statut=active 
On aimerait que ce soit https://passculture.pro/offres?structure=10381
=> (PC-27001)[BO] feat: quicklink PC pro - status page offre filtrées

api/src/pcapi/core/finance/api.py
=> (BSR)[API] refactor: Rename `_delete_dependent_event_pricings` function

api/Dockerfile
As poetry warn us, in future versions, the plugin that is used to export the requirements.txt won't be automatically installed. This could break our builds
```
#22 [builder 8/9] RUN poetry export -o requirements.txt --without dev
#22 0.846 Warning: poetry-plugin-export will not be installed by default in a future version of Poetry.
#22 0.846 In order to avoid a breaking change and make your automation forward-compatible, please install poetry-plugin-export explicitly. See https://python-poetry.org/docs/plugins/#using-plugins for details on how to install a plugin.
```
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27811
=> (PC-27811)[API] chore: Explicitly install `poetry-plugin-export`

api/src/pcapi/routes/adage_iframe/playlists.py, api/src/pcapi/routes/adage_iframe/serialization/playlists.py, api/tests/routes/adage_iframe/playlist_test.py
Pydandic does not make it easy to distinguish between serialization and deserialization meaning we can't know which is which between the camelCase and snake_case to use.
This fixes LocalOfferersPlaylistOffer by updating the fields to camelCase fields.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27785
=> (PC-27785)[ADAGE] fix: imgUrl on the local playlist is always None

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240130T172755_381fef70eb7a_add_adage_venue_address_model.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offerers/models.py
Intermediate model that will be used to link existing venues to addresses (that does not exist yet).
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27031
Ajout d'un modèle intermédiaire qui servira à lier les lieux (Venue - existants) aux adresses (Address - à venir). Cette table intermédiaire peut toutefois être remplie en attendant l'arrivée des adresses.
=> (PC-27031)[EAC] feat: new AdageVenueAddress model

api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage_iframe/playlists.py
There was two issues identified so far:
1. a join from the playlist onto itself which created a combination on the playlist content and therefore way too many duplicated SQL rows to load (around 14_000 rows while 10 were expected).
2. there was a missing limit to 10 elements per playlist.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27837
=> (PC-27837)[ADAGE] fix: playlist too long to load

api/src/pcapi/core/offers/factories.py, api/src/pcapi/domain/music_types.py, api/src/pcapi/domain/show_types.py, api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py, api/tests/core/offers/test_factories.py, api/tests/routes/native/v1/bookings_test.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/get_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26655
L'objectif de cette modification est de rendre la sandbox plus réaliste.
on n'a plus besoins de create offers with extra data car c'est ce qui ce passe par defaut dans create_offers_for_each_subcategory()
=> (PC-26655)[API] feat: offerFactory takes into consideration the subcategory for extradata

api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/workers/fully_sync_venue_job.py, api/tests/routes/backoffice/venues_test.py
Ajout d'un bouton "Resynchroniser les offres" dans la page "Lieu" pour pouvoir lancer un worker de synchronisation des stocks depuis le provider
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27482
=> (PC-27482)[BO] feat: add button to force sync offers' stocks in venue page

api/src/pcapi/connectors/api_adresse.py, api/src/pcapi/connectors/sirene.py, api/src/pcapi/routes/backoffice/pro/blueprint.py, api/tests/connectors/api_adresse/api_adresse_test.py, api/tests/routes/backoffice/pro_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-26990
Correction après test non concluant sur testing : oups, le code postal n'est pas diffusible, seulement la ville et le code INSEE !
=> (PC-26990)[BO] fix: API Sirene returns [ND] in postal code for non-diffusible, use INSEE code

api/src/pcapi/core/providers/allocine_movie_list.py
Gestion du cas `releases=[AllocineMovieRelease(releaseDate=None, ...)]`
=> (BSR)[API] fix: handle case where all release dates are null

api/src/pcapi/core/educational/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offers/models.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/offerers_test.py
Inclure les offres expirées dans celles qui sont "inactives" dans les statistiques de la page structure
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27744
=> (PC-27744)[BO] feat: flag expired offers as 'inactive' in offerer page's stats

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/core/mails/transactional/users/online_event_reminder.py, api/src/pcapi/core/users/commands.py, api/tests/core/mails/transactional/users/online_event_reminder_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25410
Cette PR prend en compte un commentaire de [cette PR](https://github.com/pass-culture/pass-culture-main/pull/9783) (sur slack) proposant une implémentation plus simple. 
Au lieu de schedule des emails et de les annuler le cas échéant, on fait tourner un cron plus régulièrement (toute les 30 minutes) pour notifier. 
Au lieu d'un email _exactement_ 30 min avant, nos utilisateurs auront un email _au moins_ 30 min avant
=> (PC-25410)[API] feat: add command to send reminder at least 30 minutes before an online event

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py
Ticket Jira (ou description si BSR) : ne pas utiliser override_features dans la sandbox
=> (BSR)[BO] fix: don't use pytest tools in sandbox scripts

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx, pro/src/pages/Reimbursements/__specs__/Reimbursements.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27558
Filtrer les justificatifs de remboursements sur le compte bancaire et non plus le point de remboursement si le FF est activé `WIP_ENABLE_NEW_BANK_DETAILS_JOURNEY`
=> (PC-27558)[PRO] feat: filter invoice on bank account if FF enabled

pro/cypress/e2e/createEventIndividualOffer.cy.ts, pro/cypress/e2e/createThingIndividualOffer.cy.ts, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx, pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx, pro/src/screens/VenueForm/VenueEditionFormScreen.tsx, pro/src/screens/VenueForm/__specs__/VenueEditionFormScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26869
Ne pas afficher les boutons "Créer une offre" si le FF `WIP_ENABLE_PRO_SIDE_NAV` est activé, sauf celui de la home pour les admin.
=> (PC-26869)[PRO] feat: Hide the offer creation button with the WIP_ENABLE_PRO_SIDE_NAV FF.

pro/src/context/ReimbursementContext/ReimbursementContext.tsx, pro/src/core/shared/constants.ts, pro/src/hooks/useCurrentUser.ts, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/BankInformations/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/ReimbursementsBanners.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/screens/IndividualOffer/StocksThing/__specs__/StocksThing.edition.spec.tsx, pro/src/store/StoreProvider/StoreProvider.tsx, pro/src/store/user/reducer.ts, pro/src/store/user/selectors.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27762 
- Ajouter la structure sélectionnée sur la home dans le contexte utilisateur pour qu'elle soit acessible partout sur PC pro
- Suppression du select de structure dans la page informations bancaires (on utilise la structure sélectionnée sur la home)
=> (PC-27762)[PRO] fix: use url offererId in bank informations page

api/src/pcapi/core/educational/api/booking.py
Lower the log level when someone tries to cancel a collective offer is beyond the cancellation date/time.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27959
=> (PC-27959)[ADAGE] feat: don't sentry when cancellation is expected

api/src/pcapi/connectors/serialization/cgr_serializers.py, api/tests/local_providers/cinema_providers/cgr/cgr_stocks_test.py, api/tests/local_providers/cinema_providers/cgr/fixtures.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26905
Fix https://sentry.passculture.team/organizations/sentry/issues/1254484/events/latest/?environment=production&project=5&query=is%3Aunresolved+CGR&statsPeriod=90d
=> (PC-26905)[API] fix: Skip showtimes with negative remaining places

pro/package.json, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26947
**Objectif**
Mettre à jour la lib jsdom
=> (PC-26947)[PRO] bump: Upgrade jsdom to 24.0.0.

api/.squawk.toml, api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240205T120726_ba414c8b1ee4_add_domain_to_national_program_intermediate_table.py, api/src/pcapi/core/educational/api/national_program.py, api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/exceptions.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/public/collective/endpoints/domains.py, api/src/pcapi/routes/public/collective/endpoints/offers.py, api/src/pcapi/routes/public/collective/serialization/domains.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_offers.py, api/tests/core/educational/api/test_national_program.py, api/tests/routes/public/blueprint_v2_openapi_test.py, api/tests/routes/public/collective/endpoints/get_collective_offers_educational_domains_test.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py, api/tests/routes/public/collective/endpoints/post_collective_offer_test.py, pro/src/apiClient/v2/models/CollectiveOffersDomainResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27568
Retranscrire côté api publique des règles qui ont été implémentées sur le portail pro, côté front, au sujet de la création et de l'édition d'offres collectives. A présent, les dispositifs nationaux sont rattachés à des domaines éducatifs et une offre ne peut donc plus être créée ou éditée s'il y a une incohérence entre les domaines et le dispositif national.
1. Ajout d'une table permettant de faire le lien entre des domaines et des dispositifs nationaux.
2. Mise à jour de la route des domaines éducatifs de l'api publique collective : un champ `nationalPrograms` fait son apparition dans chaque objet renvoyé.
3. Vérification lors de la création et de l'édition d'une offre collective que les données …
=> PC 27568 eac collective api add national programs rules

api/src/pcapi/core/history/models.py, api/src/pcapi/routes/backoffice/pivots/blueprint.py, api/src/pcapi/routes/backoffice/pivots/contexts/allocine.py, api/src/pcapi/routes/backoffice/pivots/contexts/base.py, api/src/pcapi/routes/backoffice/pivots/contexts/boost.py, api/src/pcapi/routes/backoffice/pivots/contexts/cgr.py, api/src/pcapi/routes/backoffice/pivots/contexts/cineoffice.py, api/src/pcapi/routes/backoffice/pivots/contexts/ems.py, api/tests/routes/backoffice/helpers/post.py, api/tests/routes/backoffice/pivots_test.py
Ajout d'une action à l'historique du lieu quand on supprime un pivot associé.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27829
=> (PC-27829)[BO] feat: add an action to the venue's history when deleting a pivot

api/src/pcapi/alembic/CONTRIBUTING.md
Mise à jour de la doc, concernant la partie `squawk` (comment ignorer une instruction).
=> (BSR) doc: update squawk part: ignore next statement

api/src/pcapi/connectors/big_query/queries/adage_playlists.py, api/src/pcapi/core/educational/api/playlists.py, api/src/pcapi/core/educational/commands.py, api/tests/core/educational/api/test_playlists.py
Synchronization uses the BigQuery pagination to deal with huge data set instead of making multiple queries with offset/limit or as previously on a per institution basis.
Ticket Jira: https://passculture.atlassian.net/browse/PC-27860
=> (PC-27860)[API] feat: avoid too many BigQuery requests

api/src/pcapi/core/providers/commands.py, api/src/pcapi/core/providers/models.py, api/tests/core/providers/test_commands.py
As they were defined, the "column properties" of VenueProvider did not
allow to use `joinedload()`. SQLAlchemy raised the following error:
Select statement '<sqlalchemy.sql.selectable.Select object at 0x7fb68ca6a0d0>'
returned no FROM clauses due to auto-correlation; specify correlate(<tables>)
to control correlation manually.
I could not find how to use `correlate()` on the column properties,
but `correlate_except()` achieves something similar and makes
SQLAlchemy happy.
=> (BSR)[API] perf: Avoid N+1 SQL queries in `synchronize_venue_providers_apis` command

pro/src/ui-kit/Button/ButtonLink.tsx, pro/src/ui-kit/Button/__specs__/ButtonLink.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28023
**Objectif**
Tous les liens internes sont annoncés comme étant la page courante parce que si l'attribut "aria-current" est undefined il est transformé en "page". Il faut le set à `false` par défaut
=> (PC-28023)[PRO] fix: Fix the link default current-page value.

api/README.md
Update de la doc oubliée quand on a changé la route de swagger
=> (BSR)[API] docs: update swagger url in readme

api/src/pcapi/core/external/commands/update_sendinblue_pro_attributes.py, api/tests/core/external/test_commands.py
Correction dans la commande Flask de resynchro des attributs Brevo de tous les pro : les `NON_ATTACHED_PRO` n'étaient pas dans le filtre. Il est nécessaire de les mettre à jour pour que `IS_ACTIVE_PRO` soit fiable.
=> (BSR)[API] fix: flask command update_sendinblue_pro did not include non attached pro

api/src/pcapi/core/educational/models.py, api/tests/core/educational/test_api.py
hasEndDatePassed was not working well as the end date time is at 23:59 while it should have been 23:59:59.999999
Anyway, let's now assume we consider the end date as an datetime instead to figure out hasEndDatePassed
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26360
=> (PC-26360)[API] fix: only expire offers that actually have expired

pro/src/core/OfferEducational/types.ts, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOffer.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/AdageOfferInfoSection.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/AdageOfferPartnerSection.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/__specs__/AdageOfferInfoSection.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/__specs__/AdageOfferPartnerSection.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferHeader/AdageOfferHeader.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferHeader/AdageOfferHeader.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferHeader/__specs__/AdageOfferHeader.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/AdageOfferInstitutionPanel.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/AdageOfferInstitutionPanel.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferInstitutionPanel/__specs__/AdageOfferInstitutionPanel.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/__specs__/adageOfferDates.spec.ts, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/__specs__/adageOfferInstitution.spec.ts, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/__specs__/adageOfferStocks.spec.ts, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/adageOfferDates.ts, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/adageOfferInstitution.ts, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/adageOfferStocks.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/PrebookingButton/PrebookingButton.tsx, pro/src/utils/date.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27841
**Pour voir l'interface**
- Activer le FF WIP_ENABLE_NEW_ADAGE_OFFER_DESIGN
- Aller sur "/adage-iframe/recherche/offre/B-[un id d'offre de votre env]?token=[votre token adage]"
**Objectif**
- Adapter la page offre vitrine pour que'elle fonctionne aussi pour une offre réservable (quelques infos en + sur la page de l'offre réservable)
- Ajouter le bloc de l'établissement scolaire sur la page de l'offre réservable (à la place du bloc du partenaire culturel de la page offre vitrine)
=> Pc 27841 adage bookable offer page

pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscovery.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/__specs__/AdageDiscovery.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27927
Ajouter l'information de l'elementId dans le tracking pour la playlist des domaines sur adage
=> (PC-27927)[PRO] feat: add elementId value in tracking domain playlist

pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/AppLayout.tsx, pro/src/pages/AdageIframe/app/components/AppLayout/__specs__/AppLayout.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/OfferInfos.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27651
**FF a activer**
WIP_ENABLE_NEW_ADAGE_OFFER_DESIGN
**Objectif**
Remplacer l'ancien bouton "en savoir plus" par un bouton qui redirige vers l'offre dans une nouvelle fenêtre (bouton différent pour une offre vitrine dans la recherche, et pour une offre réservable dans l'onglet "Pour mon établissement")
=> (PC-27651)[PRO] feat: Add redirect links to adage offers cards.

pro/src/components/Breadcrumb/Breadcrumb.module.scss, pro/src/components/Breadcrumb/Breadcrumb.tsx, pro/src/components/Breadcrumb/__specs__/Breadcrumb.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/VenueCard/VenueCard.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferPartnerPanel/AdageOfferPartnerPanel.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferPartnerPanel/AdageOfferPartnerPanel.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offer.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28115
L'espacement dans le bloc partenaire entre le nom du partenaire et le renvoie vers la fiche partenaire : ajouter 8px entre le nom du lieu et le button “voir la fiche partenaire”
Enlever le lien dans le fil d’ariane sur le nom de l’offre, ça n’est pas censé être cliquable
Picto dans la photo du lieu : mettre le picto “museum” en placeholder pour homogénéiser
=> (PC-28115)[PRO] fix: uxui modification adage svg and padding

api/src/pcapi/core/educational/constants.py
Added in d6211e144b28c887f56c8fd0e50d3848ac28bafd but never used.
=> (BSR)[API] chore: Remove unused `educational.constants.INTERVENTION_AREA`

pro/src/components/DialogBox/DialogBox.module.scss, pro/src/components/DialogBox/DialogBox.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28033
**Objectif**
S'assurer que les boutons de fermeture de dlialog ne décalent pas tout le contenu.
Quand on avait fait le précedent rework des dialogs on avait repéré que certains titres passaient par dessus le bouton de fermeture du dialog (ex dialog des infos bancaires). Pour régler le pb on avait mis le bouton en float. Mais dans la plupart des dialogs, le contenu est sous la forme d'un bloc general en flex, ce qui est incompatible avec l'ajout d'un élément en float.
=> (PC-28033)[PRO] fix: Undo the float right of the dialog close button.

api/src/pcapi/connectors/cgr/cgr.py, api/src/pcapi/core/external_bookings/cgr/client.py, api/src/pcapi/models/feature.py, api/tests/connectors/cgr/soap_definitions.py, api/tests/core/bookings/test_api.py, api/tests/core/external_bookings/cgr/test_client.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27818
This is to ensure that when the process of external booking is taking too much longer
(more than our timeout), they cancel their transaction on their side.
In that way, they won't have anymore bookings that exists on their side but that doesn't
on our own (because if their response exceed our timeout, the transaction is rollbacked
and the booking is never created)
This replace the former mecanism where when catching a timeout during the booking we were
calling for a cancellation.
(https://github.com/pass-culture/pass-culture-main/commit/f529d11beba9ae0914b7162108ff357050c38418, https://github.com/pass-culture/pass-culture-main/commit/99259265e30bb1951544067cc282da0e8da62a92)
=> (PC-27818)[API] feat: Forward our timeout value to CGR

api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/tests/core/offerers/test_models.py, api/tests/core/offers/test_repository.py, api/tests/routes/backoffice/offerers_test.py
Unused since bd26dd9d242e960 (except in tests, where it can be
replaced).
=> (BSR)[API] chore: Remove `UserOfferer.first_user`

api/src/pcapi/core/providers/api.py, api/tests/core/providers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28071
Dé-supprimer les stocks existants lors de la re-synchronisation
=> (PC-28071)[BO] fix: restore soft-deleted stocks in sync process

api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/core/search/backends/base.py, api/src/pcapi/core/search/commands/indexation.py, api/tests/core/search/test_api.py, api/tests/core/search/test_backend_algolia.py, api/tests/core/search/test_commands_indexation.py
We want to use sets to avoid duplicate ids in queues We can then remov the cron dedicated to this task
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28111
- ~[ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data~
- ~[ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques~
=> (PC-28111)[API] perf: use sets in reindexation queues

api/src/pcapi/core/educational/repository.py, api/src/pcapi/routes/adage/v1/serialization/prebooking.py, api/tests/routes/adage/v1/get_all_bookings_per_year_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28055
Ajouter le nom du lieu à la réponse d'une des route de l'api exposée à Adage.
=> (PC-28055)[EAC] feat: expose venue name to adage route

pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/updateIndividualOffer.spec.ts, pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts
Pour les offre synchronisé (offer.lastProvider != null), sentValues ne contient pas isDuo
Ce qui fait que !!isDuo = false, alors que c'est pas ce qu'on veut
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28061
=> (PC-28061)[PRO] fix: fix set isduo false when update synchronized offer

.github/CODEOWNERS
Permettre à la team github `ci-owners` de maintenir et améliorer la CI.
=> BSR: owners dev team on ci

api/src/pcapi/routes/adage/v1/blueprint.py
Ticket Jira: https://passculture.atlassian.net/browse/PC-28194
On dirait que le décorateur de vues ajoute un hash pour les models et le spectree de base ne le fait pas.
=> (PC-28194)[API] fix: ensure proper display on adage swagger/openapi.json

pro/src/app/AppRouter/subroutesReimbursements.tsx, pro/src/components/Header/Header.tsx, pro/src/components/ReimbursementsTabs/ReimbursementsTabs.tsx, pro/src/components/ReimbursementsTabs/constants.ts, pro/src/pages/Reimbursements/__specs__/Reimbursements.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27866
Fix l'affichage de l'onglet `Gestion financière` quand une sous-route est active
=> (PC-27866)[PRO] fix: set reimboursement link active on subroute

.github/workflows/dev_on_workflow_tests_api.yml, api/README.md, api/src/pcapi/alembic/versions/sql/schema_init.sql, api/tests/routes/pro/get_offerer_test.py, docker-compose-backend.yml
Use lighter postgres image
Dans l'image utilisé les tables tiger et topology (nécessaires pour postgis) sont déjà crées.
Il faut reset le search path parceque sinon postgres ne trouve pas nos tables: https://www.postgresql.org/docs/16/extend-extensions.html#EXTEND-EXTENSIONS-RELOCATION
Je ne comprends pas vraiment pourquoi, possiblement vu que initialement la db est vide à part les tables de postgis, donc le search path est resté lié à l'extension.
A priori il n'y a pas de risque à reset le search path.
L'image utilisée contient déjà postgis, donc il n'est plus nécessaire de l'installer.
=> (BSR)[API] chore: use lighter postgis image for docker compose

api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_backend_algolia.py
We misused the SCAN command. Documentation says:
It is important to note that the MATCH filter is applied after
elements are retrieved from the collection, just before returning
data to the client. This means that if the pattern matches very
little elements inside the collection, SCAN will likely return no
elements in most iterations.
That's exactly what happened. We performed a _single_ SCAN command. It
worked in tests (and when developing) because there was no (or very
few) keys in Redis. All keys were retrieved, the filter was applied
and the processing queues were found. On production, though, there are
many keys. So the first SCAN command likely returned a small batch of
keys that did not include any processing queue.
Now we paginate through the results.
=> (PC-28104)[API] fix: Fix use of SCAN in `clean_indexation_processing_queues` command

pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/AdageOfferPublicSection.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/__specs__/AdageOfferInfoSection.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferHeader/__specs__/AdageOfferHeader.spec.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/__specs__/adageOfferStocks.spec.ts, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/utils/adageOfferStocks.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offer.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28128
**Objectif**
- Le prix du stock d'une offre réservable étant enregistré en centimes, on le divise par 100 pour l'affichage en euros
- Certaines listes de la page offre sur adage ont un pipe "|" en trop à la fin parce que je checkais la mauvaise length
- Ajout du los de clic sur le bouton "en savoir plus" aussi sur le bouton de redirection vers l'offre adage
=> (PC-28128)[PRO] feat: Adage offers small UI adjustments.

api/src/pcapi/core/subscription/phone_validation/api.py, api/src/pcapi/core/users/api.py, api/src/pcapi/routes/native/v1/account.py, api/tests/routes/backoffice/accounts_test.py, api/tests/routes/native/v1/account_test.py
In fact, force the TTL to be the same (12 hours), whichever way we
generate the token.
=> (PC-28208)[BO] fix: Set TTL on phone validation token when sent from back-office

api/src/pcapi/core/history/models.py, api/src/pcapi/core/token/__init__.py, api/src/pcapi/core/token/serialization.py, api/src/pcapi/core/users/models.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/pro_users/blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get/details/users.html, api/src/pcapi/routes/pro/users.py, api/src/pcapi/serialization/decorator.py, api/src/pcapi/utils/urls.py, api/tests/core/token/test_token.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_users_test.py, api/tests/routes/pro/get_connect_as_test.py, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26956
Cette pr se borne a prendre le compte d'un admin dans le BO et a le connecter à pro sur le compte d'un utilisateur pro arbitraire. La gestion du cycle de vie de cet admin connecté comme un pro est hors du scope de cette pr.
Cette pr met plus l’accès sur la sécurité que l'utilisabilité et poe donc des contraintes forte sur l'utilisateur utilisant la feature.
PRO et le BO étant sur des applications flask différentes les sessions ne sont pas partagés enter les deux, il est donc indispensable d'utiliser un endpoint du coté backend pro pour connecter l'utilisateur venant du BO. Pour le faire de manière sécurisé les données de connections (id de l'utilisateur vers lequel se connecter notamment) ne sont pas …
=> Pc 26956 rpa connect as bo

pro/src/screens/SignupJourneyForm/Offerer/__specs__/OffererForm.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/validationSchema.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28073
Changer le wording du message quand un SIRET n'est pas visible dans le parcours d'inscription 
Le SIRET n'est pas visible -> Le propriétaire de ce SIRET s'oppose à la diffusion de ses données au public
=> (PC-28073)[PRO] fix: change non visible siret message

pro/src/app/App/App.tsx, pro/src/app/__specs__/App.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28224
Rediriger un utilisateur non-rattaché à une structure vers le parcours d'onboarding quand il essaie d'accèder à une page du portail pro. 
- Créer un nouvel utilisateur
- Accéder au parcours d'inscription en se connectant
- Fermet l'onglet 
- Essayer d'accéder à `/accueil` -> Vérifier qu'on est bien redirigé sur `/parcours-inscription`
=> (PC-28224)[PRO] fix: redirect non rattached pro to onboarding

pro/src/pages/Home/Offerers/OffererBanners.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27995
Voici la structure avec callout, variant "info"-1,  pour label: 'En savoir plus sur le fonctionnement du pass Culture': http://localhost:3001/accueil?structure=926 
Voici [figma](https://www.figma.com/file/AEXCkb4KbUyPmB4BRFa88s/PRO---Library?type=design&node-id=8661-52286&mode=design&t=pm35zw8YFDdMrF4q-0) pour se retrouver: 
- Callout label: 'En savoir plus', (Un email vous sera envoyé lors de la validation de votre rattachement.)
- Callout label: 'En savoir plus sur la création d’un lieu'.
Anciens:
=> (PC-27995)[PRO] style: Ajout Callout aux structures en validation

pro/cypress/e2e/createVenue.cy.ts
BSR
e2e, en cas de fail les valeurs n'étaient pas régénérées
=> (BSR)[PRO] fix: test e2e createVenue, create data in beforeEach

.github/workflows/dev_on_push_workflow_main.yml
This workflow is only relevant for feature branches (pull requests).
The previous condition made it run on maintenance branches too, which
we don't want.
---
J'ai ajouté dans cette pull request un commit de test (qui sera supprimé avant le merge) montrant que mypy-cop est bien lancé quand on fait des modifications dans le code Python : https://github.com/pass-culture/pass-culture-main/actions/runs/8079686259/job/22074709350?pr=10968 (et on voit le commentaire laissé par mypy-cop dans la pull request)
=> (BSR)[API] ci: Run mypy-cop workflow only on feature branches

api/src/pcapi/models/feature.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28251
Ajout d'un FF pour le sujet de la prévisualisation côté pro d'une offre adage pendant la création/édition
WIP_ENABLE_ADAGE_PREVIEW_OFFER_IN_PRO
=> (PC-28251)[PRO] feat: create ff preview adage offer in pro

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/pro/offerers.py, api/tests/routes/pro/post_offerer_test.py, pro/src/pages/Offerers/OffererCreation/OffererCreation.tsx, pro/src/pages/Offerers/OffererCreation/__specs__/OffererCreation.spec.tsx
fix: https://sentry.passculture.team/organizations/sentry/issues/1255572/?project=5&query=is%3Aunresolved+user_offerer&referrer=issue-stream&statsPeriod=14d&stream_index=0
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26961
=> (PC-26961)[API] fix: Catch when user belonging to an offerer try to (re)create it

api/src/pcapi/connectors/big_query/queries/offerer_stats.py
Fix offerer stats null offerer id
=> (BSR)[API] fix: filter null offerer id from offerer stats query

pro/src/pages/Home/Offerers/PartnerPage.tsx, pro/src/pages/Home/Offerers/PartnerPageCollectiveSection.tsx, pro/src/pages/Home/Offerers/PartnerPageIndividualSection.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPageCollectiveSection.spec.tsx, pro/src/pages/Home/Offerers/__specs__/PartnerPageIndividualSection.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27681
deux blocs d'info ne doivent être affichés que sur le form venue
=> (PC-27681)[PRO] fix: some fields should not be displayed for partner in venue form

api/src/pcapi/routes/backoffice/test_users/blueprint.py, api/tests/routes/backoffice/user_deletion_test.py
La fonctionnalité de suppression d'utilisateurs est présente pour aider l'équipe QA à recetter la création de compte via SSO Google. La protection via appareil de confiance étant activée en staging, il faut aussi les supprimer avec la suppression de compte.
=> (BSR)[API] fix: enable user with trusted device deletion

api/poetry.lock, api/pyproject.toml, api/src/pcapi/routes/external/sendinblue.py, api/tests/routes/external/sendinblue_test.py
IP filtering is now done by a frontend.
Fun fact: we required the `ipaddress` third-party library, which was
not necessary: it's part of the standard library since Python 3.3.
---
Ticket : https://passculture.atlassian.net/browse/PC-28278
=> (PC-28278)[API] feat: Remove IP filtering on Brevo webhooks

api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/patch_collective_offer_template_test.py
Missed the fact that PATCH on collective offer template is perfectly fine with no contact info and it should be fine as long as the model already has a contact data.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27842
=> (PC-27842)[ADAGE] fix: collective offer patches with no contact info

pro/src/pages/Home/StatisticsDashboard/__specs__/OfferStats.spec.tsx, pro/src/pages/Offers/domain/getOffersCountToDisplay.ts
Afficher 500+ lorsque le back renvoie la valeur maximale pour `publishedPublicOffers` = 500 cf https://github.com/pass-culture/pass-culture-main/blob/88910ff2e9e0859b7155ecaeb3b8198dedfeac97/api/src/pcapi/core/offerers/repository.py#L717 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28310
=> (PC-28310)[PRO] fix:display 500+ when reaching ceiling # in stats block

api/src/pcapi/routes/native/v1/serialization/offers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offers_test.py
Ajout de l'`allocineId` dans les `extraData` pour qu'il soit remonté dans la route `/native/v1/offer/{offerId}`
=> (BSR) feat: add allocine id to offer response extra data

pro/src/components/IndividualOfferForm/Categories/Categories.tsx, pro/src/components/IndividualOfferForm/Categories/__specs__/Categories.spec.tsx, pro/src/components/IndividualOfferForm/IndividualOfferForm.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/Venue.tsx, pro/src/components/IndividualOfferForm/__specs__/IndividualOfferForm.BannerAddVenue.spec.tsx, pro/src/components/IndividualOfferForm/types.ts
…
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27627
Ne pas afficher une bannière cassée (ne l'afficher que quand elle n'est pas cassée)
=> (PC-27627)[PRO] fix: offer, hide banner with broken link if offerer not set

pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss, pro/src/components/ActionsBarSticky/ActionsBarStickyRight.tsx, pro/src/components/VenueForm/VenueCreationForm.tsx, pro/src/components/VenueForm/VenueEditionForm.tsx, pro/src/components/VenueForm/VenueFormActionBar/VenueFormActionBar.tsx, pro/src/pages/IndividualOfferWizard/Confirmation/Confirmation.tsx, pro/src/screens/IndividualOffer/ActionBar/ActionBar.module.scss, pro/src/screens/IndividualOffer/ActionBar/ActionBar.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.module.scss, pro/src/screens/IndividualOfferConfirmationScreen/IndividualOfferConfirmationScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25372
- la partie gauche se met en dessous MAIS s'inverse pour que le bouton rouge soit devant
- la partie droite ce met au dessus dans le même ordre
offre création :
Rec : 
Récap : 
Confirmation :
offre édition :
page lieu : 
offre eac : 
OffreS :
=> (PC-25372)[PRO] responsive confirmation + ActionBarSticky

.githooks/pre-commit, api/src/pcapi/alembic/run_migrations.py
MacOS' cut command does not support long arguments like `--fields`, and each migration in production is in its own transaction so the offline migrations should also be printed in their own migrations.
=> (BSR) fix: fix squawk pre-commit hook

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240229T101500_8ed029bd05a6_add_allowedonadage_to_offerer.py, api/src/pcapi/core/educational/api/adage.py, api/src/pcapi/core/offerers/models.py, api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py
The flag on Venue was unreliable to know whether or not an offerer was allowed to create/use collective features.
That leads to confusions and incorrect values on BO and PRO website. We now base the flag on SIREN which should be more reliable.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27989
=> (PC-27989)[ADAGE] feat: add allowedOnAdage at Offerer level

api/src/pcapi/core/finance/commands.py, api/src/pcapi/core/finance/siret_api.py, api/src/pcapi/routes/backoffice/move_siret.py, api/tests/core/finance/test_commands.py
Ticket Jira (ou description si BSR) : cette commande est maintenant dans le backoffice, elle n'est donc plus utile
=> (BSR)[API] chore: remove unused move siret command

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240229T144043_8d4e8ebb573c_eac_update_student_levels_rename_and_add.py, api/src/pcapi/core/educational/models.py, api/tests/routes/pro/post_collective_offers_test.py, pro/src/apiClient/adage/models/StudentLevels.ts, pro/src/apiClient/v1/models/StudentLevels.ts, pro/src/core/OfferEducational/utils/__specs__/buildStudentLevelsMapWithDefaultValue.spec.ts, pro/src/core/OfferEducational/utils/buildStudentLevelsMapWithDefaultValue.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/studentsOptions.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/__specs__/FormParticipants.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28214
Les deux niveaux scolaires de Marseille en grand passent à trois : le premier est renommé et le suivant découpé en deux (CP, CE1 et CE2 d'un côté, et CM1 et CM2 de l'autre).
=> PC 28214 eac student level update

api/src/pcapi/utils/requests.py, api/tests/utils/requests_test.py
Notre wrapper `pcapi.utils.requests` n'est pas utilisé par le client Algolia, car celui-ci utilise `requests.Session.send`, qui n'est pas pris en charge par notre wrapper. Cette pull request fait les modifications nécessaires pour que ce soit le cas.
**3 commits, à relire séparément.** J'ai supprimé un argument inutilisé et j'en ai profité pour ré-écrire les tests du wrapper qui étaient... disons "peu pertinents".
=> (PC-28316)[API] Généralisation du wrapper pour `requests` (pour usage par le client Algolia)

api/src/pcapi/connectors/ems.py, api/src/pcapi/core/external/zendesk_sell_backends/logger.py, api/src/pcapi/core/external/zendesk_sell_backends/testing.py, api/src/pcapi/core/external/zendesk_sell_backends/zendesk_sell.py, api/src/pcapi/infrastructure/repository/stock_provider/provider_api.py, api/src/pcapi/routes/backoffice/external/zendesk_sell/blueprint.py, api/src/pcapi/utils/pylint.py, api/src/pcapi/utils/requests.py, api/src/pcapi/workers/apps_flyer_job.py, api/tests/conftest.py, api/tests/connectors/beneficiaries/educonnect.py, api/tests/connectors/beneficiaries/ubble_test.py, api/tests/files/pylint_requests.py, api/tests/providers/titelive_search_test.py, api/tests/routes/backoffice/zendesk_sell_tests.py, api/tests/utils/pylint_test.py, api/tests/utils/requests_test.py
We should never import the third-party `requests` package. Instead, we
should import our `pcapi.utils.wrapper`. We have forgotten in the
past, now we won't.
=> (BSR)[API] style: Add a Pylint check for `import requests`

api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py, api/src/pcapi/models/feature.py, api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25897
- Association des offres et stocks Boost avec un produit Allociné s'il existe
- Conditionnement par un feature flag.
- S'il est inactif, les offres sont créées sans être associées à un produit.
- S'il est actif, les offres pour lesquelles le produit n'est pas trouvé ne sont pas créées
- Ce feature flag est destiné à être aussi utilisé pour les autres synchronisations d'offres et stocks cinémas, sauf celle d'Allociné. Le but est de le supprimer lorsque le catalogue est assez complet et donc que les offres non créées soient marginales.
- Suppression de deux fonction privées inutilisées
=> (PC-25897)[API] feat: synchronize boost stocks with allocine products

pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/FormParticipants.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormParticipants/__specs__/FormParticipants.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28263
- WIP_ENABLE_MARSEILLE
**Objectif**
Modification wording pour l'info sur Marseille en Grand dans le formulaire de création d'une offre collective.
=> (PC-28263)[PRO] feat: Update MEG form info wording.

pro/src/components/SideNavLinks/SideNavLinks.module.scss, pro/src/components/SideNavLinks/SideNavLinks.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26868
- Rajouter le bouton créer une offre dans la barre de navigation latérale.
- Utiliser le offererId du localStorage.
=> (PC-26868)[PRO] feat: Adding the create offer button to the side nav.

api/src/pcapi/local_providers/allocine/allocine_stocks.py
Correction : les logs ne sont censés remonter que dans le cas où le produit allociné n'existe pas.
=> (BSR)[API] fix: log only when allocine product is not found

pro/src/pages/Reimbursements/ReimbursementsBanners.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28381
Lorsque l’id de la structure est précisé dans l’url, utilisé cette Id pour filtrer les données affichées dans les pages de la gestion financière.
**Contexte :** 
Certains liens du BO passe l'id de la structure dans l'url pour accéder à une page spécifique de la gestion financière
=> (PC-28381)[PRO] feat: use offererId param in reimbursement context

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/routes/pro/collective_offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/post_collective_offers_template_test.py, pro/src/apiClient/v1/models/PostCollectiveOfferTemplateBodyModel.ts, pro/src/core/OfferEducational/adapters/postCollectiveOfferAdapter.ts, pro/src/core/OfferEducational/adapters/postCollectiveOfferTemplateAdapter.ts, pro/src/core/OfferEducational/utils/__specs__/createOfferPayload.spec.ts, pro/src/core/OfferEducational/utils/createOfferPayload.ts
The contactEmail field should be optional on collective offer template Rules are:
1. contactUrl and contactForm can not be both active
2. at least one contact should be there
Commit 1b86a27628ce7b6f0924464e6dd16fddb4194998 only covered the PATCH request, this one covers the POST one
**Front**
Objectif:
Puisque le model du payload des offres vitrine et réservable n'est plus le même (contactEmail optiolnel dans les offres vitrine), il y a des problèmes de type sur la fonction `createCollectiveOfferPayload` qui est utilisée pour les 2 types d'offre.
Ticket Jira : https://passculture.atlassian.net/browse/PC-28315
=> (PC-28315)[API] fix: rework pro contact options

.github/workflows/dev_on_workflow_tests_api.yml
Corriger la syntaxe d'un hint dans les logs de CI, bug introduit dans https://github.com/pass-culture/pass-culture-main/commit/b5366f1cc3ce11b2b259842e121f090972dfbd20
La bonne syntaxe a été façonnée par @dbaty , qu'il soit couvert de louanges et de remerciements.
=> (BSR) fix squawk lint hint

pro/src/app/App/hook/useLoadFeatureFlags.ts, pro/src/context/IndividualOfferContext/adapters/getWizardData/getWizardData.ts, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx, pro/src/pages/AdageIframe/app/components/OffersForInstitution/OffersForMyInstitution.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataEdition.tsx, pro/src/utils/sendSentryCustomError.ts
PR pour fix deux choses : 
- on perd la stacktrace originelle de l'erreur en utilisant captureMessage au lieu de captureException
- mettre une variable dans le message de l'issue reportée sur Sentry a créé +200 erreurs en prod ces 2 dernières semaines
=> (BSR)[PRO] fix: sentry reporting

api/src/pcapi/routes/error_handlers/thumbnails_error_handlers.py
Logging "this error was encountered: FileSizeExceeded" at the ERROR
level is useless. We cannot do anything about it. I guess that we
wanted to log for debugging purposes: INFO level is enough, then.
---
Exemple sur Sentry : https://sentry.passculture.team/organizations/sentry/issues/416900/events
=> (BSR)[API] fix: Do not log user input error on bogus image upload

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py, api/tests/core/finance/test_commands.py
=> (BSR)[API] refactor: Remove unnecessary `commit` argument from `_create_finance_events_from_incident`

api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/revenue_details.html, api/src/pcapi/routes/backoffice/templates/offerer/get/stats.html, api/src/pcapi/routes/backoffice/templates/venue/get/stats.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/venues_test.py
Ajout du CA par année dans les pages Lieu et Structure du BO.
Ticket Jira : https://passculture.atlassian.net/browse/PC-27500
=> (PC-27500)[BO] feat: add total revenue per year in venue/offerer pages

api/src/pcapi/core/users/constants.py
We previously set the token TTL to 5 days. But it's believed not be
long enough: some users really take their time to validate their
e-mail address. They have no way to re-generate a token if it has
expired. These users are then blocked. We don't want users to be
blocked... So here we extend the TTL... until we implement a way
for users to generate a new token.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28414
=> (PC-28414)[API] feat: Increase TTL of pro email validation token

app-engine/image-resizing/app.yaml
````
[1] resource.type="gae_app"
resource.labels.module_id="image-resizing"
(protoPayload.appId="h~passculture-metier-prod")
severity=ERROR
[2] https://cloud.google.com/appengine/docs/standard/troubleshooter/latency#autoscaler_settings
[3] automatic_scaling:
min_idle_instances: automatic
max_idle_instances: automatic
min_pending_latency: automatic
max_pending_latency: automatic
max_instances: 10
[4] https://medium.com/google-cloud/app-engine-scheduler-settings-and-instance-count-4d1e669f33d5 
````
=> (BSR)[imageresizing] fix: add automatic scaling adjustment

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/src/pcapi/routes/backoffice/utils.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28225
aussi ien experiemntalement que d'apres le explain la nouvelle requete est environ 3 fois plus cher dans le cas pratique du bug et remonte 6 fois plus d'informations. Je pense que le prix supplémentaire est dut au fait qu'on a vraiment besoin des 100 lignes (alors qu'avant on ne scannais que 16 lignes dans la table offer).
Le fait de passer par un `EXISTS` a la place de `DISTINCT` accelere la solution d'un facteur 2 environ mais on reste 2 fois plus lent qu'avant.
=> (PC-28225)[BO] fix: do not hide lines if an offer has multiple stocks

api/src/pcapi/routes/adage_iframe/logs.py, api/tests/routes/adage_iframe/post_logs_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28153
Limiter le spam d'une route de _tracking_ de l'iframe adage : calculer le hash du JSON envoyé, l'enregistrer dans Redis pour 5s et n'enregistrer le log que si la clé n'existait pas.
=> (PC-28153)[EAC] feat: adage iframe: filter log spam

api/src/pcapi/core/educational/api/adage.py, api/src/pcapi/core/educational/api/address.py, api/tests/core/educational/api/test_address.py, api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28328
Bug : il peut arriver que l'on essaie d'insérer une ligne dans `adage_venue_address` avec une référence vers un lieu qui n'existe pas. Ceci peut arriver car on ne vérifie pas que les informations envoyées par le client sont exactes.
Fix : vérifier que les ids des lieux existent bien.
1. retirer les appels à `get_chunks` qui ne servent à rien. Ils auraient pu servir à faire des _commits_ toutes les N lignes mais ce n'est probablement pas nécessaire et tout avoir dans une transaction est probablement plus intéressant.
2. les insertions et les mises à jour dans `adage_venue_address` se font dans une transaction, via `atomic()`.
=> (PC-28328)[EAC] fix: filter unknown venues before updates

pro/src/screens/SignupJourneyForm/ConfirmedAttachment/ConfirmedAttachment.tsx, pro/src/screens/SignupJourneyForm/ConfirmedAttachment/__specs__/ConfirmedAttachment.spec.tsx, pro/src/screens/SignupJourneyForm/Offerers/Offerers.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28433
Rediriger l'utilisateur vers la home après son rattachement à une structure. 
Ce fix fait suite au ticket redirigeant un utilisateur sans UserOfferer vers le parcours d'inscription. Il manquait un update du currentUser après le rattachement pour mettre à jour le user dans le store. 
**Pour recetter :** 
Créer un nouvel utilisateur
Dans le parcours d'inscription saisir un Siret déjà existant
Choisir le parcours de rattachement : Rejoindre cet espace
Vérifier qu'après validation on arrive bien sur la home de PC pro
=> (PC-28433)[PRO] fix: redirect user to gome after attachment to offerer

api/src/pcapi/core/offerers/tasks.py, api/tests/core/offerers/test_tasks.py
Bug suite au ticket Jira : https://passculture.atlassian.net/browse/PC-27830
check_offerer_siren_task is now called even if "siren-caduc" tag is set,
because of codir report check when offerer is still active in the
database.
Exception was raised:
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "unique_offerer_tag"
=> (PC-27830)[API] fix: exception when trying to tag "siren-caduc" twice

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240307T154918_3784f1bb8d9e_unique_program_for_an_educational_institution.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/finance/api.py, api/tests/core/educational/test_models.py, api/tests/core/finance/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28407
À la demande de la compta, séparer dans les _invoices_ les dépenses pour le programme « Marseille en Grand » des dépenses classiques du ministère.
=> (PC-28407)[API] feat: 'Marseille en grand' in invoices

api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/helpers.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/offers/blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28211
J'ai tout cassé dans la PR #11092 , donc je tente de réparer : 
- retour à UNION (qui au moins répond vite avec des ids)
- on arrête la recherche de résas par nom de bénéficiaire en même temps que nom d'offre, ça plombe le _query plan_ et le User ID ou l'adresse email sont plus fiables
À intégrer dans la MEP de lundi (#11092 étant dans la MES d'hier).
=> (PC-28211)[BO] fix: timeout when searching for bookings

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
A rare bug could occur (and did occur once) that caused a pricing to
be set as "processed" even though it was not linked to any cashflow.
As such, it stayed in this status.
The fix is somewhat incomplete (see comments) but the bug is rare
enough that this simple solution seems good enough.
There are no tests because the bug is not testable: it happens when a
pricing is created (by another process) at a particular point in time
during the execution of `_generate_cashflows()`.
---
Ticket : https://passculture.atlassian.net/browse/PC-28425
=> (PC-28425)[API] fix: Avoid stuck processed pricings and wrong cashflow amount

api/src/pcapi/core/mails/transactional/bookings/booking_cancellation.py, api/src/pcapi/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/backoffice/multiple_offers/blueprint.py, api/tests/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary_test.py, api/tests/core/offers/test_api.py, api/tests/routes/backoffice/multiple_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23550
ticket refait apres commentaire de Patrick sur une autre PR ( fermé ) 
```
Je ne pense pas que la PR corresponde à la demande : selon ma compréhension, on souhaite adapter l'email, qui est déjà envoyé depuis la fonction reject_inappropriate_product via send_booking_cancellation_emails_to_user_and_offerer, et non ajouter un email supplémentaire au milieu de la logique.
Adapter l'email, c'est ajouter le paramètre « rejected » demandé dans la description du ticket, et dont je ne vois la trace nulle part dans le diff de cette PR.
Tu devrais mieux tester quels sont les emails envoyés dans la fonction de test que tu as ajoutée, et les paramètres qui sont envoyés. Notamment t'assurer de ne pas envoyer deux …
```
=> (PC-23550)[API] feat: send email to user when booking is cancelled because isCguIncompatible

api/.env.testing, api/src/pcapi/flask_app.py, api/src/pcapi/settings.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27658
**Objectif**
Pour obtenir le rapport d’erreur csp sur sentry, on doit ajouter l’uri sentry dans les response headers
=> (PC-27658)[API] feat: Add CSP-REPORT-ONLY response header.

api/src/pcapi/core/finance/repository.py, api/src/pcapi/routes/pro/finance.py, api/src/pcapi/routes/serialization/finance_serialize.py, api/src/pcapi/utils/rest.py, api/tests/core/finance/test_repository.py, api/tests/routes/pro/get_invoices_v2_test.py, api/tests/routes/pro/get_offerer_stats_v2_test.py, api/tests/routes/pro/get_offerers_bank_accounts_test.py, api/tests/routes/pro/get_venue_stats_test.py, api/tests/routes/pro/get_venue_test.py, api/tests/routes/pro/patch_cancel_collective_offer_booking_test.py, api/tests/routes/pro/patch_collective_offer_template_test.py, api/tests/routes/pro/patch_collective_offer_test.py, api/tests/routes/pro/patch_collective_stock_test.py, api/tests/routes/pro/patch_offer_test.py, api/tests/routes/pro/post_collective_stock_test.py, api/tests/routes/pro/post_offer_test.py, api/tests/routes/pro/post_stocks_test.py, api/tests/routes/pro/post_venue_test.py, api/tests/routes/public/booking_token/v2/patch_cancel_booking_by_token_test.py, api/tests/utils/rest_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/HasInvoiceQueryModel.ts, pro/src/apiClient/v1/models/HasInvoiceResponseModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28447
Disable les filtres de la page Justificatifs de remboursements quand la structure sélectionné n'a pas d'invoices. Au contraire activer ces filtres si la structure a des invoices, même pour une période différente que celle sélectionnée par défaut.
=> Pc 28447 enable invoice filter when offerer has one

pro/cypress/e2e/signIn/unsuccessfulSignInForWrongPasswordTest.cy.ts, pro/cypress/support/constants.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28465
unsuccessful sign in for wrong password (Connexion impossible en cas de mot de passe erroné)
=> (PC-28465) [PRO] test : unsuccessful sign in for wrong password

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/scripts/venue/acceslibre/match_acceslibre.py, api/tests/connectors/acceslibre/acceslibre_test.py
- Script en 2 parties : 
1. `run_matching` Le match qui effectue le matching avec acceslibre et sauvegarde les données dans un csv. Il peut être joué localement (cf. commentaire dans le code)
2. `run_update` La sauvegarde qui va écrire les slugs et la date de dernière mise à jour depuis le csv de match
- Ce script sera également relancé après la campagne Tally (durant laquelle potentiellement plusieurs partenaires culturels iront remplir leurs info chez acceslibre). On pourra le retirer de la basecode ensuite
- 
- Afin d'obtenir de meilleurs résultats de match, modification de la méthode `find_venue_at_accessibility_provider` (d'où les 2 commits)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28038
=> (PC-28038)[API] feat: script to match permanent venues with acceslibre

api/src/pcapi/core/bookings/api.py, api/src/pcapi/routes/native/v1/bookings.py, api/tests/core/bookings/test_api.py
The route called `edit_stock()` upon failure with external tickets,
but changes were not committed. The route could perform the commit,
but it seems more future-proof to call `edit_stock()` (and commit) in
`book_offer()` itself, because calling `edit_stock()` should be the
responsability of `book_offer()`, not its callers.
=> (BSR)[API] fix: Include side effects of booking failure in `book_offer()`

api/src/pcapi/use_cases/save_venue_bank_informations.py, api/tests/use_cases/save_venue_bank_informations_test.py
Legacy bankInformation that were turned into bankAccount doesn't have
BankAccountStatusHistory. Therefore, when we try to update the bankAccount
on a DS application change, we can't find it because of `join()` on BankAccountStatusHistory
and we try to create it (`api/src/pcapi/use_cases/save_venue_bank_informations.py +491`)
Which is fail because there is a unique constraint on the dsApplicationId field.
Hence this fix
Fix this [issue](https://sentry.passculture.team/organizations/sentry/issues/1510164/)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28475
=> (PC-28475)[API] fix: Don't join on BankAccountStatusHistory

api/src/pcapi/routes/serialization/users.py, api/tests/routes/pro/get_user_profile_test.py, api/tests/routes/pro/signin_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/NavStateResponseModel.ts, pro/src/apiClient/v1/models/SharedCurrentUserResponseModel.ts, pro/src/apiClient/v1/models/SharedLoginUserResponseModel.ts, pro/src/app/AppLayout.tsx, pro/src/app/__specs__/AppLayout.spec.tsx, pro/src/components/Footer/Footer.tsx, pro/src/components/Footer/__specs__/Footer.spec.tsx, pro/src/components/Header/Header.tsx, pro/src/hooks/__specs__/useIsNewInterfaceActive.spec.tsx, pro/src/hooks/useIsNewInterfaceActive.tsx, pro/src/pages/CookiesFooter/CookiesFooter.tsx, pro/src/pages/Home/ProfileAndSupport/Support.tsx, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.tsx, pro/src/pages/Home/StatisticsDashboard/__specs__/StatisticsDashboard.spec.tsx, pro/src/screens/Bookings/Bookings.tsx, pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28176
Afficher la nouvelle navigation pour les utilisateurs qui ont le champs `newNavDate` valorisé
**Stratégie :** 
- Retourner l'information navState dans la sérialisation des routes signin et get_profile
- Changer la condition d'affichage de la nouvelle nav
=> Pc 28176 enable side nav if user has new nav date

pro/src/pages/VenueCreation/OpeningHoursReadOnly/OpeningHoursReadOnly.module.scss, pro/src/pages/VenueCreation/OpeningHoursReadOnly/OpeningHoursReadOnly.stories.tsx, pro/src/pages/VenueCreation/OpeningHoursReadOnly/OpeningHoursReadOnly.tsx, pro/src/pages/VenueCreation/OpeningHoursReadOnly/__specs__/OpeningHoursReadOnly.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28270
Le responsive suivra quand les maquettes seront là,
visible sur storybook en attendant sa page d'accueil
=> (PC-28270)[PRO] feat: make read only OpeningHours

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/mails/transactional/finance_incidents/finance_incident_notification.py, api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/src/pcapi/core/permissions/models.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27689
- Envoi du mail lors de la validation d'un geste commercial
- Ajout du rôle CODIR chargé de valider ce type d'incidents
=> (PC-27689)[API] feat: add commercial gesture email and codir role

pro/src/screens/Bookings/BookingsRecapTable/Filters/FilterByBookingStatus/FilterByBookingStatus.tsx, pro/src/screens/Bookings/BookingsRecapTable/Filters/Filters.module.scss, pro/src/screens/Bookings/BookingsRecapTable/Filters/__specs__/FilterByBookingStatus.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26079
**Objectif**
Utiliser le [pattern Disclosure](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) de W3C pour l'ouverture du tooltip du status des réservations indiv.
- Ouverture fermeture au Space ou Enter
- Fermeture au Escape
- Ajout du aria-expanded et aria-controls
=> (PC-26079)[PRO] feat: Make booking status tooltip accessible.

api/src/pcapi/repository/clean_database.py
Ticket Jira (ou description si BSR) : vider OfferPriceLimitationRule quand on clean la db
=> (BSR)[API] fix: add OfferPriceLimitationRule to clean database

api/src/pcapi/routes/adage_iframe/serialization/favorites.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/tests/routes/adage_iframe/get_favorites_test.py
Fix : faire en sorte que les datetimes de l'iframe adage soient tous
formattés correctement (grâce à `format_into_utc_date`).
=> (BSR)[EAC] fix: some adage iframe datetimes were not properly formatted

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py
dgfip endpoint takes more than 3 seconds to get document. 3s timeout was a copy/paste from Insee backend.
Ticket Jira : https://passculture.atlassian.net/browse/PC-28559
=> (PC-28559)[API] fix: ReadTimeoutError often received when requesting attestations from API Entreprise

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py, api/tests/connectors/api_entreprise_test.py, api/tests/connectors/api_entreprise_test_data.py
error_message = errors[0]["meta"]["provider_errors"][0]["description"]
E   TypeError: string indices must be integers, not 'str'
Ticket Jira : https://passculture.atlassian.net/browse/PC-28558
=> (PC-28558)[API] fix: TypeError when receiving error 429 from API Entreprise

api/.gitignore, api/Dockerfile, infra/pc_scripts/start_backend.sh, pc
Start the backend with a proxy. 
In case you use a proxy (do not name it), you should put your key `cacert.pem` in /api repository
Then you can use `pc start-proxy-backend`
=> (BSR)[API] fix|chore: start backend with a proxy

api/src/pcapi/core/offerers/commands.py, api/src/pcapi/core/offerers/synchronize_venues_banners_with_google_places.py, api/tests/core/offerers/test_commands.py, api/tests/core/offerers/test_synchronize_venues_banners_with_google_places.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28391
---
Précision sur la valeur de `frequency`:
TL;DR: On accepte 1, 2 et 4 pour pas à refaire de PR si le besoin métier change
A priori on commence par 1/ mois
Mais il y a une discussion métier et  compta sur changer la fréquence à 2 fois mar mois.
Pour que ce soit facile de passer d'un à l'autre on a choisi de laisser la valeur en paramètre.
Mais d'être un peu restrictif pour avoir un joli diviseur de 28 (d'où 1, 2 et 4)
---
=> PC-28391 update venue banners from gmaps everyday

.github/workflows/dev_on_push_workflow_main.yml
The `update-api-client-template` step is only used on a pull
request (as per the `if` directive: `github.base_ref` is defined only
in the context of a pull request).
On the other hand, the `prepare-cache-master` step is only used on
master (that's what the `if` directive says).
As such, we can simplify the expression that fetches the docker tag to
fetch.
=> (BSR)[API] ci: Simplify steps that call `dev_on_workflow_update_api_client_template` workflow

api/src/pcapi/static/backoffice/js/addons/pc-batch-action-form.js
Fix de l'erreur js lors de l'affichage de modal d'action batch s'il y'a juste un message à la place du formulaire.
Avant :
https://github.com/pass-culture/pass-culture-main/assets/155538488/0d49b077-9368-404b-9405-5f18b15119ac
Après : 
https://github.com/pass-culture/pass-culture-main/assets/155538488/f6650243-ee21-46d3-99fa-f6a2f756d4cb
=> (BSR)[BO] fix: don't crash the js when displaying a batch action form with no form

pro/src/app/AppRouter/routesMap.tsx, pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.module.scss, pro/src/pages/CollectiveOfferPreviewEdition/CollectiveOfferPreviewEdition.module.scss, pro/src/pages/CollectiveOfferPreviewEdition/CollectiveOfferPreviewEdition.tsx, pro/src/pages/CollectiveOfferPreviewEdition/__specs__/CollectiveOfferPreviewEdition.spec.tsx, pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.module.scss, pro/src/screens/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx, pro/src/screens/CollectiveOfferSummaryEdition/__specs__/CollectiveOfferSummaryEdition.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28250
Ajout d'un bouton + lien pour aller sur l'aperçu depuis l'édition d'une offre vitrine
=> (PC-28250)[PRO] feat: preview edition

api/src/pcapi/static/backoffice/js/addons/pc-tom-select-field.js
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28075
Avant : 
Après :
=> (PC-28075)[BO] fix: display proper 'not found' message in autocomplete select fields

api/src/pcapi/connectors/entreprise/backends/api_entreprise.py, api/tests/connectors/api_entreprise_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28510
Le but de cette PR est de s'assurer qu'on n'atteint pas, et a fortiori qu'on ne dépasse pas, la volumétrie autorisée pour les appels à API Entreprise. Ainsi les appels peuvent être retardés (si c'est un appel depuis le BO, notre endpoint sera plus long à répondre), voire envoyer directement une exception.
En complément : réduction du rythme de la vérification à 4 structures par minute : https://github.com/pass-culture/infrastructure/pull/2104
=> (PC-28510)[API] feat: ensure that we never reach API Entreprise Rate Limit

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28657
Deux jointures faites en double plombent les performances.
Avec une seule, on réduit le `cost` du _Query plan_ de 765834 à 37970 (-95%) pour la liste des offres collectives en attente.
=> (PC-28657)[BO] fix: performance for collective offers query

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240319T102111_33c2838cfb4a_allow_zero_cashflow.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/templates/invoices/invoice.html, api/tests/core/finance/test_api.py, api/tests/files/invoice/rendered_invoice.html
- Génération de cashflows à 0€
- Intégrer dans les justificatifs de remboursements les contributions offreur à 100%
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28362
=> (PC-28362)[BO] feat: allow cashflow/invoice generation with amount = 0

api/src/pcapi/core/mails/transactional/sendinblue_template_ids.py, api/tests/core/mails/transactional/bookings/booking_cancellation_by_pro_to_beneficiary_test.py
Le _template_ d'email 161, copie de la version prod mise à jour, remplace le _template_ 37 sur le compte de test Brevo.
=> (BSR)[API] fix: Brevo testing template 37 replaced with 161

api/tests/routes/public/individual_offers/v1/post_product_by_ean_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
The problematic tests define next_minute and sends it to the backend that checks that next_minute is in the future. In some rare cases, next_minute is in the past when the check is done. To prevent this, next_minute is changed to in_ten_minutes.
=> (BSR)[API] fix: flaky tests that use next_minute

api/src/pcapi/connectors/entreprise/backends/testing.py, api/tests/connectors/api_entreprise_test.py, api/tests/connectors/api_entreprise_test_data.py, api/tests/core/external/external_pro_test.py, api/tests/core/offerers/test_tasks.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_test.py
fix flacky tests by moving special SIREN meaning upward in number.
=> (BSR)[API] fix: avoid using last digits of SIREN for special meaning

api/src/pcapi/connectors/recommendation.py, helmfile.yaml
`requests` expects a number of seconds as an integer, not a
`timedelta` object.
=> (PC-28496)[API] fix: Fix client timeout of Recommendation API

pro/src/components/Tutorial/Tutorial.module.scss, pro/src/components/Tutorial/Tutorial.tsx, pro/src/components/TutorialDialog/TutorialDialog.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28671
**Objectif**
Améliorer l'accessibilité du contenu du tutorial. J'ai rendu + accessible le groupe de boutons de navigation (les petit cercles). Mais c'est + du damage control qu'autre chose, dans le cadre d'un pattern carousel W3C recommande d'avoir les controles de navigation avant le contenu des pages. https://www.w3.org/WAI/ARIA/apg/patterns/carousel/. Donc toutes les pages seront KO
[J'ai créé un ticket Design ](https://www.notion.so/passcultureapp/3187d7264b6c446dace5c713b7309f8b?v=cab9f8d6853044a799487decdd47c0bc&p=65a162a2fa3146cdbfc6e446e864efa7&pm=s)dans notion pour ouvrir la discussion
=> (PC-28671)[PRO] feat: Improve tutorial navigation accessibility.

api/src/pcapi/routes/native/v1/authentication.py, api/tests/routes/native/v1/authentication_test.py
An account registered with a password and with its email not validated is a symptom of an account pre-hijacking attack waiting for an email validation. To prevent this we disable the email + password login when a SSO is enabled.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28611
=> (PC-28611)[API] fix: mitigate account pre-hijacking on SSO login

api/src/pcapi/core/providers/titelive_api.py, api/tests/providers/titelive_search_test.py
Sometimes, TiteLive sends us image urls that point to an empty image. We do not want the music sync to fail because of this, as the correct image will be synchronised at a later date.
=> (BSR)[API] fix: silence titelive thumbnail errors

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSuggestions/OffersSuggestions.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28816
**Objectif**
Considérer que les résultats de la recherche algolia peuvent être null.
`react-instantsearch` n'exporte pas de type pour SearchResults, et le type bricolé ne pense pas que `results` peut être null. J'ai ignoré l'erreur mais si vous avez une solution plus propre c'est cool 👍
=> (PC-28816)[PRO] fix: Results can be null in react instantsearch.

api/src/pcapi/connectors/entreprise/backends/testing.py, api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/tasks.py, api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/offerer/get/details/entreprise_info.html, api/src/pcapi/routes/backoffice/templates/venue/get/entreprise_info.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/utils/siren.py, api/tests/core/offerers/test_tasks.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/offerers_test.py, api/tests/routes/backoffice/pro_test.py, api/tests/routes/backoffice/venues_test.py, api/tests/utils/siren_test.py
- Backoffice: check that SIREN format is valid before calling API Entreprise (avoids error 422)
- Nightly offerer check: same check
- Generate valid SIREN/SIRET in factories according to Luhn formula (this changes SIREN/SIRET in sandbox)
Ticket Jira : https://passculture.atlassian.net/browse/PC-28660
=> (PC-28660)[API] feat: check SIREN or SIRET valid format

api/src/pcapi/routes/backoffice/templates/components/revenue_details.html
Un message de précision dans le CA par année pour une meilleur compréhension des chargés de territoire :
=> (BSR)[BO] feat: Add a note for better understanding of revenue details

pro/src/pages/Signup/SignUpValidation/SignUpValidation.tsx, pro/src/pages/Signup/SignUpValidation/__specs__/SignupValidation.spec.tsx
Fix la récupération de l'utilisateur sur la page de validation d'email 
En lien avec [cette PR](https://github.com/pass-culture/pass-culture-main/pull/11425/commits/0efb9b4f464b2dcc2fcdca74200697cc0100ba28#diff-21922470e43db3fb9a1f832b3eb1cd16e3948f005bcba5adbde8da7c6c49fc46)
=> (BSR)[PRO] fix: fix user selection in SignupValidation

pro/cypress/e2e/adageDiscovery.cy.ts, pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/DomainsCard.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/OfferFavoriteButton/OfferFavoriteButton.tsx, pro/src/ui-kit/ListIconButton/ListIconButton.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27007
Ajout de test e2e pour la page découverte : 
Accès à / redirige vers la découverte
Accès à /?token=…&venue=[quelque chose] redirige sur /recherche avec le bon filtre sur la venue
Défilement des 3 playlists et de la liste des domains
Mise en favoris d'une offre (l'étoile est rouge + aller dans mes favoris vérifier la présence de l'offre + recharger la page sur la découverte pour vérifier que l'offre est toujours en favoris)
Redirection vers une page offre au clic sur une offre d'une playlist et vérifier que header actif au bon endroit
Redirection vers la recherche au clic sur un domaine (avec le bon filtre actif)
Redirection vers la recherche au clic sur un lieu (avec le bon filtre)
=> (PC-27007)[PRO] feat: add test e2e for discovery page adage

pro/src/components/NewNavReview/NewNavReview.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28188
Ajuster l'alignement de la bannière de review de la nouvelle interface en mode responsive pour aligner l'icone avec le haut du texte
=> (PC-28188)[PRO] fix: fix alignment in responsive for new nav review

api/src/pcapi/scripts/rebuild_staging/anonymize.sql
Ticket Jira (ou description si BSR) : C'est de l'historique sans données à anonymiser, et sinon ça fait crasher la page des règles de fraude en staging
=> (BSR)[API] feat: keep offer validation rule history in staging

pro/src/screens/IndividualOffer/StocksThing/StockThing.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27743
=> (PC-27743)[PRO] style: Marge du titre du Callout de stock

pro/src/app/AppRouter/routesMap.tsx, pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.tsx, pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx, pro/src/components/SignupJourneyStepper/__specs__/SignupJourneyStepper.trackers.spec.tsx, pro/src/pages/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreation.tsx, pro/src/pages/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx, pro/src/pages/CollectiveOfferPreviewEdition/CollectiveOfferPreviewEdition.tsx, pro/src/pages/CollectiveOfferPreviewEdition/__specs__/CollectiveOfferPreviewEdition.spec.tsx, pro/src/pages/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx, pro/src/pages/CollectiveOfferSummaryCreation/__specs__/CollectiveOfferSummaryCreation.spec.tsx, pro/src/pages/Desk/__specs__/Desk.spec.tsx, pro/src/pages/Home/Offerers/__specs__/VenueCreationLinks.spec.tsx, pro/src/pages/Offerers/Offerer/OffererDetails/AttachmentInvitations/__specs__/AttachmentInvitations.spec.tsx, pro/src/pages/Reimbursements/__specs__/LinkVenuesDialog.spec.tsx, pro/src/screens/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreation.tsx, pro/src/screens/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx, pro/src/screens/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx, pro/src/screens/SignupJourneyForm/ActionBar/__specs__/ActionBar.trackers.spec.tsx, pro/src/screens/SignupJourneyForm/Validation/__specs__/ValidationScreen.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28532
**Objectif**
Intégrer l'aperçu de l'offre dans le parcours de création d'une offre collective réservable. Et correction d'un bug au passage qui faisait que le step "Récapitulatif" était accessible trop tôt dans le parcours de créarion.
=> (PC-28532)[PRO] feat: edition preview for bookable offer

api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/public/collective/serialization/offers.py, api/src/pcapi/routes/shared/validation.py, api/tests/routes/adage_iframe/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28759
Bug : lors d'une demande de contact, le format du numéro de téléphone est vérifié mais les erreurs ne sont pas gérées. Cette PR corrige cela en ajoutant une validation au niveau du modèle pydantic.
Simplification de certains tests qui comportaient plusieurs blocs de copier/coller : le même `dict` (plus ou moins) et dont le contenu n'avait pas toujours d'importance pour le test en lui-même.
=> (PC-28759)[EAC] fix: handle bad phone number

api/src/pcapi/connectors/entreprise/sirene.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/validation.py, api/src/pcapi/routes/pro/venues.py, api/tests/core/offerers/test_api.py, pro/src/pages/VenueCreation/SiretOrCommentFields/SiretOrCommentFields.tsx, pro/src/pages/VenueCreation/SiretOrCommentFields/__specs__/SiretOrCommentFields.spec.tsx, pro/src/pages/VenueCreation/SiretOrCommentFields/validationSchema.ts, pro/src/pages/VenueCreation/VenueCreationForm.tsx, pro/src/pages/VenueSettings/VenueSettingsForm.tsx, pro/src/pages/VenueSettings/VenueSettingsScreen.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28358
_Contexte : Actuellement lorsqu'un acteur veut changer de SIRET il passe par le support pour effectuer cette action. Il s'avère que parfois le SIRET communiqué est non diffusible. Dans ce cas un fois l'action support effectuée, le lieu possède un SIRET non diffusible ce qui empêche toutes modifications de ce lieu car on re-valide le SIRET à chaque modification du lieu._ 
**Solution** 
- Autoriser la modification du SIRET sur la page d'édition d'un lieu pour permettre aux acteurs d'être autonome à ce sujet. On garde les règles de validation classique du SIRET dans ce cas. 
- Autoriser la modification d'un lieu possédant un SIRET non diffusible : Dans le cas ou lieu possède un SIRET non diffusible …
=> Pc 28358 fs allow siret edition

api/src/pcapi/connectors/dms/serializer.py, api/src/pcapi/core/finance/ds.py, api/src/pcapi/use_cases/save_venue_bank_informations.py, api/tests/connector_creators/demarches_simplifiees_creators.py, api/tests/use_cases/save_venue_bank_informations_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28742
sentry issue : https://sentry.passculture.team/organizations/sentry/issues/1484914/?project=5&referrer=jira_integration
correction de l'erreur. Il s'agit de tronquer l'attribut label.
A noter:
-  pour la version V5 cela est réaliser dans le serialiser
- pour la version v4 je part du principe déjà implémenté que le label est reconstruit
=> (PC-28742)[API] fix: truncate banks account label for  DS import

api/.env.staging
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28763
**Objectif**
Pour trouver les erreurs CSP en staging, on ajoute l'uri de rapport d'erreur en staging.
=> (PC-28763)[API] feat: Add CSP report-only url in staging.

api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/pro/signup.py, api/tests/routes/pro/signup_pro_V2_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28179
Activer la nouvelle navigation lors de la création
Pour les utilisateurs non invités l'activation se fait selon la parité de leur id.
Pour les utilisateurs invité, ils "héritent" du status de l'utilisateur qui envoi l'invitation. Seul l'attribut newNavDate est a considérer.
L'attribut eligibilityDate n'est pas a modifier. Il est utilisé surtout pour distinguer les testeurs beta des testeurs A/B/
=> (PC-28179)[API] feat: enable new user to new nav according to id parity

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240328T101616_c7d04bd67054_create_index_on_action_type.py, api/src/pcapi/core/history/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28826
L'index sert à fortement accélérer la requête sur l'historique de modifications des rôles (voir ticket), identifiée dans les requêtes lentes par Sentry. Mais il apportera potentiellement un gain sur toutes les requêtes qui filtrent en fonction du type d'action (règles de fraude, sous-requêtes pour l'homologation, etc.).
=> (PC-28826)[API] perf: create index on action_history."actionType"

.github/update-jira-issues.sh, .github/workflows/dev_on_workflow_update_jira_issues.yml, .jira.d/templates/edit
Utiliser le label `SafeToDeploy` pour choisir le commit _release candidate_, comme dans le repo `pass-culture-app-native`
Si un commit est mergé alors qu'il est rattaché à un ticket Jira ayant un autre commit sur master, on édite alors les champs suivant du ticket:
- `Impropre=true`
- `SafeToDeploy=false`
signifiant que ce ticket ne peut être release candidate — on ne doit pas poser un tag sur son commit le plus élevé dans l'historique.
A l'inverse, si ce n'est pas le cas, on édite ainsi les champs :
- `Impropre=false`
- `SafeToDeploy=true`
Dans quelques jours, on supprimera l'utilisation du champ `Impropre`.
=> (BSR) ci: update Jira issue SafeToDeploy value

pro/src/pages/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx, pro/src/screens/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreation.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28921
**Objectif**
A la création d'une offre vitrine, on voit une notification d'erreur au moment de cliquer sur "Publier une offre", parce qu'il manque un early return, et l'appel pour l'offre réservable se fait en arrière plan et échoue.
=> (PC-28921)[PRO] feat: Dont patch offer on publish template offer.

api/src/pcapi/algolia_settings_offers.json
Ajout des labels GTL et des critères d'accessibilité des lieux en tant que `facet` dans la config Algolia
=> (BSR) feat: add gtl and facets to algolia config

pro/src/app/App/App.tsx, pro/src/app/__specs__/App.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28905
**Objectif**
Désactiver firebase et beamer par défaut sur l'iframe adage
=> (PC-28905)[PRO] fix: Disable firebase on adage iframe.

pro/src/components/StocksEventList/__specs__/StocksEventList.spec.tsx, pro/src/utils/__specs__/timezone.spec.ts, pro/src/utils/timezone.ts
Le code source n'est pas problématique : on veut effectivement convertir le temps de la TZ du lieu en UTC donc potentiellement le décalage est -1 u -2 suivant la date.
=> fix de la date dans les tests
=> (BSR)[PRO] fix: tests on master

api/src/pcapi/routes/adage_iframe/favorites.py, api/tests/routes/adage_iframe/get_favorites_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26162 
Légère correction : renvoyer un code d'erreur 403 au lieu de 400 si l'utilisateur n'est pas lié à un établissement (`uai` absent du _token_ d'authentification).
=> PC 26162 eac fix error code

helmfile.yaml
À merger **avant** la MES, une fois confirmé le bon fonctionnement sur testing.
---
This version adds a new deployment/service/ingress for the new API
recommendation proxy routes.
=> (BSR)[API] chore: Bump Helm chart to 0.25.0

pro/src/components/Header/Header.tsx, pro/src/components/SideNavLinks/SideNavLinks.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/DomainsCard/DomainsCard.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/VenueCard/VenueCard.tsx, pro/src/pages/SignupJourneyRoutes/SignupJourneyRoutes.tsx, pro/src/pages/Sitemap/Sitemap.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28946
**Objectif**
Ne pas laisser les `NavLink` `react-router` ajouter de `aria-current="page"` sur les liens qui ne correspondent pas à la page actuelle (ex: liens de déconnexion) parce que c'est mal interprété par les lecteurs d'écrans.
Ca n'arrive pas sur les `<Link>` (la seule différence avec le NavLink étant le isActive dispo dans les class). J'ai donc remplacé les NavLink par des Link partout où les isActive n'est pas utile, et où le `aria-current="page"` est inadapté.
=> (PC-28946)[PRO] feat: Remove aria-current attribute from logout links.

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/create_users_and_offerers.py
Corriger des incohérences dans la sandbox EAC, régression apportée par le commit https://github.com/pass-culture/pass-culture-main/commit/631304438e533f4e70ca31113a58987d63dfd61f
Avant (capture d'écran :copyright: @Vencespass )
Après correction :
=> (BSR)[API] test: fix EAC offerers/venues in sandbox

api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/src/pcapi/routes/backoffice/templates/collective_offer_template/list.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/list.html, api/src/pcapi/routes/backoffice/templates/offer/list.html, api/src/pcapi/routes/backoffice/templates/venue/list.html
- Requested limit is not always 100
- utils.limit_rows already shows a flash message to notify users that results are truncated
Clarifier l'affichage du nombre de résultats dans le BO
=> (BSR)[BO] fix: '1234+ résultats' displayed when 1234 more than 100 rows are returned

api/src/pcapi/core/educational/commands.py
The `synchronize_venues_from_adage_cultural_partners` was missing a commit at the end of its execution.
=> (PC-29017)[ADAGE] fix: ensure to commit while sync with adage

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240403T063928_edb5d745e273_index_address_related_fk.py, api/src/pcapi/alembic/versions/20240403T134107_0dc3123e5ede_index_for_offer.py, api/src/pcapi/core/offers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28637
Ajout des indes pour les colonnes Offer.offererAddressId & Stock.offererAddressId
=> (PC-28637)[API] feat: Adding index for Adress related fk

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/external/automations/user.py, api/src/pcapi/core/external/commands/update_sendinblue_batch_attributes.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/mails/transactional/users/online_event_reminder.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/core/search/staging_indexation.py, api/src/pcapi/core/users/api.py, api/src/pcapi/core/users/models.py, api/src/pcapi/core/users/repository.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/institutional/playlist.py, api/src/pcapi/scripts/external_users/sendinblue_batch_update_user_attributes.py, api/src/pcapi/scripts/fix_pro_roles.py
Un petit pas de plus sur les `type: ignore` autour des propriétés hybrides sqlalchemy.
=> (BSR)[API] chore: remove type: ignore [attr-defined] on boolean hybrid properties

api/src/pcapi/core/users/repository.py, api/tests/routes/native/v1/authentication_test.py
To prevent user enumeration attacks by comparing server response time,
a dummy password must be hashed when the email or the password does not exist.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29049
=> (PC-29049)[API] fix: empty password user login

pro/cypress/e2e/adageSaveFilter.cy.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/__specs__/Autocomplete.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/store/adageFilter/reducer.ts, pro/src/store/adageFilter/selectors.ts, pro/src/store/rootReducer.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28842
Lorsque l'on met des filtres et que l'on change de page, on souhaite garder les filtres en mémoire et les réafficher dès que l'on revient sur la page
=> (PC-28842)[PRO] feat: save filter in adage

api/src/pcapi/connectors/api_adresse.py, api/src/pcapi/scripts/venue/fix_ban_ids.py, api/tests/connectors/api_adresse/api_adresse_test.py, api/tests/connectors/api_adresse/fixtures.py, api/tests/scripts/venue/fix_ban_ids_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-28450
Cette PR ajoute un script qui permet de corriger une partie des venues permanentes avec un `banId` vide ou erroné.
Elle fait suite à 2 PR qui pourront probablement être fermées après le merge de cette PR :
- https://github.com/pass-culture/pass-culture-main/pull/9484
- https://github.com/pass-culture/pass-culture-main/pull/11000
Ce script se déroule en 5 étapes :
1) Récupération des venues permanentes, soit à partir d'un export JSON soit à partir de la DB.
2) Appel à l'endpoint `/search/csv` de l'API Adresse pour rechercher les venues permanentes dans la Base Adresse Nationale (BAN).
La recherche s'effectue en 1 seul appel, qui prend entre 20 et 40 secondes.
Le terme de recherche (appelé `q`) est formé à partir de l'adresse …
=> (PC-28450)[API] fix: Add script to fix missing or wrong ban_id in permanent venues

api/src/pcapi/connectors/serialization/allocine_serializers.py, api/tests/domain/allocine_test.py, api/tests/domain/fixtures.py, api/tests/providers/allocine_movie_list_test.py
Des erreurs Sentry nous remontent que certains champs ne sont parfois pas renseignés dans les informations que nous envoie Allociné. On préfère enregistrer des données moins complètes que de faire crasher la synchro. On rend donc le typage plus permissifs.
=> (BSR)[API] feat: make allocine movie lists and production year nullable

api/src/pcapi/routes/serialization/bookings_recap_serialize.py, api/tests/routes/pro/get_all_bookings_test.py
Fixing the bug introduced during the refactoring of the serialization of the `get_bookings_pro` #11055 which was returning a "confirmed" status for all non-cancelled and unreimbursed bookings. The "confirmed" status should only apply to event offers that can still be canceled. "booked" is the correct status for physical offers."
=> (BSR)[API] fix: serialize bookingStatus in get bookings pro with the right status for booked things

api/src/pcapi/connectors/ems.py, api/src/pcapi/connectors/serialization/ems_serializers.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/ems/client.py, api/src/pcapi/core/external_bookings/ems/constants.py, api/src/pcapi/models/feature.py, api/src/pcapi/scheduled_tasks/commands.py, api/tests/core/bookings/test_api.py, api/tests/core/external_bookings/ems/test_client.py
Revert "Revert "(PC-27999)[API] feat: Cancel failing EMS external bookings"" 
This reverts commit aa06d4bd565c98d17e303124cfb3d5f48af9ebad.
and add a FF over the all feature
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27999
=> (PC-27999)[API] feat: Cancel failing EMS external bookings

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240411T075644_f77615489a01_delete_public_api_ffs.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/models/feature.py, api/src/pcapi/routes/public/individual_offers/v1/blueprint.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/get_product_test.py, api/tests/routes/public/individual_offers/v1/patch_event_test.py, api/tests/routes/public/individual_offers/v1/post_event_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28915
Delete these FFs : 
WIP_ENABLE_EVENTS_WITH_TICKETS_FOR_PUBLIC_API
WIP_ENABLE_OFFER_CREATION_API_V1 
ENABLE_CHARLIE_BOOKINGS_API
=> (PC-28915)[API] chore: delete 3 unused feature flag

api/gunicorn.conf.py, api/src/pcapi/utils/kubernetes.py, api/tests/utils/kubernetes_test.py
Ticket : https://passculture.atlassian.net/browse/PC-29171
Seul le dernier commit est à relire. Les 2 commits m'ont servi à tester et ne seront pas mergés.
Démo (où j'ai ajouté une route `/slow?{x}` qui attend x secondes avant de rendre la main, et où la fenêtre de droite montre la valeur des métriques en temps (presque) réel. Et machine s'appelle "labit", d'où le nom de la métrique) :
[Capture vidéo du 2024-04-11 10-01-56.webm](https://github.com/pass-culture/pass-culture-main/assets/471321/ebcc63dc-99b0-4ba5-aadd-f2153eda0698)
=> (PC-29171)[API] feat: Export new Gunicorn metrics to Prometheus

api/gunicorn.conf.py
Some of our Kubernetes deployments contain "-" characters, which
cannot appear in the name of a Prometheus metric. (It's even a bit
more strict [1], but our deployments generally conform, except for the
"-".)
[1] https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
=> (PC-29171)[API] fix: Fix name of Prometheus metric

pro/src/pages/VenueEdition/OpeningHoursForm/HourLine.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28894
on reset les erreurs des deux champs heures avant de les afficher (pour qu'elles n'apparaissent pas)
=> (PC-28894)[PRO] feat: reset errors in Hour for OpeningHours

api/src/pcapi/alembic/versions/20240411T121621_ed9648801317_add_validationauthor_column_for_booking_table.py
BSR 
fix broken migration on "add validationAuthor column for Booking table"
remove if_not_exists argument
=> (BSR)[API] fix: repair broken migration

pro/src/app/AppLayout.module.scss, pro/src/components/ImageUploader/ButtonImageEdit/ButtonImageEdit.module.scss, pro/src/components/ImageUploader/ImageUploader.module.scss, pro/src/components/SoftDeletedOffererWarning/SoftDeletedOffererWarning.module.scss, pro/src/components/Tutorial/Tutorial.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscoveryBanner/AdageDiscoveryBanner.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.module.scss, pro/src/pages/Home/Card.module.scss, pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss, pro/src/pages/Offers/Offers/OffersStatusFiltersModal/OffersStatusFiltersModal.module.scss, pro/src/ui-kit/ListIconButton/ListIconButton.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29198
**Objectif**
La fonction css `color-mix` étant pas encore super bien supportée, j'ai trouvé une autre solution en utilisant `rgb`. L'idée est que `rgb` ne fonctionne pas avec les variables de couleur css lorsque celles-ci sont en hexa, mais fonctionne si elles sont en rgb. 
❌ `rgb(var(--color-input-text-color), 48%);`
✅ `rgb(from var(--color-input-text-color) r g b / 48%);`
=> (PC-29198)[PRO] fix: Dont use color-mix and use rgb instead.

pro/src/pages/Home/Offerers/VenueCreationLinks.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28935
Supprimer le bloc 'Ajouter un lieu' qui ne devrait plus être utilisé maintenant qu'on a les prochaines étapes directement dans les cartes lieux, et qu'un lieu est automatiquement créé à la création d'une structure. 
| Avant | Après | 
| ------ | ------ |
| ![Capture d’écran 2024-04-12 à 08 57 18](https://github.com/pass-culture/pass-culture-main/assets/71768799/3b03d8a3-b61f-4694-9b86-fdd67fb0407e) | ![Capture d’écran 2024-04-12 à 08 58 09](https://github.com/pass-culture/pass-culture-main/assets/71768799/d864969b-773b-4e02-9626-3bc3b2210064) |
=> (PC-28935)[PRO] feat: remove add venue card in homepage

pro/src/pages/CsvTable/CsvTable.tsx, pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/ui-kit/Button/ButtonLink.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28998
Afficher les détails de remboursements dans un nouvel onglet sans le header quand le FF WIP_ENABLE_PRO_SIDE_NAV est activé
=> (PC-28998)[PRO] feat: display csv table in new tab when ff is active

pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss, pro/src/components/ActionsBarSticky/ActionsBarSticky.tsx, pro/src/screens/SignupJourneyForm/ActionBar/ActionBar.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29223 
Fix l'affichage de la sticky bar avec la nouvelle interface : 
- Alignement des boutons à gauche pour être alignés avec le contenu
- Gestion du responsive pour que la barre ne passe pas sous la sideNav
=> (PC-29223)[PRO] fix: fix sticky bar with side nav

pro/src/components/Banner/BannerInvisibleSiren.module.scss, pro/src/components/Banner/BannerInvisibleSiren.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28994
Ajouter une marge en dessous de la bannière SIRET/SIREN Invisible dans le parcours d'inscription. En local, testable avec un SIRET/SIREN commencant par 9 (ex : 999 999 999 12345). En testing il faut trouver un siret non diffusible. 
Screen
=> (PC-28994)[PRO] fix: add missing margin between siren banner

pro/src/app/AppLayout.module.scss, pro/src/app/AppLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29205
Fix l'espace en dessous du contenu quand la sticky bar est affichée mais que la nouvelle interface n'est pas active
=> (PC-29205)[PRO] fix: fix padding for old interface in stock edition

api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py, api/src/pcapi/routes/backoffice/templates/collective_offer/list.html, api/tests/routes/backoffice/collective_offers_test.py
- CI - verte 
cas de test détecté: 
cas visible -> si authentification avec utilisateur fraud
cas invisible -> si authentification avec utilisateur non fraud
=> (PC-29204)[BO] feat: fraud team can now see price in collective offerlist

api/src/pcapi/local_providers/allocine/allocine_stocks.py, api/src/pcapi/local_providers/cinema_providers/boost/boost_stocks.py, api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py, api/src/pcapi/local_providers/cinema_providers/cgr/cgr_stocks.py, api/tests/local_providers/cinema_providers/boost/boost_stocks_test.py, api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py, api/tests/local_providers/cinema_providers/cgr/cgr_stocks_test.py, api/tests/local_providers/cinema_providers/ems/ems_stocks_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28957
- Amélioration des _query_ pour trouver le produit. On faisait anciennement un `cast` ce qui empêcher d'utiliser l'index sur `allocineId`
- Même avec le FF `WIP_SYNCHRONIZE_CINEMA_STOCKS_WITH_ALLOCINE_PRODUCTS` désactivé, rattachement des offres à un produit s'il existe.
- Même si le produit n'existe pas, on veut au moins enregistrer l'`allocineId` et/ou le `visa` si possible
- Uniformisation des fonctions `update_from_movie_information` dans les différentes synchro
=> PC-28957 synchro cine change condition on product attachment

.github/workflows/dev_on_dispatch_release_deploy.yml
Pour une raison qui m'échappe, le workflow de déploiement n'est pas en échec [quand le 1er step est en échec](https://github.com/pass-culture/pass-culture-main/actions/runs/8664779128/job/23761986240#step:6:17), et l'utilisation de `if: success()` conduit à un résultat inattendu car la condition est évaluée à `true`.
On utilise grâce à ce changement la variable d'environnement du workflow `WORKFLOW_CONCLUSION`.
=> (BSR) ci: use a more robust condition for a slack notification step

api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v2/account.py, api/tests/routes/native/v2/account_test.py
Raising an error, if a user tries to change their email to an existing one, makes the app vulnerable to user enumeration attacks.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29228
=> (PC-29228)[API] fix: silence error when user selects an existing mail

.github/dependabot.yml
`boto3` is a Python library that is released _very_ frequently. I have
counted 29 releases in the last 40 days. [1] Dependabot happily
creates a pull request for each release, resulting in a pull request
almost every day.
But `boto3` is a large library, from which we only use S3-related
features. Most of these release don't impact these features, which
means that most releases are insignificant to us. Still, we have to
manually check the changelog and approve the pull request. Almost
every day.
With this commit, we make Dependabot suggest an update of `boto3` once
a week at most.
[1] https://pypi.org/project/boto3/#history
=> (BSR)[API] ci: Don't accept Dependabot pull requests every day for boto3

pro/src/components/SummaryLayout/SummaryLayout.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOffer.module.scss, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/AdageOfferDetailsSection.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferDetailsSection/AdageOfferInfoSection.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCardContent/AdageOfferListCardContent.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCardContent/AdageOfferListCardContent.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCardContent/__specs__/AdageOfferListCardContent.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28960
Permettre des sauts de ligne et augmenter les espaces entre les lignes pour améliorer la lisibilité des offres
=> (PC-28960)[PRO] feat: allow line break and increase line height in offer description and price info

.github/dependabot.yml
The previous version of the configuration failed with the following
error:
Update configs must have a unique combination of
'package-ecosystem', 'directory', and 'target-branch'
To avoid that, apply the workaround that has been suggested here:
https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
=> (BSR)[API] fix: Work around uniqueness requirement in Dependabot configuration

pro/vite.config.ts
BSR
enlever ce warning 
```
cache.dir" is deprecated, use Vite's "cacheDir" instead if you want to change the cache director. Note caches will be written to "cacheDir/vitest"
```
=> (BSR)[PRO] fix: remove cache warning in test

api/src/pcapi/core/mails/transactional/pro/invoice_available_to_pro.py
When trying to generate invoices on the 16th of the month (which happens running the sandbox today), we are facing a bug when try to send invoice notifications. `period_start` and `period_end` would be equals (both having the day part assign at 16). Moreover, when defining `invoice_timespan` with `min.time()` for both values we now have a lower bound strictly equals to the upper bound. Nothing can match, contains or even overlaps that kind of interval !
Hence the fix, we want the lower bound to be defined with `min.time()` and the upper one with the time part of the cutoff. So we have at least a few hours between each bounds.
=> (BSR)[API] fix: Invoice generation on the 16th

api/src/pcapi/connectors/cgr/cgr.py
We need to wait a little longer than the value we send them Otherwise, for attempts very (very) close to the value of `CGR_TIMEOUT` they might consider the booking as valid on their side while on ours, the duration of the attempt + delay of the HTTP request + delay of HTTP response could exceed the `CGR_TIMEOUT` value
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29253
=> (PC-29253)[API] fix: Wait a little longer than the value sent to CGR

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/FiltersTags.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/FiltersTags/__specs__/FiltersTags.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/OfferFilters.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OfferFilters/__specs__/OfferFilters.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSuggestions/OffersSuggestions.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/__spec__/OffersSearch.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/__specs__/utils.spec.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29294
**Objectif**
Corriger le bug suivant : Quand on filtre sur un domaine artistique dans ADAGE qui ne donne pas de résultats, qu'on navigue vers la page découverte, et qu'on clic sur une carte de lieu (qui a des offres) , on est redirigé vers la recherche mais aucun résultat ne s'affiche alors que seul le lieu apparait filtré.
-> Faire en sorte que les filtres envoyés à react-instansearch via `<Configure>` soient les mêmes que ceux passés aux Offres et aux filtres.
=> Pc 29294 fix adage filters on redirect

pro/src/pages/VenueEdition/OpeningHoursForm/OpeningHoursForm.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28894
on veut enlever les erreurs sur le champ quand il disparait
=> (PC-28894)[PRO] fix: reset errors in OpeningHourForm

pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.admin.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/Offers/__specs__/Offers.admin.spec.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx
BSR
bon j'ai pas trop trouvé la raison donc : 
- split des tests pour isoler les tests admin
- comme ça semble plus concerner les waitForElementToBeRemoved je les ai remplécé par des waitFor
=> (BSR)[PRO] fix: attempt to fix flaky tests in offers

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/forms/utils.py, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/backoffice/venues/forms.py, api/tests/routes/backoffice/venues_test.py
But: ajouter un champ dans l'édition des lieux qui permette d'ajouter un URL d'acceslibre, qui peux forcer la MAJ des données d'accessibilité.
J'ai une page sur acceslibre, mais mes données n'apparaissent pas côté PC (ce qui arrive si le matching n'a pas marché). En entrant cet url, on récupère le slug et les données d'accessibilité du lieu
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28385
=> (PC-28385)[BO] feat: add acceslibre url in BO to edit venue

api/src/pcapi/core/educational/api/adage.py, api/src/pcapi/core/educational/commands.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29159 
Des lieux ne semblent pas être mis à jour lors de la synchronisation. Cette PR propose deux choses : ajouter les lieux à la session en cours et ajouter des logs de debug (affichés en fonction d'une variable).
⚠️ Je n'ai aucune garantie que cela corrigera le bug. Si le problème persiste, nous aurons alors des outils à disposition pour essayer d'y voir plus claire - et exclu la piste des objets en dehors de la session SQLA.
La liste des lieux à mettre à jour est récupérée en dehors du bloc `atomic()`. Cela ne devrait rien changer mais on ne sait jamais, autant ajouter chacun explicitement.
=> PC 29159 bug eac improve venue sync

api/src/pcapi/core/offers/validation.py, api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29229
Bug : l'api collective n'autorisait pas la création d'offre collective s'il n'y avait pas de dispositif national... alors que cette information devrait être optionnelle. Pour être exact, le code aujourd'hui permet de se passer du dispositif national, à condition de renseigner une liste de domaines éducatifs inconnus.
Fix : autoriser l'absence de dispositif national dans la fonction de validation
Ajout de quelques tests (avec un petit peu de nettoyage) afin de s'assurer qu'il est toujours possible de créer une offre collective avec le minimum d'information possible.
=> (PC-29229)[EAC] fix: coll. api: national program should not be mandatory

api/src/pcapi/utils/secrets.py
It will be used as a Kubernetes init container to block the
initialization of a pod if a secret is missing.
---
Tickets : [PC-29313](https://passculture.atlassian.net/browse/PC-29313) pour cette commande, [PC-28437](https://passculture.atlassian.net/browse/PC-28437) pour le fonctionnement général.
[PC-29313]: https://passculture.atlassian.net/browse/PC-29313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PC-28437]: https://passculture.atlassian.net/browse/PC-28437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-29313)[API] feat: Add new `flask check_secrets` command

pro/.storybook/preview.tsx, pro/src/styles/variables/_themes.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29306
**Objectif**
Ajouter le thème dans la preview storybook.
=> (PC-29306)[PRO] feat: Add css theme to the preview in storybook.

pro/src/components/AccessibilitySummarySection/AccessibilitySummarySection.tsx, pro/src/components/IndividualOfferForm/Accessibility/__specs__/Accessibility.spec.tsx, pro/src/components/IndividualOfferForm/Accessibility/constants.ts, pro/src/components/IndividualOfferForm/UsefulInformations/Venue/__specs__/VenueAccessibilityUpdates.spec.tsx, pro/src/components/IndividualOfferForm/types.ts, pro/src/components/IndividualOfferForm/utils/__specs__/setInitialFormValues.spec.ts, pro/src/components/IndividualOfferForm/utils/setInitialFormValues.ts, pro/src/core/OfferEducational/types.ts, pro/src/core/OfferEducational/utils/buildStudentLevelsMapWithDefaultValue.ts, pro/src/core/Offers/adapters/createIndividualOffer/serializers.ts, pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/serializers.spec.ts, pro/src/core/Offers/adapters/updateIndividualOffer/__specs__/updateIndividualOffer.spec.ts, pro/src/core/Offers/adapters/updateIndividualOffer/serializers.ts, pro/src/core/shared/constants.ts, pro/src/core/shared/types.ts, pro/src/hooks/useAccessibilityOptions.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersInstantSearch.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/__specs__/CollectiveDataForm.spec.tsx, pro/src/pages/VenueCreation/Accessibility/__specs__/Accessibility.spec.tsx, pro/src/pages/VenueCreation/constants.ts, pro/src/pages/VenueCreation/types.ts, pro/src/pages/VenueEdition/__specs__/setInitialFormValues.spec.tsx, pro/src/pages/VenueEdition/setInitialFormValues.ts, pro/src/pages/VenueEdition/types.ts, pro/src/ui-kit/AccessibilityLabel/AccessibilityLabel.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29134
Afficher les options des écoles à Marseille dans la liste "Public cible" sur la page partenaire quand le FF WIP_ENABLE_MARSEILLE est activé.
=> (PC-29134)[PRO] fix: show marseille levels in venue edition

api/src/pcapi/core/users/repository.py, api/src/pcapi/routes/pro/users.py, api/src/pcapi/routes/serialization/users.py, api/tests/routes/pro/post_user_new_pro_nav_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/SubmitReviewRequestModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.module.scss, pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.tsx, pro/src/components/NewNavReview/NewNavReviewDialog/__specs__/NewNavReviewDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28494
Logger les informations du formulaire de review de la nouvelle interface lorsque l'utilisateur clique sur `Envoyer`. 
Afficher un message de confirmation si l'envoie des données s'est bien passé
Sinon afficher un message d'erreur
| Formulaire |  Confirmation | 
| ---------- | ------------ |
| ![Capture d’écran 2024-04-18 à 09 30 01](https://github.com/pass-culture/pass-culture-main/assets/71768799/c0941206-5443-4047-8921-eeed15c39c3b) | ![Capture d’écran 2024-04-18 à 09 30 08](https://github.com/pass-culture/pass-culture-main/assets/71768799/4294b0f9-4512-4841-87a8-0ea766852d52) |
=> (PC-28494)[API/PRO] feat: Submit users new nav reviews

api/poetry.lock, api/pyproject.toml, api/src/pcapi/flask_app.py
It won't work like that. 
To be able to export data to prometheus we need to create a new service to expose the new metrics route.
=> (BSR)[API] revert: remove rq_exporter

api/src/pcapi/routes/native/v1/serialization/subscription.py, api/src/pcapi/routes/native/v1/subscription.py, api/src/pcapi/serialization/decorator.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/subscription_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21409
Les routes `/next_step/` et `/stepper` étaient redondantes. On les déprécie donc au profit d'une v2 de la route `/stepper` contenant toutes les infos nécessaires à l'app dans le parcours d'activation.
=> PC-21409 remove route next step

.github/workflows/dev_on_dispatch_release_deploy.yml
Le secret n'était pas récupéré, donc la notification ne pouvait être envoyée.
Au lieu de réparer, on revert cet envoi, car on ne veut pas que le reste du workflow soit bloqué par l'échec de cette notification, quelle qu'en soit la raison.
=> (BSR) fix: revert unnecessary Slack notification

api/src/pcapi/routes/native/v1/serialization/offerers.py, api/tests/routes/native/v1/offerers_test.py
The line `venue.venueTypeCode = venue.venueTypeCode.name` changes the value in the object and breaks any property using the venueTypeCode (i.e. bannerUrl)
using a getter dict we avoid actally changing the python object, and keep bannerUrl safe
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29327
=> (PC-29327)[API] fix: use getter dict instead of orm override to avoid changing the venue object

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/models/OfferFavoriteBody.ts, pro/src/apiClient/adage/models/OfferIdBody.ts, pro/src/apiClient/adage/models/StockIdBody.ts, pro/src/apiClient/adage/models/TrackingCTAShareBody.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28871
Ajout d'un champ optionnel `vueType` pour certaines routes de _tracking_ de l'iframe adage : détail d'une offre, mise en favori et partage.
=> (PC-28871)[EAC] feat: adage iframe: tracking: add vueType

api/src/pcapi/routes/backoffice/templates/collective_offer/list.html
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29204
- CI - verte 
=> (PC-29204)[BO] fix: fraud team can now see price in collective offer price written in one line now

api/src/pcapi/routes/backoffice/templates/components/links.html, api/src/pcapi/routes/backoffice/templates/venue/get.html, api/src/pcapi/routes/backoffice/venues/forms.py
Position de l'url d'acceslibre dans la modale d'édition de lieux + ajout à virus total
Egalement un petit ajout de la `bi-box-arrow-up-right` aux liens vers les sites web vérifiés par virus total
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28385
=> (PC-28385)[BO] refactor: move to end of modal acceslibre url and add it to virustotal

api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/serialization/base.py, api/src/pcapi/utils/date.py, api/tests/routes/backoffice/venues_test.py, api/tests/routes/pro/patch_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29348
Pour la relecture: le type ignore est dû au validateur `convert_to_numeric_ranges` de `OpeningHoursModel`
=> WIP (PC-29348)[API] fix: opening hours weekday wrong serialization

pro/cypress/e2e/adageSaveFilter.cy.ts, pro/src/hooks/useMediaQuery.tsx, pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/__specs__/OfferCard.spec.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/ClassroomPlaylist/ClassroomPlaylist.tsx, pro/src/pages/AdageIframe/app/components/AdageDiscovery/Playlist/NewOfferPlaylist/NewOfferPlaylist.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCardContent/AdageOfferListCardContent.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSuggestions/__specs__/OffersSuggestions.spec.tsx, pro/src/pages/AdageIframe/app/components/ToggleButtonGroup/ToggleButtonGroup.tsx, pro/src/pages/AdageIframe/app/components/ToggleButtonGroup/ToggleButtonGroupButton/ToggleButtonGroupButton.tsx, pro/src/store/adageFilter/reducer.ts, pro/src/store/adageFilter/selectors.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29154
Si le FF est activé : WIP_ENABLE_ADAGE_VISUALIZATION
On a un bouton pour trigger le mode de vue
Ajout d'un mode vue en grille, on veut afficher un nombre x d'offre en fonction de la taille d'écran de l'utilisateur
Changement de liste à vue automatiquement lorsque l'écran est petit
=> (PC-29154)[PRO] feat: adapt search vue to implement grid vue

pro/src/index.tsx
- Le chargement de hotjar n'était pas géré par oréjime en prod.
=> (BSR)[PRO] fix: Hotjar should be loaded according to user consent.

pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28869
Ajouter un tracker pour savoir si on a cliqué sur le bouton pour switch de vue sur la page de recherche adage
=> (PC-28869)[PRO] feat: add tracker for switch vue button

api/src/pcapi/core/educational/adage_backends/__init__.py, api/src/pcapi/core/educational/adage_backends/adage.py, api/src/pcapi/core/educational/adage_backends/base.py, api/src/pcapi/core/educational/adage_backends/logger.py, api/src/pcapi/core/educational/adage_backends/testing.py, api/src/pcapi/core/educational/api/adage.py, api/src/pcapi/core/educational/api/address.py, api/src/pcapi/core/educational/commands.py, api/src/pcapi/core/educational/testing.py, api/src/pcapi/utils/date.py, api/tests/core/educational/api/test_address.py, api/tests/core/educational/api/test_synchronize_adage_ids_on_venues.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28655
Demander la synchronisation des lieux ayant été modifiés récemment au lieu de télécharger les données de tous les lieux connus d'Adage.
Avant : tous les lieux qui avaient un adageId mais qui ne faisaient pas partie des lieux actifs et synchronisés par Adage perdaient leur id Adage (dans notre base de données).
Problème : si les mises à jours deviennent partielles, on se retrouverait avec un grand nombre de lieux retirés d'Adage dans notre base de données.
Solution : ne retirer que les lieux qui sont devenus non-synchronisés par Adage, ou inactif ou dont l'id adage ne correspond plus.
=> (PC-28655)[EAC] feat: sync only recent updates

api/src/pcapi/core/educational/repository.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/routes/adage_iframe/playlist_test.py
34cc9af154e687f9db92c55f6dda1629df0e8783 missed the fact that the randomized playlist was then queried without randomize through
Strangly, the tests reported random results while "real life" showed they were not random at all - 20 requests gave the same results.
This commits ensures we properly randomize this playlist
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29008
=> (PC-29008)[ADAGE] fix: randomize venue playlist for adage

pro/src/pages/VenueEdition/OpeningHoursForm/HourLine.tsx, pro/src/pages/VenueEdition/OpeningHoursForm/__specs__/OpeningHoursForm.spec.tsx, pro/src/pages/VenueEdition/setInitialFormValues.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28894
Toutes les erreurs du formulaire ne s'affichaient pas au submit, 
j'ai pas hyper bien compris pourquoi le fix fixe, le prblème venait de formik qui ne mettait pas ces champs isTouched=true
=> (PC-28894)[PRO] fix: OpeningHoursForm show all errors

api/src/pcapi/core/finance/api.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/routes/backoffice/finance/forms.py, api/src/pcapi/routes/backoffice/finance/validation.py, api/src/pcapi/routes/backoffice/templates/collective_bookings/list.html, api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html, api/tests/core/finance/test_api.py, api/tests/core/users/test_models.py, api/tests/routes/backoffice/finance_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28786
Prise en charge de la création de gestes commerciaux sur le BO
- Réservations collectives :
- Réservations individuelles :
=> (PC-28786)[BO] feat: finance - reintroduce commercial gesture creation

pro/src/app/App/App.tsx, pro/src/app/AppRouter/AppRouter.tsx, pro/src/pages/Home/Homepage.tsx, pro/src/pages/Home/__specs__/Homepage.spec.tsx, pro/src/pages/SignIn/SignIn.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29224
Réduire les rerenders et fix les effets "clignotement" sur le portail pro.
- Déplacement de la gestion des thèmes dans App pour éviter de recréer le router à chaque changement de thème. 
- Supprimer un window.reload pour mettre à jour l'interface de manière plus naturel et ne pas afficher la bannière de bienvenue tant que la nouvelle interface n'est pas affichée
- Redirection vers la homepage au Signin pour éviter que l'AppLayout soit rerendu : `navigate` ne fonctionne pas ici car appellé après le rerender du composant
=> Pc 29224 reduce app rerenders

pro/src/ui-kit/Button/Button.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29295
Dedant le scss ` &.button-**disabled** { `
il y a maintenant  un nouveau type de `.button-icon {` de couleur grey-dark 
et white d'avant. 
Pas actif:
Actif:
=> (PC-29295)[PRO] style: Picto gris sur bouton de CTA

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/connectors/serialization/acceslibre_serializers.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/commands.py, api/src/pcapi/sandboxes/scripts/mocks/accessibility_mocks.py, api/tests/connectors/acceslibre/acceslibre_test.py, api/tests/connectors/acceslibre/fixtures.py, api/tests/core/offerers/test_api.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/pro/get_venue_test.py, api/tests/routes/pro/get_venues_test.py, pro/src/apiClient/v1/models/AudioDisabilityModel.ts, pro/src/apiClient/v1/models/VisualDisabilityModel.ts, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.module.scss, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.tsx, pro/src/pages/VenueEdition/AccesLibreSection/__specs__/AccesLibreSection.spec.tsx
1er commit: changement des champs audio description et deaf and hard of hearing pour renvoyer une liste au front
2e commit: last update est désormais renvoyé par la route widget chez acceslibre 
3e commit: disposition des champs listés sur plusieurs lignes
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29277
=> (PC-29267)[API] feat: adapt acceslibre widget results

api/src/pcapi/core/educational/commands.py
log_cron_with_transaction will only commit IF the session is dirty Since synchronize_adage_ids_on_venues changes are wrapped inside an atomic all the changes are pushed to the DB and the session is cleaned which will NOT trigger the log_cron_with_transaction session's commit and will loose all the changes.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29436
=> (PC-29436)[ADAGE] fix: commit the adage venue synchronization

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/history/api.py, api/src/pcapi/core/logging.py, api/src/pcapi/core/users/models.py, api/src/pcapi/routes/pro/users.py, api/src/pcapi/utils/login_manager.py, api/tests/core/history/test_api.py, api/tests/core/logging/tests.py, api/tests/routes/pro/get_connect_as_test.py, api/tests/routes/pro/patch_offerer_bank_accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28978
Cette PR modifie le connect as pour permetre a un admin de sauter d'un utilisateur a un autre sans devoir se reconnecter a chaque fois avec un compte admin
Cette PR modifie aussi les ActionHistory pour qu'ils gerent le connect as dans pro.
=> Pc 28978 rpa connect as part 2

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240424T133200_833b6aed7272_drop_idx_venue_trgm_name.py, api/src/pcapi/alembic/versions/20240424T133641_0e5b68c5865d_drop_idx_venue_trgm_public_name.py, api/src/pcapi/alembic/versions/20240424T133809_348fd34d687b_drop_idx_offerer_trgm_name.py, api/src/pcapi/core/offerers/models.py
These indexes are no longer used according to a query on pg_stat_user_tables. Indexes using unaccent are used in every filter.
Ticket Jira : https://passculture.atlassian.net/browse/PC-29458
=> (PC-29458)[API] chore: drop deprecated indexes without unaccent

pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/AdageOfferListCard.tsx
This reverts commit cf29626c9ddcff201107ee5ecdc92d4193501e15.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29498
**Objectif**
Revert les changements d'avoir des urls absolues pour les liens vers les offres dans ADAGE.
=> Revert "(PC-29498)[PRO] feat: Use absolute urls in ADAGE offer links."

api/src/pcapi/core/offerers/factories.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/utils/crypto.py, api/tests/utils/crypto_test.py, api/tests/validation/routes/users_authentifications_test.py
L'API publique réalise pour chaque requête une authentification impliquant un delai important du à bcrypt.
Le but de la PR est d'utiliser sha3-512 pour hasher la clé public. Les anciens hash seront converti à la première requête authentifié.
La stratégie [technique ](https://www.notion.so/passcultureapp/Acc-l-rer-le-traitement-des-requ-tes-HTTP-via-cl-d-API-en-changeant-le-stockage-des-cl-s-44071edd8138419c9fcf5816d9c0a0b0#53a1883386984328bc2c3b0ff36cd53b)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29065
=> (PC-29065)[API] feat: Switch to  sha3_512 for public API Hashing

api/src/pcapi/routes/pro/venues.py
joinedload on a reversed FK are not a good idea.
We faced one cas where the offerer had:
- 1500+ pricing_point_links
- 1500+ reimbursement_point_links
Overall, the number of lines returned was 2_427_364 (1500+ * 1500+). Exploses any hope to get a response.
Using selectinload adds two more requests but avoids the combination between the two huge sets.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29511
=> (PC-29511)[PRO] fix: reduce number of lines when fetching venue

api/src/pcapi/routes/adage_iframe/security.py, api/src/pcapi/routes/error_handlers/generic_error_handlers.py, api/tests/routes/adage_iframe/get_authenticate_test.py, api/tests/routes/adage_iframe/get_features_test.py, api/tests/routes/adage_iframe/post_favorite_offer_test.py, api/tests/routes/adage_iframe/post_favorite_template_test.py, pro/scripts/customRequest.ts, pro/src/apiClient/adage/core/request.ts, pro/src/apiClient/v1/core/request.ts, pro/src/apiClient/v2/core/request.ts, pro/src/app/AppRouter/routesMap.tsx, pro/src/pages/AdageIframe/app/App.tsx, pro/src/pages/AdageIframe/app/components/UnauthenticatedError/UnauthenticatedError.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28933
- Gérer le cas où lorsqu'on était rediriger sur /connexion après avoir eu un Unauthorized, sentry envoyait quand même une alerte alors que c'est normal
- Sur adage, lorsque le token expire on gère la redirection sans envoyer d'alerte à sentry car c'est aussi normal
=> (PC-28933)[PRO] fix: sentry ApiError Unauthorized and forbidden

api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/routes/adage_iframe/playlist_test.py, pro/src/apiClient/adage/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29456
Ajouter des nouvelles routes qui renvoient chacune une liste vide.
Ceci permettra à l'équipe front de commencer le travail de leur côté grâce à cette interface
d'API. 
Les corps des fonctions seront remplis bientôt.
=> (PC-29456)[EAC] feat: adage iframe: add two new playlists routes

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/serialization/offerers.py, api/tests/routes/native/openapi_test.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/pro/get_venue_test.py
Cette PR remonte le minimum: le premier utilisateur à créditer pour les photos de maps.
Dans l'écrasante majorité des cas, on en aura qu'un, mais la possibilité de crédit multiple existe (maps envoie une liste)
Dans un soucis de simplicité, on propose cette solution qui reste très proche de l'existant, et on se donne du temps pour voir comment on veut intégrer la potentielle liste d'attributions, sans faire de breaking change compliqué.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29315
=> PC-29315 add credits to google images

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240424T152513_ad995e8eff73_drop_ix_booking_reimbursementdate.py, api/src/pcapi/core/bookings/models.py
This indexe is no longer used according to a query on pg_stat_user_tables
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29465
=> (PC-29465)[API] chore: drop unused booking reimbursement date index

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/exceptions.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/tests/routes/backoffice/individual_bookings_test.py
…eposit is past
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29385
le problème se reproduit lorsqu'un booking est expiré et possède un deposit avec une expirationDate passé par exemple ce booking et deposit qui sont lié, le booking est canceled et le deposit a une expirationDate passé :
Lorsque l'on selectionne ce booking avec ou sans les autres  et que l'on clique sur le bouton pour valider:
il retourne a présent une erreur 400 BadRequest()
- CI - rouge mais cela n'est pas lié a mes modifications le reste est vert 
ajout d'un cas de test retournant une erreur 404 not found si le booking est cancelled avec deposit possedant une expirationDate passé
- …
=> (PC-29385)[BO] fix: fix batch_validate_individual_bookings when deposit is past

pro/src/components/Footer/Footer.module.scss, pro/src/pages/CollectiveOfferEdition/CollectiveOfferEdition.tsx, pro/src/pages/CollectiveOfferStockEdition/CollectiveOfferStockEdition.tsx, pro/src/pages/IndividualOfferWizard/BookingsSummary/BookingsSummary.tsx, pro/src/pages/IndividualOfferWizard/StocksSummary/StocksSummary.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29529
Ajouter la barre d'action sur les pages d'éditions d'une offre indiv (stock/réservations)
=> (PC-29529)[PRO] fix: add missing action bar on offer edition pages

api/src/pcapi/utils/sentry.py
This reverts commit 1a5c0ee33aa9d92963ec1cf07138a688b9ef0176.
It's the only commit i reverted after this PR, the sampling will still be reduced. 
I don't know how the code could work, i can't find what `transaction_context.get("name")` (and sentry sdk devs cannot guarantee it too see [this issue](https://github.com/getsentry/sentry-python/issues/969) and [this PR](https://github.com/getsentry/sentry-docs/pull/2882/files)). If we want to do that again we should do it from the path info `path = sampling_context.get("wsgi_environ", {}).get("PATH_INFO")` like [the example](https://github.com/PostHog/posthog/blob/efbc85b08ee5261d02585bd2908076d6a270d71c/posthog/settings/sentry.py#L75) françois gave.
This is spamming logs, i revert it until we have something working
Ticket Jira (ou description …
=> (PC-29508)[API] feat: Revert add sentry traces sampler

api/tests/routes/pro/signin_test.py
Unit tests fail on Continuous Integration because of commit [786c6583](https://github.com/pass-culture/pass-culture-main/commit/786c65831ad076ee7733382fc59174e798ecf7c1). Objects remain in database, so there is one extra educational institution for all next tests.
Réparer les tests auto
=> (PC-29403)[API] test: fix regression in unit tests

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_build_and_push_docker_images.yml
Paralleliser les builds d'image docker en remplacement de steps sequentielles.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29434
Situation initiale : 
- dev_on_workflow_build_and_push_docker_images.yml est appelle une fois par dev_on_push_workflow_main.yml avec en inputs pcapi/pcapi-console/pcapi-tests true/false
- Les tags sont definis dans dev_on_workflow_build_and_push_docker_images.yml dans chaque step.
Changes list: 
Le workflow dev_on_workflow_build_and_push_docker_images.yml est rendu plus generique et est desormais appelle plusieurs fois par l'ajout de jobs de build supplementaire (1 par image a builder) dans dev_on_push_workflow_main.yml avec en inputs les tags a push et l'image a builder, ce qui permet de paralleliser le call au workflow. …
=> Pc 29434 parallel docker build

pro/src/pages/Signup/SignupContainer/SignupContainer.module.scss, pro/src/pages/Signup/SignupContainer/SignupForm.tsx, pro/src/ui-kit/form/PasswordInput/PasswordInput.module.scss, pro/src/ui-kit/form/PasswordInput/PasswordInput.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27765
Amélioration des spacings sur la page d'inscription.
Before
After
=> (PC-27765)[PRO] fix: improve signup spacings

pro/src/pages/Reimbursements/BankInformations/BankInformations.tsx, pro/src/pages/Reimbursements/ReimbursementsDetails/ReimbursementsDetails.tsx, pro/src/pages/Reimbursements/ReimbursementsInvoices/ReimbursementsInvoices.tsx, pro/src/pages/Reimbursements/__specs__/BankInformations.spec.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementInvoices.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29053
`useOutletContext()` peut être `undefined`
=> (PC-29053)[PRO] fix: useOutletContext is undefined sometimes.

pro/src/components/OfferAppPreview/OptionsIcons/OptionsIcons.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29124
oui:
non:
=> (PC-29124)[PRO] style: Enlever "A deux !" quand l’offre pas duo

api/src/pcapi/routes/serialization/users.py, api/tests/routes/pro/get_user_profile_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29577
Ajout d'un champ `isImpersonated` dans la réponse des routes pro `/current` et `/signin` qui vaut `true` lorsque la session contient une adresse dans `internal_admin_email` (cela signifie que le vrai utilisateur est un compte admin qui vient du backoffice et qu'il a utilisé la fonctionnalité `connect as`).
=> (PC-29577)[PRO] feat: add isImpersonated field to user model

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/finance/factories.py, api/src/pcapi/core/finance/models.py, api/src/pcapi/core/mails/transactional/finance_incidents/finance_incident_notification.py, api/src/pcapi/core/permissions/models.py, api/src/pcapi/routes/backoffice/finance/finance_incidents_blueprint.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py, api/tests/core/finance/test_api.py, api/tests/core/users/test_models.py, api/tests/routes/backoffice/conftest.py, api/tests/routes/backoffice/finance_test.py
Ajout d'une nouvelle permission `VALIDATE_COMMERCIAL_GESTURE` qui autorise exclusivement le role `codir_admin` à valider les gestes commerciaux 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29379
=> (PC-29379)[BO] feat: add VALIDATE_COMMERCIAL_GESTURE permission

pro/src/components/StockFormActions/StockFormActions.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29266
=> (PC-29266)[PRO] style: Ajout padding au hover, modif, stock

pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29558
Enlever l'asterisk dans le dialogue permettant à l'utilisateur de laisser un avis sur la nouvelle interface. Elle n'est pas utile pour l'accessibilité.
=> (PC-29558)[PRO] fix: remove useless asterisk in npp review dialog

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/pro/venues.py, api/src/pcapi/routes/serialization/base.py, api/tests/routes/native/v1/offerers_test.py, api/tests/routes/pro/get_venue_test.py
But: rendre le code sur les horaires d'ouverture plus intelligible (ne plus utiliser opening_days)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28861
=> (PC-28861)[API] refactor: change opening_days to opening_hours

pro/src/components/Newsletter/Newsletter.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29135
=> (PC-29135)[PRO] style: Ajout de padding, image d'accueuil

api/src/pcapi/routes/backoffice/admin/blueprint.py, api/src/pcapi/routes/backoffice/templates/admin/feature_flipping.html, api/src/pcapi/routes/backoffice/templates/layouts/connected.html, api/tests/routes/backoffice/admin_test.py, api/tests/routes/backoffice/helpers/get.py, api/tests/routes/backoffice/helpers/unauthorized.py, api/tests/routes/backoffice/user_generation_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29404
cas 1 : l'utilisateur possède les droits de gestion de role.
cas 2 : l'utilisateur ne possède pas les droits de gestion de role:
- CI - verte 
- lire uniquement les feature flag
- ne peut pas activer un feature flag
- ne peut pas désactiver un feature flag
- auteur du ticket -> OK
- nombre de commit -> OK 
- mettre le ticket en code-review -> OK 
- refresh de la page github -> 
- vérifier la sécurité afin que seul un utilisateur ayant les droit BO puisse entrer cela meme sans les permissions
=> (PC-29404)[BO] feat: feature flag are now visible in read only for authenticate user without permission

.github/workflows/dev_on_push_workflow_main.yml
Restored e2e pro tests if pro folder changes even if pcapi didnt. Tests will then be done using pcapi:latest
=> Modified conditionals for e2e pro tests

api/src/pcapi/routes/adage_iframe/logs.py, api/src/pcapi/routes/adage_iframe/serialization/logs.py, api/tests/routes/adage_iframe/post_logs_test.py, pro/src/apiClient/adage/index.ts, pro/src/apiClient/adage/models/PaginationType.ts, pro/src/apiClient/adage/models/TrackingShowMoreBody.ts, pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx, pro/src/pages/AdageIframe/app/components/Pagination/Pagination.tsx, pro/src/pages/AdageIframe/app/components/Pagination/__specs__/Pagination.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29550
Ajouter une pagination sur adage avec un tracker qui envoie si le bouton suivant ou le bouton précédent a été cliqué
=> Pc 29550 adage pagination

pro/src/screens/IndividualOffer/PriceCategoriesScreen/PriceCategoriesForm.tsx, pro/src/screens/IndividualOffer/PriceCategoriesScreen/__specs__/PriceCategoriesForm.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29516
Le setValues semblait ne servir à rien et écrasait la valeur rentrée dans le prix
=> (PC-29516)[PRO] fix: do not overwrite price when priceCategory deletion

pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx, pro/src/screens/Offers/__specs__/Offers.tracker.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29710
Ne pas afficher le bouton de création d'offre depuis la liste des offres si la structure sélectionnée n'est pas encore validé pour l'utilisateur courant (ex: rattachement non validé pour l'utilisateur)
=> (PC-29710)[PRO] fix: fix creation offer button display condition

pro/src/app/App/layout/Layout.module.scss, pro/src/app/App/layout/Layout.tsx, pro/src/app/App/layout/OldLayout.module.scss, pro/src/app/App/layout/OldLayout.tsx, pro/src/app/App/layout/__specs__/Layout.spec.tsx, pro/src/app/App/layout/__specs__/OldLayout.spec.tsx, pro/src/utils/storeFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29417
Ajout d'une bannière afin de savoir sur quel compte on est connecté via le connect-as
=> (PC-29417)[PRO] feat: connect as

api/src/pcapi/connectors/big_query/queries/__init__.py, api/src/pcapi/connectors/big_query/queries/adage_playlists.py, api/src/pcapi/core/educational/api/playlists.py, api/src/pcapi/core/educational/commands.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/adage_iframe/playlists.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_eac_data/fill.py, api/tests/routes/adage_iframe/playlist_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29485
Ajout du code (complet) pour les deux nouvelles routes d'API (iframe adage).
Pour rappel : une précédente PR avait ajouté ces fonctions dans le seul but d'exposer rapidement une interface API.
=> (PC-29485)[API] feat: adage iframe: fill two new playlists' code

pro/src/components/Header/HeaderDropdown/HeaderDropdown.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29349
Centrer l'icone du bouton de fermeture de la dropdown dans le header. Visible particulière en état focus
=> (PC-29349)[PRO] fix: center close button in header dropdown

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/routes/backoffice/venues/forms.py, api/tests/connectors/acceslibre/acceslibre_test.py, api/tests/routes/backoffice/venues_test.py
Fix d'un bug lorsqu'on essaye de recupérer des infos d'acceslibre depuis le BO (en entrant l'url) si le lieux n'existe pas chez acceslibre
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29790
=> (PC-29790)[BO] fix: should not try to sync wrong url with acceslibre

api/src/pcapi/core/educational/models.py
Ticket Jira (ou description si BSR) : les deux propriétés semblent obsolètes. Mais je fais une PR plus pour être sûr que ça casse rien, j'ai eu des résultats curieux avec mes tests
=> (BSR)[API] chore: remove very old isEducational property

api/src/pcapi/core/offerers/factories.py, api/src/pcapi/routes/adage_iframe/serialization/offers.py, api/src/pcapi/routes/institutional/serializers.py, api/src/pcapi/routes/native/v1/serialization/account.py, api/src/pcapi/routes/native/v1/serialization/bookings.py, api/src/pcapi/routes/native/v1/serialization/favorites.py, api/src/pcapi/routes/native/v1/serialization/offers.py, api/src/pcapi/routes/native/v1/serialization/settings.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/src/pcapi/routes/shared/price.py, api/tests/routes/institutional/playlist_test.py, api/tests/routes/public/individual_offers/conftest.py, api/tests/routes/public/individual_offers/v1/patch_price_category_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29217
Gérer le cas où une catégorie de prix n'existe pas, ou que l'événement en question n'est pas lié à celle-là.
Ajout de tests avec quelques modifications
1. ajout de _fixtures_ dans un nouveau module `conftest` dédié aux routes de l'api individuelle ;
2. ajout de tests qui vérifient principalement des cas d'erreur, dont celui remonté ;
3. permettre de générer des jetons d'authentification plus facilement dans les tests.
=> (PC-29217)[API] feat: handle missing price category and more

api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/offerers/test_models.py, api/tests/routes/pro/get_offer_test.py, api/tests/routes/pro/get_offerer_addresses_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/AddressResponseIsEditableModel.ts, pro/src/apiClient/v1/models/GetIndividualOfferResponseModel.ts
Retourner l'information de l'addresse pour la route /offers/id selon le FF  WIP_ENABLE_OFFERER_ADDRESS
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26152
=>  (PC-26152)[API] feat: return offererAddress of an offer under a FF

pro/src/pages/Home/Homepage.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29677
Ne pas afficher les bannières liées à la structure (en cours de rattachement, en cours de validation, etc ...) avant d'avoir chargé les données. Cela créait un effet de clignotement car on affichait la bannière avant de vérifier les conditions d'affichage.
=> (PC-29677)[PRO] fix: dont display offerer banner before loading data

pro/src/pages/Reimbursements/ReimbursementsDetails/DetailsFilters.tsx, pro/src/pages/Reimbursements/__specs__/ReimbursementDetails.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29725
=> (PC-29640)[PRO] style: Ajout callout, détail de remboursements

api/src/pcapi/routes/public/documentation_constants.py, api/src/pcapi/routes/public/spectree_schemas.py, api/tests/routes/public/blueprint_openapi_test.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/generate_expected_openapi_json.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29922
Nous avons mis en place un test sur le JSON open API généré à partir de spectree afin de vérifier que l'on n'introduit pas de régression dans la documentation Redoc.
Le but de ce ticket est d'ajouter une fonction qui permette de régénérer facilement et proprement le JSON attendu (i.e. sans trailling whitespace et de manière ordonnée pour que le commit de modification soit lisible).
=> (PC-29922)[API] Permettre de facilement corriger les tests portant sur le JSON Open API

api/src/pcapi/routes/pro/finance.py, api/tests/routes/pro/get_combined_invoices_pdf.py
Fix de l'erreur sentry: https://sentry.passculture.team/organizations/sentry/issues/1610680/?project=5&referrer=slack
=> (BSR)[API] fix: throw 424 if download invoice pdf fails

api/src/pcapi/routes/adage_iframe/playlists.py, api/tests/routes/adage_iframe/playlist_test.py
By default, we'll gather the offers within the rurality level and shake the results to avoid leaving the same offer at first place. However, from time to time, the radius is way too narrow or the rurality level is probably inaccurate. In that case, we'll fill the offers with items from nearest to further.
Ticket Jira : https://passculture.atlassian.net/browse/PC-29283
=> (PC-29283)[ADAGE] fix: ensure the playlists have 10 items if possibles

api/Dockerfile
**ATTENTION :** Ne pas merger avant la migration du serveur de prod.
---
Now that we have migrated the server to PostgreSQL 15, we can update
the client, which is installed on "console" pods.
=> (BSR)[API] feat: Update `psql` client from version 12 to version 15

pro/src/pages/CollectiveOfferFromRequest/CollectiveOfferFromRequest.tsx, pro/src/pages/CollectiveOfferStockCreation/CollectiveOfferStockCreation.tsx, pro/src/screens/CollectiveOfferVisibility/CollectiveOfferVisibility.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29984
Vérifier que l'id de la request n'est pas null avant de faire l'appel API
=> (PC-29984)[PRO] fix: dont get collective request when id is null

pro/src/components/Header/HeaderDropdown/HeaderDropdown.module.scss, pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29728
Retour à la ligne pour l'adresse mail de la pop-in profile du header dans le cas ou l'email est trop long.
=> (PC-29728)[PRO] fix: add break-word for email in profile dropdown

pro/src/config/swrQueryKeys.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/utils/extractOfferIdFromObjectId.ts, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSearch.tsx, pro/src/utils/adageFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29946
**Objectif**
Récupérer les offres de la recherche ADAGE toutes en même temps.
Jusqu'a maintenant l'api pour récupérer plusieurs offres collectives depuis leurs ids n'existait pas, donc on envoyait une requête par offre. Mais maintenant on a `getCollectiveOfferTemplates` 🎉 
J'ai aussi simplifié le fonctionnement en utilisant swr pour avoir un cache (quand on revient sur la page recherche, on va souvent requeter les memes 8 ids d'offres), gérer le loading et éviter le useEffect. Et aussi on ne veut voir que des offres vitrine, donc plus la peine d'appeler 2 apis différentes vitrine/réservable.
=> (PC-29946)[PRO] feat: Fetch all adage search offers at once.

pro/src/components/StocksEventList/SortArrow.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/BookingsTable.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveActionButtons.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingDetails.module.scss, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/CollectiveBookingsTable.tsx, pro/src/screens/Bookings/BookingsRecapTable/BookingsTable/IndividualBookingsTable.tsx, pro/src/ui-kit/Timeline/Timeline.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26084
**Objectif**
Rendre responsive les headers des tables de réservation collective et individuelle
=> (PC-26084)[PRO] style: Make booking tables headers responsive.

pro/src/app/App/layout/LateralPanel/LateralPanel.module.scss, pro/src/app/App/layout/Layout.module.scss, pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss, pro/src/components/Header/Header.module.scss, pro/src/styles/variables/_size.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29988
**Objectif**
Corriger le responsive des pages du NPP en remplaçant le breakpoint tablet par laptop dans les media queries liées au layout NPP.
Changements : 
- Affichage de la sidebar à partir du breakpoint laptop à la place de tablet
- Affichage du burger menu à partir du breakpoint laptop
- Ajout d'un padding left au actions bar sticky à partir du breakpoint laptop
- Retrait de la marge autour du contenu du layout en dessous du breakpoint mobile
=> (PC-29988)[PRO] style: Use laptop breakpoint for npp layout.

pro/src/components/StocksEventList/StocksEventList.module.scss, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.module.scss, pro/src/screens/IndividualOffer/StocksEventEdition/StocksEventEdition.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29991
**Objectif**
Rendre la page des dates et capacités d'une offre indiv responsive. On a rendu la table scrollable horizontalement. Reste à voir avec Julie si c'est conforme au RGAA, et idéalement il faudrait un nouveau design pour le responsive des tables comme celle-ci.
=> (PC-29991)[PRO] style: Make the dates & capacity tables responsive.

api/src/pcapi/routes/public/collective/endpoints/categories.py, api/tests/routes/public/expected_openapi.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29919
Marquer deux routes de l'API publique collective comme dépréciée : celles qui renvoient des informations sur les catégories et sous-catégories. Elles n'ont plus de raison d'être puisque les offres collectives fonctionnent désormais avec des formats à la place. Une correspondance permet d'utiliser des (sous)catégories mais il ne sera pas maintenu éternellement.
La version de Pydantic qui nous utilisons actuellement ne semble pas avoir la possibilité de marquer des champs comme dépréciés. Il s'agit de la seconde partie, optionnelle, du ticket.
=> (PC-29919)[API] feat: public api: deprecate collective endpoints

api/src/pcapi/connectors/acceslibre.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/commands.py, api/tests/connectors/acceslibre/acceslibre_test.py, api/tests/core/offerers/test_api.py
Contrairement à ce qu'indique le nom de la branche, il s'agit de migrer le contenu des commandes liées à acceslibre vers `offerers/api.py`
Au passage, correction du matching, qui ne prenait pas en compte les villes (ce qui ne sert à rien dans les autres appels au match car l'appel API se faisait alors par ville)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29546
=> (PC-29546)[API] refactor: move acceslibre commands to offerers/api

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240408T150954_0fdfda2e6800_add_price_to_allocine_venue_provider.py, api/src/pcapi/alembic/versions/20240522T122540_69f58f589e88_populate_allocine_venue_provider_price.py, api/src/pcapi/core/providers/api.py, api/src/pcapi/core/providers/models.py
To delete the AllocineVenueProviderPriceRule model, we first need to add
a new AllocineVenueProvider column in which we double write the price.
A later commit and deployment will exclusively read from the new column 
and delete the old model.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29068
La pull request #12359 fait suite à cette PR.
=> (PC-29068)[API] refactor: add allocine venue provider price

api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/routes/serialization/offers_serialize.py, pro/src/apiClient/v1/models/GetOffererAddressResponseModel.ts, pro/src/apiClient/v1/models/OffererAddressResponseModel.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29728
Afficher le nom du lieu pour un OA sans label. Ce cas concerne seulement les OA directement lié à une venue.
=> Pc 29728 api fix offer serialisation when oa has no label

api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/routes/pro/get_collective_offer_test.py
Bug : certaines offres collectives ont pour sous-catégorie '' (texte vide) ce qui cause des problèmes à la sérialisation.
Fix : transformer les `''` en `None`.
=> (BSR) fix: empty string subcategories to None

pro/.eslintrc.cjs, pro/cypress/cypress.config.ts, pro/cypress/tsconfig.json, pro/src/custom_types/import-jpg.d.ts, pro/src/custom_types/import-png.d.ts, pro/src/custom_types/scssModules.d.ts, pro/src/custom_types/svgAsComponent.d.ts
3 changements : 
- je ramène toutes les règles eslint à la racine (au lieu d'overrides). C'est devenu possible depuis la migration sur Vite car on n'a plus que des fichiers TS, aucun fichier JS
- rajout de la règle no default export
- maj de la config pour prendre en compte le nouveau tsconfig.json dans le dossier Cypress qui a été ajouté par le passage à cucumber
=> (BSR)[PRO] chore: improve eslint config

.cz.toml, .git-commit-message-template
Ticket Jira (ou description si BSR) :  travaux d'intérêts généraux, pour pouvoir faire des labels de commit de type `script`
=> (BSR)[API] feat: add new script type to commit labels

pro/src/components/Markdown/Markdown.tsx, pro/src/components/Markdown/__specs__/Markdown.spec.tsx
https://passculture.atlassian.net/browse/PC-30118
=> (PC-30118)[PRO] fix: fix bold regex in markdown component

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240529T183331_e77d24667815_remove_pgcrypto_extension.py, api/src/pcapi/alembic/versions/sql/schema_init.sql, api/src/pcapi/install_database_extensions.py
We needed it for the `gen_random_uuid` function. But PostgreSQL ships
an internal function with the same name since version 13.
See https://www.postgresql.org/docs/15/pgcrypto.html#id-1.11.7.37.11
=> (BSR)[API] chore: Remove unused pgcrypto PostgreSQL extension

api/src/pcapi/alembic/versions/20240130T153836_9607ada7a6b6_delete_search_history_adage_ff.py, api/src/pcapi/alembic/versions/20240215T092219_88d300a290b1_delete_adage_discovery_ff.py, api/src/pcapi/alembic/versions/20240221T150541_00738a9d13b0_remove_ff_wip_category_selection.py, api/src/pcapi/alembic/versions/20240221T153023_04c2660a8169_remove_ff_wip_partner_page.py, api/src/pcapi/alembic/versions/20240227T161721_6f80f864d7ed_remove_feature_flag_enable_format.py, api/src/pcapi/alembic/versions/20240308T135307_8d5148b6b128_remove_ff_wip_adage_satisfaction_survey.py, api/src/pcapi/alembic/versions/20240308T143042_4df45e259f14_rmove_ff_wip_adage_diffuse_help.py, api/src/pcapi/alembic/versions/20240327T141058_4959dc20bd41_remove_wip_enable_compliance_call_ff.py, api/src/pcapi/alembic/versions/20240402T121757_a70801516cff_remove_ff_double_model_writing.py, api/src/pcapi/alembic/versions/20240419T084536_9660ff700ed1_remove_ff_wip_ff_side_nav.py, api/src/pcapi/alembic/versions/20240506T132505_26fdf6be1ace_drop_wip_enable_boost_prefixed_external_booking_ff.py, api/src/pcapi/alembic/versions/20240515T125314_34a1a2acff4f_delete_enable_offer_price_limitation_ff.py, api/src/pcapi/alembic/versions/20240521T094246_fbb9ccd03884_delete_acces_libre_ff.py, api/src/pcapi/alembic/versions/20240603T124838_1161bdcd0100_remove_ff_wip_opening_hours.py
Description : Semblable à cette PR: https://github.com/pass-culture/pass-culture-main/pull/12506 mais cette fois-ci pour ajouter un espace manquant : `type: ignore` au lieu de `type:ignore`. 
Remarque : la forme sans espace (`type:ignore`) n'est pas détectée par mypy cop report
=> (BSR)[API] refactor: harmonize type ignore ; add missing whitespace

api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/offerers/validation_repository.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30115
=> (PC-30115)[BO] feat: filter offerers to validate on AE documents received status

api/src/pcapi/core/external/batch.py, api/tests/routes/native/v1/favorites_test.py
Batch refuses strings that are longer than 64 characters.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27583
=> (PC-27583)[API] fix: truncate long strings sent to Batch

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240604T155723_ff36979aea69_create_index_on_offer_criterion_criterion_id.py, api/src/pcapi/core/criteria/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30193
La recherche par tag est très utilisée par la Dir Dev dans le BO.
Il y avait déjà un index sur `venue_criterion."criterionId"`, mais pas sur `offer_criterion."criterionId"`.
=> (PC-30193)[BO] perf: add missing index on offer_criterion."criterionId"

pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/AdagePreviewLayout.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30158
**Objectif**
Quand on affiche l'aperçu ADAGE dans pro, on doit recréer une "fausse" offre avec le model ADAGE à partir de la "vraie" offre PRO. Pour ça on construit l'offre en requêtant celle de pro, et en ajustant les clés pour coller au model. On pensait qu'il y avait rien à modifier sur la clé "departementCode", sauf que côté ADAGE c'est "departmentCode".
Ce qui fait que dans l'aperçu, on utilise systématiquement la tz par défaut Europe/Paris.
=> (PC-30158)[PRO] fix: Use venue departmentCode with correct value.

pro/src/app/AppRouter/routesMap.tsx, pro/src/pages/Accessibility/Accessibility.module.scss, pro/src/pages/Accessibility/Accessibility.tsx, pro/src/pages/Accessibility/Commitment.module.scss, pro/src/pages/Accessibility/Commitment.tsx, pro/src/pages/Accessibility/Declaration.module.scss, pro/src/pages/Accessibility/Declaration.tsx, pro/src/pages/Accessibility/MultiyearScheme.module.scss, pro/src/pages/Accessibility/MultiyearScheme.tsx, pro/src/pages/Accessibility/__specs__/Accessibility.spec.tsx, pro/src/pages/Accessibility/__specs__/Commitment.spec.tsx, pro/src/pages/Accessibility/__specs__/Declaration.spec.tsx, pro/src/pages/Accessibility/__specs__/MultiyearScheme.spec.tsx, pro/src/ui-kit/Button/ButtonLink.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30041
Exemple:
=> (PC-30041)[PRO] feat: Integration of accessibility pages

api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/public/collective/serialization/domains.py, api/src/pcapi/routes/public/collective/serialization/institutions.py, api/src/pcapi/routes/public/collective/serialization/offers.py, api/src/pcapi/routes/public/collective/serialization/students_levels.py, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/serialization/national_programs.py, api/tests/routes/public/expected_openapi.json
Ticket Jira : https://passculture.atlassian.net/browse/PC-30181
Ce ticket s'est révélé un peu plus compliqué que prévu. En effet, il y a des effets de bords quand on utilise la même instance de `Field`. Voici ce qu'il se passe:
```python
from pydantic.v1 import BaseModel
from pydantic.v1 import Field
from pcapi.serialization.utils import to_camel
MY_FIELD_CONSTANT = Field(description="a field description")
class SomeResponseModel(BaseModel):
name_of_the_field: str = MY_FIELD_CONSTANT
class Config:
alias_generator = to_camel  # this will add an alias `nameOfTheField` to `MY_FIELD_CONSTANT`
class SomeOtheResponseModel(BaseModel):
another_field_name: str = MY_FIELD_CONSTANT
```
Pour palier à ce problème je propose la solution suivante :
- On transforme les constantes contenant les instances …
=> (PC-30181)[API][Redoc] Enrichir la documentation des endpoints de la section "Collective educational data"

pro/cypress/e2e/features/financialManagement.feature, pro/cypress/e2e/features/venue.feature, pro/cypress/e2e/step-definitions/commonSteps.cy.ts, pro/cypress/e2e/step-definitions/financialManagement.cy.ts, pro/cypress/e2e/step-definitions/venue.cy.ts, pro/src/pages/Home/Offerers/OffererDetails.tsx, pro/src/pages/Home/Venues/Venue.tsx
Le but est de vérifier l'affichage des lieux/partenaires/venues selon la sélection de structure/offerer
J'utilise le compte `activation_new_nav@example.com` avec la nouvelle interface (qu'on doit préférer à partir de maintenant, ce n'est pas encore fait pour les autres cas), et son contenu avec plusieurs structures et 1 ou plusieurs lieux associés. A terme, il est probable qu'on n'utilise plus les données générées par la sandbox (car elles peuvent changer à tout moment et faire échouer les tests auto) mais qu'on charge les données de test utiles pour le test. **Ne pas trop s'attarder là-dessus**...
Le principe du nouveau cas:
- on sélectionne une structure avec 2 lieux, on vérifie que seuls ces 2 lieux sont affichés
- on sélectionne une structure avec 3 lieux, on vérifie que seuls ces 3 …
=> (BSR)[PRO] E2E: Test offerer selection and venue display

api/src/pcapi/core/search/__init__.py, api/src/pcapi/core/search/backends/algolia.py, api/src/pcapi/core/search/backends/base.py
Most functions expect something that is iterable and sized.
`Collection` checks both criteria (contrary to `Iterable`, which is
not sized).
Also, import `Collection` and `Iterable` from `collections.abc`. These
aliases in `typing` are deprecated since Python 3.9.
=> (BSR)[API] chore: Fix typing annotation in `core.search`

pro/cypress/e2e/features/searchIndividualOffer.feature, pro/cypress/e2e/step-definitions/searchIndividualOffer.cy.ts, pro/src/pages/Offers/Offers/OfferItem/OfferItem.tsx
Recherche d'offre individuelle par nom ou EAN. On vérifie que les 4 colonnes en réponse à la recherche contiennent bien ce qui est attendu + le label du nombre d'offres.
- [-] J'ai écrit les tests nécessaires
- [-] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [-] J'ai ajouté des screenshots pour d'éventuels changements graphiques
=> (BSR)[PRO] E2E: search name and EAN

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/products.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/get_event_test.py, api/tests/routes/public/individual_offers/v1/get_product_by_ean_test.py, api/tests/routes/public/individual_offers/v1/get_product_test.py, api/tests/routes/public/individual_offers/v1/patch_event_test.py, api/tests/routes/public/individual_offers/v1/post_event_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30111
=> (PC-30111) [API] Ajout du champ `idAtProvider` dans les endpoints de l'API publique

.github/workflows/dev_on_workflow_deploy_app_engine_image_resizing.yml
Ticket Jira (ou description si BSR) :  clear unused app versions from image resizing service when deploying to ehp
=> (BSR)[API] ci: clear unused app versions from image resizing service when deploying to ehp

.github/workflows/dev_on_workflow_deploy.yml
In order to fix some sync timeouts while syncing app like in the example below, addition of --prune option to argocd sync command.
https://github.com/pass-culture/pass-culture-main/actions/runs/9443459787/job/26007709946
=> Add prune option to argocd app sync

.github/workflows/dev_on_workflow_deploy_app_engine_image_resizing.yml
Ticket Jira (ou description si BSR ): fix CI delete unused app versions from gcloud
=> Bsr fix CI delete unused app versions from gcloud

pro/vite.config.ts
Génère les sourceMaps pour les fichiers SCSS en _development_. Ce qui est beaucoup plus pratique pour repérer les styles directement à partir du code source.
=> (BSR)[PRO] feat: Enable SCSS sourcemaps in development

api/src/pcapi/core/offerers/models.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29065
For GET routes, the changes were never commited to the database. Even if this hash changes should be done only once, some of our users only use GET routes.
=> (PC-29065)[API] fix: commit secret changes even on GET

pro/package.json, pro/src/components/Callout/__specs__/Callout.spec.tsx, pro/src/custom_types/axe.d.ts, pro/src/pages/AdageIframe/app/__spec__/App.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/__spec__/Offers.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/OffersSuggestions/__specs__/OffersSuggestions.spec.tsx, pro/src/pages/AdageIframe/app/components/Pagination/__specs__/Pagination.spec.tsx, pro/src/pages/Signup/SignUpValidation/__specs__/SignupValidation.spec.tsx, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/__specs__/DownloadBookingModal.spec.tsx, pro/src/vitest.setup.ts, pro/yarn.lock
Ticket : https://passculture.atlassian.net/browse/PC-25154
=> (PC-25154)[PRO] chore: update testing-library/jest-dom

pro/cypress/e2e/features/collectiveBooking.feature, pro/cypress/e2e/features/counter.feature, pro/cypress/e2e/features/createAccount.feature, pro/cypress/e2e/features/createEventIndividualOffer.feature, pro/cypress/e2e/features/createThingIndividualOffer.feature, pro/cypress/e2e/features/financialManagement.feature, pro/cypress/e2e/features/searchCollectiveOffer.feature, pro/cypress/e2e/features/searchIndividualOffer.feature, pro/cypress/e2e/features/venue.feature, pro/cypress/e2e/step-definitions/commonSteps.cy.ts, pro/cypress/e2e/step-definitions/counter.cy.ts, pro/cypress/e2e/step-definitions/createEventIndividualOffer.cy.ts, pro/src/components/Callout/Callout.tsx, pro/src/pages/Desk/Desk.tsx
Dans cette PR, seulement 2 tests de la page du guichet:
- conformité de la page
- saisie d'une contremarque invalide
Comme on utilise la sandbox, on a des contremarque regénérée à chaque lancement de celle-ci donc on ne peut pas en utiliser une fixée dans le code.
Donc je met de côté pour l'instant en attendant une meilleure gestion du jeu de donnée.
=> (BSR)[PRO] Add first tests of counter/guichet

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240612T221427_a909ecd976dc_fill_start_end_datetime_for_collective_stock.py, api/src/pcapi/alembic/versions/20240612T221917_3e180517700b_fill_start_end_datetime_for_collective_stock.py
Fill `startDatetime` / `endDatetime` with the value of `beginningDatetime` on CollectiveStock.
First batch is pre deployment to make sure the code work as expected. Also performs the same operation after deployment to make sure any stock created between the pre migration and the deployment also has its values correctly filled.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30315
=> (PC-30315)[PRO] feat: fill collective stock start/end datetime

api/src/pcapi/utils/mailing.py
1. Raise a clearer exception if `get_event_datetime()` is called with
a non-event stock.
2. Rewrite conditions to help mypy.
3. Use early exit for clarity and conciseness.
=> (BSR)[API] refactor: Simplify booking date/datetime formatting in emails

api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/collective_offers.py, api/tests/routes/pro/patch_collective_offer_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29353
Fix : lorsque le lieu d'une offre collective est mis à jour, celui de sa (ou ses s'il y a eu des annulations) réservation doit l'être également.
=> (PC-29353)[EAC] fix: update offer's booking's venue

.github/workflows/dev_on_pull_request_workflow.yml, .github/workflows/dev_on_push_workflow_main.yml
Afin de faciliter/preparer le workflow aux deploiements environnements dynamique, separation du workflow main en 2 workflows :
- dev_on_push_workflow_main.yml -> Workflow pour les push on master ou maint.
- dev_on_pull_request_workflow.yml -> Workflow specifique pour les pullrequests.
Le resultat au declenchements des 2 workflows devrait rester inchange.
Cette operation presente  l'avantage de simplifier les conditions dans les workflows, et de pouvoir travailler independemment sur le workflow on_pull_request.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30338
=> PC-30338 - Separate workflows for master/maint and pull_requests

pro/cypress/e2e/features/financialManagement.feature, pro/cypress/e2e/step-definitions/financialManagement.cy.ts
Vérifie la conformité de la page de Gestion Financière: message d'information et liens vers pages externes
Un bout est commenté pour le téléchargement de justificatif de remboursement en pdf, mais cela ne marche pas en CI, seulement sur poste en local! J'ai préféré le garder
=> (BSR)[PRO] E2E: Financial page: messages and links

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/CONTRIBUTING.md, api/src/pcapi/alembic/versions/20240613T133241_3f81e39451a0_add_unicity_constraint_on_offer_id_at_provider.py, api/src/pcapi/core/offers/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30259
=> (PC-30259)[API] Ajout d'une contrainte d'unicité sur la pair (`idAtProvider`, `VenueId`) dans la table offre

pro/src/components/IndividualOfferForm/Categories/__specs__/Categories.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30351
**Objectif**
Corriger le test unitaire sur les catégories qui ne passe pas en local
=> (PC-30351)[PRO] test: Fix du test de Categories.spec.tsx.

pro/src/core/Venue/getSiretData.tsx, pro/src/screens/SignupJourneyForm/Offerer/Offerer.tsx, pro/src/screens/SignupJourneyForm/Offerer/OffererForm.tsx, pro/src/screens/SignupJourneyForm/Offerer/__specs__/Offerer.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/__specs__/OffererForm.spec.tsx, pro/src/screens/SignupJourneyForm/Offerer/validationSchema.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30218
Lors du parcours d'inscription, faire en sorte de n'appeller qu'une seule fois la route API `/sirene/siret/{siret}` pour éviter les rate limit de cloudArmour (5 appels/min/IP)
**Solution :** 
On procède à la validation du SIRET seulement à la validation du formulaire et non plus dans le schéma de validation du formulaire
=> (PC-30218)[PRO] fix: only call siren validation once on signup

api/documentation/package-lock.json, api/documentation/package.json
Fix de cette [alerte dependabot](https://github.com/pass-culture/pass-culture-main/security/dependabot/291).
En réalité ce n'est pas une vulnérabilité pour nous car il s'agit d'une alerte concernant les websockets (qui ne sont utilisées que par le serveur en mode dev). Cette PR a surtout le mérite d'éviter la pollution sur dependabot.
=> (BSR) feat: update docusaurus version and fix vulnerabilities

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/models/feature.py, api/tests/core/finance/test_api.py
Changes the finance to use `endDatetime` instead of `beginningDatetime` for CollectiveStock to reimburse cultural partners at the end of an collective event instead of the start
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30316
=> (PC-30316)[PRO] feat: use CollectiveStock.endDatetime for finance

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Update de la sandbox après revue PM, pour avoir les bons users avec les bons liens
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30412
=> (PC-30412)[API] fix: update sandbox users for discord auth

api/src/pcapi/local_providers/cinema_providers/cds/cds_stocks.py, api/src/pcapi/utils/cinema_providers.py, api/tests/core/bookings/test_api.py, api/tests/core/offers/test_api.py, api/tests/local_providers/cinema_providers/cds/cds_stocks_test.py, api/tests/routes/native/v1/offers_test.py, api/tests/utils/cinema_providers_test.py
Following this commit 45c63da9e62605603eca94e401c1b14946acb1c7, we don't need to handle the old construct of CDS uuid.
=> (BSR)[API] chore: Don't handle old construct of CDS uuid

api/src/pcapi/app.py, api/src/pcapi/routes/auth/discord.py, api/src/pcapi/routes/auth/templates/discord_signin.html, api/tests/routes/auth/discord_test.py
This reverts commit 92301e09dcff6e6286203828fdf3863635cc9cb4.
Fixer un warning très énergivore
Followup pour corriger: https://passculture.atlassian.net/browse/PC-30450
=> Revert "(PC-29764)[API] feat: require csrf token for discord aut post route"

api/src/pcapi/serialization/spec_tree.py
Remplace `ordered` par `sorted` (parce qu'en anglais `ordered` signifie commandé et non trié)
=> (BSR) feat: fix typo in `ExtendedSpecTree`

pro/cypress/e2e/features/signupJourneyCreateOfferer.feature
Comme ils sont faits actuellement, les scénarios signupJourneys utilisent des emails de la sandbox pour faire un signup. Une fois utilisés une fois, il est inutile de les réutiliser sans avoir réinitialisé la sandbox, donc il est ici inutile d'utiliser le retry global de la conf cypress.
- [-] J'ai écrit les tests nécessaires
- [-] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [-] J'ai ajouté des screenshots pour d'éventuels changements graphiques
=> (BSR)[PRO] test: no useless retries for signupJourney

api/src/pcapi/app.py, api/src/pcapi/settings.py, pro/README.md
BSR : rendre configurable l'IP utilisée par le backend.
=> (BSR)[API] feat: allow to set the backend's IP through os env

api/src/pcapi/connectors/titelive.py
TiteLive seems to have halved their authentication JWT lifespan
Fixes https://sentry.passculture.team/organizations/sentry/issues/1614596/?project=5&referrer=slack
=> (BSR)[API] fix: shorten titelive jwt lifespan

api/.env.rebuild_staging, api/src/pcapi/tasks/decorator.py, api/tests/tasks/decorator_test.py
The development env will no longer call cloud tasks. Likewise, the sandbox script is executed in the dev env, so it will no longer call cloud tasks.
=> (BSR)[API] refactor: use sync job env var to enable cloud tasks

pro/cypress/e2e/features/financialManagement.feature, pro/cypress/e2e/step-definitions/financialManagement.cy.ts, pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceTable.tsx
Test e2e du choix de structure sur la page "Gestion financière" et vérification du changement des infos (onglet Justificatifs)
Warning: Les tests e2e échouent toujours sur le searchIndividualOffer (mais ça n'a rien à voir avec ce qui est fait ici, les données ont changé dans le sandbox et c'est en cours de correction par @Amine et Jean-Marie)
Info: Quand on aura la possibilité de créer nos propres datas sans celles pré-chargées dans la sandbox, alors on fera surement un cas sans justificatif puis un cas avec plusieurs justificatifs...mais là on fait avec ce qu'on a 😇
@ncanseco-pass : les `if` vont te faire tilter, mais c'est pour éviter de vérifier une ligne vide pour rien et pas trouvé mieux que mettre une valeur vide dans le dataTable du cucumber qui nous limite un peu. Le faire marche …
=> (BSR)[PRO] test: Test offerer selection in financial view

api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_incidents.py
Prévenir les appels vers adage lors de la génération de justificatifs de remboursement dans la sandbox
=> (BSR)[BO] fix: mock adage call in industrial incidents sandbox generator

api/.env.staging, api/.env.testing, api/src/pcapi/flask_app.py, pro/firebase.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29056
Ajout de CSP report-only qui vont déclencher des erreurs sur Sentry sans bloquer le contenu. L'objectif étant d'améliorer la sécurité de l'app pro en rendant plus strictes les règles des CSP. Pour chaque type de source de contenu, on définit la liste explicite des urls qui y ont droit.
Doc du report-to : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to
Doc des CSP dans Sentry : https://sentry.passculture.team/settings/sentry/projects/pro/security-headers/csp/
Doc sur notion : https://www.notion.so/passcultureapp/Setup-des-CSP-Report-Only-Sentry-dd0912213f154c9eb39315a2924eb363?pvs=4
=> (PC-29056)[API] fix: Add report to response header for csp report only.

api/src/pcapi/scripts/beneficiary/import_test_users.py, api/tests/scripts/beneficiary/import_test_users_test.py
There is a unique constraint on ApiKey.prefix but multiple users have the same "Prénom". 
In our file email is unique, let's use that. Fix [this issue](https://sentry.passculture.team/organizations/sentry/issues/1615506/?referrer=slack)
=> (BSR)[API] fix: users generation

api/src/pcapi/routes/internal/__init__.py, api/src/pcapi/routes/internal/e2e.py, api/src/pcapi/sandboxes/scripts/getters/__init__.py, api/src/pcapi/sandboxes/scripts/getters/pro_01_create_pro_user.py, api/src/pcapi/sandboxes/scripts/utils/helpers.py
Cette PR permet d'avoir un jeu de données minimaliste pour le test CreateThingIndividualOffer sans passer par la sandbox
Idée : pour écrire un jeu de données de test : 
- on ajoute dans `pcapi/sandboxes/scripts/getters` un module correspondant à l'appel front de cypress (ici `create_pro_user`) (+ ne pas l'oublier dans le __ init__) et une méthode qui correspond à ce qu'on veut faire exactement (ici `create_pro_user_with_venue_bank_account_and_userofferer`) qui va créer les données dont on a besoin
- on ajoute un `helper`qui permet de renvoyer les données au bon format au front
A revoir ou valider ensuite côté front : 
- on appelle cette route depuis le front (ici dans `pro/cypress/e2e/step-definitions/commonSteps`) 
- on ajoute l'appel au front dans le scénario (ici dans …
=> (PC-30145)[API] feat: create minimal data for CreateThiIndividualOffer e2e test

api/gunicorn.conf.py
Registering our own handler replaces the default Gunicorn handler,
which logs the start of the request, like this:
[634677] [DEBUG] GET /health/api
... which is useful to analyze SIGKILL sent to Gunicorn workers (see
PC-27885 for an helper script).
---
Testé en local en lançant Gunicorn comme suit :
$ ENABLE_FLASK_PROMETHEUS_EXPORTER=1 PROMETHEUS_MULTIPROC_DIR=/tmp/pass-culture-prometheus GUNICORN_PORT=4999 GUNICORN_MAX_REQUESTS=10 GUNICORN_MAX_REQUESTS_JITTER=10 GUNICORN_WORKERS=2 GUNICORN_THREADS=2 GUNICORN_TIMEOUT=10 GUNICORN_LOG_LEVEL=debug ./entrypoint.sh
[...]
[2024-06-24 09:52:28 +0200] [634677] [DEBUG] GET /health/api
=> (BSR)[API] fix: Restore Gunicorn "pre request" logs

api/src/pcapi/core/finance/api.py, api/src/pcapi/domain/reimbursement.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_commercial_gestures.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_invoices.py, api/tests/core/finance/test_api.py
Ajout d'une nouvelle règle de remboursement à 100% utilisée pour les versements des gestes commerciaux
=> (PC-28786)[BO] feat: Add specific reimbursement rule for commercial gestures

pro/.vscode/extensions.json, pro/.vscode/settings.json
Ajout d'extensions recommandées pour VSCode :
- Stylelint
- Cucumber (Gherkin) Full Support (+ ajout de la configuration pour IntelliSense)
=> (BSR)[PRO] feat: Adds recommended VSCode extensions and config

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/commands.py, api/src/pcapi/core/offers/repository.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_repository.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30105
=> (PC-30105)[API] future offer script

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/repository.py, api/tests/routes/pro/patch_publish_offer_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30546
=> (PC-30546)[API] feat: delete future offer when early publish

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240624T162701_e92c101b449f_add_is_manual_edition_column_to_address.py, api/src/pcapi/alembic/versions/20240624T162702_036a69733891_update_index_ix_partial_unique_address_per_street_and_insee_code.py, api/src/pcapi/alembic/versions/20240624T162703_ce44550d83cb_create_index_ix_complete_unique_address.py, api/src/pcapi/alembic/versions/20240624T162704_17aa8cf97ab4_fill_in_address_is_manual_edition.py, api/src/pcapi/core/geography/factories.py, api/src/pcapi/core/geography/models.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/routes/backoffice/forms/fields.py, api/src/pcapi/routes/backoffice/templates/components/forms/postal_address_autocomplete.html, api/src/pcapi/routes/backoffice/venues/blueprint.py, api/src/pcapi/routes/backoffice/venues/forms.py, api/src/pcapi/static/backoffice/js/addons/pc-postal-address-autocomplete.js, api/tests/routes/backoffice/venues_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30539
=> (PC-30539)[BO] feat:  make manual address edition compatible with new "Offer Address" model

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240625T151325_4b41a69dfe71_remove_ff_wip_enable_new_nav_ab_test.py, api/src/pcapi/core/users/api.py, api/src/pcapi/models/feature.py, api/tests/routes/pro/signup_pro_V2_test.py
Arret de l'AB test et suppression du FF associé. 
Maintient de l'ancienne nav pour les utilisateurs invité par ceux qui l'ont. 
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30329
=> (PC-30329)[API] feat: remove wip_enable_new_nav_ab_test ff and stop ff

pro/cypress/e2e/step-definitions/venue.cy.ts
Suite à 1 échec (3 fois de suite avec le retry) sur master, le `GET venue-type` n'est pas toujours présent ici, je le supprime donc.
Voir https://cloud.cypress.io/projects/rit5sb/runs/43/overview/cb1e2567-cca1-4b3f-b202-0cd8d01e6041/replay?att=1&roarHideRunsWithDiffGroupsAndTags=1&ts=1719421101022.7808
=> (BSR)[PRO] test: We should not wait for a GET /venue-types

api/src/pcapi/core/educational/api/stock.py, api/src/pcapi/core/educational/exceptions.py, api/src/pcapi/routes/pro/collective_stocks.py, api/tests/core/educational/api/test_edit_collective_offer_stock.py, api/tests/routes/pro/patch_collective_stock_test.py, api/tests/routes/pro/post_collective_stock_test.py, pro/src/apiClient/v1/services/DefaultService.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30505
=> (PC-30505)[PRO] fix: Ensure the start/end date are on the same day when creating/editing a stock

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240627T154807_e8732e562de5_add_venue_provider_external_urls.py, api/src/pcapi/alembic/versions/20240627T155103_9708ed7dcc65_add_fk_constraint_in_venue_provider_external_urls.py, api/src/pcapi/core/providers/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30306
Ce qui a été décidé au final : création d'une table `VenueProviderExternalUrls` qui référence `VenueProvider` et qui se supprime en cascade quand `VenueProvider` est supprimé. Nous n'avons pas mis les external urls directement dans la table `venue_provider` car celles-ci ne seront remplies quand dans un nombre limité de cas (on ne veut pas polluer la table avec des valeurs null).
=> (PC-30306)[API] feat: add `venue_provider_external_urls` table

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external/batch.py, api/src/pcapi/notifications/push/__init__.py, api/tests/routes/native/v1/bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30215
=> Pc 30215 batch event on booking cancel

api/src/pcapi/core/mails/transactional/educational/eac_booking_cancellation.py, api/src/pcapi/core/mails/transactional/educational/eac_new_booking_to_pro.py, api/src/pcapi/core/mails/transactional/educational/eac_new_prebooking_to_pro.py, api/src/pcapi/core/mails/transactional/educational/eac_new_request_made_by_redactor_to_pro.py, api/src/pcapi/core/mails/transactional/educational/eac_one_day_after_event.py, api/src/pcapi/core/mails/transactional/educational/eac_one_day_before_event.py, api/src/pcapi/core/mails/transactional/educational/eac_pending_booking_confirmation_limit_date_in_3_days.py, api/src/pcapi/core/mails/transactional/educational/eac_sending_offerer_activation.py
common_name being `self.publicName or self.name`
Ticket Jira : https://passculture.atlassian.net/browse/PC-30048
=> (PC-30048)[PRO] feat: Replace venue.name with common_name

api/src/pcapi/routes/serialization/bookings_recap_serialize.py, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/pages/Bookings/__specs__/BookingsRecap.spec.tsx, pro/src/pages/Bookings/downloadIndividualBookingsCSVFile.ts, pro/src/pages/Bookings/downloadIndividualBookingsXLSFile.ts
It turns out Front does not like when query params order is changed. Before this fix, the default filters would be:
page=1&eventDate=booked&bookingStatusFilter=2024-06-01&bookingPeriodBeginningDate=2024-07-01
After:
page=1&bookingStatusFilter=booked&bookingPeriodBeginningDate=2024-06-01&bookingPeriodEndingDate=2024-07-01
This is because the front passes the query arguments as positional arguments rather than keyword arguments when building the url.
Ticket Jira : https://passculture.atlassian.net/browse/PC-30377
=> (PC-30377)[PRO] fix: reorder query params on reservations page

.github/workflows/dev_on_pull_request_workflow.yml, .github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_build_docker_image.yml, .github/workflows/dev_on_workflow_deploy_pro_pr_version_generic.yml, .github/workflows/dev_on_workflow_push_docker_image.yml, .github/workflows/dev_on_workflow_tests_api.yml, .github/workflows/dev_on_workflow_tests_pro.yml, .github/workflows/dev_on_workflow_tests_pro_e2e.yml, .github/workflows/dev_on_workflow_update_api_client_template.yml, .github/workflows/scripts/check-image-tag-exists.sh
Changes :
ONLY AFFECTING ON PULLREQUESTS AND ON PUSH MASTER for now 
Create Release-Hotfix / Deploy Release-hotfix will be done incrementally once the following changes will  run smoothly for several weeks to ensure stability and not potentially affecting MEPs
- Grouped test-pro Type check / Quality Check / Style Quality check in a single job.
- Grouped tests-e2e and its notifications to the same job
- Fixed Update api template not executing
- Fixed e2e tests not executing
- Create new docker tag (in addition to the commit-sha tag) for pcapi and pcapi-console images. This tag is a hash of files inside pcapi.
- Check if thus hash exists in registry before building. If, yes, do not build and do no execute tests (images in registry had their tests being run succesfully already ). Useful for …
=> PC-30398 - Modified image tags / Promoting

api/src/pcapi/routes/__init__.py, api/src/pcapi/routes/public/blueprints.py
Ticket Jira  : https://passculture.atlassian.net/browse/PC-30661
L'erreur est due à l'extension de `_check_api_is_enabled_and_json_valid` à la vieille API. Hors certains de nos partenaires techniques nous envoie des JSON dans les GET.
=> (PC-30661)[API] feat: fix error on old CM endpoint

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offer_test.py
This is requied as long as the script to fill offer's offerer_address is not run for legacy offers.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30372
=> (PC-30372)[PRO] feat: return venue's address if offer has none.

api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offer_test.py
At the moment, the venue data are not yet migrated to OffererAddress. We still have to consider cases where the offer has no address and the venue does not either.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30372
=> (PC-30372)[PRO] fix: offer and venue without address crash

pro/src/pages/Offers/Offers/Offers.module.scss, pro/src/pages/Offers/Offers/Offers.scss, pro/src/pages/Offers/Offers/Offers.tsx, pro/src/screens/Offers/Offers.module.scss, pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30064
Ajout d'une nouvelle bannière avant la liste des offres collectives pour expliquer la nouvelle fonctionnalité d'archivage
=> (PC-30064)[PRO] feat: add onboarding banner to explain new archiving feature

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
Ajouter le label du cashflow batch dans le nom des fichiers csv (invoices et down_payment) exportés
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30670
=> (PC-30670)[BO] feat: Include cashflow batch's label in exported finance csv's names

api/src/pcapi/app.py, api/src/pcapi/routes/auth/discord.py, api/src/pcapi/routes/auth/templates/discord_signin.html, api/tests/routes/auth/discord_test.py
This feature was reverted by this pr: https://github.com/pass-culture/pass-culture-main/pull/12828
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30450
=> (PC-30450)[API] fix: add csrf protection to discord auth

pro/src/app/App/layout/Layout.module.scss, pro/src/app/App/layout/Layout.tsx, pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss, pro/src/components/Footer/Footer.module.scss, pro/src/components/FormLayout/FormLayout.module.scss, pro/src/components/FormLayout/FormLayout.tsx, pro/src/components/StocksEventList/StocksEventList.module.scss, pro/src/components/StocksEventList/StocksEventList.tsx, pro/src/hooks/useWithoutFrame.tsx, pro/src/pages/Offers/Offers/OfferItem/Cells/CheckboxCell.tsx, pro/src/pages/Offers/Offers/OfferItem/OfferItem.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/OffersSynchronization.tsx, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/VenueProviderItem.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/VenueProviderItem.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.module.scss, pro/src/screens/IndividualOffer/StocksEventCreation/StocksEventCreation.tsx, pro/src/screens/IndividualOffer/StocksThing/StockThing.module.scss, pro/src/screens/IndividualOffer/StocksThing/StockThingFormActions/StockThingFormActions.module.scss, pro/src/screens/IndividualOffer/StocksThing/StocksThing.tsx, pro/src/styles/variables/_size.scss, pro/src/styles/variables/_themes.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30620
- **Commit 1 :** Uniformisation de l'utilisation du hook `useWithoutFrame` (qui sera en fait supprimé dans le commit final suite à décision PM)
- **Commit 2 :** Agrandit la taille du bloc gris représentant un pivot
- **Commit 3 :** Centre le footer et le rend responsive (correction/uniformisation de marges)
- **Commit 4 :** Fixe la taille des colonnes "checkbox" et "thumb" sur les tableaux pour les ferrer à gauche et éviter un espacement automatique incohérent visuellement
- **Commit 5 :** Fixe la tailles des colonnes de "checkbox" et de "date" sur les tableaux […]
- **Commit 6 :** Réduit en largeur les champs "prix", "date" et "quantité" dans la création d'offre physique (step 2)
- **Commit 7 :** …
=> Pc 30620 npp sans frame corrections graphiques

pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
Cela ne me satisfait pas particulièrement, mais à défaut de trouver la root cause, j'ai ajouté une pause de 2 secondes avant la création de l'offre pour éviter les échecs qui se répètent. On perd 2", mais avoir un échec fait perdre encore plus de temps, et de confiance...
A voir si c'est mieux sur les multiples runs sur master.
Ces tests flaky seront à revoir quand on aura une utilisation de donnée définitives (données créées au début du test n'utilisant plus celles de la sandbox)
=> (BSR)[PRO] test: try to fix flaky signup with wait

api/documentation/docs/tutorials/create-a-collective-offer.md
Retirer le champ subcategoryId de l'exemple de JSON fourni dans le tutoriel de la création d'une offre collective car ce champ est obsolète.
=> (BSR)[API] fix: public api doc: rm subcategory from payload example

api/src/pcapi/routes/pro/collective_offers.py, api/src/pcapi/routes/serialization/collective_offers_serialize.py, api/src/pcapi/serialization/decorator.py, api/tests/routes/pro/get_all_collective_offers_test.py, api/tests/serialization/serialization_decorator_test.py, pro/src/apiClient/v1/models/ListCollectiveOffersQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts
Ce dev est un préliminaire pour pouvoir permettre la selection de plusieurs status pour les offres collectives.
Pour le moment le dev en question lève une erreur lorsque plusieurs status sont passés, mais la validation des params fonctionne.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29685
=> (BSR)[PRO] feat: define query-params to be used as list

api/src/pcapi/routes/public/documentation_constants/http_responses.py, api/tests/routes/public/expected_openapi.json, api/tests/serialization/serialization_decorator_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30625
Cette PR fix une 500 que renvoyait notre API publique dans le cas où elle recevait une requête POST/PATCH attendant un JSON avec `Content-Type: application/x-www-form-urlencoded`.  (erreur Sentry: https://sentry.passculture.team/organizations/sentry/issues/1520231/events/287845a3839e4b988da945dd3d26cf79/?project=5&referrer=previous-event)
L'erreur 500 était due au modèle `ErrorResponseModel` qui normalement ne devait servir qu'à la documentation (et qui en réalité documentait mal) et dans les faits était appelé par spectree pour formater l'erreur.
=> (PC-30625)[API] fix: remove `ErrorResponseModel` causing 500 when content-type is incorrect

.github/workflows/dev_on_push_workflow_main.yml
For example https://github.com/pass-culture/pass-culture-main/actions/runs/9858204355/job/27220115110
=> (BSR) ci: push pod console image should be trigger when build has been done

pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30671
La ActionsBar occupe maintenant l'intégralité du corps de la version sans frames.
=> (PC-30671)[PRO] fix: Makes <ActionsBar> larger for NPP without frame

api/src/pcapi/core/offerers/api.py, api/tests/routes/pro/post_venue_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30683
Passer `offerer.allowedOnAdage` à `True` dès qu'un lieu est créé en intégration. Cela permet de permettre de rendre la création d'offres collectives possibles toujours possible en intégration.
=> (PC-30683)[API] feat: integration env: always allow offerer

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240710T153906_e199b0790783_skip_reimbursed_booking_trigger.py, api/src/pcapi/core/bookings/models.py, api/tests/core/bookings/test_models.py
Finance: éviter de vérifier les quantités des stocks lors de la génération des exports finance.
Problème: Lors de la création des invoice, il se peut qu'on ait à passer des centaines de booking de "USED" à "REIMBURSED" et ça engendre des timeouts quand on lance la commande `generate_invoices`
Solution: cette vérification est inutile à ce stade du workflow finance donc on ne garde le check que pour les autres changement d'état des bookings
=> (BSR)[BO] fix: skip check_booking trigger function when generating the invoices

pro/cypress/e2e/step-definitions/commonSteps.cy.ts, pro/cypress/e2e/step-definitions/searchIndividualOffer.cy.ts, pro/cypress/e2e/step-definitions/venue.cy.ts, pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
Quelques petites modifs suite à l'observation de cas flaky (échoue une première fois, puisse passe) notamment pour attendre la fermeture du menu de sélection en haut à droite.
=> (BSR)[PRO] test: flaky: wait for header menu to be closed

pro/src/screens/OfferEducationalStock/__specs__/validationSchema.spec.ts, pro/src/screens/OfferEducationalStock/validationSchema.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30724
=> (PC-30724) fix: allow start and end dates set to 01/09/N and 31/08/N+1 on educational offers

.github/workflows/dev_on_workflow_tests_pro_e2e.yml
Skip l'étape de déplacement et upload des vidéos vers Google Storage si run sur master....car on a tout ce qu'il faut dans Cypress Cloud
=> (BSR)[PRO] test: no screenshot and video recording with cloud

pro/src/components/Header/HeaderDropdown/HeaderDropdown.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30716
Le lien "Voir le profil" disparaît uniquement si on est dans le parcours de création de structure et que l'on est pas encore rattaché à une structure.
=> (PC-30716)[PRO] feat: Hide 'View Profile' menu link in structure creation funnel

pro/src/components/SkipLinks/SkipLinks.module.scss, pro/src/styles/variables/_z-index.scss
Fixe le problème remonté par la Qualité sur la modale de personnalisation des cookies, qui passait en dessous du header et composant <SkipLinks/>.
=> (BSR)[PRO] fix: Makes cookies preferences popup over the 'skip-link' component

api/src/pcapi/core/educational/api/stock.py, api/src/pcapi/core/educational/exceptions.py, api/src/pcapi/routes/pro/collective_stocks.py, api/tests/routes/pro/patch_collective_stock_test.py
Au vu de ce bug Sentry -> https://sentry.passculture.team/organizations/sentry/issues/1616947/?referrer=slack, @ogeber a proposé de lever une exception plutôt que d'assert la présence de l'année scholaire.
=> (BSR)[PRO] feat: raise an exception when educational year is missing

pro/package.json, pro/src/pages/AdageIframe/app/components/AdageHeader/__specs__/AdageHeader.spec.tsx, pro/src/screens/SignupJourneyForm/Authentication/__specs__/OffererAuthenticationForm.spec.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30746
Upgrade la version de @vitest/coverage-v8 et de vitest
=> (PC-30746)[PRO] upgrade: maj vitest and vitest-coverage to latest version

api/README.md, infra/pc_scripts/start_backend_no_docker.sh
BSR pour:
- modifier le readme afin de créer les superuser hors script (trop compliqué à gérer dans le script car `create user if not exist `n'existe pas avec postgresql )
- ne pas ajouter les lignes de db dans le fichier local si elles existent déjà
=> (BSR) refactor: sort readme & add verification to setup to avoid rewriting lines

api/src/pcapi/connectors/recommendation.py, api/src/pcapi/routes/native/v1/recommendation.py, api/tests/connectors/recommendation_test.py, api/tests/routes/native/v1/recommendation_test.py
The backend acts as a proxy for these routes.
If we have a timeout for recommendation api we return a 504 to native front If we have any other errors we return a 502 to native front
=> (PC-30774)[API] fix: use more specific error for recommendation routes

api/src/pcapi/sandboxes/scripts/creators/test_cases/__init__.py
Lien du ticket Jira : https://passculture.atlassian.net/browse/PC-30652
Ajouter des images pour la sandbox, sans quoi les offres créés ne peuvent être affichées sur les page lieux cinéma.
Faire aussi en sorte qu'il y ait des jours où elles n'ont pas de séances
=> (PC-30652)[API] feat: add mediations to cinema offers in sandbox

api/src/pcapi/alembic/versions/20240710T153906_e199b0790783_skip_reimbursed_booking_trigger.py
éviter de passer la migration `e199b0790783` en automatique en prod a cause de la difficulté de prendre le lock sur booking sur cette environnement.
=> (BSR)[API] fix: skip migration e199b0790783 in prod to avoid timeout

.github/workflows/dev_on_dispatch_release_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30789
J'utilise la syntaxe `continue-on-error` cf [doc GHA](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) pour ne pas bloquer le déploiement si l'envoi de message Slack échoue pour une raison ou une autre
=> (PC-30789) ci: Post a link to Slack for the deployment review

pro/src/components/UserIdentityForm/UserIdentityForm.tsx, pro/src/components/UserPasswordForm/UserPasswordForm.tsx, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeader.tsx, pro/src/pages/AdageIframe/app/components/OfferInfos/AdagePreviewLayout/AdagePreviewLayout.tsx, pro/src/pages/AdageIframe/app/components/UnauthenticatedError/UnauthenticatedError.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormNotifications/EmailInputRow/EmailInputRow.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormNotifications/FormNotifications.tsx, pro/src/ui-kit/Tooltip/useTooltipProps.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29616
**Objectif**
Corriger 3 non conformités de l'audit a11y :
- Le texte alternatif des logos ne doivent pas préciser qu'il s'agit d'un logo, l'info est redondante.
- Dans le formulaire de création d'offres collectives, quand on clic sur "Ajouter un email de notification" le champ qui apparait doit recevoir le focus automatiquement.
- Les tooltips doivent se fermer lorsqu'on clic sur la touche "Escape" (même si on n'est pas en focus dedans).
=> Pc 29616 collective offers accessibility

api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/serialization/address_serialize.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offers_test.py, pro/src/apiClient/v1/models/ListOffersOfferResponseModel.ts
we consider the location info of the offer if its exist and then the venue location data otherwise
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30375
=> (PC-30375)[API] feat: adding address information in the /offers route

api/src/pcapi/routes/backoffice/offerers/offerer_blueprint.py, api/src/pcapi/routes/backoffice/templates/offerer/get.html, api/tests/routes/backoffice/offerers_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30893
**Contexte :** La possibilité de générer les anciennes clés API a été retirée "trop rapidement" du front PRO. Le temps que les providers qui utilisent les anciennes API stocks et contre-marques fassent leur migration, nous ajoutons ce bouton de génération dans le BO pour que les personnes aillant les accès support de niveau 2 puissent générer des anciennes clés pour les providers.
=> (PC-30893)[BO] feat: add button to generate API key in Offerer view

pro/src/app/App/layout/LateralPanel/LateralPanel.module.scss, pro/src/app/App/layout/Layout.module.scss, pro/src/app/App/layout/Layout.tsx
Corriger l'affichage du menu latéral avec la bannière connect as.
=> (BSR)[PRO] fix: Fixing connect-as banner hiding elements.

pro/src/app/App/layout/Layout.module.scss, pro/src/components/Footer/Footer.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30855
3 petites lignes, mais de grosses responsabilités. En effet, le `height: 100%` sur le `.content-container` était le principal responsable du bug reporté dans le ticket. En dessous d'une certaine hauteur, la valeur de 100% finissait par devenir plus petite que l'addition de toutes les marges ajoutées pour repositionner l'action-bar, et donc créait le problème de masquage du footer et d'une partie du contenu.
Le fait de virer cette règle et d'ajouter un `flex-grow` à la place laisse le navigateur calculer l'espace nécessaire en fonction de la hauteur.
https://github.com/user-attachments/assets/d4d85860-347f-485b-b8d1-26ad3433759e
=> (PC-30855)[PRO] fix: Fix main layout structure

pro/src/pages/Offers/Offers/OfferItem/IndividualOfferItem.tsx, pro/src/pages/Offers/Offers/OffersTableHead/OffersTableHead.tsx, pro/src/pages/Offers/__specs__/Offers.spec.tsx, pro/src/repository/__specs__/venuesService.spec.ts, pro/src/repository/venuesService.ts, pro/src/utils/commonOffersApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30376
Afficher l'adresse à la place de la venue dans la liste des offres individuelles.
=> (PC-30376)[PRO] feat: Display the address instead of the venue.

pro/cypress/cypress.config.ts, pro/cypress/e2e/step-definitions/adage.cy.ts, pro/cypress/e2e/step-definitions/createThingIndividualOffer.cy.ts, pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts, pro/cypress/e2e/step-definitions/venue.cy.ts, pro/cypress/support/commands.ts
Suppression des timeouts par défaut de 30 secondes pour utiliser les valeurs par défaut de Cypress (voir [ici](https://docs.cypress.io/guides/references/configuration#Timeouts))
+ quelques timeouts définis pour les zones de lenteur
=> (BSR)[PRO] test: no more big default timeouts

pro/src/components/Address/Address.tsx, pro/src/utils/searchPatternInOptions.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30917
Meilleur filtre pour l'autocomplétion des adresses
=> (PC-30917)[PRO] fix: Address search should ignore accents for options.

api/src/pcapi/core/providers/models.py
Remove length limit set to 64 (all our keys are 86 characters long)
=> (BSR)[API] fix: fix incoherent check on `hmacKey`

pro/cypress/e2e/step-definitions/adage.cy.ts, pro/cypress/e2e/step-definitions/createThingIndividualOffer.cy.ts
Failed with a 15" timeout, previously was 30" so go back to 30"
=> (BSR)[PRO] test: timeout 15"->30" for createThingIndividualOffer

pro/.stylelintrc.json, pro/src/components/FormLayout/FormLayout.module.scss, pro/src/components/Header/Header.module.scss, pro/src/components/Header/HeaderDropdown/HeaderDropdown.module.scss, pro/src/components/TutorialDialog/TutorialDialog.module.scss, pro/src/pages/Accessibility/AccessibilityLayout.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Autocomplete/Autocomplete.module.scss, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.module.scss, pro/src/pages/LostPassword/LostPassword.module.scss, pro/src/pages/Signup/SignupConfirmation/SignupConfirmation.module.scss, pro/src/pages/Signup/SignupContainer/SignupContainer.module.scss, pro/src/screens/IndividualOffer/StocksEventCreation/DayCheckbox.module.scss, pro/src/styles/components/layout/_CookieModals.scss, pro/src/styles/mixins/_forms.scss, pro/src/ui-kit/Banners/Banner/Banner.module.scss, pro/src/ui-kit/Button/Button.module.scss, pro/src/ui-kit/form/AdageMultiselect/AdageMultiselect.module.scss, pro/src/ui-kit/form/PhoneNumberInput/CodeCountrySelect/CountryCodeSelect.module.scss, pro/src/ui-kit/form/Select/Select.module.scss, pro/src/ui-kit/form/SelectAutoComplete/SelectedValuesTags/SelectedValuesTags.module.scss, pro/src/ui-kit/form/TextArea/TextArea.module.scss, pro/src/ui-kit/form/shared/BaseInput/BaseInput.module.scss, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30930
**Objectif**
Corriger les warnings de deprecation scss qu'on voit au moment du build. scss a ajouté [ce warning](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) il y a quelques jours. On ne doit plus avoir de styles non scopés avant des styles scopés.
J'ai résolu les pbs, à noter que j'ai du dupliquer la mixin `input-theme` pour pouvoir surcharger les styles de base de `input-theme` dans les styles qui s'en servent.
J'ai pas trouvé de règles pour avertir de cette deprecation (peut-être qu'elle existe pas encore ?)
=> Pc 30930 scss deprecation warnings

api/src/pcapi/core/offerers/repository.py, api/src/pcapi/routes/pro/offerers.py, api/src/pcapi/routes/serialization/offerers_serialize.py, api/tests/core/offerers/test_repository.py, api/tests/routes/pro/get_offerer_addresses_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/GetOffererAddressesQueryModel.ts, pro/src/apiClient/v1/services/DefaultService.ts, pro/src/components/UserIdentityForm/UserIdentityForm.tsx, pro/src/components/UserPasswordForm/UserPasswordForm.tsx
Add filter to OffererAddress API to get those that have at least one offer.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30833
=> (PC-30833)[PRO] feat: add filter on OffererAddress with offers

api/src/pcapi/routes/native/v1/account.py, api/src/pcapi/routes/native/v1/offers.py, api/src/pcapi/serialization/decorator.py, api/src/pcapi/serialization/spec_tree.py, api/tests/conftest.py, api/tests/routes/native/openapi_test.py, api/tests/serialization/extended_spec_tree_test.py
Move it from `@spectree_serialize` to `ExtendedSpecTree`
Ticket Jira : https://passculture.atlassian.net/browse/PC-30905
=> (PC-30905)[API] feat: move endpoint security definition

api/src/pcapi/routes/public/blueprints.py, api/tests/routes/public/blueprint_openapi_test.py
Now that the URL of the new documentation has been communicated to providers they don't need to use the swaggers
Ticket Jira  : https://passculture.atlassian.net/browse/PC-29862
=> (PC-29862)[API] feat: remove public API redoc/swagger redirects

pro/src/components/Breadcrumb/Breadcrumb.module.scss, pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.module.scss, pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.module.scss, pro/src/components/Stepper/StepContent.tsx, pro/src/components/Stepper/Stepper.module.scss, pro/src/components/Stepper/Stepper.tsx, pro/src/screens/IndividualOffer/StocksEventCreation/HelpSection/HelpSection.module.scss, pro/src/styles/global/_layout.scss, pro/src/styles/variables/_themes.scss, pro/src/ui-kit/Button/Button.module.scss, pro/src/ui-kit/RadioButtonWithImage/RadioButtonWithImage.module.scss, pro/src/ui-kit/Timeline/Timeline.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30958
**Objectif**
Correction de 4 TODO dans des fichiers de styles : 
- Ajout d'un style par défaut du `ol` dans le fichier de reset `layout.scss`
- Remplacement de la couleur `disabled` du button secondary par du gris, comme dans la maquette de la lib
- Suppression du style `fill` sur les icons des readio buttons avec image (le style n'ayant plus d'utilité)
- Rework du stepper pour que le premier et dernier éléments ne dépassent pas du container de la liste (et éviter d'avoir à ajouter des marges autour du stepper qui dépendent de la longueur du texte qui dépasse)
Pour le stepper, voici un avant/après
**Avant**
**Après**
=> Pc 30958 fix todos

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_api.py
A database object should be manually flushed if the business logic depends on a field that is populated by the server, like the creation date. Furthermore, relying on autoflush is a bad practice because some routes disable it in order to have more control on the SQLAlchemy session.
Fixes sentry issues : 
- https://sentry.passculture.team/organizations/sentry/issues/1617244/?project=5&referrer=slack
- https://sentry.passculture.team/organizations/sentry/issues/1617236/?project=5&referrer=slack
=> (BSR)[API] fix: flush the deposit manually after object creation

pro/src/pages/Reimbursements/ReimbursementsInvoices/InvoiceTable/InvoiceActions.tsx
Problème: En cliquant sur deux boutons EN GRIS, mais pas directement sur leurs textes, le dropdown se ferme et le document PDF (/CSV) n'est pas téléchargé.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30660
=> (PC-30660)[PRO] style: Correction composant de téléchargement de PDF, GF 

api/src/pcapi/routes/serialization/address_serialize.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/routes/pro/get_offers_test.py, pro/src/apiClient/v1/models/AddressResponseIsEditableModel.ts
renvoyer le label de la venue uniquement que quand l'oa est lié à une venue
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30376
=> (PC-30376)[API] feat: sending oa label when not linked to venue

pro/src/components/Tutorial/Tutorial.module.scss, pro/src/components/Tutorial/Tutorial.tsx, pro/src/components/TutorialDialog/__specs__/TutorialDialog.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29137
**Objectif**
Corriger un pb d'accessibilité du tutorial - les boutons du stepper n'ont pas de contenu.
=> (PC-29137)[PRO] fix: Fix tutorial accessibility - empty buttons.

api/src/pcapi/core/providers/factories.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/scripts/install.py, api/src/pcapi/scripts/provider/migrate_venue_providers_to_permission_system.py, api/src/pcapi/scripts/utils.py, api/tests/core/providers/test_repository.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-30963
Résumé : Ajout d'une commande pour donner toutes les permissions aux `VenueProvider` existants et faciliter la mise en place du nouveau système de permission.
=> (PC-30963)[API] Add CLI command to easily migrate existing `VenueProvider` to new permission system

.github/workflows/dev_on_push_workflow_main.yml
Ticket Jira (ou description si BSR) : les tests E2E ne doivent pas bloquer les déploiements
=> (BSR)[API] feat: remove test-pro-e2e from blocking deployments

api/src/pcapi/core/providers/models.py, api/src/pcapi/routes/pro/venue_providers.py, api/tests/routes/pro/delete_venue_provider_test.py
Without it, DELETE on `/venueProviders/{venue.id}` was returning a 500
=> (PC-31032)[API] fix: add `cascade` param in `externalUrls` and `permissions`

pro/src/pages/LostPassword/LostPassword.module.scss
Une couleur rouge s'était introduite sur la page de mot de passe oublié, on l'enlève 
Avant : 
Après :
=> (BSR)[PRO] fix: color lostpassword page

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240725T093357_943f189a4c71_drop_wip_mandatory_booking_contact.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/models/feature.py, api/tests/core/offers/test_validation.py, pro/src/components/IndividualOfferForm/Categories/Categories.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/UsefulInformations.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/__specs__/UsefulInformations.spec.tsx, pro/src/components/IndividualOfferForm/utils/buildSubCategoryFields.ts, pro/src/screens/IndividualOffer/InformationsScreen/InformationsScreen.tsx, pro/src/screens/IndividualOffer/SummaryScreen/OfferSection/OfferSection.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30892
Si on garde pas isBookingContactEnabled, et si on passe pas par un 'true' alors il faut modifier encore plusieurs fichiers, testes ne passent pas.
Elle provient de buildSubcategoryFields.ts :
```
export const buildSubcategoryFields = (
isBookingContactEnabled: boolean,
subcategory?: SubcategoryResponseModel
): {
```
Categories.txs:
```
if (isBookingContactEnabled) {
subcategoryFields.push('bookingContact')
}
```
=> (PC-30892)[PRO] style: Delete FF WIP_MANDATORY_BOOKING_CONTACT 2

api/documentation/src/pages/change-logs.md, api/src/pcapi/routes/public/documentation_constants/fields.py, api/src/pcapi/routes/public/individual_offers/v1/serialization.py, api/tests/routes/public/expected_openapi.json, api/tests/routes/public/individual_offers/v1/post_event_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29856
La création d'un événement via l'API publique n'avait pas le même comportement par défaut que son homologue côté portail pro au niveau du champ `enableDoubleBookings` :  faux pour l'API publique et vrai pour le portail pro. Maintenant la valeur par défaut est vraie partout.
PS : si quelqu'un sait comment éviter le `type: ignore` au niveau de la fonction `OFFER_ENABLE_DOUBLE_BOOKINGS`, je suis preneur.
=> (PC-29856)[API] feat: public api: double booking enabled by default

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240711T131114_e9caf841c7d6_add_rejectreason_to_offerer.py, api/src/pcapi/core/mails/transactional/pro/new_offerer_validation.py, api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offerers/models.py, api/src/pcapi/core/offerers/tasks.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/offerers/forms.py, api/src/pcapi/routes/backoffice/offerers/validation_blueprint.py, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/tests/core/mails/transactional/pro/new_offerer_validation_test.py, api/tests/core/offerers/test_api.py, api/tests/core/offerers/test_tasks.py, api/tests/routes/backoffice/offerers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30648
screen du formulaire : 
screen de l'historique
- CI - verte 
*test_batch_set_offerer_reject* pour l'action history
*SendNewOffererRejectionEmailTest* pour le mail 
Lorsqu'on rejete une structure, un commentaire apparait avec une demande de commentaire de la part de l'utilisateur ainsi qu'un choix de raison possible.
Lorsque l'on valide ce commentaire avec pour choix Eligibilité (par exemple):
- un log ( action history) affiche la raison, 
- un mail de rejet est envoyé contenant la raison du rejet, le mail est personnalisé en fonction de du choix Eligibilité 
- sur la page de l'offerer on peux voir la raison pour laquelle il a été …
=> (PC-30648)[BO] feat: homologation - reason reject offerer

.github/workflows/dev_on_workflow_deploy.yml
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28945
Effectivement j'avais fait une erreur dans ma première PR, merci et désolé @kopax et @francois-pass-culture
J'ai refait quelques test et là ça devrait aller. Ça me fait penser que même si j'ai testé en local j'ai pas vraiment de moyen de tester avant que ça soit mergé.
C'est peut-être contenu dans les sujets de déploiement continus mais ça serait bien de pouvoir avoir un environnement qu'on démarre (par exemple sur métier-ops) pour faire ce genre de tests.
```
on ⛵ teleport.ops.passculture.team in (test-lgd) ~ via  v18.12.1 via 🐍 v3.12.2 via 💠 default on ☁️   gcpadmin.louis.gerard@passculture.app(passculture-infra-prod)
❯ failure=$(kubectl get -n test-lgd jobs/exemple-job …
```
=> (PC-28945) ci: fix return code in case of migration failure

api/src/pcapi/core/offerers/api.py, api/src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerer_tags.py, api/src/pcapi/settings.py, api/tests/core/offerers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31132
Suppression d'une feature qui n'allait jamais marcher et qui impliquait l'utilisation d'un secret qui aurait été pénible, et duquel on ne nous a jamais donné la valeur.
=> (PC-31132)[BO] refactor: remove unused EPN autotagging feature

api/src/pcapi/core/finance/api.py, api/src/pcapi/core/fraud/models.py, api/tests/core/finance/test_api.py
The legacy Educonnect fraud checks do not have any associated source data, so we return None as the known birth date instead of raising an exception.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31125
=> (PC-31125)[API] fix: support empty fraud check in age at deposit calculation

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240730T080948_7ed9516f7af7_remove_ff_collective_markdown.py, api/src/pcapi/models/feature.py, pro/src/components/Markdown/Markdown.tsx, pro/src/components/Markdown/__specs__/Markdown.spec.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31128
**Objectif**
Suppression du FF WIP_ENABLE_OFFER_MARKDOWN_DESCRIPTION responsable de l'affichage des instructions et du fonctionnement du markdown dans la description d'une offre collective.
=> (PC-31128)[PRO] feat: Remove FF WIP_ENABLE_OFFER_MARKDOWN_DESCRIPTION.

api/src/pcapi/utils/date.py, api/tests/utils/date_test.py
babel.dates.format_datetime(datetime, format="long", locale="fr") gives inconsistent results on the TZ displayed.
For "Europe/Paris" it gives:
'20 juillet 2019, 08:00:00 +0200'
but for "America/Martinique" it gives:
'20 juillet 2019, 08:00:00 HNA'
which will fails the [:-9] to discard the TZ.
Let's switch to more explicit datetime format without TZ.
=> (BSR)[PRO] fix: format_datetime for non europe timezones

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/core/educational/repository.py, api/tests/routes/pro/get_all_collective_offers_test.py
L'objectif est de mettre en avant les offres collectives sur le point d'expirer afin que le pro fasse le nécessaire que l'offre soit validé.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30572
=> (PC-30572)[PRO] feat: Implement default sort order for collective offers

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240716T150036_5f46232cb72f_add_cancellationauthor_for_booking.py, api/src/pcapi/alembic/versions/20240716T150204_35d67a2cddcd_add_cancellationauthor_for_collective_booking.py, api/src/pcapi/alembic/versions/20240716T150303_ebbed0db4e99_add_cancellationauthor_foreign_key_for_booking.py, api/src/pcapi/alembic/versions/20240716T150445_9118d1848c98_add_cancellationauthor_foreign_key_for_collective_booking.py, api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/bookings/models.py, api/src/pcapi/core/bookings/repository.py, api/src/pcapi/core/educational/api/booking.py, api/src/pcapi/core/educational/models.py, api/src/pcapi/routes/backoffice/bookings/collective_bookings_blueprint.py, api/src/pcapi/routes/backoffice/bookings/forms.py, api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/templates/accounts/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/bookings.html, api/src/pcapi/routes/backoffice/templates/finance/incidents/get/details/collective_bookings.html, api/tests/routes/backoffice/collective_bookings_test.py, api/tests/routes/backoffice/individual_bookings_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30509
par l'acteur culturelle
par le backoffice
par autre:
- CI - verte 
RESERVATION INDIVIDUELLE : _test_list_cancelled_booking_informations ligne 308 dans individual_booking_test_
Si un booking est annulé avec pour raison d'annulation "Annulée par l'acteur culturel" :
ALORS
- la phrase continue en donnant l'email de l'acteur culturel
- l'email contenue dans la phrase est un lien vers la page de l'acteur culturel
Si un booking est annulé avec pour raison d'annulation "Annulée sur le backoffice" :
ALORS
- la phrase continue en donnant le prénom et nom de l'utilisateur BO
- le nom et prénom de l'utilisateur BO contenu dans la phrase est …
=> (PC-30509)[BO] feat: Cancellation reason for booking and collective booking display user informations if done by BOuser or pro

pro/src/pages/Offers/OffersTable/Cells/Cells.module.scss, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOfferRow/CollectiveOfferRow.module.scss, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTableBody/CollectiveOffersTableBody.module.scss, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTableHead/CollectiveOffersTableHead.module.scss, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTableHead/CollectiveOffersTableHead.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30926
FF : ENABLE_COLLECTIVE_OFFERS_EXPIRATION
Adapter le responsive de la liste des offres collectives
Mobile :
Tablette : 
Laptop (scrollable pour voir les actions) :
=> (PC-30926)[PRO] feat: responsive for offer list collective

api/src/pcapi/core/history/models.py, api/src/pcapi/core/providers/api.py, api/src/pcapi/routes/backoffice/filters.py, api/src/pcapi/routes/backoffice/pivots/blueprint.py, api/src/pcapi/routes/backoffice/pivots/contexts/allocine.py, api/src/pcapi/routes/backoffice/pivots/contexts/base.py, api/src/pcapi/routes/backoffice/templates/components/history/actions.html, api/src/pcapi/routes/pro/venue_providers.py, api/tests/core/providers/test_api.py, api/tests/routes/backoffice/pivots_test.py, api/tests/routes/pro/post_venue_provider_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30741
Lorsque je syncrhonise via pro : 
ALORS un action history est crée avec ces informations 
ET L'aciont history est visible ainsi dans le lieu en question
Lorsque je créer un pivot : 
ALORS 
un action history est crée : 
on peut voir cet action history ici : 
- CI - verte 
Dans l'application pro, dans les parametres generaux, 
lorsque le formulaire de syncronisation d'un lieu a un pivot et utilisé avec : le logiciel, le siret du lieu, la raison sociale, et eventuellement le nom public ALORS
- la synchronisation est lancé en asynchrone _deja fait_
- un log historique est fait et qui apporte les informations  concernant le logiciel, le …
=> (PC-30741)[BO] feat: log user sync in pro venue pivot

api/src/pcapi/core/users/api.py, api/src/pcapi/routes/backoffice/accounts/blueprint.py, api/tests/core/users/test_api.py, api/tests/routes/backoffice/accounts_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29709
None
- CI - verte 
Si l'utilisateur ne possède pas d'extract et que le reste des conditions sont remplie ( il peut etre anonymiser)
que l'on tente d'anonymiser l'utilisateur
la route redirige vers account, un flash retourne un succès ( j'ajoute ce flash dans les tests il n'y était pas ), l'utilisateur est bien anonymiser, la ligne extract est effacé, le fichier d'extract est effacé et un log (actionhistory) est crée.
Si l'utilisateur possède un ou plusieurs extract pret et que le reste des conditions sont remplie
que l'on tente d'anonymiser l'utilisateur
la route redirige vers account, un flash retourne un succès ( j'ajoute ce …
=> Pc 29709 adapt anonymize public account with extract condition

api/documentation/docs/understanding-our-api/managing-bookings/connection-with-ticketing-system.md, api/documentation/docs/understanding-our-api/managing-bookings/countermarks-management.md, api/documentation/src/pages/change-logs.md
Update `change_logs.md` accordingly
Ticket Jira  : https://passculture.atlassian.net/browse/PC-31196
=> (PC-31196)[API] feat: add `offer_id_at_provider` and `stock_id_at_provider` in message payload documentation

api/src/pcapi/core/offerers/api.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/routes/pro/offers.py, api/src/pcapi/routes/serialization/offers_serialize.py, api/tests/core/offerers/test_api.py, api/tests/routes/pro/patch_offer_test.py, pro/src/apiClient/v1/index.ts, pro/src/apiClient/v1/models/PatchOfferBodyModel.ts, pro/src/apiClient/v1/models/PatchOfferOffererAddressBodyModel.ts
modifier l'adresse de l'offre par l'offererAddress
+ petite refacto pour rendre le code plus maintenable.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30842
=> (PC-30842)[API] feat: modfify the offererAddress during offer update

pro/cypress/support/e2e.ts
=> (BSR)[PRO] ci: Make testing library timeout the same as cypress.

.github/workflows/dev_on_dispatch_release_deploy.yml
Expliquer le mystère de l'environnement `deploy`
La PR introduisant cet usage était https://github.com/pass-culture/pass-culture-main/pull/4853
=> (BSR) docs: add a comment about the mysterious `deploy` environment

pro/src/pages/AdageIframe/app/components/OfferInfos/AdageOffer/AdageOfferHeader/__specs__/AdageOfferHeader.spec.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/AdageOfferListCard/__specs__/AdageOfferListCard.spec.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOfferRow/__specs__/CollectiveOfferRow.spec.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOfferRow/__specs__/IndividualOfferRow.spec.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30392
https://github.com/testing-library/dom-testing-library/issues/1235
=> (PC-30392)[PRO] build: Update @testing-library/cypress

api/src/pcapi/core/bookings/api.py, api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/external_bookings/validation.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/models.py, api/src/pcapi/core/offers/validation.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/core/providers/repository.py, api/src/pcapi/routes/public/individual_offers/v1/events.py, api/src/pcapi/routes/public/individual_offers/v1/utils.py, api/src/pcapi/routes/public/services/authorization.py, api/tests/core/external_bookings/test_api.py, api/tests/core/offers/test_validation.py, api/tests/core/providers/test_repository.py, api/tests/routes/public/individual_offers/v1/delete_date_test.py, api/tests/routes/public/individual_offers/v1/patch_event_test.py, api/tests/routes/public/individual_offers/v1/patch_provider_test.py, api/tests/routes/public/individual_offers/v1/patch_venue_provider_external_urls.py, api/tests/routes/public/individual_offers/v1/post_event_test.py, api/tests/routes/public/individual_offers/v1/utils.py, api/tests/routes/public/services/test_authorization.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31081
Cette PR permet :
- à un provider de créer un event avec ticket ...
- à un jeune de prendre des place pour cet event...
... quand les urls de ticketing sont définies au niveau de la venue et qu'il n'y a rien au niveau du provider.
=> (PC-31081)[API] fix: enable creation of event with tickets when ticketing urls are defined at venue level

api/src/pcapi/routes/public/individual_offers/v1/bookings.py, api/tests/routes/public/expected_openapi.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30496
=> (PC-30496)[API][doc] Add warnings to hazardous booking endpoints

api/documentation/docs/tutorials/create-a-collective-offer.md, api/src/pcapi/routes/public/documentation_constants/fields.py, api/tests/routes/public/expected_openapi.json
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30796
1. Supprimer la sous-catégorie de l'exemple de création d'une offre collective (le champ est obsolète et sera bientôt supprimé).
2. Marquer ce même champ comme obsolète dans la documentation de l'API REST.
=> (PC-30796)[API] feat: public api doc: clean: subcategoryId

api/src/pcapi/core/offers/api.py, api/tests/routes/pro/post_draft_offer_test.py, pro/src/screens/IndividualOffer/UsefulInformationScreen/__specs__/utils.spec.ts, pro/src/screens/IndividualOffer/UsefulInformationScreen/utils.ts
⚠️ Attention, côté back cette PR entraîne ce changement de comportement dans la création d'offre:
Lorsque je créé une offre brouillon (`POST` `draft_offer`), on lui donne les données d'accessibilité de la `Venue` associée. Si toutes les données sont nulles on recopie aussi les valeurs `None`. Les champs sur les critère d'accessibilité sont par contre rendus obligatoires sur la 2nd partie de la création d'offre (`PATCH` `draft_offer`)
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31199
=> (PC-31199)[PRO] fix: default a11y values in UsefulInformations

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240807T090456_03013c06a0ac_drop_venue_provider_permission_table.py, api/src/pcapi/core/providers/factories.py, api/src/pcapi/core/providers/models.py, api/src/pcapi/core/providers/repository.py, api/tests/routes/pro/post_venue_provider_test.py, api/tests/routes/public/individual_offers/v1/get_events_test.py, api/tests/routes/public/individual_offers/v1/utils.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31225
Deuxième étape de la suppression du système de permission pour l'API publique.
=> (PC-31225)[API] Drop `venu_provider_permission` table

api/src/pcapi/core/educational/models.py, api/tests/routes/pro/get_all_collective_offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30572
La première PR se basait uniquement sur la date limite de réservation pour trier les offres, ce qui faisait apparaître des offres déjà réservées (avec une date limite de résa proche dans le temps) en haut de la liste. Le comportement souhaité est de mettre en avant les offres qui ne sont pas encore réservées (donc publiées ou préréservées).
=> (PC-30572)[API] fix default collective offer order

pro/package.json, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx, pro/src/pages/Reimbursements/BankInformations/PricingPointDialog/PricingPointDialog.tsx, pro/src/pages/VenueSettings/VenueProvidersManager/AddVenueProviderButton.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx, pro/src/ui-kit/form/TextArea/TextArea.tsx, pro/yarn.lock
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31257
**Objectif**
Ajouter @types/react aux dev dependencies pour s'assurer qu'elle est tenue à jour car actuellement cette dépendance a une version de retard et il semble qu'elle n'est pas mise à jour par dependabot.
Quelques erreurs de types sont corrigées dans cette PR : 
- L'attribut "placeholder" n'existe pas sur les balises selects (et n'ont donc jamais eu d'effet), maintenant le type est plus stricte et nous empêche de les ajouter
- Il y a un conflit de types des attributs du `<textarea>` avec la librairie `react-autosize-textarea` qui n'est plus maintenue à jour
=> (PC-31257)[PRO] bump: Install an up to date version of @types/react.

pro/src/components/CollectiveOfferLayout/CollectiveOfferLayout.tsx, pro/src/components/CollectiveOfferNavigation/CollectiveOfferNavigation.tsx, pro/src/components/CollectiveOfferNavigation/__specs__/CollectiveOfferNavigation.spec.tsx, pro/src/components/CollectiveOfferSummary/CollectiveOfferSummary.tsx, pro/src/components/CollectiveOfferSummary/__specs__/CollectiveOfferSummary.spec.tsx, pro/src/components/SummaryLayout/SummaryLayout.module.scss, pro/src/components/SummaryLayout/SummarySection.tsx, pro/src/pages/CollectiveOfferEdition/CollectiveOfferEdition.tsx, pro/src/pages/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx, pro/src/pages/CollectiveOfferSummaryEdition/CollectiveOfferSummaryEdition.tsx, pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/OffersTable/Cells/__specs__/CollectiveActionsCells.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31157
**Objectif**
- Correction: les offres vitrine n'avaient plus de bouton d'action dans la liste des offres collectives
- Correction: les offres collectives archivées étaient modifiables depuis la page de récapitulatif
=> Pc 31157 fix template offers

api/src/pcapi/core/offers/repository.py, api/tests/core/bookings/test_api.py, api/tests/routes/native/v1/bookings_test.py
Une requête supplémentaire sur `offer` est parfois faite lorsqu'on crée une réservation, au bon vouloir de sqlalchemy, ce qui rend le comptage des requêtes instables dans `test_create_booking`. Cette correction a pour but de précharger l'offre en `joinedload`, ce qui réduit d'une requête et lève l'incertitude.
Note : l'instabilité disparaissait si on retirait `populate_existing`, ce qui semble confirmer une origine dans sqlalchemy.
=> (BSR)[API] fix: number of query when booking an offer (flaky test_create_booking)

pro/src/hooks/usePagination.ts, pro/src/pages/Offers/OffersTable/Cells/Cells.module.scss, pro/src/pages/Offers/OffersTable/Cells/ExpirationCell/ExpirationCell.module.scss, pro/src/pages/Offers/OffersTable/Cells/OfferEventDateCell/OfferEventDateCell.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTable.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersTableHead/CollectiveOffersTableHead.tsx, pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/__specs__/Offers.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30587
SOUS FF : ENABLE_COLLECTIVE_OFFERS_EXPIRATION
Ajouter la possibilité de trier la colonne des dates de l'évènement
=> (PC-30587)[PRO] feat: sort column event date

api/src/pcapi/core/providers/titelive_api.py, api/src/pcapi/core/providers/titelive_book_search.py, api/src/pcapi/core/providers/titelive_music_search.py, api/tests/providers/titelive_search_test.py
This was the behavior of the old sync, the new one ignored the product with titles too long.
We can find the old behavior here : https://github.com/pass-culture/pass-culture-main/blob/199941a1a00cf611267fe136350832b50fd61334/api/src/pcapi/local_providers/titelive_things/titelive_things.py#L160
I'm not sure how but it also caused this update error : https://sentry.passculture.team/organizations/sentry/issues/1617601/?referrer=slack
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31234
=> (PC-31234)[API] fix: truncate titles to 140 caracters

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/exceptions.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/core/offers/validation.py, api/tests/core/offers/test_api.py, api/tests/core/offers/test_validation.py, api/tests/routes/public/individual_offers/v1/patch_event_test.py, api/tests/routes/public/individual_offers/v1/post_event_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31228
=> (PC-31228) Fix 500 caused by duplicate (`idAtProvider`, `venueId`)

api/src/pcapi/core/bookings/api.py, api/tests/routes/native/v1/bookings_test.py
`test_cancel_booking` est instable sur le nombre de requêtes : https://github.com/pass-culture/pass-culture-main/actions/runs/10315189393/job/28555285561
Rendre ce test plus stable est l'occasion de réduire le nombre de requêtes à l'annulation d'une réservation.
=> (BSR)[API] fix: number of queries when canceling an offer (flaky test_cancel_booking)

pro/src/components/ActionsBarSticky/ActionsBarSticky.module.scss, pro/src/components/ActionsBarSticky/ActionsBarStickyRight.tsx, pro/src/components/ActionsBarSticky/__specs__/ActionsBarSticky.spec.tsx, pro/src/components/RouteLeavingGuardCollectiveOfferCreation/RouteLeavingGuardCollectiveOfferCreation.tsx, pro/src/components/RouteLeavingGuardCollectiveOfferCreation/utils.ts, pro/src/pages/CollectiveOfferConfirmation/CollectiveOfferConfirmation.tsx, pro/src/pages/CollectiveOfferCreation/CollectiveOfferCreation.tsx, pro/src/pages/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreation.tsx, pro/src/pages/CollectiveOfferStockCreation/CollectiveOfferStockCreation.tsx, pro/src/pages/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx, pro/src/pages/CollectiveOfferSummaryCreation/__specs__/CollectiveOfferSummaryCreation.spec.tsx, pro/src/pages/CollectiveOfferVisibility/CollectiveOfferCreationVisibility.tsx, pro/src/screens/CollectiveOfferPreviewCreation/CollectiveOfferPreviewCreation.tsx, pro/src/screens/CollectiveOfferPreviewCreation/__specs__/CollectiveOfferPreviewCreation.spec.tsx, pro/src/screens/CollectiveOfferSummaryCreation/CollectiveOfferSummaryCreation.tsx, pro/src/screens/CollectiveOfferVisibility/CollectiveOfferVisibility.tsx, pro/src/screens/CollectiveOfferVisibility/__specs__/CollectiveOfferVisibility.spec.tsx, pro/src/screens/OfferEducational/OfferEducational.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/__specs__/OfferEducationalForm.spec.tsx, pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx, pro/src/screens/OfferEducationalStock/__specs__/OfferEducationalStock.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31140
SOUS FF : WIP_ENABLE_COLLECTIVE_DRAFT_OFFERS
Ajouter le message de brouillon non sauvegardé ou sauvegardé lors de la création d'une offre collective
Toaster au moment de la sauvegarde et au retour sur la liste des offres
RouteLeavingGuard adapté pour la création en brouillon
=> (PC-31140)[PRO] feat: eac actionbar draft offer

pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
Augmentation de 2 timeouts qui pourraint expliquer cet échec: https://cloud.cypress.io/projects/rit5sb/runs/461/test-results/0cb853d5-4950-4233-892d-a4c01a5ffac4/replay
=> (BSR)[PRO] test: increase timeout for homepage url loading

api/src/pcapi/core/offers/repository.py, api/tests/core/educational/test_repository.py, api/tests/core/offers/test_repository.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31262
Correction de ces 3 soucis identifiés :
- la sélection du statut "Publiée sur ADAGE" remonte les offres publiées, masquées et expirées
- la sélection du statut "Expirée" ne remonte aucune offre
- la sélection du statut “Terminée” ne prend pas en compte les offres remboursées (affichées comme terminées côté front)
=> (PC-31262)[API] fix: fix collective status filters

api/src/pcapi/routes/public/collective/serialization/offers.py, api/tests/routes/public/collective/endpoints/patch_collective_offer_test.py
Set `pre` to `False` to be able to compare `endDatime`and `startDatime` as dates
Ticket Jira : https://passculture.atlassian.net/browse/PC-31248
Fix d'un bug remonté par UGC dû au fait que l'on essayait de comparer un string avec un datetime (`startDatime` n'était pas castée comme une date)
=> (PC-31262)[API] fix: update `endDatetime` validator `pre` param

pro/src/components/ScrollToFirstErrorAfterSubmit/ScrollToFirstErrorAfterSubmit.tsx, pro/src/screens/OfferEducationalStock/FormStock/FormStock.tsx, pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx, pro/src/screens/OfferEducationalStock/__specs__/OfferEducationalStock.spec.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31223
On ne veut plus pré-remplir le champs de la date limite de réservation sur la page de stock lors d'une création d'une offre collective
=> (PC-31223)[PRO] feat: do not autocomplete bookinglimitdatetime

api/src/pcapi/core/offerers/models.py, api/src/pcapi/routes/serialization/venues_serialize.py, api/tests/routes/pro/get_venue_test.py, pro/src/apiClient/v1/models/GetVenueResponseModel.ts, pro/src/utils/collectiveApiFactories.ts
Will be used to figure out wether or not a Venue can be saftely relocated - its address changes - or if we need to warn the user that the associated offer's address may need to be updated - they will be kept on the old address.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31232
=> (PC-31232)[PRO] feat: add hasOffers in Venue response

pro/src/ui-kit/form/shared/BaseInput/BaseInput.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31295
**Objectif**
Corriger le warning sur le scss qui invite à [ne pas déclarer une propriété CSS après avoir définit les propriétés "nested"](https://sass-lang.com/documentation/breaking-changes/mixed-decls/).
Pour ça, la mixin appliquée au button-right étant utilisée une seule fois pour un button dans PasswordInput, j'ai dupliqué les styles qui nous intéressent de la mixin de l'icon-left/right. Et on n'a plus besoin du `pointer-events: none` ce qui règle le pb.
=> (PC-31295)[PRO] style: Fix base input right button warning.

api/src/pcapi/core/external_bookings/api.py, api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/offers.py, api/tests/core/offers/test_repository.py, api/tests/routes/native/v1/offers_test.py
Nombreuses exceptions remontées par Sentry depuis la MEP ce matin : 
https://passculture.atlassian.net/browse/PC-31305
Cette PR est le _revert_ strict de la PR #13536
=> (PC-31305) DetachedInstanceError - revert PC-31181

pro/src/components/OfferAppPreview/OfferAppPreview.module.scss, pro/src/components/OfferAppPreview/VenueDetails/VenueDetails.module.scss, pro/src/pages/Home/StatisticsDashboard/MostViewedOffers.module.scss, pro/src/pages/Home/StatisticsDashboard/OfferStats.module.scss, pro/src/styles/index.scss, pro/src/styles/mixins/_fonts.scss, pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31273
**Objectif**
La typo "preview-text" n'existe pas dans le figma PRO, mais elle semble quand même avoir une utilité, et le DS prévoit l'introduction d'une typo du même type (avec quelques petites diff) appelée "body-xs" pour compenser ce manque.
*Avant*
*Après*
=> (PC-31273)[PRO] style: Replace preview-text with body-xs.

pro/src/components/OfferAppPreview/VenueDetails/VenueDetails.module.scss, pro/src/components/ReimbursementBankAccount/ReimbursementBankAccount.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/OfferCard/OfferCard.module.scss, pro/src/pages/AdageIframe/app/components/AdageDiscovery/VenueCard/VenueCard.module.scss, pro/src/pages/AdageIframe/app/components/AdageHeader/AdageHeaderBudget/AdageHeaderBudget.module.scss, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/Offers.module.scss, pro/src/pages/Offers/OffersTable/Cells/ExpirationCell/ExpirationCell.module.scss, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreSection.module.scss, pro/src/pages/VenueSettings/VenueProvidersManager/VenueProviderList/VenueProviderItem.module.scss, pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplication.module.scss, pro/src/screens/IndividualOffer/BookingsSummary/DownloadBookingsModal/DownloadBookingsModal.module.scss, pro/src/styles/mixins/_fonts.scss, pro/src/ui-kit/form/PhoneNumberInput/PhoneNumberInput.module.scss, pro/src/ui-kit/form/SelectAutoComplete/SelectedValuesTags/SelectedValuesTags.module.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31276
**Objectif**
La typo "highlight" qu'on a dans le code n'existe pas dans la lib figma des designers PRO. Par ailleurs on prévoit dans le DS de n'avoir qu'one typo de ce type (càd grasse et à 12px). On peut donc simplifier notre liste de typos dev en enlevant highlight et en l'alignant sur caption (seule diff la line-height)
1. le titre des sections Avant/après
2. la message d'erreur Avant/après
3. les sous-titres Avant/après
4. le message de statut Avant/après
5. le compte + les titres de colonne Avant/après
6. le texte des tags Avant/après
=> (PC-31276)[PRO] style: Remplace highlight typo with caption.

pro/src/components/IndividualOfferNavigation/LabelBooking/LabelBooking.module.scss, pro/src/components/OfferAppPreview/OptionsIcons/OptionsIcons.module.scss, pro/src/pages/Home/StatisticsDashboard/StatisticsDashboard.module.scss, pro/src/pages/VenueEdition/AccesLibreSection/AccesLibreCollapse.module.scss, pro/src/screens/IndividualOffer/StocksEventCreation/RecurrenceForm.module.scss, pro/src/styles/mixins/_fonts.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31277
**Objectif**
Proposition de suppression de la typo "mini-highlight" qui existe dans le figma design sous le nom de "hint" mais qui pourrait ne plus exister avec le DS, et qui n'a que 4 occurrences.
1. "Type" et titre du logo étiquette Avant/après
2. texte dernière mise à jour Avant/après
3. sous-titre Avant/après
4. Compteur de réservations Avant/après
=> (PC-31277)[PRO] style: Replace mini-highlight with caption

pro/src/app/App/hook/useLogNavigation.ts, pro/src/core/Offers/constants.ts, pro/src/core/Offers/hooks/useQuerySearchFilters.ts, pro/src/core/Offers/types.ts, pro/src/core/Offers/utils/__specs__/computeOffersUrl.spec.ts, pro/src/core/Offers/utils/computeOffersUrl.ts, pro/src/core/Offers/utils/serializer.ts, pro/src/pages/CollectiveOffers/CollectiveOffers.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.admin.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffers.spec.tsx, pro/src/pages/CollectiveOffers/__specs__/CollectiveOffersQueryParams.spec.tsx, pro/src/pages/Offers/OffersRoute.tsx, pro/src/pages/Offers/OffersTable/Cells/CollectiveActionsCells.tsx, pro/src/pages/Offers/OffersTable/Cells/DeleteDraftCell.tsx, pro/src/pages/Offers/OffersTable/Cells/__specs__/CollectiveActionsCells.spec.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOfferRow/__specs__/CollectiveOfferRow.spec.tsx, pro/src/pages/Offers/OffersTable/CollectiveOffersTable/CollectiveOffersActionsBar/CollectiveOffersActionsBar.tsx, pro/src/pages/Offers/OffersTable/IndividualOffersTable/IndividualOffersActionsBar/IndividualOffersActionsBar.tsx, pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplicationScreen.tsx, pro/src/screens/OfferType/OfferType.tsx, pro/src/screens/Offers/Offers.tsx, pro/src/screens/Offers/SearchFilters/CollectiveSearchFilters.tsx, pro/src/screens/Offers/SearchFilters/IndividualSearchFilters.tsx, pro/src/screens/Offers/SearchFilters/SearchFilters.module.scss, pro/src/screens/Offers/__specs__/Offers.spec.tsx, pro/src/utils/parseUrlParams.ts, pro/src/utils/translate.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29690
- séparation des filtres collectifs et individuels
- ajout du SelectAutocomplete sur les filtres collectifs pour remplacer le filtre à choix unique par un filtre à choix multiples
- modifications sur la serialisation des filtres sélectionnés en paramètres d'url et inversement pour prendre en compte les listes
- réutilisation de ces modifs pour les trackers
=> (PC-29690) multiselect status filter

pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/DetailsScreen/Subcategories/Subcategories.tsx, pro/src/screens/IndividualOffer/DetailsScreen/__specs__/DetailsScreen.spec.tsx, pro/src/ui-kit/form/TextArea/TextArea.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30897
3 commit trois fix 
- une fois l'offre crée on ne voyait plus les sous catégories
- le onChange du textArea ne fonctionnait pas
- les sous-catégorie n'étaient plus filtrées
=> (PC-30897)[PRO] fix: suggested subcategories

api/src/pcapi/core/offerers/api.py, api/tests/core/offerers/test_api.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31348
=> (PC-31348)[API] fix: user offerer attachment was NEW instead of VALIDATED in case of double API call

api/poetry.lock, api/pyproject.toml
fix types-redis version to 4.6.0.20240425
=> (BSR)[API] fix: types-redis to v 4.6.0.20240425

pro/src/components/ActionsBarSticky/ActionsBarStickyRight.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31238
**Objectif**
Restituer le changement de statut d'offre (Brouillon enregistré/Brouillon non enregistré) dans le formulaire des offres collectives.
=> (PC-31238)[PRO] feat: Restitute collective offer draft status.

api/poetry.lock, api/pyproject.toml
Revert le downgrade de types-redis
=> (BSR)[API] revert: types-redis to ^4.6.0.20240806

api/src/pcapi/utils/sentry.py
https://passculture.atlassian.net/browse/PC-31418
Eviter le crash du SDK sentry si aucun path n'est renseigné par exemple lors du traitement de tâches aynchrones
=> (PC-31418)[API] fix: prevent sentry sampling crash

api/src/pcapi/workers/decorators.py
Change failed job ttl to 1 week instead of 1 year to avoid flooding our redis with (sometimes big) useless data
> failure_ttl specifies how long (in seconds) failed jobs are kept (defaults to 1 year)
[link to rq doc](https://python-rq.org/docs/jobs/#failed-jobs)
A script will be used to clean old failed jobs
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31293
=> (PC-31293)[API] feat: save failed job for a week

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/repository.py, api/src/pcapi/routes/native/v1/offers.py, api/tests/core/offers/test_repository.py, api/tests/routes/native/v1/offers_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31369
Note: on n'utilise plus de cache sur une fonction de repository, qui était responsable de l'erreur [DetachedInstanceError](https://sentry.passculture.team/organizations/sentry/issues/1617659/events/13cbd17990ce412eaa7a229361da9b5e/?project=5)
- Le comportement d'`atomic` lors des tests U ne me permet pas d'écrire un test qui reproduit le bug (rouge avec l'ancien code et vert avec cette PR)
=> PC-31369 improve offer route

pro/src/ui-kit/form/TimePicker/BaseTimePicker.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31235
- Simplement remettre une granularité de 15min pour les temps suggérés sur les inputs de type "Durée".
=> (PC-31235)[PRO] fix: use 15-min interval for duration-like BaseTimePickers

api/src/pcapi/utils/sentry.py
Ne pas échantillonner les appels à la page d'accueil du BO,
=> (BSR)[API] feat: Don't sample BO home transactions with Sentry

pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31342
- Si un user sélectionne une sous-catégorie suggérée et que les suggestions changent, on souhaite conserver la sélection parmi la suite de radio buttons proposés même si la sélection est issue d'une liste de suggestions différente.
- Si alors, l'user sélectionne une autre sous-catégorie de cette nouvelle liste de suggestions, le radio button précédemment sélectionné ne disparaît pas de liste pour autant.
- tldr; on affiche toujours la liste des suggestions ce sous catégories telle quelle, la sélection courante (si existante, qu'importe si elle appartient à une liste précédente de suggestions), et l'options "Autre".
- Clean / réécriture DRY du composant.
- Rajouts artificiels de radio buttons en …
=> (PC-31342)[PRO] fix: cache previously selected subcat until suggestion change

api/src/pcapi/core/search/staging_indexation.py
Améliorer la mémoire allouée lors des queries
La PR divise par 10 la mémoire nécessaire pour la même opération, en n'augmentant que peu le temps d'exécution (quelques secondes)
=> (BSR)[API] perf: reduce memory allocation when sampling staging offers to index

.github/workflows/dev_on_dispatch_deploy_ops.yml, .github/workflows/dev_on_dispatch_release_deploy.yml, .github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_deploy.yml
=> (PC-31321)[API] ci: use reusable actions for migration deployment workflow

api/src/pcapi/settings.py
because it is a password.
Ticket Jira : https://passculture.atlassian.net/browse/PC-31461
=> (PC-31461)[API] fix: revert TEST_DEFAULT_PASSWORD to secrets

pro/src/components/IndividualOfferNavigation/IndividualOfferNavigation.tsx, pro/src/context/IndividualOfferContext/IndividualOfferContext.tsx, pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.spec.tsx, pro/src/screens/IndividualOffer/DetailsScreen/SuggestedSubcategories/SuggestedSubcategories.tsx, pro/src/screens/IndividualOffer/DetailsScreen/utils.ts, pro/src/utils/individualApiFactories.ts
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30914
- Sur la sélection des sous-catégories (suggéré ou sélectionné à postériori via "Autre"), le stepper change en fonction du type d'offre (good vs event). 
N.B: Bien vérifier que l'url en comporte pas de `?offer-type=`, puisque cela correspond à l'ancien parcours (voir a/b testing à mettre en place).
=> (PC-30914)[PRO] feat: make individual offer creation stepper dynamic regarding subcat (goods vs event)

pro/src/pages/AdageIframe/app/components/AdageDiscovery/AdageDiscoveryBanner/AdageDiscoveryBanner.module.scss, pro/src/pages/Home/WelcomeToTheNewBetaBanner/WelcomeToTheNewBetaBanner.module.scss, pro/src/styles/mixins/_fonts-legacy.scss
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31428
**Objectif**
Remplacer les fonts "extra-bold" sauvages par des typos de titres normales.
Vu avec Marion pour le dialog de bienvenue, et avec Agathe pour la bannière d'ADAGE.
avant/après
avant/après
=> Pc 31428 suppression font-legacy extra-bold

pro/cypress/e2e/features/collectiveBooking.feature, pro/cypress/e2e/features/cookieBanner.feature, pro/cypress/e2e/features/createEventIndividualOffer.feature, pro/cypress/e2e/features/createThingIndividualOffer.feature, pro/cypress/e2e/features/desk.feature, pro/cypress/e2e/features/financialManagement.feature, pro/cypress/e2e/features/navigation.feature, pro/cypress/e2e/features/searchCollectiveOffer.feature, pro/cypress/e2e/features/searchIndividualOffer.feature, pro/cypress/e2e/features/venue.feature, pro/cypress/e2e/step-definitions/commonSteps.cy.ts, pro/cypress/e2e/step-definitions/cookieBanner.cy.ts, pro/cypress/support/commands.ts, pro/cypress/support/index.d.ts
Ligne 38 du référentiel de test, 2 nouveaux cas de test:
- vérifie que la sélection de cookie (beamer) est conservée dans le même browser si on se log avec un second compte
- vérifie que la sélection de cookie (beamer) n'est pas conservée si on se log avec le même compte dans une autre fenêtre*
*: Cypress ne sait pas gérer plusieurs fenêtre ou tab de browser. Donc dans le même j'ai réinitialisé les cookies; local et session storage pour me reconnecter au même compte.
Voir https://docs.cypress.io/guides/references/trade-offs#Multiple-browsers-open-at-the-same-time
=> (BSR)[PRO] test: check cookie selection not linked to account

api/src/pcapi/routes/public/individual_offers/v1/providers.py, api/src/pcapi/validation/routes/users_authentifications.py, api/tests/routes/public/helpers.py, api/tests/routes/public/individual_offers/v1/get_provider_test.py, api/tests/routes/public/individual_offers/v1/patch_provider_test.py, api/tests/routes/public/individual_offers/v1/patch_venue_provider_external_urls.py, api/tests/validation/routes/users_authentifications_test.py
Cette PR vise à prévenir ce genre de bug:https://sentry.passculture.team/organizations/sentry/issues/1617472/?project=5&referrer=slack
Dans cette PR :
- Ajout du décorateur `@provider_api_key_required`
- Mise en place du décorateur sur les routes provider de l'API publique : 
- [GET Provider](https://developers.passculture.pro/rest-api#tag/Providers/operation/GetProvider)
- [PATCH Provider](https://developers.passculture.pro/rest-api#tag/Providers/operation/UpdateProvider)
- [PATCH External Urls](https://developers.passculture.pro/rest-api#tag/Providers/operation/UpdateVenueExternalUrls)
=> (BSR)[API] Add `@provider_api_key_required` decorator to prevent user using old API keys to access the new public API

pro/cypress/e2e/features/editEventIndividualOffer.feature, pro/cypress/e2e/step-definitions/editEventIndividualOffer.cy.ts
Ligne 108 référentiel des tests. Vérifie la modification d'url dans le détail d'une offre numérique
=> (BSR)[PRO] test: check url modification in a digital offer

pro/cypress/e2e/features/editEventIndividualOffer.feature
Corriger une étape qui a été renommée dans une [PR](https://github.com/pass-culture/pass-culture-main/pull/13779) et pas reportée dans une autre [PR](https://github.com/pass-culture/pass-culture-main/pull/13794) créée en même temps (my fault)
=> (BSR)[PRO] test: Step renamed in another PR

.github/workflows/dev_on_pull_request_workflow.yml, .github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_tests_api_documentation.yml, api/documentation/docusaurus.config.ts
Le but de cette PR est d'ajouter un check pour vérifier que les modifications apportées à la documentation API ne cassent pas sa génération.
**⚠️ Le deuxième commit est en erreur pour montrer que le test de la CI fonctionne comme convenu. Il sera retiré une fois que la PR est validée.**
=> (BSR)[API] feat: add api-documentation-build-checks in CI

api/poetry.lock, api/pyproject.toml
Drops deprecated pkg_resources, which enables us to upgrade setuptools without DeprecatedWarning:
https://github.com/googleapis/python-api-common-protos/commit/713e3887a3293aea314060e84bdcf8a12eda3d6c
upgrade googleapis-common-protos from 1.61.0 to 1.63.2
=> (BSR)[API] bump: upgrade googleapis-common-protos from 1.61.0 to 1.63.2

pro/cypress/e2e/features/editEventIndividualOffer.feature, pro/cypress/e2e/step-definitions/editEventIndividualOffer.cy.ts
Inutile d'ouvrir les offres individuelles car on est redirigé dessus. Passait parfois selon la vitesse d'exécution des tests...
=> (BSR)[PRO] test: Do not open again offer list bc already displayed

pro/src/components/IndividualOfferForm/Informations/Informations.tsx, pro/src/components/IndividualOfferForm/UsefulInformations/UsefulInformations.tsx, pro/src/components/NewNavReview/NewNavReviewDialog/NewNavReviewDialog.tsx, pro/src/pages/AdageIframe/app/components/OffersInstantSearch/OffersSearch/Offers/ContactButton/RequestFormDialog/DefaultFormContact.tsx, pro/src/pages/LostPassword/ChangePasswordRequestForm/ChangePasswordRequestForm.tsx, pro/src/pages/Offerers/Offerer/VenueV1/VenueEdition/CollectiveDataEdition/CollectiveDataForm/CollectiveDataForm.tsx, pro/src/pages/VenueCreation/SiretOrCommentFields/SiretOrCommentFields.tsx, pro/src/pages/VenueCreation/WithdrawalDetails/WithdrawalDetails.tsx, pro/src/pages/VenueEdition/VenueEditionForm.tsx, pro/src/screens/CollectiveOfferSelectionDuplication/CollectiveOfferSelectionDuplicationScreen.tsx, pro/src/screens/IndividualOffer/DetailsScreen/DetailsForm.tsx, pro/src/screens/IndividualOffer/UsefulInformationScreen/UsefulInformationForm.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormOfferType/FormOfferType.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormPracticalInformation/FormPracticalInformation.tsx, pro/src/screens/OfferEducational/OfferEducationalForm/FormPriceDetails/FormPriceDetails.tsx, pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx, pro/src/ui-kit/form/EmailSpellCheckInput/EmailSpellCheckInput.tsx, pro/src/ui-kit/form/TextArea/TextArea.tsx, pro/src/ui-kit/form/TextArea/__specs__/TextArea.spec.tsx, pro/src/ui-kit/form/TextInput/TextInput.tsx, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.module.scss, pro/src/ui-kit/form/shared/FieldLayout/FieldLayout.tsx, pro/src/ui-kit/form/shared/FieldLayout/FieldLayoutCharacterCount/FieldLayoutCharacterCount.module.scss, pro/src/ui-kit/form/shared/FieldLayout/FieldLayoutCharacterCount/FieldLayoutCharacterCount.spec.tsx, pro/src/ui-kit/form/shared/FieldLayout/FieldLayoutCharacterCount/FieldLayoutCharacterCount.tsx
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31438
**Objectif**
1er commit : Ne pas afficher l'astérisque dans le form mdp oublié (et autoriser à ne pas l'afficher quand le formulaire ne contient qu'un champ, et qu'il est obligatoire).
2e commit : Ajouter un faux compteur de caractères aux champs de texte pour que les technos d'assistance n'annoncent pas le texte tapé après chaque changement.
3e commit : Rendre le champ de recherche de la création d'offre collective réservable à partir d'une offre vitrine optionnel (sinon on a un astérisque qui est lu aux technos d'assistance sans explications sur la signification). Et au passage, ajout d'une annonce pour le compte d'offres trouvées dans la recherche.
=> (PC-31438)[PRO] Corrections a11y

api/poetry.lock
Corriger poetry.lock après re-re-re-re-rebase loupé.
=> (BSR)[API] fix: poetry.lock

api/src/pcapi/core/testing.py, api/tests/core/finance/test_api.py, api/tests/core/testing/tests.py
Refactor du décorateur "clean_temporary_files" pour le remplacer par une fixture
=> (BSR) chore: refactor 'clean_temporary_files fixture used in finance api tests

api/src/pcapi/routes/public/collective/serialization/offers.py, api/tests/routes/public/collective/endpoints/post_collective_offer_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31299
=> (PC-31299)[API] fix: prevent the creation of collective offer when `startDatetime` > `endDatetime`

api/alembic_version_conflict_detection.txt, api/src/pcapi/alembic/versions/20240827T091759_d8a0801f62e2_create_index_on_stock_idatproviders.py, api/src/pcapi/core/offers/models.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31274
La création de l'index sur `stock.idAtProviders` a pour but de pouvoir enlever la contrainte d'unicité sur ce champ sans pour autant perdre en performance sur la recherche sur cet index.
=> (PC-31274)[API] feat: create index on `stock.idAtProviders`

api/src/pcapi/routes/pro/offers.py, api/tests/routes/pro/get_product_by_ean_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31216
Mise à jour des messages d'erreurs avec les information fournies par les designer/euse/s. Modification du status code de la réponse lorsqu'on trouve un produit avec l'EAN fourni mais que celui-ci est non compatible avec les CGU : utilisation du code 422 : https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
=> (PC-31216)[API]feat: endpoint get product by EAN, update error code and message

api/src/pcapi/connectors/serialization/allocine_serializers.py, api/src/pcapi/core/providers/allocine.py, api/tests/providers/allocine_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31319
=> (PC-31319)[API] fix: make allocine movie release date None when invalid

api/src/pcapi/core/offers/api.py, api/src/pcapi/core/offers/repository.py, api/tests/core/offers/test_api.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31355
Le bug corrigé dans cette PR est le suivant :
Il est possible que des produits cinéma soient créés seulement avec un `visa` ou seulement avec un `allocineId`.
En voulant mettre à jour un produit qui n'a qu'un `allocineId` et pas de `visa`, avec des données contenant maintenant un `visa`, une erreur va survenir si un produit avec ce `visa` existait déjà.
La proposition est de supprimer ce dernier et donc d'effectuer le transfert des offres et des réactions associées. Quant aux médiations, elles sont aussi supprimées pour ne garder que celle(s) du produit que l'on met à jour.
=> (PC-31355)[API] fix: handle coexisting incomplete movie products

api/tests/core/offers/test_repository.py
Fix: flaky 'test_get_collective_offers_expired'
=> (BSR) fix: flaky 'test_get_collective_offers_expired'

api/TESTS.md, api/tests/conftest.py, api/tests/core/bookings/test_api.py, api/tests/core/bookings/test_api_race_condition.py, api/tests/core/bookings/test_commands.py, api/tests/core/external/test_commands.py, api/tests/core/finance/test_commands.py, api/tests/core/finance/test_siret_api.py, api/tests/core/offers/test_api.py, api/tests/core/reference/test_models.py, api/tests/core/search/test_commands_indexation.py, api/tests/core/users/test_models.py, api/tests/repository/test_transaction.py, api/tests/routes/pro/post_venue_provider_test.py, api/tests/routes/public/individual_offers/v1/post_product_test.py
Refactor du décorateur "clean_database" pour le remplacer par une fixture
=> (BSR) chore: transform 'clean_database' decorator into a fixture

api/src/pcapi/core/finance/api.py, api/tests/core/finance/test_commands.py
Ajout des lignes des notes de débit dans l'export invoices csv
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31459
=> (PC-31459)[BO] fix: include debit notes in exported invoices csv

api/src/pcapi/core/educational/models.py, api/src/pcapi/core/finance/api.py, api/src/pcapi/core/offerers/api.py
Découper le changement de status des `pricings` à 0€ lors de la création des invoices pour éviter le timeout.
sentry : https://sentry.passculture.team/organizations/sentry/issues/1617848/?project=5
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31414
=> (PC-31414)[BO] fix: chunk invoicing of free pricings over bank accounts to avoid timeouts

pro/cypress/e2e/features/createEventIndividualOffer.feature, pro/cypress/e2e/features/createThingIndividualOffer.feature, pro/cypress/e2e/features/editEventIndividualOffer.feature, pro/cypress/e2e/step-definitions/adage.cy.ts, pro/cypress/e2e/step-definitions/commonSteps.cy.ts, pro/cypress/e2e/step-definitions/createEventIndividualOffer.cy.ts, pro/cypress/e2e/step-definitions/createThingIndividualOffer.cy.ts, pro/cypress/e2e/step-definitions/editEventIndividualOffer.cy.ts, pro/cypress/support/commands.ts
Activation du FF au début du scénario (le cas createEventIndividualOffer était flaky car FF pas activé à la première exécution)
Suppression de l'activation d'un FF adage qui n'existe plus, donc devenu inutile.
Attente de la réponse du PATCH FF en 204.
=> (BSR)[PRO] test: activate FF at the beginning and not during test

api/src/pcapi/core/educational/api/offer.py, api/src/pcapi/core/geography/factories.py, api/src/pcapi/core/search/backends/algolia.py, api/tests/core/search/test_backend_algolia.py, api/tests/core/search/test_serialize_algolia.py
Depending on WIP_USE_OFFERER_ADDRESS_AS_DATA_SOURCE either it uses legacy address data in Venue if false or gets the Venue's offererAddress if true
Ticket Jira: https://passculture.atlassian.net/browse/PC-26149
=> (PC-26149)[PRO] feat: use offererAddress for Algolia index

api/src/pcapi/routes/pro/offers.py, api/tests/routes/pro/get_product_by_ean_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-31569
Mise à jour du code erreur pour faciliter la gestion des erreurs côté front. Uniformisation entre produit non trouvé et produit incompatible CGU : 422
=> (PC-31569)[API]feat: Mise à jour du code erreur lorsqu'un produit n'est pas trouvé par EAN

api/src/pcapi/connectors/discord.py, api/src/pcapi/routes/auth/discord.py, api/src/pcapi/routes/auth/exceptions.py, api/src/pcapi/routes/auth/forms/forms.py, api/src/pcapi/routes/auth/templates/discord_signin.html, api/tests/routes/auth/discord_test.py
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31571
Un seul commit, c'est fait exprès, c'est pour pouvoir rollback facilement
On veut tester en testing : en local on a une erreur de redirection flaky, je veux vérifier si un vrai env reproduit cette erreur
=> (PC-31571)[API] feat: discord auth full flow from our form

api/src/pcapi/core/offers/repository.py, api/tests/routes/native/v1/offers_test.py
This reverts commit 8ea47b13c888090c140bf3f75c2df6b5fdc6c98b.
Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31513
This fixes a [Sentry issue](https://sentry.passculture.team/organizations/sentry/issues/1617678/events/3af849c194234df1a8fee86ae68e5a89/?environment=production&project=5&query=is:unresolved+NoSuchColumnError&statsPeriod=14d&stream_index=0)
=> (PC-31513)[API] fix: avoid flaky error on offer query
